### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by headdab** [opencv/cvat#1]
Under README.md it says to read the documentation, but I don't see any.

**Comment by nmanovic** [comment]
Hi,

There are several resources. I will add all of them into README file ASAP.

- **Basic information + how to build and run**: https://github.com/opencv/cvat/blob/master/README.md
- **User's guide** (github cannot render images at the moment, it will be fixed): https://github.com/opencv/cvat/blob/master/cvat/apps/documentation/user_guide.md
- **XML format for annotations**: https://github.com/opencv/cvat/blob/master/cvat/apps/documentation/xml_format.md
- **Computer Vision Annotation Tool (CVAT): interpolation mode** screencast: https://www.youtube.com/watch?v=sc5X5hvxNfA
- **Computer Vision Annotation Tool (CVAT): attribute mode** screencast: https://www.youtube.com/watch?v=5yXaG0V7X0Q
- **Computer Vision Annotation Tool (CVAT): annotation mode** screencast: https://www.youtube.com/watch?v=uSqaQENdyJE

**Comment by bsekachev** [comment]
Good day, 
* _"I didn't realize that all the controls were off the screen"._ **Could you provide any screenshots please?**
* _"none of the figure work in the user's guide"_. **Yes, we are working on it.**
* _"i started up a gpu/tf enabled version, but I don't see anything related to tensorflow in the interface and there isn't any documentation about how to use this feature. Seems like a good idea though."_. **If you did all right, button "Run TF Annotation" should appears in the dashboard for each task. It will run auto annotation for [supported labels](https://github.com/opencv/cvat/blob/master/cvat/apps/tf_annotation/views.py#L179) (if task contain any of such labels). We will include an information about it to documentation.**
* _"I don't see anything on how to use the shared mode. When I select it, it makes me choose files, but points to //icv-cifs/icv_projects/cvat/data."_. **This path will be removed. Currently, if you want use share source, you need mount it to /home/django/share in the docker container.**

**Comment by headdab** [comment]
I attached to screenshots - partial is what I saw originally, fullscreen after I enlarged the window.  You might be making your layout decisions based on a landscape layout assumption.

I found the tf button later, but got a label error.  It makes more sense now.  Can you give me an example of the labels string I should use, say, if I want to detect person and sports_ball?  I tried:

   tag @select=class:person,sports_ball

but that's not right.  The schema is:

  label_name <prefix>input_type=attribute_name:attribute_value1,attribute_value2

When you mention labels, you're referring to label_name in the schema?  Can I include more than 2 of those in the label string when configuring the session?

Re: shared mode, I'll try your suggestion.

Thanks for the quick feedback.

![fullscreen](https://user-images.githubusercontent.com/1169194/42344219-769915ac-8050-11e8-8706-6d93fe84e2ad.png)
![partial](https://user-images.githubusercontent.com/1169194/42344220-76b3da22-8050-11e8-9d26-f67cb027e555.png)

**Comment by headdab** [comment]
So I figured out the tf thing.  I just used "person sports_ball" and that worked.

**Comment by bsekachev** [comment]
Thanks a lot,
Layout looks strange, we will be working on it. 
Yes, label is label_name.
If you want detect persons and sport balls, you need type "person sports_ball" only.
Also you may assign some attributes for labels. Attribute examples: age or gender (for person), type or model (for car) etc. I will give some examples of valid strings below:
```
# number, select, radio, checkbox, text - is input types
# You also need specify each attribute type (mutable [~] or immutable [@]). Mutable attributes may be changed frame by frame (in the case of tracked objects)
# For number input type, attribute values is min, max and step.
# For radio and select - is possible values
# For checkbox and text - is default attribute value (true, false) for checkbox and ("any text") for text
person @number=age:1,100,1 @select=gender:man,woman @radio=hair:long,short,curly,straight
car ~checkbox=parked:true
face @text=description:"default description" 
```
Of course, you may create any number of labels and attributes for task:
```
person @number=age:1,100,1 @select=gender:man,woman @radio=hair:long,short,curly,straight car ~checkbox=parked:true face @text=description:"default description" 
```
Also you may see help about it if you hover cursor to labels string.
Or you can see it in [HTML](https://github.com/opencv/cvat/blob/master/cvat/apps/dashboard/templates/dashboard/dashboard.html#L77) 
Good luck

**Comment by bsekachev** [comment]
In order to see the rendered documentation, you need press F1 key in the dashboard (task list).

**Comment by headdab** [comment]
I tried the shared thing, but may have found a bug.  I copied a small clip into the top level host share directory and can see it when I try to select files from the create task dialog, but if I select it it also selects the enclosing directory, which it also treats as a file, which I think is the reason for the error shown on the screenshot.  For this screenshot, I clicked on select files after I got the error, so you could see that screen.

The test of the error is:

  Could not create the task. ffmpy.FFRuntimeError: `ffmpeg -i /home/django/data/5/.upload/ -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 /tmp/cvat-0qn3bhs9.data/%d.jpg` exited with status 1 STDOUT: STDERR:

![share-select-files](https://user-images.githubusercontent.com/1169194/42349319-3d5fccac-8061-11e8-9f0d-02d1fb339e05.png)

**Comment by bsekachev** [comment]
Yes,  it known bug.  Actually it already was fixed,  but currently was not released. As temporary solution,  I can suggest you to put any other file (empty text file for example) together with video. In this case video only will be selected.

**Comment by nmanovic** [comment]
@headdab we added information about available documentation + screenshot, screencasts. Also fixed a couple of other issues. If you have another issues please open new issues. In any case we will try to address other issues which you found in next release. Don't hesitate to send us MRs. I will close the thread.

**Comment by headdab** [comment]
Great. Thanks!
