### ISSUE TITLE
My docker shows this, help to see what the problem is.

### ISSUE THREAD

**Issue by ytgcljj** [opencv/cvat#10]
![_20180717145917](https://user-images.githubusercontent.com/27713475/42801685-04404098-89d3-11e8-906e-8c47d23aff93.jpg)
My docker shows this, helps to see what the problem is, and why the box does not move along with the car.

**Comment by nmanovic** [comment]
Hi @ytgcljj ,

To be honest you have not provided enough information but probably (my guess) you are trying to annotate in "annotation" mode. Please choose "interpolation" mode (near "Create Track" button) and after that annotate 1st and 10th frames. You should see that bounding boxes for frames between them are interpolated automatically. Does it answer your question?

**Comment by ytgcljj** [comment]
OK, I see. I thought the border box would follow after selecting it

**Comment by nmanovic** [comment]
@ytgcljj ,

Let me close the issue. If you have any other questions don't hesitate to ask.
