### ISSUE TITLE
Preprocessing step in automatic annotation pipeline

### ISSUE THREAD

**Issue by weizhiyi777** [opencv/cvat#1004]
Hi, when I use auto annotation in CVAT, I'm wondering:
The input image is read by opencv, then the channels of it would be in order of BGR. However, the input of my model (converted by openvino) needs to be in order of RGB. How could I tackle this problem? What's more, I don't know how to do some preprocess before inference. Is there any way to do that? It could be convenient when I want to use certain models in auto annotation.

Thanks a lot!

**Comment by bsekachev** [comment]
@weizhiyi777 
Hi, 

Look at ``--reverse_input_channels`` flag in model optimizer

**Comment by weizhiyi777** [comment]
@bsekachev 
Thanks, I will try!
And if there is any way to add some preprocess operations?

**Comment by bsekachev** [comment]
@weizhiyi777 
There aren't way in CVAT to preprocess inputs before inference.
But I suppose it's a good point to be implemented.

**Comment by nmanovic** [comment]
Should be covered by #1767
