### ISSUE TITLE
TF annotations button missing

### ISSUE THREAD

**Issue by stobias123** [opencv/cvat#1014]
I'm running in a docker container, and have built with TF annotations component as described in the [README.md](https://github.com/opencv/cvat/tree/develop/components/tf_annotation). 

The tf annotations button is missing. :( 

Are there any db migrations required if I've added this after initial deployment maybe? 

I've confirmed that both `TF_` environment variables are set and the model does exist, but the button is missing in the gui.
```
TF_ANNOTATION=true
TF_ANNOTATION_MODEL_PATH=/home/django/rcnn/inference_graph
```

**Comment by bsekachev** [comment]
@stobias123 
```
TF_ANNOTATION="yes"
```

**Comment by stobias123** [comment]
ooooof that was it, thanks. wish it was boolean
