### ISSUE TITLE
How can one test the new React UI?

### ISSUE THREAD

**Issue by mistermult** [opencv/cvat#1015]
Could you please add some instructions to test the new React UI e.g. for development. This is useful to make sure new features also work in the React UI.

**Comment by bsekachev** [comment]
@mistermult 
Hi,
What exactly do you mean "test the new React UI"? 
What new features are you speaking about?

**Comment by mistermult** [comment]
@bsekachev Isn't the UI migrated to use React?
 I assume, the annotation page is currently generated from https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/templates/engine/annotation.html. The main menu already used the new design with React. How can one use the React UI for the annotation interface generated from https://github.com/opencv/cvat/blob/develop/cvat-ui/src/containers/annotation-page/annotation-page.tsx.

**Comment by bsekachev** [comment]
@mistermult 
There are two main page in CVAT: dashboard and annotation view.
React based dashboard is ready, annotation view isn't yet. 

If you want to look at React based annotation view, you can use url ```cvat_origin/tasks/{task_id}/jobs{job_id}```. But don't expect it work.

**Comment by mistermult** [comment]
@bsekachev Thank you for your help!
