### ISSUE TITLE
Cannot start TF automatic annotation (module 'tensorflow' has no attribute 'GraphDef')

### ISSUE THREAD

**Issue by itsharsh** [opencv/cvat#1017]
Got not error while building and running the following command:
`docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/analytics/docker-compose.analytics.yml -f components/cuda/docker-compose.cuda.yml -f components/openvino/docker-compose.openvino.yml -f components/tf_annotation/docker-compose.tf_annotation.yml up -d --build`

But while trying to run auto annotation using RCNN Object Detector Model, got the following error:

> Could not fetch inference status for the task 3 
> Error: Inference status for the task 3 is failed. AttributeError: module 'tensorflow' has no attribute 'GraphDef'

Branch: develop

UPDATE(03/01/2020):
[1] Installed TensorFlow version inside docker container is somehow 2.0.
But version 1.15 is mentioned in CVAT Requirements.

When I tried to change the version by typing:
`pip install tensorflow==1.15.0`
it says,

> ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied

[2] Also, recreated the container by removing all the volumes and images by:
`docker system prune`

but still getting the same error

**Comment by nmanovic** [comment]
@itsharsh , thanks for the report. We will check and try to fix the bug ASAP.

**Comment by anujonthemove** [comment]
I am using the latest version of CVAT but getting the same errors as stated above. I also changed the line `pip install tensorflow==1.15.0` so that both the CPU and GPU versions are same.

**Comment by veer5551** [comment]
Hello @nmanovic,

I am getting the same error while I run the Tf model,
`Error: Inference status for the task 4 is failed. AttributeError: module 'tensorflow' has no attribute 'GraphDef'`

Any update/suggestions on this?

@itsharsh and @anujonthemove ,
Were you able to get it running? 

Thanks a lot!

**Comment by nmanovic** [comment]
@veer5551 , it will be fixed in the PR: #1767 . Sorry about that.

**Comment by anujonthemove** [comment]
> Hello @nmanovic,
> 
> I am getting the same error while I run the Tf model,
> `Error: Inference status for the task 4 is failed. AttributeError: module 'tensorflow' has no attribute 'GraphDef'`
> 
> Any update/suggestions on this?
> 
> @itsharsh and @anujonthemove ,
> Were you able to get it running?
> 
> Thanks a lot!

No, I wasn't able to get it running. I am unable to run even OpenVINO based models also. I completely removed all the dockers, docker volumes but unable to use auto annotation with CVAT currently.

**Comment by veer5551** [comment]
Hey @nmanovic ,
Thanks for the update!
Waiting to see this feature up and running!

@anujonthemove ,
Thanks for the update! 

Thanks a lot!
