### ISSUE TITLE
ERROR: for cvat Cannot start service cvat: driver failed programming external connectivity on endpoint cvat (a419da0881ab3fbc4b555d154d87320e088c58993d9260cc901ff3b708ef06f4): Bind for 0.0.0.0:8081 failed: port is already allocated

### ISSUE THREAD

**Issue by abajaj229** [opencv/cvat#1020]
The output of docker-compose up -d
ERROR: for cvat  Cannot start service cvat: driver failed programming external connectivity on endpoint cvat (a419da0881ab3fbc4b555d154d87320e088c58993d9260cc901ff3b708ef06f4): Bind for 0.0.0.0:8081 failed: port is already allocated

**Comment by lastlaugher** [comment]
8081 port might be used by other process. You need to change the port. CVAT's default ports are 8080 (cvat django) and 7080 (cvat-ui nginx). Did you edit it?

**Comment by nmanovic** [comment]
@abajaj229 , it seems that you run CVAT server twice or another app uses the 8081 port already. You have to run `docker ps` and see if another docker app allocates the 8081 port. 

It is a problem on your side. We cannot fix it inside CVAT. I will close the issue. Don't hesitate to ask additional questions on our gitter channel.
