### ISSUE TITLE
Bad Request: Your browser sent a request that this server could not understand

### ISSUE THREAD

**Issue by CDahmsCellarEye** [opencv/cvat#1022]
Description: After CVAT install, going to http://localhost:8080/ in Chrome shows Bad Request Your browser sent a request that this server could not understand. Size of a request header field exceeds server limit.

Due to something completely unrelated I did a fresh install of Ubuntu 18.04 one week ago.  Everything else (hardware and software) I'm using works fine.  I reinstalled CVAT today following the instructions from
https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md
to the letter.

CVAT worked fine before my reinstall of Ubuntu, but now when I go to `http://localhost:8080/` I get:

```
Bad Request

Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
```

I followed the above linked instructions the same before and after the Ubuntu reinstall.  This never happened before the reinstall.  I'm using Chrome.

My current concern seems similar to:

https://github.com/opencv/cvat/issues/36

But for some reason that is not clear to me that issue was closed, even though two people reported the same concern and there does not seem to have been a resolution, so I figured I'd repost as a new issue.

Per Issue 36 linked above, I did:
```
cd ~/cvat
docker-compose down
```
changed `supervisord.conf` log level to `DEBUG` as Issue 36 instructs, then:
`docker-compose up -d --build`
After which I got the exact same error when going to `http://localhost:8080/`, the results of the `docker-compose up -d --build` command are attached.

If I do
```
cd ~/cvat
docker ps | grep cvat
```

I get:

```
cdahms@TPX1G2:~/cvat$ docker ps | grep cvat
ccf716619144        nginx                  "nginx -g 'daemon of…"   4 minutes ago       Up 4 minutes        0.0.0.0:9080->80/tcp               cvat_ui
5e69a70bb7e9        cvat                   "/usr/bin/supervisord"   4 minutes ago       Up 4 minutes        0.0.0.0:8080->8080/tcp, 8443/tcp   cvat
2987e7445e67        postgres:10.3-alpine   "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes        5432/tcp                           cvat_db
bb900e64257e        redis:4.0.5-alpine     "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes        6379/tcp                           cvat_redis
```

Suggestions ??

[docker-compose up -d --build.txt](https://github.com/opencv/cvat/files/4018104/docker-compose.up.-d.--build.txt)

**Comment by nmanovic** [comment]
@CDahmsCellarEye , could you please attach logs from `docker logs cvat` command?

**Comment by CDahmsCellarEye** [comment]
Thanks for the quick response.  1st thing this morning I ran:

```
cd ~/cvat/
docker logs cvat > 'docker logs cvat.txt'
```
the resulting `docker logs cvat.txt` is attached

[docker logs cvat.txt](https://github.com/opencv/cvat/files/4020213/docker.logs.cvat.txt)

**Comment by CDahmsCellarEye** [comment]
Very strange update.  If I use Firefox (still on same Ubuntu 18.04 install) it successfully gets to the login screen, and I can enter the Django username and pass I set during the CVAT install successfully.  But then the next screen says:

`Your browser is detected as Firefox. This tool does not support it. Please use the latest version of Google Chrome.`

**Comment by bsekachev** [comment]
@CDahmsCellarEye 

Looks suspiciously: 
```
[Fri Jan 03 17:42:53.881906 2020] [core:info] [pid 184:tid 140358356788992] [client 172.19.0.1:46642] AH00561: Request header exceeds LimitRequestFieldSize: Cookie
[Fri Jan 03 17:42:53.881908 2020] [core:debug] [pid 184:tid 140358356788992] protocol.c(1318): [client 172.19.0.1:46642] AH00567: request failed: error reading the headers
```

It says one of your headers ``Cookie`` is too big. 
Could you please send request details from the browser tab 'Network'?

**Comment by CDahmsCellarEye** [comment]
Doing the following resolved the concern:

Open `Chrome`, go to:

`dot dot dot button (at the top right)` -> `History` -> `History` -> `Clear browsing data`

set:
`Time range` => `All time`

(check) `Browsing History`

(check) `Cookies and other site data`

(check) `Cached images and files`

Choose `Clear Data`
