### ISSUE TITLE
Job cannot be saved

### ISSUE THREAD

**Issue by EvgenyM** [opencv/cvat#1025]
Saving a job causes the following error:
`Couldn't to save the job. Errors occured: Could not make create annotations. Code: 401. Message: {"detail":"Authentication credentials were not provided."}. Please report the problem to support team immediately.`

This also leads to loss of work results. Could you please advice?

**Comment by nmanovic** [comment]
@EvgenyM , you need to re-login in a new tab. Please let us know if you have any other problems. I will close the issue for now.

**Comment by cvadim4two** [comment]
Same issue, tried same solution. Works.

**Comment by apoorvajoshi92** [comment]
It worked but I have lost all my tasks... how to retain it

**Comment by jyothir07** [comment]
I have the same issue in 2.3.0 but the above mentioned method doesnot work in my case. It doesnt shows the error while exporting but doesnot save and throws the error only when u signout.
