### ISSUE TITLE
Images are not stacking up in serialized order

### ISSUE THREAD

**Issue by muck27** [opencv/cvat#1026]
Hello @oikwsat @kshramt @dustindorroh @martin-etchart  @zliang7 @nmanovic .

I have some images remotely on an ec2 server.
When i pass images to create a task, I provide image A,B,C,D on a new line respectively.
When cvat downloads the images, it downloads it in the correct order.
But when i view the task, the images are stacked in C,B,A,D.
Why is this happening and what can I do to stack them in the order of download.
Regards
Clyde

**Comment by muck27** [comment]
Ok so in the task.py file, images are sorted before stacking them up!! solved it.

**Comment by svenvanbuurennl** [comment]
Would you please share the updated task.py file that allows for image stacking in serialized order?

**Comment by ErikOrjehag** [comment]
@muck27 I have the same issue, could you share the solution?
