### ISSUE TITLE
API image returns 401 Unauthorized to all requests from UI

### ISSUE THREAD

**Issue by Kieran-Bacon** [opencv/cvat#1027]
On navigating to the login screen a network error occurs preventing logging in or creating a new user. The error appears to be between the ui image and the  API image, no actions that can be taken from this screen work as a result.

Steps taken:

- Start an new instance of ubuntu 18.04
- Run the following commands as outlined by the documentation

```bash
sudo apt-get update
sudo apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

sudo groupadd docker
sudo usermod -aG docker $USER

sudo apt-get install -y python3-pip
sudo python3 -m pip install docker-compose

sudo apt-get install -y git
git clone https://github.com/opencv/cvat
cd cvat
```
- Add to the docker-compose.yml in environment and build context
```yaml
ALLOWED_HOSTS: "*"
```
- Build and run the images - set up a user

```bash

sudo docker-compose build

sudo docker-compose up -d

sudo docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
```

Upon navigating to the logging screen:
![cvat issue main page](https://user-images.githubusercontent.com/33673650/71836107-32520b80-30ab-11ea-901c-da9d0bfee495.PNG)

Navigating to the error itself yields:
![cvat issue](https://user-images.githubusercontent.com/33673650/71836125-3e3dcd80-30ab-11ea-98bb-8904b919d64a.PNG)

**Comment by martin-etchart** [comment]
You don't need the sudo on de last 3 docker commands if you correctly added your user to the docker group. No sure it will fix anything, just saying.

Also if you are not running it locally you should create a `docker-compose.override.yml` file with this (replace <IP> with the IP of the host):

```
services:
  cvat:
    environment:
      ALLOWED_HOSTS: "*"
      UI_HOST: <IP>

  cvat_ui:
    build:
      args:
        REACT_APP_API_HOST: <IP>
```

**Comment by Kieran-Bacon** [comment]
Thank you very much! Appears that having the host as the instance public dns did the trick.
