### ISSUE TITLE
Error: Network Error after PC Restart

### ISSUE THREAD

**Issue by itsharsh** [opencv/cvat#1035]
CVAT was working fine. But after restarting my PC, I'm getting an error:
> Could not check authorization on the server
> Error: Network Error.

So I tried to run it again using:
```
docker-compose -y <yml file1> -y <yml file2>.... down
docker-compose -y <yml file1> -y <yml file2>.... up -d --build
```

and its working again.

But after restarting my PC, I'm getting the same error.

**Comment by nmanovic** [comment]
@itsharsh , probably it is really necessary to fix. The primary problem here is simple: inside `cvat` container we have temporary apache files. The first `down` command deletes these temporary files and apache can start again normally. It is a well-known problem with apache in a docker container: https://forums.docker.com/t/httpd-already-running/33397. It seems it is necessary to remove apache2.pid file explicitly every time.

**Comment by itsharsh** [comment]
Okay, thanks for giving the actual reason for the bug.
So, do I have to do that manually every time? By running this `down` and `up` command every time I start my PC. 
(Also, a startup script can do this for me).

Or is there a permanent bug fix possible?

**Comment by nmanovic** [comment]
@itsharsh , it is possible to fix. Just need to remove the file explicitly: https://github.com/docker-library/php/blob/bdfd0fc1d19102cd6f951614072a51eabf7191bf/5.6/apache/apache2-foreground

**Comment by itsharsh** [comment]
I cross-checked the existence of this apache2.pid file from the container bash (after restarting my pc again), but the folder is empty.

`docker exec -it cvat bash
cd /var/run/apache2/
ls`

This shows empty directory
![Screenshot from 2020-01-10 14-48-02](https://user-images.githubusercontent.com/14810684/72141159-5322a580-33b8-11ea-9f3e-9836f9e7c8ca.jpg)

**Comment by ppdot** [comment]
Same issues, same situation on /var/run/apache2/. Is empty. Any other idea?

**Comment by azhavoro** [comment]
pid file (httpd.pid) located here `/tmp/mod_wsgi-localhost:8080:1000/`. Directory name is generated by mod_wsgi during start up I guess.
 According mod_wsgi documentation it should be possible specify pid file location
```
--pid-file FILE-PATH  Specify an alternate file to be used to store the
                        process ID for the root process of the web server.
```

**Comment by kaustubhharapanahalli** [comment]
Hi @nmanovic  
Is this issue fixed in the new release? 
I am facing this error today. Over the past few days, it was working properly. I am running CVAT on Windows Enterprise. I am attaching the error that I am getting here.

![1](https://user-images.githubusercontent.com/22560434/76821972-9a546900-6835-11ea-9594-48b50ea0b843.png)

**Comment by azhavoro** [comment]
@kaustubhharapanahalli Hi, this issue is not fixed in the latest release, could you please attach output of `docker logs cvat` to be sure that it's the same issue?

**Comment by kaustubhharapanahalli** [comment]
@azhavoro How can fetch the logs? Is it saved in some location after it's built or should I copy from the docker app on Windows?
