### ISSUE TITLE
Error:docker-compose build 

### ISSUE THREAD

**Issue by linmengnan** [opencv/cvat#1036]
when i run docker-compose build ,  I get a error:
Successfully built bcadce97d1cb
Successfully tagged cvat:latest
Building cvat_ui
Step 1/24 : FROM ubuntu:18.04 AS cvat-ui
 ---> 549b9b86cb8d
Step 2/24 : ARG http_proxy
 ---> Using cache
 ---> 161bede381a5
Step 3/24 : ARG https_proxy
 ---> Using cache
 ---> cb9c7fe68142
Step 4/24 : ARG no_proxy
 ---> Using cache
 ---> 578071a71a5e
Step 5/24 : ARG socks_proxy
 ---> Using cache
 ---> 4d80ffa647c6
Step 6/24 : ARG REACT_APP_API_PORT
 ---> Using cache
 ---> 0bde26a804e8
Step 7/24 : ARG REACT_APP_API_PROTOCOL
 ---> Using cache
 ---> dabf1ff3c668
Step 8/24 : ARG REACT_APP_API_HOST
 ---> Using cache
 ---> a66ef4eec405
Step 9/24 : ENV TERM=xterm     http_proxy=${http_proxy}       https_proxy=${https_proxy}     no_proxy=${no_proxy}     socks_proxy=${socks_proxy}
 ---> Using cache
 ---> 17d23e8ce017
Step 10/24 : ENV LANG='C.UTF-8'      LC_ALL='C.UTF-8'
 ---> Using cache
 ---> a3e16a0dd837
Step 11/24 : RUN apt update && apt install -yq nodejs npm curl &&     npm install -g n && n 10.16.3
 ---> Using cache
 ---> a2df49f00a27
Step 12/24 : RUN mkdir /tmp/cvat-ui /tmp/cvat-core
 ---> Using cache
 ---> 4ce6d0152a17
Step 13/24 : COPY cvat-core/package*.json /tmp/cvat-core/
 ---> Using cache
 ---> 5f531f9cbeab
Step 14/24 : COPY cvat-ui/package*.json /tmp/cvat-ui/
 ---> Using cache
 ---> 3dbc43954ba2
Step 15/24 : WORKDIR /tmp/cvat-core/
 ---> Using cache
 ---> 3ca7f9290a81
Step 16/24 : RUN npm install
 ---> Running in 0e4dc4dd7de0
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Unexpected end of JSON input while parsing near '..."^0.1.0"},"devDepende'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-10T04_53_08_366Z-debug.log
How can I resolve this? thank you

**Comment by bsekachev** [comment]
@linmengnan 
Hi, have you tried to built again?
Does the error occur each build?

**Comment by linmengnan** [comment]
Yes, it happens  when I rebuild. 
@bsekachev

**Comment by bsekachev** [comment]
@linmengnan 
Have you locally installed nodejs?

**Comment by nmanovic** [comment]
@linmengnan , please check your source code. NPM complains what package.json is invalid: `npm ERR! Unexpected end of JSON input while parsing near '..."^0.1.0"},"devDepende'`

Run `git status` or clone CVAT again.

**Comment by linmengnan** [comment]
@nmanovic the same error happens when I clone cvat again
run git status ：git status
On branch develop
Your branch is up to date with 'origin/develop'.
nothing to commit, working tree clean

**Comment by linmengnan** [comment]
@bsekachev I haven't installed it

**Comment by bsekachev** [comment]
@linmengnan 
Please install it and try to install nodejs dependencies locally:
``cd cvat-core && npm install``

**Comment by linmengnan** [comment]
@bsekachev  it works，thank you！

**Comment by bsekachev** [comment]
@linmengnan 

So, have you resolved the issue?

**Comment by bsekachev** [comment]
@linmengnan 

I'll close the issue because there aren't any updates
You can reopen it if the issue still exists

**Comment by rohitner** [comment]
Alternatively, you may add `RUN npm cache clean --force` in `Dockerfile.ui` just above the task leading to the error, worked for me.
