### ISSUE TITLE
Error: Could not fetch inference status for the task Open the Browser Console to get details.

### ISSUE THREAD

**Issue by test4fest** [opencv/cvat#1038]
I am running auto_annotation.
I uploaded about 1000 images in one task, and then ran auto annotation. This message pops up.
All the images have the same labels from a dataset of multi-objects.
(The number of true labels are more than model's labels, 
but all images have the same labels)
But when I upload 10 images with the same model, the same auto annotation works like a charm.
(define one label of model for all the images)

**Comment by bsekachev** [comment]
@test4fest 
Please attach a file with logs from CVAT: ``docker logs cvat``
Logs should contain details.

**Comment by test4fest** [comment]
@bsekachev Thanks for your quick response.
[log.txt](https://github.com/opencv/cvat/files/4046660/log.txt)

**Comment by bsekachev** [comment]
@test4fest 
Hmm, 
It seems, the model returns some detections with coordinate less than 0.
Probably you can fix it in your interpretation script, by using ``max()`` function

**Comment by test4fest** [comment]
I am using yolo_v3 architecture, and in interp.py file enforce for extra check for bounding box:
# Enforcing extra checks for bounding box coordinates
            xmin = max(0,xmin)
            ymin = max(0,ymin)
            xmax = min(xmax,width)
            ymax = min(ymax,height)

**Comment by bsekachev** [comment]
@test4fest 

I am not sure, but ``{'points': {3: [ErrorDetail(string='Ensure this value is greater than or equal to 0.', code='min_value')]}}`` might mean that ``xbr`` (xmax) coordinate less than 0.

**Comment by test4fest** [comment]
It works, thanks

**Comment by Petros626** [comment]
@test4fest what did you change in these lines of code?
```python
        xmin = max(0,xmin)
        ymin = max(0,ymin)
        xmax = min(xmax,width)
        ymax = min(ymax,height)
```

**Comment by zahidesatmutlu** [comment]
Same error. I am using YOLOv8 custom model on CVAT. How can i fix it?

`
import io
import base64
import json

import cv2
import numpy as np
from ultralytics import YOLO

# Initialize your model
def init_context(context):
	context.logger.info('Init context...  0%')
	model = YOLO('best.pt')
	context.user_data.model_handler = model
	context.logger.info('Init context...100%')

# Inference endpoint
def handler(context, event):
	context.logger.info('Run custom yolov8 model')
	data = event.body
	image_buffer = io.BytesIO(base64.b64decode(data['image']))
	image = cv2.imdecode(np.frombuffer(image_buffer.getvalue(), np.uint8), cv2.IMREAD_COLOR)

	results = context.user_data.model_handler(image)
	result = results[0]

	boxes = result.boxes.data[:,:4]
	confs = result.boxes.conf
	clss = result.boxes.cls
	class_name = result.names

	detections = []
	threshold = 0.6
	for box, conf, cls in zip(boxes, confs, clss):
		label = class_name[int(cls)]
		if conf >= threshold:
			# must be in this format
			detections.append({
				'confidence': str(float(conf)),
				'label': label,
				'points': box.tolist(),
				'type': 'rectangle',
			})

	return context.Response(body=json.dumps(detections), headers={},
		content_type='application/json', status_code=200)
`

**Comment by zahidesatmutlu** [comment]
Same error. I use it on a custom YOLOv8 model CVAT. My ```main.py``` code is as follows. How can I fix it?

```bash


import io
import base64
import json

import cv2
import numpy as np
from ultralytics import YOLO

# Initialize your model
def init_context(context):
	context.logger.info('Init context...  0%')
	model = YOLO('best.pt')
	context.user_data.model_handler = model
	context.logger.info('Init context...100%')

# Inference endpoint
def handler(context, event):
	context.logger.info('Run custom yolov8 model')
	data = event.body
	image_buffer = io.BytesIO(base64.b64decode(data['image']))
	image = cv2.imdecode(np.frombuffer(image_buffer.getvalue(), np.uint8), cv2.IMREAD_COLOR)

	results = context.user_data.model_handler(image)
	result = results[0]

	boxes = result.boxes.data[:,:4]
	confs = result.boxes.conf
	clss = result.boxes.cls
	class_name = result.names

	detections = []
	threshold = 0.6
	for box, conf, cls in zip(boxes, confs, clss):
		label = class_name[int(cls)]
		if conf >= threshold:
			# must be in this format
			detections.append({
				'confidence': str(float(conf)),
				'label': label,
				'points': box.tolist(),
				'type': 'rectangle',
			})

	return context.Response(body=json.dumps(detections), headers={},
		content_type='application/json', status_code=200)


```

**Comment by Petros626** [comment]
update your code this lines do not provide the bounding box part

**Comment by zahidesatmutlu** [comment]
> @zahidesatmutlu update your code these lines do not provide the bounding box part. It must be another python file in the model folder

I delete the function from nuclio and re-deploy it. Now, it works.

**Comment by zahidesatmutlu** [comment]
> > > @zahidesatmutlu update your code these lines do not provide the bounding box part. It must be another python file in the model folder
> > 
> > I delete the function from nuclio and re-deploy it. Now, it works.
> 
> Okay then the code above does not provide any further details for the origin of the problem 😉

You are right. I am deleting it to avoid misinformation.
