### ISSUE TITLE
Upload annotation not working with polygons

### ISSUE THREAD

**Issue by vinorth05** [opencv/cvat#1041]
Hello everyone,

It seems that uploading annotation is not working after dumping annotation with polygons. It seems to be related to the latest character ";" from the "points" attribute.
In fact after deleting the point, the uploading works perfectly.

**Comment by bsekachev** [comment]
@vinorth05 

Hi, 
Cannot reproduce the issue. Polygons dump without the latest character ``;`` in my case.
What version of CVAT do you use? 

``http://localhost:8000/api/v1/server/about``

**Comment by vinorth05** [comment]
Thank you for your reply,

Here is the version :

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "name": "Computer Vision Annotation Tool",
    "description": "CVAT is completely re-designed and re-implemented version of Video Annotation Tool from Irvine, California tool. It is free, online, interactive video and image annotation tool for computer vision. It is being used by our team to annotate million of objects with different properties. Many UI and UX decisions are based on feedbacks from professional data annotation team.",
    "version": "0.6"
}

**Comment by vinorth05** [comment]
Ok now it seems to dump without the latest character, thanks!
