### ISSUE TITLE
no no models and  annotation mode in my web page

### ISSUE THREAD

**Issue by linmengnan** [opencv/cvat#1043]
After installation， only tasks mode and no no models and  annotation mode in my web page， How can i solve it， Thank you！
<img width="1856" alt="WeChate3d4c11497858ec110f3dd069dd2b7e1" src="https://user-images.githubusercontent.com/51906636/72237581-f7555800-3615-11ea-89e9-dc454e716fe4.png">

**Comment by bsekachev** [comment]
@linmengnan 

Hi, you haven't installed any auto annotation, tf annotation, or tf segmentation modules.
Please read the installation manual: https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#additional-components 

What is ``annotation mode``?

**Comment by linmengnan** [comment]
@bsekachev  ok, thank you

**Comment by duonghanu** [comment]
I already follow this guide: [https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#additional-components] but no models menu

How can i solve it?

Thanks,
Duong

**Comment by sicoyle** [comment]
> Can the links above please be fixed?

I would also link the correct links. Thanks in advance :)

**Comment by nmanovic** [comment]
https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
