### ISSUE TITLE
uploading annotations yolo format error

### ISSUE THREAD

**Issue by Diaislam** [opencv/cvat#1047]
I'm trying to upload annotation for a task in yolo format and i get this error : 
CAn not upload annotations for the job. code : 500 message : "vat.apps.engine.utils.InterepterError: KeyError at line 78: 18\n"

i'm pretty sure everything is fine in my annotations even obj.names is the same as the task

**Comment by azhavoro** [comment]
Hi @Diaislam, can you share your yolo annotation? Also what CVAT version do you use?

**Comment by Diaislam** [comment]
this is what a yolo .txt contains : 
18 0.34036458333333336 0.6016203703703704 0.09322916666666667 0.13287037037037036
18 0.7352864583333333 0.5831018518518518 0.04192708333333333 0.17731481481481481
5 0.68046875 0.6057870370370371 0.16510416666666666 0.36898148148148147
5 0.670703125 0.3578703703703704 0.20390625 0.5777777777777777
18 0.5911458333333334 0.1224537037037037 0.0890625 0.06898148148148148
5 0.8071614583333333 0.2881944444444444 0.10182291666666667 0.5763888888888888
1 0.18541666666666667 0.6337962962962963 0.13229166666666667 0.11018518518518519
5 0.81796875 0.39444444444444443 0.12916666666666668 0.7888888888888889
7 0.23411458333333332 0.6486111111111111 0.0796875 0.06759259259259259
18 0.9162760416666667 0.6914351851851852 0.05755208333333333 0.06435185185185185
1 0.028645833333333332 0.7666666666666667 0.050520833333333334 0.15833333333333333
6 0.8213541666666667 0.4361111111111111 0.13333333333333333 0.6925925925925925
6 0.814453125 0.5914351851851852 0.15807291666666667 0.46435185185185185
11 0.028776041666666665 0.819675925925926 0.05026041666666667 0.2875
5 0.7022135416666667 0.2875 0.29140625 0.4981481481481482
11 0.027604166666666666 0.7719907407407407 0.05260416666666667 0.16805555555555557
7 0.16380208333333332 0.5960648148148148 0.036458333333333336 0.038425925925925926
5 0.8151041666666666 0.5668981481481481 0.21927083333333333 0.5263888888888889
12 0.6092447916666667 0.3511574074074074 0.37213541666666666 0.5634259259259259
5 0.7401041666666667 0.30833333333333335 0.16145833333333334 0.6166666666666667

i'm used to work with this before it was working now i get this error and i have the latest version

**Comment by azhavoro** [comment]
How did you get the annotation that you are trying to upload? I mean downloaded from CVAT or smth else.
One of possible reason of this error is annotation_id from *.txt cannot be find in obj.names.

**Comment by Diaislam** [comment]
i'm actually training a model to generate auto annotations using tensorflow
this i've been working on until i got this error i'm pretty sure the ids are right

**Comment by azhavoro** [comment]
Could you please attach (or share with me via GDrive, dropbox, etc) zip file with annotation? I'll try to reproduce the error.

**Comment by Diaislam** [comment]
I found where the error : 
it was the ids of the obj.names
as tensorflow object detection starts counting from 1 taking 0 as a background
but yolo starts from zero
the only reason why it was working is that the last class wasn't found in previous videos
thank you for you help.
