### ISSUE TITLE
Suggestion: tools

### ISSUE THREAD

**Issue by test4fest** [opencv/cvat#1049]
I am using the CVAT tool, it's great.
It would be great if you can improve two things:
1- Auto annotation: map model label to different Openvino labels
It means that we might have different type of categories of the same objects but the model recognize it as one object.

2- After creating a task it's impossible to remove some labels from it. I need to create another task with a new defined labels.

Thanks

**Comment by test4fest** [comment]
I am using the CVAT tool, it's great.
It would be great if you can improve two things:
1- Auto annotation: map model label to different Openvino labels
It means that we might have different type of categories of the same objects but the model recognize it as one object.

2- After creating a task it's impossible to remove some labels from it. I need to create another task with a new defined labels.

Thanks

**Comment by nmanovic** [comment]
@test4fest ,

1. It is possible already now.
2. You can use admin panel if it is absolutely necessary. The operation isn't safe.

Does it answer your question?

**Comment by bsekachev** [comment]
@nmanovic 
> 1. It is possible already now.

Not exactly. There isn't support one model label to many task labels in the client. But it should be easy to implement if server works with it.

**Comment by test4fest** [comment]
Thanks a lot.
your respond help me. 
let me know if the first question is implemented.

**Comment by bsekachev** [comment]
@test4fest 

Implemented
