### ISSUE TITLE
How to customize action to batch assign assignees in task assignment page

### ISSUE THREAD

**Issue by russenwer** [opencv/cvat#1050]
Hello cvat team! In the task allocation interface of background management, add a drop-down action to batch allocate the assignee, try many times, and report an error of 500 when you jump to the middle page to select the assignee. Can you provide a brief code example guide,thanks

The following screenshot is the test code added locally
![image](https://user-images.githubusercontent.com/20299466/72305971-77300080-36b0-11ea-9da9-368579af218c.png)
![image](https://user-images.githubusercontent.com/20299466/72306253-7b105280-36b1-11ea-80e8-592959ac260a.png)

**Comment by nmanovic** [comment]
@russenwer ,

It is better to discuss such questions here: https://gitter.im/opencv-cvat/dev

Currently it isn't possible to assign multiple users to one task. The server doesn't support that.
