### ISSUE TITLE
No labels or no video when creating tasks using cli

### ISSUE THREAD

**Issue by arituerto** [opencv/cvat#1056]
I have 2 CVAT instances:
* local CVAT      - e0bcc4652bb38b66c838b016c632c71879887248
* remote CVAT  - 66140fdadd340ed23034432852bde09d6cefbeed

I'm playing around with the Command Line Interface for task creation and I have found some weird behaviour:
* When I create a task from local to local uploading labels.json and a video everything works ok.
* When I create a task from local to local uploading just a video the task is created without labels defined.
* When I create a task from local to remote uploading labels.json and video I receive an error:
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/cvat/logs?stderr=1&stdout=1&tail=all: dial unix /var/run/docker.sock: connect: permission denied`.
The task is created without video but with labels defined.
* When I create a task from local to remote uploading just a video the task is created without labels defined.

**Comment by bsekachev** [comment]
@arituerto 

Hi,
Where do you receive this error?

 ```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/cvat/logs?stderr=1&stdout=1&tail=all: dial unix /var/run/docker.sock: connect: permission denied.
```

**Comment by arituerto** [comment]
> @arituerto
> 
> Hi,
> Where do you receive this error?
> 
> ```
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/cvat/logs?stderr=1&stdout=1&tail=all: dial unix /var/run/docker.sock: connect: permission denied.
> ```

I check the logs of the remote CVAT `docker logs cvat`.

**Comment by bsekachev** [comment]
@arituerto 

Had you done [post installation](https://docs.docker.com/install/linux/linux-postinstall/) steps before you ran docker-containers?
Can you confirm that user on the remote host is still in docker group?
Have you tried just reboot remote host?

**Comment by bsekachev** [comment]
Related created issue is #1054

I will close this issue since there are no comments from the author for a long time.
Do not hesitate reopen it if you still need help
