### ISSUE TITLE
OSError: image file is truncated

### ISSUE THREAD

**Issue by kccheung** [opencv/cvat#106]
Cannot create task if one of the image file is a malformed image, with error info like

`cannot create task OSError: image file is truncated`

In my case, I would like the task to be created but without that malformed image file. Meanwhile, I achieved this by try except the problematic line `image = image.convert('RGB')` in `cvat/cvat/apps/engine/task.py`

**Comment by nmanovic** [comment]
Hi @kccheung ,

Thanks for you report. I don't think that suggested by you behaviors is expected by other users. Personally I don't think that it is a good idea to mask problems with data. If you have a better suggestion than just try/except such problematic line please let me know. I will reopen the issue.
