### ISSUE TITLE
Support using tags in annotation formats

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#1062]
So, we supported working with tags on the server.
We are going to support annotation with tags in client soon.

But, as far as I understand, the server isn't able to dump tags to annotation files
Probably we should update specification for CVAT XML and support dumping. Initially, at least in CVAT format.

- [x] Update CVAT XML format and its specification in docs
- [x] Implement dumping/uploading of tags in CVAT XML format
- [ ] Investigate which of other formats can contain tags and provide implementation for them

**Comment by nmanovic** [comment]
@zhiltsov-max , do you think you can add the feature in the nearest future?

**Comment by zhiltsov-max** [comment]
@nmanovic, everything, except the 3-rd point - yes, it shouldn't be a big problem. All the other formats seem to be PASCAL only, if this is true, then it should be quite simple too.

**Comment by nmanovic** [comment]
I will close the issue.
