### ISSUE TITLE
extreme clicking method

### ISSUE THREAD

**Issue by test4fest** [opencv/cvat#1063]
If it's applicable , I would like to ask you to support **[extreme clicking method](http://openaccess.thecvf.com/content_ICCV_2017/papers/Papadopoulos_Extreme_Clicking_for_ICCV_2017_paper.pdf)** for future versions.

Thanks

**Comment by nmanovic** [comment]
@test4fest , it should not very difficult to implement. It can be done in UI only. Just need a new virtual shape like "box by 4 points". Internally it can be mapped on a usual bounding box but the drawing method should be handled in another way.

Do you think it is something you can contribute?

**Comment by azhavoro** [comment]
Implemented #1111
