### ISSUE TITLE
Question Regarding Auto Segmentation

### ISSUE THREAD

**Issue by san999p** [opencv/cvat#1064]
Hi,

I see a component for Auto Segmentation but I could not find the corresponding UI (i.e Button). Can you please point me to the file where UI is implemented for Auto Segmentation ?

Thanks

**Comment by nmanovic** [comment]
@san999p ,

Please use gitter next time to ask a question. You can find information about the component here: https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#additional-components

**Comment by nmanovic** [comment]
I will close the issue. Don't hesitate to reopen the issue if you still have questions.
