### ISSUE TITLE
install the OpenVINO component error

### ISSUE THREAD

**Issue by linmengnan** [opencv/cvat#1073]
when I install the OpenVINO component，after put downloaded file into cvat/components/openvino and run docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build，
<img width="1148" alt="WeChat67661d5c98c9ab1033ea7c8f3430b785" src="https://user-images.githubusercontent.com/51906636/72701892-cfbd3d00-3b8b-11ea-974e-54dc35da68cf.png">
how can I solve it ， thank you！

**Comment by nmanovic** [comment]
@linmengnan , you have to put an archive of openvino toolkit. If you did please check that the archive is valid and can be unarchive.

I will close the issue. Please ask questions on our gitter channel. If my advice isn't help please reopen the issue.
