### ISSUE TITLE
[Question] Grouping polygons between frames

### ISSUE THREAD

**Issue by adizhol** [opencv/cvat#1079]
Hi,
I understand that there's a feature waiting to be released for tracking polygons between frames, similarly to tracking boxes.
I there a way in the mean time to annotate two polygons from two adjacent frames as the same object (i.e. group id)?

Thanks

**Comment by nmanovic** [comment]
@adizhol , you can merge them into one track. Does it answer your question?

**Comment by adizhol** [comment]
Can you point me to the relevant documentation?

**Comment by nmanovic** [comment]
https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#interpolation-mode-basics

**Comment by adizhol** [comment]
Thanks! From which version is it supported?

**Comment by adizhol** [comment]
> https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#interpolation-mode-basics

What if I already have a video with separate annotations in each frame? Can I group annotations between frames?

**Comment by nmanovic** [comment]
@adizhol, you can. I will close the issue. If you have any other questions please don't hesitate to contact us using gitter channel.

**Comment by Sentient07** [comment]
Hi, I have some detections which are in PASCAL VOC format. These detections correspond to every 10th frame in a video. I'd like to merge them using the interpolation mode. When I try uploading the annotation, the boxes are in "annotation mode" and hence are not being interpolated. Could you kindly help me out on how to change the type from annotation to interpolation?

Thank you!
