### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by muck27** [opencv/cvat#1080]
When I am creating a task, I am getting a connection timeout from the server. I did some benchmarking, if the task generation takes more than 66 seconds, I am having a timeout. How can i increase the timeout to say 2-3 minutes? Should I change a variable in the cvat-ui/react_nginx.conf

@nmanovic Please help

**Comment by bsekachev** [comment]
Hi, to adjust timeouts you need to work with the file ``cvat/mod_wsgi.conf``
There is some [documentation](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html).

**Comment by azhavoro** [comment]
@muck27 Hi, did you solve the issue?

**Comment by azhavoro** [comment]
I will close the issue. Don't hesitate to reopen the issue if you still have questions.
