### ISSUE TITLE
TF automatic annotation: How to cancel/restart ongoing automatic annotation?

### ISSUE THREAD

**Issue by itsharsh** [opencv/cvat#1082]
Branch: develop

My system got crashed due to some other reason.
But at that time, automatic annotation was running.
And after system reboot, it got stuck, and the "Automatic Annotation" button is disabled
![Screenshot (12)](https://user-images.githubusercontent.com/14810684/72802918-d7a3dc80-3c72-11ea-8fdb-fd51cbdfbe0b.png)

**Comment by bsekachev** [comment]
@itsharsh 

Hi, 
There isn't button in UI yet. We will do it.
Workaround is to open URL: ``http://localhost:8080/auto_annotation/cancel/<task_id>`` in the browser

**Comment by itsharsh** [comment]
I'm getting this output:

> Task is not being annotated currently

**Comment by bsekachev** [comment]
@itsharsh 

And does UI still show the progress?

**Comment by itsharsh** [comment]
@bsekachev 
Yes, it's stuck at the same position. (PS: attached screenshot above)

Also, it got resolved after i restarted the cvat by:
```
docker-compose -f <ymlfile1> -f <ymlfile2>  down
docker-compose -f <ymlfile1> -f <ymlfile2>  up -d
```
