### ISSUE TITLE
Cannot Export as dataset: AttributeError: 'ProjectDataset' object has no attribute 'export'\n"

### ISSUE THREAD

**Issue by ramsane** [opencv/cvat#1084]
Error: Request failed with status code 500. "AttributeError: 'ProjectDataset' object has no attribute 'export'\n".

![image](https://user-images.githubusercontent.com/14745146/72803053-23ef1c80-3c73-11ea-830f-61222076faa9.png)

On clicking any of the options, it is giving that error.
![image](https://user-images.githubusercontent.com/14745146/72803106-44b77200-3c73-11ea-9e13-d710253ee1d0.png)

Any one has any idea on why this is hapenning

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please look?
