### ISSUE TITLE
I am trying to launch cvat on my ubuntu 19.10 

### ISSUE THREAD

**Issue by IbrahimShamma99** [opencv/cvat#1090]
This error occurs
```
cvat_db uses an image, skipping
cvat_redis uses an image, skipping
Building cvat
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

```
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by bsekachev** [comment]
@IbrahimShamma99 

It seems, you haven't run ``docker service``.
Try to run ``docker run hello-world``. If it doesn't work, please [setup](https://docs.docker.com/install/linux/docker-ce/ubuntu/) docker properly before.

**Comment by IbrahimShamma99** [comment]
It works fine now.
Thanks.
