### ISSUE TITLE
share option

### ISSUE THREAD

**Issue by taylan24** [opencv/cvat#1091]
Hello,

I want to create a task with 15k images, but they cannot be uploaded from "my computer" option.
I want to use "share" option but I don't know hot to mount share directory,

Can anyone explain how to use share option?
I cannot find any enough steps in the documentation

**Comment by bsekachev** [comment]
@taylan24 

Hello, just create an additional compose file as it described [here](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path) and add it to other files with ``-f`` flag when you install CVAT

**Comment by azhavoro** [comment]
I will close the issue. Don't hesitate to reopen the issue if you still have questions.
