### ISSUE TITLE
Empty csv  file on "MOT CSV 1.0"

### ISSUE THREAD

**Issue by Rub21** [opencv/cvat#1096]
It does not work  `Actions/Dump annotation/ MOT CSV 1.0`,  it export a empty file.

**Comment by azhavoro** [comment]
@Rub21 Hi, what kind of annotation objects are you trying to dump in MOT format?https://github.com/opencv/cvat/blob/04c7669cf585a1aa0e88a4b5e9b45f9ff727630c/cvat/apps/annotation/mot.py#L37-L39 Export of tracks works fine for me.

**Comment by Rub21** [comment]
@azhavoro , I have a task with a couple of thousands of images, I labeled many of them, and I want to export them in CSV format,the XML works fine the but not in CSV.

**Comment by azhavoro** [comment]
@Rub21 Have you annotated images with single bounding boxes or tracks?

**Comment by Rub21** [comment]
some cases are a single box, some other multiple boxes, I think that is the reason why it is empty, what should be the right formats for using the options "MOT CSV 1.0".

**Comment by azhavoro** [comment]
Do you mean interpolation objects as multiple boxes(https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#interpolation-mode-basics)?
MOT exporter dumps only interpolation tracks. You can try the trick - dump your annotation as `CVAT XML for video`, upload it (be careful: this step will change the current annotations, you can create a new task with the same images or save annotations in the default format witch marked by bold font), after that dump as MOT CSV.

**Comment by azhavoro** [comment]
@Rub21 I will close the issue. Don't hesitate to reopen the issue if you still have questions.

**Comment by cstamatopoulos** [comment]
I can confirm that this is the case for me as well.
All I did was add a single bounding box in an image, either by 2 or 4 points.
Saved, and then tried to dump to MOT but the file was empty.
Other file format seem to be fine

**Comment by azhavoro** [comment]
Basically we can represent a single bounding box as a track with with the one box to dump it in MOT format. Is this approach is applicable for you?

**Comment by cstamatopoulos** [comment]
I would say so.
I expect that in the case of more bounding boxes being present in an image additional entries will be present in the csv file.
Frame will be the same, but the identity number is just going to be increasing with the number of bboxes.

**Comment by zhiltsov-max** [comment]
Fixed in #1352
