### ISSUE TITLE
Question: What code will be reused in the new React GUI?

### ISSUE THREAD

**Issue by mistermult** [opencv/cvat#1105]
There is new React/Typescript code (cvat-core, cvat-canvas, cvat-ui) and old code cvat/cvat/apps/engine/ for the GUI of the annotation editor. Is it still useful to modify the old code in cvat/cvat/apps/engine/ when the the React/Typescript is used in the future.
Example: There is a PolygonShape 
https://github.com/opencv/cvat/blob/b918aeb224629ad043bfe177e4bde1894976345a/cvat-core/src/annotations-objects.js#L949
 in the new code and a PolygonModel 
https://github.com/opencv/cvat/blob/b918aeb224629ad043bfe177e4bde1894976345a/cvat/apps/engine/static/engine/js/shapes.js#L1262
 in the old code. 

Should PR modify the old or new code? Will changes from the old code migrated to the new code?

**Comment by nmanovic** [comment]
@mistermult , it is necessary to modify cvat-core. Legacy code will life for some time but most probably will be deleted at the end of Q1'20. Let's discuss such kind of questions here: https://gitter.im/opencv-cvat/dev

I will close the issue to keep growing number of issues manageable.
