### ISSUE TITLE
Issues accessing the postgres database

### ISSUE THREAD

**Issue by Kieran-Bacon** [opencv/cvat#1110]
Creating this issue to extend this [issue](https://github.com/opencv/cvat/issues/829).

I've updated the `cvat_db` image definition to include exposing the ports:
```cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
    volumes:
      - cvat_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
```  

However when connecting to the database there are no tables defined and nothing is present.

I know that the database is filled with content as there are tasks, users, and annotations in the ui, but I seem to have no ability to access the underlying database objects.

I'm not attempting to get to the tasks/annotations via this method, I'm interested in seeing user information/login times and their ip addresses when they connected and would like to interrogate the admin tables, I am assuming that PostgreSQL is the database behind that.

I've rebuilt and forced recreate of the docker-compose app but nothing is visible.

I've been able to connect my sql client (DBeaver) to the database (and have had to use root as the username which makes me believe that I am connecting to the data) but I cannot see anything there.

**Comment by azhavoro** [comment]
Please make sure you are connected to the `cvat` database. I've successfully connected and can view table data
![dbeaver](https://user-images.githubusercontent.com/41117609/73521862-25110e00-4418-11ea-897f-4fb51fd1471e.jpeg)

**Comment by azhavoro** [comment]
@Kieran-Bacon Hi, did you solve the issue? I think it's not a CVAT issue, I'll close it, but don't hesitate to reopen the issue if you still have questions(or ask on gitter https://gitter.im/opencv-cvat).

**Comment by pranavpeddi** [comment]
Hello @azhavoro , I installed postgree on my local pc, and also configured port in docker.yml file, but how do i connect to it now.

**Comment by GeorgePearse** [comment]
What is the default password for this postgres user (root), 'postgres' is not working for me.
