### ISSUE TITLE
Duplication of Boxes on some frames.

### ISSUE THREAD

**Issue by cvadim4two** [opencv/cvat#1112]
During the annotation process, we've noticed such issue only on some frames (about 30 out of 3000). Can you suggest what may be a cause?

**Comment by azhavoro** [comment]
@cvadim4two 
Thanks for the report. Do all boxes on the frame have duplicates? This is fully manual annotations or did you use auto annotation? At the moment I have no idea what could be a cause of the issue.

**Comment by cvadim4two** [comment]
> Do all boxes on the frame have duplicates?
No, at least one item (from 8) on each frame, correct, with one box.

All annotation is manual.

Our annotator got this befor but did not pay attention and manually removed duplications.

**Comment by bsekachev** [comment]
@cvadim4two 

If all annotations are manual, I can suggest that this job has been annotated by several people in parallel.

**Comment by cvadim4two** [comment]
It may be but less likely, due to no facts i'd suggest to close issue.
Thanks for your time.

**Comment by nmanovic** [comment]
@cvadim4two , did you use ctrl+v, ctrl+c feature? May somebody inserted an element twice?

**Comment by cvadim4two** [comment]
> @cvadim4two , did you use ctrl+v, ctrl+c feature? May somebody inserted an element twice?

No, we do not use CTRL+C feature, so human factor could be possible but very unlikely.
