### ISSUE TITLE
cannot login from LAN and WAN at the same time 

### ISSUE THREAD

**Issue by yxftju** [opencv/cvat#1116]
I notice in some previous issue , some method has been provide to make the system could be login from LAN #1093  or WAN #1095  . But I found that if I set the system login from WAN for my peers, I could not even login from LAN for task managent . Can any one provide an solution ?

**Comment by azhavoro** [comment]
The issue should be resolved by `cvat-proxy` service. @yxftju feel free to reopen if you have questions related to this issue.
