### ISSUE TITLE
Failure to build "Model Manager" in CVAT

### ISSUE THREAD

**Issue by lijiayi9712** [opencv/cvat#1121]
Hi, I am pretty new to CVAT and I am trying to apply pre-trained DL models on my video data. I a following the tutorial [here](https://github.com/opencv/cvat/tree/develop/components/openvino) to install the OPENVINO toolkit. However, when I am running the command for "Build docker image", I keep getting the following errors: 
<img width="675" alt="Screen Shot 2020-02-05 at 1 55 06 AM" src="https://user-images.githubusercontent.com/25253573/73831856-dcf93f00-47bb-11ea-9df5-9c8406691ef2.png">
I am installing on a Mac and downloaded the installer. I have tried installer versions for both mac and linux and they all give me the same mistake. The current version that I am using is l_openvino_toolkit_p_2019.3.376.tgz

I have tried to directly run the installer but I still couldn't find the Model Manager in the CVAT work interface.

Many thanks!

**Comment by azhavoro** [comment]
@lijiayi9712 Hi, thanks for report 
The folder `components/openvino` should contains only one Openvino installer and it must be the linux package (.tgz)
Also please make sure  *.tgz file is not corrupted and you can extract it with the command `tar -xzf path_to_the_tgz_file`
If it doesn't help please add `set -x` to the begin of the file https://github.com/opencv/cvat/blob/develop/components/openvino/install.sh, try to build images once again and attach build logs? Thanks.

**Comment by lijiayi9712** [comment]
Thank you so much! After adding the line and downloading a new package, it works!
