### ISSUE TITLE
Cannot login after adding OpenVINO toolkit support.

### ISSUE THREAD

**Issue by atmadeep** [opencv/cvat#1122]
[Uploading cvat_logs.log…]()
![login_isuue_cvat](https://user-images.githubusercontent.com/22106111/73859075-7c234280-485f-11ea-96df-8d4bbbf7c2b1.jpeg)
1. Built the docker image without openvino toolkit support. 
1.1 Was able to create tasks and import files.
2. [Added OpenVino toolkit](https://github.com/opencv/cvat/blob/develop/cvat/apps/auto_annotation/README.md) support and rebuilt the docker image.
!! Was not able to login. 
Also the port number for login page changed from 8080 to 7080.

**Comment by bsekachev** [comment]
@atmadeep 

Have you changed config files anyhow?
Can you reach ``localhost:8080/api/v1/``? 

If you can, please attach output in the browser console (F12 -> Console tab) for investigating. 
By the way, logs you attached are unavailable. 

If you cannot, please be sure ``cvat`` container is up.

**Comment by azhavoro** [comment]
@atmadeep Hi, is the issue still relevant for you?

**Comment by nmanovic** [comment]
It isn't relevant anymore.
