### ISSUE TITLE
TF_annotation does not use a GPU with the CUDA component installed.

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#1124]
How to reproduce:
build `docker-compose -f docker-compose.yml -f components/tf_annotation/docker-compose.tf_annotation.yml -f components/cuda/docker-compose.cuda.yml up -d --build` and run tf_annotation. Inference will be runned on CPU.

Seems the `tensorflow_gpu` package is overridden by `tensorflow` from datumaro requirements.

**Comment by itsharsh** [comment]
Is this the reason for slow processing of automatic annotation?

**Comment by tealeeseng** [comment]
I changed tensorflow version to 1.12 and GPU runs. tensorflow 1.13.1 seems to be running fine with cuda 10 as per 
https://stackoverflow.com/questions/50622525/which-tensorflow-and-cuda-version-combinations-are-compatible

for your quick change, 
grep -R "=1\.13" *

and change files accordingly. I also commented away the line at datumaro/requirements.txt, as it is installing CPU version too. 

datumaro/requirements.txt:# tensorflow==1.13.1

**Comment by itsharsh** [comment]
@nmanovic 
I updated the cvat repo and built it again using:
`docker-compose -f docker-compose.yml -f components/tf_annotation/docker-compose.tf_annotation.yml -f components/cuda/docker-compose.cuda.yml up -d --build`

and getting the following error:
![Screenshot from 2020-02-11 17-06-02](https://user-images.githubusercontent.com/14810684/74233771-52e83380-4cf1-11ea-964d-ec75b1dca82e.png)

**Comment by azhavoro** [comment]
@itsharsh Hi,
at the moment tf_annotation with gpu support is broken.Please see https://github.com/opencv/cvat/issues/1133 for details.

**Comment by itsharsh** [comment]
Okay, got it, 
will wait for the fix, thanks...

**Comment by tealeeseng** [comment]
#1138  works for me.
