### ISSUE TITLE
Where the annotataed data stores in server

### ISSUE THREAD

**Issue by Cylian** [opencv/cvat#1144]
I am running CVAT on my Windows 10 workstation, and accessing the server from intranet. Everything works fine. I just want to know where the annotated data are being stored in the server locally.

**Comment by bsekachev** [comment]
@Cylian 

Hi,
On the host where you have installed CVAT (windows 10 workstation in your case). 
Inside the docker volume ``cvat_db``.

**Comment by bsekachev** [comment]
For such a kind of questions, please use gitter in the future. 
I'll close the issue for now.
