### ISSUE TITLE
Offical docker images for CVAT

### ISSUE THREAD

**Issue by MahdiEsf** [opencv/cvat#1150]
Does anyone know if there is any official docker images for CVAT? I see CVAT related images on docker hub from different people with various number of download requests and not sure what are the difference among various images and the reason why some have got dowloaded much more than other? 
Appreciate your comments if you already had experience with CVAT

**Comment by bsekachev** [comment]
@MahdiEsf 

Right now CVAT doesn't have officially distributed images on docker hub. 
We are working here to solve different legal issues. 

Related github issue: #7

**Comment by MahdiEsf** [comment]
Thanks @bsekachev .
Are there any images in docker hub recommended in terms of functionality and reliability for cvat, cvat_ui, cvat_redis, cvat_db?
Also are you aware of any documentations clarifying the differences among different docker images of the same type and hence getting more downloads from people?

**Comment by bsekachev** [comment]
@MahdiEsf 

We haven't used 3rparty docker images at all. So, I can't answer for your questions. Maybe if you ask them on gitter, somebody will answer you. 
I'll close the issue.
