### ISSUE TITLE
Unable to login to CVAT on AWS

### ISSUE THREAD

**Issue by robertbanfield** [opencv/cvat#1158]
I checked out CVAT this morning:

git describe
0.2.0-454-g538da9f
git describe --tags
v0.4.1-311-g538da9f

I have hooked up ELBs to the AWS instance that perform SSL termination and perform the port redirects.  I can access each of them at https://ss.trimbledatalabel.com and https://ssui.trimbledatalabel.com.  Network-wise, things seems fine to me, I can connect to them at those locations.  

I have created the admin user 'rbanfield' with the password 'T!bsSWjz2@Yb' anyone willing to help is welcome to try to log in.  I am unable to log in however.  It's almost like the UI doesn't even try.  Via livehttpheaders I see an OPTIONS request is sent out that returns a 200.  It looks like follows:

OPTIONS /api/v1/auth/login HTTP/1.1
Host: ss.trimbledatalabel.com:443
Accept: */*
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: POST
Origin: https://ssui.trimbledatalabel.com
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

HTTP/1.1 200
access-control-allow-credentials: true
content-length: 0
content-type: text/html; charset=utf-8
date: Tue, 18 Feb 2020 22:35:30 GMT
server: Apache
status: 200
vary: Origin

If on the other hand I go to https://ss.trimbledatalabel.com/api/v1/auth/login I am presented with a Django REST framework that allows me to enter in credentials.  When I put in my credentials, I do successfully get returned a key.

HTTP 200 OK
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "key": "c3295c36f5a94ca1da3f73fa936556435932b2ab"
}

But I'm still stuck not being able to login via https://ssui.trimbledatalabel.com.  I've tried a handful of things and no changes I've made so far work.  I'm running out of ideas and have no idea where to proceed from here.

Here are the contents of my docker-compose.yml file.  
#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: "2.3"

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: cvat
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        TF_ANNOTATION: "no"
        AUTO_SEGMENTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        TZ: "Etc/UTC"
        OPENVINO_TOOLKIT: "no"
    environment:
      ALLOWED_HOSTS: "*"
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      UI_SCHEME: https
      UI_HOST: ssui.trimbledatalabel.com
      UI_PORT: 443

    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models

  cvat_ui:
    container_name: cvat_ui
    image: nginx
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        REACT_APP_API_PROTOCOL: https
        REACT_APP_API_HOST: ss.trimbledatalabel.com
        REACT_APP_API_PORT: 443
      dockerfile: Dockerfile.ui

    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat
    ports:
      - "7080:80"

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:

**Comment by azhavoro** [comment]
@robertbanfield Hi, could you please try to change the following line 
https://github.com/opencv/cvat/blob/538da9fe0f10b45946b1a0f02e23906d18d31c0e/cvat/settings/base.py#L196
with `UI_PORT and UI_PORT != '80' and UI_PORT != '443':`?

**Comment by robertbanfield** [comment]
@azhavoro Thank you, this has enabled me to log in!
