### ISSUE TITLE
Delete label / attribute

### ISSUE THREAD

**Issue by cbasavaraj** [opencv/cvat#1159]
Hi, I'm unable to delete label(s) or attributes from a task. Tried both `Raw` and `Constructor`. I can however add labels / attributes. Any ideas? Thanks

**Comment by bsekachev** [comment]
@cbasavaraj 

Hi, 
CVAT UI doesn't allow to delete labels/attributes. It isn't safe for some reasons. 
If you actually know what you do, you can delete them in django admin panel: ``localhost:8080/admin`` by default.

**Comment by bsekachev** [comment]
I will close the issue for now. Please continue asking such a kind of questions on gitter.

**Comment by Anton-Velikodnyy** [comment]
can this be a feature request? or @cbasavaraj is there a better clarification for "It isn't safe for some reasons."

**Comment by nmanovic** [comment]
@Anton-Velikodnyy , we are going to fix that. Here an open issue for the problem: https://github.com/opencv/cvat/issues/2066
