### ISSUE TITLE
Change label ID in admin panel

### ISSUE THREAD

**Issue by selimbek** [opencv/cvat#1169]
Hi,

Firstly, thank you for your tool. Pretty well designed for annotation process ! Shortcuts are convenient even with a AZERTY keyboard :)

I would like to add new labels to a task already completed to match freshly new made tfrecords with new specification. 
I succefully add one inside the admin panel. But I can not change his ID.
It's a trouble because the new label will not match with the other tfrecords dataset labelmap ids.

Have you any idea to solve this issue ? 

Best regards,
--Selim

**Comment by azhavoro** [comment]
@Hi, let's clarify some details. Label IDs in the dumped tf_record files are generated by consistently during dump and don't depend on database IDs, only on order.
https://github.com/opencv/cvat/blob/0bb92f27c1f8a78cb66868f49b04b04f5ce32358/cvat/apps/annotation/tfrecord.py#L95
If you add a new label for the existing task, max_tf_record_id + 1 will be used for this label inside tf_record file.
Could you please describe what you want to get exactly? The same label map for the different tasks or smth else?

**Comment by selimbek** [comment]
Yes exactly, I would like to share the same label map id's in tf_record files generated from different tasks. Even if the label was added in different order.

**Comment by dsgage** [comment]
Heyo,

I had the same issue with exporting TFRecords with differing label_map.pbtxt so I couldn't use this for training.  I tried to change the "Raw" labels, but CVAT would not update my labels...

Solution:
- Dump annotations in CVAT xml format
- Open xml file, and adjust the order of the labels
- Upload annotations in CVAT xml format
- Check work ??? (everything was fine for me)
- Export as a dataset in TFRecord
- Check that label_map.pbtxt is in order

It's a bit clumsy(and scary when you are overwriting 8 hours of annotating!), but it works.  

Hope this helps any wayward annotators out there!

**Comment by selimbek** [comment]
@dsgage 
I did something similar to solve this issue:

- Dump annotation
- Create a new task with the correct order
- Import annotation
- Export dataset in Tfrecord format

**Comment by santomwz** [comment]
Hi @selimbek @dsgage 

I solve this issue similar with you guys 👍  

- Dump annotations in CVAT xml format
- Open xml file, and adjust the order of the labels
**- Remove Annotation Result in CVAT Task Job
- Delete the incorrect label or edit label from admin panel e.g: /admin/engine/task/30/change/
- Insert/Replace the correct label in CVAT task menu**
- Upload annotations in CVAT xml format
- Check work ??? (everything was fine for me)
- Export as a dataset in TFRecord
- Check that label_map.pbtxt is in order

**Comment by bsekachev** [comment]
I will close the issue for now, do not hesitate reopen it if you still have questions
