### ISSUE TITLE
CVAT : Localhost refused to connect.

### ISSUE THREAD

**Issue by AhmadM-DL** [opencv/cvat#1170]
I am trying to get CVAT to work on windows 7.
I have docker version 19.03.1, build 74b1e89e8a.

After running :
`docker-compose build`

Then:
`docker-compose up -d`

Output:
```Creating network "cvat_default" with the default driver
Creating cvat_db ... done
Creating cvat_redis ... done
Creating cvat ... done
Creating cvat_ui ... done
```

However the server is not actually up as I can't really connect to it on localhost:8080.

`docker logs cvat` output: [cvat_log.txt](https://github.com/opencv/cvat/files/4231888/cvat_log.txt)

**Comment by bsekachev** [comment]
@AhmadM-DL 

Hi, try this fix: #1146

**Comment by AhmadM-DL** [comment]
Thanks @bsekachev for your time.

It seems it have worked.

But now I have the same problem with different logging output.
The problem this time is in cvat_db:

[cvat_db_log.txt](https://github.com/opencv/cvat/files/4235541/cvat_db_log.txt)

Mainly it is saying:

```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD for the superuser. Use
       "-e POSTGRES_PASSWORD=password" to set it in "docker run".

       You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
       without a password. This is *not* recommended. See PostgreSQL
       documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

**Comment by bsekachev** [comment]
@AhmadM-DL 

Oh, yes.  Another recent fix: #1153

**Comment by AhmadM-DL** [comment]
I did that but strangely enough connection to localhost is still being refused.

And I can't find any obvious problem in the logs:
[cvat_db_log.txt](https://github.com/opencv/cvat/files/4235842/cvat_db_log.txt)
[cvat_log.txt](https://github.com/opencv/cvat/files/4235843/cvat_log.txt)
[cvat_redis_log.txt](https://github.com/opencv/cvat/files/4235844/cvat_redis_log.txt)

And also `docker ps` shows that every thing is up and ready:
[docker_ps.txt](https://github.com/opencv/cvat/files/4235846/docker_ps.txt)

Any though?

**Comment by AhmadM-DL** [comment]
It turns out the problem might have arisen from using Docker Toolbox.
 (Docker Windows requires Windows 10 )

To resolve the problem I followed the following answer on [stackoverflow](https://stackoverflow.com/questions/42866013/docker-toolbox-localhost-not-working).
It states the following:

```
I initially had a few issues with accessing my Applications at localhost:8080 while using DockerToolBox and OracleVM VirtualBox.

In VirtualBox:

Click the appropriate machine (probably the one labeled "default")
Settings
Network > Adapter 1 > Advanced > Port Forwarding
Click "+" to add a new Rule
Set Host Port 8080 & Guest Port 8080; be sure to leave Host IP and Guest IP empty
```
Though I had to do the same for port 7080 too.

Also I had to run chrome as an administrator and to use incognito mode.
