### ISSUE TITLE
Error when submit a  deeplabv3_cityscapes model in Model Manager 

### ISSUE THREAD

**Issue by Yraimtj** [opencv/cvat#1178]
I'm trying to put the converted IR model of the deeplabv3_cityscapes_train_2018_02_06 from the TensorFlow DeepLab Model Zoo in CVAT but get the following error when submit: 

**Checking request has returned the "failed" status. Message: Exception: Model was not properly created/updated. Test failed: IndexError at line 12: too many indices for array**
 
I use:
- OPENVINO_2019.3.334
- The Interpretation script is as use with semantic-segmentation-adas-0001 (https://github.com/opencv/cvat/tree/develop/utils/open_model_zoo/Transportation/semantic-segmentation-adas)
- the mapping json: I just add more class like the cityscapes dataset : 33

When I try to submit the semantic-sesmentation-adas-0001 model (https://github.com/PINTO0309/OpenVINO-ADAS/tree/master/lrmodels/FP32) it's work perfectly.

Does it mean the conversion is not correct, or the interp.py is not compatible with the model?

This is the .xml file for the cityscapes model
[xml_file.zip](https://github.com/opencv/cvat/files/4236961/xml_file.zip)

**Comment by benhoff** [comment]
The interp.py is not compatible.

**Comment by Yraimtj** [comment]
Thanks for replying @benhoff .
So what kind of interpretation script I can use for this task?

**Comment by Yraimtj** [comment]
Hi @benhoff.

Finally resolved the problem by change line #12 in the interp.py  : 

- detection = detection[0, 0, :, :] to  detection = detection[ 0, :, :]

and it's work.

**Comment by benhoff** [comment]
Did you change line 15 as well?
https://github.com/opencv/cvat/blob/8caa1695c52aab06574fc8651840ff6e80baa072/utils/open_model_zoo/Transportation/semantic-segmentation-adas/interp.py#L15

Otherwise it's hardcodes to expect only 21 classes.

**Comment by Yraimtj** [comment]
Yes, also modify this line for the corresponding  number of classes.

**Comment by benhoff** [comment]
@Yraimtj , have you thought about committing your interpret scripts to the CVAT code base?

**Comment by Yraimtj** [comment]
@benhoff , not yet but you can do this.
