### ISSUE TITLE
Where does CVAT store images?

### ISSUE THREAD

**Issue by Sreedeepthinukala** [opencv/cvat#1180]
When I create a task, where does cvat really stores the images?

Thanks .
Sree

**Comment by bsekachev** [comment]
@Sreedeepthinukala 

All data (images, annotations) are stored on your host where you have installed CVAT.
In docker volume ``cvat_data`` and ``cvat_db``.

**Comment by WilberRojas** [comment]
Hi, I'm searching for the images at the specified path, but the path might have changed because the images are not there and there is no cvat_db:
![image](https://github.com/opencv/cvat/assets/74274632/f9f8cedd-0660-45f4-8aac-ee07cd6c3ee9)
