### ISSUE TITLE
Could not save the job

### ISSUE THREAD

**Issue by yxftju** [opencv/cvat#1181]
![image](https://user-images.githubusercontent.com/6733680/75094796-5faa3880-55c9-11ea-8eed-bc064931f0c7.png)
sometimes when we save the job, we meet this problem.
if I move to next picture,I can save the job . I don't know why
I am sure I have the permissions . my account is  in annotators,observers,users group.

**Comment by azhavoro** [comment]
@yxftju Hi, you need to re-login in a new tab.
duplicate of #1025
