### ISSUE TITLE
The system become slow when there are lots of polygons

### ISSUE THREAD

**Issue by yxftju** [opencv/cvat#1182]
when there are a lot of polygons on the pictures. the websites turns slow. the websites could not response sometimes . It seems that the bandwidth of the website is enough.I don't know why.

**Comment by bsekachev** [comment]
@yxftju 

Hi,
Probably the same issue like #1141

**Comment by bsekachev** [comment]
@yxftju  

The patch #1197 is expected to help.
Let me know if it does.

**Comment by bsekachev** [comment]
Dublicate the message here: 

> One more [problem](https://github.com/opencv/cvat/issues/602#issuecomment-592062121) was found. 
It has been introduced with the PR above. 
Finally I would recommend to update with #1212. 
Also I will close the issue for now. 
Do not hesitate reopen it if you still has problems with performance after update.
