### ISSUE TITLE
Can't Upload Image to server 

### ISSUE THREAD

**Issue by ShoaibIqbal452** [opencv/cvat#1183]
i have an images dataset on google drive, when i am trying to create a task it says no `Could not create the task on the server. ValueError: No media data found. Code: 400`. When i try to upload the zip file from my local system it gives following error. `Could not put data to the server. Request failed with status code 500. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>500 Internal Server Error</title>\n</head><body>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error or\nmisconfiguration and was unable to complete\nyour request.</p>\n<p>Please contact the server administrator at \n [no address given] to inform them of the time this error occurred,\n and the actions you performed just before this error.</p>\n<p>More information about this error may be available\nin the server error log.</p>\n</body></html>\n". Code: 500`

**Comment by bsekachev** [comment]
@ShoaibIqbal452 

If you use 3rd option (remote data) when you create a task, you must specify list of direct links to images or a video (they end with *.png, *.jpg, *.mp4, etc).

**Comment by Ai-is-light** [comment]
> i have an images dataset on google drive, when i am trying to create a task it says no `Could not create the task on the server. ValueError: No media data found. Code: 400`. When i try to upload the zip file from my local system it gives following error. `Could not put data to the server. Request failed with status code 500. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>500 Internal Server Error</title>\n</head><body>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error or\nmisconfiguration and was unable to complete\nyour request.</p>\n<p>Please contact the server administrator at \n [no address given] to inform them of the time this error occurred,\n and the actions you performed just before this error.</p>\n<p>More information about this error may be available\nin the server error log.</p>\n</body></html>\n". Code: 500`

have you resovled it? @ShoaibIqbal452

**Comment by bsekachev** [comment]
I will close the issue for now, do not hesitate reopen it if you still have questions

**Comment by KuldeepPCodes** [comment]
hi i am having the same problem , i using the 3rd method Remote one and also i am passing an array in which ,i have provided on link with jpg as extension. this is the code, i have removed the auth . please help


image_data = {
    'image_quality':70,
'remote_files': ["https://images.livemint.com/rf/Image-621x414/LiveMint/Period2/2018/03/17/Photos/Processed/birds-kXAE--621x414@LiveMint-70cb.jpg"],
    "compressed_chunk_type":"imageset",
    "original_chunk_type":"imageset",
    "copy_data": "true",
}
response=requests.post('http://localhost:8080/api/v1/tasks/1/data', auth=(),data=image_data)
print(response)

**Comment by azhavoro** [comment]
@KuldeepPCodes Hi, we provide simple command line tool (utils/cli.py) that supports this case. Please inspect the code regarding remote files https://github.com/openvinotoolkit/cvat/blob/develop/utils/cli/core/core.py#L35-L36
