### ISSUE TITLE
Could not check authorization on server (Openvino, MacOS)

### ISSUE THREAD

**Issue by WafflesAreFriends** [opencv/cvat#1184]
I'm on Mac and trying to install the Openvino component. Everytime I get to the webpage on localhost, I get met with 'Could not check authorization on server' network error message. I looked into the web console and found this:

`
The network connection was lost.
XMLHttpRequest cannot load http://localhost:8080/api/v1/users/self due to access control checks.
Error: Network Error.
Failed to load resource: The network connection was lost. http://localhost:8080/api/v1/users/self
`

I'm running on a MacOS and have been able to install and use the regular component successfully. It is only when I try to install the Openvino component is when I start to have issues. I suspect that it might have something to do with my ./install.sh script under OpenVINO since I just manually install it and removed all the setup code. I don't see how that would effect this however.

**Comment by bsekachev** [comment]
@WafflesAreFriends 

Please attach output of ``docker logs cvat`` as a text file.

**Comment by WafflesAreFriends** [comment]
Oh! When I checked the logs, it said that 'openvino is not installed'. My problem was that I installed openvino for Mac manually instead of just downloading the Ubuntu version and running install. One thing I had to do though is manually unzip and rename the openvino_toolkit file to 'openvino_toolkit' and remove the tar command since it wasn't working. Thanks!
