### ISSUE TITLE
Could not create the task Error: Network Error.

### ISSUE THREAD

**Issue by linmengnan** [opencv/cvat#1190]
when i creat a new task that includes two pictures，it get a Error： Could not create the task Error: Network Error. Can i solve it，thank you！

**Comment by azhavoro** [comment]
@linmengnan Hi, could you please attach output of `docker logs cvat`, `and docker ps -a` and your docker-compose config?

**Comment by Transigent** [comment]
I got exactly the same error. Apparently this occurs when you try to drag and drop images and one of the selected items happens to be a folder. I got no warning a the time of the drag and drop. The number of items drag/dropped was 230. When I selected all except the folder it showed 229 items and worked just fine after that.

A more useful error might be suggested.

**Comment by phamlehuy53** [comment]
> @linmengnan Hi, could you please attach output of `docker logs cvat`, `docker ps -a` and your docker-compose config?

The log shows that some of my images is too large. Tks!
