### ISSUE TITLE
api for automated labeling for unsupported program.

### ISSUE THREAD

**Issue by tusharmehta212** [opencv/cvat#1196]
How can I label images using api. I know there is support for tf od api and other frameworks but i want to label data using other programs. Can someone show me api for labeling using rest calls.
Thanks

**Comment by azhavoro** [comment]
You can browse REST API endpoints with Swagger http://<cvat_url>/api/swagger/

**Comment by nmanovic** [comment]
@tusharmehta212 , you can upload/download annotation files in different formats. Also you can get/put annotations for a specific task. I will close the issue. Please ask such questions on our gitter channel.
