### ISSUE TITLE
How to set the parameter without rebuilding with different server?

### ISSUE THREAD

**Issue by archwolf118** [opencv/cvat#1221]
I am very appreciated to the authors of CVAT. CVAT is really a wonderful tool for annotation. Now we use it in ocr project everywhere. 
But there is a problem that we have to rebuild the images everytime when we change the server (because the ip changes). In some place, like banks and Police Departments, the networks are  enclosed, that is we can not connect the internet.
So could someone give me some advices how to build the docker without set the fixed ip address?
Thank you!

**Comment by azhavoro** [comment]
@archwolf118 Hi, please take a look at https://github.com/opencv/cvat/pull/1177, this patch should solve this issue. You need to configure only one runtime env variable:
environment:
      CVAT_HOST: FQDN
