### ISSUE TITLE
[cuboid] UI screen is frozen after editing cuboid drawing once

### ISSUE THREAD

**Issue by charlescho64** [opencv/cvat#1226]
Hello, 
CVAT is fantastic to me. I have been testing some function on CVAT. 
I think I got bug UI screen is frozen during drawing cuboid and editing it on march 1, 2020 develop branch.

**Comment by azhavoro** [comment]
@charlescho64 Hi, thanks for the report. Could you please provide exactly steps to reproduce the bug?

**Comment by charlescho64** [comment]
~ Test Step..
1. I installed models including openvino and tensorflow 
2. I did run auto semantic / box with installed model 
3. I found the result for auto semantic segmantation and it is ok 
4. and I tried to draw cuboid on car object and edited and it frozen.

**Comment by azhavoro** [comment]
What version are you using? Commit hash would be nice (you can use `git show` to obtain it).

**Comment by charlescho64** [comment]
commit a058765d29577b6e0de1c68d6678a52e5e02e4a6 (HEAD -> develop, origin/develop, origin/HEAD)

**Comment by charlescho64** [comment]
Hello..

I checked it again with latest commit version(commit b3f7f5b8bcc40a10871a3a0aefe3d4757d78b4e3 (HEAD -> develop, origin/develop, origin/HEAD)). I have no problem in this case again.
So, I will close it. 
Thanks...
