### ISSUE TITLE
Action recognition: 1D intervals

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#1228]
In some cases it is necessary to annotate actions for an object on a video. For now we are using attributes but in common case it isn't convenient. Due to key frames we can get a situation when such action can be interrupted by an accident.

**Comment by nikky4D** [comment]
Is there any idea on how to do this yet?

**Comment by hollowgalaxy** [comment]
@nmanovic any news on this?

**Comment by dreaquil** [comment]
We would also be interested in having this feature.

**Comment by nmanovic** [comment]
https://archive.mpi.nl/tla/elan

**Comment by rphila** [comment]
This feature will be useful for my purpose. In some cases, we need to give an annotation tag for the overall movie.
It would be like annotating an action the spans the entire video.

**Comment by nmanovic** [comment]
I will close the issue as a duplicate of https://github.com/opencv/cvat/issues/5003
