### ISSUE TITLE
Uploading large XML Files

### ISSUE THREAD

**Issue by rnekk2** [opencv/cvat#123]
I am having issues uploading large XML files. I created a task with 130K images. I uploaded the annotations XML file around 120MB. It says file being processed. Once it says annotations are being saved, it fails. Changed the DATA_UPLOAD_MAX_MEMORY_SIZE value to 300 MB from the default 100MB but still no luck.

**Comment by nmanovic** [comment]
Hi @rnekk2 ,

Could you please archive your XML file and attach to the issue (or share with us somehow)? We will try to reproduce the problem locally and improve upload functionality somehow.

**Comment by rnekk2** [comment]
Hi @nmanovic ,

                             Attached is the zip file with contains the XML
[6_Annotations-2.xml.zip](https://github.com/opencv/cvat/files/2464067/6_Annotations-2.xml.zip)

**Comment by bsekachev** [comment]
This fix works for annotation files which contain large number of shapes.
However there is other case when annotation file contains some tracks each of them is defined for wide range of frames. So, annotation have a short of time to save and we get 504 code again.

**Comment by nmanovic** [comment]
It should be fixed now. Need to check.

**Comment by nmanovic** [comment]
@azhavoro , could you please check that it works now with your new changes?

**Comment by nmanovic** [comment]
We completely reimplemented upload annotation method. It should work with huge annotation files.
