### ISSUE TITLE
Task button doesn't work

### ISSUE THREAD

**Issue by yxftju** [opencv/cvat#1234]
I found that the task button in the annotation page  jump to `localhost:3000 ` in the most recent version on develope branch, which should be `CVAT_HOST:UI_PORT`. I found that the most recent version `docker-compost.yml` has no `UI_HOST` `UI_PORT` environment. A new `CVAT_HOST` environment has been specified.But In the code `cvat/settings/base.py` it still use `UI_HOST` and `UI_PORT` to get `UI_URL` .
```
UI_SCHEME = os.environ.get('UI_SCHEME', 'http')
UI_HOST = os.environ.get('UI_HOST', 'localhost')
UI_PORT = os.environ.get('UI_PORT', '3000')
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [UI_HOST]
UI_URL = '{}://{}'.format(UI_SCHEME, UI_HOST)
```
It seems this cause the task button guide us to localhost:3000 in the annotation page.
I think this should be modify to use `CVAT_HOST` and the port should be 8080 in the newest version.

**Comment by azhavoro** [comment]
Thanks for the report.
