### ISSUE TITLE
Converting DEXTR model to Inference Engine format

### ISSUE THREAD

**Issue by AlexFridman** [opencv/cvat#1237]
Hello!

I'm going to fine-tune (hope this will help) a DEXTR model on my data and integrate it into CVAT.
Could you please guide me how to convert trained in PyTorch (DEXTR training code is only available in PyTorch) and replace current DEXTR model file with my own?

Thank you!

**Comment by bsekachev** [comment]
@AlexFridman 

Hi, long time ago I've written a script to convert the model. It worked, but I am not sure it works now. Nevertheless you can investigate how conversion can be done. 

You must install at least ``git``, ``openvino``, ``python``, ``tensorflow``, and ``keras`` and probably some minor packages. 

I attached scripts as an archive. Just execute ``convert.sh``.

[arch.zip](https://github.com/opencv/cvat/files/4297056/arch.zip)

**Comment by bsekachev** [comment]
@AlexFridman 

To replace a default model in CVAT, please consider modification of ``Dockerfile``.
```docker
ENV WITH_DEXTR=${WITH_DEXTR}
ENV DEXTR_MODEL_DIR=${HOME}/dextr
RUN if [ "$WITH_DEXTR" = "yes" ]; then \
        mkdir ${DEXTR_MODEL_DIR} -p && \
        curl https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip -o ${DEXTR_MODEL_DIR}/dextr.zip && \
        7z e ${DEXTR_MODEL_DIR}/dextr.zip -o${DEXTR_MODEL_DIR} && rm ${DEXTR_MODEL_DIR}/dextr.zip; \
    fi
```

Finally, ``DEXTR_MODEL_DIR``is expected to specify a directory with ``dextr.bin`` and ``dextr.xml``

**Comment by AlexFridman** [comment]
Thank you, guys! If I'll manage to run it -- I'll write you back!

**Comment by AlexFridman** [comment]
@bsekachev, could you please specify keras, tensorflow and pytorch version you used?
And what is `networks` package?

**Comment by bsekachev** [comment]
@AlexFridman 

``networks`` is ``https://github.com/scaelles/DEXTR-KerasTensorflow/tree/master/networks``
Unfortunately I cannot help you with exact versions.
