### ISSUE TITLE
couldn't create superuser for cvat in windows 

### ISSUE THREAD

**Issue by ghSaint** [opencv/cvat#1240]
winpty docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
'winpty' is not recognized as an internal or external command,
operable program or batch file.

**Comment by nmanovic** [comment]
@ghSaint , try to use cmd.exe instead of gitbash or any other custom interpreter. Does it solve the problem?

**Comment by ghSaint** [comment]
@nmanovic, i tried it in cmd. it was showing the same error.

**Comment by nmanovic** [comment]
Try different advices from the thread below. Recently I built cvat on Windows to help a guy from an internal team. It worked fine. I have no idea what is wrong in your case.

https://github.com/docker/for-win/issues/1588

**Comment by ghSaint** [comment]
i tried using bash and it worked.

Thanks.

**Comment by christian-cahig** [comment]
> i tried using bash and it worked.

Worked for me as well.

**Comment by vishalims095** [comment]
please use gitbash on windows

**Comment by vishalims095** [comment]
> winpty docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser' 'winpty' is not recognized as an internal or external command, operable program or batch file.

please use gitbash on windows
