### ISSUE TITLE
Cannot dump polygon

### ISSUE THREAD

**Issue by thuyngch** [opencv/cvat#1248]
I use polygon to label instance segmentation. When dumping annotation, I got the bug:

Can not dump annotations for the task. Code: 500. Message: "shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7f401c4a2a20>\n"

**Comment by thuyngch** [comment]
I guest some polygons are invalid. Show how can I trace which id of the invalid polygon from 0x7f401c4a2a20?

**Comment by zhiltsov-max** [comment]
@thuyngch, hi. Could you add logs from `docker logs cvat`? There probably should be a stacktrace.

**Comment by thuyngch** [comment]
Hi @zhiltsov-max ,
Thanks for your support. I have found how to fix this issue.
I replaced the new function:
```
        def _calc_polygons_similarity(p0, p1):
            p0 = p0.buffer(0)
            p1 = p1.buffer(0)
            overlap_area = p0.intersection(p1).area
            return overlap_area / (p0.area + p1.area - overlap_area)
```
It works
