### ISSUE TITLE
Bug: Occluded Objects Still Appear In YOLO output!

### ISSUE THREAD

**Issue by AhmadM-DL** [opencv/cvat#1253]
Hello there,

I have annotated a video using interpolation mode.

I then Exported the task as a dataset for YOLO.

However, objects that have been occluded  (totally un-observable) in a certain frame still
appeared in the annotation (bboxes text file) of the corresponding frame.

**Comment by AhmadM-DL** [comment]
Can this be resolved using daturamo?

**Comment by zhiltsov-max** [comment]
@AhmadM-DL, yes, you would filter by `--filter-mode 'i+a' -e '/item/annotation[occluded="False"]'` (check). Everything else as was described in #1251. Check an example [here](https://github.com/opencv/cvat/tree/develop/datumaro#examples).

**Comment by AhmadM-DL** [comment]
Thanks again @zhiltsov-max.
