### ISSUE TITLE
Feature requests: Let the user delete last point when drawing a polygon

### ISSUE THREAD

**Issue by yohayonyon** [opencv/cvat#1254]

**Comment by bsekachev** [comment]
@yohayonyon 

You can use right mouse button during drawing to undo the latest point

**Comment by yohayonyon** [comment]
Thank you
After a polygon is complete a point may be removed. Can it be added?

**Comment by bsekachev** [comment]
@yohayonyon 

Sure. To delete a point you can double click it (or click right mouse button on it and in context menu click "Remove"). 
You also can redraw a part of a polyshape by using shift + dblclick on a point.

**Comment by yohayonyon** [comment]
Great!
Are those features/shortcuts documented somewhere?

**Comment by yohayonyon** [comment]
Another Q: IS there a way to change all the polygons propagated from a single polygon or they are completely separate after the propagation?

**Comment by bsekachev** [comment]
@yohayonyon 

> Are those features/shortcuts documented somewhere?

Sure. In the [user's guide](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#annotation-with-polygons).

>  or they are completely separate after the propagation

Exactly.
