### ISSUE TITLE
LabelMe archive contains wrong files for interpolation tasks

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#1259]
I have an interpolation task where I annotated a couple of objects. See attached xml example with the actual annotation. If I dump annotations in LabelMe format for the task the archive contains duplicated files. Also I cannot upload the annotations in LabelMe format.

[Annotations in CVAT for videos format](https://github.com/opencv/cvat/files/4328840/test.txt)
[Annotaitons in LabelMe format](https://github.com/opencv/cvat/files/4328842/1_test.zip)
[task_test-2020_03_13_09_52_07-datumaro_project.zip](https://github.com/opencv/cvat/files/4328853/task_test-2020_03_13_09_52_07-datumaro_project.zip)

**Comment by zhiltsov-max** [comment]
@nmanovic, what is the problem with import?

**Comment by nmanovic** [comment]
```
Can not upload annotations for the job.
Code: 500.
Message: "cvat.apps.engine.utils.InterpreterError: ImportError at line 120: cannot import name 'mask_to_polygon'
```
