### ISSUE TITLE
Issue with CVAT to PASACL VOC conversion

### ISSUE THREAD

**Issue by sainisanjay** [opencv/cvat#1262]
Hi @nmanovic 
I am facing issue in converting CVAT XML format to PASCAL VOC XML format. I got the following format form CVAT:
```
<annotations>
    <image height="940" id="0" name="90.jpg" width="1820">
	<box label="Objects" occluded="1" xbr="255" xtl="0" ybr="624" ytl="509">
		<attribute name="Class">Car</attribute>
		<attribute name="Occlusion %">25-50%</attribute>
		<attribute name="Truncation %">0%</attribute>
	</box>
    </image
</annotation>
```
and after converting into PSACAL VOC using `/cvat/utils/voc/converter.py` file it always gives object element <name>`Objects`</name>, although it should be Class labels name like `Car`

```
<annotation>
   <folder>images</folder>
   <filename>90.jpg</filename>
   <path>
        /home/images/90.jpg
   </path>
   <source>
        <database>Unknown</database>
   </source>
   <size>
	<width>1820</width>
	<height>940</height>
	<depth>3</depth>
    </size>
    <segmented>0</segmented>
    <object>
	<name>Objects</name>
	<pose>Unspecified</pose>
	<truncated>0</truncated>
	<difficult>0</difficult>
    <bndbox>
	<xmin>0.0</xmin>
	<ymin>509.0</ymin>
	<xmax>255.0</xmax>
	<ymax>624.0</ymax>
    </bndbox>
    </object>
</annotation>
```

**Comment by sainisanjay** [comment]
I got to know why always `Object` is coming in label name under object, as my .xml format is bit different, in my case label is in `<attribute name="Class">Car</attribute>`. which is under box attributes. However, in `convert.py` it get the label directly form box(line number 137-138).
```
for box in img_tag.findall('box'):
    label = box.get('label')
```
in order to access label from my .xml, i replace `label = box.get('label')` into `label = (img_tag.find(".//box/attribute[@name='Class']").text)`. 
In this case it takes the label and update but it keeps all label same of all objects in the image.
For example: if my first object label is Car then it keeps all object label `<name>Car</name> `
Any idea whats going wrong?

**Comment by zhiltsov-max** [comment]
Shape class (e.g. `Car`) should not be an attribute, it should be a label. Check source task properties.

**Comment by sainisanjay** [comment]
Hi @zhiltsov-max, 
Yes you are right, i have change the `utils/voc/convert.py` as per below:

```
if unknown_tags:
                log.warn('Ignoring tags for image {}: {}'.format(image_path, unknown_tags))

            for box in img_tag.findall('box'):
                label = box.get('label')
```
into
```
if unknown_tags:
                log.warn('Ignoring tags for image {}: {}'.format(image_path, unknown_tags))
            name = 'Class'
            for box in img_tag.findall('box'):
                if box.tag == 'box':
                    for var in box:
                        if var.attrib.get('name') == name:
                            classname = var.text
                label = classname
```
Now it works very well. I just wonder if you can help me change same things `utils/tfrecords/convert.py` as it generate always only one object ID in `label_map.pbtxt`
```
item {
	id: 1
	name: 'Objects'
}
```
