### ISSUE TITLE
nginx not configured

### ISSUE THREAD

**Issue by samyhocine** [opencv/cvat#1264]
Hi,

I'm on Win10 Home and I use docker Toolbox.

I've followed the installation guide but I'm facing an issue. Working on since two days but didn't find a way to solve it :/

When I connect to "http://192.168.99.100:8080" on Google Chrome I have the nginx homepage with this message:

"Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx."

So nothing has been configured and I can't access the login page.

How is it so ?

The build went well and everything is green "done" when doing docker-compose up -d

For information:

I've modified the file docker-compose.yml (because I'm using Docker Toolbox)

```
cvat_proxy:
...
    environment:
        CVAT_HOST: "192.168.99.100"
```

And also updated the cvat-ui/package.json file with:

```
"scripts": {
    "build": "webpack --max-old-space-size=8192 --config ./webpack.config.js",
```

To increase the available mem space because of an issue I had during the build: "JavaScript heap out of memory" (issue solved with this update)

Best regards,

Samy

**Comment by samyhocine** [comment]
Is this a trivial problem ?

**Comment by azhavoro** [comment]
@samyhocine Hi, sorry for the late response. We did't try to build and use CVAT with docker toolbox, but could you please run the following command and attach cvat_proxy.conf file?
```
docker cp cvat_proxy:/etc/nginx/conf.d/default.conf cvat_proxy.conf
```

**Comment by samyhocine** [comment]
Hi,

Thanks for your feedback.

This line didn't help unfortunately. I tried this command before a:

`docker-compose up -d`

And before a "rebuilt": `docker-compose build`

Attach the cvat_proxy.conf file

Thanks ;)

**Comment by azhavoro** [comment]
@samyhocine could you post output from `docker-compose config` and `docker ps` also?

**Comment by samyhocine** [comment]
Here we go


[docker_ps_res.txt](https://github.com/opencv/cvat/files/4339935/docker_ps_res.txt)

**Comment by samyhocine** [comment]
@azhavoro here we go :)

[docker_ps_res.txt](https://github.com/opencv/cvat/files/4339943/docker_ps_res.txt)

[dockercompose_config_res.txt](https://github.com/opencv/cvat/files/4339945/dockercompose_config_res.txt)

**Comment by azhavoro** [comment]
It's very strange, everything looks ok ... nginx homepage points that it uses default config, but config is properly configured. Could you attach your docker-compose.yml? I'll try to reproduce the issue on windows.

**Comment by samyhocine** [comment]
Thanks a lot :)

Attached docker-compose.yml (.txt for the upload)

[docker-compose.yml.txt](https://github.com/opencv/cvat/files/4340128/docker-compose.yml.txt)

**Comment by yohayonyon** [comment]
I have the same issue, so I follow...

**Comment by azhavoro** [comment]
@samyhocine @yohayonyon Hi, could you please attach the output from the following commands
`docker exec -it cvat_proxy -T` and `docker exec -it cvat_ui -T`?

**Comment by azhavoro** [comment]
One more question: is the admin page http://192.168.99.100:8080/admin reachable?

**Comment by samyhocine** [comment]
@azhavoro 

[docker_exec_it_cvat_proxy_T.txt](https://github.com/opencv/cvat/files/4350075/docker_exec_it_cvat_proxy_T.txt)

[docker_exec_it_cvat_ui_T.txt](https://github.com/opencv/cvat/files/4350076/docker_exec_it_cvat_ui_T.txt)

[docker_logs_cvat_proxy.txt](https://github.com/opencv/cvat/files/4350062/docker_logs_cvat_proxy.txt)

docker logs cvat_ui returns Nothing

Yes, http://192.168.99.100:8080/admin is reachable. I can see the Django administration login panel.

**Comment by azhavoro** [comment]
@samyhocine  sorry, right command is `docker exec -it cvat_proxy nginx -T` and `docker exec -it cvat_ui nginx -T`

**Comment by samyhocine** [comment]
Sorry @azhavoro 

I've just switched on Windows 10 Pro.

Maybe @yohayonyon would like to continue 

Thanks again @azhavoro for your time ;)

**Comment by azhavoro** [comment]
@samyhocine I think it's not related with docker toolbox, there is the same issue on ubuntu https://github.com/opencv/cvat/issues/1287. Looks lite that cvat_ui not properly configured by some reason and returns default nginx page. Unfortunately I cannot reproduce the issue at the moment...

**Comment by samyhocine** [comment]
I will clone the git and try it on my Windows 10 Pro

**Comment by samyhocine** [comment]
@azhavoro 

I've installed cvat on Windows 10 Pro using Docker Desktop and it's working.

@yohayonyon for the next move ?

**Comment by yohayonyon** [comment]
1. `<machine_name>:8080/admin` - django login screen was reached. I managed to log in with the superuser credentials that I had defined.

2. `docker exec -it cvat_proxy nginx -T` - [cvat_proxy.txt](https://github.com/opencv/cvat/files/4357190/cvat_proxy.txt)


3. `docker exec -it cvat_ui nginx -T` - [cvat_ui.txt](https://github.com/opencv/cvat/files/4357054/cvat_ui.txt)

4.  `docker exec -it cvat_ui cat /usr/share/nginx/html/index.html` - [index.html.txt](https://github.com/opencv/cvat/files/4357220/index.html.txt)

Seems similar to issue #1287.

**Comment by azhavoro** [comment]
@yohayonyon thanks, yes it's the same issue, could you please rebuild cvat_ui image with the command `docker-compose build --no-cache cvat_ui` and attach full build log? Thanks.

**Comment by yohayonyon** [comment]
![Screenshot from 2020-03-20 12-45-16](https://user-images.githubusercontent.com/61744528/77156811-cd526300-6aa8-11ea-94d2-136aa2212600.png)

So far it is stuck there...

**Comment by nmanovic** [comment]
https://github.com/opencv/cvat/issues/1261

> @nmanovic , I have found two issues with the deployment:
> 
> * nginx proxy cannot work by default with long domain names (e.g. ec2-x-xx-xx-xxxx.us-east-2.compute.amazonaws.com). Need to specify a directive to resolve the issue. If you have the problem it is easy do diagnose. Just run `docker logs cvat_proxy` and you will see the recommendation from nginx.
> * When cvat-ui is complied there is a problem with memory consumed by nodejs. Some problems can be solved by use NODE_OPTIONS=`--max_old_space_size=200` environment variable. But webpack consumes too much memory. It leads to "JavaScript heap out of memory" problem ([webpack/webpack#6389](https://github.com/webpack/webpack/issues/6389)).
> 
> Our team will do the best to resolve the issue ASAP.
> 
> P.S. I tried to reproduce the issue on t2.micro with 1G RAM.

**Comment by muhammadhusein** [comment]
I also have the same problem, I'm using ubuntu OS 18.04 ...
how do i fix it?
Please..

**Comment by lbj96347** [comment]
@muhammadhusein I have met the same issue when I install CVAT on Ubuntu OS 18.04. When I type `curl http://localhost:8080/admin` , I'm not able to reach django admin. 

I realized that cvat_ui may not ready for using. So I ran `docker-compose build --no-cache cvat_ui` again. After that I try to run `docker-compose up -d`, it works now.

**Comment by luvwinnie** [comment]
it shows the same problem in macOS Catalina....., the root path goes to the Nginx default page.. Did anyone have the solution?
