### ISSUE TITLE
Better MOT format support

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#1273]
It isn't possible to upload annotations from https://motchallenge.net/instructions/

How current format is `1,0,361.5,249.5,75.90000000000146,161.5,1,person,1` but it should be `<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z>`

**Comment by zhiltsov-max** [comment]
- CVAT should be able to import MOT annotations in different variants as detection tracks and free shapes
- label names are stored in separate file, annotations contain indices as format requires
