### ISSUE TITLE
Missing classes name while generating label_map.pbtxt 

### ISSUE THREAD

**Issue by sainisanjay** [opencv/cvat#1279]
I have created tfrecord using` cvat/utils/tfrecords/convert.py `  but when i check  `label_map.pbtxt ` it missed one class name. I have 7 classes [Car Truck MotorBikes Bicycle Bus Van Pedestrian] in my xml file but it generates only 6 classes in `label_map.pbtxt `.  In my xml has only 2 MotorBikes samples which is not generated in `label_map.pbtxt `. Only lower number of sample class name is missing.

```
item {
	id: 1
	name: 'car'
}
item {
	id: 2
	name: 'van'
}
item {
	id: 3
	name: 'truck'
}
item {
	id: 4
	name: 'pedestrian'
}

item {
	id: 5
	name: 'bus'
}
item {
	id: 6
	name: 'bicycle'
}
```

**Comment by zhiltsov-max** [comment]
@sainisanjay, looking at the script, I can say that the labels are collected from input annotations, so, probably, there are no `motorbike` bboxes. I'd recommend to use task export or Datumaro for generating annotations in different formats, as these scripts are deprecated.

**Comment by sainisanjay** [comment]
Hi @zhiltsov-max, I have verified multiple times that `MoterBikes` bounding box is available in the xml file:

```
<box label="Objects" occluded="0" xbr="-143.55864" xtl="0" ybr="825.2294" ytl="363.41858">
<attribute name="Occlusion %">0%</attribute>
<attribute name="Truncation %">0%</attribute>
<attribute name="Class">MotorBikes</attribute>
</box>
```
can you elaborate what do you mean by, use task export or Datumaro for generating annotations in different formats

**Comment by zhiltsov-max** [comment]
By "task export" I meant the export buttons for the task in the CVAT UI.
By "Datumaro" I meant the [Datumaro project](https://github.com/opencv/cvat/tree/develop/datumaro) here, which have dataset conversion facilities.

**Comment by zhiltsov-max** [comment]
Probably you should take a look at `--min-train` parameter and set it to 0.
```
parser.add_argument(
        '--min-train', metavar='NUM', required=False, default=10, type=int,
        help='The minimum number of images above which the label is considered (default: 10)'
    )
```

**Comment by sainisanjay** [comment]
@zhiltsov-max Thanks `--min-train` parameter was the issue, as i was having less than 10 samples for `MoterBikes` class that's why it did't generate label for that.
