### ISSUE TITLE
Inconsistent labels between UI and CLI/API: "type" instead of "input_type"

### ISSUE THREAD

**Issue by martin-etchart** [opencv/cvat#1284]
UI shows `type` in generated labels but API and CLI expect `input_type` as in the swagger doc.

I created the label in the UI and copied the generated JSON. Manually and with the copy button.
```
[
  {
    "name": "label",
    "attributes": [
      {
        "name": "attr",
        "type": "select",
        "mutable": false,
        "values": [
          "val"
        ]
      }
    ]
  }
]
```
Using that JSON as a string with CLI fails to create the task with `500 Server Error: Internal Server Error for url: http://localhost:8080/api/v1/tasks`

```
python cli.py --auth admin:admin --server-host localhost --server-port 8080 create test_cli share "/data/1.jpg" "/data/2.jpg" --labels "[{\"name\": \"label\",\"attributes\": [{\"name\": \"attr\",\"type\": \"select\",\"mutable\": false,\"values\": [\"val\"]}]}]"
```

Changing `type` to `input_type` solves it. Even after task creation using `input_type` the UI shows `type`.

**Comment by arituerto** [comment]
Hi,
In my case I receive the same error both using "type" and "input_type". It just works if I remove all the attriburtes.

**Comment by bsekachev** [comment]
@arituerto 

Try to use button ``Copy`` (top right corner) instead of copying by hand.

**Comment by bsekachev** [comment]
Closed with PR above
