### ISSUE TITLE
Unable to load annotator UI on nginx reverse proxy

### ISSUE THREAD

**Issue by rcbop** [opencv/cvat#1291]
Hello,

I currently have CVAT set-up behind an nginx reverse proxy and all the features are working fine with the exception that I'm unable to reach the annotator UI by clicking on the job link inside the task.

Here's my nginx configuration:
```
server {
    listen 443 ssl;
    server_name mydomain.com;

    ssl_certificate /etc/nginx/ssl/cvat.crt;
    ssl_certificate_key /etc/nginx/ssl/cvat.key;

    location / {
        error_page 418 = @annotation_ui;

        if ( $query_string ~ "^id=\d+.*" ) { return 418; }

        proxy_set_header        Host $host;
        proxy_pass_header       X-CSRFToken;
        proxy_pass_header       Set-Cookie;

        resolver 127.0.0.11 valid=30s;
        set $upstream_cvat_front cvat_front;
        proxy_pass http://$upstream_cvat_front$request_uri;
        client_max_body_size 10M;
    }

    location ~* /api/.*|git/.*|tensorflow/.*|auto_annotation/.*|analytics/.*|static/.*|admin|admin/.*|documentation/.*|dextr/.*|reid/.* {
        proxy_set_header Host $http_host;
        proxy_pass_header X-CSRFToken;
        proxy_pass_header Set-Cookie;

        resolver 127.0.0.11 valid=30s;
        set $upstream_cvat_back cvat_back;
        proxy_pass http://$upstream_cvat_back$request_uri;
        client_max_body_size 10M;
    }

    # old annotation ui, will be removed in the future.
    location @annotation_ui {
        resolver 127.0.0.11 valid=30s;
        set $upstream_cvat_back cvat_back;

        proxy_pass http://$upstream_cvat_back$request_uri;
        proxy_pass_header       X-CSRFToken;a
        proxy_set_header        Host $http_host;
        proxy_pass_header       Set-Cookie;
    }
}

```

Chrome browser debugger shows that the resquest to the location **/** with the query string `?id=<some_number>` returns status code 200 instead of 418. 
The result is that the page listing the tasks is shown to the user instead of the annotator UI.

Could anybody provide guidance on how to solve this?

**Comment by Onion-Skins** [comment]
I am also using nginx reverse proxy in front of CVAT. Why is your nginx config so complicated? I just use a simple proxy_pass setting and everything works fine, including https.

**Comment by rcbop** [comment]
Hello @Onion-Skins when you say complex you mean the resolver statement? 

The reason for that is that this nginx instance is shared with another server statement that creates a different virtual host serving on a different domain (ex: mydomain2.com), using the resolver targeting the docker internal DNS prevents nginx to "die" if one of the upstream containers of either service gets killed or restarted. So long story short.. Nginx doesn't die if CVAT container exits.

That's the reason for these two lines:
```
        resolver 127.0.0.11 valid=30s;
        set $upstream_cvat_front cvat_front;
```

This is for supporting bigger files during an upload:
`client_max_body_size 10M;`

ssl configs are self explanatory. I'll try to follow your advice and simplify as much as possible as a test.

**Comment by Onion-Skins** [comment]
In fact, I am also using a common nginx reverse proxy for two virtual hosts, but I am using version 0.6.0 which does have cvat-proxy. 
I mapped the cvat-proxy's web port to 127.0.0.1:18080, and let nginx reverse proxy forward CVAT requests to that port with a single proxy_pass setting.

**Comment by jrreyes29** [comment]
@Onion-Skins could you paste your configuration, I can't set up the https in my nginx config, how do you do the proxy_pass? I have this
`
server {
    listen       80;
    server_name  _ default;
    return       404;
}

server {
    listen       443 ssl;
    server_name  ${CVAT_HOST};

    # ssl on;
    ssl_certificate /ssl/fullchain.pem;
    ssl_certificate_key /ssl/privkey.pem;
    
    location ~* /api/.*|git/.*|tensorflow/.*|auto_annotation/.*|analytics/.*|static/.*|admin|admin/.*|documentation/.*|dextr/.*|reid/.*  {
        proxy_pass              http://cvat:8080;
        proxy_pass_header       X-CSRFToken;
        proxy_set_header        Host $http_host;
        proxy_pass_header       Set-Cookie;

    }

    location / {
        # workaround for match location by arguments
        error_page 418 = @annotation_ui;

        if ( $query_string ~ "^id=\d+.*" ) { return 418; }

        proxy_pass              http://cvat_ui;
        proxy_pass_header       X-CSRFToken;
        proxy_set_header        Host $http_host;
        proxy_pass_header       Set-Cookie;

    }

    # old annotation ui, will be removed in the future.
    location @annotation_ui {
        proxy_pass              http://cvat:8080;
        proxy_pass_header       X-CSRFToken;
        proxy_set_header        Host $http_host;
        proxy_pass_header       Set-Cookie;
    }
}
`

**Comment by Onion-Skins** [comment]
location / {
                    proxy_pass http://127.0.0.1:18080;
        }

I mapped the cvat-proxy's web port to 127.0.0.1:18080.
that's it. Then you may follow the following guide on how to setup https reverse proxy on nginx.
[https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04](url)
Let's encrypt certbot make things much easier.

**Comment by bsekachev** [comment]
I will close the issue for now, do not hesitate reopen it if you still have questions
