### ISSUE TITLE
Exporting Frame-stepped project in YOLO Format

### ISSUE THREAD

**Issue by TurkeyKittin** [opencv/cvat#1294]
I have a video project which has been annotated using a frame step of 5. Upon export in the YOLO format, the annotations are wrong. All ###.jpg files have ###.txt files that are completely empty. In addition, many "frame_#####.txt" files are also generated within the export data folder and while they do have annotation data, they do not correctly correspond to the same ###.jpg files.

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please look at the issue?
