### ISSUE TITLE
uploading annotations yolo format error

### ISSUE THREAD

**Issue by AllenDun** [opencv/cvat#1309]
version 0.5.2
first, I create a task, then upload yolo format annotations zip file. There are 1000 images, and there are also 1000 yolo format txt annotations. The upload annotations are arranged as obj_train_data folder with all the txt files, obj.names file, obj.data, and train.txt. The error shows:
Could not upload annotation for the task 40
Error: Request failed with status code 500. "cvat.apps.engine.utils.InterpreterError: Exception at line 24: Failed to find 'yolo' dataset at '/tmp/tmp19xpu88g'\n".

I even do an test. For a task without annotations, I just annotate a few images and dump the annotations in the YOLO format zip. I can upload the dumped annotations to the task back. However, in the dumped folder, I put all the 1000 txt annotations in the obj_train_data folder,  modify train.txt and then upload the annotations. It fails and shows the same error.

**Comment by zhiltsov-max** [comment]
Hello, could you please check the version you use? Version 0.5.2 could not produce such an error message.
Assuming some recent version, such an error can only be obtained if there is no `.data` file in the archive root, please check its existence.

**Comment by AllenDun** [comment]
Thanks for the reply. The cvat is develop branch with 1bb582f.  obj.data file is included in the uploaded annotaions zip file

**Comment by zhiltsov-max** [comment]
Please check if there is no extra leading directory added in the archive while archiving, i.e. the file layout is like described [here](https://github.com/opencv/cvat/tree/master/cvat/apps/annotation#yolo-dumper-description):
```
archive.zip/
- train_obj_data/...
- obj.data
- ...
```
and not
```
archive.zip/
- some_dir/
   - train_obj_data/...
   - obj.data
   - ...
```

**Comment by AllenDun** [comment]
oh, Thanks a lot. I found the problem. There was an extra leading directory while archiving.
