### ISSUE TITLE
how to load  images?

### ISSUE THREAD

**Issue by flyingTan** [opencv/cvat#131]
Hi, It's a great work. but how can i load images ?

**Comment by nmanovic** [comment]
Hi @flyingTan ,

Please read [creating an annotation tak](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#creating-an-annotation-task) in documentation. Does it answer your question?

**Comment by flyingTan** [comment]
Thanks! After annotation, I can get labels, but where I can get corresponding original images.

**Comment by nmanovic** [comment]
@flyingTan ,

At the moment CVAT doesn't allow to download original images. You should have them because it uploaded them when created your annotation task. Furthermore internally CVAT doesn't keep original images. It converts original images into jpeg format with specified "Image Quality".

**Comment by flyingTan** [comment]
Thanks!
But after the video of my task has been converted into images and i got the xml label files on the web , how can i use the label files without the origin images? the default fps seem to be 25, but i need 30 fps;Also,when i try to convert video in images by ffmpeg ,it seems that the total frames hasn't equal to the frames on the web.thank you!

**Comment by nmanovic** [comment]
Hi @flyingTan ,

You need to convert your video file into frames using ffmpeg. Look at the code below to extract actual options of ffmpeg:
https://github.com/opencv/cvat/blob/1458d404dd5b1133b8c4597636cec0df7327a907/cvat/apps/engine/task.py#L246

Also it is important to specify `-vsync 0`. The option is crucial to force ffmpeg not to insert extra frames to keep frame rate.

**Comment by flyingTan** [comment]
Hi @nmanovic ,
Thanks for your hard work! i had tried converted video by the configuration in task.py. It works well on the most videos,but there are still some video has loss 1~2 frames.Anyway,thank you!

**Comment by nmanovic** [comment]
@flyingTan ,

I'm glad that you like the tool. Don't hesitate to submit us issues, questions, PRs. I will close the issue. If you think that I need to keep it open by a reason just let me know.
