### ISSUE TITLE
Server Error (500) after log in as a super user

### ISSUE THREAD

**Issue by HaKLMTT** [opencv/cvat#132]
Before I log in , every thing goes well. I don't enable tf_annotation, because I have no Nvidia GPU.
Soon after I create super user using the following cmd:
docker exec -it cvat sh -c '/usr/bin/python3 ~/manage.py createsuperuser'
And go to http://localhost:8080/, after input user and password, in the next page showing 

Server Error (500).

OS: Ubuntu
(Linux version 4.15.0-29-generic (buildd@lgw01-amd64-057) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018)

Need your help here. Thanks.

**Comment by nmanovic** [comment]
Hi @HaKLMTT ,

I guess you are using the development version. First of all please update till the latest version. Today we introduced a regression https://github.com/opencv/cvat/pull/129 in develop but it was already fixed.

Please let me know if you still have problems. In this case need to run `docker logs cvat` and send output to us.

**Comment by HaKLMTT** [comment]
After reboot the OS, the issue above disappear.
