### ISSUE TITLE
Could not check authorization on the server / Could not login on the server Error: Network Error.

### ISSUE THREAD

**Issue by Miguelistan** [opencv/cvat#1322]
Hi guys, 
I am new on CVAT and I am not a developer. The situation I have is:

- Yesterday I cloned and installed CVAT on Windows 10. It worked like a charm.
- Today, I turned the computer on, tried to log in on CVAT but I couldn´t.  

I built and run docker, without results.

Attached I am sending the login screen.

MAny thanks in advance for the help!

Miguel

![cvat login](https://user-images.githubusercontent.com/37583058/77678401-df804580-6f6f-11ea-9ebd-26a01d09f79c.png)

**Comment by bsekachev** [comment]
@Miguelistan 
Hi, try to restart docker containers using:
```bash
docker-compose down
docker-compose up
```

If you specified docker-compose files with ``-f`` flag when you build CVAT, please specify them also here.

**Comment by Miguelistan** [comment]
Dear Boris @bsekachev 
Thank you. It didnt work out. 
This is what I do, please point any problem you may see:
- Openin GitBash
- Starting Docker
- cd cvat directory
- docker-compose build
- docker-compose up -d
- go to  localhost:8080

Then it shows the problem to login the server. 
Attached you can find a txt file with all the GitBash lines

Thank you a lot

[CVAT_problem.txt](https://github.com/opencv/cvat/files/4402767/CVAT_problem.txt)

**Comment by bsekachev** [comment]
@Miguelistan 

You haven't done ``docker-compose down`` as far as I understood. Right?
You need to do it and after that, do ``docker-compose up``

**Comment by Miguelistan** [comment]
@bsekachev 

Thank you very much, it's working fine now

**Comment by mmaaz60** [comment]
Always use CVAT in a fresh Incognito Tab, cheers!

**Comment by suzoosuagr** [comment]
I met the same "Could not check authorization on the server" error. And it was solved by following @mmaaz60 's :

> Always use CVAT in a fresh Incognito Tab, cheers!

🍻

**Comment by Petros626** [comment]
@mmaaz60 hey I stuck after `docker-compose up` because in git bash is doing something and than it hung up.

**Comment by JacobBITLABS** [comment]
met the same issues as above. Some of the services was not started in the background, because docker was not granted enough memory ressources.
