### ISSUE TITLE
Save object attributes in MS COCO format

### ISSUE THREAD

**Issue by AlexFridman** [opencv/cvat#1337]
Hello!

Please, also save object attributes in MS COCO format.

For example, if I have label **test** with attribute **attr** of type "radio" with options like "**opt1**"&"**opt2**" it should looks like:

```json
{
 "is_crowd": 0,
 "segmentation": [[0, 0, 1, 1, 2, 2]],
 "metadata": {
   "attr":"opt1"
 }
}
```

Thank you!

**Comment by zhiltsov-max** [comment]
Hi, could you describe why do you need this functionality? Can you pick another format that supports attributes (`cvat`, `datumaro`, `labelme`)?

**Comment by AlexFridman** [comment]
Hello!

1) I personally like this format. 
2) Frameworks we work with (detectron2, mmdetection) support this format out of the box.
3) When I manipulating data I'm trying to stay within a single format.

As for now, I export data in datumaro format and convert it to COCO, or even lookup data out of the CVAT database.

**Comment by zhiltsov-max** [comment]
Thank, I see you point. Speaking about attributes, how do you expect popular frameworks to provide an access to them out of the box, as they are not officially described there?

**Comment by AlexFridman** [comment]
I do not assume that. Potentially through customizing data pipeline like detectron or mmdetection allow. But my point as follows:
1) if cvat support attributes - please allow users to export them staying withing their favorite data format (COCO one of the most popular ones)
2) If popular frameworks rely on COCO, please allow export data in COCO format without changing it (like dropping attributes), to allow post-process it and put to the framework.

It's not a crucial feature, but I guess it could make life easier :)
