### ISSUE TITLE
CVAT Hardware Requirements

### ISSUE THREAD

**Issue by lakshmikantdeshpande** [opencv/cvat#1345]
Hi, 
I'm running CVAT on a dual core machine with 4GB RAM on AWS. But it still feels sluggish. What are the recommended System Requirements for a better user experience ? I couldn't find anything useful in the repository. In my particular case, ~30 people would be accessing CVAT simultaneously.

**Comment by nmanovic** [comment]
@lakshmikantdeshpande , could you please describe which performance problems you have with the server?

**Comment by lakshmikantdeshpande** [comment]
@nmanovic 
It's UI is slow. Creating a task or loading a task takes a lot of time. For an end user, the UI feels slow. I just wanted to know what is the recommended system configuration for a good experience ?

**Comment by thomasstats** [comment]
@lakshmikantdeshpande some of those performance issues can be related to the end user's system as well.  AWS download speeds and upload speeds are pretty high on all EC2 instances, but if the end user's is slow or the end user's computer can't handle any of the processing it uses it'll cause some trouble.  I'm currently using a t2.xlarge instance with no speed issues, and I think I could definitely decrease that if I wanted to.  I'm guessing you're using a t2.medium by the specs you said?  t2.medium only has low network performance guaranteed, but I'm skeptical over whether or not that's the issue.  I would try initiating a test instance on a higher tier EC2 instance like xlarge or 2xlarge, set it up, see if the issue still exists, then terminate the instance.  If the issue still exists it's likely on the end user's end.  If not, then you know your instance is too small.

**Comment by lakshmikantdeshpande** [comment]
@thomasstats 
Thanks for your response. Looks like it was an issue from user's end. 
It is now working fine with just 6% of CPU usage for 3-4 clients at a time. Closing the issue.

**Comment by Vithiya-R** [comment]
What was the hardware requirement for Enterprise

**Comment by lakshmikantdeshpande** [comment]
@Vithiya-R , 
Don't remember exactly now, but my initial comment says 4gigs with dual core cpu. 
Checked quickly on gemini. It should be t3.medium.
