### ISSUE TITLE
Key sequence to reset zoom?

### ISSUE THREAD

**Issue by headdab** [opencv/cvat#135]
Is there a way to reset the video zoom and origin (viewport) to the original full resolution version?
That is besides zooming out and scrolling with the mouse?
I couldn't find anything on the help page.

Also, on the help page you have Devision instead of Division.

**Comment by nmanovic** [comment]
Hi @headdab ,

If you can help and send us some PR to fix documentation/help it will be awesome. It will help us to make the product much better.

Mouse double click should reset zoom. Does it answer your question?

**Comment by headdab** [comment]
That's it. Thanks.
