### ISSUE TITLE
XML annotation dump skips unlabelled images

### ISSUE THREAD

**Issue by ID56** [opencv/cvat#1350]
Hello. After annotating, I use CVAT's dumped XML for tfrecord generation. However, it seems that if an image is unannotated, it is ignored in the XML and subsequently is skipped from my tfrecord. While I have a workaround (collect all image name; if name is not present in xml add a blank <image> tag), I was wondering if there was a way where the dumped xml also includes those images without any annotation.

**Comment by zhiltsov-max** [comment]
Hello. This behaviour is intended. It cannot be done directly from CVAT UI, however, it can be done with Datumaro like this:
```
# export Datumaro project in CVAT UI
# unzip & change dir
datum project export -f cvat
```

**Comment by ID56** [comment]
Alright thanks a lot.
