### ISSUE TITLE
Duplicated settings for default marking type.

### ISSUE THREAD

**Issue by thomasstats** [opencv/cvat#1351]
In annotation.html there is

`        <select id="shapeTypeSelector" class="regular h2">
            <option value="box" class="regular" selected> Box </option>
            <option value="box_by_4_points" class="regular" selected> Box by 4 points </option>`

Where both of these items are marked as selected.  However, in shapeCreator.js line 235 does the following:

` this._typeSelector.val('box');`

This creates some redundancy.

**Comment by bsekachev** [comment]
Resolved with the PR above
