### ISSUE TITLE
Could not login on the server

### ISSUE THREAD

**Issue by ken292** [opencv/cvat#1361]
Why do i get this message?
How to fix this?

![image](https://user-images.githubusercontent.com/58810041/78467403-1cea8d00-773f-11ea-8224-6ea50cee21c9.png)

**Comment by nmanovic** [comment]
@ken292 , could you please describe how did you get the issue?

**Comment by nmanovic** [comment]
@ken292 , the similar issue described many times on our gitter channel: https://gitter.im/opencv-cvat/public

Could you please look answers and see if they help you?

**Comment by nmanovic** [comment]
@ken292 , I will close the issue. Don't hesitate to reopen it if you still have problems. Provide more details in the case. Also please ask support from community in our gitter channel.
