### ISSUE TITLE
docker-compose build error on windows 10 platform

### ISSUE THREAD

**Issue by fuertesa** [opencv/cvat#1366]
I have running cvat on my linux platform.. I wanted install it on my windows PC but I got this error 
when docker-compose build is run..

$ docker-compose build
cvat_db uses an image, skipping
cvat_redis uses an image, skipping
cvat_proxy uses an image, skipping
Building cvat
Step 1/53 : FROM ubuntu:16.04
 ---> 77be327e4b63
Step 2/53 : ARG http_proxy
 ---> Using cache
 ---> 02df51b28c2f
Step 3/53 : ARG https_proxy
 ---> Using cache
 ---> 2c002d44da77
Step 4/53 : ARG no_proxy
 ---> Using cache
 ---> 0959511fb030
Step 5/53 : ARG socks_proxy
 ---> Using cache
 ---> d405b580a2ec
Step 6/53 : ARG TZ
 ---> Using cache
 ---> 0a0c3742534e
Step 7/53 : ENV TERM=xterm     http_proxy=${http_proxy}       https_proxy=${https_proxy}     no_proxy=${no_proxy}     socks_proxy=${socks_proxy}     LANG='C.UTF-8'      LC_ALL='C.UTF-8'     TZ=${TZ}
 ---> Using cache
 ---> 720c3021a273
Step 8/53 : ARG USER
 ---> Using cache
 ---> 8143799d2eb6
Step 9/53 : ARG DJANGO_CONFIGURATION
 ---> Using cache
 ---> 84b1f6f27bbf
Step 10/53 : ENV DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}
 ---> Using cache
 ---> 6b8708ba5da1
Step 11/53 : RUN apt-get update &&     apt-get install -yq         software-properties-common &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         tzdata         p7zip-full         git         ssh         poppler-utils         curl &&     curl https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash &&     apt-get install -y git-lfs && git lfs install &&     if [ -z ${socks_proxy} ]; then         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30\"" >> ${HOME}/.bashrc;     else         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ProxyCommand='nc -X 5 -x ${socks_proxy} %h %p'\"" >> ${HOME}/.bashrc;     fi &&     python3 -m pip install --no-cache-dir -U pip==20.0.1 setuptools &&     ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime &&     dpkg-reconfigure -f noninteractive tzdata &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 8ec816838820
Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package software-properties-common
Service 'cvat' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -yq         software-properties-common &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         tzdata         p7zip-full         git         ssh         poppler-utils         curl &&     curl https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash &&     apt-get install -y git-lfs && git lfs install &&     if [ -z ${socks_proxy} ]; then         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30\"" >> ${HOME}/.bashrc;     else         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ProxyCommand='nc -X 5 -x ${socks_proxy} %h %p'\"" >> ${HOME}/.bashrc;     fi &&     python3 -m pip install --no-cache-dir -U pip==20.0.1 setuptools &&     ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime &&     dpkg-reconfigure -f noninteractive tzdata &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 4294967295: failed to shutdown container: container 8ec816838820ea8ab8818260ba2ffbf6ea547d197e579a845d0c3ec1ec2d0a8e encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 8ec816838820ea8ab8818260ba2ffbf6ea547d197e579a845d0c3ec1ec2d0a8e encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)

**Comment by nmanovic** [comment]
@fuertesa , it looks like you have a problem with your network. Do you have a proxy server?

```
Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Temporary failure resolving 'archive.ubuntu.com'
```

**Comment by fuertesa** [comment]
> @fuertesa , it looks like you have a problem with your network. Do you have a proxy server?
> 
> ```
> Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
> Temporary failure resolving 'archive.ubuntu.com'
> ```

Hello. I dont use proxy Im connected at home.

**Comment by nmanovic** [comment]
@fuertesa , please try again. What is the OS? If your host OS is ubuntu, please try `sudo apt update`. Otherwise try to open  http://archive.ubuntu.com/ubuntu in your browser. What is the result?

**Comment by nmanovic** [comment]
I will close the issue. Don't hesitate to reopen it if you still have the issue. It looks like a problem on your end.
