### ISSUE TITLE
Hidden or switched off points appear again

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1368]
Noticed that some points appear again even if they were hidden or switched off.
For example the image 1.JPG shows that the highlighted point is switched off but it still on the frame.
![1](https://user-images.githubusercontent.com/45849884/78560881-70340c80-781f-11ea-96f3-537a2cc7266b.JPG)
One more example:
![2](https://user-images.githubusercontent.com/45849884/78561055-c4d78780-781f-11ea-836a-359eca481e16.JPG)
It is noteworthy that if to switch to the Full-screen mode these points will disappear on the current frame. But they will appear again if to go to one frame back.

**Comment by bsekachev** [comment]
The issue is expected to be closed now
