### ISSUE TITLE
React UI crash: "Canvas is busy. Action: resize"

### ISSUE THREAD

**Issue by subdavis** [opencv/cvat#1371]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. Create an interpolated track shape
2. Press and hold the 'f' key to advance frame-by-frame
3. click any of the drag points of the track shape.
4. Screen becomes white and unresponsive, requires reload.

![Screenshot from 2020-04-06 11-28-41](https://user-images.githubusercontent.com/4214172/78575817-d9a12480-77f9-11ea-8f62-f6fd1aa9d0fe.png)

### Context

This looks like exacly the same issue as https://github.com/opencv/cvat/issues/1216, but with a different error message.   cc @bsekachev because they implemented the last set of related fixes.

### Your Environment

**CHROME ONLY**, this does not happen on firefox.  Chrome version: Version 80.0.3987.162 (Official Build) (64-bit)

- Git hash commit (`git log -1`): 39eb9c535bbc5f61d0ce2f8c8fa26509fa98a34d
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 19.03.8, build afacb8b7f0
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem: See linked issue above.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@subdavis 

Hi, similar issue (moving between frames during resizing/dragging) has been fixed here #1370
Could you please check if it helps you?

**Comment by subdavis** [comment]
I don't think so.

``` bash
git checkout bs/batch_of_fixes
docker-compose rebuild cvat_ui
docker-compose restart
```

I shift-reloaded the browser window to double-check.

**Comment by bsekachev** [comment]
@subdavis 

I am able to reproduce issue you described without the fix above and unable to reproduce it with the fix. I haven't used ``rebuild, restart`` before and I am not sure whether they do the same what ``docker-compose up --build -d`` do.
Just in case try do ``git pull origin bs/batch_of_fixes`` before build and be sure you have the latest commit the same like in remote branch.

**Comment by subdavis** [comment]
``` bash
docker-compose up --build -d
```

This apparently did something my other command did not.  Issue fixed for me.  Thanks for the quick response!

**Comment by Octoslav** [comment]
Hi

I have encountered with this issue on the v2.21.1. I am using this command to start the server:
```
docker-compose up --build -d
```

Could you please help? @bsekachev

**Comment by bsekachev** [comment]
@Octoslav 
any steps to reproduce on v2.21.1?

**Comment by Octoslav** [comment]
@bsekachev

1) Draw a rectangle or polygon in track mode
2) Drag one of it's points. **Don't release the left mouse button**
3) Press F or D key
4) Get an error:
```
Error
Canvas is busy. Action: resize

Error: Canvas is busy. Action: resize
    at m.setup (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:2965130)
    at Ue.setup (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:3157389)
    at Kae.updateCanvas (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:9119645)
    at Kae.componentDidUpdate (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:9116194)
    at _l (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:6536406)
    at Al (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:6536092)
    at yl (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:6535636)
    at https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:6547293
    at wc (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:6547795)
    at cc (https://app.cvat.ai/assets/cvat-ui.3f8ec489bebd1c377b91.min.js:2:6541611)
    ```

**Comment by bsekachev** [comment]
Thanks, I will take a look
