### ISSUE TITLE
Dump Annotations, Pascal VOC zip, can not dump label with uppercase character? No issue with "Export as dataset, PASCAL VOC 2012"

### ISSUE THREAD

**Issue by tealeeseng** [opencv/cvat#1379]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

We Upload Pascal VOC zip successfully and try to Dump Annotations, Pascal VOC zip after annotation adjustment. During Dumping Annotations, we saw following error message:
WARNING:root:The following labels are remapped to background: Xxxxxx + Xxxxx Xxx Xxxx, Xxxxxxxx Xxxxxxx Xxxxxx, Xxxx

`[
  {
    "name": "Xxxxxx + Xxxxx Xxx Xxxx",
    "id": 31,
    "attributes": []
  },
  {
    "name": "Xxxxxxxx Xxxxxxx Xxxxxx",
    "id": 32,
    "attributes": []
  },
  {
    "name": "Xxxx",
    "id": 38,
    "attributes": []
  },
  {
    "name": "wwwwww",
    "id": 40,
    "attributes": []
  }
]`

only label wwwwww appears in dumpped annotation files.

No issue with "Export as dataset, PASCAL VOC 2012"

### Expected Behaviour

All labels to be appearred in annotation files.

### Current Behaviour

only wwwwww label appears in annotation files.

### Possible Solution

I think datumaro/datumaro/plugins/voc_format/converter.py's _make_label_id_map method having the error message.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`): commit feebec2670186f8f56f4314cb45d596d5dc13e8a (HEAD -> master, tag: v0.6.1, origin/master, origin/HEAD)
Author: Nikita Manovich <40690625+nmanovic@users.noreply.github.com>
Date:   Sat Mar 21 11:17:27 2020 +0300

    Release v0.6.1 (#1267)

- Docker version `docker version` (e.g. Docker 17.0.05): Not using docker
- Are you using Docker Swarm or Kubernetes? Nope
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
07:17:57 Result is kept for 500 seconds
INFO:rq.worker:Result is kept for 500 seconds
07:19:34 default: cvat.apps.dataset_manager.task.export_project('4', <User: admin>, 'voc', 'localhost:7000') (/api/v1/tasks/4/dataset/voc)
INFO:rq.worker:default: cvat.apps.dataset_manager.task.export_project('4', <User: admin>, 'voc', 'localhost:7000') (/api/v1/tasks/4/dataset/voc)
WARNING:root:The following labels are remapped to background: Column + Gable End Wall, Concrete Casting Bucket, Household Shelter, Parapet Wall, Precast Plank, Staircase Wall, Toilet Wall, Wall, Window Facade
[2020-04-08 07:19:43,096] INFO cvat.server.task_4: The task 'safety-loads-200' is exported as 'voc' and available for downloading for next '10:00:00'. Export cache cleaning job is enqueued, id '3cea1ac7-f344-4287-aae1-9c687b390773', start in '10:00:00'
INFO:cvat.server.task_4:The task 'safety-loads-200' is exported as 'voc' and available for downloading for next '10:00:00'. Export cache cleaning job is enqueued, id '3cea1ac7-f344-4287-aae1-9c687b390773', start in '10:00:00'
07:19:43 default: Job OK (/api/v1/tasks/4/dataset/voc)
INFO:rq.worker:default: Job OK (/api/v1/tasks/4/dataset/voc)
07:19:43 Result is kept for 36000 seconds
INFO:rq.worker:Result is kept for 36000 seconds

    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by tealeeseng** [comment]
119.xml does not have annotation though i annotated "Concrete Casting Bucket" as label.
0.xml is fine, as previously.

[safety-loads (3).zip](https://github.com/opencv/cvat/files/4502351/safety-loads.3.zip)

**Comment by tealeeseng** [comment]
Hi, 
I've git checkout -b 1.0.0-beta.1
and rebuild the docker. However, 119.xml does not have annotation though I had annotated "Concrete Casting Bucket" as a label.
0.xml is fine, as previously.

please refer attached safety-loads (5).zip for more details.

Thanks. :)

[safety-loads (5).zip](https://github.com/opencv/cvat/files/4507844/safety-loads.5.zip)

**Comment by zhiltsov-max** [comment]
`safety-loads (5).zip` looks like it was obtained without the patch, as it contains uppercase characters in `labelmap.txt`. Please make sure code is updated. I've rechecked the patch, with and without, it should work.
