### ISSUE TITLE
Change git repos paths

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#1380]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Before all tasks are stored in ``data/{tid}/*``
Now they are stored in ``data/tasks/{tid}/*`` and ``data/data/{tid}/*``.
But if I create a task with a repos, all repos data are still saved in ``data/{tid}``.
Probably we should save them somewhere else to escape confused repository structure.

**Comment by nmanovic** [comment]
@azhavoro , need to fix for beta

**Comment by nmanovic** [comment]
@azhavoro , please confirm that it was resolved.
