### ISSUE TITLE
libcpu_extension_sse4.so missing

### ISSUE THREAD

**Issue by WesleyYue** [opencv/cvat#1384]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Bug

I followed the steps [here](https://github.com/opencv/cvat/blob/master/cvat/apps/dextr_segmentation/README.md), and when I'm at the "Stop Creation" step, I get the following error:
```
Segmentation has fallen. Error: 'RuntimeError: Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libcpu_extension_sse4.so': /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libcpu_extension_sse4.so: cannot open shared object file: No such file or directory '
```

I went to `/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/` and verified that `libcpu_extension_sse4.so` indeed did not exist. Was this removed from the openvino distribution?

**Comment by WesleyYue** [comment]
Related issue: https://github.com/opencv/cvat/issues/1179

**Comment by WesleyYue** [comment]
I pulled `develop` and verified this is fixed by https://github.com/opencv/cvat/pull/1269

**Comment by M-Younus** [comment]
Got same error when using openvino '_2020 2' version_ but resolved when using openvino '_2019 r3_' version.
