### ISSUE TITLE
COCO json doesn't include directory

### ISSUE THREAD

**Issue by thomasstats** [opencv/cvat#1385]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
When retrieving annotation information for COCO, I would expect that the image name contains the folder as well.  For example if I upload a set of images in a folder for "Task 1" with subfolders "Job1" ... "Jobn" each containing images to be marked that the json would return a path with the folder.  Such as "file_name": img1.jpg "path": path/to/folder/containing/img1 or "file_path": path/to/folder/img1.jpg.

### Current Behaviour
Currently the json returns simply a filename.  So in the event that I have subfolders with conflicting filenames, it requires the end user to determine which folder it came from using some type of logic.

### Possible Solution
As mentioned above, include some kind of item in the json that allows you to see the path of the image file.

### Context
We've had to use other annotation formats and convert them to COCO ourselves.

**Comment by nmanovic** [comment]
It was fixed in develop branch: https://github.com/opencv/cvat/pull/1381
