### ISSUE TITLE
Dump Pascal attributes err!

### ISSUE THREAD

**Issue by wuchangsheng951** [opencv/cvat#1389]
![image](https://user-images.githubusercontent.com/27955693/78933139-cea6f800-7a76-11ea-9e62-84d99ac5c639.png)
************************
I want to set attributes for the label. But when I dump the annotation in pascal_VOC format. It doesn't show the default or labeled attributes. It only works in "cvat XML image" format.
************************

![image](https://user-images.githubusercontent.com/27955693/78933424-44ab5f00-7a77-11ea-86b9-3e2ae5b5cfd8.png)

**Comment by zhiltsov-max** [comment]
Hello. PASCAL VOC format does not support any attributes, except `pose` and `action`. You can use another format with attributes like CVAT XML, Datumaro and LabelMe instead.

**Comment by wuchangsheng951** [comment]
> Hello. PASCAL VOC format does not support any attributes, except `pose` and `action`. You can use another format with attributes like CVAT XML, Datumaro and LabelMe instead.
Thank you so much
