### ISSUE TITLE
Creating task with large ammount of images

### ISSUE THREAD

**Issue by 4sfaloth** [opencv/cvat#139]
I am having issues creating a task with a large ammount of images (>20k). 
I have tried creating it through the browser on the same machine hosting the server, and I get this error about "too many images" and a suggestion for using the 'shared' option (which from what I understood 
 from another issue is not functional yet?).
Then I tried creating the task through the browser on another machine (running windows); on this one it was even weirder. When I get to the file dialog to pick the images, I go to the folder where they are and "select all", after thinking for a while all the images get highlighted like they are selected but the text box with the filenames remains empty, and confirming the selection like that indeed yields 0 images.

I saw some other similar issue that stated as a fix for this to edit base.py and increase the maximum number of images and data size. I did that but it did not work (same errors as above); did I have to rebuild after editing base.py? Is there any other way to create the task?

Thanks in advance

**Comment by AhmedRefaat** [comment]
I have also another question related to the one here, and it may appears stupid, but please I need your support: 
Does the tool support uploading videos or only images ?
if supports only images, then where can I convert the video into images?
if it supports video upload, then where the main video is stored ( either video or frames ) ?
Is there a possibility to link a certain folder path to be the storage area for any video uploading process ?
Many many thanks for your support and thanks for your great effort in this tool.

**Comment by bsekachev** [comment]
@4sfaloth 
- Data uploading from share works. Please refer to share path [documentation](https://github.com/opencv/cvat#share-path).
- Of course, you need rebuild a container after editing server files. You also can edit it direct in container and just rerun it.
- I will check you issue with file uploading from windows platform later.

**Comment by bsekachev** [comment]
@AhmedRefaat
- Our tool supports video files uploading.
- The FFMPEG splits you video by frames.
- Frames are stored at path /home/django/data/<task_id>/data ...
- Original video (and any uploaded files) stored at path /home/django/data/<task_id>/.upload, but actually video files aren't used after task creating. 
- If I understand you correctly, you want mount a file share to container. In such case please refer to corresponding [documentation](https://github.com/opencv/cvat#share-path) and let me know if you will have any issues.

**Comment by AhmedRefaat** [comment]
@bsekachev 
Many thanks for your reply. 
Regarding my last question, no you got my question wrongly
I want to upload the videos to another place (Not the share folder). either external HDD or other machine on the network. Can you help me where can I edit to make such setup ?
Many thanks for your fast response.

**Comment by 4sfaloth** [comment]
@bsekachev 
Thank you for your fast reply.

I will try using data upload from share again in the future. In the meantime I've rebuilt the container after changing the maximum number of images. Now, when I try to create the task on the machine running the server (ubuntu) it no longer gives the "too many images" error, but simply nothing happends when I click 'submit'. The button goes down and then is re-enabled after a second or so and I remain on the task creation window, and it is not created

**Comment by 4sfaloth** [comment]
@bsekachev 
update: I've tried using the shared functionality (edited the docker-compose.override.yml to look like the example, just changing the paths) but there must be wrong with yhe .yml. Launching the container fails with "The compose file './docker-compose.override.yml' is invalid because: services.cvat.volumes contains and invalid type, it should be an array

**Comment by bsekachev** [comment]
@4sfaloth 
- Do you have any console exceptions after press of "submit" button? 
- Oh, you found error in documentation. 
Please replace line "cvat_share:/home/django/share:ro" to "- cvat_share:/home/django/share:ro". It will fix you issue.

**Comment by 4sfaloth** [comment]
@bsekachev thanks again for your fast replies. Below answers in the same order as your last questions:

- Indeed I do. "Failed to load resource:  net::ERR_INSUFFICIENT_RESOURCES

- Thanks a lot, that did it! I managed to create the task like that

**Comment by bsekachev** [comment]
@4sfaloth 
It looks like browser don't have enough resources in order to upload you file into memory. What is file size?

Thanks for you issue, it was helpful for us.

**Comment by bsekachev** [comment]
@AhmedRefaat

If you want upload files in the CVAT from other devices (disks, PCs etc), you can:
1) Set **volumes.cvat_share.driver_opts.device** variable to full directory path of "share" (or any other directory). Please read [documentation](https://github.com/opencv/cvat#share-path). 
2) Mount any device or remote directory into this "share" directory and browse it from CVAT client.

Did I answer on you question?

**Comment by AhmedRefaat** [comment]
@bsekachev 
Many thanks for your response, but one more small correction, I want to upload to  (not from). 
So, where can I change to change the uploading bath 
I want to upload (to) another device or machine. 
or the answer is the same. 
thanks in advance.

**Comment by bsekachev** [comment]
@AhmedRefaat 
I think you can setup cvat_data volume for this purpose. 
Just change path value in docker-compose.yml for **services.cvat.volumes.cvat_data**

**Comment by iheggo** [comment]
@bsekachev 
Do not you support working with Amazon S3 storage?

**Comment by nmanovic** [comment]
@iheggo ,

As far I know it is possible to mount Amazon S3 storage as a local drive. Thus you can use it without any problems. Just mount your storage to /mnt/mydrive and specify that cvat_data points to the directory.

**Comment by nmanovic** [comment]
It seems that the issue already collected too many questions. Let's close it for now. Don't hesitate to as questions inside our [gitter](https://gitter.im/opencv-cvat)

**Comment by ArunimaB1995** [comment]
How do we upload multiple mp4 files? I have tried zipping the folder which containes all my mp4 files and trying to upload that for creating a task. However it throws this error in my console:

INFO:     172.18.0.3:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
2023-08-30 11:41:30,343 DEBG 'uvicorn-0' stdout output:
INFO:     172.18.0.3:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

**Comment by bsekachev** [comment]
@ArunimaB1995 

https://opencv.github.io/cvat/docs/manual/basics/create-multi-tasks/
