### ISSUE TITLE
Delete point bug (in new UI)

### ISSUE THREAD

**Issue by TOsmanov** [opencv/cvat#1391]
How to reproduce:
- right-click the point
- a button for deleting appears
- do not delete the point
- right-click on another point
- a button for deleting appears
- click delete point
- the first point was deleted, although the last point had to be deleted
![bug delete point](https://user-images.githubusercontent.com/54434686/78990609-84d61480-7b3f-11ea-8799-98844dc36cd1.gif)

**Comment by nmanovic** [comment]
@TOsmanov , please check if it is fixed.

**Comment by TOsmanov** [comment]
@nmanovic , problem resolved
