### ISSUE TITLE
docker-compose down command as written in the readme does not remove volumes

### ISSUE THREAD

**Issue by joaocaldeira** [opencv/cvat#14]
The option -v needs to be added. If that is not done, the data will still be there the next time docker-compose up is run.

**Comment by joaocaldeira** [comment]
More directly, my point was that listing `docker-compose down` is inconsistent with the sentence preceding it:

> The command below will stop and remove containers, networks, volumes, and images created by `up`.

To answer your question: my use case here was that I added some videos to the tool for testing when I first installed it, and then wanted to clear all data and restart cvat before adding the videos I actually want annotated.

**Comment by nmanovic** [comment]
I see. We will update README.md file. We got the line directly from [documentation](https://docs.docker.com/compose/reference/down/) and it describes the command with all options. In our case we probably need to write "The command below will stop and remove containers and networks created by up". The sentence isn't precise (external network isn't removed) but I believe it is sufficient for the case. Will it work?

**Comment by joaocaldeira** [comment]
Yes, that sounds good. Thanks!
