### ISSUE TITLE
Setting up CVAT Analytics on multiple containers

### ISSUE THREAD

**Issue by muck27** [opencv/cvat#1402]
Hey @nmanovic 

I am creating cvat jobs with different datasets as separate containers. I have never used the analytics of cvat before and I am interested in using this feature as well. I am able to create multiple cvat containers for example (cvat_1, cvat-redis_1,cvat_db_1 ),(cvat_2,cvat_redis_2, cvat_db_2) etc. but I am unable to create multiple containers for the analytics docker service since the ports are restricted to 5600 and 5601. 

When I change the above ports, i get a 500 error when loading kibana.

Can you help me create separate containers for the analytics as well

Thank You

**Comment by nmanovic** [comment]
@muck27 , I believe it is better to discuss the question on gitter. Probably somebody from community did that. It is only guess but probably you can use different docker networks: https://docs.docker.com/compose/networking/#specify-custom-networks

**Comment by nmanovic** [comment]
I will close the issue. Please ask on gitter.
