### ISSUE TITLE
service “cvat_ui” failed to build

### ISSUE THREAD

**Issue by chaoyifei** [opencv/cvat#1407]
Build docker images by default
os:ubuntu 18.04
1、docker-compose build

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
......

ERROR:Service 'cvat_ui' failed to build:the command:'/bin/sh -c npm install'returned a nono-zero code:1

**Comment by chaoyifei** [comment]
which. failed stack: n.h9ttack.oncompleta 15:167:21) Hu UnwGunw-Standard.PC-i440F
gypverb which failed "Error:not found:python\n
gypverb fanlled at gethotFoundError
gyp verb failed （/tmp/cvat-canvas/node_modules/which/which.js:68:19）\n' modules/which/which.js:13:12)\n'
gyp verb failed at E (/tmp/cvat-canvas/node
failed /tmp/cvat-canvas/node modules/which/which.1s:89:16\n' 2886:29人n
gyp verb tanled /tmp/cvat-canvas/node modules/isexe/index.is:42:5\n
gypverb wh ich /tmp/cvat-canvas/node isexe/mode.js:8:5\n
gyp verb whichi fanled code： at FSReqCallback.oncomplete(fs.js:167:21)
gypverb wnich failed } 'ENOENT
ERR！ I
**gyp ERR! Error:Can't find Python executable·python",you can set the PYTHON**
gyp ERR!stack at PvthonFinder env variable.
failNoPython
ERRL stack at pythonFinder.canonymous (/tmp/cvat.canvas./node modules/node-gyp/lib/configure.js:496:16） modytes/node-gyp/ib/configure.js:484:19）
（/tmp/cvat-canvas/node
gYD ERR!stack at E Lhodutes/which/which.1s:68:16）
at /tmp/cvat-canvas/nodemodules/which/which modules/which/which.js:80:29】
gyp ERR!stack at /tmp/cvat-canvas/node 25:89:16
9YP ERR!stack
modules/isexe/index.s:42:5
es/isexe/mode.js:8:5
at FSReqCallback.oncomplete(fs.js:167:21)
gyp ERR!System Linux5.3.e-28-eneric
ERR!
Libsass Librarv- /usr/local/bin/node··/tmp/cvat-canvas/nodo_modules/node-gyp/bin/node-gyp.jsrebuild·...verbose·.Libnass_extae·..Libsascflaget...Libea
OVD ERR! Cwd/tmp/cvat-canvas/node_modules/node-sass
node-gyp -v V3.8.8
ERR!not ok
with error code: 1
npm WARN cvat-canvas@0.5.2 No repository field.
cvat-canvaseo.5.2scriptsl should
（node_modules/fsevents);
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platforn for fsevents@1.2.9姝wanted"os":"darin","arch:any"(current:"os":"Linux,"arch·:x643）
npm ERR! code ELIFECYCLE
nom ERR!
npm node-sas5@4.13.0 postinstall:·node scripts/build.ig
npm ERRI Exit status 1
npm ERRI Failed at the node-sa59@4.13.0.oostinstall script.
npm ERR! This is probably not a problem with npm. There io likely additional logging output above.
ERR!A complete log of thisrun found int 1.77.dehua.1oo
2020.04.15 21:10
-Standard.pC.1440FX-PIIX-1006:/opt/cvat-masterevi/root/.npm/_logs/2020-04-15728_19_35_747z·dobug.log

**Comment by kaustubhharapanahalli** [comment]
Hi how did you fix the issue?

**Comment by chaoyifei** [comment]
modify Dockerfile.ui and insert  "Run apk add python2,g++" ,

**Comment by chaoyifei** [comment]
> Hi how did you fix the issue?

modify Dockerfile.ui and insert "Run apk add python2,g++" ,

**Comment by kaustubhharapanahalli** [comment]
oh okay, thanks :)

**Comment by ErikOrjehag** [comment]
I had the same issue with v1.1

**Comment by azhavoro** [comment]
Fixed in version 1.2.0-beta https://github.com/openvinotoolkit/cvat/pull/2547
