### ISSUE TITLE
Dump Annotations in new UI not working

### ISSUE THREAD

**Issue by wr0112358** [opencv/cvat#1410]
### My actions before raising this issue
- [ ] Searched issue 1256

### Current Behaviour

Dump Annotations for all formats leads to the following error, where only path changes:
Could not dump annotations for the task 4
Error: Request failed with status code 500. "FileNotFoundError: [Errno 2] No such file or directory: '/home/django/cvat/apps/annotation/coco.py'\n"

### Possible Solution

Paths to scripts should be adapted to the change in issue 1256. 

### Steps to Reproduce (for bugs)

1. Select task
2. Actions -> Dump Annotations

### Your Environment

- Git hash commit (`git log -1`): 15299e4d7db37ec9b103f7f02f214e7d86b7d059

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@wr0112358 Hi, could you confirm that this issue is actual after `docker-compose down` and `docker-compose up -d --build`?

**Comment by wr0112358** [comment]
Thank you, I was missing the --build flag.
The image label annotations are now exported succesfully. But labels are missing in the coco JSON dump. Is this on purpose?

**Comment by nmanovic** [comment]
@wr0112358 , please ask your questions in gitter chat or create another issue with description how to reproduce.
