### ISSUE TITLE
CVAT new UI: Cancel or tune image shaking while drawing a polygon

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1413]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

An image mustn't shake while drawing any shapes.
### Current Behaviour

The left mouse button uses to draw any object and to move an image. It leads to image shaking when we draw some objects, especially polygons.
### Possible Solution

Create another mode to move an image while drawing an object. For example, it can be the mouse wheel or Ctrl+LMB 
### Steps to Reproduce (for bugs)

1. Just try to draw any polygon quickly enough

### Context
It's very uncomfortable for the concentration and for the precisely annotation. Difficult to annotate objects' boundaries.

**Comment by nmanovic** [comment]
@TOsmanov , please confirm that the problem was resolved.

**Comment by TOsmanov** [comment]
@nmanovic problem resolved.
