### ISSUE TITLE
Request frames with variable resolution

### ISSUE THREAD

**Issue by thirdeye-callum** [opencv/cvat#1417]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context
Our team have been using CVAT for the past couple of months with great success. Our workflow is roughly:
- Add new videos to a file share
- Create a new task per new video using the REST API
- Annotate
- Collate annotations by querying the REST API

However, now that our annotators are working remotely we are having some issues with image load times. We have tried a few different quick fixes out:
- Ask the annotators to open several tabs at a time so that the client gets a chance to download images ahead of time
- Use the develop branch where batch image downloads have been added
- Reduce video resolution

For us reducing video resolution seems to have the biggest impact, however, it introduces some complexity in managing our data:
- when we lower the resolution of our videos (using ffmpeg etc.) I'm concerned about potentially dropping frames and having two sets of videos that are slightly out of sync
- If we later need higher resolution images to annotate objects in the background we will have to upload additional jobs for the same videos and write scripts to pass the annotations around

### Possible Solution
A potential solution might be to implement an option in the REST API that allows you to set a desired (or maximum) resolution when requesting frames. The server would  decode, resize, and encode the image before returning it.

If this solution seems like a sensible idea, our team are happy to try take a look at it, however, it would be really helpful if we could get some suggestions on where to start (what files to look at etc.)

**Comment by nmanovic** [comment]
@thirdeye-callum , could you please try in develop uncheck the checkbox below:

![image](https://user-images.githubusercontent.com/40690625/80082507-26585f80-855d-11ea-9a32-4aa199e44090.png)

It will force to use video chunks instead of chunks with images and should resize images automatically. Please try to create a task using the option and report your experience. Is it better?

**Comment by nmanovic** [comment]
@thirdeye-callum , I will close the issue. If it is a problem, don't hesitate to re-open.
