### ISSUE TITLE
CVAT new UI: The highlighted attribute doesn't correspond to the chosen attribute

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1425]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The highlighted attribute in AAM should correspond to the chosen attribute
### Current Behaviour

Noticed that the highlighted with red attribute doesn't correspond to the chosen current attribute on the right panel:
![image](https://user-images.githubusercontent.com/45849884/79575144-02fb6380-80ca-11ea-8d7b-c01c4a691f04.png)

### Possible Solution

Fix this mismatch

### Context

It's necessary to have a visual confirmation that we work with the correct attribute.

**Comment by nmanovic** [comment]
@TOsmanov , please confirm that the problem was resolved.

**Comment by TOsmanov** [comment]
@nmanovic problem resolved.
