### ISSUE TITLE
AWS Deployment of CVAT

### ISSUE THREAD

**Issue by markl21** [opencv/cvat#1426]
Hi, I have opened an AWS instance (Ubuntu 18.04) and am trying to deploy CVAT for remote access. The build worked okay, but I cannot seem to access it from my computer. Here is my docker-compose.yml file: 

cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - cvat
      - cvat_ui
    environment:
      CVAT_HOST: 3.135.223.177
    ports:
      - "7070:80"
    volumes:
      - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

My connection times out when I try to access the server (after clearing cache). I just changed the CVAT_HOST field to my AWS public IP, and assumed that it would work. I am very new to this so any help would be appreciated!

**Comment by nmanovic** [comment]
@markl21 , 

Why did you ignore the issue template? The issue doesn't contain enough information for investigation. I will close it. But please try to use develop branch and read the tutorial: https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/AWS-Deployment-Guide.md. I hope it will help.

Also it is better to ask such kind of questions on our gitter channel and only if you don't have a reply and cannot find a solution ask here.
