### ISSUE TITLE
Possible to restrict user groups to only view/work on certain tasks

### ISSUE THREAD

**Issue by MooreJParker** [opencv/cvat#143]
I have a handful of tasks and I'm attempting to make it so certain users can only view the tasks that are relevant to them. Is this functionality there? I've gone to the admin page and seen the other permissions but none seem to suite my needs. Is this functionality there? I apologize if I'm missing something.

Thanks

**Comment by nmanovic** [comment]
@MooreJParker ,

>  I'm attempting to make it so certain users can only view the tasks that are relevant to them. Is this functionality there?

At the moment all users can see/modify all tasks. The owner of the task can also delete and update it. Admin can delete and update any task. I believe permissions management will be improved by us in the future. If you can help here don't hesitate to send us PR.

**Comment by nmanovic** [comment]
Need to have only the following set of permissions: view_task, edit_task, view_anno, edit_anno.
- User `admin` will have all these permissions
- User `owner` of a task will have all these permissions only for own tasks
- User `annotator` will have view_task, view_anno, edit_anno for all tasks which are assigned on the person
- Group `observer` will have view_task, view_anno permissions

Permissions definition:
- `view_task`: see all information about the task itself (who is owner, job links, etc...)
- `edit_task`: update and delete the task
- `view_anno`: view jobs with annotations, dump annotations for a specific task
- `edit_anno`: modify/upload annotations

**Comment by arcibiyo** [comment]
Is there a any update about this topic? How can I solve this problem that one user see other user's tasks? Thanks..
