### ISSUE TITLE
CVAT new ui: annotation uploading fails in annotation window

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#1432]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible Solution

https://github.com/opencv/cvat/blob/develop/cvat-ui/src/actions/annotation-actions.ts#L368-L390

Function is called twice in a row. It expects `history` argument, but in the first call it is not provided, so the call fails with an error, when trying to unpack an input structure. Annotations are uploaded, though.

### Steps to Reproduce (for bugs)

1. Upload annotations in the new UI

### Your Environment

- Git hash commit (`git log -1`): 70b6f0f46c3a0a16d7113e930b71a26b1b105523
- Docker version `docker version` (e.g. Docker 17.0.05): -
- Are you using Docker Swarm or Kubernetes? -
- Operating System and version (e.g. Linux, Windows, MacOS): Unubtu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@TOsmanov , please confirm that the problem was resolved.

**Comment by nmanovic** [comment]
@zhiltsov-max , please confirm as well.

**Comment by TOsmanov** [comment]
@nmanovic problem resolved.
