### ISSUE TITLE
CVAT new UI: bug in "hide" function

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1433]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The function "hide" should hide/unhide shapes 
### Current Behaviour

The "hide" function doesn't work. If you click on the corresponding icon or short key the annotated shape won't disappear. But if you grip a shape and move it somewhere it will hide. But you can't unhide it.
![2](https://user-images.githubusercontent.com/45849884/79754512-5a930c80-8320-11ea-85db-7df07e7f9171.gif)

### Steps to Reproduce (for bugs)

1. Draw a new shape
1. Press "hide" (H), try to move the shape
1. Try to unhide it

### Context

This function is necessary for lots of annotations scenarios

**Comment by nmanovic** [comment]
@TOsmanov , please confirm that the problem was resolved.

**Comment by TOsmanov** [comment]
@nmanovic problem resolved.
