### ISSUE TITLE
Custom app gets redirected to <ip>:<port>/tasks

### ISSUE THREAD

**Issue by nakceb** [opencv/cvat#1436]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)
- [X] Consulted google

I have made a custom plugin to Cvat and I have it is working fine on when the url does not contain the port number. But when the portnumber is added I get automagically redirected to <ip>:<port>8000/tasks. 
### Expected Behaviour

That I can access my app with the port number in the url without being redirected

### Current Behaviour

I get redirected to /tasks even if my url is valid to my custom app.

### Your Environment

- 59430bc  (tag: v1.0.0-alpha) Add missing information into changelog.
- Docker version 19.03.8, build afacb8b7f0
- Ubuntu 16.04

**Comment by nakceb** [comment]
I think the issue is related to me changing the port when allowing all hosts:
`version: "2.3"

services:
  cvat:
    environment:
      ALLOWED_HOSTS: '*'
    ports:
      - "80:8080"`
But it is strange since an app like documents is accessable both through 
<ip>:<port>/documentation/user_guide.html and
<ip>/documentation/user_guide.html

whilst my app is only accessable with <ip>/<my_app> and not <ip>:<port>/<my_app>

**Comment by nmanovic** [comment]
@azhavoro , could you please take a look? I believe it is a proxy server configuration.

@nakceb , could you please share more information about the plugin. What is the purpose of the plugin. Are you going to open source it?

**Comment by nakceb** [comment]
@nmanovic Hi, yes I found the issue. My problem was that I had configured cvat to port 80:8080.
Then I did not have my proxy configured for my custom app. 
Solution was to add my app in the cvat.conf.template. (I also removed the port external port for the cvat container, should not have been there in the first place)
