### ISSUE TITLE
CVAT new UI: cancel "multiple paste" results in a locked workspace

### ISSUE THREAD

**Issue by TOsmanov** [opencv/cvat#1438]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Workspace is not blocked after cancel "multiple paste".

### Current Behaviour

If you cancel the multiple paste then the workspace is blocked.

### Steps to Reproduce (for bugs)

1. Copy an object using "ctrl + c"
1. Insert an object using "ctrl+v"
1. Hold "ctrl" for multiple paste
1. Insert object (left-click)
1. Do not insert an next object but press "Esc"

**Comment by nmanovic** [comment]
@TOsmanov , please confirm that the problem was resolved.

**Comment by TOsmanov** [comment]
@nmanovic problem resolved.
