### ISSUE TITLE
CVAT new UI: The block with information about the object does not disappear if the object is locked

### ISSUE THREAD

**Issue by TOsmanov** [opencv/cvat#1439]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

If an object is blocked, a block with information about the object appears when you hover and disappears when you hover over another object. 

### Current Behaviour

If an object is locked, a block with information about the object appears when you hover over it but does not disappear when you hover over another object. Now showing a block with information at a locked object can be called accidentally and a block with information will interfere.

![info block lock bug](https://user-images.githubusercontent.com/54434686/79838351-86170500-83bb-11ea-98b7-f45cc41f9ad4.gif)

### Steps to Reproduce (for bugs)

1. Lock object
1. Place the cursor on the object
1. Information block appears
1. Hover over another object
1. The block with information about the object does not disappear

### Context

In workspace
Setting "Always show object details" - disabled

**Comment by nmanovic** [comment]
@TOsmanov , please confirm that the problem was resolved.

**Comment by TOsmanov** [comment]
@nmanovic problem resolved.
