### ISSUE TITLE
How can I deploy the web server ?

### ISSUE THREAD

**Issue by LinLidi** [opencv/cvat#144]
Hi, thanks for your hard work!
The way of open the annotation web server on localhost, but if I what to deploy it on the server so that the others can just annotate by opening the browser , how to deploy the project? need I change the code or docker configuration?

**Comment by nmanovic** [comment]
@LinLidi ,

Need just add some changes into docker-compose.override.yml. One of possible way is to create such annotation server on AWS. Please read [AWS deployment guide](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/AWS-Deployment-Guide.md). Don't hesitate to ask additional questions.

**Comment by LinLidi** [comment]
Hi, @nmanovic ,
Thanks for your detailed answers, and now I have got it.it's a perfect and convenient tool to annotate.
best wishes.

**Comment by Dante-coder** [comment]
Hi, is there any installation guide on how to deploy cvat on digital ocean?

**Comment by nmanovic** [comment]
@Dante-coder , we don't have a such guide. Feel free to contribute.
