### ISSUE TITLE
CVAT new UI: change shapes' colors with a shortcut

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1442]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Need to have an option to change shapes' colors.
### Current Behaviour

No opportunity to change the color for a drawn shape
### Possible Solution

Add an option to change a color into the objects' context menu + hotkey Enter

**Comment by bsekachev** [comment]
Also we should have done neighbor colors in available set as different as possible
