### ISSUE TITLE
CVAT new UI: Filter property "shape" and operator "~="

### ISSUE THREAD

**Issue by TOsmanov** [opencv/cvat#1444]
In the new UI, it’s not clear how to use a filter with the "shape" property, 
I tried the filter "shape == polygon" and the like, but they just hide all the objects.
And also I did not understand in what cases to use the operator "~ =", for example, applying the filter "width ~ = 100" causes an error:

![image](https://user-images.githubusercontent.com/54434686/79868029-fcc9f780-83e7-11ea-8ccf-caa442803e52.png)

**Comment by nmanovic** [comment]
@TOsmanov , please confirm that the problem is resolved.

**Comment by bsekachev** [comment]
@TOsmanov 
Right filter for shape type is ``shape == "polygon"``. We've also added the example to CVAT.

**Comment by TOsmanov** [comment]
@nmanovic Problem resolved
@bsekachev Thanks, and the operator "~ =" will not be used?

**Comment by bsekachev** [comment]
@TOsmanov 
There were two issues with this operator. First right operator is ``=~``, not ``~=``
Second is that operator allows to use regular expressions (according to specification), but technically a library that we use doesn't support this operator.
So, I've just removed it from CVAT.

**Comment by TOsmanov** [comment]
@bsekachev ok thanks
