### ISSUE TITLE
I cannot annotate using cvat

### ISSUE THREAD

**Issue by AhmedRefaat** [opencv/cvat#146]
Hello All, 
Many thanks for your great work. 
I tried to install the CVAT without docker. The cvat is working but when creating a task. the Job doesn't have a link and I can not annotate. 
Kindly find the attached log file. 
[cvat_server.log](https://github.com/opencv/cvat/files/2499532/cvat_server.log)

**Comment by alalek** [comment]
> without docker

Not supported. Not tested.
Don't expect any help with digging into custom configuration of your machine.

**Comment by bsekachev** [comment]
@AhmedRefaat 
I suppose you don't start RQ workers. Visual Studio Code should start it in the "CVAT Debugging" configuration if you used [this](https://github.com/opencv/cvat/blob/develop/CONTRIBUTING.md#development-environment) manual. 
![screenshot from 2018-10-22 10-37-10](https://user-images.githubusercontent.com/40690378/47282095-9a235000-d5e6-11e8-9c70-ebdb68058b5f.png)

**Comment by nmanovic** [comment]
Hi @AhmedRefaat ,

As alalek wrote we don't support running CVAT without docker. In your particular case there is most common reason why a task can not be created. Please check that `CVAT RQ - default` is run. It is a separate process which does tasks from `default` ls

**Comment by AhmedRefaat** [comment]
@bsekachev 
many thanks for your answer, yes it works as you mentioned
however, I have another problem, I found that the video which I tried to use in task creation is uploaded in data/<task_id>/.upload however the data/<task_id>/data directory is empty, and consequently, there is no job link and I can not annotate. 
Attached a task log file as example. 
again, many thanks for your effort and reply
[task.log](https://github.com/opencv/cvat/files/2503300/task.log)

**Comment by nmanovic** [comment]
@AhmedRefaat ,

>  Executable 'ffmpeg' not found

You need to install ffmpeg

**Comment by nmanovic** [comment]
Hi @AhmedRefaat ,

Let me know if you still questions. I will suggest asking next questions inside our [gitter](https://gitter.im/opencv-cvat). I will close the issue for now. Thanks for your questions. We are always ready to help you.
