### ISSUE TITLE
Can't label an entire image (simple image classification)

### ISSUE THREAD

**Issue by HeziL1** [opencv/cvat#1465]
I am trying to use CVAT for image classification without any bonding boxes but rather only pure image labeling. 
is it possible?

**Comment by nmanovic** [comment]
@HeziL1 , it is possible in new UI. Basic functionality was added (so call `tags`). Please ask such kind of questions on our gitter channel next time and don't ignore our template when submit an issue. 

I will close the issue. Don't hesitate to reopen it if you have a feature request or want to propose some changes.

**Comment by bhavya-goyal-22** [comment]
@HeziL1 For the classification task, I propose restricting the tag to one image only. I’m planning to work on implementing this change and contribute. Please let me know what you think!.
