### ISSUE TITLE
Cuboid annotation

### ISSUE THREAD

**Issue by NcJie** [opencv/cvat#147]
Application like 3d pose estimation of a given object would be beneficial. 
Is the cuboid / 3d bounding box annotation feature in the roadmap?

**Comment by nmanovic** [comment]
Hi @NcJie ,

Thanks for your proposal. At the moment it isn't planned yet. But I agree that the feature should be implemented in the future. Let's add it as backlog.

**Comment by bsekachev** [comment]
Example:
![image](https://user-images.githubusercontent.com/40690378/50345029-8fc9f780-053e-11e9-9d00-2e66ed1d64de.png)

**Comment by jeannotes** [comment]
@bsekachev is cuboid annotation done now?

**Comment by bsekachev** [comment]
I suppose it was resolved with #678
