### ISSUE TITLE
Can't save annotation for CVAT

### ISSUE THREAD

**Issue by hidari358** [opencv/cvat#1471]
Hi, does anyone know why I got this error when trying to save the annotation?
This is the error:
Error: Request failed with status code 400. "duplicate key value violates unique constraint \"engine_trackedshape_pkey\"\nDETAIL: Key (id)=(154) already exists.\n".

**Comment by nmanovic** [comment]
@hidari358 ,

I will close the issue because the issue template was ignored and you didn't provide enough details to answer on your question. Please don't hesitate to ask the question on gitter or provide enough details here.
