### ISSUE TITLE
CVAT failed to build

### ISSUE THREAD

**Issue by ChunKhai** [opencv/cvat#1473]
I`m following the instruction on this link to install CVAT on Ubuntu 18.04.3.
https://github.com/opencv/cvat/blob/master/cvat/apps/documentation/installation.md

When I trying to execute this command " docker-compose build ", the build process begins, however, in the end, I got this error message, 
" Service "cvat" failed to build: Error processing tar file(exit status 2): fatal error: slice bounds out of range

May I know what is the issue and how can I fix it?

**Comment by azhavoro** [comment]
@ChunKhai 

I will close the issue because the issue template was ignored and you didn't provide enough details to answer your question. Please don't hesitate to ask the question on gitter or provide enough details here.

**Comment by ChunKhai** [comment]
Hi 

I`m trying to install CVAT in a virtual environment. I have created Ubuntu 18.04 using Oracle on my Windows 10 OS.

Below is part of the message when I`m executing the "docker-compose build" command:
I have tried many times and every time failed here. 

Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from kiwisolver>=1.0.1->matplotlib==3.0.3->-r /tmp/requirements/base.txt (line 40)) (46.1.3)
Collecting decorator>=4.3.0
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting smmap<4,>=3.0.1
  Downloading smmap-3.0.2-py2.py3-none-any.whl (25 kB)
Collecting defusedxml
  Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow==1.15.2 from https://files.pythonhosted.org/packages/21/2f/d42c859df2de1b6d0431736a7cf1ebd82594c2da8bf315187a7fa00b1cf2/tensorflow-1.15.2-cp35-cp35m-manylinux2010_x86_64.whl#sha256=613072266dd60986b79e517f9e4a5f5d7c8495faeb439808db9a493ec3bebf96 (from -r /tmp/requirements/base.txt (line 42)):
        Expected sha256 613072266dd60986b79e517f9e4a5f5d7c8495faeb439808db9a493ec3bebf96
             Got        4b645ab8802c70b605b4fc78e6123d4f2d99f520797ed201b479daf9673542a9

WARNING: You are using pip version 20.0.1; however, version 20.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c python3 -m pip install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt' returned a non-zero code: 1
tan@tan-VirtualBox:~/cvat$
