### ISSUE TITLE
How to dump annotations for current frame only?

### ISSUE THREAD

**Issue by M-Younus** [opencv/cvat#1481]

**Comment by zhiltsov-max** [comment]
There is no way to do this from UI. You can try to export as Datumaro dataset and then filter only the desired frames.

**Comment by nmanovic** [comment]
@M-Younus , what is your use case? Why do you need the annotations only for one frame?

**Comment by M-Younus** [comment]
> @M-Younus , what is your use case? Why do you need the annotations only for one frame?

Actually I am doing annotations for segmentation, just for checking I've to dump then check if segmentation is precized or not..so that's why I wanna export just current frame.
Yes it is very rare use case.

**Comment by nmanovic** [comment]
@M-Younus , I will close the issue in the case. It isn't possible now. If you think it can be useful for many users, don't hesitate to create a feature request.
