### ISSUE TITLE
Feature request: get objects after they have been created

### ISSUE THREAD

**Issue by frndmg** [opencv/cvat#1486]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am trying to create a set of points and group them using the reducers `createAnnotationsAsync` and `groupAnnotationsAsync` in the following way:

```ts
onCreateAnnotationsAndGrouping(sessionInstance: any, frame: number, states: any[]): Promise<void> {
    return dispatch(createAnnotationsAsync(sessionInstance, frame, states))
       .then(() => dispatch(groupAnnotationsAsync(sessionInstance, frame, states)))
}
```

When executing `groupAnnotationsAsync` the following error is displayed:
```error
Error: The object has not been saved yet. Call annotations.put([state]) before
```

I have tried setting a timeout before grouping takes place but the same error appears.

The grouping tool works well when I do it by hand.

### Expected Behaviour

It should group the points and do not throw any errors.

### Current Behaviour

An error is thrown and no grouping occurs.

### Possible Solution

I think it should be a bug on the `cavt-core` API that is causing this. But I can't be sure.

### Steps to Reproduce (for bugs)

The code is already shown.

### Context

I am trying to develop a way to annotate human pose using keypoints. Right now the approach can lead to pitfalls because you are not forced or encouraged to use correct labels in your annotation process. For now, I just want to programmatically add this points and group them in order to have a template for the human figure.

Eventually, I would like to add a template designer and create a model on the backend side.

It will be good to create a new shape that assembles these graph structures as well.

### Your Environment

- Git hash commit (`git log -1`): 81a13cb
- Docker version `docker version` (e.g. Docker 17.0.05): Not using docker for the development environment but, `18.09.5`
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows,): `uname -srvo`: `Linux 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 GNU/Linux`

### Next steps

I already asked this question on Gitter

**Comment by frndmg** [comment]
You can try this https://github.com/signatrix/cvat/tree/0c85aa1fc2ddfafafc1ff82b2e2753f44c726da6

**Comment by bsekachev** [comment]
@frndmg 

In your example you pass ``states`` to ``groupAnnotationsAsync`` that weren't saved in collection (message is about it). It's wrong using of cvat-core API.

Calling of  ``job.annotations.put(states)`` (inside createAnnotationsAsync) returns states saved in collection. You should group them instead of.

**Comment by frndmg** [comment]
@bsekachev

Thanks a lot!

I created a new reducer on `annotation-actions.ts`. I was not sure how to get the new states out of the `createAnnotationsAsync`.

**Comment by bsekachev** [comment]
Theoretically you can get the latest data from the redux storage after ``createAnnotationsAsync`` was executed. 
But creating a new action and a reducer (as you suggested) is better way I think.

**Comment by frndmg** [comment]
How could I retrieve the points I just added? @bsekachev

**Comment by bsekachev** [comment]
@frndmg 

For example something like:
```
const state: CombinedState = getStore().getState();
const { states } = state.annotation.annotations;
```

**Comment by bsekachev** [comment]
@frndmg 

Hmm..
I've just checked how it is possible and I haven't found nice way to do it.
The best option would be to return some information about added objects from ``annotations.put`` I suppose. For that we need to update API of ``cvat-core``.

**Comment by bsekachev** [comment]
@frndmg 

With the PR above you can do something like:
```
const ids = await session.annotations.put(...);
const reduxState: CombinedState = getStore().getState();
const objectsJustAdded = reduxState.annotation.annotations.states.filter((state) => ids.includes(state.clientID));
```

**Comment by frndmg** [comment]
I see. This requires fewer changes than I was doing.

I assume it should be `allObjects` on the last line.

I will add that peace of code until the PR is merged, thanks!

**Comment by bsekachev** [comment]
> I assume it should be allObjects on the last line.

Sure. 
Not at all
