### ISSUE TITLE
cvat container RESTAPI doesn't work after abnormal termination

### ISSUE THREAD

**Issue by smartnet-club** [opencv/cvat#1487]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Unable to login cvat user interface after abnormal computer termination .

### Expected Behaviour

After abnormal computer termination all services should restarted correctly.

### Current Behaviour

cvat RESTAPI is inaccessible after abnormal computer termination

### Possible Solution

The problem is in cvat container. After crash PID files not deleted.
1. /tmp/mod_wsgi-localhost:8080:1000/httpd.pid
1. /tmp/supervisord/supervisord.pid

### Steps to Reproduce (for bugs)

1. Hard reset computer

### To fix
1. Remove all *.pid on cvat contained start

**Comment by nmanovic** [comment]
@smartnet-club , it was fixed in beta.2. Could you please check? I will close the issue. Don't hesitate to reopen it if it isn't fixed in beta.2 and develop branch.
