### ISSUE TITLE
How to retrieve non-annotated images from CVAT?

### ISSUE THREAD

**Issue by Ahmad-Omar-Ahsan** [opencv/cvat#1488]
Hello everyone, 
Normally exporting images from CVAT includes only annotated images. I came across an issue that said how you can export such images using Datumaro #525 . However I don't know how I can export images using datumaro.  How can I export all images using datumaro

**Comment by zhiltsov-max** [comment]
Hi, have you tried to export task as a dataset?

**Comment by Ahmad-Omar-Ahsan** [comment]
Yes I did export annotations as CVAT annotations

**Comment by zhiltsov-max** [comment]
I'm speaking about the button "Export task as a dataset". Please try it.

**Comment by Ahmad-Omar-Ahsan** [comment]
As the problem is solved in #1494 I am closing this issue
