### ISSUE TITLE
Request for High level details to implement brush&erase functionality 

### ISSUE THREAD

**Issue by juanmed** [opencv/cvat#1492]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context

I am looking for details to implement [Brush](https://medium.com/labelbox/introducing-best-in-class-image-annotation-tools-for-computer-vision-applications-de5da8931d6e) and [erase](https://www.youtube.com/watch?time_continue=17&v=hovPoMywJOY&feature=emb_logo) functionality to create segmentation masks (At this moment I am not looking into watershed, superpixel etc implementation). This would ease creation of segmentation masks for very irregular objects appearing in  aerial view images, microscope images, medical image segmentation. Some other functionality might require it as well, #606 #772. It seems to be also part of the project `Integration of OpenCV.js tools` [here](https://github.com/opencv/cvat/projects/12). 

I am not a web developer (i.e. have no javascript experience, but python,c,c++), but are interested in looking into this as my time allows. My request is project admins' thoughts, specific details and advice on implementing brush&erase functionality.
 
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@bsekachev , could you please share your ideas?

From my perspective I will recommend to prototype the feature in UI only. Let's add these tools and convert to polygons internally. You need to convert masks to polygons only when somebody saves annotations.

Read https://github.com/opencv/cvat/blob/develop/CONTRIBUTING.md guide. Unfortunately in this case you need to implement the whole feature in js/ts/css.

**Comment by bsekachev** [comment]
@juanmed @nmanovic 

Hi, 
Implementing only brush and erase in JS client is easy and it doesn't require using OpenCV.
Simple example of brush can be found [here](https://codepen.io/kangax/pen/nadDx). As you can see, only 20 lines of code. Of course it's very simplified version, but I do not see any difficulties to implement a full version. It's a question of time only. 

The main problem I see is actually converting client masks to polygons and back. I expect to came across "underwater rocks" here. And I am not sure, that implementing the feature on client only is a right way. 

Now we have buttons "add rectangle", "add polygon", etc. I would suggest to add button "add mask" and consider this mask as an object, just drawn with a brush. So, a user presses the button, selects a label and starts drawing, being able to switch between brush/eraser and to choose a brush/eraser size. 

One more important task here is to be able assignee mapping between labels and colors. It is important not only for masks actually. I don't expect it is difficult. Just to add a field to database and change label constructor (add a [color picker](https://casesandberg.github.io/react-color/))

Later we can add advanced features like watershead from OpenCV.

I am not sure if you need to be acquainted with technical details of implementation right now. Let me know if you need.

**Comment by juanmed** [comment]
Hi, thanks for your comments and ideas. I do not need technical details right now, I first need to get familiarized with the code. I will let you know here. In the meantime I will close the issue.

**Comment by tgorovici** [comment]
Hi I would love to be able to use this feature as well. Was this project completed already? @juanmed

**Comment by juanmed** [comment]
@tgorovici  unfortunately I don't have the abilities to do it nor the time to learn them. Sorry.
