### ISSUE TITLE
Swagger document and Django Rest API's not working as expected 

### ISSUE THREAD

**Issue by gururajdori** [opencv/cvat#1495]
### Pulled CVAT with commit ID of 011c4aa675381e12a45a7be35d02464f7d6ead8c
```
    commit 011c4aa675381e12a45a7be35d02464f7d6ead8c (HEAD, tag: v1.0.0-beta.2, 
    origin/release-1.0.0)
    Author: Nikita Manovich <nikita.manovich@intel.com>
    Date:   Thu Apr 30 22:09:28 2020 +0300

    Update changelog.
```

### Built Docker and brought up CVAT services 
```
    sudo docker-compose up --build -d
```

### Created superuser of Django
```
    sudo docker exec -it cvat bash -ic 'python3 manage.py createsuperuser'
```

But I'm not able to access swagger documents. I tried with [http://localhost:8080/api/swagger/](url) but the browser is redirecting me to [http://localhost:3000](url)

However, I got the OpenAPI document at [http://localhost:8080/api/docs](url)

**I started using API as specified in the document - Following is my python script** 
```
import requests

url = "http://localhost:8080/api/v1/auth/login"

payload = "{\n    \"password\": \"test123\",\n    \"username\": \"gururaj\",\n    \"email\": \"gururaj@dori.ai\"\n}"
headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Basic Og==',
  'Content-Type': 'text/plain',
  'Cookie': 'csrftoken=KQuMhzzvtU7Zv1o9EqxfBhAxNzKSrXPFLe7NF0DKmd50IS5XnvyaYetz9f8lx2ZT'
}

response = requests.request("POST", url, headers=headers, data = payload)

print(response.text.encode('utf8'))

```

**API Response** 

```
{
    "detail": "Invalid username/password."
}
```

Somewhat I had a doubt about superuser(Admin) is not a CVAT user. So I logged into Django Admin and made changes to the user group by adding the user to annotator, observer, user, and admin
<img width="1109" alt="Screen Shot 2020-05-06 at 1 27 57 AM" src="https://user-images.githubusercontent.com/39483762/81110816-b45b1f80-8f39-11ea-8d36-a97ce7168999.png">

Something wrong in the steps I'm doing or should it be fixed in the next release? 
@nmanovic

**Comment by gururajjeerge** [comment]
@nmanovic drf-yasg is expected to serve on Allowed_hosts.
Update ALLOWED_HOSTS to IP of Host machine in the docker-compose.yml file 

Creating a pull request shortly to update instructions in README.md file

**Comment by nmanovic** [comment]
@gururajdori , I will close the issue. It seems you have found a solution and send us PR. Don't hesitate to reopen the issue if it isn't fixed yet.
