### ISSUE TITLE
Failed to create new task

### ISSUE THREAD

**Issue by smartnet-club** [opencv/cvat#1496]
Failed to create new task

### Expected Behaviour

Task created successfully.

### Current Behaviour

Error: Request failed with status code 400. {"image_quality":["This field is required."]}.

### Steps to Reproduce (for bugs)

1. Open Create new task form
1. Set Image Quality and other attributes
1. Submit

### Your Environment

- Git hash commit (`git log -1`): commit 011c4aa675381e12a45a7be35d02464f7d6ead8c (HEAD, tag: v1.0.0-beta.2, origin/release-1.0.0)
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.8
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>
cvat          | 2020-05-06 06:48:28,074 DEBG 'runserver' stderr output:
cvat          | [Wed May 06 06:48:28.073993 2020] [wsgi:error] [pid 243:tid 140507370841856] [remote 172.22.0.6:40402] [2020-05-06 06:48:28,073] WARNING django.request: Bad Request: /api/v1/tasks/12/data
cvat          | 
cvat          | 2020-05-06 06:48:28,074 DEBG 'runserver' stderr output:
cvat          | [Wed May 06 06:48:28.074083 2020] [wsgi:error] [pid 243:tid 140507370841856] [remote 172.22.0.6:40402] WARNING:django.request:Bad Request: /api/v1/tasks/12/data
cvat          | 
cvat_proxy    | 213.59.158.96 - - [06/May/2020:06:48:28 +0000] "POST /api/v1/tasks/12/data HTTP/1.1" 400 45 "http://cashcloud.no-ip.org:8080/tasks/create" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
cvat_proxy    | 213.59.158.96 - - [06/May/2020:06:48:28 +0000] "DELETE /api/v1/tasks/12 HTTP/1.1" 204 0 "http://cashcloud.no-ip.org:8080/tasks/create" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by smartnet-club** [comment]
Request payload:

**Comment by azhavoro** [comment]
@smartnet-club Hi, looks you posted payload form request at `api/v1/tasks` endpoint and it should not contain image quality parameter. What is payload of `api/v1/tasks/<task_id>/data` request?
Could you clear browser cache and try again?

**Comment by smartnet-club** [comment]
works! thanks!
