### ISSUE TITLE
Add message in UI when raw labels are wrong

### ISSUE THREAD

**Issue by smartnet-club** [opencv/cvat#1498]
While creating new task, Raw label field doesn't work.

### Expected Behaviour

Labels created by Raw field

### Current Behaviour

Pressing Done, labels appear in Constructor field, but on Submit the error:
Could not create a task
A task must contain at least one label 

### Steps to Reproduce (for bugs)

1. Open new task page.
1. Fill Raw field by label json and press Done
1. Fill other task fields
1. Pres Submit

### Your Environment

- Git hash commit (`git log -1`): commit 011c4aa (HEAD, tag: v1.0.0-beta.2, origin/release-1.0.0)
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@smartnet-club 

Could not reproduce the issue. Could you please provide labels specification you used?

**Comment by smartnet-club** [comment]
`[
    {
        "name": "Hand",
        "attributes": []
    },
    {
        "name": "Person",
        "attributes": []
    },
    {
        "name": "Refrigerator",
        "attributes": []
    },
    {
        "name": "Door",
        "attributes": []
    },
    {
        "name": "7790895000829",
        "attributes": [
            {
                "name": "color",
                "type": "radio",
                "mutable": false,
                "values": [
                    "green"
                ]
            },
            {
                "name": "name",
                "type": "text",
                "mutable": false,
                "values": [
                    "sprite bottle"
                ]
            }
        ]
    },
    {
        "name": "7790895000782",
        "attributes": [
            {
                "name": "color",
                "type": "radio",
                "mutable": false,
                "values": [
                    "black"
                ]
            },
            {
                "name": "name",
                "type": "text",
                "mutable": false,
                "values": [
                    "coke bottle"
                ]
            }
        ]
    }
]`

**Comment by bsekachev** [comment]
@smartnet-club 

Please change all ``type`` to ``input_type`` (Related #1284)
But nevertheless we should add a message if specification is wrong.

**Comment by smartnet-club** [comment]
Thanks!

**Comment by bsekachev** [comment]
Let's leave the issue opened till we have added a warning in UI
