### ISSUE TITLE
All checkboxes in temporary attributes are checked when reopening job after saving the job

### ISSUE THREAD

**Issue by yalshamy** [opencv/cvat#15]
All checkboxes in temporary attributes are checked when reopening job after saving the job although when dumping the annotation, the file downloaded is correct which contain the attributes I checked it only not all of them.

![selection_079](https://user-images.githubusercontent.com/21217765/43190248-29315172-902b-11e8-941d-8b7cde97b39a.png)
![selection_078](https://user-images.githubusercontent.com/21217765/43387018-e24010e6-9417-11e8-8a04-6506222d096f.png)

**Comment by nmanovic** [comment]
@yalshamy ,

Thank you for you report. Could you please specify labels with attributes which you specify for the task (you can modify names if it is necessary)? There are two ways to get them: using "Update Task" button in dashboard, in the annotation file there is "meta" section with the information.

**Comment by yalshamy** [comment]
HUMAN ~checkbox=Full:False ~checkbox=upper:False ~checkbox=Sideview:False ~checkbox=Frontview:False ~checkbox=Backview:False ~checkbox=MotionBlur:False ~checkbox=Reflection:False ~checkbox=Silhouette:False ~checkbox=Bad:False ~checkbox=Poster:False

**Comment by yalshamy** [comment]
Our meta is : <meta>
	<task>
	    <id>4</id>
	    <name>VID6</name>
	    <size>1480</size>
	    <mode>interpolation</mode>
	    <overlap>5</overlap>
	    <bugtracker/>
	    <created>2018-07-22 17:25:08.764504+03:00</created>
	    <updated>2018-07-26 09:51:57.182471+03:00</updated>
	    <labels>
	        <label>
	            <name>HUMAN</name>
	            <attributes>
	                <attribute>~checkbox=Sideview:False</attribute>
	                <attribute>~checkbox=Bad:False</attribute>
	                <attribute>~checkbox=Reflection:False</attribute>
	                <attribute>~checkbox=Poster:False</attribute>
	                <attribute>~checkbox=upper:False</attribute>
	                <attribute>~checkbox=MotionBlur:False</attribute>
	                <attribute>~checkbox=Frontview:False</attribute>
	                <attribute>~checkbox=Full:False</attribute>
	                <attribute>~checkbox=Backview:False</attribute>
	                <attribute>~checkbox=Silhouette:False</attribute>
	            </attributes>
	        </label>
	    </labels>
	    <segments>
	        <segment>
	            <id>4</id>
	            <start>0</start>
	            <stop>1479</stop>
	        </segment>
	    </segments>
	</task>
	<dumped>2018-07-26> 11:03:21.478817+03:00</dumped>
</meta>

**Comment by yalshamy** [comment]
our meta 
`<meta>
	<task>
	    <id>4</id>
	    <name>VID6</name>
	    <size>1480</size>
	    <mode>interpolation</mode>
	    <overlap>5</overlap>
	    <bugtracker/>
	    <created>2018-07-22 17:25:08.764504+03:00</created>
	    <updated>2018-07-26 09:51:57.182471+03:00</updated>
	    <labels>
	        <label>
	            <name>HUMAN</name>
	            <attributes>
	                <attribute>~checkbox=Sideview:False</attribute>
	                <attribute>~checkbox=Bad:False</attribute>
	                <attribute>~checkbox=Reflection:False</attribute>
	                <attribute>~checkbox=Poster:False</attribute>
	                <attribute>~checkbox=upper:False</attribute>
	                <attribute>~checkbox=MotionBlur:False</attribute>
	                <attribute>~checkbox=Frontview:False</attribute>
	                <attribute>~checkbox=Full:False</attribute>
	                <attribute>~checkbox=Backview:False</attribute>
	                <attribute>~checkbox=Silhouette:False</attribute>
	            </attributes>
	        </label>
	    </labels>
	    <segments>
	        <segment>
	            <id>4</id>
	            <start>0</start>
	            <stop>1479</stop>
	        </segment>
	    </segments>
	</task>
	<dumped>2018-07-26> 11:03:21.478817+03:00</dumped>
</meta>`

**Comment by yalshamy** [comment]
our meta is 

![selection_074](https://user-images.githubusercontent.com/21217765/43249789-402b1fa2-90ee-11e8-9255-52891e28c00b.png)

**Comment by yalshamy** [comment]
I fixed this issue when I replace False to false  on all attributes

**Comment by nmanovic** [comment]
Hi @yalshamy ,

In any case it is a problem. It should be handled correctly.
