### ISSUE TITLE
Confusion about client_id

### ISSUE THREAD

**Issue by ShihJenYu** [opencv/cvat#150]
If users get the job at the same time, will the client_id be repeated when the new shape is saved?

thanks,

**Comment by nmanovic** [comment]
@ShihJenYu ,

I'm not sure that I understand your question completely. Could you please elaborate a little bit?

**Comment by nmanovic** [comment]
Also I suggest moving the discussion to https://gitter.im/opencv-cvat.

**Comment by nmanovic** [comment]
Discussed on gitter.
