### ISSUE TITLE
How to get segment-wise video annotation without tracking box ?

### ISSUE THREAD

**Issue by Solayman-Emon** [opencv/cvat#1505]
I wanted to get segment-wise video annotation for video summarization work. The video should be chopped into around 2-3 seconds segments. I need annotation for those segments as giving scoring them, so I need not any tracking box of CVAT. How can I get this in CVAT ? Can anyone suggest me ? Thanks in advance.

**Comment by azhavoro** [comment]
Hi, I suppose you can use `tag` in this case (develop branch) https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#types-of-shapes-basics
Please use gitter for such questions in the future.
