### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by ravi7299** [opencv/cvat#1506]
docker-compose build
cvat_db uses an image, skipping
cvat_redis uses an image, skipping
cvat_proxy uses an image, skipping
Building cvat
Step 1/53 : FROM ubuntu:16.04
 ---> 005d2078bdfa
Step 2/53 : ARG http_proxy
 ---> Using cache
 ---> 59fe147ddd21
Step 3/53 : ARG https_proxy
 ---> Using cache
 ---> 1fb2a5db7884
Step 4/53 : ARG no_proxy
 ---> Using cache
 ---> 0c013dd186bf
Step 5/53 : ARG socks_proxy
 ---> Using cache
 ---> c0200e45fcdc
Step 6/53 : ARG TZ
 ---> Using cache
 ---> 690f908145bf
Step 7/53 : ENV TERM=xterm     http_proxy=${http_proxy}       https_proxy=${https_proxy}     no_proxy=${no_proxy}     socks_proxy=${socks_proxy}     LANG='C.UTF-8'      LC_ALL='C.UTF-8'     TZ=${TZ}
 ---> Using cache
 ---> 08c0548f6cc3
Step 8/53 : ARG USER
 ---> Using cache
 ---> 39d91e1cb4bc
Step 9/53 : ARG DJANGO_CONFIGURATION
 ---> Using cache
 ---> 6a07372df684
Step 10/53 : ENV DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}
 ---> Using cache
 ---> 42cce9927047
Step 11/53 : RUN apt-get update &&     apt-get install -yq         software-properties-common &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         tzdata         p7zip-full         git         ssh         poppler-utils         curl &&     curl https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash &&     apt-get install -y git-lfs && git lfs install &&     if [ -z ${socks_proxy} ]; then         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30\"" >> ${HOME}/.bashrc;     else         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ProxyCommand='nc -X 5 -x ${socks_proxy} %h %p'\"" >> ${HOME}/.bashrc;     fi &&     python3 -m pip install --no-cache-dir -U pip==20.0.1 setuptools &&     ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime &&     dpkg-reconfigure -f noninteractive tzdata &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 0365d02cc5a1
Step 12/53 : ENV USER=${USER}
 ---> Using cache
 ---> 89a7d8b6a58d
Step 13/53 : ENV HOME /home/${USER}
 ---> Using cache
 ---> e317e3e6a1ac
Step 14/53 : WORKDIR ${HOME}
 ---> Using cache
 ---> 07e03cd4e449
Step 15/53 : RUN adduser --shell /bin/bash --disabled-password --gecos "" ${USER}
 ---> Using cache
 ---> 49f0199890da
Step 16/53 : COPY components /tmp/components
 ---> Using cache
 ---> c53346bf1167
Step 17/53 : ARG OPENVINO_TOOLKIT
 ---> Using cache
 ---> 426863b55dc0
Step 18/53 : ENV OPENVINO_TOOLKIT=${OPENVINO_TOOLKIT}
 ---> Using cache
 ---> a0e9e08be3a3
Step 19/53 : ENV REID_MODEL_DIR=${HOME}/reid
 ---> Using cache
 ---> 6220a0c411e2
Step 20/53 : RUN if [ "$OPENVINO_TOOLKIT" = "yes" ]; then         /tmp/components/openvino/install.sh &&         mkdir ${REID_MODEL_DIR} &&         curl https://download.01.org/openvinotoolkit/2018_R5/open_model_zoo/person-reidentification-retail-0079/FP32/person-reidentification-retail-0079.xml -o reid/reid.xml &&         curl https://download.01.org/openvinotoolkit/2018_R5/open_model_zoo/person-reidentification-retail-0079/FP32/person-reidentification-retail-0079.bin -o reid/reid.bin;     fi
 ---> Using cache
 ---> 3895c1114c8c
Step 21/53 : ARG TF_ANNOTATION
 ---> Using cache
 ---> aec8e7964a8b
Step 22/53 : ENV TF_ANNOTATION=${TF_ANNOTATION}
 ---> Using cache
 ---> 3d1caf71323d
Step 23/53 : ENV TF_ANNOTATION_MODEL_PATH=${HOME}/rcnn/inference_graph
 ---> Using cache
 ---> a509d8c0d6d3
Step 24/53 : RUN if [ "$TF_ANNOTATION" = "yes" ]; then         bash -i /tmp/components/tf_annotation/install.sh;     fi
 ---> Using cache
 ---> ccc37c8b6a45
Step 25/53 : ARG AUTO_SEGMENTATION
 ---> Using cache
 ---> 2095770d5d05
Step 26/53 : ENV AUTO_SEGMENTATION=${AUTO_SEGMENTATION}
 ---> Using cache
 ---> 20cd04a6e0ce
Step 27/53 : ENV AUTO_SEGMENTATION_PATH=${HOME}/Mask_RCNN
 ---> Using cache
 ---> be3300c7993d
Step 28/53 : RUN if [ "$AUTO_SEGMENTATION" = "yes" ]; then     bash -i /tmp/components/auto_segmentation/install.sh;     fi
 ---> Using cache
 ---> fb016f60d729
Step 29/53 : COPY cvat/requirements/ /tmp/requirements/
 ---> Using cache
 ---> ac2de266d418
Step 30/53 : COPY supervisord.conf mod_wsgi.conf wait-for-it.sh manage.py ${HOME}/
 ---> Using cache
 ---> 734ca853910d
Step 31/53 : RUN python3 -m pip install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt
 ---> Using cache
 ---> 421a96120641
Step 32/53 : RUN python3 -m pip install --no-cache-dir pycocotools==2.0.0
 ---> Using cache
 ---> 17105bb400b1
Step 33/53 : ARG CUDA_SUPPORT
 ---> Using cache
 ---> 99090d06c6d3
Step 34/53 : ENV CUDA_SUPPORT=${CUDA_SUPPORT}
 ---> Using cache
 ---> 869caec15d35
Step 35/53 : RUN if [ "$CUDA_SUPPORT" = "yes" ]; then         /tmp/components/cuda/install.sh;     fi
 ---> Using cache
 ---> 7be9087726ef
Step 36/53 : ARG WITH_DEXTR
 ---> Using cache
 ---> d7a8b62b9af4
Step 37/53 : ENV WITH_DEXTR=${WITH_DEXTR}
 ---> Using cache
 ---> f42175fc48b3
Step 38/53 : ENV DEXTR_MODEL_DIR=${HOME}/dextr
 ---> Using cache
 ---> d30f4bb6c728
Step 39/53 : RUN if [ "$WITH_DEXTR" = "yes" ]; then         mkdir ${DEXTR_MODEL_DIR} -p &&         curl https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip -o ${DEXTR_MODEL_DIR}/dextr.zip &&         7z e ${DEXTR_MODEL_DIR}/dextr.zip -o${DEXTR_MODEL_DIR} && rm ${DEXTR_MODEL_DIR}/dextr.zip;     fi
 ---> Using cache
 ---> 707d8d85d897
Step 40/53 : COPY ssh ${HOME}/.ssh
 ---> Using cache
 ---> 0f3ab67501eb
Step 41/53 : COPY utils ${HOME}/utils
 ---> Using cache
 ---> 2c95141daeca
Step 42/53 : COPY cvat/ ${HOME}/cvat
 ---> Using cache
 ---> 6eb304a77c28
Step 43/53 : COPY cvat-core/ ${HOME}/cvat-core
 ---> Using cache
 ---> 39f8de23321d
Step 44/53 : COPY tests ${HOME}/tests
 ---> Using cache
 ---> 6d64d51cd8bf
Step 45/53 : COPY datumaro/ ${HOME}/datumaro
 ---> Using cache
 ---> 614a68cecdc9
Step 46/53 : RUN python3 -m pip install --no-cache-dir -r ${HOME}/datumaro/requirements.txt
 ---> Running in 649d79998083
Requirement already satisfied: Cython>=0.27.3 in /usr/local/lib/python3.5/dist-packages (from -r /home/django/datumaro/requirements.txt (line 1)) (0.29.13)
Requirement already satisfied: GitPython>=3.0.8 in /usr/local/lib/python3.5/dist-packages (from -r /home/django/datumaro/requirements.txt (line 2)) (3.0.8)
Collecting lxml>=4.4.1
  Downloading lxml-4.5.0-cp35-cp35m-manylinux1_x86_64.whl (5.7 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.5/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/operations/prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/operations/prepare.py", line 159, in unpack_http_url
    link, downloader, temp_dir.path, hashes
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/network/utils.py", line 39, in response_chunks
    decode_content=False,
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: You are using pip version 20.0.1; however, version 20.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c python3 -m pip install --no-cache-dir -r ${HOME}/datumaro/requirements.txt' returned a non-zero code: 2

**Comment by nmanovic** [comment]
```
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

Looks like a problem with your local network or proxy. I will close the issue. Don't hesitate to reopen the issue if you think that my guess is wrong.

@azhavoro , it is a good candidate for FAQ.
