### ISSUE TITLE
Pascal VOC 2012 dataset export does not export Attributes correctly

### ISSUE THREAD

**Issue by matthaeusheer** [opencv/cvat#1518]
### Expected Behaviour
I am labelling a "person" with an attribute "pose" which can be either "y", "n" or "o". I expect this attribute to be accessible in the produced annotation file. I export as a dataset of pascal voc 2012 format and I am in labelling a video.
![Screenshot from 2020-05-09 11-04-18](https://user-images.githubusercontent.com/8364783/81469390-df1cd080-91e4-11ea-822f-41310d9d7d61.png)

### Current Behaviour
The following annotation is being produced where the "pose" field is set to "Unspecified" instead of "o".
```xml
<annotation>
	<folder/>
	<filename>52.jpg</filename>
	<source>
		<database>Unknown</database>
		<annotation>Unknown</annotation>
		<image>Unknown</image>
	</source>
	<size>
		<width>1920</width>
		<height>1080</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<occluded>0</occluded>
		<bndbox>
			<xmin>970.3649338942307</xmin>
			<ymin>70.13979867788461</ymin>
			<xmax>1003.2655636714069</xmax>
			<ymax>112.42590015117933</ymax>
		</bndbox>
	</object>
</annotation>
```

### Possible Solution
Append the attribute to the label to produce three labels person_o, person_y, person_n. Not nice and requires postprocessing after the labelling.

### Your Environment

- Git hash commit (`git log -1`): 034268e87dbf72b6ca08f017152b962882cc1d84
- Docker version `docker version`: Docker 19.03.8
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

**Comment by zhiltsov-max** [comment]
Hi, the only supported `pose` field values currently are: `Unspecified, Left, Right, Frontal, Rear`.

**Comment by matthaeusheer** [comment]
Hey, does that mean that the "pose" attribute is some sort of default, predefined attribute name in voc2012? Do I have the freedom to chose other attribute names and use whatever values I want? Thanks for your support.

**Comment by zhiltsov-max** [comment]
PASCAL VOC 2012 defines pose with only these values. If you have access to sources, you can modify [this fragment of code](https://github.com/opencv/cvat/blob/develop/datumaro/datumaro/plugins/voc_format/converter.py#L214) to export any values.

**Comment by zhiltsov-max** [comment]
Could you describe why do you need this functionality? Can you pick another format that supports attributes (`cvat`, `datumaro`, `labelme`)?
