### ISSUE TITLE
Unable to access CVAT localhost after OpenVINO installation

### ISSUE THREAD

**Issue by jwparktom** [opencv/cvat#1521]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Access localhost:7080 and localhost:8080

### Current Behaviour

Accessing localhost:7080 gives Error: Network Error.
and localhost:8080 gives This Page is Not Available

### Possible Solution

I did find the solution:
Environment: macOS Catalina 10.15.4, latest CVAT and OpenVINO release

`docker logs cvat` throws something like this:
`
  File "/usr/local/lib/python3.5/dist-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/usr/local/lib/python3.5/dist-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/usr/local/lib/python3.5/dist-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ImportError: No module named 'gitdb.utils.compat'
`
The issue is gitdb is not installed (gitdb2 is) and CVAT requires gitdb. I don't know why gitdb2 is not used but that's another story I guess?

Solution:
`docker exec -it cvat /bin/bash`
`pip install gitdb==0.6.4`

The problem was that while building the docker with OpenVINO (followed the README), requirements.txt of datumaro installs gitdb-4.0.5. This version isn't compatible with CVAT for some reason?

**TO MAKE THIS PERSISTENT** (quick, temporary fix):
`vim Dockerfile`
and add
`RUN python3 -m pip install --no-cache-dir gitdb==0.6.4`
right after
`RUN python3 -m pip install --no-cache-dir -r ${HOME}/datumaro/requirements.txt`
to force gitdb to 0.6.4. Rebuild docker

**Comment by jwparktom** [comment]
Hopefully, this can help people set up OpenVINO docker without any problem :)

**Comment by azhavoro** [comment]
@jwparktom Could you specify version of CVAT (git log -1)?

**Comment by jwparktom** [comment]
@azhavoro Sorry for the late response. 
Running it gives the hash 7e8fc2366afe2b41f534633e4b9d42fbd580546a (released on Feb 12)
After realizing that my version was pretty outdated, updating to the latest pre-release (v1.0.0-beta.2) seemed to fix the issue.
