### ISSUE TITLE
Could not login on the server

### ISSUE THREAD

**Issue by Saad-Doukali** [opencv/cvat#1532]
I am getting problem in login :
"Could not check authorization on the server
Open the Browser Console to get details": 

Failed to load resource: the server responded with a status of 502 (Bad Gateway)
cvat-app.tsx:159 Error: Request failed with status code 502. "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.16.1</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n".
e @ index.js:8

**Comment by Saad-Doukali** [comment]
cvat-app.tsx:159 Error: Request failed with status code 502. "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.16.1</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n".

**Comment by azhavoro** [comment]
Hi, please don't ignore the issue template and add more details about CVAT version, OS, etc. Also please attach logs `docker logs cvat` and `docker logs cvat_proxy`.

**Comment by Saad-Doukali** [comment]
It's working now after runing :
docker-compose down
docker-compose up -d

**Comment by xuanwu348** [comment]
I also meet this problem, but can't work around by docker-compose down and up
![image](https://user-images.githubusercontent.com/33962139/89099838-c78c6700-d424-11ea-84fb-0bb9770408cd.png)
 
![image](https://user-images.githubusercontent.com/33962139/89099844-d2df9280-d424-11ea-8321-c07dbdfebe25.png)

> cvat_proxy    | 2020/08/01 10:27:24 [error] 7#7: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.103, server: 192.168.1.107, request: "POST /api/v1/auth/login HTTP/1.1", upstream: "http://172.19.0.4:8080/api/v1/auth/login", host: "192.168.1.107:8080", referrer: "http://192.168.1.107:8080/auth/login"

**Comment by xuanwu348** [comment]
I used this version
![image](https://user-images.githubusercontent.com/33962139/89100065-c0665880-d426-11ea-87a7-31213a53920e.png)

and when I run "docker-compose up",  These information printed
cvat          | 2020-08-01 10:41:08,810 INFO success: ssh-agent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat          | 2020-08-01 10:41:08,810 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:08,811 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:08,811 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:08,812 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:08,812 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:08,812 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:10,824 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:10,825 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:10,825 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:10,826 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:10,826 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:10,826 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:13,835 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:13,835 INFO gave up: rqscheduler entered FATAL state, too many start retries too quickly
cvat          | 2020-08-01 10:41:13,835 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:13,835 INFO gave up: runserver entered FATAL state, too many start retries too quickly
cvat          | 2020-08-01 10:41:13,836 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:13,836 INFO gave up: rqworker_low entered FATAL state, too many start retries too quickly
cvat          | 2020-08-01 10:41:13,836 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:13,836 INFO gave up: rqworker_default_0 entered FATAL state, too many start retries too quickly
cvat          | 2020-08-01 10:41:13,837 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:13,837 INFO gave up: rqworker_default_1 entered FATAL state, too many start retries too quickly
cvat          | 2020-08-01 10:41:13,837 INFO spawnerr: command at '/home/django/wait-for-it.sh' is not executable
cvat          | 2020-08-01 10:41:13,837 INFO gave up: git_status_updater entered FATAL state, too many start retries too quickly

**Comment by Axrid** [comment]
U can try with "chmod -R 777 wait-for-it.sh"

**Comment by rilpires** [comment]
> U can try with "chmod -R 777 wait-for-it.sh"

I'm not sure why, but after this my 'docker-composer up' took all the steps in building 'cvat' once again and it solved my problem that was very similar to xuanwu348

**Comment by chan60** [comment]
Hello,
I resolved same problem with migrate,
Please do 

sudo docker exec -it cvat bash -ic 'python3 ~/manage.py migrate'

**Comment by Petros626** [comment]
> It's working now after runing : docker-compose down docker-compose up -d

is this the analog command, if you use serverless functions?
`docker-compose down`
`docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
`
