### ISSUE TITLE
Capability of using CVAT on Windows 10 Home edition

### ISSUE THREAD

**Issue by kaustubhharapanahalli** [opencv/cvat#1536]
Hi,

I have a personal laptop which runs on Windows 10 Home edition. While reading the instructions I saw that currently CVAT requires Windows 10 Pro or Enterprise. 

Being a CV Engineer, I would like to use an annotation tool on my personal laptop as well. 

Is there any way I can setup CVAT on Windows 10 Home Edition?

**Comment by nmanovic** [comment]
@kaustubhharapanahalli , it is a requirement from docker. It seems you are lucky. I have found the blog post: https://www.docker.com/blog/docker-desktop-for-windows-home-is-here/. Could you please try?

**Comment by kaustubhharapanahalli** [comment]
Yep, I will try it out and let you know if it works. Thanks for the blog :)

**Comment by kaustubhharapanahalli** [comment]
Hi as per the docker setup mentions, to install Docker on Windows home, we need to have the Windows 10 Home build to be 19018+ (which is a Windows Insider Preview build). Currently, based on the latest update which I received yesterday, the Windows 10 Home (Stable Build) is at 18363.

Since obtaining a Windows Insider Preview build puts our system at a bit of a risk, I would prefer not to set up Insider Preview build on my Laptop. 

If someone in the community is interested in trying this out, I think they can try and get back to you.

Thanks :)

**Comment by kaustubhharapanahalli** [comment]
One solution that I came across is that we can use docker-toolbox for setting up docker on Windows 10 home. This is the link to installing docker-toolbox
https://docs.docker.com/toolbox/toolbox_install_windows/

But when I was running `docker-compose up -d`, I got this error. 
```
ERROR: for cvat_proxy  Cannot start service cvat_proxy: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/d/Code_Papers_Datasets/Code/cvat/cvat_proxy/nginx.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/33755e7089406b1ccb551051ed941362f4d4991f362894d1ef2f6cc0b7cfb9d8/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/33755e7089406b1ccb551051ed941362f4d4991f362894d1ef2f6cc0b7cfb9d8/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project. 
```
I am not able to figure out what the error is

**Comment by zhiltsov-max** [comment]
@kaustubhharapanahalli, it is also possible to use and develop CVAT in Windows 10 with WSL, it has almost no differences with regular Ubuntu installation. If you think it's worth to provide some installation instructions, I can do this.

**Comment by kaustubhharapanahalli** [comment]
@zhiltsov-max Yep, that will be helpful as well. I can try it out. Thanks :)

**Comment by DavideCatto** [comment]
Same Error @kaustubhharapanahalli. How have you solved?

**Comment by kaustubhharapanahalli** [comment]
@DavideCatto I have not worked on this yet. I will update if I am able to figure this out :)

**Comment by DavideCatto** [comment]
I have found a workaround; In Windows every 30 days, my password change so I must to reset credentials to be able to mount the containers. (I m using Git bash).
1) Open Docker Settings
2) Go to the "Shared Drives" tab
3) Click on the "Reset Credentials..." link on the bottom of the window
4) Re-Share the drives you want to use with Docker (You should be prompted to enter your username/password)
5) Click "Apply"
6) Go to the "Reset" tab
7) Click "Restart Docker"

Hope that it can help someone.

**Comment by kaustubhharapanahalli** [comment]
Hi @DavideCatto 

The tool works on Windows 10 Enterprise or Pro edition. I had raised this issue for Windows 10 Home edition. Home edition doesn't have support for dockers.

**Comment by pcinqmars** [comment]
I am using Docker Toolbox for Windows 10 Home.
I have successfully used the CVAT docker in the past. When I try with the current develop or master branch, it fails with same error than you.

Did you try alternatives ?
https://www.docker.com/blog/docker-desktop-for-windows-home-is-here/

**Comment by kaustubhharapanahalli** [comment]
Hi @nmanovic ,

Thanks for updating the documentation on how to use CVAT on WIndows Home. Currently, after updating the docker desktop application to the latest version, I am able to execute docker command via the command prompt provided on Windows, but when I run the command `winpty docker exec -it cvat -ic 'python3 ~/manage.py createsuperuser' it throws the following error saying `'winpty' is not recognized as an internal or external command, operable program or batch file.` 

So I tried running just `docker exec -it cvat -ic 'python3 ~/manage.py createsuperuser' 
This command worked initially but later threw this error. 
```
setupvars.sh] OpenVINO environment initialized
manage.py: unexpected EOF while looking for matching `''
manage.py: syntax error: unexpected end of file
```

Could you please take a look at this and update the documentation? 
Thanks :)

**Comment by nmanovic** [comment]
@ActiveChooN , do you think you can cover the question?

**Comment by pcinqmars** [comment]
I've successfully switched over to Docker Desktop on WSL2.
I guess this bug with Docker Toolbox won't be fixed.

One convenient thing about Docker Toolbox was the fact that it was build over VirtualBox rather than WSL2, which are two mutually exclusive technologies on Windows10 at the moment.

e.g. If you need a VM to run the service that used to talk to CVAT, now you have to choose which half of the system will be offline.
