### ISSUE TITLE
How to use GPU for auto segmentation?

### ISSUE THREAD

**Issue by alskdwq** [opencv/cvat#1537]
Hi all,

So I've installed openvino and nvidia docker and set up cvat as the documentation of the two components says, but I believe cvat still isn't using gpu for auto segmentation since it takes way too long time to do segmentation. 

I'm wondering what's the right way to use GPU for segmentation? Will CUDA be automatically enabled after it is set up as in this doc?
https://github.com/opencv/cvat/tree/master/components/cuda

Thanks in advance for any help.

**Comment by azhavoro** [comment]
@alskdwq Hi, could you please check it with `nvidia-smi` tool to be sure that GPU is not used?
Also please add additional information about CVAT version.

**Comment by alskdwq** [comment]
@azhavoro Hi, I used nvidia-smi to monitor gpu usage, and there isn't any activities when segmentation is being used. The version is 2.3 I believe, according to the version line in docker-compose.yml.

**Comment by azhavoro** [comment]
2.3 is the version of the format specification for compose, please use `git log -1`.

**Comment by alskdwq** [comment]
commit 6566e4aa117fbe248c5f5c7745c196fa0a9497d4 (HEAD -> develop, origin/develop, origin/HEAD)
Author: TOsmanov <54434686+TOsmanov@users.noreply.github.com>
Date:   Thu May 7 16:50:18 2020 +0300

Is it this one? @azhavoro

**Comment by alskdwq** [comment]
I found in the dockerr-compose_cuda.yml file that the max supported cuda driver version is 410 but I have version 418 on my machine, could this be the cause of the problem?

**Comment by azhavoro** [comment]
It should not be a cause of the problem, this limitation actual for tesla cards. lets clarify the one thing: what auto segmentation do you mean? https://github.com/opencv/cvat/tree/develop/components/auto_segmentation or https://github.com/opencv/cvat/tree/develop/cvat/apps/dextr_segmentation?

**Comment by alskdwq** [comment]
It's the dextr segmentation I'm using.

**Comment by azhavoro** [comment]
Oh, I thought that you used segmentation with mask_rcnn.  Dextr model is openvino model and cannot be performed on GPU.

**Comment by alskdwq** [comment]
Got it. Will the support for GPU be added in the future?

Sorry for the confusion, I'm new to cvat and I saw in the labeling UI saying auto segmentation so I thought dextr is the auto segmentation.

**Comment by azhavoro** [comment]
Yeah... there is some confusion in the names. Not sure that OpenVino will support CUDA, but I'm not openvino developer. If you are interested in this feature could you submit a feature request?
I'll close this issue.

**Comment by alskdwq** [comment]
Sure, thank you azhavoro!
