### ISSUE TITLE
Errors in 1.0.0 on login and creating task

### ISSUE THREAD

**Issue by manybodycpa** [opencv/cvat#1545]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Installed latest version in new directory. Expected working system.

### Current Behaviour

Ended up with 

Server 1.0
Core 0.5.2
Canvas 0.5.2
UI 0.5.2

with error messages appearing on login:

Could not get formats from the server
TypeError: (intermediate value).map is not a function

and when trying to create a task:

Could not create the task
Error: Request failed with status code 400. {"image_quality":["This field is required."]}.

### Possible Solution

Problems may be related to previous installation of version 0.5.2 in *different* directory?

### Steps to Reproduce (for bugs)

1. Install CVAT according to instructions.
2. Login
3. Try to create task

### Context

Trying to switch from version 0.5.2 to 1.0.0.

### Your Environment

- Git hash commit (`git log -1`): 0934d772f80097b8585bccb21c2fb87423833220
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.8
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

**Comment by azhavoro** [comment]
@manybodycpa Hi, could you please try to clear browser cache?
Probably related issue https://github.com/opencv/cvat/issues/1496

**Comment by manybodycpa** [comment]
Clearing the cache resolved these errors. Can you confirm that having server version 1.0.0 and version 0.5.2 after installation is the intended behavior?

**Comment by zonxin** [comment]
I have the same problem, but clearing the cache does not work.
The posted payload has no image_quality field.

Git hash commit: `(git log -1): 011c4aa675381e(v1.0.0-beta.2)`
Browser:`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0`

**Comment by azhavoro** [comment]
@zonxin Could you try to create a task with another browser or incognito mode?

**Comment by zonxin** [comment]
@azhavoro 
I also try it in Chrome. I think I find the bug.  `taskSpec` misses `image_quality` field, which is required  in `v1.0.0-beta.2` and not missed in `v0.6.0`. I will give a try.

https://github.com/opencv/cvat/blob/v1.0.0-beta.2/cvat-core/src/session.js#1582
https://github.com/opencv/cvat/blob/v1.0.0-beta.2/cvat-core/src/server-proxy.js#L388
https://github.com/opencv/cvat/blob/v0.6.0/cvat-core/src/session.js#1459

**Comment by azhavoro** [comment]
`image_quality` field was moved into taskDataSpec https://github.com/opencv/cvat/blob/v1.0.0-beta.2/cvat-core/src/session.js#L1614
Could you attach the screenshot of `about` window?

**Comment by zonxin** [comment]
@azhavoro  Sorry, I have delete the server. I think it may be my faults. I build the server fail now, because pyav requires FFmpeg>=3.2. Maybe, it is because I did not notice the upgrade fail.
Now I want to know, for the `post /task`, the `image_quality` field is required or not at the server side?

**Comment by azhavoro** [comment]
@zonxin when you create the task the client makes 2 requests:
post at the `/tasks` endpoint and there is no `image_quality` field required
post at `tasks/task_id/data`: the `image_quality` field is required for this request

**Comment by zonxin** [comment]
@azhavoro That's it! It is because my server upgrade fails, and `/tasks` endpoint of previous version requires `image_quality` .
The upgrade fail comes from that python av module requires ffmpeg>=3.2, but the version installed from source is 2.8.15. May I has to install latest ffmpeg manually?

**Comment by azhavoro** [comment]
We use this repo to install ffmpeg3 https://github.com/opencv/cvat/blob/develop/Dockerfile#L26-L27
Did  you modify the Dockerfile to delete these lines?

**Comment by zonxin** [comment]
@azhavoro Yes, I am in China. The repo is very slow due to some reason, so I delete the repo and install some related packages manually. However, installing ffmpeg manually is very boring.

**Comment by azhavoro** [comment]
Got it, in you case I think will be better try to change base image to 18.04 or 20.04 that have ffmpeg3  in main repository. So, I think that minimal dockerfile modifications will be required. We plan to change the base image but if you help with this it would be nice.

**Comment by zonxin** [comment]
I tried a little last night with 18.04, but I did not find `gstreamer-ffmpeg` for ubuntu above 16.04. In addition, some dependencies of `gstreamer0.10-ffmpeg` can not be found in 18.04 main repository. I wonder the  package will not be work properly in ubuntu > 16.04. Now I have solved my problem by downloading related package and making a local repository.

**Comment by azhavoro** [comment]
@bsekachev Can we add a hash to the bundle or use something else to resolve such issues in the future?

**Comment by bsekachev** [comment]
@azhavoro 

Probably webpack has something like this. 
Need to investigate
