### ISSUE TITLE
install error of Semi-Automatic Segmentation with Deep Extreme Cut

### ISSUE THREAD

**Issue by machinedogwc** [opencv/cvat#1551]
I tried several versions of openvino, but always got the error below, and I can't find 2018 R5.0.1 from the official website. Could help to provide a usable openvino package?

l_openvino_toolkit_p_2018.5.445
l_openvino_toolkit_p_2019.1.094
l_openvino_toolkit_p_2019.3.376
"
Type "accept" to continue or "decline" to go back to the previous menu: Incorrect input, please try again
"

**Comment by azhavoro** [comment]
@machinedogwc Hi, please don't ignore the issue template. Could you please specify CVAT version, OS and exact steps to reproduce the issue.

**Comment by machinedogwc** [comment]
> @machinedogwc Hi, please don't ignore the issue template. Could you please specify CVAT version, OS and exact steps to reproduce the issue.

I am sorry, that I am not familiar with the issue template. 
I tried v1.0.0-beta.2，Windows 10_64. 

I followed the instruction below:

# OpenVINO component is also needed
docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml build

I got a lot of "Type "accept" to continue or "decline" to go back to the previous menu: Incorrect input, please try again" after several minutes.

Thanks.
