### ISSUE TITLE
Add update guide

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#1557]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
There is no update guide and no information how to upgrade CVAT in installation guide.

### Possible Solution
Need to add Update Guide (or corresponding section to installation documentation)

### Steps to Reproduce (for bugs)
N/A

### Context
N/A

### Your Environment
N/A

### Next steps
N/a

**Comment by Shravan1804** [comment]
Hi, any news on this one?

**Comment by azhavoro** [comment]
@Shravan1804 https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/faq.md#how-to-update-cvat

**Comment by aguadopd** [comment]
@azhavoro , thanks for the hint.
Regarding backups, [the FAQ](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/faq.md#how-to-update-cvat) only says 

> Before upgrading, please follow the official docker manual and backup all CVAT volumes.

1. When I list the docker volumes in my CVAT server I get a lot of hash-named volumes that I don't know if are important or not:

```bash
~/cvat$ docker volume ls
DRIVER              VOLUME NAME
local               0c96f057a0ca243b30f4a3d80a59f075ae6f2e1422e13c8c3aad082a2c78587b
local               2bc23b47b3c678ef6c2dc12f549520f59f64e458463f349d77aacb03ed73febd
local               3ac29ae4e3bf23b560f6c1f0dd63cf1666b231946a86b5a9eecc2d0a9bc8fed1
local               3d3187d7ee6b0e9ba458357d543063e5530d5bafc8423796c35aefa7da44a611
local               03b5fed679ae48e4cf1718fc583c6dedc749d86bddd2c417665c276b5f9ac8d5
local               4d14bcd30d0eaacd1174746cc371b8dc63fcdecc4e76d183deae4763a984a002
local               4f019551082b784ce6e5e4be7048521c5e6123306250dc9c8e113f0d557b4b0a
local               06fb46299a2c0834fa09dd1db1784fb836a89abff768b94316b001eea5267713
local               8af7d84495aa863c4b5657fb0f482d013a6cba07b5ced399b0d64082eb0ec59d
local               9c20c96a9d4628c7614f93f29626babd6dd52b09f6dcb4fc97325120420b9f9d
local               9d8f64002ed02bb06cd254ca3d0cc002a55b94326addeda341229912abd0d0fc
local               034ce8b127506a4c8536585a5a432e9cdfbfe8bfafa467f263534f5cb6f33b8c
local               44a70b41414ff775b17b579510c3837edba45fe31e9301876edfaf14edd3041f
local               46a340f027c839b0acaa54c1c916239bdb377b78cb0e500cdeeefd7e6def87f3
local               50aa46b38d9a6e3131cf7b5a9bbe55f7dad00ebfa1b70461f1cab4364d24a1fe
local               53e81e5660f2150fba919cd5dc950cf170b2a93ceaf76ce3b000a681d4b2d459
local               54ab810d95d88988efaea725eaac422595a79d3dce9806dea57ef88acf8ec9bd
local               222db60a5186a9a6088dd5923c75eeb477960999e14af2dad883e2e25179e0e2
local               0289b8f4531b730a09f5e2bd7eb5b7abf0e4856b6b8b7b8dbe1cb5fb592f8b41
local               426a46a63b8c5422c57d683b6464e1bf6cdd24f55c415119043e4e42c0615814
local               721b3c700b295f6b8b0815916e59377fde272b569b817baba15b68731465fbe8
local               9580d5dd23bc49f641bebced8a3300238d630f9d2f6db259af56d304c111b3ec
local               188795c9cc14dc790552a0d9c15768c7584e599d3f7164e24cf54ea6a1854ef2
local               379439ef413d66d031c4552971f58771814470e0f4a2f1ed67024ef5e27dc9cb
local               a72f5b2fb826aa3de8f30ce3a1f33d72f6815930a3b3526ddc353ca3b9b0dff0
local               b54c14fd84ee4bd45ea05bc5658e752802d5cbece3a476db34ef740203ae5bbc
local               baa2f126fc6dacad0e1c8a9d147bdcaca0f813fd6d50bfd2dbe7cd6d95982c47
local               c0db6a49f3d8418af957a72023a53a20d376588126a3a6fe74a946257589f129
local               c452a707d6ed90556c868f0367640f7fce529b3a36eee18a6da6a3c44f3fe490
local               c26162cbe308bfa757fc22b3e5c4a7d3a2f1442859566f3b4499a7c97d318858
local               ccfc852b44c4d187d9557e883f1b652b79483e5d272d89689b4f986d83f79e28
local               cvat_cvat_data
local               cvat_cvat_db
local               cvat_cvat_keys
local               cvat_cvat_logs
local               cvat_cvat_models
local               cvat_cvat_share
local               d1c7137f48acbdba6b1ac14ff71cadf983a4a084be6dd129848e3620d6ed3015
local               d9e8ecf025a9529a30b60bb31708755bd49b95a96e364b74814cc75cb415e090
local               d28ac58e7ec21c914fdc0f96336307b217e2859c18b3fed7458d382b078f1141
local               d0184b4731fa839f4b40ff087508c1e0a86cadfdcb02e88af835305ef3cec164
local               ecb4837590be23a5c456551db1fc3afd24d147a2397ea4f7ce4d1ff2534d5e83
local               f0b9a702a638072ee6db13fac1e10e9ae820fafed267b4a0389d4f0765ea8113
local               fb6ce5f0407e99f4b9c66c7a400420a95bb523684f6640728ed21298b5826316
local               fefbb2c80c666ea2e82b3217b35b7f1d78675ffda865ef4ced91320674c56b57
```

Should those be backed up too?

2. Maybe they are related to each task?

```bash
~/cvat$ docker volume inspect fefbb2c80c666ea2e82b3217b35b7f1d78675ffda865ef4ced91320674c56b57 
[
    {
        "CreatedAt": "2020-06-03T14:00:49Z",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/fefbb2c80c666ea2e82b3217b35b7f1d78675ffda865ef4ced91320674c56b57/_data",
        "Name": "fefbb2c80c666ea2e82b3217b35b7f1d78675ffda865ef4ced91320674c56b57",
        "Options": null,
        "Scope": "local"
    }
]
```

3. A bit offtopic: all the volumes are pointing to `"/var/lib/docker/volumes/`... would be enough to backup the whole `"/var/lib/docker/volumes/` folder and replace it in case of a loss? The Docker manual is not clear to me yet, but I'm new to the topic so maybe I have to keep on learning.

**Comment by kraster010** [comment]
@aguadopd did you manage to take the backups? I also don't know which volumes we should backup.

**Comment by aguadopd** [comment]
@kraster010 No, and I guess we are not going to do it soon since we have a lot of valuable data now :rofl: .
I gues it's safe to update, anyway, as stated in https://github.com/openvinotoolkit/cvat/issues/2114#issuecomment-686397693  .
We have done it before without problem when we were starting with CVAT. Now it's a harder decision maybe.

**Comment by azhavoro** [comment]
> @aguadopd did you manage to take the backups? I also don't know which volumes we should backup.

@kraster010 all volumes associated with CVAT are prefixed with `cvat`, you should backup `*cvat_cvat_data` and `cvat_cvat_db` at least. Also yes, you can backup it by copying folder, but stop all cvat containers before.

**Comment by davodogster** [comment]
> @Shravan1804 https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/faq.md#how-to-update-cvat

Hi, how do I update it? This link is 404 error and doesn't work anymore.

**Comment by aguadopd** [comment]
> > @Shravan1804 https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/faq.md#how-to-update-cvat
> 
> Hi, how do I update it? This link is 404 error and doesn't work anymore.

Check out new docs at https://openvinotoolkit.github.io/cvat/docs/for-users/faq/#how-to-update-cvat

**Comment by davodogster** [comment]
Thanks, will it work if I’ve been using the docker file version 2.3 (cvat projects not available in that version) - with cvat repo I cloned about a year ago.. and then update to the latest cvat repo with dockerfile version 3.3.
Will the data backup and restore still work?

Cheers
________________________________

**Comment by sarathsrk** [comment]
> > > @Shravan1804 https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/faq.md#how-to-update-cvat
> > 
> > 
> > Hi, how do I update it? This link is 404 error and doesn't work anymore.
> 
> Check out new docs at https://openvinotoolkit.github.io/cvat/docs/for-users/faq/#how-to-update-cvat


The link is not working... 404 not found

**Comment by aguadopd** [comment]
> > > > @Shravan1804 https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/faq.md#how-to-update-cvat
> > > 
> > > 
> > > Hi, how do I update it? This link is 404 error and doesn't work anymore.
> > 
> > 
> > Check out new docs at https://openvinotoolkit.github.io/cvat/docs/for-users/faq/#how-to-update-cvat
> 
> The link is not working... 404 not found

Now you can find docs at https://openvinotoolkit.github.io/cvat/docs/faq/ :+1:

**Comment by mishmashlabs** [comment]
Here is the current working link:
https://cvat-ai.github.io/cvat/docs/faq/#how-to-update-cvat

**Comment by nikste** [comment]
its not working unfortunately

**Comment by nmanovic** [comment]
@nikste , https://opencv.github.io/cvat/docs/faq/#how-to-update-cvat
