### ISSUE TITLE
mount local folder as shared storage

### ISSUE THREAD

**Issue by vasanththangavel** [opencv/cvat#1561]
while adding shared storage i got error like this,how to resolve this
Configuration for volume cvat_share specifies "device" driver_opt /home/naveen/Documents/test, but a volume with the same name uses a different "device" driver_opt (/mnt/share). If you wish to use the new configuration, please remove the existing volume "cvat_cvat_share" first:
$ docker volume rm cvat_cvat_share

my yml looks like this
`# docker-compose.override.yml 
version: "2.3"

services:
  cvat_proxy:
    environment:
      CVAT_HOST: 151.81.43.124
    ports:
    - "3365:80"
    
  cvat:
    environment:
      ALLOWED_HOSTS: '*'
      CVAT_SHARE_URL: "Mounted from /mnt/test host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/user/Documents/test
      o: bind`

**Comment by azhavoro** [comment]
Did you try delete the volume as error message suggest?

**Comment by vasanththangavel** [comment]
@azhavoro, am i need to delete the volume and recreate it or how to connect to this volume with my device path

**Comment by azhavoro** [comment]
Just run `docker volume rm cvat_cvat_share`

**Comment by vasanththangavel** [comment]
Error on chrome console came like this Not allowed to load local resource

**Comment by azhavoro** [comment]
@vasanththangavel Please add more details about your issue: screenshot of error from browser console.

**Comment by bsekachev** [comment]
No answer for a long time. I will close the issue. Do not hesitate reopen it if you need

**Comment by dasmehdix** [comment]
Same problem here.

**Comment by GoGoPen** [comment]
Try to remove all mounted volume by
```
docker volume rm $(docker volume ls -q)
```

**Comment by kimlia545** [comment]
after removed cvat_cvat_share volume and recreate cvat_cvat_share 
I got "Could not send logs to the server
Open the Browser Console to get details"
Error when creating and saving task
