### ISSUE TITLE
Multiple jobs for the same segment

### ISSUE THREAD

**Issue by anderflash** [opencv/cvat#1564]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The idea is to have multiple annotators to the same set of images (so we can cross-validate them).

### Current Behaviour

Currently we need to create multiple tasks with the same image set, which waste space.

### Possible Solution

Two approaches: 
- One task, two jobs, same frame range for them, one assignee per job. (maybe one option for the user to input which frames this job is linked to)
- One task, one job, multiple assignees per job (perhaps like the Gitlab's label selection UI component)

I think the general idea is to provide a manual control over the range of frames per job (the overlap/segment size/start/end would be the automatic version of it). Nowadays we can't have a full overlap (otherwise we have a infinite loop with the current CVAT code).

### Steps to Reproduce (for bugs)

Not applicable (I think the issue description is self contained)

### Context

Datasets whose subsets can be annotated by multiple users.

### Your Environment

- Git hash commit (`git log -1`): 42fb305d673c33b183170ab9edf16a764444b6ac
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 19.03.8-ce, build afacb8b7f0
- Are you using Docker Swarm or Kubernetes? Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Linux 5.6.11-1-MANJARO #1 SMP PREEMPT Wed May 6 10:20:32 UTC 2020 x86_64 GNU/Linux
- Code example or link to GitHub repo or gist to reproduce problem:

**Comment by nmanovic** [comment]
https://github.com/opencv/cvat/issues/125 (similar issue)

**Comment by bsekachev** [comment]
Let's close it because it is a dublicate
