### ISSUE TITLE
Git synchronization issue

### ISSUE THREAD

**Issue by mkostiv** [opencv/cvat#1569]
Steps to reproduce:

1. Create a task with Git dataset repository
2. Add some annotations
3. Press `Synchronize` button

`git describe` 0.2.0-721-g42fb305

![image](https://user-images.githubusercontent.com/45266535/82478632-dd52e700-9ad9-11ea-835e-a59c4f9b03c6.png)

**Comment by azhavoro** [comment]
@mkostiv Thanks for the report.
