### ISSUE TITLE
Segmentation masks 1.1 dumping annotations

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1575]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

All frames should dump with a segmentation mask
### Current Behaviour

Noticed that when we dump annotation in the segmentation masks 1.1 format some frames don't contain a mask even if they were correctly annotated.
In the annotation tool this frame look so. As we can see it's fully annotated:
![image](https://user-images.githubusercontent.com/45849884/82558412-3a03df80-9b76-11ea-8431-e67fab29232a.png)

And so it dumps in the segmentation mask 1.1 format:
![image](https://user-images.githubusercontent.com/45849884/82558339-1b054d80-9b76-11ea-9edd-019740dd3d23.png)

### Steps to Reproduce (for bugs)

1.Annotate images with polygons using z-order
1.Dump the annotation in segmentation mask 1.1 format
1.Check the images inside the zip archive you'll get

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Is it possible that this image had the red rectangle annotation (background) with lesser `z_order` than others? This is the only possible reason I can come up with now.

**Comment by nmanovic** [comment]
@aschernov , could you please attach an annotation file which the issue?

**Comment by zhiltsov-max** [comment]
I've checked already. Seems really strange, especially taking into account that the same actions in Datumaro done manually give the expected result.

**Comment by aschernov** [comment]
[2020_05_21_16_08_19-cvat for images 1.1.zip](https://github.com/opencv/cvat/files/4668076/2020_05_21_16_08_19-cvat.for.images.1.1.zip)
[2020_05_21_16_08_19-segmentation mask 1.1.zip](https://github.com/opencv/cvat/files/4668083/2020_05_21_16_08_19-segmentation.mask.1.1.zip)
