### ISSUE TITLE
Polygon editing behaviour can be unexpected 

### ISSUE THREAD

**Issue by Kevin-Delnoije** [opencv/cvat#1579]
I am talking about the following feature:
https://youtu.be/XTwfXDh4clI?t=138

When using the new ui the previous selection dissapears when reconnecting the point.
The old ui works perfectly fine.

environment:
I followed the installation instructions a few days ago so to update i did
```bash
git pull
docker-compose build
```
everything did re-install again, so i am fairly confident i am on today's version.

**Comment by bsekachev** [comment]
@Kevin-Delnoije 

Please, do not ignore the issue template. 

I am not sure I understand you right. Could you please describe clearer or send us a gif animation with demonstration of the issue?

**Comment by Kevin-Delnoije** [comment]
sorry for the unclear explanation.
when extending the polygon with shift+doubleclick in the old UI the regions automatically get merged.
In the new ui it turns out it was me clicking the wrong area or button after extending the polygon.
here is a gif: [
![wrong_click](https://user-images.githubusercontent.com/45107767/82677292-114c1a80-9c48-11ea-931d-e46f011fa303.gif)
](url)

This is probably intended behaviour in the new UI, although it doesn't match the current documentation i think.

**Comment by bsekachev** [comment]
@Kevin-Delnoije 

The issue I believe is related with #1515
Actually we haven't decided how the function should work yet.
