### ISSUE TITLE
Annotations Don't Get Updated If We Run Automatic Annotation Again

### ISSUE THREAD

**Issue by savan77** [opencv/cvat#1580]
### My actions before raising this issue
- [* ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ *] Searched [past issues](/issues)

### Expected Behaviour

If you run automatic annotation the first time, then it works fine. But if you run automatic annotation again and go back to the annotation page, then the bounding boxes aren't updated. You have to refresh the page to force the updates. Ideally, when we go to the annotation page after running the automatic annotation it should have new annotations.

### Current Behaviour

Currently, after running the automatic annotation, it does not get updated automatically. We have to refresh the page manually. 

### Possible Solution

Not sure. I confirmed `put_task_data` is being called but it still doesn't show annotations.

### Steps to Reproduce (for bugs)

1. Run Automatic Annotation first time
2. Go to the annotation page, you will see your annotations.
3. Run automatic annotation again
4. Go to the annotation page, you won't see updated annotations even though clean old annotation button was selected.

### Context

I am just trying to automatic annotation multiple times.

### Your Environment

- Git hash commit (`git log -1`): Develop branch
- Docker version `docker version` (e.g. Docker 17.0.05): Using in Development Mode
- Are you using Docker Swarm or Kubernetes? None
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

This problem has already been discussed with @azhavoro on Gitter.

**Comment by bsekachev** [comment]
Related issue #1424

Automatic annotation isn't matter. The problem is single page application doesn't request new annotations from the server when open task again (all data are stored in a browser for the latest opened task, even when you have gone to task list).
