### ISSUE TITLE
Feature Request: "Distinct colours for different labels"

### ISSUE THREAD

**Issue by LukeAI** [opencv/cvat#1584]
Branch:
I am using the latest develop branch of cvat

Problem:
I am annotating three different classes. I have set appearance to "Label" so it is easy to see when I have made a mistake and selected the wrong class for labelling. But the colours used for different classes are three subtly different shades of pinkish purple.

![image](https://user-images.githubusercontent.com/43993778/82657432-40996200-9c1d-11ea-9a1b-82c6efeaec71.png)

Suggestion:
It would be much easier to spot my mistakes if distinct colours were used instead.
This website http://phrogz.net/css/distinct-colors.html  generates lists of visually distinct colours.
Maybe the default colours used could be taken one by one from a list like:

`#bf8f8f, #7f1100, #ff4400, #ffa280, #4c3026, #a65800, #d9a66c, #ffaa00, #664d1a, #807560, #b2982d, #ffee00, #e6e2ac, #90d900, #4c661a, #2f3326, #688060, #6cbf60, #00330e, #00ff66, #008066, #40ffd9, #8fbfb6, #10403d, #40d9ff, #406a80, #003666, #40a6ff, #acc3e6, #4059ff, #606cbf, #14004d, #3d0099, #4e3366, #b56cd9, #cc00ff, #b68fbf, #332630, #4d0033, #b32d86, #99003d, #ff80b3, #4c000a, #ff4059 `

**Comment by bsekachev** [comment]
@LukeAI 

Thank you for the information, it is really useful. 
We will look into that.

**Comment by LukeAI** [comment]
Oh I just saw that I can set the label colour in the Labels tab. So this is not super-important. Better defaults would be nicer though. It would also be really nice if the same label had the same colour across all tasks. One thing I've been a little confused about is that every time I create a new Task and upload the same label list, every label from every task seems to have a unique ID? It doesn't really matter if the annotations I download don't have differen IDs, but why is that?

**Comment by nmanovic** [comment]
@LukeAI , thanks for the issue and the link. Agree that it is necessary to fix default colors.
