### ISSUE TITLE
Feature Request: An Appearance option to show all text labels on an image

### ISSUE THREAD

**Issue by LukeAI** [opencv/cvat#1585]
Feature Request:
An Appearance tick box that shows all labels on an image.

Motivation:
When reviewing annotations and checking for errors I can see this:
![image](https://user-images.githubusercontent.com/43993778/82659046-efd73880-9c1f-11ea-9724-eb6e03eb7a7a.png)

I cannot easily, at a glance, assert that every annotation is of the correct class, I have to hover the mouse over each annotation in turn.

**Comment by bsekachev** [comment]
@LukeAI 

Hi, please look here: 
![Screenshot from 2020-05-22 13-40-45](https://user-images.githubusercontent.com/40690378/82659757-e48d0880-9c31-11ea-9bba-dd1419566e13.png)
