### ISSUE TITLE
Unable to upload annotations

### ISSUE THREAD

**Issue by Sentient07** [opencv/cvat#1586]
Hi, 

I've just finished some trial annotations. I was wondering about the quality of my annotation, hence tried to dump the annotation and re-upload over the same frames, but as a different task. What I observe is that there are no correlations between the dumped annotation and the uploaded frames. 

I am attaching the images from my CVAT tool which are 
1) Initial frame without any annotations
2) Initial frame from the task where I've manually annotated
3) Initial frame from the task where I've uploaded the dumped XML file from (2)
4) Final frame from task in (3) which shows the bounding boxes correctly aligned.

All frames except the last one seem to have no correlation with my manual annotation. Could you please help me understand the means to re-upload annotations? Could you please also clarify if this is a bug with CVAT or my way of setting up task?

Images: https://imgur.com/a/3cOY5r0 

Thanks,

**Comment by zhiltsov-max** [comment]
Hi, please specify CVAT version.

**Comment by Sentient07** [comment]
Hi. I'm using CVAT v 1.1.

**Comment by zhiltsov-max** [comment]
This version hasn't been released yet, could you specify a commit hash?

**Comment by zhiltsov-max** [comment]
@Sentient07, please provide additional details if this problem is still actual.
