### ISSUE TITLE
new UI - When moving a box point the resolution is 1 rather than 0.1 as on the old.

### ISSUE THREAD

**Issue by yohayonyon** [opencv/cvat#1590]
The latest code was used on Ubuntu 18.04.
When drawing the box and on the old UI the resolution is 0.1.

**Comment by bsekachev** [comment]
@yohayonyon 

Hi, finally, what exactly do you mean? Drawing or resizing? They are different actions.
I checked both and can confirm the issue during resizing, but not during drawing.

**Comment by yohayonyon** [comment]
I meant resizing only. When drawing the resolution is 0.1.

**Comment by bsekachev** [comment]
@yohayonyon 

Okay, thx. We will look into the issue

**Comment by yohayonyon** [comment]
Thank you
