### ISSUE TITLE
Add ability to reset the user password.

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#1600]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Currently there is no ability to reset password.

### Expected Behaviour
Should be possible reset the password.

### Current Behaviour
NA

### Steps to Reproduce (for bugs)
NA

### Context
NA

### Your Environment
NA

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by aguadopd** [comment]
Related: #167
