### ISSUE TITLE
COCO Json dumps an empty annotations list , whereas the data is dumped properly in the XML format. 

### ISSUE THREAD

**Issue by ashjostan7** [opencv/cvat#1602]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
Hi,

I tired dumping annotations in COCO json format. But the annotations section is empty. Although, when I dump in XML format the key point coordinates are present. 
The data set I created includes only keypoints , no segmentation and bounding box data. Kindly let know what I could do to get the key point coordinates in the annotations section in COCO Json format.

Thanks in advance.

**Comment by ashjostan7** [comment]
Hi, 
I tired dumping annotations in COCO json format. But the annotations section is empty. Although, when I dump in XML format the key point coordinates are present. The data set I created includes only keypoints , no segmentation and bounding box data. Kindly let know what I could do to get the key point coordinates in the annotations section in COCO Json format.

Thanks in advance.

PS: Cant attach XML and JSON file if required

**Comment by zhiltsov-max** [comment]
Hi, this is because COCO keypoints format is not supported, check this comment https://github.com/opencv/cvat/issues/1421#issuecomment-616576420

**Comment by ashjostan7** [comment]
Thanks for the clarification.
