### ISSUE TITLE
bounding box is in picture when outside property is set

### ISSUE THREAD

**Issue by 3gfisch** [opencv/cvat#1620]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] asked in gitter
- [X] Searched [past issues](/issues)

### Expected Behaviour
The labels should be in the tfrecord as i see them in the browser while labeling. At least what i expect form it. So if i end a tracked label with the "outside property" it also should not be in the exported data or.
or am i doing something wrong? Thanks ;)

### Current Behaviour
(Hi, i don't know if this is a bug or if im doing something wrong but) the bounding box in "track" mode is also in the picture where i set the "outside property" and disappears only in the next frame but I think it should also be not there in the actual frame with "outside property".

### Possible Solution
the export should take the "outside property" into account or the UI should show the bounding box in this frame that we know what we actually label.

### Steps to Reproduce (for bugs)
exported my [data set as CVAT for images 1.1](https://drive.google.com/file/d/1FLwEhJNBWhDioNWtD0cwmtLz8n7pOXP9/view?usp=sharing)
if i export data sets like this i get always one labeled frame more like described.
1. import jpgs extracted from video
2. label bounding boxes in 2 point track mode
3. go to the point wehre de object is no longer in frame and switch to outside property
4. export dataset as TFRecord v1.0
5. look inside the TFRecord file for the frame where the bounding box should be gone with the outside property, but its still there

### Context
i try to correctly label images for export in tfrecord and the train a SSD mobilenet with this data

### Your Environment

- Git hash commit (`git log -1`): fb380d985528409483cfa25550126f9c50a65de4
- Docker version `docker version` (e.g. Docker 17.0.05): 
<img width="1139" alt="Bildschirmfoto 2020-05-29 um 20 42 49" src="https://user-images.githubusercontent.com/18620991/83327809-fba9a700-a27e-11ea-87a5-853f8bd19897.png">
Docker on Mac 2.3.0.3 (45519)
- Are you using Docker Swarm or Kubernetes?: Kubernetes is with the Docker but not shure
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS 10.15.4
- Code example or link to GitHub repo or gist to reproduce problem: -
- Other diagnostic information / logs: -

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
already asked there if i did something wrong but no answer thill now

**Comment by 3gfisch** [comment]
Thanks very much! seams to work now 👍

**Comment by ladykarel** [comment]
hi there I am annotating a video rectangle track that should no longer appear on page 30 but should be in prev pages, what should I need to do?

**Comment by zhiltsov-max** [comment]
@ladykarel, enable its "outside" property at frame 30.

https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/user_guide.md#track-mode-basics

**Comment by ladykarel** [comment]
Let me check on it and change it.
