### ISSUE TITLE
HTTPS | request.scheme

### ISSUE THREAD

**Issue by RotemEmergi** [opencv/cvat#1623]
Hi !

I move to work from http to https .
I need to change the request.scheme from http to https - how and where I can set it >?

Best Regards

**Comment by azhavoro** [comment]
You cannot set scheme field of request yourself, it just represents the current scheme. You need setup ssl encryption for your CVAT instance https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#serving-over-https

Please use gitter for such questions in the future.

**Comment by nmanovic** [comment]
I will close the issue. Don't hestitate to reopen it if you want to discuss it futher.
