### ISSUE TITLE
docker-compose build hangs on Step 20/29

### ISSUE THREAD

**Issue by manybodycpa** [opencv/cvat#1633]
Following the installation instructions for git commit 

`79c39ad35cf4d6842e6c670152f64b08a04d44ea` 

causes the installation process (docker-compose build) to hang:

```
Step 20/29 : RUN npm install
 ---> Running in e1030db32432
```

No such problems on same VM using git commit

`8afb5dda2a6471ff9274a6ac18c6a425786ddfea`

**OS:** Ubuntu 18.04

**Comment by bsekachev** [comment]
@manybodycpa 

This step can take significant time to install all dependencies. How much time are you waiting? Do you get any errors?

**Comment by manybodycpa** [comment]
No error messages. I just reran the setup and waited for 10 minutes so far with no progress.

**Comment by manybodycpa** [comment]
OK, it really just took a very long time. Apologies for opening an issue.

**Comment by bsekachev** [comment]
@manybodycpa 

If no errors, process is probably running.
Could you try to wait more? There are different factors that can affect installation time: your bandwidth, npm servers ping and bandwidth, etc.

**Comment by bsekachev** [comment]
@manybodycpa 

Great
