### ISSUE TITLE
how to specify ALLOWED_HOSTS (just for one given machine), not using "*"

### ISSUE THREAD

**Issue by Eric-Zhang1990** [opencv/cvat#164]
@nmanovic  Using ALLOWED_HOSTS: "*" works for me now, but I don't know how to specify ALLOWED_HOSTS for just one given machine (like ip 192.168.110.222), can you give me a example, please? Thanks.

**Comment by nmanovic** [comment]
For example: `ALLOWED_HOSTS: example.com`. 

More information you can find in the official Django documentation: https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts

> A list of strings representing the host/domain names that this Django site can serve. This is a security measure to prevent HTTP Host header attacks, which are possible even under many seemingly-safe web server configurations.
Values in this list can be fully qualified names (e.g. 'www.example.com'), in which case they will be matched against the request’s Host header exactly (case-insensitive, not including port). A value beginning with a period can be used as a subdomain wildcard: '.example.com' will match example.com, www.example.com, and any other subdomain of example.com. A value of '*' will match anything; in this case you are responsible to provide your own validation of the Host header.

Does it answer your question?

**Comment by aurotripathy** [comment]
@Eric-Zhang1990 My understanding is, you want to restrict the hosts to one machine in the LAN with the specified IP Address. 
Did you try to specify just the IP address in quotes? May not work, just a guess, I have not tried it.

**Comment by nmanovic** [comment]
@Eric-Zhang1990 ,

I will close the issue. Don't hesitate to reopen the issue if you think your question was not answered.

**Comment by Eric-Zhang1990** [comment]
@aurotripathy  You are right, what I mean is what you say, I try to use IP address, but it does not work.

**Comment by mattli001** [comment]
@Eric-Zhang1990 
If you are runing by docker-compose.yml, you could change docker-compose.yml by add environment `ALLOWED_HOSTS="*"`
```
matt@~/cvat> git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 0f8bda7..de02c2a 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -50,6 +50,7 @@ services:
         WITH_TESTS: "no"
     environment:
       DJANGO_MODWSGI_EXTRA_ARGS: ""
+      ALLOWED_HOSTS: "*"
     volumes:
       - cvat_data:/home/django/data
       - cvat_keys:/home/django/keys
```

**Comment by nmanovic** [comment]
@Eric-Zhang1990 , it should work. Please specify IP address as a string. You can find a couple of examples here: https://stackoverflow.com/questions/37031749/django-allowed-hosts-ips-range/40665906
