### ISSUE TITLE
CVAT new UI: fill in black the "occluded" and the "hide" icons

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1646]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

To have an uniform style I'm offering to fill in black all the icons when they are activated
### Current Behaviour

![image](https://user-images.githubusercontent.com/45849884/83764979-482c2280-a683-11ea-970e-64c0ffd98f6a.png)
The "occluded property" and the "hide" have no black fill.

**Comment by bsekachev** [comment]
Occluded doesn't have dark theme in antd
