### ISSUE TITLE
How can I connect from other computers which are NOT on the LAN?

### ISSUE THREAD

**Issue by Eric-Zhang1990** [opencv/cvat#165]
@nmanovic  Now other computers that are on the same LAN can access server (192.168.110.202:8080), however, how can I connect from other computers which are **NOT** on the LAN? Thanks.

**Comment by pvenuprasad** [comment]
I have the same issue. I am able to access the server from computers connected to the LAN but not from ones which are outside the network. Could you please tell me how you resolve the issue?
