### ISSUE TITLE
how can an annotator search for a label in the dropdown list when the number of labels is very large?

### ISSUE THREAD

**Issue by shenglih** [opencv/cvat#1656]
I was just wondering if there's anything that I missed in the situation where the number of labels is over 1000 and it is infeasible for the annotator to choose from the dropdown list without any built-in search function? If not, how do you resolve such problems? Thanks for any pointers in advance.

**Comment by bsekachev** [comment]
@shenglih 

You are right. It seems to be there isn't functionality for that. Need to improve.
