### ISSUE TITLE
How to Change Background of the Mask to be Black?

### ISSUE THREAD

**Issue by sarmientoj24** [opencv/cvat#1659]
### Expected Behaviour
I'd like to change the background mask to be black when exported.

### Current Behaviour
Default mask is not black

**Comment by zhiltsov-max** [comment]
You can call the background class `background` or remove any labels called `background`.

**Comment by sarmientoj24** [comment]
DO i have to create another class to be background? Say I have five classes, do I need to make it 6 then have the last one as black?

**Comment by zhiltsov-max** [comment]
You can either create a `background` class and draw it, or don't create it and all the unannotated space will be black. Did you have any problems with obtaining black background?

**Comment by sarmientoj24** [comment]
all unannotated space is brown

**Comment by zhiltsov-max** [comment]
Can you update to the latest version and check?

**Comment by zhiltsov-max** [comment]
You can also change colors on existing png masks using [Datumaro](https://github.com/opencv/cvat/tree/develop/datumaro) (example https://github.com/opencv/cvat/pull/1670):

1. `datum project import --format voc --input-path <path/to/voc/dataset>`
  
2. Create a color map file with desired colors:
```
# label : color_rgb : parts : actions
background:0,0,0::
cat:0,0,255::
dog:255,0,0::
```

3. datum project export --format voc_segmentation -- --label-map mycolormap.txt

**Comment by bsekachev** [comment]
@sarmientoj24 No answer for a month here. I will close the issue. Do not hesitate reopen it if you still need help
