### ISSUE TITLE
Add attribute to a label after a task being created

### ISSUE THREAD

**Issue by Po-Hsuan-Huang** [opencv/cvat#166]
Hi, 

Is there a way to add attributes to a label after a task being created ? I have checked the user's guide, and it seems there's no such option.

Thank you !

**Comment by nmanovic** [comment]
Hi @Po-Hsuan-Huang ,

There are two was to do that:
- In admin panel you can find your task and change labels and attributes (it is dangerous and can lead to problems if your changes are not compatible)

![image](https://user-images.githubusercontent.com/40690625/47703762-5659c780-dc32-11e8-930c-6da7de78c9a5.png)

- You can use `update task` feature in dashboard. Press the button and type your label with necessary attributes.

![image](https://user-images.githubusercontent.com/40690625/47703718-33c7ae80-dc32-11e8-8880-2e0763ed168b.png)

**Comment by nmanovic** [comment]
Hi @Po-Hsuan-Huang ,

I will close the question. Don't hesitate to reopen the issue if you think that your question isn't answered. You can use https://gitter.im/opencv-cvat to ask new questions and discuss any problems.
