### ISSUE TITLE
Connected file share doesn't work

### ISSUE THREAD

**Issue by kitovyj** [opencv/cvat#1664]
### My actions before raising this issue
Fresh install of Ubuntu 18 in VBox, Windows 10 host. I got the same issue before in Ubuntu 17, then created a fresh Ubuntu installation.

Installed cvat following the guide.
Created docker-compose.override.yml:

version: "2.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /mnt/share host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /media/sf_deep_clattice
      o: bind

sf_deep_clattice is a VirtualBox shared folder pointing to the host (Windows) folder.

### Expected Behaviour

Seeing the content of the folder in "Connected share" tab

### Current Behaviour

When switching to "Connected share" tab I get

Could not load share data from the server
Error: Request failed with status code 500. "<h1>Server Error (500)</h1>".

cvat log:

...

mote 172.18.0.6:47030]   File "/home/django/cvat/apps/engine/views.py", line 185, in share
[Sun Jun 07 19:04:06.324071 2020] [wsgi:error] [pid 191:tid 140299067631360] [remote 172.18.0.6:47030]     content = os.scandir(directory)
[Sun Jun 07 19:04:06.324073 2020] [wsgi:error] [pid 191:tid 140299067631360] [remote 172.18.0.6:47030] PermissionError: [Errno 13] Permission denied: '/home/django/share'
[Sun Jun 07 19:04:06.324077 2020] [wsgi:error] [pid 191:tid 140299067631360] [remote 172.18.0.6:47030] 

The folder permission as it is displayed via "docker exec -t -i cvat /bin/bash" + "ls -All"

-rw------- 1 django django   16 Jun  7 19:18 .bash_history
-rw-r--r-- 1 django django   78 Jun  7 18:34 .bashrc
drwxr-xr-x 3 django django 4096 Jun  7 19:02 .cache
drwxr-xr-x 3 django django 4096 Jun  7 19:02 .config
drwxr-xr-x 2 django django 4096 Jun  7 19:02 .keras
drwxr-xr-x 1 django django 4096 Jun  7 19:02 .ssh
drwxr-xr-x 1 django django 4096 Jun  7 18:40 cvat
drwxr-xr-x 1 django django 4096 Jun  7 18:39 cvat-core
drwxr-xr-x 1 django django 4096 Jun  7 18:39 cvat-data
drwxr-xr-x 5 django django 4096 Jun  7 18:52 data
drwxr-xr-x 1 django django 4096 Jun  7 18:39 datumaro
drwxr-xr-x 3 django django 4096 Jun  7 18:53 keys
drwxr-xr-x 3 django django 4096 Jun  7 19:02 logs
-rw-r--r-- 1 django django  686 Jun  7 18:28 manage.py
drwxr-xr-x 2 django django 4096 Jun  7 18:40 media
-rw-r--r-- 1 django django  111 Jun  7 18:28 mod_wsgi.conf
drwxr-xr-x 2 root   root   4096 Jun  7 18:52 models
drwxrwx--- 1 root      999 4096 Jun  7 11:40 share
drwxr-xr-x 7 django django 4096 Jun  7 18:40 static
-rw-r--r-- 1 django django 2676 Jun  7 18:28 supervisord.conf
drwxr-xr-x 1 django django 4096 Jun  7 18:39 tests
drwxr-xr-x 1 django django 4096 Jun  7 18:39 utils
-rwxr-xr-x 1 django django 4124 Jun  7 18:28 wait-for-it.sh

----------
root? 999? what's happened? That is a fresh install. The same thing I got before in Ubuntu 17 in the same host OS.

### Possible Solution

No idea

### Steps to Reproduce (for bugs)

1. Install fresh Ubuntu 18 in VirtualBox under Windows Home 10 host.
2. Create a shared folder.
3. Install cvat following the guide
4. create a docker shared folder pointing to the VBox shared folder:

docker-compose.override.yml:

version: "2.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /mnt/share host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /media/sf_deep_clattice
      o: bind

### Context
The main issue is that cvat can't upload many large files in one task. That's why I'm forced to do all these annoying docker/linux/cvat/shared folder rain dances (without any success so far).

### Your Environment

Windows 10 Home host
Latest Virtual Box
Ubuntu 18.whatever latest fresh install
cvat is installed using the oficial guide
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

![VirtualBox_ubuntu-18_07_06_2020_21_09_25](https://user-images.githubusercontent.com/15792725/83978254-71a8b080-a906-11ea-9800-0e4980191a3c.png)

[log.txt](https://github.com/opencv/cvat/files/4742782/log.txt)

**Comment by kitovyj** [comment]
I have just realized that the issue is releated to inability to create links for VBox shared folders...

**Comment by azhavoro** [comment]
What is the permissions for this folder inside VM?

**Comment by kitovyj** [comment]
-rwxrwx---  root vboxsf
So, no permissions for the users outside the group.
So, that's my fault, thank you for reviewing. I think the issue can be closed.

**Comment by azhavoro** [comment]
👍

**Comment by Lensca84** [comment]
Hi, I want to use cvat with a VBox shared folder, do you have a workaround ?
