### ISSUE TITLE
CVAT new UI: Cannot read property 'annotations' of null

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#1666]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

**TypeError: Cannot read property 'annotations' of null**

### Expected Behaviour
N/A

### Current Behaviour
Exception occurs

### Steps to Reproduce (for bugs)
N/A

### Your Environment

- Git hash commit (`git log -1`): **35badcca5588d22bbe7bc0e6d52637053e55f40c**
- Docker version `docker version`: **Docker version 19.03.8, build afacb8b7f0**
- Are you using Docker Swarm or Kubernetes? **No**
- Operating System and version (e.g. Linux, Windows, MacOS): **Ubuntu 18.04**
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
JS stack trace:
```
TypeError: Cannot read property 'annotations' of null
    at Lo.beforeUnloadCallback (https://cvat.org/cvat-ui.min.js:72:1177773)
```

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Steps to reproduce:
1. Open tool (DO NOT OPEN A JOB)
2. Go to settings
3. Close the tab

``beforeUnloadCallback`` is called and tries to read property ``annotations`` of j``obInstance`` that is ``null``.
It will be resolved with #1705.
