### ISSUE TITLE
Password change/reset by email

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#167]
Very often it is necessary to change password for a user. The only way now is to change the password in admin panel. It is better if the user can change it without admin assistance. Probably for LDAP auth the feature should be disabled.

An article how to implement that: https://wsvincent.com/django-user-authentication-tutorial-password-reset/

**Comment by nmanovic** [comment]
No requests from users for the feature. Let's wait while somebody submit it or reopen the issue.

**Comment by jaiswati** [comment]
Hi @nmanovic , 
We need to retrieve the cvat account registered with  monikapandey234@gmail.com.  After the password was reset new password did not work.. need help on this urgently.

Best,
Swati
