### ISSUE TITLE
How to disable the "Export as a dataset" function?

### ISSUE THREAD

**Issue by brixxx** [opencv/cvat#1671]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Not every user should have the ability to download a dataset.
How can the function "Export as a dataset" be limited to certain users or be disabled?
Thanks

### Current Behaviour
The function "Export as a dataset" is available to all users for all tasks.

### Your Environment
CVAT [1.0.0] - 2020-05-29
Ubuntu 18.04.4 LTS

**Comment by brixxx** [comment]
No one has an idea?
Even a dirty solution with code changes would be very appreciated!

**Comment by azhavoro** [comment]
Hi, sorry for the late response, as workaround please take a look https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/faq.md#how-to-make-unassigned-tasks-not-visible-to-all-users. This setting reduce task visibility to owner and assignee only.

**Comment by brixxx** [comment]
@azhavoro Thank you very much!
Actually this does not solve it, because especially the assignee should not be able to export a dataset.
Could you maybe provide a workaround to achieve this or to disable the dataset export at all?
Having only the possibility to export annotations would be sufficient.

Thanks!

**Comment by azhavoro** [comment]
@brixxx Disabling of export a dateset functionality doesn't solve your issue as well, because the user should have access to the `api/v1/tasks/3896/data` endpoint (it returns task images) to annotate the task. So, actually the user can download dataset (annotations+images).
But you can modify this method https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/views.py#L631. If you dont need this functionality you can return 403 response for all requests, i.e.:
```
return Response(status=status.HTTP_403_FORBIDDEN)
```

**Comment by brixxx** [comment]
@azhavoro I thought the API would only deliver compressed and lower quality pictures for the annotation process.
However, your solution is what I was looking for.  At least for laypersons the original pictures are then not easily downloadable anymore.
So thanks a lot!

**Comment by arcibiyo** [comment]
@brixxx @azhavoro I used `reduce_task_visibility `but I have multiple jobs in one task. So, i need also **`reduce job visibilty`**. All users can see other assignee jobs in one task. How can I solve this problem? If I solve this problem, ı will not need disabled data export. Thanks.

**Comment by arcibiyo** [comment]
> @brixxx Disabling of export a dateset functionality doesn't solve your issue as well, because the user should have access to the `api/v1/tasks/3896/data` endpoint (it returns task images) to annotate the task. So, actually the user can download dataset (annotations+images).
> But you can modify this method https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/views.py#L631. If you dont need this functionality you can return 403 response for all requests, i.e.:
> 
> ```
> return Response(status=status.HTTP_403_FORBIDDEN)
> ```

changing just 631 line with `return Response(status=status.HTTP_403_FORBIDDEN)`  is enough for this process? I changed like you said  and builded. However when I clicked export data or dump annotation, data is starting to download. I wanna **user can not dowload data and annotation**. Thanks..

**Comment by azhavoro** [comment]
@arcibiyo the file has changed significantly in the last year, you need this method https://github.com/openvinotoolkit/cvat/blob/f8077148701e303e42e70066cbc0b9a610fe344c/cvat/apps/engine/views.py#L631

**Comment by arcibiyo** [comment]
@azhavoro thanks, I solve it but anyone can not export data with this way. I wanna just admin can export data. How can I modify this methods in views.py? Any advice about this topic ?

**Comment by manybodycpa** [comment]
@azhavoro I modified the function as suggested.

Even after rebuilding with

`docker-compose -f docker-compose.yml -f docker-compose.dev.yml build`

a user can export tasks as a dataset in CVAT 1.4 (this workaround worked for me using 1.1). Any advice would be appreciated.

**Comment by NarenZen** [comment]
@azhavoro After changing the functionality to `return Response(status=status.HTTP_403_FORBIDDEN)` in **dataset_export** function, How can I reflect this change in docker. 

After changing the **dataset_export** function., I gave these 2 lines., but It's not reflected in the UI. Still, download happens.

```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
docker-compose up -d
```

**Comment by hoangdung3498** [comment]
> @azhavoro After changing the functionality to `return Response(status=status.HTTP_403_FORBIDDEN)` in **dataset_export** function, How can I reflect this change in docker.
> 
> After changing the **dataset_export** function., I gave these 2 lines., but It's not reflected in the UI. Still, download happens.
> 
> ```
> docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
> docker-compose up -d
> ```

```
docker-compose`` -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.override.yml build
docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.override.yml up -d
```
try it
