### ISSUE TITLE
Cannot upload annotations to large task (due to segments?)

### ISSUE THREAD

**Issue by 4sfaloth** [opencv/cvat#168]
I have a large annotation task (20k images).
I previously had it configured without segments (1-job only) and was successfully able to upload and dump annotations' to it.
For convenience, I've deleted that task and created a new one, exactly the same except that I divided it into 200-images segments. For this new task, I am unable to upload annotations (even if I try to upload the annotations dumped from the task itself!). It always hangs on "Annotation is being saved" for a while, and then gives a gateway timeout error.

Complete error message is:
"
Annotation uploading errors was occured. <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
  <head>
    <title>504 Gateway Timeout</title>
  </head>
  <body>
    <h1>Gateway Timeout</h1>
    <p>The gateway did not receive a timely response from the upstream server or application.</p>
  </body>
</html>
"

I've tried uploading both from the same maching the server is running on and from an external machine, same result.

**Comment by 4sfaloth** [comment]
Ok, this is interesting. I have just found out that apparently the upload succeeded; I mean, if I open the jobs the images are actually annotated according to the uploaded .xml file (just checked some of the first and the last images, and am assuming the rest is fine as well). However, I still get the error above everytime I try to upload annotations (though apparently it succeeds)

**Comment by nmanovic** [comment]
Our upload operation is synchronous and it is the reason of the problem. Also uploading for 200 segments should take too much time. Need to investigate and improve implementation.

**Comment by nmanovic** [comment]
It should be fixed. Could you please check for your case? https://github.com/opencv/cvat/issues/123
