### ISSUE TITLE
Minimum and recommended HW config

### ISSUE THREAD

**Issue by ionyshch-prismsl** [opencv/cvat#17]
Hi,

I'm consider deploying CVAT on AWS. What is minimum / recommended HW config such as number of CPU cores, RAM, disk space?

**Comment by nmanovic** [comment]
Hi @ionyshch-prismsl ,

I cannot say something special here. It depends on your needs. If you need to annotate data by several guys from your team and without TF support it is enough to use m4.large (at least we used it for our internal needs). In production it runs apache with postgres and redis. You can try to use the cheapest hardware and if it doesn't work for you scale it as you like.

Let me close the issue. Don't hesitate to open it again if it doesn't answer your question.
