### ISSUE TITLE
Show image names or video name in UI (now frame numbers only)

### ISSUE THREAD

**Issue by 4sfaloth** [opencv/cvat#170]
I have created a large task (thousands of images), and am trying to generate pre-annotations using an external program. The issue, I do not know which imageId corresponds to each image. I have tried to "Dump Annotations", but that only shows me the Ids for the frames that already have annotations.

Only workaround I can think of is to upload some dummy annotations' file with at least one object per image, and then dumping those annotations to check which imageId corresponds to each image.

 Am I missing something? Is there an easier way to achieve this?

**Comment by nmanovic** [comment]
Hi @4sfaloth,

Currently it works the following way: take all images, sort them by name. In the array first image will have id=0, second id=1, ...

**Comment by 4sfaloth** [comment]
Hi @nmanovic ,

thank you for your fast reply. I was under the impression that might be the case, since I had noticed that in previous datasets.

However, in this one I have:
- Several subfolders (In 'shared' I just selected all the folders, I believe it orders first by folder name then by filename?)
- Unfortunately some of the folders and filenames have funny characters. In particular, there are some that start with a '. I believe this is messing up the ordering (or at least the order did not match the one I "guesses")

Is there really no way as of now to find out the id for each image, through its filename for instance?

**Comment by 4sfaloth** [comment]
Alright, thank you. I'll close the issue

**Comment by 4sfaloth** [comment]
Just to clarify to anyone who might do the same errors as myself: 'lexicographic order' implies that all capital letters **precede** lowercase letters. 
This is important because many file-explorer APIs will iterate over your files in (almost) lexicographic order, the _almost_ being due to that many of them ignore capitalization

**Comment by 4sfaloth** [comment]
@nmanovic is it possible to dive into more detail into the sortering algorithm?
 In particular I highly suspect (though I cannot prove it...) that it does not follow the same ordering as the python .sort method applied to a list of strings (which is also supposed to be lexicographic order). It seems to be the same in ALMOST all cases, but not always. Mind that I am talking about full filenames with complex paths, with special characters such as '_' ,  '.' and '+' in them

**Comment by nmanovic** [comment]
@4sfaloth ,

There are no any details. It is just sort call for a python array of strings: https://github.com/opencv/cvat/blob/4aefbe2630908a7ad20f67e473e5b5e7015e4cec/cvat/apps/engine/task.py#L321

**Comment by 4sfaloth** [comment]
> @4sfaloth ,
> 
> There are no any details. It is just sort call for a python array of strings:
> 
> [cvat/cvat/apps/engine/task.py](https://github.com/opencv/cvat/blob/4aefbe2630908a7ad20f67e473e5b5e7015e4cec/cvat/apps/engine/task.py#L321)
> 
> Line 321 in [4aefbe2](/opencv/cvat/commit/4aefbe2630908a7ad20f67e473e5b5e7015e4cec)
> 
>  filenames.sort()

@nmanovic thanks a lot. I am also using python to sort the filenames before uploading the annotations, so they should be matching now
 There might be something weirder going on on my side then as well; I will try to debug it more exhaustively when I find the time.

**Comment by 4sfaloth** [comment]
@nmanovic 
just one more question. Do you think it is possible python's sort yields different results when running under Windows and Linux?

**Comment by nmanovic** [comment]
@4sfaloth ,

I don't think so.

**Comment by otten456** [comment]
@nmanovic I have an idea for a new feature related to this issue:
Once a task is created you have no information about the relation between the image-IDs and original filenames (except dumping the annotations). It would be nice to have some kind of overview / meta information regarding the created tasks, in order to be aware which images / image-sets are included in a specific task

**Comment by nmanovic** [comment]
It makes sense to implement in new UI. Moved to v1.0.0 version.
