### ISSUE TITLE
Change cursor view in merge/group modes

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#171]
Need to have a visual cue that CVAT in merge/group mode at the moment. One way to provide such cue is to change mouse cursor. For example, it is possible to use "pointer" style (http://www.javascripter.net/faq/stylesc.htm)

**Comment by LiSa20120** [comment]
@nmanovic How do you plan on implementing this? 

Right now, I can think of the following :  
*Highlight shape
*Change cursor style. 
*A Popover

**Comment by bsekachev** [comment]
Resolved in new UI
