### ISSUE TITLE
Update screencasts for CVAT

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#1716]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour

We have a lot of videos for CVAT on GitHub with the old UI. https://github.com/opencv/cvat#screencasts

### Possible Solution

Let's update all of them for v1.0.0. Soon we will have interpolation for polygons and it should be a killer feature.

Use cvat.org demo server to record all videos below.

- [ ] Update [introduction](https://www.youtube.com/watch?v=L9_IvUIHGwM&feature=youtu.be) video
- [ ] Update [annotation mode](https://www.youtube.com/watch?v=6h7HxGL6Ct4&feature=youtu.be) video
- [ ] Update [interpolation mode](https://www.youtube.com/watch?v=U3MYDhESHo4&feature=youtu.be) video
- [ ] Update [attributes annotation mode](https://www.youtube.com/watch?v=UPNfWl8Egd8&feature=youtu.be) video
- [ ] Add tag annotation video
- [ ] Update [segmentation mode](https://www.youtube.com/watch?v=Fh8oKuSUIPs&feature=youtu.be) video
- [ ] Update [tutorial for polygons](https://www.youtube.com/watch?v=XTwfXDh4clI) video
- [ ] Update [semi-automatic segmentation](https://www.youtube.com/watch?v=vnqXZ-Z-VTQ) video
- [ ] Video with interpolation of polygons and polylines
 
### Context

Many users understand how to use CVAT using videos.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@aschernov , @TOsmanov , could you please help with the issue?

**Comment by aschernov** [comment]
@nmanovic , sure. We'll do it.

**Comment by bsekachev** [comment]
@nmanovic @aschernov 
I suppose it has been done. Can we close it?

**Comment by nmanovic** [comment]
@aschernov , could you please  update links in README.md file? Also need to record the tutorial for polygons, etc.

**Comment by TOsmanov** [comment]
@nmanovic , I created PR #1887 for updating links in readme.md

**Comment by bsekachev** [comment]
Solved with #2086
