### ISSUE TITLE
Return user id for REST API user register

### ISSUE THREAD

**Issue by martin-etchart** [opencv/cvat#1730]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Return user id on user creation/register with REST API

### Expected Behaviour

When creating a user via de REST API it would be nice to have the user id returned on the response body.

### Current Behaviour

Currently there is a "key" returned in the response body. Couldn't find in the docs what does that is.

### Possible Solution

Add user id to the response body.

### Context

When creating users we need to get the user ids so we can call the patch and set the permission groups for that user. Currently the only way to do that is by getting all the users list and searching that list by username.

### Your Environment

- Git hash commit (`git log -1`): `47470b84703bfc7bee243b2e7c1ae830ad587885`
- Docker version `docker version` : Docker 19.03.8
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS Mojave
- Code example or link to GitHub repo or gist to reproduce problem:
Register `test_user`:
```
curl -X POST "http://localhost:8080/api/v1/auth/register" -H "accept: application/json" -H "Content-Type: application/json" -H "X-CSRFToken: tyzEYPiKULyv7ctbirrDtRhVLUDLizrZ7SXNdDyBMANNrrBE2bXPihMevi2K0UZI" -d "{ \"username\": \"test_user\", \"password1\": \"hash8080\", \"password2\": \"hash8080\"}"
```
Example  response body:
```
{
  "key": "db2e1b4b43630224a0a8b032a72dccabfb2466b8"
}
```
### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by martin-etchart** [comment]
Maybe not just the id but similarly to a new task creation, the full object of the created user could be returned.

**Comment by inverniz** [comment]
Hi, I was wondering if this issue has really been closed? I see it is associated to a pull request with a different subject, and by printing the output of the `auth/register`  API call it doesn't seem like the user_id is returned. Looking at the [source code here ](https://github.com/openvinotoolkit/cvat/blob/7c5d71d228ed6cb800a8db09d2da1eb1a6c411af/cvat-core/src/api.js#L132) I get the same impression. Thank you for your answer!
