### ISSUE TITLE
All-green images in the segmentation class folder when dumping annotations

### ISSUE THREAD

**Issue by xiangyu19** [opencv/cvat#1736]
I got all-green images in the SegmentationClass folder while correct colors for background and instances in SegmentationObject folder. When I check the labelmap.txt, I found it was:
# label:color_rgb:parts:actions
leaf:48,112,32::
background:0,0,0::

While it was supposed to be following to get the correct masks in the SegmentationClass folder:
# label:color_rgb:parts:actions
background:0,0,0::
leaf:48,112,32::

Could you please tell me how to make the SegmentationClass and labelmap.txt work?

**Comment by zhiltsov-max** [comment]
Do you have `background` class in the task?

**Comment by xiangyu19** [comment]
No, I don't have a separate

> Do you have `background` class in the task?

No. I have only one class, leaf.

**Comment by xiangyu19** [comment]
I think I figured it out. I set one of the instances as foreground manually and then all masks worked. It seems that it will regard the annotated instances as background by default ...

**Comment by zhiltsov-max** [comment]
Should be fixed already.
