### ISSUE TITLE
can't build because of two path problems

### ISSUE THREAD

**Issue by Chester-zZz** [opencv/cvat#1749]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

docker-compose build success
### Current Behaviour

docker-compose build failed. information:

RROR in ./src/cvat-canvas-wrapper.ts
Module not found: Error: Can't resolve 'cvat-canvas/src/typescript/canvas' in '/tmp/cvat-ui/src'
 @ ./src/cvat-canvas-wrapper.ts 4:0-126 7:11-21 7:28-38 7:45-55 10:0-106 10:0-106 10:0-106 10:0-106 10:0-106
 @ ./src/reducers/about-reducer.ts
 @ ./src/reducers/root-reducer.ts
 @ ./src/index.tsx

ERROR in ./src/cvat-core-wrapper.ts
Module not found: Error: Can't resolve 'cvat-core/src/api' in '/tmp/cvat-ui/src'
 @ ./src/cvat-core-wrapper.ts 4:0-38 5:13-18
 @ ./src/components/cvat-app.tsx
 @ ./src/index.tsx
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!./src/index.html 729 bytes {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cvat-ui@1.3.1 build: `webpack --config ./webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cvat-ui@1.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-18T11_57_49_009Z-debug.log
ERROR: Service 'cvat_ui' failed to build: The command '/bin/sh -c ls /tmp/cvat-ui/src && npm run build' returned a non-zero code: 2

### Possible Solution

change    cvat-ui/src/cvat-canvas-wrapper.ts
import {
    Canvas,
    CanvasMode,
    CanvasVersion,
    RectDrawingMethod,
    CuboidDrawingMethod,
} from 'cvat-canvas/src/typescript/canvas';

to

import {
    Canvas,
    CanvasMode,
    CanvasVersion,
    RectDrawingMethod,
    CuboidDrawingMethod,
} from '../../cvat-canvas/src/typescript/canvas';

change   cvat-ui/src/cvat-core-wrapper.ts 

import _cvat from 'cvat-core/src/api';

to

import _cvat from '../../cvat-core/src/api';

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@Chester-zZz 

Hi, Cannot reproduce the issue from the latest commit in develop branch

**Comment by Chester-zZz** [comment]
> @Chester-zZz
> 
> Hi, Cannot reproduce the issue from the latest commit in develop branch

After modification of the path prefix, the docker-compose build successfully.

I'm not familiar with node and npm, I just modified the paths according to the error information.

Anyway, maybe it's a bug, maybe not...
