### ISSUE TITLE
Stuff semantic segmentation

### ISSUE THREAD

**Issue by gaussiangit** [opencv/cvat#1751]
How do I load coco stuff format ? 
https://github.com/nightrome/cocostuffapi/blob/master/annotations/stuff_examples.json

Is it supported. ?

**Comment by zhiltsov-max** [comment]
It is not supported yet. Regarding masks, Only PASCAL masks and COCO instances can be imported.

**Comment by gaussiangit** [comment]
@zhiltsov-max coco RLE support is not there at all ? Only polygon type works ?

**Comment by zhiltsov-max** [comment]
RLE instance masks are supported.

**Comment by gaussiangit** [comment]
@zhiltsov-max So you mean if I make stuff masks as instance masks by making iscrowd = 1, it should work for stuff/semantic segmentation ? Although it did not .

**Comment by zhiltsov-max** [comment]
Given the `detection` and `stuff` formats are identical, this could work, but it wasn't tested.

**Comment by gaussiangit** [comment]
@zhiltsov-max 

Got this exception when trying to do segmentation with RLE as mentioned above.  
https://github.com/opencv/cvat/blob/b706546435ec7d0abc9802983fff3c9c3997d970/cvat/apps/engine/views.py#L467

**Comment by zhiltsov-max** [comment]
Can you provide the full error message?

**Comment by gaussiangit** [comment]
2020-06-22 21:19:10,089 DEBG 'runserver' stderr output:
[Mon Jun 22 21:19:10.089498 2020] [wsgi:error] [pid 330:tid ] [] [2020-06-22 21:19:10,085] ERROR cvat.server.task_3: cannot get requested data type: preview, number: None, quality: compressed

2020-06-22 21:19:10,089 DEBG 'runserver' stderr output:
[Mon Jun 22 21:19:10.089587 2020] [wsgi:error] [pid 330:tid 139883975116544] [] Traceback (most recent call last):
[Mon Jun 22 21:19:10.089617 2020] [wsgi:error] [pid 330:tid 139883975116544] []   File "/home/django/cvat/apps/engine/views.py", line 439, in data
[Mon Jun 22 21:19:10.089622 2020] [wsgi:error] [pid 330:tid 139883975116544] []     frame_provider = FrameProvider(db_task.data)
[Mon Jun 22 21:19:10.089625 2020] [wsgi:error] [pid 330:tid 139883975116544] []   File "/home/django/cvat/apps/engine/frame_provider.py", line 77, in __init__
[Mon Jun 22 21:19:10.089629 2020] [wsgi:error] [pid 330:tid 139883975116544] []     reader_class[db_data.compressed_chunk_type],
[Mon Jun 22 21:19:10.089635 2020] [wsgi:error] [pid 330:tid 139883975116544] [] AttributeError: 'NoneType' object has no attribute 'compressed_chunk_type'
[Mon Jun 22 21:19:10.089722 2020] [wsgi:error] [pid 330:tid 139883975116544] [

2020-06-22 21:19:10,090 DEBG 'runserver' stderr output:
[Mon Jun 22 21:19:10.090088 2020] [wsgi:error] [pid 330:tid 139883975116544] [] ERROR:cvat.server.task_3:cannot get requested data type: preview, number: None, quality: compressed

2020-06-22 21:19:10,090 DEBG 'runserver' stderr output:
[Mon Jun 22 21:19:10.090180 2020] [wsgi:error] [pid 330:tid 139883975116544] [] Traceback (most recent call last):
[Mon Jun 22 21:19:10.090209 2020] [wsgi:error] [pid 330:tid 139883975116544] []   File "/home/django/cvat/apps/engine/views.py", line 439, in data

2020-06-22 21:19:10,090 DEBG 'runserver' stderr output:
[Mon Jun 22 21:19:10.090288 2020] [wsgi:error] [pid 330:tid 139883975116544] []     frame_provider = FrameProvider(db_task.data)
[Mon Jun 22 21:19:10.090407 2020] [wsgi:error] [pid 330:tid 139883975116544] []   File "/home/django/cvat/apps/engine/frame_provider.py", line 77, in __init__

2020-06-22 21:19:10,091 DEBG 'runserver' stderr output:
[Mon Jun 22 21:19:10.090987 2020] [wsgi:error] [pid 330:tid 139883975116544] []     reader_class[db_data.compressed_chunk_type],

2020-06-22 21:19:10,091 DEBG 'runserver' stderr output:

**Comment by zhiltsov-max** [comment]
@azhavoro, take a look.

**Comment by zhiltsov-max** [comment]
This error probably has nothing to do with annotation formats.

**Comment by gaussiangit** [comment]
There is no other log, I do not see annotations in case of problem with data itself. COCO file is verified as well. I am missing something.

**Comment by bsekachev** [comment]
@azhavoro Could you please look at the issue?

**Comment by azhavoro** [comment]
I believe logs is not related with annotation uploading, so let's close this issue.
@gaussiangit Feel free to reopen if the issue is still relevant for you.

**Comment by andreaceruti** [comment]
@gaussiangit Have you solved the problem? I need to do the same and I want just a binary mask
