### ISSUE TITLE
Alternative way of adding models

### ISSUE THREAD

**Issue by PMazarovich** [opencv/cvat#1752]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
- [x] Discussed this problem in gitter with developer

### Expected Behaviour
It would be useful to have a possibility of adding a custom model without any .bin .xml files, just with the python script (as example).

### Context
Currently I have some python script, that generates annotations for the provided video. Program  uses as an input parameter a path to a videofile (or to a folder with paths to images extracted from video). Outputs shape(s) for the label.

**Comment by nmanovic** [comment]
It will be supported. I'm adding such feature right now: https://github.com/opencv/cvat/pull/1767
