### ISSUE TITLE
Bug: Polygon must have at least 3 points

### ISSUE THREAD

**Issue by cinjon** [opencv/cvat#1769]
I am using cvat.org to test out the service. I used the MaskRCNN feature to annotate a video. After completion, I went into the job and found that I could not open it. I get this error in the console:

`cvat-app.tsx:192 Error: Polygon must have at least 3 points, but got 2`

I also see the same error in the window:

`Error: Polygon must have at least 3 points, but got 2`

However, I can open it in the Old UI no problem. This seems like a bug.

**Comment by bsekachev** [comment]
@cinjon 

Could you provide annotations data that you get from server to client? 
I suspicious there are wrong polygons.

**Comment by cinjon** [comment]
I just tried dumping as COCO 1.0 Annotations and got the error:

```
Could not dump annotations for the task 1690
Error: Request failed with status code 500. "AssertionError: Wrong polygon points: [395.0, 85.5, 395.0, 85.5]\n".
```

**Comment by bsekachev** [comment]
@cinjon 

It seems there is a bug in ``MaskRCNN``. Polygon mustn't have less then 3 points. But the algorithm have returned the wrong result.
Another idea is instead of the error we might output a warning and continue working in UI. 

Let's look into this.

**Comment by bsekachev** [comment]
Speaking about dumping. @zhiltsov-max what do you think? Should we have the assert?

**Comment by zhiltsov-max** [comment]
We have wrong annotations, assert is here, and it fires. Moreover, these annotations are incompatible with the official COCO python API.

**Comment by savan77** [comment]
I am also facing the same issue. The annotations were generated by the MaskRCNN model. Did you guys find any workaround?  @zhiltsov-max @bsekachev

**Comment by zhiltsov-max** [comment]
@savan77, there is 7 annotations with less than 6 values: 52, 100, 154, 176, 184, 285, 299. You're right about the function in COCO API.

**Comment by rushtehrani** [comment]
Is there a PR for this already? Looked through the PRs but couldn’t see anything. Our workaround right now is to remove the check in UI code.

**Comment by zhiltsov-max** [comment]
@savan77, actually, lambda functions have already come. It would be great, if you could prepare a PR with this fix. I also think that it can be interesting to check for small area polygons (e.g. < 1 px^2), instead of just 4-value arrays.

**Comment by savan77** [comment]
@zhiltsov-max That's great. I think it will be easier to just check for length not only logically but also computationally. Let me know what do you think, happy to send a pr.

**Comment by zhiltsov-max** [comment]
@savan77, it will be enough.

**Comment by bsekachev** [comment]
Can this issue be closed now?
