### ISSUE TITLE
Display track segments on the frame line

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#1796]
It could be useful to display track visibility segments (where track is not `outside`) on the frame line. This would simplify task navigation and provide essential hints to the user.

How this could look like:
When track is selected we can see this
![track_segments_example](https://user-images.githubusercontent.com/13832349/85507682-6ee2d680-b5fb-11ea-92ce-686a6ff24408.jpg)

**Comment by nmanovic** [comment]
The feature is connected with 1D intervals.

**Comment by nmanovic** [comment]
https://archive.mpi.nl/tla/elan
