### ISSUE TITLE
Extend contributing.md

### ISSUE THREAD

**Issue by ionyshch-prismsl** [opencv/cvat#18]
Hi,

Could you, please, describe / suggest development / testing steps.
In particular, how would one perform edit - update - run (debug) cycle for both server and client parts.

**Comment by bsekachev** [comment]
Good idea,  
I will prepare step by step manual at near time.

**Comment by bsekachev** [comment]
So, I have tried next steps on clean Ubuntu 18.04. You need:
* Install some dependencies and applications:
```bash
sudo apt-get install curl redis-server python3-dev python3-pip python3-venv libldap2-dev libsasl2-dev -y
``` 
* Install [Visual Studio Code](https://code.visualstudio.com/docs/setup/linux) for development
```bash
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt-get install code -y
```

* Perform CVAT installation steps 
```bash
git clone https://github.com/opencv/cvat
cd cvat && mkdir logs keys .vscode
python3 -m venv .env
. .env/bin/activate
pip install --upgrade wheel
pip install -r cvat/requirements/development.txt 
python manage.py migrate
python manage.py collectstatic
```
* Put launch.json ([launch.zip](https://github.com/opencv/cvat/files/2237950/launch.zip)) to cvat/.vscode dir

* Create super user and run Visual Studio Code from virtual environment
```bash
python manage.py createsuperuser
code
```

In visual studio code:
1) Go to extensions and install "Debugger for Chrome" (also you can debug it directly in the browser . It more convenience for me) and Python. Reload.
2) Open cvat dir (Ctrl+O and open), select "CVAT Debugging" configuration and press F5. 
3) You are great!

We will update contributing.md in near future.

**Comment by raunilillemets** [comment]
I had some problems following the instructions; You might want to go over the instructions.

OS: Ubuntu 19.04

1) When I ran the following commands:
pip install -r cvat/requirements/development.txt`
I got a lot of errors related to installing Pillow:

> 
> `writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
>   running build_ext
>   
>   The headers or library files could not be found for zlib,
>   a required dependency when compiling Pillow from source.
>   
>   Please see the install instructions at:
>      https://pillow.readthedocs.io/en/latest/installation.html

Following the instructions [here](https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux) helped:
`sudo apt install libjpeg8-dev zlib1g-dev`

2) Running "cvat.js debug" in Visual Code gave me:
"cannot find runtime node on PATH. Make sure to have node installed"

Installing node and npm helped.

3) Running "cvat.js debug" in Visual Code now gives me:

```
/usr/bin/node --nolazy --inspect-brk=9230 src/api.js
Debugger listening on ws://127.0.0.1:9230/d24de8ef-920f-4bd3-9a6f-72c1f65532d9
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'platform'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /prog/cvat/cvat-core/src/exceptions.js:11:22
    at Object.<anonymous> (/prog/cvat/cvat-core/src/exceptions.js:272:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Waiting for the debugger to disconnect...
Error: Cannot find module 'platform'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /prog/cvat/cvat-core/src/exceptions.js:11:22
    at Object.<anonymous> (/prog/cvat/cvat-core/src/exceptions.js:272:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

Any ideas?

PS. cvat/.vscode/launch.json file already existed in Git, this step is unnecessary.

**Comment by nmanovic** [comment]
Hi @raunilillemets , we cannot support different OS for development. At the moment internally all engineers are using Ubuntu 18.04 (LTS). If you want to use Ubuntu 19.04 it is necessary to investigate on your own.

@bsekachev , could you please help with cvat.js?

**Comment by bsekachev** [comment]
@raunilillemets 
Before you can debug cvat-core.js you need to install all node.js dependencies. 
```cd cvat-core && npm install```

**Comment by raunilillemets** [comment]
Thanks @bsekachev. 

Well, some of things which I mentioned are likely also relevant on Ubuntu 18.04. 
The first issue seems to affect different versions of Ubuntu, as mentioned [here](https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux).

About the second and third issue - the Contributing.MD file needs to be updated to include this step:
`cd cvat-core && npm install`

**Comment by bsekachev** [comment]
@raunilillemets 
Try [this](https://stackoverflow.com/questions/54304411/nodejs-debugging-error-no-such-module-http-parser)

**Comment by raunilillemets** [comment]
The suggestions there did not help, still had the same issues.

But I noticed that there are 2 really similar profiles:
"cvat.js debug (cvat)"
"debugging (cvat)"

I was using the first one and getting errors; I tried the second one and it seems to work (at least I got into the login page). I will continue using the second one.
