### ISSUE TITLE
Loading images and save segmentation on a server

### ISSUE THREAD

**Issue by seyiqi** [opencv/cvat#1801]
Hi,

First, thanks for offering this impressive tool!

I am hosting cvat on a server as a web application and access the app through local computer. All my images are on the server. However, the upload option is either from the local computer or from a url. I am wondering if there is a way to automatically upload images from the server where cvat is hosted. There are around 1TB of images so I probably won't be able to load all of them into the memory.

Besides, once the segmentation is done, I am wondering where is the segmentations are saved? I assume that the original segmentation (before export) files are saved somewhere in the machine where cvat is hosted.

Thanks for your help! 

Best,

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi, speaking about getting files from the server where CVAT is hosted, we have such the feature: https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path

**Comment by bsekachev** [comment]
It mounts server share and you can use it to files uploading: 

![Screenshot from 2020-06-25 13-37-55](https://user-images.githubusercontent.com/40690378/85704570-1853c600-b6e9-11ea-9ba7-eb3f5aeaa1be.png)

**Comment by bsekachev** [comment]
Segmentation cache file that you dump is stored inside ``cvat_data`` volume that can be accessed using ``cvat`` container.
In filesystem it has path something like that: ``/home/django/data/tasks/<task_id>/export_cache``

If you asked exactly about where segmentation is stored before any dump, than answer is: it stores in ``postgres`` database.
