### ISSUE TITLE
when trying to connect getting 404

### ISSUE THREAD

**Issue by zeevmindali** [opencv/cvat#1806]
Dear all,

I using ubuntu 18.04 that is hosted on ibm cloud 
followed each step of the install manual
when I try to open the browser with chrome, getting 404 error code.
tried to load the default nginx docer, working fine.

what I need to check to solve the issue?

**Comment by azhavoro** [comment]
@zeevmindali Hi, please don't ignore the issue template and provide CVAT version, containers logs, compose config, etc. Without that it's hard to help you.

**Comment by azhavoro** [comment]
@zeevmindali Can I close this issue too?

**Comment by zeevmindali** [comment]
yes, please do, solved
