### ISSUE TITLE
Tensorflow Problems with TF Annotations

### ISSUE THREAD

**Issue by BenjiSchlotter** [opencv/cvat#1809]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Following the guide at https://github.com/opencv/cvat/blob/develop/components/tf_annotation/README.md
i expected to run the model on a task without problems.

### Current Behaviour
`docker logs cvat` shows the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.6/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/tf_annotation/views.py", line 213, in create_thread
    raise ex
  File "/home/django/cvat/apps/tf_annotation/views.py", line 196, in create_thread
    result = run_tensorflow_annotation(image_list, labels_mapping, TRESHOLD)
  File "/home/django/cvat/apps/tf_annotation/views.py", line 109, in run_tensorflow_annotation
    od_graph_def = tf.GraphDef()
AttributeError: module 'tensorflow' has no attribute 'GraphDef'
```

This error suggests that the change of tensorflow version to 2.2.0 is to blame for that. I verified that this problem does not exists with tensorflow version 1.14.

### Possible Solution
There a two ways to fix this. We can update the code in `home/django/cvat/apps/tf_annotation/` or we downgrade the tensorflow version again. 

### Steps to Reproduce (for bugs)
1. build cvat with tf_annotation
2. create a task with a label that the model understands
3. run the model for the task
4. there is no indication of error in the UI. But the cvat logs show the above error

### Context
In the end I want to run custom tensorflow models to detect objects in images. 

### Your Environment

- Git hash commit (`git log -1`): db29291d43172aa33194a6fb28f8000309d38344
- Docker version `docker version`: 19.03.12, build 48a66213fe
- Are you using Docker Swarm or Kubernetes?
- Operating System and version: Ubuntu 18.04

**Comment by nmanovic** [comment]
It will be fixed https://github.com/opencv/cvat/pull/1767
