### ISSUE TITLE
About labels name

### ISSUE THREAD

**Issue by Eric-Zhang1990** [opencv/cvat#181]
@nmanovic  When I just add one label like "wine bottle" which has a space between 2 words, I add "wine bottle" into Labels on interface, cvat can adds it into label box, but the first character of word "wine" will become uppercase letter, like "Wine", how can I set my label which has a space? Thanks.

**Comment by Eric-Zhang1990** [comment]
@nmanovic Yes, thank you for your kind reply. There is another question about labels: the order of labels is  not consistent with the original input, can you tell me where I can make the order of labels fixed? Thank you.

**Comment by nmanovic** [comment]
@Eric-Zhang1990 ,

You cannot at the moment. We have a similar request from an internal team.  Probably it will be fixed in the future.

**Comment by Eric-Zhang1990** [comment]
@nmanovic  Ok, thank you very much.
