### ISSUE TITLE
Logout button not working

### ISSUE THREAD

**Issue by kleysonr** [opencv/cvat#1810]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)

### Expected Behaviour
When clicking on the Logout but, get the user session closed.

### Current Behaviour
When clicking on the Logout but, nothing is happening.

### Steps to Reproduce (for bugs)
Follow the default installation process.

### Your Environment
- Git hash commit (`git log -1`):
commit db29291d43172aa33194a6fb28f8000309d38344 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Andrey Zhavoronkov <41117609+azhavoro@users.noreply.github.com>
Date:   Thu Jun 25 22:28:01 2020 +0300

    added hash to js bundle names (#1803)

- Docker version `docker version` (e.g. Docker 17.0.05):
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

- Are you using Docker Swarm or Kubernetes?
No

- Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04.04

- Other diagnostic information / logs:
  No errors in the cvat logs
  Server version: 1.1
  Core version: 3.1.0
  Canvas version: 1.2.1
  UI version: 1.4.2

**Comment by ijalalfrz** [comment]
i have same issue on windows 10, does your issue resolved?

**Comment by lizhming** [comment]
Check this : https://github.com/opencv/cvat/pull/1812
