### ISSUE TITLE
Tasks lost

### ISSUE THREAD

**Issue by apoorvajoshi92** [opencv/cvat#1813]
Saving a job causes the following error:
Couldn't to save the job. Errors occured: Could not make create annotations. Code: 401. Message: {"detail":"Authentication credentials were not provided."}. Please report the problem to support team immediately.

After signing in again I lost all my tasks

**Comment by azhavoro** [comment]
Hi, could you clarify: have all your tasks or annotations been deleted?

**Comment by apoorvajoshi92** [comment]
Yes all my tasks are lost

> Hi, could you clarify: have all your tasks or annotations been deleted?

Yes all my tasks are lost

**Comment by bsekachev** [comment]
@apoorvajoshi92 does your account have admin privileges?

**Comment by apoorvajoshi92** [comment]
How to check.. I am not sure

**Comment by bsekachev** [comment]
@apoorvajoshi92 

Go to ``<cvat_origin>/admin``

**Comment by apoorvajoshi92** [comment]
Django administration

**Comment by bsekachev** [comment]
@apoorvajoshi92 
What do you mean?

**Comment by apoorvajoshi92** [comment]
I got a administration  panel

**Comment by apoorvajoshi92** [comment]
http://localhost:8080/admin/

**Comment by apoorvajoshi92** [comment]
> @apoorvajoshi92
> 
> Go to `<cvat_origin>/admin`

Where do I find this

**Comment by bsekachev** [comment]
@apoorvajoshi92 

Do you have access to administration panel?

**Comment by apoorvajoshi92** [comment]
Nope

**Comment by bsekachev** [comment]
> Nope

Try to authorize with admin account. If you don't have it, somebody with admin account should give you access to tasks. I suppose they are hidden.

**Comment by apoorvajoshi92** [comment]
And if IRS a superuser admin account.. where can I get it

**Comment by apoorvajoshi92** [comment]
It has admin rights

**Comment by apoorvajoshi92** [comment]
That's my admin account.. I have lost all my tasks. How canni get back

**Comment by bsekachev** [comment]
@azhavoro  Could you please look into this? Tasks cannot be just removed themselves.

**Comment by azhavoro** [comment]
@apoorvajoshi92 Can you see any tasks on the http://localhost:8080/admin/engine/task/ page?

**Comment by apoorvajoshi92** [comment]
There are 3 tasks which are generated after the issue was noticed... all the previous tasks are not visible

**Comment by azhavoro** [comment]
@apoorvajoshi92 Tasks cannot be deleted automatically,it's possible only with user actions with UI or REST API. Tasks can also be deleted if you deleted docker volumes. Please attach logs form `cvat` and `cvat_db` containers: `docker logs cvat > cvat.log`, `docker logs cvat_db > db.log`.

**Comment by apoorvajoshi92** [comment]
[cvat.log](https://github.com/opencv/cvat/files/4870565/cvat.log)
[db.log](https://github.com/opencv/cvat/files/4870566/db.log)

**Comment by azhavoro** [comment]
@apoorvajoshi92 Unfortunately your log is too short and has events only on June 3, looks like you recreated CVAT containers.
What is output of the following commands `docker exec -it cvat bash -c 'ls ~/data'` and `docker volume inspect cvat_cvat_data`?

**Comment by bsekachev** [comment]
I will close the issue for now. Do not hesitate reopen it if you still have questions
