### ISSUE TITLE
CVAT new UI: object's details menu settings

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1836]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The object's details menu should have a setting to automatically hide or unhide it for all objects, including new.
### Current Behaviour

Object's details are hidden by default. We have to make one more click every time to enter some attributes.
It's inconvenient.
![details](https://user-images.githubusercontent.com/45849884/86366795-e3fd7e00-bc83-11ea-83b4-0697553feb2d.JPG)
![details_1](https://user-images.githubusercontent.com/45849884/86366803-e6f86e80-bc83-11ea-897f-f5373c627220.JPG)

### Possible Solution

Add a setting "always show objects details" into "settings". This setting should be enabled for new objects too.
 It'll let annotate attributes quickly.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Settings option "always show objects details" already exist. I can suggest another solution: 
If the button "expand all" was pressed, all new objects are created with opened details. If the button "collapse all" was pressed, all new objects are created with closed details.
![image](https://user-images.githubusercontent.com/40690378/86441173-75b4cc00-bd14-11ea-98fd-1556686ab08b.png)

**Comment by aschernov** [comment]
I think it could be a good solution. Thank you.
