### ISSUE TITLE
Boxes for objects defined as outside not redrawn when object back in field of view

### ISSUE THREAD

**Issue by csgwon** [opencv/cvat#1838]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

For objects that have gone out of the field of view and marked with "Select outside property", the bounding box does not show correctly (aside from the very first time) when the object returns into the field of view.

### Expected Behaviour
I believe the box should be visible when the object is in the field of view.

### Current Behaviour
When an object goes outside the field of view, I click the "Select outside property" button, and the bounding box disappears. When I move the frames backwards the first time, the bounding box will reappear. If I repeat this again (go forward until it disappears, and go backwards again), the box no longer shows up.

If I reload the page, the box shows up again. But if I advance to the point where the object goes outside the field of view, and then move backward again, the box does not come back.

### Steps to Reproduce (for bugs)

1. Create a bounding box for an uploaded video
2. Advance a few frames, and move the bounding box
3. Advance one frame, and select the "Select outside property" button for the bounding box
4. Advance frame one position (bounding box should still be gone)
5. Move back 2 frames (bounding box will reappear)
6. Move forward 1-2 frames (bounding box disappears)
7. Move back 2-3 frames (bounding box will not reappear)

### Context
I have to continually reload to double check annotations for objects that exit the field of view.

### Your Environment

- Git hash commit (`git log -1`): d293876a6f72ff0d5ce6514b9bd4b4b4a578a13d
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 19.03.12, build 48a66213fe
- Are you using Docker Swarm or Kubernetes? Docker Swarm
- Operating System and version (e.g. Linux, Windows, MacOS): Linux (Ubuntu 18.04)
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@csgwon 

I suppose the issue has been fixed with #1834. Could you please check?

**Comment by bsekachev** [comment]
Resolved with #1834
