### ISSUE TITLE
Segmentation Annotation 

### ISSUE THREAD

**Issue by gaussiangit** [opencv/cvat#1843]
If we use auto segmentation, how do I correct generated polygon points ? It is very tedious task to correct the predicted annotations as I can not select multiple points. Is there a way to deal with this problem ? Like group small regions or eraser or paint brush like tool ?

**Comment by bsekachev** [comment]
Hi @gaussiangit, in the newest version you can edit polygons in following ways:

1. Move points one by one
1. Move the whole polygon
1. Delete a point of a polygon (Ctrl + Click on a point)
1. Redraw a border of a polygon (Shift + Click on a point)
1. Redraw a whole polygon from scratch (Shift + N when a polygon is selected)

We do not support tools like brush. There were ideas to support masks as is (not like polygons) but we do not expect it will have been done in the nearest future. If you have other ideas how we could significantly accelerate the process and you are ready to provide details, you are welcome
