### ISSUE TITLE
Object detectors in Demo at cvat.org fail to run

### ISSUE THREAD

**Issue by dschoerk** [opencv/cvat#1846]
I was testing the "Automatic Annotation" function in your demo at cvat.org. Created a task, uploaded some images and defined a "car" class, which should work for both MaskRCNN and FasterRCNN. Then selected Actions > Automatic Annotation. MaskRCNN. A progress bar is showing up, but after a couple of seconds the below error message is printed to the browsers console. Choosing FasterRCNN does not even show a progress bar, nothing happens at all. 

Error: Inference status for the task 2925 is failed. AttributeError: in user code:

    /home/django/Mask_RCNN/mrcnn/model.py:390 call  *
        roi_level = log2_graph(tf.sqrt(h * w) / (224.0 / tf.sqrt(image_area)))
    /home/django/Mask_RCNN/mrcnn/model.py:341 log2_graph  *
        return tf.log(x) / tf.log(2.0)

    AttributeError: module 'tensorflow' has no attribute 'log'

**Comment by bsekachev** [comment]
@azhavoro Looks like the attribute is unavailable since ``TF 2.0``. According to requirements we use ``2.2``. 
Implementation of ``Mask_RCNN`` we use, uses ``tensorflow>=1.3.0 (1.*)``
