### ISSUE TITLE
How to update UI when I change it in cvat-ui?

### ISSUE THREAD

**Issue by tingfengwanxiao** [opencv/cvat#1848]
hello,I use windows and install cvat,I changed  the display of UI in cvat-ui.But after I use the command docker-compose build,the UI doesn't change,How can I do to get the new UI?Thank you.

**Comment by bsekachev** [comment]
Hi, @tingfengwanxiao 

Try ``docker-compose up --build``.
I would recommend to use once ``shift+f5`` to update page in chrome. It reloads page from server instead of using a cached version.

**Comment by tingfengwanxiao** [comment]
exactly，shift+f5 works,but every time I start the task and it display the old, I will use shift+f5 to load no-cache UI,do you know how to update it,then it will be better.

**Comment by bsekachev** [comment]
@tingfengwanxiao 

I am not sure that I understand you.
You used ``docker-compose build`` to update UI. But it is not enough. The command ``build`` makes docker image. The command ``up`` makes/updates docker container. 

After that only recommendation to use ``shift + f5`` once.
