### ISSUE TITLE
Visibility is always set to 0 and how to set confidence to 0

### ISSUE THREAD

**Issue by igygi** [opencv/cvat#1856]
Hi, 

From my understanding, when making track annotations, the "occluded property" is mapped to visibility (e.g. if occluded, visibility = 0 and if not occluded, visibility = 1). 

But when I download the annotations (MOT 1.1 format), all of my visibility scores (last column) are set to 0. Is this a bug or am I missing something? 

Moreover, how do I set confidence to 0? I'd like to do this because in MOT evaluation, a confidence = 0 tells the evaluator to disregard an entry.

Thank you.

**Comment by zhiltsov-max** [comment]
Hello, you may find [this fragment of code](https://github.com/opencv/cvat/blob/develop/datumaro/datumaro/plugins/mot_format.py#L301-L309) interesting for you.

Basically, you should be able to use the `visibility` attribute to specify some floating point value, or just use `occluded` property to stick to just `0` or `1`. To control `confidence` you can try to use `ignored` checkbox attribute.

**Comment by igygi** [comment]
This is exactly what I need. Thank you!
