### ISSUE TITLE
change the UI to show the scale

### ISSUE THREAD

**Issue by tingfengwanxiao** [opencv/cvat#1860]
Hello,I want to show current scale(this.geometry.scale) attribute value in top-bar,how can I change the demo in top-bar or do you have a good idea?

**Comment by tingfengwanxiao** [comment]
![photo](https://user-images.githubusercontent.com/49578058/86767847-2efe0380-c07f-11ea-9d8f-59c13c625f96.png)

**Comment by bsekachev** [comment]
@tingfengwanxiao 

Hi, I can suggest followings:
1. Create an event in ``cvat-canvas`` component that notify about changing scale
1. Subscribe for this event in ``cvat-ui``
1. Raise an action after the value is changed and update Redux storage
1. Display this value in ``cvat-ui`` (where you want) using React ``props``
So, value will update immediately after it is changed in ``cvat-canvas``

Hope it will help you. I will close the issue for now. Do not hesitate reopen it if you have other questions

**Comment by tingfengwanxiao** [comment]
if I enlarge the image about 10 times，whether the value of geometry.scale change to 10?Can I call this value directly to show current scale of canavas?

**Comment by bsekachev** [comment]
@tingfengwanxiao 

> if I enlarge the image about 10 times，whether the value of geometry.scale change to 10
No. Each ``mousewheel`` event changes scale in 5/6 or 6/5 times (as far as I remember). Limit values are 0.1 and 10.

> Can I call this value directly to show current scale of canvas?
Not sure I understand you here.

**Comment by tingfengwanxiao** [comment]
ok,thank you,I understand.

**Comment by tingfengwanxiao** [comment]
> @tingfengwanxiao
> 
> Hi, I can suggest followings:
> 
> 1. Create an event in `cvat-canvas` component that notify about changing scale
> 2. Subscribe for this event in `cvat-ui`
> 3. Raise an action after the value is changed and update Redux storage
> 4. Display this value in `cvat-ui` (where you want) using React `props`
>    So, value will update immediately after it is changed in `cvat-canvas`
> 
> Hope it will help you. I will close the issue for now. Do not hesitate reopen it if you have other questions
//---------------------------------------------------------------------------------------------------------------------------
Disturb you again,in your step 2,Subscribe for this event in `cvat-ui`,I meet problem.I finish step1,but I still don't know where to import the subscribe and how to use it to listen the notify in step 1.

**Comment by bsekachev** [comment]
@tingfengwanxiao 

Look at ``cvat-ui/src/components/canvas-wrapper.tsx``. A lot of examples there how to listen events from canvas. 
And you can look at ``cvat-canvas/src/typescript/canvasView.ts`` to see how you can dispatch canvas events.
For example you can see how event ``canvas.setup`` works. It is dispatched in ``canvasView`` and listened in ``canvas-wrapper.tsx``

**Comment by tingfengwanxiao** [comment]
> @tingfengwanxiao
> 
> Hi, I can suggest followings:
> 
> 1. Create an event in `cvat-canvas` component that notify about changing scale
> 2. Subscribe for this event in `cvat-ui`
> 3. Raise an action after the value is changed and update Redux storage
> 4. Display this value in `cvat-ui` (where you want) using React `props`
>    So, value will update immediately after it is changed in `cvat-canvas`
> 
> Hope it will help you. I will close the issue for now. Do not hesitate reopen it if you have other questions

//-----------------------------------------------------------------------------------------------------------------------------
Hello,How to add a new value in Redux storage and update Redux storage?
