### ISSUE TITLE
import ts file from other folder

### ISSUE THREAD

**Issue by tingfengwanxiao** [opencv/cvat#1867]
Hello,I use demo 
import { CanvasModel,CanvasModelImpl } from 'cvat-canvas/src/typescript/canvasModel';
in cvat-ui/src/utils/math.ts, but I got 
ERROR in ./src/utils/math.ts
Module not found: Error: Can't resolve 'cvat-canvas/src/typescript/canvasModel' in '/tmp/cvat-ui/src/utils'.
It seems math.ts only can find and import file from cvat-ui,how can I change the configure to import ts file from cvat-canvas to cvat-ui?Thank you.

**Comment by bsekachev** [comment]
@tingfengwanxiao 

Hi, only one place where ``cvat-ui`` knows about ``cvat-canvas`` is ``cvat-canvas-wrapper.ts``. Other files in ``cvat-ui`` uses this wrapper to get something about canvas. This is just advice.

Speaking about ``import { CanvasModel,CanvasModelImpl } from 'cvat-canvas/src/typescript/canvasModel'``;
in ``cvat-ui/src/utils/math.ts``, it works for me. At least in development environment.
