### ISSUE TITLE
Expose an API to manage tasks

### ISSUE THREAD

**Issue by AFusco** [opencv/cvat#187]
I would like to add new images, create new tasks and dump annotations automatically through an API.

I'd like to upload a new image to an existing task directly from the camera, and then retrieve the latest dump from an external server/container.

I read in issue #95 that adding new images isn't currently supported.
Is such an API outside the scope of this project?

**Comment by nmanovic** [comment]
Hi @AFusco ,

First of all such API already exists but it isn't stable and well defined. A browser (client) makes request to CVAT server using a set of end points. For example, https://github.com/opencv/cvat/blob/d7e69982fd5f94d0499386f2bae605d22ce37ac2/cvat/apps/engine/urls.py#L11. Thus you can use any python library to prepare HTTP requests and send them to the server like a browser does.

Of course it would be much easy if CVAT provides a clear python API to do the same. I will keep the issue open. Thank you for the request.

**Comment by geraldmwangi** [comment]
+1 for that feature
