### ISSUE TITLE
Hide "completed" tasks by default from dashboard

### ISSUE THREAD

**Issue by 4sfaloth** [opencv/cvat#188]
I realize this may be a silly question but I can't seem to find the answer anywhere on the documentation or the GUI itself. Is there any way to 'close' (ie: mark as done and remove from the list) task segments and task themselves? 
I suppose I could just delete the task after dumping the annotations, but that is a bit inconvenient, particularly since it is not yet possible to import tasks (I am aware there is already another issue for this functionality). Is there no other way to achieve this as of now?

**Comment by nmanovic** [comment]
@4sfaloth,

At the moment it is not possible to hide some tasks. Let's keep the feature request. I believe it is worth to implement in the future.

**Comment by nmanovic** [comment]
Probably we replace "search" by "filter"
