### ISSUE TITLE
Problem moving polygon points - unexpected behaviors

### ISSUE THREAD

**Issue by miso-ramen** [opencv/cvat#1886]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour

1) When I try to move a polygon point, the point moves to the new location I drag it to.
2) When a directional arrow occurs on top of a point, I expect it to move (as a point) to a new location when I try to drag it.
### Current Behaviour

1) Experiencing inconsistent & unexpected behaviors when trying to move a polygon point. Frequently, a new point is created instead, rather than the point being moved to new location.
2) Directional arrow usually appears on a line connecting two points. However, sometimes it appears over a point. If I need to edit the point and drag it to a new location in this case, the entire image moves instead.

### Steps to Reproduce (for bugs)

1. Expected move point - create point instead (animated GIF included in post) 

2. Expected move point - move image & create point instead (animated GIF included in post) 

### Context

This makes labeling polygons in my videos very difficult and frustrating. Sometimes very jagged points are added to my polygons, which takes a lot of time to correct.

### Your Environment

- GitCommit: fec3683
- Docker version `docker version` (e.g. Docker 17.0.05): 0.18.0
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04 LTS

![move-create1](https://user-images.githubusercontent.com/67609014/87248016-1ac25980-c425-11ea-8938-9d0bd9ff2f03.GIF)
![move-create2](https://user-images.githubusercontent.com/67609014/87248018-201fa400-c425-11ea-9c40-4c3cef5ab694.GIF)

**Comment by bsekachev** [comment]
@miso-ramen 

Looks like you have several points with the same coordinates and move one of them. Could you please check it?

**Comment by miso-ramen** [comment]
Thank you, bsekachev. In the instances above, the polygons are only 4 pointed. As soon as a point is touched to move it, a new point seems to be created.

If I think I'm creating a 4-pointed polygon, but somehow the program is creating additional points, how would I go about checking that? Would I need to do an annotation dump and view the annotation file for that frame?

**Comment by bsekachev** [comment]
@miso-ramen 

Actually code of dragging points even doesn't assume ability to create new points. Issue is probably in something else.

By the way, speaking about orientation arrow. It always directed from the latest point to the first point, so if you see this arrow between two points, everything is alright. If you see it over a point, it means, that the latest point and the first point have the same coordinates, as I wrote in the first message.

I believe, need to understand why some points are duplicated for you. Maybe every click of your mouse is double? At least I am unable to reproduce the issue from provided steps

**Comment by bsekachev** [comment]
@miso-ramen 

By the way, git says that hash you provided ``fec3683`` is not in the working tree of our ``develop`` branch.
Are you sure it is correct?

**Comment by miso-ramen** [comment]
Thank you for your time on this. The hash is correct. I had installed probably the master branch. Would this hash match up? Then, a few days ago, there was a bug in annotation.py that you all fixed (problem with dumping annotations). I (perhaps incorrectly) changed the files affected, then rebuilt cvat. Should I clone the development branch and rebuild instead? I'm sorry if I did this incorrectly.

**Comment by miso-ramen** [comment]
I was able to screen capture labeling a new polygon from the beginning (a brand new task that hadn't yet been labeled) that shows all steps, when things are working as expected, then when things go awry. I hope this helps you in recreating the problem. Thank you.

![Peek 2020-07-13 11-15](https://user-images.githubusercontent.com/67609014/87325190-1f5b4080-c4ff-11ea-95cc-2677a68fe862.gif)
I start at frame 80, add a 4 pointed polygon (with track). I create a 4 pointed polygon, jump ahead by 10 frames at a time, unpin object, then move points, jump 10 frames, move points, move entire polygon; this is just as expected. Note: the orientation arrow in these frames is between points.

Then I jump backward to beginning frame (sorry...mistake), then move forward back to where polygon was created. Note: the orientation arrow is now on a point. Now, if I try to move a point, an additional point is created. If try to move the point at the location of the orientation arrow, the entire image moves. This is unexpected behavior. 

This is reproducible by me each time. I'm hoping that by repeating these events on your system, you'll also be able to recreate them. Again, thank you.

**Comment by bsekachev** [comment]
I suspicious that it is related with #1882
Anyway let's assign ``bug`` label, I will look into this issue

**Comment by miso-ramen** [comment]
Much appreciated. Thank you.

**Comment by bsekachev** [comment]
@miso-ramen 

Please, check if #1892 resolves the issue. Let me know if it does not

**Comment by miso-ramen** [comment]
I built the development branch and made the changes you outlined, then built it again. I tried to recreate the issue like I did from scratch in the video above. I was unable to. However, I imported the task my labeler was working on and asked them to see if the issue was gone. The issue still exists in the imported task.

**Comment by bsekachev** [comment]
@miso-ramen 

Actually it is expected because wrong annotation is probably have been saved for some frames (with duplicated points).

**Comment by miso-ramen** [comment]
I'll keep you posted on this. I had my labeler only create new polygons, and _not_ continue edited existing polygons. I'm told that on the new polygons, things seem to be working well. We'll continue with only new polygons from this point forward. If we see problems again, we'll let you know. Many thanks to you for your time and work on this!
