### ISSUE TITLE
Scene annotation

### ISSUE THREAD

**Issue by bluesky314** [opencv/cvat#189]
I am looking to run my convolutional net on a squash video and see if it can recognise the type of shot played( straight, volley or cross court). I want to annote the entire frame( a series of frames) and let the network decide what to look at to determine the shot played. How can I do this with your tool?

**Comment by nmanovic** [comment]
@bluesky314 ,

Just attach a couple of frames how your annotation should look like. After that I will be able to recommend. Probably now I don't understand completely how are you going to annotate data.

**Comment by nmanovic** [comment]
Let's continue our conversation in https://gitter.im/opencv-cvat/public. I will close the issue.
