### ISSUE TITLE
Using the same attribute for label twice -> Stuck

### ISSUE THREAD

**Issue by JulianWgs** [opencv/cvat#19]
There is no warning that you are using the same attribute multiple times. This can easily happen when copy, pasting stuff.

Errors I've experienced when doing this:

1. Job doesnt start up. Instead you can only see the loading screen.
_2. Can't exit out of drawing the bounding box._

EDIT: Number two has more to do with large files (3.5Gb) I think. I will further investigate.

Also the one line given makes it extremely uncomfortable to type/paste in labels.

Greetings

**Comment by nmanovic** [comment]
Hi @JulianWgs ,

Thank you for the bug report. Checking input is an important task and we will try to improve it into our next major release.
