### ISSUE TITLE
Random http 400 error code

### ISSUE THREAD

**Issue by rhlr** [opencv/cvat#190]
Thank you for the project. I have been trying to use the tool using docker-compose. All is working fine but I get random `HTTP 400` errors with the following message:
    `Impossible to save job. Errors was occured. Status: 400 Please immediately report the problem to support team`

Can you tell me what is the issue ?

This is the stacktrace:

`[2018-11-09 09:39:42,745] ERROR cvat.server.task_2: cannot save annotation for job 2
cvat          | 2018-11-09T09:39:42.746731155Z [Fri Nov 09 09:39:42.746229 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398] Traceback (most recent call last):
cvat          | 2018-11-09T09:39:42.746742073Z [Fri Nov 09 09:39:42.746233 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398]   File "/home/django/cvat/apps/engine/views.py", line 252, in save_annotation_for_job
cvat          | 2018-11-09T09:39:42.746753556Z [Fri Nov 09 09:39:42.746237 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398]     annotation.save_job(jid, json.loads(data['annotation']))
cvat          | 2018-11-09T09:39:42.746764578Z [Fri Nov 09 09:39:42.746239 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398]   File "/usr/lib/python3.5/contextlib.py", line 30, in inner
cvat          | 2018-11-09T09:39:42.746775520Z [Fri Nov 09 09:39:42.746242 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398]     return func(*args, **kwds)
cvat          | 2018-11-09T09:39:42.746785613Z [Fri Nov 09 09:39:42.746244 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398]   File "/home/django/cvat/apps/engine/annotation.py", line 83, in save_job
cvat          | 2018-11-09T09:39:42.746796494Z [Fri Nov 09 09:39:42.746246 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398]     annotation.validate_data_from_client(data)
cvat          | 2018-11-09T09:39:42.746806582Z [Fri Nov 09 09:39:42.746249 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398]   File "/home/django/cvat/apps/engine/annotation.py", line 1433, in validate_data_from_client
cvat          | 2018-11-09T09:39:42.746817340Z [Fri Nov 09 09:39:42.746251 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398]     raise Exception('Trying to create new shape(s) with existing client id {}'.format(tmp_res))
cvat          | 2018-11-09T09:39:42.746827990Z [Fri Nov 09 09:39:42.746256 2018] [wsgi:error] [pid 102:tid 140093292656384] [remote 157.35.228.56:34398] Exception: Trying to create new shape(s) with existing client id {1041, 1042, 1043, 1044}
`

**Comment by nmanovic** [comment]
Hi @rhlr ,

It seems that you annotate the same job in different tabs at the same time. It is the main reason for the problem: `raise Exception('Trying to create new shape(s) with existing client id {}'.format(tmp_res))`. Simultaneous annotation of the same job isn't supported. Now it leads to the exception on server side. We will think how to improve user experience in the case.

Does it answer your question?

**Comment by rhlr** [comment]
Yes, it indeed looked like the same issue as you have mentioned. We had multiple annotators working on the same job (on different frames), due to which we were getting the above exception. It would also be better if there's a way to get the activity of each user, like which user has annotated a particular image and who has last updated like this. Thanks again for the awesome project.

**Comment by nmanovic** [comment]
You can split one task on multiple segments. Thus you will have multiple jobs per one task with different frames. Please look at "segment size" and "overlap size" in [the section of documentation](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#creating-an-annotation-task).

Thanks for your feedback. I will close the issue. Instead I have created another one (#191).
