### ISSUE TITLE
"Image compression" definition mismatch 

### ISSUE THREAD

**Issue by ilouzl** [opencv/cvat#1900]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Mismatch between the definition of "Image quality" parameter in the Task creation page, and it's definition in the User's Guide.
### Expected Behaviour

High "Image quality" parameter should yield low compression level - and vice versa.
Also, need to maintain consistency between the documentation and the actual parameter meaning.
### Current Behaviour

In the [User guide](https://github.com/opencv/cvat/blob/4477e1777aa01bda0add51b792834eb2ab101cc9/cvat/apps/documentation/user_guide.md#L153) It's defined in the opposite way - ```Image Quality. Use this option to specify quality of uploaded images. The option helps to load high resolution datasets faster. Use the value from 1 (completely compressed images) to 95 (almost not compressed images)```
In the Task page, the Image quality parameter [tooltip](https://github.com/opencv/cvat/blob/7b31525a1c638be616c9333e75b690fc61ac7d2d/cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx#L145) displays ```Defines image compression level``` which may sound inverse to Image quality. - and in fact low value in this field yields high compression level <-> lower image quality.
### Possible Solution

Either change the name of the parameter to 

### Context

Confusion when trying to lower image quality in order to achieve better streaming experience when dealing with high resolution videos. 
### Your Environment

- Git hash commit (`git log -1`): https://github.com/opencv/cvat/commit/07de7141edbc980031da857579128088f7a4630a
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@ilouzl thanks for the report!

**Comment by nmanovic** [comment]
@ilouzl , thanks for the issue. Do you think you can help us to prepare the PR?

**Comment by ilouzl** [comment]
Sure
