### ISSUE TITLE
Import COCO annotation show several extra class

### ISSUE THREAD

**Issue by giorginagonzalez** [opencv/cvat#1909]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour

I have a task with 9 classes as bbox, but If I dump annotation in a task with COCO format and import the same annotation, appears thousands of classes instead of 9. The only difference I see is in the original task, it says "Rectangle tracker" and the new-imported task says "Polygon shape". I should see the same result in both tasks. 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):19.03.9
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

![imported_thousand_classes](https://user-images.githubusercontent.com/19914765/87688677-47dc7800-c755-11ea-9e04-5a44ddc6b7b3.jpg)
![original_nine_classes](https://user-images.githubusercontent.com/19914765/87688681-48750e80-c755-11ea-9124-5b56e99d0e4c.jpg)

**Comment by zhiltsov-max** [comment]
Hello, could you say which CVAT version are you using (`git log -1`)? Do I understand correctly that the original annotations were tracks and after uploading they became singular shapes (the same number per frame)?

**Comment by giorginagonzalez** [comment]
Hi, yes, the original annotations were bbox as tracks and after uploading they became as singular shapes. And doesn´t look like  the same number per frame . 

And the cvat version is 19.03.9

**Comment by zhiltsov-max** [comment]
`COCO` format does not support tracks of any kind, you should take a look at `CVAT for video`, `MOT` and `Datumaro` formats if you want to keep this information in the exported annotations.

**Comment by nmanovic** [comment]
@giorginagonzalez , does it mean that if download annotations from CVAT and upload it again to CVAT, you get wrong annotations (some of them are missing)? You cannot keep tracks inside COCO but at the same time it should have correct bounding boxes (unpacked tracks).

**Comment by giorginagonzalez** [comment]
Yes, if I download annotations from CVAT and upload again I get wrong annotations. It´s ok if tracker doesn´t upload but I should keep the same amount of label ID in both tasks. I mean, if I have the object "ship1", "ship2" and "ship3" in the _frame 2_, on the original task, I should see the same object from original, but I see "ship 15", "ship 16" and "ship 17" in the _frame 2_ on the task with the uploaded annotations.

**Comment by nmanovic** [comment]
@giorginagonzalez , in the example above ships has only different IDs? Is it the only difference?

Could you please attach "both annotations" for us to analyze?

**Comment by giorginagonzalez** [comment]
The differences I see are: 1. in the first task, it says "Rectangle tracker" and the new-imported task says "Polygon shape". 2. The label Id change in every frame in the new imported task.

I only have one annotation, I mean the annotation exported from the original task: 
[task_1_2-2020_07_13_19_38_04-coco 1.0 (1).zip](https://github.com/opencv/cvat/files/4943267/task_1_2-2020_07_13_19_38_04-coco.1.0.1.zip)

**Comment by nmanovic** [comment]
@giorginagonzalez , it is the expected difference. You don't have tracks thus the new shape type is "polygon shape". IDs are generated on the client at the moment.

**Comment by zhiltsov-max** [comment]
Closing as after #1782 and #1953 the export in COCO should keep tracks and boxes.
