### ISSUE TITLE
Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by tingfengwanxiao** [opencv/cvat#1917]
Hello,I meet a problem when I save annotations in docker ,Could not save annotations TypeError: Cannot read property 'log' of undefined,my environment is

Server version: 1.1

Core version: 3.1.0

Canvas version: 1.2.1

UI version: 1.4.2
//----------------------------------------------------
have you met it or may be what cause this?

**Comment by bsekachev** [comment]
@tingfengwanxiao 

Hi, I do not remember such an exception.
What are specific steps to reproduce? Just saving annotations works well for me. 
Have you changed source code of CVAT?

**Comment by tingfengwanxiao** [comment]
ok,I find the reason. I accidentally changed the code.
