### ISSUE TITLE
All frames become key frames when uploading annotations from the newer version of CVAT to the previous version.

### ISSUE THREAD

**Issue by jafar-pivotchain** [opencv/cvat#1934]
I am working with CVAT video annotation where I need to keep a track of objects moving in the video. The annotations are saved in CVAT video 1.1 format. When I uploaded the annotations (saved in a latest CVAT version ) to the older version all the frames become key frames and adjusting the boxes becomes very difficult. Could you please resolve the issue.

labels: bug

**Comment by nmanovic** [comment]
@jafar-pivotchain , could you please fill issue template. We introduce it to easily understand how to resolve a particular issue? From your description I don't know which version of CVAT do you use.

**Comment by jafar-pivotchain** [comment]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)


I am working with CVAT video annotation where I need to keep a track of objects moving in the video. The annotations are saved in CVAT video 1.1 format. When I uploaded the annotations (saved in a latest develop CVAT version ) to the older version(release 1.1) all the frames become key frames and adjusting the boxes becomes very difficult. Could you please resolve the issue.
### Expected Behaviour

The expected behaviour should be that the key frames should remain same when annotations are uploaded from higher version of CVAT to a lower version. Currently, the backward compatibility is not there. I have build CVAT from the develop branch but on different dates therefore I am using the term "version" here. The commits of these version are here.

Older git commit hash (older version): 47470b84703bfc7bee243b2e7c1ae830ad587885
New git commit hash  (Newer version):  7ecdcf182b1bfae2d29e0f256e025743dd8d198e  

### Current Behaviour


### Possible Solution


### Steps to Reproduce (for bugs)

1. Have both newer version and older version build on a system.  
1. Annotate any video sequence with tracking enabled (make bboxes over few object and track it). 
1. Save the annotations in the CVAT 1.1 video format in the newer version.
1. Now create a same task in the older version of CVAT and upload the annotations that were saved in newer version.
1. Check for the key frames. All the frames will be now key frames instead of a few.

### Context

While doing a review of these tasks the bboxes have to adjusted in all the frames as all the frames are now key frames.
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux 18.04 and Linux 16.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please look at the problem?
