### ISSUE TITLE
Returning to job list for a task and attempting to start another job results in infinite loading screen.

### ISSUE THREAD

**Issue by thomasstats** [opencv/cvat#1944]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Being able to return to the job list for a task and start a new job without an infinite loading screen.

### Current Behaviour
After returning to the job list while working on a job, clicking on another job loads the UI but infinitely loops the loading screen.  When checking the cvat logs, the most recent entry is the last action performed before returning to the job list, no actions such as clicking on the new job appear.  Upon checking the console and the HAR data there doesn't appear to be any errors, and HAR produces one request to git/repository/get/<taskid>.  This was reproduced with multiple users on different machines.  However, all was done on the same VM.

### Steps to Reproduce (for bugs)
1.  Start a job in a task with multiple jobs.  In our case we had a thousand images in a task split into 100 images per job.
2.  Press the back arrow to return to the job list, or hit task and enter the job list from the task menu.
3.  Select a different job that is assigned to you from the job list
4.  UI loads and infinitely shows the loading screen.
5.  To be able to load the job you have to go back to the job list, refresh the page (F5 or refresh button), and then enter the job.

### Context
I would say this is likely a minor issue, because it currently has a work around, but it is a bit of an annoyance for the annotators.

### Your Environment

- Git hash commit (`git log -1`):  Release 1.0.0 (#1335)
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.8
- Operating System and version (e.g. Linux, Windows, MacOS):  Ubuntu 18.04

**Comment by bsekachev** [comment]
@thomasstats 

Hi, could you please try to reproduce using develop branch? I cannot
Also we will release 1.1.0 alpha at the end of July

**Comment by thomasstats** [comment]
@bsekachev loaded develop branch on my personal computer, uploaded a task with multiple jobs, and can confirm that the problem still exists.  Is there by chance anything I could gather for you that would help you diagnose this problem further?  Like I said previously the console, cvat logs, and HAR data all seem to be rather useless.  I'm curious if it's a client side js problem.

**Comment by bsekachev** [comment]
@thomasstats 

Hmm.. I was able to reproduce it, but reproducing isn't stable for me. 
Okay, let's assign bug label, I suppose it is a client issue.

**Comment by bsekachev** [comment]
@thomasstats 

I expect the fix above will resolve the issue
