### ISSUE TITLE
In the process of retreat, the track disappears

### ISSUE THREAD

**Issue by zurenyou** [opencv/cvat#1956]
### My actions before raising this issue
+ [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
+ [x] Searched [past issues](/issues)

### Current Behaviour

After setting the track of the image sequence, when the target disappears in the image sequence, the backward operation is carried out, and the track disappears.
![Video_2020-07-29_140512](https://user-images.githubusercontent.com/47100046/88767640-8722b400-d1ac-11ea-975f-6c3b708471bb.gif)

### Your Environment

- Git hash commit (`git log -1`):cvat 1.0.0
- Docker version `docker version` (e.g. Docker 17.0.05):19.03.12
- Operating System and version (e.g. Linux, Windows, MacOS):Windows ubuntu18.04
- browser:chrome

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@zurenyou 
What versions do you see in "About" dialog?
There were similar problem before, but it has been fixed. Maybe updating CVAT will help.

**Comment by bsekachev** [comment]
@zurenyou Any updates on it?

**Comment by zurenyou** [comment]
> @zurenyou对此有任何更新吗？

I have upgraded the new version. This problem will not occur any more. Thank you
