### ISSUE TITLE
Website is down (cvat.org)

### ISSUE THREAD

**Issue by fabiomanz** [opencv/cvat#1959]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I expect if I click on the link to the cvat.org, that I will see your website.

### Current Behaviour

My browser shows me a message saying Safari couldn't connect to your server. 

### Steps to Reproduce (for bugs)

1. Open http://cvat.org or https://cvat.org in your browser.
2. See that it doesn't work, because it says it couldn' connect to the server.
1. ping cvat.org
1. See that it doesn't work, we have 100% packet loss.

### Context

I couldn't learn about your project.

### Your Environment

I tested these browsers: Safari, Firefox

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@fabiomanz CVAT.org is updating right now

**Comment by fabiomanz** [comment]
Ok, thank you for your information.

**Comment by bsekachev** [comment]
Update: We are migrating to another server. It can take time to move all data.

**Comment by wx-b** [comment]
Tried Chrome, Firefox and pinging today and can't reach cvat.org. Should the demo site be reachable?

**Comment by azhavoro** [comment]
> Tried Chrome, Firefox and pinging today and can't reach cvat.org. Should the demo site be reachable?

Hello, sorry for this, it should be fixed now.

**Comment by wx-b** [comment]
Great -- I see it working now. Thanks for fixing that.

**Comment by barisduzenli** [comment]
again? I couldn't reach cvat.org

**Comment by berruk** [comment]
Looks like it is down again. When could we be able to reach the website?

**Comment by bsekachev** [comment]
@berruk 

Thank for the notification. We are working on the issue.

**Comment by pratikk-bulani** [comment]
Looks like it is down again. When could we be able to use the website?

**Comment by Marius-Graml** [comment]
Down again? I always get connection timeout

**Comment by rakib-h** [comment]
> Update: We are migrating to another server. It can take time to move all data.

Approx. how much time it will take? When we will get it ready?

Thanks

**Comment by plazarotello** [comment]
Hello, I'm seeing ERR_CONNECTION_REFUSED when trying to access the page
