### ISSUE TITLE
Support other tensorflow object detection models

### ISSUE THREAD

**Issue by kodonnell** [opencv/cvat#196]
Currently one can run other models using `TF_ANNOTATION_MODEL_PATH` (see [here](https://github.com/opencv/cvat/blob/c35d07c3e02f6942573fecf3cf5dfb7f5ef8837c/cvat/apps/tf_annotation/views.py#L52)) - though I guess you'd need to modify this in the dockerfile somehow (maybe [here](https://github.com/opencv/cvat/issues/154#issuecomment-433030293) - though you'd still need to get the file onto the image).

however, the class labels are [hard-coded](https://github.com/opencv/cvat/blob/c35d07c3e02f6942573fecf3cf5dfb7f5ef8837c/cvat/apps/tf_annotation/views.py#L302-L319) which, in practice, means only a small subset of tensorflow object detections will work (i.e. those trained on COCO (?) which hopefully have the class names in the correct order).

Happy to submit a PR. I was thinking of doing something hacky-ish like reading the classes from a json at `TF_ANNOTATION_CLASSES_PATH` but then I realised that this isn't that great, as the same model would be used on all tasks i.e. you couldn't use model X for one annotation task, and model Y for another. So, I'm thinking that in the GUI, the user can upload a model (frozen graph + classes), which gets used - in the same way we upload videos etc. I feel like this should be pretty straightforward plumbing, since all of the code to run the model etc. already exists.

If that sounds like a good idea, I can have a play. Otherwise, if it's a bad idea, can someone propose an alternative? And - if there's not enough interest in this feature, then I can just hack something out for my own use case (which will be much quicker and easier for me, after all).

**Comment by nmanovic** [comment]
@kodonnell ,

We are working to implement the feature already. I hope to add it next year.

**Comment by savan77** [comment]
we have already implemented this feature for our local usage and working on adding tracking for videos. we are also planning to open-source once everything is tested thoroughly.

**Comment by nmanovic** [comment]
@savan77 ,

Awesome. Don't hesitate to send as PR. We are open for collaboration.

**Comment by kodonnell** [comment]
@savan77 - great work. Maybe if you submit a PR now, then we can also try it out and test it?

**Comment by savan77** [comment]
@kodonnell @nmanovic 
I am more than happy to send a PR but I am just a developer not an owner. However, I have been told that the code will be open-sourced soon. I can't comment on exactly when.

**Comment by outan** [comment]
> @kodonnell @nmanovic
> I am more than happy to send a PR but I am just a developer not an owner. However, I have been told that the code will be open-sourced soon. I can't comment on exactly when.
 
I am very happy to wait for your PR.
I really need the tracking feature in my project to greatly reduce annotation time.
And I think that is needed in many projects.

**Comment by zishanahmed08** [comment]
@savan77 any updates?
