### ISSUE TITLE
When developing without Docker it always need to run nuclio container

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#1965]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
If nuclio dashboard is off, basic functionality of CVAT is expected to work. 

### Current Behaviour
When loading UI, server raises error: 
``Error: Request failed with status code 503. "HTTPConnectionPool(host='localhost', port=8070): Max retries exceeded with url: /api/functions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a296f9b00>: Failed to establish a new connection: [Errno 111] Connection refused',))".``

### Possible Solution
If nuclio server is unavaliable, server can return empty list of functions

### Your Environment

- Git hash commit (`git log -1`):  0062ecdec
- Docker version `docker version` (e.g. Docker 17.0.05): no
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

**Comment by nmanovic** [comment]
We decided to close the bug for a while. The behavior is expected.
