### ISSUE TITLE
Error was occurred. Status 403

### ISSUE THREAD

**Issue by naufil601** [opencv/cvat#198]
Hi, 
I was using Interpolation mode to annotate a video of length approx 18000 frames and I was saving the work after regular intervals of time. However when I reached to 15000 frames and tried to save the work, following error occurred. (Screenshot Attached)
![error](https://user-images.githubusercontent.com/18327182/48599094-05fb9d00-e988-11e8-9f3e-7200b6526d56.png)

When I try to dump the annotations, it says "Dummp process is completed with an error. Undefined" but I don't see any file dumped.

Please help!

**Comment by nmanovic** [comment]
Hi @naufil601 ,

I believe it is authorization problem. You need to open another tab with CVAT (you should see login page) and login again. The authorization session is about 2 weeks AFAIK. After that you need to login again. Does it help?

**Comment by naufil601** [comment]
Thanks @nmanovic for instant help.
It worked.

**Comment by nmanovic** [comment]
@naufil601 ,

Cool. I'm glad that the problem has been resolved. I will close the issue in this case.
