### ISSUE TITLE
Where to find the coordinate of a point relative to the image（not the canvas coordinate）

### ISSUE THREAD

**Issue by tingfengwanxiao** [opencv/cvat#1991]
Hello,where to find the coordinate of a point relative to the image（not the canvas coordinate） . For example, if a 3000 * 3000 image is on the canvas, how can I get this point‘s coordinates relative to the 3000 * 3000 image (for example (200,200))when I click a point on the picture? (note:not the coordinates in the canvas)Thank you!

**Comment by nmanovic** [comment]
@tingfengwanxiao , Please ask such questions in gitter chart please. I will close the issue. Here we try to keep only defects and features.

**Comment by Once88** [comment]
I have the same question, it seems that CVAT doesn't have this feature. How can I find out the coordinates of the mouse cursor or the coordinates of a bounding box?
