### ISSUE TITLE
nuclio container keeps restarting after executing docker-compose up -d

### ISSUE THREAD

**Issue by ly10951** [opencv/cvat#1999]
### My actions before raising this issue

- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
I wish to use cvat for annotation objects in videos. However I get the following error. The server response with "Could not initialize plugins state" after executing docker-compose up -d and visiting localhost:8080.Therefore I checked the status of cvat dockers, and I found the nuclio container kept restarting.And I also checked the log of nuclio container.Thanks in advance.

### Current Behaviour

20.08.07 16:28:43.636 rd.platform.docker.runner (D) Executing {"command": "docker version"}
20.08.07 16:28:43.656 rd.platform.docker.runner (D) Command executed successfully {"output": "Client: Docker Engine - Community\n Version:           18.09.6\n API version:       1.39\n Go version:        go1.10.8\n Git commit:        481bc77\n Built:             Sat May  4 02:33:34 2019\n OS/Arch:           linux/amd64\n Experimental:      false\n\nServer: Docker Engine - Community\n Engine:\n  Version:          19.03.12\n  API version:      1.40 (minimum version 1.12)\n  Go version:       go1.13.10\n  Git commit:       48a66213fe\n  Built:            Mon Jun 22 15:44:07 2020\n  OS/Arch:          linux/amd64\n  Experimental:     false\n containerd:\n  Version:          1.2.13\n  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429\n runc:\n  Version:          1.0.0-rc10\n  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd\n docker-init:\n  Version:          0.18.0\n  GitCommit:        fec3683\n", "stderr": "", "exitCode": 0}
20.08.07 16:28:43.656 rd.platform.docker.runner (D) Executing {"command": "docker version"}
20.08.07 16:28:43.675 rd.platform.docker.runner (D) Command executed successfully {"output": "Client: Docker Engine - Community\n Version:           18.09.6\n API version:       1.39\n Go version:        go1.10.8\n Git commit:        481bc77\n Built:             Sat May  4 02:33:34 2019\n OS/Arch:           linux/amd64\n Experimental:      false\n\nServer: Docker Engine - Community\n Engine:\n  Version:          19.03.12\n  API version:      1.40 (minimum version 1.12)\n  Go version:       go1.13.10\n  Git commit:       48a66213fe\n  Built:            Mon Jun 22 15:44:07 2020\n  OS/Arch:          linux/amd64\n  Experimental:     false\n containerd:\n  Version:          1.2.13\n  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429\n runc:\n  Version:          1.0.0-rc10\n  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd\n docker-init:\n  Version:          0.18.0\n  GitCommit:        fec3683\n", "stderr": "", "exitCode": 0}
20.08.07 16:28:43.675        dashboard.platform (D) Igniting container healthiness validator
20.08.07 16:28:43.675 rd.platform.docker.runner (D) Executing {"command": "docker exec  nuclio-local-storage-reader /bin/sh -c \"/bin/cat /etc/nuclio/store/projects/nuclio/default.json\""}
20.08.07 16:28:43.732 rd.platform.docker.runner (D) Command executed successfully {"output": "eyJNZXRhIjp7Im5hbWUiOiJkZWZhdWx0IiwibmFtZXNwYWNlIjoibnVjbGlvIn0sIlNwZWMiOnt9fQ==\n", "stderr": "", "exitCode": 0}
20.08.07 16:28:43.733 rd.platform.docker.runner (D) Executing {"command": "docker exec  nuclio-local-storage-reader /bin/sh -c \"/bin/cat /etc/nuclio/store/projects/nuclio/default.json\""}
20.08.07 16:28:43.789 rd.platform.docker.runner (D) Command executed successfully {"output": "eyJNZXRhIjp7Im5hbWUiOiJkZWZhdWx0IiwibmFtZXNwYWNlIjoibnVjbGlvIn0sIlNwZWMiOnt9fQ==\n", "stderr": "", "exitCode": 0}
20.08.07 16:28:43.789                 dashboard (D) Fetching function templates from git repository {"templatesGitRepository": "https://github.com/nuclio/nuclio-templates.git", "templatesGitRef": "refs/heads/master"}
20.08.07 16:28:43.797 itFunctionTemplateFetcher (D) Fetching templates from git {"ref": "refs/heads/master"}
20.08.07 16:29:13.675 rd.platform.docker.runner (D) Executing {"command": "docker exec  nuclio-local-storage-reader /bin/sh -c \"/bin/cat /etc/nuclio/store/functions/nuclio/*\""}
20.08.07 16:29:13.758 rd.platform.docker.runner (D) Failed to execute command {"output": "cat: can't open '/etc/nuclio/store/functions/nuclio/*': No such file or directory\n", "stderr": "", "exitCode": 1, "err": "exit status 1"}
20.08.07 16:29:13.758 dashboard.platform.docker (D) Failed to execute command in container {"err": "stdout:\ncat: can't open '/etc/nuclio/store/functions/nuclio/*': No such file or directory\n\nstderr:\n", "errVerbose": "\nError - exit status 1\n    /nuclio/pkg/cmdrunner/cmdrunner.go:124\n\nCall stack:\nstdout:\ncat: can't open '/etc/nuclio/store/functions/nuclio/*': No such file or directory\n\nstderr:\n\n    /nuclio/pkg/cmdrunner/cmdrunner.go:124\nstdout:\ncat: can't open '/etc/nuclio/store/functions/nuclio/*': No such file or directory\n\nstderr:\n", "errCauses": [{"error": "exit status 1"}], "stdout": "cat: can't open '/etc/nuclio/store/functions/nuclio/*': No such file or directory\n", "stderr": ""}

Error - Get "https://github.com/nuclio/nuclio-templates.git/info/refs?service=git-upload-pack": dial tcp 52.74.223.119:443: i/o timeout
    .../gitfunctiontemplatefetcher.go:80

Call stack:
Failed to initialize git repository
    .../gitfunctiontemplatefetcher.go:80
Failed to clone repository
    .../gitfunctiontemplatefetcher.go:58
Failed to fetch one of given templateFetchers
    .../dashboard/functiontemplates/repository.go:35
parallel: This job failed:
/runners/dashboard.sh
Failed to create repository out of given fetchers
    /nuclio/cmd/dashboard/app/dashboard.go:131
Exiting

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05):Docker version 19.03.12, build 48a66213fe
- Operating System and version (e.g. Linux, Windows, MacOS):Ubuntu 18.04.4 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@ly10951 , looks like a problem with internet connection (git cannot checkout some files: i/o error)
