### ISSUE TITLE
Support Pascal VOC Format

### ISSUE THREAD

**Issue by syonekura** [opencv/cvat#2]
Hi, it would be nice to be able to export the annotations as Pascal VOC format. I Couldn't find info about supported formats in the documentation, is this feature supported?

**Comment by nmanovic** [comment]
Hi,

At the moment CVAT doesn't support Pascal VOC format. I believe the best way to support it for now is to create "scripts" directory and put a py-script which converts [CVAT format](https://github.com/opencv/cvat/blob/master/cvat/apps/documentation/xml_format.md) to Pascal VOC. What do you think?

At the moment I see only one problem. We don't keep an image size inside annotation file. Also I see [PASCAL VOC Writer library](https://github.com/AndrewCarterUK/pascal-voc-writer) which can simplify the script development.

If you can contribute such functionality it will be awesome.

**Comment by syonekura** [comment]
Sure, give me a few days and I'll submit a PR with that script :)

**Comment by nmanovic** [comment]
Hi @syonekura ,

Let me know if you want to improve the PR. It is nice but still have several open questions. FYI, in our next release we are going to release similar script for COCO dataset.

**Comment by syonekura** [comment]
I'm sorry, I was passing by and saw by chance all the comments you left! (usually I got an email each time I get feedback for PR's or comments in issues). I'll improve the PR, is there any development branch where I can see the script for COCO?
