### ISSUE TITLE
Do we have a feature of interacting with server-side annotations(dump/load datasets to/from the server)

### ISSUE THREAD

**Issue by mhe-wyze** [opencv/cvat#2010]
Dear great CVAT community, thanks for your continuous contributions to this opensource repo, excellently solved my previous use cases, I have a new issue not sure it is good to ask.

I'm currently trying to facilitate the annotating process between the annotation team and the data science team using CVAT.
I've added the server-side files sharing function according to the installation guide.

While the issue I'm facing now is loading annotations from the server and dumping annotation results/dataset to the server.
I know CVAT supports interacting annotations with the local PC, which is good, but we need to spend more extra time downloading the dataset(images+annotations), then uploading it to the server every time. If the dataset is big, time-consuming is huge.

So I'm wondering if we have this feature already, or else, would we try to add it in the future?

Additionally, it would be more convenient if we can have a task status flag on each of the task, such as Done, In process, Pending, so that data engineer or other annotators won’t re-do  it. In this case, annotators can mark the status by clicking a button.

Thanks for your help ahead.

**Comment by mhe-wyze** [comment]
Hi @nmanovic , how do you think about this?

**Comment by nmanovic** [comment]
@mhe-wyze ,

> Additionally, it would be more convenient if we can have a task status flag on each of the task, such as Done, In process, Pending, so that data engineer or other annotators won’t re-do it. In this case, annotators can mark the status by clicking a button.

Each job has a status which can be changed.

![image](https://user-images.githubusercontent.com/40690625/89986788-ba257700-dc85-11ea-929b-700a8cd45562.png)

> While the issue I'm facing now is loading annotations from the server and dumping annotation results/dataset to the server.
I know CVAT supports interacting annotations with the local PC, which is good, but we need to spend more extra time downloading the dataset(images+annotations), then uploading it to the server every time. If the dataset is big, time-consuming is huge.

It is something which we are going to fix in the future. First step on the way is the patch: https://github.com/opencv/cvat/pull/2007. Even it solves another issue it will be an initial step to support remote data sources.

**Comment by zhiltsov-max** [comment]
When datasets and annotations are exported, they are cached for some time (10 hours by default - https://github.com/opencv/cvat/blob/develop/cvat/apps/dataset_manager/views.py#L39). You can mount cache directories to a specific location on the host, the cache is placed in `cvat/data/tasks/<task id>/export_cache` for each task. Technically, it is possible to provide an option to specify another cache directory, would this help?

**Comment by mhe-wyze** [comment]
Hi @zhiltsov-max , thanks for your solution, this is very helpful. 👍

**Comment by mhe-wyze** [comment]
Hi @nmanovic , thanks for your timely comment, the following attach is my UI,
<img width="1024" alt="Screen Shot 2020-08-12 at 11 41 17 AM" src="https://user-images.githubusercontent.com/60670801/90054579-ea264780-dc90-11ea-9c65-2a4e7d9d385a.png">
I don't know why mine is a little bit different from yours, I couldn't find the status changing button either.

**Comment by nmanovic** [comment]
- Open Job
- Press info button
- Change the status

![image](https://user-images.githubusercontent.com/40690625/90055006-592d8b80-dce5-11ea-8283-dac92a59ee50.png)

**Comment by mhe-wyze** [comment]
<img width="1235" alt="Screen Shot 2020-08-12 at 12 00 43 PM" src="https://user-images.githubusercontent.com/60670801/90056478-c9132600-dc93-11ea-8f82-d015ce706a5a.png">
@nmanovic Thank you so much.

**Comment by bsekachev** [comment]
I will close the issue for now. Do not hesitate reopen it if you still have questions
