### ISSUE TITLE
CVAT no longer supports OpenVino for auto annotation?

### ISSUE THREAD

**Issue by THINK989** [opencv/cvat#2026]
Hello Devs,

This is more of a question than an issue. I had referred and installed OpenVino as an additional component a few months back and configured it with CVAT and I am able to do auto annotation with the help of OpenVino in CVAT. But at the moment, I can't find the pages I referred earlier, are those pages moved or removed. I just wanted to refer it to a friend of mine. And there's no better reference but the documents that existed on this repository few months back. I am sorry if this is not the place to ask such questions and in that case please suggest some other alternate forum or discussion room.

**Comment by nmanovic** [comment]
It is supported but we changed the implementation: https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#semi-automatic-and-automatic-annotation

**Comment by THINK989** [comment]
Hello @nmanovic ,
Thank you, I completely missed that out
