### ISSUE TITLE
Incorrect order of labels in the exported masks

### ISSUE THREAD

**Issue by KouateMuhamed** [opencv/cvat#2032]
Hi!

I'm trying to annotate images for a semantic segmentation task.

Once my images were uploaded, I made the polygonal labeling of the objects of interest using two classes.

However, when I go to "Dump annotatations> Segmentation mask 1.1"
I get two folders: "SegmentationClass" and "SegmentationObject."
In the first folder I have the masks of only ONE class, while in the second folder I have the masks with all the objects noted, but with different colors.

I would like to have masks where annotated objects appear with a single color per class.

Example: [class1] = cat (red) [class2] = dog [yellow]
Like the semantic segmentation in this pic: https://www.jeremyjordan.me/content/images/2018/05/Screen-Shot-2018-05-21-at-10.44.23-PM.png

How can I do?

Thanks in advance

**Comment by zhiltsov-max** [comment]
Hello. The masks you're looking for should be in the `SegmentationClass` directory. Could you check if `labelmap.txt` contains all the classes the task has? Please, also specify your CVAT version.

**Comment by KouateMuhamed** [comment]
Thank you for the answer!

Yer the labelmap.txt contains all the classes that the task has:
`# label:color_rgb:parts:actions
Cat:48,112,32::
background:0,0,0::
Dog:176,112,32::`

CVAT version:
Server version: 1.1b0 
Core version: 3.1.1 
Canvas version: 2.0.1 
UI version: 1.6.2

**Comment by zhiltsov-max** [comment]
Could you specify the commit hash (`git log -1`)?

**Comment by KouateMuhamed** [comment]
> Could you specify the commit hash (`git log -1`)?

Where can I find it?

**Comment by zhiltsov-max** [comment]
If you downloaded the project by cloning the repository, you need to type the command above. If you just downloaded a release or an archive from github - please tell the version.

**Comment by KouateMuhamed** [comment]
> If you downloaded the project by cloning the repository, you need to type the command above. If you just downloaded a release or an archive from github - please tell the version.

Commit hash:  5b9a1dc44306365276392f36162de4b30b464d02
