### ISSUE TITLE
How to setup HTTPS on an internal network?

### ISSUE THREAD

**Issue by ly10951** [opencv/cvat#2036]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)
Documentation is detailed and impressive, I have installed CVAT on ubuntu18.04 successfully. 
I want to try for the HTTPS support on my internal network, however following the steps in your guides I get some responds with errors. What should I do to setup HTTPS support for my CVAT server on the internal network?

### Expected Behaviour

Could get access to the server address with https protocols.
### Current Behaviour

after running **~/.acme.sh/acme.sh --issue --staging -d cvat.hohonote.com -w $HOME/CVAT/cvat/letsencrypt-webroot --debug**
for acme certification I get something like this:
[Fri Aug 14 16:50:44 CST 2020] Lets find script dir.
[Fri Aug 14 16:50:44 CST 2020] _SCRIPT_='/home/liyuan/.acme.sh/acme.sh'
[Fri Aug 14 16:50:44 CST 2020] _script='/home/liyuan/.acme.sh/acme.sh'
[Fri Aug 14 16:50:44 CST 2020] _script_home='/home/liyuan/.acme.sh'
[Fri Aug 14 16:50:44 CST 2020] Using config home:/home/liyuan/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.7
[Fri Aug 14 16:50:44 CST 2020] Running cmd: issue
[Fri Aug 14 16:50:44 CST 2020] _main_domain='cvat.hohonote.com'
[Fri Aug 14 16:50:44 CST 2020] _alt_domains='no'
[Fri Aug 14 16:50:44 CST 2020] Using config home:/home/liyuan/.acme.sh
[Fri Aug 14 16:50:44 CST 2020] default_acme_server
[Fri Aug 14 16:50:44 CST 2020] Using stage ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 14 16:50:44 CST 2020] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
[Fri Aug 14 16:50:44 CST 2020] DOMAIN_PATH='/home/liyuan/.acme.sh/cvat.hohonote.com'
[Fri Aug 14 16:50:44 CST 2020] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 14 16:50:44 CST 2020] _init api for server: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 14 16:50:44 CST 2020] GET
[Fri Aug 14 16:50:44 CST 2020] url='https://acme-staging-v02.api.letsencrypt.org/directory'
[Fri Aug 14 16:50:44 CST 2020] timeout=
[Fri Aug 14 16:50:44 CST 2020] _CURL='curl -L --silent --dump-header /home/liyuan/.acme.sh/http.header  -g '
[Fri Aug 14 16:50:52 CST 2020] ret='0'
[Fri Aug 14 16:50:52 CST 2020] ACME_KEY_CHANGE='https://acme-staging-v02.api.letsencrypt.org/acme/key-change'
[Fri Aug 14 16:50:52 CST 2020] ACME_NEW_AUTHZ
[Fri Aug 14 16:50:52 CST 2020] ACME_NEW_ORDER='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Fri Aug 14 16:50:52 CST 2020] ACME_NEW_ACCOUNT='https://acme-staging-v02.api.letsencrypt.org/acme/new-acct'
[Fri Aug 14 16:50:52 CST 2020] ACME_REVOKE_CERT='https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert'
[Fri Aug 14 16:50:52 CST 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Fri Aug 14 16:50:52 CST 2020] ACME_NEW_NONCE='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Aug 14 16:50:52 CST 2020] ACME_VERSION='2'
[Fri Aug 14 16:50:52 CST 2020] Le_NextRenewTime
[Fri Aug 14 16:50:53 CST 2020] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 14 16:50:53 CST 2020] _on_before_issue
[Fri Aug 14 16:50:53 CST 2020] _chk_main_domain='cvat.hohonote.com'
[Fri Aug 14 16:50:53 CST 2020] _chk_alt_domains
[Fri Aug 14 16:50:53 CST 2020] Le_LocalAddress
[Fri Aug 14 16:50:53 CST 2020] d='cvat.hohonote.com'
[Fri Aug 14 16:50:53 CST 2020] Check for domain='cvat.hohonote.com'
[Fri Aug 14 16:50:53 CST 2020] _currentRoot='/home/liyuan/CVAT/cvat/letsencrypt-webroot'
[Fri Aug 14 16:50:53 CST 2020] d
[Fri Aug 14 16:50:53 CST 2020] _saved_account_key_hash is not changed, skip register account.
[Fri Aug 14 16:50:53 CST 2020] Read key length:
[Fri Aug 14 16:50:53 CST 2020] _createcsr
[Fri Aug 14 16:50:53 CST 2020] Single domain='cvat.hohonote.com'
[Fri Aug 14 16:50:53 CST 2020] Getting domain auth token for each domain
[Fri Aug 14 16:50:53 CST 2020] d
[Fri Aug 14 16:50:53 CST 2020] url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Fri Aug 14 16:50:53 CST 2020] payload='{"identifiers": [{"type":"dns","value":"cvat.hohonote.com"}]}'
[Fri Aug 14 16:50:53 CST 2020] RSA key
[Fri Aug 14 16:50:53 CST 2020] HEAD
[Fri Aug 14 16:50:53 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Aug 14 16:50:53 CST 2020] _CURL='curl -L --silent --dump-header /home/liyuan/.acme.sh/http.header  -g  -I  '
[Fri Aug 14 16:50:58 CST 2020] _ret='0'
[Fri Aug 14 16:50:58 CST 2020] POST
[Fri Aug 14 16:50:58 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Fri Aug 14 16:50:58 CST 2020] _CURL='curl -L --silent --dump-header /home/liyuan/.acme.sh/http.header  -g '
[Fri Aug 14 16:51:00 CST 2020] _ret='0'
[Fri Aug 14 16:51:00 CST 2020] code='201'
[Fri Aug 14 16:51:00 CST 2020] Le_LinkOrder='https://acme-staging-v02.api.letsencrypt.org/acme/order/15137060/131463473'
[Fri Aug 14 16:51:00 CST 2020] Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/15137060/131463473'
[Fri Aug 14 16:51:00 CST 2020] url='https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/94107894'
[Fri Aug 14 16:51:00 CST 2020] payload
[Fri Aug 14 16:51:00 CST 2020] POST
[Fri Aug 14 16:51:00 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/94107894'
[Fri Aug 14 16:51:00 CST 2020] _CURL='curl -L --silent --dump-header /home/liyuan/.acme.sh/http.header  -g '
[Fri Aug 14 16:51:06 CST 2020] _ret='0'
[Fri Aug 14 16:51:06 CST 2020] code='200'
[Fri Aug 14 16:51:06 CST 2020] d='cvat.hohonote.com'
[Fri Aug 14 16:51:06 CST 2020] Getting webroot for domain='cvat.hohonote.com'
[Fri Aug 14 16:51:06 CST 2020] _w='/home/liyuan/CVAT/cvat/letsencrypt-webroot'
[Fri Aug 14 16:51:06 CST 2020] _currentRoot='/home/liyuan/CVAT/cvat/letsencrypt-webroot'
[Fri Aug 14 16:51:06 CST 2020] entry='"type":"http-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ","token":"4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE"'
[Fri Aug 14 16:51:06 CST 2020] token='4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE'
[Fri Aug 14 16:51:06 CST 2020] uri='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ'
[Fri Aug 14 16:51:06 CST 2020] keyauthorization='4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE.ql9uEpa2XVpsz3Vo-61SaR8Rjcl4u5VE6B4seHR1mC4'
[Fri Aug 14 16:51:06 CST 2020] dvlist='cvat.hohonote.com#4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE.ql9uEpa2XVpsz3Vo-61SaR8Rjcl4u5VE6B4seHR1mC4#https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ#http-01#/home/liyuan/CVAT/cvat/letsencrypt-webroot'
[Fri Aug 14 16:51:06 CST 2020] d
[Fri Aug 14 16:51:06 CST 2020] vlist='cvat.hohonote.com#4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE.ql9uEpa2XVpsz3Vo-61SaR8Rjcl4u5VE6B4seHR1mC4#https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ#http-01#/home/liyuan/CVAT/cvat/letsencrypt-webroot,'
[Fri Aug 14 16:51:06 CST 2020] d='cvat.hohonote.com'
[Fri Aug 14 16:51:06 CST 2020] ok, let's start to verify
[Fri Aug 14 16:51:06 CST 2020] Verifying: cvat.hohonote.com
[Fri Aug 14 16:51:06 CST 2020] d='cvat.hohonote.com'
[Fri Aug 14 16:51:06 CST 2020] keyauthorization='4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE.ql9uEpa2XVpsz3Vo-61SaR8Rjcl4u5VE6B4seHR1mC4'
[Fri Aug 14 16:51:06 CST 2020] uri='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ'
[Fri Aug 14 16:51:06 CST 2020] _currentRoot='/home/liyuan/CVAT/cvat/letsencrypt-webroot'
[Fri Aug 14 16:51:06 CST 2020] wellknown_path='/home/liyuan/CVAT/cvat/letsencrypt-webroot/.well-known/acme-challenge'
[Fri Aug 14 16:51:06 CST 2020] writing token:4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE to /home/liyuan/CVAT/cvat/letsencrypt-webroot/.well-known/acme-challenge/4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE
[Fri Aug 14 16:51:06 CST 2020] Changing owner/group of .well-known to root:root
[Fri Aug 14 16:51:06 CST 2020] chown: changing ownership of '/home/liyuan/CVAT/cvat/letsencrypt-webroot/.well-known/acme-challenge/Kb4078Y7-Z_vq6uUUt9TFG51tiHn-5qpZDN5RlwOtXk': Operation not permitted
chown: changing ownership of '/home/liyuan/CVAT/cvat/letsencrypt-webroot/.well-known/acme-challenge/4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE': Operation not permitted
chown: changing ownership of '/home/liyuan/CVAT/cvat/letsencrypt-webroot/.well-known/acme-challenge/7BowmtSyWvL0IdRNmR9gj-8C5Sgy7gmo2V8BvILfonI': Operation not permitted
chown: changing ownership of '/home/liyuan/CVAT/cvat/letsencrypt-webroot/.well-known/acme-challenge': Operation not permitted
chown: changing ownership of '/home/liyuan/CVAT/cvat/letsencrypt-webroot/.well-known': Operation not permitted
[Fri Aug 14 16:51:06 CST 2020] url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ'
[Fri Aug 14 16:51:06 CST 2020] payload='{}'
[Fri Aug 14 16:51:06 CST 2020] POST
[Fri Aug 14 16:51:06 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ'
[Fri Aug 14 16:51:06 CST 2020] _CURL='curl -L --silent --dump-header /home/liyuan/.acme.sh/http.header  -g '
[Fri Aug 14 16:51:12 CST 2020] _ret='0'
[Fri Aug 14 16:51:12 CST 2020] code='200'
[Fri Aug 14 16:51:12 CST 2020] trigger validation code: 200
[Fri Aug 14 16:51:12 CST 2020] sleep 2 secs to verify
[Fri Aug 14 16:51:14 CST 2020] checking
[Fri Aug 14 16:51:14 CST 2020] url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ'
[Fri Aug 14 16:51:14 CST 2020] payload
[Fri Aug 14 16:51:14 CST 2020] POST
[Fri Aug 14 16:51:14 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ'
[Fri Aug 14 16:51:14 CST 2020] _CURL='curl -L --silent --dump-header /home/liyuan/.acme.sh/http.header  -g '
[Fri Aug 14 16:51:21 CST 2020] _ret='0'
[Fri Aug 14 16:51:21 CST 2020] code='200'
[Fri Aug 14 16:51:21 CST 2020] cvat.hohonote.com:Verify error:DNS problem: NXDOMAIN looking up A for cvat.hohonote.com - check that a DNS record exists for this domain
[Fri Aug 14 16:51:21 CST 2020] Debug: get token url.
[Fri Aug 14 16:51:21 CST 2020] GET
[Fri Aug 14 16:51:21 CST 2020] url='http://cvat.hohonote.com/.well-known/acme-challenge/4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE'
[Fri Aug 14 16:51:21 CST 2020] timeout=1
[Fri Aug 14 16:51:21 CST 2020] _CURL='curl -L --silent --dump-header /home/liyuan/.acme.sh/http.header  -g  --connect-timeout 1'
[Fri Aug 14 16:51:22 CST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Fri Aug 14 16:51:22 CST 2020] ret='6'
[Fri Aug 14 16:51:22 CST 2020] Debugging, skip removing: /home/liyuan/CVAT/cvat/letsencrypt-webroot/.well-known/acme-challenge/4ws-3rL4LPKF1mY8VGsS4F1NjV1MRnDkCffIP2LeGfE
[Fri Aug 14 16:51:22 CST 2020] pid
[Fri Aug 14 16:51:22 CST 2020] No need to restore nginx, skip.
[Fri Aug 14 16:51:22 CST 2020] _clearupdns
[Fri Aug 14 16:51:22 CST 2020] dns_entries
[Fri Aug 14 16:51:22 CST 2020] skip dns.
[Fri Aug 14 16:51:22 CST 2020] _on_issue_err
[Fri Aug 14 16:51:22 CST 2020] Please add '--debug' or '--log' to check more details.
[Fri Aug 14 16:51:22 CST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Fri Aug 14 16:51:22 CST 2020] url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ'
[Fri Aug 14 16:51:22 CST 2020] payload='{}'
[Fri Aug 14 16:51:22 CST 2020] POST
[Fri Aug 14 16:51:22 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/94107894/5T4kkQ'
[Fri Aug 14 16:51:22 CST 2020] _CURL='curl -L --silent --dump-header /home/liyuan/.acme.sh/http.header  -g '
[Fri Aug 14 16:51:38 CST 2020] _ret='0'
[Fri Aug 14 16:51:38 CST 2020] code='400'
[Fri Aug 14 16:51:38 CST 2020] socat doesn't exist.
[Fri Aug 14 16:51:38 CST 2020] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2p  14 Aug 2018
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
Content of file named "docker-compose.override.yml" is as follows:
version: "2.3"

services:
  cvat_proxy:
    environment:
      CVAT_HOST: "cvat.hohonote.com 172.16.181.166"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt-webroot:/var/tmp/letsencrypt-webroot
      - /root/.acme.sh:/root/.acme.sh
        
  cvat:
    environment:
      ALLOWED_HOSTS: '*'
      CVAT_SHARE_URL: "Mounted from /mnt/share host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/myshare
      o: bind
### Possible Solution

register a fresh public domain may help, but I wonder whether I could setup https support without putting my CVAT host onto public network? What should I do to make it in the local network..
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):Ubuntu 18.04.4 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hi, it's expected behavior, the letsencript service cannot issue a certificate for domains that cannot be resolved and this guide cannot cover this case.
I can only suggest creating a self signed certificate, but it will not be accepted by any browser by default. Is it applicable for you?

**Comment by ly10951** [comment]
Got it, I will try for that. Thanks for your help I really appreciate it.
