### ISSUE TITLE
How to create new project in cvat 

### ISSUE THREAD

**Issue by hyperparameters** [opencv/cvat#2039]
I can see a default project at the top of the tasks page. 
how to create a new project, no link to create project

![image](https://user-images.githubusercontent.com/38223893/90371953-50460c80-e08d-11ea-8367-689ef975d6f7.png)

I can see `swagger` API has `projects`   `create projects` APIs how are those used

![image](https://user-images.githubusercontent.com/38223893/90372213-a9ae3b80-e08d-11ea-95cf-bc7203ddfc30.png)

**Comment by bsekachev** [comment]
@hyperparameters 

Hi, client doesn't support projects yet. It is only server side functionality. We are planning to implement it soon on the client.
@ActiveChooN will work on it.

**Comment by rectorkipa** [comment]
> @hyperparameters
> 
> Hi, client doesn't support projects yet. It is only server side functionality. We are planning to implement it soon on the client. @ActiveChooN will work on it.

still can't create project from CVAT API?
