### ISSUE TITLE
How to uninstall CVAT from my system?

### ISSUE THREAD

**Issue by MysteryCoder456** [opencv/cvat#2044]

**Comment by nmanovic** [comment]
@MysteryCoder456 , run `docker-compose down -v`. It will removes containers together with data. Let me know if you deploy any serverless functions. Need to use  `nuctl delete function ...` to delete them as well.

**Comment by MysteryCoder456** [comment]
Does this also uninstall all the huge Python packages installed (example Tensorflow, Django, etc.)?

**Comment by nmanovic** [comment]
@MysteryCoder456 , if you install CVAT in docker (as explained in official installation guide), it will not install packages on your local machine but instead inside the docker container.

**Comment by MysteryCoder456** [comment]
Thanks @nmanovic
