### ISSUE TITLE
cvat no such container

### ISSUE THREAD

**Issue by chrisdevday** [opencv/cvat#2047]
Sure this is something stupid but need some help.

Trying to install on a jetson xavier running ubuntu 18.04

I have got to the creating a superuser step

~/cvat$ docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'

but i am getting the following error:
Error: No such container: cvat

I've followed every step but something has gone wrong.

can anyone point me to what ive missed

Thank you Chris

**Comment by chrisdevday** [comment]
i re-ran _docker-compose up -d_ command and got a lot of red. including error that cvat failed to build.

any help would be appreciated

thanks

![Screenshot from 2020-08-18 14-40-40](https://user-images.githubusercontent.com/45659471/90520242-0595c480-e161-11ea-8789-20ab41936121.png)

**Comment by chrisdevday** [comment]
I think this may be because I'm trying to install on Arm architecture (nvidia jetson xavier)

**Comment by bsekachev** [comment]
Looks like there aren't package ``gstreamer`` for your architecture. We do not support ARM, but you can try look for help on gitter chat

**Comment by christianburbon** [comment]
I'm still new to this and cannot resolve this issue.

I ran into same issue of "No such container: cvat"
However, when I re-ran docker-compose up -d, I get error message "error creating temporary  lease: write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db read-only file system: uknown"
![Screenshot 2021-02-27 052422](https://user-images.githubusercontent.com/62530849/109345580-1b2c3980-78bc-11eb-98f4-25be5a7867a1.jpg)
