### ISSUE TITLE
WARNING:django.request:Unauthorized: /api/v1/users/self when using signed URL.

### ISSUE THREAD

**Issue by andyDoucette** [opencv/cvat#2056]
## Issue

When, as a normal user, I create a signed url using the /auth/signing API endpoint, I successfully get a signed url back.  
To do this, I used the "Try it out" in the swagger documentation for that endpoint, and entered this as the input:

```
{
  "url": "http://localhost:8080/tasks/562/jobs/551"
}
```

However, if I clear all site data (chrome->right click -> inspect -> Application -> Clear site data) to simulate a fresh user coming to the site and open that url, it brings me to the login page.  The cvat logs show this:

```
2020-08-20 05:49:26,847 DEBG 'runserver' stderr output:
[Thu Aug 20 05:49:26.847693 2020] [wsgi:error] [pid 247:tid 139982626047744] [remote 172.24.0.6:53902] WARNING:django.request:Unauthorized: /api/v1/users/self
```

## What I expect:
For it to log me in automatically with the user I signed the url as and go directly to the url I requested, "http://localhost:8080/tasks/562/jobs/551".

I've tried both the v1.1.0-alpha branch and the latest develop (582e23bf889ef4a47dc09cdcd8074ac65e3fe00d).  Any help would be greatly appreciated.

Is this feature supposed to be working?  Can you confirm that it's not working as desired right now?

**Comment by nmanovic** [comment]
@andyDoucette , it is expected that users have valid cookies. Need to think more about the feature. Could you please describe your scenario? How are you going to use the feature. If we implement the scenario, users with the URL will have your permissions in CVAT.

**Comment by andyDoucette** [comment]
I assume the purpose of the  /auth/signing endpoint is to give someone a url that they can use to get to a page and "auto-login" on the way.  If that's not the purpose, then that's what I'm needing.  It's cumbersome to say "go to this URL, then use this username and this password, log in, select the task, then select the job, with the new UI, etc".  What I want to do is send them a link to the job itself in the new UI, signed so that it will auto-login with the credentials I made for them.  Does that make sense?

I'm using CVAT with mturk where everyone needs their own credentials and they may only work on one job in their whole life.
