### ISSUE TITLE
Adding label with quotation is successful but does not allow any labels after

### ISSUE THREAD

**Issue by Paperone80** [opencv/cvat#206]
Hi,

I can successfully add the following label and it is also showing in the UI:
`label ~radio=labelattributes:"yes","missing","can't tell"`

However, adding any subsequent label via 'Update Task' results in the following error:

> Task update error. No closing quotation

I am using cvat github version from 2018-11-19.

**Comment by nmanovic** [comment]
Hi @Paperone80 ,

Thanks for your report. It is a bug due to "can't" word with apostrophe. We are going to fix it. Don't hesitate to send us a PR with the fix.
