### ISSUE TITLE
Data lost after restoring from backup file of docker container volume

### ISSUE THREAD

**Issue by ly10951** [opencv/cvat#2061]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have made a backup of my CVAT database cvat_db following the guide line here: https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes  as recommend. However after running the command to restore the data a server error occurred with code 500 to my server, and all data were unable to find. What should I do?

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by ly10951** [comment]
I have attached into the container cvat and found tasks created  were all available, but I can see none of them when I open it  using browser...besides all username were unable to use..
How does it happen?

**Comment by ly10951** [comment]
Follows are logs of container  cvat:

2020-08-21 06:29:36,022 DEBG 'runserver' stderr output:
[Fri Aug 21 06:29:36.022615 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] [2020-08-21 06:29:36,021] ERROR django.request: Internal Server Error: /api/v1/auth/login
[Fri Aug 21 06:29:36.022633 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] Traceback (most recent call last):
[Fri Aug 21 06:29:36.022635 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
[Fri Aug 21 06:29:36.022637 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self.connect()
[Fri Aug 21 06:29:36.022638 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 195, in connect
[Fri Aug 21 06:29:36.022639 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self.connection = self.get_new_connection(conn_params)
[Fri Aug 21 06:29:36.022641 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
[Fri Aug 21 06:29:36.022642 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     connection = Database.connect(**conn_params)
[Fri Aug 21 06:29:36.022643 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
[Fri Aug 21 06:29:36.022644 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[Fri Aug 21 06:29:36.022646 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] psycopg2.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution
[Fri Aug 21 06:29:36.022647 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] 
[Fri Aug 21 06:29:36.022648 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] 
[Fri Aug 21 06:29:36.022649 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] The above exception was the direct cause of the following exception:
[Fri Aug 21 06:29:36.022650 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] 
[Fri Aug 21 06:29:36.022651 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] Traceback (most recent call last):
[Fri Aug 21 06:29:36.022652 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Fri Aug 21 06:29:36.022653 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     response = get_response(request)
[Fri Aug 21 06:29:36.022654 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
[Fri Aug 21 06:29:36.022656 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     response = self.process_exception_by_middleware(e, request)
[Fri Aug 21 06:29:36.022657 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
[Fri Aug 21 06:29:36.022658 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Aug 21 06:29:36.022659 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Fri Aug 21 06:29:36.022660 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return view_func(*args, **kwargs)
[Fri Aug 21 06:29:36.022661 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 71, in view
[Fri Aug 21 06:29:36.022664 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return self.dispatch(request, *args, **kwargs)
[Fri Aug 21 06:29:36.022665 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 45, in _wrapper
[Fri Aug 21 06:29:36.022666 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return bound_method(*args, **kwargs)
[Fri Aug 21 06:29:36.022667 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
[Fri Aug 21 06:29:36.022669 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return view(request, *args, **kwargs)
[Fri Aug 21 06:29:36.022670 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_auth/views.py", line 49, in dispatch
[Fri Aug 21 06:29:36.022671 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return super(LoginView, self).dispatch(*args, **kwargs)
[Fri Aug 21 06:29:36.022672 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 495, in dispatch
[Fri Aug 21 06:29:36.022674 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     response = self.handle_exception(exc)
[Fri Aug 21 06:29:36.022675 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 455, in handle_exception
[Fri Aug 21 06:29:36.022676 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self.raise_uncaught_exception(exc)
[Fri Aug 21 06:29:36.022677 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 466, in raise_uncaught_exception
[Fri Aug 21 06:29:36.022678 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     raise exc
[Fri Aug 21 06:29:36.022679 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 492, in dispatch
[Fri Aug 21 06:29:36.022680 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     response = handler(request, *args, **kwargs)
[Fri Aug 21 06:29:36.022681 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_auth/views.py", line 103, in post
[Fri Aug 21 06:29:36.022682 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self.serializer.is_valid(raise_exception=True)
[Fri Aug 21 06:29:36.022683 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 236, in is_valid
[Fri Aug 21 06:29:36.022685 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self._validated_data = self.run_validation(self.initial_data)
[Fri Aug 21 06:29:36.022686 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 437, in run_validation
[Fri Aug 21 06:29:36.022687 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     value = self.validate(value)
[Fri Aug 21 06:29:36.022688 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_auth/serializers.py", line 78, in validate
[Fri Aug 21 06:29:36.022689 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     user = self._validate_username(username, password)
[Fri Aug 21 06:29:36.022691 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_auth/serializers.py", line 42, in _validate_username
[Fri Aug 21 06:29:36.022692 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     user = self.authenticate(username=username, password=password)
[Fri Aug 21 06:29:36.022693 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/rest_auth/serializers.py", line 25, in authenticate
[Fri Aug 21 06:29:36.022694 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return authenticate(self.context['request'], **kwargs)
[Fri Aug 21 06:29:36.022695 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 73, in authenticate
[Fri Aug 21 06:29:36.022696 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     user = backend.authenticate(request, **credentials)
[Fri Aug 21 06:29:36.022697 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/backends.py", line 20, in authenticate
[Fri Aug 21 06:29:36.022698 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     user = UserModel._default_manager.get_by_natural_key(username)
[Fri Aug 21 06:29:36.022700 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/base_user.py", line 44, in get_by_natural_key

2020-08-21 06:29:36,023 DEBG 'runserver' stderr output:
[Fri Aug 21 06:29:36.022701 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return self.get(**{self.model.USERNAME_FIELD: username})
[Fri Aug 21 06:29:36.022706 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
[Fri Aug 21 06:29:36.022707 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Fri Aug 21 06:29:36.022708 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/cacheops/query.py", line 354, in get
[Fri Aug 21 06:29:36.022709 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return qs._no_monkey.get(qs, *args, **kwargs)
[Fri Aug 21 06:29:36.022710 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 402, in get
[Fri Aug 21 06:29:36.022711 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     num = len(clone)
[Fri Aug 21 06:29:36.022712 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 256, in __len__
[Fri Aug 21 06:29:36.022713 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self._fetch_all()
[Fri Aug 21 06:29:36.022714 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/cacheops/query.py", line 273, in _fetch_all
[Fri Aug 21 06:29:36.022716 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return self._no_monkey._fetch_all(self)
[Fri Aug 21 06:29:36.022717 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
[Fri Aug 21 06:29:36.022718 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self._result_cache = list(self._iterable_class(self))
[Fri Aug 21 06:29:36.022719 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 55, in __iter__
[Fri Aug 21 06:29:36.022720 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
[Fri Aug 21 06:29:36.022721 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1131, in execute_sql
[Fri Aug 21 06:29:36.022722 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     cursor = self.connection.cursor()
[Fri Aug 21 06:29:36.022723 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 256, in cursor
[Fri Aug 21 06:29:36.022724 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     return self._cursor()
[Fri Aug 21 06:29:36.022725 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 233, in _cursor
[Fri Aug 21 06:29:36.022726 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self.ensure_connection()
[Fri Aug 21 06:29:36.022727 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
[Fri Aug 21 06:29:36.022729 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self.connect()
[Fri Aug 21 06:29:36.022730 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
[Fri Aug 21 06:29:36.022731 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     raise dj_exc_value.with_traceback(traceback) from exc_value
[Fri Aug 21 06:29:36.022733 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
[Fri Aug 21 06:29:36.022734 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self.connect()
[Fri Aug 21 06:29:36.022735 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 195, in connect
[Fri Aug 21 06:29:36.022736 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     self.connection = self.get_new_connection(conn_params)
[Fri Aug 21 06:29:36.022737 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
[Fri Aug 21 06:29:36.022738 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     connection = Database.connect(**conn_params)
[Fri Aug 21 06:29:36.022739 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
[Fri Aug 21 06:29:36.022740 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500]     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[Fri Aug 21 06:29:36.022742 2020] [wsgi:error] [pid 253:tid 139702464444160] [remote 172.23.0.6:44500] django.db.utils.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution

**Comment by azhavoro** [comment]
I don't know how Postgres works with the data files, but yes, I think it would be better.
I'll close the issue, feel free to reopen if you still have questions.

**Comment by arasharchor** [comment]
@azhavoro 
@ly10951 
Hi I have the same problem. Unfortunately, all containers in the server were mistakenly stopped and removed. Volumes are not deleted, but when I restart cvat, there is no more projects showing up in the website. I hope you could help. I had several datasets in the cvat.

**Comment by azhavoro** [comment]
@arasharchor Hi, please provide logs from cvat (or cvat_server) container.
Also provide output of `docker ps`, `docekr volume ls` and `docker inspect cvat` commands
