### ISSUE TITLE
While in drawing mode "move (on mouse wheel press and mouse move)" does not work with trackpad.

### ISSUE THREAD

**Issue by Paperone80** [opencv/cvat#207]
Hi,

I am using cvat github version from 2018-11-19.

From your documentation: 

> Click N for entering drawing mode. Now you can start your polygon. You can zoom in/out (on mouse wheel scroll) and move (on mouse wheel press and mouse move) while drawing. Click N again for completing the shape. Also you can set fixed number of points in the field "Poly Shape Size", then drawing will be stopped automatically. You can drag object after it was drawn and fix a position of an individual points after finishing the object. You can add/delete points after finishing.

I am using a mac for setup and testing and mainly the trackpad.  According to Apple help:

> Ctrl + CMD + Click - emulates clicking on scroll button

However, while zoom in/out works in drawing mode, moving the image does not work. While holding Ctrl + CMD also Click does NOT continue drawing though. 

Any suggestions? 

Bug on my side? If so, I'll have to trap a mouse from somewhere :)

**Comment by nmanovic** [comment]
@Paperone80 ,

Thanks for the report. I have tried on my local PC the scenario and it works. I was able to move image while drawing without any problems (keep my mouse's wheel down and move mouse). Could you please test with a mouse on your machine? I don't have apple trackpad in my hands. I hope you will help us to investigate the issue.

**Comment by nmanovic** [comment]
Hi @Paperone80 ,

I will close the issue because there is no any additional information from you. Don't hesitate to reopen the issue if your mouse doesn't work as well.
