### ISSUE TITLE
Dataset repository URL does not support gitlab subgroup repositories

### ISSUE THREAD

**Issue by ncbkr** [opencv/cvat#2072]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Our teams and projects are organized in gitlab groups and subgroups. The URL of the repository I wanted to use for task synchronization follows this pattern: `git@gitlab.com:<group>/<subgroup>/<repo>.git`. As this is a valid repository URL, I expected this to work as described in the User Guide.

### Current Behaviour
When I try to submit the task via the UI, an error message appears, telling me that the remote repository could not be read and that I should make sure I added an ssh key to git.

In order to further investigate, I tried to clone the very same repository from within the cvat docker container. The repository was successfully set up.

I then searched logs/cvat_server.log and found this line: `cmdline: git clone -v git@gitlab.com:<group>/<subgroup>.git`. So the URL I provided was cut off after the subgroup and the repository name was ignored, resulting in an invalid repository URL.

The function [_parse_url](https://github.com/opencv/cvat/blob/07de7141edbc980031da857579128088f7a4630a/cvat/apps/git/git.py#L75) confirmed this assumption. In the repository pattern, there are only capturing groups for user and repository

For me, the best solution would be if the url parsing could be extended in order to support also gitlabs groups and supgroups structure. At least there should be a better error message telling me that the repository url I want to use is not supported, The presented error was not helpful for finding the solution in my case. 

### Steps to Reproduce

1. In the UI click "create task"
2. enter any title
3. add any label
4. upload some local images
5. expand advanced configuration
6. for dataset repository URL enter an URL following this pattern: `git@gitlab.com:<group>/<subgroup>/<repo>.git`
7. click "submit"

### Context
Because of this issue we are currently not able to stick to our project structure. For us, this causes additional efforts in administrating repositories, users and roles as the dataset repository will have to live outside our groups & subgroups structure.

### Environment

- Git hash commit (`git log -1`): 07de7141edbc980031da857579128088f7a4630a
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.6-ce

**Comment by azhavoro** [comment]
Hi, could you please update you CVAT? Seems this issue was fixed already with https://github.com/opencv/cvat/issues/1651.

**Comment by bsekachev** [comment]
I will close the issue. Do not hesitate reopen it if you still experience the problem
