### ISSUE TITLE
Extract Clips from Videos with CVAT?

### ISSUE THREAD

**Issue by yh80ywol** [opencv/cvat#2073]
Hello there,

is it possible to extract clips from a larger video file?

For Example i got a 10 min. file and .json/.csv file with some annotations. 
Can i export now these clips? So i´ve got several clips witch last around 10sec. ?

Thanks in advance for your help.

**Comment by azhavoro** [comment]
Hi, I'm not sure that quite understand you question,
Do you want create a task from some long video file (annotate them or upload existing annotations) and export several short clips? If I understand correctly, the answer is no, CVAT is not a video editor and does not support video actions. You should split the original video yourself.

**Comment by yh80ywol** [comment]
> Do you want create a task from some long video file (annotate them or upload existing annotations) and export several short clips?

Yes, that´s what i wanted.
Ok thank you, i exported the timestamps and trimmed the videos with ffmpeg in python. 

Can be closed :-)
