### ISSUE TITLE
Calculation of area in coco annotations slightly off (rounded down)

### ISSUE THREAD

**Issue by LukeAI** [opencv/cvat#2074]
Noticed a small error in the coco dump of the annotations in that, for this particular example, area should be 3136.9 (or 3137) but it is given as 3136.0)

`{"area": 3136.0, "image_id": 10, "iscrowd": 0, "category_id": 2, "bbox": [116.0, 260.0, 70.0, 46.07305936073317], "id": 21, "    segmentation": [[116.0, 261.0, 186.0, 260.0, 186.0, 306.0, 118.24961948249802, 306.07305936073317]]}`

have included a little python code to verify:

```
import numpy as np
# calculate area of segmentation
def PolyArea(x, y):
    x = np.array(x, dtype=np.float)
    y = np.array(y, dtype=np.float)
    return 0.5*np.abs(np.dot(x, np.roll(y, 1)) -
                      np.dot(y, np.roll(x, 1)))

points = [[116.0, 261.0], [186.0, 260.0], [186.0, 306.0], [118.24961948249802, 306.0730593607, 3317]]
x_points = [p[0] for p in points]
y_points = [p[1] for p in points]
print(PolyArea(x_points, y_points))
# 3136.940639269451
```

**Comment by zhiltsov-max** [comment]
The algorithm above, while correct for regular polygons, does not work for self-intersecting ones, which we often have to handle. Unless it is a real problem and there is no better solution, I think, we should stick the current solution.

**Comment by LukeAI** [comment]
fair enough! it's not a problem for me.
