### ISSUE TITLE
Missing documentatio on how to 'You can add/delete points after finishing.'

### ISSUE THREAD

**Issue by Paperone80** [opencv/cvat#208]
Hi,

I am using cvat github version from 2018-11-19.

From your documentation:

> You can add/delete points after finishing.

I have figured out that 'double-click' on a point deletes it, but I haven't seen that explicitly mentioned on the docs. 

Also, how do you 'add' points???

Thanks.

**Comment by nmanovic** [comment]
@Paperone80 ,

The documentation is updated only for a release. Now documentation in develop is outdated. It will be improved till EOY together with 0.3.0 release: #180 

To add points please press `shift` and double client on a point. You will enter into "editing" mode. If you keep `shift` you can add new points without clicks. If you release `shift` you can add points one by one.

**Comment by nmanovic** [comment]
Hi @Paperone80 ,

We have added a new screencast to explain how to use polygons efficiently. I will close the issue.

https://www.youtube.com/watch?v=XTwfXDh4clI
