### ISSUE TITLE
collaborative tagging CVAT

### ISSUE THREAD

**Issue by ucesfpa** [opencv/cvat#2097]
How can I create a group for collaborative tagging? 
1. I am able to split the task in separate jobs
2. How do I invite external existing users to my task?
I looked on internet but I was not able to find related information.

**Comment by bsekachev** [comment]
Hi, 
Thanks for the question.
Try to assign a user on a task view. You can assign one user per job. The task and jobs are visible for assigned users.
Also you can assign a user for a whole task.
![Screenshot from 2020-08-31 08-01-32](https://user-images.githubusercontent.com/40690378/91684456-44178000-eb60-11ea-964e-71b0b1afab23.png)

**Comment by ucesfpa** [comment]
How to add a new assignee? should I go through the admin page add User? Will the assignee be able to enter the task even if he/she is on an other wifi? If so, does it means the data is uploaded to internet or they simply access my private server?

**Comment by bsekachev** [comment]
> How to add a new assignee? should I go through the admin page add User?

Start printing assignee nickname in the field. 

> Will the assignee be able to enter the task even if he/she is on an other wifi?

It depends on your setup. If you have forwarded your CVAT instance to the Internet, he/she can. If the instance is only in a local network - not. 

> If so, does it means the data is uploaded to internet or they simply access my private server?

Data are uploaded to your private server where you run ``docker-compose`` commands

**Comment by bsekachev** [comment]
@ucesfpa 

In common case you need to have "white" IP address without NAT and forward port in your router settings. 
It isn't CVAT questions, please google it. In CVAT only do not forget specify [right host](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#advanced-settings) that assumed to be your external IP address & port

**Comment by bsekachev** [comment]
I hope it answered your question. I will close the issue. Do not hesitate reopen it if you still need assistance or ask community on gitter
