### ISSUE TITLE
How to keep track id?

### ISSUE THREAD

**Issue by abcilike** [opencv/cvat#21]
After annotation done --> upload annotation:
The ID of the target is messed up.

How to include the id information of the calibration target in the exported annotation file, and re-import the annotation file without showing confusion.

**Comment by nmanovic** [comment]
Hi @abcilike ,

At the moment it isn't possible but we will consider to resolve the problem in one of our next releases. Thank you for your question.

**Comment by abcilike** [comment]
I found that the annotation file can save the target ID when importing the video, but not when importing the image sequence.

**Comment by nmanovic** [comment]
It doesn't work for videos in general case. The main problem here that each time when you press "save" button annotations are written to DB from scratch (not an increment). Need to track ID explicitly as an automatic attribute.

**Comment by SunskyF** [comment]
Hello, @nmanovic 
Could u give me an advice about how to dump annotation with track id? 
Actually, I just want to dump the relative object id (it means that in some frames, the same object has same id), not the id in annotation.
Thanks a lot!

**Comment by nmanovic** [comment]
@SunskyF ,

You should create "interpolation" task for that. It is created automatically if you upload a video file. If you load images the task will be considered as "annotation". At the moment the only way to dump "tracks" for "annotation" tasks is to change DB manually or change code (https://github.com/opencv/cvat/blob/master/cvat/apps/engine/annotation.py#L1015). 

Does it answer your question?

**Comment by SunskyF** [comment]
@nmanovic 
Thanks!
It helps me a lot.

**Comment by nmanovic** [comment]
#120 implements client_id for each annotation object.

**Comment by sjoycode** [comment]
> #120 implements client_id for each annotation object.

Is this feature already in **develop** branch? If I give image sequences as input the dumped annotation file still does **not** contain track ids. Instead, if I input the video file the annotation file does contain the track ids. I wonder if I am doing something wrong.

**Comment by nmanovic** [comment]
@sjoycode , at the moment if you annotate images you annotation will be in "annotation" format: https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/xml_format.md#annotation

**Comment by sttobia** [comment]
> @sjoycode , at the moment if you annotate images you annotation will be in "annotation" format: https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/xml_format.md#annotation

Are there still plans to integrate an object ID into the annotation format anytime soon? For tracking purposes this is crucial and a lot of labelling effort is lost if not being able to save the object id for later use. Especially when labelling frames of a video as single images using the interpolation mode.

**Comment by nmanovic** [comment]
Hi @sttobia , first of all you can workaround the issue. Go to admin panel and change "mode" for a task from "annotation" to "interpolation". You will loose image names but you will be able to dump the task in "interpolation" format.

In our nearst plans is to improve export/import annotations in different data annotation formats. It will close the issue completely. You will be able to upload/download annotations in most popular formats like COCO, PascalVOC, etc... I realized that it is the most critical feature for many users.

**Comment by sttobia** [comment]
> Hi @sttobia , first of all you can workaround the issue. Go to admin panel and change "mode" for a task from "annotation" to "interpolation". You will loose image names but you will be able to dump the task in "interpolation" format.
> 
> In our nearst plans is to improve export/import annotations in different data annotation formats. It will close the issue completely. You will be able to upload/download annotations in most popular formats like COCO, PascalVOC, etc... I realized that it is the most critical feature for many users.

Thanks for the quick reply! Does this also work for images and not videos? I am using single frames named using a sensor timestamp which is crucial for later reuse of the labels. Therefore the image name is somehow also critical for me.
Those plans sound very nice. Still I thought the xml file was a nice solution givin the conversion scripts in /utils you provided for the most popular formats.

**Comment by garyJune** [comment]
Hi, am wondering is this issue fixed?
I am trying to upload coco annotation JSON with specified tracking ID within attributes (under interpolation mode), current CVAT seem to still reset the ID, turn the bbox into a normal annotation and loose the track. Is there a way around? 
Thanks!

**Comment by blakete** [comment]
> Hi, am wondering is this issue fixed? I am trying to upload coco annotation JSON with specified tracking ID within attributes (under interpolation mode), current CVAT seem to still reset the ID, turn the bbox into a normal annotation and loose the track. Is there a way around? Thanks!

Have you found an answer to this? This feature is a requirement for my project.

**Comment by blakete** [comment]
> Hi @abcilike ,
> 
> At the moment it isn't possible but we will consider to resolve the problem in one of our next releases. Thank you for your question.

Has this feature been added? Is there another way around this? Uploading annotations with track ids is a requirement for my project. I look forward to hearing back from you. Thank you.

**Comment by blakete** [comment]
> Hi @sttobia , first of all you can workaround the issue. Go to admin panel and change "mode" for a task from "annotation" to "interpolation". You will loose image names but you will be able to dump the task in "interpolation" format.
> 
> In our nearst plans is to improve export/import annotations in different data annotation formats. It will close the issue completely. You will be able to upload/download annotations in most popular formats like COCO, PascalVOC, etc... I realized that it is the most critical feature for many users.

Hello! Has this label upload improvement been implemented? I am still experiencing the issue of tracking labels turning back to regular labels upon upload of labels in COCO 1.0 format. This feature is a critical requirement for my project. I look forward to hearing back from you. Thank you.

**Comment by castrovictor** [comment]
> > Hi @sttobia , first of all you can workaround the issue. Go to admin panel and change "mode" for a task from "annotation" to "interpolation". You will loose image names but you will be able to dump the task in "interpolation" format.
> > In our nearst plans is to improve export/import annotations in different data annotation formats. It will close the issue completely. You will be able to upload/download annotations in most popular formats like COCO, PascalVOC, etc... I realized that it is the most critical feature for many users.
> 
> Hi, has this label upload improvement been implemented? I am still experiencing the issue of tracking labels turning back to regular labels upon upload of labels in COCO 1.0 format. This feature is a critical requirement for my project. I look forward to hearing back from you. Thank you.

I'm in the same situation. I have been able to dump ids for objects manually drawn when creating task from video, but I am not able to import annotations with the ids, it rewrites them. It's not a problem at all the change of ids itself, the biggest problem is that it uses new ones for each frame. So it completely ignores the tracking part.

**Comment by castrovictor** [comment]
I don't mind trying to modify the function in charge of it and doing a pull request if I make it. But I do not longer see the file [cvat/apps/engine/annotation.py](https://github.com/opencv/cvat/pull/120/files/3954c0ff95901906546223d4ecce14af72b994c0#diff-6b4ec15fdc86a4bfc38c440986f5ba34e16ec6131db091765b8fd5e44d54a05b) 
Could anyone indicate me where should I look at? Unfortunately I don't have time to read the whole code project
