### ISSUE TITLE
How to convert COCO format datasets to MOT format?

### ISSUE THREAD

**Issue by Veronica1997** [opencv/cvat#2103]
Thanks a lot!

**Comment by zhiltsov-max** [comment]
You can use Datumaro for this, take a look at [examples](https://github.com/opencv/cvat/tree/develop/datumaro#examples). For simple conversion of MOT to COCO you need to do:
```
datum convert \
    --input-format mot_seq --input-path <path/to/mot/directory> \
    --output-format coco
```

Datumaro expects MOT datasets to be in [this layout](https://github.com/opencv/cvat/tree/develop/datumaro/tests/assets/mot_dataset).

**Comment by Veronica1997** [comment]
> You can use Datumaro for this, take a look at [examples](https://github.com/opencv/cvat/tree/develop/datumaro#examples). For simple conversion of MOT to COCO you need to do:
> 
> ```
> datum convert \
>     --input-format mot_seq --input-path <path/to/mot/directory> \
>     --output-format coco
> ```
> 
> Datumaro expects MOT datasets to be in [this layout](https://github.com/opencv/cvat/tree/develop/datumaro/tests/assets/mot_dataset).

Thank you very much for solving my problem! appreciate!
