### ISSUE TITLE
Possibly Feature Request: track for tag

### ISSUE THREAD

**Issue by hollowgalaxy** [opencv/cvat#2117]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Looking for a way to annotation an activity in a video (say somebody doing jumping jacks) so that by the end I have an annotation that says Person started jumping jacks at 0:35 and finished jumping jacks at 0:37
possible have a track option for tag.

### Current Behaviour

Currently using bounding box (although could have used any of the other drawing options.

### Possible Solution

Possible idea, is to allow tag with tracking option?

### Context

Having to draw an object to track an activity which sometimes doesn't need spacial information can cause an annotator to use unnecessary time trying to annotate. If annotators goal is just finding start and stop time for activity, they should have the ability to focus on that only.

### Your Environment
unedited docker-compose up

**Comment by nmanovic** [comment]
Hi @hollowgalaxy , I agree. It can be useful. We have a similar issue on github: https://github.com/opencv/cvat/issues/1228
