### ISSUE TITLE
How to see serverless function log

### ISSUE THREAD

**Issue by nvmnghia** [opencv/cvat#2119]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

See function log somewhere.

### Current Behaviour

Can't see function log in Nuclio dashboard. Only build log is provided.

### Steps to Reproduce (for bugs)

No steps.

### Context

Both Nuclio and CVAT documentation is vague about logging for serverless function.

### Your Environment

- Git hash commit (`git log -1`): `ae6ec401354ac525a49cd399c8b42172988fa7ec`
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Lubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem: Not needed
- Other diagnostic information / logs: None

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@nvmnghia , thanks for the report. You can use `docker logs <container for a function>`. To understand which containers you have run `docker ps`.  

Does it answer the question?

**Comment by nvmnghia** [comment]
@nmanovic I've just figured it out, thanks for your support. I thought I had to install Kibana or something just to see the log.
