### ISSUE TITLE
Could not save annotations

### ISSUE THREAD

**Issue by mfruhner** [opencv/cvat#2157]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
The annotations are saved without a problem

### Current Behaviour
A popup appears with the following message:

Could not save annotations
Error: Request failed with status code 400. "duplicate key value violates unique constraint \"engine_trackedshape_pkey\"\nDETAIL: Key (id)=(113) already exists.\n".

### Steps to Reproduce (for bugs)

I am annotating a video with the tracking bounding boxes. When trying to save mid way through, the error appears.

### Context
I am not able to save any annotations. All my work will be lost, when I close the window. When opening the job in a 2nd window it show the last save was 400 frames ago.

Edit: I was able to "save" my work by downloading the annotation via the "Menu" -> "Dump annotations" / "Export Dataset" Buttons.

### Your Environment

- Git hash commit (`git log -1`): cb4d8e6ee571594f74ff96bc6cbc7c597c732e4a
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.5
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu Desktop
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>
2020-09-09 07:05:44,580 DEBG 'runserver' stderr output:
[Wed Sep 09 07:05:44.580126 2020] [wsgi:error] [pid 630:tid 139984631072512] [remote 172.28.0.7:54352] WARNING:django.request:Bad Request: /api/v1/jobs/2/annotations
</summary>
    </details>

**Comment by bsekachev** [comment]
Looks like quite serious issue, but unfortunately we rarely meet it and reproducing (to get root cause) isn't simple. 
I would recommend you to save your work more often (you can enable autosave functionality in settings).
Speaking about the issue, let's assign bug label, but I can't say when it was fixed because of problems with reproducing.

**Comment by bsekachev** [comment]
By the way, when you press ``Dump annotations``, it dumps from the database. So, if you do not see results of your work in another browser tab after updating a page, it's impossible, that your results saved in dumped file, since they have the same source.

**Comment by nmanovic** [comment]
@mfruhner , ` I was able to "save" my work by downloading the annotation via the "Menu" -> "Dump annotations" / "Export Dataset" Buttons.`

Was the issue resolved?

**Comment by mfruhner** [comment]
No, as @bsekachev mentioned, the unsaved annotations were not exported in the dataset. 
I closed the window and lost my work. I could then restart from my last savepoint though.. 
this Bug is still an issue. 

Greetings, Maik

**Comment by vinayshah01** [comment]
I am getting the same error using the REST API when trying to create a new track using a subset of the shapes of an existing track. 

Here's the output from my cvat logs: 

2020-09-25 13:33:11,828 DEBG 'runserver' stderr output:
[Fri Sep 25 13:33:11.828394 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394] ERROR:django.request:Internal Server Error: /api/v1/tasks/80/annotations
[Fri Sep 25 13:33:11.828403 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394] Traceback (most recent call last):
[Fri Sep 25 13:33:11.828408 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
[Fri Sep 25 13:33:11.828414 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return self.cursor.execute(sql, params)
[Fri Sep 25 13:33:11.828419 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394] psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "engine_trackedshape_pkey"
[Fri Sep 25 13:33:11.828425 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394] DETAIL:  Key (id)=(490734) already exists.
[Fri Sep 25 13:33:11.828430 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]
[Fri Sep 25 13:33:11.828434 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]
[Fri Sep 25 13:33:11.828439 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394] The above exception was the direct cause of the following exception:
[Fri Sep 25 13:33:11.828444 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]
[Fri Sep 25 13:33:11.828448 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394] Traceback (most recent call last):
[Fri Sep 25 13:33:11.828453 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
[Fri Sep 25 13:33:11.828458 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     response = get_response(request)
[Fri Sep 25 13:33:11.828463 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
[Fri Sep 25 13:33:11.828468 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Sep 25 13:33:11.828473 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Fri Sep 25 13:33:11.828478 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return view_func(*args, **kwargs)
[Fri Sep 25 13:33:11.828483 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/rest_framework/viewsets.py", line 114, in view
[Fri Sep 25 13:33:11.828489 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return self.dispatch(request, *args, **kwargs)
[Fri Sep 25 13:33:11.828493 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
[Fri Sep 25 13:33:11.828498 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     response = self.handle_exception(exc)
[Fri Sep 25 13:33:11.828503 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
[Fri Sep 25 13:33:11.828509 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     self.raise_uncaught_exception(exc)
[Fri Sep 25 13:33:11.828513 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
[Fri Sep 25 13:33:11.828518 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     raise exc
[Fri Sep 25 13:33:11.828532 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
[Fri Sep 25 13:33:11.828539 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     response = handler(request, *args, **kwargs)
[Fri Sep 25 13:33:11.828544 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/engine/views.py", line 512, in annotations
[Fri Sep 25 13:33:11.828550 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     data = dm.task.put_task_data(pk, serializer.data)
[Fri Sep 25 13:33:11.828555 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/profiler.py", line 11, in wrapped
[Fri Sep 25 13:33:11.828560 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return f(*args, **kwargs)
[Fri Sep 25 13:33:11.828564 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
[Fri Sep 25 13:33:11.828570 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return func(*args, **kwds)
[Fri Sep 25 13:33:11.828575 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 712, in put_task_data
[Fri Sep 25 13:33:11.828580 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     annotation.put(data)
[Fri Sep 25 13:33:11.828584 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 596, in put
[Fri Sep 25 13:33:11.828589 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     self._patch_data(data, None)
[Fri Sep 25 13:33:11.828594 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 584, in _patch_data
[Fri Sep 25 13:33:11.828599 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     _data.data = put_job_data(jid, job_data)
[Fri Sep 25 13:33:11.828604 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/profiler.py", line 11, in wrapped
[Fri Sep 25 13:33:11.828609 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return f(*args, **kwargs)
[Fri Sep 25 13:33:11.828614 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
[Fri Sep 25 13:33:11.828619 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return func(*args, **kwds)
[Fri Sep 25 13:33:11.828623 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 661, in put_job_data
[Fri Sep 25 13:33:11.828628 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     annotation.put(data)
[Fri Sep 25 13:33:11.828633 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 322, in put
[Fri Sep 25 13:33:11.828638 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     self._create(data)
[Fri Sep 25 13:33:11.828643 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 312, in _create
[Fri Sep 25 13:33:11.828648 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     if self._save_to_db(data):
[Fri Sep 25 13:33:11.828653 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 307, in _save_to_db
[Fri Sep 25 13:33:11.828658 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     self._save_tracks_to_db(data["tracks"])
[Fri Sep 25 13:33:11.828663 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 178, in _save_tracks_to_db
[Fri Sep 25 13:33:11.828669 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     db_shapes = bulk_create(
[Fri Sep 25 13:33:11.828674 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/home/django/cvat/apps/dataset_manager/task.py", line 46, in bulk_create
[Fri Sep 25 13:33:11.828679 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return db_model.objects.bulk_create(objects)
[Fri Sep 25 13:33:11.828683 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
[Fri Sep 25 13:33:11.828689 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Fri Sep 25 13:33:11.828694 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/cacheops/query.py", line 373, in bulk_create
[Fri Sep 25 13:33:11.828699 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     objs = self._no_monkey.bulk_create(self, objs, *args, **kwargs)
[Fri Sep 25 13:33:11.828704 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 506, in bulk_create
[Fri Sep 25 13:33:11.828709 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     returned_columns = self._batched_insert(
[Fri Sep 25 13:33:11.828714 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1266, in _batched_insert
[Fri Sep 25 13:33:11.828719 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     inserted_rows.extend(self._insert(
[Fri Sep 25 13:33:11.828724 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1249, in _insert
[Fri Sep 25 13:33:11.828729 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return query.get_compiler(using=using).execute_sql(returning_fields)
[Fri Sep 25 13:33:11.828734 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
[Fri Sep 25 13:33:11.828739 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     cursor.execute(sql, params)
[Fri Sep 25 13:33:11.828744 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/cacheops/transaction.py", line 93, in execute
[Fri Sep 25 13:33:11.828749 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     result = self._no_monkey.execute(self, sql, params)
[Fri Sep 25 13:33:11.828755 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute

2020-09-25 13:33:11,829 DEBG 'runserver' stderr output:
[Fri Sep 25 13:33:11.828760 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
[Fri Sep 25 13:33:11.828773 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
[Fri Sep 25 13:33:11.828779 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return executor(sql, params, many, context)
[Fri Sep 25 13:33:11.828784 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
[Fri Sep 25 13:33:11.828790 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return self.cursor.execute(sql, params)
[Fri Sep 25 13:33:11.828794 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
[Fri Sep 25 13:33:11.828800 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     raise dj_exc_value.with_traceback(traceback) from exc_value
[Fri Sep 25 13:33:11.828805 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
[Fri Sep 25 13:33:11.828810 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]     return self.cursor.execute(sql, params)
[Fri Sep 25 13:33:11.828817 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394] django.db.utils.IntegrityError: duplicate key value violates unique constraint "engine_trackedshape_pkey"
[Fri Sep 25 13:33:11.828822 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394] DETAIL:  Key (id)=(490734) already exists.
[Fri Sep 25 13:33:11.828827 2020] [wsgi:error] [pid 919:tid 140326713788160] [remote 172.28.0.7:40394]

**Comment by vinayshah01** [comment]
It seems like CVAT got itself into a bad state.  I can not create any new shapes.  This includes new annotations or new key frames to existing tracks.  This is through both the GUI and the REST interface. I have tried rebooting the machine and still no luck.  Moving/resizing  existing shapes seems to work fine.

**Comment by bsekachev** [comment]
@vinayshah01 

``when trying to create a new track using a subset of the shapes of an existing track.``
It is not allowed. Doing it, you are trying to create shapes that already created (see the message ``DETAIL: Key (id)=(490734) already exists.``). All these shapes have property ``id`` which is a primary key in the database and you can put one more instance to db with existing key.

**Comment by vinayshah01** [comment]
@bsekachev thanks for the response.  

I was not populating the id field.  After posting the message I realized my issue is more general and I can not add any new annotations or key frames to existing annotations (either through the GUI or REST interface).  It looks to be in a bad state (possibly because a network failure while adding annotations).

**Comment by vinayshah01** [comment]
@bsekachev 
I have deleted all the docker volumes and re-built the containers.  It worked for a little while and then would get into this state again.  The last time it got into this state was when simply adding key frames via the web interface.

**Comment by vinayshah01** [comment]
It looks like I can repeatedly reproduce this behavior when adding a large track (one shape per frame), containing over 70k+ frames, via the REST API.

**Comment by azhavoro** [comment]
> It looks like I can repeatedly reproduce this behavior when adding a large track (one shape per frame), containing over 70k+ frames, via the REST API.

Could you please share a code snippet to reproduce this issue?

**Comment by vinayshah01** [comment]
Attached is a JSON formatted message that was sent via the REST API (PUT
​/tasks​/{id}​/annotations) that recently caused this issue.  In this case, there were two tracks that were being added each with 48 shapes.  

The associated video file has 23635 frames and its dimensions are 1280 x 480. 

[json_annotation_request.txt](https://github.com/openvinotoolkit/cvat/files/5386219/json_annotation_request.txt)

**Comment by bsekachev** [comment]
Hi, @vinayshah01 

I do not see anything suspicious in the JSON you provided. I expected to see trying to save an object in ``put`` which has ``server_id`` property. It would explain the issue, but I do not see something like that. 

If this body causes the issue, I think it means that something wrong happens with server during saving.

**Comment by ErlingLie** [comment]
I also twice encountered this issue when uploading annotations through the CLI. The tasks I am working on are single job with 300 frames. I upload the annotations in CVAT XML-format with tracked shapes. I did however, write the code for converting my model-output to CVAT-XML myself, so there might be errors with the uploaded file. However, I have only encountered the error in 2 out of 18 videos so far so it is not necessarily reproduceable.

I am not doing the actual annotation work myself, could there be any sort of user-error that produces this issue?

Also, is the currently recommended workaround to set a frequent auto-save and just reload the page whenever the error occurs?

I upload the annotation file I used here in case there is any obvious error on that part
[annotations.txt](https://github.com/openvinotoolkit/cvat/files/5409194/annotations.txt)

**Comment by ilouzl** [comment]
We are also experiencing this problem when modifying a pre-loaded CVAT For Videos 1.1 xml annotation file.
Our solution in the meanwhile is to save more frequently. 

b.t.w, I noticed that the auto-save setting resets to 15 minutes every time the page refreshes. Is that in purpose?

**Comment by bsekachev** [comment]
@ilouzl 

> b.t.w, I noticed that the auto-save setting resets to 15 minutes every time the page refreshes. Is that in purpose?

Yes, settings are saved during client session only.

**Comment by joon612** [comment]
@bsekachev Hi, I met the same problem, I sometimes encounter code 400 when saving. CVAT version 1.0. From the error message, I searched for information and found that is it might be related to PostgreSQL?
![image](https://user-images.githubusercontent.com/34393671/102755243-18d3cd80-43a9-11eb-9dfb-bb452010d137.png)

**Comment by kondrusrividya** [comment]
I am getting the error 400 while trying save annotations or export as a dataset .

**Comment by azhavoro** [comment]
@kondrusrividya try to login CVAT in a new browser tab

**Comment by kondrusrividya** [comment]
I did open cvat in new tab by leaving current tab open but lot of work is not there in the new tab. Is there any way to save my work without loosing

**Comment by azhavoro** [comment]
> I did open cvat in new tab by leaving current tab open but lot of work is not there in the new tab. Is there any way to save my work without loosing

Just login in the new tab, switch to the old tab and try to save.

**Comment by kondrusrividya** [comment]
No use . Same error 401.

**Comment by joon612** [comment]
Are there any update for this issue?

**Comment by bsekachev** [comment]
> Are there any update for this issue?

We still cannot reproduce it on our side. Need detailed steps.

**Comment by vinayshah01** [comment]
I have not been able to resolve the issue.  It seems to occur less frequently if client (browser) /server are on the same machine, but this is just be based on anecdotal evidence.  

It is difficult to reproduce since the same steps which caused it to fail once may not cause it to fail when tried again.  It maybe due to some psuedo-random event (dropped packet?) which then corrupts the database.  It maybe possible to induce this state by repeatedly updating annotations via the REST API (see attached example request from Oct 15, 2020) until a failure occurs.  

My only means of mitigation is to remove the docker volumes (docker volume rm $(docker volume ls -q) and rebuild with docker-compose.

**Comment by leeyh20** [comment]
Hi everyone, this error happens to us frequently when we press undo then redo.

**Comment by bsekachev** [comment]
Hi @leeyh20 

I tried undo/redo several times, but it was not reprosed. Would be great if you can make a gif screencast with the issue, opening job after refreshing a page, doing something and reproducing the error

**Comment by TorstenSandell** [comment]
I can reproduce this error message consistently in browser by doing the following steps:
- Create a tracked object 
- Save and reload the page
- Remove the tracked object
- Undo the remove

Trying to save after following these steps produces the error message.

**Comment by bruno-amorim-bsb-ai** [comment]
> I can reproduce this error message consistently in browser by doing the following steps:
> 
> * Create a tracked object
> * Save and reload the page
> * Remove the tracked object
> * Undo the remove
> 
> Trying to save after following these steps produces the error message.

I was able to consistently reproduce this error by following these steps. I am running CVAT release 1.7.0 on macOS 13.3.1. I have also seen this error when running on desktop Ubuntu 21.10.

**Comment by leeyh20** [comment]
Same, I am able to reproduce the error when I press Undo after deleting a label

**Comment by AlexAseyev** [comment]
In my case, the issue was caused by a data migration where the primary key (`id`) values ​​in the `engine_trackedshape` table were out of sync with the current state of the sequence (`engine_trackedshape_id_seq`). This was causing conflicts when trying to insert new records into the table, as the sequence was generating duplicate `id` values ​​that already existed in the table.

---

#### **Solution Steps**

1. **Begin a Transaction**:
```sql
BEGIN;
```
- Begin a transaction to ensure that all changes are applied atomically (either fully committed or rolled back).

2. **Lock the Table**:
```sql
LOCK TABLE engine_trackedshape IN EXCLUSIVE MODE;
```
- Lock the table to prevent concurrent changes (such as inserts) while the operations are in progress.

3. **Check the current state of the sequence and data**:
```sql
SELECT last_value FROM engine_trackedshape_id_seq;

SELECT MAX(id) FROM engine_trackedshape;
```
- Check the current value of the sequence (`last_value`) and the maximum `id` in the table.
- This ensures that the sequence is indeed out of sync with the data.

4. **Synchronize the sequence**:
```sql
SELECT setval('engine_trackedshape_id_seq', (SELECT MAX(id) FROM engine_trackedshape));
```
- Update the sequence to match the maximum `id` in the table.
- After this, the next value generated by the sequence will be greater than any existing `id`.

5. **Check sync**:
```sql
SELECT last_value FROM engine_trackedshape_id_seq;

```
- Confirm that the sequence is now properly synced with the data.

6. **Identify potentially conflicting records**:
```sql
SELECT id FROM engine_trackedshape WHERE id <= (SELECT last_value FROM engine_trackedshape_id_seq);
```
- Identify all records whose `id` values ​​fall within a range that may conflict with the sequence.
- These records may cause future conflicts if not resolved.

7. **Update `id` for old records**:
```sql
UPDATE engine_trackedshape
SET id = id + 1000000
WHERE id <= (SELECT last_value FROM engine_trackedshape_id_seq);
```
- Increment the `id` values ​​of old records so they don't overlap with the sequence range.
- This ensures that new records only use unique values.

8. **Verify changes**:
```sql
SELECT id FROM engine_trackedshape WHERE id <= (SELECT last_value FROM engine_trackedshape_id_seq);
```
- Ensure that there are no conflicting `id` values ​​left in the table after the update.

9. **Commit the transaction**:
```sql
COMMIT;
```
- Commit all changes and release the table lock.
