### ISSUE TITLE
z-order: showing and sorting

### ISSUE THREAD

**Issue by yanmu2017** [opencv/cvat#2180]
Thanks for the nice labeling tool. I have two questions while using z-order. 
I use the default 'develop' branch downloaded on September 14, 2020.

(1) showing
I understand I can use '+' or '-' to increase or decrease the z-axis, respectively.
But after doing that, I cannot find any place in the CVAT interface showing the current z-axis of a polygon, except in the downloaded xml file. Maybe I am missing something?

(2) sorting
At the moment we can sort the labeled objects with ID and updated time. Can we also sort them with their z-axis numbers?

![Screenshot from 2020-09-15 10-42-59](https://user-images.githubusercontent.com/33514089/93187626-4a048800-f740-11ea-8a9e-7463c6bf7abd.png)

**Comment by bsekachev** [comment]
Hi, @yanmu2017 
Please, follow the issue template in the future. 
Speaking about your questions. There is slider to switch current layer in UI (look at the screenshot below)
![Screenshot from 2020-09-15 12-00-25](https://user-images.githubusercontent.com/40690378/93189794-40345200-f74b-11ea-9c07-648c04066a20.png)
On a layer X you see all objects with layer <= X.

Sorting by a z order in side panel might be a feature request, but what is use case where you need it?

**Comment by yanmu2017** [comment]
Thank you for the reply.

I look for a way to check if labelled objects have desired z order numbers.  This is needed as I label an image at many layers.
I cannot find an easy way to do it in the CVAT interface and now I first download segmentation masks for checking.

Sorting by a z order will do exactly what I want here.
If the z-order number of each object can be shown on the list of objects, that would be a plus for me.

**Comment by bsekachev** [comment]
> I look for a way to check if labelled objects have desired z order numbers.

I am not sure that sorting by z order in side panel is a convenient way. You always need to look first at sidebar, second at canvas for each object. Layer slider I suppose is more convenient way here.

**Comment by noamholz** [comment]
Hi, like @yanmu2017 I'd prefer being able to sort objects within the side panel. In my case I'd like to make sure that certain labels are always behind some otherwise labelled objects. In that case, at least, I wouldn't need to search each object also in the canvas as @bsekachev pointed out.
Other intuitive ways to allow the user understand the z-axis hierarchy:
A - Show the z-axis value within each object pop up. That would also help in my case, though less than sorting in the side-panel.
B - Enable defining labels z-axis hierarchy at the task window where the labels are defined. (ofcourse with the freedom to determine some partial hierarchies like "sky" < "buildings" or whatever.

**Comment by bsekachev** [comment]
>  I wouldn't need to search each object also in the canvas as @bsekachev pointed out.

You would need to search each object in side panel in this case (maybe it is convenient when there aren't too many objects and a couple of classes, but in typical segmentation datasets there can be tens and hundreds of objects per frame with tens classes). So, trying to sort out what objects behind or in front of another objects in common case is not trivial in such the case.

I understand you case, but at the same time we should find a solution that doesn't overcomplicates the UI (In my opinion sorting by z-order is a feature that doesn't bring any additional complex, but showing exact z order for each object does). Let's submit a feature request and find a solution. The feature is out of scope of our team, so I put it in backlog. Maybe someone from the community will work on it.

**Comment by yanmu2017** [comment]
`In my opinion sorting by z-order is a feature that doesn't bring any additional complex, but showing exact z order for each object does`

Maybe put showing exact z order optional? For example, we can add a box "Show z-order" here
![Screenshot from 2020-10-12 11-34-36](https://user-images.githubusercontent.com/33514089/95730815-12292b80-0c7f-11eb-8132-f60ff9e0ecab.png)

My project has about 5 objects for each image. By showing z-order in the side panel I can easily check them without moving the Layer slider, which will save me half the time while checking.
