### ISSUE TITLE
Reopen: Where does the shared server directory point at? 

### ISSUE THREAD

**Issue by yzchaogmail** [opencv/cvat#221]
To create huge tasks the documentation suggests choosing Share option in the dialog box.
While trying to select the files I see a modal popping up with the following path as title:
**$(cvat_root)/share**
<img width="375" alt="share-path-dialog" src="https://user-images.githubusercontent.com/33389121/49496752-af57f380-f8a1-11e8-80a7-7bcbda000424.png">

**However I can not navigate from there (nor I can find where this path is).**

My server dir looks like as follow:
1. $(cvat_root)  place at:  **/usr/local/cvat:**
<img width="425" alt="usr-local-cvat" src="https://user-images.githubusercontent.com/33389121/49496996-43c25600-f8a2-11e8-84a4-23a7c634411f.png">

2. $(cvat_root)/share looks like:
root@ecs-cn-south-ubuntu:/usr/local/cvat/share# ls
data1  data2

**So,where does the shared server directory point at?** 
Thanks.

**Comment by idrissbellil** [comment]
did you read [this part](https://github.com/opencv/cvat#share-path) of the documentation?

**Comment by yzchaogmail** [comment]
https://github.com/opencv/cvat has write "Share path" configuration.

version: "2.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /mnt/share host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/share
      o: bind


When i configured as it ,it works as follow:
![image](https://user-images.githubusercontent.com/33389121/49498494-34dda280-f8a6-11e8-97a4-b6e96f189108.png)



Thanks.
