### ISSUE TITLE
Ask for help: what wrong with my labels

### ISSUE THREAD

**Issue by yzchaogmail** [opencv/cvat#222]
**When i create annotation task use labels as follow:**
vehicle @select=type:__undefined__,car,truck,bus,train ~radio=quality:good,bad ~checkbox=parked:false circle radio=color:green,red,blue @number=radius:0,10,0.1

**Error as follow:**
 <h1>Not Found</h1><p>The requested URL /check/task/9 was not found on this server.</p>

![image](https://user-images.githubusercontent.com/33389121/49498888-80448080-f8a7-11e8-90dd-9e00b05a913d.png)

**Ask for help: what wrong with my labels ?**

PS:when i modify my labels as follow,task-create success.
vehicle @select=type:__undefined__,car,truck,bus,train

**Comment by nmanovic** [comment]
Hi @yzchaogmail ,

Which CVAT version do you use? Development version has the clear message: "Could not create the task. ValueError: labels string is not correct. `radius` attribute has incorrect type Number."

But we have a bug now. "0.1" isn't supported now. It will be fixed.

**Comment by yzchaogmail** [comment]
Your apply so fast,Amazing.
Thanks.
