### ISSUE TITLE
create task for 40000 images

### ISSUE THREAD

**Issue by elyas20** [opencv/cvat#223]
I want to do annotation on a  folder containing  big amount of images, I have change max files allowed to upload on base.py to 100000. but still when I want to submit after choosing the folder, the button submit does not respond.

**Comment by elyas20** [comment]
Yes I did, however, when I use the share feature, the folder keep loading infinitely.

**Comment by bsekachev** [comment]
@elyas20 
Please try put all your images into any dir and don't open this dir in a browser. Just select it for an uploading.

**Comment by nmanovic** [comment]
@elyas20 ,

Another way to avoid "loading infinitely" to archive all your images. In this case it is possible to have "non-flat" layout of your images. Also such archive will be copied faster from a NFS share (if your mounted share is NFS). But in general you need to know that internally we "optimize" size of jpg and it will take time.

**Comment by elyas20** [comment]
Thanks @bsekachev and @nmanovic, problem solved,

However, Originally I have videos in mkv format, I have tried loading the video directly, but ffmpeg crashes. I have changed the ffmpeg options on task.py to just "ffmpeg -i video.mkv -vf fps=5 frame%04d.jpg". It did not crashed, no job url was generated, any ideas about that ?

**Comment by nmanovic** [comment]
@elyas20 ,

To be honest it is a bad idea to change ffmpeg options. Be sure that such command can extract any frames from the video. Also be sure that you don't ignore "output directory":

```
self.output = tempfile.mkdtemp(prefix='cvat-', suffix='.data')
        target_path = os.path.join(self.output, '%d.jpg')
        output_opts = '-start_number 0 -b:v 10000k -vsync 0 -an -y -q:v ' + str(translated_quality)
        if flip_flag:
            output_opts += ' -vf "transpose=2,transpose=2"'
        ff = FFmpeg(
            inputs  = {source_path: None},
            outputs = {target_path: output_opts})
        ff.run()
```

**Comment by elyas20** [comment]
Yes, I have only changed  **output_opts**. Any ideas about loading with success but job not available ?

**Comment by nmanovic** [comment]
@elyas20 , without logs we will not be able to investigate the issue and help. Please convert your video to another format to avoid ffmpeg crash. Don't hesitate to reopen the issue if you can share with us how to reproduce the issue and attach logs.
