### ISSUE TITLE
Ask for help: how to automatic annotation using TensorFlow OD API? 

### ISSUE THREAD

**Issue by yzchaogmail** [opencv/cvat#225]
https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#User's guide:

**_CVAT has many powerful features:  ...'automatic annotation using TensorFlow OD API,'._**

Is there any documents to describe how to do it?
Thanks.

**Comment by nmanovic** [comment]
Hi @yzchaogmail ,

You need to build a container with TF OD API support: https://github.com/opencv/cvat/blob/develop/components/tf_annotation/README.md

To run it efficiently you need OpenVINO (https://github.com/opencv/cvat/blob/develop/components/openvino/README.md) or CUDA (https://github.com/opencv/cvat/tree/develop/components/cuda).

If you install it correctly you should be a button for each task in dashboard "Run TF annotation"

**Comment by nmanovic** [comment]
@yzchaogmail ,

Inference without OpenVINO or CUDA can be extremely slow. How much frames the task has?

Could you please just do a simple experiment? Create a task with one image and "Run TF Annotation". Does it work?

**Comment by yzchaogmail** [comment]
Create a task with one image and "Run TF Annotation",it works!

In my computer ,the speed with OpenVINO is about 1 frame/second.

root@ecs-cn-south-ubuntu:/var/lib# uname -a
Linux ecs-cn-south-ubuntu 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@ecs-cn-south-ubuntu:/var/lib# cat /etc/issue
Ubuntu 16.04.5 LTS \n \l

root@ecs-cn-south-ubuntu:/var/lib# cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
      4  Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
root@ecs-cn-south-ubuntu:/var/lib# cat /proc/cpuinfo | grep physical | uniq -c
      1 physical id     : 0
      1 address sizes   : 42 bits physical, 48 bits virtual
      1 physical id     : 1
      1 address sizes   : 42 bits physical, 48 bits virtual
      1 physical id     : 2
      1 address sizes   : 42 bits physical, 48 bits virtual
      1 physical id     : 3
      1 address sizes   : 42 bits physical, 48 bits virtual

Thank you very much. 

![Uploading image.png…]()
