### ISSUE TITLE
Include information about job/task status in Kibana

### ISSUE THREAD

**Issue by Loc-Vo** [opencv/cvat#2253]
Hi,

My idea is to have job/task status appended into Kibana so that we can track the overall task/job status from Kibana dashboard 

Related ticket: #943 

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

Able to get job/task status from Kibana and display on the dashboard for status tracking
### Current Behaviour

not able to get job/task status from Kibana

### Your Environment

- Git hash commit (`git log -1`): **4841f83876d7ad44e1beac6a0a10f383c636bb5e**
- Docker version `docker version` (e.g. Docker 17.0.05): **19.03.12**
- Are you using Docker Swarm or Kubernetes? **No**
- Operating System and version (e.g. Linux, Windows, MacOS): **Windows 10**
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@s3298230 , Could you please attach a mock as you like to view the information in Kibana?

**Comment by s3298230** [comment]
We tend to have the following formats in the dashboard for tracking team's progress:

1/ Template
Task# | Job# | Status | User | shapes count | start/end time | Duration (actual annotation time)

2/ Example
Task 1 | Job 1 | Annotate | User 1 | [# of shape(s)] | 15:30 | 30(mins)

Task 1 | Job 1 | Validation | User 2 | [# of shape(s)] | 16:30 | 15(mins) 

Generally,we would like to measure the productivity o the team as well as finding away to track the working progress for future references (audit trail) to improve the annotation quality.

**Comment by s3298230** [comment]
Our team just came up with an extra value needed for Kibana which is the *Empty Frame* (remaining frames that are not annotated). I can see that we can extract these values using datumaro but it would be even better if we can have it along with the Kibana dashboard for task tracking.

**Comment by MarioProjects** [comment]
Hi, how you could see the number of shapes and duration and so on with Kibana. I am not able to do so.

**Comment by duongduc2908** [comment]
> We tend to have the following formats in the dashboard for tracking team's progress:
> 
> 1/ Template
> 
> ```
> Task# | Job# | Status | User | shapes count | start/end time | Duration (actual annotation time)
> ```
> 
> 2/ Example:
> 
> ```
> Task 1 | Job 1 | Annotate | User 1 | [# of shape(s)] | 15:30 | 30(mins)
> 
> Task 1 | Job 1 | Validation | User 2 | [# of shape(s)] | 16:30 | 15(mins) 
> ```
> 
> Generally,we would like to measure the productivity o the team as well as finding away to track the working progress for future references (audit trail) to improve the annotation quality.
> 
> PS: I can see we have 2 terms _working time_ and _duration_ and I believe _duration_ should match our case since it only captures the annotation tasks (draw, resize etc...) while _working time_ captures user activity in general including idle time. Please let me know if I understand it correctly.

Are there any specific instructions for this? pls
