### ISSUE TITLE
Wrong annotation in the dumped file

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#2254]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Annotation is dumped correctly

### Current Behaviour
For a reason the dumped annotation for multi-job tasks may contain some extra shapes which don't exist in the database for this job. UI representation is correct:
For example frame 86496 of 34372 job:
```xml
<image id="86496" name="336728.png" width="288" height="144">
    <box label="bad_quality" occluded="0" source="manual" xtl="0.00" ytl="0.00" xbr="288.00" ybr="144.00">
    </box>
    <box label="wrong_subject" occluded="0" source="manual" xtl="0.00" ytl="0.00" xbr="288.00" ybr="144.00">
    </box>
  </image>
```
```python
>>> db_job = Job.objects.filter(id=34372)[0]
>>> db_shapes = db_job.labeledshape_set.filter(frame=86496)
>>> db_shapes.count()
1
```

Update:
For some reason, other jobs contain annotations for this frame and this is causing the wrong shapes to appear in the dump file
```python
>>> db_job = Job.objects.filter(id=34371)[0]
>>> db_shapes = db_job.labeledshape_set.filter(frame=86496)
>>> db_shapes.count()
1
```

### Steps to Reproduce (for bugs)
N/A

### Your Environment

- Git hash commit (`git log -1`): a222741f6b3c9fea4f363f475ef9fcd4a85c6a7d
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.6
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by yasakova-anastasia** [comment]
I haven't been able to reproduce this issue. I will close this issue. Reopen it if you have this problem please.
