### ISSUE TITLE
Wrong link in annotation dump in CVAT format

### ISSUE THREAD

**Issue by ActiveChooN** [opencv/cvat#2260]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

`url` tag in annotation should follow to the correct page

### Current Behaviour

If you dump annotation in `CVAT for video 1.1` for example and then open it and follow segments section you can notice that `url` tag with link follows to the old UI with a job and don't work for the new one.

```XML
<segments>
        <segment>
          <id>5</id>
          <start>0</start>
          <stop>99</stop>
          <url>http://localhost:7000/?id=5</url>
        </segment>
</segments>
```

### Possible Solution

Fix link for the new UI

### Steps to Reproduce (for bugs)

1. Dump any task in CVAT format

### Your Environment

- Git hash commit (`git log -1`): a222741f6b3c9fea4f363f475ef9fcd4a85c6a7d
- Docker version `docker version` (e.g. Docker 17.0.05): No docker
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
I can reproduce the issue. On CVAT.org I have http://cvat.org/?id=128993 link and it doesn't work.

**Comment by yasakova-anastasia** [comment]
It's been fixed.
