### ISSUE TITLE
CopyRight Error faced while trying to create New Task

### ISSUE THREAD

**Issue by PavanVenky** [opencv/cvat#227]
Hello All,

I installed CVAT successfully in VMware hosted on Windows 7 machine.

While creating new task, I found a copyright issue as shown in screenshot below.
![screenshot from 2018-12-06 04-15-39](https://user-images.githubusercontent.com/15624252/49584030-003e1980-f980-11e8-89c8-6422bfe1d0c5.png)

Please let me know the fix to this issue.

Thanks.

**Comment by pvenuprasad** [comment]
Hello,
How did you manage to fix this issue? I have the same error when uploading video files

**Comment by PavanVenky** [comment]
Hello,

We have to create the super user before creating the task.

Please go through the next command in CVAT Github, to create superuser.

Then login with superuser credentials. You will not face this copyright
issue then.

Thank You,
Pavan.
