### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by honeytidy** [opencv/cvat#23]
I run containers without tf_annotation app:
`docker-compose up`
and visit with ip like this:
http://10.239.38.156:8080
got this error:
Bad Request (400)

Is there something wrong?

**Comment by nmanovic** [comment]
Hi @honeytidy ,

Thanks for your report. Let's investigate the problem together. Could you please attach output from `docker logs cvat` command?

**Comment by honeytidy** [comment]
I found the web can access by visit `localhost:8080`, but can not with `<ip address>:8080`
this is the log file:
[log.txt](https://github.com/opencv/cvat/files/2269330/log.txt)

**Comment by nmanovic** [comment]
Please use ALLOWED_HOSTS variable to solve the problem: https://github.com/opencv/cvat#advanced-settings.

Let me close the issue. Don't hesitate to reopen it if it doesn't answer your question.

**Comment by aurotripathy** [comment]
Kindly provide an example of docker-compose.override.yml  for a LAN situation where one connects from another computer. I've reported the same issue in #102
