### ISSUE TITLE
provide built CVAT AMI for AWS

### ISSUE THREAD

**Issue by graingert** [opencv/cvat#2327]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

this was originally brought up on https://github.com/openvinotoolkit/cvat/issues/35

> if anyone can build CVAT AMI at AWS would be great. 

The existing AWS docs are helpful but an AMI would be even easier

**Comment by nmanovic** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html
