### ISSUE TITLE
Timeout: Incomplete Dataset Export Download

### ISSUE THREAD

**Issue by cyrilzakka** [opencv/cvat#2330]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

So I've been trying to export one of my datasets for the past several days but in vain. Dumping annotations seems to be working fine, but exporting the dataset always results in a timeout halfway through the download. I've attempted this on two different networks and browsers with no success.

### Expected Behaviour
Trying to export a dataset (4.1 GB) should download successfully, without any timeouts or errors. 

### Current Behaviour
Download timeouts after 2GB have downloaded and the resulting file is unusable.

### Possible Solution
I've tried circumventing the timeout in multiple ways, which have all resulted in failure.
1 - I tried using `wget` in Colab to get around what I thought was slow internet, but the downloaded file is empty and of `Length = 0 `. 
```
!wget --no-check-certificate  --load-cookies cookies.txt \
'https://cvat.org/api/v1/tasks/###/dataset?format=TFRecord%201.0&action=download'
```
2- **Update:** This only worked once and now times out at 2GB as well.

I tried using Selenium on Colab and it was successful: 
```
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

options.add_experimental_option("prefs", {
  "download.default_directory": r"/content/",
  "download.prompt_for_download": False,
  "download.directory_upgrade": True,
  "safebrowsing.enabled": True
})

wd = webdriver.Chrome('chromedriver',options=options)
wd.get("https://cvat.org/auth/login")

username = wd.find_element_by_id("username")
password = wd.find_element_by_id("password")

username.send_keys("username")
password.send_keys("password")
element = wd.find_element_by_css_selector('.login-form-button')
wd.execute_script("arguments[0].click();", element)

from selenium.webdriver import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

wait = WebDriverWait(wd, 10)
actions = ActionChains(wd)

open = wd.find_element_by_css_selector("#root > section > main > div > div:nth-child(3) > div > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > div > a")
wd.execute_script("arguments[0].click();", open)

action_button = wd.find_element_by_css_selector("#root > section > main > div > div > div.ant-row-flex.ant-row-flex-space-between.ant-row-flex-middle.cvat-task-top-bar > div:nth-child(2) > button")
actions.move_to_element(action_button).perform()

export_data = wd.find_element_by_css_selector("body > div:nth-child(9) > div > div > ul > li:nth-child(3) > div")
actions.move_to_element(export_data).perform()

data = wd.find_element_by_xpath("//*[@id='export_task_dataset$Menu']/li[1]")
wd.execute_script("arguments[0].click();", data)
```

### Steps to Reproduce (for bugs)

1. Create Task
2. Annotate a few things
3. Export dataset
4. Download timeouts before successful download.

### Context
I can't export my data for use in research.

### Your Environment
CVAT.org

**Comment by azhavoro** [comment]
Hi, can you download the dataset with web UI manually?
Also please specify the task id.

**Comment by cyrilzakka** [comment]
I can't download with the web UI manually which is why I resorted to my workarounds. The manual download results in truncation after 2GB have been downloaded and results in a file named 'dataset' that's empty. The task ID is 17431

**Comment by azhavoro** [comment]
Thanks for the report!

**Comment by kevincolyar** [comment]
> I can't download with the web UI manually which is why I resorted to my workarounds. The manual download results in truncation after 2GB have been downloaded and results in a file named 'dataset' that's empty. The task ID is 17431

I have the same issue when trying to export a dataset.  Reports downloading a 4GB file via Chrome, but the resulting 'dataset' file is empty.

**Comment by rilut** [comment]
@kevincolyar yes I still have the same problem in 2021. did you manage to find the solutoin?

**Comment by rilut** [comment]
@azhavoro is there any temporary workaround to download dataset?

**Comment by nullket** [comment]
I have the exact same issue, but with 1 GB. It downloads until 1 GB and then fails leaving a incomplete 1 GB file. I thought this might be related to https://github.com/openvinotoolkit/cvat/issues/956 but I could not find any info in the logs. 

Temporary workaround could be to mount the docker volume and copy created zip by hand (before cache cleaner deletes it again). Going to try this now.

**Comment by cyrilzakka** [comment]
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 39 4200M   39 1667M    0     0  20.0M      0  0:03:29  0:01:23  0:02:06 20.5M
curl: (18) transfer closed with 2655909917 bytes remaining to read
```

Bug is still there. Even with blazing internet speed I'm only able to download 39%

**Comment by JobCollins** [comment]
I have also experienced this issue. I'm trying to export a 5.6GB zipped dataset and the download timeout is at 1GB always. Is there a workaround for this?

**Comment by azhavoro** [comment]
@JobCollins Hi, try to adjust `--limit-request-body` value https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L65. In the near future we plan to remove any data size limitations by default.

**Comment by JobCollins** [comment]
@azhavoro thanks for this but my annotation job was done online (cvat.org). I resolved to use online after the local installation kept failing. Or could I sign in to my online profile via local? That would be great.

**Comment by JobCollins** [comment]
Thanks a lot, @azhavoro . Using your advice, 

1.I downloaded the annotations online (which has no issues downloading) then 
2.uploaded the annotations to the offline installation and job
3.changed the local supervisord.conf code line 65

And I got my full dataset exported. Quite a workaround! 😁😅

**Comment by cyrilzakka** [comment]
Any updates on this? I have 6 datasets to export and they all expire...

**Comment by azhavoro** [comment]
@cyrilzakka Have you tried set `--limit-request-body` to `0` https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L65 here as a workaround?

**Comment by cyrilzakka** [comment]
@azhavoro I'm using CVAT online so I don't think that's an option for me. And I don't have access to the dataset in order to do what @JobCollins proposed in the offline installation... so I'm basically stuck.

**Comment by cyrilzakka** [comment]
Is there a way of downloading an uploaded video from CVAT? In other words, when first creating the dataset, I uploaded an MP4 file. Since I can't export any of my data with more than 7K annotated frames, is it possible to download the original MP4?

**Comment by lgg** [comment]
> @azhavoro I'm using CVAT online so I don't think that's an option for me. And I don't have access to the dataset in order to do what @JobCollins proposed in the offline installation... so I'm basically stuck. Any help would be greatly appreciated.

What do you mean "I'm using CVAT online"?
Do you have access to server where your CVAT instance is running?

**Comment by cyrilzakka** [comment]
> > @azhavoro I'm using CVAT online so I don't think that's an option for me. And I don't have access to the dataset in order to do what @JobCollins proposed in the offline installation... so I'm basically stuck. Any help would be greatly appreciated.
> 
> What do you mean "I'm using CVAT online"?
> Do you have access to server where your CVAT instance is running?

I used https://cvat.org/ - so I don't have access to the server to be able to set `--limit-request-body to 0`

**Comment by lgg** [comment]
> > > @azhavoro I'm using CVAT online so I don't think that's an option for me. And I don't have access to the dataset in order to do what @JobCollins proposed in the offline installation... so I'm basically stuck. Any help would be greatly appreciated.
> > 
> > 
> > What do you mean "I'm using CVAT online"?
> > Do you have access to server where your CVAT instance is running?
> 
> I used https://cvat.org/ - so I don't have access to the server to be able to set `--limit-request-body to 0`

I feel for you. Guess the only way is to try to contact owners of cvat.org and ask them for help. If i understand correctly - developers of CVAT (github issues here) are not the same persons as the owners of the website. Wish you good luck with your issue.

**Comment by azhavoro** [comment]
@lgg, we discussed internally and I'm going to disable this limit for cvat.org today

**Comment by cyrilzakka** [comment]
Great, thank you so much and I do apologize for all the trouble! Will you let me know when you disable the limit so I can download my datasets asap?

**Comment by JobCollins** [comment]
@azhavoro that would be great! Thanks @cyrilzakka for pushing this!

**Comment by aafaqin** [comment]
How to solve this problem in a running Docker hosted on a server. I have the access to the hosted server and i could end up loosing a lot of labelled images

**Comment by cyrilzakka** [comment]
Sorry to bring this up again, but has this issue been fixed? As of today, I'm still  receiving this error. Always around 46-48% of this dataset:
<img width="482" alt="Screen Shot 2021-06-17 at 8 53 35 AM" src="https://user-images.githubusercontent.com/1841186/122339309-938d3800-cf49-11eb-9f4d-6187ac63d4ed.png">

**Comment by ConstantSun** [comment]
@cyrilzakka Yea, me too. Even when I set:  --limit-request-body 0 as suggested in [(https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L65)]  
My downloading annotation file is stopped when it reaches about 1GB.

**Comment by cyrilzakka** [comment]
Even tried `-C` option on curl but still can't get my data. At this point I've exhausted all of my options :(

**Comment by memirerdol** [comment]
Is there a real solution for this issue? I cannot download my dataset which is above 1GB.

**Comment by cyrilzakka** [comment]
@memirerdol I've been waiting for a solution for 10 months now while my data is being held hostage and my research paper is on hold because of it. I would've understood had they mentioned data above a certain size couldn't be downloaded but they failed to mention it anywhere... It's super frustrating but there's nothing to be done

**Comment by cyrilzakka** [comment]
@memirerdol @ConstantSun For some odd reason, `curl` worked for me today - I was able to download 64 GB worth of my annotated data. Regular downloads using the GUI still times out after 1GB

**Comment by jaharkes** [comment]
Was having the same issue on my local setup using the default docker-compose setup and I discovered that the problem seems to be with the cvat_proxy container which is running an nginx http proxy.

proxy_buffering is enabled in which case it will (try to) cache large reponses to a temporary local file in the cvat_proxy container, and the [default setting for the maximum buffered file size](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size) is 1GB. I wasn't sure if I should completely disable buffering to a file because I didn't want to stall any worker threads in the backend, so I just bumped the setting to 10GB.

```patch
Index: cvat/cvat_proxy/nginx.conf
===================================================================
--- cvat.orig/cvat_proxy/nginx.conf
+++ cvat/cvat_proxy/nginx.conf
@@ -15,4 +15,5 @@ http {
 
     include /etc/nginx/conf.d/*.conf;
     client_max_body_size 0;
+    proxy_max_temp_file_size 10240m;
 }
```

**Comment by ryanalexmartin** [comment]
Until this issue is resolved, you can use this cURL command to download datasets from projects (as COCO):

```
curl 'https://cvat.cargocult.tech/api/projects/<project_id>/dataset/?action=download&filename=export&format=COCO%201.0&location=local&use_default_location=true' \
  -H 'accept: application/vnd.cvat+json' \
  -H 'Authorization: Basic cnlhbjpOaWhvbkcwIQ==' -u <user:password> -o out.zip
  ```

**Comment by emmeduz** [comment]
Hi all,
a possible workaround to this problem would be to download only the annotations and then extract the corresponding frames from the mp4 files outside CVAT when needed. This is possible if we know how the frames are extracted by cvat to create the tasks. 

Can someone link the exact command used to extract the frames?
