### ISSUE TITLE
Can cvat be used to annotate ocr task?

### ISSUE THREAD

**Issue by northeastsquare** [opencv/cvat#248]
Hello, can cvat be used to annotate image with box and line words for OCR tasks?

**Comment by nmanovic** [comment]
Hi @northeastsquare ,

It is definitely possible. Internally we don't have such tasks. I would annotate "line words" using 4 points polygon or 2 points polyline (underline the text). For such geometric primitives you have attach "text" attribute (label specification: `line @text=text:""`). Annotate all "lines" first and after that go to "attribute annotation mode" and annotate text itself.

Let us know if it works for you. Also if you have ideas how to improve UI/UX for the particular tasks don't hesitate to share these ideas with us or just send us a PR!

**Comment by nmanovic** [comment]
Hi @northeastsquare ,

I will close the issue. If you have other questions please use https://gitter.im/opencv-cvat channel. Don't hesitate to reopen the issue if it is necessary from your point of view.

**Comment by vinit13792** [comment]
> Hi @northeastsquare ,
> 
> It is definitely possible. Internally we don't have such tasks. I would annotate "line words" using 4 points polygon or 2 points polyline (underline the text). For such geometric primitives you have attach "text" attribute (label specification: `line @text=text:""`). Annotate all "lines" first and after that go to "attribute annotation mode" and annotate text itself.
> 
> Let us know if it works for you. Also if you have ideas how to improve UI/UX for the particular tasks don't hesitate to share these ideas with us or just send us a PR!

Dear Mr. Manovich,

I tried to follow your method, although after annotating a word in a line with the help of polygon, I couldn't find the 'text' attribute which you mentioned. Could you point out where I can find this option?

**Comment by nmanovic** [comment]
@vinit13792 , please read the guide: https://openvinotoolkit.github.io/cvat/docs/manual/basics/creating_an_annotation_task/

**Comment by vinit13792** [comment]
> @vinit13792 , please read the guide: https://openvinotoolkit.github.io/cvat/docs/manual/basics/creating_an_annotation_task/

Thank you Mr. Manovic! 

I would also like to know if CVAT has any text detection models which can be used to add texts to this annotation attribute automatically?
