### ISSUE TITLE
Arrows up and down in AAM

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#2540]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The buttons "arrow up" and "arrow down" should highlight corresponding attributes
### Current Behaviour

When we press "arrow up" in AAM we move to a lower attribute and vice versa pressing "arrow down" we move to an upper attribute.

**Comment by bsekachev** [comment]
Maybe it was fixed sometime, but current version CVAT has **expected** behaviour. I will close the issue.
