### ISSUE TITLE
CVAT format- Source only accepts manual/auto 

### ISSUE THREAD

**Issue by jahaniam** [opencv/cvat#2612]
Hi guys,
Thank you for developing this great tool. 

I am importing my annotation to cvat using the cvat 1.1 image format. I noticed field `source` could only be either `auto` or  `manual`.

I was wondering why that would be the design decision and why not just accept any text? Ideally, as automatic annotation tools are being added more and more, we would like to keep track and know which bounding box/polygon was done by which annotation.
Is this possible?
An ideal source would be `anytext`. I think that is one of the main advantages of the cvat format.
```
  <image id="0" name="1605889889184602585.png" width="640" height="480">
    <polygon label="ground" occluded="0" source="anytext"  points= "25.54,92.44;25.54,619.87;461.00,619.87;461.00,92.44" z_order="0">
    </polygon>
  </image>
```

Thanks,
Ali
PS. exporting as Pascal VOC gives unknown result in the XML annotation.

```
<annotation>
  <folder></folder>
  <filename>1607544631785479567.png</filename>
  <source>
    <database>Unknown</database>
    <annotation>Unknown</annotation>
    <image>Unknown</image>
  </source>
  <size>
    <width>480</width>
    <height>640</height>
    <depth></depth>
  </size>
  <segmented>0</segmented>
</annotation>
```

**Comment by zhiltsov-max** [comment]
Hi, it is an interesting idea.

Regarding Pascal VOC, `source` is an image source.

**Comment by jahaniam** [comment]
@zhiltsov-max Thanks for your reply.  Pascal VOC doesn't work at all. There is a bug there. Everything is Unknown when we export the task to this format.

**Comment by zhiltsov-max** [comment]
@jahaniam, the following fields are marked `Unknown`, because their values are unknown. `Source` section in PASCAL has no relation to the way of obtaining annotations in CVAT.

```
  <source>
    <database>Unknown</database>
    <annotation>Unknown</annotation>
    <image>Unknown</image>
  </source>
```

**Comment by jahaniam** [comment]
@zhiltsov-max so basically everything will be unknown in PASCAL format?!
I was expecting the annotation points to be exported at least!

**Comment by zhiltsov-max** [comment]
Pascal VOC has an official specification for their format, it is not supposed to be used with `Point` annotations. We could implement some kind of extension, but it will be incompatible with any other tool.

You can use other formats to export point annotations, which are `CVAT`, `COCO` ([instruction](https://github.com/openvinotoolkit/datumaro/issues/52#issuecomment-726077582)), `Datumaro`. The only format, which supports annotation source is `CVAT`. Any imported annotations are considered `manual`.
