### ISSUE TITLE
Explain "Select Files" in user_guide.md

### ISSUE THREAD

**Issue by enricorotundo** [opencv/cvat#264]
[user_guide.md](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#creating-an-annotation-task) could better explain the behaviour of the "Select Files" button, for instance by mentining "these are the files you want to annotate"

**Comment by nmanovic** [comment]
Hi @enricorotundo ,

Thanks for the feedback. Could you please help us improve the tool and prepare a PR with the fix? It should not take too much time but will help us a lot.
