### ISSUE TITLE
In k8s (AKS) uses NodePort instead of Service to connect to function

### ISSUE THREAD

**Issue by turowicz** [opencv/cvat#2643]
### My actions before raising this issue
- [* ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [* ] Searched [past issues](/issues)

The problem occurs while running CVAT and Nuclio in Kubernetes. By default, CVAT function invocation doesn't append the `x-nuclio-via` header, which makes `nuclio-dashboard` unable to find the desired function service.

### Expected Behaviour
There should be a possibility to tell CVAT to always include the following header for function invocations:
```
'x-nuclio-invoke-via': 'domain-name'
```

### Current Behaviour
The header is not added and Kubernetes routes via Node IP, which is an incorrect address for the function pod.

### Possible Solution
Environment setting, hardcode or docker build arg.

### Steps to Reproduce (for bugs)
1. Deploy to AKS, EKS or GKE.
2. Try running an automated task.

### Context
I'm setting up full CVAT with models in the AKS.

### Your Environment
- Git hash commit (`git log -1`): 266e7ca9b4ceb76077e8e2b54df6a3a208f3e17b
- Docker version `docker version` (e.g. Docker 17.0.05): N/A on AKS, GKE etc.
- Are you using Docker Swarm or Kubernetes? Kubernetes
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem: https://github.com/nuclio/nuclio/issues/2031
- Other diagnostic information / logs: https://github.com/Surveily/cvat/commit/9898357d878eae72a4d7b6aac69bf2649dc16274

**Comment by turowicz** [comment]
cc @bsekachev

**Comment by turowicz** [comment]
cc @jahaniam

**Comment by bsekachev** [comment]
@azhavoro Could you please take a look into the issue? I suppose adding HTTP header is quite easy to fix.

**Comment by nmanovic** [comment]
@turowicz , how can we reproduce the issue on our end? Could you please contribute the code? Thus we will be able to support it and test in the future.

**Comment by turowicz** [comment]
@nmanovic The way to reproduce is with a Kubernetes cluster where all services are running as ClusterIPs, not NodePorts. That way it will require you to use cluster internal DNS (service names) and you will see the problem. Please see my fix in the commit mentioned in the original description.

**Comment by azhavoro** [comment]
Fixed in https://github.com/opencv/cvat/commit/5e2eda76014c325c69dc297749d1d123ed315626
