### ISSUE TITLE
 ImportError: Bad git executable.

### ISSUE THREAD

**Issue by Jianfenl** [opencv/cvat#265]
Hi，

After I successfully build the image ，i tried to start the container by docker-compose up and got the following error. Could anyone help solve it. thanks

cvat          | 2019-01-09 01:34:38,415 DEBG 'git_status_updater' stderr output:
cvat          | Traceback (most recent call last):
cvat          |   File "/home/django/manage.py", line 21, in <module>
cvat          |     execute_from_command_line(sys.argv)
cvat          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
cvat          |     utility.execute()
cvat          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
cvat          |     self.fetch_command(subcommand).run_from_argv(self.argv)
cvat          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 224, in fetch_command
cvat          |     klass = load_command_class(app_name, subcommand)
cvat          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 36, in load_command_class
cvat          |     module = import_module('%s.management.commands.%s' % (app_name, name))
cvat          |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
cvat          |     return _bootstrap._gcd_import(name[level:], package, level)
cvat          |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
cvat          |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
cvat          |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
cvat          |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
cvat          |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
cvat          |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
cvat          |   File "/home/django/cvat/apps/git/management/commands/update_git_states.py", line 6, in <module>
cvat          |     from cvat.apps.git.git import update_states
cvat          |   File "/home/django/cvat/apps/git/git.py", line 22, in <module>
cvat          |     import git
cvat          |   File "/usr/local/lib/python3.5/dist-packages/git/__init__.py", line 82, in <module>
cvat          |     refresh()
cvat          |   File "/usr/local/lib/python3.5/dist-packages/git/__init__.py", line 73, in refresh
cvat          |     if not Git.refresh(path=path):
cvat          |   File "/usr/local/lib/python3.5/dist-packages/git/cmd.py", line 290, in refresh
cvat          |     raise ImportError(err)
cvat          | ImportError: Bad git executable.
cvat          | The git executable must be specified in one of the following ways:
cvat          |     - be included in your $PATH
cvat          |     - be set via $GIT_PYTHON_GIT_EXECUTABLE
cvat          |     - explicitly set via git.refresh()
cvat          |
cvat          | All git commands will error until this is rectified.

**Comment by nmanovic** [comment]
@bsekachev , could you please look at the issue ASAP?

**Comment by bsekachev** [comment]
@Jianfenl 
I don't have same issue in my case.
Please could you provide some more information? For example about you platform, build and up commands etc.

**Comment by Jianfenl** [comment]
> @Jianfenl
> I don't have same issue in my case.
> Please could you provide some more information? For example about your platform, build and up commands, build log etc.

Hi @bsekachev , I removed the image and  rebuild it ，this time it works fine. I don't know why. 
thanks anyway.

**Comment by nmanovic** [comment]
@Jianfenl ,

In any case thanks for the report. I will close the issue.
