### ISSUE TITLE
Support of webhooks

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#2657]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Just an idea. CVAT could support user's webhooks. They are some HTTP requests, may be with data which are triggered automatically on different events: create, save, delete, change something.
There could be two types of hooks: admin-owned which are global and user-owned when only the user actions trigger them.
I believe it would be useful when integration with other platforms. 
Hope somebody from the community will find the idea useful

**Comment by rsnk96** [comment]
Agreed, this would help a lot! :+1:

**Comment by addisonklinke** [comment]
I would specifically find it helpful to have webhooks for the following events
* Annotation created
* Annotation deleted
* Annotation updated

**Comment by christian-steinmeyer** [comment]
For our use case, it would be nice to somehow trigger a webhook when the status of a task changes (e.g. created, validation, completed)

**Comment by bsekachev** [comment]
@kirill-sizov 

Could you please to sum up what has been done in this PR #4863 ?

**Comment by kirill-sizov** [comment]
Hi, @christian-steinmeyer, we have merged first implementation of webhooks in our develop branch, now you can configure webhooks

for project: Project -> Actinons -> Setup Webhook
or
for organization: Organization -> Settings -> Actions -> Setup Webooks

On the webhook creation page, you will see a list of available events that trigger the webhook.

Additional information will be available in our documentation within one week.

**Comment by kirill-sizov** [comment]
Webhooks implemented in CVAT,  look at our documentation for more info: https://opencv.github.io/cvat/docs/administration/advanced/webhooks/
