### ISSUE TITLE
Instructions for each labeling task / project

### ISSUE THREAD

**Issue by kbegiedza** [opencv/cvat#2664]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Currently we have to prepare and distribute documentation for each project and task outside CVAT which is slow and error prone process.
In AWS's Sage Maker we can give instructions per labeling task for annotators.

I believe this feature will improve productivity of annotation team and decrease error rate.

### Possible Solution
Side panel with instructions for created task (text + images).

**Comment by bsekachev** [comment]
Hi, @Ursanon 

You can use field "Issue tracker" to left a link with specification (to any 3rdparty server) when create a task or a project.
Your request to support it directly in CVAT is a part of #351, but it is out of priority of the core team.

**Comment by bsekachev** [comment]
Implemented in https://github.com/opencv/cvat/pull/6191
