### ISSUE TITLE
Reimplement UI using React, Ant Design

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#271]
At the moment GUI isn't very module and attractive. Also most of UI elements are handmade. It is much better to use special frameworks to solve these to problems: nodejs + babel + webpack + React + Ant Design. The UI part will use REST API to create/delete annotation tasks, etc...

**Comment by nmanovic** [comment]
Also it is necessary to create client side JS library to communicate with the server and manipulate annotation objects. The library should not provide UI capabilities. UI component should use the library to implement all functions.

**Comment by nmanovic** [comment]
Thanks @rushtehrani! We will review these ideas carefully and provide a feedback.

**Comment by nmanovic** [comment]
Hi @rushtehrani ,

Thanks one more time for the awesome work!
We discussed the new design internally. I commented many screenshots in projects.invisionapp.com. 
A couple of general questions:
- Can we have at least two styles: day and night?
- How is it not possible to estimate the UI in "dynamic". When the user works with an object it can be highlighted, show some text near the object, show context menus.

Also from our side we will try to prepare a document which describe all UI/UX features to be sure that the new UI will cover the same scope.

**Comment by rushtehrani** [comment]
@nmanovic the document will be very helpful, if possible, try to include planned features as well.  Will review your comments and get back to you.  

I am not clear on what you mean by your second question above.  Can you elaborate?  Was that something in the UI mockups?

**Comment by nmanovic** [comment]
@rushtehrani ,

>> I am not clear on what you mean by your second question above. Can you elaborate?
when you draw/select/delete a bounding box you interact with it. It can be highlighted, other elements during the process can be highlighted or appear. If you are not going to change the part and it will behave as previously that it isn't necessary to show that in UI mockups.

>>  the document will be very helpful, if possible, try to include planned features as well.
I hope to have it in a couple of weeks. Need time to prepare and review it several times.

**Comment by AllenDun** [comment]
for different monitors, the UI is not very convenient to use, especially for the scroll bars. Maybe the layout is  not very good.

**Comment by nmanovic** [comment]
Hi @AllenDun ,

Do you mean the current UI or the proposed UI?

**Comment by AllenDun** [comment]
The current UI.
