### ISSUE TITLE
Add the names of damaged files in the console's messages

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#2723]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

In some cases (for example, damaged files) it will be useful to see an extended information in console's messages.
### Current Behaviour

Sometimes we can't create a CVAT task due to some files inside a dataset could be damaged. The current console's message contains an error code, but doesn't include an extended information about  what files are damaged.
<img width="431" alt="error_message" src="https://user-images.githubusercontent.com/45849884/105958518-c6fb2300-608b-11eb-8c54-dac54df4ae8c.PNG">

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

We often deal with a big data. And when we can't set up a CVAT task we have to find a way how to compute damaged files. It takes time. If the console's message will contain an information or a list of damaged files it will allow us to remove or fix such files and continue setting up a task, saving time.
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by lgg** [comment]
It's not the CVAT error. Current error is provided by PIL and only shown by CVAT, so on the "cvat side" we don't know anything about filename. Try to ask developers here: https://github.com/python-pillow/Pillow to add displaying a filename of broken file.

https://github.com/openvinotoolkit/cvat/blob/e43707d779fecb826a2c33bff8b46e7d79db09c4/cvat-core/src/server-proxy.js#L487

**Comment by nmanovic** [comment]
@lgg , thanks for your answer. On the server we know the filename and can include it into the error message.
