### ISSUE TITLE
Git repository not working from web-app

### ISSUE THREAD

**Issue by smoosbau** [opencv/cvat#2737]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

If setting a dataset repository URL  for a task submission fails. But if checking out the same repository from within the container (docker exec ...) it works perfectly fine and as expected.

### Expected Behaviour
Set dataset repository URL can be cloned.

### Current Behaviour
Repository cannot be cloned using the GUI.

### Steps to Reproduce (for bugs)
1. create a new task
2. add CVATs SSH key to your github account
3. add a private github repository
4. try to set the repositories SSH link as dataset repository URL

### Context
I cannot version my currently running projects without making them public on GitHub. Furthermore the versioning has no history as every new commit overrides the branches history.

### Your Environment
Docker Containers running on Arch Linux. Web Browser is Chromium but I tested it with Chrome, too.
- Git hash commit (`git log -1`): 473554bd59b6f78d6cbf0ba3aa540d2045c724ff
- Docker version `docker version` (e.g. Docker 17.0.05): 
    Client:
     Version:           20.10.2
     API version:       1.41
     Go version:        go1.15.6
    Git commit:        2291f610ae
     Built:             Tue Jan 19 17:19:21 2021
     OS/Arch:           linux/amd64
    Context:           default
    Experimental:      true

    Server:
     Engine:
      Version:          20.10.2
      API version:      1.41 (minimum version 1.12)
      Go version:       go1.15.6
      Git commit:       8891c58a43
      Built:            Tue Jan 19 17:18:55 2021
      OS/Arch:          linux/amd64
      Experimental:     false
     containerd:
      Version:          v1.4.3
      GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b.m
     runc:
      Version:          1.0.0-rc92
      GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
     docker-init:
      Version:          0.19.0
      GitCommit:        de40ad0

- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): 
    LSB Version:    1.4
    Distributor ID: Arch
    Description:    Arch Linux
    Release:        rolling

**Comment by azhavoro** [comment]
@smoosbau Hi, please attach logs from cvat container `docker logs cvat > cvat.log`

**Comment by smoosbau** [comment]
@azhavoro Thanks for your comment. Due to it I know where the error is coming from.
I can only choose betwen an https:// link or an ssh:// link. Sadly the first one needs user and password and the second one is not supported from the web GUI and thus I tried to use <remote link> instead of ssh://<remote link>. 
'docker exec -it cvat bash -ic 'git clone -v ssh://git@bitbucket.opt01.net:7999/ip/cvat_test.git /home/django/data/tasks/24/artifacts/repos' works as expected. 
Are there plans to allow ssh:// links from the web GUI, too?
