### ISSUE TITLE
problem with login

### ISSUE THREAD

**Issue by VellalaVineethKumar** [opencv/cvat#274]
The login page for user is not loading. It says "The web page at http://localhost:8080/ might be temporarily down or it may have moved permanently to a new web address."

**Comment by nmanovic** [comment]
@VellalaVineethKumar ,

Could you please send us logs for `cvat` container? In general need to have output from two commands:
- `docker ps`
- `docker logs cvat`

Also it will be useful to archive log files from the container: `docker cp cvat:/home/django/logs /tmp/` and attach to the issue.

**Comment by VellalaVineethKumar** [comment]
Thank you
i just flused thye docker image and succeded in logging in
