### ISSUE TITLE
The bug has been found. Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#278]
TypeError: Cannot convert undefined or null to object
    at Object.window.cvat.addAction [as undo] (http://localhost:8000/static/CACHE/js/1cbc5cd3f66d.js:3472:56)
    at HistoryModel.undo (http://localhost:8000/static/CACHE/js/1cbc5cd3f66d.js:1305:22)
    at HistoryController.undo (http://localhost:8000/static/CACHE/js/1cbc5cd3f66d.js:1426:25)
    at HistoryController.<anonymous> (http://localhost:8000/static/CACHE/js/1cbc5cd3f66d.js:1409:22)
    at HistoryController.<anonymous> (http://localhost:8000/static/CACHE/js/1cbc5cd3f66d.js:1074:31)
    at _fireCallback (http://localhost:8000/static/CACHE/js/e21661c7e642.js:11147:17)
    at Mousetrap.self._handleKey (http://localhost:8000/static/CACHE/js/e21661c7e642.js:11208:21)
    at Mousetrap.handleKey (http://localhost:8000/static/CACHE/js/e21661c7e642.js:11525:32)
    at HTMLDocument._handleKeyEvent (http://localhost:8000/static/CACHE/js/e21661c7e642.js:11268:18)

**Comment by bsekachev** [comment]
Error cannot be reproduced and it has occurred once.

**Comment by didumin** [comment]
Hi! 
I've meet the same issue with k8s helm deployment, would you kindly take a look 

![Screenshot 2024-05-23 at 14 08 30](https://github.com/cvat-ai/cvat/assets/152881276/99a3b2f3-c314-4486-a36e-f9fdc008904a)

frontend container logs 

`> │ /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration                                                                                                                                                                       ││ /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/                                                                                                                                                                                              ││ /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh                                                                                                                                                                                  ││ 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf                                                                                                                                                                          ││ 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version                                                                                                                                                                ││ /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh                                                                                                                                                                                          ││ /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh                                                                                                                                                                                      ││ /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh                                                                                                                                                                                      ││ /docker-entrypoint.sh: Configuration complete; ready for start up                                                                                                                                                                                                      ││ 2024/05/23 11:02:19 [warn] 1#1: duplicate MIME type "text/html" in /etc/nginx/conf.d/default.conf:18                                                                                                                                                                   ││ nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/conf.d/default.conf:18                                                                                                                                                                                     ││ 2024/05/23 11:02:19 [notice] 1#1: using the "epoll" event method                                                                                                                                                                                                       ││ 2024/05/23 11:02:19 [notice] 1#1: nginx/1.25.4                                                                                                                                                                                                                         ││ 2024/05/23 11:02:19 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r10)                                                                                                                                                                         ││ 2024/05/23 11:02:19 [notice] 1#1: OS: Linux 5.4.0-155-generic                                                                                                                                                                                                          ││ 2024/05/23 11:02:19 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576                                                                                                                                                                                            ││ 2024/05/23 11:02:19 [notice] 1#1: start worker processes                                                                                                                                                                                                               ││ 2024/05/23 11:02:19 [notice] 1#1: start worker process 29                                                                                                                                                                                                              ││ 2024/05/23 11:02:19 [notice] 1#1: start worker process 30                                                                                                                                                                                                              ││ 2024/05/23 11:02:19 [notice] 1#1: start worker process 31                                                                                                                                                                                                              ││ 2024/05/23 11:02:19 [notice] 1#1: start worker process 32                                                                                                                                                                                                              ││ 127.0.0.1 - - [23/May/2024:11:02:56 +0000] "GET /auth/register HTTP/1.1" 200 691 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36" "-"                                    ││ 127.0.0.1 - - [23/May/2024:11:02:57 +0000] "GET /api/server/health/?format=json&org= HTTP/1.1" 200 691 "http://localhost:8080/auth/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0 ││ 127.0.0.1 - - [23/May/2024:11:02:57 +0000] "GET /api/user-agreements?org= HTTP/1.1" 200 691 "http://localhost:8080/auth/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/5 ││ 127.0.0.1 - - [23/May/2024:11:02:57 +0000] "GET /api/schema/?scheme=json&org= HTTP/1.1" 200 691 "http://localhost:8080/auth/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safa ││ 127.0.0.1 - - [23/May/2024:11:02:57 +0000] "GET /favicon.ico HTTP/1.1" 200 5863 "http://localhost:8080/auth/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36" "-"   ││ 127.0.0.1 - - [23/May/2024:11:02:57 +0000] "POST /api/events?org= HTTP/1.1" 405 552 "http://localhost:8080/auth/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36" " ││ 127.0.0.1 - - [23/May/2024:11:03:02 +0000] "GET / HTTP/1.1" 200 691 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36" "-"                                                 ││ 127.0.0.1 - - [23/May/2024:11:03:02 +0000] "GET /api/server/health/?format=json&org= HTTP/1.1" 200 691 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537 ││ 127.0.0.1 - - [23/May/2024:11:03:03 +0000] "GET /api/user-agreements?org= HTTP/1.1" 200 691 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36" "-"    ││ 127.0.0.1 - - [23/May/2024:11:03:03 +0000] "GET /api/schema/?scheme=json&org= HTTP/1.1" 200 691 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36" "- ││                                                                                                                                                                                                                                                                        ││   
 `
backend 
cvat-server logs 
`
vat-backend 2024-05-23 11:11:37,332 DEBG 'uvicorn-0' stderr output:                                                                                                                                                                                                   ││ cvat-backend wait-for-it.sh: cvat-postgresql:5432 is available after 0 seconds                                                                                                                                                                                         ││ cvat-backend                                                                                                                                                                                                                                                           ││ cvat-backend 2024-05-23 11:11:37,338 DEBG 'uvicorn-0' stderr output:                                                                                                                                                                                                   ││ cvat-backend wait-for-it.sh: waiting for cvat-redis-master:6379 without a timeout                                                                                                                                                                                      ││ cvat-backend                                                                                                                                                                                                                                                           ││ cvat-backend 2024-05-23 11:11:37,341 DEBG 'uvicorn-0' stderr output:                                                                                                                                                                                                   ││ cvat-backend wait-for-it.sh: cvat-redis-master:6379 is available after 0 seconds                                                                                                                                                                                       ││ cvat-backend                                                                                                                                                                                                                                                           ││ cvat-backend 2024-05-23 11:11:37,346 DEBG 'uvicorn-0' stderr output:                                                                                                                                                                                                   ││ cvat-backend wait-for-it.sh: waiting for cvat-kvrocks:6666 without a timeout                                                                                                                                                                                           ││ cvat-backend                                                                                                                                                                                                                                                           ││ cvat-backend 2024-05-23 11:11:37,350 DEBG 'uvicorn-0' stderr output:                                                                                                                                                                                                   ││ cvat-backend wait-for-it.sh: cvat-kvrocks:6666 is available after 0 seconds                                                                                                                                                                                            ││ cvat-backend                                                                                                                                                                                                                                                           ││ cvat-backend 2024-05-23 11:11:38,351 INFO success: nginx-0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                                                                               ││ cvat-backend 2024-05-23 11:11:38,351 INFO success: smokescreen entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                                                                           ││ cvat-backend 2024-05-23 11:11:38,351 INFO success: uvicorn-0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                                                                             ││ cvat-backend 2024-05-23 11:11:39,040 DEBG 'uvicorn-0' stderr output:                                                                                                                                                                                                   ││ cvat-backend INFO:     Started server process [36]                                                                                                                                                                                                                     ││ cvat-backend INFO:     Waiting for application startup.                                                                                                                                                                                                                ││ cvat-backend                                                                                                                                                                                                                                                           ││ cvat-backend 2024-05-23 11:11:39,040 DEBG 'uvicorn-0' stderr output:                                                                                                                                                                                                   ││ cvat-backend INFO:     ASGI 'lifespan' protocol appears unsupported.                                                                                                                                                                                                   ││ cvat-backend INFO:     Application startup complete.                                                                                                                                                                                                                   ││ cvat-backend                                                                                                                                                                                                                                                           ││ cvat-backend 2024-05-23 11:11:39,041 DEBG 'uvicorn-0' stderr output:                                                                                                                                                                                                   ││ cvat-backend INFO:     Uvicorn running on socket /tmp/uvicorn.sock (Press CTRL+C to quit)     `

**Comment by didumin** [comment]
also "create new account" shows up with 
TypeError
o.map is not a function

TypeError: o.map is not a function
    at xV (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:9761357)
    at Jl (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5404492)
    at zr (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5413339)
    at Fr (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5413158)
    at Lr (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5412841)
    at wi (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5454066)
    at _s (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5443298)
    at Es (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5443223)
    at fs (http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5440246)
    at http://localhost:8080/assets/cvat-ui.5cadd6faf9aae8b22ffc.min.js:2:5391901
    
![Screenshot 2024-05-23 at 19 38 17](https://github.com/cvat-ai/cvat/assets/152881276/68d645f5-cfc4-4be1-acec-978355f5186d)
