### ISSUE TITLE
I encountered difficulties in the task configuration page.

### ISSUE THREAD

**Issue by peach1995** [opencv/cvat#28]
Now，I hava create new task.After I filled out name,labels and select files,I submitted this page.But I have been waiting for this page for two or three hours for this page that has one word: "Sucessful Request!Creating...". 
So,I want to know how to configure the task,can you share your configuration.
my configuration is as follows:
Name:            task 1
Labels:           vehicle @select=type:__undefined__,car,truck,bus,train ~radio=quality:good,bad ~checkbox=parked:false
Select Files:    2.mp4

**Comment by sjoycode** [comment]
> Labels: vehicle @select=type:undefined,car,truck,bus,train
Labels: vehicle @select=type:__undefined__,car,truck,bus,train ...
Please note "__" means double underscore. 

However this small typo does not seem to cause the main issue. Are you sure you have right privilege to make annotation (it's better to work first as **admin** as I messed up with the user permission the first time I tried). 

Another reason could be this: your mp4 video has more than 500 frames. I found it convenient to extract the frames first (with **ffmpeg**) and then proceed toward annotation. The "local" option under "Source" can not load more than 500 frames. If this is the case you need to choose "share" under "Source" option to load reasonably high number of frames (>500).

**Comment by bsekachev** [comment]
Hi, I think you have run all from Visual Studio Code, right?
Message "Sucessful Request! Creating..." means that server took you request and it was added to RQ queue. If "CVAT RQ - default" is not run, request never will be processed. Therefore make sure that it is run.

![screenshot from 2018-08-13 10-09-06](https://user-images.githubusercontent.com/40690378/44017568-721772da-9ee1-11e8-8309-fd900238ac69.png)
"CVAT Server" is server code and database. 
"CVAT Client" is Google Chrome
"CVAT RQ - default" is rq worker. It creates tasks in a separate process.
"CVAT RQ - low" is too rq worker. It makes auto-annotation with Tensorflow.
"CVAT Debugging" aggregates all together. You need run it.

**Comment by nmanovic** [comment]
Hi @peach1995 ,

Could you please confirm that the provided solution works for you? If so I'm going to close the issue.

**Comment by peach1995** [comment]
Thank you for your replies.I have tryed these solutions.
1.I have added all the privileges to my user.
2.My video only have 17s and is less than 500 frames.
3.I have start "CVAT Debugging
![image](https://user-images.githubusercontent.com/14214133/44019726-3a14c352-9f12-11e8-9340-3df7e826955b.png)
But my problem still exists.

![img_20180813_160336_2](https://user-images.githubusercontent.com/14214133/44020050-38b66302-9f13-11e8-9739-cdd41e43fefe.jpg)

**Comment by nmanovic** [comment]
Hi @peach1995 ,

It is a known problem with VS code (I have the same problem time to time). As you can see "CVAT RQ -default" doesn't have "Main Thread". Please stop "CVAT RQ - default" and run it one more time (choose corresponding item). After that it should work.

**Comment by peach1995** [comment]
Thank you for your reply,I finish my problem.
this problem need stop "CVAT Server",then restart "CVAT RQ-default".Finally,I start "CVAT Server".
We need two MainThread.
![image](https://user-images.githubusercontent.com/14214133/44024449-e396316a-9f1f-11e8-92f1-fa3f7c5943d2.png)

**Comment by nmanovic** [comment]
Awesome! Thus it is a problem with a 3rd party tool (VS code) I will close the problem.
