### ISSUE TITLE
Collect docker container logs as artifacts for failed build runs

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#2819]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Sometimes, container logs can be helpful on failed build runs

**Comment by nmanovic** [comment]
@dmitriikhurtin , was it fixed? Could you please specify the PR and I will close the issue?

**Comment by azhavoro** [comment]
Definitely, the issue was solved a long time ago
