### ISSUE TITLE
Double click is used for "Delete point" and for "Fit". It isn't conveniently.

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#283]
Often an user wants delete a point from a poly shape, but instead an user fits the player screen.

**Comment by nmanovic** [comment]
Need to collect statistics how often we use "fit" feature (add logs). Need to find another shortcut for one of them.

**Comment by ajayramezh** [comment]
What is "fit" feature?  I am trying to reproduce this issue - 

Steps:
1. Create a polygon(works)
2. Delete the points on the Polygon by double click(works)

So, as an enhancement to CVAT, first, we need to add logs to fit feature? Based on fit feature usage we can provide another shortcut? 

If you explain fit feature, I think I can add the logs to it. Any advice on this enhancement ?

**Comment by bsekachev** [comment]
@ajayramezh 
"Fit Image" feature is auto resize of an image in such way that it fully displayed in the player.
The feature has the same shortcut (double click) as the delete point feature. It is inconvenient due to possible misses by points.
Log for the feature has been already added.

**Comment by bsekachev** [comment]
In React UI you need to hold 'Ctrl' to delete a point.
Fitting doesn't work when 'Ctrl' pressed. 
So, issue is expected to be fixed, but let's get feedback from DA team.

**Comment by nmanovic** [comment]
The problem was fixed. Now we have context menu to delete a point. @ActiveChooN , please reopen the issue if I'm wrong.

**Comment by bsekachev** [comment]
@nmanovic 

There always was a context menu in CVAT. 
The issue is about double click is used in two scenarios. 
But in new UI it also has been fixed
