### ISSUE TITLE
Delay in sending logs to Logstash

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#2832]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

It looks like in case of a lot of log events (about about 1 million per day), python-logstash-async doesn't process them in time and keeps them in the queue. This leads events being pushed to logstash with a long delay(several hours in our case).

### Possible Solution
Adjust python-logstash-async settings

### Your Environment

- Git hash commit (`git log -1`): 59c3b28116f0f8599fc327bf031c05d13bceab3e
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by abid1998** [comment]
I can start working on this if someone can point me towards a direction. I am new contributor.

**Comment by chaoyifei** [comment]
In general, each data may be delayed

**Comment by chaoyifei** [comment]
> I can start working on this if someone can point me towards a direction. I am new contributor.

Hi,did you fix this problem?

**Comment by chaoyifei** [comment]
> I can start working on this if someone can point me towards a direction. I am new contributor.
Hi,did you fix this problem? @abidahmadq

**Comment by 315386775** [comment]
@abidahmadq did you fix this problem

**Comment by bsekachev** [comment]
Probably it is not relevant anymore. New logging system.
