### ISSUE TITLE
Optionally push dataset repository to master

### ISSUE THREAD

**Issue by jbrownkramer** [opencv/cvat#2836]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)

### Expected Behaviour

Press sync (or even better auto sync) and the git repository automagically updates to reflect the current tags.

### Current Behaviour

Manually have to merge the branch that gets pushed from CVAT.

### Possible Solution

Optionally specify the branch name it gets pushed to, including master

### Context

This would eliminate one more manual step in a process that I wish were more automated.

**Comment by bsekachev** [comment]
Not relevant, git feature was removed
