### ISSUE TITLE
Filter search can be very slow

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#285]
In big jobs with a large number of objects the search works slowly. It is related with the need to interpolate objects for each frame. Probably there is faster approach.

**Comment by nmanovic** [comment]
Need to add logs for the feature to understand problems, overhead. Common idea that we don't need to interpolation frames because we don't need bounding boxes. Use low_bound algorithm to find correct values for attributes. Also need some visual hints for the feature.

**Comment by bsekachev** [comment]
Suppose this issue has been resolved in new UI
