### ISSUE TITLE
Where does the shared server directory point at?

### ISSUE THREAD

**Issue by sjoycode** [opencv/cvat#29]
To create huge tasks the [documentation](https://github.com/opencv/cvat/blob/master/cvat/apps/documentation/user_guide.md) suggests choosing [Share](https://github.com/opencv/cvat/blob/master/cvat/apps/documentation/static/documentation/images/image005.jpg) option in the dialog box. 
While trying to select the files I see a modal popping up with the following path as title:
**//icv-cifs/icv_projects/cvat/data**

However I can not navigate from there (nor I can find where this path is). The documentation also does not elaborate much for large number of frames. Any advice?

![modal](https://user-images.githubusercontent.com/6692800/44013337-c921d3ee-9e79-11e8-97ef-ce96ae5f1249.JPG)

**Comment by bsekachev** [comment]
Hi, thanks for you question.
We have fixed already this problem. It will be merged at near time.
Currently, if you want create task bigger, you can change LOCAL_LOAD_MAX_FILES_COUNT and LOCAL_LOAD_MAX_FILES_SIZE variables in the cvat/settings/base.py. They define max number of files and max files size for data uploading via client.

**Comment by sjoycode** [comment]
I see. Thanks for letting me know how to get around the issue. Please feel free to close this thread if you wish

**Comment by davidsblom** [comment]
Is this fix already merged in the develop branch, because I would like to use large datasets. Thanks!

**Comment by nmanovic** [comment]
Hi @davidsblom ,

Yes, it was merged. Let us know if you have any problems.
