### ISSUE TITLE
Semi automatic semantic segmentation

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#290]

**Comment by AllenDun** [comment]
exiting functionality and very useful in production since it takes a very long time for semantic segmentation

**Comment by nmanovic** [comment]
@AllenDun ,

I'm not sure I catch your point. Could you please explain it in more details?

**Comment by AllenDun** [comment]
Our annotation team finds it takes so long time to do annotation in semantic  segmentation mode when there are thousands of images. It would be great to use semi automatic semantic segmentation.

**Comment by nmanovic** [comment]
@AllenDun ,

If your team has some particular ideas how to improve instance/semantic segmentation don't hesitate to share such ideas with us. For example, if you need a feature from another annotation tool or graphical editor to make the process better.
