### ISSUE TITLE
Support of (Key-)Point formats in CVAT

### ISSUE THREAD

**Issue by JParzival** [opencv/cvat#2910]
Hello everyone,

the issue itself is that, when I export annotations in COCO Format, points are not shown in the json, but polygons are.
I have tried both creating a new task and only annotating points and also combining points and polygons, and neither of them exports the COCO Format with both instances.

### Expected Behaviour
The expected behaviour is to be able to export the COCO Format with both points and polygons.

### Current Behaviour
The current behaviour is that the COCO Format is not able to export points.

### Possible Solution
It would just be a matter of implementing the points inside the COCO Format, so that they can be exported alongside the polygons.

### Steps to Reproduce (for bugs)
1. Create a new task
2. Set a point
3. Export in COCO Format

### Context
The project that I am actually working in requires both a combination of a mask and a keypoint inside of it, in the most important part of the object. Without the points, the goal cannot be accomplished.

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 19.03.12, build 48a66213fe
- Are you using Docker Swarm or Kubernetes? No, just Docker (required for the application)
- Operating System and version (e.g. Linux, Windows, MacOS): Windows
- Code example or link to GitHub repo or gist to reproduce problem: https://github.com/openvinotoolkit/cvat

**Comment by nmanovic** [comment]
@kirill-sizov , it is a very hot issue.

**Comment by mylee16** [comment]
Can consider trying this:
- Exporting CVAT dataset as Datumaro 1.0 format, including save images
- Unzip the dataset
- Create a new folder, `datum create`, followed by `datum import [path of unzipped dataset]`
- `datum export -f coco_person_keypoints source-1`

**Comment by yasakova-anastasia** [comment]
Keypoints have been added to CVAT and [COCO](https://github.com/opencv/cvat/pull/4821) formats.

**Comment by oz-swapnil** [comment]
This issue arose again in the latest version of CVAT.

**Comment by nmanovic** [comment]
@yasakova-anastasia , could you please check?

**Comment by yasakova-anastasia** [comment]
@oz-swapnil, could you please describe your problem in more detail? Keypoints are supported in CVAT and COCO Keypoints formats.

**Comment by oz-swapnil** [comment]
I have annotated points with multiple labels in 56 images, saved the task and tried to export the dataset as COCO Keypoints 1.0. In the JSON file, the annotations field was empty.
"annotations":[]

**Comment by yasakova-anastasia** [comment]
This format can only export skeleton annotations. Do you have skeleton annotations?
If you want to know more about skeletons, you can watch [this video](https://www.youtube.com/watch?v=88TVX58GHIc).

**Comment by oz-swapnil** [comment]
Got it @zhiltsov-max! Thank you for the clarification and thank you @yasakova-anastasia and @nmanovic for helping out. This issue can be closed now.
