### ISSUE TITLE
The 'keyframe' property changed at upload MOT 1.1 annotations.

### ISSUE THREAD

**Issue by DmitriyOparin** [opencv/cvat#2925]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The keyframe property does not change in all frames.

### Current Behaviour

The keyframe property changes in second, third and others frames.

### Possible Solution

Fix this bug.

### Steps to Reproduce (for bugs)

1.Create task with several images.
2.Draw 'Rectangle' (track) in first frame.
3.Dump MOT 1.1 annotations.
4.Upload MOT 1.1 annotations.

### Your Environment

- Git hash commit (`git log -1`): 62cc956967db2720d69c374e31ce8c85b575e429
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
MOT format can't represent keyframes, so all frames are considered keyframes on import.

**Comment by yasakova-anastasia** [comment]
I think it's not a bug because MOT format doesn't support keyframes.
