### ISSUE TITLE
Auto annotation using PyTorch models

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#297]
Need to implement a component which will annotate data using uploaded PyTorch models. It should be similar to auto annotation app based on OpenVINO.

**Comment by eliethesaiyan** [comment]
@nmanovic , I am not able to display pytorch models in the auto-annotation dropbox, but I can see them on CVAT models list and have them marked `ready` as status in nuclio functions. I would appreciate it a lot if you could give some hints for debugging this issue!

**Comment by nmanovic** [comment]
@eliethesaiyan , which models you want to see and where? We have 3 pytorch serverless functions: https://github.com/openvinotoolkit/cvat/tree/develop/serverless/pytorch

2 of them for interactive segmentation (IOG and FBRS)
1 of them for tracking (SiamMask)

**Comment by eliethesaiyan** [comment]
@nmanovic , FBRS would be the one I want to see, i can see them here
![image](https://user-images.githubusercontent.com/6031044/108577055-09e6a880-7363-11eb-88b6-348461afcd49.png)
 in nuclio functions but  i couldnt load them here 
![image](https://user-images.githubusercontent.com/6031044/108577122-40242800-7363-11eb-87f2-f0848936e344.png)

**Comment by nmanovic** [comment]
@eliethesaiyan , you need to open the job and use "magic wand" to use it. FBRS is an interactive model. It can not be run as a detector on the whole task. It requires some input from you (at least one positive point).

![image](https://raw.githubusercontent.com/saic-vul/fbrs_interactive_segmentation/master/images/fbrs_interactive_demo.gif)

**Comment by eliethesaiyan** [comment]
@nmanovic, thank you very much, I was not aware of this feature, I just tried it indeed and it seems to work!
I have a different interface compare to the one that is in this gif you`ve referenced, is loaded through OpenCV?

**Comment by beep-love** [comment]
@nmanovic Can we use our trained PyTorch model In cvat to perform automatic annotation?
