### ISSUE TITLE
Delete / mark as broken image from task

### ISSUE THREAD

**Issue by kbegiedza** [opencv/cvat#3000]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context
Sometimes I want to delete few images from created task (they are low quality or contains too many objects / whatever reason).
Currently there is no possible solution for this.

Many other tools provides this feature or 'broken image' flag instead.

Current process:
* export whole dataset
* find & delete image with related annotation
* re-upload dataset

**Comment by nmanovic** [comment]
@Ursanon , probably it can be supported exactly as a flag. Internally we will have all images but don't show them by default in UI. The flag has to be stored in DB (e.g. inside image info table).

**Comment by dnns92** [comment]
Dear Contributors,
I just want to emphazise the necessity of this feature. Following new EU regulations, hosts must ensure that hosted images do not endorse violence. This might be the case in many datasets for certain images, e.g. in the widerface dataset, which contains army imagery (including some brutal scenes). Right now when detecting such an image in our cvat, I have to manually download the task, delete the image from the hdd and the annotations and re-upload the task. Then I have to adapt our scripts to the new task ID, which is a time-consuming work. Having a delete-button would make my life much easier!

Cheers!

**Comment by nmanovic** [comment]
hi @dnns92 , thanks for the comment. The feature is mostly ready: https://github.com/openvinotoolkit/cvat/pull/4194. We will merge it as soon as it will be possible. Sorry for the bad experience.

**Comment by bsekachev** [comment]
Hi guys, @kbegiedza @dnns92 

The feature has been finished and implemented in our CVAT fork, here: https://github.com/cvat-ai/cvat
