### ISSUE TITLE
With big amount of projects/tasks Projects page get slow to open and makes too much api and db requests

### ISSUE THREAD

**Issue by summeroff** [opencv/cvat#3128]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Projects page opens fast and not make unnecessary web and db requests. 

### Current Behaviour
It was faster in the beginning but with growing number of projects and tasks it get slower and slower. 
Right now to open Projects it takes 30+ seconds. 

In browsers dev tools it shows what /projects request takes 30 seconds to complete and then followed by huge amount of /data?type=preview requests. 

<a href="https://ibb.co/Dp3LPRH"><img src="https://i.ibb.co/Dp3LPRH/projects-network-list1.png" alt="projects-network-list1" border="0"></a>

Also with enabled query logging on db. It logs like 30000+ sql select queries just when Projects page requested. 
To get this logs I add this to compose config 
```
    container_name: cvat_db
    image: postgres:10-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
```
refreshed page in browser and saved logs by
`docker logs 5278709de3c0 &> sql.log.txt`

### Your Environment

- Git hash commit (`git log -1`): 17908003df9565bab02120c38834023f31eef494
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.5, build 55c4c88
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Window locally and ubuntu on vps. 
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by ActiveChooN** [comment]
@summeroff, it was happening due to attempting to serialize and return all nested tasks in the projects' request. So it resulted in numerous queries to the database. The related patch should fix it by retrieving only necessary previews and no nested tasks in the projects' request.

**Comment by summeroff** [comment]
Checked on dk/fix-issue-3128 branch. 
Projects page is fast now but only for a first page "projects?page=1". Any other page is noticeable slower. 

Pages of individual projects still slow for projects what has big number of tasks.

**Comment by ActiveChooN** [comment]
@summeroff, I would reopen the issue and move it to a backlog, if slow responses remain. You are free to open PR if you have a solution.

**Comment by bsekachev** [comment]
REST API was significantly optimized. Not relevant anymore.
