### ISSUE TITLE
Not correct number of frames in video

### ISSUE THREAD

**Issue by Alexander-Petrikov** [opencv/cvat#32]
I load video with resolution 4096x2178. Number of frames is 1079.
In job statistic I see number of frames is 959 and in xml file number of frames is the same.

**Comment by nmanovic** [comment]
@Alexander-Petrikov ,

Why do you think that number of frames is 1079? Indeed we use ffmpeg to extract frames with -vsync 0.

```
-vsync parameter
Video sync method. For compatibility reasons old values can be specified as numbers. Newly added values will have to be specified as strings always.

0, passthrough
Each frame is passed with its timestamp from the demuxer to the muxer.

1, cfr
Frames will be duplicated and dropped to achieve exactly the requested constant frame rate.

2, vfr
Frames are passed through with their timestamp or dropped so as to prevent 2 frames from having the same timestamp.

drop
As passthrough but destroys all timestamps, making the muxer generate fresh timestamps based on frame-rate.

-1, auto
Chooses between 1 and 2 depending on muxer capabilities. This is the default method.
```

**Comment by Alexander-Petrikov** [comment]
OpenCV shows me number of frames 1079. 
Also I run commands from https://stackoverflow.com/a/28376817. The result is the same with and without option '-vsync 0'

**Comment by nmanovic** [comment]
Hi @Alexander-Petrikov ,

Could you please insert here output from the command below?

```
ffmpeg -i <your video file> -start_number 0 -b:v 10000k -vsync 0 -an -y  %d.jpg
```

Please run the experiment on your local machine. Also it will be good to run it in cvat container as well but I hope that results should be the same.

**Comment by nmanovic** [comment]
Hi @Alexander-Petrikov ,

I'm glad that the issue has been resolved. I will close the discussion in this case.
