### ISSUE TITLE
After cvat upgrading to version 1.2 analytics doesn't work correctly.

### ISSUE THREAD

**Issue by dzabrodin** [opencv/cvat#3206]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

 What I tried to do:

* fixing of cvat_libana_setup configuration [#522](https://github.com/openvinotoolkit/cvat/issues/522)  and then rebuilding
* upgrading to 1.3 and develop versions (2021-04-29)

When I deployed CVAT 1.3 on the other host, this problem isn't appear.

### Expected Behaviour

Correct CVAT logs registration and displaying all events in Analytics tab

### Current Behaviour

Events that happened after the upgrading aren't displayed

### Steps to Reproduce (for bugs)

1. Update to CVAT 1.2
2. build and run CVAT with command "docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/analytics/docker-compose.analytics.yml up -d --build"

### Your Environment

- Git hash commit (`git log -1`): ada95e8f5eaf7615be3a9a7d5c6b3ec9cbf17279
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.6
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
- [logs link on google drive](https://drive.google.com/drive/folders/1SDDRHJpO1Rnvj4H_xjvRTIwr5v2RBNdf?usp=sharing)
### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by turowicz** [comment]
Same problem on 1.3

**Comment by turowicz** [comment]
Going to Dashboard > Management throws:

```
Cannot read property '2' of undefined
```
