### ISSUE TITLE
Interpolation format xml file convert to annotation format

### ISSUE THREAD

**Issue by 7wdeepin** [opencv/cvat#327]
I use cvat tool in interpolation mode to label frame in video. How can i convert interpolation format xml file to annotation format ?

**Comment by nmanovic** [comment]
@7wdeepin ,

Did you find a solution? Why have you closed the issue?

**Comment by 7wdeepin** [comment]
I did not find the function and i try to parse xml file by myself.

**Comment by nmanovic** [comment]
@7wdeepin ,

There is a workaround. You can go to admin panel and change "annotation mode" for your task from "interpolation" to "annotation". After that dump your annotations. I hope it will work.

![image](https://user-images.githubusercontent.com/40690625/52850369-5966be00-3124-11e9-9ad6-f767d842fa36.png)

**Comment by turner-rovco** [comment]
Was just having this issue as well actually! Thanks for the respone nmanovic, I tried that and got the following error?

Dump process completed with an error. OSError: [Errno 22] Invalid argument: '/home/django/data/4/data/0/0/0.jpg'

**Comment by 7wdeepin** [comment]
@nmanovic ,

Thank you for your response. I have tried the method mentioned above, but some errors happened when ready to dump xml file, 
`Dump process completed with an error. OSError: [Errno 22] Invalid argument: '/home/django/data/9/data/0/0/0.jpg'` . 
And i have solved the problem by parsing interpolation xml file.

**Comment by bjornamr** [comment]
Can you share the file for parsing, @7wdeepin ?

**Comment by 7wdeepin** [comment]
@bjornamr ,
I'm sorry for the license, I have no permission to share the code.

**Comment by AntoineSevec** [comment]
Someone else can share the file for parsing ?
