### ISSUE TITLE
Connecting computers outside the network

### ISSUE THREAD

**Issue by pvenuprasad** [opencv/cvat#329]
I have issue with the server. I am able to access the server from computers connected to the LAN but not from ones which are outside the network. Could you please tell me how you resolve the issue?

**Comment by nmanovic** [comment]
Hi @pvenuprasad ,

Probably it isn't related to CVAT. It is pure configuration of your computer and LAN. You need to be sure that the port is opened (default port of CVAT is 8080) and firewall is configured correctly.

**Comment by nmanovic** [comment]
@pvenuprasad ,

I will close the issue. Don't hesitate to ask me additional questions using gitter.im/opencv-cvat.

**Comment by JoeyZhu** [comment]
maybe 8080 is blocked on your ISP
