### ISSUE TITLE
how to get image which are uploaded by others?

### ISSUE THREAD

**Issue by valleyzine** [opencv/cvat#331]
Hello Dear.

the scenario is as below.
1) I have a superuser account in cvat.
2) Other user upload images and annotated the images.
3) Save the work.
4) I can dump/download the annoation file (XML) 
5) But i can't download the images.
*6) How can i get/download the images.

regards,
jin

**Comment by nmanovic** [comment]
Hi @valleyzine , please use gitter.im/opencv-cvat to ask questions. Now we don't have a good way to download original images from CVAT server. There are several workarounds. One of them: you can go to the server `data` directory and find necessary images.

**Comment by nmanovic** [comment]
@valleyzine , I will close the issue. If you have any other questions, don't hesitate to ask them in our gitter room.
