### ISSUE TITLE
Add documentaiton about how to use LFS checkbox

### ISSUE THREAD

**Issue by CrazySandy** [opencv/cvat#335]
when create new task,there is an options:use LFS. I do not find the instructions for this in the use guide. so anyone can help to explain what is it used for ? thanks!

**Comment by nmanovic** [comment]
@CrazySandy , please use gitter.im/opencv-cvat for such questions. In general LFS is a feature of git (https://git-lfs.github.com/). If you enable it CVAT will store your annotations as LFS files in provided git repository. Otherwise it will store them as usual text files.

**Comment by nmanovic** [comment]
It was fixed: `Use LFS. If the annotation file is large, you can create a repository with LFS support.`
