### ISSUE TITLE
Feature request: Temporarly disabling OpenCV intelligent scissors to create a boundary manually [Shortcut?]

### ISSUE THREAD

**Issue by michaelyyq** [opencv/cvat#3383]
1. When using opencv polygon annotation mode, blur boundary is noisy. If it can be turned to normal polygon mode with hot key, it will be great.
2. When editing the polygon annotation, how can we add point.

**Comment by bsekachev** [comment]
Hi @michaelyyq 

> 1. When using opencv polygon annotation mode, blur boundary is noisy. If it can be turned to normal polygon mode with hot key, it will be great.

Could you please provide an example for better understanding?

> 2. When editing the polygon annotation, how can we add point.

Holding "Shift" press on a point. Release "Shift". Then you can redraw a part of the boundary (you also can add a point in the middle). Then press a neighbor point. 

![Peek 2021-07-02 12-51](https://user-images.githubusercontent.com/40690378/124256648-35a94480-db34-11eb-93ef-2fb5a6539119.gif)

**Comment by michaelyyq** [comment]
> Hi @michaelyyq
> 
> > 1. When using opencv polygon annotation mode, blur boundary is noisy. If it can be turned to normal polygon mode with hot key, it will be great.
> 
> Could you please provide an example for better understanding?
> 
> > 1. When editing the polygon annotation, how can we add point.
> 
> Holding "Shift" press on a point. Release "Shift". Then you can redraw a part of the boundary (you also can add a point in the middle). Then press a neighbor point.
> 
> ![Peek 2021-07-02 12-51](https://user-images.githubusercontent.com/40690378/124256648-35a94480-db34-11eb-93ef-2fb5a6539119.gif)

**Comment by michaelyyq** [comment]
1. Example: When using Opencv mode,  it will detect the boundary and create polygon points automatically. But often the boundary is blurry so that the created points deviate too far which I have to change or move carefully with a tiny step.  The moment what I want is that I can draw a line manually.

**Comment by michaelyyq** [comment]
If there is a hot key to switch automatically boundary creating and manually drawing, it will be better.

**Comment by michaelyyq** [comment]
Do I express clearly? Need a gif animation?

**Comment by michaelyyq** [comment]
![cvat#3383.png](https://i.loli.net/2021/07/02/ED37Shmsjg8NKMe.png)
- [cvat#3383](https://i.loli.net/2021/07/02/ED37Shmsjg8NKMe.png)
Please see the picture， point C is not what I want, I want point A to move straight to point B as a line segment.

**Comment by michaelyyq** [comment]
Because of the indistinct boundary between point A and point B, Opencv line detection is deviating to point C. I want to draw a line A to B in polygon draw mode when it is needed or I will listen to the Opencv recommended points. So it needs a function to switch between the two modes by a hotkey freely.

**Comment by michaelyyq** [comment]
@bsekachev Hi, Will you be free to answer my question？Look forward to your answer.

**Comment by bsekachev** [comment]
@michaelyyq 

As far as I understand, you want to temporarily disable the OpenCV algorithm to draw a part of the border manually, then enable it again. It might be implemented for example by holding a key (when it is held, OpenCV does not suggest automatic borders). But this feature is not implemented yet.

**Comment by michaelyyq** [comment]
@bsekachev Thanks for your great answer. You just get what I mean. Will you mind planning to implement this feature recently? For tedious annotation jobs, it will significantly improve convenience with this feature.

**Comment by bsekachev** [comment]
@michaelyyq 

We do not have direct plans to implement it, but now we are working on improvements in serverless functions and OpenCV integration. Probably we could implement it on our side together with other features, but I can promise anything. Since CVAT is an open-source tool, it would be awesome if somebody from the community could provide us the feature.

**Comment by bsekachev** [comment]
Related #2800

**Comment by bsekachev** [comment]
Implemented
