### ISSUE TITLE
OpenVINO version

### ISSUE THREAD

**Issue by kenho211** [opencv/cvat#340]
I have used pre-trained model of OpenVINO for human detection.
I followed the installation guide of installation of the OpenVINO component (using 2018 R3)
To merge the bounding boxes, I use the new function, Run ReID Merge and got the following error.

![reid](https://user-images.githubusercontent.com/32618031/53653843-435e0f00-3c87-11e9-8178-fa2febcdd2a7.PNG)

**Comment by kenho211** [comment]
Installing OpenVINO 2018 R5.0.1 solved the problem.

**Comment by machinedogwc** [comment]
hi, could you help to provide the  OpenVINO 2018 R5.0.1 ? I can't find it in the website.Thanks

**Comment by kenho211** [comment]
https://docs.openvinotoolkit.org/
You can select version on the top right
