### ISSUE TITLE
Reduce number of jpeg file generated from video input file

### ISSUE THREAD

**Issue by zliang7** [opencv/cvat#343]
When create a task with a video input, every frame is extracted and saved to disk. For a relative long video (e.g. 15min), too much (15*60*25 = 22500) files are generated. A policy is needed to reduce the number of files, e.g. each 100-th frame.

**Comment by nmanovic** [comment]
Hi @zliang7 ,

We already have similar issue: https://github.com/opencv/cvat/issues/194. I will close this one.
