### ISSUE TITLE
The selection of 3D object（point cloud and the increase and optimization of annotation function)

### ISSUE THREAD

**Issue by DeepBlue23** [opencv/cvat#3435]
1.Point cloud annotation needs top view frame drawing, because what we see in the work area is a plane image, so it is better to determine the size of the object by first frame drawing from the top view.
2.Through some traditional algorithms, such as "L-shape". By adjusting the box marked with the target point cloud, you can get the desired box more conveniently in the adjustment phase.
3.You can modify the box size parameter manually, which can help the annotator reduce unnecessary fine-tuning.Or you can set the parameter of the label size. The box of the label is selected according to the parameter size given by the label by default, and the subsequent adjustment is reserved

**Comment by nmanovic** [comment]
@DeepBlue23 , if you can explain in more details each item, it will help. For now I'm not sure I understand exactly what you mean.

**Comment by bsekachev** [comment]
I will close the issue for now. 
Do not hesitate to reopen if you have any updates.
