### ISSUE TITLE
Unable to download file bigger that 1gb in local cvat 

### ISSUE THREAD

**Issue by joaquin03** [opencv/cvat#3499]
I'm taring to download a datasets bigger that 1GB, the download start but when arrives to 1gb stops.

I try with this 
Try to set `--limit-request-body 0` here https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L65 and rebuild images with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

But didn't change anything.

Do you have any recommendations. 

Thanks!

**Comment by azhavoro** [comment]
@joaquin03 Hi, try to use the release 1.5.0, this issue should be fixed.

**Comment by rusguliev** [comment]
Hi, we are using version 1.5.0 and we are also experiencing the problem of downloading files over 1gb.
