### ISSUE TITLE
CVAT - AWS-Deployment guide 

### ISSUE THREAD

**Issue by ajayramezh** [opencv/cvat#35]
It would be nice if we have some docs telling how we can deploy this into the AWS CUDA Deep-learning machine. 
Let me add this to the doc of CVAT or if anyone can build CVAT AMI at AWS would be great. Most of the time, we use the CVAT in AWS. I believe it would be helpful to other teams.

**Comment by nmanovic** [comment]
Hi @ajayramezh ,

> Let me add this to the doc of CVAT 

Please don't hesitate to send us a PR with such kind of documentation. We will be glad to include it as a guide.
