### ISSUE TITLE
Thumbnail Previews Not Showing

### ISSUE THREAD

**Issue by kosehy** [opencv/cvat#3509]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

After creating more task, I expect that when I reload the task page that has a preview, the fetch request `/api/v1/tasks/1/data?type=preview` should return a successful fetch without uncommenting `Use Cache` option in Advanced configuration.

### Current Behaviour

After creating task, when I reload the task page that has a preview, it will take around 1 minute and will timeout, to which the page will then finally load without any images, and will display 'preview' in it's place.

### Possible Solution

During making task, uncheck the `Use cache` option in Advanced configuration will solve the timeout issue.

### Steps to Reproduce (for bugs)

1. Change the accessModes value to ReadWriteMany in [backend storage file](https://github.com/openvinotoolkit/cvat/blob/develop/helm-chart/templates/cvat_backend/storage.yml)
2. Use [how to deploy cvat using helm-chart](https://github.com/openvinotoolkit/cvat/tree/develop/helm-chart#how-to-deploy-new-version-of-chart-to-cluster) to deploy cvat using kubernetes
3. Create new project
4. Create a new task without uncommenting `No Cache` option in Advanced configuration
5. Open task
6. reload web browser
7. Suddenly the page will take more than 1 minutes, and the preview image is not display.
![image](https://user-images.githubusercontent.com/10434273/128136351-5637947d-c22f-4b7a-868b-011cba03eebe.png)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes? Kubernetes 1.19.9
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Storage Class: openebs-rwx
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
   kubectl exec -it -n cvat $(kubectl get pod -n cvat | grep backend| awk '{print $1}') -- bash -c "python3 manage.py createsuperuser"
<details>
<summary>Logs from `cvat` container</summary>
[Wed Aug 04 06:52:02.292165 2021] [wsgi:error] [pid 539:tid 140149688346368] [client 192.168.24.22:43300] Timeout when reading response headers from daemon process 'localhost:8080': /tmp/cvat-server/htdocs/api, referer: https://cvat.test.local/tasks?page=1

2021-08-04 06:52:02,296 DEBG 'runserver' stderr output:
[Wed Aug 04 06:52:02.296122 2021] [wsgi:error] [pid 539:tid 140149691123456] [client 192.168.24.22:43298] Timeout when reading response headers from daemon process 'localhost:8080': /tmp/cvat-server/htdocs/api, referer: https://cvat.test.local/tasks?page=1
2021-08-04T06:52:02.296506501Z
2021-08-04 06:52:04,917 DEBG 'rqworker_low' stderr output:
DEBUG - 2021-08-04 06:52:04,916 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.
2021-08-04T06:52:04.917431224Z
2021-08-04 06:52:34,918 DEBG 'rqworker_low' stderr output:
DEBUG - 2021-08-04 06:52:34,917 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.
2021-08-04T06:52:34.928198066Z
2021-08-04 06:52:42,525 DEBG 'runserver' stderr output:
[Wed Aug 04 06:52:42.525316 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300] [2021-08-04 06:52:42,522] ERROR cvat.server.task_6: cannot get requested data type: preview, number: None, quality: compressed
[Wed Aug 04 06:52:42.525355 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300] Traceback (most recent call last):
[Wed Aug 04 06:52:42.525358 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]   File "/home/django/cvat/apps/engine/views.py", line 586, in data
[Wed Aug 04 06:52:42.525361 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]     frame_provider = FrameProvider(db_task.data, db_task.dimension)
[Wed Aug 04 06:52:42.525365 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]   File "/home/django/cvat/apps/engine/frame_provider.py", line 96, in __init__
[Wed Aug 04 06:52:42.525367 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]     cache = CacheInteraction(dimension=dimension)
[Wed Aug 04 06:52:42.525368 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]   File "/home/django/cvat/apps/engine/cache.py", line 22, in __init__
[Wed Aug 04 06:52:42.525370 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]     self._cache = Cache(settings.CACHE_ROOT)
[Wed Aug 04 06:52:42.525372 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]   File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 576, in __init__
[Wed Aug 04 06:52:42.525374 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]     self.drop_tag_index()
[Wed Aug 04 06:52:42.525375 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]   File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 2026, in drop_tag_index
[Wed Aug 04 06:52:42.525378 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]     self.reset('tag_index', 0)
[Wed Aug 04 06:52:42.525379 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]   File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 2412, in reset
[Wed Aug 04 06:52:42.525381 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]     sql_retry(statement, (value, key))
[Wed Aug 04 06:52:42.525383 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]   File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 663, in _execute_with_retry
[Wed Aug 04 06:52:42.525385 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300]     return sql(statement, *args, **kwargs)
[Wed Aug 04 06:52:42.525386 2021] [wsgi:error] [pid 712:tid 140149590943488] [remote 192.168.24.22:43300] sqlite3.OperationalError: database is locked

2021-08-04 06:52:42,525 DEBG 'runserver' stderr output:
</details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@Marishka17 @azhavoro Could you please comment?

**Comment by Marishka17** [comment]
Related issue #2793

**Comment by pkumar219** [comment]
are there any solution for this issue?

**Comment by nmanovic** [comment]
@pkumar219 , need more details from you to understand what is going on. We re-implemented how they are shown now.

**Comment by pkumar219** [comment]
i upgraded to CVAT to latest version and after that thumbnails not showing up https://localsystem/api/tasks/157/data?org=&type=preview which is not showing up ,what was the changes that was made? how can i fix it after upgrade?

**Comment by jv1522** [comment]
Even I am facing this issue. I wonder if this could be resolved.

**Comment by bsekachev** [comment]
Not relevant anymore, cache was redesigned using KeyDB in RAM
