### ISSUE TITLE
Slow frame load for videos

### ISSUE THREAD

**Issue by demirhere** [opencv/cvat#356]
I've discussed this on Gitter as well, but I'll open an issue for now as I can't seem to find a solution.

We're running cvat on AWS EC2. Our video loads at 200 ms per frame, and this is after reducing the resolution a lot (15 KB) per frame. We've increased the instance from 1 core 2GB to 2 core 4GB. We've tested just downloading a file from the server to test if the server is slow, but it downloads 1.5 MB/s. We also tested disk read times - the files are on SSD already, and the disk read is normal.

Is there anything that can be done?

**Comment by demirhere** [comment]
We just launched a new instance in our office server (as opposed to our current AWS EC2 machine). The load time is very fast (1 ms/frame) on localhost, as well as for machines in the same network. But as soon as we connect from outside the network, it goes back up to 180ms/frame.

**Comment by nmanovic** [comment]
It seems we need to optimise somehow loading of frames. There are a number of ways to do that. One way is to use https://github.com/phoboslab/jsmpeg library. The idea is:
- compress a batch of frames (e.g. 1000) as a video file (ts)
TRANSMIT DATA:
- send it to the client
- decompress it on the client using jsmpeg
- when it is necessary send next batch of frames as a video
- GOTO TRANSMIT DATA

**Comment by cagdasbas** [comment]
@nmanovic We also upgraded apache2 to a more recent version (2.4.38) and enabled http2 but it didn't help either. CVAT sends the images sequentially. Result is the same with both Firefox 66 and Chrome  73.

**Comment by nmanovic** [comment]
Note: Don't use html5 `<video>` tag to implement the feature. In general case it is not possible to have precise frame-by-frame positioning. Discussion: https://github.com/w3c/media-and-entertainment/issues/4

**Comment by PGCodehub** [comment]
Hi @nmanovic 

Thanks for amazing tool and we are presently using it but this slow loading problem is really huge problem 

I would like to solve it if possible , I have no experience in server side stuff  , can you please guide me a little on how to get started  or anything , I might be able to solve this using your proposed method(https://github.com/opencv/cvat/issues/356#issuecomment-477825194)

It would really be great help , Thank you

**Comment by nmanovic** [comment]
@PGCodehub ,

You can run one instance of CVAT in your infrastructure from scratch. Upload a couple of typical tasks and see if it works better for your case. If you confirm that it works fast enough for you it means that we go in the right direction.

**Comment by bsekachev** [comment]
@PGCodehub 

Hope it helped you. I will close the issue
