### ISSUE TITLE
Can't connect to localhost if project is build with tf annotation component

### ISSUE THREAD

**Issue by RasidCetin** [opencv/cvat#358]
Hello,

I have a problem with the connection to the login page when I try to build with the tf annotation component. This is how it looks when I try to connect to the login page. 
![Screenshot from 2019-03-26 16-12-44](https://user-images.githubusercontent.com/6826644/55003986-1381fd00-4fe2-11e9-8b10-722c81495e94.png)

Output of "docker ps":
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                              NAMES
42824587bbca        cvat                   "/usr/bin/supervisord"   8 minutes ago       Up 8 minutes        0.0.0.0:8080->8080/tcp, 8443/tcp   cvat
763e85143cb3        redis:4.0.5-alpine     "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        6379/tcp                           cvat_redis
29d0edddec8e        postgres:10.3-alpine   "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        5432/tcp                           cvat_db

Output of "docker logs cvat":
[logs_cvat.txt](https://github.com/opencv/cvat/files/3008535/logs_cvat.txt)

One of the errors from "docker logs cvat" is: "ImportError: No module named 'openvino'". It is required this module in order to run the image for tf annotation?

If I build the project just with the default components, everything is alright. I am able to load videos and start the annotation process.
Would you be kind to provide all the steps that I should perform in order to make this component work? Thank you!

**Comment by bsekachev** [comment]
@RasidCetin 
Thank you for your report. This is a bug. I will fixed it as soon as possible and notify you.

**Comment by bsekachev** [comment]
@RasidCetin 
The fix works for me #359
