### ISSUE TITLE
Multiple context images per 2d image

### ISSUE THREAD

**Issue by tom-robo** [opencv/cvat#3596]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

Hi All, really glad to see there is an option of context images for the 2D as well as 3D cases. I was wondering if it would be possible to extend the 2D context images to allow multiple context images per image. 

I have tried adding multiple context images to each image directory for related_images/  but it didn't work (not unexpected). It would also be great if the context image could be viewed side-by-side with the image to be annotated instead of blanking off the surrounding screen when viewing the context image. 

Thanks.

**Comment by bsekachev** [comment]
Resolved in https://github.com/opencv/cvat/pull/5542
