### ISSUE TITLE
After Import Task an error message is displayed for the next issues

### ISSUE THREAD

**Issue by SandyChou84** [opencv/cvat#3613]
When I use the import task button, I can view the problem commands, but when I select the problem button (hope go to next issues), an error message appears:

TypeError
 Cannot read property 'username' of null

TypeError: Cannot read property 'username' of null
 at http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:414:1054586
 at Array.map ()
 at b_ (http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:414:1053887)
 at Ko (http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:352:57930)
 at gs (http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:352:104169)
 at cl (http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:352:96717)
 at sl (http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:352:96642)
 at Qs (http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:352:93672)
 at http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:352:45314
 at t.unstable_runWithPriority (http://localhost:8080/cvat-ui.9a9b3494bd04d60fdf16.min.js:360:3844)

CVAT version
 Server: 1.5
 Core: 3.13.3
 Canvas: 2.5.0
 UI: 1.21.1

Thanks for the help.

**Comment by bsekachev** [comment]
> When I use the import task button, I can view the problem commands, but when I select the problem button (hope go to next issues), an error message appears:

Unfortunately, I don't understand your message. Please, be more descriptive, provide some screenshots or a gif file.

**Comment by bsekachev** [comment]
@SandyChou84 

Got your email and saw the error.
Did you export the task on the same CVAT instance? I suspect that user who created the issue does not exist on the instance, where you imported the task.

**Comment by SandyChou84** [comment]
My step for Export Tast :
1、"Request a review" and select the username. 
2、Create the issues in frame 0 and frame 257.
3、"Save current changes".
4、"Submit the review".
5、"Export Task".

My step for Import Task:
1、"Import Task".
2、click "Issue" (happen error)
3、"Request a review" and select the username.
4、click "Issue" (happen error)
5、"Submit the review".
6、click "Issues" (happen error)

I don't know how use click "issues"  no error in Import task.

Thanks for your help.

**Comment by bsekachev** [comment]
Let's close for now as outdated. If somebody can reproduce in the newest version, please, reopen
