### ISSUE TITLE
Auto annotation with personal models

### ISSUE THREAD

**Issue by RasidCetin** [opencv/cvat#363]
Hello,

    Is there a way in which I can upload my own model in order to use the auto annotation functionality? In this moment I am able just to run with the default model. I don't see anywhere a function which I can use to upload my model.
   I've build the project as is summarized here: https://github.com/opencv/cvat/blob/develop/components/tf_annotation/README.md.

   The login page looks like this:
![Screenshot from 2019-03-28 12-25-13](https://user-images.githubusercontent.com/6826644/55150631-341e9400-5155-11e9-9259-ce5c12fd5743.png)

    It is required another component to be installed to have the option to load my models? Thank you! :)

**Comment by bsekachev** [comment]
@RasidCetin 
Yes, you can upload your custom models for automatic annotation. 
For more information, please refer to this [page](https://github.com/opencv/cvat/blob/develop/cvat/apps/auto_annotation/README.md).
Also, you need build CVAT with [OpenVINO component](https://github.com/opencv/cvat/tree/develop/components/openvino).
I recommend to use R5 version.

**Comment by nmanovic** [comment]
Hi @RasidCetin ,

I hope we answer on the question. I will close the issue. If you have any other questions please use https://gitter.im/opencv-cvat channel.

**Comment by getcontrol** [comment]
Literally all of the links above are now broken:
https://github.com/openvinotoolkit/cvat/blob/develop/components/tf_annotation/README.md
https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/auto_annotation/README.md
https://github.com/openvinotoolkit/cvat/tree/develop/components/openvino

**Comment by bsekachev** [comment]
@getcontrol 
Could you please submit a separate "Documentation" issue? The documentation has recently been significantly modified and it is why you can notice some dead links now.
