### ISSUE TITLE
No support to change label name after creating task

### ISSUE THREAD

**Issue by Alexander-Petrikov** [opencv/cvat#37]
I created a task with the wrong label (maybe with mistake). After creating the task, I can not change this label, only add a new one. The decision to create a new task does not look good.

**Comment by nmanovic** [comment]
Hi @Alexander-Petrikov ,

I agree that the feature is useful but need to say that it is dangerous. Probably only admin should be able to delete a label with attributes from a task. Also you can add a new label already now (use `update task` button) and don't use the old one.

**Comment by nmanovic** [comment]
hi @Alexander-Petrikov ,

Now you can change labels and attributes for a task inside admin panel: #157
