### ISSUE TITLE
Provide CLI as own package

### ISSUE THREAD

**Issue by christian-steinmeyer** [opencv/cvat#3716]
### My actions before raising this issue
- [ x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x ] Searched [past issues](/issues)

### Expected Behaviour

I'd like to be able to `pip install cvat-cli`.

### Current Behaviour

`ERROR: No matching distribution found for cvat-cli` :(
### Possible Solution

Extract the [utils/cli](/openvinotoolkit/cvat/tree/develop/utils/cli) directory to its own repository named `cvat-cli`, make this pypi conform so that it can be packaged and easily worked with from within python code and include it as a git submodule here in the cvat repository

### Context

We have a CVAT instance for labeling data. We now want to write code that automatically downloads all new labelled data. Right now, we've implemented custom functions for this, but it would be much easier if we could just import the cli and use that instead.

**Comment by christian-steinmeyer** [comment]
Is this scheduled? Looks, like we're not the only ones looking for something like this.

**Comment by christian-steinmeyer** [comment]
Hey @azhavoro any idea, when this might be tackled?

**Comment by zhiltsov-max** [comment]
Hi, we have [published `cvat-cli` package on PyPI](https://pypi.org/project/cvat-cli/). Install with `pip install cvat-cli`.
