### ISSUE TITLE
Inference Error from Automatic Annotation[Failed to invoke nuclio function]

### ISSUE THREAD

**Issue by himalayanZephyr** [opencv/cvat#3734]
Hi
I'm trying to run a custom Retinanet model using an Auto Annotation setup.
Strangely, it was working before and now it's not anymore. I assume it has something to do with nuclio.

I'm getting the following error from **cvat** logs

```
`Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 502, in __call__
    LambdaJob._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 370, in _call_detector
    annotations = function.invoke(db_task, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 204, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 78, in invoke
    return self._http(method="post", url='/api/function_invocations',
  File "/home/django/cvat/apps/lambda_manager/views.py", line 56, in _http
    reply.raise_for_status()
  File "/opt/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations
```

And this is the error from **nuclio** logs

`"responseStatus": 500, "responseTime": "269.738178ms", "responseBody": "{\"error\": \"Failed to invoke function: Post \"http://172.17.0.1:32769\": dial tcp 172.17.0.1:32769: connect: connection refused\"}"}`

I tried nuctl version 1.6.18, 1.6.4 and 1.5.16.
I wonder when it was working intermittently (restarting the computer or changing to a different network), the port that cvat was trying to access was accessible sometimes and the other times not?

I am using Ubuntu 18.10 (on which it worked sometimes ). Did not work at all on Ubuntu 20 (same error though)

No success trying the tips from this thread https://github.com/openvinotoolkit/cvat/issues/2189

**Comment by bsekachev** [comment]
Hi @himalayanZephyr 

Try to deploy the function again. Sometimes it happens with nuclio after rebooting.

**Comment by himalayanZephyr** [comment]
@bsekachev Thanks for your comment. I'll try that on the machine on which it worked before. Any ideas what can I do about the machine where it didn't work at all? I already tried redeploying several times on nuclio on the machine where it did not work even for a single time but no success there.

**Comment by bsekachev** [comment]
1. Documentation mentioned that [only 1.5.16 is supported](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/). Maybe try one more time with this version.
2. Do you have any proxy setups in your environment?
3. What is ``docker ps`` output?
4. Maybe there is output exactly from the function container?
