### ISSUE TITLE
Export format for Microsoft's Visual Object Tagging Tool (VoTT)

### ISSUE THREAD

**Issue by ghost** [opencv/cvat#3751]
Do you have plans to include the export format for Microsoft's[ Visual Object Tagging Tool](https://github.com/microsoft/VoTT) (VoTT)?

This would accessible via "Tasks > Actions > Dump Annotations" and there would be a VoTT 2.2.0 option within this menu.

**Comment by bsekachev** [comment]
Hi @TomJamesAtDataSummit 

This is probably question for [Datumaro](https://github.com/openvinotoolkit/datumaro) project which is used internally to work with different formats. 
As you can see in this issue https://github.com/openvinotoolkit/datumaro/issues/137, there is VoTT format in the list.

**Comment by bsekachev** [comment]
Since VoTT is not maintained anymore, the issue is not relevant
