### ISSUE TITLE
Feature request: add tracking

### ISSUE THREAD

**Issue by kodonnell** [opencv/cvat#38]
It'd be great to add a tracking mode e.g. see video [here](https://www.pyimagesearch.com/2018/07/30/opencv-object-tracking/).

Specifically, if I enable tracking (per track) if there are no annotations in the future of the track, then attempt to track the last annotated box for all future frames. If the user goes to the next frame while one of these tracks is displayed, then this is considered as marking this as 'good', and it gets added as a key frame. Otherwise the user can edit it manually.

There are probably more UI considerations, but this would provide a lot of value. My use case is tracking people heads, and the standard interpolation is less useful (but still much better than without!) due to heads 'bobbing' while walking etc. Feature tracking would likely solve this in many situations (aside from when a head is occluded etc.).

Aside from UI considerations, this is pretty easy to implement. It can even be done in the browser with opencv.js (and suitable performance, depending on device).

**Comment by nmanovic** [comment]
Hi @kodonnell ,

I agree that in some cases it can be very useful feature. Need to add the feature in the future. If you can prepare a PR just let me know.

Previously we used tracking in other our annotation tools. The main problem that most of our annotation tasks required **precise** annotations which trackers could not give us. Even on your video you can see that results are very bad. Especially difficult to track non rigid objects (like human).

**Comment by kodonnell** [comment]
Thanks @nmanovic. I agree - tracking can be hard and won't work in all circumstances, especially if you need exact annotations. In our case, we're less interested in exactness, as we're more using it to say "is there a head there or not?" as opposed to the exact bounding box around the head.

FYI - I thought the results on the video were pretty good.

**Comment by bsekachev** [comment]
Duplicated #211
