### ISSUE TITLE
Implement cvat-core.js library

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#383]
CVAT will consist of 3 parts: server with REST API (https://github.com/opencv/cvat/issues/262), cvat.js library, lightweight UI (https://github.com/opencv/cvat/issues/271). Need to implement the javascript library which will implement core logic on client side. Draft specification for the API is attached.
[cvat_js.pdf](https://github.com/opencv/cvat/files/3058450/cvat_js.pdf)

**Comment by shubhham11111** [comment]
![Uploading crop.JPEG…]()
