### ISSUE TITLE
Remember what frame you were on

### ISSUE THREAD

**Issue by mrKallah** [opencv/cvat#3830]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I've had twice now that the website crashes when I am mid video, and I don't know exactly where I am, I think a good addition would be to either when you load back in have a 'continue from where you left' button or that it simply starts you where you left. 

### Expected Behaviour

For each time the frame is changed, use something like the google chrome local storage or a storage for the current user which stores the current frame. Thus if something were to happen, then you don't have to spend a lot of time trying to find your way back. 

### Current Behaviour

Currently you start on frame 0 which gives you no indication of where you left

### Possible Solution

Very rough idea for implementation: 
```js
//on load
storage = window.localStorage;
current_frame = int(localStorage.getItem('frame' + task_name));
jump_to_frame()

// on new frame
storage.setItem('frame' + task_name, current_frame);
```

### Context

I've had to look for where I was in the video after chrome tab crashed.

### Your Environment

- Git hash commit (`git log -1`): fb6305fff8801e6c56a1f671eb7416258c18ede2
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.9
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by ActiveChooN** [comment]
Suggestion with a "Continue from N frame" was implemented in https://github.com/openvinotoolkit/cvat/pull/4297. I will keep this PR open because of a memory issue.

**Comment by bsekachev** [comment]
Let's have another issue for memory leak if it still relevant..
