### ISSUE TITLE
404 not found when access through localhost 

### ISSUE THREAD

**Issue by longtth** [opencv/cvat#3835]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour

`cvat` should show up and work 

### Current Behaviour

It throw `404 page not found` when I access to http://localhost:8080 

![image](https://user-images.githubusercontent.com/1010849/139071373-1192d563-a2b9-4fc4-9fcf-3155bc94d0c9.png)
![image](https://user-images.githubusercontent.com/1010849/139071397-d5f5b5a6-4b99-4f69-9f11-71f13b563b5e.png)

### Steps to Reproduce (for bugs)

1. clone from github, checkout to tag `1.6.0` 
1. `~/cvat$ docker-compose up -d` 

### Context

I can't use cvat on this new computer at all 

### Your Environment

- Git hash commit (`git log -1`):

```
me@mypc~/cvat$ git log -1
commit 8d03ed7959632d6f3ffd76020ad577fa409acfcd (HEAD -> v1.6.0-branch, tag: v1.6.0, origin/master)
Merge: 56c9626a 476b2fcf
Author: Nikita Manovich <nikita.manovich@intel.com>
Date:   Fri Sep 17 14:22:09 2021 +0300

    Merge branch 'release-1.6.0'
```

- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.9, build c2ea9bc
- Are you using Docker Swarm or Kubernetes? No 
- Operating System and version (e.g. Linux, Windows, MacOS): ubuntu 20.04 
- Code example or link to GitHub repo or gist to reproduce problem: N/A 
- Other diagnostic information / logs:
  I don't know how to get logs from cvat container, is there any guide for it?

**Comment by ygl89** [comment]
I have the same issue when use cvat locally on my own PC.
http://localhost:8080/   return a 404 not found

**Comment by fenghan0430** [comment]
Rebooting can really solve the problem.😅😅😅
