### ISSUE TITLE
Task name character encoding a bit of a problem

### ISSUE THREAD

**Issue by wangzyon** [opencv/cvat#3871]
When I use "Dataset repository URL", the "Name" must be ASCII

![Dingtalk_20211105173806](https://user-images.githubusercontent.com/36832126/140490323-0379e09e-08fc-4a39-b843-021a719c2063.jpg)
![Dingtalk_20211105173835](https://user-images.githubusercontent.com/36832126/140490332-b205b292-e2ca-40d6-aecd-6b27eceedf09.jpg)

**Comment by nmanovic** [comment]
@wangzyon , thanks for the report.

**Comment by bsekachev** [comment]
Feature was removed
