### ISSUE TITLE
Assigning tasks to roles in CVAT 

### ISSUE THREAD

**Issue by keshavadk** [opencv/cvat#3889]
@VesninEN , OK. I will mark the issue as a bug. Too many users complain. But the problem here is only bad error handling. Indeed your user doesn't have permissions to create a task. To do that you need to go to "admin" panel and add necessary permissions to the new user (e.g. assign "user" group/role). Read here how to create the superuser: https://github.com/opencv/cvat#create-superuser-account

_Originally posted by @nmanovic in https://github.com/openvinotoolkit/cvat/issues/345#issuecomment-470395684_

**Comment by keshavadk** [comment]
If a newly created user is assigned to any group in admin panel and we were able to save . But when we logout and login again to the superuser account, the assigned group(for example : if a user is assigned to annotator group in admin panel) will be reverted back.

**Comment by nmanovic** [comment]
@keshavadk , are you using LDAP or Basic authentication?

**Comment by keshavadk** [comment]
For now , we are testing phase ,so we are using basic authentication. In future ,the requirement will  be LDAP.

**Comment by nmanovic** [comment]
@keshavadk , which CVAT version do you use? Could you please write a short video how to reproduce the problem?

**Comment by bsekachev** [comment]
I will close the issue for now. 
Do not hesitate to reopen if you have any updates.
