### ISSUE TITLE
Support OpenVINO 2019R*

### ISSUE THREAD

**Issue by fadeevla** [opencv/cvat#392]
$sudo docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build

fails with error below: (additionally to this I cannot find install_cv_sdk_dependencies.sh in l_openvino_toolkit_p_2019.1.094.tgz)

/tmp/components/openvino/install.sh: line 26: ./install_cv_sdk_dependencies.sh: No such file or directory
/tmp/components/openvino/install.sh: line 34: /opt/intel/computer_vision_sdk/bin/setupvars.sh: No such file or directory
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c if [ "$OPENVINO_TOOLKIT" = "yes" ]; then         /tmp/components/openvino/install.sh;     fi' returned a non-zero code: 1

**Comment by nmanovic** [comment]
Hi @fadeevla ,

It seems that you didn't put openvino package into corresponding directory. Please read the instructions: https://github.com/opencv/cvat/tree/develop/components/openvino.

**Comment by alalek** [comment]
OpenVINO 2019R1 has been migrated on new names:

```.diff
-install_cv_sdk_dependencies.sh
+install_openvino_dependencies.sh
```

**Comment by nmanovic** [comment]
@alalek , cool. I didn't know that. It seems we need to support that.

**Comment by nmanovic** [comment]
@fadeevla ,

There are two ways to continue. Right now you can use the previous version of OpenVINO or submit a PR to support the new one. The fix isn't very difficult.

**Comment by fadeevla** [comment]
@nmanovic ,
do you know if there is an OpenVINO archive, so I can download 2018 release?

**Comment by bsekachev** [comment]
@fadeevla 
You can choose 2018 R5 version on the download page.
![Selection_001](https://user-images.githubusercontent.com/40690378/56013651-85548900-5cfa-11e9-850f-b477511408b7.png)

**Comment by bsekachev** [comment]
PR have not decided problem. There are dependencies issues.

**Comment by fadeevla** [comment]
> @fadeevla
> You can choose 2018 R5 version on the download page.
> ![Selection_001](https://user-images.githubusercontent.com/40690378/56013812-407d2200-5cfb-11e9-885c-ab4bbf15cbc0.png)

@bsekachev 
strange, but the only option I have is 2019 R1. I'm using chrome/macos. the page looks exactly as your screenshot, one exception is version selection box is replaced with simple text Version: 2019 R1.

**Comment by alalek** [comment]
Looks like old version is not available for "new" OpenVINO users. /cc @moslex

**Comment by bsekachev** [comment]
@fadeevla 
Okay, in this case I can suggest you to use fixed version from [this](https://github.com/opencv/cvat/tree/bs/openvinoR5) branch. Installation with 2019R1 is successful here. ReID, Deep Extreme Cut, custom models must work. But unfortunately there are some issues with OpenVINO 2019R1 and TF Object Detector, thus detector can be inferred only with tensorflow framework (there aren't significant disadvantages, but ~4 times slower). 
We will close this issue when we fix it.
Thank you.

**Comment by nmanovic** [comment]
@bsekachev ,

As far as I understand the issue was closed by your PR (https://github.com/opencv/cvat/pull/400). I close the issue.
