### ISSUE TITLE
Open job without having to visit the task page

### ISSUE THREAD

**Issue by TOsmanov** [opencv/cvat#3929]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Related #3927

The task page is convenient in tasks where one large dataset is divided into equal parts, but if you need to mark up a large number of small videos you have to create one task for each video and for opening job need visit the task page accordingly. 

#### Statistics 
Such a page visit takes approximately 5 seconds if you need to annotation 500 videos visiting the task pages will take 42 minutes

### Expected Behaviour

Need a way to go from the project page or from tasks page to the job without having to visit the task page

For example:
- Separate button on the task UI element.
- Universal link for go to the first job in the task without knowing the jobs number:
  `https://cvat.org/tasks/123456/jobs/first` or something like that.
  It may also be worth adding a button to the menu to go to the next job.

### Current Behaviour

In cases where you need to mark a large number of small tasks, you have to go to the task page and then to the job or create links with using excel, which takes time. 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@TOsmanov , now you can open https://cvat.org/tasks/123456 and see all jobs. Why doesn't it work for you?

**Comment by TOsmanov** [comment]
> @TOsmanov , now you can open https://cvat.org/tasks/123456 and see all jobs. Why doesn't it work for you?

@nmanovic , this is working, but if I have a project consisting of several tasks with one job in each task, to open the job I need to visit the task page. The problem is that need to visit the task page. Need a way to go from the project page or from tasks page to the job without having to visit the task page, this will make it easier to work with a large number of small videos

**Comment by bsekachev** [comment]
Now we have ``jobs`` page. I will close the issue.
