### ISSUE TITLE
Info about datasets

### ISSUE THREAD

**Issue by bhargav-sudo** [opencv/cvat#3939]
Hi,
Why does annotation was not there on the downloaded dataset images ..?
Why the structure of datasets like market1510 , yolo ,pascal VOC etc.. in CVAT looks different when compare to original..?
Can we able to make the structure of datasets similar to the original one..?

Thanks.

**Comment by nmanovic** [comment]
@bhargav-sudo , thanks for your comments. Could you please describe in more details and give us a couple of examples? What is the difference?

**Comment by bhargav-sudo** [comment]
Hi,

lets take some of the dataset like Market-1510. 
When I downloaded the Market-1510 dataset from the online.
it has a folders of Train , test  etc..

I used CVAT tool for re-identification. First I had done detection and the re-identification using auto annotation.
When I downloaded that dataset from CVAT. The folder has only some images(save images from the Export dataset) and txt file. 

So, what's the difference here..?
and How can I make CVAT Market-1510 dataset into original one..?

Thanks.

**Comment by nmanovic** [comment]
@kirill-sizov , could you please look at answer?

**Comment by bhargav-sudo** [comment]
Hi guys,
any update..?

Thanks.

**Comment by kirill-sizov** [comment]
> Hi guys, any update..?
> 
> Thanks.

Hi, do you use Tag=`market-1501` during your annotation process in CVAT?

**Comment by bhargav-sudo** [comment]
Thanks for the reply @kirill-sizov.

Am new to this. where can i find that..?

**Comment by kirill-sizov** [comment]
If you want to get expected result of exporting into the Market-1501 you should use Label with value `market-1501` and attributes: `query`, `person_id`, `camera_id`. Particular use case for Market-1501 dataset it's when you have cropped images with people: one person per image. And after that using CVAT you can fill information about person for each image: `query`, `person_id`, `camera_id`. We implemented such logic based on original dataset.

It will be interesting to get more information about your use case: what kind of images do you have? what types of annotation objects did you try to use in CVAT for getting Market-1501 dataset?

**Comment by bhargav-sudo** [comment]
Thanks,

I just annotated the data with person detection and next with reidentification.
Then i exported the dataset from the option that you had provided.
I didn't attached any tags.

I want the dataset like you mentioned in above.

**Comment by bhargav-sudo** [comment]
First thing I want to know how to set these tags that you said in the above message.

Coming to our use case. We need the dataset from CVAT like the original one from the online.

**Comment by bhargav-sudo** [comment]
HI, Is this is the thing that you are trying to mention.
![Screenshot 2021-11-24 at 22-23-09 Computer Vision Annotation Tool](https://user-images.githubusercontent.com/57169077/143281491-cda37c7e-fc18-496d-815e-6151ffbfac17.png)

**Comment by kirill-sizov** [comment]
It's better to specify type for attributes, try to use this labels definition in Raw (instead of Constructor):
```json
[
  {
    "name": "market-1501",
    "color": "#e2c8c0",
    "attributes": [
      {
        "name": "person_id",
        "input_type": "number",
        "mutable": false,
        "values": [
          "0",
          "1000",
          "1"
        ]
      },
      {
        "name": "camera_id",
        "input_type": "number",
        "mutable": false,
        "values": [
          "0",
          "100", 
          "1"
        ]
      },
      {
        "name": "query",
        "input_type": "checkbox",
        "mutable": false,
        "values": [
          "true"
        ]
      }
    ]
  }
]
```

Also don't forget to change values for attributes `camera_id` and `person_id` according your dataset (convention for list of values: `"values"=["start", "stop", "step"]`)

Once you create a task with a label definition like this, you can annotate your images with tags, see the documentation to read more about this [here](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/annotation-with-tags/)  and about the attribute annotation mode [here](https://openvinotoolkit.github.io/cvat/docs/manual/basics/attribute-annotation-mode-basics/).

**Comment by bhargav-sudo** [comment]
Thanks @kirill-sizov. 
Will do this and let you know.

Am i correct like first detection and the reidentification..?
Thanks.

**Comment by bhargav-sudo** [comment]
HI @kirill-sizov 
It works.

I had a doubt what does the folder "query" called..?
How it get structured..? Does it selects one random photo from the video or it selects one random photo from one person (like 2 photos for 2 persons).

Does CVAT provides any option to crop the images. ? If not how can you crop them manually..?

Thanks.

**Comment by bhargav-sudo** [comment]
HI @nmanovic. I had tried adding my own dl models into nuclio.
CVAT uses openvino_2020.2 version of models. I modified the code to use other versions of openvino or other type of models in the same version. (like 0031 reidentiication model instead of 0300). 
I tried for detection models too. The function has deployed completely. 

![Screenshot from 2021-11-25 20-42-34](https://user-images.githubusercontent.com/57169077/143465995-d6e450ce-7163-4707-8c2e-e97bf041c373.png)

But it didn't got added to the list of CVAT models.
![Screenshot from 2021-11-25 20-46-19](https://user-images.githubusercontent.com/57169077/143466421-c4e11c32-f972-465a-a638-f930d8833f68.png)

Any reasons and how to solve it.?
Thanks.

**Comment by zhiltsov-max** [comment]
> I had a doubt what does the folder "query" called..?
> How it get structured..? Does it selects one random photo from the video or it selects one random photo from one person (like 2 photos for 2 persons).

You can find a simple explanation of query and gallery subsets in ReID context [here](https://www.researchgate.net/figure/In-traditional-person-re-identification-if-the-query-image-is-matched-to-a-wrong-target_fig3_261154753) and [here](https://cysu.github.io/open-reid/notes/evaluation_metrics.html). Basically, "query" subset means "identities to be classified".

**Comment by bhargav-sudo** [comment]
Thanks @zhiltsov-max.

So, for every person we have one query image to match with the gallery images.

**Comment by bhargav-sudo** [comment]
> HI @nmanovic. I had tried adding my own dl models into nuclio. CVAT uses openvino_2020.2 version of models. I modified the code to use other versions of openvino or other type of models in the same version. (like 0031 reidentiication model instead of 0300). I tried for detection models too. The function has deployed completely.
> 
> ![Screenshot from 2021-11-25 20-42-34](https://user-images.githubusercontent.com/57169077/143465995-d6e450ce-7163-4707-8c2e-e97bf041c373.png)
> 
> But it didn't got added to the list of CVAT models. ![Screenshot from 2021-11-25 20-46-19](https://user-images.githubusercontent.com/57169077/143466421-c4e11c32-f972-465a-a638-f930d8833f68.png)
> 
> Any reasons and how to solve it.? Thanks.

Hi. Any updates..?

Thanks

**Comment by bhargav-sudo** [comment]
> If you want to get expected result of exporting into the Market-1501 you should use Label with value `market-1501` and attributes: `query`, `person_id`, `camera_id`. Particular use case for Market-1501 dataset it's **when you have cropped images with people: one person per image. And after that using CVAT you can fill information about person for each image:** `query`, `person_id`, `camera_id`. We implemented such logic based on [original Market-1501 dataset](http://zheng-lab.cecs.anu.edu.au/Project/project_reid.html).
> 
> **It will be interesting to get more information about your use case: what kind of images do you have?** what types of annotation objects did you try to use in CVAT for getting Market-1501 dataset?

Hi @kirill-sizov we are still working on it. 
we are annotating on a video. And I am not able get the folders like query, gt_query, gt_bbox when we export the dataset into market-1501.
But as you mentioned before about cropping images. 
(like taking cropped images and attaching the labels or how can i do that..?)

**Comment by zhiltsov-max** [comment]
> But as you mentioned before about cropping images.
(like taking cropped images and attaching the labels or how can i do that..?)

Hi, you could crop images with Datumaro. How would you like to crop them? A fixed coordinates, by a bbox or something else? From the conversation above, I can assume, you would like to auto-annotate images with a model and then crop by a bbox, is it correct?

**Comment by bhargav-sudo** [comment]
Hi @zhiltsov-max 
Yes, you are correct. 
we need the data of person_reid to train the model.
And we need the that exported data in the market-1501 format where it has **query, gt_query, gt_bbox** these folder structure.

**Comment by bsekachev** [comment]
Sorry for lack of response from our side. There are too many issues opened. I am trying to reduce them now and I will close this issue. 

Please, if the question is still relevant, let us know and do not hesitate to reopen.
