### ISSUE TITLE
Error: Request failed with status code 502. "Bad Gateway".

### ISSUE THREAD

**Issue by isagastiberri** [opencv/cvat#3948]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I had CVAT running on a machine that unexpectedly shut down. Now, when I do the docker-compose up and I try to access it I get this errors 
![image](https://user-images.githubusercontent.com/56122555/143473215-b20c1851-f0c9-42fd-9404-cd7b73d200df.png)
We are not sure what is happening, maybe the app lost connection to the database but we don't understand why. Except for the up and down we have not changed anything from the docker-compose that was working earlier today.

I hope you can help us. Thanks a lot in advance

**Comment by leeyh20** [comment]
Hello, I am also facing the same issue. We have not changed any settings，in fact traefik reports that everything is fine. We checked the logs and there's nothing unusual with the logs. But no matter what settings we change, cvat still reports this error today. 

It only started happening today.

**Comment by azhavoro** [comment]
@isagastiberri Hi, please provide output of `docker ps` command and log file from cvat container `docker logs cvat > cvat.log`

**Comment by isagastiberri** [comment]
@azhavoro The output from docker ps:
![image](https://user-images.githubusercontent.com/56122555/143546354-8b5cb916-96f2-4ced-a72e-4a6d5aa656ee.png)

Also, find attached the logs from cvat
[cvat_server.log](https://github.com/openvinotoolkit/cvat/files/7607235/cvat_server.log)

Looking a bit at them I noticed that the last logs are from before it broke, I'm not sure why but there are no logs showing for after the shut down

**Comment by azhavoro** [comment]
@isagastiberri your log looks very strange... I only see a lot of decoding exceptions and no messages about server startup, try to run `docker-compose down` and `docker-compose up -d`. If that doesn't help, collect the logs again. Also I find `no space left on device` error, please make sure that you have some free space on your disk.

**Comment by isagastiberri** [comment]
Sorry, my mistake, I think I was looking at the wrong logs, here you can find attached the newer ones

**Comment by isagastiberri** [comment]
Sorry, I realized I wasn't looking at the correct logs, here you can find attached the newest ones, I just did a docker.compose down and up again.

[cvat_restart.log](https://github.com/openvinotoolkit/cvat/files/7607659/cvat_restart.log)

I do have enough space in the disk now, we solved that mistake. I've also done docker compose down and up several times before, as whenever we had this same error that was the way to solve it, but it's not working this time.

**Comment by azhavoro** [comment]
Seems something wrong with your database, please attach logs from postgres container as well: `cvat logs cvat_db > cvat_db.log`
Thanks.

**Comment by azhavoro** [comment]
> @azhavoro I'm facing similar issue, here is my logs from cvat_db
> 
> ```
> docker logs cvat_db --details
> 
>  PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
>  2021-12-01 13:29:22.723 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
>  2021-12-01 13:29:22.723 UTC [1] LOG:  listening on IPv6 address "::", port 5432
>  2021-12-01 13:29:22.725 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
>  2021-12-01 13:29:22.738 UTC [21] LOG:  database system was shut down at 2021-12-01 13:29:13 UTC
>  2021-12-01 13:29:22.744 UTC [1] LOG:  database system is ready to accept connections
>  2021-12-01 13:29:24.766 UTC [28] LOG:  incomplete startup packet
> ```

Your database is ok, please attach cvat container logs as well

**Comment by northanapon** [comment]
I have the same 502 Bad Gateway issue when I tried to upgrade CVAT today. I removed the old images and volumes before reinstalling them. 

I would like to provide logs:
- [cvat_db.log](https://github.com/openvinotoolkit/cvat/files/7761644/cvat_db.log)
- [cvat.log](https://github.com/openvinotoolkit/cvat/files/7761645/cvat.log)
- [traefik.log](https://github.com/openvinotoolkit/cvat/files/7761642/traefik.log)
- [cvat_ui.log](https://github.com/openvinotoolkit/cvat/files/7761643/cvat_ui.log)

**Comment by northanapon** [comment]
My issue was resolved.

My machine is behind an organization's proxy. Removing proxy setting from `.docker/config.json` and then restarting the docker (down and up) solves the problem.

**Comment by DP1701** [comment]
Hello all, i also get this error message, but I can still log in and use CVAT. 


![photo](https://user-images.githubusercontent.com/68444979/151809096-ac67d489-b650-4298-b8eb-64518aac6313.png)

To install CVAT, I followed the installation instructions for macOS Mojave ([link](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/)). The difference is that I modified the docker-compose.yml file (starting at line 110) and added the docker-compose.override.yml file. The goal is to store the CVAT data on an external disk and to have a share path for uploading. I have attached both files. Unfortunately I don't know why the error appears before the login. 

I currently have version 1.7.0 installed.

[docker-compose.yml.txt](https://github.com/openvinotoolkit/cvat/files/7971359/docker-compose.yml.txt)
[docker-compose.override.yml.txt](https://github.com/openvinotoolkit/cvat/files/7971360/docker-compose.override.yml.txt)

[cvat.log](https://github.com/openvinotoolkit/cvat/files/7971369/cvat.log)
[cvat_db.log](https://github.com/openvinotoolkit/cvat/files/7971371/cvat_db.log)
[cvat_ui.log](https://github.com/openvinotoolkit/cvat/files/7971373/cvat_ui.log)

**Comment by sinnud** [comment]
I met the same error for `develop` branch. Then I changed to CVAT with tag `v2.0.0-alpha` and the error disappeared. Looks the `develop` branch have extra code to raise this issue.

**Comment by sinnud** [comment]
@yustiks Looks `v2.0.0-alpha` is gone because `release-2.0.0` is ready. Wish this bug is gone.

**Comment by nmanovic** [comment]
@yustiks , please attach your logs.

**Comment by yustiks** [comment]
> @yustiks , please attach your logs.
![Screenshot 2022-02-28 at 18 12 58](https://user-images.githubusercontent.com/2270085/156142179-e010c7f8-ea5b-4f6e-b824-41aada45762d.png)

**Comment by yustiks** [comment]
> @yustiks , please attach your logs.

and 'docker ps'
![Screenshot 2022-03-01 at 10 29 45](https://user-images.githubusercontent.com/2270085/156142708-deca46f5-bd33-4b70-bcd8-70b0d14f4bd1.png)

**Comment by nmanovic** [comment]
@yustiks , could you please create a separate issue? I see an exception in UI but I believe it is not 502 bad gateway error. Right?

@bsekachev , could you please look at the exception? What can be a reason for that?

**Comment by bsekachev** [comment]
@nmanovic 

There was recent issue with similar exception #4388
The instance was incorrectly configured there.
Need to work with client-side logs and requests details, to say more.

**Comment by bsekachev** [comment]
I will close the issue for now. 
Do not hesitate to reopen if you have any updates.

**Comment by IyadElwy** [comment]
> My issue was resolved.
> 
> My machine is behind an organization's proxy. Removing proxy setting from `.docker/config.json` and then restarting the docker (down and up) solves the problem.

Dude! Thank you! This fixed it for me after 3 days of debugging.

**Comment by yunjunglab** [comment]
> My issue was resolved.
> 
> My machine is behind an organization's proxy. Removing proxy setting from `.docker/config.json` and then restarting the docker (down and up) solves the problem.

you are my hero!
