### ISSUE TITLE
How to group bounding boxes between different frames ? 

### ISSUE THREAD

**Issue by HaiNguyen2903** [opencv/cvat#3966]
Hi there, 
I'm trying to use the 'group' annotation mode in CVAT. This feature enable grouping different bounding boxes into one group in 1 frame. 

My problem here is that it seem like I can only group bounding boxes in the same frame. If I have 2 boxes appear in 2 different frames, for example 1 box at frame 1 and 1 box at frame 5, how can I group those into 1 group ? 

![image](https://user-images.githubusercontent.com/50733949/144066059-23eb47b0-fef4-412e-b35f-7b59845657fa.png)

**Comment by bsekachev** [comment]
Hi, @HaiNguyen2903 

Look at merge feature: https://openvinotoolkit.github.io/cvat/docs/manual/basics/track-mode-basics/

**Comment by zhiltsov-max** [comment]
Datumaro uses the same group ids as CVAT provides, so they are image-local as well, i.e. if 2 images have annotations with the same group ids, they are not considered in the same group by the tool (but, of course, in custom scripts you can use the format with any logics you wish). The thing you're talking about is more like `track_id`, because they represent grouping over multiple frames, but it also doesn't cover the situation completely, because it's supposed to represent a single instance across different frames. Could you describe your use case in more detail?

**Comment by HaiNguyen2903** [comment]
Hi @zhiltsov-max, thanks for replying me,
I used the **track_id** in my situation, and want to merge 2 different **track_id** in different frame. CVAT will work well if these 2 track_id are both appear in at least 1 frame, so I can group those in that frame. But in case these track_ids do not share similar frame, I cannot group the track_ids.
So I want to ask wether CVAT has any feature for this situation ? Or where can I adjust in the source code to adapt with this problem.
Thanks you so much.

**Comment by zhiltsov-max** [comment]
Probably, CVAT can't do exactly this now. One thing you can try is to replace all shapes with tracks, set proper values to `outside` properties of each track (probably, to be appearing just at one frame), and then join tracks into groups.
If you want to adjust some code, contact @bsekachev.

**Comment by HaiNguyen2903** [comment]
@zhiltsov-max Currently all of my rectangle boxes are defined as Track (not Shape). But can you explain more detail about your solution ? I'm not fully understand about how and where to set the proper values to ```outside```, and what to do next after that to group ids as I described above.
Thanks you so much.

**Comment by zhiltsov-max** [comment]
Please check the [user manual](https://openvinotoolkit.github.io/cvat/docs/manual/basics/track-mode-basics/). `Outside` can be toggled by this button: 
![image](https://user-images.githubusercontent.com/13832349/150106118-2b265968-7e38-4aeb-b7b5-157e1c31b01c.png)
Select 2 tracks and join them into a group. If you need to see hidden tracks to select them, you can enable their display in settings.

**Comment by HaiNguyen2903** [comment]
Oh my god, this idea really save me and solve the problem ! 
Basically, if I need to group 2 track_ids in different frame, I just need to create an extra track_id that appear at the same frame with track id 1, merge the extra track_id with the track id 2 (now these 2 track_id appear in at least 1 similar frame), then group those track id at that similar frame :D
Thank you so much ! I really appreciate that !
