### ISSUE TITLE
ppa:~mc3man/ubuntu/trusty-media ubuntu 16.04

### ISSUE THREAD

**Issue by zyxcambridge** [opencv/cvat#397]
**ppa:~mc3man/ubuntu/trusty-media 

not find in ubuntu 16.04
Processing triggers for dbus (1.10.6-1ubuntu3.3) ...
Cannot add PPA: 'ppa:~mc3man/ubuntu/xerus-media'.
ERROR: '~mc3man' user or team does not exist.
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -yq         python-software-properties         software-properties-common         wget &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         unzip         unrar         p7zip-full         vim &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

**Comment by nmanovic** [comment]
@zyxcambridge ,

Do you have proxy?

**Comment by nmanovic** [comment]
@zyxcambridge ,

I will close the issue. Don't hesitate to reopen it if you still have the issue. Also if you have more questions you can ask on our https://gitter.im/opencv-cvat channel.

**Comment by zyxcambridge** [comment]
> @zyxcambridge ,
> 
> Do you have proxy?

i use the proxy ，but which do not work 。 i am in china shanghai。

**Comment by venergiac** [comment]
same error

**Comment by RaphaelMagnee** [comment]
I am behind proxy and I have same error.
I am running this command to pass proxy info:
docker-compose build --build-arg http_proxy="http://myID:myPass@companyProxyIP:8080";https_proxy="http://myID:myPass@companyProxyIP:8080"
It gets all the ubuntu packages but then fails adding the PPA with exact same error message as above.

**Comment by feacluster** [comment]
> 
> 
> I am behind proxy and I have same error.
> I am running this command to pass proxy info:
> docker-compose build --build-arg http_proxy="[http://myID:myPass@companyProxyIP:8080";https_proxy="http://myID:myPass@companyProxyIP:8080](http://myID:myPass@companyProxyIP:8080%22;https_proxy=%22http://myID:myPass@companyProxyIP:8080)"
> It gets all the ubuntu packages but then fails adding the PPA with exact same error message as above.

I have the same issue. I am also behind a corporate proxy. I set the http_proxy same was as you. It works fine for everything except this step:  Cannot add PPA: 'ppa:~mc3man/ubuntu/xerus-media'.

**Comment by venergiac** [comment]
the work-around to me was to builld the image on docker-hub and changing the image on docker-compose

`    
      cvat:
       container_name: cvat
       image: venergiac/opencv-cvat:0.4.1` 

https://hub.docker.com/r/venergiac/opencv-cvat

**Comment by feacluster** [comment]
> 
> 
> the work-around to me was to builld the image on docker-hub and changing the image on docker-compose
> 
> ` cvat: container_name: cvat image: venergiac/opencv-cvat:0.4.1`
> 
> https://hub.docker.com/r/venergiac/opencv-cvat

Interesting. I am a newbie to docker. I tried to pull your image but got these errors:

[hussaif1@b34 cvat]$ docker pull venergiac/opencv-cvat
Using default tag: latest
Trying to pull repository registry.access.redhat.com/venergiac/opencv-cvat ...
Pulling repository registry.access.redhat.com/venergiac/opencv-cvat
Trying to pull repository docker.io/venergiac/opencv-cvat ...
Trying to pull repository registry.fedoraproject.org/venergiac/opencv-cvat ...
Pulling repository registry.fedoraproject.org/venergiac/opencv-cvat
Trying to pull repository quay.io/venergiac/opencv-cvat ...
Pulling repository quay.io/venergiac/opencv-cvat
Trying to pull repository registry.centos.org/venergiac/opencv-cvat ...
Pulling repository registry.centos.org/venergiac/opencv-cvat
Trying to pull repository docker.io/venergiac/opencv-cvat ...
manifest for docker.io/venergiac/opencv-cvat:latest not found

**Comment by feacluster** [comment]
I figured out how to build the docker image on another machine and upload it to docker-hub. But how do I run it. I tried:

[hussaif1@lustwzb34 ~]$ docker run -it -p 8080:8080 hussaif1/cvat
Error: Format string '%(ENV_HOME)s/wait-for-it.sh db:5432 -t 0 -- bash -ic \\\n"/usr/bin/python3 ~/manage.py migrate && \\\n/usr/bin/python3 ~/manage.py collectstatic --no-input && \\\nexec /usr/bin/python3 $HOME/manage.py runmodwsgi --log-to-terminal --port 8080 \\\n--limit-request-body 1073741824 --log-level INFO --include-file ~/mod_wsgi.conf \\\n%(ENV_DJANGO_MODWSGI_EXTRA_ARGS)s --locale %(ENV_LC_ALL)s"' for 'program:runserver.command' contains names ('ENV_DJANGO_MODWSGI_EXTRA_ARGS') which cannot be expanded. Available names: ENV_CUDA_SUPPORT, ENV_DEXTR_MODEL_DIR, ENV_DJANGO_CONFIGURATION, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_OPENVINO_TOOLKIT, ENV_PATH, ENV_REID_MODEL_DIR, ENV_TERM, ENV_TF_ANNOTATION, ENV_TF_ANNOTATION_MODEL_PATH, ENV_USER, ENV_WITH_DEXTR, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, process_num, program_name in section 'program:runserver' (file: 'supervisord.conf')
For help, use /usr/bin/supervisord -h

**Comment by Ai-is-light** [comment]
@feacluster have you solved your problem.
@venergiac would u mind telling us how to do it. thx
