### ISSUE TITLE
CUDA installation failed!

### ISSUE THREAD

**Issue by kingmacth** [opencv/cvat#398]
I want to use the GPU version of tf_annotation. So I modified docker-compose.tf_annotation.yml and added CUDA_SUPPORT: "yes". However, the following error will be reported. I have installed cuda 10 and cudnn7, and TensorFlow works fine.

`docker-compose -f docker-compose.yml -f components/tf_annotation/docker-compose.tf_annotation.yml build`
`train4@train4-System-Product-Name:~/cvat$ docker-compose -f docker-compose.yml -f components/tf_annotation/docker-compose.tf_annotation.yml build
cvat_db uses an image, skipping
cvat_redis uses an image, skipping
Building cvat
Step 1/48 : FROM ubuntu:16.04
 ---> 9361ce633ff1
Step 2/48 : ARG http_proxy
 ---> Using cache
 ---> b8a5d2ba665d
Step 3/48 : ARG https_proxy
 ---> Using cache
 ---> d9e8f75a481c
Step 4/48 : ARG no_proxy
 ---> Using cache
 ---> e2d761e3fcaa
Step 5/48 : ARG socks_proxy
 ---> Using cache
 ---> 9302c4edee70
Step 6/48 : ENV TERM=xterm     http_proxy=${http_proxy}       https_proxy=${https_proxy}     no_proxy=${no_proxy}     socks_proxy=${socks_proxy}
 ---> Using cache
 ---> 64d839395ba9
Step 7/48 : ENV LANG='C.UTF-8'      LC_ALL='C.UTF-8'
 ---> Using cache
 ---> 4287a14cea12
Step 8/48 : ARG USER
 ---> Using cache
 ---> 0068d16aa4b4
Step 9/48 : ARG DJANGO_CONFIGURATION
 ---> Using cache
 ---> 0ef7bfeef476
Step 10/48 : ENV DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}
 ---> Using cache
 ---> c2bb0f133b0f
Step 11/48 : RUN apt-get update &&     apt-get install -yq         python-software-properties         software-properties-common         wget &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         unzip         unrar         p7zip-full         vim &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 06d3d2e4575f
Step 12/48 : ENV USER=${USER}
 ---> Using cache
 ---> 1283b9459d40
Step 13/48 : ENV HOME /home/${USER}
 ---> Using cache
 ---> 8731a4d02f4f
Step 14/48 : WORKDIR ${HOME}
 ---> Using cache
 ---> 1f8c455bf5d1
Step 15/48 : RUN adduser --shell /bin/bash --disabled-password --gecos "" ${USER}
 ---> Using cache
 ---> 0c3cf2d1c694
Step 16/48 : COPY components /tmp/components
 ---> Using cache
 ---> de5a5522b493
Step 17/48 : ARG OPENVINO_TOOLKIT
 ---> Using cache
 ---> 25fb7e4bc8a9
Step 18/48 : ENV OPENVINO_TOOLKIT=${OPENVINO_TOOLKIT}
 ---> Using cache
 ---> 1b3790870c03
Step 19/48 : RUN if [ "$OPENVINO_TOOLKIT" = "yes" ]; then         /tmp/components/openvino/install.sh;     fi
 ---> Using cache
 ---> 1bac77d9b507
Step 20/48 : ARG CUDA_SUPPORT
 ---> Using cache
 ---> 731bb0283dd0
Step 21/48 : ENV CUDA_SUPPORT=${CUDA_SUPPORT}
 ---> Using cache
 ---> e9f64d04e53f
Step 22/48 : RUN if [ "$CUDA_SUPPORT" = "yes" ]; then         /tmp/components/cuda/install.sh;     fi
 ---> Running in 0e8883cd70c8
Executing: /tmp/tmp.VpJJxvBYbL/gpg.1.sh --fetch-keys
http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
gpgkeys: no key data found for http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: WARNING: unable to fetch URI http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub: bad public key
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [816 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [551 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [6121 B]
Get:10 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1211 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [963 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [19.1 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7942 B]
Get:18 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8532 B]
Fetched 15.8 MB in 20s (751 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cuda-cudart-10-0
E: Unable to locate package cuda-libraries-10-0
E: Unable to locate package libnccl2
E: Unable to locate package libcudnn7
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c if [ "$CUDA_SUPPORT" = "yes" ]; then         /tmp/components/cuda/install.sh;     fi' returned a non-zero code: 100`

**Comment by nmanovic** [comment]
@bsekachev , could you please look at the issue?

**Comment by bsekachev** [comment]
Hi,  @kingmacth 

You don't need modify any files in order to support CUDA. 
Just use next command for build:
```
docker-compose -f components/tf_annotation/docker-compose.tf_annotation.yml -f components/cuda/docker-compose.cuda.yml -f docker-compose.yml build
```

**Comment by bsekachev** [comment]
@kingmacth 

Please, let me know if you still have the problem. Otherwise we will close the issue.

**Comment by nmanovic** [comment]
@kingmacth , I will close the PR. Feel free to reopen it if you still have issues. Please don't modify code if you report an issue. We are not able to in the case.

**Comment by kingmacth** [comment]
@bsekachev    I used the following command:`docker-compose -f components/tf_annotation/docker-compose.tf_annotation.yml -f components/cuda/docker-compose.cuda.yml -f docker-compose.yml build`

The following error will occur:`The repository is setup! You can now install packages.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  git-lfs
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 5048 kB of archives.
After this operation, 12.6 MB of additional disk space will be used.
Get:1 https://packagecloud.io/github/git-lfs/ubuntu xenial/main amd64 git-lfs amd64 2.7.1 [5048 kB]
Err:1 https://packagecloud.io/github/git-lfs/ubuntu xenial/main amd64 git-lfs amd64 2.7.1
  GnuTLS recv error (-54): Error in the pull function.
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/pool/xenial/main/g/git-lfs/git-lfs_2.7.1_amd64.deb  GnuTLS recv error (-54): Error in the pull function.

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y ssh netcat-openbsd git curl zip  &&     wget -qO /dev/stdout https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash &&     apt-get install -y git-lfs &&     git lfs install &&     rm -rf /var/lib/apt/lists/* &&     if [ -z ${socks_proxy} ]; then         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30\"" >> ${HOME}/.bashrc;     else         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ProxyCommand='nc -X 5 -x ${socks_proxy} %h %p'\"" >> ${HOME}/.bashrc;     fi' returned a non-zero code: 100`

**Comment by guofenggitlearning** [comment]
@kingmacth sudo apt-get install ntp
