### ISSUE TITLE
Running on AWS EC2

### ISSUE THREAD

**Issue by oostap1** [opencv/cvat#4]
Was trying to run cvat on EC2 AWS and met an issue to access cvat from outside AWS. It was returning Bad requests: 400 all the time. Found solution to add EC2 instance public IP to ALLOWED_HOSTS in docker-compose.override.yml as specified in documentation. But it is not the nicests solution, every time IP changes I have to change that value. It would be great if someone with move AWS experience can provide more elegant solution. Thanks

**Comment by nmanovic** [comment]
Hi,

Could you please look at the documentation below? Try to specify a sub-domain or '*'. 

https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts

**Comment by oostap1** [comment]
Did try * that and got:

> _ERROR: yaml.scanner.ScannerError: while scanning an alias
>   in "./docker-compose.override.yml", line 6, column 22
> expected alphabetic or numeric character, but found '\n'
>   in "./docker-compose.override.yml", line 6, column 23_

'*' works !!!. Thanks

**Comment by imneonizer** [comment]
Access CVAT remotely via <HOST_IP>:port 
can anybody help i am trying to connect but it shows bad request 400 i didn't understood anything on this page: https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts
if anybody could help an easy way to do
i am new to linux.
