### ISSUE TITLE
How to run it without docker?

### ISSUE THREAD

**Issue by imistyrain** [opencv/cvat#41]
It's tedious to install docker and configure the settings, is there any way to run it directly?
After install lots library missed for django, I meet a problem:
ERRORS:
engine.Task: (auth.E005) The permission codenamed 'view_task' clashes with a builtin permission for model 'engine.Task'.
the script is:
    sudo python3 manage.py createsuperuser

**Comment by bsekachev** [comment]
Docker is simplest way to build the production server.
Also you can setup the debug environment without docker as described [here](https://github.com/opencv/cvat/blob/master/CONTRIBUTING.md). Debug server works slower. We haven't described problem in this instruction.

**Comment by imistyrain** [comment]
Thanks for quick response.
I have tried with your suggesttion, but found it also needs python3-venv, which was not able to install on my machine because of dependicy problems. So is there any way to run it directly?

**Comment by imistyrain** [comment]
Why it needs a special version of a libray? Such like numpy 1.14.2, scipy 1.0.1 .etc
I don't think it's good practice.

Another problem is that it uses VS code to run, is it really necessary?
After serval minutes of searching,I succeed to run it with the script:
python3 manage.py runserver --noreload --nothreading --insecure 127.0.0.1:7000

**Comment by 1329844541** [comment]
> Why it needs a special version of a libray? Such like numpy 1.14.2, scipy 1.0.1 .etc
> I don't think it's good practice.
> 
> Another problem is that it uses VS code to run, is it really necessary?
> After serval minutes of searching,I succeed to run it with the script:
> python3 manage.py runserver --noreload --nothreading --insecure 127.0.0.1:7000

Hello,I read your CSDN article about this,but I met a problem

>  https://blog.csdn.net/qq_26572229/article/details/83150120
and could you help me?I would be very thankful.

**Comment by penghaoxiao** [comment]
Run the following script:
python3 manage.py runserver --noreload --nothreading --insecure 127.0.0.1:7000

return:
[2021-06-04 06:11:56,566] INFO django.server: "GET / HTTP/1.1" 301 0
INFO - 2021-06-04 06:11:56,566 - basehttp - "GET / HTTP/1.1" 301 0
[2021-06-04 06:11:56,568] INFO django.server: "GET / HTTP/1.1" 301 0
INFO - 2021-06-04 06:11:56,568 - basehttp - "GET / HTTP/1.1" 301 0
[2021-06-04 06:11:56,569] INFO django.server: "GET / HTTP/1.1" 301 0
INFO - 2021-06-04 06:11:56,569 - basehttp - "GET / HTTP/1.1" 301 0
[2021-06-04 06:11:56,570] INFO django.server: "GET / HTTP/1.1" 301 0
INFO - 2021-06-04 06:11:56,570 - basehttp - "GET / HTTP/1.1" 301 0
[2021-06-04 06:11:56,571] INFO django.server: "GET / HTTP/1.1" 301 0
INFO - 2021-06-04 06:11:56,571 - basehttp - "GET / HTTP/1.1" 301 0
[2021-06-04 06:11:56,572] INFO django.server: "GET / HTTP/1.1" 301 0

Why can't I open the web page.
