### ISSUE TITLE
nference status for the task 2 is failed. requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations

### ISSUE THREAD

**Issue by pavanbalajin** [opencv/cvat#4108]
Hi I am facing above issue in CVAT Auto annotation setup, could you please help

internal log shows 

	Line 188: 22.01.04 08:53:48.069 .api/function_invocations (W) Failed to invoke function {"err": "Failed to send HTTP request", "errVerbose": "\nError - Post \"http://172.17.0.1:0\": dial tcp 172.17.0.1:0: connect: connection refused\n    /nuclio/pkg/platform/abstract/invoker.go:119\n\nCall stack:\nFailed to send HTTP request\n    /nuclio/pkg/platform/abstract/invoker.go:119\nFailed to send HTTP request", "errCauses": [{"error": "Post \"http://172.17.0.1:0\": dial tcp 172.17.0.1:0: connect: connection refused"}]}
	Line 188: 22.01.04 08:53:48.069 .api/function_invocations (W) Failed to invoke function {"err": "Failed to send HTTP request", "errVerbose": "\nError - Post \"http://172.17.0.1:0\": dial tcp 172.17.0.1:0: connect: connection refused\n    /nuclio/pkg/platform/abstract/invoker.go:119\n\nCall stack:\nFailed to send HTTP request\n    /nuclio/pkg/platform/abstract/invoker.go:119\nFailed to send HTTP request", "errCauses": [{"error": "Post \"http://172.17.0.1:0\": dial tcp 172.17.0.1:0: connect: connection refused"}]}

nuctl get function
====================================
pavan@DESKTOP-RFQODH7:~/cvat$ sudo nuctl get function
  NAMESPACE |              NAME              | PROJECT |  STATE   | NODE PORT | REPLICAS
  nuclio    | openvino-dextr                 | cvat    | ready    |     52994 | 1/1
  nuclio    | openvino-omz-public-yolo-v3-tf | cvat    | ready    |     54533 | 1/1
  nuclio    | tf-matterport-mask-rcnn        | cvat    | building |         0 | 1/1

docker logs cvat
===========================================================
2022-01-04 11:02:12,477 DEBG 'ssh-agent' stderr output:
debug1: process_add_identity: add ssh-rsa SHA256:6+YaXebkopRNs6FXutOetCTvsexQv/iA5FIF+DQ91xo "django@0a27847d39f0" (life: 0) (confirm: 0) (provider: none)

2022-01-04 11:02:12,482 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 11

2022-01-04 11:02:51,290 DEBG 'rqworker_low' stderr output:
INFO - 2022-01-04 11:02:51,290 - worker - low: __call__(cleanup=False, function=<cvat.apps.lambda_manager.views.LambdaFunction object at 0x7fb59ffaad60>, mapping={'person': 'person', 'car': 'car'}, max_distance=None, quality=None, task=2, threshold=None) (9243da79-b643-4e13-a23f-188f18f33ddb)

2022-01-04 11:02:51,291 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:02:51,291 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2022-01-04 11:02:51,303 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:02:51,302 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.

2022-01-04 11:03:21,305 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:03:21,304 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.

2022-01-04 11:03:22,019 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:03:22,019 - worker - Handling failed execution of job 9243da79-b643-4e13-a23f-188f18f33ddb

2022-01-04 11:03:22,024 DEBG 'rqworker_low' stderr output:
ERROR - 2022-01-04 11:03:22,023 - worker - Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 517, in __call__
    LambdaJob._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 375, in _call_detector
    annotations = function.invoke(db_task, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 206, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 76, in invoke
    return self._http(method="post", url='/api/function_invocations',
  File "/home/django/cvat/apps/lambda_manager/views.py", line 54, in _http
    reply.raise_for_status()
  File "/opt/venv/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 517, in __call__
    LambdaJob._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 375, in _call_detector
    annotations = function.invoke(db_task, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 206, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 76, in invoke
    return self._http(method="post", url='/api/function_invocations',
  File "/home/django/cvat/apps/lambda_manager/views.py", line 54, in _http
    reply.raise_for_status()
  File "/opt/venv/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations

2022-01-04 11:03:22,025 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:03:22,024 - worker - Invoking exception handler <function rq_handler at 0x7f713ebfca60>

2022-01-04 11:03:22,047 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:03:22,046 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2022-01-04 11:03:22,048 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:03:22,047 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2022-01-04 11:03:22,050 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:03:22,050 - worker - *** Listening on low...

2022-01-04 11:03:22,052 DEBG 'rqworker_low' stderr output:
DEBUG - 2022-01-04 11:03:22,052 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

pavan@DESKTOP-RFQODH7:~/cvat$
=============================================
pavan@DESKTOP-RFQODH7:~/cvat$ nuctl version
Client version:
"Label: 1.6.4, Git commit: 8a45e60d6a358497aecd6158f8bf0fb0120a4c40, OS: linux, Arch: amd64, Go version: go1.14.3"pavan@DESKTOP-RFQODH7:~/cvat$

**Comment by thangict210** [comment]
If you are using **WSL2**. You have to configure HttpTrigger port manually and cvat_cvat network. Also use latest version of Nuclio.

>   triggers:

    myHttpTrigger:
      maxWorkers: 2
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        port: 32768
        maxRequestBodySize: 33554432 # 32MB

>   platform:

    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
      network: cvat_cvat

**Comment by thangict210** [comment]
If you are using **WSL2**. You have to configure HttpTrigger port manually and cvat_cvat network. Also use latest version of Nuclio.

```
spec:
  ...
  triggers:
    myHttpTrigger:
      maxWorkers: 2
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        port: 32768
        maxRequestBodySize: 33554432 # 32MB

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
      network: cvat_cvat
```

**Comment by pavanbalajin** [comment]
> Nuclio

I am using latest version of Nuclio,
i have modified the function.yaml, located in pavan@DESKTOP-RFQODH7:~/cvat/serverless/openvino/omz/public/yolo-v3-tf/nuclio$ vi function.yaml

which port number need to be mentioned here, i am new could you please help
=========================
  triggers:
    myHttpTrigger:
      maxWorkers: 2
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        port: 8080
        maxRequestBodySize: 33554432 # 32MB

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
      network: cvat_cvat
"function.yaml" 133L, 4667C

**Comment by thangict210** [comment]
> nuclio | openvino-omz-public-yolo-v3-tf | cvat | ready | 54533 | 1/1

node port must be unique. try to use node port generated by Nuclio. Ex: 54533

**Comment by bsekachev** [comment]
Sorry for no response from our side for a long time, too many issues opened. 
If you still experiencing the issue, try the latest CVAT version. It should work.

For now I will close the issue, do not hesitate to reopen it :)
