### ISSUE TITLE
Unable to download project dataset in yolo format

### ISSUE THREAD

**Issue by thasin96** [opencv/cvat#4122]
### My actions before raising this issue
I have gone through this thread https://github.com/openvinotoolkit/cvat/issues/608. I am able to download multiple tasks in single file using project->export dataset option for COCO format. 

I have multiple tasks in train and validation subset. I want to download the whole project so that merging of the tasks will be automatically processed. To do that, the above thread suggests, using project-> export dataset option. USing the option, i am able to download coco format but when I try to export dataset in yolo format, dataset is not downloaded properly. The downloaded zip has `obj.data` and `obj.names`. 
 
### Expected Behaviour
It should download images and annotations in yolo format for all the tasks based on my subset similiarly how coco format is working. 

### Current Behaviour
Instead of downloading dataset, it downloads `obj.data` and `obj.names`.

### Steps to Reproduce (for bugs)
1. create multiple tasks in train and validation subset
2. Export dataset from projects
3. choose yolo format in the dialogue box

### Context
This will be really helpful. reference thread: https://github.com/openvinotoolkit/cvat/issues/608

### Your Environment
cvat.org

**Comment by zhiltsov-max** [comment]
Hi, try to name subsets as `train` and `valid`. YOLO only works with with these names. Please also look at this thread: https://github.com/openvinotoolkit/datumaro/issues/565.

**Comment by yasakova-anastasia** [comment]
It was fixed by https://github.com/openvinotoolkit/datumaro/pull/688
