### ISSUE TITLE
Develop visual indication for points annotation order

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#4123]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Ability to see the order of annotated points in cases when one object consists of several points and the annotation order of these points is important. 

### Current Behaviour

For example, here one face must be annotated with 5 points in the following order: left eye -> right eye -> nose -> left mouth corner -> right mouth corner:
![image](https://user-images.githubusercontent.com/45849884/148638781-c4c5fe9f-0f5c-44c7-92e5-c98275695b62.png)
But there is no visual indication of how these points were annotated, following the requested order or not. Therefore, there is no ability to verify that the markup is correct.

### Possible Solution

Add visual indication with information about annotation order. For example, it can be a small digit near each point.
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Let's use skeletons for such scenarious
