### ISSUE TITLE
Default pinned property

### ISSUE THREAD

**Issue by yisaienkov** [opencv/cvat#4177]
How can I set the pinned property to True by default?
Or maybe I can upload annotations to task with this property?

**Comment by bsekachev** [comment]
By default ``pinned`` is true only for polygons
There is no formal way to make it true for other types of shapes (except of code changing of course). 

Could you please clarify your use case?

**Comment by yisaienkov** [comment]
@bsekachev Thanks, I did it with code changing.

I have a lot of good boxes from the model, but a lot of them have incorrect labels. 
The task is only to correct the labels without changing the position of the boxes. 
But with a large number of boxes, sometimes they can easily moved.

**Comment by bsekachev** [comment]
Okay, got it. 

You also could try attribute annotation mode. 
![image](https://user-images.githubusercontent.com/40690378/150191636-8a7645f0-351a-458b-b551-41818e1adf3b.png)

There you can switch objects using Tab and setup a label at right sidebar. 

In standard view you can also bind labels to hotkeys (Ctrl + 1, 2, 3, ...) (if their count less than 11) and switch labels with hotkeys. 
![image](https://user-images.githubusercontent.com/40690378/150192181-b73fba96-18af-4232-bab6-573ae01b940c.png)

**Comment by yisaienkov** [comment]
Thanks but I try it and it's not so comfortable for my case :(
And I have a lot of checkboxes (multilabel classification) and in attribute annotation mode they show one by one, not altogether.
