### ISSUE TITLE
Unexpected behaviour with task `meta`

### ISSUE THREAD

**Issue by Sigura** [opencv/cvat#4179]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. Make `manifest.jsonl` with own order (not abc) on aws (2D images)
2. Add `manifest.jsonl` to cloud storage
2. Create tasks with same `manifest.jsonl`
3. In task creation form files in expected order (as in `manifest.jsonl`)
4. After creation file names show in abc order in "player"
5. But files shown as it is in `manifest.jsonl` file

Export to COCO mess too – file names and order.

This endpoint shown files in expected order:
`cloudstorages/{store_id}/content?manifest_path=manifest.jsonl`

But `tasks/{new-task-id}/data/meta` return abc order. (looks like abc)

I checked folder `/home/django/data/storages/{store_id}/{name}/manifest.jsonl` it has expected order

### Possible Solution

Let users make own order in `manifest.jsonl` and use it as it is

And restore it from manifest or form `request.data['server_files']`

Steps:

1. Remove all unexpected `sorted` from code

Found related:
 * [task.py#L281](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/task.py#L281)
 * [task.py#L129](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/task.py#L129)
 * [media_extractors.py#L126](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/media_extractors.py#L126)

2. Fix order after `serializer` creation

~~and I don't know why `data['server_files']` income reversed?!!~~

now I know why it may come in any order, because find the root of this evil

https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/views.py#L630

Because looks like serializer does not guaranties income order, is not it?

But it fixable there – just rebuild it if from `request.data['server_files']`.

### Your Environment
```
Author: Maria Khrustaleva <maya17grd@gmail.com>
Date:   Wed Dec 1 16:57:31 2021 +0300

    Remove key_file_path field (#3959)

    * Remove key_file_path field
    * fix
    * Update comparison
```

**Comment by Sigura** [comment]
I found cache
```
> docker exec -u root -it cvat_db sh
> psql -U root -d cvat
# select * from engine_image where path ilike '%{task/path}%' order by frame limit 12;
```

how I can safely clean it?

**Comment by Sigura** [comment]
But may be it's not a cache issue but unexpected sorting?

**Comment by Marishka17** [comment]
@Sigura, Hi, you can specify `Sorting method` in the advanced section of the task creation form. In your case, you can choose `Predefined` sorting.
See [here](https://openvinotoolkit.github.io/cvat/docs/manual/basics/creating_an_annotation_task/#sorting-method) for  details.

**Comment by Sigura** [comment]
> @Sigura, Hi, you can specify `Sorting method` in the advanced section of the task creation form. In your case, you can choose `Predefined` sorting. See [here](https://openvinotoolkit.github.io/cvat/docs/manual/basics/creating_an_annotation_task/#sorting-method) for details.

I know, but I think it's the wrong way.

CVAT can use a user-defined order in the manifest file, and then all those constructions do not need.

AND it's the matter! Bug with wrong frame order persists too.

**Comment by Marishka17** [comment]
> > @Sigura, Hi, you can specify `Sorting method` in the advanced section of the task creation form. In your case, you can choose `Predefined` sorting. See [here](https://openvinotoolkit.github.io/cvat/docs/manual/basics/creating_an_annotation_task/#sorting-method) for details.
> 
> I know, but I think it's the wrong way.
> 
> CVAT can use a user-defined order in the manifest file, and then all those constructions do not need.

The manifest file in the current implementation plays the role of a list of files in the cloud storage. And I believe that we should not limit the order of the files to the order in the manifest file.

> AND it's the matter! Bug with wrong frame order persists too.

I'll investigate it. Thanks.

**Comment by Sigura** [comment]
@gHerzmann I removed all sorting from source code  and fixed it in `request.data['server_files']` and rebuild images

Because do not understand why anybody need to setup it in another place than `manifest `
