### ISSUE TITLE
Status for tasks

### ISSUE THREAD

**Issue by kbegiedza** [opencv/cvat#4181]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I would like to see task/ latest job status on task list.

### Current Behaviour
1. Create task
2. Assign annotator
3. Assign reviewer
4. *labelling in progress*
5. request a review

annotator view:
![image](https://user-images.githubusercontent.com/8686134/149624175-f34c0c2b-f49c-47ff-bf83-27c25b4230b1.png)

### Possible Solution
It would be super helpful if instead of `pending` it will show status from latest job:

![image](https://user-images.githubusercontent.com/8686134/149624278-7800483f-ddb6-489d-9c49-19f710caf452.png)

With status visible on Tasks list we can streamline annotator workflow - annotate everything in 'annotation / pending' state, skip / wait if 'validation in progress'

**Comment by mrKallah** [comment]
It would also be great if it showed what stage of uploading the task it is at too, like "compressing 40%" or "uploading 32%" etc.

**Comment by bsekachev** [comment]
@kbegiedza

We are going to implement a list of jobs that are related to a user, because after [Identity Access Management](https://github.com/openvinotoolkit/cvat/pull/3788) implementation annotators are not able to see a task if they assigned only to jobs. Would it improve your pipeline?

**Comment by bsekachev** [comment]
> It would also be great if it showed what stage of uploading the task it is at too, like "compressing 40%" or "uploading 32%" etc.

That is interesting idea, could you please submit a dedicated issue?

**Comment by kbegiedza** [comment]
I belive it will @bsekachev , do we have any ETA for this list of jobs for annotator ?

**Comment by bsekachev** [comment]
The jobs page were implemented: https://github.com/opencv/cvat/pull/4258
It also includes advanced filtration features.
