### ISSUE TITLE
Wrong thumbnails for video in the Project Task

### ISSUE THREAD

**Issue by DanLuoNEU** [opencv/cvat#4204]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When I added the 12th task in one project, the thumbnail for the task is not from the exact video. At the same time, the sort order of tasks is in a chaos.

### Expected Behaviour

The thumbnails for tasks should be right and tasks are sorted as the created order.

### Steps to Reproduce (for bugs)

1. add 12 video tasks for one project
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):

commit 182d941fadc7bb1001336dbca08b89c51b281bbb (HEAD -> develop, origin/develop, origin/HEAD)
Author: wartek69 <alextcher@hotmail.com>
Date:   Mon Jan 17 20:56:58 2022 +0100

    Added YOLOv5 serverless function for auto labeling (#4178)
    
    * added yolov5 serverless function for auto labeling
    * updated CHANGELOG.md
    
    Co-authored-by: Alex <aleksander.chernyavskiy@seafar.eu>

- Docker version `docker version` (e.g. Docker 17.0.05):

Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:36 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by Marishka17** [comment]
Hi @DanLuoNEU, Could you please try the latest CVAT version and check if this problem is still reproduced or not? I guess the problem with sorting absence was fixed.

**Comment by DanLuoNEU** [comment]
> Hi @DanLuoNEU, Could you please try the latest CVAT version and check if this problem is still reproduced or not? I guess the problem with sorting absence was fixed.

Thanks for the reply. But I think it is fixed a long time ago with the updates.
