### ISSUE TITLE
Disable Export dataset option to user 

### ISSUE THREAD

**Issue by NarenZen** [opencv/cvat#4209]
Export dataset option should be visible only to Admin not to the user.

Because users can download the dataset to their local computer, it can cause data leaks and privacy issues.

**Comment by bsekachev** [comment]
Hi, Do you want a user to have access to a task (I suppose the user is assigned to the task in this case, right?), but at the same time does not have access to exporting features?

**Comment by NarenZen** [comment]
Exactly. Only admin can have the option to "Export Dataset".

**Comment by bsekachev** [comment]
You can try to assign users (who are not supposed to be able to export datasets) not to tasks, but to jobs. In this case they will not be able to export dataset for the whole task as far as I know. 

@nmanovic can correct me if I am wrong.
