### ISSUE TITLE
Upload progress bar

### ISSUE THREAD

**Issue by mrKallah** [opencv/cvat#4214]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

It would be great if it showed what stage of uploading the task it is at, like "compressing 40%" or "uploading 32%" etc. Where it now sais pending and has a gray/green bar, it would be nice if that was a progress bar for the upload/processing so you could A have some indication if the task has frozen and B have some indication of how far along the process is. Originally posted in #4181, @bsekachev asked for a standalone post

### Expected Behaviour
Show some indication of the tasks upload/process progress from the UI, if, for-example you leave the upload page or you upload using CLI. 

### Current Behaviour
No way to tell progress

### Possible Solution
Using the % of upload / processing displayed to user on the upload page, show that in the progress bar on the task progress bar. 

### Steps to Reproduce (for bugs)
Upload task via CLI
Go to tasks in Web UI
Click show hidden
No progress indication available\ for hidden tasks 

### Context
It would be nice to know how far away from finishing to upload a large file, its just convenience. 

### Your Environment

- Git hash commit (`git log -1`): Not avaliabe, away from office for a few days
- Docker version `docker version` (e.g. Docker 17.0.05):Not avaliabe, away from office for a few days
- Are you using Docker Swarm or Kubernetes?Not avaliabe, away from office for a few days
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem: 
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Covered by https://github.com/opencv/cvat/commit/b50b275e0bed602be3648fea7cc57e395c196e54
