### ISSUE TITLE
Top-level (label, not instance) attribute support

### ISSUE THREAD

**Issue by matt-deboer** [opencv/cvat#4217]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

It would be useful to have attributes that could be applied to every label in a project, specifically so that they could be used in filters, and import/export from/to dataset formats that have label-level attributes (such as COCO). Currently, filters treat attributes of the same name (on different labels) as different, and they cannot be filtered together.

### Expected Behaviour

For example, suppose I created a "supercategory" or "parent" attribute on a label; and then I would like to filter objects/labels where "supercategory" == "machine" or something like this, and I want to see all of the different labels that have "supercategory" attribute of "machine" or "animal", etc. 
Or suppose I create a top-level True/False attribute of `is_keypoint` which would allow me to hide the keypoint attributes when I'm not doing keypoint annotation. 
Or suppose I want to create an arbitrary named grouping of labels...

### Current Behaviour
There is no concept of global attribute applicable to all labels.

### Possible Solution
Create a top-level "attributes" data entity at the project level.

**Comment by bsekachev** [comment]
For you case I would suggest to use complex filters, conjuncted with ``Or``:

![image](https://user-images.githubusercontent.com/40690378/188726074-effd3e0a-24fd-4741-afb9-0148b85200e0.png)

to find specific attributes value within multiple labels. 
If it does not work for you, let us now.

We do not have ``global`` attributes in our roadmap, so, I will close the issue for now. 
Do not hesitate to reopen if you are ready to contribute, we will be happy to help
