### ISSUE TITLE
get some info message

### ISSUE THREAD

**Issue by xiongda777** [opencv/cvat#4232]
I want get job-info-total of all jobs,but its inefficient to views each job page.how can I get them from cvat_db？

**Comment by bsekachev** [comment]
It is not stored in the database, but computer automatically from the information about all the shapes/tracks/tags. 
This information can be fetched from API endpoint: /api/v1/tasks/<id>/annotations.

**Comment by bsekachev** [comment]
I will close the issue for now. 
Do not hesitate to reopen if you have any updates.
