### ISSUE TITLE
Update PostgreSQL till 14.1

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#4245]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible Solution

Current version of PostgreSQL is 10. It is still supported but the new version works faster and it has some features which helps us to implement testing system for REST API: https://github.com/openvinotoolkit/cvat/pull/4090. For example, `FORCE` option for `DROP DATABASE`. Also re-creating database from a template database is twice faster.

1. Need to update docker-compose.yml
2. Need to write a document how to migrate cvat_db volume. There are several ways. One easy way is to use dump/restore https://jlelse.blog/dev/migrate-postgres-docker. Probably it can be optimized using `-Fc` option and `-j` for restore. Another way is to try `pg_update` tool: https://github.com/tianon/docker-postgres-upgrade/tree/master/10-to-14. The approach should be faster but it will have more steps. Probably we can describe both ways. For most of users the easiest way is preferable.
3. Need to migrate data on our internal server using the instruction above
4. Need to migrate data on cvat.org using the instruction above.

**Comment by azhavoro** [comment]
Currently using postgres:15-alpine
