### ISSUE TITLE
Exporting rotated bboxes loses angle

### ISSUE THREAD

**Issue by dreambit** [opencv/cvat#4250]
When exporting rotated bbox to yolo format, angle is not included

**Comment by zhiltsov-max** [comment]
Hi, thanks for reporting. Could you please explain in more detail, which output is expected?

**Comment by bsekachev** [comment]
As far as I remeber, angle is exported only in CVAT format. In other rotated rectangles are transformed to polygons.

**Comment by dreambit** [comment]
@zhiltsov-max Hi, for yolo, I think, expected is angle as the last parameter, like class, x, y, w, h, angle

**Comment by dreambit** [comment]
> As far as I remeber, angle is exported only in CVAT format. In other rotated rectangles are transformed to polygons.

for coco - angle is included in exported json

**Comment by zhiltsov-max** [comment]
Is is a conventional format which is supported by any frameworks?

**Comment by dreambit** [comment]
it is not yet supported, but we are planning to add angle to yolo detector, angle will be represented as -1 .. 1, (like -180..180)

**Comment by bsekachev** [comment]
Probably the same issue #4745

I will close as a duplicate. Please, follow to above issue.
