### ISSUE TITLE
Serverless functions not deployed: image created, but not starting in docker, just keeps restarting

### ISSUE THREAD

**Issue by KonstantinLS** [opencv/cvat#4262]
# Serverless functions not deployed: function image is created, but can't start in docker, just keeps restarting

### My actions before raising this issue
- [x] Read/searched [Semi-automatic and Automatic Annotation](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)
- [x] Searched 3629 and alike(/issues)

Hi, I've got local cvat from https://github.com/openvinotoolkit/cvat.git install on Windows 10 Pro, WSL2 with Ubuntu, Docker Desktop latest, nuctl-1.5.16-linux-amd64, all seems to be in full accordance with installation docs

cvat is OK on localhost:8080
nuclio is OK on localhost:8070, cvat project is created OK in nuclio

Try to deploy with below commands in WSL command line:
```
nuctl deploy --project-name cvat \
  --path serverless/openvino/dextr/nuclio \
  --volume `pwd`/serverless/common:/opt/nuclio/common \
  --platform local
``` 
or
```
./deploy_cpu.sh openvino/dextr/
```
results in error:
```
Error - fork/exec /opt/nuclio/common/openvino/python3: no such file or directory
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:231

Call stack:
Can't run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:231
Failed to run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:106
Failed to start runtime
    /nuclio/pkg/processor/worker/factory.go:101
Failed to create worker
    /nuclio/pkg/processor/worker/factory.go:122
Failed to create workers
    /nuclio/pkg/processor/worker/factory.go:132

    /nuclio/pkg/platform/local/platform.go:1001
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:182
  NAMESPACE |      NAME      | PROJECT | STATE | NODE PORT | REPLICAS
  nuclio    | openvino-dextr | cvat    | error |         0 | 1/1
```

the function image is actually created. function appears in Docker Desktop dashboard,  tries to start and then goes to restart again, and keeps restarting until above error is returned in WSL CLI. Function also appears in Nuclio dashboard with error status under cvat project
the same behavior for all functions, not DEXTR only

Is it possible to deploy serverless functions on local Windows installation?

I've read many of similar cases but neither work or applicable

Thank you very much for your help!

**Comment by irisitystefannilsson** [comment]
Hello, if you have checked out cvat using git on windows there is a possibility you've got the wrong kind of EOL in the python3 script.
You can check this by:
$ file serverless/common/openvino/python3
If it returns:
serverless/common/openvino/python3: Bourne-Again shell script, ASCII text executable, with CRLF line terminators
you have windows line-endings in the file. Fix this by running
$  dos2unix serverless/common/openvino/python3
dos2unix: converting file serverless/common/openvino/python3 to Unix format...

**Comment by bsekachev** [comment]
@CHENGW4 

Have you checked ``EOL`` solution?

**Comment by bsekachev** [comment]
I will close the issue for now, please do not hesitate to reopen if you are ready to continue discussion

**Comment by vividzhang** [comment]
I have the same problem. My OS is ubuntu 18.04(x86_64), I can open python3 terminal directly
![image](https://user-images.githubusercontent.com/21956027/199873711-b4860320-860a-4648-98ce-4aca804ca0c5.png)

**Comment by vividzhang** [comment]
![image](https://user-images.githubusercontent.com/21956027/199873823-ca000170-8e7f-409f-8465-b16f58aa6772.png)

**Comment by vividzhang** [comment]
Alright, my command is [nuctl deploy --project-name cvat --path "./serverless/openvino/omz/public/mask_rcnn_inception_resnet_v2_atrous_coco/nuclio" --platform local], no --volume param, add [--volume `pwd`/serverless/common:/opt/nuclio/common] param, solved.
