### ISSUE TITLE
Use more robust python package management system instead of pip (Poetry, ...)

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#4270]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Using pip as a package manager has many issues with dependency resolution which we are faced before. Poetry has some advantages here. https://python-poetry.org/

**Comment by lozhn** [comment]
but poetry can shoot you in the face :(

**Comment by breznak** [comment]
I can help with transition to poetry if wanted

**Comment by zhiltsov-max** [comment]
@breznak, it would be great! Please send us a PR with Poetry and also look at #4633.

**Comment by azhavoro** [comment]
Fixed https://github.com/opencv/cvat/pull/6048
