### ISSUE TITLE
Use multiple GPUs for automatic annotation

### ISSUE THREAD

**Issue by jpapon** [opencv/cvat#429]
The Tensorflow Object Detection component only uses a single GPU, queuing tasks on it.
It would be great if it assigned tasks to all available GPUs.

**Comment by tealeeseng** [comment]
load_image_into_numpy() is slow in cvat/cvat/apps/tf_annotation/views.py 
likely due to "np.array(image.getdata())"
==============================
def load_image_into_numpy(image):
    (im_width, im_height) = image.size
    return np.array(image.getdata()).reshape((im_height, im_width, 3)).astype(np.uint8)


try
=====================================
def load_image_into_numpy_array_perf(image):
    test = np.asarray(image)
    return test

**Comment by DefUs3r** [comment]
Hi @nmanovic could you let me know if I can work on this and make this my next PR?

**Comment by bsekachev** [comment]
I do not think this request is relevant
With nuclio you may deploy serverless functions on different GPUs
