### ISSUE TITLE
Could not create the task. ffmpy.FFRuntimeError

### ISSUE THREAD

**Issue by ionyshch-prismsl** [opencv/cvat#43]
Built docker image from the latest sources. Created superuser. Getting an error on task creation:

> Could not create the task. ffmpy.FFRuntimeError: `ffmpeg -i /home/django/data/2/.upload/20170209T193000.000000Z.mp4 -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 /tmp/cvat-p9csbe_h.data/%d.jpg` exited with status 1 STDOUT: STDERR: 

<img width="1436" alt="screen shot 2018-09-05 at 16 22 23" src="https://user-images.githubusercontent.com/24312265/45098739-49d35a00-b12e-11e8-9baf-a52121d71360.png">

Connected to running cvat container with `docker exec -it <container id> /bin/bash` and pasted command from error message into terminal. It fails, because folder cvat-* in /tmp doesn't exist.

**Comment by ionyshch-prismsl** [comment]
Seems problem is with video file. After I manually created destination folder, got another error:  Invalid pts (16) <= last (16). 
When omitting all parameters except input and output `ffmpeg -i <input file> %d.jpg` got output, but with dozen of warnings from ffmpeg

> Past duration xxxxxxx too large

Thus workaround in similar situation would be to convert video into images locally and upload images.

**Comment by bsekachev** [comment]
FFPMEG just can't process you video file. I don't know reason. You can try to convert it to other video format for example. Also you can send me it for my investigation.

**Comment by nmanovic** [comment]
Hi @ionyshch-prismsl ,

Thanks for your report. We are not going to support "bad" videos. Your suggests are correct. Just convert the video into another format or upload images directly.
