### ISSUE TITLE
Difficulties in installing docker-compose

### ISSUE THREAD

**Issue by movetheglobe** [opencv/cvat#430]
Hi! I am running the docker-compose comand, and I am running into an error. ERROR: Cannot locate specified Dockerfile: Dockerfile

Any suggestions.

**Comment by nmanovic** [comment]
Probably you run docker-compose in a wrong directory or your clonned version of cvat repository is corrupted. Could you please ask your questsions here: gitter.im/opencv-cvat. I will close the issue for now. I'm ready to answer on your other questsions on our gitter channel.
