### ISSUE TITLE
Serverless / Automatic Annotation Installation Error (BUG)

### ISSUE THREAD

**Issue by naufalahnaf17** [opencv/cvat#4312]
### My actions before raising this issue
hey, guys I just wondering about this error, is there a step that I'm missing while deploying the model using nuctl. 

### Expected Behaviour
20.07.17 12:05:23.377                     nuctl (I) Deploying function {"name": ""}
20.07.17 12:05:23.378                     nuctl (I) Building {"versionInfo": "Label: 1.4.8, Git commit: 238d4539ac7783896d6c414535d0462b5f4cbcf1, OS: darwin, Arch: amd64, Go version: go1.14.3", "name": ""}
20.07.17 12:05:23.590                     nuctl (I) Cleaning up before deployment
20.07.17 12:05:23.694                     nuctl (I) Function already exists, deleting
20.07.17 12:05:24.271                     nuctl (I) Staging files and preparing base images
20.07.17 12:05:24.274                     nuctl (I) Building processor image {"imageName": "cvat/openvino.omz.public.yolo-v3-tf:latest"}
20.07.17 12:05:24.274     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.4.8-amd64"}
20.07.17 12:05:27.432     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/uhttpc:0.0.1-amd64"}
20.07.17 12:05:31.462            nuctl.platform (I) Building docker image {"image": "cvat/openvino.omz.public.yolo-v3-tf:latest"}
20.07.17 12:05:32.798            nuctl.platform (I) Pushing docker image into registry {"image": "cvat/openvino.omz.public.yolo-v3-tf:latest", "registry": ""}
20.07.17 12:05:32.798            nuctl.platform (I) Docker image was successfully built and pushed into docker registry {"image": "cvat/openvino.omz.public.yolo-v3-tf:latest"}
20.07.17 12:05:32.798                     nuctl (I) Build complete
20.07.17 12:05:35.452                     nuctl (I) Function deploy complete {"httpPort": 57308}

### Current Behaviour
![Screenshot from 2022-02-10 10-38-54](https://user-images.githubusercontent.com/49228747/153332756-c0e6ab14-30ae-4f3c-aa0c-374f6308d8a8.png)

### Steps to Reproduce (for bugs)
1.nuctl create project cvat
2.nuctl deploy --project-name cvat \
    --path serverless/openvino/dextr/nuclio \
    --volume `pwd`/serverless/common:/opt/nuclio/common \
    --platform local
3.step no 2 working fine
4.nuctl deploy --project-name cvat \
    --path serverless/openvino/omz/public/yolo-v3-tf/nuclio \
    --volume `pwd`/serverless/openvino/common:/opt/nuclio/common \
    --platform local
5. i got problem with step no 4

### Context

Development working fine without models deploy , but I cant try the auto annotation which I think this is very usefull

### Your Environment

- Python 3.8
- Nuclio 1.5.16
- Docker 20.10.12
- Ubuntu 20

**Comment by naufalahnaf17** [comment]
@bsekachev

**Comment by atekoa** [comment]
Same issue

**Comment by dheerajvarma24** [comment]
Is there any update on this bug. I am facing the same issue with WSL2 on windows 11. 
Openvino is giving an error while converting yolo to IR representation.
