### ISSUE TITLE
A question of tensorflow

### ISSUE THREAD

**Issue by 5658www638** [opencv/cvat#432]
May I ask you a question?I used win10 to install the GPU version of TensorFlow successfully, and also ran for several days, suddenly these days do not work, there is "Fail to load the native Tensorflow runtime". CUDA and cuDNN certainly no problem because I managed to run the convolution neural network. You have no good solution, I have looked for a lot of information, can not work.

**Comment by nmanovic** [comment]
Hi @5658www638, please use our gitter channel for such questions: gitter.im/opencv-cvat. I have no answer on your question. Probably somebody from CVAT community will help. I will close the issue for now.
