### ISSUE TITLE
How to upload a task from a video with annotations?

### ISSUE THREAD

**Issue by evekeen** [opencv/cvat#4325]
Use case:
* There is a video file with an object that needs to be annotated with a bbox
* Person A and Person B both have independent local CVAT instances
* Person A creates a task from the video file and makes annotations
* Person A dumped the annotations into a file (e.g. in COCO format)
* Person B imports the annotations to their instance for review and corrections

There is a way of importing annotations along with a video through CLI/REST, although the annotations have frame_XXX references, and the upload only works with a set of images.
Is there a way of creating a task via CLI using a video file and the dumped annotations?

So far I managed to split video into images first and then upload as image sequence. But then zoom always resets in the UI, since it interprets the task as per-image, which actually is not true. And I cannot guarantee that my image sequence is the same as it was at the other person instance.

**Comment by bsekachev** [comment]
Hi, What you need is probably backup/restore of a task.
Please, refer to user guide: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/backup/ 

You can disable "Reset zoom" (enabled by default for images): 
![image](https://user-images.githubusercontent.com/40690378/153544679-f68b1766-0c79-4848-aae9-91ed749bac16.png)

There is related bug #4289, but generally it works

**Comment by evekeen** [comment]
Thank you for response! How do I enable backup on my instance? I don't the menu item
Server version: 1.7
Core version: 3.17.0
Canvas version: 2.8.0
UI version: 1.25.0

**Comment by bsekachev** [comment]
@evekeen 

Why can't you build it? Usually we publish docker images when releases come.

**Comment by evekeen** [comment]
@bsekachev its just tricky to set everything up on Mac with Apple processor in order to build. 
BTW when I tried the feature on cvat.org, the image quality went significantly down after re-import. Is there a setting about keeping the image quality somewhere?

**Comment by bsekachev** [comment]
@evekeen 

I am not sure I understand what kind of re-import you are talking about. Could you please clarify the scenario? If it is true, it might be a bug,  because I don't expect image quality degradation after any kind of import.

**Comment by evekeen** [comment]
@bsekachev the scenario is following:
1. Backup a task
2. Import the task from the backup on the same instance
3. Compare image quality of 2 tasks

In the imported task quality is significantly worse

**Comment by bsekachev** [comment]
@evekeen Are you able to provide a couple of screenshots with these images? If image quality is actually worse, better to submit a new issue with the scenario you provided and these screenshot, because as I told before, I suspect it is just a bug

**Comment by evekeen** [comment]
@bsekachev I've created an issue: https://github.com/openvinotoolkit/cvat/issues/4377
