### ISSUE TITLE
Mac users not able to load jobs where compressed_chunk_type = video

### ISSUE THREAD

**Issue by katab** [opencv/cvat#4329]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Mac users in my team, contrary to them using PC, are not able to enter certain video jobs. The page keeps loading forever and I get the following error from the console:

download.worker.js:24 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'status')
    at download.worker.js:24:40

I checked the database and realized that the tasks in question were videos where the compressed_chunk_type is video rather than imageset. My issue/question is why Mac users don't seem to be able to enter jobs where the compressed_chunk_type is video? 

As I understand it, the compressed_chunk_type will be imageset if the "Use zip chunks" is checked while creating the task, and video otherwise. However, the "Use zip chunks" option is not yet available in the CLI. I think you have merged this feature to master so I guess it will be available in next release? Still, I would like to be able to enter all jobs from all computers despite compressed_chunk_type.

### Expected Behaviour

All users, Mac as well as PC, should be able to enter all jobs despite compressed_chunk_type. 

### Current Behaviour

Mac users are not able to enter jobs in a video task where the compressed_chunk_type is video instead of imageset. 

### Steps to Reproduce (for bugs)

1. Create a task from video data and don't check the "Use zip chunks" option (such that the compressed_chunk_type is video rather than imageset).
2. Use a PC.
3. Enter the created task and click on one of the jobs.
4. The job will load and you will see the job interface and be able to annotate, review etc. 
5. Then use a Mac instead.
6. Enter the same task and click on one of the jobs.
7. Realise that the job never stops loading and you don't see the job interface. 

### Context

Some people are not able to reach some jobs. We want to be able to reach all jobs despite computer and compressed_chunk_type. 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@AlexeyAlexeevXperienceAI 

Since you are the only person has MAC, can you please check this issue? :)
