### ISSUE TITLE
Not able to call any newly added file through href/onClick

### ISSUE THREAD

**Issue by SteveChalissery** [opencv/cvat#4339]
![Screenshot (932)_LI](https://user-images.githubusercontent.com/74970484/153833448-9ec51ac5-a29d-4918-ac21-febfe004f1a0.jpg)
as you can see in this pic. I am able to change headers,add new buttons and all  ,  but i want to call new files
and when i add my file path in ""href"" it doesn't work  . the page just refresh.

i dont know if it is a restriction or what

i am using Docker Desktop for opening CVAT

can somone tell me how to call files( React.js) in this CVAT?

**Comment by bsekachev** [comment]
@SteveChalissery 

There are not any restrictions. I don't have any ideas why your button is not clickable, but if you share your code changes, it might be helpful.

**Comment by bsekachev** [comment]
I can only suggest you that CVEF is a correct type. If it is used for onClick callback, it must be a function. 
And I am not sure that your import the JavaScript file to TypeScript project is correct.
