### ISSUE TITLE
Cannot use Organizations feature (introduced in issue #3788) after installation using Docker

### ISSUE THREAD

**Issue by lmtri1998** [opencv/cvat#4350]
Hi, I followed the steps to install using Docker 20.10.12 on my macOS 11.6 and Ubuntu 20.04 (using both the develop branch and the  v2.0.0-alpha release. However, I was unable to find the organization tabs and features (Issue #3788). May I asked if there are any extra steps in order to deploy and use these functionality on my own machine? Thank you
![WhatsApp Image 2022-02-16 at 4 24 54 PM](https://user-images.githubusercontent.com/33169300/154234573-a65afdf1-8bd3-4ed8-9f33-55eb2fdf8026.jpeg)
!

**Comment by bsekachev** [comment]
Did you add ``-f docker-compose.dev.yml`` when build docker images?

**Comment by lmtri1998** [comment]
Thank you for your reply! I was abled to build it successfully with the Organizations feature. However, the Worker/Annotator user was still able to export the datasets. I only want the Supervisor or the Maintainer to be able to export the datasets. Are these types of restrictions available in this version yet ? Is there anyway to disable the export feature for Worker ?

**Comment by bsekachev** [comment]
Hi, We provide basic permission configuration which is correct from our point of view and corresponds to our goals.
But users can change the permissions as they want. To do that, they need to modify .rego files in ``cvat/apps/iam/rules/`` and restart ``cvat_opa`` docker service.
@nmanovic probably can tell more about it.
And probably it is a good idea to add one more FAQ item @azhavoro

**Comment by nmanovic** [comment]
@lmtri1998 , please look at https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/tasks.csv As you can see, `Owner, Project:owner, Assignee, Project:assignee` can export a dataset. If your worker or annotator are assigned on the task, they can. To change that, you can modify https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/tasks.rego
