### ISSUE TITLE
Detection error occured: When using the custom detector model on an image (> 10MB)

### ISSUE THREAD

**Issue by ZaibanAli** [opencv/cvat#4352]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)

### Expected Behaviour

The custom detector model should wait for the response back no matter how long the custom model (nuclio) takes to respond back.

### Current Behaviour

The deployed custom model works fine on small images or when the time it takes to respond back is small. But when I annotate a bigger image (normally takes 3 mins to respond), I get "Detection error occurred  {Error: Request failed with status code 504}" on the frontend. However, the inference is still in process on the backend (verified by seeing system/memory utilization).

### Possible Solution

On the frontend the CVAT should wait for the response back from nuclio. The event timeout defined in function.yaml should be used instead on CVAT internal timeouts (if any).

### Steps to Reproduce (for bugs)

![CVAT stuck in loading on frontend](https://github.com/ZaibanAli/cvat/blob/za/develop/site/issues/Screenshot%202022-02-15%20at%2023.12.12.png)
![CVAT Detection error occured on frontend](https://github.com/ZaibanAli/cvat/blob/za/develop/site/issues/Screenshot%202022-02-15%20at%2019.05.50.png)

1. To produce this error deploy a custom detector with a response back time of 3 mins (can be simulated with time.sleep())

### Context

Due to this, I am unable to use my own model for debugging purposes and improvement on CVAT. Further, I cannot leverage the automatic labeling functionality of CVAT,  thus I am stuck with old inefficient ways.

### Your Environment

- Git hash commit (`61787ce749c105bd5aab0d5046ad95b5349918a2`):
- Docker version `20.10.12`:
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): `Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0 x86_64)`
- Code example or link to GitHub repo or gist to reproduce problem: [Custom Detector Code](https://github.com/ZaibanAli/cvat/tree/za/develop/serverless/tensorflow/crack_detection/nuclio)
- Other diagnostic information / logs:

2022-02-16 12:36:42,843 DEBG 'runserver' stderr output:
[Wed Feb 16 12:36:42.842527 2022] [wsgi:error] [pid 2708:tid 139936564872960] [remote ] [2022-02-16 12:36:42,842] ERROR django.request: Gateway Timeout: /api/v1/lambda/functions/tf-crack-detection-v0.0.1
[Wed Feb 16 12:36:42.842704 2022] [wsgi:error] [pid 2708:tid 139936564872960] [remote ] ERROR - 2022-02-16 12:36:42,842 - log - Gateway Timeout: /api/v1/lambda/functions/tf-crack-detection-v0.0.1

**Comment by bsekachev** [comment]
> The custom detector model should wait for the response back no matter how long the custom model (nuclio) takes to respond back.

It is against of serverless function concept which should be quick. 
Maybe we will get rid of nuclio in the future, but no actions are planned to fix the behavioud you described, you can try to increase timeout manually.
