### ISSUE TITLE
How to actually load data into a shared directory

### ISSUE THREAD

**Issue by bogflap** [opencv/cvat#436]
I know this is not specific to CVAT but how do I use docker to include a shared directory to contain images. Also how do I use docker to stop it including the shared directory. A final point. I assume that CVAT will resize images in the shared directory as required so I can put images of any size into the shared directory

**Comment by nmanovic** [comment]
@bogflap , could you please use our https://gitter.im/opencv-cvat/public channel four such questions? Information how to use docker together with shared directory you can find here: https://github.com/opencv/cvat#share-path. CVAT doesn't resign images on server. It scales images your browser. You can upload images of different size.

I will close the issue. As I said please use our gitter channel to submit new questions. We use issues only for bugs and feature requests.
