### ISSUE TITLE
Create task with git repository 

### ISSUE THREAD

**Issue by LeDuySon** [opencv/cvat#4365]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour 
Create a task with github repository for synchronizing task https://openvinotoolkit.github.io/cvat/docs/manual/advanced/task-synchronization/

### Context

I'm trying to create new task with a git repository using cli https://openvinotoolkit.github.io/cvat/docs/manual/advanced/cli// but it always shows error that "format" key is missing. When i dont create task with github repository, everything works fine. 

### Your Environment

- Code example or link to GitHub repo or gist to reproduce problem:
```
subprocess.call([
            'python', 'cvat/utils/cli/cli.py', \
            "--auth", auth_account, \
            "create", task_name, \
            "--labels", '[{"name": "person"}]', \
            "--project_id", str(args.project_id), \
            "--dataset_repository_url", "https://github.com/LeDuySon/BackupDataset", \
            "--annotation_format", "CVAT 1.1", \
            "local", video_path
            ])
```
- Other diagnostic information / logs:
![image](https://user-images.githubusercontent.com/33374938/154788577-44adc5fd-5a12-40f4-aaec-0975b6832b8b.png)
![image](https://user-images.githubusercontent.com/33374938/154789189-36852ca9-0e53-484e-92a9-e80a2f11e4f2.png)

**Comment by bsekachev** [comment]
@zhiltsov-max Does SDK cover creating tasks with attached git repos?

**Comment by zhiltsov-max** [comment]
Hi, yes, it does. Both SDK and CLI.
