### ISSUE TITLE
Share disk and analytics monitoring doesn't work

### ISSUE THREAD

**Issue by Jakubelo** [opencv/cvat#4382]
### My actions before raising this issue
I did the steps, which is:
-export of CVAT_HOST, ACME_EMAIL
- run ` docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.https.yml -f docker-compose.override.yml -f components/analytics/docker-compose.analytics.yml build`
- run `docker-compose up -d`

### Expected Behaviour
Working and visible share disk, and available option Analytics.
![image](https://user-images.githubusercontent.com/55293845/155351372-da10cf5b-ef4d-496a-83d6-425f6de9e739.png)

![image](https://user-images.githubusercontent.com/55293845/155351278-37ae7ca0-4c02-45d1-bd49-88bff25221de.png)

### Current Behaviour
The docker is starting containers without errors. Errors only within first display of UI, I get 502 error (If you want an attached pic, please tell me)

[cvat.log](https://github.com/openvinotoolkit/cvat/files/8125635/cvat.log)
[cvat-inspect.log](https://github.com/openvinotoolkit/cvat/files/8125636/cvat-inspect.log)

### Your Environment

- Git hash commit (`git log -1`):  1e44b961aca8f4dd5f82480ea997c9d5e9d49965
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu ec2 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Your log file looks ok,
I suggest try to solve the issue step by step, could you try to run CVAT without analytics and https compose configs firstly?

**Comment by Jakubelo** [comment]
@azhavoro Okay, so i did `docker-compose down` then rebuild with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.override.yml build --no-cache` the override has only share mount config. I have to say I don't know, whether I rebuild image without https and analytics config.

When I did `docker-compose up -d`, all containers were created:
```
Creating network "cvat-safeway_cvat" with the default driver
Creating cvat_redis ... done
Creating cvat_opa   ... done
Creating traefik    ... done
Creating cvat_db    ... done
Creating cvat       ... done
Creating cvat_ui    ... done
```

But when I want login to UI I get following errors:


```Could not get user agreements from the server
Error: Request failed with status code 502. "Bad Gateway".
Could not login on the server
Error: Request failed with status code 502. "Bad Gateway".
```

**Comment by azhavoro** [comment]
Without logs I cannot help you, please attach logs from cvat container at least

**Comment by Jakubelo** [comment]
@azhavoro Yes I uploaded file to previous message

**Comment by bsekachev** [comment]
I hope you solved the issue. Will close it as outdated. Please, do not hesitate to reopen if still relevant.
