### ISSUE TITLE
Refactor dataset_repo app on server to use DRF and OPA

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#4386]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible Solution

At the moment REST API for dataset_repo doesn't correspond our guidelines: https://github.com/openvinotoolkit/cvat/blob/eac5b60d9b3b316d1ec7875b5a525813d507ab87/cvat/apps/dataset_repo/urls.py#L11

Also it is not protected by IAM: https://github.com/openvinotoolkit/cvat/blob/eac5b60d9b3b316d1ec7875b5a525813d507ab87/cvat/apps/dataset_repo/views.py#L39. In many cases only logic_required decorator is used and some functions use old permissions system (which was deleted).

**Comment by nmanovic** [comment]
@Marishka17 , refactoring of REST API need to start from the issue.

**Comment by bsekachev** [comment]
The app was removed, not relevant
