### ISSUE TITLE
export a range of few tasks

### ISSUE THREAD

**Issue by GintonD** [opencv/cvat#4395]
### My actions before raising this issue

- [ ] Searched simialr ussues

### Expected Behaviour
i want to export a range of few tasks by one click

### Current Behaviour
now, i can export single task or single project

### Possible Solution
possiblity of select wanted tasks for exporting and then click "export dataset tasks"

**Comment by azhavoro** [comment]
Why the project exporting is not working in this case?

**Comment by bsekachev** [comment]
I will close the issue, since there is not response.
Do not hesitate to reopen if you have any more thoughts about it.
