### ISSUE TITLE
Load and refine existed third party label

### ISSUE THREAD

**Issue by mszuyx** [opencv/cvat#4405]
Hi, the CVAT team!

I really love the features in CVAT and how intuitive they are, great job!

For my project, I already generated some auto labels using a simple neural network model. But I would like to refine/clean up these existing labels using CVAT. Is there a way to do that? (The labels are for a semantic segmentation task)

If so, can you point me to an example/tutorial?

Thanks!
Yu

**Comment by bsekachev** [comment]
Hello, thank you for your positive feedback and sorry for long response from our side.

You can generally make an annotation file in one of suitable formats, create a task with the images, and upload the annotation file to the task. After that you can refine annotations somehow and get annotations back, by exporting them.
