### ISSUE TITLE
Release v2.0.0 the annotator can also download data

### ISSUE THREAD

**Issue by fanasite** [opencv/cvat#4441]
version Release v2.0.0
![2022-03-11_13-04_1](https://user-images.githubusercontent.com/101313505/157809916-c7cbf356-2b9c-4fc3-93fa-72dfe703c55e.png)

I make a super users，names admin123
and make a common users, names worker01
![2022-03-11_11-25](https://user-images.githubusercontent.com/101313505/157809898-784cdda2-c0d6-4313-b6d8-d97b7bc08b80.png)

use super users admin123 make an organization
invite worker01 as a Worker member
![2022-03-11_11-26](https://user-images.githubusercontent.com/101313505/157809878-58501e6d-67bb-449b-adf1-b65675ff2fd9.png)

use super users admin123 create a task，assigned to worker01
![2022-03-11_13-04](https://user-images.githubusercontent.com/101313505/157809854-f1914bb2-e676-40d8-8feb-796ca07a0a15.png)

then login out admin123， login in worker01，choose the task
export task dataset
![2022-03-11_13-06](https://user-images.githubusercontent.com/101313505/157809819-61de288e-46d3-4a62-b0d5-761cf37c187a.png)

it look export data successful
![2022-03-11_13-06_1](https://user-images.githubusercontent.com/101313505/157809785-b57af3b0-c297-47b7-a040-7f5ba8c614cf.png)

it can look the task belong to
![2022-03-11_13-10](https://user-images.githubusercontent.com/101313505/157809763-ea568960-c47e-4770-8c35-c660428d5eb2.png)

**Comment by nmanovic** [comment]
@fanasite , it is by design. Please look at permissions in the file (look at export:dataset scope): https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/tasks.csv

If you see how to improve the default choice, let me know.

**Comment by fanasite** [comment]
> @fanasite , it is by design. Please look at permissions in the file (look at export:dataset scope): https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/tasks.csv
> 
> If you see how to improve the default choice, let me know.

so, I can understand it, didn't solve this issue https://github.com/openvinotoolkit/cvat/issues/3318?

the assignee also can download dataset.

**Comment by nmanovic** [comment]
@fanasite , an assignee for a job cannot download the dataset. It was the fix. An assignee for a task is a person, who is responsible for the task. Basically it is the owner's delegate to manage the task (including the ability to download the dataset). If you don't need to have an assignee for a task, just reset the field. Also you can easily fix these permissions if you don't like the default behaviors. Just modify https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/tasks.rego as needed and restart OPA container.

**Comment by fanasite** [comment]
> 



> @fanasite , an assignee for a job cannot download the dataset. It was the fix. An assignee for a task is a person, who is responsible for the task. Basically it is the owner's delegate to manage the task (including the ability to download the dataset). If you don't need to have an assignee for a task, just reset the field. Also you can easily fix these permissions if you don't like the default behaviors. Just modify https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/tasks.rego as needed and restart OPA container.

ok, I try to change tasks.rego this file.

before
![2022-03-16_10-37](https://user-images.githubusercontent.com/101313505/158505780-487e0ce8-2f0f-487e-98f1-ae59e1bb68a9.png)

I delete [utils.EXPORT_DATASET]  [utils.EXPORT_ANNOTATIONS]  [utils.EXPORT_BACKUP]
![2022-03-16_10-36](https://user-images.githubusercontent.com/101313505/158505935-f2befb15-6b45-4795-b62c-657a3fb3c3e6.png)

then restart OPA container, use worker01 login in cvat

successful, worker01 cannot download dataset.
![2022-03-16_10-34](https://user-images.githubusercontent.com/101313505/158508030-8ad1d6ec-4256-4c93-b1ea-5d651faf0c8c.png)

thank very much!

**Comment by nmanovic** [comment]
@fanasite , just for your information. The change delete rights for other people as well (e.g. the task owner).
