### ISSUE TITLE
Future of CVAT Development in Russia

### ISSUE THREAD

**Issue by dketterer** [opencv/cvat#4444]
In the context of the war of Russia against Ukraine, I am wondering if Intel Corporation will keep development in Russia and what that means for CVAT since the main contributors from Intel are located in Russia.

I think it would be good to have a statement about this. I think the community might want to know as early as possible if something changes.

**Comment by nmanovic** [comment]
@dketterer , no plans to change something. We are working on the next version of CVAT which should add critical features for our world wide community. I will keep you posted.

I will close the issue as invalid.

**Comment by dketterer** [comment]
I don't think this is "invalid" but very much a concerning issue. Intel has [suspended operations in Russia](https://www.intel.com/content/www/us/en/newsroom/news/russia-business-statement.html). Maintainers and developers have mostly [stopped contributing](https://github.com/openvinotoolkit/cvat/graphs/contributors?from=2022-02-01&to=2022-05-30&type=c).

I do not expect concrete answers how development will continue as this may concern the safety of some people but for now it seems the development and maintenance is interrupted.

**Comment by nmanovic** [comment]
@dketterer ,

**Comment by nmanovic** [comment]
@dketterer , please send your questions to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope they will help and answer.

**Comment by nmanovic** [comment]
@dketterer , CVAT.org should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is supported by CVAT core team. Please try our new repository: https://github.com/cvat-ai/cvat

**Comment by bsekachev** [comment]
The code development team now is international. 
Hope it answers your issue, so, I will close it.
