### ISSUE TITLE
[Bug] CLI task create call fails when the project is under an organization

### ISSUE THREAD

**Issue by neumannjan** [opencv/cvat#4449]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

When I issue a POST call to `/api/tasks` to create a task under a certain project, it doesn't allow me to create it under the organization that the project belongs to, even though I, as the task creator, am part of said organization. (I used the CLI and also tried it in Swagger)

### Expected Behaviour

`python cli.py --auth [...] create --project_id 2 [...]` should succeed when project with the supplied ID is under an organization that the user is authorized to create tasks for. 

### Current Behaviour

The above call fails with status code 400 and the following error:

```
The task and its project should be in the same organization.
```

### Steps to Reproduce (for bugs)

1. Create an organization
1. Create a user that isn't the owner of the orgnaization. Make them staff.
1. Use `cli.py` to create a task for the project from the non-owner user

**Comment by pedrofrodenas** [comment]
Yes, I have the same problem. Calling  api/tasks with POST method does not allow to include a organization, but when you use GET method the organization field is included. I can't upload tasks via API when the project_id is under a organization.
When the task is created using the Browser UI selecting a organization it can be created but using the API not.

**Comment by nmanovic** [comment]
Please add `?org=slug` where slug is the slug for your org in corresponding API calls. Also it is possible to use X-Organization HTTP header. We are going to improve the documentation and provide some python SDK in the future.

https://github.com/openvinotoolkit/cvat/blob/be334fdee95563b54c011290ffa6b4bbf9fd4296/cvat/apps/iam/views.py#L31

**Comment by neumannjan** [comment]
While the REST API supports this, `cli.py` lacks the support for this, but it should support it as well.

**Comment by kimSooHyun950921** [comment]
as explained above,
The cli code was executed by changing the code as shown below.
```python
    with requests.Session() as session:
        session.headers.update({'X-Organization':'org name'})
        api = CVAT_API_V2('%s:%s' % (args.server_host, args.server_port), args.https)
        cli = CLI(session, api, args.auth)
        try:
            actions[args.action](cli, **args.__dict__)
        except (requests.exceptions.HTTPError,
                requests.exceptions.ConnectionError,
                requests.exceptions.RequestException) as e:
            log.critical(e)
```

**Comment by Stanley-Michael** [comment]
@kimSooHyun950921 please could you elaborate on what code was changed to the code you have provided, and to what post above explained this

**Comment by SpecLad** [comment]
In the next release, the CLI will have an `--organization` option, which you can use to set the organization in which the task will be created (see #6317).

I'm not considering this issue fixed, though, since I think it would be useful for CVAT to automatically determine the organization when the task is linked to a project. That will need to be implemented in the server, rather than the CLI.

**Comment by hetfmt** [comment]
The problem is the same when working with the Python high-level SDK.
Should I create a new bug report, or will the above update to the CLI also address the problem with the Python high-level SDK?

**Comment by SpecLad** [comment]
@hetfmt You can do this with the SDK already; just need to set the organization context. See <https://opencv.github.io/cvat/docs/api_sdk/sdk/highlevel-api/#users-and-organizations>.

**Comment by hetfmt** [comment]
@SpecLad Excellent! Thank you! I just tested it, and it works like a charm :-)
