### ISSUE TITLE
CVAT <> Adding users

### ISSUE THREAD

**Issue by MohamadHam** [opencv/cvat#4458]
Hello ,  could you please let me know how to add a specific user to a specific **project** in CVAT tool?

I have many projects and I need to add my client to the related project.

Thanks!

**Comment by ningjunwei2** [comment]
Can you click admin page to go to the admin page？

**Comment by bsekachev** [comment]
Try to use ``Organizations`` feature.
Create an organization, invite this person to the organization (with the corresponding role), using email and within the organization create a project.

To know more about organizations, please follow this link: https://opencv.github.io/cvat/docs/manual/advanced/organization/

**Comment by davodogster** [comment]
@bsekachev Is that feature fully functional? right now I had to upgrade all my users to admin so they can view the tasks.

**Comment by bsekachev** [comment]
@davodogster 

Users must have ``maintainer`` role in an organization to see all the resources of the organization. 
They do not need to have ``admin`` role in CVAT.

**Comment by rkube** [comment]
I'm having issues adding users on our cvat instance. Wheh I try to add them I get the error
```
Error: Request failed with status code 400. ["You cannot invite an user with user@host email. It is not a valid email in the system."].
```

What should I put for `user@host` here?

**Comment by bsekachev** [comment]
@rkube 

It means that this email is not registered in CVAT platform.

**Comment by DJRIZZ** [comment]
This is probably a foolish question, so forgive me in advance for asking: does the organization feature work for CVAT run locally rather than the web-based version? The option to create an organization and invite users is included with the desktop version, but I don't see how it would work when run locally. Thanks for your input.

**Comment by Meryemama** [comment]
> This is probably a foolish question, so forgive me in advance for asking: does the organization feature work for CVAT run locally rather than the web-based version? The option to create an organization and invite users is included with the desktop version, but I don't see how it would work when run locally. Thanks for your input.

Same question...

**Comment by mbspng** [comment]
Could we please get an answer to this? Does it work or not? The documentation is lacking here. I have got the local client to SEND an invitation mail, and it actually arrives, by modifying `cvat/settings/base.py` with this code

```
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "<...>@gmail.com"
EMAIL_HOST_PASSWORD = "<app password>"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 10
```

and settings up a Gmail account with an "app password" for this, but the invitation email that arrives in non-functional. When pressing the accept button to end up at `example.com` and there are also not invitations arriving at the recipient's local CVAT client... well, how should they... So... Can this be made to work or not?? If so, documentation needs to be updated.

**Comment by Mickeyyyang** [comment]
> Could we please get an answer to this? Does it work or not? The documentation is lacking here. I have got the local client to SEND an invitation mail, and it actually arrives, by modifying `cvat/settings/base.py` with this code
> 
> ```
> EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
> EMAIL_HOST = "smtp.gmail.com"
> EMAIL_PORT = 587
> EMAIL_HOST_USER = "<...>@gmail.com"
> EMAIL_HOST_PASSWORD = "<app password>"
> EMAIL_USE_TLS = True
> EMAIL_USE_SSL = False
> EMAIL_TIMEOUT = 10
> ```
> 
> and settings up a Gmail account with an "app password" for this, but the invitation email that arrives in non-functional. When pressing the accept button to end up at `example.com` and there are also not invitations arriving at the recipient's local CVAT client... well, how should they... So... Can this be made to work or not?? If so, documentation needs to be updated.

DO you solve this problem?

**Comment by mbspng** [comment]
> > Could we please get an answer to this? Does it work or not? The documentation is lacking here. I have got the local client to SEND an invitation mail, and it actually arrives, by modifying `cvat/settings/base.py` with this code
> > ```
> > EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
> > EMAIL_HOST = "smtp.gmail.com"
> > EMAIL_PORT = 587
> > EMAIL_HOST_USER = "<...>@gmail.com"
> > EMAIL_HOST_PASSWORD = "<app password>"
> > EMAIL_USE_TLS = True
> > EMAIL_USE_SSL = False
> > EMAIL_TIMEOUT = 10
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and settings up a Gmail account with an "app password" for this, but the invitation email that arrives in non-functional. When pressing the accept button to end up at `example.com` and there are also not invitations arriving at the recipient's local CVAT client... well, how should they... So... Can this be made to work or not?? If so, documentation needs to be updated.
> 
> DO you solve this problem?

Did you mean "Did you solve this problem?" ? No I did not. I gave up on CVAT entirely. Buggy mess.
