### ISSUE TITLE
Renaming a task in the project does not affect subset name in the exported dataset

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#4462]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

Renaming a task should rename the subset.

### Current Behaviour

If I create a project from a dataset with multiple subsets and then rename a task, the subset name is not changed. It seems, there is no way to change the subset name now.

![image](https://user-images.githubusercontent.com/13832349/158333491-b8739407-2ae7-4788-947d-94137c46963b.png)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

Exporting in YOLO requires specific subset names ("train", "valid"). If I want to rename a subset, I can't.

### Your Environment

- UI version: 1.36.0
- Git hash commit (`git log -1`): 
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@zhiltsov-max 

![image](https://github.com/opencv/cvat/assets/40690378/878702af-9bfe-4c16-9716-218c149cdcec)
