### ISSUE TITLE
What do I need to do to create batches of tasks.

### ISSUE THREAD

**Issue by shuait** [opencv/cvat#447]
I have a few hundreds of short videos <20 seconds, and they all share the same labels. I wonder what I need to do to create, say 300 tasks, at the same time?

**Comment by nmanovic** [comment]
@shuait ,

Do you still have problems with opening your annotation tasks? You can use REST API for that. At the moment we don't have a good tutorial which describe how to use it. An annotation task is created using 2 calls to CVAT server:

1. POST http://host:port/api/v1/tasks
1. POST http://host:port/api/v1/tasks/id/data 

An example can be found here: https://github.com/opencv/cvat/blob/a5a9b0a0192fc4a75279563b0ba6579f07db3498/cvat/apps/engine/tests/test_rest_api.py#L1053

You can use [httpie](https://httpie.org) tool to send requests (or any other tool like curl).

Does it answer on your question?

**Comment by shuait** [comment]
Great! Thanks I will give it a try and report my findings.

**Comment by shuait** [comment]
Think I'm getting something here. One more question about using mounted data, I have all videos mounted on cvat_share, each video is a zipped archive containing frames. Now I can create a new task using API,  but I can't find an example to use remote files in the same format such as:

`        data = {
            "client_files[0]": generate_image_file("test_1.jpg"),
            "client_files[1]": generate_image_file("test_2.jpg"),
            "client_files[2]": generate_image_file("test_3.jpg"),
        }`

any suggestion

**Comment by shuait** [comment]
ah figure it out. I should have not encoded the data dictionary object in to json. Will post my solution for future reference.

**Comment by shuait** [comment]
Here's my solution for future reference, I'm using python's 3.5 `requests` package. I still wonder if there's a way I can update a task's dataset repository using API?

    # First set up server api variables
    server = 'http://<hostname>:<port(default 8080)>'
    api = '/api/v1'
    tasks = '/tasks'
    users = '/users'
    auth = (<admin user name>, <passwd>)

    # get all files mounted on share
    req = server + api + '/server/share?directory=/'
    response = requests.get(req, auth=auth)
    pprint('shared file get result: {}'.format(response))
    shared_fnames = [ res['name'] for res in response.json()]
 

    for fname in shared_fnames[:1]:
        create_task_data = {
            "name": fname,
            "owner": 1,
            "assignee": 2,
            "overlap": 0,
            "segment_size": 500,
            "z_order": False,
            "image_quality": 95,
            "labels": <your labels as a list of dictionary>
        }

        # create tasks
        req = server + api + tasks
        response = requests.post(req, json=create_task_data, auth=auth)
        print('task create response: {}'.format(response))
     
        # send data to task
        task_id = response.json()['id']
        data = {'server_files[0]': fname}
        req = server + api +tasks + f'/{task_id}/data'
        print("task data request: {}".format(req))
        response = requests.post(req, data=data, auth=auth)
        print("task data response: {}".format(response))

**Comment by nmanovic** [comment]
@shuait , if you can contribute a tutorial how to use REST API for the specific task it will be awesome.

**Comment by shuait** [comment]
@nmanovic yeah, I would like to help. Could you tell me how can I contribute to this?

**Comment by shuait** [comment]
It seems I can't set task mode to interpolation when creating them.  
Each of my task uses extracted frames in a single zipped archive. By default tasks are set mode as "annotation"

I tried specifying task mode to interpolation when creating it as:

    data = {
               "name": <some file name>, 
               "mode": "interpolation",
               <...some other keys.>    
                }

This didn't work, and use patch to update task info didn't work as well. 
The only way to change task mode is to use admin panel and manually change task mode from "annotation" to "interpolation".  Any idea how to do it using API?

**Comment by nmanovic** [comment]
@shuait ,

At the moment it isn't possible to do using API. Mode is set automatically. Mode is readonly field. Probably it can be changed.

**Comment by pannaf** [comment]
@shuait I don't fully understand your script. I wonder if you could help me a little bit by providing a few more details on how to use your script. Specifically, did you create a new directory api/v1/server/share?directory=/ somewhere in the cvat directory? And then you placed your videos there? What was the structure of your "labels" field in the create_task_data? Thanks!

**Comment by Sreedeepthinukala** [comment]
@pannaf  did you ever figure out the answer?

**Comment by KhidirGlal** [comment]
I'm new to API in general, I'm using your code to create a new tasks,  I created a new local server to test the code then I will try it on my main could hosted server. 
do you have any idea how to solve this error? 

![image](https://user-images.githubusercontent.com/99792172/156910405-794cb90b-3101-4c99-aad1-5d04221baa8c.png)

**Comment by nmanovic** [comment]
@KhidirGlal , please look at our CLI: https://github.com/openvinotoolkit/cvat/tree/develop/utils/cli

**Comment by alexeyneu** [comment]
> One more question about using mounted data, I have all videos mounted on cvat_share, each video is a zipped archive containing frames. Now I can create a new task using API, but I can't find an example to use remote files in the same format such as:

cool page

**Comment by Qalababbass** [comment]
Hi, I had a similar task where i needed to create tasks in a pre-defined project in CVAT using CVAT REST API. I am also uploading images to these tasks. There are some other methods too for debug.
Maybe it will be helpful for somebody new at CVAT.
[CVAT_REST_API](https://github.com/Qalababbass/CVAT_REST_API/blob/main/create_cvat_tasks.py)

Happy for my contribution.
