### ISSUE TITLE
develope environment external postgres

### ISSUE THREAD

**Issue by Goseokbin** [opencv/cvat#4474]
i want to set develop environment. i created postgres, cvat_opa, redis pod in kubernetes cluster and connect with cvat_backend.
so i edit code in settings/base.py, settings/development.py  like that.

``` python
# settings/development.py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cvat_dev',
        'USER': 'cvat_dev',
        'PASSWORD': 'my_password',
        'HOST': 'DB_HOST',
        'PORT': '32442',
    }
}
IAM_OPA_DATA_URL = 'http://my_opa_host:8181/v1/data'
```
```
# base.py
IAM_OPA_DATA_URL = 'http:///my_opa_host:8181v1/data'
RQ_QUEUES = {
    'default': {
        'HOST': 'redis_host,
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': '4h'
    },
    'low': {
        'HOST': 'redis_host,
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': '24h'
    }
}
```
and start debugging server:debug, ui.js:debug  
i can login but have so error

1. invalid token error
![image](https://user-images.githubusercontent.com/37431938/158505346-8b4db103-6a12-49da-b9f3-8007bde2ebd9.png)

2. requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
![image](https://user-images.githubusercontent.com/37431938/158506513-63c64585-021d-454b-a8ff-44ef6cb6f30c.png)

how to solve this error..?

**Comment by bsekachev** [comment]
Sorry, but the core team does not support others databases on develop environment. 
So, we can't help you here. You can ask for help on gitter.
