### ISSUE TITLE
Adding assignee to dumped XML

### ISSUE THREAD

**Issue by thogerb** [opencv/cvat#448]
Hi

Thank you for an amazing tool. A simple "feature"/add-on we would love to see is, if the XML dump also contained reference to the assignee. We would think: Just like "owner" is included on the task level of the XML, it could also include an < assignee > field.

Currently we have to "hack" this by retrieving the assignee of a task from an exposed API endpoint, separate from the rest of our processing of the XML.

We hope this can be implemented. Thank you!

Best regards

**Comment by nmanovic** [comment]
@azhavoro , could you please slightly improve your PR and add the feature?

**Comment by nmanovic** [comment]
It was implemented
