### ISSUE TITLE
Update annotation attribute(s) failed

### ISSUE THREAD

**Issue by fredO13** [opencv/cvat#4483]
![image](https://user-images.githubusercontent.com/51124484/158621121-9c111395-d9e2-4b32-a7be-f373b6131b7e.png)

Can add tag to image, but when trying to change on attribute of the tag, I get this error

**Comment by bsekachev** [comment]
Please provide the attribute specification and what value you are trying to set

**Comment by fredO13** [comment]
![image](https://user-images.githubusercontent.com/51124484/158772405-f42fb544-5d0f-4e72-a645-8a93ae5234bb.png)

**Comment by fredO13** [comment]
I cant' set any of the attributes

**Comment by bsekachev** [comment]
@fredO13 

Can you specify default values for the attributes here? And then try again
![image](https://user-images.githubusercontent.com/40690378/158773759-75325ad8-e9a2-458f-bd9f-634dae088eed.png)
