### ISSUE TITLE
any documents or illustration for cvat user groups, like business, worker, observer?

### ISSUE THREAD

**Issue by ted8201** [opencv/cvat#4484]
Great project, and really appreciate it. Is there a document describes more information about Groups in admin panel. The groups "admin, annotator, business, observer, and worker.", more specific illustration. And can we assign annotation and validation to different people?

**Comment by davodogster** [comment]
@nmanovic Hi any update on this? @bsekachev

**Comment by edwardnguyen1705** [comment]
Dear @nmanovic ,
Thanks for sharing your excellent work.
Any update on this issue?

**Comment by nmanovic** [comment]
@edwardnguyen1705 , we have a general article about permissions in CVAT: https://www.cvat.ai/post/cvat-open-policy-agent

I will close the issue. We improve documentation constantly. I don't think we need an issue about that.
