### ISSUE TITLE
python cli is not uploading images

### ISSUE THREAD

**Issue by jafar-pivotchain** [opencv/cvat#4491]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have CVAT v2.0 running on a cloud instance. I am trying to upload the images with annotations through the command-line interface. I am able to get the metadata on the UI however the images are not present. I have tried the similar exercise on the cloud instance as well but getting same result.
Earlier I was using cvat 1.3 the commands from share and local were working perfectly fine.
### Expected Behaviour

The images should get uploaded for resourcetype local, share or remote
### Current Behaviour

```
python3 cli.py create "newtask" --labels '[{"name": "cat"},{"name": "dog"}]' local /home/admin-pc/Pictures/yoloxx.jpg

python3 cli.py create "newtask" --labels '[{"name": "cat"},{"name": "dog"}]' share /cvat_share/*.jpg
```

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`): cvat-v2.0
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.12, build e91ed57
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04.4 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
![Screenshot from 2022-03-21 19-31-46](https://user-images.githubusercontent.com/57425148/159277504-b6c4e59d-7128-40e9-8fa8-ba9f88d15f43.png)
![Screenshot from 2022-03-21 19-29-01](https://user-images.githubusercontent.com/57425148/159277513-96599653-6e29-4c28-983a-833734c86b1f.png)
![Screenshot from 2022-03-21 19-28-40](https://user-images.githubusercontent.com/57425148/159277519-c69d30f7-7d15-4439-9fd9-df07ade39de5.png)

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by Marishka17** [comment]
Hi, @jafar-pivotchain, I will close this issue now because it works locally for me. (I didn't test it on the cloud instance but I guess it shouldn't be causing the issue). Could you please check it with the latest CVAT cli and reopen it if this issue will be still relevant?
