### ISSUE TITLE
Remove background trapped by object

### ISSUE THREAD

**Issue by TimothyEbert** [opencv/cvat#4492]
- In outlining an insect there are times that the antennae and legs trap background. I want to remove that background.
- My best solution is to make a new class "trapped Background"
- Is there a better solution?

**Comment by bsekachev** [comment]
The usecase is not clear, could you please provide more details and some screenshots?

**Comment by bsekachev** [comment]
I will close the issue. Do not hesitate to reopen if you can provide the requested information.
