### ISSUE TITLE
Please tell me how CVAT annotations are supposed to be used

### ISSUE THREAD

**Issue by johan-sightic** [opencv/cvat#4502]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi!
I have annotated a few videos with rectangle tracks and now I want to download my annotations so that I can use them to train a deep learning model. I export them to CVAT for Video 1.1 (I also tried a few other formats). However, in the exported xml file there is no reference to the video file that the annotations belong to. This seems strange but I solved it by naming the task the same as the video file. But I still can't pair the annotations with video frames because the "frame" value of the tracks do not refer to the frame of the video but is instead some kind of consecutive numbers.

This seems very strange to me and I can't figure out how to use the annotations I crated. I therefore assume that I have missed something or totally misunderstood how CVAT is supposed to be used, can someone explain it to me?

**Comment by EyescannerJE** [comment]
I realized that It works if you export each task manually instead of exporting the entire project, but this is also not very convenient. 
When I export the entire dataset it sets `source="manual"` for each track.

**Comment by EyescannerJE** [comment]
The source value for a task export: `<source>eye0.mp4</source>`, is it possible to get the full file path so that it works even if many files have the same name?

**Comment by EyescannerJE** [comment]
Here is also an example of the frame problem @bsekachev @ActiveChooN:
```xml
  <track id="1" label="Eyelids" source="manual" task_id="72" subset="default">
  ...
    <box frame="6242" outside="0" occluded="0" keyframe="0" xtl="0.48" ytl="33.30" xbr="399.80" ybr="229.92" z_order="0">
    </box>
    <box frame="6243" outside="0" occluded="1" keyframe="1" xtl="0.48" ytl="33.30" xbr="399.80" ybr="229.90" z_order="0">
    </box>
  </track>
  <track id="2" label="Eyelids" source="manual" task_id="73" subset="default">
    <box frame="6244" outside="0" occluded="1" keyframe="1" xtl="0.00" ytl="147.76" xbr="400.00" ybr="324.44" z_order="0">
    </box>
    <box frame="6245" outside="0" occluded="1" keyframe="0" xtl="0.00" ytl="147.76" xbr="400.00" ybr="324.43" z_order="0">
    </box>
  ...
  </track>
```
Each video has roughly 3000 frames but it varies (no video has more than 3500 frames). As you can see when one track ends and a new starts the frame values is not reset but continues counting up.

**Comment by jeethesh-pai** [comment]
Was this problem solved ? I am facing the same problem with CVAT 2.3 version. I would like to bind the source to a file name instead of "manual".
