### ISSUE TITLE
New serverless functions for Interactive Segmentation

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#4521]
Need to investigate different methods for semi-automatic semantic annotation and add them as serverless functions:

https://paperswithcode.com/task/interactive-segmentation

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

**Comment by bsekachev** [comment]
I suppose it was supported
