### ISSUE TITLE
An error message is displayed when the Task page is opened

### ISSUE THREAD

**Issue by Alan-huan** [opencv/cvat#4522]
Could not receive repository status
TypeError: Cannot read properties of undefined (reading 'value')
![image](https://user-images.githubusercontent.com/56532001/160323926-23b9c96a-b583-46b3-a1c8-45a2729ec957.png)

**Comment by bsekachev** [comment]
@Alan-huan 

Please, provide more information according to issue template, screenshots, logs from the browser console.
