### ISSUE TITLE
Issue with importing task

### ISSUE THREAD

**Issue by lschaupp** [opencv/cvat#4530]
Hey everyone,

After exporting a task and re-importing it, I am getting the following error:
"KeyError: 'reviews'\n".

Can anyone explain what is going on?
I am on the latest stable release.

Cheers

**Comment by nmanovic** [comment]
@lschaupp , did use CVAT v1.7.0 for export and CVAT v2.0.0 for import? If so, it will not work. You can try to modify the backup manually to remove unsupported keys.
