### ISSUE TITLE
Same storage already exists

### ISSUE THREAD

**Issue by jamesdi1993** [opencv/cvat#4533]
Hello, 

Thanks for your work in building this tool. We've been developing and testing heavily based of cvat. Most recently we kept running into the error "Same storage already exists" with status code 400, when attaching a new cloud storage with AWS S3. 

We've verified that there's no duplicate (as specified in the manifest.jsonl file) in our existing cloud storages, even across different user accounts. One thing we did differently is that instead of putting the images directly under the bucket root, we put it under a prefix as "s3://<bucket_name>/some_prefix/<image_name>.jpg", and modified the manifest.jsonl file to reflect that. 

A few questions:
1) Does CVAT has an upper limit on the number of cloud storages we could attach? 
2) (This is a hack) The error went away, when we tried to modify an existing cloud storage under a different prefix, and replace with the new manifest.jsonl. Is this expected? 

Thanks in advance for your help.

**Comment by nmanovic** [comment]
@Marishka17 , could you please help to investigate?

**Comment by Marishka17** [comment]
@jamesdi1993, Thanks, I'll investigate this case. But maybe one clarifying question: 
Are you sure that you don't have another bucket with the same `provider`/`bucket`/`credentials` set?

**Comment by jamesdi1993** [comment]
Hi @Marishka17 just wanted to follow up on this thread, could you share if there's any info / update on this issue?

**Comment by Marishka17** [comment]
@jamesdi1993, Hello, As I remember, the current solution was implemented so that users can create only one cloud storage with unique  `provider/bucket/credentials` set.  This approach was implemented due to unique bucket name requirements on the provider's side (e.g you cannot create a bucket with some name if such bucket already exists). But if you have several subsets on the bucket you can create several manifests and attach them when creating cloud storage in CVAT.
If it was available in your case to create several cloud storages in CVAT with unique `provider/bucket/credentials` set, please, provide more details.

**Comment by jamesdi1993** [comment]
@Marishka17 Thanks for the reply. I followed your suggestion of using attaching single storage, and import the subsets of data by attaching multiple manifests under the same bucket. I think this would work for us in the short / medium term. 

I'm able to attach multiple storages on the same provider & bucket & credentials, as provided by the example above. The confusing part is that it works for 2-3 storages and gave error messages then after trying attach more storages. Perhaps it's worth either fix the logic to enable it as a feature, or disabling it altogether.

**Comment by giuseta** [comment]
I am using CVAT v2.1.0 and we have the same bucket organization of @jamesdi1993, i.e. one bucket and several subfolders:

- bucket_name/image_folder_1
- bucket_name/image_folder_2
- ...
I've successfully created a and I would like to create a cloud storage inside an organization  We created a `manifest.jsonl` for image_folder_1
