### ISSUE TITLE
Build docker-compose.dev.yml on version v2.0.0 fails

### ISSUE THREAD

**Issue by pedrofrodenas** [opencv/cvat#4535]
### Expected Behaviour

After running the following command, the image cvat_server should be built:

`docker-compose -f docker-compose.dev.yml build`

### Current Behaviour

After pulling Ubuntu 20.04 and installing packages onto this image appears the following error:

`Building cvat
Sending build context to Docker daemon  70.16MB
Step 1/53 : FROM ubuntu:20.04 as build-image
20.04: Pulling from library/ubuntu
4d32b49e2995: Pull complete 
Digest: sha256:bea6d19168bbfd6af8d77c2cc3c572114eb5d113e6f422573c93cb605a0e2ffb
Status: Downloaded newer image for ubuntu:20.04
 ---> ff0fea8310f3
Step 2/53 : ARG http_proxy
 ---> Running in f3c7d49df759
Removing intermediate container f3c7d49df759
 ---> c9ccce68c59c
Step 3/53 : ARG https_proxy
 ---> Running in 4e9d0aea2200
Removing intermediate container 4e9d0aea2200
 ---> f3779363d039
Step 4/53 : ARG no_proxy="nuclio,${no_proxy}"
 ---> Running in ed1a5ea711bb
Removing intermediate container ed1a5ea711bb
 ---> befb9cd18071
Step 5/53 : ARG socks_proxy
 ---> Running in 7132a44636a2
Removing intermediate container 7132a44636a2
 ---> 7d7c9d730c90
Step 6/53 : ARG DJANGO_CONFIGURATION="production"
 ---> Running in 44d5bc439d38
Removing intermediate container 44d5bc439d38
 ---> 6826ab5aa758
Step 7/53 : RUN apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -yq         apache2-dev         build-essential         curl         libgeos-dev         libldap2-dev         libsasl2-dev         nasm         git         pkg-config         python3-dev         python3-pip         python3-venv &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 202e0c010cd6
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [25.8 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [863 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Err:4 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:863333 [weak]
   - SHA256:351b9d40be591520128f46051715996ee31c6b42da652f20d567c29de64c1dfc
   - SHA1:8bebf687acabed23d9052b510d269efcd0806a4b [weak]
   - MD5Sum:e6c7e9c070bd5cfc559cfc0007d4310e [weak]
  Hashes of received file:
   - SHA256:b8fc8c2b54d1db1ec5f238d9de182f8d33c261e4be8f3bde7166a1fff97a714d
   - SHA1:a7c781c0b7e9391e85ee33a0aaa1eebaa82a7744 [weak]
   - MD5Sum:2ff3d09bd6f9b5179f551e8de6b2973a [weak]
   - Filesize:1687351 [weak]
  Last modification reported: Wed, 30 Mar 2022 05:36:28 +0000
  Release file created at: Wed, 30 Mar 2022 07:44:26 +0000
Ign:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
Get:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1069 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Err:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:11344505 [weak]
   - SHA256:200acdc3421757fa8f8759c1cedacae2cf8f5821d7810ca59d8a313c5b3ae71e
   - SHA1:28dce64e724849c2296c10a2a3de8334c7829494 [weak]
   - MD5Sum:fc2f03a69a8d61b33e29934cbba9e675 [weak]
  Hashes of received file:
   - SHA256:182545f3942a02c42e13c6b5fd607c25d211ebdc37ec6f5259efc1b69eb91056
   - SHA1:689a1717e94f61b84316c7cb25160656e26a2075 [weak]
   - MD5Sum:81561a76bfa760b6772b36129c372c84 [weak]
   - Filesize:2105715 [weak]
  Last modification reported: Wed, 30 Mar 2022 07:45:52 +0000
  Release file created at: Thu, 23 Apr 2020 17:33:17 +0000
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2106 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1146 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1147 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [51.2 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [26.0 kB]
Fetched 11.5 MB in 44s (262 kB/s)
Reading package lists...
W: http://archive.ubuntu.com/ubuntu/dists/focal/universe/binary-amd64/by-hash/SHA256/200acdc3421757fa8f8759c1cedacae2cf8f5821d7810ca59d8a313c5b3ae71e: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/universe/binary-amd64/by-hash/SHA256/351b9d40be591520128f46051715996ee31c6b42da652f20d567c29de64c1dfc  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:863333 [weak]
    - SHA256:351b9d40be591520128f46051715996ee31c6b42da652f20d567c29de64c1dfc
    - SHA1:8bebf687acabed23d9052b510d269efcd0806a4b [weak]
    - MD5Sum:e6c7e9c070bd5cfc559cfc0007d4310e [weak]
   Hashes of received file:
    - SHA256:b8fc8c2b54d1db1ec5f238d9de182f8d33c261e4be8f3bde7166a1fff97a714d
    - SHA1:a7c781c0b7e9391e85ee33a0aaa1eebaa82a7744 [weak]
    - MD5Sum:2ff3d09bd6f9b5179f551e8de6b2973a [weak]
    - Filesize:1687351 [weak]
   Last modification reported: Wed, 30 Mar 2022 05:36:28 +0000
   Release file created at: Wed, 30 Mar 2022 07:44:26 +0000
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/universe/binary-amd64/by-hash/SHA256/200acdc3421757fa8f8759c1cedacae2cf8f5821d7810ca59d8a313c5b3ae71e  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:11344505 [weak]
    - SHA256:200acdc3421757fa8f8759c1cedacae2cf8f5821d7810ca59d8a313c5b3ae71e
    - SHA1:28dce64e724849c2296c10a2a3de8334c7829494 [weak]
    - MD5Sum:fc2f03a69a8d61b33e29934cbba9e675 [weak]
   Hashes of received file:
    - SHA256:182545f3942a02c42e13c6b5fd607c25d211ebdc37ec6f5259efc1b69eb91056
    - SHA1:689a1717e94f61b84316c7cb25160656e26a2075 [weak]
    - MD5Sum:81561a76bfa760b6772b36129c372c84 [weak]
    - Filesize:2105715 [weak]
   Last modification reported: Wed, 30 Mar 2022 07:45:52 +0000
   Release file created at: Thu, 23 Apr 2020 17:33:17 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -yq         apache2-dev         build-essential         curl         libgeos-dev         libldap2-dev         libsasl2-dev         nasm         git         pkg-config         python3-dev         python3-pip         python3-venv &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
ERROR: Service 'cvat' failed to build : Build failed`

### Your Environment
docker version:

Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:02 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:53 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker-compose version:

docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

**Comment by bsekachev** [comment]
I will close the issue as outdated. If you have the same issue with the newest release, please, reopen
