### ISSUE TITLE
Overwhelming CVAT FS by unused files

### ISSUE THREAD

**Issue by PMazarovich** [opencv/cvat#4536]
Hello!
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Keep only one copy of the video or delete it after image extraction process (maybe even add a checkbox in UI like "remove video from FS after creation")

### Current Behaviour
Now, as far as I understand, when user create a task from video, raw video file is stored in CVAT FS. Even if user choose to cut the video using from -> to frames in UI.
Let's say we have one 6gb video that we want to split into different tasks and annotate separately. This means, that if user decide to create 100 chunks from this 6 gb video, he will have 600 gb occupied in FS just by 100 copies of the same 6gb file
Is it possible somehow to get rid of original video file? Or maybe this can be a feature for CVAT?

**Comment by bsekachev** [comment]
Sorry, unfortunately this is not supported. Front edge of a 2D cuboid is always not distorsed.
