### ISSUE TITLE
Nuclio Dextr function (AI Tool) not working with latest CVAT version

### ISSUE THREAD

**Issue by petergro-hub** [opencv/cvat#4548]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
- [x] Checked that model (and model container) is working
- [x] Checked that model and CVAT container are communicating
- [x] Checked that communications contain valid inputs/outputs

### Expected Behaviour

When using the AI-Tool interactor model "DEXTR", after selecting 4 or more points a polygon should be shown. 

### Current Behaviour

The selected points just remain as is, no polygons are added, no error is displayed. (No Timeout either after several minutes)

<img src="https://user-images.githubusercontent.com/65029581/162100811-95d48d45-8a46-4d46-b60d-ca5120bb45ab.png" alt="DEXTR_ISSUE" width="150"/>

### Steps to Reproduce (for bugs)

1. Install OpenCV according to the installation manual
2. Deploy OpenCV with `docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/serverless/docker-compose.serverless.yml up -d` 
(Only volumes are mounted in the override)
3. Follow the AI tool installation steps, install the functions with `./serverless/deploy_cpu.sh`
4. Set up a task with images, use AI tool "DEXTR"

### Context

I've used CVAT before the 2.0 upgrade, DEXTR was working fine, after updating to the latest version the issue appeared.
I've tried other AI tools, they work successfully.
DEXTR container logs show a successful call: `processor.http (I) call handler {"worker_id": "1"}`
Calling the process through nuclio dashboard POST request `/projects/cvat/functions/openvino-dextr/code` with a custom image, sends back a working set of coordinates of the type:
```
[
    [
        179,
        26
    ],
    [
        178,
        27
    ],
...
]
```

### Your Environment

- Git hash commit (`git log -1`): 737ee712d27e558152203d19b8bd329071f7a182
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.14
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04.3 LTS (Focal Fossa)"

**Comment by nmanovic** [comment]
@petergro-hub , it should be fixed in the develop branch. Please try.

**Comment by petergro-hub** [comment]
@nmanovic Pulling the latest version and setting up with unreleased changes via: `docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.override.yml -f components/serverless/docker-compose.serverless.yml up -d --build` fixed it for me, thanks.

**Comment by petergro-hub** [comment]
The annotation now works, however when a "worker" or "user" tries to use the AI tools, the result is:
"Error: Request failed with status code 403. {"detail":"You do not have permission to perform this action."}."
Is there a way to provide access without elevating the users to staff?

**Comment by nikste** [comment]
@petergro-hub did you solve this? I'm experiencing the same error with a non admin user (with hrnet as interactor) and a 403.
(admin user works)

**Comment by bsekachev** [comment]
Now it should work. Could you please check?
