### ISSUE TITLE
CLI commands to dump all annotations for a project

### ISSUE THREAD

**Issue by varungupta31** [opencv/cvat#4552]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context

I have about 600+ annotated videos and downloading completed annotations (either manually or via CLI) for each task at once, is cumbersome. I see that there is now a feature to dump project annotations, as discussed [here](https://github.com/openvinotoolkit/cvat/issues/2678) and [here](https://github.com/openvinotoolkit/cvat/pull/3365).

However, when I open my cvat, browse to projects, I see an option to 'export project dataset', I get an error message --->

![image](https://user-images.githubusercontent.com/51288316/162172032-cd1a090a-bffb-41ad-841e-13afe4d49da5.png)

I don't know if this is supposed to download annotation files or not.
So, is there a way to download annotations for an entire project? (CLI)
(if yes, is there a further provision to dump only `completed` tasks, and leave out the `pending` ones?

### Your Environment

```

Server version: 1.6
Core version: 3.16.0
Canvas version: 2.7.0
UI version: 1.23.1

```

**Comment by zhiltsov-max** [comment]
Hi. Thanks for reporting the project export problem. I'd like to ask about the bulk export functionality. Could you please describe the desired output in your case? Do you expect multiple separate output datasets for each task, or a single one (merged from all the tasks)? Project export will cover the second case, but for the first case we will probably need to download each task separately (which can be automated with SDK/CLI, if you need).
