### ISSUE TITLE
need info related to delete some images from task and need to merge tasks from different people's account to one task

### ISSUE THREAD

**Issue by AmmarFarooqKhan** [opencv/cvat#4554]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
Hey
Actually I wanna train my data using yolov3. First I created a task on cvat using my account. Suppose uploaded 1000 images, annotated 700. Now I wanna delete these not labeled 300 images.
Next thing is due to burden, I gave 500 images to 4 different people each, so in total 2000 images. Now I've in total 5 output folders. How can I merge these 5 into 1 to train smoothly.

**Comment by AmmarFarooqKhan** [comment]
Hey
Actually, I wanna train my data using yolov3. First I created a task on cvat using my account. Suppose uploaded 1000 images, annotated 700. Now I wanna delete these not labeled 300 images.
Next thing is due to burden, I gave 500 images to 4 different people each, so in total 2000 images. Now I've in total 5 output folders. How can I merge these 5 into 1 to train smoothly.

**Comment by bsekachev** [comment]
Please consider using [Datumaro](https://github.com/openvinotoolkit/datumaro) product. You requirements out of CVAT responsibilities.
