### ISSUE TITLE
Error: Request failed with status code 500. "UnboundLocalError: local variable 'logger' referenced before assignment\n"

### ISSUE THREAD

**Issue by kimlia545** [opencv/cvat#4555]
### My actions before raising this issue
- [✓ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [✓ ] Searched [past issues](/issues)

I created task with "Connected file share"
"Could not create the task
Open the Browser Console to get details
cvat-app.tsx:262 Error: Request failed with status code 504.
504 Gateway Timeout<
"
An error occurred, but a task was created.
"Export task dataset" is not working 

Error: Request failed with status code 400. "[Errno 2] No such file or directory: '/home/django/data/tasks/68/logs/task.log'".
Error: Request failed with status code 500. "UnboundLocalError: local variable 'logger' referenced before assignment\n"

Error does not occur when importing a few images from the "Connected file share" 

Error arise when importing more than ten thousand images
Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
cvat-app.tsx:262 Error: Request failed with status code 504. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>504 Gateway Timeout</title>\n</head><body>\n<h1>Gateway Timeout</h1>\n<p>The gateway did not receive a timely response\nfrom the upstream server or application.</p>\n</body></html>\n".
e @ cvat-app.tsx:262

**Comment by kimlia545** [comment]
Error does not occur when importing a few images from the "Connected file share" 

Error arise when importing more than ten thousand images
Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
cvat-app.tsx:262 Error: Request failed with status code 504. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>504 Gateway Timeout</title>\n</head><body>\n<h1>Gateway Timeout</h1>\n<p>The gateway did not receive a timely response\nfrom the upstream server or application.</p>\n</body></html>\n".
e @ cvat-app.tsx:262

**Comment by lix4** [comment]
I got the same issue. Have you found the solution?

**Comment by kimlia545** [comment]
@lix4 
Hi, sorry for the late reply.
I didn't solve the problem, I deleted and reinstalled docker.
I think it's a problem related to this  https://github.com/openvinotoolkit/cvat/issues/2263
