### ISSUE TITLE
Mask rcnn Auto Annotation error

### ISSUE THREAD

**Issue by SabinaUS** [opencv/cvat#4561]
Hello, I try to use auto annotation based on mascrcnn (gpu), I uploaded the model to nuclio successfully, but when I try to implement the model on cvat platform it gives me an error: 
![Screenshot from 2022-04-11 16-19-45](https://user-images.githubusercontent.com/61276853/162686662-6dcde626-751e-422f-9a83-fe46ca451419.png)
My environment:
Ubuntu 18.04
docker version: 20.10.14
nuclio version: 1.5.16

**Comment by bsekachev** [comment]
I will close the issue as outdated. Recently tried it and it works in current develop
