### ISSUE TITLE
Can be uploaded maskrcnn trained on cpu to auto annotation 

### ISSUE THREAD

**Issue by SabinaUS** [opencv/cvat#4564]
### My actions before raising this issue
- [ yes] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [yes ] Searched [past issues](/issues)

### Expected Behaviour
I first wanted to upload maskrcnn GPU-based model upload to cvat, but it kept going in error.
When I uploaded maskrcnn CPU based (openvino) it worked well. But I want to upload my custom trained marcrcnn
I could not find a way to train on openvino and upload that model

### Current Behaviour
Can I train maskrcnn based on cpu on my custom dataset and upload it to CVAT?
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 20.10.14):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux. Ubuntu 18.04):
- Nuclio: [1.7.11](https://github.com/nuclio/nuclio/releases/tag/1.7.11)

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
You can find different examples of deployed OpenVINO models in the repository, but converting model to OpenVINO format is not CVAT issue. I would suggest referring to the OpenVINO documentations
