### ISSUE TITLE
Export image for each labelled object

### ISSUE THREAD

**Issue by BarcaBear** [opencv/cvat#4569]
Is there a way to export an image of each labelled object. We use R at the moment to do this after exporting each task. It would be great if cvat supported this feature.

I.e. select export, select export as classifier, select which objects to export, cat, dog. Two folders would be created, one with cats and one with dogs.

**Comment by nmanovic** [comment]
@BarcaBear , CVAT supports multiple data annotation formats: https://github.com/openvinotoolkit/cvat#supported-annotation-formats. You can use REST API to export an archive in an appropriate format and use it for any purpose. Also https://voxel51.com/docs/fiftyone/ has great integration with CVAT.

**Comment by BarcaBear** [comment]
Has this been marked completed because the feature has been implemented? Or because there is no work planned?

**Comment by bsekachev** [comment]
@BarcaBear 

Your request in general is supported.
For example you can export data in ``Datumaro`` format and after that modify or filter the dataset as you wish.
