### ISSUE TITLE
Building Docker with dextr fails with 503 Error

### ISSUE THREAD

**Issue by erosten** [opencv/cvat#457]
Trying to build docker with dextr support fails with 
`--2019-05-21 21:49:26--  https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip
Resolving download.01.org (download.01.org)... 104.69.64.46, 2600:1406:3f:39d::ae6, 2600:1406:3f:38d::ae6
Connecting to download.01.org (download.01.org)|104.69.64.46|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2019-05-21 21:49:27 ERROR 503: Service Unavailable.
`

In the dockerfile, it says #TODO: CHANGE URL. What is the proper URL to use so that we can use semi automatic segmentation?

**Comment by bsekachev** [comment]
@erosten 

I suppose resource was temporary unavailable. Now it works for me. Please try to build the container again.

**Comment by erosten** [comment]
Looks like it was. Thanks for getting back to me.
