### ISSUE TITLE
Can't create user nor superuser

### ISSUE THREAD

**Issue by BrunoVox** [opencv/cvat#4570]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Install CVAT, create a superuser or a normal user and log in.

### Current Behaviour

CVAT is built and ran using
`docker compose up -d`

Whenever I create a user, I can't log in. 

![image](https://user-images.githubusercontent.com/31042118/163289053-cdebd838-b9ea-42fb-93b8-6038a3d9083c.png)

When I try to log in with wrong credentials:

![image](https://user-images.githubusercontent.com/31042118/163289152-f9992f68-18b8-48ca-9789-7d197768f5ef.png)

When I try logging in with correct credentials:

![image](https://user-images.githubusercontent.com/31042118/163289261-af97e283-9a23-4608-bd0c-128d133f773b.png)

Might be important to show you that opa seems to be restarting indefinitely for unknown reasons (I didn't modify CVAT, I'm only using version 2.1.0 as released).

![image](https://user-images.githubusercontent.com/31042118/163289368-27daba30-dec5-4175-b858-087bf0412da3.png)

### Steps to Reproduce (for bugs)

1. Get release version 2.1.0.
2. Build it using `docker compose up -d`
3. Create a superuser using `docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'`
4. Go to `localhost:8080` and try logging in.

### Context

I have been using CVAT both locally and in the AWS. For some reason, when I tried running it today locally, I started facing this issue. I'm just trying to run it locally to work on a small dataset.

### Your Environment

- Git hash commit (`git log -1`): `fatal: not a git repository (or any of the parent directories): .git` (I'm using the release 2.1.0 version, as I said before).
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.14, build a224086.
- Are you using Docker Swarm or Kubernetes? No.
- Operating System and version (e.g. Linux, Windows, MacOS): Linux - Ubuntu 20.04 LTS
- Code example or link to GitHub repo or gist to reproduce problem: 
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    
    [cvat.log](https://github.com/openvinotoolkit/cvat/files/8485354/cvat.log)

    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by BrunoVox** [comment]
I kinda figured it out, even though an explanation from someone who understands CVAT more than I do would be nice.

The first thing to notice is that, when checking the logs from cvat_opa, I realized there was a `permission denied` issue while trying to run the `run --server --addr :8181 --set=decision_logs.console=true /rules` command. I decided to check the [openpolicyagent image](https://hub.docker.com/r/openpolicyagent/opa/), hoping to find a way of running the command as root. In fact, in the `docker-compose.yml` file we were using the rootless version, which came as default in version 2.1.0 and "sets the user to a non-root value". I decided to give the standard image a try (`openpolicyagent/opa:<version>`) and it worked for me.

The main question for me is: why does it work on my EC2 machine and not in my local machine? Also, I tried building from a past develop branch commit, which used to work on my machine, and it suddenly stopped working. This makes no sense to me.

Would it be the case of using the opa standard version as default on CVAT?

Thanks in advance to whoever takes some time in researching this issue.

**Comment by nmanovic** [comment]
@BrunoVox ,

docker-compose mounts a local directory (`./cvat/apps/iam/rules`) into OPA container. Probably on your local system there are some permission issues with the directory. Please look and try to adjust using `chmod` and `chown`

```
    volumes:
      - ./cvat/apps/iam/rules:/rules
```
