### ISSUE TITLE
How To Add Custom Model for Automated Annotations

### ISSUE THREAD

**Issue by madenburak** [opencv/cvat#4575]
I have custom yolov5 model. I changed torch.hub.load with from local in main.py and changed classes in function.yaml. But it doesn't work.

**Comment by nmanovic** [comment]
@madenburak , try to follow steps in the tutorial: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/. It is the best source of documentation which we have at the moment. Also try to ask our community on the gitter hub. Post here specific problems. I will try to help.

**Comment by madenburak** [comment]
Thanks @nmanovic. I resolved this problem. But yolov5 is run on cpu. I want to run on gpu. How can i do it?

**Comment by nmanovic** [comment]
@madenburak , we have a couple of examples how to do that. For example, https://github.com/openvinotoolkit/cvat/blob/develop/serverless/pytorch/foolwood/siammask/nuclio/function-gpu.yaml

In general you need to install right packages (e.g., torch==1.9.0+cu111, etc). Also you need change function.yaml configuration (e.g., add ` nvidia.com/gpu: 1`).

Run `diff -u function.yaml and function-gpu.yaml` (or a similar command) to see the difference. Here you can find some hints: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/#advanced-capabilities

**Comment by tdhooghe** [comment]
@madenburak may I ask you how you resolved the problem with using you custom model?

**Comment by gd1925** [comment]
Hi @madenburak, I am also attempting something similar with my custom model on CVAT. Were you able to load your model and run it for auto annotations?

**Comment by nfrvnikita** [comment]
@madenburak madenburak Hi, can you help me with functional.yaml? I do not understand how to change the file in order to make the model work with my weights. Do you have an example?

**Comment by ZA0068** [comment]
> [@madenburak](https://github.com/madenburak) , try to follow steps in the tutorial: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/. It is the best source of documentation which we have at the moment. Also try to ask our community on the gitter hub. Post here specific problems. I will try to help.

Site is broken.

**Comment by dvnam1605** [comment]
> @madenburak , try to follow steps in the tutorial: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/. It is the best source of documentation which we have at the moment. Also try to ask our community on the gitter hub. Post here specific problems. I will try to help.

this page now is 404, how can  I resolved this now?
