### ISSUE TITLE
Finish the job from CLI

### ISSUE THREAD

**Issue by mrKallah** [opencv/cvat#4577]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

It would be nice to add the ability to finish the job from CLI, as when you upload annotations via the CLI, you still manually have to go through and finish the job on each item manually. 

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@mrKallah , thanks for the feedback. CLI should be improved for sure. You can use [REST API](https://openvinotoolkit.github.io/cvat/docs/administration/basics/rest_api_guide/) directly to solve the problem.

**Comment by mrKallah** [comment]
> @mrKallah , thanks for the feedback. CLI should be improved for sure. You can use [REST API](https://openvinotoolkit.github.io/cvat/docs/administration/basics/rest_api_guide/) directly to solve the problem.


Not sure if I am doing something wrong here, but I am using 
```python3
import requests

id = 89

payload = {
  "status": "completed"
}

server_ip = "192.168.10.141"
PORT = 8080

USR = "username"
PASSWORD = "password"

response = requests.patch('http://{}:{}/api/tasks/{}'.format(server_ip, PORT, id), data=payload, auth=(USR, PASSWORD))

print(response)
print(response.request.url)
print(response.request.body)
print(response.request.headers)
```

and its returning

```
<Response [200]>

http://192.168.10.141:8080/api/tasks/89

status=completed

{'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '16', 'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Basic cHJvYm90aWM6QWxiZXJ0MTE='}
```

But not actually changing the status on the task, as the task remains "annotation" and not "completed".

**Comment by nmanovic** [comment]
@mrKallah , first of all `status` is a deprecated field. It will be removed in the future. You need to use `state` and `stage`. Also you can change these fields only for jobs inside the task. For a task these fields are ready only and calculated based on the list of jobs for the task.

**Comment by mrKallah** [comment]
When I try to use the Swagger API under `/api/jobs/{id}` for `get` and `patch` I get 404 when I try to make changes. I do not get the same for `/api/tasks/{id}/jobs`, however, this does not have a `patch` or `put`, so I cannot make changes with this. I assume this is not by design, so not sure if this may be a bug? I have just run a `docker-compose pull` and I have the most recent version. 

Git hash commit (git log -1): commit ba4175bf5b4467bf0fbf89a3fd645cceef7f7c23
Docker version docker version (e.g. Docker 17.0.05): 20.10.14, build a224086
Are you using Docker Swarm or Kubernetes? No
Operating System and version (e.g. Linux, Windows, MacOS): Linux, Ubuntu

![image](https://user-images.githubusercontent.com/17428615/164384933-6bd14366-b9d6-4d04-8c93-0505aa0bd190.png)

**Comment by mrKallah** [comment]
I figured it out, was putting in the task ID not the job ID

**Comment by nmanovic** [comment]
@mrKallah , thanks. I will close the issue. For your information, we significantly improved REST API, CLI. Also @zhiltsov-max is working on Python SDK.

**Comment by zhiltsov-max** [comment]
Related: #4637
