### ISSUE TITLE
Maximum number of manifests added to cloud storage

### ISSUE THREAD

**Issue by mm-fsai** [opencv/cvat#4578]
https://github.com/openvinotoolkit/cvat/blob/master/cvat-ui/src/components/create-cloud-storage-page/manifests-manager.tsx#L23

It looks like there is a maximum number of 5 manifests that can be added. Is there a way to override this?

**Comment by nmanovic** [comment]
@mm-e1 , thanks for the report. We will look into the limitation.

**Comment by muhammadAgfian96** [comment]
is there update for this?
