### ISSUE TITLE
Not able to login to CVAT UI which is deployed in AWS EC2 instance

### ISSUE THREAD

**Issue by KushBhatnagar** [opencv/cvat#4580]
I have installed CVAT in AWS EC2 instance and after starting all docker containers I am not able to login from UI, getting 500 Internal Server Error in browser console. However, I can able to access Django admin page where I can all created users. In `docker logs cvat_proxy` I can see http error codes but no other information/recommendation available in logs.

**Screenshots**

- **Error on UI Page loading**
![On Loading UI Page](https://user-images.githubusercontent.com/12119739/164221367-6e97b311-6283-4009-a9db-ad405748f6ac.png)

- **Error on Login**
![OnLogin](https://user-images.githubusercontent.com/12119739/164221480-6cbd4647-7c58-470e-8e9b-8feff46ce4ca.png)

- **Django Admin Page**
![DjangoAdminPage](https://user-images.githubusercontent.com/12119739/164221544-70a7ee34-f417-4f35-bb59-c40b46381140.png)

**Referred following resources for resolution, but nothing worked**

-  Official installation guide for [AWS](https://openvinotoolkit.github.io/cvat/docs/administration/basics/aws-deployment-guide/)
-  Followed solution in [Cannot deploy CVAT on AWS EC2 instance](https://github.com/openvinotoolkit/cvat/issues/1287#)
-  Referred related PR [Fix AWS deployment](https://github.com/openvinotoolkit/cvat/pull/1316) and updated `docker-compose.override.yml`, like :
```
version: "2.3"

services:
  cvat_proxy:
    environment:
      ALLOWED_HOSTS:
      CVAT_HOST: ec2-34-196-74-213.compute-1.amazonaws.com
```

**Additional Information**

-  [cvat_proxy_logs.txt](https://github.com/openvinotoolkit/cvat/files/8521171/cvat_proxy_logs.txt)

- Docker Version : **Docker version 20.10.14, build a224086**

- CVAT Version : **[1.4.0] - 2021-05-18**

-  OS Version : **Ubuntu VERSION="20.04.3 LTS (Focal Fossa)**

**Comment by nmanovic** [comment]
@KushBhatnagar , do you have the same issue with CVAT v2.1.0?

**Comment by KushBhatnagar** [comment]
@nmanovic :  I am using older version(1.4.0) because I need to migrate data from another instance to this AWS EC2 instance. In running instance we are using this older version, and according to official CVAT backup [guide](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/backup_guide/#how-to-backup-all-cvat-data)  version of CVAT should be same in both machines.

However, I did tried to install new version(2.1.0) in the same EC2 instance but there is no **cvat_proxy** server running and I am not able to access the UI.

- `docker-ps` output 
![image](https://user-images.githubusercontent.com/12119739/164486736-e5e0a20b-2837-4af3-840b-010c727d58a5.png)
 
- UI Page Error
![image](https://user-images.githubusercontent.com/12119739/164486877-8603983d-9297-4b95-8598-eabc2c32c02f.png)

**Comment by KushBhatnagar** [comment]
@nmanovic  : Any update on this issue?

**Comment by nmanovic** [comment]
@KushBhatnagar , why do you try to open port 80 on the latest screenshot? Traefik is the cvat_proxy. Try to access 8080 port. It should work.

Also if you need to migrate data, the approach is right. Need to install 1.4.0 first and after that upgrade it till 2.1.0. Could you please share logs for docker containers? I will try to help and investigate. Just run `docker logs cvat > cvat.log` and share with me cvat.log. If you like, you can send it privately (e.g. using gitter).

**Comment by KushBhatnagar** [comment]
@nmanovic , I am not sure about Traefix port. I have not changed anything in the setup and trying to access 8080 port only.
Please the [cvat.log](https://github.com/openvinotoolkit/cvat/files/8556116/cvat.log) from 1.4.0 version.

**Comment by nmanovic** [comment]
@KushBhatnagar , it cannot be logs from 1.4.0. OPA was introduced in v2.0.0, but in your logs I see:

```
equests.exceptions.ConnectionError: HTTPConnectionPool(host='opa', port=8181): Max retries exceeded with url: /v1/data/users/allow (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61811f6c70>: Failed to establish a new connection:
```

**Comment by KushBhatnagar** [comment]
@nmanovic : I have installed **1.4.0** only, I am attaching `CHANELOG.md` from the installation folder to verify this please take a look. I have captured the cvat logs again but here also I can see 'OPA', not sure why this is coming.
 
[CHANGELOG.md](https://github.com/openvinotoolkit/cvat/files/8560324/CHANGELOG.md)
[cvat.log](https://github.com/openvinotoolkit/cvat/files/8560325/cvat.log)

However, as suggested in previous comments I did install new version **2.1.0** in the same EC2 instances but I have stopped/removed those containers and deleted the setup. Is there something else I need to check regarding this?

**Comment by KushBhatnagar** [comment]
@nmanovic : Do you have any input or update on this?

**Comment by a873054267** [comment]
> @nmanovic : I have installed **1.4.0** only, I am attaching `CHANELOG.md` from the installation folder to verify this please take a look. I have captured the cvat logs again but here also I can see 'OPA', not sure why this is coming.
> 
> [CHANGELOG.md](https://github.com/openvinotoolkit/cvat/files/8560324/CHANGELOG.md) [cvat.log](https://github.com/openvinotoolkit/cvat/files/8560325/cvat.log)
> 
> However, as suggested in previous comments I did install new version **2.1.0** in the same EC2 instances but I have stopped/removed those containers and deleted the setup. Is there something else I need to check regarding this?

The reason is ： execute the command ‘’export CVAT_HOST=<YOUR_DOMAIN>“； but I don't know how to solve it;

**Comment by KushBhatnagar** [comment]
@nmanovic : Any update on this issue? It's a kind of blocker for particular release. Any kind of input will be helpful

**Comment by Pepslee** [comment]
Try to add slash at the end of login endpoint:

`localhost:8080/auth/login/`
instead of 
`localhost:8080/auth/login`

**Comment by KushBhatnagar** [comment]
> Try to add slash at the end of login endpoint:
> 
> `localhost:8080/auth/login/` instead of `localhost:8080/auth/login`

@Pepslee  : I have tried this but nothing has changed

**Comment by drivo** [comment]
Hi there, I had exactly the same issue and in my case it was related to the missing /cvat/apps/iam/rules folder. This folder is only available on git repo and it is a strong dependency of CVAT OPA. In my case I fell in error because I only downloaded the docker-compose.yml file, without considering the remaining part of git repo. 

I hope it will help you too. 👋🏻

**Comment by nmanovic** [comment]
@azhavoro , please cover the case in your guide. I will close the issue. @KushBhatnagar , we are going to provide add step by step guide how to upgrade CVAT. I hope such questions will be less in the future.
