### ISSUE TITLE
Nuclio Shape/Tag Attribute Support Broken

### ISSUE THREAD

**Issue by subdavis** [opencv/cvat#4588]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When a nuclio function returns attributes, either on a single frame or when run for all frames, the attribute should be persisted.

### Current Behaviour

All attributes returned from nuclio functions are ignored.

### Possible Solution

It looks like there are two bugs:

* One in the client code, when a function is run on a single frame.
* And one in the server code, when a function is run on a whole task.

You can see the correct values in the JSON using chrome network inspector.

![Screenshot from 2022-04-22 15-35-55](https://user-images.githubusercontent.com/4214172/164782498-ca82fb33-541b-4f56-b958-98785656f789.png)

But in the UI, these values are ignored.

![Screenshot from 2022-04-22 15-37-53](https://user-images.githubusercontent.com/4214172/164782726-cf634f80-6a5b-4017-b5d0-99f2e8a01147.png)

### Steps to Reproduce (for bugs)

1. Deploy the intel face recognition function `nuctl deploy --file serverless/openvino/omz/intel/face-detection-0205/nuclio/function.yaml --path serverless/openvino/omz/intel/face-detection-0205/nuclio/ --platform local --project-name cvat --volume "$(pwd)/serverless/common:/opt/nuclio/common"`
1. Run it on something (using magic wand OR task automatic annotation dialog)
1. No attributes are saved.

### Your Environment

Not applicable: broken in all environments.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Example of serverless function supporting attributes:
https://github.com/opencv/cvat/blob/develop/serverless/openvino/omz/intel/face-detection-0205/nuclio/function.yaml
