### ISSUE TITLE
screencast links broken

### ISSUE THREAD

**Issue by alex9311** [opencv/cvat#459]
several of the links on the main README under "screencasts" are broken. 

Looks like some of the videos are on [Nikita's channel](https://www.youtube.com/channel/UCV3qghS05GjAI714ID97IuA)? Not sure what is meant to be on the README

**Comment by bsekachev** [comment]
@alex9311 

I don't have any problem with it. Links work correctly.

**Comment by alex9311** [comment]
how weird... The link for the introduction video (https://www.youtube.com/watch?v=L9_IvUIHGwM&feature=youtu.be) leads to a "this video does not exist" for me

![missing-video](https://user-images.githubusercontent.com/1326899/58189939-52de6a00-7c70-11e9-8bc2-f62488ffde61.png)

**Comment by bsekachev** [comment]
@alex9311 

It is strange, the link is opened as expected for me.

**Comment by bsekachev** [comment]
@alex9311 

Is the problem still reproduced?

**Comment by alex9311** [comment]
it seems fixed now! Did you change something?

**Comment by bsekachev** [comment]
@alex9311 
No, I suppose there was some problems with youtube. 
I will close the issue.
