### ISSUE TITLE
Container cvat_server is restarting, wait until the container is running

### ISSUE THREAD

**Issue by arasharchor** [opencv/cvat#4590]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
by typing `docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'`
I expectd to see the command line to ensert admin username, email and password

### Current Behaviour
I am getting the following response
`Error response from daemon: Container 1314e75cb455e709cd7a2f73f63c041bd95f2362a3b84b659a2ecb34679abf66 is restarting, wait until the container is running`
### Steps to Reproduce (for bugs)
1. Ubuntu 20.04 LTS
2. git clone https://github.com/opencv/cvat
3. cd cvat
4.export CVAT_HOST=SERVER_DOMAIN  (e.g. cvat.github.com)
5.docker-compose up -d
6.docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'

### Context
I am trying to install and compile CVAT on my own sever with Ubuntu 20.04 LTS

### Your Environment
- Git hash commit (`git log -1`):
commit ba4175bf5b4467bf0fbf89a3fd645cceef7f7c23 (HEAD -> develop, origin/develop, origin/HEAD)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Apr 12 19:05:28 2022 +0300

    Bump ansi-regex from 3.0.0 to 3.0.1 in /cvat-core (#4565)
    
    Bumps [ansi-regex](https://github.com/chalk/ansi-regex) from 3.0.0 to 3.0.1.
    - [Release notes](https://github.com/chalk/ansi-regex/releases)
    - [Commits](https://github.com/chalk/ansi-regex/compare/v3.0.0...v3.0.1)
    
    ---
    updated-dependencies:
    - dependency-name: ansi-regex
      dependency-type: indirect
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>
    
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

- Docker version `docker version` (e.g. Docker 17.0.05):
 Version:          20.10.14

- Are you using Docker Swarm or Kubernetes?
I do not know
- Operating System and version (e.g. Linux, Windows, MacOS):
Linux 20.04 LTS

**Comment by mherzog01** [comment]
The following worked for me:  https://github.com/opencv/cvat/issues/4816#issuecomment-1223677614

**Comment by bsekachev** [comment]
Closed as outdated
