### ISSUE TITLE
How to remove some buttons from cvat-ui

### ISSUE THREAD

**Issue by arcibiyo** [opencv/cvat#4591]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

 Provide a general summary of the issue in the Title above 

### Expected Behaviour
 I wanna remove some buttons from cvat interface like cuboid and elipse  

### Current Behaviour
 I didnt find how to redesign. I don't know what to change in cvat-ui 

### Possible Solution
 Not obligatory, but probably my solution migth  be in there > cvat/cvat-ui

### Context
 I wanna remove some buttons from cvat user interface as i show in the picture below
![image](https://user-images.githubusercontent.com/47760055/164972655-b4b605ba-3bb8-49db-83ae-71982c427250.png)
how can i remove these buttons from the interface and update cvat-interface

### Your Environment
 I am using lastest cvat version

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by arcibiyo** [comment]
@nmanovic hi sir. Maybe you can help me about this topic ?

**Comment by nmanovic** [comment]
@arcibiyo , at the moment it is possible only with source code modification. It is not configured. Please describe your case in more details. It will give us an idea what is the best strategy to do that.

**Comment by arcibiyo** [comment]
@nmanovic actually ı wanna just use rectangle button (draw new rectangle) to label ojbects and disable other draw buttons.

**Comment by nmanovic** [comment]
@arcibiyo , in this case we know about the request. It was asked a couple of times. We will work to resolve the issue. Current idea is to extend the labels specification. Using the labels specification, it will be possible to restrict UI.
