### ISSUE TITLE
CVAT Project (Team Members Management Issue - New Member Invitation, Roles Exchange)

### ISSUE THREAD

**Issue by RakeshG1** [opencv/cvat#4592]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

- A user with Maintainer role could able to invite new member to the existing project in CVAT

### Current Behaviour

- It says "request failed with status code 403 : You do not have permission for this action"
- Also a user with Owner role can't make other or give his ownership rights to other user. For example when he wants to leave the project

### Possible Solution

- Please look over this issue and suggest work around solution for this

### Steps to Reproduce (for bugs)

1. This can be reproduced in any CVAT test project with having 2 users. (Owner, Maintainer)
2. Where Maintainer trying to invite other new user
3. And Owner tries to make other user as owner

### Context

- We are using CVAT for Computer Vision project. During this we want to invite new team members and exchange the roles permisions

### Your Environment

- Git hash commit (`git log -1`): 
- Docker version `docker version` (e.g. Docker 17.0.05):  
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 Pro
- Code example or link to GitHub repo or gist to reproduce problem: 
- Other diagnostic information / logs: 
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@RakeshG1, please look at https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/invitations.csv table. `Maintainer` user should be able to invite users with `Supervisor` and `Worker` roles. `Owner` user should be able to invite users with `Worker`, `Supervisor`, `Maintainer` roles. Is it the case?

For now it isn't possible to change ownership, but I agree that it is a useful feature. Need to implement it in the future.

How to deal with no-code changes: you can use Django tools to update DB directly (change the owner). Another approach is to add some code and be able to modify an Organization object in `/admin` panel. The most complex way is to implement the feature in CVAT UI and add corresponding logic on the CVAT server.

**Comment by RakeshG1** [comment]
@nmanovic Thanks for the reply!! & apologies for the delay in response. Sure, I will try to check in the above suggested direction & let you know in case it doesn't work.
