### ISSUE TITLE
REST API can create task but won't add GCP cloud storage to it

### ISSUE THREAD

**Issue by nlandau-divert** [opencv/cvat#4593]
### Expected Behaviour

Based on the commit found [here](https://github.com/openvinotoolkit/cvat/pull/3561).
I am able to create a new cloud storage by sending a POST request to http://<server IP>:<port>/api/cloudstoreages with the following command body:

```
{
  "provider_type": "GOOGLE_CLOUD_STORAGE",
  "resource": "my_bucket",
  "display_name": "My Bucket",
  "credentials_type": "KEY_FILE_PATH",
  "key_file_path": "/credentials/gcs.json",
  "specific_attributes": "region=US-EAST1",
  "manifests": ["test_manifest.jsonl"]
}
```

Then I should be able to create a new task with that cloud storage attached by sending a POST request to http://<server IP>:<port>/api/tasks the following body:

```
{
  "name": "Test Task",
  "project_id": 1,
  "chunk_size": 1,
  "image_quality": 70,
  "server_files": [
     "test/img1.jpg",
     "test/img2.jpg",
     "test/manifest.jsonl"
  ],
  "cloud_storage_id": 1,
  "use_zip_chunks": true,
  "use_cache": true
}
```

### Current Behaviour

With my requests the cloud storage is created and the manifest is attached. I am able to manually create a labeling task with data from this new cloud store, but when I try to use the API a task is created with no dataset attached. I can go to the tasks page and see a new task is there but there are no images and no jobs attached to it. 

I have tried the POST request with "remote_files" and "client_files" instead of server files with no change in result as well as manually creating the task and trying to use a PATCH request to update an existing task with more photos.

When I then go inspect the status of the newly created task at http://<server IP>:<port>/api/task/<id>/status, I see the following error 
```
{
    "state": "Failed",
    "message": "FileNotFoundError: [Errno 2] No such file or directory: '/home/django/data/storages/1/test/manfiest.jsonl'",
    "progress": 0.0
}
```

I went into the docker container and manually added the test files, both manifest and images into the directory from the error above and the request then worked. 

Why is this searching a directory within the docker container for files and not the cloud storage?

### Context

I need to use the API to add new labeling jobs as new photos are collected.

### Your Environment

Using the following CVAT versions:

Server version: 2.1
Core version: 5.0.1
Canvas version: 2.13.2
UI version: 1.37.0

Interacting with the API using python requests library in python 3.7.

**Comment by kaninaba94** [comment]
Push! This happened to me, too

**Comment by nmanovic** [comment]
@Marishka17 , could you please look?
