### ISSUE TITLE
MilTracker issue...?

### ISSUE THREAD

**Issue by bhargav-sudo** [opencv/cvat#4594]
Hi team, 
I doesn't know if this is a problem.

I was annotating around 40 persons in a video using the recently added feature **trackerMIL**. Suddenly trackerMIL has been inactive for that task and has completely gone into manual mode. 

I had thought of enabling tracker switcher too.
But that option isn't in part of my task.
![Screenshot from 2022-04-26 07-17-36](https://user-images.githubusercontent.com/57169077/165203285-7ad55fc2-df20-4088-a1c8-62c9a2dbcb3e.png)

How can I get all those 40 into trackerMIL. 

Thanks.

**Comment by klakhov** [comment]
I hope merge feature helped you.
