### ISSUE TITLE
Reappearance of label with tracking after outside property

### ISSUE THREAD

**Issue by whiteplatin** [opencv/cvat#4595]
Hi,

Let me explain what I mean with that title.
Ive been annotating objects from a vid file, and once the object  disappears from I use the switch outside property "O".

What I cant seem to do with CVAT is to switch back "inside" once the same object appears again. 
Is there a way to do that with CVAT, so that the reappeared objects keeps the id and doesnt get a new one ?

**Comment by moon5ye** [comment]
Have the same issue. Did you solve that?

**Comment by klakhov** [comment]
Currently you can use [merge feature](https://opencv.github.io/cvat/docs/manual/basics/track-mode-basics/)  to merge several tracks into one.
