### ISSUE TITLE
Limited number of Cloud Storages are visible when create a task

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#4596]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

It is possible to select any cloud storage when create a task.

### Current Behaviour

Now it is not the case. It looks like UI requests only first page with cloud storages. Thus only 10 are available by default and others cannot be seletected.

### Possible Solution

Use `page=all` to select all pages or interactive search.

### Steps to Reproduce (for bugs)

1. Go to CVAT.org as admin and try to create a task with `dummy1` AWS S3 cloud storage

### Your Environment

- Git hash commit (`git log -1`): ba4175bf5b4467bf0fbf89a3fd645cceef7f7c23
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.14, build a224086
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem: N/A
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
- Requesting all the cloud storages with ``page=all`` is not a solution.

- More general approach is now implemented when a user can start entering cloud storage name and it will make ``search`` requests showing corresponding results.

I believe we can close the issue.
