### ISSUE TITLE
Limit cache in time

### ISSUE THREAD

**Issue by dmitrysarov** [opencv/cvat#4600]
I am using Google Cloud Storage and after a while, I understood that images on storage should be updated (e.g. quality issues). 
I overwrite images and manifest. But the image on CVAT seems to be never updated because of this line

https://github.com/openvinotoolkit/cvat/blob/ba4175bf5b4467bf0fbf89a3fd645cceef7f7c23/cvat/settings/base.py#L459

So maybe the default TIMEOUT should be limited? Otherwise, updates will never happen, it seems to be unexpected behavior. 
Thanks.

**Comment by Marishka17** [comment]
Hi, @dmitrysarov, could you please provide more information about your case & steps sequence?

**Comment by bsekachev** [comment]
I will close the issue for now. Not sure why you need to update images on cloud storages, maybe you should create another task instead?
Do not hesitate to reopen if you have any updates.
