### ISSUE TITLE
Could not update annotations. Error: "rotation" is expected to be "number", but "object" has been got."

### ISSUE THREAD

**Issue by kangsive** [opencv/cvat#4601]
### My actions before raising this issue
- [ ] drag the bbox to the next position
- [ ] change it's action labels

### Expected Behaviour
the bboxes should move and track to the next position

### Current Behaviour
it stays in the last position

### Steps to Reproduce (for bugs)

1. Create an annotation project, with only one label, add several attributes (checkbox, False, Mutable)
1. Add a new task, link to a video with normal resolution, in the <Advanced configuration>, <frame_step> set as the fps of the video, others remain default
1. Open the task and start annotation, try to change the position and labels of all bboxes as possible
1. Go and annotate the video frame by frame
2. At some frames during annotation, you will encounter such situation: you drag one target bbox to it's expected new position and change it's action labels, press F, it dramatically shift back to it's original position, and when you mark it as a keyframe, it pop up the error "Could not update annotations
Error: "rotation" is expected to be "number", but "object" has been got."

### Context
It memory serve correctly, when using a previous CVAT version in last summer, I did not have such a problem. I update the repo these days and now this problem accidentally but frequently happens in my annotation, severely slowdown the dataset preparing work. 

### Your Environment

- Docker version : 19.03.14/20.10.6-ce
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): linux/amd64, openSUSE Leap 15.2
- Code example or link to GitHub repo or gist to reproduce problem: the latest commit of this repo

**Comment by bsekachev** [comment]
I believe we fixed that, but could not find the PR. 
Please, try the newest version.
