### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by MosesNjau** [opencv/cvat#4606]
TypeError
Cannot read properties of null (reading 'dumpers')

TypeError: Cannot read properties of null (reading 'dumpers')
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:728328
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:338531
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:339065
    at Sv (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:728294)
    at Ko (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:57930)
    at Ri (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66791)
    at Di (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66610)
    at Ai (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66293)
    at gs (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:107698)
    at cl (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:96717)

**Comment by hamed-ahangari** [comment]
Dear MosesNJau, I'm not sure if my situation is related to yours, but it's been like three hours that cvat.org isn't working - I'm getting 500 server errors every second.
```
Error: Request failed with status code 500. "\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n".
```

**Comment by MosesNjau** [comment]
Hello @hamed-ahangari,

yeah, I was getting the same, but now it seems that it has been solved.
it's working fine now

**Comment by Marishka17** [comment]
Hi, @MosesNjau, @hamed-ahangari, @GowthamTammineni, Could you please provide more information on how this issue can be reproduced?

**Comment by bsekachev** [comment]
I will close the issue. Do not hesitate to reopen if you can provide the requested information.

**Comment by Soham-beast** [comment]
Error: Request failed with status code 500. "\n<!doctype html>\n<html lang="en">\n<head>\n <title>Server Error (500)</title>\n</head>\n<body>\n <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n".

I am getting this error, while I am trying to download the annotations in YOLO format. Can anyone help me?
