### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by AdithyaSabarishSaravanan** [opencv/cvat#4608]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Summary:
Unable to login and load images.

### Expected Behaviour
BE able to login and load the projects and tasks.

### Current Behaviour
Sporadically this happens. Sometimes able to login and many times login fails.

### Steps to Reproduce (for bugs)

1. Open website cvat.org
2. Try to login using the credentials.

### Context:
This is affecting my project deadlines.

### Your Environment

- Online tool using cvat.org website

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### Issue attachments:

![image](https://user-images.githubusercontent.com/67763094/166198832-a95037ce-fcc7-469f-a656-fee0bba5fbdd.png)

**Comment by Mohammed-Elias** [comment]
@nmanovic @klakhov could you please help us with this, I really don't have any clue what is happening?!

**Comment by theobouwman** [comment]
They are both located in Russia for I can see in their GitHub profile...

**Comment by strcom** [comment]
Ensure you have opa rules loaded. I've tried today update to latest version CVAT and coudn't login for some time, because my opa rules where empty (I'm using default docker-compose configuration).

**Comment by bsekachev** [comment]
Now it online in read only mode.
Users are able to move their data to https://app.cvat.ai
cvat.org will be maintained for some period of time and then disabled forever.
