### ISSUE TITLE
Please change project export pipeline of public CVAT website

### ISSUE THREAD

**Issue by JohannesDecker95** [opencv/cvat#4609]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation) => No related information found
- [a little bit] Searched [past issues](/issues) => It looks like that the related bug is not a new one

I tried several times to download a backup from a project/task from the public CVAT website and it never worked. Instead, I got the following error message, every time I tried to backup.
<img width="384" alt="Bildschirmfoto 2022-05-02 um 11 51 13" src="https://user-images.githubusercontent.com/61199140/166218891-676cdeee-85e8-4aac-8087-73222ea49588.png">

### Expected Behaviour

Backup of a project/task should be downloaded as zip file on my computer.

### Current Behaviour

After clicking on the backup in the dropdown menu of activities at the project/task side, it takes a while and then the error message occurs that tells me that "not enough space [to store the backup] on the device is left". Sometimes the error message contains the path where the backup will be created initially, how it is shown in the image above. The path tells me that it is a problem at the server where the public CVAT website is hosted.

### Possible Solution

Implement an/a agent/service at the host server of the public CVAT website, which empties the related directories daily.

### Steps to Reproduce (for bugs)

The directory path in the image above should provide the ability to identify the related project at the public CVAT webservice to you.

### Your Environment

- Operating System and version (MacOS newest version M1):
- Public CVAT Website

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by klakhov** [comment]
There were problems with old cvat instance. Project exporting should work fine  on https://app.cvat.ai/
Let us know if you have any problems
