### ISSUE TITLE
Can't export dataset from CVAT.org

### ISSUE THREAD

**Issue by Mohammed-Elias** [opencv/cvat#4610]
Apparently, I can't export any of the datasets on the website, I don't know what is the problem!

```
    Could not export dataset for the [task 208084](https://cvat.org/tasks/208084)
    Open the Browser Console to get details
```

### My actions before raising this issue
- [ - ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ - ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi, @Mohammed-Elias 

Please provide output from the browser console and logs from ``docker logs cvat``.

**Comment by mohammed-alhussein-askui** [comment]
@bsekachev Thanks a lot for your reply, the problem happened after you changed the docker image version in March for `cvat` and `cvat_ui`, I solved the problem by installing it locally, and changed the it `v2.0.0`
