### ISSUE TITLE
Usually Cannot Login / If Login Cannot Review or Export

### ISSUE THREAD

**Issue by BrandBrigade** [opencv/cvat#4613]
We are using the CVAT server.
For the last 3 days we cannot work for one of the following reason: We cannot login / If we can login we cannot open jobs / If we can open jobs we cannot export the dataset

![image](https://user-images.githubusercontent.com/104736088/166421594-e4131643-e90c-41ad-a903-3f1731a3e35c.png)
Please advice

**Comment by nmanovic** [comment]
@BrandBrigade , it should work now. Thanks for the report.

**Comment by nmanovic** [comment]
@BrandBrigade , if you need a reliable solution, I will recommend to host your own CVAT instance or contact an organisation which will help you with that. CVAT.org hosts the latest version of CVAT. Even we try to maximise uptime of the server, it is a free SaaS solution without any warranties.

**Comment by PWZER** [comment]
@nmanovic I have the same problem, when running with docker-compose, how should I solve it?

**Comment by bsekachev** [comment]
Now it online in read only mode.
Users are able to move their data to https://app.cvat.ai
cvat.org will be maintained for some period of time and then disabled forever.
