### ISSUE TITLE
When importing images to the task "FileNotFoundError: [Errno 2] No such file or directory: 'clamscan'."

### ISSUE THREAD

**Issue by rita-carv** [opencv/cvat#4615]
<img width="1181" alt="Captura de ecrã 2022-05-03, às 16 11 01" src="https://user-images.githubusercontent.com/102165556/166481770-ae60c264-0142-419d-80da-68d3d8228dbc.png">

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When I try to import .png or .jpeg images to my new task it retrieves me an error "FileNotFoundError: [Errno 2] No such file or directory: 'clamscan'." 

### Expected Behaviour
Correctly import the images. 

### Current Behaviour
It is not importing the images to my new task

### Steps to Reproduce (for bugs)

1. Create a new task 
2. Give a name to the task 
3. Give two labels
4. Import 16 images .png/.jpeg (I tried both and it doesn't work)

### Context
I need to annotate some images to my YOLO, and I consider that cvat is really good for that and it's not working

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): macOS Monterey
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@rita-carv , it looks like we have a problem with antivirus. It will take another day to fix.

**Comment by davpapp** [comment]
I'm having the same issue. Is there a temporary workaround?

**Comment by trucnguyen83** [comment]
Hi, I'm also having the same error. Hope that it can be fixed soon.

**Comment by EricEdmundXiang** [comment]
I'm also having the same error.

**Comment by davpapp** [comment]
To anyone still trying, it appears to be fixed now.

**Comment by zhiltsov-max** [comment]
Seems to be fixed.
