### ISSUE TITLE
"CSRF token missing or incorrect" when trying to upload annotations (COCO Format)

### ISSUE THREAD

**Issue by lubin-liu** [opencv/cvat#4617]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Be able to upload annotations to a task on browser. The images from the task is loaded from cloud storage (AWS S3).

### Current Behaviour

When uploading annotations in COCO 1.0 format, the following error occurs:

Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://cvat.org/api/jobs/372892/annotations/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).

### Steps to Reproduce (for bugs)

1. Open a task
2. Menu -> Upload annotations -> COCO 1.0
3. Select file corresponding to annotations in COCO Format

### Your Environment

- Git hash commit (`git log -1`): NA
- Docker version `docker version` (e.g. Docker 17.0.05): NA
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): cvat.org
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Hi @lubin-liu , try to relogin in CVAT

**Comment by nskostas** [comment]
Hi @bsekachev, 
I'm having the same error as @lubin-liu.

Also, I've tried to relogin in CVAT, and now the error is the following:
`Error: Request failed with status code 400. "Could not match item id: 'f927a8c2-a521-11e7-93c7-e55f29b1fcdc_PGB_7_PGB_7_PGB7' with any task frame\n".`

Environment:
Docker local environment from windows 10.

Thanks.

**Comment by bsekachev** [comment]
Hi, @nskostas 

It says that in your annotation file you have image named ``f927a8c2-a521-11e7-93c7-e55f29b1fcdc_PGB_7_PGB_7_PGB7``, but your task does not have images with this name.

**Comment by cyberkostas1984** [comment]
Hi @bsekachev , 
Thanks for your quick reply. That's true the file is missing, is there a way to still import the annotations when some files are missing (ie you want to revise/reannotate part of your dataset)?
Thanks

**Comment by nskostas** [comment]
Hi @bsekachev ,
Thanks for your quick reply. That's true the file is missing, is there a way to still import the annotations when some files are missing (ie you want to revise/reannotate part of your dataset)?
Thanks

**Comment by bsekachev** [comment]
@nskostas 

That is probably question for @zhiltsov-max. Maxim, could you please comment on that?

**Comment by zhiltsov-max** [comment]
Hi. Currently, you will need to remove extra images and all associated annotations. It can be done 
- with [Datumaro](https://github.com/openvinotoolkit/datumaro) (install with `pip install datumaro`) in a python script like this:

```python
import datumaro as dm

dataset = dm.Dataset.import_from('path/', 'coco')
dataset.remove('<your image name here>')
dataset.export('path2/', 'coco_instances')
```

Annotations in the `path/` directory need to be placed [like described here](https://openvinotoolkit.github.io/datumaro/docs/formats/coco/#import-coco-dataset).

- manually by modifying the json file with annotations

**Comment by nskostas** [comment]
Hi @zhiltsov-max ,

Thanks for the suggestions. We can already remove missing images from the annotations , so no problem with that.
It's just that I think it would be useful for CVAT to be able to 'ignore' the missing files and continue annotating the rest of the existing images.

Is there any plan of introducing this functionality in the future maybe?

Thanks

**Comment by bsekachev** [comment]
@zhiltsov-max Could you please answer/submit corresponding issue?

**Comment by zhiltsov-max** [comment]
@nskostas, hi. Currently, there is no such feature in our plans, but it sounds reasonable and interesting to me. Thank you, I'll create a feature request issue for this idea.

**Comment by GRGSIBERIA** [comment]
## Occurred Environments
* Windows 10, docker
* Server version: 2.3
* Core version: 7.3.0
* Canvas version: 2.16.1
* UI version: 1.45.0

## Reproduction Procedure
0. I haven't operated CVAT for a long time
1. Export a CVAT XML as edited tags
2. Import edited a CVAT XML
3. Occurred an error like the issue title

## Patch Solution
1. Sign-out user account
2. Sign-in user account
3. Upload XML for a Task

## Hypothesis
Maybe, Users can continue to action for the session has expired.
Forced reload didn't update the CSRF token.
This may be due to session reuse for a long time.

## Fundamental Solution
* try-catch CSRF error as shows a dialog "please sign-out, sign-in"
* Don't reuse settions, All users are sign-out after long periods of inactivity (don't forget to save a job)
* Another solution is to refresh the CSRF token at regular intervals, Ajax can do anything, maybe :P
* Don't delete `'django.middleware.csrf.CsrfViewMiddleware'`

**Comment by Mr-Qiuqi** [comment]
> Hi @lubin-liu , try to relogin in CVAT

This is very useful
