### ISSUE TITLE
How can I convert cvat dump annoation format to yolo or to coco  or to pascal voc ?

### ISSUE THREAD

**Issue by toplinuxsir** [opencv/cvat#462]
How can I convert cvat dump annoation format to yolo or to coco  or to pascal voc ?
Thanks !

**Comment by bsekachev** [comment]
@toplinuxsir 
We have converting scripts for that purpose: https://github.com/opencv/cvat/tree/develop/utils
As far as I see, yolo has not been supported yet. If you create the conversion script for yolo, it would be great if you make a PR with it.

**Comment by nmanovic** [comment]
Yolo format is supported in the branch which will be merged into develop soon: https://github.com/opencv/cvat/pull/454. You can use the script right now. I will close the issue. Don't hesitate to ask additional questions in our [Gitter chat](https://gitter.im/opencv-cvat)
