### ISSUE TITLE
Video Keypoint Annotation

### ISSUE THREAD

**Issue by iitdpooja** [opencv/cvat#4620]
I am working on a Human joint detection project and I want to annotate my data. I want to annotate data using keypoint detection skeleton type model.

Can CVAT support this kind of annotation?

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@iitdpooja 

It is possible, but maybe not the most efficient way. You can create several labels (leg, hand, etc.) and annotate objects using one point. After each skeleton annotated, you can group points for each person. In annotation file they will have the same group_id identificator.

**Comment by yasakova-anastasia** [comment]
It was added by https://github.com/cvat-ai/cvat-opencv/pull/1.
