### ISSUE TITLE
bug: PASCAL VOC 1.1 can't import dataset

### ISSUE THREAD

**Issue by ftconan** [opencv/cvat#4621]
### My actions before raising this issue
- [✅] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [✅ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. First, I exported the PASCAL VOC 1.1 dataset zip archive in the CVAT annotation interface menu
2. Then, I clicked on the Import Dataset button in the Project menu and was prompted with an error that there was no backgroud label
3. I delete the background label from labelmap.txt and upload the zip archive again, but there is no media file error
4. the error is as follows
<img width="1439" alt="截屏2022-05-05 14 57 48" src="https://user-images.githubusercontent.com/18213023/166893238-92efc90e-2270-4862-861b-567c9f553fda.png">
<img width="679" alt="截屏2022-05-05 15 00 36" src="https://user-images.githubusercontent.com/18213023/166893503-9d8ddcae-358f-4ad6-bd66-57bcaffae650.png">
<img width="681" alt="截屏2022-05-05 15 01 01" src="https://user-images.githubusercontent.com/18213023/166893521-e0584ae8-6241-49be-8dde-ef52ea40185b.png">
<img width="1440" alt="截屏2022-05-05 15 01 45" src="https://user-images.githubusercontent.com/18213023/166893535-78560b4b-5f00-488b-bcc6-8a3b1971cc9e.png">
5. Please resolve this as soon as possible, thank 

### Your Environment

- Git hash commit (`git log -1`): cvat 2.1
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): 
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by yasakova-anastasia** [comment]
Hi, @ftconan 

You are most likely exporting the dataset without saving the images. In this case, it won't be possible to import the dataset. If you need to continue working with this dataset, you can add images to the dataset in the `JPEGImages` folder. Or if it's still possible to export this dataset with saving images.

Adding a `background` label is a necessary part of Pascal VOC. This problem in your case could also be solved by adding a `background` label to the project.
