### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'id' in

### ISSUE THREAD

**Issue by PWZER** [opencv/cvat#4626]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Login authentication

### Current Behaviour

![image](https://user-images.githubusercontent.com/13550831/167306966-ee8fd2fa-8a10-43df-8f6b-9fbcc02786dc.png)

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/13550831/167307077-141dbfd7-6b5e-4898-97b5-60ee7d073b54.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/13550831/167307094-09f76800-5265-4ae3-ac97-376e2087874d.png">

### Steps to Reproduce (for bugs)

```bash
git clone https://github.com/opencv/cvat
cd cvat
sudo docker-compose up -d
```

### Your Environment

- Git hash commit (`git log -1`): `master` and `develop` tried
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.14, build a224086
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu22.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by PWZER** [comment]
```bash
$ docker images
REPOSITORY             TAG               IMAGE ID       CREATED        SIZE
pytorch/pytorch        latest            ca04e7f7c8e5   8 weeks ago    5.82GB
postgres               10-alpine         eeb19929169c   4 months ago   76.3MB
openvino/cvat_ui       latest            2b45ff0ccf48   5 months ago   49MB
openvino/cvat_server   latest            7720e30a355d   5 months ago   4.71GB
openpolicyagent/opa    0.34.2-rootless   f85ee8a15a91   5 months ago   71.9MB
traefik                v2.4              de1a7c9d5d63   8 months ago   92MB
redis                  4.0-alpine        e3dd0e49bca5   2 years ago    20.4MB
```

**Comment by xiakj** [comment]
遇到了同样的问题 Mark

**Comment by PWZER** [comment]
The issue has been resolved, I did this
- clear custom registry mirrors from `/etc/docker/daemon.json`
- run `sudo docker-compose pull` to update the latest images
- also note that the browser url has port 8080 instead of 80

**Comment by xiakj** [comment]
@PWZER 
thand's for you reply

**Comment by xiakj** [comment]
@PWZER 
unfortunately, your advice cannot resolve my problem.
how to "clear custom registry mirrors from /etc/docker/daemon.json"? can you tell me the command line,thanks

**Comment by bsekachev** [comment]
@xiakj 

If the issue still relevant,  please provide screenshots from Network tab (I am interested in requests details). I suspect that there are issues related with cache.

**Comment by sijin-dm** [comment]
I meet the same problem also. I deploy cvat in k8s with helm chart, and all the pods are in the running status. Do you have any idea @bsekachev  ?
![image](https://user-images.githubusercontent.com/61957607/211600896-53c92e2b-c313-47d7-b266-5ba2eadfcb14.png)

**Comment by bsekachev** [comment]
@azhavoro 
Can you suggest something about k8s and helm?

**Comment by jpfleischer** [comment]
The solution is to
`export CVAT_HOST=mysite.com`
