### ISSUE TITLE
Cannot call canvas2d.draw API to draw a rectangle on the canvas

### ISSUE THREAD

**Issue by withtimesgo1115** [opencv/cvat#4629]
Hi, I tried to import the canvas2d module and then use its API to draw a  Rect shape instead of using cvat web labeling tools. However, after creating a canvas2d instance and mounting the canvas.html() to my root container element, I cannot draw a rectangle on the canvas. Actually, I can see the red lines to draw the rectangle shape but once I clicked the mouse, the shape cannot appear on the canvas anymore. I just call the API like this: 
```
c.draw({
      enabled: true,
      shapeType: 'rectangle',
      crosshair: true,
      rectDrawingMethod: 'By 2 points',
});
```
what's wrong with this, could anyone give me some kind of guidance? Thanks in advance!

**Comment by bsekachev** [comment]
Hi

Need more details to suggest, maybe code snippet, HTML code, etc.

**Comment by kirill-sizov** [comment]
Hi, @withtimesgo1115, Is this issue still relevant for you?

**Comment by withtimesgo1115** [comment]
> Hi, @withtimesgo1115, Is this issue still relevant for you?

Hey, Kirill, nope, actually I have solved the problem. Thank you for your reminder :)
