### ISSUE TITLE
Python SDK Support

### ISSUE THREAD

**Issue by manoj130** [opencv/cvat#4637]
I want to interact with CVAT in local server and docker with CMD using python script
is there a stable python API to create and upload and download data from CVAT

**Comment by bsekachev** [comment]
Hello,

We have only a CLI interface (https://github.com/openvinotoolkit/cvat/tree/develop/utils/cli), but actually it is not well spported and may not to work time to time. 
You can consider CVAT REST API as a quite stable and write a simple Python wrapper around it. Generally, having such SDK is a good idea, I believe.

**Comment by manoj130** [comment]
All i want to do is integrate this Cvat tool to my code and get access of annotations to a variable level

**Comment by nmichlo** [comment]
An official python API that matches the REST API would be an excellent feature. It would make development of many tasks much quicker too.

**Comment by dasturge** [comment]
@nmichlo any other way I could get the schema?  This doesn't seem to work on my instance, I get "The requested resource was not found on this server"

**Comment by nmichlo** [comment]
@dasturge Try starting your own CVAT instance locally?

```bash
git clone https://github.com/openvinotoolkit/cvat
cd cat
docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up
docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
```

Make sure to login at http://localhost:8080 before visiting http://localhost:8080/api/schema/?scheme=json

----------------

One thing I have noticed is that the returned schema from CVAT seems wrong. The generator is not able to generate a valid CLI, you need to go in and make manual changes to get it working.

**Comment by dasturge** [comment]
@nmichlo I tried these steps and they did not work for me.  Still "The requested resource was not found on this server".

**Comment by zhiltsov-max** [comment]
Hi, we have published `cvat-cli` package on PyPI. Install with `pip install cvat-cli`.
