### ISSUE TITLE
CVAT Version Update from v1.0.0 to v2.0.0 on AWS

### ISSUE THREAD

**Issue by mshaider-msh** [opencv/cvat#4643]
### Expected Behaviour
Successful loading of data after version upgrade 

### Current Behaviour
I was using CVAT v1.0.0 on Ubuntu 18.05 and followed steps on following link to create the backup,
Link: [https://openvinotoolkit.github.io/cvat/v1.5.0/docs/administration/advanced/backup_guide/#how-to-backup-all-cvat-data](https://openvinotoolkit.github.io/cvat/v1.5.0/docs/administration/advanced/backup_guide/#how-to-backup-all-cvat-data )
After running, `ls backup`, I got `cvat_data.tar.bz2` and `cvat_db.tar.bz2`. (Note: I didn't get `cvat_events.tar.bz2`)

After that I cloned latest version of v2.0.0 and followed steps on following link to upgrade CVAT,
Link: [https://openvinotoolkit.github.io/cvat/v1.5.0/docs/faq/ 
](https://openvinotoolkit.github.io/cvat/v1.5.0/docs/faq/ )

Using the backup files I generated earlier, I backup data again. 
But as a result of upgrade, I was able to access login accounts which were generated on older version and names of tasks are also loading but without any data and status. For status, I got across this link, 
Link: [https://github.com/openvinotoolkit/cvat/issues/4470 
](https://github.com/openvinotoolkit/cvat/issues/4470 )

Potentially, that could be the issue for status but data is not loading for any of the task/project

### Context
Tried to upgrade version of CVAT from v1.0.0 to v2.0.0

### Your Environment

Details of AWS
Instance type: t2.medium
Platform: Linux Ubuntu 18.05
Storage: Root device type is EBS volume having device name of /dev/sda1

**Comment by bsekachev** [comment]
There were difficult migration between 1.0 and 2.0. In our case it took a couple of days to finish. But it very depend on a number of data in CVAT. Could you provide ``docker logs cvat``?

**Comment by mshaider-msh** [comment]
Here is the text files with output of `docker logs cvat 
[cvat-logs.txt](https://github.com/openvinotoolkit/cvat/files/8720612/cvat-logs.txt)
`

**Comment by mshaider-msh** [comment]
@bsekachev do you think i missed some step during upgrade process? well, i tried to review all necessary information before starting upgrade process. 
During your upgrade process, what kind of issues did you face?

**Comment by bsekachev** [comment]
@azhavoro 
Could you please take a look?

**Comment by azhavoro** [comment]
@mshaider-msh Hello

Seems you have wrong data structure of CVAT data inside the CVAT container for some reason.
Unfortunately the log you attached is not full and does not contain any migration logs. Could you please also attach the migration log file:`docker cp cvat:/home/django/logs/migrations/0024_auto_20191023_1025.log .`

**Comment by mshaider-msh** [comment]
Thanks @bsekachev @azhavoro 

Output of that file is just, 

```
Start schema migration...

Schema migration is finished...

Start data migration...
```
It seems like migration didn't happen for whole data. What do you think I missed during whole process?

**Comment by azhavoro** [comment]
@mshaider-msh  If the migration log is empty, then your data has not migrated... I suggest deploying your old version, restoring your data from the backup, and trying to upgrade again. Also note that migrating from v1 to v2 may take some time depending on your data. Please let me know if you need help on these steps.

**Comment by mshaider-msh** [comment]
Alright, so here is the update. I used original version again and made another clone of that EC2 instance. On the cloned EC2 instance, I tried to make an upgrade of version again. This time, I am having following error, 

```
WARNING: The no_proxy variable is not set. Defaulting to a blank string.
Starting cvat_opa ... 
Creating cvat_redis ... error
Starting traefik    ... 
Creating cvat_db    ... 

ERROR: for cvat_redis  Cannot create container for service cvat_redis: Conflict. The container name "/cvat_redis" is already in use by container "8705221087b43a724f32bc61cda7e35b1023dc8c0f60def8a5f241798Starting cvat_opa   ... done

Starting traefik    ... done
 You have to remove (or rename) that container to be able to reuse that name.

ERROR: for cvat_redis  Cannot create container for service cvat_redis: Conflict. The container name "/cvat_redis" is already in use by container "8705221087b43a724f32bc61cda7e35b1023dc8c0f60def8a5f241798f851fb7". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for cvat_db  Cannot create container for service cvat_db: Conflict. The container name "/cvat_db" is already in use by container "742af25e38c4952afbb32ad73cdd5050eff3c50749a95581421fda7a640d04c9". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

```
Before running upgrade process, I made sure that, all docker containers are stopped (using `docker-compose stop`). Also, I made sure that no container is running by using `docker ps`. Also, I cloned new version of CVAT in a different folder and running the upgrade process there. And output of `my docker volume` ls is:
```
...
local     c4b1b0ce1c1f57db15a007897420ec80fd24f576428bfba02f77dd0008f95aae
local     c37b6bf9287e8961fa39c214e8dcd743c383ffcfd276a235d67c9175add04cff
local     cbb66614870f2cac4aef746348eef4b86b03929d9b276412c49e12acc69c163a
local     cvat_cvat_data
local     cvat_cvat_db
local     cvat_cvat_events
local     cvat_cvat_keys
local     cvat_cvat_logs
local     cvat_cvat_models
local     cvat_data
local     loren_cvat_cvat_data
local     loren_cvat_cvat_db
local     loren_cvat_cvat_keys
local     loren_cvat_cvat_logs
local     loren_cvat_cvat_models
local     d916f85bf3318136ba49ecfc0d49efe70cf1523441900ddb79c4e1c937ff4417
local     f292d89eb5744efbe80dcfeadd2a37b771f5d59422c6a6ad2c3714d090de9557
local     ffb56da3f47131b339f7d92290c35849813424af7356be6e72759c902d817a66
...
```
I have two folders for CVAT repo. 'loren_cvat' (old version v1.0.0 of already running CVAT) and 'cvat' (new CVAT repository which I cloned from GitHIb). So, probably, above docker volumes are from them. My question is, according to error, if i remove or rename the volumes which it is showing in-use then wouldn't I losing all data? I don't want to loose data during upgrade process so what will be the best work way around?

**Comment by mshaider-msh** [comment]
Here I have attached the cvat logs file also. @azhavoro kindly let me know what should be the best way forwar
[cvat-logs-file.txt](https://github.com/openvinotoolkit/cvat/files/8887609/cvat-logs-file.txt)
d

**Comment by kirill-sizov** [comment]
Hi, @mshaider-msh, Is this question still relevant for you?

**Comment by nmanovic** [comment]
Please read the guide. We can help you with the upgrade as commercal support.  I will close the issue. Don't hesitate to contact us with any other questions.
https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/
