### ISSUE TITLE
Helm Chart minor problems

### ISSUE THREAD

**Issue by Keramblock** [opencv/cvat#4651]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
Right now commit to helm chart broke the way postgresql secret was supposed to work with external db, and replaced it with constants in deployment for every installation except bundled postgresql chart from bitnami
<img width="1079" alt="изображение" src="https://user-images.githubusercontent.com/3233532/169787971-3f0fbf61-4663-4632-8f66-24c51cc6c012.png">

### Possible Solution
we should revert that and also add rules.tar.gz to .gitignore 
I will try to do it myself when I will have time for that

### Context
Right now my installation will be  broken on update

### Your Environment
k8s, helm

**Comment by Keramblock** [comment]
P.S. if one want to hardcode his psql settings - he could use postgresql.secret.create: true in override.variables.yaml for that

**Comment by nmanovic** [comment]
@Keramblock , I believe the current version of the helm chart in CVAT should have all your changes. Also, we changed the way how we prepare and send rules. I will close the issue.
