### ISSUE TITLE
Support ARM CPU

### ISSUE THREAD

**Issue by aarunjith** [opencv/cvat#4654]
### My actions before raising this issue
- [ x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x ] Searched [past issues](/issues)

### Expected Behaviour
docker-compose -up should work out of the box

### Current Behaviour
<img width="528" alt="image" src="https://user-images.githubusercontent.com/34453139/169843365-600f2d53-9375-41a8-9211-0be847090770.png">
cvat_ui and cvat_opa containers failing with docker entrypoint error. I searched online for this issue and it seems like fixing a shebang is the issue

### Steps to Reproduce (for bugs)
Followed the steps in the installation guide on a ubuntu 20.04 machine.

### Your Environment
- Git hash commit (`git log -1`): commit 71515ba662eab96554a2f7f3b02375385f680ebd
Author: Nico Galoppo <nico.galoppo@intel.com>
Date:   Sun May 15 22:35:50 2022 -0700

    Revert Open3D to 0.11.2

    This change fixes a dependency conflict that causes a very old version
    of Jinja2 to be installed (see #4618). Open3D is only used for PCD
    conversion, so this reverting to an older version is acceptable.

    This is a temporary workaround. As a future update we'd like to get rid
    of the Open3D dependency, since it pulls in a bunch of unnecessary
    dependencies. Also, we'd like to make python dependency resolution more
    robust by pinning all (recursive) dependencies to specific versions with
    a tool like pip-tools or poetry.

commit ba4175bf5b4467bf0fbf89a3fd645cceef7f7c23
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Apr 12 19:05:28 2022 +0300

    Bump ansi-regex from 3.0.0 to 3.0.1 in /cvat-core (#4565)

    Bumps [ansi-regex](https://github.com/chalk/ansi-regex) from 3.0.0 to 3.0.1.
    - [Release notes](https://github.com/chalk/ansi-regex/releases)
- Docker version `docker version` (e.g. Docker 17.0.05): Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:01 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux, Ubuntu 20.04

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@aarunjith , you are right. ARM64 isn't well supported by us at the moment. Need to use correct OPA docker image (see OS/ARCH column): https://hub.docker.com/r/openpolicyagent/opa

Also in tests need to download right binaries: https://github.com/openvinotoolkit/cvat/blob/d7560bbd39fec68f944515c2591dda74f3764b90/.github/workflows/main.yml#L71

**Comment by haimat** [comment]
Hello everyone - we are also planning to install CVAT on one of our machines, which has an ARM processor.
Is this possible, and if so, what do I need to watch out for when installing CVAT on ARM?
