### ISSUE TITLE
Problem with localhost.

### ISSUE THREAD

**Issue by mikhailkonyk** [opencv/cvat#467]
Hi, people, I'm trying to install cvat, and i have a problem with localhost. It isn't openning. How do i fix this?
![Ошибка](https://user-images.githubusercontent.com/43651370/58765768-13bcec80-857f-11e9-8dcc-b22d64d36013.png)

**Comment by nmanovic** [comment]
@mikhailkonyk , please run `docker logs cvat` command and post here its output.

**Comment by nmanovic** [comment]
@mikhailkonyk , I will close the issue. Please ask your new questions in our Gitter channel.
