### ISSUE TITLE
how can react-code hot-reload  when i modify react-code

### ISSUE THREAD

**Issue by iFindWhatILove** [opencv/cvat#4671]
everytime when i change react-code in the filefolder of cvat-ui, i must run the command below:
1. docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
2. docker-compose up -d

otherwise, the new-code which i modified doesn't work. i don't know how to make it enable to hot-reload when i modify react-code

**Comment by bsekachev** [comment]
Hi @iFindWhatILove 

We do not support hot-reload when using Docker, I don't know what to suggest exactly. Probably you need to pass React source code somehow as a volume and redesign containers somehow. 

If you need hot-reload, you can use development environment, please, see [here](https://openvinotoolkit.github.io/cvat/docs/contributing/development-environment/).
