### ISSUE TITLE
Can't open jobs in CVAT due to "invalid mode is specified".

### ISSUE THREAD

**Issue by Hommus** [opencv/cvat#4673]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Current Behaviour

I'm using the CLI to upload tasks to CVAT, and it appears to work until you try and open a job, and then an error occurs: "Invalid mode is specified". After a bit of digging, it looks like the task and job mode are set to "", instead of "annotation". 

When uploading using the CLI, this problem only occurs _occasionally_, and I haven't been able to work out why.

### Possible Solution
Not a great solution, but I'm currently exporting the task and re-importing it back into CVAT. This seems to fix everything, but it does merge all the jobs into one.

### Steps to Reproduce (for bugs)
The only information I have for reproducing is the code I used to create the tasks:
```python
        subprocess.run(
            [
                "python",
                "/home/user/cvat/utils/cli/cli.py",
                "--auth",
                f"{USER}:{PW}",
                "--server-host",
                CVAT_HOST,
                "--server-port",
                CVAT_PORT,
                "create",
                "--annotation_format",
                "Segmentation mask 1.1",
                "--overlap",
                "0",
                "--image_quality",
                f"{image_quality}",
                "--project_id",
                f"{project_id}",
                "--segment_size",
                f"{segment_size}",
                f"{task_name}",
                "local",
                *images,
            ]
        )
```

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    2022-06-06 04:57:32,355 DEBG 'runserver' stderr output:
    [Mon Jun 06 04:57:32.355742 2022] [wsgi:error] [pid 359:tid 139648624416512] [remote xxx.xx.x.x:xxxxx] INFO - 2022-06-06 04:57:32,355 - views - {"client_id":533480,"name":"Send user activity","time":"2022-06-06T04:57:32.307000Z","payload":{"working_time":9731},"is_active":true,"username":"xxx-xxx"}
    </details>

**Comment by Marishka17** [comment]
I'll close this issue now because I can create a task with cli and open the job after that without errors. Please try the latest CVAT cli version and don't hesitate to reopen the issue if it is still relevant.
