### ISSUE TITLE
404 page not found error

### ISSUE THREAD

**Issue by bely66** [opencv/cvat#4676]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I deployed CVAT using the docs docker on Azure machine with Ubuntu 18.04 and set the `CVAT_HOST=0.0.0.0` initially 
### Current Behaviour

What I was getting is 404 page not found on mydomain:8080
and the Traefik container logs showed:
`Cannot start the provider *file.Provider: unable to read directory /etc/traefik/rules: open /etc/traefik/rules: no such file or directory`

### Possible Solution

Maybe having a way to add /etc/traefik/rules directory would help.
I tried to change the host to `CVAT_HOST=mydomain` and nothing happened
### Your Environment

- Git hash commit (`git log -1`): 
commit d7560bbd39fec68f944515c2591dda74f3764b90 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: ba4175bf b7dba6aa
Author: Nico Galoppo <nico.galoppo@intel.com>
Date:   Tue May 17 11:25:58 2022 -0500
Merge pull request #4639 from openvinotoolkit/ncgalopp/fix-build

- Docker version 20.10.12, build e91ed57
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Other diagnostic information / logs:
level=error msg="Cannot start the provider *file.Provider: unable to read directory /etc/traefik/rules: open /etc/traefik/rules: no such file or directory" from the

**Comment by bely66** [comment]
@waqarsqureshi  Sorry for the late reply, I'm getting this error when I use the out of the box, docker-compose.yml

when I run docker-compose up -d on the azure remote machine after I set the CVAT_HOST env variable.

I try to access it using: machine_ip_address:8080. 
it shows me 404 not found

**Comment by Shooskay** [comment]
Oh! 
I try access  http://localhost:8080   get  login page

firefox access by  https://  automatically

**Comment by Shooskay** [comment]
Itry Google chrome  
I got "404 page not found" 

orz

**Comment by Shooskay** [comment]
I try  Traefik dashboard

access to http://wpc5054.cs.oki.co.jp:8090/

I got 
404 page not found

**Comment by Shooskay** [comment]
oh!
docker-compose down
export CVAT_HOST=cvat.mydomain.example.com
docker-compose up -d

access to http://CVAT_HOST=cvat.mydomain.example.com:8080

I got login page

**Comment by lucasrodri** [comment]
@Shooskay your solution worked for me. Thank you very much!!!

**Comment by spped2000** [comment]
sudo usermod -aG docker $USER
sudo chmod 666 /var/run/docker.sock

sudo apt-get install unzip
export CVAT_VERSION="v2.2.0"
cd cvat
docker compose down
cd ..
mv cvat cvat_170
wget https://github.com/opencv/cvat/archive/refs/tags/${CVAT_VERSION}.zip
unzip ${CVAT_VERSION}.zip && mv cvat-${CVAT_VERSION:1} cvat
cd cvat
docker pull cvat/server:${CVAT_VERSION}
docker tag cvat/server:${CVAT_VERSION} openvino/cvat_server:latest
docker pull cvat/ui:${CVAT_VERSION}
docker tag cvat/ui:${CVAT_VERSION} openvino/cvat_ui:latest

docker stop $(docker ps -aq)
docker compose up -d

**Comment by oerx** [comment]
My issue was resolved by noticing the 90% disk space warning in the logs, which led me to free up more space. After doing that, the container started working again.
