### ISSUE TITLE
upload annotation coco 1.0 using API

### ISSUE THREAD

**Issue by yvpaulo** [opencv/cvat#4677]
Hello Guys

I tried to upload annotations in coco format using the api: http://cvat-....com:8080/api/tasks/46/annotations/?format=COCO%201.0' 
Cod:
 url = f"{host_cvat}/api/tasks/{task_id}/annotations/?format={data_format}"
    
    with open(annot_json_path, encoding='utf-8') as annot_json:
        annot_json_data = json.load(annot_json)
   
    payload = json.dumps({
    "annotation_file": annot_json_data # ou [annot_json_data]
    })
    headers = {
    'accept': '*/*',
    'Content-Type': 'application/json',
    'Authorization': f'Token {Token}'
    }

    response = requests.request("PUT", url, headers=headers,
                                data=payload
                               )
But when I upload the files I get the following error:
{"annotation_file":["The submitted data was not a file. Check the encoding type on the form."]}

if I use this in request: files={'annotation_file': open(f'./{annot_json_path}', 'r')}
return this error: '{"detail":"JSON parse error - Expecting value: line 1 column 1 (char 0)"}'

The json file not have problem, Because ai can upload using the IDE, but not using API.
I need your help please.
Thanks

**Comment by zhiltsov-max** [comment]
Hi. Please check the [CLI](https://github.com/openvinotoolkit/cvat/blob/develop/utils/cli/core/core.py#L200-L215) for an example.

**Comment by yvpaulo** [comment]
Is it necessary for the file to be zipped? or a json? Thanks.

**Comment by zhiltsov-max** [comment]
No, it depends on the format. You can find information about accepted files [here](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/). For COCO format, you can send a json or a zip.

**Comment by zhiltsov-max** [comment]
I'll close the issue. Please feel free to reopen if there are any other questions.
