### ISSUE TITLE
Cannot upload annotation files larger than 1 MB (413 Request Entity Too Large)

### ISSUE THREAD

**Issue by ninafiona** [opencv/cvat#4679]
I sucessfully created a task with 750 images and now want to upload an annotation file (COCO) that is of file size 1.2MB. I get the following error:

> ``` Failed to load resource: the server responded with a status of 413 ()```
```cvat-app.tsx:262 Error: Request failed with status code 413. "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.21.6</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n". ```

I tried removing some annotations which shrunk the file size to 800kB and then the upload succeeded. How can I upload larger files?

**Comment by stevezkw1998** [comment]
@Marishka17 The fix for this issue was on Mar 11, 2022
However this issue also happened in 2.7.2 which was released on Sep 26

It doesn't make sense why later version still has this issue.
