### ISSUE TITLE
CVAT Website Won't Upload Photos (AttributeError: 'NoneType' object has no attribute 'seek')

### ISSUE THREAD

**Issue by burnsmj** [opencv/cvat#4680]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I am currently using the cvat.org website to upload images for annotation.  I currently have a few hundred images in one of my projects, but recently when trying to upload more I get the error pop-up: Error: Could not create the task on the server. AttributeError: 'NoneType' object has no attribute 'seek'.  I am not much of a computer person (hence using the website as opposed to the CLI), so I am not sure what this means.  I tried adding an attribute to the label in my project (something that wouldn't change the data I am getting) and this didn't help.  I also tried uploading single images and images I have gotten to work in the past and it didn't change anything.  

My current set up is:
- Multiple tasks within a single project
- One label (this is all I need; now with an attribute that is set to True of False) 
- Create new task within a project
- Trying to upload 100 images from a local folder (previously have done over 300 in a single upload)
- 100% Image quality
- Use Zip Chunks = Y
- Use Cache = Y
- Sorting Method = Random
- Format = CVAT for Images 1.1

Everything starts out normal, and then I get the above error pop-up after about 5 seconds.

### Expected Behaviour
Images upload to new CVAT task.

### Current Behaviour
Error pops up after about 5 seconds of uploading - Error: Could not create the task on the server. AttributeError: 'NoneType' object has no attribute 'seek'.

### Steps to Reproduce (for bugs)

1. Create new task
2. Name task "JUNK"
3. Create label "Label"
4. Drag files from computer folder (1 image, 999kb, 572x581pixels, RGB, .tif, no alpha) Note: Provided as a jpeg because github does not support tif files.
5. Expand advanced configurations
6. Sorting method = Random
7. Use zip chunks = checked
8. Use cache = checked
9. Image quality = 100
10. Format = CVAT for images 1.1
11. Click submit
12. Wait 5 seconds

### Context
I am trying to determine area coverage by a blue stain in sample images.  To do so I am using polygons to select the stained area.

### Your Environment
MacOS Version 12.3.1
Chrome Browser Version 100.0.4896.75 (Official Build) (x86_64)

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
<img width="394" alt="Screen Shot 2022-06-08 at 12 04 53 PM" src="https://user-images.githubusercontent.com/55208620/172675360-d546d780-64de-495f-bc94-10c8a3298b5e.png">
![2FACC_20220406_1](https://user-images.githubusercontent.com/55208620/172675520-7dd7df50-616c-4717-821c-db39a82f699f.jpg)

**Comment by bsekachev** [comment]
Now it online in read only mode.
Users are able to move their data to https://app.cvat.ai
cvat.org will be maintained for some period of time and then disabled forever.
