### ISSUE TITLE
Save page crashes when annotating more than 1000 images

### ISSUE THREAD

**Issue by zoujiali1996** [opencv/cvat#4681]
An image with more than 1000 marks will crash the page, and at 500 marks the page will render slowly and stagger
![image](https://user-images.githubusercontent.com/64458501/173028280-69b00831-9145-41a5-aba5-f12d1c19d1b3.png)
<img width="788" alt="df8c05d3ddd219895accecf0df9e90a" src="https://user-images.githubusercontent.com/64458501/173028329-a77814d5-eba2-41f9-9056-9b3997c3dcff.png">

**Comment by jessonzj** [comment]
> Save page crashes when annotating more than 1000 images ![middle_img_v2_e7900326-4bb9-44dd-8fa0-7ed46ad5ff1g](https://user-images.githubusercontent.com/64458501/172759832-99f66816-c387-4a09-b14d-b61d56eb986a.png)

> the error code is `SBOX_FATAL_MEMORY_EXCEEDED` ? And I have the same problem.
> <img width="1074" alt="image" src="https://user-images.githubusercontent.com/42288290/172804165-67a985c5-43f3-44b5-bf37-9992aeb5597b.png">

**Comment by bsekachev** [comment]
There was many improvements since then, I will close the issue.
