### ISSUE TITLE
Could not  check authorization on the server and Could not get user agreements from the server

### ISSUE THREAD

**Issue by chendust** [opencv/cvat#4683]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Current Behaviour

docker starts without errors.i am getting the following error:
<img width="1440" alt="企业微信截图_c7e77c7e-a1d5-49ce-be39-d1a52d3fa816" src="https://user-images.githubusercontent.com/54810996/172823425-f05e23a7-2664-4a72-8a6e-761a511b94af.png">
<img width="545" alt="企业微信截图_aad36fbe-7328-4a52-959f-697ec697f44e" src="https://user-images.githubusercontent.com/54810996/172823445-2dbf8b5e-07aa-487a-b818-fdfef53b1fba.png">

### Possible Solution

I have tried to hange the port 8080 and 8090,but it didn't work!

### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): MacOS

**Comment by Petros626** [comment]
for me the same, working on it couldn't save annotations, couldn't log out...

**Comment by nmanovic** [comment]
Please send your questions about CVAT.org to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope they will help and answer.

**Comment by Petros626** [comment]
Sorry for the late reply, I will do

**Comment by Petros626** [comment]
> Sorry for the late reply, I will do, but isn't this repo for the issues?

**Comment by nmanovic** [comment]
Please migrate your tasks to [CVAT.ai](http://cvat.ai/). Use the following instructions: https://cvat-ai.github.io/cvat/docs/faq/#how-to-migrate-data-from-cvatorg-to-cvatai

**Comment by Huxwell** [comment]
I get the same problem in Nov 2022 with the lastest changes in CVAT; but the ticket is closed.
Has it been fixed, does it only affect some specific setup, were you able to replicate it or is there a specific action that solves this problem?
To me this is an app-breaking bug.
