### ISSUE TITLE
Unable to create task in CVAT. Keeps throwing 500 error in browser console.

### ISSUE THREAD

**Issue by igloopigloo** [opencv/cvat#4684]
### My actions before raising this issue
Searched for the solution. Seems to be an issue with my images (not sure). But I still need some clarification.

### Expected Behaviour
Should be able to create task on clicking submit button.

### Current Behaviour
It keeps throwing error message. It worked once with some random picture downloaded from google. But not anymore.

### Possible Solution
Please tell me what images it supports, if that's an issue.

### Steps to Reproduce (for bugs)

1. Create account
1. Add labels
1. Uploaded images (tried with different kinds) (have attached my images here)
![first](https://user-images.githubusercontent.com/101135348/172857795-7710429f-f0c2-4b49-ac6f-308bf4e91181.PNG)
![second](https://user-images.githubusercontent.com/101135348/172857798-a02be72a-3b70-4a57-854c-e470536fd8d6.PNG)
![third](https://user-images.githubusercontent.com/101135348/172857799-b23e1943-a312-469c-9efc-0571a90caed4.PNG)
 
1. Click Submit

### Context
I am learning image segmentation, but now want to use my own dataset.

### Your Environment
Using online CVAT on google chrome.

**Comment by Petros626** [comment]
same problem for me since yesterday, dont know whats wrong with the server

**Comment by nmanovic** [comment]
Please send your questions about CVAT.org to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope they will help and answer.

**Comment by nmanovic** [comment]
@Petros626 , @igloopigloo , CVAT.org should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is supported by CVAT core team. Please try our new repository: https://github.com/cvat-ai/cvat

**Comment by Petros626** [comment]
> @Petros626 , @igloopigloo , CVAT.org should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is supported by CVAT core team. Please try our new repository: https://github.com/cvat-ai/cvat

was my mistake I tried to use CVAT via link address in repi, but must be runned on localhost via Docker.

**Comment by bsekachev** [comment]
Now it online in read only mode.
Users are able to move their data to https://app.cvat.ai
cvat.org will be maintained for some period of time and then disabled forever.
