### ISSUE TITLE
Annotation not being exported

### ISSUE THREAD

**Issue by kaichand9** [opencv/cvat#4686]
Hi , I am new to CVAT. Started Image labelling using CVAT tool. Steps followed are mentioned below:

Created login & using on chrome window - URL - https://cvat.org/tasks?page=1 (Using windows 10 as operating system)
Created new Project and Task - Created New Labels - Unloaded and loaded blast hole for mining site
Added Photos by Click drag files into this area.
One by one created label/annotation using all JPG/Photos.
After completing job. When exporting annotated/labeled data in Pascal Voc 1.1 or segmentation mask 1.1. It is creating blank files
No details of polygons there inside the folders. Only photos copied back.
Can anyone suggest why export data is not working. Do i need to install CVAT or I need to create local host using IIS manager or making any mistake, your support is highly appreciated
Exporting zip but polygon location not being exporting

**Comment by nmanovic** [comment]
Please send your questions about CVAT.org to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope they will help and answer.

**Comment by kaichand9** [comment]
Hi Nikita,

Thanks for your reply.Can you help me in this. Really appreciate it

XML generating using online is shown below. not having details of
annotation.

[image: Voc-xml.JPG]

Thanks & Regards
Kailash Chand Jangid
Sr. Photogrammetry Specialist,
http://www.thiess.com,
Mo. No. - 09810134398
