### ISSUE TITLE
Could not login at CVAT.org, Keeps signing out logged in  users

### ISSUE THREAD

**Issue by MosesNjau** [opencv/cvat#4688]
This tool is not stable for the last 36 hours, Keeps signing out logged-in users, does not save annotations, and can't create tasks.

After every 30 minutes or so, it seems to work then all issues stated above reappear.

Any fixes?
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/37952315/173186514-3fbaf216-497a-4667-b060-c373207eab56.png">

**Comment by nmanovic** [comment]
Please send your questions to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum.

**Comment by bsekachev** [comment]
Now it online in read only mode.
Users are able to move their data to https://app.cvat.ai
cvat.org will be maintained for some period of time and then disabled forever.
