### ISSUE TITLE
CVAT DISCONTINUED?

### ISSUE THREAD

**Issue by sezarxray** [opencv/cvat#4689]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Is cvat development stopped?
30 days without any change?

**Comment by alalek** [comment]
You could find some details here: https://github.com/openvinotoolkit/cvat/issues/4444#issuecomment-1141066544

**Comment by nmanovic** [comment]
@sezarxray ,

The short answer is no. Please send your questions to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum.

**Comment by nmanovic** [comment]
@sezarxray , CVAT.org should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is supported by CVAT core team. Please try our new repository: https://github.com/cvat-ai/cvat

**Comment by bsekachev** [comment]
Now it online in read only mode.
Users are able to move their data to https://app.cvat.ai
cvat.org will be maintained for some period of time and then disabled forever.
