### ISSUE TITLE
Localhost cvat doesn't recognize my new password after I reset it on cvat.org

### ISSUE THREAD

**Issue by NinjaDev06** [opencv/cvat#4690]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour
I should be able to connect into my localhost CVAT after I reset my password on cvat.org.

### Current Behaviour
I got the following error when I trying to use my old or new password :
```
Could not login on the server
Error: Request failed with status code 400. {"non_field_errors":["Unable to log in with provided credentials."]}.
```

### Possible Solution
I have three suggestions and I'm open to anything that allow me to get my several weeks of annotation:
1. My new password work on my localhost instance.
2. I have a way to extract all the annotation I made to import them back into cvat.org
3. I can change the ownership of the project to a new account

### Steps to Reproduce (for bugs)
1. Lost my password
1. Tried to reset my password from my localhost instance, but without success, Got the error "Could not reset password on the server."
1. Reset my password on cvat.org
1. Can login into cvat.org
1. Can't login into my localhost cvat

### Context
I lost my access to all the annotations I made. It's several weeks of effort I lost.
My goal is to get back the work I did.

### Your Environment

- Git hash commit (`git log -1`): 3bd7c7e4
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 4.3.2
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@NinjaDev06 , your localhost and CVAT.org are two different and unconnected instances of CVAT. If you reset your password on CVAT.org, you reset it only on CVAT.org. Your own CVAT instance on localhost is a separate instance with a separate DB. They don't know about each over. You can create a new admin user using createsuperuser command in console (see the installation guide).
