### ISSUE TITLE
Delete Files Directly from the Storage 

### ISSUE THREAD

**Issue by varungupta31** [opencv/cvat#4691]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Context

The storage of the server on which my CVAT is hosted, is full. This resulted the CVAT to be offline. 
I wish to create some space just to use commands like dump (to create annotation backup), and then delete (to free up space).
However, currently, since the server storage is full the CVAT has become unresponsive, and is giving errors to CLI commands as well. 

How Can I free up space directly from the disk? (i.e. I'm having difficulty locating where the annotations and tasks are saved)

I have read the past discussions, but I'm unable to locate any directory: `cvat_data`

### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Server Version: 1.6
- Core Version: 3.16.0
- Canvas Version: 2.7.0
- UI Version: 1.23.1

**Comment by waqarsqureshi** [comment]
#4675 mentions the folders. Access them through root or using sudo. Use the Ubuntu File Explorer Nautilius in sudo mode. Type sudo nautilius &. A new window of nautilus will open. It should give the access to the folders mentioned in #4675

**Comment by varungupta31** [comment]
@waqarsqureshi thanks for the prompt response :)
I will look into this, meanwhile I resolved the issue by creating space by removing other files from the system. I will keep the discussion active, till I check out your suggestion and find the desired answer.
