### ISSUE TITLE
V2.1.0 Search Bar Not Working

### ISSUE THREAD

**Issue by hamzahzmalik** [opencv/cvat#4697]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
The search bar used to function in previous versions as described here in the documentation
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/search/

### Current Behaviour
The search bar is only working for strings and I cannot search based on id or assignee or status, etc.

### Your Environment
- Git hash commit (`git log -1`):
  d7560bbd39fec68f944515c2591dda74f3764b90
- Docker version `docker version`:
  20.10.16
- Are you using Docker Swarm or Kubernetes?
  No
- Operating System and version (e.g. Linux, Windows, MacOS):
   Ubuntu 20.04

**Comment by bsekachev** [comment]
@hamzahzmalik 

Hi, looks like documentation was not updated. Please, use "Filters" button (which is at the right), it is much more powerful. Search now works by matching within different fields

**Comment by ChengYongfei** [comment]
The dev branch has a bug in cvat-core/src/api-implementation.js line 233 @bsekachev 
` if (['id', 'page', 'search', 'sort', 'page', 'filter'].includes(key)) `  add 'filter' in this line

**Comment by bsekachev** [comment]
Thank you for report @ChengYongfei
