### ISSUE TITLE
The Online Server Failed

### ISSUE THREAD

**Issue by DataPrincess-5418** [opencv/cvat#4700]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

It should be able to login and turn to the project page

### Current Behaviour

It fails to work
![1655486727155](https://user-images.githubusercontent.com/76899663/174348296-98ff9cd6-2ebd-4ae4-aaae-0f4457729a05.png)

### Possible Solution

I have no idea what's going on. I have tried this on multiple browsers and none of them works. My teammates' web also got the same problem.

### Context

I have been use the website for past months, and it works perfectly. I really hope that I could go back to use this to annotate the video

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@DataPrincess-5418 ,

Please send your questions and complains to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope that they should help if so many users are unhappy.

**Comment by JohnLee16** [comment]
@DataPrincess-5418  Hi, have your problem been fixed?

**Comment by VishalBalaji321** [comment]
It is still not fixed.

**Comment by nmanovic** [comment]
@VishalBalaji321 , @JohnLee16 , @DataPrincess-5418 , CVAT.org should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is supported by CVAT core team.

**Comment by nmanovic** [comment]
Migrate your data to [CVAT.ai](http://cvat.ai/): https://cvat-ai.github.io/cvat/docs/faq/#how-to-migrate-data-from-cvatorg-to-cvatai

**Comment by DataPrincess-5418** [comment]
Yes, it has been solved, thanks )
