### ISSUE TITLE
Could not login on the server

### ISSUE THREAD

**Issue by Smogulove** [opencv/cvat#4703]
Hello i am using the web site version of CVAT and recently it started to throw the error while i and my colleagues trying to login "Could not login on the server"
Some days there is no error at all and it works fine, but only some days...
I have googled it, but all the answers are about local github version of CVAT, what about online web version? 
thank you
![asd](https://user-images.githubusercontent.com/21981483/174637929-6ee00d68-1124-44f3-82e0-e8ddf200d936.png)

**Comment by nmanovic** [comment]
@Smogulove , Please send your questions and complains to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope that they will help.

**Comment by Bouye** [comment]
I have the same issue(CVAT the online version) and sometimes when i delete cookies the server let me in but at the moment i can't access it at all.
Can anyone help ?

**Comment by strcom** [comment]
Try to login on private mode of your browser (this mode is available for chrome, firefox and other browsers). I noticed on other sites (not sure for CVAT) than browser cache sometime is not updating even that updated with ctrl+f5. So I allways recommending first to use private mode of the browser.

> I have the same issue(CVAT the online version) and sometimes when i delete cookies the server let me in but at the moment i can't access it at all. Can anyone help ?

**Comment by Bouye** [comment]
> Try to login on private mode of your browser (this mode is available for chrome, firefox and other browsers). I noticed on other sites (not sure for CVAT) than browser cache sometime is not updating even then updated with ctrl+f5. So I allways recommending first to use private mode of the browser.
> 

I tried but unfortunately the problem remains.

**Comment by prassivenky** [comment]
Hello,
Might be a silly question but if the situation persists for a really long time as nmanovic hinted above, is it sensible to download and install CVAT offline for Windows or is it also going to be problematic. 
Thanks,
Prassi

**Comment by strcom** [comment]
Try to change password. And also create new account. May be this is someone administrative error with your account personally? PS. I've never used online cvat - we are using locally hosted version of cvat in our case

> 
> I tried but unfortunately the problem remains.

**Comment by prassivenky** [comment]
> Try to change password. And also create new account. May be this is someone administrative error with your account personally? PS. I've never used online cvat - we are using locally hosted version of cvat in our case
> 
> > I tried but unfortunately the problem remains.

I tried changing my password too and it does not work, also I guess opening a new account makes it impossible to transfer existing open tasks from the old acc to the new one.

**Comment by strcom** [comment]
Here #4715 I see there was errors with access. This can be reason you cant login today. Creating new account only checks that system is working (in service). I recommending creating your own hosted version of cvat for your company (we did so).

**Comment by strcom** [comment]
May be I'm not right, and developers of CVAT will beat me today ))) But i dont belive that online verson of cvat is productive-oriented. So, we have our own locally hosted server in our company (also you can do it on any other docker-hosting providers or vps hosting). 
This is Linux machine with enough disk space and memory, Also we have installed: docker + docker-compose. And after that we can start [docker-compose.yaml](https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.yml) that is part of source code CVAT. (Also in new version (>2) we have rules https://github.com/openvinotoolkit/cvat/tree/develop/cvat/apps/iam/rules copy on server). Thats all. Also we connected directory with images to cvat-docker-container:
- /mnt/cvat:/home/django/share:ro
And can access locally mounted dirs with images in CVAT.
And admin panel also accessible with controlling local users.

> I am sorry but could you elaborate ? Do you mean I should download and install CVAT offline ? Did that work for you ?

**Comment by Akashbhukt** [comment]
@strcom Can you help to install the cvat tool on my windows computer. From start to end. I am facing the problem from two days.

**Comment by strcom** [comment]
There is your plan (I can't write detail plan in comment):
1) Install docker for windows (https://runnable.com/docker/install-docker-on-windows-10)
2) Install docker-compose (https://docs.docker.com/compose/install/compose-desktop/)
3) You need learn docker/docker-compose in base (how to run/stop containers on docker-compose, what is containers and images in docker)
4) Download file https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.yml and save on folder (exp. "d:/CVAT")
5) Download and copy files https://github.com/openvinotoolkit/cvat/tree/develop/cvat/apps/iam/rules (better way to get from zip of source code cvar https://github.com/openvinotoolkit/cvat/archive/refs/heads/develop.zip, also you can get file docker-compose.yml for step 4 from this zip-file)
Get this folder from zip /cvat-develop/cvat/apps/iam/rules and place in folder d:/CVAT/cvat/apps/iam/rules 
In original docker-compose.yml you can see such an option to send rules to contaner OPA:
./cvat/apps/iam/rules:/rules
6) Here i don't know how exactly start docker-compose.yml from Windows, but can suppose that this is like in linux. From local folder local folder "d:/CVAT" from power-shell console or command line (cmd.exe) start command:
docker-compose up -d
To stop containers from folder "d:/CVAT":
docker-compose down
7) After that you can access local version cvat:
http://localhost:8080
8) You need to create super user for access admin console of CVAT
Command from powershell or command line:
docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
There will be some questions about admin login and password.
9) After that you can access admin console of CVAT:
http://localhost:8080/admin
And create users and give them roles
10) After that you can access CVAT
http://localhost:8080
11) For share CVAT for corporate work - you can configure your Windows Defender so, anybody on local network can access your local hosted CVAT
12) IF you need change password of super user run command from powershell or console:
docker exec -it cvat bash -ic 'python3 ~/manage.py changepassword ADMIN'
where ADMIN - is a name of your superuser
13) For access local images on you PC you must share folder with images for locally hosted CVAT service.
For that you must modify docker-compose.yml:
...
cvat:
    container_name: cvat
    ...
    volumes:
      - PATHTOLOCALFOLDER:/home/django/share:ro
where PATHTOLOCALFOLDER is your local folder with images
After that you can access local images without need to copy them to cvat. This is optional, but your local copy of CVAT can be faster.

> @strcom Can you help to install the cvat tool on my windows computer. From start to end. I am facing the problem from two days.

**Comment by prassivenky** [comment]
> There is your plan (I can't write detail plan in comment):
> 
>     1. Install docker for windows (https://runnable.com/docker/install-docker-on-windows-10)
> 
>     2. Install docker-compose (https://docs.docker.com/compose/install/compose-desktop/)
> 
>     3. You need learn docker/docker-compose in base (how to run/stop containers on docker-compose, what is containers and images in docker)
> 
>     4. Download file https://github.com/openvinotoolkit/cvat/blob/develop/docker-compose.yml and save on folder (exp. "d:/CVAT")
> 
>     5. Download and copy files https://github.com/openvinotoolkit/cvat/tree/develop/cvat/apps/iam/rules (better way to get from zip of source code cvar https://github.com/openvinotoolkit/cvat/archive/refs/heads/develop.zip, also you can get file docker-compose.yml for step 4 from this zip-file)
>        Get this folder from zip /cvat-develop/cvat/apps/iam/rules and place in folder d:/CVAT/cvat/apps/iam/rules
>        In original docker-compose.yml you can see such an option to send rules to contaner OPA:
>        ./cvat/apps/iam/rules:/rules
> 
>     6. Here i don't know how exactly start docker-compose.yml on Windows, but can suppose, that this is like in Linux. From local folder "d:/CVAT"  in power-shell console or command line (cmd.exe) start command:
>        docker-compose up -d
>        Later (after work) you can stop containers from folder "d:/CVAT":
>        docker-compose down
> 
>     7. After that you can access local version cvat:
>        http://localhost:8080
> 
>     8. You need to create Super User for access CVAT admin console
>        Command from powershell or command line:
>        docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
>        There will be some questions about admin login and password.
> 
>     9. After that you can access admin console of CVAT:
>        http://localhost:8080/admin
>        And create users and give them roles
> 
>     10. After that you can access CVAT
>         http://localhost:8080
> 
>     11. For share CVAT for corporate work - you can configure your Windows Defender so, anybody on local network can access your local hosted CVAT
> 
>     12. IF you need change password of super user run command from powershell or console:
>         docker exec -it cvat bash -ic 'python3 ~/manage.py changepassword ADMIN'
>         where ADMIN - is a name of your superuser
> 
>     13. For access local images on you PC you must share folder with images for locally hosted CVAT service.
>         For that you must modify docker-compose.yml:
>         ...
>         cvat:
>         container_name: cvat
>         ...
>         volumes:
>         - PATHTOLOCALFOLDER:/home/django/share:ro
>         where PATHTOLOCALFOLDER is your local folder with images. And restart docker services of CVAT.
>         After that you can access local images without need to copy them to cvat. This is optional, but your local copy of CVAT can be faster.
> 
> 
> > @strcom Can you help to install the cvat tool on my windows computer. From start to end. I am facing the problem from two days.

There is one problem on Windows and WSL which makes it next to impossible to work with CVAT. I think everyone would face this. The Docker Desktop takes almost 95 Percent of the memory because of the vmmem exe file and the solution to this has been a hit and miss for me. So, even though I could install it, I basically cant annotate a single frame because it just hangs forever. Anyone who knows a more reliable method than the .wslconfig method, please let me know. Thanks...

**Comment by nmanovic** [comment]
@Smogulove , @strcom , @Bouye , @prassivenky , CVAT.org should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is supported by CVAT core team.

**Comment by nmanovic** [comment]
Please use our new online seriver [CVAT.ai](http://cvat.ai/): https://cvat-ai.github.io/cvat/docs/faq/#how-to-migrate-data-from-cvatorg-to-cvatai

**Comment by sangeun-jo** [comment]
I removed browser cache and it worked.
