### ISSUE TITLE
Cannot upload files to a newly created task using the REST API

### ISSUE THREAD

**Issue by FeryET** [opencv/cvat#4704]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I cannot attach files to a newly created task using the REST API.

### Expected Behaviour
Being able to do so.

### Current Behaviour
Currently, the `api/tasks/{id}/data` endpoint which can be used to upload a file using the API is not working.

I am using `httpx` in the python client, there are no difference in using the three stage `Upload-Start`, `Upload-Multiple` and `Upload-Finish` or the all in one `Upload-Start` and `Upload-Multiple` headers. 

```python
images = [("client_files", ("filename.png", open("filename.png", "rb").read(), "image/png"))]
async with httpx.AsyncClient(
        base_url=upload_endpoint,
        headers=auth_header, # ----- > {"Authorization": "Token {token}"},
    ) as httpx_client:
        response = await httpx_client.post(
            upload_endpoint,
            headers={"Upload-Start": "true", "Upload-Finish": "true"},
            data=data,
            files=images,
        )
```

The server log is the following:
```
INFO - 2022-06-20 16:21:48,784 - worker - default: cvat.apps.engine.task._create_thread(100, {'chunk_size': None, 'size': 0, 'image_quality': 100, 'start_frame': 0, 'st...) (/api/tasks/100)
cvat        | 
cvat        | 2022-06-20 16:21:48,785 DEBG 'rqworker_default_0' stderr output:
cvat        | DEBUG - 2022-06-20 16:21:48,785 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
cvat        | 
cvat        | 2022-06-20 16:21:48,803 DEBG 'rqworker_default_0' stderr output:
cvat        | DEBUG - 2022-06-20 16:21:48,803 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.
cvat        | 
cvat        | 2022-06-20 16:21:48,836 DEBG 'rqworker_default_0' stderr output:
cvat        | [2022-06-20 16:21:48,835] INFO cvat.server: create task #100
cvat        | 
cvat        | 2022-06-20 16:21:48,836 DEBG 'rqworker_default_0' stderr output:
cvat        | INFO - 2022-06-20 16:21:48,835 - task - create task #100
cvat        | 
cvat        | 2022-06-20 16:21:48,844 DEBG 'rqworker_default_0' stderr output:
cvat        | DEBUG - 2022-06-20 16:21:48,844 - worker - Handling failed execution of job /api/tasks/100
cvat        | 
cvat        | 2022-06-20 16:21:48,846 DEBG 'rqworker_default_0' stderr output:
cvat        | ERROR - 2022-06-20 16:21:48,846 - worker - Traceback (most recent call last):
cvat        |   File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
cvat        |     rv = job.perform()
cvat        |   File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
cvat        |     self._result = self._execute()
cvat        |   File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
cvat        |     return self.func(*self.args, **self.kwargs)
cvat        |   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
cvat        |     return func(*args, **kwds)
cvat        |   File "/home/django/cvat/apps/engine/task.py", line 291, in _create_thread
cvat        |     media, task_mode = _validate_data(media, manifest_files)
cvat        |   File "/home/django/cvat/apps/engine/task.py", line 190, in _validate_data
cvat        |     raise ValueError('No media data found')
cvat        | ValueError: No media data found
cvat        | Traceback (most recent call last):
cvat        |   File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
cvat        |     rv = job.perform()
cvat        |   File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
cvat        |     self._result = self._execute()
cvat        |   File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
cvat        |     return self.func(*self.args, **self.kwargs)
cvat        |   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
cvat        |     return func(*args, **kwds)
cvat        |   File "/home/django/cvat/apps/engine/task.py", line 291, in _create_thread
cvat        |     media, task_mode = _validate_data(media, manifest_files)
cvat        |   File "/home/django/cvat/apps/engine/task.py", line 190, in _validate_data
cvat        |     raise ValueError('No media data found')
cvat        | ValueError: No media data found

```

### Possible Solution
I don't know the solution, but does uploading files depend on a correct CSRF cookie?

### Steps to Reproduce (for bugs)

1. Run the docker-compose file.
2. Create a task without the data.
3. Upload a file using the api call like mentioned above.

### Context
I am trying to upload some incompatible data after transformation (DICOM data) which is run by a script. 
### Your Environment

- Git hash commit (`git log -1`): 3bd7c7e422d57986bd629da07214a3a3e666c68c
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.14, build a224086
- Are you using Docker Swarm or Kubernetes? Docker compose.
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem: not needed.

**Comment by FeryET** [comment]
So I finally understood what was my problem, and indeed this was not a bug in the software, but a bug in the documentation of the software. All I had to do was to provide the index of the file in the `files` segment of my request.

```
images = [("client_files[0]",  # <------- This has been changed from `client_files` to an item in the array.
                 ("filename.png", open("filename.png", "rb").read(), "image/png"))] 
async with httpx.AsyncClient(
        base_url=upload_endpoint,
        headers=auth_header, # ----- > {"Authorization": "Token {token}"},
    ) as httpx_client:
        response = await httpx_client.post(
            upload_endpoint,
            headers={"Upload-Start": "true", "Upload-Finish": "true"},
            data=data,
            files=images,
        )
```

**Comment by sammed-ai** [comment]
Hey, 
What are your "data" variable and upload_endpoint variable? I am also facing a similar issue.

**Comment by FeryET** [comment]
> Hey, What are your "data" variable and upload_endpoint variable? I am also facing a similar issue.

Data is a dict with compression level in it (you can look it up in swagger), and the upload data endpoint is the post request endpoint for a task. Something like `/api/tasks/{id}/data/`.

**Comment by zhiltsov-max** [comment]
Hi, the issue looks resolved. If you're interested in CVAT REST API, please also check the recently released `cvat-sdk` and `cvat-cli` Python packages on PyPI, and the updated REST API docs at http://app.cvat.ai/api/docs .

**Comment by hamedhaghighi** [comment]
> So I finally understood what was my problem, and indeed this was not a bug in the software, but a bug in the documentation of the software. All I had to do was to provide the index of the file in the `files` segment of my request.
> 
> ```
> images = [("client_files[0]",  # <------- This has been changed from `client_files` to an item in the array.
>                  ("filename.png", open("filename.png", "rb").read(), "image/png"))] 
> async with httpx.AsyncClient(
>         base_url=upload_endpoint,
>         headers=auth_header, # ----- > {"Authorization": "Token {token}"},
>     ) as httpx_client:
>         response = await httpx_client.post(
>             upload_endpoint,
>             headers={"Upload-Start": "true", "Upload-Finish": "true"},
>             data=data,
>             files=images,
>         )
> ```

Thanks save lots of my time.
