### ISSUE TITLE
If nginx already uses port 80, how to modify the configuration to start cvat

### ISSUE THREAD

**Issue by lingchensimon** [opencv/cvat#4706]
### My actions before raising this issue
![image](https://user-images.githubusercontent.com/92513876/174748013-4c6e82f2-2c7d-4c78-aaee-b8e8293c012f.png)

### Current Behaviour
![image](https://user-images.githubusercontent.com/92513876/174748167-06006a58-1c6e-493f-9d95-7abaa5efaefc.png)

Hi cvat team,
When deploying cvat, I found that the port conflicts with the ngnix port, but after modifying the port, the page cannot log in.
The result of this experiment is pasted below.I would appreciate it if someone could provide any suggestions or solutions for implementation.

Thank you,

**Comment by azhavoro** [comment]
Hello, you need to change the port for traefik service only https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port
