### ISSUE TITLE
CVAT on OCI compute becomes really slow after a while

### ISSUE THREAD

**Issue by pravemp** [opencv/cvat#4708]
### My actions before raising this issue
- [ yes] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ yes] Searched [past issues](/issues)

We deploy CVAT docker on OCI compute with pretty good shape. Initially it runs really fast but becomes really slow after a while (~2 hrs after the initial run). There are hardly any tasks created. The compute's RAM consumption is also very less.
Compute configurations - 
18CPUS
40GB RAM
175GB storage

### Expected Behaviour
I expect it not be very slow (35 seconds to load tasks) gradually. It gets worse with time

### Current Behaviour
Currently it takes forever to load the tasks

### Steps to Reproduce (for bugs)
Try running the CVAT 2.0 on any OCI compute and wait for a couple of hours before which it slows down for limited resources (tasks,projects) created

### Context
I am trying to integrate CVAT on to my application.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.11-ol
- Are you using Docker Swarm or Kubernetes? Docker Compose
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
[cvat-logs.txt](https://github.com/openvinotoolkit/cvat/files/8951038/cvat-logs.txt)

- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@pravemp , really need to investigate. We have pretty long experience to maintain different internal and public servers. I can say that I hear about the problem first time. Did you modify CVAT? Could you please run `docker stats` and describe your observations? Please analyze the purpose of your computer. Can it be an antivirus or any over heavy process which works in parallel? Did you try to run it on another computer?

**Comment by pravemp** [comment]
Thanks a lot for the response.
1. No we haven't modified CVAT in anyways. We are using the published images
2. Executing 'Docker stats', i found below results. 
`6ce5f65fb8f9        cvat_ui             0.00%               15.56MiB / 4GiB     0.38%               60.7kB / 38.7MB     0B / 8.19kB         17
1c03bb59cf78        cvat                0.03%               1.538GiB / 4GiB     38.44%              1.1MB / 7.22MB      0B / 1.01MB         40
b7c4cd8e3450        cvat_db             0.00%               12.96MiB / 4GiB     0.32%               440kB / 486kB       0B / 1.28MB         8
e087cd5ba4e6        cvat_redis          0.05%               9.805MiB / 4GiB     0.24%               720kB / 346kB       0B / 352kB          4
64f1be106b19        cvat_opa            0.00%               1010MiB / 4GiB      24.65%              117kB / 66.3kB      0B / 0B             22
e0a0a451ce8e        traefik             0.00%               27.43MiB / 4GiB     0.67%               45MB / 45MB         303kB / 0B          20`

3. This compute/host has been brought up with a sole purpose of launching cvat. 

what we tried as a fix - 
1. Increased the memory limits. Attached the docker-compose file
[docker-compose.yml.zip](https://github.com/openvinotoolkit/cvat/files/8951474/docker-compose.yml.zip)
After increasing, on restarting docker it was really fast but after couple of hours started slowing down.

**Comment by pravemp** [comment]
Difficult as the OCI (ORACLE CLOUD INFRASTRUCTURE) compute deployed with CVAT services are not publicly accessible. Let me give a shot at trying this in free trail computes and try to share it.

Meanwhile if there is anything that could hinder the Network IO speed please keep me posted
