### ISSUE TITLE
Issue with Share Sources

### ISSUE THREAD

**Issue by KevinLe1997** [opencv/cvat#471]
I'm trying to test out the Share Source option. Whenever I select "Share" and "Select Files", I'm greeted with a blank box. Is there a way around this? 

Thank you in advance! 
![image](https://user-images.githubusercontent.com/35794960/58817502-db0e2900-85f9-11e9-8060-67f228344c92.png)

**Comment by bsekachev** [comment]
@KevinLe1997 
Hi, have you mounted any [share](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path) to docker container?

**Comment by KevinLe1997** [comment]
Hi @bsekachev , I don't believe so. I'm not exactly sure since I'm using a work computer and am told the CVAT program is being ran in a Docker container.

**Comment by KevinLe1997** [comment]
So on our Docker container, we have a directory called "mnt" with nothing inside of it. From the example that you gave us in the documentation to set up Share sources, I simply changed "/mnt/share" to "/mnt". I am not given any errors, able to build, and do "docker-compose up -d". However, the blank screen in the above picture still appears when I choose Share for sources.

**Comment by bsekachev** [comment]
@KevinLe1997 
The directory ```/mnt/share``` isn't in the container. It is in the host server where docker container is built.
And of course UI doesn't show you any files while ```/mnt/share``` is empty.

**Comment by KevinLe1997** [comment]
You were right. "/mnt" exists within the container. I mounted some files onto "/mnt" and was finally able to see them. Thanks for the help.
