### ISSUE TITLE
Does cvat create tasks support concurrency?

### ISSUE THREAD

**Issue by SnowCats** [opencv/cvat#4710]
Does cvat create tasks support concurrency? For example, can I create multiple tasks at the same time?

**Comment by nmanovic** [comment]
@SnowCats , it does. The number of tasks which can be created in parallel are controlled by workers. By default CVAT has 2 works: https://github.com/openvinotoolkit/cvat/blob/d7560bbd39fec68f944515c2591dda74f3764b90/supervisord.conf#L25. This workers are used for dumping datasets and etc. You can increase the number of workers if it necessary.
