### ISSUE TITLE
CVAT not working

### ISSUE THREAD

**Issue by FurqanMehmood** [opencv/cvat#4713]
I am loading the website but i am getting 
 Error: Request failed with status code 500.

**Comment by ObjectMuffin** [comment]
Yesterday and today I was not able to get past the login page. It keeps saying error to reach the servers.

**Comment by strcom** [comment]
Ensure you have opa rules loaded. I've tried today update to latest version CVAT and coudn't login for some time, because my opa rules where empty (I'm using default docker-compose configuration).

**Comment by zerols** [comment]
today same question, can't login, F12 show me 500

**Comment by nmanovic** [comment]
@zerols , @strcom, @ObjectMuffin , @FurqanMehmood , CVAT.org should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is support by CVAT core team.

**Comment by nmanovic** [comment]
https://cvat-ai.github.io/cvat/docs/faq/#how-to-migrate-data-from-cvatorg-to-cvatai
