### ISSUE TITLE
Restore project after backup

### ISSUE THREAD

**Issue by marcoslucianops** [opencv/cvat#4719]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I'm replacing the computer that are running the CVAT. I did the backup of all projects but I'm not able to restore it in the new computer. I'm getting the error `The requested resource does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.`. I tried to create [Share path](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#share-path) but it seems to work only in task uploads. How can I solve this issue?

**Comment by mbirkhez** [comment]
I am facing the same issue

**Comment by bsekachev** [comment]
Hi,

Try with current develop branch.
Now it uses TUS protocol to upload data to server

**Comment by bsekachev** [comment]
I will close the issue for now. If you still experiencing the issue, please do not hesitate to reopen.

Thank you.

**Comment by mfsen** [comment]
How can i increase this limitation. I have a project size of 100Gb and i cannot able to upload because of this limitaiton.
