### ISSUE TITLE
Tasks not reorganized when moved to a different project

### ISSUE THREAD

**Issue by mbirkhez** [opencv/cvat#4722]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When I create a new project and move a task from lets say page 3 of another project (which has 5 pages) to the new one, I expect the task would appear on page 1 of the new project. Instead I see 5 pages have been created and the task appears on page 3 but the rest of the pages are empty.

Similarly, when I move all the tasks present on one page of the project to a different project, I expect the number of pages should decrease by 1 i.e. the tasks reorganize in the dashboard however I can still see the empty page.

### Current Behaviour

Tasks do not reorganize in the viewing dashboard

### Steps to Reproduce (for bugs)

1. Create 'project A' with enough tasks to fill 3 pages.
2. Create a new 'project B'
3. Move task on page 2 of 'project A' to 'project B'
4. The task will appear on page 2 of 'project B' while page 1 and 3 are empty
5. Move all tasks from page 2 of 'project A' to 'project B'
6. Page 2 of 'project A' will appear empty

**Comment by bsekachev** [comment]
@klakhov 

Could you please investigate the issue?

**Comment by klakhov** [comment]
@mbirkhez Hello, I tried to reproduce the issue but everything woked fine for me.
Maybe I'm doing something wrong?
![repr1](https://user-images.githubusercontent.com/50956430/192457752-8d43ac86-17e5-49ff-925e-b65878d35660.gif)

Tried to reproduce it on last develop version 9e67bcb53c4f434c636a90f80f49294088dda6bd. What version are you using? Maybe issue was fixed.
