### ISSUE TITLE
Requesting insight to make brush tool work

### ISSUE THREAD

**Issue by kkmehta03** [opencv/cvat#4723]
Hi, 
I'm working on making the brush tool from [this](https://github.com/openvinotoolkit/cvat/tree/bs/masks) branch to work.
It's able to export in CVAT format like this 
```
<mask label="blah" occluded="0" source="manual" rle="17, 10, 27, 15, 23, 18, 20, 21, 18, 23, 16, 24, 15, 26, 13, 27, 13, 27, 12, 29, 10, 30, 9, 32, 7, 34, 5, 36, 3, 38, 2, 38, 2, 39, 1, 39, 1, 120, 1, 39, 1, 39, 1, 39, 2, 38, 2, 38, 3, 37, 3, 37, 3, 37, 4, 36, 4, 35, 6, 34, 7, 33, 7, 32, 9, 30, 10, 29, 13, 26, 15, 23, 18, 20, 22, 15, 12" left="79" top="304" width="40" height="40" z_order="0"> </mask>
```
But it seems like the RLE here, is relative to the `left, top, width, height` numbers, because when i create `datum_annotation RLE`, the output is very weird. To test it out, i draw a polygon with the same shape and at the same space as the brush. the locations for the brush mask doesn't match with the location of the polygon. 

Can you shed some light on this please? Is there anything that can be done?

**Comment by kkmehta03** [comment]
Hi @bsekachev,
Thanks for your response! 
Could you give a small code snippet or approach or documentation that I could follow? 
I'm not able to crack how to convert this particular list along with the 4 border points into realistic points. 
If not that, something to see the logic on how to convert that list into PIL image?

Thanks!

**Comment by bsekachev** [comment]
@kkmehta03 

Have you seen this code from the branch?

```js
static rle2Mask(rle) {
            const [left, top, right, bottom] = rle.slice(-4);
            const width = right - left;
            const height = bottom - top;
            const decoded = Array(width * height).fill(0);
            const latestIdx = rle.length - 4;
            let decodedIdx = 0;
            let value = 0;
            for (let rleCountIdx = 0; rleCountIdx < latestIdx; rleCountIdx += 1) {
                let count = rle[rleCountIdx];
                while (count > 0) {
                    decoded[decodedIdx] = value;
                    decodedIdx++;
                    count--;
                }
                value = Math.abs(value - 1);
            }

            return [decoded, [left, top, right, bottom]];
        }
```

You can do approximately the same in Python with numpy array and then encode it to datumaro RLE using pycocotools.

**Comment by kkmehta03** [comment]
yeah but this one isn't a single array right? it still has the left, top, right, bottom array separately

**Comment by bsekachev** [comment]
@kkmehta03 

Let's imagine that you created this image. It is actually fragment, but, then you can place it to another image (which has the same size as dataset picture). Using ``left`` and ``top`` coordinates. Right?

**Comment by bsekachev** [comment]
Yes, exactly

**Comment by kkmehta03** [comment]
thank you very much! i'll try this out and comment further
