### ISSUE TITLE
Cannot connect using CLI

### ISSUE THREAD

**Issue by ninafiona** [opencv/cvat#4725]
I want to upload annotations using the CLI so I first tried to list the tasks using ` python cli.py --server-host my-server.com --auth ninafiona ls `. I enter my passwort and after a few seconds I get the following errors: 
```
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by zhiltsov-max** [comment]
Hi, please try to include the `--https` parameter:

```bash
python cli.py --server-host my-server.com --auth ninafiona --https ls
```

Did the command you use worked previously or is it the first time you're trying?

**Comment by zhiltsov-max** [comment]
Hi. If you're using a custom server, please contact the support team if there are any extra security improvements from their side. One of the possible reasons is the `User-Agent` request header check on the server / reverse proxy. I'll close the issue, please feel free to reopen if needed.
