### ISSUE TITLE
COCO annotations upload ellipse not being drawn

### ISSUE THREAD

**Issue by kkmehta03** [opencv/cvat#4727]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

when the task -> Upload annotations -> coco 1.0 is clicked and a coco json is uploaded, the polygons are drawn fine but the ellipse isnt. It doesn't show up on the right either under the annotations. 

### Expected Behaviour

recognize and draw all annotations including ellipses

### Current Behaviour

ellipse annotations being uploaded except for polygon, polyline, rectangle, etc. 

Mostly because the coco annotations has RLE in it. 

### Steps to Reproduce (for bugs)

1. Create an ellipse, export in coco format. 
2. open the task, import the same coco 
3. open the job, you'll see the ellipse not being shown

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by kirill-sizov** [comment]
Hi, @kkmehta03,
COCO format does not support ellipse type of shape, so CVAT dump ellipses as RLE Mask for COCO format.
When we uploading such annotations into the CVAT we don't see any shapes because currently CVAT doesn't support RLE Mask.
Functionality with supporting RLE Mask for CVAT currently in progress #4543.

I will close this issue, but if you will have any related questions or problems feel free to re-open.

**Comment by Huxwell** [comment]
If I may ask, are you planning to support dumping them as set of keypoints? Of course this would only be approximation of ellipsis, but would be compatible with existing code in various projects that parses code from COCO annotations dumped by CVAT.
