### ISSUE TITLE
Exporting of image and annotation 

### ISSUE THREAD

**Issue by lchunleo** [opencv/cvat#4731]
Am trying out the video annotation feature and encounter long waiting time. It happens when  I annotate certain portion of the video and then export out the image together with the annotation . However it seem to take forever and unsure when it is completed. 

In addition is the cvat stored the image chip somewhere or it is just processing without storing ?

**Comment by nmanovic** [comment]
@lchunleo , I have no idea from the description how to help you. Which version of CVAT do you use? Could you please share logs `docker logs cvat`?
