### ISSUE TITLE
Annotations format differs in task export and annotation download API

### ISSUE THREAD

**Issue by weidenka** [opencv/cvat#4735]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour
The annotation format slightly differs depending on how I download it from CVAT:
- Method 1 directly download the annotations json file
- Method 2 export and then download the entire task

Method2 gives me a field with the `attribute_name` while Method 1 returns a `spec_id`.

### Expected Behaviour
Would expect the same file format for both approaches. And I consider Method 2 to be correct.

### Current Behaviour
Method 1:
```json
      "shapes": [
        {
          "type": "points",
          "occluded": false,
          "z_order": 0,
          "points": [478.263671875,700.28515625],
          "id": 89265,
          "frame": 124,
          "outside": false,
          "attributes": [
            {
              "spec_id": 63,
              "value": "some_value"
            }
          ]
        },
```
Method 2:
```json
          {
            "type": "points",
            "occluded": false,
            "z_order": 0,
            "points": [478.263671875, 700.28515625],
            "frame": 124,
            "outside": false,
            "attributes": [
              {
                "value": "some_value",
                "name": "attribute_name"
              }
            ]
```

### Steps to Reproduce (for bugs)
Method 1:
```shell
http -o annotations.json --auth "me:mybirthday" GET "http://mycvathost.local:8080/api/v1/tasks/<taskId>/annotations"
``` 
and Method2:
```shell
http -o task.zip --auth "me:mybirthday" GET "http://mycvathost.local:8080/api/v1/tasks/<taskId>?action=export"
http -o task.zip --auth "me:mybirthday" GET "http://mycvathost.local:8080/api/v1/tasks/<taskId>?action=download"
``` 

### Context
I try to get the annotations only since export and video download is slow.

### Your Environment

will provide env details soon

**Comment by weidenka** [comment]
I'm running CVAT 1.7 on a linux machine.

**Comment by bsekachev** [comment]
Hi @weidenka 

CVAT has about 20 different annotation formats.
REST API in Method1 is used to communication between client and server. You should not use it to export annotations.

I will close the issue for now, do not hesitate to reopen if you still have questions.
Thank you.
