### ISSUE TITLE
You do not have permission to perform this action.

### ISSUE THREAD

**Issue by gecastro** [opencv/cvat#4737]
I'm currently using the last build from docker hub and I started to get the error

Could not restore the project
Error: Request failed with status code 403. {"detail":"You do not have permission to perform this action."}.

I did create some projects in an Organization (where I'm the owner of the organization) and suddenly, it tells me that I don't have permissions to restore the backup of a dataset, or to create a new project.

Is there a fix this issue? or to manually check the permissions in the database?

**Comment by nmanovic** [comment]
@gecastro , are you a regular user on the CVAT instance? If so, you cannot create more than 3 projects by default as far as I remember. You need to have "business" or "admin" role on the instance.
