### ISSUE TITLE
Instructions on how to build from source?

### ISSUE THREAD

**Issue by feacluster** [opencv/cvat#474]
I am unable to use the docker containers because of issues with corporate proxy. Is there any guide for how to build this from source? My guess is no, but can't hurt to ask :-)

**Comment by nmanovic** [comment]
@feacluster, thanks for the question. It is not a problem to run CVAT behind a proxy. We do that internally. Need to specify build arguments in docker-compose.override.yml correctly (http_proxy=..., https_proxy=..., ...). Please ask your next questions in our gitter channel. I will close the issue.
