### ISSUE TITLE
"400 Bad Request" on login page built with AWS

### ISSUE THREAD

**Issue by tatsuya0410** [opencv/cvat#4740]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I can access and log in to the CVAT built on EC2 from my PC.
![image](https://user-images.githubusercontent.com/4319215/178213359-7d520190-2351-4362-99bc-bb38cb59d98b.png)

### Current Behaviour
When I open the login page, an error occurs and I cannot log in.

### Steps to Reproduce (for bugs)

1. Ubuntu 20.04 launched on AWS EC2

2. I installed CVTA according to this.
 https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/ 

3.Configured ALLOWED_HOSTS in docker_compose.yml
![image](https://user-images.githubusercontent.com/4319215/178213041-72a2e3a9-80b8-4e8f-b8ce-735fd1e978ef.png)

4. export CVAT_HOST environment variable
　export CVAT_HOST=52.194.46.78 

5. AWS inbound rule releases port 8080

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05):
20.10.17

- Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 20.04

Please help me build my first CVAT.

**Comment by azhavoro** [comment]
Please attach the log file from cvat container: `docker log cvat > log.txt`
You don't specify ALLOWED_HOSTS env variable for cvat service, also seems CIDR notation `52.194.46.78*` is incorrect. Please just try to follow the guide https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port
