### ISSUE TITLE
track_id is exported, but not imported from Datumaro 1.0

### ISSUE THREAD

**Issue by jf99** [opencv/cvat#4741]
Hello, I think I have to open this new issue, because no-one will notice an [updated closed one](https://github.com/openvinotoolkit/cvat/issues/4043#issuecomment-1175018849).

I can draw tracks in CVAT (notice the text "POINTS TRACK" on the left and the button to toggle the "outside" property):
![pointstrack](https://user-images.githubusercontent.com/7962377/177328649-65edf3bc-442b-4b4e-bae5-8406bb90d364.png)
I can also export them as [Datumaro 1.0](https://github.com/openvinotoolkit/cvat/files/9046390/track-test-github-datumaro.zip). Notice that the default.json file in the attached zip archive contains tags with the key "track_id". However, after I import the zip into CVAT again ("Upload annotations -> Datumaro 1.0") all that is left are point **shapes** (instead of point **tracks**).
![pointsshape](https://user-images.githubusercontent.com/7962377/177329796-b5960248-8a31-4610-9351-ed2c973310ff.png)
Exporting the labels once again will generate a JSON without track_id.

Server version: 2.1
Core version: 5.0.1
Canvas version: 2.13.2
UI version: 1.37.0

**Comment by jf99** [comment]
Closing in favor of https://github.com/cvat-ai/cvat/issues/104

**Comment by yasakova-anastasia** [comment]
Hi, @jf99
Datumaro format doesn't support tracks. You can use other formats that support tracks for your task. You can find information about formats [here](https://opencv.github.io/cvat/docs/manual/advanced/formats/).
