### ISSUE TITLE
How CVAT tracks activity and time for analytics?

### ISSUE THREAD

**Issue by kbegiedza** [opencv/cvat#4742]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

How CVAT tracks activity and time for analytics purposes?

Is it reliable source for annotators' working time?

**Comment by nmanovic** [comment]
@kbegiedza , the algorithm is implemented on the client side. Thus you cannot trust the algorithm completely. Indeed you should collect other metrics as well: quality of annotations, the data annotation speed. For many problems the data annotation speed is known. It depends on data, it depends on the data annotation tool, etc. But if somebody annotates 1 bounding box per hour just clicking different UI elements, it is definetely a problem.

**Comment by kbegiedza** [comment]
@nmanovic 
Thank you for fast response.

Could you navigate me to implementation or concrete methods / files ?
I suppouse every annotation action is sent as an event / activity and then filtered in analytics component, am I right ?
