### ISSUE TITLE
Media Upload via CLI create's jobs sometimes and sometimes does not create jobs.

### ISSUE THREAD

**Issue by sammed-ai** [opencv/cvat#4743]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When i run the command 
`python3 cvat/utils/cli/cli.py --auth username:password --server-host 'CVATWEBSITE' --server-port CVATPORT --https  create 'task 1' --labels labels.json remote https://file-examples.com/storage/fe64bbb60e62cc956a036bf/2017/10/file_example_JPG_100kB.jpg`

The task is created and a job is created and the image is visible when I open the task page. But when I run the same command after downloading the image, the task is created but the job is not created and also the image is not present.

`python3 cvat/utils/cli/cli.py --auth username:password --server-host 'CVATWEBSITE' --server-port CVATPORT --https  create 'task 1' --labels labels.json local file_example_JPG_100kB.jpeg`

The above command does not work.

Similarly, taking an example from the documentation

`python3 cvat/utils/cli/cli.py --auth username:password --server-host 'CVATWEBSITE' --server-port CVATPORT --https  create 'task 1' --labels labels.json remote https://github.com/opencv/opencv/blob/master/samples/data/vtest.avi?raw=true`

When I run the above command it works as expected. But when I download the AVI file and try to run it via local argument it does not run.

`python3 cvat/utils/cli/cli.py --auth username:password --server-host 'CVATWEBSITE' --server-port CVATPORT --https  create 'task 1' --labels labels.json local vtest.avi`

The above command does not work.

This is not the problem with the local argument because sometimes with the remote argument also a few URLs do not work as expected.
### Expected Behaviour

The task, job and image should be created irrespective of the source of the media file.
### Current Behaviour

The jobs and images are not created all the time when using the local argument and sometimes when using the remote argument.
### Steps to Reproduce (for bugs)

1. Run the above-mentioned commands on a local instance of CVAT.
### Context

Iteratively creating tasks based on a folder containing images.
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
<img width="1340" alt="Screenshot 2022-07-12 at 3 05 50 PM" src="https://user-images.githubusercontent.com/72775806/178460057-f1b15b32-934d-4866-848e-3ab268e6ad6b.png">

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Hi! I can see there is some strange path being used to look for the uploaded image. Did you modify the server somehow?

I wasn't able to reproduce the issue. We have updated CLI and now it is released on PyPI, you can install it with `pip install cvat-cli`. We have [a similar test](https://github.com/opencv/cvat/blob/develop/tests/python/cli/test_cli.py#L105-L114) that should cover the scenario in the issue. Please check if this problem still persists, feel free to reopen the issue.
