### ISSUE TITLE
Oriented bounding boxes broken with COCO format

### ISSUE THREAD

**Issue by domef** [opencv/cvat#4745]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When exporting bounding boxes with orientation in COCO format, the angle of rotation is stored in `attributes.rotation` for each annotation. This is ok since COCO doesn't officially support rotated bounding boxes. The problem is when I try to import the .json file I exported before: the bounding boxes are correctly imported but the angle is completely discarded and all the bounding boxes are axes aligned.

### Expected Behaviour
The oriented bounding boxes should be correctly imported when using the COCO format.

### Current Behaviour
The oriented bounding boxes are wrongly imported since the orientation is discarded.

### Your Environment
I'm using Ubuntu 18.04 and I installed following the guide https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64.

**Comment by ken5e** [comment]
Hi domef, I encounter the same problem too. It seems like cvat abandoned all rotation information and set all rotation to 0.0. Have you solved this problem
![● Untitled-1 ipynb - Visual Studio Code 29_07_2022 10_26_16 (2)](https://user-images.githubusercontent.com/69415655/181670097-9f3a5949-9697-49bf-b3c6-673af187ce50.png)
?

**Comment by bsekachev** [comment]
Hi @domef 

Thank you for the report, I can submit that that is a server bug.
