### ISSUE TITLE
nuclio update

### ISSUE THREAD

**Issue by malfonso0** [opencv/cvat#4746]
hi, just curiosity.
i have seen that niclio is in the 1.9 version, and cvat is still useing (recommending) 1.5

- can i change and update the nuclio version ? ( on the docker compose) and it will work?
- its there any advantage in updating the nuclio version

thanks

**Comment by nmanovic** [comment]
@malfonso0 , it was updated: https://cvat-ai.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

From the documentation:
You have to install nuctl command line tool to build and deploy serverless functions. Download [version 1.8.14](https://github.com/nuclio/nuclio/releases/tag/1.8.14).
