### ISSUE TITLE
Create an annotation from a segmented mask

### ISSUE THREAD

**Issue by TryAnotherName** [opencv/cvat#4748]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Question
Hello.
I ran into a problem when using "Upload annotations" for the CVAT 1.1 annotation.
For my project, I need to load an annotation with rotated bounding boxes created from a segmented masks for markup. I use the function OpenCV.minAreaRect and get 4 coordinates. After that, I calculate the angle on the sides of the box. But no matter what coordinates and angles of the bounding box I insert, it is displayed incorrectly in the task. It seems that when calculating a rotated bounding box, CVAT recalculates its coordinates for drawing, but I could not find information on how it does this.

**Comment by bsekachev** [comment]
Hello,

First you need to calculate the rotation angle. It must be a number of degrees in range [0; 360].
Secondly rotate your box to ``-angle``, you will get coordinates of not-rotated bounding box.
Finally put ``x1,y1, x2,y2`` of the not-rotated box to CVAT and ``angle`` separately.

In the UI CVAT rotates two points (x1,y1) (x2,y2) around the bounding box center. 

I hope it will help, I will close the issue for now. 
Do not hesitate to reopen if you still have questions, thank you.
