### ISSUE TITLE
Zoom randomly resets to default in process of annotation

### ISSUE THREAD

**Issue by Daydream3r** [opencv/cvat#4749]
Hi! Title says it. Has anyone experienced this and able to troubleshoot? Happens when drawing polygon shape.
MacBook M1, macOS Monterey, Google Chrome web browser

**Comment by bsekachev** [comment]
Hi, I didn't meet the issue.
It can be reset if you make double click.

**Comment by bsekachev** [comment]
We will close the issue, do not hesitate to reopen if you have any updates on this. 
Thank you.
