### ISSUE TITLE
cvat_opa container always restart

### ISSUE THREAD

**Issue by hhgz9527** [opencv/cvat#4755]
> macOS Version

> 2.1.0 release and develop branch both have this issue

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/7303158/179131424-b97f1548-5811-4a49-b953-76a7731d0eba.png">
<img width="814" alt="image" src="https://user-images.githubusercontent.com/7303158/179131456-2602d86d-1d45-4976-a48d-56aaf5c366ac.png">

**Comment by hhgz9527** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/7303158/179133370-caf4dac4-b65a-45ec-83f7-c895e9a86df9.png">

/cvat/apps/iam/rules permissions also ok

**Comment by nmanovic** [comment]
@hhgz9527 , could you please share logs from cvat and opa containers?

- `docker logs cvat`
- `docker logs cvat_opa`

**Comment by firefox3dxo** [comment]
modify docker-compose.yml
add user : root  , as below
services:
   cvat_opa:   
     user: root
     ......

**Comment by nmanovic** [comment]
@hhgz9527 , did you solve the problem?

**Comment by bsekachev** [comment]
We will close the issue, do not hesitate to reopen if you have any updates on this. 
Thank you.
