### ISSUE TITLE
upload both CVAT for images and videos annotations

### ISSUE THREAD

**Issue by doroteja-m** [opencv/cvat#4759]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have previously labeled a video from which i exported both CVAT for video and CVAT for images xml files. When i upload a new video i want to be able to upload both of those annotation files since i need both tracking and tags, but the XML files seem to be overwriting one another. Is there a way to achieve this? 

Also, why arent tags exoporeted in CVAT video format solely in CVAT images?

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): linux 
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Both images and videos formats support tags and videos.
Just dump annotations in one of them and then upload it to a new task.

Yes, they overwrite each other, but you do not need to upload the both
