### ISSUE TITLE
Cuboid for tilted objects

### ISSUE THREAD

**Issue by Steven-m2ai** [opencv/cvat#4762]
Hello,

I have images taken by a top down camera (~45 degrees looking downwards). As such, the objects have a tilt angle, and the front face of the cuboid thus will not be a "perfect rectangle" (it is distorted because of the object's tilt). 

Is there any way to label this using the cuboid?

Thanks

**Comment by bsekachev** [comment]
Sorry, unfortunately this is not supported. Front edge of a 2D cuboid is always not distorsed.
