### ISSUE TITLE
Adding points to existing polygon

### ISSUE THREAD

**Issue by domef** [opencv/cvat#4763]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

After creating a polygon I can select a point and delete it. Is it possible to add a new point to an existing polygon?

**Comment by ncianeo** [comment]
Do [Shift + click] on a point of your polygons.

**Comment by kitovyj** [comment]
Also encountered the same issue. How to add a new point in an existing polygon, between the another two? Shift +  Click, Shift + double click dont work - these start drawing a new object instead of modifying the existing one.

**Comment by ncianeo** [comment]
@kitovyj 
You should [shift+click] on an existing point of your polygon first. It will take you to the polygon editing view. Then you can add additional points to your polygon.
