### ISSUE TITLE
What are the functions of port 8090?

### ISSUE THREAD

**Issue by fadelmuli** [opencv/cvat#4766]
Hello. I've installed CVAT on my own server without any modification on docker-compose yaml files. When I run `docker container ls`, I notice that container `traefik` uses both port 8080 and 8090. I know that port 8080 is used to access the web UI. But what is the function of port 8090? Is it safe if I disable that port?

Thank you very much

**Comment by kirill-sizov** [comment]
Hi @fadelmuli, thank you for your question.

I think you can disable port 8090 that will have no any affects.

This port is used for traefik dashboard ([that disabled by default](https://github.com/opencv/cvat/blob/1b034e72bdeccf57dfa09ad9c936b39b03e0a336/docker-compose.yml#L145-L152)). If you don't need this dashboard you can disable this port.

I will close this issue, but you can reopen it in case you will have any related questions.
