### ISSUE TITLE
TransT tracker integration

### ISSUE THREAD

**Issue by dschoerk** [opencv/cvat#4768]
Hi, I've recently started to use CVAT to annotate videos of traffic scenes. Before coming across CVAT I briefly experimented with Supervisely and was very impressed by their [semi-automatic video annotation with TransT ](https://www.youtube.com/watch?v=EMvqTFu1ILE). TransT is a single object tracking algorithm and was presented recently at CVPR21, a Pytorch implementation is available [here](https://github.com/chenxin-dlut/TransT). So I picked that up and integrated it into CVAT as a new tracking tool. If you find this useful I would like to open a pull request for this new feature. 

a demo video showing the workflow and a comparison between TransT and SiamMask if you are interested:
https://www.youtube.com/watch?v=_oT44BXMaJY

**Comment by nmanovic** [comment]
@dschoerk , thanks for the contribution. It looks like the tracker was integrated. I will close the issue: https://github.com/opencv/cvat/tree/develop/serverless/pytorch/dschoerk/transt/nuclio

**Comment by rohit901** [comment]
Hi @dschoerk, thanks for the integration. However, the tracker seems quite slow and we have to keep clicking next frame in a video for it to work right? Seems counter-intuitive, and I wonder why not just use interpolation method and do it manually? Granted, I'm running on CPU, but will there be a difference even if I run on GPU?

**Comment by basilevs** [comment]
> Granted, I'm running on CPU, but will there be a difference even if I run on GPU?

Even hosted model runs the same way.
