### ISSUE TITLE
Including models into CVAT tool

### ISSUE THREAD

**Issue by bhargav-sudo** [opencv/cvat#4771]
Hi, Can we include other OpenVINO models into the tool for using Auto-annotation mode.
Like I need to add person-detection model from OpenVINO.

**Comment by kirill-sizov** [comment]
Hi @bhargav-sudo, thank you for your question.

I think you can try to find according information in [our documentation](https://opencv.github.io/cvat/docs/) particular in [adding your own DL models section](https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models)

If you will have any problems / questions with  deploying wanted model, open new issue or reopen this one.
