### ISSUE TITLE
https://cvat.org/ down?

### ISSUE THREAD

**Issue by JFMeyer2k** [opencv/cvat#4772]
Was it taken down on purpose as I can't connect to it anymore. 
Will it be back?

**Comment by nmanovic** [comment]
@JFMeyer2k , It should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is supported by CVAT core team.

**Comment by ActiveChooN** [comment]
Hi @JFMeyer2k, cvat.org was on maintenance. Should be work fine by now.

**Comment by nmanovic** [comment]
@JFMeyer2k , https://cvat-ai.github.io/cvat/docs/faq/#how-to-migrate-data-from-cvatorg-to-cvatai

**Comment by nmanovic** [comment]
@JFMeyer2k , I will close the issue as outdated. CVAT.org is running in read only mode. You can port your tasks on [CVAT.ai](http://cvat.ai/). Please use the instruction: https://cvat-ai.github.io/cvat/docs/faq/#how-to-migrate-data-from-cvatorg-to-cvatai
