### ISSUE TITLE
Annotators with "user" accounts have no permissions to resolve issues after reviews

### ISSUE THREAD

**Issue by arasharchor** [opencv/cvat#4778]
Having "user" account, I am not able to resolve an issue, created during review by admin. 
I think user shall have the permission to resolve issues which shows the admin, that issue has been resolved. 

Please let me know if there is a solution for this behavior or this is actually a bug.This was not happening in the last versions. 

![image](https://user-images.githubusercontent.com/12903362/179623370-c1095713-9538-4728-9e04-5bd25fb1a3f2.png)
![image](https://user-images.githubusercontent.com/12903362/179624049-343d788b-0a7c-430d-a2a6-55efc9f53208.png)

**Comment by bsekachev** [comment]
@nmanovic I tried this scenario and it actually looks strange when job assigned cannot resolve issues. Bug?

Rego rules:
```
is_issue_admin {
    is_task_staff
}

is_issue_admin {
    is_issue_owner
}

allow {
    { utils.UPDATE, utils.DELETE }[input.scope]
    utils.is_sandbox
    utils.has_perm(utils.WORKER)
    is_issue_admin
}
```

Should is_issue_admin be true if is_job_staff is true?

**Comment by nmanovic** [comment]
@bsekachev , looks like a bug. But probably there were some idea behind the code. In any case let's change the code. I will do that tomorrow.
