### ISSUE TITLE
Fail to build CUDA suport

### ISSUE THREAD

**Issue by shuait** [opencv/cvat#478]
tried to build tf OD with GPU support on a cloud instance by running

#!/usr/bin/env bash

docker-compose -f docker-compose.yml \
               -f docker-compose.override.yml \
               -f ./components/cuda/docker-compose.cuda.yml \
               -f ./components/tf_annotation/docker-compose.tf_annotation.yml \
               up -d --build

got error and here's the following message

Step 22/48 : RUN if [ "$CUDA_SUPPORT" = "yes" ]; then         /tmp/components/cuda/install.sh;     fi
 ---> Running in 2ba0c7259a15
Executing: /tmp/tmp.E9gKbYvfQy/gpg.1.sh --fetch-keys
http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
gpgkeys: no key data found for http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: WARNING: unable to fetch URI http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub: bad public key
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [853 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [557 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [6113 B]
Get:10 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]Get:11 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1248 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [968 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [19.1 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7942 B]
Get:18 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8532 B]
Fetched 15.8 MB in 12s (1296 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cuda-cudart-9-0
E: Unable to locate package cuda-libraries-9-0
E: Unable to locate package libnccl2
E: Unable to locate package libcudnn7
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c if [ "$CUDA_SUPPORT" = "yes" ]; then         /tmp/components/cuda/install.sh;     fi' returned a non-zero code: 100

**Comment by nmanovic** [comment]
@shuait , does the command work locally on your machine?

**Comment by bsekachev** [comment]
@shuait 
Sometimes NVIDIA has problems with keys. Is the problem still observed?

**Comment by WeiyeShao** [comment]
I have same problem in my own machine.
OS: Ubuntu 16.04

**Comment by bsekachev** [comment]
@WeiyeShao 
Still have the problem?

**Comment by shuait** [comment]
problem still exists... I can download the public key from my browser however.

**Comment by nmanovic** [comment]
Hi @shuait , we don't see the issue on our side. Could you please help us to investigate? We are not able to resolve such kind of problems remotely. It can be a problem with proxy or some settings of your computer. Just try to repeat the same actions on your host and see if you can reproduce the issue.

**Comment by shuait** [comment]
Switched to another cluster in Singapore and the problem resolved by itself. Seems to be a firewall related issue.

**Comment by nmanovic** [comment]
@shuait , thanks for the note. I will close the issue for now.
