### ISSUE TITLE
Add support for Oracle OCI Buckets

### ISSUE THREAD

**Issue by rodrigoberriel** [opencv/cvat#4783]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
CVAT already supports S3 cloud storage compatible API, and Oracle provides an [Amazon S3 Compatibility API](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm) for their Buckets. Therefore, it would be expected that CVAT supports OCI Buckets.

### Current Behaviour
When entering the Access key and Secret key pair, there is a limit for their length ([20 for the access key](https://github.com/openvinotoolkit/cvat/blob/d7560bbd39fec68f944515c2591dda74f3764b90/cvat/apps/engine/serializers.py#L943) and [40 for the secret key](https://github.com/openvinotoolkit/cvat/blob/d7560bbd39fec68f944515c2591dda74f3764b90/cvat/apps/engine/serializers.py#L944)). The Oracle OCI Customer Secret Key pair, however, is longer than that: 40 for the access key and 44 for the secret key. This limitation prevents the use of OCI Buckets in CVAT.

### Possible Solution
There are two obvious ways to implement a solution:
1. Change the length limits of the access and secret key pair. Straightforward and I cannot foresee side effects since the limits would be increased.
2. Implement a new Cloud Storage provider extending AWS S3 and basically changing the limits as in option 1.

I can provide a PR in both ways. Let me know which would be preferred for CVAT.

### Context
Our company has migrated from AWS to Oracle OCI and we had been using AWS S3 to store the data we annotate using CVAT. As part of the migration, we moved our AWS S3 Buckets to Oracle OCI Buckets and would love to continue to use CVAT. We changed our CVAT locally but I think this could be part of CVAT in general as Oracle continues to push its cloud to more and more customers.

### Your Environment

- Git hash commit (`git log -1`): `d7560bbd39fec68f944515c2591dda74f3764b90`
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.17
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu 22.04

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@Marishka17 

Could you please look and comment?

**Comment by rodrigoberriel** [comment]
I submitted #4876. Please let me know if I can be of any help.
