### ISSUE TITLE
Rectangular box annotation rotation problem

### ISSUE THREAD

**Issue by Sunny-Day200** [opencv/cvat#4784]
Add the least components in the latest version of cvat to rotate the rectangular box annotation

Running only the (docker-compose Up) rectangle box comment does not appear to rotate
I hope to get your help

**Comment by bsekachev** [comment]
Hi,

Because ``docker-compose up`` do not rebuild a docker image, actually you can't upgrade the application this way. 
Try to clone this repository https://github.com/cvat-ai/cvat (because the current one have issues with the latest release) and do ``docker-compose up -d --build``

**Comment by Sunny-Day200** [comment]
Thanked your reply
My current version of cvat is the latest version. After starting with (docker compose up -d --build), the rectangular box annotation still cannot be rotated. Does it need to add other components?


If you clone again https://github.com/cvat-ai/cvat Will it affect the data I have uploaded before。。。。。。。

**Comment by bsekachev** [comment]
> After starting with (docker compose up -d --build), the rectangular box annotation still cannot be rotated. Does it need to add other components?

Be sure you are using correct instance, maybe you have deployed more. Share with us CVAT version from UI (top right menu > About), please provide some screenshots where rotation point does not appear.

**Comment by Sunny-Day200** [comment]
> > 启动后（docker compose up -d --build），矩形框注解还是不能旋转。是否需要添加其他组件？
> 
> 确保您使用的是正确的实例，也许您已经部署了更多实例。与我们分享来自 UI 的 CVAT 版本（右上角菜单 > 关于），请提供一些没有出现旋转点的屏幕截图。

![image](https://user-images.githubusercontent.com/53826251/182338625-c2fdd535-0f3c-49f6-84e3-2e2f662009fd.png)
![微信图片编辑_20220802171359](https://user-images.githubusercontent.com/53826251/182338880-62daf80f-9cdd-45ae-b373-8d0b28a9a6f8.jpg)

**Comment by Sunny-Day200** [comment]
> > 启动后（docker docker up -d --build），组合框注解还是不能旋转。是否需要添加其他组件？
> 
> 确保您是的实例，可能您已经部署没有出现来自与分享的 CVAT 版本更多使用的 UI （使用菜单实例>关于），请参阅旋转点的屏幕截图。

![image](https://user-images.githubusercontent.com/53826251/182339093-ad450d2f-d459-4480-8978-d3456d8114f8.png)
![微信图片编辑_20220802171359](https://user-images.githubusercontent.com/53826251/182339128-b5fb3512-6402-4448-8f43-dd507a2b72a6.jpg)

**Comment by bsekachev** [comment]
Hi again, 

Sorry for long response. I was on vacation.

According to this patch https://github.com/opencv/cvat/pull/3832
Bounding boxes can be rotated starting from 1.26.0
So, I can suggest that you upgrade your server wrong way.
