### ISSUE TITLE
 one bug of computing Jobs issues nums

### ISSUE THREAD

**Issue by lyq12580** [opencv/cvat#4787]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

find a bug in "cvat\cvat-ui\src\components\task-page\job-list.tsx"
### Current Behaviour

 useEffect(() => {
        setError(null);
        jobInstance
            .issues(jobInstance.id)
            .then((issues: any[]) => {
                setSummary({
                    issues_unsolved: issues.filter((issue) => !issue.**resolved_date**).length,
                    issues_resolved: issues.filter((issue) => issue.**resolved_date**).length,
                });
            })
            .catch((_error: any) => {
                // eslint-disable-next-line
                console.log(_error);
                setError(_error);
            });
    }, []);
### Possible Solution

 useEffect(() => {
        setError(null);
        jobInstance
            .issues(jobInstance.id)
            .then((issues: any[]) => {
                setSummary({
                    issues_unsolved: issues.filter((issue) => !issue.**resolved**).length,
                    issues_resolved: issues.filter((issue) => issue.**resolved**).length,
                });
            })
            .catch((_error: any) => {
                // eslint-disable-next-line
                console.log(_error);
                setError(_error);
            });
    }, []);
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by alex4men** [comment]
@lyq12580 why did you close the issue? The bug is still there. I could make a pull request.

**Comment by nmanovic** [comment]
@alex4men , please do! We love contribution.

**Comment by lyq12580** [comment]
> @lyq12580 why did you close the issue? Your solution works, but the bug is still in the repo. Could you open the issue, please? I could make a pull request, if you wish.

nobody can reply me, so i close it. Now  it is already  opened

**Comment by lyq12580** [comment]
> @lyq12580 why did you close the issue? Your solution works, but the bug is still in the repo. Could you open the issue, please? I could make a pull request, if you wish.

please help make a pull request ,Thanks
