### ISSUE TITLE
english letters always appeared while inputting chinese in text box of labels attribute

### ISSUE THREAD

**Issue by yangxiuwu** [opencv/cvat#4790]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

english letters should not appear in text box while typing chinese 

### Current Behaviour

<img width="483" alt="image" src="https://user-images.githubusercontent.com/17425009/182793231-3c28c0e4-3328-40e6-94e8-968fb7a31912.png">

### Possible Solution

ignore keyup and keydown event ?

### Your Environment

- Git hash commit (`git log -1`):
commit 3bd7c7e422d57986bd629da07214a3a3e666c68c
Merge: e33db5c 119a27b
Author: Nikita Manovich <nikita.manovich@gmail.com>
Date:   Sat Apr 9 05:50:19 2022 +0300

    Merge pull request #4556 from openvinotoolkit/release-2.1.0
    
    release v2.1.0
- Docker version `docker version` (e.g. Docker 17.0.05):
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
- Are you using Docker Swarm or Kubernetes?
No
- Operating System and version (e.g. Linux, Windows, MacOS):
Centos 7 Linux 3.10.0-1160.45.1.el7.x86_64
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
From description, it looks like it is a bug, but could you please suggest a way to reproduce?
We do not have a Chinese keyboard and are not acquainted about its specific :(

**Comment by yangxiuwu** [comment]
1、add a label with text attribute

**Comment by yangxiuwu** [comment]
can refer to https://blog.evanyou.me/2014/01/03/composition-event/

**Comment by yangxiuwu** [comment]
solved this problem by using compositionupdae event 
 modify cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-attribute.tsx as following:
```ts
const lock = useRef(false)

    function handleComposition(e: React.CompositionEvent<HTMLInputElement>) {
        if (e.type === 'compositionupdate') {
            lock.current = true
        }
    }

    return (
        <>
            <Col span={8} style={attrNameStyle}>
                <Text className='cvat-text'>{attrName}</Text>
            </Col>
            <Col span={16}>
                <Input
                    ref={ref}
                    size='small'
                    disabled={readonly}
                    onChange={(event: React.ChangeEvent<HTMLInputElement>): void => {
                        if (ref.current && ref.current.input) {
                            setSelection({
                                start: ref.current.input.selectionStart,
                                end: ref.current.input.selectionEnd,
                                direction: ref.current.input.selectionDirection,
                            });
                        }

                        if (lock.current) {
                            lock.current = false;
                            return;
                        }

                        changeAttribute(attrID, event.target.value);
                    }}
                    onCompositionUpdate={handleComposition}
                    value={attrValue}
                    className='cvat-object-item-text-attribute'
                />
            </Col>
```
