### ISSUE TITLE
can not import dataset

### ISSUE THREAD

**Issue by leoyahaha** [opencv/cvat#4792]
As shown in figure
![8S5AYD9O(X8@J1D7H}3(J(O](https://user-images.githubusercontent.com/91840036/183335846-f277c900-c8ec-4288-8c76-bffbd29fed6a.png)
This problem occurred after my server was restarted, which was fine before.

**Comment by nmanovic** [comment]
@leoyahaha , unfortunately the bug request doesn't have enough information to investigate the issue. Could you please add more information about your CVAT version, how you updated it and so on.

**Comment by bsekachev** [comment]
@leoyahaha 

I will close the issue, because there are not any response from your site.
If you are ready to provide more information, do not hesitate to reopen.

Thank you.
