### ISSUE TITLE
No bounding box or label generated with auto labeling

### ISSUE THREAD

**Issue by ngadhvi** [opencv/cvat#4794]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have trained an object detection model with my own toy data using PyTorch Detectron2 and deployed it as explained in the Serverless Tutorial under the section "Adding your own DL models". The model gets deployed without any problem, is visible in the CVAT -> Models, and I can even start the Automatic Annotation from the "Actions" but when I open this job it does not show any label or bounding box on the images. 
 
### Current Behaviour
After starting the Automatic Annotation from the "Actions" on any Task, it should generate label and bounding box but it does not.
If I try revoking the deployed function using the below curl command, it produces its label, its prediction score, and even the bbox for the object detected. 

`
image=$(curl https://froms3bucket/myimage.png --output - | base64 | tr -d '\n')
cat << EOF > /tmp/input.json
{"image": "$image"}

EOF

cat /tmp/input.json | nuctl invoke pth.detectron2.retinanet50.v1 -c 'application/json' --platform local` 

### Possible Solution
:(

### Steps to Reproduce (for bugs)
Deploy the serverless custom model using https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/.

### Context
We have an influx of images coming and training a small portion of these will help us save hundreds of man hours. I have tried debugging but it does not get me anywhere.  

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05):
-> Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:56 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:02 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux with Deep Learning AMI (Ubuntu 18.04) Version 61.2 on AWS. 
- Code example or link to GitHub repo or gist to reproduce problem: Find attachment for the main.py and function.yaml (renamed their extensions to get them uploaded here).
- Other diagnostic information / logs:
  Docker logs for the deployed function for any prediction done is as follows and it does not throw any errors as well:

Run retinanet50 model {"worker_id": "0"}

[function.txt](https://github.com/openvinotoolkit/cvat/files/9283733/function.txt)
[main.txt](https://github.com/openvinotoolkit/cvat/files/9283805/main.txt)

**Comment by ngadhvi** [comment]
Update:
if the class name in the function.yaml file goes beyond certain it does not work. I got this working by changing the class name "my_classname_cn1" to "my_classname". This sure is a bug.

**Comment by bsekachev** [comment]
Hi @ngadhvi 

I am not sure what should be reaction on this issue from our side, but I can suggest that if we had a way to debug serverless function, it would be easier to understand the root cause, isn't it?

**Comment by bsekachev** [comment]
I closed the issue for now, please, do not hesitate to reopen it, if the issue is still relevant
