### ISSUE TITLE
CVAT class limit 

### ISSUE THREAD

**Issue by Akhp888** [opencv/cvat#4796]
Hello ,

I want to use CVAT as my base annotation tool so as part of documentation I want to if there is any limit on adding number of classes in CVAT projects ?

Image for reference 
![image](https://user-images.githubusercontent.com/42496053/183651957-f00b9838-3511-4ba6-a887-69666e1a357d.png)

Also curious to know if there is any mean to add 100's or 1000's of classes at once without dumping them manually one by one ?

**Comment by bsekachev** [comment]
No, there are not any limit to number of classes. 
You can generate JSON format (it is easy, just add a couple of labels and see) and use ``Raw`` tab to add 1000's of classes.
