### ISSUE TITLE
not able to setup project getting some error

### ISSUE THREAD

**Issue by RajasekharKadasani** [opencv/cvat#480]
Unpacking xauth (1:1.0.9-1ubuntu2) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.47.0-1ubuntu2.13_amd64.deb ...
Unpacking curl (7.47.0-1ubuntu2.13) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../liberror-perl_0.17-1.2_all.deb ...
Unpacking liberror-perl (0.17-1.2) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.7.4-0ubuntu1.6_all.deb ...
Unpacking git-man (1:2.7.4-0ubuntu1.6) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.7.4-0ubuntu1.6_amd64.deb ...
Unpacking git (1:2.7.4-0ubuntu1.6) ...
Selecting previously unselected package ncurses-term.
Preparing to unpack .../ncurses-term_6.0+20160213-1ubuntu1_all.deb ...
Unpacking ncurses-term (6.0+20160213-1ubuntu1) ...
Selecting previously unselected package python3-chardet.
Preparing to unpack .../python3-chardet_2.3.0-2_all.deb ...
Unpacking python3-chardet (2.3.0-2) ...
Selecting previously unselected package python3-six.
Preparing to unpack .../python3-six_1.10.0-3_all.deb ...
Unpacking python3-six (1.10.0-3) ...
Selecting previously unselected package python3-urllib3.
Preparing to unpack .../python3-urllib3_1.13.1-2ubuntu0.16.04.3_all.deb ...
Unpacking python3-urllib3 (1.13.1-2ubuntu0.16.04.3) ...
Selecting previously unselected package python3-requests.
Preparing to unpack .../python3-requests_2.9.1-3ubuntu0.1_all.deb ...
Unpacking python3-requests (2.9.1-3ubuntu0.1) ...
Selecting previously unselected package zip.
Preparing to unpack .../archives/zip_3.0-11_amd64.deb ...
Unpacking zip (3.0-11) ...
Selecting previously unselected package ssh-import-id.
Preparing to unpack .../ssh-import-id_5.5-0ubuntu1_all.deb ...
Unpacking ssh-import-id (5.5-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu21.21) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Setting up libpopt0:amd64 (1.16-10) ...
Setting up openssh-client (1:7.2p2-4ubuntu2.8) ...
Setting up openssh-sftp-server (1:7.2p2-4ubuntu2.8) ...
Setting up openssh-server (1:7.2p2-4ubuntu2.8) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:jNYqx53U/VPYf29JqHw3LdyE8TxxEhshMiTS0OejUGU root@310d84542b8e (RSA)
Creating SSH2 DSA key; this may take some time ...
1024 SHA256:/zJHWbxZKB94j2MQtPj6hFLLTBw8b4CqLhUQ0lvOAW0 root@310d84542b8e (DSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:84fZ9g3/fAfDS5YNEaySZ4Hh9wHuft9ZDAjP4x4/kJ4 root@310d84542b8e (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:BFGo38QV1aTOZ7FF/l9UVZBAqvfayCRGaj7u9KFi190 root@310d84542b8e (ED25519)
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up ssh (1:7.2p2-4ubuntu2.8) ...
Setting up less (481-2.1ubuntu0.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Setting up netcat-openbsd (1.105-7ubuntu1) ...
update-alternatives: using /bin/nc.openbsd to provide /bin/nc (nc) in auto mode
Setting up libxmuu1:amd64 (2:1.1.2-2) ...
Setting up rsync (3.1.1-3ubuntu1.2) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Setting up xauth (1:1.0.9-1ubuntu2) ...
Setting up curl (7.47.0-1ubuntu2.13) ...
Setting up liberror-perl (0.17-1.2) ...
Setting up git-man (1:2.7.4-0ubuntu1.6) ...
Setting up git (1:2.7.4-0ubuntu1.6) ...
Setting up ncurses-term (6.0+20160213-1ubuntu1) ...
Setting up python3-chardet (2.3.0-2) ...
Setting up python3-six (1.10.0-3) ...
Setting up python3-urllib3 (1.13.1-2ubuntu0.16.04.3) ...
Setting up python3-requests (2.9.1-3ubuntu0.1) ...
Setting up zip (3.0-11) ...
Setting up ssh-import-id (5.5-0ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for systemd (229-4ubuntu21.21) ...
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/github_git-lfs.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
Reading package lists...
Building dependency tree...
Reading state information...
**E: Unable to locate package git-lfs
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y ssh netcat-openbsd git curl zip  &&     wget -qO /dev/stdout https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash &&     apt-get install -y git-lfs &&     git lfs install &&     rm -rf /var/lib/apt/lists/* &&     if [ -z ${socks_proxy} ]; then         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30\"" >> ${HOME}/.bashrc;     else         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ProxyCommand='nc -X 5 -x ${socks_proxy} %h %p'\"" >> ${HOME}/.bashrc;     fi' returned a non-zero code: 100**

**Comment by RajasekharKadasani** [comment]
starting i faced proxy i come over it by setting proxy,,,,,,.docker----config.json file

**Comment by nmanovic** [comment]
@RajasekharKadasani , you need to ask the question on our [gitter channel](https://gitter.im/opencv-cvat). It was answered many times. I will close the issue. I don't think that it is a bug in CVAT. Probably it is a gab in documentation but I don't feel that I can cover the topic completely. Internally we run CVAT behind a proxy without any issues. Of course you need to provide `-build-arg http_proxy=...` for your docker-compose command.
