### ISSUE TITLE
query on annotation tools?

### ISSUE THREAD

**Issue by Suzan009** [opencv/cvat#4803]
I have to question

1. What tools are available for 2D and 3D pose estimation cases? Do CVAT offer this? How to achieve this with cvat?
2. Do CVAT offer any functionality for depth estimation task? How to achieve this with cvat?

**Comment by nmanovic** [comment]
@Suzan009 , you can find the 2D  pose estimation in the PR: https://github.com/cvat-ai/cvat/pull/1

**Comment by nmanovic** [comment]
@Suzan009 , I will close the issue. Don't hestitate to submit a feature request.
