### ISSUE TITLE
Multiple storage devices

### ISSUE THREAD

**Issue by mrKallah** [opencv/cvat#4804]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Is it possible to import multiple storage drives? I tried using 

```
volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /media/share1/path/to/files/ &&/media/share2/path/to/files/
      o: bind
```

however, this did not work, is this possible, or should I use symlinks or something to make put a link to all the files in one folder? Thank you

### Expected Behaviour

Allow for multiple storage devices

### Current Behaviour

Not able to have multiple storage devices

### Possible Solution

symlinks

### Steps to Reproduce (for bugs)

1. have two places you wish to mount to your cvat
2. try to mount them
3. experience eternal dread

### Context

We have our data for different projects split on separate servers, we want to mount both of these devices to our cvat. If this is not possible, then we would have to look into doing something for handling creating symlinks for the different files in a central location

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@mrKallah , you can try to link/mount all your directories into one folder and share the common folder. I hope it will work. Also you can install [minio](https://github.com/minio/minio) and share data as cloud storages inside CVAT. I will close the issue. Don't hesitate to ask your questions on our discord or gitter charts.
