### ISSUE TITLE
Exporting big data annotations leads RAM leak

### ISSUE THREAD

**Issue by chaoyifei** [opencv/cvat#4809]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
   Export big data annotations 

### Current Behaviour
export big data annotaions about 2 million points  failed 

work-horse terminated unexpectedly ; waitpid returned9  （RAM 8G）

### Steps to Reproduce (for bugs)

1. export big data annotaions about 2 million  points,save_images=False
1. work-horse terminated unexpectedly ; waitpid returned9  

### Context

I found during debugging:

Memory leak point is  https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/dataset_manager/task.py line 43  _merge_table_rows 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@chaoyifei , we will look into the issue. I'm not sure that we will be able to fix it. Probably 8 Gb is not enough for such amount of data.

Are you working with images or videos in your case?

**Comment by chaoyifei** [comment]
> Probably 8 Gb is not enough for such amount of data.
> 
> Are you working with images or videos in your case?

I'm working with images ,but i think  there is a scenario:
At the same time, there are several big data set tasks to download,So simply increasing RAM is not enough

**Comment by bsekachev** [comment]
> At the same time, there are several big data set tasks to download,So simply increasing RAM is not enough

By default CVAT has two workers which are responsible for datasets exporting, so, you can export only two datasets simultaneously, others are in a queue.

**Comment by bsekachev** [comment]
I will close the issue for now. 
Do not hesitate to reopen if you have any updates.
