### ISSUE TITLE
mounting google drive folders using google-drive-ocaml

### ISSUE THREAD

**Issue by vikaschouhan** [opencv/cvat#481]
Hi,
Can I use images on google drive directly in cvat. May be mount it using google-drive-ocaml in the docker container and using it as cvat_share (share path).
Have anyone tried it ?
Thanks

**Comment by nmanovic** [comment]
@vikaschouhan , if you can mount google drive directly into a directory on host you can use it as cvat_share. No problems here. Please submit your next questions to our [gitter chat](https://gitter.im/opencv-cvat). I will close the issue.
