### ISSUE TITLE
Allow skip annotations with problems on import/export

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#4811]
**Idea**

> [...] is there a way to still import the annotations when some files are missing (ie you want to revise/reannotate part of your dataset)?

_Originally posted by @nskostas in https://github.com/opencv/cvat/issues/4617#issuecomment-1137198208_

**Possible implementation**
- Add a page with dataset/annotations import options, like we implemented for export
- The page should list error control options and format options
- Maybe add frame filter and transformations (data projections)

Related: 
- Other ideas described here: https://github.com/openvinotoolkit/datumaro/issues/142 
- Error control for import/export in Datumaro: https://github.com/openvinotoolkit/datumaro/pull/650 (requires CVAT to upgrade Datumaro dependency to [v0.3](https://github.com/openvinotoolkit/datumaro/releases/tag/v0.3))

**Comment by nmanovic** [comment]
We are not going to support that in the nearest future. If annotations have errors, it can potentially lead to other problems. I hope it can be workarounded by CVAT SDK in the future.
