### ISSUE TITLE
cvat_opa not running

### ISSUE THREAD

**Issue by venki-lfc** [opencv/cvat#4815]
### My actions before raising this issue
- [X ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X ] Searched [past issues](/issues)

I want to run cvat locally in my windows machine and I am unable to run the containers properly when I enter `docker-compose up -d`. The traefik, cvat_db and cvat_redis containers are running but the rest do not.  It looks like cvat_opa is the culprit here. 

In CLI:

> C:\Users\Venkatesan.KALAPATTI\Projects\cvat>docker-compose up -d
WARNING: The no_proxy variable is not set. Defaulting to a blank string.
Creating network "cvat_cvat" with the default driver
Creating cvat_opa ...
Creating traefik    ... done
Creating cvat_db    ... done
Creating cvat_redis ... done

Docker GUI:
![image](https://user-images.githubusercontent.com/60582874/185967125-656d4e72-30c8-44d3-913b-f897f723b1b0.png)

Commenting out volumes, however, causes the container to run.

>   cvat_opa:
    container_name: cvat_opa
    image: openpolicyagent/opa:0.34.2-rootless
    restart: always
    networks:
      cvat:
        aliases:
          - opa
    #volumes:
    #  - ./cvat/apps/iam/rules:/rules
    ports:
      - '8181:8181'
    command: run --server --addr :8181 --set=decision_logs.console=true /rules

In Docker GUI, after commenting out volumes in OPA
![image](https://user-images.githubusercontent.com/60582874/185967861-efd14fc3-8778-4547-9faa-9257e542cf7f.png)

Could you please tell me how to get rid of this issue?

### Steps to Reproduce (for bugs)
1. `git clone https://github.com/opencv/cvat`
2. `cd cvat`
3. `docker-compose up -d`

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` : v20.10.17
- Are you using Docker Swarm or Kubernetes?: No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
> level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
cvat_db | 
cvat_db | PostgreSQL Database directory appears to contain a database; Skipping initialization
cvat_db | 
cvat_db | 2022-08-22 16:12:46.457 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
cvat_db | 2022-08-22 16:12:46.457 UTC [1] LOG:  listening on IPv6 address "::", port 5432
cvat_db | 2022-08-22 16:12:46.464 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
cvat_db | 2022-08-22 16:12:46.483 UTC [22] LOG:  database system was shut down at 2022-08-22 16:12:40 UTC
cvat_db | 2022-08-22 16:12:46.489 UTC [1] LOG:  database system is ready to accept connections
traefik | time="2022-08-22T16:12:46Z" level=info msg="Configuration loaded from flags."
traefik | time="2022-08-22T16:12:46Z" level=error msg="Cannot start the provider *file.Provider: unable to read directory /etc/traefik/rules: open /etc/traefik/rules: no such file or directory"
cvat_redis | 1:C 22 Aug 16:12:46.187 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cvat_redis | 1:C 22 Aug 16:12:46.187 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
cvat_redis | 1:C 22 Aug 16:12:46.187 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cvat_redis | 1:M 22 Aug 16:12:46.189 * Running mode=standalone, port=6379.
cvat_redis | 1:M 22 Aug 16:12:46.189 # Server initialized
cvat_redis | 1:M 22 Aug 16:12:46.189 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
cvat_redis | 1:M 22 Aug 16:12:46.189 * Ready to accept connections

**Comment by bsekachev** [comment]
Hi @venki-lfc

First of all, let's abort any changes in docker configuration. CVAT will not work without cvat opa container.
I would suggest to find some logs to understand why the process freezes.

**Comment by bsekachev** [comment]
I closed the issue for now, please, do not hesitate to reopen it, if the issue is still relevant
