### ISSUE TITLE
`cvat_server` container does not start successfully

### ISSUE THREAD

**Issue by maltoze** [opencv/cvat#4816]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

`cvat_server` container should be start successfully

### Current Behaviour

please see logs

### Possible Solution

https://github.com/opencv/cvat/blob/5e2eda76014c325c69dc297749d1d123ed315626/Dockerfile#L147

may be this should be added before.
```
RUN mkdir ${HOME}/supervisord
```

### Steps to Reproduce (for bugs)

1. git clone https://github.com/opencv/cvat
2. cd cvat
3. docker-compose up -d

### Your Environment

- Git hash commit (`git log -1`): 916b5dcfd840d066ca4d4673a65fa4226150eb15
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.6
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Logs

```bash
docker logs -f --tail=100 cvat_server
```
output:
```
Error: could not find config file supervisord/server.conf
For help, use /usr/bin/supervisord -h
Error: could not find config file supervisord/server.conf
For help, use /usr/bin/supervisord -h
Error: could not find config file supervisord/server.conf
For help, use /usr/bin/supervisord -h
Error: could not find config file supervisord/server.conf
For help, use /usr/bin/supervisord -h
Error: could not find config file supervisord/server.conf
For help, use /usr/bin/supervisord -h
```

**Comment by nmanovic** [comment]
@azhavoro , could you please look?

**Comment by chaoyifei** [comment]
your docker version ?  

Maybe you can try     COPY --chown=“django” supervisord/ ${HOME}/supervisord

**Comment by azhavoro** [comment]
@maltoze Hi,

The reason is that the build config doesn't really point to development images, so as a workaround I would suggest 2 options:
specify version `CVAT_VERSION=dev docker-compose up -d` 
or build actual images yourself with
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

As generall solution I think we can set `dev` instead of `latest` for develop and pin actual version for each CVAT release. Now downloading the compose config from the develop branch, we do not run a really developed version, actually we run the latest release. @nmanovic @klakhov  What do you think?

**Comment by tlpss** [comment]
@azhavoro  I'm encountering the same issue. Could you specify how I should get the latest release of CVAT up and running using docker-compose?

**Comment by azhavoro** [comment]
> @azhavoro I'm encountering the same issue. Could you specify how I should get the latest release of CVAT up and running using docker-compose?
Try this
```shell
CVAT_VERSION=dev docker-compose pull
CVAT_VERSION=dev docker-compose up -d
```

**Comment by tlpss** [comment]
@azhavoro that works indeed, but it seems strange that we should deploy with the 'dev' tag? Will these always be stable?

**Comment by azhavoro** [comment]
> @azhavoro that works indeed, but it seems strange that we should deploy with the 'dev' tag? Will these always be stable?

The problem is only relevant for the develop branch, so I don't think it's strange to use `dev` images with the development branch. If you want to deploy the latest release: https://github.com/opencv/cvat/releases/tag/v2.1.0.

**Comment by tlpss** [comment]
> The problem is only relevant for the develop branch, so I don't think it's strange to use dev images with the development branch. If you want to deploy the latest release: https://github.com/opencv/cvat/releases/tag/v2.1.0.

My bad @azhavoro , I didn't notice the default branch on github was the development branch! Thanks for your reply.
