### ISSUE TITLE
Utilize development configuration in docker-compose

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#4818]
### Current Behaviour

It seems like nowhere in the dev containers the `development` configuration of Django is set. Thus, we can't obtain stack traces if something fails, and we can't see informative error messages if we just follow the deployment guide.

Also, we can possibly add request/response tracing on the server with a solution like this -https://gist.github.com/SehgalDivij/1ca5c647c710a2c3a0397bce5ec1c1b4

### Possible Solution

Possibly, we can use `development` Django configuration when we start containers with `docker-compose ... -f docker-compose.dev.yml ...`.

### Your Environment

- Git hash commit (`git log -1`): [916b5dc](https://github.com/opencv/cvat/commit/916b5dcfd840d066ca4d4673a65fa4226150eb15)

**Comment by nmanovic** [comment]
@zhiltsov-max , let's close the issue. We are developing CVAT without containers usually. Also you added a way to debug containers. I believe it is enough for now.
