### ISSUE TITLE
SDK Timeline

### ISSUE THREAD

**Issue by connor11son** [opencv/cvat#4827]
I was wondering if there is a status/timeline for the SDK?

**Comment by zhiltsov-max** [comment]
Hi! Thank you for interest for this part of CVAT. I cannot provide any time estimates, but we are actively working on this feature, and a big part of functionality is already covered in the existing PRs: #4813, #4819. We'll publish PyPI packages as soon as we can.

Are there any specific requirements or other thoughts from your side, that you would like to discuss?

Related: #4637

**Comment by connor11son** [comment]
Hi there,

I have seen that there is active development on the SDK in those branches, but the (understandable) lack of documentation makes installation difficult. I think for my particular case we will just end up writing our own wrapper around the API to do what we need, but if any help is needed with documentation I would be glad to help.

**Comment by zhiltsov-max** [comment]
You can find development installation instructions here: https://github.com/opencv/cvat/blob/develop/cvat-sdk/developer_guide.md#how-to-generate-api . Basically, you need to know that there is a handwritten and an auto-generated parts. To generate the code, you need to do the following:

```bash
git clone https://github.com/opencv/cvat
cd cvat/

# Set up python
python -m virtualenv venv
. venv/bin/activate

# Install server and generator requirements
pip install -r cvat/requirements/development.txt
pip install -r cvat-sdk/gen/requirements.txt

# Obtain REST API schema
python manage.py spectacular --file schema.yml && mkdir -p cvat-sdk/schema/ && mv schema.yml cvat-sdk/schema/

# Generate SDK API code
cd cvat-sdk/
gen/generate.sh

# Install packages
cd ../
pip install -e cvat-sdk/ # '-e' if you want to edit the code without reinstalling the package
pip install -e cvat-cli/
```

After this, you'll be able to use both updated CLI and SDK. SDK tests and code examples are here: https://github.com/opencv/cvat/blob/develop/tests/python/sdk/test_tasks.py#L86

**Comment by connor11son** [comment]
Thank you very much! Is there a base image from which I can start from and run the above?

**Comment by zhiltsov-max** [comment]
No, currently there is no such image. The generated code relies on the latest develop branch changes on the server schema output, so you need to pull the develop branch.

**Comment by zhiltsov-max** [comment]
Hi, we have published [`cvat-sdk`](https://pypi.org/project/cvat-sdk/) and [`cvat-cli`](https://pypi.org/project/cvat-cli/) packages on PyPI. Install with `pip install cvat-sdk cvat-cli`.

**Comment by connor11son** [comment]
Awesome, thank you very much. We will try it out today.

**Comment by connor11son** [comment]
One thing: on the PyPI page it says that Python>=3.7 is needed, however the sdk will only work in 3.8 and above due to [this](https://github.com/opencv/cvat/blob/7218f4e2834722b4eccead8096cff7821348facd/cvat-sdk/cvat_sdk/core/proxies/model_proxy.py#L16) line.

[Related](https://stackoverflow.com/questions/61206437/importerror-cannot-import-name-literal-from-typing).
