### ISSUE TITLE
Improve e-mail confirmation and other e-mail templates

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4831]
We are using https://github.com/pennersr/django-allauth for authorization. It can send emails and have different templates which can be customized. See the documentation: https://github.com/pennersr/django-allauth/blob/master/docs/advanced.rst#sending-email

Need to copy templates from https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account/messages and provide 2 versions: txt and html.

Nice e-mail templates can be found here: https://github.com/sendgrid/email-templates/tree/master/paste-templates

To test how e-mails are working it is possible to use https://mailtrap.io/

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/40690625/180648708-e612b02b-e2dd-4321-8152-a0bbae02f3f9.png">

Issue by @nmanovic

**Comment by nmanovic** [comment]
It was implemented by @Marishka17 . I will close the issue.
