### ISSUE TITLE
Export Task and Job State

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4834]
#Feature Request
Hi, i think it could be great that for the cvat_annotation format export ( at project or task label) the xml object for the task and jobs (segments) contains the status of each, as their appear on the page.

Currently i have some "open" tasks.. and when i export the dataset for annotation i cant know which ones are actually finished and which doesnt.. this leads to BAD training
THANKS

Issue by @malfonso0

**Comment by nmanovic** [comment]
@malfonso0, I hope CVAT SDK should fix the issue. Please try cvat-sdk

**Comment by malfonso0** [comment]
hi, yes, i have starting using the sdk. where i download the project/task/job information and then download only jobs with completed status.
this is a little por complex that just download the project in cvat data with all the informations, but still ok
