### ISSUE TITLE
Remove the user if an email confirmation cannot be sent 

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4837]
We had some problems with our free email server. I was not able to register a new user. Now after all problems were resolved, I tried to register again but got the error below. Need to delete the user if we cannot send a confirmation email.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/40690625/181238463-6e0b2c11-87ec-4683-a95d-4b6f020cfffa.png">

Issue by @nmanovic

**Comment by nmanovic** [comment]
@Marishka17 , need to have a way to resent the confirmation email.

**Comment by Marishka17** [comment]
@nmanovic, it was implemented. Now if the user has an unverified email and tries to log in then a new confirmation email will be sent.
