### ISSUE TITLE
Can't fully utilize TUS protocol

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4839]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Current Behaviour

TUS protocol supposes a leading HEAD request to retrieve file state on the server. Server supports this, but `traefik` converts these HEAD requests to GET, and then server rejects it. Thus, we cannot continue an interrupted file uploading.

Workaround: both UI and SDK always send files from scratch. It leads to:
- more user traffic
- possible filename conflicts (partially uploaded files are not autoremoved)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Issue by @zhiltsov-max

**Comment by SpecLad** [comment]
After investigation, I found out that traefik is innocent. The one converting the requests is actually mod\_wsgi, as explained [here](https://github.com/GrahamDumpleton/mod_wsgi/blob/4.9.4/src/server/mod_wsgi.c#L6293). I'm currently investigating if it would be safe to turn this functionality off (I believe it should be).

**Comment by zhiltsov-max** [comment]
Great news! The checks in the function suggest to look at the configuration parameters.

**Comment by SpecLad** [comment]
@zhiltsov-max The description says that there's a workaround in the UI to always send files from scratch, but I don't see where this workaround is implemented. It seems like the UI just uses `tus-js-client` normally. Does this workaround actually exist?

**Comment by zhiltsov-max** [comment]
@SpecLad. Speaking about UI, I don't remember checking the library itself (maybe I did, but I just don't remember). I see there is a comment about [the implementation](https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L596-L602) that "we try, and if it fails, we start from scratch". I can't say it's a workaround, probably for UI I just meant that there is no option to continue uploading anywhere, because this scenario is not expected.
