### ISSUE TITLE
Boundary Box Capture

### ISSUE THREAD

**Issue by KevinLe1997** [opencv/cvat#484]
Hi all,

A task given to me was to try to build upon the functionality of CVAT. Right now, I want to make it so that I am able to extract the actual pixels within a boundary box to be exported. How would you suggest I go about tackling this problem?

**Comment by nmanovic** [comment]
@KevinLe1997 , we have the [gitter channel](https://gitter.im/opencv-cvat) for such questions. The best way to extract actual pixels within a bounding box is to implement a python script which does that.
