### ISSUE TITLE
Second click on a confirmation link for registration lead to 500 error

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4841]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/40690625/181243644-b55ace2a-c430-41f1-afbf-f0d3fd8eb12a.png">

Issue by @nmanovic

**Comment by nmanovic** [comment]
@yasakova-anastasia , please don't link. Better create an issue in the repo and delete the old one.

**Comment by Marishka17** [comment]
Has been fixed in #5147
