### ISSUE TITLE
Github pages is down

### ISSUE THREAD

**Issue by dschoerk** [opencv/cvat#4849]
Tried to access the manual but it seems all the links pointing to https://cvat-ai.github.io are down. 

e.g.: https://cvat-ai.github.io/cvat/docs/

**Comment by nmanovic** [comment]
@dschoerk , thank you. We are working to resolve the issue. Please use the link for now: https://opencv.github.io/cvat/docs/

**Comment by dschoerk** [comment]
thanks!

**Comment by nmanovic** [comment]
@azhavoro , we didn't think that we will move documentation multiple times. Need to find a solution. Should we contact GitHub support for the help? Need to redirect old domains if it is possible.

**Comment by azhavoro** [comment]
I think we need configure custom domain like docs.cvat.ai for both repos.
