### ISSUE TITLE
Uploading ".mpg" Files

### ISSUE THREAD

**Issue by KevinLe1997** [opencv/cvat#485]
Hi, 

I tried uploading a ".mpg" file to CVAT to annotate, but am greeted with this error:

Can not create task. ffmpy.FFRuntimeError: `ffmpeg -i /home/django/data/42/.upload/MISB_552.mpg -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 /tmp/cvat-j8hajioq.data/%d.jpg` exited with status 1 STDOUT: STDERR:

Is there a way around this? Does CVAT not accept ".mpg" files?

**Comment by nmanovic** [comment]
@KevinLe1997 ,

We support formats which accepted by ffmpeg. Probably your file is corrupted. Could you please check that on your side?

**Comment by KevinLe1997** [comment]
Is there a certain way to check for corruption? I am able to perfectly load it on my computer and view it.

**Comment by nmanovic** [comment]
@KevinLe1997 , just run ffmpeg command above and see its output. I will close the issue for now. Don't hesitate to ask additional questions. If you think that CVAT has a bug just submit an appropriate issue with exhaustive description (it should have enough information to reproduce the problem) and we will try to investigate and fix it.
