### ISSUE TITLE
DB lock in development mode when creating two tasks at the same time

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4857]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

It is expected that in development mode (with sqlite as the DB) and in production mode it be possible to create multiple (2) tasks in parallel. behavior should be the same for development and production mode.

### Current Behaviour

Error: `Could not create the task on the server. django.db.utils.OperationalError: database is locked.`

### Steps to Reproduce (for bugs)

1. Run in development mode (with sqlite as DB)
2. Open two tabs on create task page and fill data (video file is preferable for the task to be created for some time)
3. Click on Submit button in both tabs

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Issue by @AlexeyAlexeevXperienceAI

**Comment by nmanovic** [comment]
Probably need to use PostgreSQL for development as well. Too many problems with SQLite.

**Comment by azhavoro** [comment]
Fixed by #5999
