### ISSUE TITLE
How to use polyshapeEditor？

### ISSUE THREAD

**Issue by guozj583** [opencv/cvat#486]
Hey,friend:	
  When I used the polyline shape to complete the video annotation, I pressed stop create
Button. However, I later found out that I missed one point. I need to add one point based on the original shape. How can I implement such a function?
 
  Also, I have studied polyshapeEditor.js, but I did not see the function implementation of the script on the UI interface, I don't know how to use it. Could you guide me how to do it?

thanks.

**Comment by nmanovic** [comment]
Hi @guozj583 , I'm not sure that I understand your question. If you don't know how to draw a polygon in UI you need to read [the user guide](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md) and look at [the screencast](https://www.youtube.com/watch?v=XTwfXDh4clI). Again please don't use "issues" to ask questions. Next time I will close such issue from you without an answer. We have the [gitter channel](https://gitter.im/opencv-cvat) for such questions.

**Comment by guozj583** [comment]
OK, I see.
