### ISSUE TITLE
Non admin user can't use interactor (HRNET) 403 permission denied error

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4860]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Loging in as Admin user lets me use HRNET 
Being logged in as a worker account throws an Error:
```
Interaction error occured
Error: Request failed with status code 403. {"detail":"You do not have permission to perform this action."}.
```
in this thread it seems to have been observed as well:
https://github.com/openvinotoolkit/cvat/issues/4548

### Expected Behaviour
No error, same behaviour admin and worker

### Current Behaviour
Error see above

### Steps to Reproduce (for bugs)
1. Add 2 users, one admin one worker
2. use HR net with both, admin works, worker throws permission error

### Context
Installing it and using HRNET in an larger effort to annotate data for speeding up the annotation process.

### Your Environment
- Git hash commit (`git log -1`): 3a88677eb4b6d509c3640ca2ec4dab662f642a55

Issue by @nikste

**Comment by zhangzhangzhiyuan** [comment]
hi, yasakova-anastasia
i have met that problem too, have u solve this problem already?

**Comment by alex4men** [comment]
@yasakova-anastasia @zhangzhangzhiyuan here is the fix: https://github.com/opencv/cvat/issues/4996#issuecomment-1266185805
