### ISSUE TITLE
Fix unstable E2E test

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4862]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
Test case `actions_tasks3/case_107_connected_file_share.js` [fails](https://github.com/opencv/cvat/runs/7962156616?check_suite_focus=true). Need to fix such unstable behavior.

Issue by @kirill-sizov

**Comment by kirill-sizov** [comment]
Fixed in #4892
