### ISSUE TITLE
Documentations Unavailable and Documentation Archive

### ISSUE THREAD

**Issue by varungupta31** [opencv/cvat#4864]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Several GitHub Pages including the ones for [Manual](https://cvat-ai.github.io/cvat/docs/manual/), [CLI](https://cvat-ai.github.io/cvat/docs/manual/advanced/cli/), [FAQ](https://cvat-ai.github.io/cvat/docs/faq/), are unavailable.

And, Is there an archive for the documentation (CLI) for the openvinotoolkit's version of the CVAT?

Kindly resolve,
Thanks.

![image](https://user-images.githubusercontent.com/51288316/186893500-3737ad68-1d85-4852-85b4-7eb7ffd04fed.png)

**Comment by azhavoro** [comment]
We are working to resolve the issue. Please use the link for now: https://opencv.github.io/cvat/docs/

Duplicate #4849
