### ISSUE TITLE
Split dataset after task creation

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4869]
Hi! 

Is it possible to split task data to jobs after data uploading ? I didn't find how to do it. It's possible to split data to jobs only on uploading stage. I need to split task data to distribute the work among annotators. If it is possible how to manually select which image append in which job, to be able to manager choose images for all annotators in a balanced way in complexity.

Issue by @RocketFlash

Hi,

> Is it possible to split task data to jobs after data uploading ?

No. In the future we were planning to add the feature to make jobs, but we do not have any implementation details. Maybe it will be available only cloning existing jobs. 

> I need to split task data to distribute the work among annotators. 

Just do it on creating task stage. 

>  If it is possible how to manually select which image append in which job, to be able to manager choose images for all annotators in a balanced way in complexity.

You can specify segment size == 1, and choose images for annotators independently. 

Answer by @bsekachev

**Comment by nmanovic** [comment]
I will close the issue. I hope the PR https://github.com/opencv/cvat/pull/5536 will solve it partially.
