### ISSUE TITLE
Images are reloaded and not cached. Creates Flickering.

### ISSUE THREAD

**Issue by mistermult** [opencv/cvat#487]
Recreate the bug:
* Use the master branch or develop branch
* Start CVAT and annotate a video (in debug mode or in docker
* Open the network tab in the Chrome debugger.
* Move the slider to change the frames.
* For each frame a new HTTP-Request is send to the server to get the image for the frame (see the waiting time in the for the Request). While loading the player is empty and blue. This creates a flickering and the user cannot quickly judge if everything is annotated correctly in the video.

I think the images were cached in the past and were only loaded at the beginning. The code for the FrameProvider seems to implement some caching, but it is not working.

**Comment by Ai-is-light** [comment]
when I restarted my Mac, and reload this repo and tool, I got ERR_EMPTY_RESPONSE, anyway, I can't restart the tool again

**Comment by nmanovic** [comment]
@Ai-is-light , run the following commands `docker-compose down` and `docker-compose up -d`. It should help.

**Comment by nmanovic** [comment]
We will investigate the issue with caching images. Thanks for the report.

**Comment by nmanovic** [comment]
@Ai-is-light , a couple of questions:
- Could you please check that when you open "Chrome debugger" caching actually is enabled?

![image](https://user-images.githubusercontent.com/40690625/59654753-7a7c0180-914c-11e9-8a34-f95b41bb0f80.png)

**Comment by bsekachev** [comment]
@azhavoro 

I suppose we can close the issue for now with introducing data streaming patch
