### ISSUE TITLE
Error: No such container: cvat

### ISSUE THREAD

**Issue by sunwell1994** [opencv/cvat#4872]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

always return this error when execute the image. No error when compiling and building. 
### Expected Behaviour

after 

> docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
 CVAT should be open at the port 

### Current Behaviour

return "Error: No such container: cvat"

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`): commit 53697ecac5e77804a774658adf3700ca64d6f81a

- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.17
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by YIminta** [comment]
docker-compose.yml file has been modified：cvat -> cvat_server

so use
sudo docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'

**Comment by YIminta** [comment]
docker-compose.yml中的容器名字修改了，原来是cvat，现在是cvat_server。使用sudo docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser' 试试吧

**Comment by sunwell1994** [comment]
> docker-compose.yml file has been modified：cvat -> cvat_server
> 
> so use sudo docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'

Thanks a lot. It works.

**Comment by pengwenbangGithub** [comment]
> 

多谢
