### ISSUE TITLE
havent permission to perform 

### ISSUE THREAD

**Issue by zhangzhangzhiyuan** [opencv/cvat#4874]
HI,that is my first time to use github. may i raise a question?
when i create a new project or a task, the website(www.cvat.org) imform me that: error code:403, u havent permission to perform......
so, how can i use cvat as before. 
by the way cvat is the best tool in annotation field after my countless failure.

**Comment by nmanovic** [comment]
@zhangzhangzhiyuan , cvat.org is in readonly mode. Please use cvat.ai instead: http://app.cvat.ai/. I will close the issue.

**Comment by zhangzhangzhiyuan** [comment]
thanks for your reply. u are really a kind man

Nikita Manovich ***@***.***> 于2022年8月29日周一 12:02写道：
