### ISSUE TITLE
Error: Could not check authorization on the server. Open the Browser Console to get details

### ISSUE THREAD

**Issue by kulanjith404** [opencv/cvat#4881]
HI,

I just install CVAT in  Ubuntu 18.04LTS. All installations and configurations did without any error. But when I load the CVAT site it's getting the error "Could not check authorization on the server. Open the Browser Console to get details". Please help.

![Capture](https://user-images.githubusercontent.com/88020828/187316767-6dc8d19f-308c-47e3-bd69-25f50e2ec5a5.PNG)

![Untitled](https://user-images.githubusercontent.com/88020828/187317523-5f5a01bd-a289-47f9-a919-774f7d6b5ce8.png)

**Comment by bsekachev** [comment]
Hi, 

Look at Network tab, probably you will see some failed requests there. 
Have you changed any default host/port values?

**Comment by kulanjith404** [comment]
Hi Bsekachev,

The network tab to totally empty. Please find the attached image also I didn't change any ports. Shall I send the docker.compose.yml file?

![Capture](https://user-images.githubusercontent.com/88020828/187364403-86beaf45-489b-42c1-bd6a-c24337ff54ee.PNG)

**Comment by kulanjith404** [comment]
# Copyright (C) 2018-2022 Intel Corporation
#
# SPDX-License-Identifier: MIT

version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
      CVAT_HOST: <cvat.projectx.com>
    volumes:
      - cvat_db:/var/lib/postgresql/data
    networks:
      - cvat

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    restart: always
    networks:
      - cvat

  cvat_server:
    container_name: cvat_server
    image: cvat/server:${CVAT_VERSION:-latest}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      ADAPTIVE_AUTO_ANNOTATION: 'false'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
      NUMPROCS: 1
    command: -c supervisord/server.conf
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat.loadbalancer.server.port=8080
      - traefik.http.routers.cvat.rule=Host(`${CVAT_HOST:-cvat.projectx.com}`) &&
        PathPrefix(`/api/`, `/git/`, `/opencv/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)
      - traefik.http.routers.cvat.entrypoints=web
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cvat_utils:
    container_name: cvat_utils
    image: cvat/server:${CVAT_VERSION:-latest}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
    command: -c supervisord/utils.conf
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_worker_default:
    container_name: cvat_worker_default
    image: cvat/server:${CVAT_VERSION:-latest}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
      NUMPROCS: 2
    command: -c supervisord/worker.default.conf
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_worker_low:
    container_name: cvat_worker_low
    image: cvat/server:${CVAT_VERSION:-latest}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
      NUMPROCS: 1
    command: -c supervisord/worker.low.conf
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_ui:
    container_name: cvat_ui
    image: cvat/ui:${CVAT_VERSION:-latest}
    restart: always
    depends_on:
      - cvat_server
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat-ui.loadbalancer.server.port=80
      - traefik.http.routers.cvat-ui.rule=Host(`${CVAT_HOST:-cvat.projectx.com}`)
      - traefik.http.routers.cvat-ui.entrypoints=web
    networks:
      - cvat

  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: always
    command:
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=cvat'
      - '--entryPoints.web.address=:8080'
      - '--providers.file.directory=/etc/traefik/rules'
    # Uncomment to get Traefik dashboard
    #   - "--entryPoints.dashboard.address=:8090"
    #   - "--api.dashboard=true"
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.dashboard.entrypoints=dashboard
    #   - traefik.http.routers.dashboard.service=api@internal
    #   - traefik.http.routers.dashboard.rule=Host(`${CVAT_HOST:-localhost}`)
    ports:
      - 8080:8080
      - 8090:8090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - cvat

  cvat_opa:
    container_name: cvat_opa
    image: openpolicyagent/opa:0.34.2-rootless
    restart: always
    networks:
      cvat:
        aliases:
          - opa
    volumes:
      - ./cvat/apps/iam/rules:/rules
    ports:
      - '8181:8181'
    command: run --server --addr :8181 --set=decision_logs.console=true /rules

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:

networks:
  cvat:

**Comment by bsekachev** [comment]
> The network tab to totally empty. Please find the attached image also I didn't change any ports. Shall I send the docker.compose.yml file?

First you need to open Network tab, then update page :)

**Comment by bsekachev** [comment]
Also, please provide ``docker ps`` output.

**Comment by kulanjith404** [comment]
Hi Bsekachev,

Here I attachthe output of docker ps

![Capture](https://user-images.githubusercontent.com/88020828/187497025-0ffad08d-b7c3-4e10-88c6-3072051dd521.PNG)

**Comment by bsekachev** [comment]
@kulanjith404 

Try to enable checkbox "Disable cache" and update the page, what do you see then?

**Comment by kulanjith404** [comment]
@bsekachev 

Then it seems to like this

![Capture](https://user-images.githubusercontent.com/88020828/187498502-d7d04b6f-6b69-47f1-8174-4d215965878d.PNG)

**Comment by bsekachev** [comment]
@kulanjith404 

Oh, now on the screenshot with ``docker ps`` I see you have multiple ``cvat/server:latest`` and they all are restarting.
It means that the server is unhealphy.
Try to attach us logs ``docker logs cvat``

**Comment by kulanjith404** [comment]
FYI

![Capture](https://user-images.githubusercontent.com/88020828/187499887-15693aca-b1fd-480f-b56f-9b71870ceab1.PNG)

**Comment by kulanjith404** [comment]
@bsekachev 

if you like I can provide an Anydesk to you.

**Comment by bsekachev** [comment]
@kulanjith404 

What about ``docker logs cvat_server``?

**Comment by kulanjith404** [comment]
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:27:32.240578116Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:27:32.240605045Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:27:33.87940005Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:27:33.879434879Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:27:36.176817666Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:27:36.176849537Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:27:38.995251171Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:27:38.995282493Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:27:43.282917072Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:27:43.282963275Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:27:50.799051705Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:27:50.799095209Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:28:05.947468219Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:28:05.947506013Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:28:32.819095398Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:28:32.819142229Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:29:25.244538866Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:29:25.244594587Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:30:26.370332587Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:30:26.370419188Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:31:28.130305531Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:31:28.130356525Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:32:30.373557255Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:32:30.373602918Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:33:31.523902136Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:33:31.52395242Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:34:32.796118645Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:34:32.796153939Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:35:34.029614331Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:35:34.029656567Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:36:35.204237368Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:36:35.204295338Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:37:36.33347186Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:37:36.333512441Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:38:37.536780911Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:38:37.536821989Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:39:38.659117319Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:39:38.659159546Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:40:39.811789067Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:40:39.811829718Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:41:40.962609993Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:41:40.962654121Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:42:42.080300118Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:42:42.080341913Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:43:43.24753589Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:43:43.247578784Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:44:44.356065545Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:44:44.356106536Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:45:45.429396575Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:45:45.429454786Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:46:46.645070536Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:46:46.645115803Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:47:47.797770318Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:47:47.797820652Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:48:48.87947166Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:48:48.880456274Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:49:50.002770671Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:49:50.002856376Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:50:51.200989199Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:50:51.201028632Z"}
{"log":"Error: could not find config file supervisord/worker.low.conf\n","stream":"stderr","time":"2022-08-29T23:51:59.026019902Z"}
{"log":"For help, use /usr/bin/supervisord -h\n","stream":"stderr","time":"2022-08-29T23:51:59.026046278Z"}

**Comment by bsekachev** [comment]
@kulanjith404 

Try to rebuild with this command ``docker-compose up -d --build`` 🤔

**Comment by bsekachev** [comment]
I will close the issue. Please, do not hesitate to reopen if you are still experiencing the issue.

**Comment by kulanjith404** [comment]
The Issue is still same. :(

**Comment by bsekachev** [comment]
Then, please provide the following:

- Commit hash
- Has you changed anyhow the default configuration?
- Did you try to rebuild as I suggested before?

**Comment by kulanjith404** [comment]
No, I only changed localhost domain in docker.compose.yml file

Yes, I tried it before

**Comment by bsekachev** [comment]
@kulanjith404 

To change default host, please follow FAQ: https://opencv.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

Do not try to update the configuration in this case.

**Comment by kulanjith404** [comment]
I'm gonna reinstall the CVAT server to the new fresh ubuntu 18.04 and implement it again. I'll give an update after that. Please open this ticket until I implement it again. Thanks for the given support. @bsekachev

**Comment by bsekachev** [comment]
It was more than month from your latest reply, I hope you sorted it out. 
I will close the issue. Please, comment if you didn't.

**Comment by dnns92** [comment]
Dear @kulanjith404, did you fix this? I'm still getting this error.

Cheers.
