### ISSUE TITLE
datumaro custom dataset import/export

### ISSUE THREAD

**Issue by yaeji98** [opencv/cvat#4884]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am currently looking for a custom dataset export method.

custom dataset is composed of json files

is there solution?

### Expected Behaviour

```
@importer(name='Custom', ext='JSON', version='1.0')
def _import(src_file, instance_data, load_data_callback=None):

    dataset = Dataset.import_from(src_file.name, 'custom_format',env=dm_env)

    import_dm_annotations(dataset, instance_data)
```
i expect import custom json file 
So I want an antonation to be drawn cvat tools.

### Current Behaviour

`Error: Request failed with status code 500. "datumaro.components.errors.NoMatchingFormatsError: Failed to detect dataset format automatically: no matching formats found\n".`

### Steps to Reproduce (for bugs)

1. move to cvat -> apps -> dataset_manager -> formats 
2. create 'custom.py' file
```
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT

from tempfile import TemporaryDirectory

from datumaro.components.dataset import Dataset
# from datumaro.components.extractor import DatasetItem, Bbox

from cvat.apps.dataset_manager.bindings import GetCVATDataExtractor, \
    import_dm_annotations
from cvat.apps.dataset_manager.util import make_zip_archive

from .registry import dm_env, exporter, importer

@exporter(name='Custom', ext='ZIP', version='1.0')
def _export(dst_file, instance_data, save_images=False):
    dataset = Dataset.from_extractors(GetCVATDataExtractor(
        instance_data, include_images=save_images), env=dm_env)
    with TemporaryDirectory() as temp_dir:
        dataset.export(temp_dir, 'custom_instances', save_images=save_images,
            merge_images=True)

        make_zip_archive(temp_dir, dst_file)

@importer(name='MAICLOUD', ext='JSON', version='1.0')
def _import(src_file, instance_data, load_data_callback=None):

    dataset = Dataset.import_from(src_file.name, 'custom_format',env=dm_env)

    import_dm_annotations(dataset, instance_data)

```
4. docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
5. docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
6. localhost:8080

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by kirill-sizov** [comment]
Hi, @yaeji98, we have special section in our documentation: [**How to add new annotation format** ](https://opencv.github.io/cvat/docs/contributing/new-annotation-format/) see it.

In general you two ways to add your custom format into the CVAT:

1. Implement your custom format in Datumaro and in this case code snippet that you provided should works. See Datumaro [docs](https://cvat-ai.github.io/datumaro/docs/) and [code](https://github.com/openvinotoolkit/datumaro) to get more information about it.
2. Implement exporting and importing inside in your `custom.py` see [CVAT format implementation as example](https://github.com/opencv/cvat/blob/develop/cvat/apps/dataset_manager/formats/cvat.py)
