### ISSUE TITLE
[cvat-ui] dashboard

### ISSUE THREAD

**Issue by zankevich** [opencv/cvat#489]
Pre-requirements:
- [x] Typescript support
- [x] Redux setup (thunk, logger)
- [x] Antd setup (customize variables)
- [x] React router setup (with protected routes)

Login page: (blocked, est. ~1d)
- [x] Login form with validations
- [x] Login/logout actions and reducer
- [x] Redirects if already logged in or on success login

Register page: (blocked, est. ~2d)
- [x] Register form with validations
- [x] Register actions and reducer
- [x] Redirects if logged in or registered

Page not found:
- [x] Display some message and button to redirect on default page (`/dashboard`)
- [x] Redirect here if asking for unexisting page

Dashboard page:
- [x] Display list of tasks with pagination
- [x] Create task modal form with validations
- [x] Update task modal form with validations
- [x] Upload annotation dialog
- [x] Dump annotation dialog
- [x] Delete task
- [x] Filter tasks with persisting in query params (`page`, `search`)
- [x] Filter tasks with persisting in query params ( other then `page`, `search`) (~4d)

**Comment by nmanovic** [comment]
@zankevich , what is your time estimation for the mentioned tasks?

**Comment by zankevich** [comment]
> @zankevich , what is your time estimation for the mentioned tasks?

Estimations added. Have some questions about implementation. Depends on them estimations can change.

**Comment by nmanovic** [comment]
@zankevich , why "Login page: (blocked, est. ~1d)" is in blocked state? Do you miss something on our side?

**Comment by nmanovic** [comment]
@zankevich , let's add "best guess" for implementing new UI design for dashboard only. I know that it is not finished yet but let's break it on separate tasks and estimate each one. From our talk today it should take approximately 2 months.

**Comment by zankevich** [comment]
> @zankevich , why "Login page: (blocked, est. ~1d)" is in blocked state? Do you miss something on our side?

Already implemented. PR will be ready soon.

**Comment by zankevich** [comment]
> @zankevich , let's add "best guess" for implementing new UI design for dashboard only. I know that it is not finished yet but let's break it on separate tasks and estimate each one. From our talk today it should take approximately 2 months.

There is no clear designs but for now I saw some major changes (not just UI styles). So my raw estimations for now is about 1 month +.
