### ISSUE TITLE
Request for help in identifying objects with "hidden" property in the XML annotation files

### ISSUE THREAD

**Issue by gd1925** [opencv/cvat#4896]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi all, I am interested in exporting annotations/labels in the form of PASCAL VOC format and then structure the images with annotations in order to pass the images and labels for training. I am writing a script now to remove annotations with "occluded" and "outside" property flag (mentioned as "occluded" in the annotations files with different formats)

After looking into the cvat documentation, it seems like the "hidden" flag is for visualization purpose, i.e. maybe the bounding box is blocking something else, so the annotator wants to hide it. The hidden flag will not change any property of the annotation. Is it possible to remove the objects that have chosen as "hidden" in the frames ? Is there any property that the objects with "hidden" property has that can enable me to ignore those particular objects in the frames?

![image](https://user-images.githubusercontent.com/50822928/188081024-aa86ddfb-6b0d-4419-9c1d-a1f207e95634.png)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
> After looking into the cvat documentation, it seems like the "hidden" flag is for visualization purpose, i.e. maybe the bounding box is blocking something else, so the annotator wants to hide it. The hidden flag will not change any property of the annotation.

Exactly. ``Hidden`` flag on UI is only for best UX of annotators, when they have temporary hide an object. If you update a page, the shape becomes visible. 

> Is there any property that the objects with "hidden" property has that can enable me to ignore those particular objects in the frames?

From the piece of annotation you provided, I see that you are annotation a video (``frame_000001``, ...). In this case you need to use ``Tracks`` and their ``outside`` property. It shows that an object disappears from a frame.

If you are using ``Shapes`` to annotate your videos, you need to delete these shapes from corresponding frames in UI. 

Do you see any problems with this approach?
