### ISSUE TITLE
Show attributes returned from a detector

### ISSUE THREAD

**Issue by tadejsv** [opencv/cvat#4898]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Detector models return some attributes, e.g. `confidence` (like [here](https://github.com/opencv/cvat/blob/6410b86a4edb7fbc3335d624aaf8e13f0afd8f0c/serverless/openvino/omz/public/yolo-v3-tf/nuclio/model_handler.py#L154)), but this is not shown in CVAT UI.

### Expected Behaviour

Returned attributes should be shown.

### Current Behaviour
 
Attributes are not shown :(

### Steps to Reproduce (for bugs)

1. Go to [app.cvat.ai](https://app.cvat.ai).
2. Creat a new task, add a label (Car), and attribute `confidence` for it - like so 
![image](https://user-images.githubusercontent.com/11489772/188269482-6083af8a-616c-42db-bec3-315c7d220159.png)

3. Upload image with some cars
4. Use Yolov3 automatic detector to detect cars (which should set confidence, see this  [part of code](https://github.com/opencv/cvat/blob/6410b86a4edb7fbc3335d624aaf8e13f0afd8f0c/serverless/openvino/omz/public/yolo-v3-tf/nuclio/model_handler.py#L154))
5. Observe that the value of `confidence` is not set for any detection.

![image](https://user-images.githubusercontent.com/11489772/188269533-a6ba9487-a2de-44f3-a478-5c4330ea360f.png)

**Comment by tadejsv** [comment]
Actually, I see that in the code, `confidence` is returned as string. However, even if I set the `confidence` attribute as Text, the attribute remains empty.

**Comment by bsekachev** [comment]
Hello, please consider this PR #3917 and this one #4506.

They both are merged to develop (do not worry about the second one is ``closed``).

You need to configure serverless function .yml file and its model_handler.py

You can look at ``serverless/openvino/omz/intel/face-detection-0205/nuclio/function.yaml`` as an example.

It has ``spec`` description:
![image](https://user-images.githubusercontent.com/40690378/190335646-fa8b8ede-922f-4ae6-8a6a-3db02733121c.png)

And in the code you can see:
![image](https://user-images.githubusercontent.com/40690378/190335876-0f3f181b-32d5-4e54-a9a6-98241c26d2e6.png)

**Comment by tadejsv** [comment]
Will try it out, thanks!

**Comment by bsekachev** [comment]
Well, I will close the issue now. Do not hesitate to reopen if you still have questions.
