### ISSUE TITLE
serverless/deploy_cpu.sh is currently broken.

### ISSUE THREAD

**Issue by IuliuNovac** [opencv/cvat#4899]
### My actions before raising this issue
- [X ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

I am currenly takeing the latest dev branch and building with CVAT_VERSION=dev docker-compose up -d since using v2.1.0 has oudated dockers. However, then running serverless/deploy_cpu.sh the 

### Expected Behaviour
Exect instalation

### Current Behaviour
All fail.
### Possible Solution
Someone messed up serverless/common/openvino/python3 or it's oudated.

### Steps to Reproduce (for bugs)

Follow instruction from - https://opencv.github.io/cvat/docs/administration/basics/installation/
then 

```
CVAT_VERSION=dev  docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d

nuctl create project cvat

./serverless/deploy_cpu.sh

```

### Context
22.09.03 16:17:29.005 cessor.healthcheck.server (I) Listening {"listenAddress": ":8082"}
22.09.03 16:17:29.005            processor.http (D) Creating worker pool {"num": 2}
22.09.03 16:17:29.007 sor.http.w0.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-cc9ns6fsctgc73ao53l0.sock"}
22.09.03 16:17:29.007 sor.http.w0.python.logger (W) Python 3.6 runtime is deprecated and will soon not be supported. Please migrate your code and use Python 3.7 runtime (`python:3.7`) or higher
22.09.03 16:17:29.007 sor.http.w0.python.logger (D) Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
22.09.03 16:17:29.007 sor.http.w0.python.logger (D) Using Python handler {"handler": "main:handler"}

Error - exec: "/opt/nuclio/common/openvino/python3": stat /opt/nuclio/common/openvino/python3: no such file or directory
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239

Call stack:
Can't run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
Failed to run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:106
Failed to start runtime
    /nuclio/pkg/processor/worker/factory.go:100
Failed to create worker
    /nuclio/pkg/processor/worker/factory.go:119
Failed to create workers
    /nuclio/pkg/processor/worker/factory.go:129

22.09.03 16:17:29.008 sor.http.w0.python.logger (E) Can't find Python exe {"error": "exec: \"/opt/nuclio/common/openvino/python3\": stat /opt/nuclio/common/openvino/python3: no such file or directory"}
22.09.03 16:17:29.008 sor.http.w1.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-cc9ns6fsctgc73ao53kg.sock"}
22.09.03 16:17:29.008 sor.http.w1.python.logger (W) Python 3.6 runtime is deprecated and will soon not be supported. Please migrate your code and use Python 3.7 runtime (`python:3.7`) or higher
22.09.03 16:17:29.008 sor.http.w1.python.logger (D) Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
22.09.03 16:17:29.008 sor.http.w1.python.logger (D) Using Python handler {"handler": "main:handler"}
22.09.03 16:17:29.008 sor.http.w1.python.logger (E) Can't find Python exe {"error": "exec: \"/opt/nuclio/common/openvino/python3\": stat /opt/nuclio/common/openvino/python3: no such file or directory"}

### Your Environment
Client: Docker Engine - Community
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.11.0 (83626)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Linux 20.04

**Comment by IuliuNovac** [comment]
I am not sure which version is deployed on cvat.ai, but Ai tool is broke, at least HRNET isn't working

**Comment by IuliuNovac** [comment]
For me, on the cvat.ai HRnet, IOG, f-BRS are broken .

**Comment by yasakova-anastasia** [comment]
It's been fixed by https://github.com/opencv/cvat/pull/5039
