### ISSUE TITLE
Hrnet is broke, here is the fix

### ISSUE THREAD

**Issue by IuliuNovac** [opencv/cvat#4900]
The issue is that ubuntu 20.04 or software-properties-common comes with python 2.7.  However, you use python3 for installation and then have python execution in nuclio. The links are broken, and instead of running python 3, it executes with python 2.

I have solved the issues by removing python, followed by installation  and linking it as it's done in detron2/retinanet (the only one which works with GPU)

I am too lazy to make a commit, but here is the fix as it is, as I had to go to sleep two hours ago.

Replace this:
```

        - kind: RUN
          value: add-apt-repository ppa:deadsnakes/ppa
        - kind: RUN
          value: apt-get update && apt-get install -y --no-install-recommends build-essential git curl libglib2.0-0 software-properties-common python3 python3.6-dev python3-pip python3-tk
        - kind: RUN

```
With this:
```
        - kind: RUN
          value: add-apt-repository ppa:deadsnakes/ppa
        - kind: RUN
          value: apt remove python* -y
        - kind: RUN
          value: apt-get update && apt-get install -y --no-install-recommends build-essential git curl libglib2.0-0 software-properties-common python3 python3.6-dev python3-pip python3-tk
        - kind: RUN
          value: ln -s /usr/bin/pip3 /usr/local/bin/pip && ln -s /usr/bin/python3 /usr/bin/python
```

This worked for me, so you should check the bug yourself prior to taking my words for granted since it could be some issues specific to my machine.

**Comment by yasakova-anastasia** [comment]
It was fixed by #4944
