### ISSUE TITLE
How to use my auto-annotation inference api in my container service w/o nuclio?

### ISSUE THREAD

**Issue by deryann** [opencv/cvat#4905]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have some container which can provide service for inference like service interface of  nuclio building.
But for some reson I do not want to run nuclio on my platform.
How could I manually append this container and its port into cvat?

### Expected Behaviour
some possible way to add model w/o nuclio.

### Current Behaviour
I want to find a way to add some models for auto-annotation w/o nuclio.

### Possible Solution
Some doc or issue discuss I missed.

**Comment by bsekachev** [comment]
Hello,

Unfortunately CVAT does not support this kind of integrations for now.
It is probably possible somehow, but we do not have ready answers, need to invest much time to investigations.
