### ISSUE TITLE
Export annotated dataset feature not working as expected

### ISSUE THREAD

**Issue by sebkken** [opencv/cvat#4916]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I am having trouble in exporting the annotated dataset, when trying Segmentation Mask 1.1 format. I keep getting only 3 items in the zip - `labelmap.txt, JPEGImages, ImageSets.` I dont see `SegmentationClass` or `SegmentationObject` items in the zip at all, despite my having labeled a few objects in the images. This is a consistent behaviour. Anything I might be missing?

### Expected Behaviour
The exported zip should contain the 5 items -  `labelmap.txt, JPEGImages, ImageSets`, `SegmentationClass` and `SegmentationObject`

### Current Behaviour
I keep getting only 3 items in the zip - `labelmap.txt, JPEGImages, ImageSets.`

### Steps to Reproduce (for bugs)
1. Create a new labeling job by uploading a sequence of images.
1.  Draw polyline around the objects in the image. (Shape, not Track)
1. Save
1. Export Task dataset > Format : Segmentation Mask 1.1 (Include images or not) > enter zip name > OK 

### Context
I am not able to export the labeled dataset, and do not know where to look for logs for this process specifically. `docker logs` doesnt give any helpful logs unfortunately.

### Your Environment
- Git hash commit (`git log -1`): d7560bbd39fec68f944515c2591dda74f3764b90
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.17
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem: N/A
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
@sebkken 

> Draw polyline 

A polyline is infinitely thin. It will not be drawn on a segmentation mask. Use polygons instead.

**Comment by zhiltsov-max** [comment]
@sebkken, could you describe what is the expected result? Currently, we only export 2d annotations with non-zero area, i.e. boxes, polygons and ovals ([docs](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-voc/#segmentation-mask-export)).

**Comment by sebkken** [comment]
@bsekachev @zhiltsov-max Thanks for the information. We started using the polygons instead of polylines, and this issue has been resolved. Thanks so much for the prompt response.
