### ISSUE TITLE
Do batch Automatic Annotations with API

### ISSUE THREAD

**Issue by johnpapav** [opencv/cvat#4918]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour
Is there any way to use the API to do batch Automatic Annotations? I have tons of projects and selecting them one by one and clicking Automatic Annotation through the GUI is very time consuming. Could this be done in batch or any other way? 

### Possible Solution
Perhaps somehow through the API?

### Your Environment
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.17
- Are you using Docker Swarm or Kubernetes? N/A
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04.1

**Comment by bsekachev** [comment]
Hi,

You can run the serverless function for a task through REST API:
``POST: /lambda/functions/${functionID}``

Request body generally has:
```
task: <task_id_number>;
```

You can see specific body on Goggle Chrome ``Network`` tab, buy running a specific serverless method. It can be different for different kinds of serverless functions. 

If you are working inside an organization, add ``?org=<ORG_SLUG>`` to URL. 

You can get lambda requests using:
```GET: /lambda/requests```

You can get specific request status using:
```GET: /lambda/requests/<request_id>```

You can cancel lambda inference using:
```DELETE: /lambda/requests/<request_id>```

**Comment by johnpapav** [comment]
Thanks!
