### ISSUE TITLE
cvat.pth.foolwood.siammask build failed

### ISSUE THREAD

**Issue by looput** [opencv/cvat#4920]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am stucking in build cvat.pth.foolwood.siammask due to network issue, is it possible to upload the image to docker hub

**Comment by dschoerk** [comment]
did you look into this solution? https://github.com/opencv/cvat/issues/4912
