### ISSUE TITLE
Add new option under actions tab

### ISSUE THREAD

**Issue by himanshudw** [opencv/cvat#4933]
### My actions before raising this issue
- Read/searched doc on CVAT and README.md under cvat-ui section

Intend to add train button on the UI of CVAT under the Actions tab

### Expected Behaviour
The click on the train button should take the dataset along with the annotation to a new page.

### Current Behaviour
Unable to locate the procedure to make these changes 

### Context
![image](https://user-images.githubusercontent.com/61216926/189655672-45f56f9f-348d-4f5b-89c7-173b6344855f.png)
Trying to add a train button under the dropdown in the actions tab

In the earlier version it is reflected as below but not sure about the changes need to be done in this new version
![image](https://user-images.githubusercontent.com/61216926/189657387-2ee56c6b-3b84-42e1-9d71-6f907553aa47.png)

### Your Environment
- Docker version `docker version` :20.10.17
- Operating System and version :Linux
- CVAT Version :dev

**Comment by klakhov** [comment]
Hey! You can look on [actions-menu component](https://github.com/opencv/cvat/tree/develop/cvat-ui/src/components/actions-menu) and [actions-menu container](https://github.com/opencv/cvat/tree/develop/cvat-ui/src/containers/actions-menu)

**Comment by himanshudw** [comment]
Hey thanks for that @klakhov , could you please tell me the next action to this. After making the changes do I need to do npm version patch or npm start from the cvat-ui address ??

**Comment by klakhov** [comment]
@himanshudw That depends on how you are using CVAT. If you are using docker, you need to build images locally with `.dev.yml` config and then restart your containers. [Refer to docs](https://opencv.github.io/cvat/docs/administration/basics/installation/#how-to-pullbuildupdate-cvat-images)
```
docker-compose down
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
```

If you are using development environment, [refer to dev docs](https://opencv.github.io/cvat/docs/contributing/development-environment/#run-cvat), all changes in cvat-ui will be automatically detected and applied.

**Comment by himanshudw** [comment]
Thanks a lot for those, it worked this way.

**Comment by klakhov** [comment]
Recently Source & Target cloud storages(#4842) were implemented in CVAT. Documentation for that feature is WIP, but you can find link to demo in the #4842. 
You can export your dataset to attached cloud storage like that:
![image](https://user-images.githubusercontent.com/50956430/192532934-9ea291d6-30da-425a-8d9a-2609102f2708.png)

**Comment by himanshudw** [comment]
Few questions here 
1) How can I connect my azure container as cloud storage without the manifest file?
2) Manifest file needs to be created for every task that I am making, if yes how to do so
3) What are source and target cloud storage, is it different from connected file share that comes up when we create a new task?

**Comment by klakhov** [comment]
@Marishka17 could you please help with answering these questions?

**Comment by Marishka17** [comment]
@himanshudw, Hi 
> How can I connect my azure container as cloud storage without the manifest file

In the current implementation, it's impossible to attach cloud storage without a manifest file (but it's in our future plans). As a workaround, you can put the empty file to your bucket and specify it when attaching storage to CVAT.
Documentation for attaching Azure Blob Container can be found [here](https://opencv.github.io/cvat/docs/manual/basics/attach-cloud-storage/#using-azure-blob-container).

> Manifest file needs to be created for every task that I am making, if yes how to do so

The manifest file is used for another functionality. If you want to use data on your bucket, you can attach this bucket to CVAT. In this case, you should prepare a manifest file that will specify bucket content. If you have several datasets on your bucket and want to create annotation tasks with these data you can prepare one manifest or several for each dataset.
Please see the [documentation](https://opencv.github.io/cvat/docs/manual/advanced/dataset_manifest/#alternative-way-to-use-with-cvatserver) for preparing manifest file.

> What are source and target cloud storage, is it different from connected file share that comes up when we create a new task?

Source storage specifies the location from which annotations and backups will be uploaded to CVAT.
Target storage specifies the location to which annotations and backups will be downloaded from CVAT.
Yes it's different from a connected file share

**Comment by himanshudw** [comment]
Hi @mari

Thank you so much for that clarification. I have been able to add the cloud storage with a blank manifest file but then it is giving error as per the below image

![image](https://user-images.githubusercontent.com/61216926/192788743-0b7c0495-8a0e-480d-9838-609cd0952955.png)

The main intent for me is to upload the annotation for the task in TFrecord 1.0 format to the azure container so as per the demo in on of the above comment I could see it happening.

Now as you rightly mentioned that the dataset on the azure cloud could be used to create a task and for that we need the manifest file so while creating a task 
![image](https://user-images.githubusercontent.com/61216926/192789993-45c51b1a-941c-4840-a679-ef375b6d1181.png)

I request you to kindly clarify the paths for manifest file else a way out for me to upload the annotations directly to the cloud storage using the UI.

Thanks in advance
