### ISSUE TITLE
Better support of human pose/keypoints scenario

### ISSUE THREAD

**Issue by foreverYoungGitHub** [opencv/cvat#494]
Thanks for your great work!

I just start using this tool to annotate a tiny dataset for human pose/keypoints. This is kind of easy to use. 

However as long as I copy the keypoints from one frame to other frame, it is super hard for me to make sure which joints is corresponding to which points.

It would be good that it could visualize the order/name for the keypoint based on its order. For example, the first joint is visualized as 1 at the side of the point when I select the points. Or visualize all the order of the points when I select the annoatation.

It would be a great help for me to annotate the keypoint. Espically in the video.

Hopefully it could be a easy fix in the js end.

Best,

Yang

**Comment by nmanovic** [comment]
I agree that it may be useful. Alternative approach is to have one point per joint. Thus the point will have a separate label and you can visualize its name.

**Comment by altear** [comment]
This would be very useful for creating annotations sets to use with deeplabcut and deepposekit 

Also there seems to be a lack of shortcuts/cycling ability to go through keypoints efficiently (ex. in deeplabcut, after you label one keypoint it auto-selects the next label)

**Comment by bsekachev** [comment]
The feature has been implemented here https://github.com/cvat-ai/cvat/pull/1

It also was merged to current repository, you need to update CVAT from ``develop`` branch if you want to use it.
It is initial implementation and probably will be improved in the future, so, we are glad to get any feedbacks.

Thank you.

**Comment by adamsau** [comment]
@bsekachev just want to know does this branch support annotating points and export to COCO keypoint formats?

**Comment by bsekachev** [comment]
@adamsau 

It supports annotation points and dumping in CVAT format.
Dumping in COCO format is in progress #4821
