### ISSUE TITLE
[Feature Request] Remove dependency on external files when running the cvat multi-container application

### ISSUE THREAD

**Issue by ajagadi1** [opencv/cvat#4943]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Unless `cvat/apps/iam/rules` (available in https://github.com/opencv/cvat/tree/develop/cvat/apps/iam/rules) is present adjacent to the cvat docker-compose.yml available in https://github.com/opencv/cvat/blob/develop/docker-compose.yml, the cvat application doesn't work as expected.

### Expected Behaviour
The cvat docker compose file https://github.com/opencv/cvat/blob/develop/docker-compose.yml should be self-sufficient and should be able to run the application successfully (using `docker-compose up -d`) without depending on `cvat/apps/iam/rules`  present on the host machine.

### Current Behaviour
If the `cvat/apps/iam/rules` is not present on the host machine adjacent to the cvat docker-compose.yml file, then upon doing `docker-compose up -d`, the web app comes up and super user creation is successful, but login using super user fails with status code 500.

### Possible Solution
The cvat_opa service has the below (in https://github.com/opencv/cvat/blob/develop/docker-compose.yml) and we can see that it runs the rules in the command section:
```
volumes:
  - ./cvat/apps/iam/rules:/rules
ports:
  - '8181:8181'
command: run --server --addr :8181 --set=decision_logs.console=true /rules
```
Perhaps instead of mounting the `/cvat/apps/iam/rules` from host machine onto the cvat_opa container, having the rules already within the cvat_opa image by developing this docker image with its base as openpolicyagent/opa:0.34.2-rootless could solve this problem.

### Context
In order to run the cvat docker-compose application, there is a dependency on `cvat/apps/iam/rules` present on the host machine which isn't good. It would be great if the cvat application can be self-sufficient.

### Your Environment

- Git hash commit (`git log -1`): 3bd7c7e422d57986bd629da07214a3a3e666c68c
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- CVAT version: v2.1.0

**Comment by nmanovic** [comment]
@ajagadi1 , could you please help us to resolve the issue? I believe it should not be very difficult.
