### ISSUE TITLE
Failed to create nuclio project

### ISSUE THREAD

**Issue by Tpoc311** [opencv/cvat#4948]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi everybody!

I'm trying to use serverless service for automatic annotation. But i get an error when i try to create nuclio project.

### Current Behaviour

![2022-09-13_15-15-32](https://user-images.githubusercontent.com/38178648/190094442-b7083daa-5eb4-40e8-9220-7a631bbc472c.png)

### Possible Solution

I'm not sure, but it may be point in version of kubernetes or nuclio. In my case i work at our work cluster so it is not applicable here to change kubernetes version - [check here](https://github.com/nuclio/nuclio/issues/750.).
And I installed nuclio accordingly with CVAT documentation - the same version as mentioned [in this file](https://github.com/opencv/cvat/blob/develop/components/serverless/docker-compose.serverless.yml) on my machine.
 
### Steps to Reproduce (for bugs)

1. Get and start CVAT service.

```
git clone https://github.com/opencv/cvat
chmod -R 776 cvat/
cd cvat && docker-compose up -d
```

2. Getting serverless ready (accordingly with [docs](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/))

```
docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
wget https://github.com/nuclio/nuclio/releases/download/1.8.14/nuctl-1.8.14-linux-amd64
sudo chmod +x nuctl-1.8.14-linux-amd64
sudo ln -sf $(pwd)/nuctl-1.8.14-linux-amd64 /usr/local/bin/nuctl
```

3. Trying to create nuclio project:

```
nuctl create project cvat
```
This step gives an error.

### Context
I am trying to use models for auto annotation for data in CVAT.

### Your Environment
1. CentOS Linux release 8.5.2111
2. Docker Engine 20.10.12
3. Kubernetes Client 1.19.0
4. Kubernetes Server 1.21.1
5. Python 3.6.8 (just in case)

**Comment by azhavoro** [comment]
Hello, If the kubernetes config file (~/.kube/config) is present in your system `nuctl` will attempt to use your cluster instead of local installation
```shell
nuctl -h | grep platform
      --platform string     Platform identifier - "kube", "local", or "auto" (default "auto")
```

Try specifying the `--platform local` option for all nuctl commands

**Comment by Tpoc311** [comment]
Now it works fine and output is as following:
![2022-09-14_13-18-50](https://user-images.githubusercontent.com/38178648/190134634-8e8b0420-174d-4f89-be2b-76c191569be6.png)

Thanks to @azhavoro ! :)
