### ISSUE TITLE
New TF Annotation

### ISSUE THREAD

**Issue by KevinLe1997** [opencv/cvat#495]
Hi guys,

I was able to run the commands given to us in the documentation to set up the Tensorflow Object Detector. I'm not exactly sure how to test it out. I created a new task, with a simple label of 'car'. I clicked the "New TF Annotation" button and it tells me the process has started. After a while, it fails, giving me the error: Tensorflow annotation failed. Error: Work-horse process was terminated unexpectedly (waitpid returned 9).

Did I do something incorrectly? 

Thank you!

**Comment by nmanovic** [comment]
@KevinLe1997 , need logs. Which version of CVAT are you using?

**Comment by KevinLe1997** [comment]
Sorry about that @nmanovic , assuming it's the version that is stated on my docker-compose.yml file, it should be version 2.3

**Comment by nmanovic** [comment]
@KevinLe1997 ,

It is a version for your docker-compose file. Which git branch/tag do you use to build CVAT?

**Comment by KevinLe1997** [comment]
Develop

**Comment by KevinLe1997** [comment]
For some reason, the issue resolved itself. I'm gonna go ahead and close the issue. Thank you @nmanovic

**Comment by cyruszhang** [comment]
running into the same problem. 

OS: iOS Catalina
cvat version: 2.3
branch: develop

do I need to install tensorflow libs separately?

**Comment by nmanovic** [comment]
@cyruszhang , you don't. Please send logs with the problem otherwise we cannot investigate on our side.

**Comment by cyruszhang** [comment]
thanks Nikita. log goes like this:
[2019-12-02 23:49:14,166] ERROR cvat.server.task_7: exception was occured during tensorflow annotation request
Traceback (most recent call last):
  File "/home/django/cvat/apps/tf_annotation/views.py", line 289, in create
    raise Exception('No labels found for tf annotation')
Exception: No labels found for tf annotation

I checked my label setup, and it seems fine: 
![image](https://user-images.githubusercontent.com/2977989/70078694-02997a80-15b8-11ea-808b-402e05373611.png)
