### ISSUE TITLE
Failed to create a task

### ISSUE THREAD

**Issue by seasenzzr000** [opencv/cvat#4955]
An error was displayed while creating a task

could not create the task 
Error:Could not create the task on the server.
ValueError:No media data found.

**Comment by bsekachev** [comment]
Please, fill the issue template first.
Second you need to provide specific steps to reproduce the issue, including a list of files you are trying to use to create a task.

Usually such error occurs when you don't provide any image/video data during task creation.

**Comment by bsekachev** [comment]
I will close the issue, because there is not response from your side.
Do not hesitate to reopen if you still have the issue.
Thank you.
