### ISSUE TITLE
Could not get models from the server

### ISSUE THREAD

**Issue by qwerty54321qwe** [opencv/cvat#4957]
I am a user of the online version of CVAT, and this morning I Encountered an error.
The error displayed as follows:

<img width="288" alt="1663304027(1)" src="https://user-images.githubusercontent.com/56580613/190559775-4b6a24e0-6fb2-444a-bf72-2eb27ac548bb.png">

![1663304319(1)](https://user-images.githubusercontent.com/56580613/190560438-6baf1c38-b305-41c6-a709-ef035fe0e1ab.jpg)

I'll be very thankful if someone help me the fix error！

### Your Environment
- Operating System and version :  Windows

**Comment by bsekachev** [comment]
Hello, the team is looking into the issue. Thank you for the report.

**Comment by bsekachev** [comment]
@qwerty54321qwe 

Now it should work.

**Comment by qwerty54321qwe** [comment]
Thanks a lot!!



---Original---
From: "Boris ***@***.***&gt;
Date: Fri, Sep 16, 2022 14:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [opencv/cvat] Could not get models from the server (Issue #4957)




 
Closed #4957 as completed.
