### ISSUE TITLE
CLI create task error with sorting_method

### ISSUE THREAD

**Issue by vjpdss** [opencv/cvat#4962]
I am trying to upload tasks via command line interface using the following command:

```
(cvat) user@machine:~/cvat python cvat-cli/src/cvat_cli/__main__.py --auth some_user:some_password \
--server-host some_server create test_cli \
share //some_folder/some_file.mp4 --chunk_size 8 \
--completion_verification_period 5 --frame_step 360 \
--project_id 1 --lfs --overlap 0 --segment_size 100 \
--use_zip_chunks --use_cache
```

I have tried this with the script in the cvat repo and installing cvat-cli using pip:

```
(cvat) user@machine:~/cvat cvat-cli --auth some_user:some_password \
--server-host some_server create test_cli \
share //some_folder/some_file.mp4 --chunk_size 8 \
--completion_verification_period 5 --frame_step 360 \
--project_id 1 --lfs --overlap 0 --segment_size 100 \
--use_zip_chunks --use_cache
```
Get the same error using both cases.

### Expected Behaviour

 I would expect the task to be created successfully.

### Current Behaviour

I get the following output using both methods:

```
0.00B [00:00, ?B/s][2022-09-16 11:08:49] INFO: Created task ID: 29 NAME: test_cli
[2022-09-16 11:08:49] CRITICAL: Status Code: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Allow': 'GET, POST, HEAD, OPTIONS', 'Content-Length': '69', 'Content-Type': 'application/vnd.cvat+json', 'Date': 'Fri, 16 Sep 2022 09:08:49 GMT', 'Referrer-Policy': 'same-origin', 'Server': 'Apache', 'Vary': 'Accept,Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY'})
HTTP response body: {"sorting_method":["\"\"lexicographical\"\" is not a valid choice."]}
```

### Possible Solution

I have used tcpdump to capture traffic and used wireshark to see what's going on with the HTTP stream. Since the problem is in that it is not recognising the sorting method when using the CLI i have tried and captured traffic using the WUI and the CLI. The difference is merely that when using the CLI, the are extra quotation marks added to the string value of sorting_method:
![CVAT_HTTP_WUI](https://user-images.githubusercontent.com/53142394/190620500-06e44ddf-3ec5-4b45-a52d-412698c9204b.png)
![CVAT_HTTP_CLI](https://user-images.githubusercontent.com/53142394/190620517-0e331bb8-5c97-442f-985a-5a38bc936b1f.png)

I am not very familiar with HTTP protocols and how cvat server handles these requests, but I am assuming that removing the quotation marks from the sorting method would suffice.

Thanks in advance and please let me know if there's any extra information you need (this is my firts issue)

**Comment by zhiltsov-max** [comment]
Hi, thank you for reporting the problem. Could you please add more info about the server (version) or check if the problem can be reproduced on https://app.cvat.ai?

**Comment by zhiltsov-max** [comment]
Hi, thank you for reporting the problem. Yes, it looks like a bug. As a temporary workaround, please use the UI vesion.

**Comment by jenschurchill** [comment]
This breaks my automated pipeline; Please note that frame_filter "step=24" is also quoted in one and not the other.
