### ISSUE TITLE
Mounting connected file share issue 

### ISSUE THREAD

**Issue by himanshudw** [opencv/cvat#4965]
### My actions before raising this issue
https://github.com/opencv/cvat/issues/2263
Installation document

### Expected Behaviour
The task should be created using the mounted share should 

### Current Behaviour
![image](https://user-images.githubusercontent.com/61216926/190836956-7776cd98-f054-481c-bdd0-6b6c5c1aabc4.png)

### Possible Solution
The mounted share should be used to create the task

### Steps to Reproduce (for bugs)
I did sudo blobfuse ~/azure_share --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/mluserscpy/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other to get the data from my azure share

I have created a volume with name as cvat_share using below
docker volume create --name cvat_share --opt type=none --opt device=/home/mlusers/azure_share/Dataset --opt o=bind
thereafter I have update the docker-compose.override.yml as below
# docker-compose.override.yml
version: "3.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: ""
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    external: true

Then I did docker-compose and thereafter I could see the root share but it is not working to create the task

### Context
This is not allowing to create the task using the data we have on azure that we have.

### Your Environment
Docker version docker version :20.10.17
Operating System and version :Linux
CVAT Version :dev

**Comment by bsekachev** [comment]
Please, specify a version you are using.

**Comment by himanshudw** [comment]
@bsekachev - Using the dev version
