### ISSUE TITLE
No documentation for setting up a share

### ISSUE THREAD

**Issue by scottcher** [opencv/cvat#497]
I've seen quite a few questions regarding how to set up a share location for transferring files to CVAT without using the upload option.  I've looked all through the user guide and aside from a reference that the share option exists, there is no documentation for actually setting up a share.

New to CVAT, new to Docker, new to Django - could really use a step-by step for adding a share for transferring files from my Windows environment to my CVAT environment.

**Comment by nmanovic** [comment]
Hi @scottcher , you can find the information inside [installation guide](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path). If you can help us make the documentation better don't hesitate to submit a PR. For now I will close the issue.
