### ISSUE TITLE
Internal Server error when uploading file with API

### ISSUE THREAD

**Issue by johnpapav** [opencv/cvat#4970]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Expected Behaviour
I want to upload files to a task through the API but I get 500 error.
The curl I send:
<code>
{
curl -X 'POST' \
  'http://localhost:8080/api/tasks/16/data/' \

...

  "chunk_size": 2147483647,
  "size": 2147483647,
  "image_quality": 100,
  "start_frame": 2147483647,
  "stop_frame": 2147483647,
  "frame_filter": "step=1",
  "compressed_chunk_type": "video",
  "original_chunk_type": "video",
  "client_files": ["xx.jpg"],
  "server_files": [],
  "remote_files": [],
  "use_zip_chunks": false,
  "cloud_storage_id": 0,
  "use_cache": false,
  "copy_data": false,
  "storage_method": "cache",
  "storage": "local",
  "sorting_method": "lexicographical"
}
</code>
### Current Behaviour
It always returns Server Error (500) regardless if I use the client upload or the server upload 

### Your Environment
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.18
- Are you using Docker Swarm or Kubernetes? n/a
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04

**Comment by azhavoro** [comment]
Hi, could you attach container logs as well? `docker logs cvat_server > cvat_server.txt`

**Comment by johnpapav** [comment]
[https://github.com/johnpapav/cvat_logs/blob/main/cvat_server.txt](url)

**Comment by zhiltsov-max** [comment]
Please try to upgrade the server version and apply the migrations needed. 

For simple, non-docker deployments it can be done with:
`python manage.py makemigrations && python manage.py migrate`. 

If your server uses Docker, you need to run these commands inside the running container: 
`docker exec -it --entrypoint '/bin/bash' cvat_server -c 'python manage.py makemigrations && python manage.py migrate'`
