### ISSUE TITLE
CLI no longer working after update

### ISSUE THREAD

**Issue by johnpapav** [opencv/cvat#4971]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Expected Behaviour
After the latest source code update the cvat_cli can't find the locally hosted cvat server.

### Current Behaviour
It used to work just fine and now always returns

<code> cvat_sdk.core.exceptions.InvalidHostException: Failed to detect host schema automatically, please check the server url and try to specify schema explicitly </code>

the command I've been using is:
<code>
cvat-cli --auth user:pass --server-host localhost --server-port 8080 ls
</code>

The cvat server is up and running just fine, the api can see it and I have tried using different ports and host names to no avail.

### Your Environment
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.18
- Are you using Docker Swarm or Kubernetes? n/a
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04

**Comment by zhiltsov-max** [comment]
Hi, thanks for reporting the problem, I was able to reproduce it. As a quick fix, please add `http://` or `https://` to the `--server-host` argument as the error message suggests.
