### ISSUE TITLE
API returns 202 Accepted when an image is uploaded, but does not add it to the task

### ISSUE THREAD

**Issue by noxz-dev** [opencv/cvat#4972]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

Image is added to the Task and a job is created 

### Current Behaviour

Task is still uncompleted

### Steps to Reproduce (for bugs)

```js
import fs from "fs";
import fetch, { FormData } from "node-fetch";
const file = fs.readFileSync("./city-street.jpg");

const form = new FormData();
form.append("image_quality", 70);
form.append("use_zip_chunks", true);
form.append("use_cache", true);
form.append("sorting_method", "lexicographical");
form.append("client_files", [file]);

fetch("http://localhost:8080/api/tasks", {
  method: "POST",
  body: JSON.stringify({
    name: "my task 2",
    owner: 1,
    assignee: 1,
    overlap: 0,
    segment_size: 100,
    z_order: false,
    image_quality: 75,
    source_storage: { location: "local" },
    target_storage: { location: "local" },
    project_id: null,
    labels: [{ name: "car" }, { name: "person" }],
  }),
  headers: {
    Authorization: "Token ...",
    "Content-Type": "application/json",
  },
})
  .then(async (resp) => {
    const parsedData = await resp.json();
    console.log("task created", parsedData);

    const tid = parsedData.id;

    fetch(`http://localhost:8080/api/tasks/${tid}/data/`, {
      method: "POST",
      body: form,
      headers: {
        Authorization: "Token ...",
      },
    })
      .then(async (data) => {
        console.log(data);
        console.log(await data.json());
      })
      .catch((err) => {
        console.log(err);
      });
  })
  .catch((err) => {
    console.log(err);
  });
```

### Context

i tried to create a task via the REST api and attach an image, am i missing something ?

### Your Environment

- Git hash commit (`git log -1`): 9f89787f95504474b154974c7ec6087dd13149dd
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.12
- Are you using Docker Swarm or Kubernetes?: no
- Operating System and version (e.g. Linux, Windows, MacOS): linux (WSL)
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by klakhov** [comment]
Hello @noxz-dev, try to use `client_files[0]: file`, `client_files[1]: file` etc. as separated form fields instead of `client_files: [file]`. You can check [createTask](https://github.com/opencv/cvat/blob/develop/cvat-core/src/server-proxy.ts#L1062) function for better understanding (we are using TUS upload protocol).

Btw maybe it would be easier for you to use our [CLI](https://opencv.github.io/cvat/docs/api_sdk/cli/) or [SDK](https://opencv.github.io/cvat/docs/api_sdk/sdk/)?

**Comment by billynguyenlss** [comment]
Hello, I have tried using `client_files[0]: file`, `client_files[1]: file` but get error with status_code=500. When I used `client_files[0]: [file]`, I still get the status_code=200.

**Comment by klakhov** [comment]
Hey, what error do you get on the server?(check cvat container logs).
If everything goes fine with data upload you should get '202' status code. As you can see in [createTask](https://github.com/opencv/cvat/blob/develop/cvat-core/src/server-proxy.ts#L964) then we need to wait for task data processing. Here we are requesting status and if its finished, then task is ready to go.

**Comment by bsekachev** [comment]
I will close the issue, since there is not response from your side.
I can also suggest to create a task via ``cvat-core`` module (or at least look how it is implemented there).
