### ISSUE TITLE
Login CVAT return 500 err

### ISSUE THREAD

**Issue by starztp** [opencv/cvat#4973]
I installed CVAT from the installation guide: https://opencv.github.io/cvat/docs/administration/basics/installation/ 
My OS system is macOS 12.1
I installed the source and checkout the release branch release-2.2.0,then docker-compose up -d.
After I created the superuser,I visited localhost:8080 ,the project page showed.But when I input the correct password and try to sign in, the API returns 500 error code to me. Then I try to use an incorrect password to login , it returns Unable to log in with provided credentials.
 
### Expected Behaviour
When I use  the correct password to login,login success

### Current Behaviour
When I use  the correct password to login,login failed and return 500 code.

### Possible Solution
I found the cvat_server container logs when I was login.
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/25835562/191002538-bde0b476-fed7-49c8-a2a5-8d0d6947ea7d.png">

Then I test the connection between the cvat_server and cvat_opa.
docker exec -it cvat_server ping cvat_opa(I installed ping command on cvat_server before test)
<img width="511" alt="image" src="https://user-images.githubusercontent.com/25835562/191003227-f6eb81b9-7be1-4215-8edc-247dff3bf3b7.png">

### Steps to Reproduce (for bugs)

1. git clone https://github.com/opencv/cvat.git
2.git checkout release-2.2.0
3.docker-compose up -d
4.create the superuser
5.visit localhost:8080 and try to login with the correct password

### Your Environment

- Git hash commit (`git log -1`): 79ce99acc59e8558d9a7589c41050a258dd3c909
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):  MacOs 12.1

**Comment by starztp** [comment]
docker ps
when I use docker ps,I found the cvat_opa status is always up a few seconds ago.
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/25835562/191152265-5a71f9dd-c775-48a7-8c3e-00da8f43c468.png">


docker logs -f -t --tail 1000 cvat_opa
I found no logs for cvat_opa
<img width="487" alt="image" src="https://user-images.githubusercontent.com/25835562/191152772-a3b95224-335f-46d7-89f9-9e82664706a3.png">

**Comment by kirill-sizov** [comment]
@nmanovic Please tell me, have you ever had such problems on MacOS?

**Comment by nmanovic** [comment]
@starztp , could you please provide me exact steps which you use to start CVAT? I believe that OPA cannot find rules, because we don't copy them into the container. But if you clone the github repo and start docker-compose from the cloned cvat directory, it should not be an issue.

**Comment by starztp** [comment]
I start the cvat from the installation guide:https://opencv.github.io/cvat/docs/administration/basics/installation/,the guide told me to clone the source and start docker-compose from the cloned cvat directory,the exact steps was provided,could you please tell me which rules the OPA cannot found ?
![image](https://user-images.githubusercontent.com/25835562/191712910-c4af6306-1bbf-44b0-ae49-fa3c722e95ef.png)

![image](https://user-images.githubusercontent.com/25835562/191712406-e37079db-80e4-4940-a021-6576ffd63303.png)

**Comment by nmanovic** [comment]
@starztp , please try our latest release. We have changed the logic connected with OPA. Thus you should not the problem anymore: https://github.com/opencv/cvat/releases/tag/v2.3.0
