### ISSUE TITLE
Feature Request: Import tasks to project

### ISSUE THREAD

**Issue by LukeAI** [opencv/cvat#4979]
### My actions before raising this issue
- [X ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

I have many tasks, unassociated with a project, created on an older version of CVAT (from before projects) - I wish to merge these tasks into a single project (with a single labelling schema etc). I would like to request that the devs consider adding the feature of moving an existing task to a project.

**Comment by bsekachev** [comment]
Hi @LukeAI 

You can do this:
![image](https://user-images.githubusercontent.com/40690378/191429021-58530c5d-c7c7-4ce8-8453-20a2903e6e5f.png)
