### ISSUE TITLE
Adding a new Tensorflow Model

### ISSUE THREAD

**Issue by KevinLe1997** [opencv/cvat#498]
Hi all, 
On the Intel site, it says that other Tensorflow models can easily be implemented into CVAT aside from the default. However, in regards to issue #296 and #196, this feature seems to be unimplemented at the moment. I noticed that those issues are kind of old so I wanted to double-check. 
Thank you!

**Comment by nmanovic** [comment]
@KevinLe1997 , you are right. The only way to integrate a TF model is to hack code (or convert it to OpenVINO IR format). I will close the issue. Please ask your questions on our gitter channel. During a couple of weeks we got +20 issues and I don't think that it is right.
