### ISSUE TITLE
proposal Install locally with pip

### ISSUE THREAD

**Issue by monkeycc** [opencv/cvat#4991]
### proposal
Docker images are very troublesome

It is recommended to add
Install locally with pip
`pip install  cvat
`
```
https://github.com/heartexlabs/label-studio
https://github.com/PaddleCV-SIG/PaddleLabel
https://github.com/open-mmlab/labelbee-client
```
Now more and more tools appear
All can be directly installed by pip

**Comment by nmanovic** [comment]
@monkeycc , the main problem is that out-of-the-box CVAT provides features of commercial tools (analytics, permissions management, DB, etc). The functionality requires complex installation procedures and docker helps with that. I agree that it will be great to have a simplified version of CVAT that can be installed by pip only. For now, the only solution is to use the Free plan on [CVAT.ai](http://cvat.ai). Just register and use CVAT.

Let's keep the ticket open and see if we can find a solution.

**Comment by nmanovic** [comment]
I'm not sure that we are going to simplify installation in the nearest future. I will close the issue. In any case simplification is one of our primary priorities. But It doesn't make any sense to keep the issue for years.
