### ISSUE TITLE
I can't download my dataaset from your website.

### ISSUE THREAD

**Issue by shoutOutYangJie** [opencv/cvat#4992]
![image](https://user-images.githubusercontent.com/46734514/192190750-093afe85-c5e8-4265-ae58-ef0f97ef1987.png)
 the error happened when I click "Export job  dataset" and "ok" button.

**Comment by bsekachev** [comment]
Hi @shoutOutYangJie 

Can you try to open a task page and export the whole task?

**Comment by shoutOutYangJie** [comment]
> Hi @shoutOutYangJie
> 
> Can you try to open a task page and export the whole task?

Yes  I can
