### ISSUE TITLE
nuctl create project : stdout:\nUnable to find image 'gcr.io/iguazio/alpine:3.15

### ISSUE THREAD

**Issue by belkahorry** [opencv/cvat#4994]
### My actions before raising this issue
- [] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [] Searched [past issues](/issues)

### Expected Behaviour

Follwing the instruction 'Semi-automatic and Automatic Annotation' to install AI auto tools.
During step 'Create cvat project inside nuclio dashboard where you will deploy new serverless functions and deploy a couple of DL models',
command `nuctl create project cvat` should pass

### Current Behaviour

raise error:
`sudo nuctl create project cvat

22.09.26 18:17:33.395     nuctl.platform.docker (W) Failed to run container {"err": "stdout:\nUnable to find image 'gcr.io/iguazio/alpine:3.15' locally\ndocker: Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.\n\nstderr:\n", "errVerbose": "\nError - exit status 125\n    /nuclio/pkg/cmdrunner/shellrunner.go:96\n\nCall stack:\nstdout:\nUnable to find image 'gcr.io/iguazio/alpine:3.15' locally\ndocker: Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.\n\nstderr:\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:96\nstdout:\nUnable to find image 'gcr.io/iguazio/alpine:3.15' locally\ndocker: Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.\n\nstderr:\n", "stdout": "Unable to find image 'gcr.io/iguazio/alpine:3.15' locally\ndocker: Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.\n", "stderr": ""}

Error - exit status 125
    /nuclio/pkg/cmdrunner/shellrunner.go:96

Call stack:
stdout:
Unable to find image 'gcr.io/iguazio/alpine:3.15' locally
docker: Error response from daemon: Get "https://gcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

stderr:

    /nuclio/pkg/cmdrunner/shellrunner.go:96
Failed to run container with storage volume
    ...//nuclio/pkg/platform/local/client/store.go:430
Failed to run cat command
    ...//nuclio/pkg/platform/local/client/store.go:340
Failed to get projects
    ...//nuclio/pkg/platform/local/client/store.go:99
Failed getting projects
    /nuclio/pkg/platform/local/platform.go:504
`

### Possible Solution

I'm a newer to docker, error mentioned image 'gcr.io/iguazio/alpine:3.15', should i get it locally?

### Steps to Reproduce (for bugs)

1.`sudo docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d`
2.`wget https://github.com/nuclio/nuclio/releases/download/<version>/nuctl-<version>-linux-amd64`
3. ```
sudo chmod +x nuctl-<version>-linux-amd64
sudo ln -sf $(pwd)/nuctl-<version>-linux-amd64 /usr/local/bin/nuctl
```
4.`sudo nuctl create project cvat`

### Context
<!--- How has this issue affected you? What are you trying to accomplish?
Providing context helps us come up with a solution that is most useful in
the real world -->
Maybe it dosent matter to my annotation task,i want to finish the instruction of installing of components needed for semi-automatic and automatic annotation, i wish it could help to boost the speed of segmentation annotation

### Your Environment
<!--- Include as many relevant details about the environment you experienced
the bug in -->
- Git hash commit (`git log -1`):commit be5f9773d04727430aedb238e063ecee5118c2f6 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05):20.10.18
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:[Semi-automatic and Automatic Annotation](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Hi @belkahorry 

Unfortunately as our experience has shown ``nuclio`` behaves quite unstable and can be affected by different system/networks configurations.
I can suggest trying to pull the image manually with ``docker pull`` before building, to change network (sometimes just sharing wifi from your phone can help), or just try to perform the steps later. 

Finally, I believe you should redirect this problem to ``nuclio`` developers: https://github.com/nuclio/nuclio, because we are not ``nuclio`` experts and you are trying to perform CVAT independent things (like creating a nuclio project).

Thank you, do not hesitate to reopen the issue if you believe it is CVAT related issue.

**Comment by zhentai-SMU** [comment]
the same problem

**Comment by 315386775** [comment]
the same problem

**Comment by yuandanfei** [comment]
https://github.com/opencv/cvat/issues/5012
