### ISSUE TITLE
[Feature] Remove the save button from job screen.  (Automatic persistence)

### ISSUE THREAD

**Issue by DuaneNielsen** [opencv/cvat#4997]
Feature Request - Autosave

### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Expected Behaviour

On the job screen, remove the save button.  All actions on the job screen should be persistent.

User actions can already be undone, corrected or deleted.  The save button serves no purpose other than a potential loss of the users work in the event of a server disconnect, browser crash, or just plain forgetting to press the button.

### Current Behaviour

Currently the user is required to press save.  If they forget, or are unable to save, they can lose quite a lot of work

### Possible Solution

Fairly self explanatory.

### Context

Lost 1.5 hours of work from closing the browser window without pressing the save button.

### Your Environment
Latest version as of Sept 2022.  Running on docker.

**Comment by bsekachev** [comment]
Hello,

Please consider using "Auto save" feature:
![image](https://user-images.githubusercontent.com/40690378/192471723-eae545b5-2e75-4a3c-a703-b75c6855f2a2.png)

You can for example save the job each 1 minute or more.

**Comment by DuaneNielsen** [comment]
Sorry to hear your code base is based on 2000's type architecture!  I don't think I've seen a modern web based application with a save button for quite a few years now.

Anyway, best of luck with the project.  I'll take a look around and see what else is out there.

**Comment by nmanovic** [comment]
@DuaneNielsen , In many cases we don't want to save changes automatically. It should stay at least for now.
