### ISSUE TITLE
Wrong order of shapes in a track (keypoint annotations)

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#500]
My group is doing keypoint interpolation and we ran into a problem where half our tasks were failing to "Dump annotation" when the button on the cvat dashboard was used.

This was the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/engine/annotation.py", line 121, in dump_task_data
    annotation.dump(file_path, scheme, host, query_params)
  File "/home/django/cvat/apps/engine/annotation.py", line 1412, in dump
    track, 0, db_task.size):
  File "/home/django/cvat/apps/engine/annotation.py", line 1118, in get_interpolated_shapes
    assert shape["frame"] > curr_frame
AssertionError
```

That is an assert in `TrackManager.get_interpolated_shapes`. The assert is in a loop where shapes of a track are being iterated through.

**Comment by ilouzl** [comment]
I'm getting the same error when trying to load "cvat for video" annotations into a task.
The task contains several jobs (video splits), but I noticed that if I add a new task without splitting the video to jobs, annotation load is successful (of course using the same video and annotation files).
I'm on version https://github.com/openvinotoolkit/cvat/releases/tag/v1.2.0-alpha

**Comment by bsekachev** [comment]
@ilouzl 

It would be helpful if you provide a video and annotations to stable reproducing the issue. I understand that they may be private. Just  it would dramatically simplify issue reproducing and consequently fixing.

**Comment by ilouzl** [comment]
@bsekachev you're right.
Attached is a dummy video and annotations that raises the same error.
[Archive.zip](https://github.com/openvinotoolkit/cvat/files/5669401/Archive.zip)
