### ISSUE TITLE
Request for polygon merging.

### ISSUE THREAD

**Issue by yuanyuangoo** [opencv/cvat#5006]
Can we have a button to merge multiple polygons into one polygon?

**Comment by bsekachev** [comment]
Hi @yuanyuangoo 

Polygon can be only grouped within one frame. 
In exported annotations grouped objects have the same ``group_id`` identifier. Please, refer to documentation: https://opencv.github.io/cvat/docs/manual/advanced/shape-grouping/

Also there is a feature under active development #4543, like Paint & Brush tools. It uses binary masks instead of vector shapes and it does not have such restrictions like polygons. 

I hope it will help, I will close the issue.

**Comment by nmanovic** [comment]
@yuanyuangoo , could you please give us an idea what you mean? How do you want to merge them?

**Comment by bsekachev** [comment]
#774

**Comment by yuanyuangoo** [comment]
> 

@nmanovic Hi, like if I only want to merge two polygons that partly overlapped, it would delete two polygons and create a new polygon that would be the union of the two old polygons. Grouping just makes them very messy, and I cannot send them to the background or foreground together. 

It is useful when I label a big object, and I want to add more area to the labeled object. Which point is the starting point would not be an issue for me.

**Comment by breznak** [comment]
I am +1 for this issue, being able to merge objects in 1 frame into a common object would be helpful. Eg some toolits only allow instance-segmentation (differentiate between instances, eg apple1, apple2), and not semantic segmentation (you only differentiate the class/type of objects - apple/orange). So by merging objects manually in CVAT dataset we can implement "semantic segmentation" even using only instance-segmentation toolkits.

**Comment by zhiltsov-max** [comment]
@yuanyuangoo, @breznak, how do you think, would it be useful for annotators to be able to work with grouped objects like we can in vector image editors (CorelDraw, Adobe Illustrator, Inkscape) or other tools (like Google Presentations, Word, or PowerPoint)? I mean, to work with a group just like a single object (select by 1 click, move all elements to bg/fg, drag by mouse, resize etc.), while still being able to work with separate objects by a ctrl+click?

**Comment by yuanyuangoo** [comment]
Hi, this idea is helpful for semantic segmentation, which would work for me. But it would work for instance segmentation if I want to add a part to a labeled object when labeling a big thing.

**Comment by yuanyuangoo** [comment]
Hi, this idea is helpful for semantic segmentation, which would work for me. But it would work for instance segmentation if I want to add a part to a labelled object when labelling a big thing.
________________________________

**Comment by Fraccalo** [comment]
I'd also find this function incredibly useful (I used it extensively in with other tools, e.g. V7, and I think it's a great functionality). And having it in the polygon tool rather than in a brush-like tool would be great.

**Comment by nmanovic** [comment]
@Fraccalo , we have added a brush tool. Probably it will help a little bit with your use case: https://opencv.github.io/cvat/docs/manual/advanced/annotation-with-brush-tool/
