### ISSUE TITLE
Adjust some paint & brush tools icons

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#5008]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

![image](https://user-images.githubusercontent.com/40690378/192723065-c25dec10-f6df-43d3-bb5b-21e943b814bd.png)
I do not really like two icons I've highlighted, their style looks a bit bolder that for others.
I've taken them from the Internet, maybe it is a good idea to redraw them from scratch.

**Comment by rahulsrivastava1** [comment]
Hi, I want to work on this issue

**Comment by bsekachev** [comment]
Hello, @rahulsrivastava1 

Actually, this is a ticket for our designer.
That is not about development, I am not sure you should work on it. 
If you want to collaborate in the project, you can choose between multiple other issues :)
