### ISSUE TITLE
More complex Auto annotation handling?

### ISSUE THREAD

**Issue by benhoff** [opencv/cvat#501]
Some of the openvino models require a significant amount of post processing. Specifically the [text detection model](https://github.com/opencv/open_model_zoo/blob/master/intel_models/text-detection-0002/description/text-detection-0002.md) outputs a [1x2x192x320] matrix and a [1x16x192x320] matrix that need to be combined together to create the bounding boxes.

See [here](https://github.com/opencv/open_model_zoo/blob/2018/demos/python_demos/text_detection_demo.py#L238) for an example of the post processing calculations (`a` & `b` are the matrixes talked about).

Is there a good way to do this with the current autoannotation app? I think with the limited keywords the answer is not currently, but wanted to make sure I wasn't missing anything.

**Comment by nmanovic** [comment]
@benhoff , probably you are right. We restricted environment for running a python script to avoid security issues. It is just a surprise for me that an output layer so complex. What is your suggestion?

**Comment by benhoff** [comment]
Is there a reason the security model is like that? One option would be to make only administrators capable of uploading new models, or requiring administrator privileges to execute more privileged code.

There's more structural issues with the code, since the first output is automatically selected in the code base currently. See this [line of code](https://github.com/opencv/cvat/blob/e4435fc7913e993f1e127e70f74abcb72432ae7b/cvat/apps/auto_annotation/model_loader.py#L42) where the `self._output_blob_name` is used to select/return only a single result.

**Comment by nmanovic** [comment]
@benhoff , need to think about administrator privileges for such code and don't restrict the python environment. I hope it is a solution.

> There's more structural issues with the code, since the first output is automatically selected in the code base currently. See this line of code where the self._output_blob_name is used to select/return only a single result.

The feature is relatively new. Let's improve it together. If you send us a PR I will be happy to accept it. Otherwise definitely we will fix your findings in the future.

**Comment by nmanovic** [comment]
@benhoff , just clarification. Regular users should be able to upload a model but the model should be run in the restricted environment. For users with admin privileges we can use the python environment without restrictions.

**Comment by benhoff** [comment]
See: https://github.com/opencv/cvat/pull/514
