### ISSUE TITLE
Could not create the task Open the Browser Console to get details

### ISSUE THREAD

**Issue by hadi-ghnd** [opencv/cvat#5020]
### My actions before raising this issue

- Installed docker
- Installed CVAT
- ran `docker-compose up -d`
- Opened **localhost:8080** in chrome
- Created an account
- Created a project 
- Creating a task (this is where the error happens).

I have tried this in windows with the same video, so the problem is not from the data.

### Current Behaviour
It shows this message:

> Could not create the task
> Open the Browser Console to get details

The Chrome console shows:

> cvat-app.tsx:292 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/tasks/9/data/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).

### Possible Solution
Seems to be a problem with authentication.

### Your Environment
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.4
- Code example or link to GitHub repo or gist to reproduce problem:

Please let me know how to fix this.

Thank you.

**Comment by bsekachev** [comment]
@hadi-ghnd 

I can not reproduce it. 

Could you please be more specific, provide exact CVAT commit hash, fill the issue template, provide some logs from the CVAT container?

**Comment by hadi-ghnd** [comment]
Thank you @bsekachev.
Your suggestion [here](https://github.com/opencv/cvat/issues/4996#issuecomment-1267527650) fixed this issue.
