### ISSUE TITLE
Mount /tmp from host to images to improve efficiency and reduce container size

### ISSUE THREAD

**Issue by breznak** [opencv/cvat#5023]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hello, 

I would like to mount /tmp of the containers to the host machine's /tmp, if possible. 

### Expected Behaviour

`--volume /tmp:/tmp:rw`

### Current Behaviour
If I look correctly into the `docker-compose.yml` the host's /tmp is not mounted into the images, so the container's /tmp inflates the container size! 

### Possible Solution
- simply mount it
- I was thinking how to handle multi-platform (windows, osx; linux is OK). I'd suggest to introduce `CVAT_TEMP_DIR`, which would by default not be used (=current behavior), and we could set it to `CVAT_TEMP_DIR=/tmp` to do suggested behavior. 
- I can implement this in a PR if confirmed by the devs that this approach would be accepted. 

### Your Environment
- cvat master or stable release

**Comment by azhavoro** [comment]
I think in 99% cases /tmp and /var/lib/docker directories are physically on the same partition, so `size of tmp inside the container` + `size of the tmp host` = `size of the tmp that will be mounted into the container `. Also I see the following disadvantages in this approach:
   - tmp directory will not be cleared of container data after container restart
   - security: in most cases host and containers have user with uid 1000

**Comment by breznak** [comment]
> in 99% cases /tmp and /var/lib/docker directories are physically on the same partition, 

I would disagree on this one, a lot of systems mount /tmp as tmpfs (in RAM only) for performance reasons. Also this is not about size mounted to the container, but size on host that is persistent (my motivation is that my cloud instance of CVAT ran out of space and crashed everything, separate /tmp that is cleared on restart would help here). 

> tmp directory will not be cleared of container data after container restart 

I think it boils down to if we want to allow /tmp in containers to be mounted in RAM. Ideally the option CVAT_TMP with default =None would allow this approach, while keeping the default as is now for the reasons you highlight. Would that be good solution? 

> security: in most cases host have user with uid 1000 which created in cvat container as well 

good point! so the host's user 1000 would be able to interfere with the containers' user 1000 (django?) files. 
Fair point and it should be a warning in docs, again, for single-purpose machines on cloud-hosting this is not an issue.

**Comment by nmanovic** [comment]
@breznak , we are not going to add the feature in the nearest future. Feel free to contribute, if you think it is important for your use case. I will close the issue.
