### ISSUE TITLE
[feature] add PERSISTENT_MOUNTPOINT to prevent data loss

### ISSUE THREAD

**Issue by breznak** [opencv/cvat#5024]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I'd like to be able to specify `CVAT_PERSISTENT_DIR=/mnt/my/data` which would aggregate all data from CVAT that are persistent for the datasets (/home/django, /var/lib/postgres, etc). 

Goal is to have all the valuable data stored on host file-system outside the docker containers. 

### Expected Behaviour
After specifying CVAT_PERSISTENT_DIR, all data from annotation is stored (optionally) on the host filesystem. 
So I can eg. safely delete the containers. 

### Current Behaviour
Data is stored in containers (quite unexpected). 
Motivation, I have mistakenly pruned the stopped cvat containers (as my GCE instance failed on full disk space), and by removing I lost all the annotated data!! 

### Possible Solution
As proposed, a CVAT_PERSISTENT_DIR where all needed paths are mounted in subdirs. This should be quite easy to implement. 
I can make a PR when devs agree on this approach, and please let me know all of which paths need to be stored (eg. /home/django,..?)

### Steps to Reproduce (for bugs)
Annotate data (export was broken in that version), prone all cvat containers... and you've just lost your data. 

### Context
This was esp. problematic as project export was broken? It will make upgrades and backups way easier. 

### Your Environment
cvat master, and stable 2.2.0 release.

**Comment by azhavoro** [comment]
> Current Behaviour
> Data is stored in containers (quite unexpected).

https://github.com/opencv/cvat/blob/develop/docker-compose.yml#L194-L198
This is not true, all data is stored in volumes, if you lost all data, then you deleted these volumes explicetly.
Take a look at bind mount if you want to specify volume data location like this
https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path

**Comment by breznak** [comment]
> if you lost all data, then you deleted these volumes explicetly. 

yes, it is definitely my mistake, I did "cleaning in docker". I somehow expected that the valuable data is stored on host. 

> [use share-path] 

yes, this would be a solution! Can we make it a default? Eg if the CVAT_PERSISTENT_DIR is specified, all these "valuable" volumes are mounted under it. so the data remains on host (and can be easily backed-up). 

Please let me know if this would be a reasonable approach, if not then this issue can be closed. Thank you for your replies
