### ISSUE TITLE
Cannot import backup of project/task under different org (personal workspace) 

### ISSUE THREAD

**Issue by breznak** [opencv/cvat#5025]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I am able to create a backup of production project/task which is under an org (I am maintainer), and import it into my personal workspace to make experiments 

### Current Behaviour

Unable to import the backups, I am afraid to load backup of an existing task/project into the production workspace, as I don't know how it behaves. 

### Possible Solution
I'd expect a "backup" to be fully independent and be able to replicate it in the "personal workspace". 

### Steps to Reproduce (for bugs)

1. have project under org MyOrg
2. backup project / task
3. switch to your Personal Workspace
4. try loading the backups for investigation -> fails. 

### Context
in console I get

> Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/api/tasks/backup/:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
cvat-app.tsx:284 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://MY_IP:8080/api/tasks/backup/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a)
e @ cvat-app.tsx:284
:8080/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 (Forbidden)

### Your Environment

- Git hash commit (`git log -1`): `release-2.2.0`
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.12
- Are you using Docker Swarm or Kubernetes? no; `docker compose up -d ...`
- Operating System and version (e.g. Linux, Windows, MacOS): linux

**Comment by bsekachev** [comment]
@breznak 

I am not sure it is related with organizations. Try to logout/login. Will it help?

**Comment by bsekachev** [comment]
@breznak 

Please, let us know if you still experiencing the issue. 
We need your help to reproduce and fix it. 
For now I will close the issue because there are not response from your.
