### ISSUE TITLE
Exported Cityscape 1.0/Segmentation Mask annotations from cvat.ai online tool are completely white

### ISSUE THREAD

**Issue by ktbrady42** [opencv/cvat#5031]
### My actions before raising this issue
- Told to raise the issue after contacting support via email

### Expected Behaviour
My dataset has all pixels corresponding to the sidewalk labeled as 1, everything else should be 0, this is validated by the show bitmap option within the tool. When exporting the annotations I am expecting this same binary mask.

### Current Behaviour
Once exporting the tagged images using Cityscapes 1.0 or Segmentation mask I am only getting entirely white annotations.

### Possible Solution
I had previously been tagging my images through cvat.org and had no issues such as this.

### Steps to Reproduce (for bugs)
1. Exporting Task #9318 Created by ktbrady42 on September 21st, 2022

### Context
I am trying to get a Semantic Segmentation Network trained using these annotations.

### Your Environment
Windows 10, cvat.ai online tool

**Comment by nmanovic** [comment]
@ktbrady42 , thanks for the report. We are going to fix it in the nearest future.
