### ISSUE TITLE
Export job dataset doesn't work

### ISSUE THREAD

**Issue by chernov-a** [opencv/cvat#5032]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The export job dataset option must not require permissions from a project or task owner to make data export.
### Current Behaviour

There is a project https://app.cvat.ai/projects/1489. I'm the owner. When I try to dump annotation inside a job, it says that I don't have  permissions to do it (403 error). But when I export annotation from the project list or a task windows, everything works well.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
@Marishka17 
Was it fixed with the recent patch?

**Comment by sans-dev** [comment]
> @Marishka17 Was it fixed with the recent patch?

Don't think to. I stumbled accross the same issue and till today it persists.

**Comment by Marishka17** [comment]
@bsekachev, @sans-dev, Oh, sorry for the delay. No, this issue is related to OPA

**Comment by chaojieji** [comment]
I am encountering this problem as well.

**Comment by Marishka17** [comment]
Has been fixed in #5282
