### ISSUE TITLE
Tracker initialization error

### ISSUE THREAD

**Issue by monster519** [opencv/cvat#5033]
When I try to use the tracker SiamMask it shows 'tracker initialization error'. I don't understand where is the error. Can you help me?
![2022-10-04 15-10-46 的屏幕截图](https://user-images.githubusercontent.com/82307771/193757653-242cc5ea-2e9e-4f85-99e0-49fb0ffe9049.png)

**Comment by erenuito** [comment]
how did you solve this bro
