### ISSUE TITLE
File index.json in the project backup 

### ISSUE THREAD

**Issue by mabelc** [opencv/cvat#5034]
Hi,

I am new to cvat.
I have created a backup and I am trying understand what is the file index.json for. Inside it looks like:

{"0":36,"1":197,"2":358,"3":519,"4":680}

I only have 5 images in the task.

Thanks,
Mabel

**Comment by bsekachev** [comment]
@mabelc 

Internal "kitchen". It is offset (in characters) in ``manifest.jsonl`` that corresponds to a frame. 

@Marishka17 Am I correct?
