### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by timmermansjoy** [opencv/cvat#5036]
### My actions before raising this issue
- [ x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x ] Searched [past issues](/issues)
- [ x ] Contacted on discord

I have setup CVAT on our local server. Everything worked well until now, where I get on every action an generic console.log error or a 400 error. I have already checked my storage, but that seems to be fine. I have cleared up 50gb of docker volumes. afterwards it tracked 1 activity in kibana and afterwards it is badk to this behaviour

![Screenshot 2022-10-04 at 4 35 19 PM](https://user-images.githubusercontent.com/61321383/193848756-e24907e3-7a89-4857-97d8-2e9de09b866b.png)
![Screenshot 2022-10-04 at 4 41 05 PM](https://user-images.githubusercontent.com/61321383/193849664-f2c6da7f-0420-4516-bcec-610a6c79ba33.png)
![Screenshot 2022-10-04 at 4 41 21 PM](https://user-images.githubusercontent.com/61321383/193849622-c65d9987-1241-4afc-96a4-768b33ed6310.png)

### Expected Behaviour

To log all the activities and for there to be no error

### Current Behaviour

giving errors on every interaction, going into a job, out a job, in a task, ....

### Possible Solution

have a look at what causes the error

### Context

it is very distracting to click the console log errors because they dont go away automatically, it doesn't give a clear overview of who is working when. This was a deciding feature of using CVAT

### Your Environment

- Git hash commit (`git log -1`): used docker compose did do a git pull and a docker pull trying this. but now I dont know since everything is done inside the docker what git hash it is
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.17
- Are you using Docker Swarm or Kubernetes?: compose
- Operating System and version (e.g. Linux, Windows, MacOS): Linux (ubuntu 18)

**Comment by azhavoro** [comment]
Hi, at the moment I have no idea what is the reason, but internally CVAT never deletes the log folder...
Try creating this folder manually:
```shell
docker exec -it cvat_server bash
mkdir /home/django/data/tasks/94/logs
```

**Comment by timmermansjoy** [comment]
hi there. I looked in the `cvat_server` container and I can see that some folders are not in there. so indeed all of the numbers that are missing have that log issue. however I dont get any task logging in kibana for everything? also this does not seem like a viable solution to go in and create a folder for if it randomly is missing?

I can still anotate the videos that dont have this folder. but it does make me worried about the longevity of the storage and the stability of cvat

<img width="1146" alt="Screenshot 2022-10-04 at 8 39 40 PM" src="https://user-images.githubusercontent.com/61321383/193899201-a64b5b3c-03d4-438c-b805-5bcdb937f9ca.png">

**Comment by azhavoro** [comment]
In general, it is absolutely normal that some numbers are missing, the task may be deleted or not created due to a decoding error, for example, so in this case it will be skipped here.
Do I understand correctly that you can open task 94 (<cvat_host>/tasks/94) and annotate it, but you will get an error about the log folder and as I see in your screenshot the folder`94` is missing too

@Marishka17 Do you have any idea why this might happen?

**Comment by timmermansjoy** [comment]
yes. as you can see, 94 is still annotated. I get that if there is a decoding error that it should not be created. but then it is still created on other places so that I can still annotate it?  yet for other issues the time progress does not get tracked

![Screenshot 2022-10-04 at 9 46 27 PM](https://user-images.githubusercontent.com/61321383/193911648-c227c710-b0ae-46be-bf97-1f5b1a7938ea.png)

**Comment by Marishka17** [comment]
@timmermansjoy, Hi, as I can see from exception message you've attached a git repository to this task, haven't you?

**Comment by timmermansjoy** [comment]
Hi there. I see the error you are referring to looking back. but I have not done so, only thing I've done with git is git clone the cvat repo. afterwards I didn't do anything with it I dont know why it is trying to make these requests or how you could add a git repo or what it would gain? I assume backups or something? I cant seem to find anything in the documentation about this feature even?

**Comment by timmermansjoy** [comment]
no more information afterwards?

**Comment by bsekachev** [comment]
@timmermansjoy 

How have you created the task #94? From local files or maybe shared storage, cloud storage, ...?
Basically if you do not see the task ID in ``data/tasks`` you do not have the task in this CVAT instance.

What if in ``cvat_server`` container you do ``mkdir 94 94/logs -p``? Will you still get the error?

**Comment by bsekachev** [comment]
One more question: Do you see num 94 in ``data/data``? In ``data/jobs``?

**Comment by timmermansjoy** [comment]
> How have you created the task #94?

I have created them with a local file uploading it with the `create multi task feature`

> Basically if you do not see the task ID in data/tasks you do not have the task in this CVAT instance.

I do see the task in my instance tho. it is just that it gives errors? but all the annotation data stays stored and I can watch the video

![Screenshot 2022-10-11 at 9 05 22 AM](https://user-images.githubusercontent.com/61321383/195019079-e246e0f2-c302-426d-86e1-7b707558ef60.png)
![Screenshot 2022-10-11 at 9 10 22 AM](https://user-images.githubusercontent.com/61321383/195019993-965affa0-f097-4a0c-b2ec-ebdaeaac0b85.png)


> What if in cvat_server container you do mkdir 94 94/logs -p? Will you still get the error?

it fixes the ui and it doesn't give me the error that it does not exist. sometimes I do get the error it still can't send logs?

![Screenshot 2022-10-11 at 9 13 55 AM](https://user-images.githubusercontent.com/61321383/195020604-5669f9c9-79cb-4bcf-91af-52441843bf28.png)

> One more question: Do you see num 94 in data/data? In data/jobs?

yes these folders where there from the start

![Screenshot 2022-10-11 at 9 11 43 AM](https://user-images.githubusercontent.com/61321383/195020217-777e470c-8472-434f-b739-23e4d0a16b5a.png)

**Comment by timmermansjoy** [comment]
@bsekachev I did all the things manually, those errors saying the file does not does not occur anymore, but still sometimes the cloud not send logs to the server

**Comment by timmermansjoy** [comment]
I nailed down the issue. It has to do with a corrupt video file, however there goes something wrong in the error handeling in CVAT. I also tried this at CVAT.AI but get the same result. when uploading a corrupted .mp4 file. it says it can't create this task, but afterwards the task is still in the list and you have all these issues. So something is still letting the task be created even when saying there is a problem creating this task. 

as you can see in the image, in cvat.ai task 22095 will have these same issues

![Screenshot 2022-10-21 at 11 08 51 AM](https://user-images.githubusercontent.com/61321383/197159061-fb50e643-dbec-43c0-879b-43487db3160f.png)

**Comment by bsekachev** [comment]
@timmermansjoy 

This task does not exist on cvat.ai now.

**Comment by nmanovic** [comment]
@timmermansjoy , I will close the issue. Feel free to reopen if you still have it and provide more details.
