### ISSUE TITLE
Cannot upload annotations to jobs

### ISSUE THREAD

**Issue by W-A-James** [opencv/cvat#504]
Hi I am trying to automate annotation uploading for jobs in cvat using the requests library in Python. Using the api documentation, we construct the valid url with the path /api/v1/jobs/<job_id>/annotations and send a put request with what seems like valid JSON only to get a 400 status code with the following details:

**JSON file**
```json
{
    "version": 28,
    "tags": [],
    "shapes": [
        {
            "type": "rectangle",
            "occluded": false,
            "z_order": 1,
            "points": [
                313.5,
                240.8857421875,
                367.8000030517578,
                288.8000000000011
            ],
            "id": 104434,
            "frame": 0,
            "label_id": 1924,
            "group": 0,
            "attributes": []
        }
    ],
    "tracks": []
}
```

**Put request**
```python
url = 'https://cvat.<server_url>/api/v1/jobs/<job_id>/annotations'
requests.put(url, json=json_data, auth=self._auth)
```

**Server response**
```bash
Response status:400-"label_id `1924` is invalid"
```

From what I understand from the documentation, the JSON file is properly structured and has the correct data-types, so I am somewhat confused as to why this Response is being given. Any help would be much appreciated.

**Comment by bsekachev** [comment]
@W-A-James 
Hi, I suppose you do not have a label with id 1924 in your database. So, server doesn't know what label shape has.

**Comment by bsekachev** [comment]
@W-A-James 
You can see a list of labels with a get request: /api/v1/tasks/<task_id>. 
Task id can be found through job id with a get request: /api/v1/jobs/<job_id>.

**Comment by W-A-James** [comment]
> @W-A-James
> Hi, I suppose you do not have a label with id 1924 in your database. So, server doesn't know what label shape has.

Thank you so much, I found the problem. I had assumed that the task_id and job_id were the same which was the reason the server couldn't figure out the label.
