### ISSUE TITLE
Allow the user to see dataset import/export logs

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#5040]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

A window where the user can see dataset import/export logs. In Datumaro, there are places where some useful import/export info is logged, e.g. which classes are mapped to what colors for segmentation exports etc.

### Current Behaviour

Currently, it is only possible to see exception stack trace when an error is thrown, and only in the debug mode. But annotations can be imported/exported successfully, while there are some useful info is printed. There are also some warnings possible (this replicates with https://github.com/opencv/cvat/issues/1529).

**Comment by nmanovic** [comment]
@zhiltsov-max , I will close the issue. I'm not sure we will have time to invest into it in the nearest future.
