### ISSUE TITLE
An additional slash at the end of the hostname makes some operations unworkable

### ISSUE THREAD

**Issue by jcorrochanoj** [opencv/cvat#5046]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

An additional slash at the end of the hostname makes some operations unworkable.

### Current Behaviour

Using some operations from high-level API does not work when an additional slash at the end of the hostname is added. For example:
- download_backup
- export_dataset
- create_task_from_data

However, other operations like downloading independent images (download_frames) or getting information about projects or tasks work properly.

### Steps to Reproduce (for bugs)

Using the following code, having a slash at the end of the hostname, can be used to reproduce the error

```
from cvat_sdk import make_client, models
from cvat_sdk.core.proxies.tasks import ResourceType, Task

with make_client(host="http://localhost:8080/") as client:
    # Authorize using the basic auth
    client.login(('user', 'password'))

    # Models are used the same way as in the layer 1
    task_spec = {
        "name": "example task 2",
        "labels": [
            {
                "name": "car",
                "color": "#ff00ff",
                "attributes": [
                    {
                        "name": "a",
                        "mutable": True,
                        "input_type": "number",
                        "default_value": "5",
                        "values": ["4", "5", "6"],
                    }
                ],
            }
        ]
    }
    task = client.tasks.create_from_data(
        spec=task_spec,
        resource_type=ResourceType.LOCAL,
        resources=["image00200.png", "image01000.png"],
    )
```

### Context
This is a minor bug that led me to try many other things before I saw where the problem was. The solution should be simple and I believe it could avoid a lot of headaches.

### Your Environment
- Git hash commit: ba4175bf5b4467bf0fbf89a3fd645cceef7f7c23
- Docker version `docker version`: 19.03.13-ce
- Operating System and version: Linux (AWS EC2 Amazon Linux)

**Comment by bsekachev** [comment]
@zhiltsov-max  Do you have any ideas here?

**Comment by zhiltsov-max** [comment]
Hi, thanks for reporting the problem. Yes, looks like something to be fixed.
