### ISSUE TITLE
Keypoint Numbering Messed up for COCO Keypoint export

### ISSUE THREAD

**Issue by jitaxis** [opencv/cvat#5048]
### My actions before raising this issue
Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
Searched [past issues](https://github.com/opencv/cvat/issues?q=keypoint+is%3Aclosed)

When exporting keypoint annotations using the COCO keypoint annotation and then importing them back into CVAT, the keypoints are in the wrong order. I don't know if this is useful, but the annotation was done using the keypoint skeleton.

### Expected Behaviour
The annotations shouldn't change order when exported. It occurs on the export as I open them on another annotator to check. 
This does not occur when exporting in CVAT format.

### Current Behaviour
The key points are incorrect order. E.g Square is annotated as below.
```
1--2
|  |
4--3
```
When importing this back into CVAT the following may occur.
```
3--2
|  |
1--4
```

### Possible Solution
There doesn't seem to be a pattern in the changes I can see, but I assume this is happening in the conversion to COCO keypoint.

### Steps to Reproduce (for bugs)
1. Annotate images in CVAT using a keypoint skeleton 
2. Export annotations
3. Import annotations onto a copy of the dataset to visualise it.

### Context
I need this for a project, but this is also a bug in the performance.

### Your Environment
I am using the web browser version of CVAT on a linux ubunutu 20.04 OS, with Chrome as my browser.

**Comment by jitaxis** [comment]
> Hi, @jitaxis
> 
> If you are using app.cvat.ai, please share a task/job ID with us.

The task ID is: 
#15200
The Job ID is:
#15642
Let me know if there is anything else required.

**Comment by bsekachev** [comment]
@jitaxis 

Looks like I was able to reproduce it.
Is it something like this?

**From:**
![image](https://user-images.githubusercontent.com/40690378/194479945-c5070a49-1186-4520-b5ab-09de7e664de2.png)

**To:**
![image](https://user-images.githubusercontent.com/40690378/194479998-5fa7fbe1-7001-41d6-bdf3-03bc43c3c2e4.png)

**Comment by bsekachev** [comment]
@yasakova-anastasia Could you please look at the problem?

@jitaxis Thank you for the report.
You can use **CVAT for Images** format as a temporary workaround.

**Comment by jitaxis** [comment]
> @jitaxis
> 
> Looks like I was able to reproduce it. Is it something like this?
> 
> **From:** ![image](https://user-images.githubusercontent.com/40690378/194479945-c5070a49-1186-4520-b5ab-09de7e664de2.png)
> 
> **To:** ![image](https://user-images.githubusercontent.com/40690378/194479998-5fa7fbe1-7001-41d6-bdf3-03bc43c3c2e4.png)

Yes, that is exactly it.
I need to have my annotations in COCO format for other work, so I won't be able to use **CVAT for Images** as a workaround for that. Do you know of a conversion script that I could use or how long this issue may take to be fixed?

**Comment by SpecLad** [comment]
I was able to reproduce this on app.cvat.ai, but not on a development server (with the latest commit). It's possible this has already been fixed.

**Comment by bsekachev** [comment]
@SpecLad 

I am not sure about it. 
Try to restore a task from a backup on your local instance.

**Comment by jitaxis** [comment]
Is the fix able to be used in the docker image of cvat?

**Comment by bsekachev** [comment]
@jitaxis 

Just pull the changes from the repository and: 

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/40690378/196627160-b53fe184-29c5-452b-878c-bf6a36d1b693.png">

**Comment by bsekachev** [comment]
Probably ``--build`` argument is missed.

**Comment by jitaxis** [comment]
> @jitaxis
> 
> Just pull the changes from the repository and:
> 
> <img alt="image" width="1023" src="https://user-images.githubusercontent.com/40690378/196627160-b53fe184-29c5-452b-878c-bf6a36d1b693.png">

I'm still getting the same issue with the key points as before. I pulled the latest "develop" branch and ran the line you mentioned above.
My cvat information is below:
Server version: 2.3
Core version: 7.0.1
Canvas version: 2.15.4
UI version: 1.42.2

Is there something I am missing?

**Comment by bsekachev** [comment]
@SpecLad Could you please have a look?

**Comment by SpecLad** [comment]
@jitaxis Did you use the `--build` option to `docker-compose`? At the time you posted your comment, the latest UI version should've been higher than 1.42.2, so you might have used outdated Docker images.
