### ISSUE TITLE
fbrs: returned a non-zero code: 7

### ISSUE THREAD

**Issue by monster519** [opencv/cvat#5049]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

I am getting an error `returned a non-zero code: 7` when I try to execute the command as follows:
`nuctl deploy --project-name cvat --path serverless/pytorch/saic-vul/fbrs/nuclio --platform local`

Details are as follows：
`22.10.06 19:15:40.358                     nuctl (I) Deploying function {"name": ""}
22.10.06 19:15:40.358                     nuctl (I) Building {"builderKind": "docker", "versionInfo": "Label: 1.8.14, Git commit: cbb0774230996a3eb4621c1a2079e2317578005b, OS: linux, Arch: amd64, Go version: go1.17.8", "name": ""}
22.10.06 19:15:40.491                     nuctl (I) Staging files and preparing base images
22.10.06 19:15:40.491                     nuctl (W) Python 3.6 runtime is deprecated and will soon not be supported. Please migrate your code and use Python 3.7 runtime (`python:3.7`) or higher
22.10.06 19:15:40.491                     nuctl (I) Building processor image {"registryURL": "", "imageName": "cvat.pth.saic-vul.fbrs:latest"}
22.10.06 19:15:40.491     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.8.14-amd64"}
22.10.06 19:15:44.008     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/uhttpc:0.0.1-amd64"}
22.10.06 19:15:48.445            nuctl.platform (I) Building docker image {"image": "cvat.pth.saic-vul.fbrs:latest"}
22.10.06 19:17:58.180     nuctl.platform.docker (W) Docker command outputted to stderr - this may result in errors {"workingDir": "/tmp/nuclio-build-207289897/staging", "cmd": "docker build --network host --force-rm -t cvat.pth.saic-vul.fbrs:latest -f /tmp/nuclio-build-207289897/staging/Dockerfile.processor   --build-arg NUCLIO_LABEL=1.8.14 --build-arg NUCLIO_ARCH=amd64 --build-arg NUCLIO_BUILD_LOCAL_HANDLER_DIR=handler  .", "stderr": "The command '/bin/sh -c curl -c ./cookie -s -L \"https://drive.google.com/uc?export=download&id=${fileid}\"' returned a non-zero code: 7\n"}
22.10.06 19:17:58.183                     nuctl (W) Failed to create a function; setting the function status {"err": "Failed to build processor image", "errVerbose": "\nError - exit status 7\n    /nuclio/pkg/cmdrunner/shellrunner.go:96\n\nCall stack:\nstdout:\nSending build context to Docker daemon  50.08MB\r\r\nStep 1/22 : FROM python:3.6.11\n ---> 6693bf717fb6\nStep 2/22 : ARG NUCLIO_LABEL\n ---> Using cache\n ---> d065cd43b45c\nStep 3/22 : ARG NUCLIO_ARCH\n ---> Using cache\n ---> 301b1b637d41\nStep 4/22 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR\n ---> Using cache\n ---> 005122017f71\nStep 5/22 : WORKDIR /opt/nuclio\n ---> Using cache\n ---> e1c18b7e7432\nStep 6/22 : RUN git clone https://github.com/saic-vul/fbrs_interactive_segmentation.git fbrs\n ---> Using cache\n ---> c9381f7a0dcb\nStep 7/22 : WORKDIR /opt/nuclio/fbrs\n ---> Using cache\n ---> 4c701eac3039\nStep 8/22 : ENV fileid=1Z9dQtpWVTobEdmUBntpUU0pJl-pEXUwR\n ---> Using cache\n ---> 9109854e14fc\nStep 9/22 : ENV filename=resnet101_dh256_sbd.pth\n ---> Using cache\n ---> 02da3a9a64c5\nStep 10/22 : RUN curl -c ./cookie -s -L \"https://drive.google.com/uc?export=download&id=${fileid}\"\n ---> Running in 869551aa4b19\nRemoving intermediate container 869551aa4b19\n\nstderr:\nThe command '/bin/sh -c curl -c ./cookie -s -L \"https://drive.google.com/uc?export=download&id=${fileid}\"' returned a non-zero code: 7\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:96\nFailed to build\n    /nuclio/pkg/dockerclient/shell.go:117\nFailed to build docker image\n    .../pkg/containerimagebuilderpusher/docker.go:54\nFailed to build processor image\n    /nuclio/pkg/processor/build/builder.go:263\nFailed to build processor image"}

Error - exit status 7
    /nuclio/pkg/cmdrunner/shellrunner.go:96

Call stack:
stdout:
Sending build context to Docker daemon  50.08MB
Step 1/22 : FROM python:3.6.11
 ---> 6693bf717fb6
Step 2/22 : ARG NUCLIO_LABEL
 ---> Using cache
 ---> d065cd43b45c
Step 3/22 : ARG NUCLIO_ARCH
 ---> Using cache
 ---> 301b1b637d41
Step 4/22 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR
 ---> Using cache
 ---> 005122017f71
Step 5/22 : WORKDIR /opt/nuclio
 ---> Using cache
 ---> e1c18b7e7432
Step 6/22 : RUN git clone https://github.com/saic-vul/fbrs_interactive_segmentation.git fbrs
 ---> Using cache
 ---> c9381f7a0dcb
Step 7/22 : WORKDIR /opt/nuclio/fbrs
 ---> Using cache
 ---> 4c701eac3039
Step 8/22 : ENV fileid=1Z9dQtpWVTobEdmUBntpUU0pJl-pEXUwR
 ---> Using cache
 ---> 9109854e14fc
Step 9/22 : ENV filename=resnet101_dh256_sbd.pth
 ---> Using cache
 ---> 02da3a9a64c5
Step 10/22 : RUN curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}"
 ---> Running in 869551aa4b19
Removing intermediate container 869551aa4b19

stderr:
The command '/bin/sh -c curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}"' returned a non-zero code: 7

    /nuclio/pkg/cmdrunner/shellrunner.go:96
Failed to build
    /nuclio/pkg/dockerclient/shell.go:117
Failed to build docker image
    .../pkg/containerimagebuilderpusher/docker.go:54
Failed to build processor image
    /nuclio/pkg/processor/build/builder.go:263
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:197`
![2022-10-06 19-24-10 的屏幕截图](https://user-images.githubusercontent.com/82307771/194300791-ab5e4b65-c6b9-491e-ab77-86169b6e7ad3.png)
![2022-10-06 19-24-21 的屏幕截图](https://user-images.githubusercontent.com/82307771/194300833-991a7ec4-279d-47c0-aecb-86339272f2db.png)

I don't know how to solve it, please help me

**Comment by bsekachev** [comment]
@monster519 

Please, fill out the issue template including git hash of the commit you are working on.

**Comment by monster519** [comment]
> @monster519
> 
> Please, fill out the issue template including git hash of the commit you are working on.

Sorry. How can I get the git hash?

**Comment by bsekachev** [comment]
@monster519 

>  How can I get the git hash?

``git log -1``

**Comment by monster519** [comment]
- Git hash commit(`git log -1`):
![2022-10-07 16-33-29 的屏幕截图](https://user-images.githubusercontent.com/82307771/194510013-13c4b3ca-7095-4aa3-bba7-b7a3b22d2659.png)
- Operating System and version (e.g. Linux, Windows, MacOS): linux
- Docker Version:
`Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:34 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
 Version:          20.10.18
 API version:      1.41 (minimum version 1.12)
 Go version:       go1.18.6
 Git commit:       e42327a
 Built:            Thu Sep  8 23:09:28 2022
 OS/Arch:          linux/amd64
 Experimental:     false
 containerd:
 Version:          1.6.8
 GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
 Version:          1.1.4
 GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
 Version:          0.19.0
 GitCommit:        de40ad0
`

**Comment by monster519** [comment]
latest situation：
When I try `nuctl deploy --project-name cvat --path serverless/pytorch/saic-vul/fbrs/nuclio --volume `pwd`/serverless/common:/opt/nuclio/common --platform local` it shows as follows:
`22.10.07 16:44:27.239                     nuctl (I) Deploying function {"name": ""}
22.10.07 16:44:27.239                     nuctl (I) Building {"builderKind": "docker", "versionInfo": "Label: 1.8.14, Git commit: cbb0774230996a3eb4621c1a2079e2317578005b, OS: linux, Arch: amd64, Go version: go1.17.8", "name": ""}
22.10.07 16:44:27.350                     nuctl (I) Staging files and preparing base images
22.10.07 16:44:27.350                     nuctl (W) Python 3.6 runtime is deprecated and will soon not be supported. Please migrate your code and use Python 3.7 runtime (`python:3.7`) or higher
22.10.07 16:44:27.351                     nuctl (I) Building processor image {"registryURL": "", "imageName": "cvat.pth.saic-vul.fbrs:latest"}
22.10.07 16:44:27.351     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.8.14-amd64"}
22.10.07 16:44:30.627     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/uhttpc:0.0.1-amd64"}
22.10.07 16:44:35.095            nuctl.platform (I) Building docker image {"image": "cvat.pth.saic-vul.fbrs:latest"}
22.10.07 16:46:45.048     nuctl.platform.docker (W) Docker command outputted to stderr - this may result in errors {"workingDir": "/tmp/nuclio-build-1913219471/staging", "cmd": "docker build --network host --force-rm -t cvat.pth.saic-vul.fbrs:latest -f /tmp/nuclio-build-1913219471/staging/Dockerfile.processor   --build-arg NUCLIO_LABEL=1.8.14 --build-arg NUCLIO_ARCH=amd64 --build-arg NUCLIO_BUILD_LOCAL_HANDLER_DIR=handler  .", "stderr": "The command '/bin/sh -c curl -L \"https://drive.google.com/uc?export=download&confirm=t&id=${fileid}\" -o ${filename}' returned a non-zero code: 7\n"}
22.10.07 16:46:45.054                     nuctl (W) Failed to create a function; setting the function status {"err": "Failed to build processor image", "errVerbose": "\nError - exit status 7\n    /nuclio/pkg/cmdrunner/shellrunner.go:96\n\nCall stack:\nstdout:\nSending build context to Docker daemon  50.08MB\r\r\nStep`
`1/21 : FROM python:3.6.11\n ---> 6693bf717fb6\nStep 2/21 : ARG NUCLIO_LABEL\n ---> Using cache\n ---> dad68b1aa670\nStep 3/21 : ARG NUCLIO_ARCH\n ---> Using cache\n ---> f83dffc9f4f4\nStep 4/21 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR\n ---> Using cache\n ---> 60ce4e9821dd\nStep 5/21 : WORKDIR /opt/nuclio\n ---> Using cache\n ---> 781c22505b9b\nStep 6/21 : RUN git clone https://github.com/saic-vul/fbrs_interactive_segmentation.git fbrs\n ---> Using cache\n ---> a87eca56fc1a\nStep 7/21 : WORKDIR /opt/nuclio/fbrs\n ---> Using cache\n ---> 5816d6778c5b\nStep 8/21 : ENV fileid=1Z9dQtpWVTobEdmUBntpUU0pJl-pEXUwR\n ---> Using cache\n ---> 77e8479ba87d\nStep 9/21 : ENV filename=resnet101_dh256_sbd.pth\n ---> Using cache\n ---> 2ad0dac89d8c\nStep 10/21 : RUN curl -L \"https://drive.google.com/uc?export=download&confirm=t&id=${fileid}\" -o ${filename}\n ---> Running in 2cfa66bf98d5\n\u001b[91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                    \u001b[0m\u001b[91m             Dload  Upload   Total   Spent    Left  Speed\n\u001b[0m\u001b[91m\r  0     0    0\u001b[0m\u001b[91m     0    0   \u001b[0m\u001b[91m  0      0 \u001b[0m\u001b[91m     0 --:\u001b[0m\u001b[91m--:-- --:--:-- \u001b[0m\u001b[91m--:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--   \u001b[0m\u001b[91m  0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:-- \u001b[0m\u001b[91m    0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--    \u001b[0m\u001b[91m 0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--    \u001b[0m\u001b[91m 0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:25 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:27 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:28 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:32 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:33 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:34 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:35 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:36 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:37 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:38 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:39 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:40 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:41 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:42 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:43 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:44 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:45 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:46 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:47 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:48 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:49 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:50 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:51 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:52 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:53 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:54 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:55 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:56 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:57 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:58 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:01 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:02 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:03 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:04 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:05 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:06 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:07 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:08 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:09 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:10 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:11 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:12 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:13 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:17 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:18 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:19 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:20 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:21 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:22 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:23 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:24 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:25 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:26 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:27 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:28 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:29 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 \u001b[0m\u001b[91m--:--:--  0:01:30 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:31 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:32 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:33 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:34 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:35 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:36 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:37 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:38 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:39 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:40 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:41 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:42 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:43 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:44 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:45 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:46 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:47 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:48 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:49 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:50 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:51 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:52 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:53 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:54 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:55 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:56 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:57 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:58 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:01:59 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:01 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:02 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:03 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:04 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:05 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:08 --:--:--     0\u001b[0m\u001b[91m\r  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0\u001b[0m\u001b[91mcurl: (7) Failed to connect to drive.google.com port 443: Connection ti\u001b[0m\u001b[91mmed out\n\u001b[0mRemoving intermediate container 2cfa66bf98d5\n\nstderr:\nThe command '/bin/sh -c curl -L \"https://drive.google.com/uc?export=download&confirm=t&id=${fileid}\" -o ${filename}' returned a non-zero code: 7\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:96\nFailed to build\n    /nuclio/pkg/dockerclient/shell.go:117\nFailed to build docker image\n    .../pkg/containerimagebuilderpusher/docker.go:54\nFailed to build processor image\n    /nuclio/pkg/processor/build/builder.go:263\nFailed to build processor image"}`
`Error - exit status 7
    /nuclio/pkg/cmdrunner/shellrunner.go:96

Call stack:
stdout:
Sending build context to Docker daemon  50.08MB
Step 1/21 : FROM python:3.6.11
 ---> 6693bf717fb6
Step 2/21 : ARG NUCLIO_LABEL
 ---> Using cache
 ---> dad68b1aa670
Step 3/21 : ARG NUCLIO_ARCH
 ---> Using cache
 ---> f83dffc9f4f4
Step 4/21 : ARG NUCLIO_BUILD_LOCAL_HANDLER_DIR
 ---> Using cache
 ---> 60ce4e9821dd
Step 5/21 : WORKDIR /opt/nuclio
 ---> Using cache
 ---> 781c22505b9b
Step 6/21 : RUN git clone https://github.com/saic-vul/fbrs_interactive_segmentation.git fbrs
 ---> Using cache
 ---> a87eca56fc1a
Step 7/21 : WORKDIR /opt/nuclio/fbrs
 ---> Using cache
 ---> 5816d6778c5b
Step 8/21 : ENV fileid=1Z9dQtpWVTobEdmUBntpUU0pJl-pEXUwR
 ---> Using cache
 ---> 77e8479ba87d
Step 9/21 : ENV filename=resnet101_dh256_sbd.pth
 ---> Using cache
 ---> 2ad0dac89d8c
Step 10/21 : RUN curl -L "https://drive.google.com/uc?export=download&confirm=t&id=${fileid}" -o ${filename}
 ---> Running in 2cfa66bf98d5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0curl: (7) Failed to connect to drive.google.com port 443: Connection timed out
Removing intermediate container 2cfa66bf98d5

stderr:
The command '/bin/sh -c curl -L "https://drive.google.com/uc?export=download&confirm=t&id=${fileid}" -o ${filename}' returned a non-zero code: 7

    /nuclio/pkg/cmdrunner/shellrunner.go:96
Failed to build
    /nuclio/pkg/dockerclient/shell.go:117
Failed to build docker image
    .../pkg/containerimagebuilderpusher/docker.go:54
Failed to build processor image
    /nuclio/pkg/processor/build/builder.go:263
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:197`

**Comment by monster519** [comment]
Hello, I did this operation under the proxy . How can I solve this problem under the proxy? (If you do not use a proxy, drive.google.com cannot connect even on the chrome. Using a proxy can access drive.google.com on the chrome.)

**Comment by bsekachev** [comment]
@monster519 

Please, google something like: "How to setup proxy settings for docker". It is about Docker, not about CVAT.

**Comment by monster519** [comment]
Thank you, I will close this issue.
