### ISSUE TITLE
Could not get models from the server

### ISSUE THREAD

**Issue by monster519** [opencv/cvat#5050]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When I open `http://localhost:8080`, it shows `Could not get models from the server Open the Browser Console to get details`.
![2022-10-06 21-57-33 的屏幕截图](https://user-images.githubusercontent.com/82307771/194333049-4e11ca9b-d669-4671-88cf-29fbe6c4e5b8.png)
I can't access `http://localhost:8070/` and the nuclio dashboard.

When I try `nuctl create project cvat`, it shows 
`22.10.06 21:55:37.705                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}`

When I try `nuctl get function`, it shows
NAMESPACE |      NAME      | PROJECT | STATE | REPLICAS | NODE PORT  
  nuclio    | openvino-dextr | cvat    | ready | 1/1      |     49153 

I reinstalled docker, CVAT and nuclio but still the same. Can you help me?

**Comment by nfrik** [comment]
I still have this problem in 2.2. Any clues on how to resolve this?
