### ISSUE TITLE
In web(cvat.ai), unable to auto annotate with models, 403 error

### ISSUE THREAD

**Issue by hwk06023** [opencv/cvat#5053]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I try to Automatic annotations in [cvat.ai](cvat.ai). But it doesn't work.
Organization : personal worksapce

### Current Behaviour

```
Error: Request failed with status code 403. {"detail":"You do not have permission to perform this action."}.
```

### Steps to Reproduce (for bugs)

1. Upload Data to my task (CVAT for Video)
1. Action -> Automatic Annotation
1. Select Model (ex. Mask RCNN, YOLO ..) 
1. Annotate

![Screenshot from 2022-10-09 17-06-14](https://user-images.githubusercontent.com/30601991/194745349-6cbfbda0-efc8-4d97-91d4-731b496b5a7f.png)

### Your Environment
in Chrome

**Comment by nmanovic** [comment]
It is a paid feature. You can run automatic annotation on a frame inside the data annotation view. We are working to adjust limitations. Soon we will clarify our Pro plan. We see that it is opaque for our community.

**Comment by hwk06023** [comment]
Thank you for your guidance.
