### ISSUE TITLE
cvat istallation eroor

### ISSUE THREAD

**Issue by Fawad7860** [opencv/cvat#5055]
i faced to an error while runing docker compose up _d i dont know what to do 
![image](https://user-images.githubusercontent.com/113134270/194472323-c63091c2-c6c3-4a06-8c01-a54b8ed8356c.png)

**Comment by zhiltsov-max** [comment]
Hi! It seems, you failed to connect to the official Docker registry during the installation process. This can happen for multiple reasons. For example, if you're behind a corporate proxy, you'll need to configure your proxy server settings.
