### ISSUE TITLE
cvat-cli `--sorting-method predefined` results in seemingly random order of images

### ISSUE THREAD

**Issue by nikste** [opencv/cvat#5061]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

using the current master (v.2.2.0) and cvat-cli for create task and sorting method predefined will result in a seemingly random order of images in the task.
Using version 2.1.0 works as expected but only sometimes.
(creating many tasks with a script)

**Comment by zhiltsov-max** [comment]
Hi, thanks for reporting the problem! I was able to reproduce.

**Comment by nikste** [comment]
so using master `v.2.1.0` `utils/cli/cli.py` (and the cvat server side `v2.2.0`) it seems to upload "less" random: either in the order specified or inverse. On first glance this looks like something went wrong in the cli and not the server.

For people with the same problem: After creating the task with `cli.py .. create ..` I could identify the order by checking if the first picture was correct using `cli.py ... dump ..` and checking the image names in the json. If its still the wrong order use `cli.py .. create ..` with the inverse order than the call before and again check the order.

**Comment by zhiltsov-max** [comment]
No, the reason for this problem is different, and behavior depends on the OS implementation. It can be reproduced both in UI and SDK, all the versions since the TUS protocol support introduction are affected. The file order is random, though it can be partially sorted. One way to avoid is to send all files in a single `POST tasks/{id}/data` request.

**Comment by nikste** [comment]
Ok I'm not an expert in this :) My observation was that the cli in the previous version would either have the correct sorting or inverse sorting, but i guess it will send everything in one post request. With the newest cli version it looks completely random to me. But i didn't look into the code and how its handled at all.

**Comment by nikste** [comment]
thanks for looking into this though!

**Comment by zhiltsov-max** [comment]
It's still possible to create task with older versions of CLI (the ones that were placed in `utils/cli/`), they can be obtained only from this repository at specific commits (prior to v2.2.0, e.g. [here](https://github.com/opencv/cvat/tree/v2.1.0/utils/cli)). These versions sent all data in a single request, so were not affected by this problem.

**Comment by nikste** [comment]
random as in for some tasks you need to specify the image order in reverse and for some others not, it seems to be pretty stable for creation with the same `cli.py .. create .. ` command

**Comment by AljoSt** [comment]
is there any update on this? With the current version of the sdk (2.4.0) using `predefined` sorting method still doesn't work

**Comment by AljoSt** [comment]
Just in case other people come here: `job_file_mapping`(https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/models/data-request/) can be used for this
