### ISSUE TITLE
Unable to run rest api tests - No such container:path: test_cvat_server_1:\tmp

### ISSUE THREAD

**Issue by awbage** [opencv/cvat#5063]
### My actions before raising this issue
- [+] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [+] Searched [past issues](/issues)

### Expected Behaviour
Running tests

### Current Behaviour
When I run a specific test or all tests using "pytest ./tests/python" I'm getting an error msg:
**No such container:path: test_cvat_server_1:\tmp**

### Possible Solution
It seems to me, Docker doesn't execute copying function properly
tests/python/shared/fixtures/init.py :196 - docker_restore_data_volumes

### Context
Environment was installed in accordance with the instructions
Here is a problem with copying tarball or creating "tmp" directory
I also tried to add required directory in test-cvat_server-1 container manually but it didn't work out

If you know what can I do about it please let me know. Thank you
![tcs1](https://user-images.githubusercontent.com/77973427/194765360-821425b7-88f9-4fb1-9851-6c41b38dd833.png)
![docker](https://user-images.githubusercontent.com/77973427/194765346-90627f48-dd17-41bc-843f-9913fe0d1ce7.png)

### Your Environment
- Python 3.9
- Docker-compose v2.10.2
- Docker version 20.10.17
- Windows 10 21H2
- Other diagnostic information / logs:

! _pytest.outcomes.Exit: Command failed: docker container cp C:\Users\Я\PycharmProjects\cvat\tests\python\shared\assets\cvat_db\cvat_data.tar.bz2 test_cvat_server_1:/tmp/cvat_data.tar.
bz2.
Error message: Error: No such container:path: test_cvat_server_1:\tmp
![no_such_cont](https://user-images.githubusercontent.com/77973427/194765438-3c67f7ed-7e40-46b5-83e2-1cfa9de47f6e.png)

**Comment by awbage** [comment]
Hi!
1. The issue is the same since the very first attempt to run tests
2. Output - Error: No such container: test_cvat_server_1
![lah](https://user-images.githubusercontent.com/77973427/194812857-a95a827c-4568-4aff-bedf-4d28f87e3f0c.png)
But maybe it makes sense to use dash symbols instead (docker exec -it test-cvat_server-1 ls -lah)
![dash](https://user-images.githubusercontent.com/77973427/194813451-f91c4cc6-2340-492c-8aab-863b35a15006.png)
3. I also tried to follow the advice from provided link, but didn't help
I'll see what else I can do, and will keep you updated!
If there is anything else I should try, please let me know. I only have a couple of days left to complete the test, and I I would greatly appreciate any assistance.

**Comment by zhiltsov-max** [comment]
Hmm, in the develop branch containers [use underscores](https://github.com/opencv/cvat/blob/develop/tests/python/shared/fixtures/init.py#L122) in their names. Which CVAT version are you using? Did you modify files somehow?

**Comment by awbage** [comment]
I had to modify two files since I couldn't install the cvat_sdk.api_client module but I thought it was not the cause of this problem
![client](https://user-images.githubusercontent.com/77973427/194827117-5133d990-c26c-4f01-bd71-72c9aba6b40c.png)

**Comment by zhiltsov-max** [comment]
No, this seems unrelated. Did you try to rename any containers? 

The developer installation instructions for SDK and CLI are available [here](https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/). You'll need to install both SDK and CLI like this: `pip install -e cvat-sdk/`, `pip install -e cvat-cli/`.

**Comment by awbage** [comment]
No, I didn't try to rename them, should I?

**Comment by zhiltsov-max** [comment]
I'm not sure why in your case the containers have the `test-`, while they are supposed to have underscores (`_`) in their names. If you can, please try to rename them (or just sync your branch with the actual `develop`).

**Comment by awbage** [comment]
Renaming some of these containers manually has finally led to some kind of success
Thank you!
![test](https://user-images.githubusercontent.com/77973427/194870831-a4ca7582-6164-4085-9420-2bbe37c2c892.png)

**Comment by zhiltsov-max** [comment]
I will close the issue as resolved. Feel free to reopen, if needed.

**Comment by azhavoro** [comment]
https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore
