### ISSUE TITLE
Helm readme doesn't work - link broken

### ISSUE THREAD

**Issue by turowicz** [opencv/cvat#5065]
Go to : https://github.com/opencv/cvat/blob/develop/helm-chart/README.md
Click "details"
404

**Comment by azhavoro** [comment]
Hello
Thanks, will be fixed soon

**Comment by turowicz** [comment]
Old version: https://github.com/opencv/cvat/blob/5e2eda76014c325c69dc297749d1d123ed315626/helm-chart/README.md

**Comment by azhavoro** [comment]
https://opencv.github.io/cvat/docs/administration/advanced/k8s_deployment_with_helm/
