### ISSUE TITLE
Installation sudo add-apt-repository

### ISSUE THREAD

**Issue by yustiks** [opencv/cvat#509]
Hello, thank You for the open-sourced project!
I am trying to install following the installation steps and I get one error during performing of it:
I follow the article:
```
https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md
```
When I run 
```
sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"
```
sytems gives me error:
```
Некорректные данные ввода, репозиторий не добавлен.
```
which means not correct data, repository was not added.

Any suggestions?

**Comment by yustiks** [comment]
I solved the issue by just skipping it. Basically, after I got the error I continued the intsallation process and worked ok.

**Comment by samwolf1982** [comment]
read node 
https://docs.docker.com/install/linux/docker-ce/ubuntu/

> 
Note: The lsb_release -cs sub-command below returns the name of your Ubuntu distribution, such as xenial. Sometimes, in a distribution like Linux Mint, you might need to change $(lsb_release -cs) to your parent Ubuntu distribution. For example, if you are using Linux Mint Tessa, you could use bionic. Docker does not offer any guarantees on untested and unsupported Ubuntu distributions.
>
