### ISSUE TITLE
Notify a user when a task is assigned to them

### ISSUE THREAD

**Issue by kais-bedioui** [opencv/cvat#5090]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)
- [ X ] Posted question on gitter.

In our annotation workflow, we want to include field experts in the loop and their role will be reviewers for the annotations generated by the semi-automatic labeling. What can I do in CVAT so that this reviewer (user) can get a notification whenever they are assigned to review some task(s)?
Thanks in advance
### Expected Behaviour
When a non-admin user is assigned as an annotator or reviewer in a given task, he/she gets a notification on CVAT or via email (if possible).

### Current Behaviour
When assigned to a contribute to a task, user gets no notification. They must manually check each task if they are assigned to it or not.

### Your Environment
We are using a local installation of CVAT on a Ubuntu 20.04 server.

**Comment by stemann** [comment]
Sounds like a duplicate of #2960

**Comment by kais-bedioui** [comment]
@stemann Thanks for tagging.
I will close this issue.
