### ISSUE TITLE
Open the Browser to get details

### ISSUE THREAD

**Issue by Adithyan-cpu** [opencv/cvat#5097]
Am getting the below error in the console, and I can upload the data in the morning time but after a couple of hours am getting the below error. 

Data are not corrupt as it is uploaded in the morning successfully.

please help me to resolve the issue.

Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at companion-bubble.js:1465:19726
    at Generator.next (<anonymous>)
    at Ln (companion-bubble.js:1465:19144)
/api/tasks/17487/data?org=&type=preview:1          Failed to load resource: the server responded with a status of 500 ()
/api/tasks/17429/data?org=&type=preview:1          Failed to load resource: the server responded with a status of 404 ()
/api/tasks/17425/data?org=&type=preview:1          Failed to load resource: the server responded with a status of 404 ()
/api/tasks/17272/data?org=&type=preview:1          Failed to load resource: the server responded with a status of 404 ()
/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 ()
/api/tasks/17124/data?org=&type=preview:1          Failed to load resource: the server responded with a status of 404 ()

**Comment by bsekachev** [comment]
@Adithyan-cpu 

Please, fill the issue template and provide some logs from ``cvat_server`` container.

**Comment by bsekachev** [comment]
I will close the issue for now. Do not hesitate to reopen if you are ready to provide requested details.
