### ISSUE TITLE
If there are multiple jobs in one task, delete_frames are saved for each job and the previous data is deleted.

### ISSUE THREAD

**Issue by byeong0** [opencv/cvat#5105]
### My actions before raising this issue
- [V] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [V] Searched [past issues](/issues)

### Expected Behaviour

engine_data.deleted_frames existing data must not be deleted.

### Current Behaviour

engine_data.deleted_frames data will be deleted.

If there are multiple jobs in one task,
While deletion frames are managed in task units,
'deleted_frames' seems to load/save on a job

save the job that deleted some frames
If you save another job in the same task, 
deleted frame data saved in the previous job is deleted.

Because the engine_job<->engine_task<->engine_data relationship
calls only the 'deleted_frames' of the job, the 'deleted_frames' stored in the task unit is
It seems to disappear because it has been updated to deleted_frame by job unit.

### Possible Solution

'deleted_frames' must be saved/loaded on a task basis or the column 'deleted_frames' must be managed on a job basis.

### Steps to Reproduce (for bugs)

1.Create multiple jobs in one task
1.Delete and save some frame from the first Job
1.Delete and save some frame from the second Job.
1.Delete frame data for the first Job disappears

### Your Environment

- cvat v2.2.0

**Comment by bsekachev** [comment]
@byeong0 

Thank you for report. I submit that there is a bug.

**Comment by bsekachev** [comment]
@byeong0 Please, try the PR above. It should help.

**Comment by byeong0** [comment]
> @byeong0 Please, try the PR above. It should help.

Thank you very much for the quick bug fix. When I tried the PR above, it works well.
