### ISSUE TITLE
404 Not found error when loading the browser UI for CVAT (Ubuntu 18.04)

### ISSUE THREAD

**Issue by tangtang666** [opencv/cvat#5107]
When i access the default localhost:8080 ,I get the 404 error, The traefik log is this, How to solve it？I test it on mac,it has the same questions.

```
# Not modified any file
step 1
git clone https://github.com/opencv/cvat.git

step 2
cd cvat
docker-compose up -d

```
```
time="2022-10-13T03:07:46Z" level=info msg="Configuration loaded from flags."
time="2022-10-13T03:07:46Z" level=error msg="Cannot start the provider *file.Provider: unable to read directory /etc/traefik/rules: open /etc/traefik/rules: no such file or directory"
```

**Comment by tangtang666** [comment]
use export CVAT_HOST=

**Comment by tangtang666** [comment]
CVAT_HOST just localhost work,0.0.0.0 not work

**Comment by azhavoro** [comment]
Hi, why do you expect 0.0.0.0 to work?
The currently used traefik `Host` matcher assumes only an exact match
https://doc.traefik.io/traefik/routing/routers/#rule

**Comment by tangtang666** [comment]
> Hi, why do you expect 0.0.0.0 to work? The currently used traefik `Host` matcher assumes only an exact match https://doc.traefik.io/traefik/routing/routers/#rule

Hi,I set the true ip it work,not 0.0.0.0

**Comment by TANKCHENG** [comment]
I think ipv6 maybe prior than ipv4, so localhost is not working.
Change localhost into IP address in LAN network, it will be successful.

export CVAT_HOST= "IP address in LAN network"
