### ISSUE TITLE
Improve error messages for a user

### ISSUE THREAD

**Issue by vskubriev** [opencv/cvat#511]
Deployed with docker-compose instance does not work as expected.

There is a screenshot:

![image](https://user-images.githubusercontent.com/4639077/59924563-aba34d00-943e-11e9-8511-c3f7ecdf0c9b.png)

docker logs cvat:

```
2019-06-21 13:05:07,800 DEBG 'runserver' stderr output:
[Fri Jun 21 13:05:07.800730 2019] [wsgi:error] [pid 177:tid 139934843741952] [remote 192.168.128.141:37976] [2019-06-21 13:05:07,800] WARNING django.request: Bad Request: /api/v1/tasks
```

**Comment by bsekachev** [comment]
@vskubriev 
You need to specify a labels. Message isn't well. We will fix it.

**Comment by vskubriev** [comment]
Thank you very much for a help.
