### ISSUE TITLE
Unable to import dataset with annotation

### ISSUE THREAD

**Issue by lchunleo** [opencv/cvat#5117]
Hi

  I have a dataset which has been annotated (external to CVAT) in yolo. I tried to do an import of the dataset (labels + images) in zipped and encountered issue.
 i am able to import the dataset but it subsequently fails:

Error: Request failed with status code 500. "datumaro.components.errors.DatasetNotFoundError: Failed to find dataset at '/tmp/tmpgozmpgkh'\n".

Is there also a tutorial to how to format the dataset and import it, just to make sure am doing correctly?

am using
Server version: 2.1

Core version: 5.0.1

Canvas version: 2.13.2

UI version: 1.37.0

**Comment by zhiltsov-max** [comment]
Hi, please check this page: https://opencv.github.io/cvat/docs/manual/advanced/formats/

**Comment by bsekachev** [comment]
I will close the issue, because there is not response from you side. 
Please, do not hesitate to reopen if you have more details.

**Comment by yfllllll** [comment]
@lchunleo have u solved this problem
