### ISSUE TITLE
Filters should not reset

### ISSUE THREAD

**Issue by Sumered** [opencv/cvat#5119]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
Filters resets when changing from jobs to tasks or when entering job and then going back to jobs.

### Expected Behaviour
Filters should be somehow more persistent so laberators does not need to set them every time they finish labeling etc.

**Comment by bsekachev** [comment]
Hi @Sumered 

You can restore filters from ``Recently used``.
You do not need to input them every time from scratch. 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/40690378/196226093-3789dfba-3bbe-4ae0-aff6-f35330ddc286.png">

**Comment by bsekachev** [comment]
I will close the issue, hope the advice helped you.
