### ISSUE TITLE
Can't upload an archive with images when creating the task 

### ISSUE THREAD

**Issue by dan1ssimo** [opencv/cvat#5120]
### My actions before raising this issue
- ☑️ Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- ☑️ Searched [past issues](/issues)

I have a large dataset of the format:
/dataset
-- /class1
---- /class1 images
-- /class2
---- /class2 images
...

I archived the dataset, so there are class folders inside the archive, and images inside them. I wanted to upload them to the markup platform when I created the task, but service gives me an error.

### Expected Behaviour
I'm expected to load my archive and get the job with all of my pictures from archive

### Current Behaviour
when I click submit & open, an error appears in the upper right corner of the screen: Could not create the task. Open the Browser Console to get details. Here is what is written in the console:

`Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/tasks/48/data/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).`

Then I tried to archive a separate class so that only images are in the archive at once, but this resulted in the same error.

### Steps to Reproduce (for bugs)
1. raise CVAT locally
2. go to the tab "tasks" and create a new one
3. upload an archive with images
4. Press "submit & open"

### Context
Trying to load a large dataset

### Your Environment
- Git hash commit: `commit 6811c57ef452367f36dfe7dcbd3b363df21e1744 (HEAD -> develop, origin/develop, origin/HEAD)`
- Docker version: 20.10.14
- Operating System and version: Ubuntu 20.04.5 LTS

**Comment by bsekachev** [comment]
Hi @dan1ssimo 

Try to logout/login. 

If the problem persists, can you share a minimal data needed to reproduce the issue?

**Comment by bob77109** [comment]
same error when i upload an archive with images(1000imgs, 700MB).
