### ISSUE TITLE
Can I upload annotation masks as jpg? What should I do, otherwise, to convert my annotations into a proper format (e.g. segmentation-masks 1.1)?

### ISSUE THREAD

**Issue by francescocister** [opencv/cvat#5125]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
@francescocister 

> Can I upload annotation masks as jpg?

I do not think so, because of .jpg compression specifics. 

> What should I do, otherwise, to convert my annotations into a proper format

To choose a format and write a conversion script, sorry for very common answer, but your format is not a CVAT issue. Try to ask community on gitter or Discord.

Thank you.
