### ISSUE TITLE
Kibana Analytics and Setting

### ISSUE THREAD

**Issue by 315386775** [opencv/cvat#5141]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Kibana Analytics with Chinese

i18n settings in Kibana(https://github.com/elastic/kibana/edit/8.4/docs/settings/i18n-settings.asciidoc)

i have add (i18n.locale: "zh-CN") in kibana.yml and build up again.

but the Analytics is also English version.

### Accuracy Statistics

In the labeling stage, the wrong image of a job is marked. How to count the accuracy of each job in the analysis interface.

### Time Statistics

The worker is currently being marked with cvat, but it is not displayed in the analysis interface

**Comment by azhavoro** [comment]
Hi
1. We don't Kibana, please ask your question in the Kibana repository
2. No way at the moment, this information is not logged in ELK
3. All events are sent to the server when the worker saves the annotation, just click the save button and you can see the events from the worker in Kibana.

**Comment by ConsciousML** [comment]
Hi,

I have the same issue, I have a huge delay by more than a week.
It is not usable in a production environment and we cannot measure the performance of our annotators.
What should we do ?

Best.

**Comment by azhavoro** [comment]
Hi, regarding delay see #2832

**Comment by bsekachev** [comment]
Let's close as a dublicate of issue with delays.
