### ISSUE TITLE
fix z-axis

### ISSUE THREAD

**Issue by guo0522** [opencv/cvat#5142]
### My actions before raising this issue
- [v] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [v] Searched [past issues](/issues)

### Expected Behaviour
1. Do any changes on the specific layer.
2. adjust brightness, contrast, and saturation

### Current Behaviour
1. z-order slider will change to the highest layer after I change any label on the current image.
3. brightness, contrast, and saturation hotkey is not working.

**Comment by bsekachev** [comment]
@guo0522 

> z-order slider will change to the highest layer after I change any label on the current image.

Thank you for feeback, I will look at the issue.

> brightness, contrast, and saturation hotkey is not working.

These features do not have hotkeys.

**Comment by bsekachev** [comment]
@guo0522 

Please, consider the PR above. It fixes z order behaviour

**Comment by guo0522** [comment]
@bsekachev Thanks for your quick reply and for fixing the z-order bug.
for the colorspace tool, I couldn't find a mechanism for adjusting brightness, contrast, and saturation in setting.

**Comment by bsekachev** [comment]
@guo0522 

Hi, it is not in settings.
It is here: 

<img width="947" alt="image" src="https://user-images.githubusercontent.com/40690378/197467104-52533965-f122-4924-82a7-b0996d6bc32b.png">

**Comment by guo0522** [comment]
Oh~I see it, very grateful for your help.
