### ISSUE TITLE
CVAT share not mounting - no error message

### ISSUE THREAD

**Issue by cpalomares** [opencv/cvat#5146]
The mounting of a network share not working, here is my overwrite file:
version: '3.3'

services:
  cvat_server:
    environment:
       CVAT_SHARE_URL: "Here we share!"
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_default:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/cvattest
      o: bind

The share is active on the host computer and can be accessed ad the host level ? I am using the latest version of CVAT just pulled yesterday.

any Ideas why shares are not mounting, am I messing anything ?
Thanks in advance

**Comment by bsekachev** [comment]
Hi @cpalomares 

You can look at example file where we mount shared storage to perform end-to-end testing: ``tests/docker-compose.file_share.yml``. 

What command do you use to build CVAT after these changes?

**Comment by cpalomares** [comment]
Hi @bsekachev I use :
 docker-compose -f docker-compose.yml  up -d --build --remove-orphans

**Comment by bsekachev** [comment]
You need to include the file with shared storage configuration via an additional ``-f`` argument.

**Comment by cpalomares** [comment]
@bsekachev I used thus following and worked :

 docker-compose up -d --build --remove-orphans

Thanks !!
