### ISSUE TITLE
Upload data annotation from CVAT to Azure Blob storage without using the manifest file

### ISSUE THREAD

**Issue by himanshudw** [opencv/cvat#5149]
### My actions before raising this issue
Read CVAT documentation to export dataset over the cloud service.
https://github.com/opencv/cvat/issues/4933- This does not solve the issue as even after creating manifest file we are not able to upload data to cloud

We expect that on the button click under the CVAT actions tab we are able to upload the annotation in a particular format to Azure blob storage.

### Expected Behaviour
The annotation file should be stored in Azure blob storage

### Current Behaviour
NA

### Possible Solution
NA

### Steps to Reproduce (for bugs)
We know that the util.py file under cvat/cvat/apps/dataset_manager needs to be updated to write the file over Azure blob storage but we are unable to get the location from where we can access the annotation file or a particular wat to use the API 

### Context
We are trying to use the annotation from CVAT to train our model but unable to fetch the dataset and their annotation

### Your Environment
Docker version docker version :20.10.17
Operating System and version :Linux
CVAT Version :dev

**Comment by zhiltsov-max** [comment]
@Marishka17 , please look at this issue.

**Comment by Marishka17** [comment]
@himanshudw, Hi, Could you please explain why you cannot attach your Azure container with a dummy manifest file (if  you are not going to use data from cloud storage to create tasks) and then use it for export annotations to Azure container?

**Comment by himanshudw** [comment]
Actually we want the data to be uploaded from our local computer and while we click on a train button(added in the action's menu) we would like to upload the annotation in TFrecord format for the task on Azure blob storage.

**Comment by himanshudw** [comment]
@Marishka17 
We have been able to get the new UI wherein we got the option for local storage and the target storage.

We have an azure cloud storage mounted on the CVAT.

We did as per the demo(https://user-images.githubusercontent.com/49038720/188583538-43722c39-85b0-495e-8ef2-c7376b51e4f9.mp4) but after exporting the dataset in any of the format we get error as attached 
<img width="946" alt="image" src="https://user-images.githubusercontent.com/61216926/198577705-60007f0c-6756-4e54-9818-47920d4973eb.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/61216926/198578161-c2294a53-0f9e-4ba9-8cc3-f2d2d61cda25.png">

**Comment by Marishka17** [comment]
@himanshudw, thanks for reporting the bug. I'll investigate.
