### ISSUE TITLE
Permissions for new users 

### ISSUE THREAD

**Issue by ninafiona** [opencv/cvat#5150]
I hosted a cvat instance and saw that anyone can sign up as a new user and create tasks. How can I 

a) disable sign-up (so new users have to be created by admin)
b) not add new users to group "user" so they have no permissions? 

As a workaround I could change the rules in OPA for "user", but I hope there is an easier way of achieving this.

**Comment by bsekachev** [comment]
Dublicate of #1283

**Comment by ninafiona** [comment]
Thanks, I tried their workaround setting up email-verification. It works, but I think the error message should be adapted for that solution. 

Is there another solution for workaround b)? 

I also tried changing the auth.csv (https://github.com/opencv/cvat/blob/develop/cvat/apps/iam/rules/auth.csv) `Priviledge` for `/auth/register` to `Admin`, but that did not result in any change.

**Comment by nmanovic** [comment]
@ninafiona , I will close the issue as a duplicate

**Comment by nmanovic** [comment]
https://github.com/opencv/cvat/issues/1283
