### ISSUE TITLE
Manual annotation is lost

### ISSUE THREAD

**Issue by 315386775** [opencv/cvat#5169]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

A job is completed and i am click the save button. But when a person re-examined these annotated images, it was found that the annotations of several images were missing. 

e.g. A job has 300 images, the first 200 are normal, and the last 100 are lost.

how to check and solve it.

**Comment by 315386775** [comment]
i have check the log. there is no log for user action during the last 100 images. 
May the reason for the network? how to avoid it?

**Comment by bsekachev** [comment]
If you didn't see any notifications about errors during saving, I do not think there were some Network issues.
Is it your local instance or ``app.cvat.ai``?

**Comment by bsekachev** [comment]
I will close the issue, because I do not have any ideas on how we can help with that. 
If you provide more details, we can try to investigate, but as I told, CVAT does not delete annotations itself.

**Comment by 315386775** [comment]
@bsekachev i have checked the log again. i find the infomation as follows. 

D:\01_Project\04_label\kitti_object_vis-master\server.txt

"from" => 1169, "to" => 1172,
"from" => 1385,  "to" => 1387,

there is no infomation about frame 1386, 1170 and 1172. i confirmed that i marked these frames.
