### ISSUE TITLE
Analytics Tools Problem

### ISSUE THREAD

**Issue by 315386775** [opencv/cvat#5176]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I want to get the user's annotation operation information at least a day ago. how to config or slove it.

### Current Behaviour

Installation Analytics followed _https://opencv.github.io/cvat/docs/administration/advanced/analytics/_

In Analytics the information as shown below. Now i only can get 10-10's infomation

![20221027103135](https://user-images.githubusercontent.com/12441747/198181867-55c56943-bbaf-4a0b-a365-f7f62e0fd0a0.png)

![20221027111119](https://user-images.githubusercontent.com/12441747/198182161-9ac2dbab-be9e-45aa-9b6c-6e026188bffe.jpg)

**Comment by azhavoro** [comment]
Hi, could you attach logs from cvat_server, logstash, elasticsearch containers?

**Comment by 315386775** [comment]
@azhavoro 

`
>>docker exec -it cvat_server bash
django@9a22c688255e:~$ ls
cvat  data  keys  logs  manage.py  media  mod_wsgi.conf  share  sources  static  supervisord  utils  wait-for-it.sh
django@9a22c688255e:~$ `

where log is usefull. and how to attach logs from logstash, elasticsearch containers.

**Comment by azhavoro** [comment]
```shell
docker logs cvat_server > server.txt
docker logs cvat_logstash > logstash.txt
docker logs cvat_elasticsearch > elasticsearch.txt
```

**Comment by 315386775** [comment]
@azhavoro 

server.txt is normal.

logstach.txt is very big. i has 20G+. Can i delete it? or how to modify the config/

elasticsearch.txt as following. 

[elasticsearch.txt](https://github.com/opencv/cvat/files/9878464/elasticsearch.txt)

**Comment by azhavoro** [comment]
`high disk watermark [90%] exceeded on [Ngi0vu8oRqOhNCgce8KiKQ][Ngi0vu8][/usr/share/elasticsearch/data/nodes/0] free: 35.8gb[8.8%], shards will be relocated away from this node`
The issue is not related with cvat, the reason is that all elasticsearch indexes are read-only, this is a well-known behavior of elasticsearch, please google the solution

**Comment by azhavoro** [comment]
Regarding log size you can manage it with docker compose, just add these lines into ovverdie file or modify `components/analytics/docker-compose.analytics.yml`
```yml
services:
  logstash:
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"

```

**Comment by 315386775** [comment]
@azhavoro thanks. good job
