### ISSUE TITLE
How can i run code cvat in test enviroment ?

### ISSUE THREAD

**Issue by ThorPham** [opencv/cvat#5180]
Thank you for your work. Cvat is great tool for annotation .
I want to add more feature on cvat so i want to run cvat in local without docker to debug and testing code.
How can i do that.

**Comment by zhiltsov-max** [comment]
https://opencv.github.io/cvat/docs/contributing/development-environment/

**Comment by ThorPham** [comment]
Thank you so much

**Comment by ThorPham** [comment]
I has problem when build development enviroment.
Could not check authorization on the server
Error: Request failed with status code 500. "Error occurred while trying to proxy: localhost:3000/api/users/self?org=".
how can i fix it.

**Comment by zhiltsov-max** [comment]
@bsekachev , please check this issue.

**Comment by ThorPham** [comment]
Log in brower
![image](https://user-images.githubusercontent.com/33828708/198685757-9f41ff38-9b02-4436-af04-bccd4b9f219d.png)

**Comment by zhiltsov-max** [comment]
Hi, please try to change `localhost` to `127.0.0.1` here: https://github.com/opencv/cvat/blob/develop/cvat-ui/package.json#L8

**Comment by bsekachev** [comment]
@ThorPham 

As I see, you have changed default configuration (at least I see not default port number)
So, if you want us to help you, please provide all the details.

**Comment by ThorPham** [comment]
@bsekachevv , @zhiltsov-max thank you for your support. Sorry my bad , i forget run docker so it has error.
