### ISSUE TITLE
Can't init Auto Annotation Tool in terminal with nuclio

### ISSUE THREAD

**Issue by dan1ssimo** [opencv/cvat#5182]
### My actions before raising this issue
- [✅] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [✅] Searched [past issues](/issues)

  I would like to try using automatic annotation in CVAT deployed locally, but even following the documentation clearly, I ran into an error
![image](https://user-images.githubusercontent.com/59598620/198520919-cee64c6d-cb5c-4b90-8e74-43a08f2061dd.png)

### Steps to Reproduce (for bugs)
1. Just followed every step from the [documentation](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/) and from the [video](https://www.youtube.com/watch?v=qYQE95VjfmA&ab_channel=IntelSoftware)

**Comment by bsekachev** [comment]
@dan1ssimo 

Please, address your question to [nuclio](https://github.com/nuclio/nuclio) project.
I've just tried this command and it works as expected for me on Ubuntu 20.04.

**Comment by nmanovic** [comment]
@dan1ssimo , let us know if you solve the problem. I will close the issue for now. I have no idea how we can help here. Don't hesitate to reopen it if you can provide more details or a way how to reproduce it on our side.
