### ISSUE TITLE
How CVAT processing images?

### ISSUE THREAD

**Issue by dan1ssimo** [opencv/cvat#5183]
### My actions before raising this issue
- [✅] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [✅] Searched [past issues](/issues)
I have CVAT deployed in cloud. I upload a video in task, annotate it, and when i try to export annotated images - CVAT crashes 

### Expected Behaviour
Expected to get annotated images 

### Current Behaviour
got a crash of cvat

**Comment by zhiltsov-max** [comment]
Please fill the issue template.
