### ISSUE TITLE
Deploy skeleton model on CVAT 

### ISSUE THREAD

**Issue by OnceUponATimeMathley** [opencv/cvat#5184]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

I write serverless function for skeleton model, and send json format to the CVAT. But I insert some error before SkeletonShape super constructor. It has the error : Cannot read properties of null (reading 'every') instead of my custom error.
But with RectangleShape, it go to my error first
![Screenshot from 2022-10-28 15-59-37](https://user-images.githubusercontent.com/52577359/198548836-ce70ffc8-142f-4844-a987-790875de2a9f.png)
How can I check the function the json output go into before create SkeletonShape object. Thanks
![Screenshot from 2022-10-27 11-58-14](https://user-images.githubusercontent.com/52577359/198548987-924fcd4c-980a-40a8-b82e-57dcf178ae62.png)

**Comment by bsekachev** [comment]
Please, do not dublicate your issues #5177
