### ISSUE TITLE
Errors when installing cvat-sdk from local git repo (broken file structure)

### ISSUE THREAD

**Issue by inpv** [opencv/cvat#5201]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The `cvat-sdk` module correctly installs from local (and fresh) git repo.

### Current Behaviour

At the moment the command `pip install -e cvat-sdk/`, which is referenced as required in REST API test [docs](https://github.com/opencv/cvat/tree/develop/tests/python), doesn't yield the expected results.

See the full stack trace:
```
(.env) [%USER%@%HOST% cvat]$ python3.9 -m pip install -e cvat-sdk/
Obtaining file:///home/%USER%/Development/cvat/cvat-sdk
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['gen', 'cvat_sdk'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Possible Solution

I tried editing `pyproject.toml` with [project] and [tool.setuptools] as it was mentioned [here](https://github.com/pypa/setuptools/issues/3197#issuecomment-1078770109) and ended up with `api_client` folder missing, so to me the best option seems to restructure the package into `src`-based layout, like in `cvat-cli`. This method will also make it convenient to put unit tests there in a separate directory as well.

### Steps to Reproduce (for bugs)

1. Install `cvat`
2. `cd` to its location
3. Activate python's `env`
4. `pip install -e cvat-sdk/`

My particular setup is python 3.9, pytest 6.2.5, pip 22.3.

### Context

The new module is really needed for testing purposes, since the versions at PyPI are already kinda outdated and do not have new features like insecure host check [control](https://github.com/opencv/cvat/commit/68375ec23e6c60441c3c574448b6c0b76d129d60) from CLI and server version check [tests](https://github.com/opencv/cvat/blob/12a295af72ff65e1c68c47536c761c739680dcd6/tests/python/sdk/test_client.py#L97) for which there are no exceptions mentioned in 2.1.0 yet (e.g. "IncompatibleVersionException").

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi! Please follow [this guide](https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/) to set `cvat-sdk` and `cvat-cli`.

**Comment by inpv** [comment]
Thanks! I have a couple questions/notes about the dev [docs](https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/) though:

1. Installing the packages locally via `mkdir -p cvat-sdk/schema/ && python manage.py spectacular --file cvat-sdk/schema/schema.yml` yields some errors:
```
(.env) [%USER%@%HOST% cvat]$ mkdir -p cvat-sdk/schema/ && python manage.py spectacular --file cvat-sdk/schema/schema.yml
Warning #0: Fixed: LoginSerializerEx: registered extensions CookieTokenRefreshSerializerExtension for "dj_rest_auth.jwt_auth.CookieTokenRefreshSerializer" has an installed app but target class was not found.
Warning #1: Fixed: registered extensions SimpleJWTCookieScheme for "dj_rest_auth.jwt_auth.JWTCookieAuthentication" has an installed app but target class was not found.
Warning #2: @extend_schema_view argument "update" was not found on view MembershipViewSet. method override for "update" will be ignored.
Warning #3: @extend_schema_view argument "update" was not found on view OrganizationViewSet. method override for "update" will be ignored.
Error #0: WebhookViewSet: exception raised while getting serializer. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'NoneType' object is not callable)
Warning #4: enum naming encountered a non-optimally resolvable collision for fields named "type". The same name has been used for multiple choice sets in multiple components. The collision was resolved with "Type478Enum". add an entry to ENUM_NAME_OVERRIDES to fix the naming.
Warning #5: encountered multiple names for the same choice set (Type478Enum). This may be unwanted even though the generated schema is technically correct. Add an entry to ENUM_NAME_OVERRIDES to fix the naming.

Schema generation summary:
Warnings: 13 (6 unique)
Errors:   5 (1 unique)
```
Do I need to install any other packages before downloading the schema? (I can run both the dev server locally and in Docker)

2. The command at step 2 about installing the generator dependencies from root /cvat directory should be corrected to `pip install -r cvat-sdk/gen/requirements.txt`, because of wrong dir error (chdir to package root dir is only at step 3).

3. It may be necessary to state that Docker services should be started before attempting to run the command at step 3.

4. It also may be necessary to state that `pip install -e` commands should be run from cvat root dir, not the package root dir.

**Comment by zhiltsov-max** [comment]
Hi,

1. These warnings are expected at this moment. No extra actions from your side are required.
2. - 4. Please send us a PR if you see how the docs can be improved.

**Comment by inpv** [comment]
Ok, thanks. The package built fine. Does the CVAT CI system utilize the nightly or the stable `cvat-sdk` package upon building the `develop` test server, though?

**Comment by inpv** [comment]
How do I run all these checks locally before commit? Can the `act` [module](https://github.com/nektos/act) truly emulate them, for example?

**Comment by zhiltsov-max** [comment]
The steps to run tests are described here: https://opencv.github.io/cvat/docs/contributing/running-tests/

**Comment by nmanovic** [comment]
I will close the issue. It looks like all questions were answered.
