### ISSUE TITLE
Error while new installation

### ISSUE THREAD

**Issue by smarnav2904** [opencv/cvat#5203]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X ] Searched [past issues](/issues)

Once all previous container and volumes were deleted, I tried to make a new installation of CVAT, but when the SuperUser is created a bunch of errors appear in the console when logging.
### Expected Behaviour
The main screen of CVAT should appear on screen once logged.

### Current Behaviour
When user credentials are provided, I should be able to log in.

### Possible Solution
---

### Steps to Reproduce (for bugs)
1. Delete all your current containers and volumes of CVAT.
2. Delete your CVAT folder.
3. Run: `git clone https://github.com/opencv/cvat` and `cd cvat` to get cvat and move to the folder.
4. Run: `docker-compose up -d` to start the containers and create your volumes.
5. Run: `docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'` to create a superuser (for instance, I used Admin/Admin as credentials as a test, password requirements were overridden for this purpose).
6. Try to log in, then this errors appear:
![imagen](https://user-images.githubusercontent.com/95945394/198972146-de9aa8ea-d41d-407f-a07a-ba8b04d190b1.png)

### Your Environment
- Docker version `20.10.17` 
- Linux
- Log of cvat_server in the moment of the error:
![imagen](https://user-images.githubusercontent.com/95945394/198972974-a14e7f96-94e7-462a-baa3-11375fcc68ec.png)
![imagen](https://user-images.githubusercontent.com/95945394/198973054-8eb0d5db-41bb-4d7d-8f09-5c1127371b09.png)

**Comment by zhiltsov-max** [comment]
@azhavoro , could you please check?

**Comment by azhavoro** [comment]
@smarnav2904 Hello,

it seems you need to update your local docker images with `docker compose pull`

**Comment by smarnav2904** [comment]
> @smarnav2904 Hello,
> 
> it seems you need to update your local docker images with `docker compose pull`

Replicated the process described in the issue but doing so, still the same error

**Comment by smarnav2904** [comment]
> What is output of `docker images` in your case?

![image](https://user-images.githubusercontent.com/95945394/199453750-d2122c6c-692b-46b7-9c3c-02e9e898ed1e.png)
Just to note, the image called "cvat/prueba" its actually a custom image that I made to test a serverless function

**Comment by azhavoro** [comment]
Your cvat/server:dev hash differs from docker hub published image https://hub.docker.com/r/cvat/server/tags,
try to pull manually `docker pull cvat/server:dev` and `docker pull cvat/ui:dev`

**Comment by smarnav2904** [comment]
> Your cvat/server:dev hash differs from docker hub published image https://hub.docker.com/r/cvat/server/tags, try to pull manually `docker pull cvat/server:dev` and `docker pull cvat/ui:dev`

Thanks for you quick answer but the error still persist. Once previous images were removed, I pulled those you mentioned.
Image for reference of the images:
![image](https://user-images.githubusercontent.com/95945394/199462413-fb194de1-1243-4b90-ab25-09dbfb7ac3b5.png)

**Comment by azhavoro** [comment]
please attach `docker ps` output, `docker logs cvat_server > server.txt` and `docker logs cvat_opa > opa.txt` containers logs

**Comment by smarnav2904** [comment]
Docker ps output:
![image](https://user-images.githubusercontent.com/95945394/199464953-1ca30090-9f8f-4dc2-9f79-9d6f954898dc.png)


Server.txt
[server.txt](https://github.com/opencv/cvat/files/9919388/server.txt)

Opa.txt its empty, bash launches this error when trying to retrieve the logs:
![image](https://user-images.githubusercontent.com/95945394/199465619-5d72c401-dae9-4d78-a29a-5af80142968d.png)

**Comment by azhavoro** [comment]
What exact version of cvat are you using `git log -1`?

**Comment by smarnav2904** [comment]
> 

![image](https://user-images.githubusercontent.com/95945394/199468690-054dbd2c-a8da-4dea-936a-6e896b44876f.png)
For instance, the installation process followed its the one provided in the website, to quote:
`git clone https://github.com/opencv/cvat`

**Comment by smarnav2904** [comment]
> You need to update cvat source code with `git pull`, currently you are using old compose config with new images

Thanks, that fixed the error, somehow `git clone` was not retrieving latest version. Consider this issue closed.
