### ISSUE TITLE
Automatic annotation using yolov3 gives error

### ISSUE THREAD

**Issue by janezlapajne** [opencv/cvat#5205]
Related to common issue, such as [https://github.com/opencv/cvat/issues/2820](https://github.com/opencv/cvat/issues/2820).

I followed the instructions in the [manual](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/). All commands execute properly and the connection to app UI is established. However, when I run:
```
nuctl deploy --project-name cvat \
  --path serverless/openvino/omz/public/yolo-v3-tf/nuclio \
  --volume `pwd`/serverless/common:/opt/nuclio/common \
  --platform local
```
it gives me an error:
```
Error - fork/exec /opt/nuclio/common/openvino/python3: no such file or directory
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239

Call stack:
Can't run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
Failed to run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:106
Failed to start runtime
    /nuclio/pkg/processor/worker/factory.go:100
Failed to create worker
    /nuclio/pkg/processor/worker/factory.go:119
Failed to create workers
    /nuclio/pkg/processor/worker/factory.go:129

    /nuclio/pkg/platform/local/platform.go:1168
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:197
```

It is interesting to see, that it says: No such file or directory, since the python3 exist on my local machine (I guess something goes wrong when the volume is mapped?). Also, when I open UI and try to use an option: `Automatic anotation` it throws an error:
```
Fetching inference status for the [task 2](http://localhost:8080/tasks/2)
Error: Inference status for the task 2 is failed. requests.exceptions.InvalidURL: Failed to parse: http://host.docker.internal:None
```

My setup:
- Windows 10 with wsl2
- git log -1:
commit 12a295af72ff65e1c68c47536c761c739680dcd6 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Kirill Sizov <kirill.sizov@cvat.ai>
Date:   Fri Oct 28 17:11:04 2022 +0300
- docker version: Docker Desktop 4.13.0 (89412) is currently the newest version available

**Comment by bsekachev** [comment]
@janezlapajne 
Do you have ``python3`` file inside `pwd`/serverless/common/openvino in CVAT directory?

**Comment by janezlapajne** [comment]
@bsekachev yes I do, in the same folder also lies model_loader.py file.

**Comment by bsekachev** [comment]
@janezlapajne 

I suppose the reason is wsl, because the same command works for me well on Ubuntu OS.  What is `pwd` output on wsl?

**Comment by janezlapajne** [comment]
Hello again @bsekachev, yes, this might have something to do with wsl, because the path is mapped to: `/mnt/c/Users/username`. This is why I moved the whole repo to `\\wsl$\Ubuntu\home\username`, so as a consequence the pwd command now outputs: `/home/username/cvat` . Obviously, the file is now accessible and at program's disposal, however, now a different error appeared:
```
Error - exec: "/opt/nuclio/common/openvino/python3": permission denied
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239

Call stack:
Can't run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
Failed to run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:106
Failed to start runtime
    /nuclio/pkg/processor/worker/factory.go:100
Failed to create worker
    /nuclio/pkg/processor/worker/factory.go:119
Failed to create workers
    /nuclio/pkg/processor/worker/factory.go:129

    /nuclio/pkg/platform/local/platform.go:1168
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:197
```

Any idea on how to give it proper permissions? I used the commands stated in the manual, but nothing changes:
```
sudo chmod +x nuctl-<version>-linux-amd64
sudo ln -sf $(pwd)/nuctl-<version>-linux-amd64 /usr/local/bin/nuctl
```

**Comment by bsekachev** [comment]
> Any idea on how to give it proper permissions? I used the commands stated in the manual, but nothing changes:

There are instructions in manual on how change permissions for ``nuclio`` binary.
In your case something wrong with ``serverless/common/openvino/python3`` or/and with some parent directories.

What can you see if you do ``ls -la serverless/common/openvino/``?

**Comment by janezlapajne** [comment]
yes indeed. The output from command:
```
➜  cvat git:(develop) ✗ ls -la serverless/common/openvino
total 16K
drwxr-xr-x 2 janezla janezla 4.0K Nov  1 23:03 .
drwxr-xr-x 3 janezla janezla 4.0K Nov  1 23:03 ..
-rw-r--r-- 1 janezla janezla 2.6K Oct 30 17:19 model_loader.py
-rw-r--r-- 1 janezla janezla  142 Oct 30 17:19 python3
```

I tried to use `sudo chmod -x serverless/common/openvino/python3`, but then the file is again not visible by the program...

**Comment by bsekachev** [comment]
``python3`` must be executable. ``chmod -x`` removes executable flag. You need to add it with ``chmod +x``. 

<img width="287" alt="image" src="https://user-images.githubusercontent.com/40690378/199452677-e07a50cb-8ae7-4189-965d-fc4c0ac29bae.png">

**Comment by janezlapajne** [comment]
Ah sorry, I accidentally posted the wrong command. I meant with + of course. I wanted to tell you, that when a file IS executable the program gives error:
```
Error - fork/exec /opt/nuclio/common/openvino/python3: no such file or directory
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239

Call stack:
Can't run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
Failed to run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:106
Failed to start runtime
    /nuclio/pkg/processor/worker/factory.go:100
Failed to create worker
    /nuclio/pkg/processor/worker/factory.go:119
Failed to create workers
    /nuclio/pkg/processor/worker/factory.go:129

    /nuclio/pkg/platform/local/platform.go:1168
Failed to deploy function
```

And corresponding permissions:
```
➜  cvat git:(develop) ✗ ls -la serverless/common/openvino
total 16K
drwxr-xr-x 2 janezla janezla 4.0K Nov  1 23:03 .
drwxr-xr-x 3 janezla janezla 4.0K Nov  1 23:03 ..
-rw-r--r-- 1 janezla janezla 2.6K Oct 30 17:19 model_loader.py
-rwxr-xr-x 1 janezla janezla  142 Oct 30 17:19 python3
```

**Comment by bsekachev** [comment]
Did you try this suggestion? 
https://github.com/docker/for-win/issues/2151#issuecomment-402163189

**Comment by janezlapajne** [comment]
To be sincere, I didn't 😅 Thank you for the suggestion. But to be honest, I will probably try further sometime in the future, since I already invested too much time on it 😊 Anyways, if I figure something out, I will post it here.

**Comment by nmanovic** [comment]
@janezlapajne , I will close the issue. It looks like we cannot help here anymore.

**Comment by venuss920** [comment]
Please give the port number in the - nuctl deploy --project-name cvat --path "./serverless/pytorch/facebookresearch/sam/nuclio/" --platform local --triggers '{"myHttpTrigger": {"kind": "http", "maxWorkers": 1, "attributes": {"port": 49156}}}', and also change the 
in attributes: maxRequestBodySize to 61708864 #more than 32MB, this will solve your internal host error:None
