### ISSUE TITLE
Provide better organization for installation instructions docs

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#5209]
Currently, there are already 3 platforms with separate instructions. I feel, we should reorganize this section to [use tabs](https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes) or something else. The tabs seem to require hugo/docsy upgrade.

**Comment by nmanovic** [comment]
The installation documentation has been redesigned. Let's keep it in the form for now.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/40690625/210587425-98ad7803-23a4-48b0-ba7b-7e2968479546.png">

**Comment by zhiltsov-max** [comment]
I think we need to revisit the dev instructions: https://opencv.github.io/cvat/docs/contributing/development-environment/
