### ISSUE TITLE
How do I export CVAT annotation for YOLO5? Is there a way to apply image augmentation using CVAT?

### ISSUE THREAD

**Issue by martinenkoEduard** [opencv/cvat#5217]
How do I export CVAT annotation for YOLO5? Is there a way to apply image augmentation using CVAT?

**Comment by zhiltsov-max** [comment]
Hi, please try to use [`Export task dataset`](https://opencv.github.io/cvat/docs/manual/basics/tasks-page/) and select `YOLO` format. 

CVAT can't help with image augmentations, but please check if [Datumaro](https://github.com/cvat-ai/datumaro) can be useful for you.
