### ISSUE TITLE
Unstable Cypress tests

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#5220]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

* actions_organizations/case_113_new_organization_pipeline.js (<https://github.com/opencv/cvat/actions/runs/3370435670>), (<https://github.com/opencv/cvat/actions/runs/3434910998>)
* actions_tasks3/case_19_all_image_rotate_features.js (<https://github.com/opencv/cvat/actions/runs/3327849116>)
* actions_tasks3/case_18_filters_functionality.js (<https://github.com/opencv/cvat/actions/runs/3367707635>), maybe fixed by  #5212

**Comment by klakhov** [comment]
Fells like `actions_tasks3/case_18_filters_functionality.js` is unstable. Failed [here](https://github.com/opencv/cvat/actions/runs/3468942785/jobs/5795556187)

**Comment by nmanovic** [comment]
I will propose the following practice. If a test is failed, we don't re-run them but just fix. It is useless to have issues about unstable tests on github.

**Comment by bsekachev** [comment]
@nmanovic 

If it was easy to fix them, we would do this. But it even difficult to reproduce.
So, the issue is for the future tests engineer who might invest time to them.
