### ISSUE TITLE
Model list not displaying

### ISSUE THREAD

**Issue by smarnav2904** [opencv/cvat#5222]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

Created a serverless function to run a custom Darknet Model to use in Auto Annotation mode, but when done, CVAT throws an error when displaying model list.

### Expected Behaviour
The model list should appear with my model and all the previous ones used, as Yolov3 or Mask-RCNN.

### Current Behaviour
Once the serverless function as been tested and deployed (throwing the expected result when invoked), CVAT throws and error while trying to retrieve the model list, screenshot as additional info of the error:
![image](https://user-images.githubusercontent.com/95945394/199476099-72fc9cee-12be-4b04-a63f-363955b81cea.png)

### Steps to Reproduce (for bugs)
1.Get the image that i'm using from dockerhub `docker pull smarnav/darknet-mirror-detector`
2.Create the serverless function with GPU Support `nuctl deploy prueba --project-name cvat --run-image smarnav/darknet-mirror-detector:latest  --runtime python:3.6 --handler darknet_images:handler --platform local --resource-limit nvidia.com/gpu=1` 
3.Once deployed, you can test it invoking it with any image that you want, result should be something like this:
![image](https://user-images.githubusercontent.com/95945394/199477166-bdc50ccf-daec-476c-bf82-6bf5a0c6fb0e.png)
4.Then deploying cvat with serverless support should bring the model list with my model, but not the case

### Context
This docker image its going to be used for a project on a Solar Energy Plant, using it to detect failures in the structures, CVAT its need to provide more info to make the model more accurate in the long term, providing the personal on the plant a way to annotate the images in a semi-autonomous way 

### Your Environment
- Docker version `20.10.17`
- Operating System: Linux
-The image that im using for the serverless function was provided previously.

**Comment by smarnav2904** [comment]
To add more information, `docker logs cvat_server` throws this error:
![imagen](https://user-images.githubusercontent.com/95945394/199683848-54a3c0af-bf92-45c7-bfe2-4f16445e1303.png)

**Comment by azhavoro** [comment]
@smarnav2904 You need to specify the `annotations` section in the metadata. You can find a detailed example here
https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/#dl-model-as-a-serverless-function

**Comment by smarnav2904** [comment]
I got to fix it, the problem was that cvat was not reading the yaml properly.
Fixed it giving it the configuration manually by going to nuclio dashboard and setting it there.
Consider this issue closed.
