### ISSUE TITLE
I created a Cvat account but I did not receive the verification email

### ISSUE THREAD

**Issue by magnades** [opencv/cvat#5224]
Greetings, 

I created a Cvat account but I did not receive the verification email. For this reason, I can not log in to my account and use Cvat online. Can you please send againt the email. Besides, I tried to recover my password, but the system do not let me because my email is not verified. Please can you help me

Best regards,

Juan

**Comment by bsekachev** [comment]
Hi @magnades 

Unfortunately sometimes it happens, we are looking for a solution. Now I activated your account manually.

**Comment by SakshiPradyumnAsurion** [comment]
Hello,
I face the same issue of not receiving verification email. And not able to proceed when trying to log in saying email is not verified
Associated with this email address and account
Thank you for the help
