### ISSUE TITLE
[enhancement] Annotate using more than 1 image as "reference"

### ISSUE THREAD

**Issue by kunaltyagi** [opencv/cvat#5227]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Allow more than a single image at a time be used as reference for annotation

### Current Behaviour
Can't use more than a single image as reference

### Possible Solution
1. Allow creation of more than 1 viewport and select an arbitrary image (in the dataset) for the other viewport
2. Allow each viewport to be manipulated independently (zoom, pan, rotate, skew) as well as in locked mode
3. Moving ahead by 1 frame should advance both viewports by 1 frame
4. The tracks could be locked as well. Moving a track point in 1 viewport would also move it similarly in the other viewport (relative to it's existing position)

### Context
This would help in the following 2 scenarios:
1. Annotate Multi-camera datasets
2. Annotate features which need to be common between 2 frames

**Comment by bsekachev** [comment]
Related to #4648 and #3596 and #793

**Comment by nmanovic** [comment]
@kunaltyagi , thanks for the issue. It is very popular senario right now. But it is a huge feature. If somebody is ready to pay for it, our team can implement it. I will close the issue as duplicate.
