### ISSUE TITLE
"No media data found" in UI dataset import

### ISSUE THREAD

**Issue by julled** [opencv/cvat#5229]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I want to export a dataset, edit the dataset externaly and upload the dataset again via Import in the UI.
The dataset was created via file share data.
If i import the dataset again via CVAT or COCO format, i receive a visual error 

> Could not import dataset to the [project 7](http://breakout.hs-augsburg.de:8080/projects/7)
> Error: Request failed with status code 500. "ValueError: No media data found\n".

### Expected Behaviour

The dataset should imported and replace / extend the current dataset on the server.

### Current Behaviour

The error above appear.

### Possible Solution

I think there is a error in the shared files implementation.

### Steps to Reproduce (for bugs)
1. Create a dataset which includes at least one task with images in /shared/folderX/folderY/img.jpg
1. Export the dataset in the CVAT fileformat via UI (disabled "save images" option)
1. Import the dataset in the CVAT fileformat via UI
1.

### Context

I want to export a dataset, edit the dataset externaly and upload the dataset again via Import in the UI.

### Your Environment

- Running via  `CVAT_VERSION=dev docker-compose  up -d`
- Git hash commit (`git log -1`):
```
commit 2311b10b800a5c564af3af547472541e9b9b7cde (HEAD -> develop, origin/develop, origin/HEAD)                                                                          
Author: Anastasia Yasakova <yasakova_anastasiya@mail.ru>
Date:   Fri Oct 21 12:52:36 2022 +0300

    Fix an issue with Imagenet dataset import (#4861)

```
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 20.10.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Debian
- Code example or link to GitHub repo or gist to reproduce problem: No
- Other diagnostic information / logs:
```

django@c58e8b630737:~$ cat logs/cvat_server.log 
....
[2022-11-03 18:44:25,540] INFO cvat.server.project_7: The project '2022-08-xx' is exported as 'CVAT for images 1.1' at '/home/django/data/projects/7/export_cache/annotations_cvat-for-images-11.ZIP' and available for downloading for the next 3:20:00. Export cache cleaning job is enqueued, id '2fd48142-d81c-44b8-80c2-9fea218200e2'
[2022-11-03 18:45:52,344] INFO cvat.server: create task #116
[2022-11-03 18:45:53,763] ERROR django.request: Internal Server Error: /api/projects/7/dataset
```

**Comment by zhiltsov-max** [comment]
@yasakova-anastasia, could you please check?

**Comment by julled** [comment]
Ive also tested this with the unittest images from https://github.com/opencv/cvat/tree/develop/tests/mounted_file_share/images and it yields the same error.

Maybe the shared folder causes a problem? This issue might be related to https://github.com/opencv/cvat/issues/5230

Export and import a TASK on the same data on a shared folder works.

**Comment by julled** [comment]
i tried the proposed changes in the mnt shared from https://github.com/opencv/cvat/issues/5228#issuecomment-1303320245 but it didnt help me on my problem.

**Comment by zhiltsov-max** [comment]
Hi, I failed to reproduce the error. Please check that you're exporting with the "Save images" option is enabled.

**Comment by julled** [comment]
I have disabled this option. I need to disable this due to huge size of the dataset.

Could you please try to also disable to save images option to reproduce this?

**Comment by zhiltsov-max** [comment]
If the imported archive doesn't contain images, it's impossible to import it as a dataset. Consider creating tasks with images and importing annotations to these tasks insted.

**Comment by julled** [comment]
Thx for clarifying this, this was not obvious for me from the GUI. 

Usecase is 
> I want to export a dataset, edit the dataset externaly and upload the dataset again via Import in the UI.

As every dataset has quite some tasks (about 30 for our appliocation) its quite some manual work to export , edit the dataset externaly and import each task again.

**Comment by zhiltsov-max** [comment]
Ok, please check if you can use our [SDK and CLI](https://opencv.github.io/cvat/docs/api_sdk/) to automate these operations. 

> I want to export a dataset(without image files), edit the dataset externaly (add annotations, tags etc. via custom scripts) and upload the dataset again via Import in the UI.

In the exported datasets, do you expect that only annotations are going to change or the image set / the images themselves are going to change too? In the first case, you can just export only annotations and mount the images from the shared directory where they are needed then. In the second case, you will need to recreate tasks manually (maybe, using SDK or CLI) specifying image list from the share in the creation parameters each time and then import annotations if you want to save the disk space.

**Comment by julled** [comment]
I expect to not change the images for our usecase. The annotation-info i want to add is already generated externally, so i dont need the images to generate/extend that info.

But due to this bug or missing feature from this issue at least this usecase seems to not work.

**Comment by zhiltsov-max** [comment]
This problem is not a bug. The datasets are expected to be self-contained. If you have a set of annotations for an existing task, please use "Upload annotations" as I described above.

**Comment by julled** [comment]
> This problem is not a bug. The datasets are expected to be self-contained. If you have a set of annotations for an existing task, please use "Upload annotations" as I described above.

Thank you for this info. I though that its still expected to get imported again even if there is no image data included in the export.
