### ISSUE TITLE
upload mot1.1 annotation file, the visibility and ignored information fail to be loaded。

### ISSUE THREAD

**Issue by optimal16** [opencv/cvat#5231]
When I upload mot1.1 annotation file, the visibility and ignored information fail to be loaded。
![image](https://user-images.githubusercontent.com/21096083/199906629-3122a475-f8e8-4208-9b1a-6ac0d9248308.png)
In fact, project label default values are used for both visibility and ignored  all images. 
Meanwhile, the bounding box is successfully loaded.

![image](https://user-images.githubusercontent.com/21096083/199907451-d965e220-b80a-45dc-b802-08e0545c8eb9.png)

**Comment by zhiltsov-max** [comment]
@yasakova-anastasia , could you please check?

**Comment by dangnh0611** [comment]
I'm facing the same problem, any update ?
