### ISSUE TITLE
When I use "docker build" and: "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"

### ISSUE THREAD

**Issue by mesakas** [opencv/cvat#5234]
### My actions before raising this issue

I modify "cvat/apps/engine/task.py":

```python
# modify before
raise ValueError('Only one {} or many {} can be used simultaneously, but {} found.'.format(unique_types, multiply_types, count))

# modify after
raise ValueError('==test modify== Only one {} or many {} can be used simultaneously, but {} found.'.format(unique_types, multiply_types, count))
```

just a little change, but when I use `docker build -t app .`:

```
C:\Users\Ming\Desktop\cvat-mod\cvat> docker build -t app .
...
...
...
#10 304.0 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libp/libpipeline/libpipeline1_1.5.2-2build1_amd64.deb  502  Bad Gateway [IP: 91.189.91.38 80]
#10 304.0 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
executor failed running [/bin/sh -c apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -yq         apache2-dev         build-essential         curl         libgeos-dev         libldap2-dev         libsasl2-dev         nasm         git         pkg-config         python3-dev         python3-pip         python3-venv &&     rm -rf /var/lib/apt/lists/*]: exit code: 100
```

so, this is my not use `apt-get`?, but my program running in docker, I am confused.

what should I do?😢

### Your Environment

- Windows 11
- WSL2 -> Ubuntu 22.04

**Comment by zhiltsov-max** [comment]
Hi. It seems that during container build there was some problem connecting to the update server to retrieve OS packages. Such problems can appear from time to time, typically they don't require any actions from the user side. Please try to build the container again later. The error itself indicates a connection problem.

**Comment by mesakas** [comment]
> Hi. It seems that during the Docker image build there was some problem connecting to the update server to retrieve OS packages. Such problems can appear from time to time, typically they don't require any actions from the user side. Please try to build the container again later. Was it the first time you built an image or you did it before in this environment?

is first time.

**Comment by zhiltsov-max** [comment]
Hi! Did you check if the server access problem is resolved?

**Comment by mesakas** [comment]
Thank you, is Internet error, already can be use.
