### ISSUE TITLE
Change a user's password as superuser account?

### ISSUE THREAD

**Issue by connor11son** [opencv/cvat#5243]
Is it possible to use the API to change a user's password as the admin account? I see there is the option to change password for the authenticated user, but not sure if I can make a request when authenticated as superuser to changes another user's password.

**Comment by zhiltsov-max** [comment]
@azhavoro , please look at this issue.

**Comment by nmanovic** [comment]
@connor11son , for now, it isn't possible to change a user's password as the admin account. You can do that in the admin panel. I don't understand the reason to change the password of another user. Why cannot the user change their own password?

**Comment by nmanovic** [comment]
I will close the issue because the original question was answered.
