### ISSUE TITLE
Error while logging

### ISSUE THREAD

**Issue by PierreColombo** [opencv/cvat#5244]
### My actions before raising this issue
- [v ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [v ] Searched [past issues](/issues)

Hi ! 
I am trying to follow the developping guide to contribute on Deep Learning Models and set up a local environement.
I can run the server and got to the logging page.

While I go on Chrome at http://localhost:3000/ i face the following error:

`Could not check authorization on the server
Open the Browser Console to get details`

The console gives the following error:

`ConnectionError at /api/users/self
HTTPConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /v1/data/users/allow (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feee99d91f0>: Failed to establish a new connection: [Errno 61] Connection refused'))`

If i try to register a new user I get the following error

`export-dataset-modal.tsx:243 

Uncaught TypeError: Cannot read properties of null (reading 'dumpers')
    at Function.mapStateToProps [as mapToProps] (export-dataset-modal.tsx:243:50)
    at mapToPropsProxy (wrapMapToProps.js:47:1)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:56:1)
    at mapToPropsProxy (wrapMapToProps.js:47:1)
    at handleFirstCall (selectorFactory.js:19:1)
    at pureFinalPropsSelector (selectorFactory.js:60:1)
    at selector (connect.js:313:1)
    at useSyncExternalStore (use-sync-external-store-shim.development.js:115:1)
    at ConnectFunction (connect.js:337:1)
    at renderWithHooks (react-dom.development.js:14803:1)
mapStateToProps @ export-dataset-modal.tsx:243
mapToPropsProxy @ wrapMapToProps.js:47
detectFactoryAndVerify @ wrapMapToProps.js:56
mapToPropsProxy @ wrapMapToProps.js:47
handleFirstCall @ selectorFactory.js:19
pureFinalPropsSelector @ selectorFactory.js:60
selector @ connect.js:313
useSyncExternalStore @ use-sync-external-store-shim.development.js:115
ConnectFunction @ connect.js:337
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
updateSimpleMemoComponent @ react-dom.development.js:16972
updateMemoComponent @ react-dom.development.js:16861
beginWork @ react-dom.development.js:18682
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonyme) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
batchedUpdates$1 @ react-dom.development.js:21862
notify @ Subscription.js:16
notifyNestedSubs @ Subscription.js:88
handleChangeWrapper @ Subscription.js:93
dispatch @ redux.js:297
(anonyme) @ redux-logger.es.js:847
(anonyme) @ index.js:20
dispatch @ redux.js:691
(anonyme) @ plugins-actions.ts:31
await in (anonyme) (asynchrone)
(anonyme) @ index.js:16
initPlugins @ index.tsx:112
componentDidUpdate @ cvat-app.tsx:236
commitLifeCycles @ react-dom.development.js:19835
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonyme) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
batchedUpdates$1 @ react-dom.development.js:21862
notify @ Subscription.js:16
notifyNestedSubs @ Subscription.js:88
handleChangeWrapper @ Subscription.js:93
dispatch @ redux.js:297
(anonyme) @ redux-logger.es.js:847
(anonyme) @ index.js:20
dispatch @ redux.js:691
(anonyme) @ auth-actions.ts:98
await in (anonyme) (asynchrone)
(anonyme) @ index.js:16
onRegister @ register-page.tsx:38
onSubmit @ register-page.tsx:52
onFinish @ register-form.tsx:115
onFinish @ Form.js:74
(anonyme) @ useForm.js:845
Promise.then (asynchrone)
FormStore.submit @ useForm.js:840
onSubmit @ Form.js:125
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:389
executeDispatchesInOrder @ react-dom.development.js:414
executeDispatchesAndRelease @ react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3287
forEachAccumulated @ react-dom.development.js:3259
runEventsInBatch @ react-dom.development.js:3304
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
'
And this one in 

'import-dataset-modal.tsx:479'

' Uncaught TypeError: Cannot read properties of null (reading 'loaders')
    at Function.mapStateToProps [as mapToProps] (import-dataset-modal.tsx:479:52)
    at mapToPropsProxy (wrapMapToProps.js:47:1)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:56:1)
    at mapToPropsProxy (wrapMapToProps.js:47:1)
    at handleFirstCall (selectorFactory.js:19:1)
    at pureFinalPropsSelector (selectorFactory.js:60:1)
    at selector (connect.js:313:1)
    at useSyncExternalStore (use-sync-external-store-shim.development.js:115:1)
    at ConnectFunction (connect.js:337:1)
    at renderWithHooks (react-dom.development.js:14803:1)`
### Expected Behaviour

I would like to be able to log in and test my new segmentation model. 
### Current Behaviour

Cannot log despite following the proposed steps.

### Steps to Reproduce (for bugs)

I am running on MACOS and on archlinux i have the same problem.

### Context

I am trying to provide the community new DL models.
### Your Environment

- Git hash commit (`git log -1`): commit 445bc3401397e8aa87e61cce193a9d9925674104 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): Server: Docker Desktop 4.13.0 (89412)
- Are you using Docker Swarm or Kubernetes? No 
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS M1
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Thanks a lot for your help !

**Comment by zhiltsov-max** [comment]
Hi, please start the OPA container: `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d cvat_opa`.

**Comment by azhavoro** [comment]
@PierreColombo Hi, you need to add missed port forwarding option for opa container:
`docker run -d --rm --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.34.2-rootless \
run --server --set=decision_logs.console=true --set=services.cvat.url=http://host.docker.internal:7000/ \
--set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules`
I will update the documentation

**Comment by mikhail-treskin** [comment]
@azhavoro  @zhiltsov-max  @PierreColombo  Hey guys!

I've tried all of the advices above but still keep getting same error both on develop (7383c17) and v2.2.0 (79ce99a) if i'm running in local dev environment. Meanwhile running with docker-compose works fine, so looks like something wrong with networking between services in local env. 
What is the most suspicious that on a first glance both django and cvat_opa_debug logs (see below) says that everything is ok, but on authorisation page all of requests are getting 403 response and "Could not check authorization on the server"/"Could not get user agreements from the server" errors are raised.
Environment is pretty the same as @PierreColombo originally mentioned (MacOS 13.0.1 Intel; Docker Engine v20.10.17) redis server up and running as standalone process. 

Any clues on that?

docker ps: 
```
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS          PORTS                    NAMES
b711d662df79   openpolicyagent/opa:0.34.2-rootless   "/opa run --server -…"   21 minutes ago   Up 21 minutes   0.0.0.0:8181->8181/tcp   cvat_opa_debug
f8134752ce96   gcr.io/iguazio/alpine:3.15            "/bin/sh -c '/bin/sl…"   3 hours ago      Up 3 hours                               nuclio-local-storage-reader
``` 
cvat_opa_debug logs:
```
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2022-11-18T14:26:19Z"}
{"level":"info","msg":"Starting bundle loader.","name":"cvat","plugin":"bundle","time":"2022-11-18T14:26:19Z"}
{"level":"info","msg":"Starting decision logger.","plugin":"decision_logs","time":"2022-11-18T14:26:19Z"}
{"level":"info","msg":"Bundle loaded and activated successfully. Etag updated to \"5cde574896ba3e5e2db9e964d0ffb9d1573f90e737e9c7d32cc561774df8020371281ee2587baf1838e33fa03be97bc3f48290ec5853dfd4b4d095a169371772\".","name":"cvat","plugin":"bundle","time":"2022-11-18T14:26:19Z"}
{"current_version":"0.34.2","download_opa":"https://openpolicyagent.org/downloads/v0.46.1/opa_linux_amd64","latest_version":"0.46.1","level":"info","msg":"OPA is out of date.","release_notes":"https://github.com/open-policy-agent/opa/releases/tag/v0.46.1","time":"2022-11-18T14:26:20Z"}
```

django logs:
```
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2022 - 14:18:20
Django version 3.2.16, using settings 'cvat.settings.development'
Starting development server at http://127.0.0.1:7000/
Quit the server with CONTROL-C.
[2022-11-18 14:20:02,813] INFO django.server: "GET /api/auth/rules HTTP/1.1" 200 5163
INFO:django.server:"GET /api/auth/rules HTTP/1.1" 200 5163
[2022-11-18 14:20:12,114] INFO django.server: "GET /api/auth/rules HTTP/1.1" 304 0
INFO:django.server:"GET /api/auth/rules HTTP/1.1" 304 0
[2022-11-18 14:20:22,046] INFO django.server: "GET /api/auth/rules HTTP/1.1" 304 0
INFO:django.server:"GET /api/auth/rules HTTP/1.1" 304 0
[2022-11-18 14:20:30,795] INFO django.server: "GET /api/auth/rules HTTP/1.1" 304 0
INFO:django.server:"GET /api/auth/rules HTTP/1.1" 304 0
[2022-11-18 14:20:38,620] INFO django.server: "GET /api/auth/rules HTTP/1.1" 304 0
INFO:django.server:"GET /api/auth/rules HTTP/1.1" 304 0
....
```

chrome dev-console logs (call stack collapsed):
```
xhr.js:220                 GET http://localhost:3000/api/users/self?org= 403 (Forbidden)
cvat-app.tsx:295     Errror: Request failed with status code 403. "".
xhr.js:220                 GET http://localhost:3000/api/user-agreements?org= 403 (Forbidden)
cvat-app.tsx:295     Error: Request failed with status code 403. "".
xhr.js:220                 OPTIONS http://localhost:3000/api/auth/password/change?org= 403 (Forbidden)
xhr.js:220                 OPTIONS http://localhost:3000/api/auth/password/reset?org= 403 (Forbidden)
xhr.js:220                 GET http://localhost:3000/api/server/advanced-auth?org= 403 (Forbidden)
```

What also looks suspicious (at least I haven't seen such behaviour previously), that django process keeps producing and rotating threads continuously if opa is running, but i'm not sure that it somehow relates to an issue

![Screenshot 2022-11-18 at 17 57 06](https://user-images.githubusercontent.com/56150992/202735359-091b346f-c6ce-4f81-a74c-0803884d09b3.png)

**Comment by nmanovic** [comment]
@mikhail-treskin , let's have a call. Find me in linkedin. I will try to help you setup the environment.

**Comment by nmanovic** [comment]
I believe the issue was resolved. I will close it.

**Comment by piwawa** [comment]
> I believe the issue was resolved. I will close it.

nuclio                  | 23.06.15 03:45:01.220 dashboard.platform.docker (D) Container is healthy {"containerID": "7039d3544d6ed438dfdf863cf9e80fa22ab3338fee75e051868f39de205b5055"}
cvat_opa                | {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp: lookup cvat-server on 127.0.0.11:53: no such host","name":"cvat","plugin":"bundle","time":"2023-06-15T03:45:07Z"}
cvat_opa                | {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp: lookup cvat-server on 127.0.0.11:53: no such host","name":"cvat","plugin":"bundle","time":"2023-06-15T03:45:21Z"}

I met same error when i deploy like this `docker compose -f docker-compose.yml -f docker-compose.dev.yml -f components/serverless/docker-compose.serverless.yml -f docker-compose.override.yml up -d --build`.

These containers can not be up:

![image](https://github.com/opencv/cvat/assets/46926496/cd9c8f9d-2d6c-4eb1-a1c6-0d86b3349148)

**Comment by stevezkw1998** [comment]
> @PierreColombo Hi, you need to add missed port forwarding option for opa container: `docker run -d --rm --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.34.2-rootless \ run --server --set=decision_logs.console=true --set=services.cvat.url=http://host.docker.internal:7000/ \ --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules` I will update the documentation

Hi @azhavoro Could you please share the link of your updated document? I need this guidance to solve my issue, thanks
