### ISSUE TITLE
Incorrect Label Colors

### ISSUE THREAD

**Issue by dotsinspace** [opencv/cvat#5246]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Incorrect Labeling colors. when segmented mask images are downloaded from Cvat and incorrect labeling colors when used datum.
### Expected Behaviour
Expecting the output image to be correct is what is shown in CVAT.

On Cvat and Expecting these colors
![image](https://user-images.githubusercontent.com/76559517/200142155-b8683843-22e7-4a37-81b4-d803938b9d97.png)

### Current Behaviour
When Downloaded
1. Segmented Object
![image](https://user-images.githubusercontent.com/76559517/200142197-5b635e6a-516b-4ba3-951f-573940812c5e.png)
2. Segmented Class
![image](https://user-images.githubusercontent.com/76559517/200142205-b154067d-0678-4d65-9963-211dbfde0258.png)

The same is happening in the datum I used the following commands.

```
datum convert -i annotations.xml -if cvat -o cvat-dm -f datumaro --overwrite
datum transform -t polygons_to_masks --overwrite cvat-dm/:datumaro
datum convert -i cvat-dm/ -if datumaro -o voc -f voc --overwrite
```

### Steps to Reproduce (for bugs)
Please use this zip and try out it with datum installed (pip install datum[default])
https://drive.google.com/drive/folders/1LrU7xotEzHltkg8Q2e8CRs4yXOySUSyf?usp=sharing

Please help its urgent.

**Comment by dotsinspace** [comment]
dont know if what I am saying is a solution or not but I did try removing the polygon to the minimum say where you have only two or three items annotated and guess what it works..but when I have 1000 labels and 1000s polygon points this problem arrieses.

**Comment by dotsinspace** [comment]
All tools are failing on the same..tried following.

1. DataLoop
2. Hasty
3. Cvat
4. Datum
5. ReactLabel ( Mac Only )

**Comment by zhiltsov-max** [comment]
Hi! Thank you for reporting the problem. To me, it looks like color channels can be swapped. Need to investigate.

Please note, that PASCAL VOC mask encoding can handle a maximum of 255 labels / instances per image, because they are encoded as palette-based PNGs. If you want to export more that 255 - consider using another format. Possible options with different encoding are Datumaro (unlimited) COCO panoptic (via Datumaro. Encodes segment ids, no colors), KITTI (unlimited in indexed masks), CityScapes (up to 1k instances and, probably, 65 or 200k labels).

**Comment by dotsinspace** [comment]
Okay..i tried using datumaro it works with COCO panoptic but i want custom label colors..problem is this.

**Comment by zhiltsov-max** [comment]
Does your dataset really needs to display segmentations with 1k labels? Probably, colors are only useful for humans. Please check if you can use some other encoding for training, and apply some colormap only when rendering, and only to show images with distinct colors for shapes.

**Comment by dotsinspace** [comment]
Yes i am annotating humans with label around 1100.

**Comment by zhiltsov-max** [comment]
I mean, "for humans" is to visualize results for people to show. Could you please describe your use case?

**Comment by dotsinspace** [comment]
okay, I am working on a project where we have to segment everything (Labels are above > 100, and annotations are around a few to 100s )..example is shown above. no problem is this I can annotate them but when I download Mask from cvat label colors seem mismatched. to get around this I tried datmaru..but the same problem arose. now what I am trying to do now is parse XML to SVG and SVG to Png. for color reduction I am using Photopea which is an online tool.

**Comment by zhiltsov-max** [comment]
Ok, then consider the advice above. Basically, you can use any mask format if you have < 255 labels in total or instances per image. Otherwise, you should consider one of the formats with special data encoding.
