### ISSUE TITLE
Detection Error Occured

### ISSUE THREAD

**Issue by michael-selasi-dzamesi** [opencv/cvat#5248]
![Screenshot from 2022-11-07 08-41-33](https://user-images.githubusercontent.com/73562161/200253708-264e4500-a400-4451-a174-e69042a7a3b9.png)
![Screenshot from 2022-11-07 08-41-13](https://user-images.githubusercontent.com/73562161/200253710-4ccd9ab5-3ec6-4822-ac5a-a10d0d8f7021.png)

# I am new to CVAT and Nuclio, I am trying out the semi-automatic annotation and I am encountering these issue

# Here is more on the error description

![Screenshot from 2022-11-07 08-46-55](https://user-images.githubusercontent.com/73562161/200254193-397ea0be-f61c-4c05-b358-ef75c5053441.png)

**Comment by bsekachev** [comment]
Hi @michael-selasi-dzamesi 

Please provide us ``docker ps``, ``docker logs cvat_server`` and steps to reproduce the issue.

**Comment by michael-selasi-dzamesi** [comment]
@bsekachev Here is the information you requested:

#### docker ps

![Screenshot from 2022-11-07 10-07-16](https://user-images.githubusercontent.com/73562161/200270904-30405391-28e1-4948-b544-4a8be550adfb.png)

#### docker logs cvat_server
![Screenshot from 2022-11-07 10-08-40](https://user-images.githubusercontent.com/73562161/200271194-70ff6d6a-d10d-4707-a97d-eabf887bdf93.png)

**Comment by michael-selasi-dzamesi** [comment]
@bsekachev I have realized the problem is with my data, and not from your end. Thank you for making me read the log file!!!
