### ISSUE TITLE
Export all images of a job even if no annotation is present

### ISSUE THREAD

**Issue by lostcontrol** [opencv/cvat#525]
We have images of static scenes taken with different exposure time, lighting conditions, etc. We annotate only one image of a given scene and then duplicate the information using a Python script to the other pictures of the same scene.

The problem is that at the moment CVAT only export in the XML images that have at least one annotation. In order to workaround this, we draw a point in the corner of the first picture and propagate it to the whole set of picture and later filter out the points annotations. It would be nice if CVAT would also export images with empty annotations.

Something like the following:
```
<image height="2050" id="58" name="001-001.png" width="2448">
  <box label="A" occluded="0" xbr="2063.41" xtl="1832.21" ybr="1577.37" ytl="1269.10" />
  <box label="B" occluded="0" xbr="827.76" xtl="540.04" ybr="1895.92" ytl="1572.24" />
</image>
<image height="2050" id="58" name="001-002.png" width="2448" />
<image height="2050" id="58" name="001-003.png" width="2448" />
<image height="2050" id="58" name="001-004.png" width="2448" />
```

**Comment by LukeAI** [comment]
Will this be implemented soon? Would be really useful for my use-case.

**Comment by olympus999** [comment]
I had the same need, I ended up getting the data from DB.
Example query:
"""select path, frame from cvatv2.public.engine_image where task_id = {task_id};;""".format(task_id=task_id)

**Comment by benhoff** [comment]
@LukeAI & @lostcontrol, which data format are you using? This would need to get implemented at the individual dumper level.

**Comment by LukeAI** [comment]
yolo

**Comment by lostcontrol** [comment]
We are using the CVAT XML format.

**Comment by nmanovic** [comment]
@zhiltsov-max , do you think the issue is possible to resolve using datumaro? Could you please post here a solution or advice?

**Comment by zhiltsov-max** [comment]
It definitely can be done with Datumaro - just export task as dataset of the desired format.
