### ISSUE TITLE
How CVAT is using dataset manifest file? why CVAT needs it?

### ISSUE THREAD

**Issue by ranumintel** [opencv/cvat#5251]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi, you can read more about this [here](https://opencv.github.io/cvat/docs/manual/basics/attach-cloud-storage/) in the docs. The use of these files will also be extended in #5083, and there the documentation is [also extended](https://github.com/opencv/cvat/blob/420356934c5eefec024d6c75c5e841735b7df4cf/site/content/en/docs/manual/advanced/dataset_manifest.md) to be more helpful.
