### ISSUE TITLE
Want to have an option to change the type of shape (e.g from polyline to polygon)

### ISSUE THREAD

**Issue by Abulegenov** [opencv/cvat#5252]
### My actions before raising this issue
- [ ] I am annotating some work and I only use polygon type of shape. However, sometimes I accidentally choose polylines and realize it after I finished the annotation. Here I faced the problem that it is not possible to change the type of annotation,  thus you can only reannotate your current job, which I found ineffective time usage. It would be great if there would be an option to change the type of shape with one click. 

### Expected Behaviour
Having an option to change the type of shape of annotated instances.
Also it would be great to have an option to change all same typed shapes to desired shape. In the info section we have information about the quantity of instances, and going further if we could interchange them that would be awesome.

### Current Behaviour
There isn't any)

### Possible Solution
Just write few lines of code, with usage of already given points, and change the structure of annotation to desired one

### Steps to Reproduce (for bugs)
1. Upload some work
2. Annotate with any shape
3. try to change the type of shape

### Context
Currently I have more than 100 instances that are polylines, but I need polygons. 

### Your Environment
don't think it is necessary here (I downloaded cvat 4 months ago)

**Comment by bsekachev** [comment]
@Abulegenov 

In your case, you can try dumping annotations in one of formats (let's say ``CVAT format``), create a copy (just for backup) then open the copy, rename all ``polyline`` to ``polygon`` and upload this copy annotation file back. 

I do not think that implementing this conversion is UI is a good solution:
1. You anyway need to go throught each object and change its annotation type
2. If try to generalize, in the most of cases, it is unclear how to convert different annotation types between each other (polygon -> rectangle, points -> polyline, polygon, ellipse -> cuboid, mask -> polygon, etc.. )

**Comment by nmanovic** [comment]
@Abulegenov , thanks for the proposal. I don't think we are going to implement the idea in the nearest future. I will close the issue.
