### ISSUE TITLE
How to debug CVAT easily?

### ISSUE THREAD

**Issue by mesakas** [opencv/cvat#5254]
I Want change CVAT source, but I can only use valumes in Docker now, It's really inefficient.
Is there any way use like:

`python manage.py runserver`

and

`npm run start`

Can it be done in this way? 😢

**Comment by bsekachev** [comment]
@mesakas 

Please, follow the guide to setup dev environment: https://opencv.github.io/cvat/docs/contributing/development-environment/

**Comment by zhiltsov-max** [comment]
Hi, there is an option to have bare-metal deployment, it is described [here](https://opencv.github.io/cvat/docs/contributing/development-environment/). There are predefined VS Code tasks to run server and UI in debug mode. 
If you need to debug in docker - please check [this branch](https://github.com/opencv/cvat/tree/zm/allow-remote-debugging). It's not merged yet, but it allows you to use VS Code tasks to debug server deployed with docker. In this brach, you need to launch containers with the following command: `CVAT_DEBUG_ENABLED=yes docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`.

**Comment by mesakas** [comment]
thank you!
