### ISSUE TITLE
Skeleton Track: Hide keypoints does not take effect immediately

### ISSUE THREAD

**Issue by ConsciousML** [opencv/cvat#5256]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

When using the new skeleton annotation feature, when we hide a keypoint, it does not take effect immediately.

### Expected Behaviour

When clicking the "Switch Outside Property" on a keypoint, it should hide right away.

### Current Behaviour

When clicking the "Switch Outside Property" on a keypoint,  it is need to go one frame forward and one frame back to see it disappear.

### Context

It is confusing because sometimes we don't know if we correctly set the keypoint outside.

### Your Environment

- Git hash commit (`git log -1`): 46b88c11ab2bbb4989365899196bf4157ee94b90
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.21
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04

**Comment by bsekachev** [comment]
Hi @ConsciousML 

Looks like a bug, I will look into it.

**Comment by ConsciousML** [comment]
Thank you very much @bsekachev
It works perfectly now !
