### ISSUE TITLE
Error when serving conecction: body size exceeds the given limit

### ISSUE THREAD

**Issue by smarnav2904** [opencv/cvat#5258]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

I got a custom Darknet Model running on CVAT, capable to annotate images automatically, however, when I try to use the same model to annotate a video, an error its thrown which says the same as the title.
I tried to remove the maxRequestBodySize parameter in my function.yaml but the error still persist.
### Expected Behavior
The video should get annotated.

### Current Behavior
Video it's not annotated

**Comment by bsekachev** [comment]
Serverless functions in CVAT do not work with videos.
When you want to annotate the whole video (a task, I assume),

<img width="860" alt="image" src="https://user-images.githubusercontent.com/40690378/200590139-b1f91045-710c-4f0b-94e7-71a2906b66b5.png">

 it sends frame by frame to the serverless function, get results and saves them.

**Comment by smarnav2904** [comment]
Doing so still throws the same error as the title, just for claritifaction, the model I'm running uses this configuration:
`triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 1000
      attributes:
        maxRequestBodySize: 33554432
        readBufferSize: 33554432`

**Comment by zhoupan163** [comment]
Hello，
![image](https://github.com/opencv/cvat/assets/49024472/f646ec43-e2f5-45d9-b92f-c38057fe83c7)
I check the docker logs:
error when serving connection "172.17.0.4:8080"<->"172.17.0.1:33830": body size exceeds the given limit

**Comment by sd3ntato** [comment]
@zhoupan163  did you manage to solve the issue?
I'm stuck with the same problem

**Comment by zhoupan163** [comment]
> @zhoupan163 did you manage to solve the issue? I'm stuck with the same problem
Yes, I have already resolved it，Thank for your help

**Comment by Sunhill666** [comment]
@smarnav2904 did you solve the issue?

**Comment by Sunhill666** [comment]
Guys, I solved this problem by increasing maxRequestBodySize.
For example, I use sam's DL model, and I change maxRequestBodySize in `function.yaml` to `67108864`, which is 64MB.
