### ISSUE TITLE
Quality control: honeypot

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#526]
One way to control quality is to implement so called honeypots. An owner of a task can provide annotations for a couple of frames. These frames can be used to calculate quality of the whole task. For example, we need to annotate 1000 frames with bounding boxes for vehicles. The owner of the task can annotate 20 arbiturarly frames (2%). If all frames are annotated correctly we can say that quality is very high (about 100%).

**Comment by vivekkalyanarangan30** [comment]
@nmanovic is this available for self-hosted version? If yes, can you point me to some documentation on the setup?

**Comment by zhiltsov-max** [comment]
Implemented for tasks in [Release 2.5.0](https://github.com/opencv/cvat/releases/tag/v2.5.0), extended for projects in #6367.

Documentation is available [here](https://opencv.github.io/cvat/docs/manual/advanced/analytics-and-monitoring/annotation-quality/) and [here](https://www.youtube.com/watch?v=0HtBnr_CZAM).

**Comment by vivekkalyanarangan30** [comment]
@zhiltsov-max actually I am unable to see the same interface in spite os using version 2.5 - 

<img width="1394" alt="Screenshot 2023-08-18 at 10 52 02 AM" src="https://github.com/opencv/cvat/assets/12863647/46927088-f1b5-4bf2-9d3d-493e40f061e9">
<img width="797" alt="Screenshot 2023-08-18 at 10 53 07 AM" src="https://github.com/opencv/cvat/assets/12863647/cd676a33-6c07-4d21-86a8-8cba809c638c">

**Comment by zhiltsov-max** [comment]
@vivekkalyanarangan30, I suppose you can be on the develop branch somewhere between the previous release and 2.5.0. Please try to run CVAT from the release tag (`git checkout v2.5.0 && CVAT_VERSION=v2.5.0 docker compose up -d`).
