### ISSUE TITLE
Unable to export polygon annotations into PASCAL VOC 1.1 format for my instance segmentation task.

### ISSUE THREAD

**Issue by utkarsa-anand** [opencv/cvat#5263]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Get polygon coordinates for each polygon annotation in the **PASCAL VOC 1.1** xml file.

### Current Behaviour
No polygon coordinates in the xml file
![current_behaviour](https://user-images.githubusercontent.com/117763935/200814016-fc0f4227-7802-49aa-b967-b1e77cc6a0b8.JPG)

### Steps to Reproduce (for bugs)

1. Draw polygon annotations to an input Image.
2. Export the annotations into PASCAL VOC 1.1 format

### Context
The model that we are training is designed to accept only PASCAL VOC 1.1 format images. Earlier we were training in Rectangle annotations in PASCAL VOC 1.1 format which was working fine but now the Polygon annotations are not getting exported to PASCAL VOC 1.1 format.

### Your Environment
-CVAT version 2.2.0

**Comment by zhiltsov-max** [comment]
Hi, please use the `Segmentation Mask` format.

**Comment by nmanovic** [comment]
@utkarsa-anand , PASCAL VOC doesn't support polygons. You should have masks for your classes and objects. I will close the issue. Please look at SegmentationClass and SegmentationObject directories.

I will close the issue.
