### ISSUE TITLE
Automatic annotate dataset imported from connected file share error:  [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vividzhang** [opencv/cvat#5267]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Task page: Actions -> Automatic annotation -> success

### Current Behaviour

Task page: Actions -> Automatic annotation -> FileNotFoundError: [Errno 2] No such file or directory
![image](https://user-images.githubusercontent.com/21956027/200993856-c1783767-7853-47b5-86e0-9eb15f91ca19.png)

### Steps to Reproduce (for bugs)

1. modify docker-compose.yam to volume share path
![image](https://user-images.githubusercontent.com/21956027/200994615-393815e5-81a0-4765-b806-6049024be588.png)
![image](https://user-images.githubusercontent.com/21956027/200994665-5efdcfb9-46c3-4a25-8064-77f2fcf4fc71.png)
2. docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
3. project page -> create a new task
4. Select files -> Connected file share -> choose dataset directory -> submit & open
5. task page -> Actions -> Automatic annotation -> select a model -> annotate -> error

### Your Environment

- Git hash commit (`git log -1`):  c7125a8ffbef2945a2256bc584f75353dd69ea1e
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.21
- Are you using Docker Swarm or Kubernetes?    Docker Swarm
- Operating System and version (e.g. Linux, Windows, MacOS):  Ubuntu 18.04

**Comment by azhavoro** [comment]
Please see https://github.com/opencv/cvat/issues/5228#issuecomment-1303320245

**Comment by azhavoro** [comment]
https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path

**Comment by walterwangimagr** [comment]
Same issue here, found the solution, just add 
cvat_worker_low:
    volumes:
      - cvat_share:/home/django/share:ro

**Comment by vividzhang** [comment]
It works. Thank you very much!

**Comment by IndefiniteBen** [comment]
Same issue here, but `cvat_worker_low` gives the same error:
> service "cvat_worker_low" has neither an image nor a build context specified: invalid compose project

I had to instead add the below to the `services` section of `docker-compose.override.yaml`:
```
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share:ro
```

**Comment by peidongha** [comment]
@IndefiniteBen  Same issue here, I had to instead add the below to the services section of docker-compose.override.yaml,and it is working.
 cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share:ro
