### ISSUE TITLE
I want to export the annotations from cvat. But I am getting error request failed with status code 403. You don't have permission to perform requested action. HOW TO GET PERMISSION?

### ISSUE THREAD

**Issue by Chetan571999** [opencv/cvat#5268]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi! Please be more specific about the situation. 
- Where the situation happens? Is your own server or the official app?
- What is your role in the project/task? Does it happen in an org project, your own project, you own task, ...? E.g. `annotator`-s can't export datasets.

**Comment by Chetan571999** [comment]
I am using the cvat.ai on chrome. It's my own project.

**Comment by zhiltsov-max** [comment]
Hi, please try to export data for the task instead. It must be on the task overview page:
![image](https://user-images.githubusercontent.com/13832349/201275705-5ad2c458-5888-460b-aba5-b6b2bc0bf552.png)

**Comment by Chetan571999** [comment]
Actually I tried that several times but still got the same error.

**Comment by ArtyomSkaruba** [comment]
Registered today and faced the same problem.
You can use the previous version (i use 2.1.0) or wait for a fix.

https://opencv.github.io/cvat/docs/administration/basics/installation/
