### ISSUE TITLE
  3D lidar

### ISSUE THREAD

**Issue by keshavadk** [opencv/cvat#5276]
In 3D Lidar, when we update/switch the attribute of an object and copy that object only the default attribute values get copied ,not the updated attributes. But in case of 2D image the updated attributes also get copied. How can I make updated attributes also get copied in 3D view?

Thank you.

**Comment by bsekachev** [comment]
Hi, @keshavadk 

That is probably a bug, need to investigate

**Comment by nmanovic** [comment]
It should be fixed now. Could you please check? I will close the issue.

**Comment by keshavadk** [comment]
Ok [nmanovic](https://github.com/nmanovic), Thank you for the support.
