### ISSUE TITLE
Right click to add issue

### ISSUE THREAD

**Issue by Harsturomai** [opencv/cvat#5278]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Right click in "Review" mode to be able to add an issue. I am confident this functionality was implemented previously.

### Current Behaviour
Required to use left toolbar to select "Open an issue" option.

**Comment by Harsturomai** [comment]
https://user-images.githubusercontent.com/110007098/201294074-83fb2609-ac6c-4469-a18b-b8fdd9d552aa.mp4

I can't replicate, the video is of me right clicking. Right clicking outside opens Chrome Dev Console so my right click input is working. I am working on the develop branch. Any ideas on what else to test?

**Comment by bsekachev** [comment]
You need to use ``right click`` on an object. It does not work on empty area.

**Comment by bsekachev** [comment]
You also can use ``N`` to start a new issue and then click an empty area on the canvas (or select a region)

**Comment by Harsturomai** [comment]
I was sure I was able to right click in an empty area. To indicate, for example, "You didn't draw a box around this target". Using `N` is sufficient. Thank you
