### ISSUE TITLE
Skeleton Track: CVAT for images 1.1 annotation xml has skeleton track which has been switched off

### ISSUE THREAD

**Issue by erichhhhho** [opencv/cvat#5279]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

For CVAT V2.2 release, the exported CVAT for images 1.1 annotation .xml should not have skeleton annotation in the frame that it has been switched off. 

### Current Behaviour
 The .xml exported from the annotation task has skeleton annotation for each frame even in the frame that has been switched off/set the switch outside property as true.

### Possible Solution
 To update the .xml export part for skeleton track annotation.

### Steps to Reproduce (for bugs)

1. Create an annotation task and start one annotation job 
1. Annotate skeleton as track type in frame i
1. Switch outside property as true in frame i+n 
![image](https://user-images.githubusercontent.com/17566212/201294344-ef2f1c1a-af4e-441e-8312-6c7448e33348.png)
1. Export task dataset for this job using CVAT for images 1.1 format

### Context

The file size of the exported xml will be super large since it contains skeleton annotation for each frame (including the frame where the annotation marked as outside). If it is annotated as shape, the issue will not happen.

### Your Environment

- Git hash commit (`git log -1`): 79ce99acc59e8558d9a7589c41050a258dd3c909
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.9
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04.6 LTS
- Code example or link to GitHub repo or gist to reproduce problem: https://github.com/opencv/cvat/tree/release-2.2.0
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
@yasakova-anastasia 

Can you please look at this issue?

**Comment by erichhhhho** [comment]
Hello, may I ask if there is any update on the issue?
