### ISSUE TITLE
Add django allauth openId connect provider when it is merged

### ISSUE THREAD

**Issue by muhmuhhum** [opencv/cvat#5280]
In django-allauth there is an open PR to include openIdConnect provider into allauth https://github.com/pennersr/django-allauth/pull/3165 and then it would be nice to have a solution like in this draft commit in paperless included into cvat https://github.com/paperless-ngx/paperless-ngx/pull/1746. We have a private network in azure so we cant use solutions like Datawiz, so it would be nice to just add our openid connect server into cvat without any custom code

**Comment by nmanovic** [comment]
@muhmuhhum , the PR https://github.com/pennersr/django-allauth/pull/3165 a has been merged. Thank you for the explanation and the request.
