### ISSUE TITLE
JS Error After Importing Annotation Using API

### ISSUE THREAD

**Issue by Tsil-sudo** [opencv/cvat#5281]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)
I imported the annotation using python in the format asked in the API. I am using CVAT local

I imported the annotations using API but the server gave me "TypeError
Cannot read properties of undefined (reading 'id')", The format of the object imported is correct

Below, the error from the server and the JSON object
![Screenshot from 2022-11-11 16-30-07](https://user-images.githubusercontent.com/63632398/201355371-c7877063-d94e-4659-b1f2-d2af7a765f49.png)
![Screenshot from 2022-11-11 16-59-55](https://user-images.githubusercontent.com/63632398/201355554-b58dc172-241c-4261-a5b5-c59a52214977.png)

**Comment by zhiltsov-max** [comment]
Hi, could you please share the annotations so we could reproduce the problem? Images are not required.

**Comment by bsekachev** [comment]
And also, task specifications, thank you in advance.

**Comment by Tsil-sudo** [comment]
Hi, sorry I was out for the weekend, Here are the annotations:

 "shapes": [
        {
            "type": "polyline",
            "occluded": false,
            "outside": false,
            "z_order": 0,
            "rotation": 0.0,
            "points": [
                362.8394840060017,
                668.7667597084508,
                423.48995051983957,
                531.334334869258,
                591.2938517140637,
                667.9517845825845,
                580.8321770552869,
                703.9399454087767
            ],
            "id": 186,
            "frame": 0,
            "label_id": 1,
            "group": 0,
            "source": "manual",
            "attributes": [],
            "elements": []
        },
        {
            "type": "polyline",
            "occluded": false,
            "outside": false,
            "z_order": 0,
            "rotation": 0.0,
            "points": [
                277.8508922826969,
                689.1483610280741,
                388.45194596737844,
                518.5069998224743,
                508.8558554029027,
                698.9183415725637,
                469.10149169955093,
                757.0852526753628
            ],
            "id": 167,
            "frame": 1,
            "label_id": 3,
            "group": 0,
            "source": "manual",
            "attributes": [],
            "elements": []
        },
        {
            "type": "polyline",
            "occluded": false,
            "outside": false,
            "z_order": 0,
            "rotation": 0.0,
            "points": [
                122.87360024107409,
                403.3364611358184,
                195.7734511178539,
                346.9227956163316,
                340.9816837646763,
                536.8913649191209,
                158.83334842029797,
                566.3993952449101
            ],
            "id": 166,
            "frame": 1,
            "label_id": 3,
            "group": 0,
            "source": "manual",
            "attributes": [],
            "elements": []
        },
        {
            "type": "polyline",
            "occluded": false,
            "outside": false,
            "z_order": 0,
            "rotation": 0.0,
            "points": [
                306.49626542549277,
                469.3650676223569,
                395.8032342252837,
                375.0936827988426,
                560.2771554076965,
                442.3669175722837,
                534.9388991435696,
                527.5018686243561
            ],
            "id": 144,
            "frame": 2,
            "label_id": 3,
            "group": 0,
            "source": "manual",
            "attributes": [],
            "elements": []
        },
        {
            "type": "polyline",
            "occluded": false,
            "outside": false,
            "z_order": 0,
            "rotation": 0.0,
            "points": [
                426.33576916912625,
                349.6805783175334,
                495.5928397963766,
                321.23510775400985,
                546.506145771004,
                380.37174392554573,
                452.26994153699667,
                571.8130443824165
            ],
            "id": 142,
            "frame": 2,
            "label_id": 3,
            "group": 0,
            "source": "manual",
            "attributes": [],
            "elements": []
        }
]

**Comment by nmanovic** [comment]
@Tsil-sudo , probably we need to have exact steps how to create a task, and upload annotations. If you can share with us a backup for the task + exact instructions how to reproduce the problem, we will be able to fix it.
