### ISSUE TITLE
cvat-docs-Docker Desktop for Windows-Link could not be downloaded

### ISSUE THREAD

**Issue by monkeycc** [opencv/cvat#5284]
`https://opencv.github.io/cvat/docs/administration/basics/installation/#windows-10
`
Download and install Docker Desktop for Windows.
(https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe).

It should be modified as
`https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe`

**Comment by mdacoca** [comment]
updated link
