### ISSUE TITLE
[Question] Active learning in CVAT

### ISSUE THREAD

**Issue by senovr** [opencv/cvat#5287]
Hello everyone, 
I have a question about active learning loop in CVAT.

Under "active learning", I mean following loop with human-in-the-middle:

1. I have unlabelled dataset.
2. I applying pre-trained model to get some (partially not correct) labels
3. I put model in the backend of CVAT
4. CVAT demonstrates to me images with low confidence.
5. I am correcting the labels.
6. After some number of images has been corrected (for example, each 20 images), model gets re-trained
7. re-trained models generates new labels for the rest of the images.
8. Cycle is repeating.

Is it implemented in some manner or do you have any plans to implement it?

**Comment by nmanovic** [comment]
@senovr , it is not yet implemented but in our nearest plans.

**Comment by nmanovic** [comment]
I will close the issue for now.

**Comment by doantientai** [comment]
Hi @nmanovic, how is it going with the active learning feature?
