### ISSUE TITLE
COCO annotation labels incorrect when downloaded

### ISSUE THREAD

**Issue by jitaxis** [opencv/cvat#5297]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

COCO annotation labels are incorrect when downloaded.
 For example if I have two annotation labels , "visible Orange" and "hidden Orange". Each are applied to every image once each. When downloaded in COCO format I will get a images that only have "visible orange" and images that only have "hidden orange"
 
### Expected Behaviour

When I download in COCO format, it should have the same label to image as for CVAT format.

### Current Behaviour

Annotation label is change when downloaded in COCO format

### Steps to Reproduce (for bugs)

1. Create data set with atleast two labels (mine has two for masks and one skeleton)
2. Download an annotated dataset that has both annotations on the images
3. Upload or look at the annotation .json file to see the mistake

### Context

Greatly as I need my annotations in COCO format for one of my work projects.

### Your Environment

- Git hash commit (git log -1):
commit https://github.com/opencv/cvat/commit/6acab035f2ad2cb9501d814c9c5c38e49bf8e628

- Docker version docker version (e.g. Docker 17.0.05):
Client:
Version: 20.10.12
Server:
Engine:
Version: 20.10.12

- Operating System and version (e.g. Linux, Windows, MacOS):
Linux-20.04

I have attached two images below showing the difference between CVAT annotation upload and COCO annotation
[COCO_annotation_error.zip](https://github.com/opencv/cvat/files/10017249/COCO_annotation_error.zip)

**Comment by nmanovic** [comment]
@jitaxis , I will close the issue. If you can provide more information how to reproduce the issue on our side, feel free to reopen.
