### ISSUE TITLE
Issues where Korean is broken

### ISSUE THREAD

**Issue by taeseok-lomin** [opencv/cvat#5298]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

There is an issue with Korean input when proceeding with text form labels.
Consonants and vowels are entered in order, but consonants and vowels are entered separately.

Expected Behaviour "유형자산마리아가나"
Current Behaviour "유형자산ㅁㅏㄹㅣㅇㅏㄱㅏㄴㅏ"

If I remove the React DOM input from the developer tools, the problem goes away.
It is cumbersome to have to change it every time you try labeling.
If this part can be revise, please revise it.

Please refer to the example image.
Thanks a lot.

### Expected Behaviour

![image](https://user-images.githubusercontent.com/111740026/202081501-1b8ce11a-82b5-4db6-a8be-d5b9b55c70e6.png)

### Current Behaviour

![image](https://user-images.githubusercontent.com/111740026/202081605-66e1a992-95e7-4479-9b1b-c91506d53f16.png)

### Possible Solution

![image](https://user-images.githubusercontent.com/111740026/202081539-e32d5e12-1249-44a0-a62b-edd88bd827e5.png)
![image](https://user-images.githubusercontent.com/111740026/202081623-fc14c1d8-4516-456d-a242-3d37ad3e3e7b.png)

### Steps to Reproduce (for bugs)

1. https://github.com/facebook/react-native/issues/19313
1. https://github.com/facebook/react-native/commit/1a83dc36ce0af33ac7a3c311354fce4bfa5ba1a3
1.
1.

### Context

I am creating data using CVAT.
I solved the problem with developer tools, but it is inconvenient to have to edit every time the page is loaded.
If possible, please correct that part.
thank you

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 20.10.17
- Are you using Docker Swarm or Kubernetes? No I'm not. just use docker-compose
- Operating System and version (e.g. Linux, Windows, MacOS):
Server: Ubuntu20.04
Client: Google Chrome
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bigstones** [comment]
The issue has been resolved with an update in the following link.

https://github.com/opencv/cvat/pull/7340
https://github.com/opencv/cvat/pull/6916

**Comment by bsekachev** [comment]
@bigstones 

Thanks
