### ISSUE TITLE
Error code 500 on F-BRS

### ISSUE THREAD

**Issue by kodecreer** [opencv/cvat#5299]
### My actions before raising this issue
- [* ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ *] Searched [past issues](/issues)

### Expected Behaviour

I try using F BRS on the website and it pulls a 500 error. This isn’t an issue on my intel MacBook in the past.
### Possible Solution

There may be a functionality not working in the chrome version on Mac M1
### Steps to Reproduce (for bugs)

1. Mac M1 using chrome
1. Use F-BRS and convert to masks to be true
1. Click on spot
1.

### Context

Use F-BRS
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Online Chrome on Mac M1.

**Comment by nmanovic** [comment]
@kodecreer , thanks for the report. It is a bug with the deployment of the function on our site.
