### ISSUE TITLE
Erro when trying to run CVAT: Could not check authorization on the server Error: Request failed with status code 502. "Bad Gateway".

### ISSUE THREAD

**Issue by Huxwell** [opencv/cvat#5302]
### My actions before raising this issue
- [yes] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [yes] Searched [past issues](/issues)
I've seen this issue on multiple ocasion, but it seems to be related to multiple separate bugs/missconfigurations, often described as solved / with suggestion to create a separate ticket.

### Expected Behaviour
Normal login.

### Current Behaviour
Error when trying to run CVAT: 
localhost:8080 shows:
Could not check authorization on the server Error: Request failed with status code 502. "Bad Gateway".
http://localhost:8080/auth/login shows:
Could not check authorization on the server Open the Browser Console to get details

### Steps to Reproduce (for bugs)

1. `git clone https://github.com/opencv/cvat`
2. `cd cvat`
3. `docker-compose up -d`
4. `open localhost:8080` in chrome browser

### Context
I used to have a running cvat instance, but a did `git pull` in the repository due to different problem (unable to create task from backup). Then I started to get this error.

I issued 
```
rm -rf cvat
docker-compose down
docker rm -f $(docker ps -a -q)
docker volume rm $(docker volume ls -q)
```
before cloning new CVAT to make sure I have a clean version

### Your Environment

- Git hash commit (`git log -1`):
```
Author: Anastasia Yasakova <yasakova_anastasiya@mail.ru>
Date:   Wed Nov 16 13:07:59 2022 +0200

    Fix: visibility and ignored information fail to be loaded (MOT dataset format) (#5270)
```
- Docker version `docker version` (e.g. Docker 17.0.05):
`20.10.18`
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 20.04.5 LTS
- Other diagnostic information / logs (I've used `docker logs cvat_server` because `cvat` is not there):
https://pastebin.com/UsMu0gxQ
My chrome console shows:
https://pastebin.com/mzPTRsrh

**Comment by nmanovic** [comment]
@Huxwell , let's try to investigate. CVAT server needs time to start up. For many seconds in the beginning it runs some service code.  For example, prepare the database. While it is in the state, it returns 502 HTTP error. After 30 seconds or so, you should be able to authenticate yourself.

Could you please run `docker logs cvat_server` and post output as a file here? I believe together we will find an answer.

And thanks for the report. We will try to make CVAT more stable in the next release.

**Comment by Huxwell** [comment]
[cvat_docker_logs.txt](https://github.com/opencv/cvat/files/10029652/cvat_docker_logs.txt)
The error appears even without me doing anything - just entering localhost:8080 is enough.

Waiting for a few minutes unfortunatelly doesn't help - when I try to login, I get another similar error.
![image](https://user-images.githubusercontent.com/9086268/202403670-41823ec2-bf2e-4e78-a20d-b3b3def8d144.png)

**Comment by azhavoro** [comment]
@Huxwell Hi, seems you are using old cvat images that you have locally, try to update with `docker compose pull` or build yourself with `docker compose -f docker-compose.yml -f docker-compose.dev.yml build`

**Comment by Huxwell** [comment]
After `docker-compose pull` I am able to sucessfully login!
I am supprised that following commands didn't trigger pulling new images before:
```
docker rm -f $(docker ps -a -q)
docker volume rm $(docker volume ls -q)
```
Thanks for helping me out!

**Comment by JeeBoom** [comment]
i have same question ，but when i run docker-compose pull ， the progress can't run
i use mac apple m2 ，please help me
<img width="995" alt="image" src="https://github.com/opencv/cvat/assets/24579053/07b9121f-c7f4-45a4-ac83-2091be458774">
![image](https://github.com/opencv/cvat/assets/24579053/8a39b103-86b6-4cab-99e8-9963f49164b6)
