### ISSUE TITLE
Integrate pip-tools for dependency management

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#5310]
pip dependency resolver was taking extremely long due to complex version resolution prior to this change (>6 hours on CI). This commit introduces version pinning with pip-tools. A wrapper script to update the pinned versions when dependencies are added, or when upgrades are needed, is provided.

**Comment by kirill-sizov** [comment]
@nmanovic Do you have link on CI-workflow that takes >6 hours?

**Comment by nmanovic** [comment]
@kirill-sizov , I have copied the message from a pull request of Nico G. and his PR. I don't have the link.
