### ISSUE TITLE
Can't run nuclio docker containers for automatic annotation purpose

### ISSUE THREAD

**Issue by milanziuziakowski** [opencv/cvat#5317]
Hello, 

My goal is to run locally CVAT to annotate images. For this purpose I'd like to use Semi-Automation tools

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Followed the instruction: https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/ . Searched for possible solutions but couldn't resolve it with what I read.

### Expected Behaviour

The docker containers should have status "running" and its function should complete

### Current Behaviour
All the time I'm seeing the same type of error, which blocks me from completing the container run:
(E) Can't find Python exe {"error": "exec: \"/opt/nuclio/common/openvino/python3\": stat /opt/nuclio/common/openvino/python3: no such file or directory"}

In the result the containers are stuck on status "building" or "error" on WSL terminal output and "Restarting (1)" on Windows Docker Desktop App. 
The finish of the output of command: 
~/cvat/serverless$ ./deploy_cpu.sh openvino/dextr/

is following:

22.11.18 16:10:22.064 sor.http.w1.python.logger (E) Can't find Python exe {"error": "exec: \"/opt/nuclio/common/openvino/python3\": stat /opt/nuclio/common/openvino/python3: no such file or directory"}

Error - exec: "/opt/nuclio/common/openvino/python3": stat /opt/nuclio/common/openvino/python3: no such file or directory
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239

Call stack:
Can't run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
Failed to run wrapper
    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:106
Failed to start runtime
    /nuclio/pkg/processor/worker/factory.go:100
Failed to create worker
    /nuclio/pkg/processor/worker/factory.go:119
Failed to create workers
    /nuclio/pkg/processor/worker/factory.go:129

    /nuclio/pkg/platform/local/platform.go:1168
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:197

Status of the nuclio containers: 
  NAMESPACE |                          NAME                          | PROJECT |  STATE   | REPLICAS
  nuclio    | openvino-dextr                                         | cvat    | error    | 1/1
  nuclio    | openvino-mask-rcnn-inception-resnet-v2-atrous-coco     | cvat    | building | 1/1
  nuclio    | openvino-omz-face-detection-0205                       | cvat    | building | 1/1
  nuclio    | openvino-omz-intel-person-reidentification-retail-0300 | cvat    | building | 1/1
  nuclio    | openvino-omz-intel-text-detection-0004                 | cvat    | error    | 1/1
  nuclio    | openvino-omz-public-faster_rcnn_inception-v2-coco      | cvat    | error    | 1/1
  nuclio    | openvino-omz-public-yolo-v3-tf                         | cvat    | building | 1/1
  nuclio    | openvino-omz-semantic-segmentation-adas-0001           | cvat    | error    | 1/1
  nuclio    | tf-matterport-mask-rcnn                                | cvat    | error    | 1/1

Whole output: 
[deploy_cpu_output.txt](https://github.com/opencv/cvat/files/10043023/deploy_cpu_output.txt)

### Your Environment

OS Windows 10 with containers run on Ubuntu WSL (ver 2004.2020.424.0), docker 20.10.21
nuctl version the same as on docs: [1.8.14]

**Comment by nmanovic** [comment]
@milanziuziakowski , I have tried that on my mac with the develop branch. Instructions work pretty well for me. I don't have a PC with Windows. Could you please tell me which CVAT version you use?

Unfortunately, problems with nuclio is hard to debug remotely. You need to ask our community. Please provide more details, I will try to help.

**Comment by milanziuziakowski** [comment]
The CVAT version that I used was the most recent one from github, so it's probably 2.2.0 as I can see in CHANGELOG. Not sure if it's correct way to check the version.

Thanks for the answer.

**Comment by milanziuziakowski** [comment]
Done, started whole process from begin. This time cloned the repo in WSL with command instead of download and extract repo in .zip format as previously. Done as the instruction says and this time nuclio function completed successfully. AI Tools available in web app
