### ISSUE TITLE
Hi, I am trying to upload images and it is a large size of 7.5GB. Please help me

### ISSUE THREAD

**Issue by Jefjaica** [opencv/cvat#5323]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by nmanovic** [comment]
@Jefjaica , where do you try to upload images and how we can help you? Please ask questions in one of channels: https://github.com/opencv/cvat#where-to-ask-questions

**Comment by Jefjaica** [comment]
Hi Nikita,

I am trying to create a task for annotation. But when I try to upload
images, I get an error message because the file is 7.5GB.
