### ISSUE TITLE
Automatic annotation for landmark/pose prediction

### ISSUE THREAD

**Issue by sangdv** [opencv/cvat#5324]
Hi, we want to integrate our landmark/pose prediction model into CVAT for automatically suggesting keypoints. But it seems that CVAT allows integrating only interactors, detectors and trackers, which are not suitable for the landmark prediction task. Could you please guide me on how to do that?

**Comment by martin0258** [comment]
@sangdv As far as I know, it is currently not officially supported. However, if you want to implement it by modifying the source code, you may follow [ref](https://github.com/opencv/cvat/issues/5177) as a starting point.

**Comment by schliffen** [comment]
Pose (or point) auto annotation is very critic. It would be appreciated if you add this feature too.

**Comment by hardikdava** [comment]
Hello, I was able to get it working for landmark as type of "points". But I am wondering how to work with `type=skeleton` with serverless functions. @nmanovic where can I find more information about return type of `skeleton` for serverless function response?

**Comment by KTXKIKI** [comment]
> 您好，我能够让它作为“点”类型为地标工作。但是我想知道如何使用无服务器函数。在哪里可以找到有关无服务器函数响应的返回类型的详细信息？`type=skeleton``skeleton`

Now that we support YOLOv8, we can proceed with it
