### ISSUE TITLE
Support rotated bounding boxes in automatic annotation

### ISSUE THREAD

**Issue by hyfung** [opencv/cvat#5325]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

We are using CVAT's automatic annotation tool Nuclio

We wrote a custom YoloV5 detector with our own model

YoloV5 supports rotated rectangle detection in the following format `[x, y, w, h, theta]` where theta is the rotation angle

CVAT automatic annotation also supports attributes returned from Nuclio functions, as seen in this issue [5306](https://github.com/opencv/cvat/issues/5306)

After inspecting the source code, `rotation` is considered as `attributes` by CVAT too but adding this to the response payload did not help `'attributes': {'name': 'rotation', 'input_type': 'number', 'value': angle}` where `angle` is a number, returned by the YoloV5 detector

Directly returning `'points': [x, y, w, h, theta]` yields the error "Got 2.5 points"

### Current Behaviour
Rotation returned from Lambda function is not used by CVAT

### Possible Solution
Allow CVAT to also accept a `rotation` parameter from the Lambda function and make use of it in the handler, adding `rotation` in the `attributes` field of an annotation

**Comment by heurainbow** [comment]
any progress here?

**Comment by bsekachev** [comment]
Implemented in #6961
