### ISSUE TITLE
CVAT 2.2.0 fails meta?org= with rootless docker

### ISSUE THREAD

**Issue by dnns92** [opencv/cvat#5329]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

cvat 2.2.0 returns 404 when loading any job. In the browser console, I get a 404 on "meta?org=". I checked that it is not a permission issue in the container I can see, edit, etc. all files.

Interestingly enough, this 
~~~bash
<ip>:<port>/api/jobs/<job-id>/data/meta?org=  # this does not exist
<ip>:<port>/api/jobs/<job-id>?meta?org=   # this does exist
~~~

Is there a deprecated API called somewhere?

I'm on version tags/v2.2.0

RL: <redacted>/api/jobs/7/data/meta?org=
Request Method: GET
Status Code: 404 Not Found
Remote Address: <redacted>
...

![image](https://user-images.githubusercontent.com/39763670/203020490-94ab4428-6897-401d-8e02-ce3244a89c2d.png)
All of these return a 200 code instead of a 404 like meta does.

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by kirill-sizov** [comment]
Hi @dnns92 does the job with the `<job-id>` id belong to the any organization?

**Comment by dnns92** [comment]
I upgraded CVAT 2.1.0 to CVAT 2.2.0 and did not change any cvat_files related data.

The job (like all other I tested, do not belong to any organization)
![image](https://user-images.githubusercontent.com/39763670/204557591-1894aaf4-4987-478d-8d3e-ffda6ce20b5a.png)

**Comment by nmanovic** [comment]
@dnns92 , please try release v2.3.0. If you can reproduce the issue, we will investigate. For now I will close the issue.
