### ISSUE TITLE
Could not find any dockerfile for cvat_ui

### ISSUE THREAD

**Issue by mindgarage-shan** [opencv/cvat#5330]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

I generally want to add my new GUI components. For that I need to rebuild the docker image. I couldn't find any dockerfile to do so. Or is there any other way of extending the GUI of CVAT.

There is a way to rebuild mentioned in the following issue but it does not work.

https://github.com/opencv/cvat/issues/4933

**Comment by kirill-sizov** [comment]
Hi @mindgarage-shan, for cvat/ui image we Dockerfile.ui that you can find in our root directory: https://github.com/opencv/cvat/blob/6b747b458a478b062795e65bc3b1efcfb60dc944/Dockerfile.ui

**Comment by mindgarage-shan** [comment]
Thanks for the answer; the mentioned docker runs on port 8081; I am not sure; shall we change the port internally somewhere? 
The main question, however, is, there are trackers, detectors, and interactions in the magic stick. I want to add one more there.
I did it. But when I rebuild, it downloads the cvat_ui image with the same hash as the original, and I don't see any change.

**Comment by kirill-sizov** [comment]
To build your local version of cvat/ui image add `docker-compose.dev.yml` when you runs cvat instance with docker-compose

**Comment by mindgarage-shan** [comment]
Hi @kirill-sizov, I provide all the details as follows

### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)


I am trying to create a new tab for the automatic labeling function by modifying cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx and cvat-core/src/enums.ts.
I run the following command, but nothing change in the UI:

1. docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
2. CVAT_VERSION=dev docker-compose pull


### Expected Behaviour

When hover to the magic wand, it should have a new tab "Dummy Tab" next to Tracker tab.

### Current Behaviour

It only appears default models.(Interactors, Detectors and Trackers)

### Possible Solution


### Steps to Reproduce (for bugs)

1. Add code to cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx 
   -> In renderPopoverContent(), add
   <Tabs.TabPane key='dummy_tab' tab='DummyModels'>
        {this.renderLabelBlock()}
        {this.renderVehicleBlock()}
   </Tabs.TabPane>
2. Add code to cvat-core/src/enums.ts.
    export enum ModelType {
      DETECTOR = 'detector',
      INTERACTOR = 'interactor',
      TRACKER = 'tracker',
      DUMMY_MODEL = 'dummy_model',
    }
3. docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
4. CVAT_VERSION=dev docker-compose pull

### Context

The goal is to create a new automatic labeling function from other open-source models.

### Your Environment

- Git hash commit (`git log -1`): 7706eee504e73d538dd9d7ff76e7b9ae6aaaf7cb
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.21
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): 20.04.1-Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
