### ISSUE TITLE
Hide a bounding box around a skeleton if it isn't selected

### ISSUE THREAD

**Issue by ArMaxik** [opencv/cvat#5332]
### Expected Behaviour

Thank you for skeleton annotation feature!
During skeleton annotation bounding box is stiched to the points. It is impossible to place both of them accurate.

### Current Behaviour
For example, I placed a skeleton. The bounding box is slightly big:
![Skeleton1](https://user-images.githubusercontent.com/7460322/203066206-bc4d7b13-067f-4d74-855e-6347a79e075b.png)

If i try to scale the boundging box, the skeleton will move proportionally:
![Skeleton2](https://user-images.githubusercontent.com/7460322/203066375-524d3c5e-df37-4605-8820-01aa703f59e3.png)

### Possible Solution

I think it will be very helpful to add an button on bounding box object, that turning on\off connection to the points. Or even turn it off automatically when you are reshaping the box.

### Context

With current behavior the use of skeleton annotation feature is inconvenient.

**Comment by bsekachev** [comment]
@ArMaxik  The only reason why this bounding box exists is to be able resize the whole skeleton proportionally :)
So, if it is inconvenient for you, maybe do you want not to see the bounding box at all?

**Comment by ArMaxik** [comment]
@bsekachev The annotation with both bounding boxes and skeletons is crutual for some computer vision algorithms. It's easier to have them in one task rather than in two different. For example, for top down methods I will train object detection model on accurate bboxes and after I will train keypoints detection model on object crops. Some methods, like YOLO-pose, are using bbox and skeletons simultaniously while trainnig.

Also well known COCO dataset has both types of annotations, but i can't import it into cvat without loosing bounding boxes.

So, that's why i think CVAT should be able to handle both types of annotations under one task. Bbox should't be dependet on keypoints coordinates.

**Comment by nmanovic** [comment]
@ArMaxik , @bsekachev , bounding box around a skeleton should be used only for manipulation with a skeleton. We should not show it by default. As I can see, it can confuse people.

Let's just hide the bounding box around a skeleton if it isn't selected.

**Comment by ArMaxik** [comment]
> Let's just hide the bounding box around a skeleton if it isn't selected.

@nmanovic It will be great!

But there is still a confusing part of the skeleton annotation. When exporting to a format that allows instances with points and bboxes (like COCO keypoints), bbox is automatically created around the skeleton and doesn't represent the whole object.

I sugest considering groups formed by the group instrument. If there is one skeleton and one bbox in one group, they will represent one instance during export.
