### ISSUE TITLE
Can't get dataset of specific task via API

### ISSUE THREAD

**Issue by erikadicesare** [opencv/cvat#5343]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

I'm trying to do a get request to export the dataset of a specific task. 
My code is as follow (i'm using Flask):
`requests.get('{}/tasks/{}/dataset'.format(url_cvat, id), params={"format":"coco"}, headers={"Authorization": f'Token {keyLogin}'})`
I think the problem is `params={"format":"coco"}` because what i got is the follow error **'Unknown format specified for the request'**

Can someone help me?

**Comment by Marishka17** [comment]
Hi, @erikadicesare 
You can find available formats by request `../api/server/annotation/formats`
Change `coco` to `COCO 1.0`

**Comment by erikadicesare** [comment]
> 

Hi, thank you. 
Now I also add some other parameters inside `params`. So the request is like this:
`requests.get('{}/tasks/{}/dataset'.format(url_cvat, id), params={"action" : "download", "filename":"prova", "format":"CVAT for images 1.1", "location":"local"}, headers={"Authorization": f'Token {keyLogin}'})`
But the download doesn't start (I got <Response [200]>)

**Comment by zhiltsov-max** [comment]
Hi, please check [these tests](https://github.com/opencv/cvat/blob/develop/tests/python/rest_api/test_tasks.py#L396-L403).
