### ISSUE TITLE
new to CVAT. drawing polygon

### ISSUE THREAD

**Issue by newmluser** [opencv/cvat#535]
I have loaded a picture.
kept--> Annotation-->Polygon.

pressed N (Captial N)
I am not able to get the option to mark.
I tried left click as mentioned in https://www.youtube.com/watch?v=XTwfXDh4clI
and saw this also...
https://github.com/opencv/cvat/blob/master/cvat/apps/documentation/user_guide.md#annotation-with-polygons

am I missing anything please ..when I press left the image is also moving

**Comment by nmanovic** [comment]
@newmluser , please in chrome browser click F12 and see "console". Let's know if you see any errors.

**Comment by bsekachev** [comment]
Resolved on gitter
