### ISSUE TITLE
new CVAT set up in development environemnt , not showing created projects and tasks.

### ISSUE THREAD

**Issue by keshavadk** [opencv/cvat#5350]
I took the latest pull of CVAT and set up in my local machine using development environment. 
The servers are up , but when i create projects and tasks:
1. Projects and tasks not visible on UI  but it is visible in database and also admin page.

Can i know how can we fix this?
![issue](https://user-images.githubusercontent.com/16021947/203696637-0b06d42a-d587-4213-8a2e-a677535aaf05.JPG)

![admin](https://user-images.githubusercontent.com/16021947/203696372-e1b48d25-af7a-4875-a4bd-ff8dcca9074f.JPG)

**Comment by zhiltsov-max** [comment]
Hi, could you please add the error log from the browser console? Please make sure you've started the OPA container as described [here](https://opencv.github.io/cvat/docs/contributing/development-environment/):

```
docker run -d --rm --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.34.2-rootless \
 run --server --set=decision_logs.console=true --set=services.cvat.url=http://host.docker.internal:7000 \
 --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules
```

**Comment by nmanovic** [comment]
@keshavadk , most probably the issue is on your side. If you can provide steps to reproduce the problem, feel free to reopen the issue.

**Comment by keshavadk** [comment]
ok [nmanovic](https://github.com/nmanovic). Thank you.
