### ISSUE TITLE
How to label a specified type of picture

### ISSUE THREAD

**Issue by YuanNBB** [opencv/cvat#5358]
Now, i have a large number of images, including IR images and color images in same folder.
ex: 1_ir.png, 1_color.png; 2_ir.png, 2_color.png.
But I just want to label the color picture. How can I filter it when i use "connected file share" to add images;
BTW, in my project, i have request that it can display the order of label point when draw points;
example, first point is eyes, second point is nose, third point is mouth...
because i need to verify these points are correct.
Thanks!
![无标题](https://user-images.githubusercontent.com/119041739/203957740-261c2bce-a4b3-4a1e-8eb1-71dde3b9cc58.png)

**Comment by nmanovic** [comment]
@YuanNBB , it isn't well implemented in CVAT at the moment. You need to select all *_color.png images manually. There are many ways how to fix it. I will close the issue because most probably our team will not have time to implement the feature in the nearest future. Feel free to contribute!
