### ISSUE TITLE
CVAT deployment on Kubernetes with Helm - 404 page not found

### ISSUE THREAD

**Issue by marekpawlowski** [opencv/cvat#5359]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Description
Hi, 
I try to run cvat with using helm-chart and instruction plased in documentatiom but I have problem. When I try to open CVAT via web browser (aws elb treafik service adres) I get 404 on that page. I don't know where can be aproblem becasue in configuration of services allowed hosts is equals "*". I try to run it with default configuration without any overited variables.
 

### Expected Behaviour
Access to service.

### Current Behaviour
404 page not found

**Comment by azhavoro** [comment]
@marekpawlowski Hi you have to override host value here https://github.com/opencv/cvat/blob/develop/helm-chart/values.yaml#L283
like this:
```shell
helm upgrade -n default cvat -i --create-namespace helm-chart -f helm-chart/values.yaml -f helm-chart/values.override.yaml --set ingress.hosts[0].host=YOUR_DOMAIN
```
