### ISSUE TITLE
Permission denied during docker-compose down

### ISSUE THREAD

**Issue by yustiks** [opencv/cvat#536]
Hello, guys! Thank you for the work you made!
I try to run the docker, and it doesn't work.
I follow all the commands in the installation guide (https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md) and open the google chrome, but I don't see the CVAT environment. What can be a reason?
Thank You!

**Comment by bsekachev** [comment]
@yustiks 
Hello, what do you see? 
Could you please attach an output of  the command ```docker logs cvat```?

**Comment by yustiks** [comment]
@bsekachev  
Server URL         : http://localhost:8080/
Server Root        : /tmp/mod_wsgi-localhost:8080:1000
Server Conf        : /tmp/mod_wsgi-localhost:8080:1000/httpd.conf
Error Log File     : /dev/stderr (INFO)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : C.UTF-8

2019-07-01 06:40:48,112 DEBG 'runserver' stdout output:
httpd (pid 12) already running

2019-07-01 06:40:48,112 DEBG fd 25 closed, stopped monitoring <POutputDispatcher at 140277958244184 for <Subprocess at 140277958566040 with name runserver in state RUNNING> (stderr)>
2019-07-01 06:40:48,112 DEBG fd 21 closed, stopped monitoring <POutputDispatcher at 140277958243896 for <Subprocess at 140277958566040 with name runserver in state RUNNING> (stdout)>
2019-07-01 06:40:48,113 INFO exited: runserver (exit status 0; expected)
2019-07-01 06:40:48,113 DEBG received SIGCLD indicating a child quit

**Comment by bsekachev** [comment]
@yustiks 
What about ```docker ps```?

**Comment by yustiks** [comment]
@bsekachev 
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                              NAMES
72e4e34f47ce        cvat                   "/usr/bin/supervisord"   9 days ago          Up 2 hours          0.0.0.0:8080->8080/tcp, 8443/tcp   cvat
3019da9729ea        postgres:10.3-alpine   "docker-entrypoint.s…"   9 days ago          Up 2 hours          5432/tcp                           cvat_db
a89878d32b60        redis:4.0.5-alpine     "docker-entrypoint.s…"   9 days ago          Up 2 hours          6379/tcp                           cvat_redis

**Comment by bsekachev** [comment]
@yustiks 
Try the followings:
```
docker-compose <build_args> down
docker-compose <build_args> up -d
```
Where <build_args> are docker-compose files which have been used to built. 
For example if you had used openvino:
```
docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml down
docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml up -d
```

**Comment by yustiks** [comment]
@bsekachev thank you for advice, I have already tried. 
sudo docker-compose -f docker-compose.yml -f docker-compose.yml down
Stopping cvat       ... error
Stopping cvat_db    ... error
Stopping cvat_redis ... error

ERROR: for cvat  cannot stop container: 72e4e34f47ced80d87aff83378a51928e85e09f4840dd1698eeadb71bf2752f4: Cannot kill container 72e4e34f47ced80d87aff83378a51928e85e09f4840dd1698eeadb71bf2752f4: unknown error after kill: docker-runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied"
: unknown
Removing network cvat_default
ERROR: network cvat_default id 5cc7fc974f08e756bdc671e4f2e05e84085a23abd5fa82948c3a512b338abb66 has active endpoints

**Comment by bsekachev** [comment]
@yustiks 
Why have you chosen docker-compose.yml twice?

**Comment by yustiks** [comment]
@bsekachev same problem with 
```
sudo docker-compose -f docker-compose.yml down
```

**Comment by bsekachev** [comment]
@yustiks 
What command have you used to built?

**Comment by yustiks** [comment]
@bsekachev 
docker-compose up -d

**Comment by bsekachev** [comment]
@yustiks 
I see, that docker can't kill cvat container beacuse of permission denied 
```
ERROR: for cvat  cannot stop container: 72e4e34f47ced80d87aff83378a51928e85e09f4840dd1698eeadb71bf2752f4: Cannot kill container 72e4e34f47ced80d87aff83378a51928e85e09f4840dd1698eeadb71bf2752f4: unknown error after kill: docker-runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied"
```
Similar issue is here: https://github.com/moby/moby/issues/38478

**Comment by bsekachev** [comment]
@yustiks 
Have you managed to with the issue?

**Comment by yustiks** [comment]
@bsekachev I tried the method You send, still have the same issue. I can't install in my laptop this docker

**Comment by bsekachev** [comment]
@yustiks 
It seems to be a known docker issue. 
Try the followings to remove (if you do not have any other built containers)
```
sudo apt-get purge --auto-remove apparmor
sudo service docker restart
docker system prune --all --volumes
```

Maybe you found a useful information here: https://forums.docker.com/t/can-not-stop-docker-container-permission-denied-error/41142/3
Or here: https://stackoverflow.com/questions/47223280/docker-containers-can-not-be-stopped-or-removed-permission-denied-error

**Comment by nmanovic** [comment]
@yustiks , I will close the issue. It seems we can do nothing with that. Please try commands which Boris posted. If you think that it is a bug in CVAT don't hesitate to reopen the issue.
