### ISSUE TITLE
It is impossible to rotate the frame at a large approximation

### ISSUE THREAD

**Issue by AndreanoCuritello** [opencv/cvat#5363]
I am trying to rotate the frame of object 1, but the mouse focus does not hold to the white circle until I remove object 2.
![image](https://user-images.githubusercontent.com/13471862/204090636-c3e3bc72-c6f3-414f-ab46-4b2d4a88b347.png)

**Comment by bsekachev** [comment]
@AndreanoCuritello 

Use ``ctrl`` hold to freeze active object.
