### ISSUE TITLE
Question: how to restrict dataset export to admin users only? 

### ISSUE THREAD

**Issue by mojcris** [opencv/cvat#5367]
In the following cases the user is able to export annotations and/or datasets: 
1. If you add a new user and give them user/annotator permissions from Django admin page and then assign them a whole task or job, they can export annotations and/or datasets
2. If you give them the supervisor role in the organization, they are able to export annotations and/or datasets

Is it possible to restrict annotation and dataset export to only admin users?

**Comment by mojcris** [comment]
Thanks. It worked.

**Comment by xXxTheUserxXx** [comment]
> 



> Hi, please check this file: https://github.com/opencv/cvat/blob/develop/cvat/apps/iam/rules/tasks.rego#L197-L218

Should this also work to prevent "Export job" when the job is assigned to the roll "worker"? Thanks in advance.

**Comment by zhiltsov-max** [comment]
@xXxTheUserxXx, depending on what is needed, you should change restrictions in [cvat/apps/iam/rules/jobs.rego](https://github.com/opencv/cvat/blob/61adec55d1eadc4bb37206a7e9f956f057f57928/cvat/apps/iam/rules/jobs.rego#L142-L159) (for jobs) or in [cvat/apps/iam/rules/tasks.rego](https://github.com/opencv/cvat/blob/61adec55d1eadc4bb37206a7e9f956f057f57928/cvat/apps/iam/rules/tasks.rego#L193-L214) (for tasks). Please look for `import_*` and `export_*` scopes. You will need to rebuild and restart the server for the changes to apply.

**Comment by zhiltsov-max** [comment]
@xXxTheUserxXx, looks right. Have you rebuild and restarted the server?

**Comment by xXxTheUserxXx** [comment]
@zhiltsov-max , 

to rebuild and restarted the server I did:

docker-compose down
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build 
export CVAT_HOST=XXX.XXX.XXX.XXX
docker-compose up -d

Is there a way to completely disable the "Export Job" button? 
Unfortunately this is a real problem for me.

**Comment by zhiltsov-max** [comment]
> Is there a way to completely disable the "Export Job" button?

You can change [this function](https://github.com/opencv/cvat/blob/1c753d5ed47e283613e9d9d1247f51afa9903369/cvat/apps/engine/views.py#L1498) on the server and add some code like `return Response(status=status.HTTP_400_BAD_REQUEST)`. You may also want to modify [this function](https://github.com/opencv/cvat/blob/1c753d5ed47e283613e9d9d1247f51afa9903369/cvat/apps/engine/views.py#L1401) the same way.

**Comment by xXxTheUserxXx** [comment]
@zhiltsov-max Thank you. 

"return Response(status=status.HTTP_400_BAD_REQUEST)" solved my problem.

**Comment by azadehashouri** [comment]
@xXxTheUserxXx 
Hello,
Could you help me how you add "return Response(status=status.HTTP_400_BAD_REQUEST)" to the CVAT codes?

I changed `cvat/cvat/apps/engine/rules/jobs.rego` but still worker users can export tasks.

Thank you in advance.

**Comment by anoop-dv** [comment]
@azadehashouri 
Hi, 
I'm also having this issue. Did you find a fix?

**Comment by azadehashouri** [comment]
@anoop-d

Hi,
Yes. To restrict dataset exports to admin users you must comment line 163 and line 164 of `cvat/apps/engine/rules/jobs.rego`.

Moreover, you must comment same commands related to worker role in `/cvat/cvat/apps/engine/rules/tasks.rego` which are started from line 176.

After that run following commands to restrart containers of CVAT:

```
sudo docker compose -f docker-compose.yml -f docker-compose.dev.yml down


sudo docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build --force-recreate cvat_server

sudo -E docker compose up -d
```

**Comment by anoop-dv** [comment]
@azadehashouri 

Hi,
Thanks for your response. I implemented the code changes you provided, and everything is now functioning.
