### ISSUE TITLE
size of the downloaded labels dont match with the original in cvat

### ISSUE THREAD

**Issue by Rodrigoalvort** [opencv/cvat#5368]
Good morning.

 I'm having a problem when I download the labels generated over CVAT in YOLO format.  the result labels are scaled and doest match how they look over the application. i take a look over the label's transformation to see if I processed them wrong before plotting them.  this issue occurs in a few images overall, almost all of them show the correct label size and position. I send you an example of the labels and the images and the code I'm using to plot them.

`
import cv2
import matplotlib.pyplot as plt
def determine_label_kitti(label, labels):
	"""
	Definition: Converts label index to label from label set
	Parameters: label - label from file
				labels - list of labels
	Returns: label corresponding to index in yolo label
	"""
	return str(labels[int(label)])

def parse_labels_kitti(label_file, img_width, img_height):
	"""
	Definition: Parsers label file to extract label and bounding box
		coordinates. Converts (x, y, width, height) YOLO format to
		(x1, y1, x2, y2) KITTI format.
	Parameters: label_file - file with YOLO label(s) inside
				labels - list of labels in dataset
				img_width - width of input image
				img_height - height of input image
	Returns: all_labels - contains a list of labels for objects in image
			 all_coords - contains a list of coordinates for objects in image
	"""
	lfile = open(label_file)
	coords = []
	all_coords = []
	all_labels = []
	for line in lfile:
		l = line.split(" ")
		coords = list(map(float, list(map(float, l[1:5]))))
		x1 = float(img_width) * (2.0 * float(coords[0]) - float(coords[2])) / 2.0
		y1 = float(img_height) * (2.0 * float(coords[1]) - float(coords[3])) / 2.0
		x2 = float(img_width) * (2.0 * float(coords[0]) + float(coords[2])) / 2.0
		y2 = float(img_height) * (2.0 * float(coords[1]) + float(coords[3])) / 2.0
		tmp = [x1, y1, x2, y2]
		all_coords.append(list(map(int, tmp)))
	lfile.close()
	return all_coords

im = cv2.imread("/content/upload_00009249.jpg")
height, width,_ = im.shape
result = parse_labels_kitti("/content/upload_00009249.txt",width,height)

print(height,width)
print(result)
for x1, y1, x2, y2 in result:
  cv2.rectangle(im,(x1,y1) , (x2,y2), (0, 0, 255), thickness= 3, lineType=cv2.LINE_8) 

plt.figure(figsize=(15,15))
plt.imshow(im)
`
 
[upload_00009249.txt](https://github.com/opencv/cvat/files/10104447/upload_00009249.txt)
![upload_00009249](https://user-images.githubusercontent.com/41381387/204299452-bc275609-6067-488c-981c-ae4c88e42282.jpg)

the result of the code and the input examples is shown in the image.

![image](https://user-images.githubusercontent.com/41381387/204299560-f3c7e795-799a-4d4a-a2c7-40566dfcc03d.png)

the only anomalous behavior is the canvas of CVAT  is bigger than the image that is been labeled.

This issue in the data is giving noise to the model in the training process.  I have cvat running on premise over an ec2 instances since the start of the year. the OS is ubuntu, and run cvat  running the dockercompose

**Comment by yasakova-anastasia** [comment]
Hi, @Rodrigoalvort

Could you provide more information on how to reproduce this issue please? I created a task, added some bounding boxes, exported the annotations in YOLO format, and uploaded them again. I was unable to reproduce this issue. Could you describe the issue pipeline in detail please?
