### ISSUE TITLE
Question: data privacy

### ISSUE THREAD

**Issue by ntatsisk** [opencv/cvat#537]
Hello, I am new to CVAT and I have a question. I am planning to annotate medical data and I have not understood if the images are actually uploaded to a server or they stay locally. I am worried about the privacy of the data. Thanks.

**Comment by bsekachev** [comment]
@ntatsisk 
Your data will be uploaded to your server (where you will have built CVAT), NOT to the Internet. 
In fact if you will have built CVAT on your local PC, data will stay locally.

**Comment by ntatsisk** [comment]
OK I got it! Thanks for the fast response!

**Comment by aleph17** [comment]
So, the images uploaded to the server will not be accessible to anyone else. And I don't need to worry about the privacy side of the data?
