### ISSUE TITLE
CVAT stopped working - a padding to disable MSIE

### ISSUE THREAD

**Issue by davodogster** [opencv/cvat#5375]
### My actions before raising this issue
- [ yes] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ yes] Searched [past issues](/issues)

### Expected Behaviour
Able to login to CVAT

### Current Behaviour
All of our users were logged out of our CVAT server and cannot get back in. @nmanovic please let me know if you guys can help.
We are running it on a local server where multiple machines on our network can access it at 10.10.16.58:8080.

![image](https://user-images.githubusercontent.com/46079516/204693756-91beadd4-7370-4576-94c4-fe9540a87af9.png)

Environment
linux 
docker 20.10.21
![image](https://user-images.githubusercontent.com/46079516/204693940-0ddc48bb-1090-48a8-9f5e-027e411fcf73.png)
![image](https://user-images.githubusercontent.com/46079516/204920543-f22293b6-585b-4660-87f8-cb2a524502d7.png)
![image](https://user-images.githubusercontent.com/46079516/204922226-8e701cbc-b3b0-40fc-afaa-9503f37e21e6.png)

![image](https://user-images.githubusercontent.com/46079516/204694227-5cbb9fc7-a3b7-48b9-8088-19a9aa07f405.png)

**Some output from docker logs cvat**

![image](https://user-images.githubusercontent.com/46079516/204709183-8cb45e91-6367-46ef-9746-e3c1c602fc72.png)

![image](https://user-images.githubusercontent.com/46079516/204709276-e3132891-a06b-404f-bfdb-893690e6350b.png)

Edit - the orginal version of CVAT we were using was from 2-3 years ago but we have been succeffuly upgrading it over time. Although, after the last upgrade I think "Could not check authorization on the server" was a common error for us, but I think we were still able to login despite that error in the past. The main error might be related to 405 - Method not allowed.

**Comment by zhiltsov-max** [comment]
@azhavoro , could you please check?

**Comment by davodogster** [comment]
@zhiltsov-max Thank - please let me know if you can help @azhavoro I'm not using cvat.org

**Comment by davodogster** [comment]
@zhiltsov-max @azhavoro Hi guys, we don't know exactly what was causing the issue but we were able to solve it by adding -443:443 in the dockerfile. It is the only thing that worked for us. Now all users can login again. 
![image](https://user-images.githubusercontent.com/46079516/205159701-790e5990-35c7-4d5b-ad2c-f08a18974071.png)

Thanks, Sam

**Comment by nmanovic** [comment]
@davodogster , I will close the issue. It looks like the problem was resolved.
