### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by erikadicesare** [opencv/cvat#5378]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I'm trying to attach images to an empty task using the api `https://app.cvat.ai/api/tasks/{id}/data/`. 
Sometimes it works, sometimes it doesn't (especially when there are more images).

### Current Behaviour
 What i got is the following error: 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

### Context

The empty task is created with the following data:
```
data = {
        "name": name_task,
        "project_id": id,
        "owner": 0,
        "assignee": 0,
        "overlap": 0,
        "segment_size": 150,
        "z_order": False,
        "image_quality": 100,
    }
```
When I add images to the task I only set the `image_quality` option and the `client_files` array in the following way:
```
images = {f'client_files[{i}]': open(f, 'rb') for i, f in enumerate(fs)}
uploadImgs = requests.post('{}/tasks/{}/data'.format(url_cvat,taskId), data={'image_quality':100}, files=images, headers={"Authorization": f'Token {keyLogin}'})
```
### Your Environment

- Docker version: `20.10.21`
- Are you using Docker Swarm or Kubernetes? Docker Swarm
- Operating System and version (e.g. Linux, Windows, MacOS): CVAT is running on Windows, while the server in which I use the API is on Linux

**Comment by zhiltsov-max** [comment]
Hi, everything looks correct to me, could you please check the server logs, if possible? You can obtain them with these commands:

`docker logs cvat_server`
`docker logs cvat_worker_default`

Please also consider using our Python [SDK](https://opencv.github.io/cvat/docs/api_sdk/sdk/) and [CLI](https://opencv.github.io/cvat/docs/api_sdk/cli/).

**Comment by nmanovic** [comment]
@erikadicesare , I will close the issue. If you can provide more information, please don't hesitate to reopen the issue.
