### ISSUE TITLE
Question: Migrating projects from CVAT 1.3 to 2.2

### ISSUE THREAD

**Issue by mojcris** [opencv/cvat#5397]
Hi, 

I have some projects from an older version of CVAT (1.3) and now I'd like to use CVAT 2.2 but I don't know how to migrate my projects. I tried export the annotations and importing them in CVAT 2.2 but I get the following error: 
```
{"detail":"CSRF Failed: CSRF token missing or incorrect."}
``` 

What's the best way to manually move projects from my old CVAT to the newest CVAT? 

Thanks.

**Comment by bsekachev** [comment]
Hi @mojcris 

Try to logout/login again.

**Comment by bsekachev** [comment]
Maybe a better option is just to upgrade CVAT.
All your data are expected to be keep in this case.

**Comment by mojcris** [comment]
Thanks for your reply. The problem is that I have 2 different instances of CVAT (one older and one the latest) and I have projects in both CVATs. I'm trying to find a way to have all my projects in one place. Is export/import a good way to do this?

**Comment by bsekachev** [comment]
@mojcris 

In general yes, I expect this wat should also work. 
Try the first advice

**Comment by mojcris** [comment]
Thank you very much. I'm going to try it now.

**Comment by mojcris** [comment]
> Hi @mojcris
> 
> Try to logout/login again.

This worked for me. Thanks so much.

**Comment by mojcris** [comment]
Also, I realized that after upgrade to the latest CVAT from versions < 2.0, all the projects remain in the personal workspace of admin. Is it possible to move them all to a different workspace?

**Comment by bsekachev** [comment]
@mojcris 

Permissions system was significantly reworked. Now to share a project/task/job with someone, owner needs to assign a user to this project/task/job. If you want to share a project with a group of people, you need to [create an organization first](https://opencv.github.io/cvat/docs/manual/advanced/organization/), activate it and then create a project inside it. You can invite different users into the organization and assign corresponding roles.  

Unfortunately there is not a feature to move a project between organizations now. Related issue #4202
