### ISSUE TITLE
Ability to copy an existing tracked polygon instead of creating a new one

### ISSUE THREAD

**Issue by medphisiker** [opencv/cvat#5400]
### My actions before raising this issue
- [ ] I create a task for labeling from the set of images.
- [ ] I read docs about "Track mode with polygons" [link](https://opencv.github.io/cvat/docs/manual/advanced/annotation-with-polygons/track-mode-with-polygons/).
- [ ] Then I create track polygon on frame 1 (step 1) and press N key to finish it (step 2), moved to the frame 3 (step 3), press Shift+N to create the new polygon (step 4) and press N to finish (step 5).

This is a great basic scenario when an object changes on frames. 
But I have a conveyor. The objects on it are translate from left to the right and practically do not change. 
It would be great after we created the track polygon on step 2, and move to frame 3 on step 3, for example press Shift+C to copy polygon instead of creation new one on step 4.

Also, when interpolating tracked polygons on intermediate frames, I get offset polygons relative to the real position of objects along the X-axis. It would be great not to edit them pointwise. And just move the entire polygon entirely along the X and Y axes.
This would greatly speed up the work of the labeling in our case when labeling objects on conveyor.

### Expected Behaviour
There is no bug in this case, there is a request to add additional functionality.

### Current Behaviour
We need to constantly recreate a new polygon in step 4. And it would be great to just copy an existing one to a new location. And you also need to constantly pull up the interpolated polygons along the X-axis, pointwise, and it would be great just to be able to move the polygon as a whole.

### Possible Solution
It would be great after we created the track polygon on step 2, and move to frame 3 on step 3, for example press Shift+C to copy polygon instead of creation new one on step 4.
nd it would be great to just copy an existing one to a new location. And you also need to constantly pull up the interpolated polygons along the X-axis, pointwise, and it would be great just to be able to move the polygon as a whole.

### Steps to Reproduce (for bugs)

You need to follow all the steps specified in the instructions [link](https://opencv.github.io/cvat/docs/manual/advanced/annotation-with-polygons/track-mode-with-polygons/).

1. create track polygon on frame 1 and press N key to finish it
2. moved to the frame 3
3. press Shift+N, create the new polygon and press N to finish

### Context
Everything works, but in our case, with these two options, the work would be accelerated several times.

### Your Environment
- I use 2.2 realise of CVAT:
- Docker version `docker version` (e.g. Docker  20.10.21):
- I use Docker Compose standart run
- Operating System is Linux Ubuntu Server 20.04.5 LTS (GNU/Linux 5.15.0-53-generic x86_64)

**Comment by bsekachev** [comment]
> The objects on it are translate from left to the right and practically do not change.

If they are just shifted, you can move polygon. Do not need to redraw a keyframe from scratch. 
Just check that **pinned** property is deactivated. By default is activated for polygons. 

![demo](https://user-images.githubusercontent.com/40690378/205100050-e1f0b36c-b53d-4ab4-8a11-b3d3bb646484.gif)

**Comment by medphisiker** [comment]
Thank you very much for the quick response and visual hint I have already tried everything works, thank you very much)
Well, to create tracks after a few frames, I can copy the mask by moving forward a few frames, inserting it in the right place, and then converting the first and second polygon shape to tracking polygon according to your answer on this issue [link](https://github.com/opencv/cvat/issues/5401).

Once again, thank you very much, this issue has been resolved, it can be closed.
