### ISSUE TITLE
How do I add images to a previously created markup task?

### ISSUE THREAD

**Issue by medphisiker** [opencv/cvat#5405]
### My actions before raising this issue
- I create a task for labeling from the set of images.
- I label some images.
- I decide to append some new images for labeling to a previously created task. But I can't to find how to do that.
- I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation).

I wanted to ask is it possible to add new images to an already existing markup task?
If not, is it possible to somehow save the already existing labeled images from the task and transfer them to a new labeling task?

### Context
There were data, some of the data has already been labeled up, and then the customer comes and says that there is more data and he is ready to pay for their markup. We need to save what has already been marked up earlier and mark up new data.

**Comment by bsekachev** [comment]
Hi @medphisiker 

No way to add data to existing task.
If you want to annotate more and more, please consider using projects.
In general **project === dataset**.  You can have as many data as you need with the same specification and when everything is annotated, you just export the project as a dataset in one of supported formats.

**Comment by zhiltsov-max** [comment]
You can also create an empty project and move existing annotated tasks to the new project, this will allow you to extend the task with new data and keep existing annotations.

**Comment by nmanovic** [comment]
@medphisiker , I hope the question was answered. I will close the issue.

**Comment by medphisiker** [comment]
Thank you for your help and advice. I tried everything and everything works. Now I figured it out ) I have no more questions about this appeal.

**Comment by AntonisCSt** [comment]
In my case:
1) export annotations in specific format (e.g. COCO)
2) creating a new task
3) adding previous data (careful to have the same names and dimensions) + new data
4) importing annotations from 1)

worked :)
