### ISSUE TITLE
Docker compose not working

### ISSUE THREAD

**Issue by harishhasti95** [opencv/cvat#5423]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Not able to run the docker compose command in windows 10

This is the error I recieved
Error response from daemon: no such image: cvat/ui:dev  docker-compose up -d: invalid reference format

**Comment by nmanovic** [comment]
@harishhasti95 , please try the latest develop version. If you still have the issue, please provide exact command which you run. I believe it is a problem on your side.
