### ISSUE TITLE
"Tag annotation" gets an error JS when accessing saved work. 

### ISSUE THREAD

**Issue by Tsil-sudo** [opencv/cvat#5443]
### My actions before raising this issue
- I was working on "tag annotation" and then saved the job, then went out,  When I went back to the task to continue, I got the error

It is related to the UI, I got the same issue when importing annotation from outside which had already been tagged. I already raised the issue a month ago

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>TypeError
Cannot read properties of undefined (reading 'id')

TypeError: Cannot read properties of undefined (reading 'id')
    at mV (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:5819093)
    at $o (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4010330)
    at ws (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4056235)
    at fl (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4049011)
    at dl (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4048936)
    at rl (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4045966)
    at http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:3997739
    at t.unstable_runWithPriority (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4163771)
    at Ua (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:3997448)
    at qa (http://192.168.88.250:8888/assets/cvat-ui.db4623b230fbbf696798.min.js:2:3997684)</summary>
    </details>

**Comment by bsekachev** [comment]
Please provide exact steps to reproduce (would be great if you attached a gif or a videofile), from an empty task to fail. 
Also provide the version of CVAT your are using (`git log -1``)

Thanks in advance.

**Comment by Tsil-sudo** [comment]
https://user-images.githubusercontent.com/63632398/206664038-50608670-7dcc-4e55-bcd7-e24f7ca7e177.mp4

Here is a video of the exact steps.

git log -1 output: 
commit 0a5b71123d84e3d42076fbe261cd3e4a6ef46c75 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Roman Donchenko <roman@cvat.ai>
Date:   Mon Nov 7 11:45:57 2022 +0300

**Comment by bsekachev** [comment]
@Tsil-sudo 

Can I ask you to share project specification?

**Comment by Tsil-sudo** [comment]
@bsekachev 

Excuse-me, I was out for the last few days. 
I was doing "tag annotation". 
what do you mean by project specification please?

**Comment by bsekachev** [comment]
@Tsil-sudo 

Hello,

Specification is labels to be annotated in a project. All text from this field:
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/40690378/208619359-70c56822-be3a-4ede-9364-10dad102fc53.png">

**Comment by Tsil-sudo** [comment]
@bsekachev 
Good morning,
Thank you for your reply,

Alright there it is:
[
  {
    "name": "Orange épluchée (entière ou en quartier)",
    "id": 163,
    "color": "#051233",
    "type": null,
    "attributes": []
  },
  {
    "name": "Prune verte (Reine Claude)",
    "id": 164,
    "color": "#d77cec",
    "type": null,
    "attributes": []
  },
  {
    "name": "Amandes",
    "id": 165,
    "color": "#6b392a",
    "type": null,
    "attributes": []
  },
  {
    "name": "Amandes effilées",
    "id": 166,
    "color": "#195330",
    "type": null,
    "attributes": []
  },
  {
    "name": "Orange sanguine (entière avec peau)",
    "id": 167,
    "color": "#7871f3",
    "type": null,
    "attributes": []
  },
  {
    "name": "Cacahuètes",
    "id": 168,
    "color": "#827ae3",
    "type": null,
    "attributes": []
  },
  {
    "name": "Clémentine entière (épluchée)",
    "id": 169,
    "color": "#75c983",
    "type": null,
    "attributes": []
  },
  {
    "name": "Abricots secs",
    "id": 170,
    "color": "#b75ceb",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pruneaux",
    "id": 171,
    "color": "#153789",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pastèque (entière avec peau)",
    "id": 172,
    "color": "#e42178",
    "type": null,
    "attributes": []
  },
  {
    "name": "Mûres",
    "id": 173,
    "color": "#2d6808",
    "type": null,
    "attributes": []
  },
  {
    "name": "Compote (la sauce pas le pot) (tous types)",
    "id": 174,
    "color": "#1107ff",
    "type": null,
    "attributes": []
  },
  {
    "name": "Tranche de pamplemousse",
    "id": 175,
    "color": "#0aa8be",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pêche en quartiers",
    "id": 176,
    "color": "#b534de",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pomme découpée (en quartiers)",
    "id": 177,
    "color": "#0350ca",
    "type": null,
    "attributes": []
  },
  {
    "name": "Citron jaune entier (avec peau)",
    "id": 178,
    "color": "#03ad5b",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pom'Potes",
    "id": 179,
    "color": "#c1f012",
    "type": null,
    "attributes": []
  },
  {
    "name": "Fraises",
    "id": 180,
    "color": "#e7b33f",
    "type": null,
    "attributes": []
  },
  {
    "name": "Litchis (epluchés)",
    "id": 181,
    "color": "#07287d",
    "type": null,
    "attributes": []
  },
  {
    "name": "Melon (la chair)",
    "id": 182,
    "color": "#9aab51",
    "type": null,
    "attributes": []
  },
  {
    "name": "Compote en pot (tous types/parfums)",
    "id": 183,
    "color": "#14da46",
    "type": null,
    "attributes": []
  },
  {
    "name": "Prune rouge (Quetsche)",
    "id": 184,
    "color": "#416307",
    "type": null,
    "attributes": []
  },
  {
    "name": "Kaki découpé",
    "id": 185,
    "color": "#7dac1f",
    "type": null,
    "attributes": []
  },
  {
    "name": "Papaye entière",
    "id": 186,
    "color": "#5c1a62",
    "type": null,
    "attributes": []
  },
  {
    "name": "Cerneau de noix",
    "id": 187,
    "color": "#2b6fdd",
    "type": null,
    "attributes": []
  },
  {
    "name": "Noix de cajou",
    "id": 188,
    "color": "#8b1456",
    "type": null,
    "attributes": []
  },
  {
    "name": "Poire en quartiers",
    "id": 189,
    "color": "#27b6b0",
    "type": null,
    "attributes": []
  },
  {
    "name": "Tranche de citron vert",
    "id": 190,
    "color": "#3a6590",
    "type": null,
    "attributes": []
  },
  {
    "name": "Mélange de noix",
    "id": 191,
    "color": "#e0f137",
    "type": null,
    "attributes": []
  },
  {
    "name": "Cranberry",
    "id": 192,
    "color": "#ebe92c",
    "type": null,
    "attributes": []
  },
  {
    "name": "Raisin blanc",
    "id": 193,
    "color": "#1ebbf5",
    "type": null,
    "attributes": []
  },
  {
    "name": "Kiwi épluché",
    "id": 194,
    "color": "#84c030",
    "type": null,
    "attributes": []
  },
  {
    "name": "Noix (avec coquille)",
    "id": 195,
    "color": "#f98f87",
    "type": null,
    "attributes": []
  },
  {
    "name": "Citron vert entier (avec peau)",
    "id": 196,
    "color": "#7ab2cc",
    "type": null,
    "attributes": []
  },
  {
    "name": "Morceaux de noix de coco",
    "id": 197,
    "color": "#c41d12",
    "type": null,
    "attributes": []
  },
  {
    "name": "Kiwi entier avec peau",
    "id": 198,
    "color": "#3a02a5",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pamplemousse (coupé en deux)",
    "id": 199,
    "color": "#84fc31",
    "type": null,
    "attributes": []
  },
  {
    "name": "Graines de tournesol",
    "id": 200,
    "color": "#6e8b79",
    "type": null,
    "attributes": []
  },
  {
    "name": "Ananas (en rondelles)",
    "id": 201,
    "color": "#962c1b",
    "type": null,
    "attributes": []
  },
  {
    "name": "Noisettes",
    "id": 202,
    "color": "#96e741",
    "type": null,
    "attributes": []
  },
  {
    "name": "Raisins secs",
    "id": 203,
    "color": "#c9a9aa",
    "type": null,
    "attributes": []
  },
  {
    "name": "Graines de chia",
    "id": 204,
    "color": "#0e7ba9",
    "type": null,
    "attributes": []
  },
  {
    "name": "Mangue (entière)",
    "id": 205,
    "color": "#650231",
    "type": null,
    "attributes": []
  },
  {
    "name": "Banane en rondelle",
    "id": 206,
    "color": "#bb5633",
    "type": null,
    "attributes": []
  },
  {
    "name": "Banane (entière avec peau)",
    "id": 207,
    "color": "#596b58",
    "type": null,
    "attributes": []
  },
  {
    "name": "Melon (entier avec peau)",
    "id": 208,
    "color": "#3ad747",
    "type": null,
    "attributes": []
  },
  {
    "name": "Papaye ouverte (la chair)",
    "id": 209,
    "color": "#6b56f2",
    "type": null,
    "attributes": []
  },
  {
    "name": "Melon jaune (la chair)",
    "id": 210,
    "color": "#e9a425",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pamplemousse (entier avec peau)",
    "id": 211,
    "color": "#b0b86d",
    "type": null,
    "attributes": []
  },
  {
    "name": "Nectarine (entière avec peau)",
    "id": 212,
    "color": "#33d45b",
    "type": null,
    "attributes": []
  },
  {
    "name": "Myrtilles",
    "id": 213,
    "color": "#996724",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pignons de pin",
    "id": 214,
    "color": "#941990",
    "type": null,
    "attributes": []
  },
  {
    "name": "Kaki entier avec peau",
    "id": 215,
    "color": "#e3c96c",
    "type": null,
    "attributes": []
  },
  {
    "name": "Compote de pomme",
    "id": 216,
    "color": "#150e13",
    "type": null,
    "attributes": []
  },
  {
    "name": "Ananas (en dés / morceaux)",
    "id": 217,
    "color": "#5e04f5",
    "type": null,
    "attributes": []
  },
  {
    "name": "Framboise",
    "id": 218,
    "color": "#4ed35b",
    "type": null,
    "attributes": []
  },
  {
    "name": "Cerises",
    "id": 219,
    "color": "#c68d78",
    "type": null,
    "attributes": []
  },
  {
    "name": "Baies de goji",
    "id": 220,
    "color": "#8a3837",
    "type": null,
    "attributes": []
  },
  {
    "name": "Grenade",
    "id": 221,
    "color": "#466875",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pistaches (avec coquille)",
    "id": 222,
    "color": "#f55f49",
    "type": null,
    "attributes": []
  },
  {
    "name": "Graines de lin",
    "id": 223,
    "color": "#b03150",
    "type": null,
    "attributes": []
  },
  {
    "name": "Salade de fruits",
    "id": 224,
    "color": "#926f2f",
    "type": null,
    "attributes": []
  },
  {
    "name": "Clémentine (avec peau)",
    "id": 225,
    "color": "#c11d99",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pomme marron entière (avec peau)",
    "id": 226,
    "color": "#635718",
    "type": null,
    "attributes": []
  },
  {
    "name": "Figues séchées",
    "id": 227,
    "color": "#5a3288",
    "type": null,
    "attributes": []
  },
  {
    "name": "Noisettes (avec coquille)",
    "id": 228,
    "color": "#2fbad9",
    "type": null,
    "attributes": []
  },
  {
    "name": "Fruit de la passion (entier avec peau)",
    "id": 229,
    "color": "#11d916",
    "type": null,
    "attributes": []
  },
  {
    "name": "Amandes coques",
    "id": 230,
    "color": "#00299e",
    "type": null,
    "attributes": []
  },
  {
    "name": "Graines de sésame",
    "id": 231,
    "color": "#f7e24d",
    "type": null,
    "attributes": []
  },
  {
    "name": "Grains de grenade",
    "id": 232,
    "color": "#a0aa15",
    "type": null,
    "attributes": []
  },
  {
    "name": "Abricot",
    "id": 233,
    "color": "#d8a544",
    "type": null,
    "attributes": []
  },
  {
    "name": "Orange (entière avec peau)",
    "id": 234,
    "color": "#d0545f",
    "type": null,
    "attributes": []
  },
  {
    "name": "Grenade ouverte (coupée en deux)",
    "id": 235,
    "color": "#45e4ba",
    "type": null,
    "attributes": []
  },
  {
    "name": "Noix de pécan",
    "id": 236,
    "color": "#77a431",
    "type": null,
    "attributes": []
  },
  {
    "name": "Banane plantain",
    "id": 237,
    "color": "#05dcb7",
    "type": null,
    "attributes": []
  },
  {
    "name": "Mirabelles",
    "id": 238,
    "color": "#b571be",
    "type": null,
    "attributes": []
  },
  {
    "name": "Dattes séchées",
    "id": 239,
    "color": "#64049b",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pomme verte entière (avec peau)",
    "id": 240,
    "color": "#ca6f8b",
    "type": null,
    "attributes": []
  },
  {
    "name": "Melon jaune (entier avec peau)",
    "id": 241,
    "color": "#b11894",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pomme rouge entière (avec peau)",
    "id": 242,
    "color": "#ac5bc4",
    "type": null,
    "attributes": []
  },
  {
    "name": "Cacahuètes (avec sa coquille)",
    "id": 243,
    "color": "#81c783",
    "type": null,
    "attributes": []
  },
  {
    "name": "Ananas entier",
    "id": 244,
    "color": "#b353e2",
    "type": null,
    "attributes": []
  },
  {
    "name": "Nectarine en tranche",
    "id": 245,
    "color": "#1b26cd",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pomme jaune entière (avec peau)",
    "id": 246,
    "color": "#a41989",
    "type": null,
    "attributes": []
  },
  {
    "name": "Noix de coco en copeaux",
    "id": 247,
    "color": "#817e88",
    "type": null,
    "attributes": []
  },
  {
    "name": "Orange sanguine épluchée",
    "id": 248,
    "color": "#fbcc88",
    "type": null,
    "attributes": []
  },
  {
    "name": "Poire (entière avec peau)",
    "id": 249,
    "color": "#c178db",
    "type": null,
    "attributes": []
  },
  {
    "name": "Fruit de la passion (ouvert coupé en deux)",
    "id": 250,
    "color": "#b78079",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pistaches décortiquées",
    "id": 251,
    "color": "#6faba6",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pêche (entière avec peau)",
    "id": 252,
    "color": "#787a21",
    "type": null,
    "attributes": []
  },
  {
    "name": "Figue ouverte (coupée)",
    "id": 253,
    "color": "#5e37fc",
    "type": null,
    "attributes": []
  },
  {
    "name": "Figue entière",
    "id": 254,
    "color": "#8876a8",
    "type": null,
    "attributes": []
  },
  {
    "name": "Tranche de citron jaune",
    "id": 255,
    "color": "#c379fa",
    "type": null,
    "attributes": []
  },
  {
    "name": "Pastèque (la chair)",
    "id": 256,
    "color": "#5d20ed",
    "type": null,
    "attributes": []
  },
  {
    "name": "Raisin noir",
    "id": 257,
    "color": "#f2df8b",
    "type": null,
    "attributes": []
  },
  {
    "name": "Noix de coco (entière)",
    "id": 258,
    "color": "#ae9b04",
    "type": null,
    "attributes": []
  },
  {
    "name": "Mangue épluchée (la chair)",
    "id": 259,
    "color": "#84b133",
    "type": null,
    "attributes": []
  },
  {
    "name": "Banane (entière sans peau)",
    "id": 260,
    "color": "#95cc4e",
    "type": null,
    "attributes": []
  },
  {
    "name": "Mélange de fruits secs",
    "id": 261,
    "color": "#02ab67",
    "type": null,
    "attributes": []
  }
]

**Comment by Tsil-sudo** [comment]
@bsekachev 
I have found the error, it's in these labels. The key "type" should not be "null". I changed them to "any" and the error does not occur anymore.

Thank you so much for your help
