### ISSUE TITLE
Unable to create a new task

### ISSUE THREAD

**Issue by kd610** [opencv/cvat#5448]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

A task will be successfully created once the data is uploaded and clicked `save & continue`.

### Current Behaviour

I follow an installation manual using Docker by `docker-compose up`. It successfully builds the software and I can access it there via localhost:8080. But I couldn't finish creating a task as I stuck after I uploaded a video and save&continue. I bet there might be a problem with the `cvat_worker_low` node (an error message is below). 
```
cvat_worker_low       | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -ic " \\\nif [ \\"%(ENV_CVAT_DEBUG_ENABLED)s\\" = \'yes\' ]; then \\\n_DEBUG_CMD=\\"-m debugpy --listen 0.0.0.0:%(ENV_CVAT_DEBUG_PORT)s\\";\nelse\n_DEBUG_CMD=\\"\\";\nfi && \\\n\\\nexec python3 ${_DEBUG_CMD} %(ENV_HOME)s/manage.py rqworker -v 3 low \\\n"' for 'program:rqworker_low.command' contains names ('ENV_CVAT_DEBUG_ENABLED') which cannot be expanded. Available names: ENV_CVAT_DEBUG_PORT, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_HOST, ENV_DJANGO_CONFIGURATION, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, process_num, program_name in section 'program:rqworker_low' (file: 'supervisord/worker.low.conf')
```
Also, the screenshots of logs after I run `docker-compose up` are shown below.
<img width="1535" alt="Screen Shot 2022-12-11 at 12 50 44" src="https://user-images.githubusercontent.com/51090806/206902055-d5d9aed0-9ff3-48be-99e3-c78cde9a846a.png">
<img width="1542" alt="Screen Shot 2022-12-11 at 12 50 55" src="https://user-images.githubusercontent.com/51090806/206902057-d925c7bd-eb37-4cc6-ae60-ecb4e3e81eda.png">

### Steps to Reproduce (for bugs)

1. Clone the latest `cvan` repository.
2. Run `docker-compose up`

### Context

This issue affects me to create a new task to start annotation...

### Your Environment

- Git hash commit (`git log -1`): a3b4f97f9a806edbce5905ec1250892c5a70774e
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 4.13.1
- Are you using Docker Swarm or Kubernetes?: No
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS Monterey, MacBook Pro (13-inch, M1, 2020)

**Comment by ranshadmi** [comment]
Having the same issue on Windows 10. Following any helpful comments.

**Comment by amitmohanty** [comment]
following

**Comment by nmanovic** [comment]
@kd610 , thanks for the report. I can reproduce it. It leads to problems with creating new tasks. Containers for cvat_worker_default and cvat_worker_low are restarting.

**Comment by nmanovic** [comment]
To reproduce the problem it is necessary to run CVAT using `docker-compose up -d` command.

**Comment by nmanovic** [comment]
The current workaround is to run `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d` command. It will define a missing environment variable.

**Comment by ranshadmi** [comment]
> @kd610 , thanks for the report. I can reproduce it. It leads to problems with creating new tasks. Containers for cvat_worker_default and cvat_worker_low are restarting.

Exactly what I'm seeing!

**Comment by David-19940718** [comment]
> The current workaround is to run `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d` command. It will define a missing environment variable.

Thanks very much, everything is ok after run the command `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d`.

**Comment by cccober** [comment]
> @nmanovic This didn't work out for me. `cvat_worker_low` and `cvat_worker_default `are unable to start and keep on restarting

didn't work either
