### ISSUE TITLE
Question: Is the way to specify CVAT directories to store its data(datasets and annotation)?

### ISSUE THREAD

**Issue by medphisiker** [opencv/cvat#5463]
### My actions before raising this issue
- I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- I searched [past issues](/issues)

As I understand from the FAQ in [docs,](https://opencv.github.io/cvat/docs/faq/) CVAT stores data in `cvat_data:/home/django/data ` and annotations in `cvat_db:/var/lib/postgresql/data`.
I have a server with the file system on SSD (256 Gb). I also have a mounted HDD(6 Tb) as catalog `\hdd` in file system.
Is there a way to specify other directories to store CVAT data?
I would like to store all big data on hdd for example in directories:
`cvat_data:/hdd/django/data `
`cvat_db:/hdd/var/lib/postgresql/data`

### Current Behaviour
Now CVAT stores all data on an SSD on which there is not much space.

### Possible Solution
Specify CVAT directories on the HDD to store all its data.

### Context
It would be great if CVAT, like the whole system, worked on an SSD, and the data would be stored on the HDD.

### Your Environment

- I install CVAT 2.2.0 realise
- Operating System is Linux Ubuntu Server 20.04.

**Comment by medphisiker** [comment]
Hello,

thanks you for the help. Unfortunately I'm a little confused.
First I run docker compose as usual. I inspect volume `cvat_cvat_data` and get this description:
```
{
    "CreatedAt": "2022-12-13T12:55:07Z",
    "Driver": "local",
    "Labels": {
        "com.docker.compose.project": "cvat",
        "com.docker.compose.version": "2.6.0",
        "com.docker.compose.volume": "cvat_data"
    },
    "Mountpoint": "/var/lib/docker/volumes/cvat_cvat_data/_data",
    "Name": "cvat_cvat_data",
    "Options": null,
    "Scope": "local"
}
```
Then I down all containers. I go to config file `docker-compose.yml`, goto end of this file and paste text to specify options for volumes as you as you suggested. Then I run all cvat containers by command with `--build` option to apply changes of **docker-compose.yml**:
`docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d --build`

CVAT starts well. I inspect volume `cvat_cvat_data` again. I was expecting to get a description like this:
```
{
    "CreatedAt": "2022-12-13T12:55:07Z",
    "Driver": "local",
    "Labels": {
        "com.docker.compose.project": "cvat",
        "com.docker.compose.version": "2.6.0",
        "com.docker.compose.volume": "cvat_data"
    },
    "Mountpoint": "/var/lib/docker/volumes/cvat_cvat_data/_data",
    "Name": "cvat_cvat_data",
    "Options": {
               "device": "/hdd/cvat_data",
               "o": "bind",
               "type": "none"
    },
    "Scope": "local"
}
```
But I get the same description as before with `"Options": null`. 
So the volume is located in the same place as before ? 
Unfortunately, I don't know docker volume so well yet. 
How can I verify that they are now really stored on the hdd? )

**Comment by azhavoro** [comment]
Compose doesnt recreate a volumes, try to deleting them manually first or by adding **-v** option: `docker compose down -v`, but note that you will lose all your data

**Comment by medphisiker** [comment]
Thank you very much it works )
I make a backup of all tasks.
Then I down all containers. 
Then I remove docker volumes: `cvat_cvat_data`  and `cvat_cvat_db`.
I go to config file docker-compose.yml, goto end of this file and paste text to specify options for volumes as you as you suggested.
Then I run all cvat containers by command with --build option to apply changes of docker-compose.yml:
`docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d --build`

And it recreate them.

I inspect volume `cvat_cvat_data` again. I get a description like I expected:
```
{
    "CreatedAt": "2022-12-15T10:35:34Z",
    "Driver": "local",
    "Labels": {
        "com.docker.compose.project": "cvat",
        "com.docker.compose.version": "2.6.0",
        "com.docker.compose.volume": "cvat_data"
    },
    "Mountpoint": "/var/lib/docker/volumes/cvat_cvat_data/_data",
    "Name": "cvat_cvat_data",
    "Options": {
        "device": "/hdd/cvat_data",
        "o": "bind",
        "type": "none"
    },
    "Scope": "local"
}
```
For now my docker volumes on hdd )
And then I login to CVAT web interface and restore all my tasks from backups.

**Comment by wangwangteam** [comment]
thanks for your work. please help me! 
my .yml is :
![image](https://user-images.githubusercontent.com/26371875/237060680-195ba3c6-56d4-4919-92f5-cc3c62e2b742.png)

When I use the above method, the background service starts normally, but when I access it using a browser, I get an error：
![image](https://user-images.githubusercontent.com/26371875/237060013-9ea6036a-0517-44a7-80c5-001bc7f30595.png)

**Comment by Bin-Saleem** [comment]
> thanks for your work. please help me! my .yml is : ![image](https://user-images.githubusercontent.com/26371875/237060680-195ba3c6-56d4-4919-92f5-cc3c62e2b742.png)
> 
> When I use the above method, the background service starts normally, but when I access it using a browser, I get an error： ![image](https://user-images.githubusercontent.com/26371875/237060013-9ea6036a-0517-44a7-80c5-001bc7f30595.png)

Have you solved this issue?
