### ISSUE TITLE
[Feature Request] Adding the propagate function to Tag annotation

### ISSUE THREAD

**Issue by AbdelsalamHaa** [opencv/cvat#5464]
### My actions before raising this issue
I have a video where I need to classify each image into two classes. So I used Tag annotation. However, using the stander one with the box label. I could propagate the label to many frames ahead. But this feature doesn't exist with Tag annotation. 

### Expected Behaviour
Propagate function to the Tag annotation

### Current Behaviour
Need to tag frame by frame

**Comment by bsekachev** [comment]
Hi @AbdelsalamHaa 

Why do you think it does not exist? 
<img width="243" alt="image" src="https://user-images.githubusercontent.com/40690378/207595526-47a8575d-b1ba-4e06-aaca-d66121a16333.png">

**Comment by AbdelsalamHaa** [comment]
Hi @bsekachev 

Thank you very much for your response. This is for the standred labeling. There is a different type of annotation wich is called Tag Annotation. This one can't propagate. 
You may view the image below. This annotation is to tag the entire image to a label.

![image](https://user-images.githubusercontent.com/35866217/207600005-66e441db-bba7-4289-95c0-3480d17bae45.png)

**Comment by bsekachev** [comment]
Okay, I see

**Comment by nmanovic** [comment]
Probably you need something like https://github.com/opencv/cvat/issues/1228. I will close the issue as a duplicate.
