### ISSUE TITLE
when i use helm deploy cvat have a error

### ISSUE THREAD

**Issue by xs818818** [opencv/cvat#5466]
helm upgrade -n default cvat -i --create-namespace ./helm-chart -f ./helm-chart/values.yaml -f ./helm-chart/values.override.yaml

Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "cvat-redis-replicas-0": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "cvat-redis-replicas-0": pod has unbound immediate PersistentVolumeClaims

**Comment by azhavoro** [comment]
@xs818818 Hi,
we use bitnami's redis subchart and don't manage it, it might need to be updated.
Try to update redis subchart.

**Comment by xs818818** [comment]
success，thank you
