### ISSUE TITLE
CVAT Upload from Local Disk Stuck at 0%

### ISSUE THREAD

**Issue by lazarulian** [opencv/cvat#5468]
## My actions before raising this issue
- Read and searched through the current open issues
- Wiped and did a fresh install across two different devices

## Expected Behaviour
When creating a new task, selecting images from the local disk, I expect to upload them and then be able to view them in the task and begin to annotate.

## Current Behaviour
I installed a clean copy of CVAT, went to upload files for a task from the local disk and then got stuck with:
> Uploading to Server 0%

After this, it never actually uploaded and nothing happened. I was not able to annotate anything.

#### Environment 1:
- MacOS Montery 12.6 - ARM M1 Pro
- Docker Version 4.3.2 

#### Environment 2: 
- Windows 10 Enterprise 19044.2251 - Intel i9 x86
- Docker Version 4.15.0

Please let me know what the issue could be and if there is any solution. Thank you so much for your time, I really appreciate it.

**Comment by azhavoro** [comment]
Probably the same issue #5448

**Comment by zhiltsov-max** [comment]
Should be working now, please check https://github.com/opencv/cvat/issues/5482#issuecomment-1357817210 for recommendations.
