### ISSUE TITLE
Custom model with its weights YOLOv5

### ISSUE THREAD

**Issue by nfrvnikita** [opencv/cvat#5471]
Hello all!
Question about loading my weights into the YOLOv5 model in CVAT.

To begin with, I've deplooped the model:
```
nuctl deploy --project-name cvat \
--path serverless/pytorch/ultralytics/yolov5/nuclio
--volume /ultralytics/yolov5/nuclio:/ultralytics/yolov5/nuclio
--platform local
```

Also in the main.py I put the following:
```
model = CustomModule('ultralyics/yolov5', 'custom', path='/ultralytics/yolov5/nuclio/nuclio/weights.pt', force_reload=True)
```

Then using docker cp:
```
docker cp /home/user/cvat/serverless/pytorch/ultralytics/yolov5/nuclio <id_container>:/ultralytics/yolov5/nuclio
```
I moved the weights to the folder, but when I go to the localhost and try to do autoannotation - nothing happens. The model still has the base weights. What am I doing wrong?

**Comment by nmanovic** [comment]
@nfrvnikita , please read https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/. Please ask questions in our public channels: https://github.com/opencv/cvat#contact-us
