### ISSUE TITLE
Add end-to-end tests ensuring key scenarios are working on CI

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#5472]
Problems like these (#5448) show that we need a couple of tests ensuring the key scenarios are working. I suggest to add a github CI test launching CVAT, creating a task and exporting it.

**Comment by nmanovic** [comment]
@zhiltsov-max , it looks like we have such tests. The problem in #5448 is how we launch CVAT instance. In general we need to improve our CI and testing infra. I don't think we need to remind us about that on GitHub.
