### ISSUE TITLE
Error installing cvat v2.2.0 on kubernetes using helm chart

### ISSUE THREAD

**Issue by MauroRibeiroHV** [opencv/cvat#5475]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Expected Behaviour
Installed cvat v2.2.0 in kubernetes
Created super user
When doing login it would login
Could create users

### Current Behaviour
Cant login
Cant create users

Error logging in:

`2022-12-15 16:43:56,177 DEBG 'runserver' stderr output:
[Thu Dec 15 16:43:56.170582 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714] [2022-12-15 16:43:56,169] ERROR django.request: Internal Server Error: /api/users/self
[Thu Dec 15 16:43:56.170616 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714] Traceback (most recent call last):
[Thu Dec 15 16:43:56.170623 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Thu Dec 15 16:43:56.170630 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     response = get_response(request)
[Thu Dec 15 16:43:56.170636 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Thu Dec 15 16:43:56.170642 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Dec 15 16:43:56.170649 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Thu Dec 15 16:43:56.170656 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return view_func(*args, **kwargs)
[Thu Dec 15 16:43:56.170662 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Thu Dec 15 16:43:56.170668 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return self.dispatch(request, *args, **kwargs)
[Thu Dec 15 16:43:56.170674 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Thu Dec 15 16:43:56.170680 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     response = self.handle_exception(exc)
[Thu Dec 15 16:43:56.170686 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Thu Dec 15 16:43:56.170692 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     self.raise_uncaught_exception(exc)
[Thu Dec 15 16:43:56.170698 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Thu Dec 15 16:43:56.170707 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     raise exc

2022-12-15 16:43:56,179 DEBG 'runserver' stderr output:
[Thu Dec 15 16:43:56.170715 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
[Thu Dec 15 16:43:56.170728 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     self.initial(request, *args, **kwargs)
[Thu Dec 15 16:43:56.170737 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
[Thu Dec 15 16:43:56.170744 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     self.check_permissions(request)
[Thu Dec 15 16:43:56.170750 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 332, in check_permissions
[Thu Dec 15 16:43:56.170756 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     if not permission.has_permission(request, self):
[Thu Dec 15 16:43:56.170762 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/home/django/cvat/apps/iam/permissions.py", line 1049, in has_permission
[Thu Dec 15 16:43:56.170768 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return self.check_permission(request, view, None)
[Thu Dec 15 16:43:56.170774 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/home/django/cvat/apps/iam/permissions.py", line 1045, in check_permission
[Thu Dec 15 16:43:56.170780 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return all(permissions)
[Thu Dec 15 16:43:56.170803 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/home/django/cvat/apps/iam/permissions.py", line 79, in __bool__
[Thu Dec 15 16:43:56.170809 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return r.json()['result']
[Thu Dec 15 16:43:56.170816 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714] KeyError: 'result'
[Thu Dec 15 16:43:56.177595 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714] ERROR:django.request:Internal Server Error: /api/users/self
[Thu Dec 15 16:43:56.177617 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714] Traceback (most recent call last):
[Thu Dec 15 16:43:56.177629 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Thu Dec 15 16:43:56.177639 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     response = get_response(request)
[Thu Dec 15 16:43:56.177650 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Thu Dec 15 16:43:56.177661 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Dec 15 16:43:56.177672 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Thu Dec 15 16:43:56.177684 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return view_func(*args, **kwargs)
[Thu Dec 15 16:43:56.177694 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Thu Dec 15 16:43:56.177706 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return self.dispatch(request, *args, **kwargs)
[Thu Dec 15 16:43:56.177717 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Thu Dec 15 16:43:56.177728 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     response = self.handle_exception(exc)
[Thu Dec 15 16:43:56.177742 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Thu Dec 15 16:43:56.177752 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     self.raise_uncaught_exception(exc)
[Thu Dec 15 16:43:56.177763 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Thu Dec 15 16:43:56.177774 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     raise exc
[Thu Dec 15 16:43:56.177783 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
[Thu Dec 15 16:43:56.177790 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     self.initial(request, *args, **kwargs)
[Thu Dec 15 16:43:56.177799 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
[Thu Dec 15 16:43:56.177809 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     self.check_permissions(request)
[Thu Dec 15 16:43:56.177819 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 332, in check_permissions
[Thu Dec 15 16:43:56.177830 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     if not permission.has_permission(request, self):
[Thu Dec 15 16:43:56.177840 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/home/django/cvat/apps/iam/permissions.py", line 1049, in has_permission
[Thu Dec 15 16:43:56.177850 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return self.check_permission(request, view, None)
[Thu Dec 15 16:43:56.177860 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/home/django/cvat/apps/iam/permissions.py", line 1045, in check_permission
[Thu Dec 15 16:43:56.177871 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return all(permissions)
[Thu Dec 15 16:43:56.177880 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]   File "/home/django/cvat/apps/iam/permissions.py", line 79, in __bool__
[Thu Dec 15 16:43:56.177890 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714]     return r.json()['result']
[Thu Dec 15 16:43:56.177900 2022] [wsgi:error] [pid 65:tid 139795576813312] [remote 10.244.2.11:34714] KeyError: 'result'`

Error creating users:
`TypeError
Cannot read properties of null (reading 'dumpers')

TypeError: Cannot read properties of null (reading 'dumpers')
    at https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:5494136
    at e (https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4341519)
    at https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4341724
    at u (https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4340778)
    at t.useSyncExternalStoreWithSelector (https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4341794)
    at https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4384184
    at YA (https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:5494102)
    at $o (https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4010330)
    at ji (https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4019179)
    at Ii (https://cvat2.hibi-dev.hitachi-lumada.io/assets/cvat-ui.db4623b230fbbf696798.min.js:2:4018998)`

### Steps to Reproduce (for bugs)
1. Install cvat v2.2.0 in kubernetes using helm chart
1. Create super user
1. Try to login
1. Try to create an user

### Context
Created rules.tar.gz
Pods are created and running

### Your Environment
Kubernetes v1.21.9

**Comment by MauroRibeiroHV** [comment]
The problem was on the rules file! Was malformed, i ran the command again and it worked now!

**Comment by cccober** [comment]
hi, where is the rules file?

**Comment by MauroRibeiroHV** [comment]
You have to generate it, check the README
