### ISSUE TITLE
Cannot connect to the server.

### ISSUE THREAD

**Issue by vgoineau** [opencv/cvat#5476]
I install CVAT on Docker Swarm. All services are running without any issue. Logs look good for cvat_ui, cvat_server and cvat_db. When I try to access the services https://cvat.<mydomain>. Spinner appear and try to connect to server. In console I see that it is trying to do health check on /api/server/health/?format=json&org=.  But after 5 sec, the request is cancelled. UI is repeating this request multiple times (10 to be exactly). After 10 times... it crash and a popup says Cannot Connect to the server

Now, the issue is that when I try to access the api directly, the /api/server/health/ is working after 6-8 sec. 

### Expected Behaviour
First, request to /api/server/health should take less than 6-8 sec. 
Second, even if the request has delay UI should wait more than 5 sec. 

### Current Behaviour
UI do a health check before loading and it's takes time to server to respond. 

### Steps to Reproduce (for bugs)
- Install CVAT on Docker Swarm with traefik
- Hit your cvat domain and wait

### Your Environment

- Docker version 20.10.21
- Swarm setup with 1 master and 5 worker
- OS is on Linux Ubuntu 22.04

- Logs cvat_server : 
`2022-12-16 01:17:57,771 DEBG 'runserver' stderr output:
[Fri Dec 16 01:17:57.771847 2022] [wsgi:info] [pid 647:tid 140576527637568] mod_wsgi (pid=647): Imported 'mod_wsgi'.
2022-12-16 01:17:57,772 DEBG 'runserver' stderr output:
[Fri Dec 16 01:17:57.772327 2022] [wsgi:info] [pid 647:tid 140576527637568] mod_wsgi (pid=647, process='localhost:8080', application=''): Loading Python script file '/tmp/cvat-server/handler.wsgi'.
[Fri Dec 16 01:17:57.761062 2022] [wsgi:info] [pid 647:tid 140576527637568] mod_wsgi (pid=647): Attach interpreter ''.
2022-12-16 01:17:57,761 DEBG 'runserver' stderr output:` 

- Logs cvat_ui:
` - - [16/Dec/2022:01:35:35 +0000] "GET /favicon.ico HTTP/1.1" 200 102581 "https://cvat.domain.com/api/server/health/?format=json&org=" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "192.168.0.1"
10.0.2.3 - - [16/Dec/2022:01:33:37 +0000] "GET /favicon.ico HTTP/1.1" 200 102581 "https://cvat.domain.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "192.168.0.1"
10.0.2.3 - - [16/Dec/2022:01:33:36 +0000] "GET / HTTP/1.1" 200 1128 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "192.168.0.1"
10.0.2.3 - - [16/Dec/2022:01:30:32 +0000] "GET /favicon.ico HTTP/1.1" 200 102581 "https://cvat.domain.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "192.168.0.1"`

- Console logs : no error in console only this network error :  
![image](https://user-images.githubusercontent.com/13660594/208003790-1f86b080-91ac-4610-a89a-63edd1fa99d4.png)

**Comment by Lucas-Hsu** [comment]
I clone the latest development branch and got the same issue today.

**Comment by vgoineau** [comment]
Hi @Lucas-Hsu are you using Brave Browser for any chances ?

This morning we test my setup on Google Chrome (not chromium base browser) and no errors. And... more snappy. On my side Brave is my go to browser and it very slow or 5 out of 10 not working at all with this "Cannot connect to the server".

**Comment by vgoineau** [comment]
Sorry. after multiple test, Chrome gives us the same thing... seams not to be browser related.

**Comment by nmanovic** [comment]
@vgoineau , please try our latest version v2.3.0. I hope it will help you to resolve the issue. Also, you can use our CVAT.ai cloud instance. In this case you don't need to install it locally and maintain it.

**Comment by vgoineau** [comment]
So v2.3.0 seems working. We do have slowlyness but works. Thanks for this fix. 

@nmanovic : thanks for your suggestion but cloud instance is not legally possible for us so we need to be internal 100%. This policy might change but for now... this is the way ;-)
