### ISSUE TITLE
Example Serverless Model Deployment CVAT for Automatic Labelling

### ISSUE THREAD

**Issue by Clayrisee** [opencv/cvat#5477]
### My actions before raising this issue
- [ v] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ v] Searched [past issues](/issues)

Is there any example automatic labelling for classification case? 
Thanks

**Comment by nmanovic** [comment]
I don't think so. But probably the article can help to implement such case: https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/.

Please don't submit questions as GitHub issues. Use our public channel to ask questions: https://github.com/opencv/cvat#contact-us
