### ISSUE TITLE
An assignee for a job should be able to use AI tools

### ISSUE THREAD

**Issue by medphisiker** [opencv/cvat#5480]
### My actions before raising this issue
- I read/searched [the docs page](https://opencv.github.io/cvat/docs/manual/advanced/organization/) about organisations.
It points that "In addition to roles, there are groups of users that are configured on the Admin page. Read more about the roles in [IAM system roles section](https://opencv.github.io/cvat/docs/administration/advanced/iam_system_roles)."
But for now IAM system roles section is empty page.
- I searched [past issues](/issues)

Hello I have CVAT v 2.20. From Django admin page I create two users: one superuser and one worker.
I really like the group worker for a data labeling specialist that has access to exactly the work it does.
But I also have two AI Tools models (DEXTR and f-BRS) that simplify data markup for worker.
But there is interesting nuances I can use AI Tools models from superuser, but I can't use them from worker's account.
```
Interaction error occured
Error: Request failed with status code 403. {"detail":"You do not have permission to perform this action."}.
```
I would really like to have a worker account that can use AI Tools in his work.
Unfortunately, there is no documentation [IAM system roles section](https://opencv.github.io/cvat/docs/administration/advanced/iam_system_roles) about user groups yet. 
Can I somehow add rights for worker so that he can use AI Tools DL models?

### Expected Behaviour
I think that person with worker account (data labeling specialist ) can use AI Tools that make his job easier.

### Current Behaviour
User with worker group( data labeling specialist ) can't use AI Tools for data labeling.

### Possible Solution
I think that CVAT have a special command or option that give permissions for using AI Tools for selected user.

### Your Environment
- CVAT v 2.20
- Linux Ubuntu Server 20.04

**Comment by medphisiker** [comment]
I found a solution. I had a job assigned to a worker. But the task was not assigned to him. I also assigned a task to worker and after that worker got access to AI Tools

**Comment by medphisiker** [comment]
The way I found to assign worker `task` works good for tasks with one `job` and one worker.

But if I have a `task` with several `jobs` that different workers do I have the same problem.
I can assign `task` for only one of all workers, and only this one worker can use AI Tools models (DEXTR and f-BRS) that simplify data markup.
The search for the possibility of adding the privilege for using AI Tools models by users from `worker` group is still relevant.

**Comment by zhiltsov-max** [comment]
Should have been fixed with https://github.com/opencv/cvat/pull/5392

**Comment by medphisiker** [comment]
Thank you very much for the quick response and quick code fix )
I have upgraded to the latest version of CVAT.
For now all workers that was assignee to some `job `can use use `AI Tools models` (DEXTR and f-BRS) that simplify data labeling.

**Comment by FunnyDragonK** [comment]
> Thank you very much for the quick response and quick code fix ) I have upgraded to the latest version of CVAT. For now all workers that was assignee to some `job `can use use `AI Tools models` (DEXTR and f-BRS) that simplify data labeling.

My version information is as follows, the same problem is still there. What should I do to solve this problem?
![image](https://github.com/opencv/cvat/assets/25117539/e9433fa0-58aa-445d-8ef3-1fd6e9198986)
