### ISSUE TITLE
Can't able to create webhooks in CVAT V2.2.0

### ISSUE THREAD

**Issue by RohithkumarRavi** [opencv/cvat#5485]
### My actions before raising this issue
- [ ] Read [CVAT documentation](https://opencv.github.io/cvat/docs/administration/advanced/webhooks/)
- [ ] Read [API documentation](https://app.cvat.ai/api/docs/#tag/webhooks/operation/webhooks_create)
- [ ] Read [CVAT SDK Documentation](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/webhooks-api/#create)

### Issue
Not able to create webhook through API, CVAT SDK (Webhook section is not available in CVAT user interface)

**Comment by nmanovic** [comment]
@RohithkumarRavi , the feature will be available in v2.3.0. It will be release this week. For now you can use `develop` branch.
