### ISSUE TITLE
Changing UI

### ISSUE THREAD

**Issue by smarnav2904** [opencv/cvat#5487]
How can I change the UI of CVAT? I have been trying to follow the guidelines of cvat/ui page, but it stills feels confusing. Which are the guidelines I should follow to for example, add the logo of my organization in the main page?

**Comment by bsekachev** [comment]
Hi  @smarnav2904 

- Setup development configuration as described here: https://opencv.github.io/cvat/docs/contributing/development-environment/ 
- If you want to add a logo, for example, you need to update source code in ``cvat-ui/src``

What type of guidlines do you expect?

**Comment by smarnav2904** [comment]
About the technologies you use to develop the UI, looking at the code I can see you use typescript, html, webpack...
But I don't know if I am missing something or my knowledge it's still not enough but I don't get to put a simple image.
Changing or adding HTML tags results for me in broken images...
