### ISSUE TITLE
invalid IP address in add-host: "host-gateway"

### ISSUE THREAD

**Issue by geoffzhang** [opencv/cvat#5488]
when i run:
>> docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up
the error occurred: 
cvat_redis is up-to-date
Recreating nuclio ... 
cvat_db is up-to-date
cvat_opa is up-to-date
traefik is up-to-date
cvat_utils is up-to-date
Recreating 847f0b8597cf_cvat_worker_low ... 
Recreating d70ca6decff8_cvat_server     ... 
cvat_worker_webhooks is up-to-date
Recreating d70ca6decff8_cvat_server     ... error
Recreating 847f0b8597cf_cvat_worker_low ... error
Recreating nuclio                       ... done

ERROR: for 847f0b8597cf_cvat_worker_low  Cannot create container for service cvat_worker_low: invalid IP address in add-host: "host-gateway"

ERROR: for cvat_server  Cannot create container for service cvat_server: invalid IP address in add-host: "host-gateway"

ERROR: for cvat_worker_low  Cannot create container for service cvat_worker_low: invalid IP address in add-host: "host-gateway"
ERROR: Encountered errors while bringing up the project.

please how to solve it ?

**Comment by azhavoro** [comment]
Try to update docker
https://github.com/docker/cli/issues/2664
