### ISSUE TITLE
Optional attributes in labels

### ISSUE THREAD

**Issue by titarch** [opencv/cvat#5489]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I would like to draw shapes using a label that may use a different combination of its attributes depending on what is annotated. I had been using an old version of cvat before that made it possible to make select attribute optional instead of having a default value so that they did not appear automatically.

I searched though the docs and the other issues but it possible I missed something about the way to do this, maybe by editing the advanced label config? (trying to remove the default values adds it back in again though).
If this feature was removed on purpose, is there another way of accomplishing this? I know I could split everything in several labels, but then I would have to duplicate the shapes, which I don't think is ideal.

Thanks in advance for your help.

**Comment by titarch** [comment]
Here is an example:
![image](https://user-images.githubusercontent.com/23527994/208442299-6bfd71a0-efa0-44f2-bd62-92a5bf18aee7.png)

I would like to have the ability to remove the blurry attribute if I don't need it in the instance, or better: having to specifically add it when I need it. This not the best example since I know I could use a tag for storing the blurry attribute but this is not the point.

**Comment by bsekachev** [comment]
Hi, @titarch 

I do not think we have removed something related with attributes annotation. 
There is special value ``__undefined__`` which marks an attribute as not annotated. Maybe not really well documented.. 
Is it what you need? 

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/40690378/208620186-60b0c7b8-400d-48ce-a62a-f711a68ebee8.png">
<img width="228" alt="image" src="https://user-images.githubusercontent.com/40690378/208620230-2f3cbd8b-d5af-4ded-9a72-d70731f05a1d.png">

**Comment by titarch** [comment]
Hi @bsekachev, thanks a lot for your reply, this is nice maybe I can use this, this is definitely better than nothing.
It just lacks a few properties and logic I wish it would have, I have been trying to implement my own field called "optional" that is a checkbox like "mutable", and make it not appear on new shapes by default and have an interface just like this:
![image](https://user-images.githubusercontent.com/23527994/208646704-077594a2-f539-4d24-b0ac-b44835a2b964.png)

I have been struggling on implementing the frontend logic though, I need to extend the state to manage the possibility that any optional attribute may be added or not and make sure it has the right consequences in all different annotation modes and dataset exports, if you have any tips on that please feel free to share. If that is a feature you are interested in I can submit a PR.

**Comment by titarch** [comment]
I was able to easily adapt the code to prevent attributes with \_\_undefined\_\_ value to not dump in the (image) XML.
I am happy with that for now, hiding the optional attributes in the ui is lower priority.

Here is my patch if anyone is interested:
```patch
diff --git a/cvat/apps/dataset_manager/formats/cvat.py b/cvat/apps/dataset_manager/formats/cvat.py
index f46078f5..072bf696 100644
--- a/cvat/apps/dataset_manager/formats/cvat.py
+++ b/cvat/apps/dataset_manager/formats/cvat.py
@@ -719,6 +719,8 @@ def dump_as_cvat_annotation(dumper, annotations):
                     raise NotImplementedError("unknown shape type")
 
                 for attr in shape.attributes:
+                    if attr.value == "__undefined__":
+                        continue
                     dumper.add_attribute(OrderedDict([
                         ("name", attr.name),
                         ("value", attr.value)
```

**Comment by nmanovic** [comment]
@titarch , thanks for your feedback. It looks like we are not going to fix that in the nearest future. I will close it for now. I'm glad that you have found a workaround for your use case.
