### ISSUE TITLE
How to fix  " is not a valid value for "ACCEPT_EULA"?

### ISSUE THREAD

**Issue by otsukaoly** [opencv/cvat#549]
I executed below.

docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build --build-arg http_proxy=http://(server):(port) --build-arg https_proxy=(server):(port)

The error is below.

Processing triggers for man-db (2.7.5-1) ...
" is not a valid value for "ACCEPT_EULA"
/tmp/components/openvino/l_openvino_toolkit_p_2019.1.144/silent.cfg has errors
Service 'cvat' failed to build: The command '/bin/sh -c if [ "$OPENVINO_TOOLKIT" = "yes" ]; then         /tmp/components/openvino/install.sh;     fi' returned a non-zero code: 2

I decompressed the l_openvino_toolkit_p_2019.1.144.org.tgz file using the winzip, edited the silent.cfg file to change the value of ACCEPT_EULA from decline to accept and recompressed them. But another error happened.

How to fix it?

**Comment by bsekachev** [comment]
@otsukaoly  
Hi, I suppose you use windows. If it is true, than there is a related issue #534:

```
git checkout develop
git pull origin develop
git rm --cached -r .
git reset --hard
# Now you can build container
```

**Comment by bsekachev** [comment]
I will close the issue. If you will have any problems with the solution, you can reopen it.

**Comment by otsukaoly** [comment]
Thanks a lot!
Now I can see the "Model Manager" button.

**Comment by otsukaoly** [comment]
I have a simple question.

I clicked Model Manager button.
But I cannot see any model in the Uploaded Models list.
Should I download any model below?
https://github.com/opencv/open_model_zoo/tree/2018/intel_models

**Comment by bsekachev** [comment]
@otsukaoly 
Yes, You need to upload a model before you can use it. 
It can be models from Open Model Zoo, or your custom models, converted to OpenVINO Inference Engine format.

**Comment by otsukaoly** [comment]
Thank you for your reply.
I'm trying to execute the open_model_zoo module.
Now I have other problems about OpenSSL.

https://stackoverflow.com/questions/49302516/where-to-get-and-install-crypto-dll-on-64-bit-windows/56945015#56945015

It is not related to original issue.
So the status 'closed' is O.K.
