### ISSUE TITLE
Length of the ACCESS KEY ID when creating a cloud storage

### ISSUE THREAD

**Issue by darkAlert** [opencv/cvat#5510]
I'm trying to attach S3 storage (Yandex Cloud S3, not AWS) and choosing AWS S3 in the Provider field. It works if I choose the "Anonymous access". But I can't use the "Key Id and secret access key pair" option because Yandex Cloud S3 uses longer keys, but CVAT key length is limited (I mean web interface, and 4 more characters needed in ACCESS KEY ID filed).

Can anyone please suggest how to get around this limitation?

**Comment by rodrigoberriel** [comment]
Not sure how they intend to fix this type of issue for now, but you can implement a workaround following https://github.com/opencv/cvat/pull/4876.
