### ISSUE TITLE
Error attaching сloud storage «STORJ»

### ISSUE THREAD

**Issue by Sergej199** [opencv/cvat#5512]
An error occurs when trying to attach cloud storage «STORJ»( Provider: AWS S3; Authorization type: Key id and secret key pair ). The number of characters that can be input in the "SECRET ACCESS KEY ID" field is not enough. It's necessary to change the maximum number of characters allowed for the "SECRET ACCESS KEY ID" field (file /cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx; line 347: maxLength={44}; and file cvat/apps/engine/serializers.py; line 1179: secret_key = serializers.CharField(max_length=44, allow_blank=True, required=False))

Thank you in advance

patchfile:

diff --git a/cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx b/cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx
index f8b62a7c..583c1861 100644
--- a/cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx
+++ b/cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx
@@ -344,7 +344,7 @@ export default function CreateCloudStorageForm(props: Props): JSX.Element {
                         {...internalCommonProps}
                     >
                         <Input.Password
-maxLength={44}
+maxLength={128}
                             visibilityToggle={secretKeyVisibility}
                             onChange={() => setSecretKeyVisibility(true)}
                             onFocus={() => onFocusCredentialsItem('secretKey', 'secret_key')}
diff --git a/cvat/apps/engine/serializers.py b/cvat/apps/engine/serializers.py
index fd2448b5..92f80a60 100644
--- a/cvat/apps/engine/serializers.py
+++ b/cvat/apps/engine/serializers.py
@@ -1176,7 +1176,7 @@ class CloudStorageWriteSerializer(serializers.ModelSerializer):
     owner = BasicUserSerializer(required=False)
     session_token = serializers.CharField(max_length=440, allow_blank=True, required=False)
     key = serializers.CharField(max_length=40, allow_blank=True, required=False) 
-secret_key = serializers.CharField(max_length=44, allow_blank=True, required=False)
+secret_key = serializers.CharField(max_length=128, allow_blank=True, required=False)
     key_file = serializers.FileField(required=False)
     account_name = serializers.CharField(max_length=24, allow_blank=True, required=False)
     manifests = ManifestSerializer(many=True, default=[])

**Comment by darkAlert** [comment]
Today I created exactly the same request :D
https://github.com/opencv/cvat/issues/5510

**Comment by Sergej199** [comment]
Hi, @darkAlert
The problem of "SECRET ACCESS KEY ID" field (and not in the "ACCESS KEY ID" field) is described

**Comment by darkAlert** [comment]
> Hi, @darkAlert The problem of "SECRET ACCESS KEY ID" field (and not in the "ACCESS KEY ID" field) is described

As for me - the same problem related to the key length limit
