### ISSUE TITLE
CVAT pascal voc export and reimport

### ISSUE THREAD

**Issue by FurqanMehmood** [opencv/cvat#5515]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
I can see the annotations on images

### Current Behaviour
I exported the annotation in pascal voc without saving images.
I created the task again and imported the annotations but they are not visible on images

### Steps to Reproduce (for bugs)

1. Create a task
2. Export annotation in pascal voc without images
3. delete the task
4. Create new task with same images
5. import the pascal voc zip file

1.
1.

### Your Environment

- Operating System and version ( Windows):

**Comment by zhiltsov-max** [comment]
Hi, could you please add details about the annotations? Which annotation types were used for annotation?

**Comment by FurqanMehmood** [comment]
I have annotated polygons

**Comment by zhiltsov-max** [comment]
OK, please use the `Segmentation mask` format then. The polygons will be converted to masks automatically.

**Comment by FurqanMehmood** [comment]
Its my client requirements

**Comment by nmanovic** [comment]
@FurqanMehmood , don't hesitate to contact us if you need commercial support. I will close the issue. Please use another annotation format if you need polygons.
