### ISSUE TITLE
Yolov5 not using the gpu

### ISSUE THREAD

**Issue by mexxBf** [opencv/cvat#5516]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)
- 
Hi, 
I'm trying to use my GPU with my custom Yolov5 model. Using the CPU is working well, but using deploy_gpu.sh puts out an "error"

ERROR: No supported GPU(s) detected to run this container

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...

nvidia-smi is working if I use "docker exec -it nuclio-nuclio-ultralytics-yolov5 nvidia-smi"

### Expected Behaviour
Using the gpu for annotation 

### Current Behaviour
Its using the cpu

### Possible Solution

My guess is, that something of the above mentioned in the error is missing for the docker container

### Steps to Reproduce (for bugs)
start the deploy_gpu.sh for the yolov5 example

**Comment by mexxBf** [comment]
Seems to be an issue in my setup. Some other task blocked my GPU and it ended in an error. Restarting helped, no idea why this happens though.

**Comment by erenuito** [comment]
did you solve the problem? are there any update for entry?

**Comment by erenuito** [comment]
what did you to change while setuping to solve the error?
