### ISSUE TITLE
CVAT Deployment with  Google Cloud

### ISSUE THREAD

**Issue by Starscream-97** [opencv/cvat#5517]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Current Behaviour
even creating a super upser account it doesn't want to log in

### Possible Solution
set up the two container that are restarting up

### Steps to Reproduce (for bugs)
1.  Create an Instance
2. Create a firewall rule 
3. 1.Follow installtion guide
4.  go to docker-compose.yml and change in the tarfeik  the host to public ip adrress and lunch

### Context
CONTAINER ID   IMAGE                                 COMMAND                  CREATED       STATUS                          PORTS                                                                                          NAMES
5c34a73d05d9   cvat/server:dev                       "/usr/bin/supervisor…"   2 hours ago   Up 2 hours                      8080/tcp                                                                                       cvat_server
f3960638ab9b   traefik:v2.9                          "/entrypoint.sh --pr…"   2 hours ago   Up 2 hours                      0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik
95a5e110e105   cvat_logstash                         "/usr/local/bin/dock…"   2 hours ago   Up 2 hours                      5044/tcp, 8080/tcp, 9600/tcp                                                                   cvat_logstash
27b580e85a17   cvat_kibana                           "/usr/local/bin/kiba…"   2 hours ago   Up 2 hours                      5601/tcp                                                                                       cvat_kibana
51488f4c20fd   cvat_elasticsearch                    "/usr/local/bin/dock…"   2 hours ago   Up 2 hours                      9200/tcp, 9300/tcp                                                                             cvat_elasticsearch
35ccd2a8420e   cvat/ui:dev                           "/docker-entrypoint.…"   3 hours ago   Up 3 hours                      80/tcp                                                                                         cvat_ui
ff79bf3c2dbd   cvat/server:dev                       "/usr/bin/supervisor…"   3 hours ago   Up 3 hours                      8080/tcp                                                                                       cvat_worker_webhooks
73782aaec66a   cvat/server:dev                       "/usr/bin/supervisor…"   3 hours ago   Up 3 hours                      8080/tcp                                                                                       cvat_worker_default
0bea59d5d792   cvat/server:dev                       "/usr/bin/supervisor…"   3 hours ago   Up 3 hours                      8080/tcp                                                                                       cvat_worker_low
a86a161680ed   cvat/server:dev                       "/usr/bin/supervisor…"   3 hours ago   Restarting (2) 11 seconds ago                                                                                                  cvat_utils
4fc355c8dd3b   redis:4.0-alpine                      "docker-entrypoint.s…"   3 hours ago   Up 3 hours                      6379/tcp                                                                                       cvat_redis
2544f62a9625   postgres:15-alpine                    "docker-entrypoint.s…"   3 hours ago   Up 3 hours                      5432/tcp                                                                                       cvat_db
39352552560e   openpolicyagent/opa:0.34.2-rootless   "/opa run --server -…"   3 hours ago   Up 3 hours                                                                                                                     cvat_opa

### Your Environment
# Copyright (C) 2018-2022 Intel Corporation
#
# SPDX-License-Identifier: MIT

version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data
    networks:
      - cvat

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    restart: always
    networks:
      - cvat

  cvat_server:
    container_name: cvat_server
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
 ADAPTIVE_AUTO_ANNOTATION: 'false'
      IAM_OPA_BUNDLE: '1'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy:-}
      NUMPROCS: 1
      USE_ALLAUTH_SOCIAL_ACCOUNTS: ""
      SOCIAL_AUTH_GOOGLE_CLIENT_ID: ""
      SOCIAL_AUTH_GOOGLE_CLIENT_SECRET: ""
      SOCIAL_AUTH_GITHUB_CLIENT_ID: ""
      SOCIAL_AUTH_GITHUB_CLIENT_SECRET: ""
    command: -c supervisord/server.conf
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat.loadbalancer.server.port=8080
      - traefik.http.routers.cvat.rule=Host(`${CVAT_HOST:-localhost}`) &&
        PathPrefix(`/api/`, `/git/`, `/opencv/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)
      - traefik.http.routers.cvat.entrypoints=web
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      cvat:
        aliases:
          - cvat-server

  cvat_utils:
    container_name: cvat_utils
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy:-}
    command: -c supervisord/utils.conf
    volumes:
      - cvat_data:/home/django/data
      -  - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_worker_default:
    container_name: cvat_worker_default
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy:-}
      NUMPROCS: 2
    command: -c supervisord/worker.default.conf
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_worker_low:
    container_name: cvat_worker_low
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy:-}
      NUMPROCS: 1
    command: -c supervisord/worker.low.conf
  volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_worker_webhooks:
    container_name: cvat_worker_webhooks
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    environment:
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy:-}
      NUMPROCS: 1
    command: -c supervisord/worker.webhooks.conf
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_ui:
    container_name: cvat_ui
    image: cvat/ui:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      - cvat_server
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat-ui.loadbalancer.server.port=80
      - traefik.http.routers.cvat-ui.rule=Host(`${CVAT_HOST:-3x.xx.xx.xx}`)
      - traefik.http.routers.cvat-ui.entrypoints=web
    networks:
  - cvat

  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    command:
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=cvat'
      - '--entryPoints.web.address=:8080'
      - '--providers.file.directory=/etc/traefik/rules'
    # Uncomment to get Traefik dashboard
     # - "--entryPoints.dashboard.address=:8090"
     # - "--api.dashboard=true"
    labels:
     # - traefik.enable=true
     # - traefik.http.routers.dashboard.entrypoints=dashboard
     # - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.rule=Host(`${CVAT_HOST:-3x.xx.xx.xx}`)
    ports:
      - 8080:8080
      - 8090:8090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - cvat

  cvat_opa:
    container_name: cvat_opa
    image: openpolicyagent/opa:0.34.2-rootless
    restart: always
    networks:
      cvat:
        aliases:
          - opa
    command:
      - run
      - --server
      - --set=decision_logs.console=true
      - --set=services.cvat.url=http://cvat-server:8080
      -  - --set=bundles.cvat.service=cvat
      - --set=bundles.cvat.resource=/api/auth/rules
      - --set=bundles.cvat.polling.min_delay_seconds=5
      - --set=bundles.cvat.polling.max_delay_seconds=15

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:

networks:
  cvat:

**Comment by nmanovic** [comment]
@Starscream-97 , please use our public CVAT.ai cloud instance instead: http://app.cvat.ai/. No need to setup and maintain your own CVAT intstance. I will close the issue because it is very specific. Don't hesitate to contact us if you need commercial support.
