### ISSUE TITLE
CVAT pascal voc export issue

### ISSUE THREAD

**Issue by FurqanMehmood** [opencv/cvat#5527]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
The annotation in .xml file

### Current Behaviour
i am exporting the annotations but the .xml contains no information about the polygons

### Steps to Reproduce (for bugs)
1. Upload dataset
2. annotate object by drawing polygon
3. save polygon
4. export dataset by selecting pascal voc format

### Your Environment

- Operating System and version ( Windows):

**Comment by zhiltsov-max** [comment]
Hi,

The Pascal VOC is described [here](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html#data). It has labels, boxes, keypoints, and segmentations, but not polygons. Polygons can be exported as masks in the `Segmentation mask` format.
