### ISSUE TITLE
Bulk upload of vidoes dataset for annotation

### ISSUE THREAD

**Issue by Sathibhu** [opencv/cvat#553]
Hello,

I was wondering, Is there a feature from CVAT which allows to run script to bulk upload the videos to CVAT tool for annotation. I realized I was doing the same manual work for a long time to upload a video dataset for tagging (just the video upload part)

Any pointers?

Thanks,
Sathish

**Comment by nmanovic** [comment]
You can find an example in my answer (attached). It is just sample. I will keep your request open till we have a good solution in mainline.
[create_task.py.txt](https://github.com/opencv/cvat/files/3372851/create_task.py.txt)

**Comment by nmanovic** [comment]
CLI was merged: https://github.com/opencv/cvat/tree/develop/utils/cli
