### ISSUE TITLE
Problem with upgrading database

### ISSUE THREAD

**Issue by StellaASchlotter** [opencv/cvat#5544]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I wanted to upgrade the database as described in https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/#how-to-upgrade-postgresql-database-base-image

I ran into an error because I have an override file similar to what can be found in the docs at https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path

The error came from the command `docker compose up -d cvat_db` because the version of the docker-compose files are different to the override file. 

### Possible Solution
Simply add the line `version: "3.3" ` to all the other docker-compose files.

**Comment by nmanovic** [comment]
@StellaASchlotter , please look at https://github.com/opencv/cvat/pull/5524. Do you use docker-compose v2? Could you please remove `version: "3.3" ` from override docker compose file?

@SpecLad , could you please advise?

**Comment by StellaASchlotter** [comment]
Removing the version in the override file works for me. I suggest removing the version in the docs at https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path so that there is no confusion again.

**Comment by SpecLad** [comment]
Thank you for the report. I will fix the docs.
