### ISSUE TITLE
YoloV7 serverless support for automatic annotation

### ISSUE THREAD

**Issue by hardikdava** [opencv/cvat#5548]
It would be great to have support for YoloV7 object detector for automatic annotation. I already created such feature using ONNX backend. Please let me know if it is needed so other can also use it. How can I provide PR for it?

**Comment by zhiltsov-max** [comment]
Hi, thank you for asking! Yes, it would be great to have this model available in CVAT. Please follow the contribution guide [here](https://opencv.github.io/cvat/docs/contributing/). Basically, you just need to create a PR and follow the template. We expect most PRs to include tests and documentation, but in case of models, we don't have a relevant test suite now, so it's not needed.

**Comment by yasakova-anastasia** [comment]
#5552
