### ISSUE TITLE
Mmdetection MaskRCNN serverless support for semi-automatic annotation

### ISSUE THREAD

**Issue by michael-selasi-dzamesi** [opencv/cvat#5551]
I have created a serverless support for semi-automatic annotation using Mmdetection implementation of MaskRCNN, I believe this would be helpful for anyone who would like to use any of Mmdetection's implementations in building a serveless function. Do let me know if it is needed. Thank you

**Comment by zhiltsov-max** [comment]
Hi! In general, the new models are welcomed in CVAT. Currently, we already have MaskRCNN implemented in OpenVINO and Keras. Would this new implementation have any differences?

**Comment by michael-selasi-dzamesi** [comment]
Yes, I have seen those, but the new addition here is mmdetection and not MaskRCNN. Anyone building an object detection, instance segmentation, or panoptic segmentation serverless function using mmdetection can switch out the MaskRCNN I used and replace it with the architectures available on mmdetection. You can check out mmdetection below
https://github.com/open-mmlab/mmdetection

**Comment by julled** [comment]
@michael-selasi-dzamesi i support your request, changing mmdetection algorithms is quite easy, so it should be easy to switch to another algorithm if needed. mmdetection got many StateOfTheArt algorithms which should be interesting to use in CVAT.

where did you implement this?  did you implement this by any chance using the mmdetection model-serve functionality? https://mmdetection.readthedocs.io/en/latest/useful_tools.html#model-serving

**Comment by gedsim** [comment]
> Hi, @michael-selasi-dzamesi, I would love to try MMdetection for CVAT. Do you have a guide/tutorial for that? Thanks!

**Comment by nmanovic** [comment]
https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/
