### ISSUE TITLE
It is very slow when more than 10 people do their job together.

### ISSUE THREAD

**Issue by YuanNBB** [opencv/cvat#5553]
Hi, developer，

It is very slow when more than 10 people do their job together,
This question bothers me very much, how to resolve it?
btw, The memory of the server is enough!

**Comment by nmanovic** [comment]
@YuanNBB , probably you need to describe the issue better. By the description, we cannot help. What is slow?

**Comment by YuanNBB** [comment]
Hi, developer,
 I mean, the system is slow to respond!
for example, drag progress bar in job page ,save annotation.
And the system often fails to jump to next frame.

**Comment by bsekachev** [comment]
@YuanNBB Can you provide screenshot how system fails? 
Did you investigate bandwidth between server and clients? What image resolution do you have? How many objects to you annotate?

**Comment by bsekachev** [comment]
I will close this issue as not answered.
