### ISSUE TITLE
Cannot enter next frame

### ISSUE THREAD

**Issue by YuanNBB** [opencv/cvat#5559]
![1673252630627](https://user-images.githubusercontent.com/119041739/211266006-0be0a84f-3439-49a7-aaf5-cf7792c4793a.jpg)
it cannot enter next frame if keep 'F' down

**Comment by YuanNBB** [comment]
it also cannot jump to frame when input frame number directly 
![image](https://user-images.githubusercontent.com/119041739/211267035-14450cee-06df-457a-9720-ff1b67029fee.png)

**Comment by YuanNBB** [comment]
![image](https://user-images.githubusercontent.com/119041739/211483399-97a29774-997a-404d-9ea3-f92b885c950e.png)
the first frame also cannot show normally when enter job page.

**Comment by bsekachev** [comment]
@YuanNBB 

Is it your local instance or app.cvat.ai? 
Can you share us a failed request details from browser tools (F12 in Chrome, Network tab, Red requests)?

**Comment by YuanNBB** [comment]
1. cvat is installed on docker swarm
2. version: v2.3.0
![image](https://user-images.githubusercontent.com/119041739/211770569-fe8adbed-ea44-4b9d-ad12-072e37f9ac4a.png)

**Comment by bsekachev** [comment]
What can you see in ``docker logs cvat_server``?

**Comment by YuanNBB** [comment]
Hi, i used the way of  connected file share when upload file;
Accoding to the log, seem like cannot find file.
so i use the commond:
![image](https://user-images.githubusercontent.com/119041739/211954636-638bdad2-365a-4383-88b9-12393285a3f1.png)
cannot find any file in this path, but i can enter other jobs.
`
2023-01-12 01:19:09,805 DEBG 'runserver' stderr output:
[Thu Jan 12 01:19:09.804821 2023] [wsgi:error] [pid 148:tid 140151608624896] [remote 172.31.0.2:54454] [2023-01-12 01:19:09,797] INFO cvat.server.task_1: get repository request

2023-01-12 01:19:09,810 DEBG 'runserver' stderr output:
[Thu Jan 12 01:19:09.810095 2023] [wsgi:error] [pid 148:tid 140151608624896] [remote 172.31.0.2:54454] INFO:cvat.server.task_1:get repository request

2023-01-12 01:19:09,835 DEBG 'runserver' stderr output:
[Thu Jan 12 01:19:09.834907 2023] [wsgi:error] [pid 148:tid 140151921424128] [remote 172.31.0.2:54452] INFO:cvat.client.task_1:{"job_id":6,"task_id":1,"client_id":731105,"name":"Load job","time":"2023-01-12T01:16:34.033000Z","payload":{"duration":10624,"frame count":2000,"track count":0,"object count":0,"box count":0,"polygon count":0,"polyline count":0,"points count":0,"cuboids count":0,"tag count":0},"is_active":true,"username":"wangyi"}

2023-01-12 01:19:09,835 DEBG 'runserver' stderr output:
[Thu Jan 12 01:19:09.835274 2023] [wsgi:error] [pid 148:tid 140151921424128] [remote 172.31.0.2:54452] INFO:cvat.client:{"client_id":731105,"name":"Send user activity","time":"2023-01-12T01:19:09.507000Z","payload":{"working_time":10548},"is_active":true,"username":"wangyi"}

2023-01-12 01:19:28,265 DEBG 'runserver' stderr output:
[Thu Jan 12 01:19:28.265460 2023] [wsgi:error] [pid 148:tid 140151921424128] [remote 172.31.0.2:54678] INFO:cvat.client:{"client_id":731105,"name":"Send user activity","time":"2023-01-12T01:19:27.930000Z","payload":{"working_time":18330},"is_active":true,"username":"wangyi"}

2023-01-12 01:19:37,275 DEBG 'runserver' stderr output:
[Thu Jan 12 01:19:37.275234 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712] [2023-01-12 01:19:37,274] ERROR django.request: Internal Server Error: /api/jobs/6/data
[Thu Jan 12 01:19:37.275251 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712] Traceback (most recent call last):
[Thu Jan 12 01:19:37.275254 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Thu Jan 12 01:19:37.275256 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     response = get_response(request)
[Thu Jan 12 01:19:37.275259 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Thu Jan 12 01:19:37.275261 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Jan 12 01:19:37.275263 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Thu Jan 12 01:19:37.275266 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     return view_func(*args, **kwargs)
[Thu Jan 12 01:19:37.275268 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Thu Jan 12 01:19:37.275270 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     return self.dispatch(request, *args, **kwargs)
[Thu Jan 12 01:19:37.275272 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Thu Jan 12 01:19:37.275274 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     response = self.handle_exception(exc)
[Thu Jan 12 01:19:37.275276 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Thu Jan 12 01:19:37.275279 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     self.raise_uncaught_exception(exc)
[Thu Jan 12 01:19:37.275281 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Thu Jan 12 01:19:37.275283 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     raise exc
[Thu Jan 12 01:19:37.275285 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Thu Jan 12 01:19:37.275287 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     response = handler(request, *args, **kwargs)
[Thu Jan 12 01:19:37.275290 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/views.py", line 1646, in data
[Thu Jan 12 01:19:37.275292 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     return data_getter(request, db_job.segment.start_frame,
[Thu Jan 12 01:19:37.275294 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/views.py", line 680, in __call__
[Thu Jan 12 01:19:37.275296 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     buff, mime_type = frame_provider.get_chunk(self.number, self.quality)
[Thu Jan 12 01:19:37.275298 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/frame_provider.py", line 171, in get_chunk
[Thu Jan 12 01:19:37.275300 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     return self._loaders[quality].get_chunk_path(chunk_number, quality, self._db_data)
[Thu Jan 12 01:19:37.275304 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/cache.py", line 32, in get_buff_mime
[Thu Jan 12 01:19:37.275306 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     chunk, tag = self.prepare_chunk_buff(db_data, quality, chunk_number)
[Thu Jan 12 01:19:37.275308 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/cache.py", line 103, in prepare_chunk_buff
[Thu Jan 12 01:19:37.275310 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     writer.save_as_chunk(images, buff)
[Thu Jan 12 01:19:37.275312 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/media_extractors.py", line 624, in save_as_chunk
[Thu Jan 12 01:19:37.275314 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     w, h, image_buf = self._compress_image(image, self._image_quality)
[Thu Jan 12 01:19:37.275316 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/media_extractors.py", line 583, in _compress_image
[Thu Jan 12 01:19:37.275319 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     image = image_path.to_image() if isinstance(image_path, av.VideoFrame) else Image.open(image_path)
[Thu Jan 12 01:19:37.275321 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/PIL/Image.py", line 3131, in open
[Thu Jan 12 01:19:37.275323 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     fp = builtins.open(filename, "rb")
[Thu Jan 12 01:19:37.275325 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712] FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/test/0009936.jpg'

2023-01-12 01:19:37,275 DEBG 'runserver' stderr output:
[Thu Jan 12 01:19:37.275435 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712] ERROR:django.request:Internal Server Error: /api/jobs/6/data
[Thu Jan 12 01:19:37.275440 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712] Traceback (most recent call last):
[Thu Jan 12 01:19:37.275442 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Thu Jan 12 01:19:37.275444 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     response = get_response(request)
[Thu Jan 12 01:19:37.275446 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Thu Jan 12 01:19:37.275449 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Jan 12 01:19:37.275451 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Thu Jan 12 01:19:37.275453 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     return view_func(*args, **kwargs)
[Thu Jan 12 01:19:37.275455 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Thu Jan 12 01:19:37.275457 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     return self.dispatch(request, *args, **kwargs)
[Thu Jan 12 01:19:37.275459 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Thu Jan 12 01:19:37.275461 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     response = self.handle_exception(exc)
[Thu Jan 12 01:19:37.275463 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Thu Jan 12 01:19:37.275465 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     self.raise_uncaught_exception(exc)
[Thu Jan 12 01:19:37.275467 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Thu Jan 12 01:19:37.275469 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     raise exc
[Thu Jan 12 01:19:37.275471 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Thu Jan 12 01:19:37.275474 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     response = handler(request, *args, **kwargs)
[Thu Jan 12 01:19:37.275476 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/views.py", line 1646, in data
[Thu Jan 12 01:19:37.275478 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     return data_getter(request, db_job.segment.start_frame,
[Thu Jan 12 01:19:37.275480 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/views.py", line 680, in __call__
[Thu Jan 12 01:19:37.275482 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     buff, mime_type = frame_provider.get_chunk(self.number, self.quality)
[Thu Jan 12 01:19:37.275484 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/frame_provider.py", line 171, in get_chunk
[Thu Jan 12 01:19:37.275486 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     return self._loaders[quality].get_chunk_path(chunk_number, quality, self._db_data)
[Thu Jan 12 01:19:37.275489 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/cache.py", line 32, in get_buff_mime
[Thu Jan 12 01:19:37.275491 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     chunk, tag = self.prepare_chunk_buff(db_data, quality, chunk_number)
[Thu Jan 12 01:19:37.275493 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/cache.py", line 103, in prepare_chunk_buff
[Thu Jan 12 01:19:37.275495 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     writer.save_as_chunk(images, buff)
[Thu Jan 12 01:19:37.275497 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/media_extractors.py", line 624, in save_as_chunk
[Thu Jan 12 01:19:37.275500 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     w, h, image_buf = self._compress_image(image, self._image_quality)
[Thu Jan 12 01:19:37.275502 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/home/django/cvat/apps/engine/media_extractors.py", line 583, in _compress_image
[Thu Jan 12 01:19:37.275504 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     image = image_path.to_image() if isinstance(image_path, av.VideoFrame) else Image.open(image_path)
[Thu Jan 12 01:19:37.275506 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]   File "/opt/venv/lib/python3.8/site-packages/PIL/Image.py", line 3131, in open
[Thu Jan 12 01:19:37.275508 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712]     fp = builtins.open(filename, "rb")
[Thu Jan 12 01:19:37.275510 2023] [wsgi:error] [pid 148:tid 140151617017600] [remote 172.31.0.2:54712] FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/test/0009936.jpg'`

**Comment by bsekachev** [comment]
You see these errors because files have been removed from share.
By default CVAT does not copy them from file share to internal file system to avoid dublicating. You can configure this behaviour here:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/40690378/214096932-063a9805-2f8a-461c-9474-cf5a69a9aaed.png">

In other jobs you might have some cached data or you copied them when creating. If you want to restore access to this job, please restore the data.
