### ISSUE TITLE
Adding new dataset import to existing project error 409  File with same name already exist

### ISSUE THREAD

**Issue by randubin** [opencv/cvat#5563]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

Project imported

### Current Behaviour

Error 409
Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/projects/1/dataset/, response code: 409, response text: "File with same name already exists", request id: n/a).
<html>
<body>
<div tabindex="-1" class="console-group console-group-messages" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative;"><div tabindex="-1" class="console-message-wrapper console-from-api console-error-level console-selected" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--override-error-border-color); border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: var(--override-error-border-color); --console-color-black:#000; --console-color-red:#a00; --console-color-green:#0a0; --console-color-yellow:#a50; --console-color-blue:#00a; --console-color-magenta:#a0a; --console-color-cyan:#0aa; --console-color-gray:#aaa; --console-color-darkgray:#555; --console-color-lightred:#f55; --console-color-lightgreen:#5f5; --console-color-lightyellow:#ff5; --console-color-lightblue:#55f; --console-color-ightmagenta:#f5f; --console-color-lightcyan:#5ff; --console-color-white:#fff; background-color: var(--override-focused-message-background-color); --override-error-text-color:rgb(200 0 0);"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" aria-label="cvat-app.tsx:357 Error: Request failed with status code 409. &quot;Import job already exists&quot;. Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

e | @ | cvat-app.tsx:357
-- | -- | --
  | showErrors | @ | cvat-app.tsx:368
  | componentDidUpdate | @ | cvat-app.tsx:263
  | ss | @ | react-dom.production.min.js:212
  | vl | @ | react-dom.production.min.js:255
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:19
  | Ua | @ | react-dom.production.min.js:122
  | gl | @ | react-dom.production.min.js:248
  | rl | @ | react-dom.production.min.js:239
  | (anonymous) | @ | react-dom.production.min.js:123
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:19
  | Ua | @ | react-dom.production.min.js:122
  | qa | @ | react-dom.production.min.js:123
  | Ga | @ | react-dom.production.min.js:122
  | al | @ | react-dom.production.min.js:240
  | notify | @ | Subscription.js:16
  | notifyNestedSubs | @ | Subscription.js:88
  | a | @ | Subscription.js:93
  | v | @ | redux.js:296
  | (anonymous) | @ | redux-logger.es.js:832
  | (anonymous) | @ | index.js:20
  | dispatch | @ | redux.js:691
  | (anonymous) | @ | import-actions.ts:147
  | await in (anonymous) (async) |   |  
  | (anonymous) | @ | index.js:16
  | N | @ | import-dataset-modal.tsx:243
  | (anonymous) | @ | import-dataset-modal.tsx:286
  | onFinish | @ | Form.js:74
  | (anonymous) | @ | useForm.js:845
  | Promise.then (async) |   |  
  | Re.submit | @ | useForm.js:840
  | onOk | @ | import-dataset-modal.tsx:318
  | w | @ | Modal.js:90
  | Q | @ | button.js:241
  | s | @ | react-dom.production.min.js:14
  | f | @ | react-dom.production.min.js:14
  | (anonymous) | @ | react-dom.production.min.js:14
  | v | @ | react-dom.production.min.js:15
  | ot | @ | react-dom.production.min.js:52
  | rt | @ | react-dom.production.min.js:51
  | it | @ | react-dom.production.min.js:52
  | pt | @ | react-dom.production.min.js:56
  | j | @ | react-dom.production.min.js:287
  | H | @ | react-dom.production.min.js:19
  | Xt | @ | react-dom.production.min.js:70
  | $t | @ | react-dom.production.min.js:69
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:19
  | Ua | @ | react-dom.production.min.js:122
  | I | @ | react-dom.production.min.js:287
  | qt | @ | react-dom.production.min.js:68

</span></div></div></div></div></div></div><div aria-hidden="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; height: 0px; color: transparent;">﻿</div><div class="source-code" id="console-prompt" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; clear: right; position: relative; margin: 0px 22px 0px 20px;"><div class="widget" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style;"><div class="console-prompt-editor-container" style="box-sizing: border-box; min-width: 0px; min-height: 21px;"><devtools-text-editor style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="cm-editor ͼ1 ͼ2 ͼ4 ͼ5" style="box-sizing: border-box; flex-direction: column; position: relative !important; display: flex !important; color: color: var(--color-text-primary); cursor: auto;"><div aria-live="polite" style="position: absolute; top: -10000px;"></div><div tabindex="-1" class="cm-scroller" style="font-family: var(--source-code-font-family); line-height: 1.2em; height: 22.3958px; overflow-x: auto; position: relative; z-index: 0; display: flex !important; align-items: flex-start !important; font-size: var(--source-code-font-size);"><div spellcheck="false" autocorrect="off" autocapitalize="off" translate="no" contenteditable="true" class="cm-content cm-lineWrapping" role="textbox" aria-multiline="true" aria-label="Console prompt" aria-autocomplete="list" style="margin: 0px; flex-grow: 2; flex-shrink: 1; min-height: 100%; display: block; white-space: break-spaces; overflow-wrap: anywhere; box-sizing: border-box; padding: 4px 0px; outline: none; word-break: break-word; caret-color: black; -webkit-user-modify: read-write-plaintext-only; tab-size: 4;"><div class="cm-line" style="display: block; padding: 0px 2px 0px 4px; caret-color: transparent !important;"><br style="color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: break-spaces; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgba(0, 0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>
Note if I upload to a different project it is uploading with success.
### Steps to Reproduce (for bugs)

1. When i upload the same import task to one project it fails.
1.When I upload the same task to another project it upload fine.
1. All import tasks fail for that project

### Context

Can't upload new imported tasks to a project.
### Your Environment

- Git hash commit (`git log -1`): commit 760f40d3d83c6e7aa0edfc56412a6d9b6070548b (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): v4.11.1.
- Are you using Docker Swarm or Kubernetes?no
- Operating System and version (e.g. Linux, Windows, MacOS): windows
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by KonstantinosDagres** [comment]
Hello. 

We also have the same issue with an ubuntu-based server. Specifically, we updated the CVAT to the latest version (v.2.3.0 from v.2.1.0). 

Before the update we exported backup from all the existing tasks. After the update, we started to import the backup tasks one after the other. In some tasks after the upload process, the CVAT crashed just when the upload had finished. When restarted, this task was not visible to the tasks list. Then we tried to import it again, but CVAT failed to import and this error emerged. After that, we tried to manually create this task and import the annotation zip folder and the result was successful. 

We are still facing this problem and we are looking for the solution.
