### ISSUE TITLE
Manually setting the Z-Order value of each separate annotation

### ISSUE THREAD

**Issue by KiKariJeZZa** [opencv/cvat#5576]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Is there a way to manually set the Z-Order value of each separate annotation? I want to be able to keep my Z-Order values neat, but also have my annotations on separate layers as I am using segmentation. I understand that the "to background" (- key) and "to foreground" (+ key) feature exists, but say for example I have an annotation on Layer -4, and one on Layer 5, if I send Layer 5 "to background" it becomes Layer -5, and when I send Layer -4 "to foreground" it becomes Layer 6.

I am unable to find an issue raised by this in previous posts, or online in the CVAT documentation, so I am wondering if there is a way to do this? 

Thanks.

**Comment by bsekachev** [comment]
Hi,
Dublicate of #3942
