### ISSUE TITLE
Regarding problem import JSON file for keypoint detection (No data point store in JSON)

### ISSUE THREAD

**Issue by jishan900** [opencv/cvat#5577]
After finishing the label when I tried to export JSON for the keypoint detection as [MS COCO Keypoints Detection] it exports the JSON but unfortunately, there is no information about the data labeling in that JSON. For example, I have 4 key points in an image, then after labeling definitely in JSON there will be 4 different point coordinates (x,y) information. But, in JSON there is nothing information about keypoint. I think it is a great problem with the labeling for the keypoint. I hope you will check it.

**Comment by zhiltsov-max** [comment]
A duplicate of https://github.com/opencv/cvat/issues/5831
