### ISSUE TITLE
Would be very helpful to have a box for free hand text for each task

### ISSUE THREAD

**Issue by GeorgePearse** [opencv/cvat#5580]
### My actions before raising this issue
Searched for other similar feature requests.

### Expected Behaviour
A box underneath where the labels are define on the task view which enables you to add free text comments.

### Context
Every day I autolabel all of the available data from the previous day but sometimes there's some caveat or problem, e.g. some camera feed was broken or lighting was very bad or similar. CVAT would be the best place for me to record this, with whatever frames were available and a quick comment stating why that data shouldn't be used in training or similar. I've even considered storing this information as a png and sending that as workaround.

**Comment by GeorgePearse** [comment]
Yes but the ideal scenario for me is that the frames remain there, almost like documentation of the problem. So that another Engineer can view and understand it, but maybe I'm torturing the desired use of CVAT.

**Comment by bsekachev** [comment]
"the frames remain there", actually, they stay. Just marked as deleted.

You can always toogle showing removed frames:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/40690378/212117862-4f5372b0-f497-40d1-8f3c-d3ce5b57a18c.png">

Another option with text is leaving an issue (but available only in review mode):
<img width="936" alt="image" src="https://user-images.githubusercontent.com/40690378/212118394-16e9efce-80c9-490f-8ba8-33f1696cd1b9.png">
<img width="258" alt="image" src="https://user-images.githubusercontent.com/40690378/212118456-2b4f50ec-8983-46a2-897c-f4fe04b9f3ca.png">

**Comment by GeorgePearse** [comment]
Other use cases:

* Adding small task specific instructions for labellers.
* Adding a description of that dataset, e.g. particularly dark

**Comment by bsekachev** [comment]
For the latest two use-cases you provided, ``Issue tracker`` field exists.

<img width="149" alt="image" src="https://user-images.githubusercontent.com/40690378/212948663-5714c244-5a97-4556-87e7-300d37b9b980.png">

It can be a link to google docs for example with any specification. Integration of something like markdown specification into CVAT is also solution, but even if we start implementing it, it will take some time. 

So, I just suggested a quick solution.

**Comment by bsekachev** [comment]
Related #3680
