### ISSUE TITLE
Python SDK client.tasks.create_from_data does not work

### ISSUE THREAD

**Issue by PMazarovich** [opencv/cvat#5584]
### Current Behaviour
Try upload the remote file into cvat with this code:
```
with Client('localhost:8080') as client:
    client.login(('test', 'test'))
    task_spec = {
        "name": "testNAME",
        "project_id": 1,
        "assignee_id": 1,
    }
    client.tasks.create_from_data(spec=task_spec, resource_type=ResourceType.REMOTE, resources=["http://192.168.48.12:85/blabalbla.mp4"])
```
You will get url in additional quotes, that leads to an error in cvat server def _validate_url(url) failure as url looks like '"http://192.168.48.12:85/blabalbla.mp4"'.

### Your Environment
CVAT 2.2.0

**Comment by bsekachev** [comment]
Hi, @PMazarovich 

I am not sure that ``192.168.48.12:85`` is reachable from a docker container?

**Comment by PMazarovich** [comment]
Hello, @bsekachev , I am sure, this address is reachable. I can upload video from this address using "remote sources" from UI

**Comment by bsekachev** [comment]
Okay, let's mark it as a bug, need to investigate. 

@zhiltsov-max Do you have some ideas why it does not work with SDK? Can it be related with that Client was initialized by 'localhost:8080'?

**Comment by zhiltsov-max** [comment]
@PMazarovich, could you please specify the SDK version?

**Comment by PMazarovich** [comment]
@zhiltsov-max , 2.1.0.post1

**Comment by zhiltsov-max** [comment]
Could you please try to upgrade to the latest version with `pip install --upgrade cvat-cli`, if possible? Note that the latest release is for 2.3.0 and there was no dedicated release for 2.2.0, so there might be some issues when using it with 2.2.0. In that case, you may need to generate the SDK from the 2.2.0 release branch, the instructions are [here](https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/).

**Comment by PMazarovich** [comment]
@zhiltsov-max , @bsekachev after updating cli and sdk all worked
Thanks!
