### ISSUE TITLE
Hidden tasks are not shown

### ISSUE THREAD

**Issue by manybodycpa** [opencv/cvat#5588]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

While a task is being generated, a popup appears:

"Some tasks are temporary hidden because they are not fully created yet | Show all"

Clicking on "Show all" should show the task list including the hidden tasks.

### Current Behaviour

Nothing happens when clicking on "Show all".

### Possible Solution

Things worked fine in version 1.4. Moreover, the popup contains a grammar error, it should read "temporarily" rather than "temporary".

### Steps to Reproduce (for bugs)

Create a task. While the video is still being uploaded, refresh the task list.

### Your Environment

- Git hash commit (`git log -1`): 119a27bbd6e589d140d49bc5c3f9098aee2dfff9
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.21
- Operating System and version (e.g. Linux, Windows, MacOS): Linux

**Comment by bsekachev** [comment]
Hi @manybodycpa 

This probably was fixed in https://github.com/cvat-ai/cvat-opencv/pull/100
Should work for release 2.2+
