### ISSUE TITLE
task creation error for videos ONLY from attached cloud storage, manifest has been verified!

### ISSUE THREAD

**Issue by j-gruber1** [opencv/cvat#5589]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour

Tested on both ap.cvat.ai and on a self-hosted CVAT (versions are both latest at time of writing).

When creating a task, I am unable to select a cloud attached video file. I have tried multiple mp4 video files, including the attached.

Appears to only be an issue for videos and not images as I am able to load images from the same attached cloud storage. manifest.jsonl is created using the create.py script and check for correctness. Also used a manually composed manifest.json which did not solve the issue.

When attempting to select the video manifest from cloud storage it throws the below error without additional details.
![image](https://user-images.githubusercontent.com/19680071/212444638-2398db21-cadb-4d14-9726-d737a85b2b47.png)

The attached google cloud bucket contains these files.
![image](https://user-images.githubusercontent.com/19680071/212444684-e29f2011-d391-4519-b629-73873ea364c0.png)

### Possible Solution

Unknown

### Context

Have been setting up a production deployment of CVAT for commercial purposes.

This issue means I can only use local storage which often fails (mp4 used are >100MB each)

### Your Environment
https://github.com/opencv/cvat/commit/31f0578220d9cd9d20136cf0bde40996da334946
Server version: 2.4
Core version: 7.4.1
Canvas version: 2.16.1
UI version: 1.46.1

Video used for testing attached.

index.json
`{"0":109,"1":176,"2":245,"3":316,"4":387,"5":458,"6":529,"7":600,"8":671,"9":742,"10":813}`

manifest.json
`{"version":"1.0"}
{"type":"video"}
{"properties":{"name":"example.mp4","resolution":[480,270],"length":901}}
{"number":0,"pts":0,"checksum":"4e39e1ef1dc516399f84b5892d57c3ca"}
{"number":90,"pts":90,"checksum":"e4698e8c755e64dc7a8034d1ee4584f0"}
{"number":180,"pts":180,"checksum":"f9f9f2da1dad2280d509a26ed74ec13a"}
{"number":270,"pts":270,"checksum":"6f44e76475d4ce3f520ac95a92180122"}
{"number":360,"pts":360,"checksum":"35d04fd515ebbede60e3ef96b829d087"}
{"number":450,"pts":450,"checksum":"582787855a2334e6b194023d0a1e86f7"}
{"number":540,"pts":540,"checksum":"4525ac36c3930ccc2a292f22fbe1dd5e"}
{"number":630,"pts":630,"checksum":"cb14fe95bfc57bc3f7fea82a7ba9f8b8"}
{"number":720,"pts":720,"checksum":"1a26aa9ddedc4d07fea8bafd97d1be0f"}
{"number":810,"pts":810,"checksum":"71b1842c4feab3a53e80221e2f4abc40"}
{"number":900,"pts":900,"checksum":"19c66ae7d20e8b6b13e30e6e503be7b4"}`

https://user-images.githubusercontent.com/19680071/212445314-9ad1b7a8-332d-4471-b1d0-9d2cac18ac89.mp4

**Comment by j-gruber1** [comment]
Correct me if wrong, but it appears this is yet to be implemented? Could you please propose a workaround for myself and future readers?

I'd also suggest updating the UX from "Could not fetch cloud storage data" to something like "Fetching videos from cloud storage data is not supported."

(https://github.com/opencv/cvat/projects/32#card-79111195)

**Comment by bsekachev** [comment]
Dublicate of #4460
