### ISSUE TITLE
no models/analytics tabs

### ISSUE THREAD

**Issue by nicklhh** [opencv/cvat#5592]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

i install via docker in windows10 and i cant find AI Tools & model/analytics tabs on top

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by azhavoro** [comment]
https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
https://opencv.github.io/cvat/docs/administration/advanced/analytics/
