### ISSUE TITLE
Storage space is not recovered when deleting projects

### ISSUE THREAD

**Issue by jcorrochanoj** [opencv/cvat#5595]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When deleting projects, the data related to the tasks of this one is eliminated.

### Current Behaviour
When a project is deleted, data occupied is not recovered.

### Steps to Reproduce (for bugs)

1. Check free space in the machine where CVAT is running
2. Create a project and upload tasks with data
3. Check again the free space to check that now there is less
4. Delete the project
5. Check again the free space to check that space is not recovered

### Your Environment
- CVAT VERSIONS: 
    - Server version: 2.2
    - Core version: 5.0.1
    - Canvas version: 2.13.2
    - UI version: 1.37.0
- Docker version `docker version` (e.g. Docker 17.0.05):
- Operating System and version: EC2 instance on AWS, details:
    - NAME="Amazon Linux"
    - VERSION="2"
    - ID="amzn"
    - ID_LIKE="centos rhel fedora"
    - VERSION_ID="2"
    - PRETTY_NAME="Amazon Linux 2"
    - ANSI_COLOR="0;33"
    - CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"

### Context

Hello,

Trying to clean up and recover space on the machine where I have CVAT, I have deleted old labeling projects. However, I have seen that after deleting the projects nothing of space has been recovered. 

I have found some related issues, in which the same situation was commented but when deleting tasks. I have seen that this BUG was solved and I have been able to verify that when deleting tasks the space is recovered, but not with the projects. In this case, I have not found any issue directly related.

Related issues (but with tasks):
- https://github.com/opencv/cvat/issues/1925
- https://github.com/opencv/cvat/issues/2859

What could I do to recover this space occupied by 'ghost' projects?
I am not in the latest version of CVAT, so if someone can reproduce this problem in a newer version to exclude that it is a problem already solved, I would appreciate it.

**Comment by bsekachev** [comment]
@jcorrochanoj 

Thank you for the report. 
I can submit that ``/projects/<id>`` exists after removal, ``/data/<task_id>`` where task_id is a task from a removed project also exists after removal, but ``/tasks/<task_id>`` is removed.
