### ISSUE TITLE
CVAT should set a custom User-Agent for its HTTP requests

### ISSUE THREAD

**Issue by SpecLad** [opencv/cvat#5598]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When you create a task with remote sources and specify an image URL, CVAT should make HTTP requests with a custom User-Agent header (for example, `CVAT/2.3.0 (https://cvat.ai/)`). Same for any other requests that CVAT makes (such as webhooks).

### Current Behaviour

It uses a generic User-Agent header (currently `python-requests/2.26.0`).

### Possible Solution

Self-explanatory.

### Steps to Reproduce (for bugs)

1. Go to <https://app.cvat.ai/tasks/create>.
1. Fill out mandatory fields.
1. Select "Remote sources" and enter `https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Bicolor_he-cat.JPG/1280px-Bicolor_he-cat.JPG` into the textbox.
1. Press "Submit & Open" and watch it fail (see below for an explanation)

### Context

I was trying to create a test task using images from Wikipedia, but it wasn't working. I eventually found that the Wikimedia Foundation has a [user agent policy](https://meta.wikimedia.org/wiki/User-Agent_policy) that prohibits requests that use generic User-Agent strings. 

I think we should comply with this policy. It would allow downloading images from Wikipedia (and any websites with similar policies), and it would be helpful for website administrators who want to know who downloads their images.

### Your Environment

Reproduced with app.cvat.ai.

**Comment by zhiltsov-max** [comment]
I think we should also use a custom user-agent in SDK. Currently, there we have `OpenAPI-Generator/2.0-alpha/python`.
