### ISSUE TITLE
Video file name / url in output file

### ISSUE THREAD

**Issue by BrunoLansacSBD** [opencv/cvat#56]
Hi,
First of all, thanks for the tool. It works great!

When I annotate video files, and for that purpose I create an annotation task per video, I cannot seem to find any reference to the original video name / path / url inside the task itself. Moreover, inside the output XML file generated after annotating, there are no references to that information at all. The only thing I can find is the url of the corresponding task, but I don't think I can extract from that url the information I'm looking for (i.e. the name of the video).

The only workaround I can think of is naming the annotation task after the video itself, and do the same for the xml file. However, I don't really like that solution. The ideal solution for me would be to have video file name inside the xml file.

Am I missing something? Please point me in the right direction. 

Thank you very much

**Comment by nmanovic** [comment]
Hi @BrunoLansacSBD ,

I believe it can be useful information. Could you please prepare a merge request for the feature?

**Comment by BrunoLansacSBD** [comment]
Hi @nmanovic ,

Could you please give me a hint on where in the code should I implement that? I'm sure it is by far easier for you to point me in the right direction than me going through all the code.

Thanks

**Comment by nmanovic** [comment]
Hi @BrunoLansacSBD ,

I believe you need to modify 'dump' function here: https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/annotation.py#L1636

Also it seems that we don't have name of video file into DB. There are two solutions:
- Add it to DB (preferable) - https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/task.py#L626
- Find it in upload directory - https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/task.py#L513

**Comment by edumotya** [comment]
Still cannot find video filename at dumped xml annotations:

```
<?xml version="1.0" encoding="utf-8"?>
<annotations>
  <version>1.1</version>
  <meta>
    <task>
      <id>17</id>
      <name>TASK_NAME</name>
      <size>780</size>
      <mode>interpolation</mode>
      <overlap>5</overlap>
      <bugtracker></bugtracker>
      <flipped>False</flipped>
      <created>2019-05-07 17:18:40.352595+03:00</created>
      <updated>2019-05-07 17:18:40.352623+03:00</updated>
      <labels>
        <label>
          <name>car</name>
          <attributes>
            <attribute>
              <name>color</name>
              <mutable>False</mutable>
              <input_type>select</input_type>
              <default_value>blue</default_value>
              <values>blue
</values>
            </attribute>
          </attributes>
        </label>
        <label>
          <name>red</name>
          <attributes>
          </attributes>
        </label>
      </labels>
      <segments>
        <segment>
          <id>25</id>
          <start>0</start>
          <stop>779</stop>
          <url>http://xxxxxx:8080/?id=25</url>
        </segment>
      </segments>
      <owner>
        <username>ADMIN</username>
        <email>xxxx@gmail.com</email>
      </owner>
      <original_size>
        <width>1920</width>
        <height>1080</height>
      </original_size>
    </task>
    <dumped>2019-05-07 17:47:21.629405+03:00</dumped>
  </meta>
</annotations>
```

**Comment by nmanovic** [comment]
@azhavoro , could you please slightly improve your patch and implement the feature?

**Comment by nmanovic** [comment]
It is already fixed in develop branch.
```
    </task>
    <dumped>2019-08-02 17:16:00.652366+03:00</dumped>
    <source>zy4VPKKrS+2t4XQYOM28jQ.MOV</source>
  </meta>
```

**Comment by EyescannerJE** [comment]
Is this solved? I can't see the name of the file anywhere in a "CVAT for video 1.1" export.
Are people using CVAT with out this feature? I don't understand how that is possible?
