### ISSUE TITLE
Cannot connect to localhost:8080, got "404 page not found"

### ISSUE THREAD

**Issue by waklose** [opencv/cvat#5602]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The login screen should show up at localhost:8080, after running docker compose up -d.

### Current Behaviour

"404 page not found" shows up.

### Possible Solution

I have notices from earlier issues that they use v1 of docker compose (i.e. the commands are called using "docker-compose" instead of "docker compose" which is what is used in the installation guide).

### Steps to Reproduce (for bugs)

1. Followed the installation guide for Ubuntu 18.04

### Your Environment

- Git hash commit (`git log -1`): 
commit a8052fc70d34ffc760b890d05457aabdff3fbca1 (HEAD -> develop, origin/develop, origin/HEAD)
Author: vainkop <vainkop@gmail.com>
Date:   Wed Jan 18 10:34:31 2023 +0300

    Update upgrade_guide.md (#5585)
    
    Add How to upgrade CVAT from v2.2.0 to v2.3.0
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.9
- Are you using Docker Swarm or Kubernetes? Only using docker compose.
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Other diagnostic information / logs:

Terminal output:
[docker_cvat_terminalOutput.txt](https://github.com/opencv/cvat/files/10455055/docker_cvat_terminalOutput.txt)
Logs (docker logs cvat_server): 
[cvat.log](https://github.com/opencv/cvat/files/10455532/cvat.log)

**Comment by waklose** [comment]
Hi, thanks for a quick response.

Here it is: [ps_output.txt](https://github.com/opencv/cvat/files/10463870/ps_output.txt)

**Comment by bsekachev** [comment]
@waklose 

I see these 3 containers are restarting:

```
ac06dd0f852f   cvat/server:dev                       "/usr/bin/supervisor…"   2 minutes ago   Restarting (2) 38 seconds ago                                                                                                  cvat_worker_export
398a54f91dd5   cvat/server:dev                       "/usr/bin/supervisor…"   2 minutes ago   Restarting (2) 43 seconds ago                                                                                                  cvat_worker_import
2ba86a64bbc9   cvat/server:dev                       "/usr/bin/supervisor…"   2 minutes ago   Restarting (2) 36 seconds ago                                                                                                  cvat_worker_annotation
```

Can you share logs from them?

**Comment by waklose** [comment]
When I try `docker logs <container_id>` on those 3 containers I get multiple copies of the same error message:
[error_from_36d693c7323b.txt](https://github.com/opencv/cvat/files/10464248/error_from_36d693c7323b.txt)

I also tried with the flags --follow and --since, and I get expected output from the other containers.

**Comment by azhavoro** [comment]
```
traefik                 | time="2023-01-19T08:36:12Z" level=error msg="Failed to retrieve information of the docker client and server host: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version\": dial unix /var/run/docker.sock: connect: permission denied" providerName=docker
```

this is the reason

**Comment by waklose** [comment]
Thank you, however it does not seem to be the only problem. After giving permission the new terminal output is: 
[terminal_output#2.txt](https://github.com/opencv/cvat/files/10464601/terminal_output.2.txt). And those same 3 containers mentioned by @bsekachev are still having trouble.
