### ISSUE TITLE
WSL2 cvat error nuclio openvino python3: no such file or directory

### ISSUE THREAD

**Issue by k-spit** [opencv/cvat#5603]
### My actions before raising this issue
- [✓] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [✓] Searched [past issues](/issues)

### Expected Behaviour
Deploy new serverless function according to [opencv documentation](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/).

### Current Behaviour
The path `serverless/common/` was mounted into the container as a volume. Double checked that `serverless/common/openvino/python3` is executable. See the following log.

```
2023-01-19 12:07:01 23.01.19 11:07:01.491 sor.http.w0.python.logger (D) Running wrapper {"command": "/opt/nuclio/common/openvino/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-cf4i8ld244se6fm5e0vg.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger --decode-event-strings"}
2023-01-19 12:07:01
2023-01-19 12:07:01 Error - fork/exec /opt/nuclio/common/openvino/python3: no such file or directory
2023-01-19 12:07:01     ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
2023-01-19 12:07:01
2023-01-19 12:07:01 Call stack:
2023-01-19 12:07:01 Can't run wrapper
2023-01-19 12:07:01     ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
2023-01-19 12:07:01 Failed to run wrapper
2023-01-19 12:07:01     ...//nuclio/pkg/processor/runtime/rpc/abstract.go:106
2023-01-19 12:07:01 Failed to start runtime
2023-01-19 12:07:01     /nuclio/pkg/processor/worker/factory.go:100
2023-01-19 12:07:01 Failed to create worker
2023-01-19 12:07:01     /nuclio/pkg/processor/worker/factory.go:119
2023-01-19 12:07:01 Failed to create workers
2023-01-19 12:07:01     /nuclio/pkg/processor/worker/factory.go:129
```

### Possible Solution

Tried provided solutions mentioned in #5205, #2820, #5351 with no success.
We tried to build the docker image for dextr on our own writing a Dockerfile. When deploying it with `nuctl` also 
```
Error - fork/exec /opt/nuclio/common/openvino/python3: no such file or directory
                          ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
```
occured.

### Steps to Reproduce (for bugs)

1. following the opencv documentation [Semi-automatic and Automatic Annotation](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/).
2. If the following `nuctl`command is run the mentioned problem occurs.
```
nuctl deploy --project-name cvat \
 --path serverless/openvino/dextr/nuclio \
 --volume `pwd`/serverless/common:/opt/nuclio/common \
 --platform local
```

### Your Environment

- latest develop branch or release branch v2.2.0 in git (no differences regarding the error trace) :
- Docker version `docker version v20.10.22`:
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version: Windows 10 Pro 21H2 19044.2486
- WSL version: 2
- Other diagnostic information / logs: cvat container log [fulllog.txt](https://github.com/opencv/cvat/files/10457006/fulllog.txt)

**Comment by bsekachev** [comment]
Hi, @k-spit 

It is a known problem with WSL. Unfortunately we didn't investigate a root cause yet. If you can help, would be great.  
Also you can try to use a virtual machine instead, for example I am using VMWare on Windows 10 with Ubuntu 20 and nuclio functions work well.

**Comment by Fafa87** [comment]
I am having the same problem and have tried a lot of various versions and still the effect is the same : /

**Comment by Fafa87** [comment]
Well, I put up Ubuntu on Oracle VM VirtualBox and got to the same result:
```
Error - fork/exec /opt/nuclio/common/openvino/python3: no such file or directory

    ...//nuclio/pkg/processor/runtime/rpc/abstract.go:239
```

![image](https://user-images.githubusercontent.com/9865688/216852672-88d82529-97a4-40ff-849e-2bdac60d0a0c.png)

**Comment by Fafa87** [comment]
Above I used the repo downloaded clone on Windows (and accessed as shared folder). 
But when I checkout a clean repo and purged entire repo it **worked**! I will try to track it down - perhaps it is something silly :)

**Comment by Fafa87** [comment]
@k-spit It seems that the problem is caused by getting the repo with CRLF. 
You can try cloning it with LF endline and it should run smoothly as it does for me now.
It would be great to have double confirmation that it was indeed the issue.

@bsekachev FYI ^

**Comment by bsekachev** [comment]
@k-spit Could you please try advice from @Fafa87?

**Comment by k-spit** [comment]
@Fafa87 Do you mean when git cloning ?

**Comment by Fafa87** [comment]
Yes, when you clone git normalizes the endlines. You have to change that setting before making a clone:
`git config --global core.autocrlf input`  
`git config --global core.eol lf`

Those worked for me but check endlines manually before installing.

**Comment by k-spit** [comment]
@Fafa87 that solution did it. Thank you :)
