### ISSUE TITLE
How to export segmentation result in polygon format?

### ISSUE THREAD

**Issue by saka3324** [opencv/cvat#5604]
I want to annotate images for my segmentation project and export in polygon style.
I exported alomost all formats available but still don't understand which format is suitable for my case.
Is there any format similar to Labelme, which return segmentation results as polygon for each labels.

Thank you.

**Comment by Saharkakavand** [comment]
How did you solve this task?

**Comment by saka3324** [comment]
Hi, 
just export COCO format and put it into Roboflow, URL down bellow, and you can convert it any format as you want, like YOLO.
I wish this can help you.
https://roboflow.com/
