### ISSUE TITLE
Webpack error, development environment

### ISSUE THREAD

**Issue by MPiecuch** [opencv/cvat#5605]
Hello, 

I am trying to prepare developement environment according to https://opencv.github.io/cvat/v2.3.0/docs/contributing/development-environment/. In the end after the setup and installation part when I am trying to launch CVAT using this command

`yarn run start:cvat-ui`

I get errors like this

`<e> [webpack-dev-server] [HPM] Error occurred while proxying request 10.130.7.252:3000/api/server/health/?format=json&org= to http://localhost:7000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)`

I was trying to launch it on WSL1 with Ubuntu 18.04, WSL2 Ubuntu 20.04, and Ubuntu 22.04 and pure Ubuntu 22.04
Is it a problem with a webpack version or something else?

Thanks.

**Comment by bsekachev** [comment]
@MPiecuch 

Hi, be sure you have run CVAT server part. As you can see, it cannot reach localhost:7000.

**Comment by MPiecuch** [comment]
Thanks a lot!.

Now everything is up and running but there are some problems with openpolicyagent container. I ran it as it is written in manual but in logs I get:

`{"level":"error","msg":"Bundle load failed: request failed: Get \"http://host.docker.internal:7000/api/auth/rules\": dial tcp: lookup host.docker.internal on 8.8.8.8:53: no such host","name":"cvat","plugin":"bundle","time":"2023-01-20T08:26:37Z"}`

**Comment by bsekachev** [comment]
Try to run Open Policy Agent this way:

``docker run -d --rm  --name cvat_opa_debug -p 8181:8181 -v ${PWD}/cvat/apps/iam/rules:/rules --network=host openpolicyagent/opa:0.45.0-rootless     run --server --set=decision_logs.console=true /rules``

**Comment by MPiecuch** [comment]
Thanks, this works.

In the meantine I figured out similar solution:
`docker run -d --rm --net=host --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.34.2-rootless run --server --set=decision_logs.console=true --set=services.cvat.url=http://localhost:7000 --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules `

I'm closing this task, thanks for help.
