### ISSUE TITLE
Allow more than 5 manifests per storage

### ISSUE THREAD

**Issue by muhammadAgfian96** [opencv/cvat#5628]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi,
i integrate use aws s3 as cloud storage, and adding more manifest.jsonl but limited for 5 manifest.jsonl file for one bucket...
we just have one bucket for putting all our dataset in different project. and my strategy is putting manifest.jsonl in every projects,  it seems hard to update manifest.jsonl... 
is there efficient way to update manifest.jsonl?

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): Linux, self-hosted

**Comment by Marishka17** [comment]
Was fixed in https://github.com/opencv/cvat/pull/5660
