### ISSUE TITLE
`segment_size` for task creation not used

### ISSUE THREAD

**Issue by julled** [opencv/cvat#5630]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I want to segment tasks via SDK just like in the UI

### Steps to Reproduce (for bugs)

1. Add a task via SDK
1. add data_params
```
data_params = {
    "image_quality": 85,
    "segment_size": 4
}

```
1. no split of the data done

### Expected Behaviour

New created task will split up the images into segments like in the UI

### Current Behaviour

No split done, segment_size ignored in code (not 100% sure if this is the right place actually)

https://github.com/opencv/cvat/blob/5a9858cc5224a5ad7b18a2f18679f0e47274de4e/cvat-sdk/cvat_sdk/core/proxies/tasks.py#L87

### Possible Solution

Add a segment_size to the task creation `data_params`

### Context

I want to segment tasks via SDK just like in the UI

### Your Environment

cvat2.3  & cvat-sdk2.3 & debian

**Comment by zhiltsov-max** [comment]
Hi, this parameter should be specified in the [task creation parameters](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/models/task-write-request/), not in the [data parameters](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/models/data-request/).

**Comment by julled** [comment]
Thanks, this works!
I didnt see this.
