### ISSUE TITLE
No Endpoint to create user

### ISSUE THREAD

**Issue by MauroRibeiroHV** [opencv/cvat#5636]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

I was trying to create users programmatically but there is no endpoint in swagger to do it.

### Steps to Reproduce (for bugs)

1. Open CVAT Swagger
1. On User section, no POST to create user
1.
1.

### Expected Behaviour
I expected a way to create new users

### Current Behaviour
No way to create users

### Possible Solution
Add endpoint to create users

### Context
The need to create some fixed users in various environments

**Comment by bsekachev** [comment]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/40690378/220954975-9a94f29c-cbdd-49eb-85e4-5f4a908964ea.png">
