### ISSUE TITLE
Connecting a task with a dataset repository [GitHub]

### ISSUE THREAD

**Issue by DP1701** [opencv/cvat#5637]
Hello,

I would have a question when creating a task and linking it to a dataset repository. I wanted to create a test task with an image and specify the URL:

Dataset repository URL
```
https://github.com/DP1701/testAnno.git [annotation.zip]
```

Is this correct? Anyway I get the error message:

Could not create the task

Error: Request failed with status code 403. {"detail": "You do not have permission to perform this action."}.

From the [instructions](https://opencv.github.io/cvat/docs/manual/basics/create_an_annotation_task/#create-a-task) I don't know if I have to specify anything special. I don't get the SSH key displayed either.

Does the repository have to be public?

**Comment by DP1701** [comment]
@zhiltsov-max Is there a more detailed description of how to do this connection with a github account?

**Comment by zhiltsov-max** [comment]
Hi, there's no documentation on this functionality, unfortunately, but everything looks correct. Could you please add more details about the server, the user and the repository? I need to double check about private repositories.

**Comment by DP1701** [comment]
@zhiltsov-max 
Hi, 

I am currently using the server version 2.4 and have the role "Admin" on the server. 
On github I have simply created a repo that is public.  

[https://github.com/DP1701/testAnno](https://github.com/DP1701/testAnno)

Maybe something still needs to be unlocked on github?

Neither with https nor with SSH the connection works. 

Do you need more information?

![Bildschirmfoto 2023-02-24 um 10 52 57](https://user-images.githubusercontent.com/68444979/221149030-c8982906-0dc5-4335-b750-0463b6ad0e23.png)

**Comment by DP1701** [comment]
@zhiltsov-max 

Have you been able to verify that perhaps? 

I have one more question because I noticed this. 
Is it possible to share a project with multiple persons but they don't have rights to create projects. 
For example, I have an organization where the persons are supposed to make annotations as workers. But they should also be able to see each other's work to know how certain objects are annotated. So preferably the complete project with the tasks.

So far I only see the possibility that I have to classify them as maintainers within an organization. But they also get the rights to create projects and assign them to others.

**Comment by bsekachev** [comment]
Closed as outdated. If still relevant, please, reopen.
