### ISSUE TITLE
A more efficient labeling method for polyline

### ISSUE THREAD

**Issue by 315386775** [opencv/cvat#5640]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When the mouse is placed on the polyline, the polyline can be selected and moved, and there is no need to move to the endpoint of the line. This expected operation is similar to the new rectangle labeling.

Fig1. move freely the rectangle when the mouse is placed on the rectangle
![20230128110807](https://user-images.githubusercontent.com/12441747/215239086-5d069a9b-97fb-44a5-a166-492a53da8eb8.jpg)
Fig1. cannot move the ployline when the mouse is placed on the ployline
![20230128110852](https://user-images.githubusercontent.com/12441747/215239088-8b3ff220-af7e-4300-bd15-0f6f2af7f3ab.png)

**Comment by bsekachev** [comment]
"Pinned" property is default "true" for polylines. 
If you want to move polylines, first uncheck this property. 

<img width="230" alt="image" src="https://user-images.githubusercontent.com/40690378/216945636-896ed4d9-a131-4f36-a780-6e8499822769.png">
