### ISSUE TITLE
2.3.0 helm chart dependencies upgrade version 

### ISSUE THREAD

**Issue by xhsbs** [opencv/cvat#5643]
### Current Behaviour
switch to v2.3.0
```sh
git checkout v2.3.0
cd helm-chart
helm dependency update
```

Error: can't get a valid version for repositories postgresql. Try changing the version constraint in Chart.yaml
![image](https://user-images.githubusercontent.com/123819777/215483794-b183a331-2564-4b5d-b0bf-28b4b90c77fb.png)

###  Possible Solution 
update Chart.yaml dependencies postgresql version from 10.16.* to 12.1.*

**Comment by bsekachev** [comment]
@azhavoro Could you please look?

**Comment by SpecLad** [comment]
This was fixed in #5505.
