### ISSUE TITLE
403 not authorized for Automatic Annotations without an organization

### ISSUE THREAD

**Issue by ruckc** [opencv/cvat#5664]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. deploy cvat locally w/ serverless
1. deploy yolov5 or mask-rcnn
1. login to cvat with new user
1. create project & task
1. Try to automatic annotate
1. receive
> Could not infer model for the [task 42](http://localhost:8080/tasks/42)
> Error: Request failed with status code 403. {"detail":"not authorized"}.

### Expected Behaviour
Without an organization, and logged in as a superuser, I'd assume the logic would allow executing lambda methods.

### Current Behaviour
cvat_opa outputs `{"bundles":{"cvat":{}},"decision_id":"b9ab9b90-5fe5-4698-b03e-339d176c4550","input":{"auth":{"organization":null,"user":{"id":1,"privilege":"user"}},"resource":null,"scope":"call:offline"},"labels":{"id":"a71046a3-34b8-4deb-8b22-4b2ac0fef8f4","version":"0.45.0"},"level":"info","metrics":{"counter_server_query_cache_hit":1,"timer_rego_input_parse_ns":53400,"timer_rego_query_eval_ns":333300,"timer_server_handler_ns":442500},"msg":"Decision Log","path":"lambda/allow","requested_by":"172.20.0.12:53006","result":false,"time":"2023-02-02T20:59:53Z","timestamp":"2023-02-02T20:59:53.822375882Z","type":"openpolicyagent.org/decision_logs"}`
cvat_server logs `WARNING django.request: Forbidden: /api/lambda/requests`

### Possible Solution
Support single user CVAT to execute lambda methods by default

### Context
Can't use automatic annotations

### Your Environment
- Git hash commit (`git log -1`): commit 4df7c4c20889e6981d3ea6f257fd24be2532c094 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 20.10.23
- Are you using Docker Swarm or Kubernetes? Plain Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Linux via WSL2
- Code example or link to GitHub repo or gist to reproduce problem:

**Comment by bsekachev** [comment]
Hi @ruckc 

For superuser I have:
```"user":{"id":1,"privilege":"admin"}}```

But what you provided is:
```"user":{"id":1,"privilege":"user"}```

So, are you sure you are a superuser?

**Comment by ruckc** [comment]
Shouldn't the initial user be created with admin?

**Comment by bsekachev** [comment]
No, you can create admin via django command: ``python manage.py createsuperuser``.

**Comment by bsekachev** [comment]
I hope you solved the problem. I will close it. Do not hesitate to reopen if any questions.
