### ISSUE TITLE
Could not fetch projects  Open the Browser Console to get details

### ISSUE THREAD

**Issue by kkhxx** [opencv/cvat#5666]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Expected Behaviour

See projects, tasks, jobs

### Current Behaviour

![1](https://user-images.githubusercontent.com/48484812/216554234-355c2811-0a8b-47a2-9b1d-7f282c232fd6.PNG)

Could not fetch projects

Open the Browser Console to get details

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):20.10.22
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Windows
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
![2](https://user-images.githubusercontent.com/48484812/216554723-8c8e5512-5af3-4c1d-b0b3-dcc0b9633412.PNG)
![3](https://user-images.githubusercontent.com/48484812/216554738-3a51a58a-60ca-4861-9941-5802010af5f7.PNG)

    </details>

**Comment by kkhxx** [comment]
no in ubuntu latest version

it happens when I import tasks, annotations etc.

**Comment by kkhxx** [comment]
> Hi, @kkhxx
> 
> Please, be more informative. What version, or is it our online platform?
> 
![ubuntu](https://user-images.githubusercontent.com/48484812/217400238-aa8f77af-efc5-43e8-87cf-95b304340b13.PNG)
I installed with [git clone https://github.com/opencv/cvat]

> In the console I see a lot of errors with code 500, it means the error is server-side, please provide logs from docker container in this case: `docker logs cvat_server`.
> ![log1](https://user-images.githubusercontent.com/48484812/217400035-799719a2-a846-4bfd-83fe-2c2645647d2c.PNG)
> What is `docker ps` output?
![docker ps](https://user-images.githubusercontent.com/48484812/217399440-d1452b10-884c-44ac-a22d-d26aef0102ce.PNG)

**Comment by yasakova-anastasia** [comment]
I think the issue has been fixed by #5662 and #5700. I will close this issue. Please reopen this issue if you have it again.
