### ISSUE TITLE
Project created via api doesnt have labels

### ISSUE THREAD

**Issue by arseniymerkulov** [opencv/cvat#5667]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

Code fragment which inflicts the issue 
```
        data = {
            'name': 'project',
            'labels': [
                 {'name': 'cat'},
                 {'name': 'dog'},
            ]
        }

        response = requests.post(f'{self.url}/api/projects', data=data, auth=self._get_auth_data())
        assert response.ok
```

### Expected Behaviour

Request should create project with labels in it 

### Current Behaviour

Project created without labels
![image](https://user-images.githubusercontent.com/94524043/216585938-a8ede637-a08f-43a0-a1b0-c36aede13814.png)

### Possible Solution

Perhaps my labels in wrong format

### Your Environment

- Git hash commit (`git log -1`): commit d5f3f93e8177de13659bedb3467208a196d360b7
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.12
- Are you using **Docker Swarm** or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 Home 22H2
- Code example or link to GitHub repo or gist to reproduce problem: https://github.com/arseniymerkulov/cvat-use-cases

**Comment by zhiltsov-max** [comment]
Hi. The request looks correct, it is basically the same what UI sends. I couldn't reproduce the problem - sending the request produces a project with 2 labels:

```
curl -X 'POST' 'https://app.cvat.ai/api/projects'   \
  -H 'accept: application/vnd.cvat+json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: <...>' \
  -H 'cookie: csrftoken=<...>; sessionid=<...>' \ 
  -H 'referer: https://app.cvat.ai/api/swagger' \
  -d '{"name": "test_5667-2", "labels": [{"name": "cat"}, {"name": "dog"}]}'
```

Please check our tests ([1](https://github.com/opencv/cvat/blob/develop/tests/python/rest_api/test_projects.py#L279), [2](https://github.com/opencv/cvat/blob/develop/tests/python/sdk/test_projects.py#L72-L80)) and our [SDK](https://opencv.github.io/cvat/docs/api_sdk/sdk/) for examples. You can also play with API [here](https://app.cvat.ai/api/swagger/#/projects/projects_create) (sending this request will require it to be written in one line).

**Comment by arseniymerkulov** [comment]
Thanks for your answer. Solved by putting payload in json request field instead of data
