### ISSUE TITLE
How to run CVAT without docker for development 

### ISSUE THREAD

**Issue by SaihholdChiu** [opencv/cvat#5669]
there is no instructions for building development environment, please tell me how to run CVAT directly without docker.

**Comment by azhavoro** [comment]
https://opencv.github.io/cvat/docs/contributing/development-environment/

**Comment by jrermi12** [comment]
it still using docker, wanted to run it on local Ubuntu, to test the changes made to the server. i was able to run it without docker. but the main issue am facing is setting up the email back-end server and how the OPA rule work and configure that as well.
