### ISSUE TITLE
facing issues while installing development environment.

### ISSUE THREAD

**Issue by SaihholdChiu** [opencv/cvat#5671]
My actions before raising this issue
-  Read/searched [the docs](https://opencv.github.io/cvat/docs/contributing/development-environment/)

platform:
macos(Intel)

issues:
while running: "pip3 install -r cvat/requirements/development.txt -r utils/dataset_manifest/requirements.txt"
facing issue:  "pkg-config could not find libraries ['avformat', 'avcodec', 'avdevice', 'avutil', 'avfilter', 'swscale', 'swresample']"

description:
I searched the documentation of development environment and found a relate info and followed the instruction but did not solve the problem:

"""
If you faced with error OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']. You may fix this using

sudo ln -s /opt/homebrew/lib/libgeos_c.dylib /usr/local/lib
"""

**Comment by zhiltsov-max** [comment]
Hi, please try answers from this [thread](https://stackoverflow.com/a/43714671) depending on your environment. I will close the issue, feel free to reopen and ask more questions is the problem persists.
