### ISSUE TITLE
Error "The task and its project should be in the same organization"

### ISSUE THREAD

**Issue by adammz1** [opencv/cvat#5673]
I am trying to create a task in a specific organization (ID 2). I get the error "The task and its project should be in the same organization". The code below works when creating a task in a project in the default organization (Personal workspace). Any ideas? 

```
from cvat_sdk import make_client, models
from cvat_sdk.core.proxies.tasks import ResourceType, Task

     with make_client(host="http://0.0.0.0:8080/", credentials=("username", "password")) as client:

          # Fill in task parameters first.
          # Models are used the same way as in the layer 1.
          task_spec = {
              'image_quality': 70,
              "name": "example task",
              'mode': 'annotation',
              'organization': 2,
              'project_id': 1,
          }

            task = client.tasks.create_from_data(
                spec=task_spec,
                annotation_path='',
                annotation_format='YOLO ZIP 1.0',
                resource_type=ResourceType.LOCAL,
                resources=['sample_img.jpg'],
            )
```

**Comment by zhiltsov-max** [comment]
Hi, please try to add the organization header like it was done [here](https://github.com/opencv/cvat/pull/5225/files#diff-41ccea8c7332ea933b995475be6816b63a1509b97b033413cc6b8db9fc8348ddR405-R407). Actions within an organization require an extra header or a query parameter. With the high-level API in SDK, you can use the header-based variant.
