### ISSUE TITLE
Debugging in Development environment doesn't bind breakpoint

### ISSUE THREAD

**Issue by MustiDarsh** [opencv/cvat#5675]
### My actions before raising this issue
- [V] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [V] Searched [past issues](/issues)

I have been using CVAT for quite some time and would like to contribute to the community. 
I set up my development environment by following the installation guide for [Development Environment](https://opencv.github.io/cvat/docs/contributing/development-environment/).

When running CVAT locally using:
`yarn run start:cvat-ui`
and starting VS Code from Ubuntu by running:
`source .env/bin/activate && code`
and starting the `Server: debug` to start the REST server and its workers, I get a working CVAT instance working at http://localhost:3000

Now, I would like to debug the UI by simply placing a breakpoint in the `*.tsx` files. 

I placed 2 breakpoints (see code snippet below) in `cvat\cvat-ui\src\components\create-project-page.tsx` and visited `http://localhost:3000/tasks/create` and clicked the Submit & Open and Submit & Continue buttons, but my breakpoint was never reached. 

When performing inspect elements in the browser page (Chrome which was launched by `Server: Chrome`) and using the _Network tab_ browse to `cvat\cvat-ui\src\components\create-project-page.tsx` and place a breakpoint there, it works in the browser. But simply, my breakpoints in VS Code are not reached. 

I noticed that my breakpoints are "greyed out", as shown below:
![image](https://user-images.githubusercontent.com/15389273/217114518-83a2b226-e16c-4248-891f-f3e1efd181b5.png)
with the following message when hovering over them:
![image](https://user-images.githubusercontent.com/15389273/217114714-7a9e12a3-c62d-45c4-9624-108bf5772d69.png)

Troubleshooting shows me the following message:
![image](https://user-images.githubusercontent.com/15389273/217115047-dc1ce2f6-df18-4821-84c9-3ea85b8de1f1.png)

I haven't applied any changes to the code or launch.json, so all of this is with the code at commit 2ab66fc32cb5f8346928b88ecaf75cb6fb350a99

### Steps to Reproduce (for bugs)
1. Start REST Server and workers `Server: Debug`
2. Run `ui.js: debug`
3. Run `Server: Chrome`
4. Place breakpoints in: `cvat\cvat-ui\src\components\create-project-page.tsx`
5. visit `http://localhost:3000/tasks/create`
6. click  Submit & Open and Submit & Continue

### Update 08022023
I could reproduce the problem above in 2 different environments when installing clean installs of Ubuntu 18.04 and Ubuntu 22.04 (not supported by CVAT yet). As it seems the problems does not pertain to WSL or anything related. 

### Expected Behaviour
Setting breakpoint and pausing the run when pressing the buttons. 

### Current Behaviour
Breakpoints are never reached when pressing the buttons. 

### Your Environment
- Git hash commit (`git log -1`): commit 2ab66fc32cb5f8346928b88ecaf75cb6fb350a99
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 23.0.0, build e92dd87
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 with WSL2 running Ubuntu 18.04
Additional information:
```
WSL v1.0.3.0
Python 3.9.16
Node v16.19.1
npm 8.19.3
yarn 1.22.19
```

Any ideas if I have missed something?

**Comment by bsekachev** [comment]
@MustiDarsh 

Actually we never use VS Code to debug JS code, only for Python. For JS code Chrome dev tools are more convenient IMHO.
