### ISSUE TITLE
Unable to upload annotations on CVAT with "Coco keypoints 1.0" format

### ISSUE THREAD

**Issue by iqraRajpoot** [opencv/cvat#5677]
### Current Behaviour
i am unable to upload annotations with "coco keypoints 1.0" format, it is giving me this error:
![cvat error](https://user-images.githubusercontent.com/35895082/217188323-9c858c39-fc1e-47b7-9b29-6406f0419c3d.png)

image and its annotation file are in this drive link.
https://drive.google.com/drive/folders/18SlAFCVxuh-R8vncUHu6TqCeUGHGKFZy?usp=sharing
**Note**: this annotation file belongs to halpe dataset based on "coco" format.
### Expected Behaviour
it should show keypoints on the image.

### Possible Solution
not sure

**Comment by yasakova-anastasia** [comment]
Hi @iqraRajpoot

You should use the `COCO 1.0` format for such an annotation file. You will be able to get bounding boxes. If you want to get a skeleton, you need to define categories in the annotation file, add `keypoints` and `skeleton`.
