### ISSUE TITLE
Why is chrome a requirement for launching, and can this be made open to all browsers?

### ISSUE THREAD

**Issue by SirSharpest** [opencv/cvat#568]
Hi, 

Just installed via the docker instructions and I've gotten the message to use Chrome - is there a way around this?

**Comment by nmanovic** [comment]
@SirSharpest , we don't have resources to support all possible browsers. We know that current UI uses features which work in Chrome engine. Probably next version of UI will support other browsers as well.

**Comment by SirSharpest** [comment]
@nmanovic Is there a comprehensive list of UI elements that need addressed, I'd be happy to work on this if we could start a resource for it.

**Comment by nmanovic** [comment]
@SirSharpest ,

I general you can try to disable the check and see how it works. For now I don't think that we want to enable it for old UI but we will try to support all major browsers in the new UI.
