### ISSUE TITLE
Add display for skeleton points in UI right sidebar

### ISSUE THREAD

**Issue by ArMaxik** [opencv/cvat#5693]
### Steps to Reproduce (for bugs)

1. Create a task.
1. On the frame place at least 2 rectangle annotations (class doesn't matter).
1. Group some annotations with grouping tool.
1. Export task to a coco format

### Expected Behaviour

Export performed well, there are all annotations in the instances_default. json file. Coco format doesn't support group option, so this attribute is expected to be omitted.

### Current Behaviour

The number of annotations in the instances_default.json equals to the number of groups, created in the step 3. Certain annotations are missing.

### Your Environment

- Git hash commit: 2c4676ace32a68572b38205f002a98e93af917d0 Release v2.3.0

**Comment by zhiltsov-max** [comment]
Hi, this behavior is intentional, it is described, e.g., [here](https://github.com/opencv/cvat/issues/2600#issuecomment-749029219). The grouped annotations should be exported as whole objects in this format, the label and other properties of the exported object are taken from the biggest (by area) object in a group. Do you have any ideas how we can improve the behavior?

**Comment by ArMaxik** [comment]
@zhiltsov-max, thank you for the reply! I am annotating humans and hats on their heads. I want to associate each hat with a corresponding human. Group tool is perfect for such task. I know that coco will lose all groups, but it's done in advance.

As for polygons, IMHO, it's better to make the interface similar for skeletons: all keypoints are grouped under one object, we see it as a nested list in the UI. So it will be clear that they are the one object, not just a bunch of grouped annotations.

**Comment by bsekachev** [comment]
Not sure I clearly understand the request. Maybe providing an example mockup would be useful.
Anyway I do not think we are going to modify the interface significantly now. I will close the issue.
