### ISSUE TITLE
Error response from daemon: manifest for cvat/server:2.2.0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by isspid** [opencv/cvat#5698]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

After trying to update from 1.7 to 2.2 I got the issue in the title. Output from the last command:
```
$ docker compose up -d
time="2023-02-13T11:42:46+01:00" level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
time="2023-02-13T11:42:46+01:00" level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
time="2023-02-13T11:42:46+01:00" level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
time="2023-02-13T11:42:46+01:00" level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
cvat_opa Pulling
cvat_ui Pulling
cvat_worker_low Pulling
cvat_server Pulling
cvat_worker_default Pulling
cvat_utils Pulling
e8614d09b7be Pulling fs layer
c6f4d1a13b69 Pulling fs layer
a1f1879bb7de Pulling fs layer
29f2f97b419c Pulling fs layer
cvat_server Error
cvat_worker_low Error
cvat_utils Error
cvat_worker_default Error
cvat_ui Error
Error response from daemon: manifest for cvat/server:2.2.0 not found: manifest unknown: manifest unknown

```

### Steps to Reproduce (for bugs)

1. Followed the steps from the [upgrade webpage](https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/) one to one. All steps worked well up to the last one.

### Expected Behaviour

Last command should run making CVAT accessible from localhost.

### Current Behaviour

Last command fails.
### Your Environment

- Git hash commit (`git log -1`):```- git log -1
fatal: not a git repository (or any of the parent directories): .git```
- Docker version `docker version` (e.g. Docker 17.0.05): 

- Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by peige-musashi** [comment]
Met the same issue when upgrade from 1.7.0 to 2.2.0 following the guide.
