### ISSUE TITLE
in cvat2.3.0, there is no difference for different group, can't change the permission for different user

### ISSUE THREAD

**Issue by qingqiqiu** [opencv/cvat#5710]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by qingqiqiu** [comment]
the old verion v1.5.0 has different permission for different group, which is more reasonable

**Comment by bsekachev** [comment]
Hi @qingqiqiu 

The issue is not clear. Please, provide more information.
