### ISSUE TITLE
CVAT doesnot delete old zip files that were prepared for "export dataset"

### ISSUE THREAD

**Issue by SixtyTrees** [opencv/cvat#5742]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

I have to export datasets frequently. Hence, the zip files for download consume a large portion of space on the disk. Eventuallly docker duns out of space because of these zip files that are currently not needed.

### Steps to Reproduce (for bugs)

1. Create CVAT image, allocate minimal disk space to the image 
2. Create a task that occupies 1/4 of the allowed disk space
3. Perform a random markup
4. Export the dataset as "CVAT for images"
5. Repeat the export step several times (until you get the message "CVAT ran out of space") 

### Expected Behaviour

CVAT should delete old zip files after user downloaded the exported set

### Current Behaviour

Apparently, CVAT keeps old zip files, hence it runs out of space due to obsolete zip files with exported data

### Possible Solution

Delete obsolete zip files once user has downloaded them. 
OR provide a command to cleanup obsolete zip files.

### Context

I have to ask our system administrator to increase the size of the disk, available for the image. We will run out of total disk memory soon.

### Your Environment

I have to ask our system admin to collect this data. Briefly, this is Windows server. We use older version:
Server version: 1.1b0, Core version: 3.3.1, Canvas version: 2.0.2, UI version: 1.6.7
- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi,

Currently, the policy is the following: the exported datasets are cached for the time specified [here](https://github.com/opencv/cvat/blob/develop/cvat/apps/dataset_manager/views.py#L42) (10 hours by default). The export parameters (job/task/project, format name, save_images) define the file name in the cache. The same file name should be reused for the same export parameters, meaning the file will be reused after the task is updated. There are temporary directories being created during exporting, but they are removed after exporting.

Could you please check if the export parameters are the same in your case?

**Comment by SixtyTrees** [comment]
> the exported datasets are cached for the time specified (10 hours by default)
This solved my issue. Thank you.
