### ISSUE TITLE
Change default port in traefik container to something other than 8080

### ISSUE THREAD

**Issue by antortjim** [opencv/cvat#5751]
### My actions before raising this issue
- [x] Read/searched [the docs](https://opencv.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port)
- [x] Searched [past issues](https://github.com/opencv/cvat/issues/1555)

### Steps to Reproduce (for bugs)

1. Navigate to [my cvat clone](https://github.com/opencv/cvat/commit/c9f214a8948e3a42e01c5b2b539b94c0bc7110c4). `cd cvat`
1. Edit `docker-compose.yml`
```
     #   - traefik.http.routers.dashboard.service=api@internal
     #   - traefik.http.routers.dashboard.rule=Host(`${CVAT_HOST:-localhost}`)
     ports:
-      - 8080:8080
+      - 9090:8080
       - 8090:8090
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
```
1. Make sure cvat sees this new config. Run `docker compose down` and `docker compose up -d` or `sudo -E docker compose up -d`.

### Expected Behaviour
I expect to be able to reach cvat on CVAT_HOST:9090, just like I did when the port was 8080

### Current Behaviour
I get the error 

```
This site can’t be reached
10.43.205.5 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

10.43.205.5 is the public IP of the server where I run CVAT. I need to reach it both locally and remotely, and setting `CVAT_HOST` to the public IP is the only way I managed to get remote access to work (independently of changing the port). Setting `CVAT_HOST`  to `0.0.0.0` or something like that does not seem to work. 

### Possible Solution
My only solution for now is to stop cvat when I need to use [dvc](https://dvc.org/) and then bring it up again, which is definitely not ideal

### Context
I need to use  [dvc](https://dvc.org/) and cvat on the same computer, both of which need port 8080 (dvc needs it I believe to push/pull from a remote storage)

### Your Environment

- Git hash commit (`git log -1`): `c9f214a8948e3a42e01c5b2b539b94c0bc7110c4`
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 23.0.1, build a5ee5b1
- Are you using Docker Swarm or Kubernetes? Plain Docker, I think
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04.4 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs: Let me know which container(s) logs I should bring here, if needed!

**Comment by azhavoro** [comment]
Cannot reprocuce locally, most likely it's related with firewall settings for your VPS, please check that.

**Comment by saad-abdullah62** [comment]
@antortjim  Facing the same problem, did you find any leads to the solution?

**Comment by antortjim** [comment]
I do not know why port 8090 would not work, but it's working as expected with port 8081. So likely looks like a weird issue on my side. Fortunately, I am not constrained to any port, so I will just use 8081. @saad-abdullah62 hopefully you can do the same too?

**Comment by saad-abdullah62** [comment]
@antortjim  thanks for quick reply, for me CVAT was running on internal IP address on specified port, but the router was blocking the port and therefore i couldn't use that port from external IP address for CVAT.
