### ISSUE TITLE
.pcd files appear empty - lidar data

### ISSUE THREAD

**Issue by Huxwell** [opencv/cvat#5755]
When I upload pcd files to tasks on app.cvat.io the points are not there.:
![image](https://user-images.githubusercontent.com/9086268/220660303-816c23f0-b61b-4f7a-a922-db96d217b0c2.png)

segments.ai for comparison:
![image](https://user-images.githubusercontent.com/9086268/220657575-e17b5a53-2890-4854-adb8-10561aef0782.png)
CloudCompare for comparison:
![image](https://user-images.githubusercontent.com/9086268/220658701-5f1a0b30-8cb9-4ca1-ae1d-b4fb6dad59cf.png)

**Comment by bsekachev** [comment]
@Huxwell 

Hi, could you please share an example file with us?

**Comment by Huxwell** [comment]
I cannot share the actual data, but I will try to generate some mock points that crash on CVAT, but work well on segments/cloudcompare.

I've tried default example from:
https://www.seqsense.org/pcdeditor -> export the example
And it actually renders fine in CVAT. So it's not a problem with .pcd files in general, rather some detail in file internals...

**Comment by Huxwell** [comment]
I cannot share the actual data, but I will try to generate some mock points that crash on CVAT, but work well on segments/cloudcompare.

I've tried default example from:
https://www.seqsense.org/pcdeditor -> export the example
And it actually renders fine in CVAT. So it's not a problem with .pcd files in general, rather some detail in file internals...

**Comment by Huxwell** [comment]
The solution was to drop `intensity` channel.
When I only have `x y z` in my files they render correctly.
Which leads me to the question: how to included 4th channel (intensity) correctly to cvat?
Intensity is pretty useful data and it's a shame to miss it.

**Comment by bsekachev** [comment]
In general CVAT uses PCD loader from three.js: https://threejs.org/docs/#examples/en/loaders/PCDLoader 
It says it supports intensity, need to investigate to undestand mode.

**Comment by Huxwell** [comment]
Few more notes:
- When intensity is integer from 0 to 255, **no points will load**
- When intensity is from 0.0 to 1.0 the points load correctly, but they are all white (intensity is not visible)
- When I add colors to pcd, no points will load
- When there is no intensity, points load correcly
The example files with just 8 points each are below, but you have to change extension from .txt to .pcd (github rejected .pcb extension). Sorry that it took few days for me to provide them.

[colors.txt](https://github.com/opencv/cvat/files/10861639/colors.txt)
[xyz_only.txt](https://github.com/opencv/cvat/files/10861641/xyz_only.txt)



[0to1.txt](https://github.com/opencv/cvat/files/10861636/0to1.txt)
[0to255.txt](https://github.com/opencv/cvat/files/10861638/0to255.txt)

**Comment by Huxwell** [comment]
Ok, some accidental progress!
![image](https://user-images.githubusercontent.com/9086268/222163804-3a49e113-24d8-4c3e-9463-4526023a9cdd.png)
[0to255force_float.txt](https://github.com/opencv/cvat/files/10861839/0to255force_float.txt)
I glued '.0' to intensities in 0-255 range, but kept the 'rgb' FIELD header and got shades of blue.

I tried different variants of headers and color channels, but I wasn't able to get different colors then white or blue though.
I.e. this results in all white (no shades):
[0to255force_float_3_channels.txt](https://github.com/opencv/cvat/files/10861891/0to255force_float_3_channels.txt)
![image](https://user-images.githubusercontent.com/9086268/222166241-f1b3bb60-9b50-44d8-9579-e1dd7185fc39.png)

**Comment by Huxwell** [comment]
https://pcl.readthedocs.io/projects/tutorials/en/latest/pcd_file_format.html the example embedded in this tutorial loads to CVAT with rgb colors. 
I was unable to figure out how they are generating these rgb float4 values with mantissa in the course of a few h of googling and trial and error. I made a ticket to them asking for explanation: https://github.com/isl-org/Open3D/issues/5963

**Comment by Huxwell** [comment]
![image](https://user-images.githubusercontent.com/9086268/222451860-e1aac265-bf24-4cef-8867-fcbb8ad9a75b.png)
Apparently some colors are displayed, some are lost.
If using open3d library, `o3d.io.write_point_cloud(outpath, pcd, write_ascii=False)` write_as_ascii has to be false otherwise points won't load at all (XYZ don't mind, but color does).

if pcd is instance of o3d.geometry.PointCloud(not o3d.t.geometry.PointCloud), the code below will generate colors that render in cvat:
pcd.colors = o3d.utility.Vector3dVector([[0,255,0], [255,0,0] ... ])

The problem is, the behaviour is stochastic. Values such us (0,255,0) will render, but smth like (23,127,99) probablly won't.
Apparently float 4 bytes format used in pcd format is lossy compression (?).

**Comment by Huxwell** [comment]
I haven't find a way to properly upload files with intensities, but found a workaround/hack that works:
https://github.com/PointCloudLibrary/pcl/issues/5621
