### ISSUE TITLE
Continiously restarting cvat_worker_export, cvat_worker_import and cvat_worker_annotation

### ISSUE THREAD

**Issue by wDevil** [opencv/cvat#5766]
### Steps to Reproduce (for bugs)
0. git clone https://github.com/opencv/cvat
1. CVAT_VERSION=v2.3.0 docker-compose pull
2. CVAT_VERSION=v2.3.0 docker-compose up

in console errors is printing in loop(see screenshots), can't create superuser
<img width="714" alt="Снимок экрана 2023-02-24 в 16 49 26" src="https://user-images.githubusercontent.com/1007933/221152156-1167815e-4a58-4838-9af5-939c0e1dff8f.png">

<img width="681" alt="Снимок экрана 2023-02-24 в 16 49 07" src="https://user-images.githubusercontent.com/1007933/221152347-15f8c84e-135f-483c-9df1-05a2113f38f7.png">
<img width="1074" alt="Снимок экрана 2023-02-24 в 16 49 37" src="https://user-images.githubusercontent.com/1007933/221152510-072cd5c4-b54f-4d7f-8f74-df82942a9ba4.png">

### Your Environment

- Git hash commit (`git log -1`): commit 4351d7a80bac67b1f98cb18cf0264a7c03e9a2e1 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): docker -v
Docker version 20.10.14, build a224086349
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): macos ventura 13.2.1 (22D68)

**Comment by wDevil** [comment]
also a'l try to use other version v2.1.0, v.2.2.0, dev. All versions in looping during docker-compose up command with errors:

```
cvat_opa                | {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.25.0.12:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-02-24T10:02:13Z"}
cvat_worker_export      | Error: could not find config file supervisord/worker.export.conf
cvat_worker_export      | For help, use /usr/bin/supervisord -h
cvat_worker_import      | Error: could not find config file supervisord/worker.import.conf
cvat_worker_import      | For help, use /usr/bin/supervisord -h
cvat_worker_export exited with code 2
cvat_worker_import exited with code 2
```

**Comment by symb10z** [comment]
I have same issue. @wDevil Did you solve it?

**Comment by zhiltsov-max** [comment]
It looks like you might need to rebuild or re-download the Docker image for CVAT server. Could you please try to run

`CVAT_VERSION=v2.3.0 docker compose up --pull=always`?

**Comment by zhiltsov-max** [comment]
Hi, please also run `git checkout v2.3.0`.

**Comment by CheloGE** [comment]
> Hi, please also run `git checkout v2.3.0` before running the containers.

Hi @zhiltsov-max Thank you. I tried that and the server now doesn't have the `cvat_worker_export`, `cvat_worker_import` and `cvat_worker_annotation` after that change so no longer this issue. However,  after I checkout to the branch you suggested whenever I want to create a new annotation task I get the following error, hence I'm still not able to annotate anything on the local server.

```
django.db.utils.ProgrammingError: relation "engine_jobcommit" does not exist
LINE 1: INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timest...
```

Here is the full logs in case you want to take a look.

![image](https://user-images.githubusercontent.com/6826404/227053441-dd1cd3ee-9aa2-4870-89d1-fc5cf4356206.png)

**Comment by CheloGE** [comment]
Thank you for the response @zhiltsov-max. Here is the log output after running that command:

![image](https://user-images.githubusercontent.com/6826404/227334318-fbf47ed6-913f-4f7c-a02f-5437072b715a.png)
![image](https://user-images.githubusercontent.com/6826404/227334248-067150be-8e13-426f-8f16-1c0fa48764d1.png)

or if you prefer I also exported the logs in the following file:

[logs.txt](https://github.com/opencv/cvat/files/11055312/logs.txt)

**Comment by zhiltsov-max** [comment]
@azhavoro, could you please look?

**Comment by azhavoro** [comment]
@CheloGE
your database schema and CVAT code are not compatible (different versions), I think the reason is that you ran the develop version of cvat, then you tried to run the v2.3.0 version. This will not work. CUrrently you need to use `dev` images or delete the database.

**Comment by CheloGE** [comment]
Hi @azhavoro Thank you for the hint. Yes, you are right, I did run the `dev` branch of `cvat` first and then switch to the `2.3.0` version. However, I can't use the `dev` version because it is v2.5 and I must run the `v2.3.0` as I have some libraries that are not yet compatible with version 2.4 onwards. Does that mean that the only option I have is deleting the database? Do you mind explaining me how should I do that?

**Comment by azhavoro** [comment]
@CheloGE If you have any data you don't want to lose, an additional option to try is to manually unapply migrations, but I'm not sure if that's possible. If you don't have CVAT data, it will be much easier to just delete the cvat database with `docker compose down -v` that will delete all docker volumes as well

**Comment by CheloGE** [comment]
> @CheloGE If you have any data you don't want to lose, an additional option to try is to manually unapply migrations, but I'm not sure if that's possible. If you don't have CVAT data, it will be much easier to just delete the cvat database with `docker compose down -v` that will delete all docker volumes as well

After applying the `docker compose down -v` command the error was fixed. Now, everything is running as expected. Thank you very much! @azhavoro
