### ISSUE TITLE
Webhook URL fails (too long)

### ISSUE THREAD

**Issue by atekoa** [opencv/cvat#5767]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Error: Request failed with status code 400. {"target_url":["Ensure this field has no more than 200 characters."]}.

### Steps to Reproduce (for bugs)

1. Create a Teams webhook, the url is quite large... more than 200 chars

### Possible Solution

Maybe is a DB field with this size?? 

### Your Environment

- cvat release v2.3.0

**Comment by kirill-sizov** [comment]
We don't have reasons for have limit in 200 characters, sent PRs with increasing this value
