### ISSUE TITLE
Can't upload my annotation file (coco format)

### ISSUE THREAD

**Issue by DavidShaer** [opencv/cvat#5773]
Hi,
I'm trying to upload my annotation file (coco format)
The images were loaded with no issues, but when trying to upload the annotations (zip file) I got the following error:
Could not upload annotation for the [task 92382](https://app.cvat.ai/tasks/92382)
Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://app.cvat.ai/api/jobs/91972/annotations/, response code: 409, response text: "File with same name already exists", request id: n/a).

The structure is as follows:
cvat_data_test_coco.zip 
    -> annotations -> instances_default.json
    -> images -> 000000.jpg, 000001.jpg, 000002.jpg

The annotation file looks as follows:
{"licenses": [{"name": "", "id": 0, "url": ""}], "info": {"contributor": "", "date_created": "", "description": "", "url": "", "version": "", "year": ""}, "categories": [{"id": 1, "name": "product", "supercategory": ""}, {"id": 2, "name": "credit_card", "supercategory": ""}, {"id": 3, "name": "phone", "supercategory": ""}, {"id": 4, "name": "wallet", "supercategory": ""}, {"id": 5, "name": "hands_only", "supercategory": ""}, {"id": 6, "name": "other", "supercategory": ""}], "images": [{"id": 1, "width": 1920, "height": 1080, "file_name": "/Users/davidshaer/Desktop/composite/projects/fujitsu-scan-avoidance/products_tracking_data_collection/post_processing_results/cvat_data_test_coco/images/000001.jpg", "license": 0, "flickr_url": "", "coco_url": "", "date_captured": 0}, {"id": 2, "width": 1920, "height": 1080, "file_name": "/Users/davidshaer/Desktop/composite/projects/fujitsu-scan-avoidance/products_tracking_data_collection/post_processing_results/cvat_data_test_coco/images/000000.jpg", "license": 0, "flickr_url": "", "coco_url": "", "date_captured": 0}, {"id": 3, "width": 1920, "height": 1080, "file_name": "/Users/davidshaer/Desktop/composite/projects/fujitsu-scan-avoidance/products_tracking_data_collection/post_processing_results/cvat_data_test_coco/images/000002.jpg", "license": 0, "flickr_url": "", "coco_url": "", "date_captured": 0}], "annotations": [{"id": 1, "image_id": 1, "category_id": 1, "segmentation": [], "area": 45466, "bbox": [916, 339, 179, 254], "iscrowd": 0, "attributes": {"occluded": false, "track_id": 1, "keyframe": true}}, {"id": 2, "image_id": 2, "category_id": 1, "segmentation": [], "area": 45466, "bbox": [916, 339, 179, 254], "iscrowd": 0, "attributes": {"occluded": false, "track_id": 2, "keyframe": true}}, {"id": 3, "image_id": 3, "category_id": 1, "segmentation": [], "area": 45466, "bbox": [916, 339, 179, 254], "iscrowd": 0, "attributes": {"occluded": false, "track_id": 3, "keyframe": true}}]}

Environment:
mac os
CVAT online

Any help will be appreciated 
Thanks
David

**Comment by zhiltsov-max** [comment]
Hi, thank for reporting the problem. As a workaround, please rename the file and try to upload it again.
