### ISSUE TITLE
How to rotate cuboids in point cloud annotations?

### ISSUE THREAD

**Issue by Huxwell** [opencv/cvat#5775]
Can I rotate the cuboid annotations using CVAT GUI?
If this feature is not supported, are there plans to support it in the near future?
Is there a documentation for annotating cuboids/lidar point clouds?

I was able to rotate a cuboid, by exporting annotation to Datarumo 3D format and editing rotation parameter from [0,0,0] to [0.5,0.5,0], but this approach won't scale:

```
      "annotations": [{
          "id": 0,
          "type": "cuboid_3d",
          "attributes": {"occluded": false},
          "group": 0,
          "label_id": 0,
          "position": [7.01,-0.86,0.17],
          "rotation": [0.5,0.5,0],
          "scale": [0.95,1.48,2.19]
        }]
```

![image](https://user-images.githubusercontent.com/9086268/221543110-36d78063-0b4c-4050-9f79-e11d0878278c.png)
![image](https://user-images.githubusercontent.com/9086268/221543460-97cf24a5-6128-48f9-bea0-bb3a0e3f077b.png)

**Comment by bsekachev** [comment]
@Huxwell 

Please, read the manual: https://opencv.github.io/cvat/docs/manual/basics/3d-object-annotation-basics/

**Comment by Huxwell** [comment]
Thanks, is solves my issue. In fact, it is implemented in a really convenient way!

The only think I am still struggling with in 3D annotation is intensity channel&format - couldn't find this in the documentation that you have kindly linked.
This is in the https://github.com/opencv/cvat/issues/5755 ticket.
