### ISSUE TITLE
Container CVAT_vector

### ISSUE THREAD

**Issue by rschraml** [opencv/cvat#5786]
### docker compose up -d

I cannot start cvat again after changing the traefik ports. Any idea whats wrong? We already have annotations in the database....
![issue](https://user-images.githubusercontent.com/12030725/221853650-0f78c3a4-dd9c-4697-863c-d4d47627bf57.png)

Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/rschraml/meru/cvat/components/analytics/vector/vector.toml" to rootfs at "/etc/vector/vector.toml": mount /home/rschraml/meru/cvat/components/analytics/vector/vector.toml:/etc/vector/vector.toml (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by azhavoro** [comment]
Cannot reproduce...
Have you checked the file /home/rschraml/meru/cvat/components/analytics/vector/vector.toml as docker suggests?

**Comment by NickLojewski** [comment]
I am dealing with this as well. I am running on MacOS and using Minikube to run my Docker Daemon because I want to avoid Docker Desktop. How are you set up @rschraml?

**Comment by rschraml** [comment]
I have deleted vector.toml and created a new folder named vector.toml -> then it was able to start up again. Thanks for the help - sometimes trying to understand the error message is the key :-)

**Comment by oe3gwu** [comment]
I have got the same issue. I tried deleting the folder, doesnt help. It was empty anyway.

![image](https://github.com/opencv/cvat/assets/17622063/b9abd1bd-460c-4eb2-abc7-4c1d703985e3)

**Comment by ZaibanAli** [comment]
same issue

**Comment by madsci1016** [comment]
I am having the same error when deploying with portainer. Not sure how to fix it.

**Comment by Kuriss** [comment]
I am having the same error when deploying with portainer. Not sure how to fix it.

**Comment by vijaynyaya** [comment]
@rschraml Can you please clarify this. Did you place the vector.toml file inside the newly created vector.toml folder.
The issue hasn't been resolved yet. No response from the CVAT team.
