### ISSUE TITLE
Could not fetch tasks after clicking back arrow in Chrome

### ISSUE THREAD

**Issue by may109** [opencv/cvat#5787]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. open a job of video clip
2. click "save" and "Finish the job"
3. click "back" arrow in chrome browser
4. the error 400 shows up
Error: Request failed with status code 400. ["filter: != operation with [{'var': 'status'}, 'completed'] arguments is not implemented"]. 

### Expected Behaviour
no error and load the previous page

### Current Behaviour
it reports error 400

### Possible Solution
refresh the page properly with updated list of tasks

### Context
Failed to go to previous page and the error confuses labellers.

### Your Environment
- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:

**Comment by bsekachev** [comment]
Hi, @may109 

What is you CVAT version? I cannot reproduce it.

**Comment by may109** [comment]
[image: Screen Shot 2023-03-13 at 9.02.12 AM.png]
