### ISSUE TITLE
Correct way to use remote files field 

### ISSUE THREAD

**Issue by arseniymerkulov** [opencv/cvat#5791]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

Im trying to attach remote image to empty task via following code. However, task remains empty 
```
  def recreate_task(self, task: CVATTask):
        data = {
            'name': task.name,
            'project_id': self.project.id,
            'owner_id': self.user.id,
            'segment_size': task.segment_size
        }
  
        response = requests.post(f'{self.url}/api/tasks',
                                 json=data,
                                 auth=self._get_auth_data(),
                                 headers=self._get_headers())
        
        assert response.ok
        task.id = response.json()['id']

  def attach_url_images(self, task: CVATTask):
        response = requests.post(f'{self.url}/api/tasks/{task.id}/data',
                                 json={
                                        'remote_files': ['https://picsum.photos/id/1/600/600'],
                                        'image_quality': task.image_quality
                                       },
                                 auth=self._get_auth_data(),
                                 headers=self._get_headers())
        print(response.text)
        assert response.ok
```
response:
```
{"chunk_size":null,"size":0,"image_quality":75,"start_frame":0,"stop_frame":0,"frame_filter":"","compressed_chunk_type":"imageset","original_chunk_type":"imageset","client_files":[],"server_files":[],"remote_files":["https://picsum.photos/id/1/600/600"],"use_zip_chunks":false,"use_cache":false,"copy_data":false,"storage_method":"file_system","storage":"local","sorting_method":"lexicographical","filename_pattern":null}
```

![image](https://user-images.githubusercontent.com/94524043/222123938-06a558c5-41b1-4aee-b5b4-b34a102b799a.png)

How to do that correctly? 
Tried both json and data fields of post method

### Your Environment

Git hash commit (git log -1): commit cdb4eb0f25dd9b03146463a579e54d277c9670db
Docker version docker version (e.g. Docker 17.0.05): 20.10.23
Are you using **Docker Swarm** or Kubernetes?
Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 Home 22H2

**Comment by zhiltsov-max** [comment]
Hi, the requests look correct, please check if the task id is correct in the data uploading function. I could not reproduce.

**Comment by zhiltsov-max** [comment]
Hi! Remote files are dedicated solely for direct links to files in the Internet. You can find an example of remote files [here](https://github.com/opencv/cvat/blob/66fb0261feec25a4061ed1f554b2a52cfe528229/tests/python/rest_api/test_remote_url.py#L61-L65). If you want to use files from an existing cloud storage, you need to use `server_files` instead, an example using low-level API is [here](https://github.com/opencv/cvat/blob/66fb0261feec25a4061ed1f554b2a52cfe528229/tests/python/rest_api/test_tasks.py#L986-L1138).

**Comment by arseniymerkulov** [comment]
@zhiltsov-max 
I understand that. Server files example helped fix the problem, thank you
