### ISSUE TITLE
Re-id app to merge bboxes into tracks after TF annotation

### ISSUE THREAD

**Issue by tropicalpb** [opencv/cvat#58]
Hi, great tool.  For ground-truth annotation, there are often too many objects in every frame.  It would be tremendously tedious work to annotate the track for every single one of objects.  Is there any pre-trained model or a way to run a custom model that can detect possibly identical objects, and all I have to do is to review and merge their tracks/IDs into one?

thanks

**Comment by nmanovic** [comment]
OpenVINO has such algorithm: https://software.intel.com/en-us/openvino-toolkit/documentation/pretrained-models (Person Re-Identification). AFAIK it can be used not only for person. I hope that our team will integrate the algorithm into public repo for Release 0.3.0.

**Comment by dsdon10** [comment]
Hello folks - we have installed CVAT into our web platform for you to use. You are free to test it out here:

https://c.onepanel.io

We should have GPU optimized capability working soon along with TF_annotation and will train on the entire ImageNet dataset. We will provide free GPU time if you ask to test it out.

Don
Onepanel.io

**Comment by tropicalpb** [comment]
that's great.  when will 0.3.0 come out?
