### ISSUE TITLE
Difficulty creating projects with cvat_sdk

### ISSUE THREAD

**Issue by quaid281** [opencv/cvat#5804]
All I'm trying to do is create a project
Why would this code:
```
import time
from cvat_sdk.api_client import Configuration, ApiClient, exceptions
from cvat_sdk.api_client.model.project_read import ProjectRead
from cvat_sdk.api_client.model.project_write_request import ProjectWriteRequest
from cvat_sdk.api_client.api.projects_api import ProjectsApi
from pprint import pprint
import os

configuration = Configuration(
    host = "http://localhost:8080",
    username = 'admin',
    password = 'admin',
)

def new_projects(foldername):
    with ApiClient(configuration) as api_client:
        project_write_request = ProjectWriteRequest(
            name=foldername,
        )
        try:
            api_response = ProjectsApi(api_client).create(project_write_request)
            pprint(api_response)
        except exceptions.ApiException as e:
            print("Exception when calling ProjectsApi.projects_create: %s\n" % e)

directory_path = r'C:\Users\testFolder' #Need to change this to where the folders will be held
for foldername in os.listdir(directory_path):
    if os.path.isdir(os.path.join(directory_path, foldername)):
        new_projects(foldername)
```

Give me this error:
    raise get_type_error(input_value, path_to_item, valid_classes,
cvat_sdk.api_client.exceptions.ApiTypeError: Invalid type for variable 'tasks'. Required value type is list and passed type was dict at ['received_data']['tasks']

**Comment by samokhinv** [comment]
+1

Similar error when trying to create task using `client.create_from_data` and existing project's id. Error relates to `labels` instead of `tasks`

**Comment by saifkhichi96** [comment]
+1

I am getting the `ApiTypeError` on almost all SDK calls. For example, calling the method `api_client.projects.list()` gives the following error:
```
cvat_sdk.api_client.exceptions.ApiTypeError: Invalid type for variable 'tasks'. Required value type is list and passed type was dict at ['received_data']['results'][0]['tasks']
```

Similarly, trying to create a PyTorch dataset from a task by calling `cvat_sdk.pytorch.TaskVisionDataset(api_client, task_id)` gives the following error:
```
cvat_sdk.api_client.exceptions.ApiTypeError: Invalid type for variable 'labels'. Required value type is list and passed type was dict at ['received_data']['labels']
```

The stacktrace shows the following:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cvat_sdk/pytorch/__init__.py", line 127, in __init__
    self._task = client.tasks.retrieve(task_id)
  File "cvat_sdk/core/proxies/model_proxy.py", line 138, in retrieve
    (model, _) = self.api.retrieve(id=obj_id)
  File "cvat_sdk/api_client/api/tasks_api.py", line 3447, in retrieve
    return self.retrieve_endpoint.call_with_http_info(**kwargs)
  File "cvat_sdk/api_client/api_client.py", line 1052, in call_with_http_info
    return self.api_client.call_api(
  File "cvat_sdk/api_client/api_client.py", line 495, in call_api
    return self.__call_api(**params)
  File "cvat_sdk/api_client/api_client.py", line 280, in __call_api
    return_data = self.deserialize(
  File "cvat_sdk/api_client/api_client.py", line 387, in deserialize
    deserialized_data = validate_and_convert_types(
  File "cvat_sdk/api_client/model_utils.py", line 1590, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "cvat_sdk/api_client/model_utils.py", line 1479, in attempt_convert_item
    raise conversion_exc
  File "cvat_sdk/api_client/model_utils.py", line 1470, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "cvat_sdk/api_client/model_utils.py", line 1384, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "cvat_sdk/api_client/model_utils.py", line 51, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "cvat_sdk/api_client/model_utils.py", line 379, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "cvat_sdk/api_client/model_utils.py", line 51, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "cvat_sdk/api_client/model/task_read.py", line 521, in _from_openapi_data
    self.labels = labels
  File "cvat_sdk/api_client/model_utils.py", line 197, in __setattr__
    self[attr] = value
  File "cvat_sdk/api_client/model_utils.py", line 518, in __setitem__
    self.set_attribute(name, value)
  File "cvat_sdk/api_client/model_utils.py", line 169, in set_attribute
    value = validate_and_convert_types(
  File "cvat_sdk/api_client/model_utils.py", line 1590, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "cvat_sdk/api_client/model_utils.py", line 1465, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
```
I tested this using `cvat-sdk` versions `2.1.0`, `2.1.0.post1` and `2.3.0` with Python 3.8.

**Comment by saifkhichi96** [comment]
@azhavoro @nmanovic 

I can fix this problem in the released versions of the SDK (`2.3.0`) by changing `must_convert=True` to `must_convert=False` on L1598 in `cvat_sdk/api_client/model_utils.py`. In the develop branch, this corresponds to [L1277](https://github.com/opencv/cvat/blob/8df8b1fd282dfb9f51d906c816e32ede26e7d4fb/cvat-sdk/gen/templates/openapi-generator/model_utils.mustache#L1277) in `cvat-sdk/gen/templates/openapi-generator/model_utils.mustache`.

I didn't create a PR because I am not sure what the implications of making this change. Would changing this line to `must_convert=False` break something else?

**Comment by nmanovic** [comment]
@SpecLad , please look into the issue.

**Comment by quaid281** [comment]
> @azhavoro @nmanovic
> 
> I can fix this problem in the released versions of the SDK (`2.3.0`) by changing `must_convert=True` to `must_convert=False` on L1598 in `cvat_sdk/api_client/model_utils.py`. In the develop branch, this corresponds to [L1277](https://github.com/opencv/cvat/blob/8df8b1fd282dfb9f51d906c816e32ede26e7d4fb/cvat-sdk/gen/templates/openapi-generator/model_utils.mustache#L1277) in `cvat-sdk/gen/templates/openapi-generator/model_utils.mustache`.
> 
> I didn't create a PR because I am not sure what the implications of this change. Would `must_convert=False` break something else? Why do we need `True` here? I can open a PR if someone can confirm this.
> 
> Edit: I found out that this code was added by @zhiltsov-max in commit [7b2fc54](https://github.com/opencv/cvat/commits/6dd662b8e7dd603543e0f28e37080923e4b84b19/cvat-sdk/cvat_sdk/model_utils.py)

This Works.

**Comment by zhiltsov-max** [comment]
Hi. I suppose, the reason is that you're trying to work with the public server at app.cvat.ai, which was updated recently with latest changes, while there is no SDK release in `pip` yet. Please follow [these instructions](https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/#how-to-generate-package-code) to build the develop version of SDK while it's not updated in `pip`. Sorry for inconvenience.

**Comment by saifkhichi96** [comment]
I am using a local server that is synced with the `develop` branch. This works for me.

> Hi. I suppose, the reason is that you're trying to work with the public server at app.cvat.ai, which was updated recently with latest changes, while there is no SDK release in `pip` yet. Please follow [these instructions](https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/#how-to-generate-package-code) to build the develop version of SDK while it's not updated in `pip`. Sorry for inconvenience.

**Comment by SpecLad** [comment]
I tested the reproduction script with the server and SDK from the 2.4.0 release, and it works as expected. It also works with SDK 2.4.0 and app.cvat.ai.

Most likely, the problem was due to mismatched server and SDK versions.
