### ISSUE TITLE
how to volumes a local path to docker when deploy custom DL model.

### ISSUE THREAD

**Issue by gwang74** [opencv/cvat#5811]
### Setup Method

Docker

### Nuclio Version

latest

### Issue Description
deploy custom DL models , i wan to volumes a local path to docker , just like a Dockfile.
```ymal
  volumes:
    -localpath:path
```

my function.ymal  , copy [cvat](https://github.com/opencv/cvat/blob/985c9ee4c33e409b2ac35b05580a285067d09164/serverless/openvino/omz/intel/text-detection-0004/nuclio/function.yaml#L22)   ,but it not work.
```ymal
  volumes:
    - volume:
        name: maskrcnn
        configMap:
          name: "localpath"
          defaultMode: 0750
      volumeMount:
        name: maskrcnn
        mountPath: /opt/nuclio/maskrcnn

  build:
          ...

    directives:
      preCopy:
          ...
        - kind: WORKDIR
          value: /opt/nuclio/maskrcnn
        - kind: RUN
          value: pip3 install -r requirements.txt -i https://pypi.douban.com/simple/
```

### Setup Logs

```shell
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

What is the correct approach.

**Comment by bsekachev** [comment]
Hi, @gwang74 

Probably it is a question for nuclio community. 
In CVAT we don't have such experience.
