### ISSUE TITLE
new django application url not reflecting 

### ISSUE THREAD

**Issue by pavandayala** [opencv/cvat#5817]
### My actions before raising this issue
- Analyzed the opencv and dataset_repo app functionality before creating my own application

i have created a new django application under cvat.apps folder, added the app name in cvat.settings.base.py  and also updated url in cvat.urls.py file
But, unable to access the urls of my application. Tried adding the URL in existing dataset_repo and opencv applications but to no avail. 
please help me if i have missed any change or let me know how to create new djanog app inside cvat folder

**Comment by bsekachev** [comment]
Hi @pavandayala 

I do not think there is some specific for adding apps in CVAT.
Probably better to ask in django community with providing some examples.
