### ISSUE TITLE
External authentications other than LDAP

### ISSUE THREAD

**Issue by rushtehrani** [opencv/cvat#582]
Need a generic way to authenticate to external APIs other than LDAP. Ideally this should happen every time CVAT is loaded.  Initial thoughts are that this can be done in two ways:

- Expect the API to return a `user` object and http code `200` when login is successful.
- Allow developers to create their own custom auth providers

**Comment by nmanovic** [comment]
@rushtehrani , do I understand correctly that the main idea here is to avoid extra authorization inside CVAT if it is integrated in a 3rd-party platform? How does it work now in OnePanel?

**Comment by rushtehrani** [comment]
@nmanovic correct, right now, we have updated CVAT’s code to create the user when CVAT launches. After that, we don’t ever log the CVAT user out as all authentication goes through Onepanel.

**Comment by nmanovic** [comment]
Added link on all possible auth applications for Django: https://djangopackages.org/search/?q=auth

**Comment by nmanovic** [comment]
Related issue #1217
