### ISSUE TITLE
3 questions about 3D box annotation

### ISSUE THREAD

**Issue by LightningApple** [opencv/cvat#5825]
hi, I can't find the discripiton about "Sly Point Cloud Format 1.0"。 For example:
    {
      "key": "93452191-7555-4d83-b481-d4d92f526942",
      "objectKey": "d534a416-d564-47f1-b730-ed75d266a533",
      "geometryType": "cuboid_3d",
      "geometry": {
        "position": {
          "x": -5.3,
          "y": 44.51,
          "z": -0.34
        },
        "rotation": {
          "x": 0.0,
          "y": 0.0,
          "z": -0.55
        },
        "dimensions": {
          "x": 8.9,
          "y": 2.95,
          "z": 3.31
        }
      }

rotation z -0.55 means what?  the same car in another annotation program called labelCloud, the rotation z is 147degree(Absolute Rotations as Euler angles in degrees (0..360°) [yaw, pitch, roll]).   

Another question in the gui how can  I find the front face of the 3D box , in other words, how show the cubox the progress direction?

Last question, if has any shortcut in keyboard to rotate the cubox, because it is hard to fit the points by mouse dargging.

**Comment by bsekachev** [comment]
Hi @LightningApple 

Sly pointcloud format is Supevisely format. You can find description here: https://docs.supervise.ly/data-organization/00_ann_format_navi/07_supervisely_format_pointcloud_episode

> rotation z -0.55 means what?

Rotation of a cuboid across Z axis in radians. Not sure about other tools, but in our case the value is quite simple. CVAT normalizes this value within [-Pi : Pi]

For example I rotated a cuboid on 45 degres on the screenshot below:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/40690378/224667850-a1366c72-1391-4901-b71f-a78e36bb5360.png">

In this case, when I save the job I see:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/40690378/224668147-b2e55f71-bf6b-4103-8074-f3199c5c7de3.png">

> Another question in the gui how can I find the front face of the 3D box , in other words, how show the cubox the progress direction?
> Last question, if has any shortcut in keyboard to rotate the cubox, because it is hard to fit the points by mouse dargging.

Not yet. 3D workspace is under active development.

**Comment by LightningApple** [comment]
thanks, I got it.

**Comment by LightningApple** [comment]
I got it.
