### ISSUE TITLE
I can no longer upload videos, despite i can label and export my other videos

### ISSUE THREAD

**Issue by Mehdi-Kabbaj** [opencv/cvat#5827]
Hello, 

Since last week i can not upload new videos on my CVAT server.

I still can tagging and export my other works.

I've got errors on Chrome consol log:

![Screenshot from 2023-03-06 10-06-25](https://user-images.githubusercontent.com/56678101/223998158-4535bd48-44d0-4055-944e-decbde15fd29.png)

And errors on docker logs : 

![Capture d’écran de 2023-03-06 15-45-50](https://user-images.githubusercontent.com/56678101/223998431-5ca2e1c7-cff8-4c3d-a455-0452eb6318af.png)

It seems it's about cvat database and a null value for "deleted frames", but i don't know why that suddenly happened.

Any solution to solve that ?

**Comment by nmanovic** [comment]
@Mehdi-Kabbaj , need more information how to reproduce the issue on our side. Could you please specify how did you deploy CVAT instance? Which version of CVAT do you use? Is it the latest release v2.4.0?
