### ISSUE TITLE
cvat 2.3.0, cvat-cli, av.error.UnknownError

### ISSUE THREAD

**Issue by apiszcz** [opencv/cvat#5836]
cvat 2.2.0 and earlier was ok, getting the following error cvat-cli trying to create tasks

cvat 2.3.0, cvat-cli 2.3.0
HTTP response body: b'{"state":"Failed","message":"av.error.UnknownError: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] Initialize failed","progress":0.0}'

This error occurs when operating CVAT 2.2, 2.3 or 2.4 within a Virtualbox Debian 11 or Ubuntu 22 VM. 
Operating CVAT 2.2,2.3,2.4 in other environments does not produce the error, create tasks work fine with the same video files.

**Comment by zhiltsov-max** [comment]
Hi, could you please add steps to reproduce the error? How CVAT is deployed?

**Comment by apiszcz** [comment]
This error occurs when running inside of a VirtualBox VM on Ubuntu 22.x or Debian. If i run in other NON virtualbox environments there is no error. It would be useful to have CVAT as an appliance file but does not appear to be possible.

**Comment by apiszcz** [comment]
Yes
VirtualBox->Ubuntu 22->Docker(latest)->CVAT
also tried
VirtualBox->Debian11.6->Docker(latest)->CVAT

**Comment by zhiltsov-max** [comment]
There was an update of the av dependency in https://github.com/opencv/cvat/pull/5380/files. Could you please check if this change introduces the regression in your case? Can you try to change the updated lines with `av` in the local files and rebuild CVAT using the command `docker compose -f docker-compose.yml -f docker-compose.dev-yml up --build -d`?

**Comment by apiszcz** [comment]
Thank you, I reviewed the files in my cvat folder, (no updates or changes).
Based on the following I did not try an update since these are the only two changes I see in 5380.
Though am wonder if version 8 works?

cvat/requirements/base.txt
rq==1.5.2
av==9.2.0

utils/dataset_manifest/requirements.txt
av==9.2.0 --no-binary=av

**Comment by apiszcz** [comment]
CVAT >= 2.1
VirtualBox 7.0.6
Ubuntu 22.04 or Debian 11.6

**Comment by apiszcz** [comment]
Update:
Today, the same error appears with CVAT 2.4 installed on docker (4.17) for windows 10 and WSL2.

`[2023-03-25 12:16:24] INFO: Task 1 creation status=Failed, message=av.error.UnknownError: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] Initialize failed`

**Comment by apiszcz** [comment]
testing different codecs for the input file
ffmpeg -i in.ts -c:v CODEC -o out.mkv

[libsvtav1]
Could not create the task
Error: Could not create the task on the server. RuntimeError: Stream.decode requires a valid CodecContext.

[jpeg2000]
Could not create the task

Error: Could not create the task on the server. av.error.UnknownError: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] Initialize failed.

[libtheora]
Could not create the task

Error: Could not create the task on the server. av.error.UnknownError: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] Initialize failed.

[libvpx]
Could not create the task
Error: Could not create the task on the server. av.error.UnknownError: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] Initialize failed.

[libx264]
Could not create the task
Error: Could not create the task on the server. av.error.UnknownError: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] Initialize failed.

[libx265]
Could not create the task
Error: Could not create the task on the server. av.error.UnknownError: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] Initialize failed.

[libxavs2]
Could not create the task
Error: Could not create the task on the server. RuntimeError: Stream.decode requires a valid CodecContext.

[libxvid]
Could not create the task
Error: Could not create the task on the server. av.error.UnknownError: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] Initialize failed.

**Comment by apiszcz** [comment]
Note: Installed cvat 2.4 on a new LINUX Ubuntu 20.04 instance no issues importing, Everything works.

**Comment by zhiltsov-max** [comment]
Hi, sorry for the late response, were you able to resolve the issue? As I understand, the problem was in the too old hardware, and rebuilding the ffmpeg dependencies, specifically libopenh264, helped? It is correct?

**Comment by apiszcz** [comment]
I did not recompile/build. switched to more recent CPU.
