### ISSUE TITLE
Change object annotation layer orders?

### ISSUE THREAD

**Issue by liand23** [opencv/cvat#584]
Hi I am wondering if it is possible to change the annotations's layer order?

When I am using the tool for segmentation labeling, on the object panel, the early labeled objects are always on lower layers, and the later labeled objects are always covering the early ones. Is it possible to change the orders of the annotations on the object panel?

**Comment by bsekachev** [comment]
@liand23 
Hi, Please, read about [z order](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#annotation-with-polygons).
You also can enable it for a task after it has been created, by using an admin panel.

**Comment by liand23** [comment]
Got it! Thank you very much!
