### ISSUE TITLE
Issue with annotating vertical video - dimensions reversed

### ISSUE THREAD

**Issue by udamaster** [opencv/cvat#5842]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

When I attempt to annotate vertical video it appears CVAT rotates the video properly but does not swap the height and width. What you end up with is stretched video and I'm quite sure any annotations will not correlate properly to the video frame. Can I adjust this somehow? Gone through all the menus and nothing is jumping out at me.

Thank you!

![image](https://user-images.githubusercontent.com/100089338/224493204-99a5c740-5e67-4a0c-b751-db3ab5315fac.png)

### Steps to Reproduce (for bugs)

1. Record vertical video
2. Import into CVAT
3. Open task and look at frame dimensions

### Expected Behaviour

Expecting to see rotation and dimensions accounted for appropriately.

### Your Environment

Macbook Pro, running latest docker

**Comment by bsekachev** [comment]
Hi @udamaster 

Thank you for report. 
Looks like a bug, need to check.

**Comment by udamaster** [comment]
One key detail I just discovered. Seems to only happen with vertical video from Android devices. Tested video from iOS and it works as expected.

**Comment by bsekachev** [comment]
@udamaster 

Can you please provide all metadata (excluding personal) of the videofile?

**Comment by udamaster** [comment]
That was the right question to ask ...after pulling up both the iOS and Android ...the resolution of the Android is somehow square! As luck would have it, the first video we tested was the ONLY one with this issue. Must have been a misconfiguration during post processing.

Thanks for your time.
