### ISSUE TITLE
Create from Backup: ERR TIMED OUT

### ISSUE THREAD

**Issue by atekoa** [opencv/cvat#5846]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Download a (big ~3.6GB in my case) project backup
1. Create from backup
1. After several calls, the process ends with ERR_TIME_OUT

### Current Behaviour

![image](https://user-images.githubusercontent.com/5947222/224741652-88bf0c60-dce1-4a32-908e-23d1b049e75a.png)

### Your Environment

CVAT v2.3.0

- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat.server` container</summary>
  2023-03-13 15:11:56,987 DEBG 'runserver' stderr output:
  [Mon Mar 13 15:11:56.987063 2023] [reqtimeout:info] [pid 87:tid 140343208675072] [client 10.0.4.5:55280] AH01382: Request body read timeout
  
  2023-03-13 15:11:56,988 DEBG 'runserver' stderr output:
  [Mon Mar 13 15:11:56.988665 2023] [wsgi:error] [pid 87:tid 140343208675072] [client 10.0.4.5:55280] mod_wsgi (pid=87): Request data read error when proxying data to daemon process: The timeout specified has expired., referer: https://cvat.mydomain.com/projects?page=1
  
  2023-03-13 15:11:57,003 DEBG 'runserver' stderr output:
  [Mon Mar 13 15:11:57.003741 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] [2023-03-13 15:11:56,996] ERROR django.request: Internal Server Error: /api/projects/backup/6be80b0b-0d23-444b-9630-6d80a9e409c2
  [Mon Mar 13 15:11:57.003783 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] Traceback (most recent call last):
  [Mon Mar 13 15:11:57.003790 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/http/request.py", line 391, in read
  [Mon Mar 13 15:11:57.003793 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return self._stream.read(*args, **kwargs)
  [Mon Mar 13 15:11:57.003797 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 34, in read
  [Mon Mar 13 15:11:57.003800 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     result = self.buffer + self._read_limited()
  [Mon Mar 13 15:11:57.003802 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
  [Mon Mar 13 15:11:57.003805 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     result = self.stream.read(size)
  [Mon Mar 13 15:11:57.003808 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] OSError: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
  [Mon Mar 13 15:11:57.003812 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] 
  [Mon Mar 13 15:11:57.003815 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] The above exception was the direct cause of the following exception:
  [Mon Mar 13 15:11:57.003818 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] 
  [Mon Mar 13 15:11:57.003820 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] Traceback (most recent call last):
  [Mon Mar 13 15:11:57.003823 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/http/request.py", line 336, in body
  [Mon Mar 13 15:11:57.003826 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     self._body = self.read()
  [Mon Mar 13 15:11:57.003829 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/http/request.py", line 393, in read
  [Mon Mar 13 15:11:57.003832 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     raise UnreadablePostError(*e.args) from e
  [Mon Mar 13 15:11:57.003836 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] django.http.request.UnreadablePostError: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
  [Mon Mar 13 15:11:57.003839 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] 
  [Mon Mar 13 15:11:57.003841 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] The above exception was the direct cause of the following exception:
  [Mon Mar 13 15:11:57.003844 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] 
  [Mon Mar 13 15:11:57.003846 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] Traceback (most recent call last):
  [Mon Mar 13 15:11:57.003849 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
  [Mon Mar 13 15:11:57.003852 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     response = get_response(request)
  [Mon Mar 13 15:11:57.003854 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
  [Mon Mar 13 15:11:57.003858 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
  
  2023-03-13 15:11:57,004 DEBG 'runserver' stderr output:
  [Mon Mar 13 15:11:57.003864 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  [Mon Mar 13 15:11:57.003872 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return view_func(*args, **kwargs)
  [Mon Mar 13 15:11:57.003875 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
  [Mon Mar 13 15:11:57.003878 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return self.dispatch(request, *args, **kwargs)
  [Mon Mar 13 15:11:57.003881 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
  [Mon Mar 13 15:11:57.003883 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     response = self.handle_exception(exc)
  [Mon Mar 13 15:11:57.003886 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
  [Mon Mar 13 15:11:57.003889 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     self.raise_uncaught_exception(exc)
  [Mon Mar 13 15:11:57.003892 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
  [Mon Mar 13 15:11:57.003895 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     raise exc
  [Mon Mar 13 15:11:57.003897 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
  [Mon Mar 13 15:11:57.003900 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     response = handler(request, *args, **kwargs)
  [Mon Mar 13 15:11:57.003903 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/home/django/cvat/apps/engine/views.py", line 621, in append_backup_chunk
  [Mon Mar 13 15:11:57.003905 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return self.append_tus_chunk(request, file_id)
  [Mon Mar 13 15:11:57.003908 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/home/django/cvat/apps/engine/mixins.py", line 202, in append_tus_chunk
  [Mon Mar 13 15:11:57.003911 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     chunk = TusChunk(request)
  [Mon Mar 13 15:11:57.003914 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/home/django/cvat/apps/engine/mixins.py", line 94, in __init__
  [Mon Mar 13 15:11:57.003916 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     self.content = request.body
  [Mon Mar 13 15:11:57.003919 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/request.py", line 416, in __getattr__
  [Mon Mar 13 15:11:57.003922 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return getattr(self._request, attr)
  [Mon Mar 13 15:11:57.003925 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/http/request.py", line 338, in body
  [Mon Mar 13 15:11:57.003927 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     raise UnreadablePostError(*e.args) from e
  [Mon Mar 13 15:11:57.003930 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] django.http.request.UnreadablePostError: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
  
  2023-03-13 15:11:57,004 DEBG 'runserver' stderr output:
  [Mon Mar 13 15:11:57.004546 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] ERROR:django.request:Internal Server Error: /api/projects/backup/6be80b0b-0d23-444b-9630-6d80a9e409c2
  [Mon Mar 13 15:11:57.004560 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] Traceback (most recent call last):
  [Mon Mar 13 15:11:57.004564 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/http/request.py", line 391, in read
  [Mon Mar 13 15:11:57.004567 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return self._stream.read(*args, **kwargs)
  [Mon Mar 13 15:11:57.004570 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 34, in read
  [Mon Mar 13 15:11:57.004572 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     result = self.buffer + self._read_limited()
  [Mon Mar 13 15:11:57.004575 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
  
  2023-03-13 15:11:57,004 DEBG 'runserver' stderr output:
  [Mon Mar 13 15:11:57.004578 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     result = self.stream.read(size)
  [Mon Mar 13 15:11:57.004581 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] OSError: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
  [Mon Mar 13 15:11:57.004584 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] 
  [Mon Mar 13 15:11:57.004586 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] The above exception was the direct cause of the following exception:
  [Mon Mar 13 15:11:57.004589 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] 
  [Mon Mar 13 15:11:57.004591 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] Traceback (most recent call last):
  [Mon Mar 13 15:11:57.004594 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/http/request.py", line 336, in body
  [Mon Mar 13 15:11:57.004597 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     self._body = self.read()
  [Mon Mar 13 15:11:57.004599 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/http/request.py", line 393, in read
  [Mon Mar 13 15:11:57.004602 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     raise UnreadablePostError(*e.args) from e
  [Mon Mar 13 15:11:57.004605 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] django.http.request.UnreadablePostError: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
  [Mon Mar 13 15:11:57.004608 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] 
  [Mon Mar 13 15:11:57.004611 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] The above exception was the direct cause of the following exception:
  [Mon Mar 13 15:11:57.004614 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] 
  [Mon Mar 13 15:11:57.004616 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] Traceback (most recent call last):
  [Mon Mar 13 15:11:57.004619 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
  [Mon Mar 13 15:11:57.004621 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     response = get_response(request)
  [Mon Mar 13 15:11:57.004624 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
  [Mon Mar 13 15:11:57.004627 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
  [Mon Mar 13 15:11:57.004630 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  [Mon Mar 13 15:11:57.004633 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return view_func(*args, **kwargs)
  [Mon Mar 13 15:11:57.004636 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
  [Mon Mar 13 15:11:57.004638 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return self.dispatch(request, *args, **kwargs)
  [Mon Mar 13 15:11:57.004641 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
  [Mon Mar 13 15:11:57.004644 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     response = self.handle_exception(exc)
  [Mon Mar 13 15:11:57.004647 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
  [Mon Mar 13 15:11:57.004651 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     self.raise_uncaught_exception(exc)
  [Mon Mar 13 15:11:57.004654 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
  [Mon Mar 13 15:11:57.004657 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     raise exc
  [Mon Mar 13 15:11:57.004660 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
  [Mon Mar 13 15:11:57.004663 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     response = handler(request, *args, **kwargs)
  [Mon Mar 13 15:11:57.004665 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/home/django/cvat/apps/engine/views.py", line 621, in append_backup_chunk
  [Mon Mar 13 15:11:57.004668 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return self.append_tus_chunk(request, file_id)
  [Mon Mar 13 15:11:57.004671 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/home/django/cvat/apps/engine/mixins.py", line 202, in append_tus_chunk
  [Mon Mar 13 15:11:57.004673 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     chunk = TusChunk(request)
  [Mon Mar 13 15:11:57.004676 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/home/django/cvat/apps/engine/mixins.py", line 94, in __init__
  [Mon Mar 13 15:11:57.004678 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     self.content = request.body
  [Mon Mar 13 15:11:57.004681 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/request.py", line 416, in __getattr__
  [Mon Mar 13 15:11:57.004683 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     return getattr(self._request, attr)
  [Mon Mar 13 15:11:57.004686 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]   File "/opt/venv/lib/python3.8/site-packages/django/http/request.py", line 338, in body
  [Mon Mar 13 15:11:57.004689 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280]     raise UnreadablePostError(*e.args) from e
  [Mon Mar 13 15:11:57.004692 2023] [wsgi:error] [pid 86:tid 140342613079808] [remote 10.0.4.5:55280] django.http.request.UnreadablePostError: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
  
    </details>

**Comment by zhiltsov-max** [comment]
@azhavoro, could you please check the issue?

**Comment by atekoa** [comment]
We have upgraded to v2.4.0 and now the same backup that was failing before has worked. I only see difference in the time of each request, maybe it reached some kind of timeout?

![backup](https://user-images.githubusercontent.com/5947222/225891598-96d2ab80-5038-4b32-92d6-29f275995cac.jpg)

**Comment by nmanovic** [comment]
@atekoa , we have fixed a number of problems. If you cannot reproduce the issue on CVAT v2.4.0, I will close the issue. Thank you for the feedback.
