### ISSUE TITLE
Documentation: Add some examples of using search in a dashboard

### ISSUE THREAD

**Issue by kostasthebarbarian** [opencv/cvat#586]
Typing 'annotation' in search toolbar of dashboard does not filter tasks in 'annotation' mode.

**Comment by bsekachev** [comment]
@kostasthebarbarian 
Could you please provide some examples. It works for me right.

**Comment by kostasthebarbarian** [comment]
@bsekachev 
See attached screenshot. The filter is 'annotation' but I also get a completed task in the list.
I am on Mac OS.
<img width="1291" alt="Screen Shot 2019-07-24 at 1 49 32 PM" src="https://user-images.githubusercontent.com/7796006/61823946-123ed080-ae1a-11e9-9f1a-f7da166056ab.png">

**Comment by bsekachev** [comment]
@kostasthebarbarian 
If you want to see only tasks with a status "annotation", you need to write: "status: annotation"
When you write just "annotation", this word is searched in all task fields (name, mode, status, etc)

I agree, that probably there is a lack of documentation.

**Comment by kostasthebarbarian** [comment]
@bsekachev 
All clear. Thank you for the reply.

**Comment by kostasthebarbarian** [comment]
@bsekachev 
As far as examples are concerned, it would be good to know how to enter multiple search criteria, e.g., name:foo status:completed (I tried this and it did not work. Is the feature supported?)

**Comment by bsekachev** [comment]
@kostasthebarbarian 
Multiple requests aren't supported now

**Comment by bsekachev** [comment]
@kostasthebarbarian 
Ohh, I was wrong. 
You can do requests with several conditions.
Something like that: ```mode: annotation AND name: Images AND status: verification```
But only AND condition is supported.

**Comment by kostasthebarbarian** [comment]
@bsekachev 
Great, thanks for the reply.
