### ISSUE TITLE
Unable to move the line about 45 degrees

### ISSUE THREAD

**Issue by kgloveyou** [opencv/cvat#5870]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.draw a polyline about 45 degrees
2.hove on the polyline ,it is selected;But, the moving cursor cannot be displayed.
3.So, i can not move the polyline.
<img width="1920" alt="20230316181141" src="https://user-images.githubusercontent.com/5866147/225585465-767b26ca-bee4-417b-83f2-5ff6d2f870c8.png">

### Expected Behaviour
it is able to move the polyline.

### Current Behaviour
it is unable to move the polyline.

### Your Environment
https://app.cvat.ai/tasks/58787/jobs/57403

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
On your screenshot polyline is pinned. 
It is why you are unable to move it. Unpin it first. 

https://github.com/opencv/cvat/issues/4396#issuecomment-1060314472
