### ISSUE TITLE
What causes this error and how to handle it when running the server:debug development environment, even though the website runs normally

### ISSUE THREAD

**Issue by LamThanhNguyen** [opencv/cvat#5879]
![cvat_django_error](https://user-images.githubusercontent.com/48795168/225889939-8719112d-e3f3-4d7f-8b24-6759ea200a5e.png)

**Comment by azhavoro** [comment]
From https://opencv.github.io/cvat/docs/contributing/development-environment/:
```shell
 docker run -d --rm --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.45.0-rootless \
 run --server --set=decision_logs.console=true --set=services.cvat.url=http://host.docker.internal:7000 \
 --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules

```

**Comment by azhavoro** [comment]
You need to open ports like this:
```
cvat_vector:
    ports:
      - '8282:80'

  cvat_clickhouse:
    ports:
      - '8123:8123'
```
or dont pass these env variables here: https://github.com/opencv/cvat/blob/develop/.vscode/launch.json
```json
  "DJANGO_LOG_SERVER_HOST": "localhost",
  "DJANGO_LOG_SERVER_PORT": "8282"
```

**Comment by nmanovic** [comment]
@LamThanhNguyen , thanks for the question. I will close the issue. If you feel that we have not answered your question, please reopen and comment.
