### ISSUE TITLE
Could not create the task - 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by maecky** [opencv/cvat#5885]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create Azure Blob Store according to documentation
2. Upload image data (50k Images) and manifest file to blob storage
3. Create an empty Project
4. Create a new Task
    - Select previously created cloud storage
    - Select manifest file
    - Tick "select all" and choose all Images there
    - Advanced Conifguration:
         - untick "use cache"
         - untick "Use project source storage" -> select Cloud Storage
         - untick "Use project target storage" -> select Cloud Storage
5. Submit & Continue

### Expected Behaviour

Task is created and I can start labeling the dataset.

### Current Behaviour
Popup in the right upper corner:
"Could not create the task
Open the Browser Console to get details:

From the Browser Console:
```
xhr.js:220          POST http://localhost:8080/api/tasks/7/data?org=test504 (Gateway Timeout)
xhr.js:220          DELETE http://localhost:8080/api/tasks/7?org=test500 (Internal Server Error)
cvat-app.tsx:354 Error: Request failed with status code 504. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>504 Gateway Timeout</title>\n</head><body>\n<h1>Gateway Timeout</h1>\n<p>The gateway did not receive a timely response\nfrom the upstream server or application.</p>\n</body></html>\n".
```

### Your Environment
Latest updates from repository pulled and deployed with docker-compose.

I tried several combinations to create the task (with cache / without cache, with Project source storage enabled / disabled, etc)
Any ideas how I can solve this issue without mounting a local file store into the container are welcome :)

Thx!

**Comment by bsekachev** [comment]
Hi, @maecky 

Please, provide some logs from ``cvat_server`` container

**Comment by nmanovic** [comment]
@maecky , we need more information from you. Do you use the latest CVAT v2.4.0? Please attach logs as Boris asked. It will help us to identify the issue.

**Comment by maecky** [comment]
I'm on a business trip currently - will provide them at the end of the week when I have access to my machine again.

**Comment by maecky** [comment]
I wanted to reproduce the error but my cloud storage is not working anymore. So I tried to create a new cloud storage connection, but I get the same error in the browser now:


```
xhr.js:220          POST http://localhost:8080/api/cloudstorages?org=test 504 (Gateway Timeout)
cvat-app.tsx:354 Error: Request failed with status code 504. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>504 Gateway Timeout</title>\n</head><body>\n<h1>Gateway Timeout</h1>\n<p>The gateway did not receive a timely response\nfrom the upstream server or application.</p>\n</body></html>\n".
```

This is the cvat server log:

```
2023-03-28 11:17:20 2023-03-28 09:17:20,672 DEBG 'runserver' stderr output:
2023-03-28 11:17:20 [Tue Mar 28 09:17:20.672609 2023] [wsgi:error] [pid 104:tid 139812239501056] [client 172.20.0.7:59152] Timeout when reading response headers from daemon process 'localhost:8080': /tmp/cvat-server/htdocs/api, referer: http://localhost:8080/cloudstorages/create
2023-03-28 11:17:20 
2023-03-28 11:17:48 2023-03-28 09:17:48,176 DEBG 'runserver' stderr output:
2023-03-28 11:17:48 [Tue Mar 28 09:17:48.176409 2023] [wsgi:error] [pid 70:tid 139811715544832] [remote 172.20.0.7:59152] [2023-03-28 09:17:48,176] WARNING django.request: Bad Request: /api/cloudstorages
2023-03-28 11:17:48 
2023-03-28 11:17:48 2023-03-28 09:17:48,176 DEBG 'runserver' stderr output:
2023-03-28 11:17:48 [Tue Mar 28 09:17:48.176494 2023] [wsgi:error] [pid 70:tid 139811715544832] [remote 172.20.0.7:59152] WARNING:django.request:Bad Request: /api/cloudstorages
2023-03-28 11:17:48
```

**Comment by josiahls** [comment]
I think I have a similar issue with AWS. I have 2.4.2 installed based on the changelog. 

This worked for my validation set (which is smaller). I think depending on the cloud storage, its not waiting long enough if there are lots of cloud storage files.

**Comment by josiahls** [comment]
With the help of our almightly overlord gpt-4, I was able to solve this.

**Issue**: Timeout when reading response headers from daemon process while creating a task with a large number of images.

**Temporary Solution**: We increased various timeout settings in the `command` section of `[program:runserver]` in `supervisord/server.conf`. Additionally, we mounted the modified `supervisord.conf` into the `cvat_server` service in the `docker-compose.yml` file. Here are the changes made:

1. Added the following options to the `command` in the `[program:runserver]` section:

   ```
   --request-timeout 1200
   --connect-timeout 1200
   --socket-timeout 1200
   --queue-timeout 1200
   --header-timeout 1200
   --header-max-timeout 2400
   --header-min-rate 500
   ```

2. Added a volume mount in the `cvat_server` service of the `docker-compose.yml` file:

   ```
   volumes:
     - ./custom_supervisord.conf:/app/supervisord/server.conf
   ```

**Recommendation**: You can monitor the data download progress using PostgreSQL by running a query like:

```sql
SELECT count(*) FROM engine_serverfile WHERE data_id=58;
```

Replace `58` with the relevant `data_id` for your task.

As well as via docker:

`docker compose logs cvat_server -f`

and 

`docker compose logs cvat_worker_import -f`

**Note**: This is still a bug that needs to be addressed. The task creation takes a long time to download the images, and CVAT should not timeout when the download is actively in progress.

I now and also dealing with https://github.com/opencv/cvat/issues/5887

**Comment by handcreate** [comment]
I have a similar issue with [Connected file share]. This error occurs when it takes more than 60 seconds to import images. My cvat version: 2.4.3

**Comment by geometrikal** [comment]
Worked for me, just needed to change `/app/supervisord/server.conf` to `/home/django/supervisord/server.conf` for version v242

**Comment by arehmer** [comment]
I get the same Exception when using the Python Implementiation of cvat_sdk. I call  client.tasks.create_from_data() providing the path to a folder that contains roughly 5000 images. Then I get the following error message and exception
```
line 127, in create_task_from_data    task = client.tasks.create_from_data(spec=task_spec,...
line 372, in create_from_data    task.upload_data(...
line 125, in upload_data    DataUploader(self._client).upload_files(...
line 371, in upload_files response = self._client.api_client.rest_client.POST(
line 256, in POST    return self.request("POST", url,...
line 209, in request    raise ServiceException(http_resp=r)

ServiceException: Status Code: 504
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'Content-Length': '176', 'Content-Type': 'text/html', 'Date': 'Fri, 01 Sep 2023 08:53:57 GMT', 'Server': 'nginx/1.18.0 (Ubuntu)'})
HTTP response body: b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n'
```

I can upload about 1400 images no problem. Problems occured when uploading 2800 images or more. But I don't know where excatly the limit is.

**Comment by geometrikal** [comment]
@nmanovic solved this by increasing the server timeouts but it looks like the .conf file format has changed in latest versions (compared to v2.4.2). 

Is it possible to turn these task API endpoints that can potentially take a long time and time out into background tasks where you poll for status etc?
