### ISSUE TITLE
Win 10 CVAT error

### ISSUE THREAD

**Issue by modyngs** [opencv/cvat#5888]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. installing WLS2 with ubuntu 20.04, git, Docker Desktop integrated with WSL
1. git clone https://github.com/opencv/cvat && cd cvat && docker compose up -d

### Expected Behaviour

runs as smooth as possible!!

### Current Behaviour

it just runs for less than 5 min on port 8080 and then the whole docker container stops working and all the containers stops working!!

### Your Environment

- Git hash commit (`git log -1`): $ git log -1
commit cb72be0d5ac2a201411021119957ba77d2d7b9c3 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Roman Donchenko <roman@cvat.ai>
Date:   Fri Mar 17 20:03:24 2023 +0300

    Synchronize the main and full workflows (#5875)

    The full workflow is broken, because some changes from the main workflow
    weren't applied to it. Update them both to minimize differences between
    them.

- Docker version `docker version` (e.g. Docker 17.0.05): $docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Containers: 13
  Running: 4
  Paused: 0
  Stopped: 9
 Images: 10
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.38GiB
 Name: docker-desktop
 ID: YX66:AXPV:ZGJY:EUQZ:T3O6:6W7U:IEOH:VWRR:Q5A4:5UA7:SNXD:AO4O
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 Pro 22H2
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>2023-03-18 15:58:45 cvat_opa                | {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.18.0.10:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-03-18T12:28:45Z"} 
unexpected input error!!

</summary>
    </details>

**Comment by bsekachev** [comment]
Hi, @modyngs 

Please, provide logs from ``cvat_server`` container.

**Comment by nmanovic** [comment]
@modyngs , don't hesitate to reopen the issue if you can provide more details.
