### ISSUE TITLE
submit error

### ISSUE THREAD

**Issue by 180haguro** [opencv/cvat#589]
When I submit any pictures on Task Configuration window, window shows error message "Copyright (C) 2018 Intel Corporation SPDX-License-Identifier: MIT --> <!-- Copyright (c) 2018 by Tyler Fry .........".
Please let me know how can I resolve this error.

**Comment by bsekachev** [comment]
@180haguro 
Hi, could you please attach an output of the command ```docker logs cvat``` as a text file?
