### ISSUE TITLE
data privacy policy

### ISSUE THREAD

**Issue by neorosynapse** [opencv/cvat#5891]
Hello,

Im using CVAT for a company project. I have tested it and plan to upgrade to pro. My management concern is related to data privacy. Is the data deleted at the same time I delete it from my online repository? Is the data and annotations I have done kept somewhere safe and not distributed further? It would be nice if you could have some details.

Best regards,
Roberts

**Comment by nmanovic** [comment]
@neorosynapse ,

Please read our privacy and terms of use policies:
- https://www.cvat.ai/privacy
- https://www.cvat.ai/terms-of-use

>> Is the data deleted at the same time I delete it from my online repository?

If you delete a project or task, all related data will be deleted as well.

>> Is the data and annotations I have done kept somewhere safe and not distributed further?

All data is kept inside our DB on an AWS instance. It is safe and not distributed further.

We are ready to collaborate with your company to provide any other requested information. Don't hesitate to contact us using https://www.cvat.ai/get-in-touch

I will close the issue.
