### ISSUE TITLE
413 error for request - Request Entity Too Large

### ISSUE THREAD

**Issue by adammz1** [opencv/cvat#5895]
I am trying to upload > 3 gigabytes of data to cvat hosted on a private google compute server, as implemented here: https://opencv.github.io/cvat/docs/administration/basics/installation/

I receive error: 

Exception: 413 error for request <PreparedRequest [POST]> to url http://99.999.99.99:8080/api/tasks/36/data with the reason Request Entity Too Large. The requested resource does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

The code for uploading the images is below. This code works perfectly fine for smaller datasets. 

```
dataset = fo.Dataset.from_dir(
            name="dataset_name",
            data_path="path/to/folder",
            dataset_type=fo.types.YOLOv4Dataset,
            label_field="ground_truth",
            labels_path="path/to/labels",
            classes="error, request",
        )
```
Is there a parameter I can change in the CVAT server client side?

**Comment by nmanovic** [comment]
@adammz1 , which version of CVAT do you use? Is it the latest release v2.4.0?
Try to adjust the variable LOCAL_LOAD_MAX_FILES_SIZE: https://github.com/opencv/cvat/blob/befe77c8d4e7f70a0e1be89d1d1848446e8fb423/cvat/settings/base.py#L504

**Comment by bsekachev** [comment]
Closed as outdated. If still relevant, please, reopen

**Comment by fkite-cs** [comment]
hi @bsekachev, im getting the same error when i upload the annotations to cvat (UI). The size of my zip file is 33 MB.
i have been testing different versions (2.4.6 to 2.4.0) and i always get the same error.
LOCAL_LOAD_MAX_FILES_SIZE = 512 * 1024 * 1024  # 512 MB  has the same value.
Do you know if some configuration of the host computer could trigger this error or is there other parameter in cvat configuration that i need to change?
