### ISSUE TITLE
Can not login to CVAT on kubernetes k3s installed via helm

### ISSUE THREAD

**Issue by dskudney** [opencv/cvat#5897]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Follow the Helm install instructions without overrides
1. The install went well and all pods are running
2. I can port forward the backend server and front end server and hit the login page
3. I did create a super user

### Expected Behaviour
Should be able to login 

### Current Behaviour
![image](https://user-images.githubusercontent.com/549715/226718172-79ff0299-c369-410d-aa88-c6dba60c4907.png)

![image](https://user-images.githubusercontent.com/549715/226718448-47901774-ee60-4009-8b2b-85fe7ccf20fc.png)

### Your Environment
Running in a VM on a k3s instance kubernetes version 1.25

**Comment by azhavoro** [comment]
The issue is defenetly related with ingress, that route all requests to the frontend insdead of backend for a reason, could you provide output of `kubectl describe ingress cvat`

**Comment by dskudney** [comment]
Thank you for the response as I really want to get this working

Following you will find the output from  __kubectl describe ingress -n _cvat___ 

![image](https://user-images.githubusercontent.com/549715/226922627-488b93ce-a233-4729-9ce1-fc5615cf8162.png)

**Comment by azhavoro** [comment]
> I can port forward the backend server and front end server and hit the login page

This will not work, you need expose traefik LB service ports instead of cvat application servece ports, please read k3s docs https://docs.k3s.io/networking

**Comment by dskudney** [comment]
I am not using the Traefik / k3s load balancer 

In other words, I disabled the Traefik that ships with k3s and I'm using the Traefik that ships with CVAT with the default configuration and you can see an External IP is set on the LB

Are you saying I have to create IngressRoutes for the services as well ?

Your doc's do not mention anything like that other than a reference to Minikube

With regard to port-forwarding when I disable the load balancer, I should be able to port forward but that does not work as I've tried it.

![image](https://user-images.githubusercontent.com/549715/227531012-752b5c25-516b-49ad-88f6-e7f50d2d0b84.png)
