### ISSUE TITLE
Error : The container name "/cvat_..." is already in use by container "..."

### ISSUE THREAD

**Issue by LouisSnz** [opencv/cvat#5907]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi everyone,

I try to setup CVAT locally and then I will try to run it on a local server. I have some errors when I use the `docker-compose`. It tells me that containers names are already in use.

I am out of ideas, some help would be much appreciated.

### Steps to Reproduce (for bugs)

I execute the following commands to start the docker:
```
git clone https://github.com/cvat-ai/cvat
cd cvat
docker-compose up -d
```
### Expected Behaviour

The docker should run normally, I guess.

### Current Behaviour

```
docker-compose up -d

Creating network "cvat_cvat" with the default driver
Creating cvat_redis      ... done
Creating cvat_opa        ... done
Creating cvat_grafana ... 
Creating traefik         ... done
Creating cvat_clickhouse ... 
Creating cvat_db         ... done
Creating cvat_worker_webhooks ... 
Creating cvat_worker_export   ... 
Creating cvat_worker_import     ... 
Creating cvat_utils             ... 
Creating cvat_utils             ... error
Creating cvat_worker_annotation ... 
Creating cvat_worker_import     ... error
ERROR: for cvat_utils  Cannot create container for service cvat_utils: Conflict. The container name "/cvat_utils" is already in use by container "d1b2e4621e5f1bd0ba8b3014da853497e893b8a927fbc4ad0b3914ad1bCreating cvat_worker_annotation ... error
ERROR: for cvat_worker_import  Cannot create container for service cvat_worker_import: Conflict. The container name "/cvat_worker_import" is already in use by container "aaaf8838da1e5d5c47c60f7065889dcc6613c3d271fe234bc0a60061a2c33d53". You have to remove (or rename) that container to be able to reuse that name.
Creating cvat_worker_webhooks   ... error
ERROR: for cvat_worker_annotation  Cannot create container for service cvat_worker_annotation: Conflict. The container name "/cvat_worker_annotation" is already in use by container "1e1a0d8aa5850bb15fb241Creating cvat_grafana           ... done
Creating cvat_clickhouse        ... done
9f5f73e96". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for cvat_worker_webhooks  Cannot create container for service cvat_worker_webhooks: Conflict. The container name "/cvat_worker_webhooks" is already in use by container "1d28c512f23ddde3b9042520db210a8b4331e2d37768d3e1727e28345487f7c3". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for cvat_worker_export  Cannot create container for service cvat_worker_export: Conflict. The container name "/cvat_worker_export" is already in use by container "64b43a9ef091493419060e0b541b9027ee28da9177f0d19c35914897cda276e5". You have to remove (or rename) that container to be able to reuse that name.
Creating cvat_vector            ... done
ERROR: for cvat_utils  Cannot create container for service cvat_utils: Conflict. The container name "/cvat_utils" is already in use by container "d1b2e4621e5f1bd0ba8b3014da853497e893b8a927fbc4ad0b3914ad1b989fa0". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for cvat_worker_import  Cannot create container for service cvat_worker_import: Conflict. The container name "/cvat_worker_import" is already in use by container "aaaf8838da1e5d5c47c60f7065889dcc6613c3d271fe234bc0a60061a2c33d53". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for cvat_worker_annotation  Cannot create container for service cvat_worker_annotation: Conflict. The container name "/cvat_worker_annotation" is already in use by container "1e1a0d8aa5850bb15fb2418e4cfc0c771fdb97f383051a745e5be92a66bf978c". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for cvat_server  Cannot create container for service cvat_server: Conflict. The container name "/cvat_server" is already in use by container "cc12152cc41f9728f6843249ef5387403f951d65396e29adaed94c49f5f73e96". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for cvat_worker_webhooks  Cannot create container for service cvat_worker_webhooks: Conflict. The container name "/cvat_worker_webhooks" is already in use by container "1d28c512f23ddde3b9042520db210a8b4331e2d37768d3e1727e28345487f7c3". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for cvat_worker_export  Cannot create container for service cvat_worker_export: Conflict. The container name "/cvat_worker_export" is already in use by container "64b43a9ef091493419060e0b541b9027ee28da9177f0d19c35914897cda276e5". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```

### Possible Solution

I have tried many things:
- I have tried to down and up the docker multiple times.
- I purged completely every containers, volumes and images on docker with this command `docker system prune --all --volumes`
- I restarted my docker with `sudo systemctl restart docker`
- I reinstalled completely Docker.

None of these solutions worked, and I am out of ideas...

### Your Environment

- Git hash commit (`git log -1`): 
commit befe77c8d4e7f70a0e1be89d1d1848446e8fb423 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05):
    <details>
    <summary> `docker version` </summary>
    
    Client:
     Version:           20.10.21
     API version:       1.41
     Go version:        go1.18.1
     Git commit:        20.10.21-0ubuntu1~22.04.2
     Built:             Thu Mar  2 18:26:04 2023
     OS/Arch:           linux/amd64
     Context:           default
     Experimental:      true
    
    Server:
     Engine:
      Version:          20.10.21
      API version:      1.41 (minimum version 1.12)
      Go version:       go1.18.1
      Git commit:       20.10.21-0ubuntu1 22.04.2
      Built:            Wed Feb 15 15:26:57 2023
      OS/Arch:          linux/amd64
      Experimental:     false
     containerd:
      Version:          1.6.12-0ubuntu1 22.04.1
      GitCommit:        
     runc:
      Version:          1.1.4-0ubuntu1 22.04.1
      GitCommit:        
     docker-init:
      Version:          0.19.0
      GitCommit: 

     </details>

- Are you using Docker Swarm or Kubernetes? Docker Swarm
- Operating System and version (e.g. Linux, Windows, MacOS): Linux - Pop!_OS 22.04 LTS
- Code example or link to GitHub repo or gist to reproduce problem: -
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by nmanovic** [comment]
@LouisSnz, I will close the issue. Don't hesitate to reopen if the question isn't answered.
