### ISSUE TITLE
The image cannot be displayed on the canvas

### ISSUE THREAD

**Issue by zrh617** [opencv/cvat#5910]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

Method One:
1.import 'download.worker' file
`import DownloadWorker from './download.worker';`
2.The problem that pops up as follows, the code shows it isn't a constructor。
`export 'default' (imported as 'DownloadWorker') was not found in './download.worker' (module has no exports)`

Method Two:
1.Change the code of the file 'download.worker' to
```import Axios from 'axios';

Axios.defaults.withCredentials = true;
Axios.defaults.xsrfHeaderName = 'X-CSRFTOKEN';
Axios.defaults.xsrfCookieName = 'csrftoken';

class DownloadService {
    postMessage = async (e) => {
        console.log(e, 'e');
        await Axios.get(e.url, e.config)
            .then((response) => {
                console.log(response, 'response');
                postMessage({
                    responseData: response.data,
                    id: e.id,
                    isSuccess: true,
                });
                return response
            })
            .catch((error) => {
                console.log(error, 'error');
                postMessage({
                    id: e.id,
                    status: error.response.status,
                    responseData: error.response.data,
                    isSuccess: false,
                });
            });
    }
    onmessage = (e) => {
        Axios.get(e.data.url, e.data.config)
            .then((response) => {
                postMessage({
                    responseData: response.data,
                    id: e.data.id,
                    isSuccess: true,
                });
            })
            .catch((error) => {
                postMessage({
                    id: e.data.id,
                    status: error.response.status,
                    responseData: error.response.data,
                    isSuccess: false,
                });
            });
    };
}

export default DownloadService
```
2. The code will not continue to execute after calling the image acquisition interface，methods that do not perform decoding.

### Expected Behaviour

After obtaining the picture, it is successfully decoded and displayed on the canvas

### Current Behaviour

After getting the picture, the execution of the subsequent code is blocked, and it keeps going in circles.

### Context

Now I can't decode the data returned by the server and display the picture on the container.
**I'm not sure whether it's the download.worker.js file or the cvat-data file. Can you help me solve my doubts?**

**Comment by zrh617** [comment]
![image](https://user-images.githubusercontent.com/52558007/227117375-61ebf2bc-d3f2-4bb4-8553-671bfccdeeba.png)

**Comment by zrh617** [comment]
![image](https://user-images.githubusercontent.com/52558007/227117474-1249362a-7737-4ac8-a317-ae8da535683b.png)

**Comment by zrh617** [comment]
> Please, provide some more information, like logs from the browser console for example. How did you install CVAT? What is the version? Can you provide data decoding does not work with?
> 
> `./download.worker` is actually JS worker, it is not like a regular JS module. It is why you see errors in source code, but they should not affect working. At least we didn't have issues with it.

Hi, I install CVAT by git clone. I tried version release-2.3.0 and dev but it also didn't work.

Steps to Reproduce (for bugs):
1.I checked MDN's documentation on Web Workers，and change `./download.worker` as follows，then it is no error and work.
```
import Axios from 'axios';

Axios.defaults.withCredentials = true;
Axios.defaults.xsrfHeaderName = 'X-CSRFTOKEN';
Axios.defaults.xsrfCookieName = 'csrftoken';

onmessage = (e) => {
    Axios.get(e.data.url, e.data.config)
        .then((response) => {
            postMessage({
                responseData: response.data,
                id: e.data.id,
                isSuccess: true,
            });
        })
        .catch((error) => {
            postMessage({
                id: e.data.id,
                status: error.response.status,
                responseData: error.response.data,
                isSuccess: false,
            });
        });
};

export default onmessage
```
2. If I new WorkerWrappedAxios like source code，and then as follows:
![image](https://user-images.githubusercontent.com/52558007/227200314-dab3e687-0400-4c4c-ac64-ad11f2c2638b.png)

![image](https://user-images.githubusercontent.com/52558007/227200457-0029d139-e686-45a4-b375-e51e1602ba9c.png)

![image](https://user-images.githubusercontent.com/52558007/227199996-8c75c114-77fa-4488-b7f6-6819f28fc02d.png)

It will frantically request the interface，the reason seems to be postmessage during initialization.

3. If I new WorkerWrappedAxios in function getData，and then as follows, other errors are reported by antd.
![image](https://user-images.githubusercontent.com/52558007/227202357-11455d88-63b2-4f77-89e0-1c2ae282a30e.png)

![image](https://user-images.githubusercontent.com/52558007/227202427-3357e8a7-2802-4b5a-b5ea-f20c42f8ad98.png)

![image](https://user-images.githubusercontent.com/52558007/227202548-7a5ef4d7-2d20-46ed-9156-bf4d5357e6b3.png)

It will not call the request image interface, it can only postmessage once.

4. Thank you very much for your help.

**Comment by zrh617** [comment]
> Please, provide some more information, like logs from the browser console for example. How did you install CVAT? What is the version? Can you provide data decoding does not work with?
> 
> `./download.worker` is actually JS worker, it is not like a regular JS module. It is why you see errors in source code, but they should not affect working. At least we didn't have issues with it.

This is my [code address](https://github.com/zrh617/CVAT-Demo/tree/main). React ^18.2.0, react-router-dom ^6.4.3, antd ^5.0.1.

Currently, the front-end and back-end are separated, so only the front-end code.Thanks again!

**Comment by Gaoee** [comment]
I also got the same problem. I want to use CVAT front-end separately in my project, but it is unable to show images in the annotation page.

**Comment by zrh617** [comment]
Now my code can call the image acquisition interface, and the process can run normally, but the image still cannot be displayed.

[I updated the code on github](https://github.com/zrh617/CVAT-Demo). What's the problem, could you help me?
