### ISSUE TITLE
Export an image dataset to Datumaro format has point_cloud field

### ISSUE THREAD

**Issue by vinnamkim** [opencv/cvat#5924]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. Import this project backup in CVAT 2.4: [car_tree_bug_cvat.zip](https://github.com/opencv/cvat/files/11058077/car_tree_bug_cvat.zip)
1. Export it to Datumaro 1.0 format with **turning off "Save images" option**
1. The exported annotation file has a `point_cloud` field although there is no point cloud in the dataset:
```json
{
    "id": "Slide9",
    "annotations": [
        // ...
    ],
    "attr": {
        "frame": 5
    },
    "point_cloud": {
        "path": ""
    },
    "media": {
        "path": ""
    }
}
```

### Expected Behaviour
The `point_cloud` field should be removed.

### Current Behaviour
The `point_cloud` field exists.

### Context

While investigating https://github.com/openvinotoolkit/datumaro/issues/873, I found it.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi. I suppose, the reason is that CVAT uses an outdated version of Datumaro, which exports annotations in an old format version, if it has been modified in the later releases. Currently, CVAT is at the customized release 0.3 (available [here](https://github.com/cvat-ai/datumaro)).

**Comment by zhiltsov-max** [comment]
Hi. I suppose, the reason is that CVAT uses an outdated version of Datumaro, which exports annotations in an old format version, if it has been modified in the later releases. Currently, CVAT is at the customized release 0.3 (available [here](https://github.com/cvat-ai/datumaro)).
