### ISSUE TITLE
Export of a job with tracks from a task with multiple jobs failed

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#5927]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create a task with several jobs
1. Add a track to the second job
1. Export job dataset

### Expected Behaviour

Job export completed successfully

### Current Behaviour

"KeyError: 'type'\n".

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by LightningApple** [comment]
I encountered a similar problem. Because in the same frame, some objects I created by shape, and some objects I created by track. 
![image](https://user-images.githubusercontent.com/20971522/229433820-33c2a872-2f67-449d-a9b8-c75e0364ad1b.png)
