### ISSUE TITLE
Is it possible to edit id of an object for MOT data format?

### ISSUE THREAD

**Issue by hardikdava** [opencv/cvat#5935]
Hello CVAT developers, I want to label a video for multi object tracking task and want to export annotations in MOT format. I guess MOT data format is supported currently. But I also want to change an object id for annotating an object throughout the frames. An idea is to generate detections using automatic annotations and then change an object id instead of using predefined object id. So is it possible to change an object id during annotation session? If so, then how can I do it?

**Comment by zhiltsov-max** [comment]
Hi, there is no way to do this from CVAT now. As an option, you can try to export in different format that supports attributes, while adding an `object_id` attribute during annotating.

**Comment by hardikdava** [comment]
Thank you for your reply @zhiltsov-max . Is there any long term tracker available in cvat? If not, then how can I implement it? Where can I find reiD apis?
