### ISSUE TITLE
cannot create new project with sdk

### ISSUE THREAD

**Issue by tomliumd** [opencv/cvat#5943]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am attempting to create a new blank project with the cvat_sdk. The api client raises an ApiType error

### Steps to Reproduce (for bugs)

```python
from cvat_sdk.api_client import Configuration, ApiClient, exceptions
from cvat_sdk.api_client.model.project_read import ProjectRead
from cvat_sdk.api_client.model.project_write_request import ProjectWriteRequest
from pprint import pprint

# Set up an API client
# Read Configuration class docs for more info about parameters and authentication methods
configuration = Configuration(
    host = "http://localhost:8080",
    username = 'django',
    password = 'password',
)

api_client = ApiClient(configuration)
project_write_request = ProjectWriteRequest(
    name="name_example",
    labels=[],
) 

(data, response) = api_client.projects_api.create(
    project_write_request,
)
```

### Expected Behaviour
This should post a new project with name. 

### Current Behaviour
cvat_sdk.api_client.exceptions.ApiTypeError: Invalid type for variable 'tasks'. Required value type is list and passed type was str at ['received_data']['tasks']

### Possible Solution
Not sure

### Context
I am trying to create a project using the sdk api and then assign tasks to this project.

**Comment by nmanovic** [comment]
@SpecLad , could you please look at the issue?

**Comment by SpecLad** [comment]
Most likely, it's a mismatch between the server and SDK versions. Which versions are you using?

**Comment by nmanovic** [comment]
I will close the issue. Don't hesitate to reopen it if you can provide more information.
