### ISSUE TITLE
"'Only one manifest file can be attached to data'".

### ISSUE THREAD

**Issue by lschaupp** [opencv/cvat#5949]
Having this error message when restoring a project.

1. Backup current project
2. Restore project

Any help?

**Comment by nmanovic** [comment]
@lschaupp , could you please provide more information? Please try to create a similar project on http://app.cvat.ai/ and reproduce the issue. It will help us a lot.

**Comment by nmanovic** [comment]
I will close the issue. Don't hesitate to reopen it if you can provide more information.
