### ISSUE TITLE
 server issue 

### ISSUE THREAD

**Issue by nayab-1** [opencv/cvat#5952]
we are facing the server issue.
![Screenshot from 2023-03-29 12-52-34](https://user-images.githubusercontent.com/129262802/228458285-7a6ab899-2c4e-4201-a471-ad97d77afc2d.png)

**Comment by nmanovic** [comment]
@nayab-1 , again I will close the issue as invalid. Most probably you do something wrong. Please ask our community before create an issue on github.
You always can use our CVAT.ai cloud (http://app.cvat.ai/) if you have difficulties to setup CVAT on your own.
