### ISSUE TITLE
aws deployment issue with Django

### ISSUE THREAD

**Issue by Lee4396** [opencv/cvat#5963]
[Mon Apr 03 10:25:43.138195 2023] [wsgi:error] [pid 70:tid 140422208788224] [remote 10.78.40.178:22442] [2023-04-03 10:25:43,138] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '10.78.40.235:8080'. You may need to add '10.78.40.235' to ALLOWED_HOSTS.

above is the error message, any similar issues?

**Comment by Lee4396** [comment]
anyone tried setting up cvat with fargate?

**Comment by nmanovic** [comment]
@Lee4396 , please ask our community https://gitter.im/opencv-cvat/public or https://discord.gg/fNR3eXfk6C. Also try to look at our FAQ. Probably you need to setup only CVAT_HOST variable.

I will close the issue. We keep here only bug reports or feature requests.

**Comment by Lee4396** [comment]
Hi @nmanovic,

I dont know if this is a bug or sth else, but I have been looking through the discussion and issues, seems all of them are setting up the server with the docker compose methad. However, I am trying to set it up with AWS Aurora and elasticcache providing the database and caching services as the instruction suggests.

I am able to connect to the db and redis for I have checked the connection counts as well as the new records cvat writes, and it says available like this 'cvat-redis-test-002.snmk2q.0001.euc1.cache.amazonaws.com:6379 is available after 0 seconds
'

However, when I try to access the server with port 8080 I always get the following logs from cvat and a code 410:

2023-04-11 13:16:40,491 DEBG 'runserver' stderr output:
[Tue Apr 11 13:16:40.490856 2023] [wsgi:error] [pid 200:tid 140276898047744] [remote 10.112.121.81:27958] WARNING - 2023-04-11 13:16:40,490 - base - Gone: /

2023-04-11 13:16:40,491 DEBG 'runserver' stderr output:
[Tue Apr 11 13:16:40.491446 2023] [wsgi:error] [pid 200:tid 140276898047744] [remote 10.112.121.81:27958] [2023-04-11 13:16:40,491] WARNING django.request: Gone: /

2023-04-11 13:16:40,492 DEBG 'runserver' stderr output:
[Tue Apr 11 13:16:40.491543 2023] [wsgi:error] [pid 200:tid 140276898047744] [remote 10.112.121.81:27958] WARNING - 2023-04-11 13:16:40,491 - log - Gone: /

The code I use to run the server is:
docker run -p 8080:8080 --name cvat-server -e CVAT_POSTGRES_HOST=XXXX -e CVAT_POSTGRES_PASSWORD=XXXXX -e CVAT_REDIS_HOST=XXXX -e DJANGO_MODWSGI_EXTRA_ARGS= -e ALLOWED_HOSTS=* -d openvino/cvat_server
where XXXX is the the specific of the service detail

the only address I can access is admin/login. I am wondering if it is because the ui is not included in the server and we need to run a separate cvatui? and if so, how do we connect the ui to the server since the dockerfile doesnt provide the option for me to operate. Thank you.
