### ISSUE TITLE
Image quality should not be capped at 95

### ISSUE THREAD

**Issue by HashiamKadhim** [opencv/cvat#597]
Image quality should be a user selected parameter, why bound it by 95?

**Comment by bsekachev** [comment]
@HashiamKadhim 
Hi, 95 is the highest value of quality supported by the Pillow library. 
But for a user it might be better, to normalize values between 1 and 100. 
We would be grateful if you prepare PR for it

**Comment by nmanovic** [comment]
Hi @HashiamKadhim ,

I will close the issue for now. 

From Pillow documentation: https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html
```
quality
The image quality, on a scale from 1 (worst) to 95 (best). The default is 75. Values above 95 should be avoided; 100 disables portions of the JPEG compression algorithm, and results in large files with hardly any gain in image quality.
```
