### ISSUE TITLE
Uploading data in chunks using Upload-Start and Upload-Finish Results in an error

### ISSUE THREAD

**Issue by patches11** [opencv/cvat#5983]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I am using the API to create a task and then attaching a large number of server files to the task.

Because there are so many files, attaching via a single request times out. I am attempting to split this task up using the Upload-Start and Upload-Finish headers, but this results in an error on the server like this:

 Key (data_id, file)=(896, /home/django/data/data/896/raw/manifest.jsonl) already exists.

### Steps to Reproduce (for bugs)
1. Create a task via the API /api/tasks
2. Post multipart form data using Upload-Start /api/tasks/{task_id}/data
3. Post an initial request to /api/tasks/{task_id}/data with server_files, which will work
4. Error - on second post to /api/tasks/{task_id}/data with server_files

### Your Environment
K8s install of cvat 2.4.0

**Comment by zhiltsov-max** [comment]
Hi, could you please specify which files are being uploaded? Do you specify only `server_files`? Multiple-request uploads are only possible with `client_files`, and they must follow the protocol as shown [here](https://github.com/opencv/cvat/issues/5847#issuecomment-1468564437).

**Comment by patches11** [comment]
Yes I am specifying 90k server_files, I do not specify client_files.

It times out because the request with 90k files, even if it is just filesnames, take too long

**Comment by zhiltsov-max** [comment]
Could you please try to split the task into several tasks in one project? Is it possible in your case?

**Comment by patches11** [comment]
That isn't ideal for our use case, but yes we could try that.

For now I believe I have solved my issue by sending a directory in server_files
