### ISSUE TITLE
Modification on cvat-ui doesn't apply when restarting the docker

### ISSUE THREAD

**Issue by AgapeGithub** [opencv/cvat#5986]
### My actions before raising this issue

I want to disable the image downloading the annotation so i modify some code :
https://github.com/opencv/cvat/blob/master/cvat-ui/src/components/export-dataset/export-dataset-modal.tsx

line 126 : "values.saveImages," changed to "false,"
line 136 : "const resource = values.saveImages ? 'Dataset' : 'Annotations';" changed to "const resource = 'Annotations';"

But unfortunately when i restart the docker (docker compose down then docker compose up) the modification didn't apply.

Could you help me to apply the modification please?

### Steps to Reproduce (for bugs)
modify some code in :
https://github.com/opencv/cvat/blob/master/cvat-ui/src/components/export-dataset/export-dataset-modal.tsx

here are the changes :
line 126 : "values.saveImages," changed to "false,"
line 136 : "const resource = values.saveImages ? 'Dataset' : 'Annotations';" changed to "const resource = 'Annotations';"

### Expected Behaviour
To Disable indefinitly the checkbox "Save Images" when exporting annotation

### Current Behaviour
No Change in the code

**Comment by bsekachev** [comment]
@AgapeGithub 

You need to restart docker images if you did changes with ``--build``. 
Also do not forget to include ``docker-compose.dev.yml`` file.

**Comment by nmanovic** [comment]
I will close the issue.

**Comment by AgapeGithub** [comment]
Thank you very much everyone, sorry i was off till now so i didn't see your message,

@bsekachev  could you please give me the exact command to execute?
i tried with 
# docker compose build docker-compose.dev.yml

but it didn't work

**Comment by bsekachev** [comment]
Exact command depends on modules you enabled in your CVAT build. 

In general it might be like: ``docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build``

**Comment by AgapeGithub** [comment]
<img width="430" alt="Capture" src="https://user-images.githubusercontent.com/92428893/230600924-691b73ae-8d73-410f-9d6b-7bba05d69867.PNG">

when i execute it send me this error, could you help me what's wrong in it please?

**Comment by bsekachev** [comment]
@zhiltsov-max 

Datumaro can't be fetched. Any ideas?

**Comment by zhiltsov-max** [comment]
As I see, the building process can't reach github.com. It can happen because of many problems, including internet proxy settings (if proxy is used), and because GitHub can be down (can be checked [here](https://www.githubstatus.com/history)).  Please make sure github is reachable during the build.
