### ISSUE TITLE
group id

### ISSUE THREAD

**Issue by hyunk525** [opencv/cvat#5992]
Hello, when the same object appears in different tasks, can I give the same group id? or is there a way I can modify the group id myself?

**Comment by zhiltsov-max** [comment]
Hi. Groups do only work within a single frame of a single job/task. If you want to annotate the same object on different frames of the same jobs/tasks, consider using Tracks. There is no way currently to indicate relationships between annotations in different tasks. If you need this, consider using a custom label attribute.
