### ISSUE TITLE
Not able to get jobs with task_id using CVAT_SDK, 

### ISSUE THREAD

**Issue by MIRA-KUMAR** [opencv/cvat#5995]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Documentation is very bad, I'm going through all docs, and I don't know why I'm getting the error. 
I got paginated tasks using project id, but not for jobs with task_id, using the same types of functions. 

from functools import reduce
from flask import request, jsonify
from helpers.auth import auth
from cvat_sdk.api_client import ApiClient, Configuration
from cvat_sdk.core.helpers import get_paginated_collection

def get_all_jobs(project_id, task_id):
    print(project_id, task_id)
    tokens = auth(request.headers.get("Authorization"))
    
    if not tokens:
        return {"error":"Unauthorized"}, 401
    
   
    configuration = Configuration(host="http://localhost:8080", 
                                  api_key={
                                    "sessionAuth": tokens[2],
                                    "csrfAuth": tokens[3],
                                    "tokenAuth": tokens[4],
                                  })

    with ApiClient(configuration) as api_client:
        data= get_paginated_collection(api_client.tasks_api.list_jobs_endpoint, id=task_id, return_json=True)
        
        data = reduce(lambda x, y: x + y, data)

    return jsonify({"data": data}), 200, { "Content-Type": "application/json"}

        
Getting error:-

raise ApiTypeError(
cvat_sdk.api_client.exceptions.ApiTypeError: Got an unexpected parameter 'page' to method `list_jobs`

### Steps to Reproduce (for bugs)

1. Check above

PLease provide an update soon. 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by nmanovic** [comment]
@SpecLad , could you please look at the issue?
