### ISSUE TITLE
Error: Database is locked on localhost:3000

### ISSUE THREAD

**Issue by zhitm** [opencv/cvat#5996]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Install cvat as [here](https://opencv.github.io/cvat/docs/administration/basics/installation/#how-to-pullbuildupdate-cvat-images)
2. ```docker run -d --rm --name cvat_opa_debug -p 8181:8181 -v ${PWD}/cvat/apps/iam/rules:/rules --network=host openpolicyagent/opa:0.45.0-rootless run --server --set=decision_logs.console=true /rules```
3. Go to localhost:3000
4. I have an error while creating task: database is locked

### Context

I am using dev branch code and I want to integrate my tracker in c++ by addons instead of TrackerMil.

### Your Environment
- Docker version `docker version` (e.g. Docker 17.0.05): 23.0.3
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.10

**Comment by bsekachev** [comment]
Hi @zhitm 

Thanks for the report. 
In ``cvat/cvat/settings/development.py`` try to remove the following lines and restart the server:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/40690378/230877624-974cab7e-6014-475f-bc06-6c40f0261c70.png">

**Comment by zhitm** [comment]
> Hi @zhitm
> 
> Thanks for the report. In `cvat/cvat/settings/development.py` try to remove the following lines and restart the server:
> 
> <img alt="image" width="200" src="https://user-images.githubusercontent.com/40690378/230877624-974cab7e-6014-475f-bc06-6c40f0261c70.png">

Thank you for quick answer! It works.
