### ISSUE TITLE
Undo functionality

### ISSUE THREAD

**Issue by headdab** [opencv/cvat#6]
Have you considered undo functionality?
Seems like that would be a very useful feature.
Thanks.

**Comment by nmanovic** [comment]
@headdab,

We agree. It is a very useful feature. I'm not sure that it will be delivered in our next release but we will try to implement it in the future. Do you have any idea how it should be implemented to be convenient for you? For example, it can be per frame/image only or global with jumps to corresponding frames.

**Comment by headdab** [comment]
I haven't used the tool enough to have a strong opinion, but the case I'm most concerned about is when I delete something, like a track, accidentally and want to recover it.

Intuitively, I think it should just undo exactly what the last keystroke or mouse click did.
However, I think it only needs to undo database visible changes, i.e., we don't need to undo frame seeking, that type of thing.

**Comment by nmanovic** [comment]
Done in `develop` branch. Documentation will be updated lately.
