### ISSUE TITLE
Adding annotations or custom model to my CVAT environment

### ISSUE THREAD

**Issue by fschvart** [opencv/cvat#6001]
I've searched online and couldn't find a good guide or any instructions on how to upload semantic masks and use them as annotations in CVAT.

I have an mmsegmentation-based model, and I want to add it, or its inference results to CVAT. 
I want to make my annotators life easier and have them fix the small errors that the model does, rather than annotating from scratch.

My model generates semantic bitmap masks, so I was wondering, what is the best way to add the annotation results to CVAT? I saw that there's a format called Segmentation Masks 1.1, but couldn't find anywhere if that's what I'm looking for, and if so, how should I structure the file I upload. 

I'll really appreciate your help!

**Comment by bsekachev** [comment]
On the main page we have a list of supported formats. 
<img width="607" alt="image" src="https://github.com/opencv/cvat/assets/40690378/87f3ff82-03f0-4af1-9572-8e0e2a9dce80">


Please, keep your annotations in one of them and upload them to CVAT using standard pipeline: https://opencv.github.io/cvat/docs/manual/advanced/export-import-datasets/
