### ISSUE TITLE
Add actions button in the task jobs list

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#6005]
Currently, the UI displays the Actions button on the task page

![image](https://user-images.githubusercontent.com/13832349/231117872-fdf6bea9-61b0-4e6c-9a18-6d37f84341e9.png)

It works for the task, but there is no such button for the jobs list below.

However, there is such element for jobs in the jobs list on the Jobs tab:

![image](https://user-images.githubusercontent.com/13832349/231118431-971f1f59-b77c-4640-b55b-d4b9b53e8808.png)

The suggestion is to add more buttons to the job actions (e.g. clear annotations) and to add such actions button to the task jobs list. This will help to reduce the number of actions needed to do some things with the job (we will be able to skip job loading, page switches etc.).

Version: a7f7ff1 (2.4.1)

**Comment by bsekachev** [comment]
Added
