### ISSUE TITLE
CVAT_UI Fails building

### ISSUE THREAD

**Issue by visheshsom** [opencv/cvat#6009]
Hello,

I encountered an issue when trying to build the CVAT
![error](https://user-images.githubusercontent.com/24978566/231243273-4b4f51ee-95e7-4b38-a698-972c15d7982f.png)
. The build process fails with exit code 137. Here are the relevant error messages from the build output:

**=> ERROR [cvat-ui 16/16] RUN CLIENT_PLUGINS="${CLIENT_PLUGINS}" UI_APP_CONFIG="${UI_APP_CONFIG}" yarn run build:cvat-ui**                                                                                                                                              24.8s
------
 > [cvat-ui 16/16] RUN CLIENT_PLUGINS="${CLIENT_PLUGINS}" UI_APP_CONFIG="${UI_APP_CONFIG}" yarn run build:cvat-ui:
#0 2.342 yarn run v1.22.19
#0 2.376 $ yarn workspace cvat-ui run build
#0 2.695 $ webpack --config ./webpack.config.js
#0 4.398 List of plugins:  []
#0 24.11 Killed
#0 24.18 error Command failed with exit code 137.
#0 24.18 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 24.38 error Command failed.
#0 24.38 Exit code: 137
#0 24.38 Command: /usr/local/bin/node
#0 24.38 Arguments: /opt/yarn-v1.22.19/lib/cli.js run build
#0 24.38 Directory: /tmp/cvat-ui
#0 24.38 Output:
#0 24.38 
#0 24.38 info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
#0 24.43 error Command failed with exit code 137.
#0 24.43 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c CLIENT_PLUGINS="${CLIENT_PLUGINS}" UI_APP_CONFIG="${UI_APP_CONFIG}" yarn run build:cvat-ui]: exit code: 137

-------
I have tried rebuilding the Docker Image, but the issue persists. Please help me understand what might be causing this error and suggest possible solutions?

**Comment by visheshsom** [comment]
> This is out-of-memory error, webpack requires a lot of memory to build. Try to free memory or building the image on a different machine.

![swap2](https://user-images.githubusercontent.com/24978566/231431013-f3c10b56-1304-4b51-b324-a990ea5c8d66.png)

**Still, the issue is there.** 

=> ERROR [cvat-ui 16/16] RUN CLIENT_PLUGINS="${CLIENT_PLUGINS}" UI_APP_CONFIG="${UI_APP_CONFIG}" yarn run build:cvat-ui                                                                                                                                92.8s
------
 > [cvat-ui 16/16] RUN CLIENT_PLUGINS="${CLIENT_PLUGINS}" UI_APP_CONFIG="${UI_APP_CONFIG}" yarn run build:cvat-ui:
#0 5.621 yarn run v1.22.19
#0 5.753 $ yarn workspace cvat-ui run build
#0 6.371 $ webpack --config ./webpack.config.js
#0 11.19 List of plugins:  []
#0 91.50 Killed
#0 91.50 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 91.50 error Command failed with exit code 137.
#0 91.68 error Command failed.
#0 91.68 Exit code: 137
#0 91.68 Command: /usr/local/bin/node
#0 91.68 Arguments: /opt/yarn-v1.22.19/lib/cli.js run build
#0 91.68 Directory: /tmp/cvat-ui
#0 91.68 Output:
#0 91.68 
#0 91.68 info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
#0 91.75 error Command failed with exit code 137.
#0 91.75 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c CLIENT_PLUGINS="${CLIENT_PLUGINS}" UI_APP_CONFIG="${UI_APP_CONFIG}" yarn run build:cvat-ui]: exit code: 137
-------

**Comment by bsekachev** [comment]
@visheshsom 

You need to look at memory available for Docker. Usually it does not have all the system memory.
https://docs.docker.com/config/containers/resource_constraints/
