### ISSUE TITLE
No default attributes in dumped annotation

### ISSUE THREAD

**Issue by sbanori** [opencv/cvat#601]
Hello,
I have a little problem after dump annotation. But first... My labels look this like:

Label_1 @number=Shelf_ID:1,10,1 @checkbox=Face:true @number=Order_on_shelf:1,50,1
Label_2 @number=Shelf_ID:1,10,1 @checkbox=Face:true @number=Order_on_shelf:1,50,1
Label_3 @number=Shelf_ID:1,10,1 @checkbox=Face:true @number=Order_on_shelf:1,50,1
Label_4 @number=Shelf_ID:1,10,1 @checkbox=Face:true @number=Order_on_shelf:1,50,1
Label_5 @number=Shelf_ID:1,10,1 @checkbox=Face:true @number=Order_on_shelf:1,50,1

On annotated photo we see a rack in the shop with few shelfs. We use attributes to count on which shelf and on which place on shelf is annotated product. Of course on every photo we don't need to change attributes for only one product (this product which have posistion on first shelf and on the first position on shelf) so it means that default attributes are good for him.

And here we have a problem because if we won't do anything with any attribute on this instance of label, after dump annotation, in xml file we can see only his name but with no values of attributes like below:

```
<box label="Label_1" occluded="0" xtl="308.15" ytl="1436.57" xbr="536.26" ybr="1707.47">
      <attribute name="Order_on_shelf">2</attribute>
      <attribute name="Shelf_ID">1</attribute>
      <attribute name="Face">false</attribute>
    </box>
    <box label="Label_2" occluded="0" xtl="3.26" ytl="1410.68" xbr="119.15" ybr="1680.02">
    </box>
    <box label="Label_3" occluded="0" xtl="527.86" ytl="1492.75" xbr="760.65" ybr="1722.92">
      <attribute name="Order_on_shelf">3</attribute>
      <attribute name="Face">true</attribute>
      <attribute name="Shelf_ID">1</attribute>
    </box>
```

When I will change any attribute on this instance for example:
1. Shelf_ID=1 ---> ShelfId=2
2. Save work
3. Shelf_ID=2 ---> Shelft_ID=1
4. Save work.

Then everything is OK, instance was "touched" so we can see his default values, but only because I changed them for a moment. After dump anotation we see now correct values.:

```
<box label="Label_1" occluded="0" xtl="308.15" ytl="1436.57" xbr="536.26" ybr="1707.47">
      <attribute name="Order_on_shelf">2</attribute>
      <attribute name="Shelf_ID">1</attribute>
      <attribute name="Face">false</attribute>
    </box>
    <box label="Label_2" occluded="0" xtl="3.26" ytl="1410.68" xbr="119.15" ybr="1680.02">
      <attribute name="Order_on_shelf">1</attribute>
      <attribute name="Shelf_ID">1</attribute>
      <attribute name="Face">true</attribute>
    </box>
    <box label="Label_3" occluded="0" xtl="527.86" ytl="1492.75" xbr="760.65" ybr="1722.92">
      <attribute name="Order_on_shelf">3</attribute>
      <attribute name="Face">true</attribute>
      <attribute name="Shelf_ID">1</attribute>
    </box>
```

EDIT: Or maybe this is normal funcionality in CVAT, which means that no changes on default values of attributes aren't copied on every line of unchanged instance of objects.

**Comment by nmanovic** [comment]
@sbanori , it looks like a bug. We should dump attributes in the case I believe. Let us reproduce the issue on our side. @azhavoro , could you please look at the issue?

**Comment by azhavoro** [comment]
Hi @sbanori, I can reproduce this behaviour only if I uploaded (via 'upload annotation' button on dashboard view) annotation that doesn't contain a attribute values. After that a dumped annotation will have attributes only for a changed objects. Does it look like on you scenario?

**Comment by sbanori** [comment]
Hello @azhavoro , no it doesn't look exactly like this. I don't use "upload annotation" functionality in this case.
I do annotation myself. Let's take example from my first post in this issue.
If the product on photo is first product on first shelf, it means that I don't need to touch attributes on this instance of label (Label_2) so I stay on default values of attributes. If now we have next product, it will be next instance (of Label_1) next to first instance (Label_2), it means that is still first shelf (so I don't touch this attribute Shelf_ID) but I change value of attribute "Order_on_shelf" from 1 to 2. Label_1 will have changed one value (Order_on_shelf). On Label_2 we haven't changed any value so we still have default values of attributes. And here is a problem, if we don't change anything in attributes on instance, this instance won't have attributes in xml dumped file.
I solved this temporary by change for a while on any other values and after Save Work, come back to default value, then it will be in xml file.

**Comment by azhavoro** [comment]
Ok, it's very strange...
Could you please little bit help to investigate issue? It would be nice if you do following steps:
1. Open any your own job
1. open devtools (F12) and go to Network tab
1. add any object (dont touch attributes, just draw a box)
1. save job
1. In devtools you can see several requests, you should choose __annotations?action=create__ from a list. Click on them and expand 'request payload' section and please post a screenshot or json that you find on this section

For example:
![image](https://user-images.githubusercontent.com/41117609/62199440-2c356180-b38c-11e9-8f51-c2b5401bd789.png)

**Comment by sbanori** [comment]
I know why wee see another effects :) But first, here is json from your steps:

```
{
  "version": 5,
  "shapes": [
    {
      "attributes": [
        {
          "value": "1",
          "spec_id": 399
        },
        {
          "value": "true",
          "spec_id": 400
        },
        {
          "value": "1",
          "spec_id": 401
        }
      ],
      "label_id": 3441,
      "group": 0,
      "frame": 0,
      "type": "rectangle",
      "occluded": false,
      "z_order": 1,
      "points": [
        333.80078125,
        1746.416015625,
        566.4331359863281,
        1996.9431610107422
      ]
    }
  ],
  "tracks": [],
  "tags": []
}
```

And it work properly when I did it like you said. Default attributes are in the xml file and it works without bug.

I made some tests and know I see when is this bug. It's when I use AutoAnnotation.
When I write boundingbox by my hand, with default attributes, it's OK. Xml will show these attributes. But when I use AutoAnnotation, then untouched default attributes aren't visible in Xml files.

**Comment by azhavoro** [comment]
@sbanori Got it, thanks for help! We'll fix this issue.
