### ISSUE TITLE
Question: how to use my library as cvat tracker

### ISSUE THREAD

**Issue by zhitm** [opencv/cvat#6010]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce

1.  Install cvat as [here](https://opencv.github.io/cvat/docs/contributing/development-environment/)
2. Run on localhost:3000

I have calculate.node file (you can create it in way described [here](https://nodejs.org/api/addons.html)  and [here](https://www.geeksforgeeks.org/why-do-we-need-c-addons-in-node-js/)).
It allows me use my custom c++ tracker based on opencv trackers in javascript and typescript.  
1) Where I  should place this file to run from cvat?
2) How to add dependency at cvat/cvat-ui/src/utils/opencv-wrapper/tracker-mil.ts ([link](https://github.com/opencv/cvat/blob/develop/cvat-ui/src/utils/opencv-wrapper/tracker-mil.ts))

Example of using addon in js:

```
const Jimp = require('jimp');
const addon = require('./build/Release/calculate');

const obj1 = addon.createObject();

async function onRuntimeInitialized(){
    // load local image file with jimp. It supports jpg, png, bmp, tiff and gif:
    var jimpSrc = await Jimp.read('./rgb.png');
    // // `jimpImage.bitmap` property has the decoded ImageData that we can use to create a cv:Mat
    var src = cv.matFromImageData(jimpSrc.bitmap);


    // console.log(src.channels())
    const ui8 = new Int8Array(src.data);

    const buffer = Buffer.from(ui8)
    console.log(buffer)
    addon.init(obj1, src.rows, src.cols, src.type(), buffer, Array(100,100,100, 100));
    addon.reinit(obj1, Array(100,100,100, 100))


}
// Finally, load the open.js as before. The function `onRuntimeInitialized` contains our program.
Module = {
    onRuntimeInitialized
};
cv = require('./opencv.js');
```
### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.4

**Comment by bsekachev** [comment]
@zhitm 

Probably browser runtime is not able to run it this way. Node.js is another runtime. 
If you want to perform C++ compiled code in a browser, look at WebAssembly or Emscripten technologies. 

We can't help here, because didn't work in this direction, so, I will close the issue. 

Thank you.
