### ISSUE TITLE
Cannot move project to organization

### ISSUE THREAD

**Issue by tomliumd** [opencv/cvat#6033]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Using CVAT SDK I created projects and tasks however all the projects and tasks are on my personal workspace. 
I created an organization id=1, but no matter what I do I cant move the projects to the organization. I even tried creating project with the argument org_id = 1 but this did not work.

### Expected Behaviour
I would love to be able to projects_api.update(org_id=xx) and update the project or projects_api.create(org_id=xx, data)

**Comment by bsekachev** [comment]
Not supported, please follow #4202
