### ISSUE TITLE
Task creation impossible in WebUI when local share contains a big hierarchy of folders with images

### ISSUE THREAD

**Issue by vkachurka** [opencv/cvat#6037]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create a folder X with at least 500 folders inside (1000 would be better), each containing some images.
1. Start new CVAT instance v2.4.2 (with HTTPS), with folder X connected as local share.
1. Create new annotation project, inside it - new annotation task.
1. Select "Connected file share", "check" the folder "X", observe ~500 requests fired for each sub-folder.
2. "Un-check" one subfolder, another ~500 requests will be fired again for each sub-folder still "checked".
3. When the requests are not finished, try to "Submit and Open" the task - it will refuse with an error, that the task should contain at least one file.

### Expected Behaviour

The FileManager **should not** request full information about each sub-folder (via separate request for each sub-folder) each time I check or uncheck one of the sub-folders. It should make these requests only when I click "Submit".

### Current Behaviour

FileManager requests full information about each sub-folder each time that I check/uncheck one of the subfolders. While the requests are sent (1 request per sub-folder at ~10RPS speed), task can't be submitted - it fails with error "task should contain at least one file".

### Possible Solution

Stop FileManager from triggering the GetFiles each time I check or uncheck a sub-folder in "Connected file share".

### Context

If your folder structure is big (~1000 sub-folders in each folder), and you need to uncheck manually at least 10 subfolders, the situation becomes unbearable: thousands of requests are sent with stable frequency of ~10 RPS. The task can't be submitted for creation until all thousands of requests are finished, which makes this GUI virtually impossible to use.

This worked well in CVAT v2.2, and judging by Git Blame, it seems that broken behavior was induced by commit 1db247aedd.

### Your Environment

- Git hash commit (`git log -1`): b4549f42ee1c
- Docker version `docker version` (e.g. Docker 17.0.05): 23.0.3
- Are you using Docker Swarm or Kubernetes? No, own instance in-cloud
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04.2 LTS

Attached are examples "how many requests are fired". Picture 1 - before unchecking one sub-folder, Picture 2 - after unchecking one subfolder.
![Screenshot-20230417223806-1502x831](https://user-images.githubusercontent.com/8413630/232612179-e373c049-5c39-4a26-a3df-2d4b819e543a.png)
![Screenshot-20230417224707-1502x831](https://user-images.githubusercontent.com/8413630/232612192-65c78962-9ed9-4aff-81b6-006c634fd216.png)

**Comment by vkachurka** [comment]
And just for comparison, here is an example of good behavior. These are 2 screenshots for CVAT v2.2 (in the same situation as in first message) - we see that FileManager works within a concept of lazy initialization, not firing thousands of requests after un-checking one sub-folder. I would say that this is a normal behavior that anybody would expect in this case. So for me all this situation seems like a regression bug, induced after v2.2.

![Screenshot-20230418092635-1534x862](https://user-images.githubusercontent.com/8413630/232704149-691c136c-7592-4362-939d-37ab352a9d26.png)
![Screenshot-20230418092648-1534x862](https://user-images.githubusercontent.com/8413630/232704174-110f864d-5869-4c5d-a2d5-689e94bde97c.png)

**Comment by bsekachev** [comment]
Hi @vkachurka 

Thank you for report.
