### ISSUE TITLE
Unable to preview video data on Azure cloud storage from manifest

### ISSUE THREAD

**Issue by realtimshady1** [opencv/cvat#6042]
### My actions before raising this issue
- Set up CVAT on a server
- Created a container populated with video data on Azure
- Generated data manifest for one video
- Connected the azure cloud storage and specified the manifest file

### Expected Behaviour
It should display a preview of the data and allow me to select the data for a job

### Current Behaviour
An error popup saying 'Could not fetch preview for cloud storage Error: . "\"An internal error has occurred\"".'
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/20720732/232948769-d32243a4-c579-4a78-8475-ee68dcc0a6c5.png">

### Context
If try the same thing but with image data, it works fine.

**Comment by Marishka17** [comment]
@realtimshady1, Hi, video data from cloud storage is not supported in the current implementation.

**Comment by realtimshady1** [comment]
How do I use the video manifest that's outlined in this article then? https://opencv.github.io/cvat/docs/manual/advanced/dataset_manifest/
Is it only supported for uploaded videos or for local storages?

**Comment by Marishka17** [comment]
As I remember the video manifest file should be supported for client files from the computer and server files from connected file share.

**Comment by realtimshady1** [comment]
yep, I mounted my azure container as a fileshare, so far without needing the video manifest and it is all being previewed on CVAT. Thanks
