### ISSUE TITLE
Could not restore the project Error: Request failed with status code 500. "TypeError: Label() got an unexpected keyword argument 'type'\n".

### ISSUE THREAD

**Issue by alligator29** [opencv/cvat#6056]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Could not restore the project
Error: Request failed with status code 500. "TypeError: Label() got an unexpected keyword argument 'type'\n".

Getting this error when trying to restore a project from backup.

**Comment by bsekachev** [comment]
Please, fill the issue template, providing the version you are using and the version backup has been done.

**Comment by DaniNexplore** [comment]
i have the same error, i have created a backup on CVAT server on premise, and i try to restore file into cvat.app
version on premise installation
Server version: 2.1

Core version: 5.0.1

Canvas version: 2.13.2

UI version: 1.37.0

Version  on cloud CVAT.app

Server version: 2.4.3

Core version: 9.0.1

Canvas version: 2.16.3

UI version: 1.50.8

**Comment by bsekachev** [comment]
@DaniNexplore Sorry, it is not clear what version the backup was done and where you try to restore it.

**Comment by DaniNexplore** [comment]
Hi

 **i have generated the backup in** 

Server version: 2.1

Core version: 5.0.1

Canvas version: 2.13.2

UI version: 1.37.0

**and i am trying to restore on:**

Server version: 2.4.3

Core version: 9.0.1

Canvas version: 2.16.3

UI version: 1.50.8
