### ISSUE TITLE
can't add model with url

### ISSUE THREAD

**Issue by kkhxx** [opencv/cvat#6057]
### My actions before raising this issue

Insert same url but can't get provider in local CVAT

How can I add models in local CVAT?

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Expected Behaviour

![online cvat](https://user-images.githubusercontent.com/48484812/233545132-0a591e42-7605-4a87-88b5-50fb986b98d9.PNG)

### Current Behaviour

![local cvat](https://user-images.githubusercontent.com/48484812/233545147-140973e7-f3bd-4cf7-9c3f-8592ea85dae0.PNG)

### Your Environment

- Git hash commit (`git log -1`):
![git log -1](https://user-images.githubusercontent.com/48484812/233545672-e186f200-3a46-4b7a-a646-a61ee8a5ed62.PNG)

- Docker version `docker version` (e.g. Docker 17.0.05):
![docker version](https://user-images.githubusercontent.com/48484812/233545752-bb15edc3-ab03-41a4-b979-0d91be41c080.PNG)

- Are you using Docker Swarm or Kubernetes? Kubernetes 
- Operating System and version (e.g. Linux, Windows, MacOS):
![ubuntu version](https://user-images.githubusercontent.com/48484812/233545918-ae5f8d01-8a70-4707-8a6e-8c20300f15bd.PNG)

- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by nmanovic** [comment]
@kkhxx , it is a paid feature. It is available only on CVAT.ai cloud.

**Comment by qiuleizhen** [comment]
I met the same issure~
