### ISSUE TITLE
Segmentation using watershed

### ISSUE THREAD

**Issue by HagegeR** [opencv/cvat#606]
First of all, very impressive work,

I wanted to know if you could implement a watershed segmentation option, a little bit like that:

[https://github.com/abreheret/PixelAnnotationTool](url)

the main backend function is simply watershed from opencv

it would be needed to add a "brushing" interaction with the canvas and a button to run the watershedding

**Comment by nmanovic** [comment]
Probably it can be a nice feature. Could you please estimate how much your annotation speed can be improved if the feature will be implemented?

**Comment by HagegeR** [comment]
well it will depend on the kind of annotation that will be done and on how accurate we want it to be, but I think it will be anywhere between 4 and 10 times faster on segmentation work.

**Comment by hannes09** [comment]
Can you give an update about the status of this feature? Is there any chance to see a watershed tool in the near future?

**Comment by DPeled** [comment]
Hey, I have this feature implemented with python on my forked version of an older version of this repo.
I can use it to write this feature using `OpenCV.js`. I'll take this on myself.

**Comment by bsekachev** [comment]
We have SAM now. 
It is much better than classic CV algorithms and we will integrate new. 
So, I do not consider the issue relevant anymore.
