### ISSUE TITLE
Upload to an existing porjects dataset or merge completed tasks within project.

### ISSUE THREAD

**Issue by BaileyHelfer** [opencv/cvat#6060]
### Feature Request
When managing your projects it would be nice to upload images to an existing train/test/validation dataset. If you want to use the same project and every time you add new images to the dataset there is going to be a new task entry for every one. If there was a way to either merge completed tasks in the project or the ability to add data to existing tasks within the project that would be great. Also being able to view the images within the dataset in a gallery like view would be nice as well.

**Comment by bsekachev** [comment]
Hi @BaileyHelfer 

We are not going to implement adding new data to existing tasks. It would be a breaking change, our model considers new tasks if you need more data in a dataset. 
You can push completed task to a project subset if you want.
