### ISSUE TITLE
SAM with GPU support not working

### ISSUE THREAD

**Issue by cirobr** [opencv/cvat#6061]
Cheers,

I have successfully installed CVAT and used on a server within my local network. I have also successfully installed and used YoloV3 as automatic annotation tool, by following these instructions:

[Semi-automatic and Automatic Annotation](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)

With the recent launch of Meta's SAM, have successfully installed and used its CPU version by following these instructions:

[The Facebook Segment Anything Model is now available in the self-hosted version of CVAT](https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat)

Its counterpart for GPU, however, is not working on my setup. When trying to segment an object, the following error occurs:

`Interaction error occurred
Error: Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://host.docker.internal:32768/".`

The exact commands to install GPU support followed the instructions from Nvidia from the below link:

[Setting up NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)

As a proof that it has been correctly installed, a test instruction and its output are given next:

`sudo docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi`

![image](https://user-images.githubusercontent.com/37887021/233858325-f5ea81bb-71a9-4035-aecc-a6dd03eb9891.png)

The exact commands to install the model with GPU support are as follows:

`cd ./github/cvat/

docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml down

cd serverless && ./deploy_gpu.sh pytorch/facebookresearch/sam/nuclio/

cd ..

docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d --build`

CVAT runs on a remote Ubuntu Mate 22.04 machine, fully updated.

Thanks for advising, any help is appreciated.

**Comment by ryanalexmartin** [comment]
Can you show the output of the SAM docker container's logs?

`docker ps` 
`docker logs {name_of_container}`

**Comment by bsekachev** [comment]
@cirobr 

Please, provide the full log. I see exception in what you provided, but without any deatils. 

``docker logs container_name``

**Comment by cirobr** [comment]
I think I've caught the issue: GPU out of memory. Both nvidia-smi and full log follow here. Interesting to notice the large python3 process running, possibly loaded by the model.

![2023-04-26](https://user-images.githubusercontent.com/37887021/234575859-cc4c18c9-8f13-4843-995d-552dbf6bd0b1.png)

[log.txt](https://github.com/opencv/cvat/files/11332804/log.txt)

**Comment by cirobr** [comment]
I have rebooted the system. System wakes up already with half of available GPU memory occupied, without even starting CVAT UI.

![2023-04-26 (1)](https://user-images.githubusercontent.com/37887021/234578108-1dc9729d-95bb-466b-9abe-a06584333def.png)

**Comment by bsekachev** [comment]
@cirobr 

> System wakes up already with half of available GPU memory occupied, without even starting CVAT UI.

Probably some docker containers with serverless functions started automatically.

Also, on your previous screenshots I see also yolo-v3 deployed by nuclio. If you deployed it on GPU, you should now that they are always in-memory. I mean any deployed nuclio function on GPU is always reserves GPU memory even if it is not used.

**Comment by cirobr** [comment]
At first glance, could not find the culprit container for the 3 GB GPU usage. After doing a complete and careful cleanup of all containers from docker, besides all processes from nuclio, I managed to finally reclaim those 3 GB.

Unfortunately, when installing only sam-gpu, the 3 GB occupation returned. After restarting CVAT UI, same original error happened again, and GPU occupation approached on almost 6 GB.

New log files and nvidia-smi follow:

![2023-04-26 (2)](https://user-images.githubusercontent.com/37887021/234597847-437e1e94-b612-45c4-bcba-1098f5c47a7e.png)

[ps.txt](https://github.com/opencv/cvat/files/11333669/ps.txt)


[log.txt](https://github.com/opencv/cvat/files/11333656/log.txt)

**Comment by bsekachev** [comment]
For me on 3070 with 8Gb it works fine on GPU. 
In your case it fails on ``self.predictor.set_image(numpy_image)``, so, it can not convert image to GPU pytorch tensor, requiring 1024 Mb of memory and having only ~190 Mb. 

In SAM repository some people reports that it does not work with 6Gb and even 8Gb. 
https://github.com/facebookresearch/segment-anything/issues/33

You can try modifing source code of the serverless functions according to proposed ideas. 
Or just use it on CPU.

**Comment by filipemarinho** [comment]
I managed to use the SAM model on my 6gb RTX 3060 gpu, I changed the weights to the B model which is much lighter and added the reduceMemoryUsage in the nuctl after the maxRequestBodySize attribute

**Comment by RaulEP** [comment]
> 

Hey filipemarinho, Could you please share how you loaded the SAM B model in a nuctl function? I am experiencing issues to do that. 

what I do is substitute the weigths of the model in the function_gpu.py file, is there anything else I should consider?
Thanks
