### ISSUE TITLE
BUG: 'nuctl create project cvat' results in 'no route to host' error.

### ISSUE THREAD

**Issue by Huxwell** [opencv/cvat#6064]
I am following:
https://opencv.github.io/cvat/v2.2.0/docs/administration/basics/installation/
and
https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
and 
https://www.youtube.com/watch?v=SDM7421w9UE&ab_channel=CVAT
guides to run SAM.
Regular, default CVAT runs ok at localhost:8080. 
However, when I try to enable auto-segmentation, I get an error pretty early:

`nuctl create project cvat` results in 

```
Error - Get "https://192.168.49.2:8443/apis/nuclio.io/v1beta1/namespaces/default/nuclioprojects/default": dial tcp 192.168.49.2:8443: connect: no route to host
    .../abstract/project/internalc/kube/kube.go:61

Call stack:
Failed to get a project
    .../abstract/project/internalc/kube/kube.go:61
Failed getting projects
    /nuclio/pkg/platform/kube/platform.go:703
Failed to get projects
    ...//nuclio/pkg/platform/abstract/platform.go:1077
Failed to ensure default project existence
    /nuclio/pkg/platform/kube/platform.go:172
Failed to initialize platform
    /nuclio/pkg/platform/factory/factory.go:84
```

Here is a list of commands I used:
```
git clone https://github.com/opencv/cvat
cd cvat
CVAT_VERSION=dev docker-compose up -d
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
less components/serverless/docker-compose.serverless.yml #got 1.8.14 , i'm on amd64 
wget https://github.com/nuclio/nuclio/releases/download/1.8.14/nuctl-1.8.14-linux-amd64
sudo chmod +x nuctl-1.8.14-linux-amd64 
sudo ln -sf $(pwd)/nuctl-1.8.14-linux-amd64 /usr/local/bin/nuctl
nuctl create project cvat
```

**Comment by Huxwell** [comment]
I have cleaned the instalation:
```
docker-compose down -v --remove-orphans
docker rmi -f $(docker images -aq)
cd ../
rm -rf cvat
sudo rm -r /usr/local/bin/nuctl
```
And did from scratch, but withouth **docker-compose up**
```
git clone https://github.com/opencv/cvat
cd cvat
CVAT_VERSION=dev docker-compose up -d
less components/serverless/docker-compose.serverless.yml #got 1.8.14 , i'm on amd64 
wget https://github.com/nuclio/nuclio/releases/download/1.8.14/nuctl-1.8.14-linux-amd64
sudo chmod +x nuctl-1.8.14-linux-amd64 
sudo ln -sf $(pwd)/nuctl-1.8.14-linux-amd64 /usr/local/bin/nuctl
nuctl create project cvat
```

But the error remains the same.

**Comment by bsekachev** [comment]
@Huxwell 

Hi, I would suggest to address your issue to nuclio team. It is another product: https://github.com/nuclio/nuclio

Unfortunately we are not nuclio experts and don't have ideas about the reason of you problem.

**Comment by Huxwell** [comment]
https://github.com/nuclio/nuclio/issues/2905

**Comment by Huxwell** [comment]
This problem was solved now, please update your tutorial for future users:

![image](https://user-images.githubusercontent.com/9086268/235611920-6724c181-5c42-40f8-9823-da642292a8b1.png)
` --platform local` is missing in project creation command
