### ISSUE TITLE
How does CVAT know the endpoints of the deployed serverless functions?

### ISSUE THREAD

**Issue by ArivCR7** [opencv/cvat#6065]
Thank you for the incredible work on CVAT. My requirement is to run the serverless functions in a big server with huge RAM and GPU. And to be able to invoke the functions from the CVAT server which is deployed in a different lightweight server. I see documentations related to exposing a function on nuclio. But I want to know where do I specify the function endpoints in CVAT to use auto-annotation feature.

**Comment by bsekachev** [comment]
Hi @ArivCR7 

Serverless functions are managed by nuclio, so, probably docs about exposing a function on nuclio is what you need.

**Comment by ArivCR7** [comment]
If I deploy the serverless functions on a different server, where do I configure the endpoints of those functions in cvat?

**Comment by ArivCR7** [comment]
Hi @bsekachev 
Any thoughts on this please.

**Comment by bsekachev** [comment]
@azhavoro 
Do you have some ideas?

**Comment by ArivCR7** [comment]
Sharing the way I solved this for future reference. If the nuclio functions are deployed in a different server with serviceType nodePort, configure the below env vars in the CVAT server:
CVAT_NUCLIO_HOST: <IP Address x.x.x.x>
KUBERNETES_SERVICE_HOST: true
Add them in the cvat_server service. By relaunching the docker compose, CVAT server can now see the deployed nuclio functions in the remote server.

**Comment by ganindu7** [comment]
@ArivCR7  can you share the compose override for your solution please. does https://github.com/opencv/cvat/issues/6714#issuecomment-1728003525 make sense to you?

**Comment by mr-pinkk** [comment]
For anyone trying to setup nuclio on a different machine than cvat is: to invoke the functions properly you need to set the env variable:
CVAT_NUCLIO_INVOKE_METHOD: 'dashboard'

without it cvat assumes the nuclio functions are running on the same machine, which is not the case.
