### ISSUE TITLE
Shortcut to change active shape.

### ISSUE THREAD

**Issue by pwmhm** [opencv/cvat#6066]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Currently, if i want to annotate 2 different object with different shapes (e.g. Polyline and Point). I have to click on Polyline -> shape, then draw the line, then click again on Point -> shape, then draw the point. This is quite disruptive and i was hoping if there are any shortcut that can solve this.

There is already a shortcut for switching label for an activated object (ctrl + 0..9) but not for switching activated object. Is this a feasible feature to implement?

**Comment by bsekachev** [comment]
Hi @pwmhm 

Why not annotate first all the polylines and then all the points?

**Comment by pwmhm** [comment]
> Hi @pwmhm
> 
> Why not annotate first all the polylines and then all the points?

Hi @bsekachev,

so, one issue with this. In the next frame, i would have to switch again to polyline. And it maybe is also worth noting that for my use case, not all images present have points and polylines to annotate, it might just be polylines/points. In this case it would be useful to have a shortcut to switch between active objects.

**Comment by bsekachev** [comment]
Still don't see why not annotate first polylines (on those frames where you need to annotate them), and then annotate points.
Concentrating on one simple task usually has better performance, then making different tasks in parallel.
