### ISSUE TITLE
Technical specifications of the server

### ISSUE THREAD

**Issue by outforz** [opencv/cvat#6069]
Hey guys! 
I need some advice on the technical specifications for the server.
We have a team with about 20-30 annotators planned at the same time.
Automatic annotation tools will not be used. 
All work will consist of manual annotation of videos and images.
Can you advise how much RAM will be needed and what is the optimal processor for this task?
Thanks!

**Comment by bsekachev** [comment]
Hi @outforz 

We do not have "official" recommendations. And actually these recommendations very depend on tasks you are going to do. I would suggest 32 Gb of RAM and 8-core 16-threads CPU 2018 year+.
