### ISSUE TITLE
KeyError: 'pos_points' when invoking a deployed nuclio function

### ISSUE THREAD

**Issue by almondamonnut** [opencv/cvat#6077]
### My actions before raising this issue
- I Read/searched the docs:([[Installation Guide | CVAT (opencv.github.io)](https://opencv.github.io/cvat/docs/administration/basics/installation/)](https://opencv.github.io/cvat/docs/administration/basics/installation/)

[[Installation Guide — NVIDIA Cloud Native Technologies documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)

[[Semi-automatic and Automatic Annotation | CVAT (opencv.github.io)](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)

[[Setup additional components in development environment | CVAT (opencv.github.io)](https://opencv.github.io/cvat/docs/contributing/setup-additional-components/#dl-models-as-serverless-functions)](https://opencv.github.io/cvat/docs/contributing/setup-additional-components/#dl-models-as-serverless-functions)

[[CVAT](https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat)](https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat)

Then I got these 3 functions with status ready:
nuctl get function
  NAMESPACE |              NAME              | PROJECT | STATE | REPLICAS | NODE PORT  
  nuclio    | openvino-dextr                 | cvat    | ready | 1/1      |     32770  
  nuclio    | pth-saic-vul-hrnet             | cvat    | ready | 1/1      |     32769  
  nuclio    | pth.facebookresearch.sam.vit_h | cvat    | ready | 1/1      |     32768 

So I tested the functions one by one. 
All deployed functions gave me the same error:

image=$(curl https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png --output - | base64 | tr -d '\n')
cat << EOF > /tmp/input.json
{"image": "$image"}
EOF
cat /tmp/input.json | nuctl invoke openvino-dextr -c 'application/json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  462k  100  462k    0     0  1235k      0 --:--:-- --:--:-- --:--:-- 1233k
23.04.27 00:17:50.338    nuctl.platform.invoker (I) Executing function {"method": "POST", "url": "http://:32770", "bodyLength": 631790, "headers": {"Content-Type":["application/json"],"X-Nuclio-Log-Level":["info"],"X-Nuclio-Target":["openvino-dextr"]}}
23.04.27 00:17:50.344    nuctl.platform.invoker (I) Got response {"status": "500 Internal Server Error"}
23.04.27 00:17:50.344                     nuctl (I) >>> Start of function logs
23.04.27 00:17:50.344            openvino-dextr (I) call handler {"time": 1682529470343.4753, "worker_id": "0"}
23.04.27 00:17:50.344            openvino-dextr (E) Exception caught in handler {"time": 1682529470344.109, "exc": "'pos_points'", "traceback": "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 118, in serve_requests\n    await self._handle_event(event)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 312, in _handle_event\n    entrypoint_output = self._entrypoint(self._context, event)\n  File \"/opt/nuclio/main.py\", line 18, in handler\n    points = data[\"pos_points\"]\nKeyError: 'pos_points'\n", "worker_id": "0"}
23.04.27 00:17:50.344                     nuctl (I) <<< End of function logs

> Response headers:
Server = nuclio
Date = Wed, 26 Apr 2023 17:17:50 GMT
Content-Type = text/plain
Content-Length = 422

> Response body:
Exception caught in handler - "'pos_points'": Traceback (most recent call last):
  File "/opt/nuclio/_nuclio_wrapper.py", line 118, in serve_requests
    await self._handle_event(event)
  File "/opt/nuclio/_nuclio_wrapper.py", line 312, in _handle_event
    entrypoint_output = self._entrypoint(self._context, event)
  File "/opt/nuclio/main.py", line 18, in handler
    points = data["pos_points"]
KeyError: 'pos_points'

### Steps to Reproduce (for bugs)

Use either Ubuntu 18.04, 20.04, 22.04, either WSL2, and dual boot, I have tried all and found this same error.
Then follow the 5 tutorials mentioned above.

### Expected Behaviour
The deployed functions should return some kind of masks or answer as number, not Exception like this.

### Current Behaviour

> Response body:
Exception caught in handler - "'pos_points'": Traceback (most recent call last):
  File "/opt/nuclio/_nuclio_wrapper.py", line 118, in serve_requests
    await self._handle_event(event)
  File "/opt/nuclio/_nuclio_wrapper.py", line 312, in _handle_event
    entrypoint_output = self._entrypoint(self._context, event)
  File "/opt/nuclio/main.py", line 18, in handler
    points = data["pos_points"]
KeyError: 'pos_points'

### Possible Solution

I guess the problem is not with the deployed functions, but with /opt/nuclio/_nuclio_wrapper.py, /opt/nuclio/main.py
If I need to solve this alone, I'll read the codes mentioned above to figure out at which point it started to go wrong.

### Context

I want to deploy any segmentation model that provide me polygon masks around objects that I click on the UI of CVAT, that means the deployed functions need to work well first.

### Your Environment

- Git hash commit (`git log -1`):
git log -1
commit 269545bdcf1029e649641a5169901797eff5792f (HEAD -> develop, origin/develop, origin/HEAD)
Author: Andrey Zhavoronkov <andrey@cvat.ai>
Date:   Tue Apr 25 18:22:17 2023 +0300

    develop 2.5.0 (#6070)

- Docker version `docker version` (e.g. Docker 17.0.05):
docker version
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:03 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:32:03 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Are you using Docker Swarm or Kubernetes?
Swarm

- Operating System and version (e.g. Linux, Windows, MacOS):
This problem persists in WSL2 Ubuntu 18.04, 20.04, 22.04, and Ubuntu dual boot 18.04 and 22.04

**Comment by bsekachev** [comment]
I will close the issue
