### ISSUE TITLE
Cannot upload annotation or backup task 

### ISSUE THREAD

**Issue by claudio9russo7** [opencv/cvat#6078]
### My actions before raising this issue
- [X ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

Hello, i tried to upload annotation or backup task but i cannot work out it. The type of error is this:
Error: tus: failed to upload chunk at offset 0, caused by [object ProgressEvent], originated from request (method: PATCH, url: "my url"/api/tasks/4/annotations/f005e914-3464-4f0e-8e8b-f12fc6ababbd, response code: n/a, response text: n/a, request id: n/a).

In the images you can see the entire error i think:
![Cvat_error](https://user-images.githubusercontent.com/99536010/234677324-f0b44ba2-7979-4347-9ba8-afe1e7dd3348.png)

For the build of containers i  just define:
CVAT_HOST as environment variable
docker compose up -d
I modified only the docker override.yaml for folder binding, that's it
### Expected Behaviour

Correct upload of annotation 
### Your Environment

- Git hash commit (`git log -1`): release-2.4.0
- Docker version `docker version` (e.g. Docker 17.0.05): 23.0.3
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04.2 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
Cvat_server logs:
2023-04-26 18:22:48,474 DEBG 'runserver' stderr output:
[Wed Apr 26 18:22:48.474144 2023] [wsgi:error] [pid 74:tid 139724552636160] [remote 172.19.0.4:57148] [2023-04-26 18:22:48,452] INFO cvat.server.task_5: get repository request

2023-04-26 18:22:48,474 DEBG 'runserver' stderr output:
[Wed Apr 26 18:22:48.474768 2023] [wsgi:error] [pid 74:tid 139724552636160] [remote 172.19.0.4:57148] INFO:cvat.server.task_5:get repository request

2023-04-26 18:23:35,033 DEBG 'runserver' stderr output:
[Wed Apr 26 18:23:35.033119 2023] [wsgi:error] [pid 74:tid 139724569421568] [remote 172.19.0.4:48912] [2023-04-26 18:23:35,032] WARNING django.request: Not Found: /api/functions/requests/
[Wed Apr 26 18:23:35.033259 2023] [wsgi:error] [pid 74:tid 139724569421568] [remote 172.19.0.4:48912] WARNING:django.request:Not Found: /api/functions/requests/

2023-04-26 18:23:41,185 DEBG 'runserver' stderr output:
[Wed Apr 26 18:23:41.184690 2023] [wsgi:error] [pid 74:tid 139724552636160] [remote 172.19.0.4:48948] [2023-04-26 18:23:41,184] WARNING django.request: Not Found: /api/functions/requests/
[Wed Apr 26 18:23:41.184877 2023] [wsgi:error] [pid 74:tid 139724552636160] [remote 172.19.0.4:48948] WARNING:django.request:Not Found: /api/functions/requests/

2023-04-26 18:23:48,810 DEBG 'runserver' stderr output:
[Wed Apr 26 18:23:48.809933 2023] [wsgi:error] [pid 74:tid 139724552636160] [remote 172.19.0.4:33878] [2023-04-26 18:23:48,809] WARNING django.request: Not Found: /api/functions/requests/
[Wed Apr 26 18:23:48.810071 2023] [wsgi:error] [pid 74:tid 139724552636160] [remote 172.19.0.4:33878] WARNING:django.request:Not Found: /api/functions/requests/

2023-04-26 18:32:56,260 DEBG 'runserver' stderr output:
[Wed Apr 26 18:32:56.260228 2023] [wsgi:error] [pid 74:tid 139724552636160] [remote 172.19.0.4:43390] [2023-04-26 18:32:56,259] WARNING django.request: Not Found: /api/user-agreements

2023-04-26 18:32:56,263 DEBG 'runserver' stderr output:
[Wed Apr 26 18:32:56.263170 2023] [wsgi:error] [pid 74:tid 139724552636160] [remote 172.19.0.4:43390] WARNING:django.request:Not Found: /api/user-agreements

2023-04-26 18:32:56,624 DEBG 'runserver' stderr output:
[Wed Apr 26 18:32:56.624693 2023] [wsgi:error] [pid 74:tid 139724918589184] [remote 172.19.0.4:43514] [2023-04-26 18:32:56,624] WARNING django.request: Not Found: /api/functions/requests/

2023-04-26 18:32:56,625 DEBG 'runserver' stderr output:
[Wed Apr 26 18:32:56.624898 2023] [wsgi:error] [pid 74:tid 139724918589184] [remote 172.19.0.4:43514] WARNING:django.request:Not Found: /api/functions/requests/

2023-04-26 18:42:23,808 DEBG 'runserver' stderr output:
[Wed Apr 26 18:42:23.808026 2023] [wsgi:error] [pid 74:tid 139724926981888] [remote 172.19.0.4:48578] [2023-04-26 18:42:23,807] WARNING django.request: Not Found: /api/functions/requests/

2023-04-26 18:42:23,808 DEBG 'runserver' stderr output:
[Wed Apr 26 18:42:23.808180 2023] [wsgi:error] [pid 74:tid 139724926981888] [remote 172.19.0.4:48578] WARNING:django.request:Not Found: /api/functions/requests/

2023-04-26 18:42:25,977 DEBG 'runserver' stderr output:
[Wed Apr 26 18:42:25.977217 2023] [wsgi:error] [pid 74:tid 139724926981888] [remote 172.19.0.4:58504] [2023-04-26 18:42:25,954] INFO cvat.server.task_4: get repository request

2023-04-26 18:42:25,977 DEBG 'runserver' stderr output:
[Wed Apr 26 18:42:25.977712 2023] [wsgi:error] [pid 74:tid 139724926981888] [remote 172.19.0.4:58504] INFO:cvat.server.task_4:get repository request

**Comment by bsekachev** [comment]
@claudio9russo7 

Something wrong with you server configuration. You are trying to send requests from ``https`` to ``http``. The browser blocks them.
