### ISSUE TITLE
CVAT on arm64 (aarch64) Linux

### ISSUE THREAD

**Issue by cirobr** [opencv/cvat#6079]
Cheers,

I got a number of complaints on terminal when attempting to install CVAT on an ARM Linux machine. It appears some of the containers are not ready for it. Is it really the case?

Thanks.

**Comment by bsekachev** [comment]
Hi @cirobr 

We do not support arm officially. There might be some problems.

**Comment by bsekachev** [comment]
There is related issue #4654
