### ISSUE TITLE
[Question] What is the purpose of using mutable attribute of label?

### ISSUE THREAD

**Issue by lutuantai95** [opencv/cvat#6080]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Sorry, i have a small question!
What is the purpose of using **mutable attribute** of label?

![image](https://user-images.githubusercontent.com/26337793/234750265-2b26f88d-2dba-4bf7-83cf-6b17a12190ac.png)

**Comment by nmanovic** [comment]
@lutuantai95 , please read our documentation. It is valuable for video annotation. Some properties can be mutable. For example, you annotate a car as a track and there are 2 types of attributes:
- Model attribute will be constant
- IsParked attribute can be 'True' or 'False' for the same track on different frames.
