### ISSUE TITLE
ERR_CONNECTION_RESET for localhost:8080

### ISSUE THREAD

**Issue by ToPP13** [opencv/cvat#6084]
### My actions before raising this issue
cvat 2.2.0 was ok on connecting to cvat ui by localhost:8080 on several machines but suddenly google chrome gets error on connection and provides upgrade suggestions to 2.3.0

I followed [instructions](https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/#how-to-upgrade-cvat-from-v220-to-v230) to upgrade on two different machines - both results are negative. No connections at all (ERR_CONNECTION_RESET)

I change version to 2.4.0 and still has the same issues.

### Steps to Reproduce (for bugs)
1. Install cvat 2.2.0
2. Wait for several days or weeks probable with several reboots / compose ups and downs
3. Get error on connection with upgrade guide suggestion
4. Follow the intruction to upgrade on 2.3.0 / 2.4.0
5. Get the error

### Your Environment

- Git hash commit (`git log -1`) - no commit, https://github.com/opencv/cvat/archive/refs/tags/v2.3.0.zip, https://github.com/opencv/cvat/archive/refs/tags/v2.4.0.zip
- Client: Docker Engine - Community  Version:           23.0.3
- Docker Swarm or Kubernetes - no idea., seems none of them
- Ubuntu "22.04.2 LTS
- Other diagnostic information 

Current docker containers:

|CONTAINER  |   ID |  IMAGE |  STATUS | PORTS | NAMES |
0676a877453b   cvat/ui:v2.4.0 Up 2 minutes   80/tcp  cvat_ui
8d22d9df549f   cvat/server:v2.4.0  Up 2 minutes   8080/tcp, 0.0.0.0:9093->9093/tcp, :::9093->9093/tcp cvat_worker_import
6e6e1df47778   cvat/server:v2.4.0 Up 2 minutes   8080/tcp, 0.0.0.0:9092->9092/tcp, :::9092->9092/tcp cvat_worker_export
0f8da1b6fda5   cvat/server:v2.4.0 Up 2 minutes   8080/tcp cvat_worker_webhooks
49cc3d48fb8a   cvat/server:v2.4.0 Up 2 minutes   8080/tcp cvat_utils
9f16b7d42e96   cvat/server:v2.4.0 Up 2 minutes   8080/tcp, 0.0.0.0:9091->9091/tcp, :::9091->9091/tcp  cvat_worker_annotation
e281e2f61f91   cvat/server:v2.4.0 Up 2 minutes   8080/tcp, 0.0.0.0:9090->9090/tcp, :::9090->9090/tcp cvat_server
f3c983124682   timberio/vector:0.26.0-alpine Up 2 minutes cvat_vector
d3efd29031ba   postgres:15-alpine Up 2 minutes 5432/tcp cvat_db
1c566da05499   redis:4.0-alpine  Up 2 minutes   6379/tcp  cvat_redis
99b59aea319e   openpolicyagent/opa:0.45.0-rootless Up 2 minutes   0.0.0.0:8181->8181/tcp, :::8181->8181/tcp  cvat_opa
c5236dc7541f   grafana/grafana-oss:9.3.6 "Up 2 minutes   3000/tcp cvat_grafana
b22d4e536312   clickhouse/clickhouse-server:22.3-alpine Up 2 minutes   8123/tcp, 9000/tcp, 9009/tcp cvat_clickhouse
4282e85c455d   traefik:v2.4  Up 2 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik

**Comment by bsekachev** [comment]
Hi @ToPP13 

Did you try to build without ``https`` support to localize the problem? 
Omit ``-f docker-compose.https.yml`` in compose configuration.
