### ISSUE TITLE
API does not have a frame step parameter

### ISSUE THREAD

**Issue by realtimshady1** [opencv/cvat#6085]
### Expected Behaviour
I was hoping to use the CVAT API to create tasks for videos with a frame step

### Current Behaviour
CVAT API does not have a parameter for frame step for POST or PATCH requests

### Possible Solution
I have to use the UI to manually choose the frame step

**Comment by zhiltsov-max** [comment]
Hi, please use `frame_filter="step=N"` parameter instead.

**Comment by realtimshady1** [comment]
works perfectly
