### ISSUE TITLE
automatically detect if tracked object is visible, outside or occluded ,depending on scores and previous annotations 

### ISSUE THREAD

**Issue by amine-ammor** [opencv/cvat#6088]
Hello,

First of all, thank you for your amazing tool.

The issue concerns a feature request/proposal, concerning the tracker (more precisely the one that can be incorporated on the AI tool):

is it possible to use the previous annotations, to automatically detect if the object on the current frame is (totally of partially occluded) ?

It could be on the form of a function that decide if the tracked object is hidden by analyzing the scores of the annotated frames (manually of semi-automatically) along with the properties of the object on the previous frames (not occluded ,occluded,outside).

The simplest default function, could be a function that compares the score of the tracked object on the current frame against a threshold value.

The use case of this feature would be to avoid for the user the burden to select multiple keyframes, each time an object appears and disappear (in case it happens multiple times), and maybe to add automatically new keyframes.

It would be more useful with recents trackers' models that can find back disappeared object, even if the tracked object disappeared for multiple frames.

Thank you for your reply.

**Comment by bsekachev** [comment]
Hello, I don't think it is possible to implement general solution for that using scores and previous annotation.
