### ISSUE TITLE
[Need help]: Error in running manage.py

### ISSUE THREAD

**Issue by vamsykothuru** [opencv/cvat#609]
Please bear with my question. I am new to ubuntu and stuck with an error.

First of all thank you guys for building a wonderful tool. I was able to test it and it was awesome. I am trying to access the url from another system and with the help of stackoverflow post i came to know that we need to run manage.py.

If i run manage.py i am getting the below error..
File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

I feel like it is a silly question for you guys. kindly bear with me.

Thanks,
Ravi

**Comment by nmanovic** [comment]
Hi @vamsykothuru ,

To access the url from another system you don't need to run manage.py. You need to change ALLOWED_HOST and re-build + re-run your container. See instructions here: https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#advanced-settings

**Comment by nmanovic** [comment]
Indeed it is a question for your gitter.im/opencv-cvat chat. Please use github issues only for reporting bugs and feature requests. I will close the issue for now. Don't hesitate to ask more questions on our gitter channel.
