### ISSUE TITLE
cvat.ai errors during task creation, recovering from backup etc.

### ISSUE THREAD

**Issue by svolkovych** [opencv/cvat#6095]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Hi everyone,

I'm not sure that's the best place to raise my issue but I will give it a try.
I've been using cvat.ai to annotate my data quite intensively recently but it stopped working smoothly as before.
It started raising errors during execution of many tasks such as task creation, loading projects and tasks from backup etc.
For example, when I try to create a new task in the existing project, during execution of "Submint & Open" (or "Submit and Continue") it raises such kind of errors:

![image](https://user-images.githubusercontent.com/7767945/235720402-1ecd5809-75a0-42d6-9ad1-0ddb6de7c756.png)

Another errors I saw in similar situation is smth like "axioserror: request failed with status code 502"

Can you please hint me what can be the reason? I tried it from different machines today and faced the same issue. Thus, I just cannot create a new task (though created many in the past).

Can it be some issue at your side (I mean cvat.ai)?

I use Win10 21H1 64 bits and Google Chrome 112.0.5615.139.

Let me know if some additional info is required.
Thanks in advance!

**Comment by svolkovych** [comment]
Okay, I've just tried it from my Android phone with different internet provider... with similar result. I was not able to recover the task from the backup, same error with "Bad Gateway" appeared. What can be the reason of this?

**Comment by bsekachev** [comment]
@svolkovych 

Can you provide logs from the server? ``docker logs cvat_server``
