### ISSUE TITLE
Helm Chart Volume Configuration "ReadWriteOnce" Doesn't Work with Multiple Pods

### ISSUE THREAD

**Issue by moghtader** [opencv/cvat#6096]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

When using the Helm Chart, the storage.yml ReadWriteOnce option under the backend folder structure doesn't work in my K8s environment. If you have deployments across multiple nodes, ReadWriteOnce will form a race condition causing only one backend pod to start successfully. ReadWriteOnce by definition only allows one node to mount - so how is this supposed to work? 

### Steps to Reproduce (for bugs)
1. Attempt to deploy the helm chart to Kubernetes with the default storage

### Expected Behaviour
1. The defaults for the helm chart should be able to launch CVAT in K8s with the minimal amount of modification. 
### Possible Solution
1. Changing storage.yml to ReadWriteMany 
2. Put all backend deployments into the same node (maybe there's a reason this isn't designed this way though)

**Comment by westernspion** [comment]
Do we actually need these pods to all share storage? Or can they each be granted individual PVCs for each instance of the server/utils/workers pods? Sharing a cache a la volumes seems like a poor design choice so I question if this is just an assumption made in the docker-compose configuration and just found it's way into the helm chart.

**Comment by moghtader** [comment]
I'm unsure why it is needed that all share the same claim. Maybe someone more familiar with the chart knows? It might have some unintended consequences if we remove it.
