### ISSUE TITLE
Empty annotations exported using "COCO Keypoints 1.0" and "YOLO 1.0" formats for Ployline

### ISSUE THREAD

**Issue by Soham-Objectways** [opencv/cvat#6102]
When exporting a task with poly-line annotation using "COCO Keypoints 1.0" and "YOLO 1.0" formats, the resulting annotations are empty. This occurs despite the fact that the annotations were properly created and saved within the tool.

### Steps to Reproduce (for bugs)
1. Create a task with poly-line annotation using.
2. Annotate the task with at least one poly-line annotation and save the task.
3. Export the task using the "COCO Keypoints 1.0" or "YOLO 1.0" format.
4. Open the exported annotation file and note that it is empty, despite the presence of annotations in the original task.

### Expected Behaviour
The exported annotation file should contain the same annotations as the original task.

### Current Behaviour
The exported annotation file is empty, even though annotations were properly created and saved within the tool.

**Comment by zhiltsov-max** [comment]
Hi, both these formats don't support polylines, please find format descriptions [here](https://opencv.github.io/cvat/docs/manual/advanced/formats/). Currently, polylines can only be exported in `CVAT for *` and `Datumaro` formats.
