### ISSUE TITLE
Looking for help uploading annotation (COCO format, from JSON file) to task using CVAT API

### ISSUE THREAD

**Issue by gd822** [opencv/cvat#6103]
Hello there,

I'm looking for help with accomplishing **my goal**.
_<please excuse me if this is not the best place to post this, if you have recommendations for a better place, just let me know, I will gladly post this in a more ideal place>_

**my goal:** 
programmatically upload a set of annotations to a task (already populated with images) using the CVAT API. 

**additional context:**
I've been trying to perform the upload with my annotations stored locally in a JSON file (COCO format) and have not been successful yet. I'm hoping for guidance in the right direction and/or an example of a functioning annotation upload using the CVAT API. Any help would be very much appreciated. Thank you!

**Environment details:** 
-I'm running CVAT from a docker container on my local machine

**Things I've been able to successfully do already (via the CVAT API):**
-create/delete a project
-create/delete a task
-upload images to a task
-upload labels to a project

**Examples of how I have tried to accomplish my main goal**

++++ **general attempt1:** ++++++++++++++++++
```
annotations_file_path = Path(r"C:\local_path\annotation_file_in_COCO_format.json")
with open(annotations_file_path, "rb") as f:
    annotations_temp = json.load(f)

# convert json to binary
b64_dict = base64.urlsafe_b64encode(json.dumps(annotations_temp).encode()).decode()
	
# Upload the annotations to the task 
response = requests.put(f"{cvat_server}/api/tasks/{task_id}/annotations", headers=headers, data={'annotation_file': b64_dict})
print(response.json())
```

this results in the following error msg:
{'detail': 'Unsupported media type "application/x-www-form-urlencoded" in request.'}

+++++ **general attempt2:** (motivated by how I'm uploading images to a task) +++++++

```
annotations_file_path = Path(r"C:\local_path")
annotation_file_name = "annotation_file_in_COCO_format.json"
full_annotation_path = Path(os.path.join(annotations_file_path, annotation_file_name))
annotations = []
prefix = f'client_files[1]'
with open(full_annotation_path, "rb") as f:
    annotations_temp = json.load(f)
b64_dict = base64.urlsafe_b64encode(json.dumps(annotations_temp).encode()).decode()
current_tuple = (prefix, (annotation_file_name, b64_dict))
annotations.append(current_tuple)
response = requests.put(f'{cvat_server}/api/tasks/{task_id}/annotations', headers=headers, files=annotations)
# response = requests.post(f'{cvat_server}/api/tasks/{task_id}/annotations', headers=headers, files=annotations)
response.json()
```

when I use requests.put, I get the following return:
{'version': 0, 'tags': [], 'shapes': [], 'tracks': []}

when I use requests.post, I get the following return:
'No such file were uploaded'
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**additional context:**
my headers dict looks like this (and functions correctly in the other contexts I've already had success):
`{'Authorization': 'Token <token_UUID_goes_here>'}`

`cvat_server = 'http://localhost:8080'
`

**Comment by zhiltsov-max** [comment]
Hi, the first variant is almost correct. The endpoint description is available [here](https://app.cvat.ai/api/docs/#tag/tasks/operation/tasks_create_annotations). You need to upload the file in the `annotation_file` field. If you're uploading a binary file, specify the `multipart/form-data` encoding, while for text files json can be used. After uploading you need to send requests to the same endpoint, without files, and wait for the 201 status, 202 will be returned during processing. And example test is [here](https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/tests/test_rest_api.py#L5912-L5923).

We recommend using our high-level Python SDK for file uploading and downloading, you can find an example [here](https://github.com/opencv/cvat/blob/5399f6e189c547dd7948bfac2b4ff61f5b907848/tests/python/rest_api/test_tasks.py#L1363-L1369).

**Comment by gd822** [comment]
Hi zhiltsov-max, 

Thanks for the advice. I was able to get annotations loaded to a task by using the cvat_sdk. 

Many thanks! :)

**Comment by stevezkw1998** [comment]
> Hi zhiltsov-max,
> 
> Thanks for the advice. I was able to get annotations loaded to a task by using the cvat_sdk.
> 
> Many thanks! :)

Hi @gd822 would you like to share your solution on using cvat_sdk upload annotation_file to CVAT task
Appreciate it

**Comment by gd822** [comment]
Hi @stevezkw1998, 

I am still in a beta testing stage with the tools and haven't formalized any classes. So far, just learning how to use the CVAT API / SDK. Here is the rough script I came up with:

```
import cvat_sdk
import cvat_sdk.core
import os
from pathlib import Path
from shared.utils.config import (
    BASE_URL,
    USER_PASS,
    get_method,
    make_api_client,
    patch_method,
    post_method,
)

import requests
import json
import os
import base64
from pathlib import Path

## Set basic session variables
cvat_server = 'http://localhost:8080'
cvat_username = 'insert_username_here' # superuser
cvat_password = 'insert_pass_here'
auth = requests.post(f'{cvat_server}/api/auth/login', json={'username': cvat_username, 'password': cvat_password})
auth_token = auth.json()['key']
headers = {'Authorization': f'Token {auth_token}'}
client = cvat_sdk.make_client('localhost', port='8080', credentials=(cvat_username, os.getenv('cvat_localhost_test_password'))) 

## make a new project
project_var = client.projects.create({'name': 'test_subset_work'})

## add labels to project
project_id = project_var.id
labels = [
	{'name': 'label_1', 'color': '#FFE4C4', 'type': 'rectangle'},
	{'name': 'label_2', 'color': '#FA8072', 'type': 'rectangle'},
	{'name': 'label_3', 'color': '#F0E68C', 'type': 'rectangle'},
	{'name': 'label_4', 'color': '#98FB98', 'type': 'rectangle'}	
]

url = f'{cvat_server}/api/projects/{project_id}'
for iter in range(len(labels)):
	data_temp = {
		'name': labels[iter]['name'],
		'attributes': [],
		'color': labels[iter]['color'],
		'multi_shapes': False,
		'type': labels[iter]['type']
	}
	data_temp2 = {'labels': [data_temp]}
	response = requests.patch(url, headers=headers, json=data_temp2)
	response_json = response.json()
	
assign_to = 3 # user_id
task_var = client.tasks.create({'name': 'test_sdk_subset_task', 
					'mode': 'annotation',
					'assignee_id':assign_to,
					'project_id': project_id})
task_id = task_var.id


## Upload the image(s) to the task
image_path = Path(r'insert_image_path_here')
images_to_upload = os.listdir(image_path)
images = []
for iter in range(len(images_to_upload)):
	# iter = 0
	current_image = images_to_upload[iter]
	full_image_path = Path(os.path.join(image_path, current_image))
	prefix = f'client_files[{iter}]'
	binary_data = open(full_image_path, "rb").read()
	current_tuple = (prefix, (current_image, binary_data))
	images.append(current_tuple)
response = requests.post(f'{cvat_server}/api/tasks/{task_id}/data', headers=headers, data={'image_quality': 100}, files=images)
response.json()

annotations_file_path = Path(r"insert_path_to_annotation_file") # annotation file is stored in COCO format
task_var.import_annotations('COCO 1.0',annotations_file_path)
```

**Comment by stevezkw1998** [comment]
Thank you @gd822 Appreciate it

**Comment by lexx2842** [comment]
Thank you for the script @gd822 , I am searching since days for a solution. However, I am getting an error message when using it:  ModuleNotFoundError: No module named 'config'.
I tried to solve, without success, there is no such module and also nothing in the cvat file structure
Do you have a newer script, that you were successfully able to run? Can you share it? highly appreciated!

**Comment by zhiltsov-max** [comment]
Hi, you can find examples for all high-level API functions [here in the tests](https://github.com/cvat-ai/cvat/blob/967a5a6c32d745857bcd99b6b82df18e13be31f0/tests/python/sdk/). If you want to upload annotations to an existing task, you can do it this way ([a test](https://github.com/cvat-ai/cvat/blob/967a5a6c32d745857bcd99b6b82df18e13be31f0/tests/python/sdk/test_tasks.py#L353-L361)):

```python
import os
import sys

from cvat_sdk import make_client
from cvat_sdk.core.helpers import DeferredTqdmProgressReporter


with make_client("https://app.cvat.ai", port=443, credentials=("user", "password")) as client:
    # If working within an org, set the org slug:
    # client.organization_slug = ""

    task = client.tasks.retrieve(42)

    task.import_annotations(
        format_name="CVAT 1.1", 
        filename=f"some/dir/task-annotations-cvat_for_images.zip",
        pbar=DeferredTqdmProgressReporter()
    )
```
