### ISSUE TITLE
Create CVAT instance with analytics support

### ISSUE THREAD

**Issue by ninafiona** [opencv/cvat#6109]
The documentation states

> If your CVAT instance was created with analytics support, you can press the Analytics button in the dashboard and analytics and journals will be opened in a new tab.
(https://opencv.github.io/cvat/docs/manual/advanced/analytics/)

But there is no guide on how to create the instance with analytics support. Can someone give me a hint or make the documentation a bit clearer at this point?

**Comment by bsekachev** [comment]
@azhavoro 
Could you please comment on that?

**Comment by ninafiona** [comment]
Never mind. I figured out there was a permission issue, after resolving that I was able to start the grafana docker and the analytics tab worked. :+1:

**Comment by Siomn** [comment]
Hi，I cann't open analytics tab, and I guess the issue is also permission issue. Could you give some methods on how you resolved your permission issue?

**Comment by ninafiona** [comment]
There is also a bit more documentation here: https://opencv.github.io/cvat/docs/administration/advanced/analytics/ 
I saw that there was one permission error in the docker logs, I don't remember but maybe it was the [grafana_conf.yml](https://github.com/opencv/cvat/blob/develop/components/analytics/grafana_conf.yml). Just edit the permissions and start again, it should work.

**Comment by Siomn** [comment]
@zhouyuangan A few days ago, I cleared docker and reinstalled cvat. In this process, I did not do any steps other than the official requirements, and then it worked. However, after the GPU automatic update yesterday, the analysis interface could not be opened again....
