### ISSUE TITLE
500 Server Error on Automated Annotation / TF model deploy problem

### ISSUE THREAD

**Issue by prnr** [opencv/cvat#6115]
### My actions before raising this issue
- [O] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [O] Searched [past issues](/issues)

Hi! I have two issues using CVAT, so I want to ask.

1.
If I try to automate with YOLOv7, the following error message is displayed

Fetching inference status for the task 3

Error: Inference status for the task 3 is failed. requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://host.docker.internal:12048/

![2023-05-08 110723](https://user-images.githubusercontent.com/22967869/236743051-bae184e3-ec44-491e-a0a7-04cbf3c9de88.png)

I checked that Yolo5/Yolo3 is working normally, and only Yolo7 is having a problem.

It works normally when processing images in small amounts (10 to 100 sheets), but errors occur when using 50,000 sheets (ImageNet LSVRC2012 validation set).
It could be a problem with a particular image, or simply because there's a lot of workload, but I don't know exactly what the problem is.
(There's a high possibility that I'm not understanding because I lack a lot of programming knowledge.)

I will attach the result of "docker logs cvat_server / docker logs docker logs nuclio-nuclio-onnx-yolov7".
[logs_nuclio-yolo7.txt](https://github.com/opencv/cvat/files/11418138/logs_nuclio-yolo7.txt)
[logs_server.txt](https://github.com/opencv/cvat/files/11418139/logs_server.txt)

2.
Installation of mask_rcnn (serverless\tensorflow\matterport\mask_rcnn) using tensorflow does not proceed.

I've also modified the deploy-gpu file that I'm talking about in the forum (https://github.com/opencv/cvat/issues/5170), , in this case
23.05.08 12:18:33.810 nuctl.platform (I) Building docker image {"image": "cvat/tf.matterport.mask_rcnn_gpu:latest"}
Stops from and doesn't progress further (I've been waiting for about 24 hours but it doesn't).

[log_deploy-MRCNN.txt](https://github.com/opencv/cvat/files/11418143/log_deploy-MRCNN.txt)

Since it is a WSL2 environment, I am thinking that the installation of the Nvidia Container Toolkit may be wrong. First, I installed CUDA referring to https://learn.microsoft.com/ko-kr/windows/ai/directml/gpu-cuda-in-wsl and Nvidia Docker referring to https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker.

### Steps to Reproduce (for bugs)
1. Clone Repository
1. Set up for WSL2/Docker Desktop environment(With installation guide)
1. Run as serverless
1. Deploy DL model with codes on https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

### Your Environment

- CPU : Intel 12700F
- Memory: 64GB
- GPU : RTX3060 / Nvidia Studio driver 531.61 / cuda 12.1.0.531.14
- OS : Windows 11 Pro insider / WSL2 Ubuntu-20.04
- Python 3.8.10 / Docker Desktop 4.19.0 / Git 2.40.1
- A brain with a low understanding of coding
- Terrible English skills through a web translator

**Comment by weertman** [comment]
I'm having a similar issue on cvat's web hosted version of CVAT after running automatic annotations on a task. It still seems to be working within a task. 

<img width="295" alt="Screenshot 2023-05-09 at 12 36 48 AM" src="https://user-images.githubusercontent.com/86493327/237027110-236cced9-c891-4c85-898a-e0810f5d444e.png">

**Comment by prnr** [comment]
Any answers or advice?

**Comment by bsekachev** [comment]
```
23.05.08 02:01:01.049 sor.http.w1.python.logger (E) Exception caught in handler {"worker_id": "1", "exc": "too many indices for array: array is 2-dimensional, but 3 were indexed", "traceback": "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 118, in serve_requests\n    await self._handle_event(event)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 312, in _handle_event\n    entrypoint_output = self._entrypoint(self._context, event)\n  File \"/opt/nuclio/main.py\", line 34, in handler\n    results = context.user_data.model.infer(image, threshold)\n  File \"/opt/nuclio/model_handler.py\", line 95, in infer\n    image = image[:, :, ::-1].copy()\nIndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n"}
```

Are you trying to process grayscale image?

**Comment by prnr** [comment]
> ```
> 23.05.08 02:01:01.049 sor.http.w1.python.logger (E) Exception caught in handler {"worker_id": "1", "exc": "too many indices for array: array is 2-dimensional, but 3 were indexed", "traceback":
> "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 118, in serve_requests\n    await self._handle_event(event)\n 
> File \"/opt/nuclio/_nuclio_wrapper.py\", line 312, in _handle_event\n    entrypoint_output = self._entrypoint(self._context, event)\n 
> File \"/opt/nuclio/main.py\", line 34, in handler\n    results = context.user_data.model.infer(image, threshold)\n 
> File \"/opt/nuclio/model_handler.py\", line 95, in infer\n    image = image[:, :, ::-1].copy()\nIndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n"}
> ```
> 
> **IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed**
> 
> Are you trying to process grayscale image?

No, I'm trying ILSVRC2017 dataset images, colored.

**Comment by prnr** [comment]
It was an image format issue, I re-encoded everything and it worked fine.

**Comment by hoangdung3498** [comment]
> It was an image format issue, I re-encoded everything and it worked fine.

how do you re-encoded images? Can't you explain to me more detail ?, thank you

**Comment by prnr** [comment]
> > It was an image format issue, I re-encoded everything and it worked fine.
> 
> how do you re-encoded images? Can't you explain to me more detail ?, thank you

Among the images, there were dozens of jpg with extensions but actually png/jfif mixed (maybe someone changed the extensions arbitrarily during the collection process). I just unified it to jpg using a tool distributed on the web, and that solved the problem.
