### ISSUE TITLE
change volumes/cvat_data, it dosen’t work

### ISSUE THREAD

**Issue by wangwangteam** [opencv/cvat#6119]
### My actions before raising this issue
I change the file :  docker-compose.override.yml :
volumes:
  cvat_db:
  cvat_data:
    name: cvat_cvat_data
    driver_opts:
      device: /mnt/nas-public-linkdata/UploadData
      o: bind
      type: none
  cvat_keys:
  cvat_logs:
  cvat_events_db:

then,
use CLI: 
 `docker-compose -f docker-compose.override.yml up -d `

and the server is running, but when I visit 'localhost:8080' use chrome, return like this:
![image](https://user-images.githubusercontent.com/26371875/237056162-9b356682-fa3b-466e-8b7b-680dd2b48b65.png)
 
my docker images is :

![image](https://user-images.githubusercontent.com/26371875/237056730-6d8645c2-05e8-4e90-b914-ff13438992a5.png)

cvat_server logs like this:

![image](https://user-images.githubusercontent.com/26371875/237057547-44101e0a-7c94-49b1-8e63-ba9bf8031aef.png)
![image](https://user-images.githubusercontent.com/26371875/237057561-98c39224-6857-4e88-ba93-160ada1cdb57.png)

### Your Environment

- Docker version ` 23.0.5` :
- Operating System and version  `Linux Ubuntu 22.04.2 LTS`:

**Comment by bsekachev** [comment]
@wangwangteam 

What is output of thiis command? 

``docker exec -t cvat_server python manage.py health_check``?

**Comment by bsekachev** [comment]
@azhavoro 
 
Did we fix the issue with ``diskcache``?

**Comment by wangwangteam** [comment]
I'm so sorry. It seems to be my own mistake, I found that the mypath set cannot be a NAS, it must be a directory of the current host, and after I changed it, it worked fine.

thx

**Comment by bsekachev** [comment]
Great
