### ISSUE TITLE
Deployed SAM model not using GPU

### ISSUE THREAD

**Issue by ArivCR7** [opencv/cvat#6124]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat)

I deployed SAM model in CVAT following the [document](https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat) and used deploy_gpu.sh. The function got deployed successfully, but is not using GPU when I invoke it. I use `watch -n 1 nvidia-smi' to monitor the GPU usage every second. I don't see GPU utilization when I invoke the SAM model on cvat. 
Anything needs to be added to enable GPU for the deployed functions?

### Context
As the deployed model is not using GPU, the inference takes time for every invocation. Would be helpful if the steps to enable GPU is provided.

### Your Environment

- Git hash commit (`git log -1`):
-commit 5399f6e189c547dd7948bfac2b4ff61f5b907848 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.22
- Are you using Docker Swarm or Kubernetes? Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
My GPU is NVIDIA A10 Tensor Core GPU

**Comment by geometrikal** [comment]
I just came here to also log this issue.

- git tag v2.4.2
- docker
- Ubuntu 20.04
- Quadro RTX 6000

**Comment by geometrikal** [comment]
Looking inside the container it seems that cuda is available:
 ```
root@3ab50b54dee6:/opt/nuclio/sam# nvidia-smi
Wed May 10 13:34:04 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 6000     Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   41C    P0    61W / 250W |   7236MiB / 22698MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
root@3ab50b54dee6:/opt/nuclio/sam# python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>>
```

Also confirmed that the device is cuda in model_handler.py
