### ISSUE TITLE
Analytics tab is visible only for superusers

### ISSUE THREAD

**Issue by ArMaxik** [opencv/cvat#6125]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Be logged in as any user **without superuser** status but **in business** group.
1. There is no analytics tab next to "Projects", "Tasks", "Jobs".
1. Can still access analytics through direct link

### Expected Behavior

I see the "Analytics" tab.
### Current Behavior

I do not see the "Analytics" tab. The tab is only displayed for superusers.
### Possible Solution

Make the "Analytics" tab visible to all users with a business role, not only for superusers.

### Your Environment

- Git hash commit: 8a2c23f2c83f01d84f62c5b9c7bcfece2f97169b (v2.4.3)
- Docker version `23.0.6`
- Are you using Docker Swarm or Kubernetes?: Docker
- Ubuntu 18.04 x64

**Comment by bsekachev** [comment]
It is not available for users with business role because it has analytics for all the users on a platform. It would be leack of personal data for such services like app.cvat.ai.
We are working to integrate more permission-based analytics per task/job/project. The first step is in this PR #6371.
