### ISSUE TITLE
After updating of the CVAT version v2.4.2, saving the annotation file is quite slow

### ISSUE THREAD

**Issue by ramyarulmani** [opencv/cvat#6128]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
@ramyarulmani 

Thank you for the report. Could you provide some fair comparisons and steps to reproduce? We didn't notice any degradation here.
