### ISSUE TITLE
Export Annotations Only and not Images using API

### ISSUE THREAD

**Issue by quaid281** [opencv/cvat#6132]
Apologies for not inputting my issue in the correct format.
Question:
1.  I have working code that exports annotations from cvat using the retrieve_annotation method in the ProjectsAPI class.  My question is the retrieve_annotations method is downloading the annotations along with the images.  Is there a parameter that need to be set that is not included in the documentation?  I just only want the annotations and not the images

Here is what my code looks like:
```
        while True:
            try:
                (_, response) = api_client.projects_api.retrieve_annotations(
                    'COCO 1.0',
                    id,
                    filename=name,
                    location = 'local',
                    _parse_response=False,
                )
                if response.status == HTTPStatus.OK:
                    break

                sleep(1)  # Adjust this interval as needed
            except exceptions.ApiException as e:
                print("Exception when calling ProjectsApi.retrieve_annotations(): %s\n" % e)
        try:
            with open(f'C://Users//{name}.zip', 'wb') as f:
                f.write(response.data)
            print(f'Just Completed {name}')
        except IOError as e:
            print(f"Exception when writing to file: {e}")
```

**Comment by bsekachev** [comment]
@zhiltsov-max @SpecLad

**Comment by zhiltsov-max** [comment]
Hi, I suspect the file downloaded may be different from what is being tested. This code fragment is not enough to download the annotations in a specific format, because it misses the initial request. The code should have these parts (described [here](https://opencv.github.io/cvat/docs/api_sdk/sdk/lowlevel-api/#receiving-data)):

```python
while True:
  (_, response) = api_client.projects_api.retrieve_annotations(format, id, ...)
  if response.status == 201:
    break
  sleep(1)

(_, response) = api_client.projects_api.retrieve_annotations(format, id, action='download', ...)
assert response.status == 200
with open(filename) as f: 
  f.write(response.data)
```

**Comment by quaid281** [comment]
Hmm, that's interest.  That Works, Thanks @zhiltsov-max

**Comment by saad-abdullah62** [comment]
@bsekachev can you tell if we can update or retrieve annotations for only specific frame given frame id using High Level API? I couldn't find any thing like this in documentation.
