### ISSUE TITLE
Ability to load a subset of files in a directory

### ISSUE THREAD

**Issue by EladProject** [opencv/cvat#6133]
Hello,

Is there a way to select a subset of files in a folder (with regex or wildcards) so I won't need to select the relevant files by hand?
If not, how do I open an RFE for this?

Thanks,
Elad

**Comment by bsekachev** [comment]
Hi @EladProject 

Do you mean when browsing shared or cloud storages?

**Comment by EladProject** [comment]
When browsing a local directory, although similar functionality may also be helpful for other types of storage.
My use case: 
I have a directory containing 100s of files, I only want to load a subset of them (easily distinguishable by a regex or even just wildcards). My current workaround (didn't try it yet) is to zip the relevant files, but it would be nice if I can simply filter them from the UI.

**Comment by EladProject** [comment]
ok.
That's good enough
