### ISSUE TITLE
Fails to launch CVAT 2.3 docker-compose

### ISSUE THREAD

**Issue by stevezkw1998** [opencv/cvat#6134]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

I try to deploy CVAT 2.3 in my own machine, but fail in docker-compose up

### Steps to Reproduce (for bugs)
In my own machine
1. git clone https://github.com/opencv/cvat.git
2. cd cvat
3. git checkout v2.3.0
4. export CVAT_HOST=MY_IP
5. docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d

### Expected Behaviour
CVAT 2.3 docker compose should be launch successfully

### Current Behaviour
![image](https://github.com/opencv/cvat/assets/53121066/0213ecc6-34ae-4fc3-83cb-cbfe60c8fcf0)
localmachine:~/cvat$ docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

### Your Environment

- Git hash commit (`git log -1`):
localmachine:~/cvat$ git log -1
commit 2c4676ace32a68572b38205f002a98e93af917d0
Merge: d699f1f fb4af9c
Author: Nikita Manovich <nikita@cvat.ai>
Date:   Thu Dec 22 17:58:41 2022 +0200

    Release v2.3.0
- Docker version `docker version` (e.g. Docker 17.0.05):
Docker version 20.10.7, build f0df350
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):
Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
@stevezkw1998 

Please, consider upgrading docker & docker compose tools.

**Comment by stevezkw1998** [comment]
@bsekachev 

Thank you for your help, I solved it after upgrading docker compose tools
