### ISSUE TITLE
how to restrict download permissions  of files to users  in cvat

### ISSUE THREAD

**Issue by Praiselinee** [opencv/cvat#6135]
### My actions before raising this issue
- [ ] Read/searched (https://github.com/opencv/cvat/issues/4441)
- [ ] Searched [past issues](/issues)

I want to restrict the users to download the  jobs from CVAT , and give access to only selected users.
change the export behaviour permissions.

### Expected Behaviour
To restrict download to users and only authorised and selected users can download the job/job files

### Current Behaviour
all users can download the jobs from dataset

**Comment by bsekachev** [comment]
> all users can download the jobs from dataset

That is not exactly true. Only staff assigneed to a job (or its task, or its project) can export the job as a dataset.

Generally Open Policy Agent rego files are responsible for permissons (in case with jobs: ``cvat/apps/iam/rules/jobs.rego``), consider changing them according your needs and rebuilding CVAT with ``-f docker-compose.dev.yml`` and ```--build`` arguments.
