### ISSUE TITLE
(nuclio) Failed to start yolo-v3-tf 

### ISSUE THREAD

**Issue by rongirl** [opencv/cvat#6138]
### My actions before raising this issue
- [x] Read/searched [the docs](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)
- [x] Searched [past issues](/issues)

Hello, I deployed successfully yolo-v3-tf 
```shell
nuctl deploy --project-name cvat \
  --path serverless/openvino/omz/public/yolo-v3-tf/nuclio \
  --volume `pwd`/serverless/common:/opt/nuclio/common \
  --platform local
```
Then I tried to test the deployed model 
```shell
image=$(curl https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png --output - | base64 | tr -d '\n')
cat << EOF > /tmp/input.json
{"image": "$image"}
EOF
cat /tmp/input.json | nuctl invoke openvino.omz.public.yolo-v3-tf -c 'application/json'
```
I got this error 
```shell 
Error - Function not found: openvino.omz.public.yolo-v3-tf @ nuclio
    /nuclio/pkg/nuctl/command/invoke.go:132

Call stack:
Failed to invoke function
    /nuclio/pkg/nuctl/command/invoke.go:132
```
How can I solve it?
Thank you.
### Your Environment
Docker 23.0.6
KDE neon 5.27
Nuctl 1.8.14

**Comment by bsekachev** [comment]
@rongirl 

> Hello, I deployed successfully yolo-v3-tf

Nuclio literally says that the model does not exist. What is output of ``nuctl get functions``?
