### ISSUE TITLE
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

### ISSUE THREAD

**Issue by Ai-is-light** [opencv/cvat#614]
I load the cvat, postgres, redis with docker under the Mac, while after loading those images into the CentOS computer and run docker-compose up -d --build, I got the following ERROR:
Creating network "cvat_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
Looking forward to any reply

**Comment by bsekachev** [comment]
@Ai-is-light 
You have copied docker images from one the system to another, have you?

**Comment by Ai-is-light** [comment]
Yes, you are right? I have to do that, because I have to use the inner network and compute. I got this docker image from docker hub, like 
https://github.com/opencv/cvat/issues/397
https://hub.docker.com/r/venergiac/opencv-cvat

And, I also build this repo's cvat and it can work well in my Mac. However I have to let CVAT working at the inner network. Would you mind sharing this repo'docker, or giving some suggetion.
My environment is CentOS7, which is re-created by our own team and cannot connect the internet.
I have tried to re-build the CVAT, but the docker cannot connect the internet.
looking forward any replies.
Thx
@bsekachev

**Comment by nmanovic** [comment]
@Ai-is-light , it isn't an issue with CVAT. Try to ask the question on our https://gitter.im/opencv-cvat. The scenario is unusual and it should be investigated on your end. We don't have such experience for now.

I will close the issue. Don't hesitate ask your questions on our gitter channel and submit new bug/feature requests. Thanks!

**Comment by VisionaryMind** [comment]
I have also encountered this problem, in in my case, it was due to the fact that I was using a VPN. Simply disabling the VPN temporarily allows docker-compose to run without the IPv4 overlapping address error.
