### ISSUE TITLE
Could not fetch frame data from the server! 0

### ISSUE THREAD

**Issue by b3c3ll** [opencv/cvat#6142]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. I have installed the git clone https://github.com/opencv/cvat
1. then exports the host and email!
1. docker compose -f docker-compose.yml -f docker-compose.https.yml up -d

### Expected Behaviour

It Might have run smootly and showing the Video!

I have installed on the same server last month and it was going great!

### Current Behaviour

It wont show the Video file!

### Your Environment

$ git log -1
commit 2a41d5969ce2dba2eb48b461243802a3a9ea8746 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Boris Sekachev <boris.sekachev@yandex.ru>
Date:   Fri May 12 18:00:08 2023 +0300

$ docker version
Client: Docker Engine - Community
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        ef23cbc
 Built:             Fri May  5 21:18:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.9
  Git commit:       9dbdbd4
  Built:            Fri May  5 21:18:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 
- Operating System and version (e.g. Linux, Windows, MacOS):
Linux
5.4.0-148-generic Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Chrome is up to date
Version 113.0.5672.93 (Official Build) (64-bit)

**Comment by b3c3ll** [comment]
I do Confirm that i can access the Video Frames usign MS Edge!!
While chrome is not openning Frames
@bsekachev

**Comment by bsekachev** [comment]
1. Please, provide more error details like screenshots, docker logs, etc. 
2. Try to clear the browser cache in Chrome.
