### ISSUE TITLE
Not able to load multiple images for annotation

### ISSUE THREAD

**Issue by vamsykothuru** [opencv/cvat#615]
Hi,

I tried creating a task for testing with three images. 
![Screenshot from 2019-08-05 10-17-43](https://user-images.githubusercontent.com/37617863/62439787-d33e4280-b76a-11e9-8f52-55cc40d56f98.png)

Task created successfully..Able to load the task..
![Screenshot from 2019-08-05 10-18-00](https://user-images.githubusercontent.com/37617863/62439811-f0731100-b76a-11e9-9ddc-76b29e73a748.png)

But in all the three frames i am able to see only the first image.
![Screenshot from 2019-08-05 10-23-47](https://user-images.githubusercontent.com/37617863/62439877-4942a980-b76b-11e9-9902-c18997f69335.png)
![Screenshot from 2019-08-05 10-24-05](https://user-images.githubusercontent.com/37617863/62439900-67a8a500-b76b-11e9-8368-d705860a24ca.png)
![Screenshot from 2019-08-05 10-25-29](https://user-images.githubusercontent.com/37617863/62439901-69726880-b76b-11e9-85de-e1465c88fb33.png)

Please suggest..

**Comment by nmanovic** [comment]
@vamsykothuru , please check files which you are loading. Probably they are all the same.

**Comment by nmanovic** [comment]
@vamsykothuru , need more information from you to advise something. I will close the issue for now. Don't hesitate to reopen it if you can reproduce the problem on your side and check that loaded images are different.

**Comment by vamsykothuru** [comment]
@nmanovic, I have checked the images. filenames deceived me. Filenames are different but seems like all are same. 

Thanks for your time.

Thanks,
Ravi
