### ISSUE TITLE
Is is possilble to mute every labels with specific class at once? CVAT 2.4

### ISSUE THREAD

**Issue by stevezkw1998** [opencv/cvat#6153]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

As we known, CVAT allows us to mute some spcific labels by right clicking label and press key 'K' in keyborad.
![image](https://github.com/opencv/cvat/assets/53121066/7164aab3-cf2b-4d15-94d5-7dbe80942d3b)
But is it possible to hide all labels with class like 'car' at once in Project layer?
![image](https://github.com/opencv/cvat/assets/53121066/f56cfef5-6df4-49c9-90de-fa5053cb51c4)

### Expected Behaviour
Allow us to mute all labels with specific class like 'car'

### Current Behaviour
I didn't find any related support

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
On project layer it is impossible.
But you can hide all specific labels in a job using [annotation filters feature. ](https://opencv.github.io/cvat/docs/manual/advanced/filter/)

<img width="596" alt="image" src="https://github.com/opencv/cvat/assets/40690378/57948cfd-a952-4bd5-8b6a-b538b96b062b">

**Comment by stevezkw1998** [comment]
> On project layer it is impossible. But you can hide all specific labels in a job using [annotation filters feature. ](https://opencv.github.io/cvat/docs/manual/advanced/filter/)
> 
> <img alt="image" width="596" src="https://user-images.githubusercontent.com/40690378/238551070-57948cfd-a952-4bd5-8b6a-b538b96b062b.png">

Thank you for your great help @bsekachev , it solve my issues
