### ISSUE TITLE
Adjust bbox without changing key-points when editing skeleton

### ISSUE THREAD

**Issue by stevezkw1998** [opencv/cvat#6158]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Is it possible to only adjust bbox without changing the positions of any points in the skeleton when [Editing the skeleton](https://opencv.github.io/cvat/docs/manual/advanced/annotation-with-skeletons/editing-the-skeleton/)?

### Steps to Reproduce (for bugs)
Before adjust the bbox
![image](https://github.com/opencv/cvat/assets/53121066/bbca561b-d14a-4a19-9112-bd83ef24fa40)
After adjust the bbox (I don't want to change any positions of the key-points)
![image](https://github.com/opencv/cvat/assets/53121066/3533af4b-878e-43ab-a934-e69c7cf81ff8)

### Expected Behaviour
See above

### Current Behaviour
See above

### Possible Solution
Solution 1: 
Maybe we can considering separate key-points and wrapped bbox first, and then draw key-points and bbox separatly, eventually merge bbox + key-points into a new skeleton.

Solution 2:
Allow option to only adjust bbox without changing key-points.

### Context
Some time overweight cat and skim cat have same skeleton key-points but different wrapped bbox.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Hi @stevezkw1998 

You do not have boudning box annotations in your example. Bounding box you see is not real. It is used exactly to resize the whole skeleton. Nothing to adjust here. If you want to have a bounding box, create another bounding box label and annotate the object using it. 
Please look at this issue #5904

**Comment by stevezkw1998** [comment]
Thank you for your explaination @bsekachev 
Now I understand how it works
