### ISSUE TITLE
What format is the JSON response from API annotations?

### ISSUE THREAD

**Issue by realtimshady1** [opencv/cvat#6159]
I am using the GET request for /api/jobs/{id}/annotations without a format specified so it is received as a JSON. I am not able to determine the format of this annotation.

Here is a sample of the output.
```
{'version': 0,
 'tags': [],
 'shapes': [{'id': 183998,
   'label_id': 370,
   'type': 'rectangle',
   'frame': 70,
   'group': 0,
   'source': 'manual',
   'occluded': False,
   'outside': False,
   'z_order': 0,
   'rotation': 0.0,
   'points': [209.0, 349.0, 219.0, 360.0],
   'attributes': [{'spec_id': 8, 'value': 'false'}],
   'elements': []},
  {'id': 183971,
   'label_id': 370,
   'type': 'rectangle',
   'frame': 71,
   'group': 0,
   'source': 'manual',
   'occluded': False,
   'outside': False,
   'z_order': 0,
   'rotation': 0.0,
   'points': [209.0, 349.0, 219.0, 360.0],
   'attributes': [{'spec_id': 8, 'value': 'false'}],
   'elements': []},
...
  {'id': 184020,
   'label_id': 370,
   'type': 'rectangle',
   'frame': 2651,
   'group': 0,
   'source': 'manual',
   'occluded': False,
   'outside': False,
   'z_order': 0,
   'rotation': 0.0,
   'points': [65.0, 304.0, 76.0, 315.0],
   'attributes': [{'spec_id': 8, 'value': 'false'}],
   'elements': []}],
 'tracks': []}

**Comment by kompaqt** [comment]
The response is in the internal cvat format.

If you need another format (i.e. CVAT 1.1) you can use:
`/api/jobs/{id}/annotations?format=CVAT for images 1.1&action=download` 

The response will be a zip file which needs to be unzipped and decoded.
A clear advantage is that you get label/ attribute names and not only internal id's.

**Comment by bsekachev** [comment]
@realtimshady1

You are using endpoint to transmit annotations from server to client. Endpoint return types can be found here: <CVAT_HOST>/api/swagger/.
 If you want export a dataset, consider using ``*/dataset`` endpoints from the link above.
