### ISSUE TITLE
Annotation XML timezone problem

### ISSUE THREAD

**Issue by jax79sg** [opencv/cvat#616]
Hi, 
I am using the 'updated' element of the annotation xml and noted that the date/time given is not that of the system time. Interestingly, the discrepancy is also consistent with the logs printed in CVAT. 

I post a line from the logs for clarity.
```
cvat          | 2019-08-05 07:47:55,481 DEBG 'runserver' stderr output: 

2019-08-05 08:52:49.193254+03:00
```

The first line's date time is in sync with the system time, which seems to be displayed in UTC +0.
I perform a update of the annotation and dumped it. The 2nd line is a printout that i extract from the annotation xml. The time is skewed by a couple of hours.

Am i missing something?

**Comment by nmanovic** [comment]
@jax79sg , I agree they should be synchronized.
