### ISSUE TITLE
Adding labels to existing project

### ISSUE THREAD

**Issue by quaid281** [opencv/cvat#6166]
Apologies once again for not using the proper format for new issues.

I have an existing project with 10 labels, I want to use the CVAT SDK to add 15 more labels.
The labelsApi doesn't not have a 'create' method?  Should I be using 'partial_update' method?

Here is my code:
```
def load_labels(label_list):
    """
    Load labels from a JSON file.
    Args:    file_path (Path): Path to the JSON file containing labels.
    Returns: list: A list of PatchedLabelRequest objects.
    """
    labels = [PatchedLabelRequest(name=label['name'], color=label['color']) for label in label_list]
    return labels

# Replace this with your actual project id
project_id = 8
df = pd.read_excel(r'C:\Users\Downloads\Official CVAT Annotations.xlsx',sheet_name=0)
df.columns = df.iloc[0]
df =df.iloc[1: , :]
new_labels = load_labels(df.to_dict('records'))

with ApiClient(configuration) as api_client:
    # Get all labels in the project
    try:
        (data, response) = api_client.labels_api.list(
            project_id=project_id,
        )
        labels = data.results
        print(labels)
    except exceptions.ApiException as e:
        print("Exception when calling LabelsApi.list(): %s\n" % e)

    # Create new labels in the project
    for new_label in new_labels:
        label_request = PatchedLabelRequest(
            name=new_label['name'],
            color=new_label['color']
        )

        try:
            (data, response) = api_client.labels_api.create(
                project_id,
                label_request=label_request,
            )
            print(f"Created label {new_label.name}")
        except exceptions.ApiException as e:
            print(f"Exception when calling LabelsApi.create(): {e}")
```

**Comment by zhiltsov-max** [comment]
Hi, sorry for late response. The labels can only be added to projects/tasks using their `partial_update()` / PATCH operations. You can find API examples [here](https://github.com/opencv/cvat/blob/99a6cf9e5e1d1763cfb70fdd43f79c4c53c1d1c8/tests/python/rest_api/test_projects.py#L787-L792) for a project and [here](https://github.com/opencv/cvat/blob/99a6cf9e5e1d1763cfb70fdd43f79c4c53c1d1c8/tests/python/rest_api/test_tasks.py#L1417-L1422) for a task, also you can use SDK like this:

```python
from cvat_sdk.api_client import models
from cvat_sdk.api_client.api_client import ApiClient

with ApiClient(...) as api_client:
  api_client.tasks_api.partial_update(id, patched_task_write_request=models.PatchedTaskWriteRequest(labels=[{"labels": [new_label]}]))
```

**Comment by quaid281** [comment]
No Worries.  I'm trying to add the labels to projects.  I've tried the code above an I'm having issues with the 'id' parameter not being recognized.  I've tried `api_client.tasks_api.partial_update()` and `api_client.projects_api.partial_update()` and I get the following error:

` File "C:\Users\Downloads\CVAT\autoExport.py", line 84, in update_labels
    api_client.tasks_api.partial_update(id, patched_task_write_request=models.PatchedTaskWriteRequest(labels=[{"labels": [new_labels]}]))
  File "C:\Users\AppData\Local\miniconda3\envs\qaqc\lib\site-packages\cvat_sdk\api_client\api\tasks_api.py", line 2564, in partial_update
    return self.partial_update_endpoint.call_with_http_info(**kwargs)
  File "C:\Users\AppData\Local\miniconda3\envs\qaqc\lib\site-packages\cvat_sdk\api_client\api_client.py", line 1058, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\AppData\Local\miniconda3\envs\qaqc\lib\site-packages\cvat_sdk\api_client\api_client.py", line 497, in call_api
    return self.__call_api(**params)
  File "C:\Users\AppData\Local\miniconda3\envs\qaqc\lib\site-packages\cvat_sdk\api_client\api_client.py", line 273, in __call_api
    raise e
  File "C:\Users\AppData\Local\miniconda3\envs\qaqc\lib\site-packages\cvat_sdk\api_client\api_client.py", line 265, in __call_api
    response = self.request(
  File "C:\Users\AppData\Local\miniconda3\envs\qaqc\lib\site-packages\cvat_sdk\api_client\api_client.py", line 547, in request
    return self.rest_client.PATCH(url,
  File "C:\Users\AppData\Local\miniconda3\envs\qaqc\lib\site-packages\cvat_sdk\api_client\rest.py", line 278, in PATCH
    return self.request("PATCH", url,
  File "C:\Users\AppData\Local\miniconda3\envs\qaqc\lib\site-packages\cvat_sdk\api_client\rest.py", line 206, in request
    raise NotFoundException(http_resp=r)
    
    
cvat_sdk.api_client.exceptions.NotFoundException: Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 20 Jul 2023 18:31:05 GMT', 'Content-Type': 'application/vnd.cvat+json', 'Content-Length': '23', 'Connection': 'keep-alive', 
'Allow': 'GET, PATCH, DELETE, HEAD, OPTIONS', 'Referrer-Policy': 'same-origin', 'Server': 'Apache', 'Vary': 'Accept,Origin,Cookie', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': 'c4e005d8-1b2f-4130-b5be-74f2e1a87372'})
HTTP response body: {"detail":"Not found."}`
