### ISSUE TITLE
Cannot load models for automatic annotation

### ISSUE THREAD

**Issue by ShangWeiKuo** [opencv/cvat#6169]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

- **Docker version: 20.10.19**
- **CVAT version: v2.4.1**

Hello. I've installed CVAT sucessfully. 

However. There are no models I could choose as the picture below when I opened the Automatic Annotation dialog window.

How should I do to get the pre-trained models or upload my custom models ?

Thank you for your help in advance.

![image](https://github.com/opencv/cvat/assets/26018604/94f72faa-ea8c-4bf8-9c79-5046be0fb6bd)

**Comment by bsekachev** [comment]
You need to deploy them. Please, read the [guide](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/).

<img width="1013" alt="image" src="https://github.com/opencv/cvat/assets/40690378/cbb164f4-0ee4-4e0f-9da0-8d7890ef90c1">

**Comment by bsekachev** [comment]
We have multiple models, you can deploy your own using presented as an example. 
There is also a [guide](https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/) for this.

**Comment by ShangWeiKuo** [comment]
Thank you very much @bsekachev 

Dose CVAT supports **tensorrt** format in the field `annotations.framework` if I would like to adding my tensorrt engine models ?
