### ISSUE TITLE
Mac installation failed

### ISSUE THREAD

**Issue by niaoyu** [opencv/cvat#617]
Following the steps, when try "docker-compose up -d", the console shows

Starting cvat_db ... 
Starting cvat_db ... error
ERROR: for cvat_db  Cannot start service cvat_db: b'Mounts denied: EOF'
ERROR: for cvat_db  Cannot start service cvat_db: b'Mounts denied: EOF'

When I run the 
`docker volume create pgdata`
`docker run -it --rm -v pgdata:/var/lib/postgresql/data postgres:10.3-alpine`
it shows "docker: Error response from daemon: Mounts denied: EOF".

**Comment by nmanovic** [comment]
Hi @niaoyu ,

The same commands work fine for me:

<details>
```bash
nmanovic@Nikitas-MBP:~/Workspace/cvat$ docker volume create pgdata
pgdata
nmanovic@Nikitas-MBP:~/Workspace/cvat$ docker run -it --rm -v pgdata:/var/lib/postgresql/data postgres:10.3-alpine
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
2019-08-05 12:25:47.310 UTC [28] WARNING:  no usable system locales were found
ok
syncing data to disk ... ok
```
</details>

Probably it is a permission issue with your docker. Could you please check on your side?

**Comment by nmanovic** [comment]
@niaoyu , I will close the issue. Even the simple command which you mentioned didn't work on your machine. Need to check on your side.
