### ISSUE TITLE
Spent time on annotating 

### ISSUE THREAD

**Issue by p0mad** [opencv/cvat#6172]
Is it possible to measure how much time was spent on the labelling by each user?

**Comment by realtimshady1** [comment]
There is an 'Analytics' tab which will open up Graphana. You can browse standard dashboards at the left panel with the 4 squares icon and select the 'Management' dashboard. This will show how much time and actions have been spent on each Task/Job.
<img width="1862" alt="image" src="https://github.com/opencv/cvat/assets/20720732/c7b6e544-1301-4e73-9fab-63dd09103e1a">

**Comment by p0mad** [comment]
Great, But how can i access that without grafana?
( my grafana container always exits!

but there could be a backend to that grafana like prometheus or some other agents!
any other ways to check the spent time?

**Comment by p0mad** [comment]
@realtimshady1 
which specific ports needs to be open for Grafana?
I get bad gateway error on browser!

**Comment by realtimshady1** [comment]
if you're getting bad gateway error and the grafana container is not running. Try running docker compose again to get it up and running again with `docker compose -f docker-compose.yml up -d`

**Comment by bsekachev** [comment]
@p0mad Have you solved the issue?
