### ISSUE TITLE
Use different OpenCV tracker

### ISSUE THREAD

**Issue by realtimshady1** [opencv/cvat#6175]
How can I use different a different OpenCV tracker other than TrackerMIL?

It seems that there are a number of other available trackers:
1. BOOSTING
2. MIL
3. KCF
4. TLD
5. MEDIANFLOW
6. GOTURN
7. MOSSE
8. CSRT

I tried just replacing every 'TrackerMIL' with 'TrackerMOSSE' but I think more will be needed to switch to a different tracker

**Comment by bsekachev** [comment]
Hi @realtimshady1 

Other trackers from OpenCV are not supported.

**Comment by realtimshady1** [comment]
can this be an enhancement then?

**Comment by realtimshady1** [comment]
I'm not quite sure, there's no longer a need for it but I do understand the code better since last year. So perhaps it can be looked into
