### ISSUE TITLE
WHAT'S HAPPENING?? I CAN't SEE MY RUNNING CONTAINERS, WHILE WEBPAGE IS UP!!!!

### ISSUE THREAD

**Issue by b3c3ll** [opencv/cvat#6176]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. I have installed cvat in my server
1. got some restarts
1. containers are not visible ( docker ps -a) while the webpage is up and accessible publicly! not even with sudo docker ps -a  !!!
1. when i turn the server off, the access would be cut off!
2.  I just wanted to check logs of trafica but i found that non of the containers nor images are visible!

### Expected Behaviour

Able to see the containers

### Current Behaviour

No visible container or docker images 

### Your Environment

- Git hash commit (`git log -1`): 
~/cvat$ git log -1
commit 7141f3be1d66fff43c627ea2a82720e3020619e2 (HEAD, origin/develop, origin/HEAD, develop)
Author: Andrey Zhavoronkov <andrey@cvat.ai>
Date:   Tue May 16 20:59:12 2023 +0300

    Revert "Fix version of postgres image (#6136)" (#6151)

- Docker version `docker version` (e.g. Docker 17.0.05):
docker version
Client: Docker Engine - Community
 Version:           24.0.0
 API version:       1.41 (downgraded from 1.43)
 Go version:        go1.20.4
 Git commit:        98fdcd7
 Built:             Mon May 15 18:49:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       5d6db84
  Built:            Mon Apr 10 09:55:49 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5

- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):
uname -a
Linux data-delete-x 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by b3c3ll** [comment]
Steps to reproduce:

git clone https://github.com/opencv/cvat
cd cvat && git checkout 7141f3be1d66fff43c627ea2a82720e3020619e2
cd ~/cvat && export CVAT_HOST=testns.net                    ====>>>> Replaced with fake address!
export ACME_EMAIL=aabssd@gmail.com
docker compose -f docker-compose.yml -f docker-compose.https.yml up -d

**Comment by timmermansjoy** [comment]
this sounds like its an issue with your docker install that it lost visibility of the docker deamon that is running the containers

**Comment by b3c3ll** [comment]
@timmermansjoy
Hi and thanks for the replay!

it's been running for quite a while ( three days now ) and its running smotly[ visible on the web store and backups, ...] but i dont see the containers!! [docker ps -a]
even i can't stop it unless i turn the server down!

Thats the way i installed my docker and docker-compose:

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get --no-install-recommends install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo groupadd docker
sudo usermod -aG docker $USER
sudo chmod 666 /var/run/docker.sock
Do you see any wrong installation behavior?

Thats pretty funny because i have some other containers and images and i can see then and do stop/start!

what would be the problem and any possible solution that came to your mind?

thanks
best regards

**Comment by bsekachev** [comment]
@b3c3ll 

Please, address the issue to Docker community.
