### ISSUE TITLE
Uploading annotation with xml rules unclear, seems have nothing to do with metadata

### ISSUE THREAD

**Issue by stevezkw1998** [opencv/cvat#6177]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When I upload annotations.xml in CVAT format to a job as annotations, I found:
1. No matter which metadata I deleted, annotations will be succcessfully uploaded.
2. No matter I modifed images id, images name, images size, annotations will be succcessfully uploaded.
3. Only when I delete/edit tags like 'skeleton' insdie 'image' that would impact annotation.

This cause problems:
1. If job has 10 images, but annotations.xml has 7 images, what will happen?
2. If job has 7 images, but annotations.xml has 10 images, what will happen?
3. Does the matching rules follows the order of images like 1st anno match 1st images no matter the name?

### Expected Behaviour
I think it should at least has a specific and clear rules for us to know how we can write a proper annotations.xml when we want to upload annotations.xml to CVAT

### Current Behaviour
Uploading annotation with xml rules unclear

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
1. Metadata are not used during importing annotations, they exist for user to satisfy some requirements
2. If there is an image in annotation file not presented in a task, annotations from the image are not expected to be uploaded
3. If CVAT task has some images where annotations are not presented in annotations file, it will stay without annotations after upload

> write a proper annotations.xml when we want to upload annotations.xml to CVAT

1. Keep correct frame names
2. Format specification is here: https://opencv.github.io/cvat/docs/manual/advanced/xml_format/
