### ISSUE TITLE
'Invalid dts sequences' in generating manifest file for video(.mp4) file

### ISSUE THREAD

**Issue by Pan-will** [opencv/cvat#6178]
### My actions before raising this issue  &&  Steps to Reproduce (for bugs)
1.Prepare the MP4 video file
2.Execute the command in the terminal: python  cvat/utils/dataset_manifest/create.py  --force  --output-dir  cvat-files/video  cvat-files/video/bird.mp4
3.The following problem occurs in the terminal: 
![image](https://github.com/opencv/cvat/assets/50573470/1679a9fc-9748-462f-97ea-7ccf311bbe5e)

### Expected Behaviour
Expect the following console output and a manifest.jsonl file
![image](https://github.com/opencv/cvat/assets/50573470/c01b170c-37c9-440c-90bb-380cfdb29871)

### Current Behaviour
See Steps to Reproduce above

### Possible Solution
Not yet available

### Context
I tried to use the create.py script to generate manifest.jsonl files for.mp4 video files, but the generation failed.

### Your Environment
Operating System and version: Linux nbser-<username>-cpu-0 5.16.20-1.el7.bzl.x86_64 #3 SMP PREEMPT Thu Aug 18 13:53:10 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

Python version 3.8.10
git version 2.25.1
numpy                          1.22.2
natsort                        8.0.0
av                             9.2.0
tqdm                           4.65.0
 opencv-python-headless   4.5.5.62 
pillow                       9.3.0

**Comment by bsekachev** [comment]
@Pan-will 
I can suggest trying to convert the video using other codecs.
