### ISSUE TITLE
Set up isssues with semi annotation with deep learning model.

### ISSUE THREAD

**Issue by lchunleo** [opencv/cvat#6179]
i am facing some issues regarding deploying serverless for the annotation and have two issues. 
1) Magic Wand not appearing
2) Model tab does not show the nuctl deployed models.

1) The Magic wand, i unable to get it appearing. i follow the discussion but unable to find the cause.
https://github.com/opencv/cvat/issues/5987

2) At this point, i had been following the guides on checking the nuctl deployed and have successfully deployed and verified through the nuctl dashboard and get functions. Based on this guide (https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/) i am following up to the deployment of the siamese mask. However i dont see it in the model and my running of the container is ok and no error.

And if i get docker-compose yml from the github and run i will encounter "service "cvat" has neither an image nor a build context specified: invalid compose project" why is it so? 

Appreciate help in these issues. Thanks in advance

**Comment by realtimshady1** [comment]
I followed this tutorial page and it worked for me
https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

**Comment by lchunleo** [comment]
> @lchunleo
> 
> Please, provide all steps you did and logs you have. Also fill the issue template as possible.

Thanks . i noted the issues arised because i am using a old version of cvat and thus the newer functions such as SAM can't work. i have to reinstall the new cvat to make it work
