### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by trinath503** [opencv/cvat#618]
missing : ppa:mc3man/xerus-media
![Screenshot from 2019-08-05 17-45-18](https://user-images.githubusercontent.com/19545163/62464013-20d9a000-b7a9-11e9-9259-1d7e6d1e73fc.png)

ERROR: '~mc3man' user or team does not exist.
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -yq         python-software-properties         software-properties-common         wget &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         unzip         unrar         p7zip-full         vim &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

**Comment by nmanovic** [comment]
Hi @trinath503 , could you please check internet connection or your proxy settings? We can build CVAT without any problems on our side.

ppa:mc3man/xerus-media: https://launchpad.net/~mc3man/+archive/ubuntu/xerus-media

**Comment by trinath503** [comment]
I tried on the online server - it worked but on the local machine it's throwing the error which mentioned earlier.
Thanks

**Comment by nmanovic** [comment]
@trinath503 , you need to check your local machine. Try to run on your local machine the command below. Does it work?
```
sudo apt-get update && \
    apt-get install -yq \
        python-software-properties \
        software-properties-common \
        wget && \
    add-apt-repository ppa:mc3man/xerus-media -y && \
    add-apt-repository ppa:mc3man/gstffmpeg-keep -y
```

P.S. I will close the issue because our team can do nothing with your local environment.
