### ISSUE TITLE
What to do when exporting data so as not to change the original file name

### ISSUE THREAD

**Issue by wangwangteam** [opencv/cvat#6180]
### My actions before raising this issue
- export  MOT data

### Steps to Reproduce (for bugs)

1. click  menu
2. click  export job data
3. click MOT 1.1, and  save images

### Expected Behaviour

The name of the exported image is the same as the name of the image at the time of upload

### Current Behaviour

origin  imgs name like this :
DJI_1000(1).JPG  DJI_1000(2).JPG 

export imgs name like this:
000001.JPG   000002.JPG

### Possible Solution

no idea.
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Probably this is because MOT is designed for videos. 

@zhiltsov-max Do you have any suggestions?
