### ISSUE TITLE
Methods for CVAT to call nuclio deep learning models

### ISSUE THREAD

**Issue by ShangWeiKuo** [opencv/cvat#6182]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hello. 

Does CVAT send the request of automatic annotation to nuclio and get the inference results from nuclio by Webhook API or Django RESTful API ?

**Comment by bsekachev** [comment]
@ShangWeiKuo 

Webhook API **is not** used for automatic annotation. So, the second one.

**Comment by ShangWeiKuo** [comment]
Excuse me @bsekachev 

How CVAT sends the request of automatic annotation to nuclio and get the inference results by Django RESTful API ?
