### ISSUE TITLE
There are no images/containers with "worker_low" in Docker desktop.

### ISSUE THREAD

**Issue by prnr** [opencv/cvat#6185]
### My actions before raising this issue
- [O] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [O] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. build with serverless option(https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/) in wsl ubuntu any version / Docker Desktop 4.19.0
2. Install CUDA-related features(Nvidia docker toolkit, driver, etc)

### Context

![sc 2023-05-23 123214](https://github.com/opencv/cvat/assets/22967869/44350af0-edfe-427e-8df1-9514c522fdd9)

I was installing a model with TF applied and was looking at that post because I faced a similar situation to https://github.com/opencv/cvat/issues/4904, and I realized that there is no container or image called 'cvat_worker_low' in my Docker. There is no item related to worker_low in Docs, and I can't find a similar case even if I search for Issues. Is there a reason you can guess?

![sc2023-05-23 122511](https://github.com/opencv/cvat/assets/22967869/c8d06e7a-d2dc-400a-a022-fde48bcaf2d8)

All the models that use GPU are not working now.

### Your Environment

- Git hash commit (`git log -1`):commit 157f7e3596b4638b4d5730baf087828522e25245 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): Desktop 4.19.0
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows WSL Ubuntu 20.04
- Other diagnostic information / logs:
docker ps

![sc 2023-05-23 123503](https://github.com/opencv/cvat/assets/22967869/a4fc414a-a4be-42c8-b5a1-e84c0a71bd3a)

**Comment by bsekachev** [comment]
@prnr 

``cvat_worker_low`` was renamed to ``cvat_worker_annotation``

**Comment by prnr** [comment]
> @prnr
> 
> `cvat_worker_low` was renamed to `cvat_worker_annotation`

Thanks! The problem hasn't been solved, but the curiosity has been solved!
