### ISSUE TITLE
Could someone please kindly  tell me why I cannot find the Ai tools button(magic wand) on the left side tool bar ?Is it a bug or something?

### ISSUE THREAD

**Issue by gtlee-422** [opencv/cvat#6188]
- [ yes] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ yes] Searched [past issues](/issues)

Greeting! 

1.I has just installed the cvat annotation tool from the github days ago ,and figured that there is not  the AI tools button(magic wand) . As a beginner of  CVAT,I cannot solve the problem by myslef .There are so many experienced super engineers here ,please help me figure out the problem if you guys have the solution to retify the issue.

Is this a bug that can be fixed  or something else  ? The screenshot of CVAT interface is attached down below.

![image](https://github.com/opencv/cvat/assets/133858335/ab3a5ed2-5715-4393-a606-c461f5578832)

2.The detailed description of the CVAT is  below:
![image](https://github.com/opencv/cvat/assets/133858335/b9649dec-1bb1-4ec5-954d-8436b63c76ca)

3.All the running details of 14 image section of the docker  are  listed in the CVAT container.txt.

[
[CVAT container.txt](https://github.com/opencv/cvat/files/11549695/CVAT.container.txt)
](url)

I have been told that the Ai tools of the CVAT  ,can offer the best Ai supportive experience for the user and help the user to annotate more effectively and rapidly. 

If there is  a possible way to solve the issue please let me know .Thank you so much  for your time .

Steps to Reproduce (for bugs)
  git clone https://github.com/opencv/cvat
 cd cvat
 docker-compose up -d
 <Maybe some parts of the procedures in the midst of the installation have not listed in this part .I am so sorry for that because I cannot remember everthing .I have tried to recall but failed . >
 open localhost:8080 in chrome browser

- Git hash commit (`git log -1`):
   fatal: not a git repository (or any of the parent directories): .git
   Please let me know which part  I have done something wrong ,I just cannot get the hash commit .
- Docker version `docker version` (e.g. Docker 17.0.05):
   The current version   is  Docker Desktop 4.19.0 (106363).

- Are you using Docker Swarm or Kubernetes? 
    No.
 
- Operating System and version (e.g. Linux, Windows, MacOS):
  system:windows 10 pro
  Ubuntu 20.04.6 LTS
  GIT :git version 2.21.0.windows.1
  WSL2
 
 

- Other diagnostic information / logs:none
    <details>
    <summary>Logs from `cvat` container</summary>
    logs from CVAT container has been uploaded  can be checked  via  the link down below:
           https://github.com/opencv/cvat/files/11549695/CVAT.container.txt
    </details>

Thank you so much for your patience and your time.

**Comment by bsekachev** [comment]
You did not install this component. Please look at the following guide: https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

**Comment by gtlee-422** [comment]
> You did not install this component. Please look at the following guide: https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

Thank you a lot for your advice,sir. I will give it a try .

**Comment by gtlee-422** [comment]
> You did not install this component. Please look at the following guide: https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

I have successfully installed the Ai tools following the given information.
Thank you for your help,sir.

**Comment by lsm140** [comment]
> > You did not install this component. Please look at the following guide: https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
> 
> I have successfully installed the Ai tools following the given information. Thank you for your help,sir.

But I didn't find a solution about AI tools on the above website（https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/）. What command did you use to solve it?

**Comment by lsm140** [comment]
I has installed this component,but still  does not work(including restart computer and restart browser)

**Comment by Hagonata** [comment]
> You did not install this component. Please look at the following guide: https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

I need OpenVINO install for this?

**Comment by bsekachev** [comment]
You do not need  to install OpenVINO on host machine. It will be installed inside the container automatically if you are using models from OpenVINO.

**Comment by Hagonata** [comment]
```
~/cvat$ docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED             STATUS                   PORTS                                                                                          NAMES
595972f4a0b3   cvat/ui:dev                                "/docker-entrypoint.…"   6 minutes ago       Up 6 minutes             80/tcp                                                                                         cvat_ui
31ffb6ac93de   timberio/vector:0.26.0-alpine              "/usr/local/bin/vect…"   6 minutes ago       Up 6 minutes                                                                                                            cvat_vector
2fa48c90e99f   cvat/server:dev                            "/usr/bin/supervisor…"   6 minutes ago       Up 6 minutes             8080/tcp                                                                                       cvat_utils
dbd2458210df   cvat/server:dev                            "/home/django/backen…"   6 minutes ago       Up 6 minutes             8080/tcp                                                                                       cvat_server
9b94b29ceeb5   cvat/server:dev                            "/usr/bin/supervisor…"   6 minutes ago       Up 6 minutes             8080/tcp                                                                                       cvat_worker_annotation
b5961f6bb762   cvat/server:dev                            "/usr/bin/supervisor…"   6 minutes ago       Up 6 minutes             8080/tcp                                                                                       cvat_worker_quality_reports
b10c0b9384df   cvat/server:dev                            "/usr/bin/supervisor…"   6 minutes ago       Up 6 minutes             8080/tcp                                                                                       cvat_worker_webhooks
12222ec30734   cvat/server:dev                            "/usr/bin/supervisor…"   6 minutes ago       Up 6 minutes             8080/tcp                                                                                       cvat_worker_import
9415b81c2107   cvat/server:dev                            "/usr/bin/supervisor…"   6 minutes ago       Up 6 minutes             8080/tcp                                                                                       cvat_worker_export
a1de44058f99   postgres:15-alpine                         "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes             5432/tcp                                                                                       cvat_db
136c383d6be1   quay.io/nuclio/dashboard:1.8.14-amd64      "/docker-entrypoint.…"   6 minutes ago       Up 6 minutes (healthy)   80/tcp, 0.0.0.0:8070->8070/tcp, :::8070->8070/tcp                                              nuclio
2b6c27b74786   redis:7.0-alpine                           "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes             6379/tcp                                                                                       cvat_redis
3eb859a294b3   grafana/grafana-oss:9.3.6                  "sh -euc 'mkdir -p /…"   6 minutes ago       Up 6 minutes             3000/tcp                                                                                       cvat_grafana
3b170a26cbc2   traefik:v2.9                               "/entrypoint.sh --pr…"   6 minutes ago       Up 6 minutes             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik
f09c213aff11   openpolicyagent/opa:0.45.0-rootless        "/opa run --server -…"   6 minutes ago       Up 6 minutes                                                                                                            cvat_opa
2833fd2b005c   clickhouse/clickhouse-server:22.3-alpine   "/entrypoint.sh"         6 minutes ago       Up 6 minutes             8123/tcp, 9000/tcp, 9009/tcp                                                                   cvat_clickhouse
afdaaf37c27b   gcr.io/iguazio/alpine:3.15                 "/bin/sh -c '/bin/sl…"   About an hour ago   Up About an hour                                                                                                        nuclio-local-storage-reader
```
looks like I already have a Nuclio container running (quay.io/nuclio/dashboard:1.8.14-amd64). But I don't have AI tools yet.

**Comment by Hagonata** [comment]
> You do not need to install OpenVINO on host machine. It will be installed inside the container automatically if you are using models from OpenVINO.

https://github.com/opencv/cvat/issues/6188#issuecomment-1674700162
