### ISSUE TITLE
models not showing in CVAT

### ISSUE THREAD

**Issue by aligh97** [opencv/cvat#6190]
I'm using Windows 11.
Docker Desktop version: 4.19.0

### Actions before raising this issue
I use this command to deploy nuclio dashboard:
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d

This is the nuclio image in docker-compose.serverless.yml: quay.io/nuclio/dashboard:1.8.14-amd64

When I tried to deploy sam, I get this error:
![photo_2023-05-24_10-04-13](https://github.com/opencv/cvat/assets/66427191/53831ea8-f5e0-4a51-bff3-7a8ecd51f79e)

When I deployed YoloV5 model, it deployed successfully but I can't see the model in CVAT.

**Comment by bsekachev** [comment]
> When I tried to deploy sam, I get this error

Please, provide all the steps you did, ``docker ps`` output, build logs, etc.

**Comment by bsekachev** [comment]
> I can't deploy sam, I only get that error I sent.

It is not clear how you are trying to deploy it.
I expect you use the following command ``deploy_gpu.sh pytorch/facebookresearch/sam/nuclio`` and provide us build log for SAM.
