### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by e-velin** [opencv/cvat#6194]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

I am following the installation tutorial (https://opencv.github.io/cvat/docs/administration/basics/installation/) to install cvat on a Mac m1.

### Current Behaviour

At the step "docker compose up -d" I receive the warning "The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested" for cvat_opa, cvat_worker_webhooks, cvat_server, cvat_worker_import, cvat_worker_export, cvat_utils, cvat_worker_annotation, cvat_ui

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05): Docker 23.0.5
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS 13.3.1

**Comment by winsento** [comment]
You can set the environment variable `DOCKER_DEFAULT_PLATFORM` or `--platform` to `linux/amd64`.
```
export DOCKER_DEFAULT_PLATFORM=linux/amd64 && docker-compose up -d
```

**Comment by govindrai** [comment]
@winsento That doesn't resolve it for me. Still get an error once I go to localhost:8080

**Comment by Kutegz** [comment]
I have a similar issue on both Linux and Windows
The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested

**Comment by daf1286** [comment]
I run export DOCKER_DEFAULT_PLATFORM=linux/amd64 && docker-compose up -d as you said in my Mac and the answer was no configuration file provided: not found

**Comment by bsekachev** [comment]
M1/2/3 CPUs are not supported yet :(

**Comment by Raajhub** [comment]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested- I am running on Mac- M1 -14.4.

Is there any other way to run containers on MAC M1. TIA>

**Comment by flipper09112** [comment]
@bsekachev some update relative to run in Mac m1

I cant export my video labeling with images and maiby is because of this.

` 
 ! cvat_worker_export The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                 0.0s 

`
