### ISSUE TITLE
export dataset or project from CLI

### ISSUE THREAD

**Issue by abdallah1989203** [opencv/cvat#6197]
### My actions before raising this issue
- [*] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ *] Searched [past issues](/issues)

Is it possible to export dataset or project from CLI ?
This order is just for a one task.
cvat-cli --server-host https:/www --server-port 12345 --insecure --auth user:password dump --with-images True --format "COCO 1.0" task_id name.zip

**Comment by bsekachev** [comment]
@zhiltsov-max @SpecLad

**Comment by zhiltsov-max** [comment]
Hi, no, the CLI currently supports only tasks. Please consider using our SDK instead:

```python
from cvat_sdk import make_client

with make_client(host, port, credentials=(user, password)) as client:
    client.projects.retrieve(project_id).export_dataset(format, filename)
```
