### ISSUE TITLE
Installation steps without Docker

### ISSUE THREAD

**Issue by AhmedRefaat** [opencv/cvat#62]
Hello Guys, 
Can you support installation steps without using docker ?

**Comment by nmanovic** [comment]
@AhmedRefaat ,

[Dockerfile](/Dockerfile) itself is a good documentation how to install CVAT without docker. Need to install a lot of dependencies. Support installation instructions for many OSes is overkill for our small team. Thus it is easy for us to say: "we work on any OS where docker is supported" and it covers Linux, Windows, Mac OS, etc...

Does it answer your question?

**Comment by dsdon10** [comment]
Hello folks - we have installed CVAT into our web platform for you to use.  You are free to test it out here:  

https://c.onepanel.io 

We should have GPU optimized capability working soon along with TF_annotation and will train on the entire ImageNet dataset. We will provide free GPU time if you ask to test it out.

Don
Onepanel.io

**Comment by nmanovic** [comment]
@dsdon10 ,

It is a good news. Just send me more details privately (how to run, how to use your platform). I will be glad to try it. But I will delete your message from the issue because it isn't relevant. Thank you.

**Comment by nmanovic** [comment]
@AhmedRefaat ,

I will close the issue. Please don't hesitate to open it again if you think that your question was not answered.
