### ISSUE TITLE
Documentation v0.5.0

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#620]
Describe the following features in documentation:

- [ ] Remote data source (list of URLs to create an annotation task)
- [ ] Load/Dump annotations in different formats
- [ ] Linear interpolation for a single point
- [ ] Video frame filter
- [ ] Auto annotation (link on the cvat/apps/auto_annotation, a couple of examples)

**Comment by BalzGuenat** [comment]
Please also describe the Dataset Repository feature better. Specifically how the credentials for the repo access can be configured.
