### ISSUE TITLE
When creating a new task and the image is a remote download link, an error was reported: Cannot resolve IP address for domain 'xxx. xxx. com'

### ISSUE THREAD

**Issue by liudaolunboluo** [opencv/cvat#6200]
Please note that xxx.xxx.com is an internal domain name of ours. I started CVAT using Docker.composit and configured Extra in Docker.composit.yml_ Hosts, but when I create a new task on the interface, remote_ When files filled in my own xxx.xxx.cmd, I still reported an error: Cannot resolve IP address for domain 'xxx xxx.  com' ； I noticed in the code that in task. py:_ validate_ In the URL method, Python DNS is used to query the A record of IPv4 corresponding to the domain name. It seems that this is from the public DNS server being queried? So what should I do when facing a custom domain name that allows me to download the files corresponding to my own domain name from CVAT deployed on my own server

**Comment by bsekachev** [comment]
Sorry, it looks like we are unable to help with your network configuration.
