### ISSUE TITLE
API-posted issues not shown until refresh

### ISSUE THREAD

**Issue by rubenverhack** [opencv/cvat#6203]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

I am working on a workflow automatically does some sanity checks on annotations. Each time a job is saved, it calls a custom webhook which then posts an issue to the relevant frames if any. The issue is that when posting issues to a job, the assignee does not see the issue / the UI doesn't auto-refresh the issues. If the assignee refreshes the page, then the issue shows up.

It can be reproduced by simply by posting an issue and verifying that it does not show up in the UI until the page is refreshed:

``` 
import requests
import time

api_url = "http://localhost:8080/api/issues"
auth = ('USERNAME', 'PASSWORD')  # replace with your actual username and password
headers = {'Content-Type': 'application/json'}

data = {
  "frame": 0,
  "position": [
    100, 100, 100, 100
  ],
  "job": 1,
  "assignee": 1,
  "message": "There is an issue",
  "resolved": False
}

response = requests.post(api_url, auth=auth, headers=headers, json=data)
print('response')
```

### Expected Behaviour
The issue should be added to the list of issues immediately

### Current Behaviour
The issue is only visible once the page is refreshed, or the job is reopened.

### Possible Solution
Auto-refresh the issues list in the UI when an issue was added.

### Context
I am trying to build a annotation validation system that activates a webhook on saving. The webhook gets the job annotations and performs some sanity checks on it (e.g. a certain two tags can not be really close to each other in a video, ...). This then pushes an issue to the task.

### Your Environment

- Git hash commit (`git log -1`): 37d24e47969cea533ee2aba86d35ccd683f5ada5 
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.13
- Are you using Docker Swarm or Kubernetes? Docker compose
- Operating System and version (e.g. Linux, Windows, MacOS): Linux on WSL2

**Comment by bsekachev** [comment]
Current interaction model (REST API) does not allow client to be auto-updated when server has some changes. 
Using websockets might be a solution, but it is very global change to consider it now.
