### ISSUE TITLE
Indefinite "loading" animation when trying to open a job.

### ISSUE THREAD

**Issue by dave-aiE** [opencv/cvat#6210]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The http://localhost:8080/tasks/3/jobs/1 loads the annotation job.

### Current Behaviour

I recently updated (then completely re-installed) CVAT. Everything works until I try to launch the annotation job. The http://localhost:8080/tasks/3/jobs/1 loads in the web browser, but the spinning "loading" animation just repeats indefinitely.

I gave my user status as staff and superuser, and I selected my user for all groups. Nothing helped...

I've tried to work on various jobs: new videos, new images, backup of old video jobs.  The same effect on all of them.

### Steps to Reproduce (for bugs)

1. Install latest CVAT on Windows 11 as per [installation guide](https://opencv.github.io/cvat/docs/administration/basics/installation/#how-to-get-cvat-source-code)
2. Create project.
3. Create task for project.
4. Click "Job #'1"
5. http://localhost:8080/tasks/3/jobs/1 gives a constant rotating "loading" symbol

### Context

I need to update my version of CVAT to match other developers. I cannot collaborate if the job does not load...

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05): Docker 23.0.5
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 11
- Other diagnostic information / logs: 
2023-05-30 14:36:05 cvat_server             | 2023-05-30 12:36:05,145 DEBG 'runserver' stderr output:
2023-05-30 14:36:05 cvat_server             | [Tue May 30 12:36:05.144993 2023] [wsgi:error] [pid 150:tid 140575914407488] [remote 172.18.0.4:34802] WARNING:django.request:Not Found: /api/user-agreements
2023-05-30 14:36:05 cvat_server             |

**Comment by bsekachev** [comment]
Hi. If still relevant, what can you see in the browser dev tools (F12, On ``Console`` tab)? On ``Network`` tab?

**Comment by dave-aiE** [comment]
Thanks for the advice, on the Console tab, it shows the error report:
```
:8080/api/server/health/?format=json&org=:1     Failed to load resource: the server responded with a status of 502 (Bad Gateway)
server-proxy.ts:211 Uncaught TypeError: Cannot read properties of undefined (reading 'id') at t.onerror (server-proxy.ts:211:24)
:8080/assets/download.worker.643278900685e6b656bc.js:1     Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
:8080/api/events?org=:1     Failed to load resource: the server responded with a status of 502 (Bad Gateway)
logger-storage.ts:69 Uncaught (in promise) Error: Request failed with status code 502. "Bad Gateway".
    at Re (server-proxy.ts:165:16)
    at Object.save (server-proxy.ts:1727:15)
    at async gt.value (logger-storage.ts:138:31)
    at async gt.apiWrapper (plugins.ts:42:13)
    at async gt.log (logger-storage.ts:68:9)
:8080/api/lambda/sam_detector.onnx:1     Failed to load resource: the server responded with a status of 502 (Bad Gateway)
ort-web.min.js:6 Failed to load model because protobuf parsing failed.
oe @ ort-web.min.js:6
ort-web.min.js:6 Uncaught (in promise) Error: Can't create a session
    at e.createSessionFinalize (ort-web.min.js:6:451003)
    at e.createSessionFinalize (ort-web.min.js:6:443647)
    at e.OnnxruntimeWebAssemblySessionHandler.loadModel (ort-web.min.js:6:446615)
    at async Object.createSessionHandler (ort-web.min.js:6:156542)
    at async d.create (inference-session-impl.js:170:15)
:8080/api/server/health/?format=json&org=:1     Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:8080/api/server/health/?format=json&org=:1     Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:8080/api/server/health/?format=json&org=:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8080/api/server/health/?format=json&org=:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8080/api/user-agreements?org=:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1     Failed to load resource: the server responded with a status of 404 (Not Found)
```

On the Network tab, I see no errors...
<img width="439" alt="image" src="https://github.com/opencv/cvat/assets/99660775/c90d7ef5-c903-4de3-9069-fa7ed2bdc619">

**Comment by bsekachev** [comment]
> On the Network tab, I see no errors...

First open Network tab, the update the page.

> ```:8080/api/server/health/?format=json&org=:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)```

This is the error. Server is unhealthy, so, check this response on Network tab.

**Comment by dave-aiE** [comment]
I see, thanks again for the advice. There errors reported in the Network tab are the following:
<img width="800" alt="image" src="https://github.com/opencv/cvat/assets/99660775/b43c8545-77fb-4fd2-82f0-82938f268bf4">


and:
<img width="796" alt="image" src="https://github.com/opencv/cvat/assets/99660775/7a12c914-d7a0-4eb4-9a4c-1a2d94555a6d">

**Comment by bsekachev** [comment]
@dave-aiE 

The second one is not a problem.
The first one.. Try to clear the browser cache and reload the page.

**Comment by bsekachev** [comment]
Updating a page once with enabled option ``Disable cache`` is also a solution. 

<img width="424" alt="image" src="https://github.com/opencv/cvat/assets/40690378/ccc10167-a0b8-4d34-b865-cdefc172a56d">

> Do you have any idea what particularly might be the problem with my browser cache

We added new header in recent release. Browser cached server response without necessary header.

**Comment by dave-aiE** [comment]
Super, this works as well.

Thanks a lot for your help!
