### ISSUE TITLE
Upgrading from 2.3.0 to 2.4.4 failed with HTTP502

### ISSUE THREAD

**Issue by hyfung** [opencv/cvat#6213]
### My actions before raising this issue
- [Yes ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ Yes] Searched [past issues](/issues)

I would like to upgrade CVAT from 2.3 to 2.4.3 for Segment Anything Model

I am currently using
- Server 2.3
- Core 7.0.0
- Canvas 2.15.3
- UI 1.42.0

Hosted on
- Ubuntu 20.04 Server
- Docker, non-clustered

The server was deployed with
```bash
#!/bin/bash
sudo -E docker-compose \
  -f docker-compose.yml \
  -f docker-compose.https.yml \
  -f components/analytics/docker-compose.analytics.yml \
  -f components/serverless/docker-compose.serverless.yml \
  up -d
```

and torn down with ... for upgrade
```bash
#!/bin/bash
sudo -E docker-compose \
  -f docker-compose.yml \
  -f docker-compose.https.yml \
  -f components/analytics/docker-compose.analytics.yml \
  -f components/serverless/docker-compose.serverless.yml \
  down
```

Docker volumes were preserved

I cloned a new repo from CVAT
```bash
git clone https://github.com/opencv/cvat.git
cd cvat
git checkout v2.4.4
```

Then started the containers
```bash
export CVAT_VERSION=v2.4.4

sudo -E docker-compose \
  -f docker-compose.yml \
  -f docker-compose.https.yml \
  -f components/serverless/docker-compose.serverless.yml \
  up -d --build
```

CVAT either
- Throws 502 in browser console
- Says "please follow upgrade guide"

Also followed this step https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/ for PGSQL DB dump & import, did not work

### Steps to Reproduce (for bugs)
Refer to above

### Expected Behaviour
- CVAT would be able to re-use the volumes
- All existing data will be preserved

### Current Behaviour
CVAT either
- Throws 502 in browser console
- Says "please follow upgrade guide"

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by azhavoro** [comment]
Please provide logs from cvat_server and cvat_db containers
