### ISSUE TITLE
function.yaml for automatic annotation of tags.

### ISSUE THREAD

**Issue by tommy-hayashida** [opencv/cvat#6220]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have written main.py based on the following issue and pull request. #3358 #3896

Can you tell me how to write a function.yaml to auto-annotate tags?
I don't know what should be in annotations.type.

### Steps to Reproduce (for bugs)

I filled in that field with tag and deployed it.
However, when I looked at the cvat model list, the deployed function did not appear.

```
metadata:
  name: exapmle
  namespace: cvat
  annotations:
    name: exapmle
    type: tag
    framework: onnx
    spec: |
      [
        { "id": 0, "name": "zero" },
        { "id": 1, "name": "one" },
        { "id": 2, "name": "two" }
      ]
...
```

```
23.06.01 09:52:21.313                     nuctl (I) Function deploy complete ...
```

### Your Environment

- CVAT version
![無題](https://github.com/opencv/cvat/assets/23076639/10b7b97b-381c-4800-84ad-2f2e569a9afb)
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 24.0.1
- Operating System and version (e.g. Linux, Windows, MacOS): server Ubuntu18.04,  client Windows10

**Comment by bsekachev** [comment]
Probably server/client code need to modified to support tags. Writing ``function.yaml`` is not enought.

**Comment by bsekachev** [comment]
``type`` can be only ``detector``, ``interactor``, ``tracker``, ``reid``. 
In your case the correct value is probably ``detector``.

You do not need special ``function.yaml`` for tags. 
Just from main.py::handler you need to return list of structures where "type": "tag".

Like this:
```
results.append({
                "confidence": confidence_value,
                "label": "zero",
                "type": "tag",
            })
```

**Comment by tommy-hayashida** [comment]
Thanks!
After replacing 'tag' with 'detector' in function.yaml, the model now appears in the CVAT model list.

However, when I run the auto-annotation, I get an error message 'Could not create annotations Error: Object shape must be one of: ["rectangle","polygon","polyline","points","ellipse","cuboid","skeleton","mask"]'.

main.py is written as follows. Is this correct?

```
    ...
    results = [{'type': 'tag', 'label': infered_label}]
    return context.Response(body=json.dumps(results), headers={},
        content_type='application/json', status_code=200)

```

**Comment by tommy-hayashida** [comment]
I found this issue. #4212
Does this mean there are other codes to add?

**Comment by bsekachev** [comment]
1. You can try running the detector on task (offline mode)
2. In case with online mode, probably need to modify client code a little bit, because before we have not ever had any detectors returnings tags. 

This file: ``cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx``.

In the simplest case to add something like this: 
<img width="751" alt="image" src="https://github.com/opencv/cvat/assets/40690378/54b988d6-e24e-48da-a72d-2195cef8f93d">

```
                                if (data.type === ObjectType.TAG) {
                                    return new core.classes.ObjectState({
                                        label: jobLabel,
                                        frame,
                                        objectType: ObjectType.TAG,
                                        source: 'auto',
                                    });
                                }
```

**Comment by tommy-hayashida** [comment]
I modifed tools-control.tsx.
![無題](https://github.com/opencv/cvat/assets/23076639/9c75d9d4-54ba-4da0-b47f-8bc4b9621988)

Then I received another error message on CVAT.

```
Detection error occurred
Error: Request failed with status code 503. "HTTPConnectionPool(host='host.docker.internal', port=32769): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.co
nnection.HTTPConnection object at 0x7f390045f190>: Failed to establish a new connection: [Errno 111] Connection refused'))".
```
