### ISSUE TITLE
Interaction error occurred Error: Exception in plugin Segmeny Anything: Error: Request failed with status code 403. 

### ISSUE THREAD

**Issue by thanujan96** [opencv/cvat#6221]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. installed cvat 2.4.4 in aws g5.2xlarge instance 
1. created an organization 
1. created a task
1. invited a worker
2. assigned a job for the worker
3. when the worker using hrnet model, he is getting Error as below
Interaction error occurred
Error: Exception in plugin Segmeny Anything: Error: Request failed with status code 403. {"detail":"You do not have permission to perform this action."}.
4 when i assign the worker to a task he is getting no errors

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by thanujan96** [comment]
![image](https://github.com/opencv/cvat/assets/58055657/1eb292d4-4437-4c04-8e13-9143aa70a4ea)
you could show the error here. please help to fix this issue.

**Comment by thanujan96** [comment]
@nmanovic  I am encountering an error when a worker is not assigned to a task but is assigned to a job. The error occurs in the SAM model plugin when it attempts to access the task ID.

**Comment by bsekachev** [comment]
Need to investigate, might be permissions issue

**Comment by thanujan96** [comment]
Thank you!
