### ISSUE TITLE
S3FS mount on Kubernetes using helm-chart

### ISSUE THREAD

**Issue by RohithkumarRavi** [opencv/cvat#6223]
I am setting up CVAT on kubernetes  using helm chart. I want to mount S3 using S3FS. But I couldn't find any documentation on mounting S3fs on helm. Can someone guide me

**Comment by mafs12** [comment]
Hi @RohithkumarRavi I would recommend taking a look at something like [datashim](https://github.com/datashim-io/datashim). We have used it with CVAT v1.6.0.

My issue now is that in CVAT 2.x there's several backend pods running and I'm not sure in which ones I should mount the PV created by _datashim_. Should I add it as additional volume to the same pods that require the default storage?

Could someone help with this, please?

**Comment by mafs12** [comment]
I think I got the answer to my question from https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path.
