### ISSUE TITLE
CVAT containers cannot link to Internet

### ISSUE THREAD

**Issue by ShangWeiKuo** [opencv/cvat#6226]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Excuse me @bsekachev  

When I entered into one of the CVAT containers and tried to make sure if it can link to Internet by implementing **curl www.google.com** as the picture below. 

However. I found that the container named cvat_server with bridge mode cannot connect to external network. 

Is it normal that the CVAT containers can only communicate with the other containers instead of the external ip addresses ?

![image](https://github.com/opencv/cvat/assets/26018604/8bd39051-4d53-4df7-9ead-ab9028c7f006)

**Comment by azhavoro** [comment]
cannot reproduce, check your proxy settings
```terminal
 docker run --entrypoint bash cvat/server:dev -c "curl -I www.google.com"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
content-type: text/html; charset=ISO-8859-1
...
connection: close
```
