### ISSUE TITLE
Cannot upload data to Tasks API: urllib3.exceptions.MaxRetryError SSLEOFError EOF occurred in violation of protocol (_ssl.c:2426)

### ISSUE THREAD

**Issue by timresink** [opencv/cvat#6235]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi,

I am trying to use the CVAT SDK (low-level API) to automatically upload images to a certain Task. To do this, I follow the steps described in the documentation:  https://opencv.github.io/cvat/docs/api_sdk/sdk/lowlevel-api/#binary-data-in-requests-and-responses

Now this works well on my own debian system, but when I run it in a docker container it fails with the error 
`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host={host}, port=443): Max retries exceeded with url: {url}?org={org} (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')))`. 
I have verified/tried the following things:
[x] I have verified that my openssl version is identical inside and outside docker.
[x] set the `verify_ssl=False` in the api_client, and but to no avail. 
[x] setting ssl_ca_cert to /etc/ssl/certs/ca-certicates.crt
[x] adding a delay between requests as some forums were suggesting a time delay. 

The closest error I could find was this [boto3 issue](https://github.com/boto/boto3/issues/3708), which reports the exact same SSL error (_ssl.c:2426) and is also related to form/multi-part post requests.

### reproducing
* Python3.10.11
* the docker image is the python 3.10 is 3.10-slim-bullseye
* cvat_sdk version is 2.3.0

 It would be much appreciated if anyone could help me resolve this!

**Comment by AbdelsalamHaa** [comment]
Hi @timresink 
I have tried to upload more data using the same guideline as yours, but I couldn't upload more data to a task 
the code is below. 
Using this code I faced an error HTTP response body: "Adding more data is not supported"
Your help will be very appreciated. 


from pprint import pprint

        from cvat_sdk.api_client import Configuration, ApiClient, exceptions
        from cvat_sdk.api_client.models import *
        
        # Set up an API client
        # Read Configuration class docs for more info about parameters and authentication methods
        configuration = Configuration(
            host = "localhost:8080",
            username = 'username',
            password = 'password',
        )
        
        with ApiClient(configuration) as api_client:
            (_, response) = api_client.tasks_api.create_data(
            id=120, # this is the task ID 
            data_request=models.DataRequest(
                client_files=[
                    open('./Documents/profileimage_r.jpg', 'rb')
                ],
                image_quality=70,
            ),
            _content_type="multipart/form-data", # required
        )
        
using this code I got this error 

---------------------------------------------------------------------------
ApiException                              Traceback (most recent call last)
<ipython-input-33-0d8485cbee44> in <module>
     13 
     14 with ApiClient(configuration) as api_client:
---> 15     (_, response) = api_client.tasks_api.create_data(
     16     id=120,
     17     data_request=models.DataRequest(

~\anaconda3\lib\site-packages\cvat_sdk\api_client\api\tasks_api.py in create_data(self, id, data_request, _parse_response, _request_timeout, _validate_inputs, _validate_outputs, _check_status, _spec_property_naming, _content_type, _host_index, _request_auths, _async_call, **kwargs)
   2226         kwargs['id'] = id
   2227         kwargs['data_request'] = data_request
-> 2228         return self.create_data_endpoint.call_with_http_info(**kwargs)
   2229 
   2230     def destroy(

~\anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py in call_with_http_info(self, _parse_response, _request_timeout, _validate_inputs, _validate_outputs, _check_status, _spec_property_naming, _content_type, _host_index, _request_auths, _async_call, **kwargs)
   1056                         params['header']['Content-Type'] = content_types_list
   1057 
-> 1058         return self.api_client.call_api(
   1059             self.settings['endpoint_path'], self.settings['http_method'],
   1060             params['path'],

~\anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_schema, auth_settings, collection_formats, _async_call, _parse_response, _request_timeout, _host, _check_type, _request_auths, _check_status)
    495 
    496         if not _async_call:
--> 497             return self.__call_api(**params)
    498 
    499         return self.pool.apply_async(self.__call_api, (), kwds=params)

~\anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_schema, auth_settings, collection_formats, _parse_response, _request_timeout, _host, _check_type, _check_status, _request_auths)
    271         except ApiException as e:
    272             e.body = e.body.decode('utf-8')
--> 273             raise e
    274 
    275         self.last_response = response

~\anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_schema, auth_settings, collection_formats, _parse_response, _request_timeout, _host, _check_type, _check_status, _request_auths)
    263         try:
    264             # perform request and return response
--> 265             response = self.request(
    266                 method, url, query_params=query_params, headers=header_params,
    267                 post_params=post_params, body=body,

~\anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py in request(self, method, url, query_params, headers, post_params, body, _parse_response, _request_timeout, _check_status)
    527                                             body=body)
    528         elif method == "POST":
--> 529             return self.rest_client.POST(url,
    530                                          query_params=query_params,
    531                                          headers=headers,

~\anaconda3\lib\site-packages\cvat_sdk\api_client\rest.py in POST(self, url, headers, query_params, post_params, body, _parse_response, _request_timeout, _check_status)
    254     def POST(self, url, headers=None, query_params=None, post_params=None,
    255              body=None, _parse_response=True, _request_timeout=None, _check_status=True):
--> 256         return self.request("POST", url,
    257                             headers=headers,
    258                             query_params=query_params,

~\anaconda3\lib\site-packages\cvat_sdk\api_client\rest.py in request(self, method, url, query_params, headers, body, post_params, _parse_response, _request_timeout, _check_status)
    209                 raise ServiceException(http_resp=r)
    210 
--> 211             raise ApiException(http_resp=r)
    212 
    213         return r

ApiException: Status Code: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Allow': 'GET, POST, HEAD, OPTIONS', 'Content-Length': '35', 'Content-Type': 'application/vnd.cvat+json', 'Date': 'Tue, 13 Jun 2023 08:52:37 GMT', 'Referrer-Policy': 'same-origin', 'Server': 'Apache', 'Vary': 'Accept,Origin,Cookie', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': '23d085c8-6df1-4725-944d-353e3bbd90a8'})
HTTP response body: "Adding more data is not supported"
