### ISSUE TITLE
Failed to install self-hosted

### ISSUE THREAD

**Issue by muhammadAgfian96** [opencv/cvat#6236]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. git clone the latest
2. set CVAT_VERSION=latest
3. docker-compose up -d

### Current Behaviour

```
reating network "cvat_cvat" with the default driver
Creating cvat_opa        ... done
Creating cvat_redis      ... done
Creating cvat_db         ... done
Creating cvat_clickhouse        ... done
Creating cvat_grafana           ... done
Creating traefik                ... done
Creating cvat_utils             ... done
Creating cvat_worker_import     ... done
Creating cvat_worker_webhooks   ... done
Creating cvat_server            ... error
Creating cvat_worker_annotation ... 
Creating cvat_worker_export     ... done
Creating cvat_vector            ... 
Creating cvat_worker_annotation ... done
ERROR: for cvat_server  Cannot start service cvat_server: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/home/django/backend_entrypoint.sh": 
Creating cvat_vector            ... done

ERROR: for cvat_server  Cannot start service cvat_server: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/home/django/backend_entrypoint.sh": stat /home/django/backend_entrypoint.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

### Your Environment

- Git hash commit (`git log -1`):
```
commit 520d219f3ef1e39b08c8ce0d5da6f4e4f54c2f79 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Andrey Zhavoronkov <andrey@cvat.ai>
Date:   Fri Jun 2 18:40:28 2023 +0300

    Updated CHANGELOG for v2.5.0 (#6234)
```
- Docker version `docker version` (e.g. Docker 17.0.05): `Docker version 20.10.12, build e91ed57`
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by MuhammadSYahyaS** [comment]
I got the same exact issue with `CVAT_VERSION=v2.4.5`.

**Comment by muhammadAgfian96** [comment]
i see, i just notice the `command` for cvat_server is different.
now able to install it.

**Comment by GilbertPan97** [comment]
> i see, i just notice the `command` for cvat_server is different. now able to install it.
> 
> Thanks!

Can you explain in detail how you solved this problem? i met the same problem when i updated the cvat repository
