### ISSUE TITLE
getting 404 page not found error

### ISSUE THREAD

**Issue by tarunmcom** [opencv/cvat#6243]
I installed cvat on ubuntu 20.04 as follows:-
1. docker was already installed.
2. cloned cvat repo using `git clone https://github.com/opencv/cvat`
3. `cd cvat`
4. `export CVAT_HOST=192.168.1.21`
5. `sudo docker compose up -d`

After this every container is running and no error but when I try to access using chrome browser I get this message:- 404 page not found , on the chrome.
I tried to search the issue on internet but seems like those solutions are for older versions.
Kindly help

**Comment by azhavoro** [comment]
https://opencv.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

**Comment by 3210448723** [comment]
Another case, if you are using zerotier and want to access it from within its virtual network, you need to set the IP assigned to zerotier by the IP where the CVAT device is deployed, and, cVAT can not be accessed by machines on a non-zerotier virtual network within the device's LAN unless you have set multiple hostnames like: https://docs.cvat.ai/docs/faq/#how-to-specify-multiple-hostnames

还有一种情况，如果你使用了zerotier并且想在其虚拟网络中访问的话，需要设置部署CVAT设备的ip为zerotier分配的ip。同时，该设备局域网内非zerotier虚拟网络中的机器无法访问CVAT，除非你设置了多个主机名，如：https://docs.cvat.ai/docs/faq/#how-to-specify-multiple-hostnames
