### ISSUE TITLE
Cvat looking for SAM nuclio function at incorrect port

### ISSUE THREAD

**Issue by adnan-earthsense** [opencv/cvat#6244]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

I am having a problem with the Segment Anything interactor model. For some reason, CVAT is looking for the function at port 32769 when the SAM model is at 32768, as seen by `docker ps`. If I issue ``docker restart nuclio-nuclio-pth-facebookresearch-sam-vit-h`, then when it restarts, the port number increments by 1, and then I can use the model in CVAT without the error. But this doesn't make sense to me, as I haven't hard coded any port number anywhere, as far as I am aware. So I don't know why it isn't looking for the function in the right place.

The exact error message is the same one as in issue #6222, but the poster there confirmed his issue is not related to the ports:
```
Interaction error occurred
Error: Request failed with status code 503. "HTTPConnectionPool(host='host.docker.internal', port=32769): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64a03a7a60>: Failed to establish a new connection: [Errno 111] Connection refused'))".
```

If I grep for the port number in the git repo, the only file that has 32768 is
```
cvat$ find . -name "*.*" -type f -exec grep -l 32768 {} \+
./cvat/apps/opencv/static/opencv/js/opencv_4.5.4_dev.js
```
Not sure if this is any help. But I do notice that when it finally does work, it briefly has a message pop up saying something about opencv initialization being successful. There is another recent issue ( #6237 ) regarding opencv initialization, so maybe there's something fishy going on there? Don't really know.

### Steps to Reproduce (for bugs)

1. I reboot my computer, and I open CVAT in chrome by going to the localhost:8080 url. 
1. I open up any task, and try to use the SAM interactor model. Once I click, it returns the error message above

### Expected Behaviour

CVAT should be looking for SAM at the port that it is on. Not looking at some hardcoded value

### Current Behaviour

I get a 503 error saying it can't reach the nuclio function.

### Possible Solution

If I restart the docker container for SAM, that increments the port that it is on up to 32769, the port that CVAT is looking for it on. But this is hacky and I don't want to have to do this.

Instead, perhaps there is somewhere that I can declare which port nuclio should use for SAM, and which port CVAT should be looking for SAM on?

### Context

I want to use CVAT for labeling many images, and this is just an annoyance to have to deal with every  time I want to get started.

### Your Environment

- Git hash commit (`git log -1`):
```
commit 20f65e50d8751e0f41151b7bde1eaa4c77fc0e98 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Anastasia Yasakova <yasakova_anastasiya@mail.ru>
Date:   Sun Jun 4 10:44:38 2023 +0300

    Fix nightly build (#6225)
```
- Docker version `docker version` (e.g. Docker 17.0.05):
24.0.2
- Are you using Docker Swarm or Kubernetes?
No
- Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Try to remove / redeploy the function. Usually it helps. 
Root cause why it happens is not clear :(

**Comment by adnan-earthsense** [comment]
Hmm, this seems to have worked. I rebooted and refreshed the page a few times and hopefully things continue to work. I was able to close some ports on my firewall now, thanks a lot!

**Comment by thompsonmj** [comment]
I am experiencing the same error. It seems that if intermittent manual intervention like discussed above is necessary, this issue should remain open.

**Comment by thompsonmj** [comment]
I made the following local change to `cvat/serverless/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml`:
```yaml
  triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB
        port: 32768 # added this line
```
After redeploying, I am able to use the SAM interactor without errors.
