### ISSUE TITLE
SAM model doesn't always get the border pixels

### ISSUE THREAD

**Issue by davodogster** [opencv/cvat#6250]
Hi I'm running SAM on CVAT.ai free version and often it won't segment the border pixels even if I add point prompts for them.

![image](https://github.com/opencv/cvat/assets/46079516/d8537f5a-7bad-4e51-8e16-b197fc0b823c)
![image](https://github.com/opencv/cvat/assets/46079516/c69ab792-e7ea-49d5-b775-e8bac5a61d23)

Also, does CVAT.ai run SAM on the GPU or CPU? We are considering purchasing the Cloud Pro version for our organisation.

Thank you, Sam

**Comment by bsekachev** [comment]
@davodogster 

CVAT.ai runs SAM on GPU.

**Comment by davodogster** [comment]
Thanks! @bsekachev and do you know why SAM doesn't segment the pixels along the border of the image? Sometimes it misses the top/bottom borders and other times the left/right as shown in the images above.

**Comment by davodogster** [comment]
@bsekachev Thanks!!
