### ISSUE TITLE
Unable to access localhost with localIP and PublicIP in AWS EC2

### ISSUE THREAD

**Issue by tejan74** [opencv/cvat#6253]
### My actions before raising this issue
- [ searched] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ issues] Searched [past issues](/issues)

Unable to access localhost with localIP and PublicIP in AWS EC2

root@ip-172-31-15-48:/home/ubuntu/cvat# curl localhost:8080
<!doctype html><html lang="en"><head><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="ie=edge"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="description" content="Computer Vision Annotation Tool (CVAT) is a free, open source, web-based image and video annotation tool which is used for labeling data for computer vision algorithms. CVAT supports the primary tasks of supervised machine learning: object detection, image classification, and image segmentation. CVAT allows users to annotate data for each of these cases"/><meta name="”robots”" content="index, follow"/><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,400;8..144,500;8..144,600;8..144,700;8..144,800&family=Sora&display=swap" rel="stylesheet"></head><title>Computer Vision Annotation Tool</title><body><div id="root"></div><div id="layout-grid"></div><script defer="defer" src="/assets/cvat-ui.c4fe86113f7f9b5a7ab1.min.js"></script><script defer="defer" src="/assets/plugin_0.dfac7d6985992cbdb922.min.js"></script></body></html>root@ip-172-31-15-48:/home/ubuntu/cvat# 
root@ip-172-31-15-48:/home/ubuntu/cvat# 
root@ip-172-31-15-48:/home/ubuntu/cvat# curl 172.31.15.48:8080
404 page not found
root@ip-172-31-15-48:/home/ubuntu/cvat# 

we checked configuration in AWS with other web application it works fine but cvat needs code changes i guess, please provide your inputs to expose localhost to public ip in EC2

### Expected Behaviour
it is expected to access with local IP if application run in localhost like other webservers.

### Current Behaviour
getting 404 page not found error in EC2.

### Possible Solution
CVAT_HOST with localIP is working but without export it must run in localIP by default.

 
![Screenshot 2023-06-06 222942](https://github.com/opencv/cvat/assets/23494498/4b054e77-25ea-4a96-add2-f78285a03ff7)

**Comment by azhavoro** [comment]
https://opencv.github.io/cvat/docs/faq/#how-to-specify-multiple-hostnames
