### ISSUE TITLE
Integrate custom model (yolov8)

### ISSUE THREAD

**Issue by kurkurzz** [opencv/cvat#6257]
CVAT allow model integration out of the box. However, those models only suitable for general use cases. I have a custom model (in my case is yolov8) that I want to integrate into CVAT. Is there any resource/documentation on how to do that. Appreciate it.

**Comment by bsekachev** [comment]
Some piece of information can be found here:
https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models

**Comment by Natriumpikant** [comment]
For other people how state the same issue:
@kurkurzz solved this integration. 
https://github.com/kurkurzz/custom-yolov8-auto-annotation-cvat-blueprint

**Comment by BeanBagKing** [comment]
I hate docker so much, there's a reason I paid for cloud hosting. I wish we could upload our own custom models. That would make things so much easier.
