### ISSUE TITLE
Windows 10 (with WSL) deploy models to CVAT

### ISSUE THREAD

**Issue by Petros626** [opencv/cvat#6260]
Hey,

I followed this guide to install CVAT for Windows 10 (https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/) and after that unfortunately it's not possible for me to see the deployed models on the UI. At the same time I also followed this video here (https://www.youtube.com/watch?v=uKMKM5o5vUw).

Steps to reproduce:

1. open http://localhost:8070
2. create example project
3. new function 
4. import `.yaml` file from `cvat/serverless`
5. copy in source code the code from `main.py` (sometimes available, sometimes not- then i copied from github)
6. deploy
7. open http://localhost:8080 <-- under models you can see anything

Sometimes the `.yaml` file wasn't correct formatted, so I choosed a online YAML Formatter and to be sure a Python formatter, depending on the specific Python version, BUT as you can see some models, are created without any error and other not. The really funny thing is, however, that no models are displayed at all.

![image](https://github.com/opencv/cvat/assets/62354721/d50f0c65-e8e6-45d4-a22d-4d9b950c7bca)

![image](https://github.com/opencv/cvat/assets/62354721/ab9f8fb8-a382-4989-b5c4-69855cf7005b)

Thanks in advance, pls enlighten me and others

**Comment by bsekachev** [comment]
> create example project

Project name must be ``cvat``

**Comment by Petros626** [comment]
You mean in nuclio or cvat itself?

**Comment by Petros626** [comment]
@bsekachev from where can you get this information? I'll try and tell if it helped.

**Comment by Petros626** [comment]
Oh I overlooked that, but never thought it's important

**Comment by bsekachev** [comment]
I hope you solved the issue. I will close it.

**Comment by Petros626** [comment]
> I hope you solved the issue. I will close it.

In case the status `unhealthy` influecne the use of one of these models I'll reopen this issue.

**Comment by Petros626** [comment]
@bsekachev can't reopen the issue. Unfortunately with the guide, I end up every time in the unhealthy status of the specific models I deployed.
