### ISSUE TITLE
Missing SEMI-AUTO source of annotation

### ISSUE THREAD

**Issue by pktiuk** [opencv/cvat#6261]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation) 
    [Docs mentioning semi-auto](https://opencv.github.io/cvat/docs/manual/basics/settings/)
- [x] Searched [past issues](/issues)

According to [docs](https://opencv.github.io/cvat/docs/manual/basics/settings/) there are 3 sources of annotation

> Source- source of creating of objects MANUAL, AUTO or SEMI-AUTO.

But case of SEMI-AUTO is not handled anywhere in CVAT UI (or in source code).

### Steps to Reproduce (for bugs)

1. Create annotation with semi-auto source
   - either export annotations.xml with source 
```xml
<track id="0" label="mbt" source="semi-auto">
```
   - Use cvat SDK
```python
LabeledShapeRequest(type=ShapeType("mask"),

                                                  occluded=bool(int(obj["occluded"])),
                                                  source="semi-auto",
                                                  outside=False,
                                                  z_order=0,
                                                  rotation=0.0,
                                                  label_id=mappings_project_labels[obj["label"]],
                                                  points=obj["rle"] + [obj["xtl"], obj["ytl"], obj["xbr"] - 1, obj["ybr"] - 1],
                                                  frame=frame_id))
```
2. See it in CVAT ui

### Expected Behaviour

Visible source should be `SEMI-AUTO`

### Current Behaviour

It shows `MANUAL`

### Possible Solution

Implement handling it.

### Your Environment

CVAT 2.4.5

**Comment by bsekachev** [comment]
@pktiuk 

I think it is a documentation issue. We never have something like "semi-auto" in CVAT.

**Comment by pktiuk** [comment]
@bsekachev    

But I think this `semi-auto` may be very useful. Especially in case of annotating with SAM

**Comment by bsekachev** [comment]
You are always welcome to implement that
