### ISSUE TITLE
How do I achieve that the annotator does not have permission to download the dataset？

### ISSUE THREAD

**Issue by zhicai-liu** [opencv/cvat#6262]
Until now, annotators can download the job assigned to them. But I don't want them to download any data.

**Comment by zhicai-liu** [comment]
> @zhicai-liu
> 
> Modify `cvat/apps/iam/rules/jobs.rego` corresponding way, defining new rules for `EXPORT_DATASET` and `EXPORT_ANNOTATIONS` actions. Then rebuild CVAT from source files.

@bsekachev I can understand what you mean, but I'm sorry that I don't know how to modify it specifically. Could you please tell me what it should be changed into, or give me a specific modification tutorial.

**Comment by zhicai-liu** [comment]
> For example out of an organization, instead of:
> 
> ```
> allow {
>     { utils.VIEW, utils.EXPORT_DATASET, utils.EXPORT_ANNOTATIONS, utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_METADATA, utils.VIEW_COMMITS }[input.scope]
>     utils.is_sandbox
>     is_job_staff
> }
> ```
> 
> should be something like:
> 
> ```
> allow {
>     { utils.EXPORT_DATASET, utils.EXPORT_ANNOTATIONS }[input.scope]
>     utils.is_sandbox
>     is_task_staff
> }
> 
> allow {
>     { utils.VIEW, utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_METADATA, utils.VIEW_COMMITS }[input.scope]
>     utils.is_sandbox
>     is_job_staff
> }
> ```

How do I modify it if the worker/annotator is in an organization？

**Comment by bsekachev** [comment]
Sorry, I can't provide exact code. I will close the issue.
