### ISSUE TITLE
[Idea] Mask track for CVAT

### ISSUE THREAD

**Issue by astkwcz** [opencv/cvat#6264]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

During partial updating of annotations (api_client.tasks_api.partial_update_annotations) I have an issue with updating PatchedLabeledDataRequest for tracks for a mask ShapeType. (PatchedLabeledDataReques -> LabeledTrackRequest -> TrackedShapeRequest)
https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/tasks-api/#partial_update_annotations

When I do it through python cvat_sdk, it is updated, but when I go to CVAT IU, I get a message that job (task) is broken due to not allowed ShapeType for a mask and I also cannot download any data thought UI.

While looking in CVAT UI for which ShapeType is allowed to create tracks it is almost all of them i.e.: rectangle, polygon polyline, points, ellipse, cuboid, skeleton, but not a mask (a pictures below shows what I mean)
![cvat-mask](https://github.com/opencv/cvat/assets/135839164/2c31fe56-178c-48b7-9905-0cff18b34e1a)

![cvat-rectangle](https://github.com/opencv/cvat/assets/135839164/dbfece42-a676-4b8b-addc-dc81ef189392)

Will track label for mask will be implemented in the future like all of others shape types?

**Comment by bsekachev** [comment]
@astkwcz 

Tracked masks are not supported at all. But you can work with tracked masks if they are represented as polygons. 
Probably there are some bugs on the server if it allows to put tracked masks.
