### ISSUE TITLE
How to associate tracking tags of adjacent jobs when I use overlap between jobs

### ISSUE THREAD

**Issue by 2033329616** [opencv/cvat#6268]
I need to make some tracking labels, if there are too many frames in one job, cvat will be slower, some I split it into many jobs with overlap size 3, but I can't  associate tracking tags of adjacent jobs,

**Comment by bsekachev** [comment]
What do you mean speaking "tracking tags". Tags cannot be tracked on CVAT.

**Comment by 2033329616** [comment]
Sorry I use the uncorrect word, here I mean tracking id between jobs

**Comment by bsekachev** [comment]
When you export a whole task, tracks between neighbors jobs will be merged automatically using IoU metrics on overlapped frames.

**Comment by johnnynunez** [comment]
> When you export a whole task, tracks between neighbors jobs will be merged automatically using IoU metrics on overlapped frames.

and if you track in the same video? I'm fixing annotations with semi automatic labelling
<img width="289" alt="Screenshot 2024-06-05 at 08 44 04" src="https://github.com/cvat-ai/cvat/assets/22727137/fda5d579-4596-442b-ba67-62bc7b68a08e">
