### ISSUE TITLE
pretags laod

### ISSUE THREAD

**Issue by rogercomeon** [opencv/cvat#6269]
Annotations that I export in Cityscapes 1.0 format using cavat.ai can't be imported using the Upload annotations option.
I do the task of image semantic segmentation. I have tried to import annotations in other formats, such as CVAT for images 1.1 and Segmentation mask 1.1.

In addition, I have a problem that I am doing semantic Segmentation tasks, but I find that the exported annotations have instance segmentation tags, such as Segmentation mask 1.1 and PASCAL VOC 1.1.But I don't need these labels. But when I remove SegmentationObject from Segmentation mask 1.1 and PASCAL VOC 1.1, the load annotations are not available, but I don't need the SegmentationObject folder. Error: Request failed with status code 400. "Image 000001: Error: Request failed with Status code 400. "Image 000001: can't import annotation #14 (polygon): Label 'background' is not registered for this task\n".. May I ask how to solve this? I don't see the solution in the document.

Has anyone encountered this problem? Thank you very much for your answer.My requirement is to import pretags (semantically segmented labels inferred from other models) into cvat.ai.

**Comment by rogercomeon** [comment]
This is the  Cityscapes 1.0 format wrong warning:
Could not upload annotation for the [task 193710](https://app.cvat.ai/tasks/193710)Error: Request failed with status code 400. "The annotations that were uploaded are not correct"
And if I do not change dataset formats. In fact, there is a lot of information that I don’t need. For example, I don’t need instance segmentation labels for semantic segmentation tasks, but for Segmentation mask 1.1 and PASCAL VOC 1.1, if I don’t have instance segmentation labels, I can’t import them into cvat. This is It seems a bit useless.

**Comment by bsekachev** [comment]
>  In fact, there is a lot of information that I don’t need

But CVAT needs.

**Comment by rogercomeon** [comment]
> > In fact, there is a lot of information that I don’t need
> 
> But CVAT needs.

In this case, how should I pre-label, I want to use some models for global pre-labeling and then fine-tune to improve labeling efficiency.

**Comment by bsekachev** [comment]
You can use any format CVAT supports (there are more formats supporting masks), but please, do not modify them.
