### ISSUE TITLE
DEXTR responses huge, server slow - not configured with compression

### ISSUE THREAD

**Issue by kwikwag** [opencv/cvat#6283]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. Setup CVAT with serverless component with DEXTR deployed on a remote computer over a slow network
1. Create a task and run DEXTR

### Expected Behaviour
Response should be quick once the calculation on the server side is complete.

### Current Behaviour
Since the coordinates and mask are encoded in JSON (🤦 PNG base64-encoded would have been advisable) the response is quite large (16MB) which is very slow on a remote connection e.g. to an AWS EC2 instance.

### Possible Solution
Apply the following patch (not sure all options are needed but this works!):

```patch
diff --git a/docker-compose.yml b/docker-compose.yml
index 5f0e5c89..fc6e9d64 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -52,6 +52,8 @@ services:
       - traefik.http.routers.cvat.rule=Host(`${CVAT_HOST:-localhost}`) &&
         PathPrefix(`/api/`, `/git/`, `/opencv/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)
       - traefik.http.routers.cvat.entrypoints=web
+      - traefik.http.routers.cvat.middlewares=test-compress
+      - traefik.http.middlewares.test-compress.compress=true
     volumes:
       - cvat_data:/home/django/data
       - cvat_keys:/home/django/keys
@@ -178,6 +180,8 @@ services:
       - traefik.http.services.cvat-ui.loadbalancer.server.port=80
       - traefik.http.routers.cvat-ui.rule=Host(`${CVAT_HOST:-localhost}`)
       - traefik.http.routers.cvat-ui.entrypoints=web
+      - traefik.http.routers.cvat-ui.middlewares=test-compress
+      - traefik.http.middlewares.test-compress.compress=true
     networks:
       - cvat

@@ -198,6 +202,7 @@ services:
     #   - traefik.http.routers.dashboard.entrypoints=dashboard
     #   - traefik.http.routers.dashboard.service=api@internal
     #   - traefik.http.routers.dashboard.rule=Host(`${CVAT_HOST:-localhost}`)
+      - traefik.http.middlewares.test-compress.compress=true
     ports:
       - 8080:8080
       - 8090:8090
```
### Context
It was painstaking to use DEXTR remotely.

### Your Environment
- Git hash commit (`git log -1`): 61470b621e0786a7977dbc131a84550a49524382 (HEAD, tag: v2.4.0)
- Docker version `docker version` (e.g. Docker 17.0.05): Docker Engine - Community  20.10.7
- Are you using Docker Swarm or Kubernetes? None of the above
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04.2 LTS
- Code example or link to GitHub repo or gist to reproduce problem: N/A
- Other diagnostic information / logs: N/A

**Comment by kwikwag** [comment]
Note that this causes some ZIP payloads to be re-compressed, which is a waste of CPU cycles, but not a big deal as far as I am concerned... This can easily be avoided by adding `traefik.http.middlewares.test-compress.compress.excludedcontenttypes=application/zip`. It can potentially alleviate the need to use Zip archives for data delivery in the first place...

**Comment by kwikwag** [comment]
Also note that once compressed, the 16MB payload above becomes 120KB.

**Comment by bsekachev** [comment]
@azhavoro 

Do you think we can add compression for lambda functions?

**Comment by azhavoro** [comment]
We have now enabled compression middleware that should work with these responses, @kwikwag could you try to use the latest release?
