### ISSUE TITLE
console stuck on 'Building docker image' when installing SAM CPU integration on self hosted CVAT

### ISSUE THREAD

**Issue by KanielDatz** [opencv/cvat#6284]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
- [ ]searched https://stackoverflow.com/questions/58600717/docker-gets-stuck-on-building-and-other-commands
- [x] reinstalling everything, following instructions [here](https://opencv.github.io/cvat/docs/administration/basics/installation/#windows-10) and [here](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/) and [here](https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat)

-- also tried downgrading Nuclio to 1.11.19  > but same problem happens

### Steps to Reproduce (for bugs)

1. installed CVAT on windows 11 following instructions
2. installed Nuclio 1.8.14
3. console got stuck when running the instructions for installing SAM for CPU

### Current Behaviour

console is stuck on 

23.06.11 15:31:39.755            nuctl.platform (I) Building docker image {"image": "cvat.pth.facebookresearch.sam.vit_h:latest"}

<img width="671" alt="Screenshot 2023-06-11 154817" src="https://github.com/opencv/cvat/assets/93449840/cba88f11-0cc7-437e-82a4-921db6f20090">

How much time should it take? maybe I'm not waiting enough? waited about 30 min.

### Your Environment

- Docker version : 4.20.1
- Operating System and version (e.g. Linux, Windows, MacOS): win11 with WSL2 running Ubunto
- Other diagnostic information / logs:

snapshot from  Nuclio:
<img width="374" alt="Screenshot 2023-06-11 155231" src="https://github.com/opencv/cvat/assets/93449840/b8c42eaa-4470-41f1-8b53-7cf55381c0c3">

snap from docker (there is no image for SAM):
<img width="592" alt="image" src="https://github.com/opencv/cvat/assets/93449840/88447c82-d6d7-42f2-9a31-083e65163743">

when opening CVAT I see and can use the SAM tool but this error pops up when waiting for the mask:
![7e5d5573-4422-4f97-b498-619227e3d825](https://github.com/opencv/cvat/assets/93449840/7173dc81-10df-4430-8053-c008da72044e)

**Comment by descilla** [comment]
It mainly depends on your internet connection and the load of the SAM-Download-Servers. To build the docker image the ``vit_b`` checkpoint is downloaded which is 2,4GB in size. This sometimes takes a while.

**Comment by KanielDatz** [comment]
works!
I just had a terrible network.
Thanks a lot!

remember to run 
`docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
`
otherwise the magic wand symbol won't come up.
