### ISSUE TITLE
Interaction error occurred using SAM

### ISSUE THREAD

**Issue by aligh97** [opencv/cvat#6285]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. followed this [guide](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/) to install CVAT
2. deployed SAM using this command: `cd serverless && ./deploy_cpu.sh pytorch/facebookresearch/sam/nuclio/`

### Expected Behaviour

I expected that use SAM properly.
### Current Behaviour

after I go to `localhost:8080` and try to annotate my images with Segment Anything after this message `Waiting a response from Segment Anything..` I get this error:

![photo_2023-06-11_17-15-35](https://github.com/opencv/cvat/assets/66427191/c5c458ca-296d-4fb8-8743-60d4da92cb21)

### Context

I'm trying to annotate my images using SAM. I installed CVAT and deploy SAM using docker and it worked without any error. when I started to annotate I got that error and have no clue what to do.

### Your Environment

- Ubuntu 20.04 and the latest version of Google Chrome.
- Docker version: Docker Desktop 4.19.0

**Comment by descilla** [comment]
Do you have checked the logs of the SAM serverless function container?
Use the following command to do so: ``docker logs nuclio-nuclio-pth-facebookresearch-sam-vit-h``

**Comment by davodogster** [comment]
@descilla @aligh97 We are also receiving this error on our self hosted GPU Ubuntu segment-anything model.

![image](https://github.com/opencv/cvat/assets/46079516/d0f277f4-cc23-4c53-986a-7da1c13f496a)

For some of our tasks the SAM interactor works fine, and some others it doesn't. Do you know why?

**Comment by aligh97** [comment]
@descilla this is the logs of the SAM serverless function container:

![photo_2023-06-12_09-24-44](https://github.com/opencv/cvat/assets/66427191/f626b6da-11b4-4d50-a6e4-33ba336dbf4f)

**Comment by bsekachev** [comment]
@aligh97 

Something killed your process with the model. Do you have enough RAM?

**Comment by aligh97** [comment]
@bsekachev 
I have 16GB RAM.
When I open docker and use CVAT, it uses 88% of my RAM.

**Comment by aligh97** [comment]
@bsekachev 
I have 16GB RAM.
When I open docker and use CVAT, it uses 88% of my RAM.

**Comment by bsekachev** [comment]
@aligh97 

``docker stats --no-stream``  ?

**Comment by aligh97** [comment]
for me:
```python
CONTAINER ID   NAME                                           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O   PIDS
605d9b8c99a1   nuclio-nuclio-pth-facebookresearch-sam-vit-h   185.49%   161.7MiB / 7.636GiB   2.07%     266B / 0B         0B / 0B     37
```

**Comment by bsekachev** [comment]
Docker has its own limits for RAM usage. As you can see it allows to use up to 7.6 GB. 
I suspect it is not enough when model is runned and docker kills the process.

Try to increase memory limits, modifying function.yaml according to this article: 
https://nuclio.io/docs/latest/reference/function-configuration/function-configuration-reference/

**Comment by bsekachev** [comment]
When SAM is running it show consumption up to 10 GB on my PC.

**Comment by aligh97** [comment]
oh, I see. then it's most likely the limits for RAM usage.
I will try to increase memory limits.

**Comment by davodogster** [comment]
@bsekachev @aligh97 Do you know which code or script I need to modify and run to increase the memory limits?
Thanks, Sam :)

**Comment by aligh97** [comment]
@bsekachev You need to create a `.wslconfig` file in your profile directory(open your File Explorer, and type and enter %UserProfile% to go to your profile directory in Windows.) and then add the following commands:
```python
[wsl2]
# Limits VM memory to use no more than 4 GB, this can be set as whole numbers using GB or MB
memory=12GB
```

You can see [this link](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconfig-file) and set your configurations.

**Comment by davodogster** [comment]
@aligh97 I'm using linux ubuntu

**Comment by aligh97** [comment]
I guess this command line sets the maximum RAM usage:
```python
sudo docker run -it --memory="[memory_limit]" [docker_image]
```
The value of memory_limit should be a positive integer followed by the suffix b, k, m, or g for example `--memory="12g"`

**Comment by yangchengxin** [comment]
![image](https://github.com/user-attachments/assets/9f73cb83-4461-419e-91f0-2bf9708ac6c8)
how can i fix this problem   I'm trying to annotate my images using yolov8 seg, please help me~
