### ISSUE TITLE
I exported a dataset in Coco kepoints format from CVAT, but an error occurred when I imported this zip file into another CVAT project at another address

### ISSUE THREAD

**Issue by liudaolunboluo** [opencv/cvat#6286]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I exported a dataset in Coco kepoints format from CVAT, but an error occurred when I imported this zip file into another CVAT project at another address，The two CVAT versions are consistent, both of which are 2.2.0，The error message is as follows：
"cvat.apps.dataset_manager.bindings.CvatImportError: Image cE9VSk9GWEo2Nkhv20230311: can't import annotation #0 (points): Label None is not registered for this task\n"

### Steps to Reproduce (for bugs)
1.Export dataset format as coco keypoints
2.Import annotation files on the project page, select Coco keypoints as the format
this is my export Annotation file Json:
```
{
    "licenses": [
        {
            "name": "",
            "id": 0,
            "url": ""
        }
    ],
    "info": {
        "contributor": "",
        "date_created": "",
        "description": "",
        "url": "",
        "version": "",
        "year": ""
    },
    "categories": [
        {
            "id": 1,
            "name": "points",
            "supercategory": "",
            "keypoints": [],
            "skeleton": []
        }
    ],
    "images": [
        {
            "id": 1,
            "width": 1080,
            "height": 685,
            "file_name": "cE9VSk9GWEo2Nkhv20230311.jpg",
            "license": 0,
            "flickr_url": "",
            "coco_url": "",
            "date_captured": 0
        },
        {
            "id": 2,
            "width": 445,
            "height": 594,
            "file_name": "cFcyYXRKbENVcUFB20230311.jpg",
            "license": 0,
            "flickr_url": "",
            "coco_url": "",
            "date_captured": 0
        }
    ],
    "annotations": [
        {
            "id": 1,
            "image_id": 1,
            "category_id": 1,
            "segmentation": [],
            "area": 696799.1436000001,
            "bbox": [
                6.53,
                13.68,
                1058.74,
                658.14
            ],
            "iscrowd": 0,
            "attributes": {
                "occluded": false
            },
            "keypoints": [
                8.91,
                16.07,
                2,
                1060.5,
                13.68,
                2,
                1065.27,
                671.82,
                2,
                6.53,
                667.05,
                2
            ],
            "num_keypoints": 4
        },
        {
            "id": 2,
            "image_id": 2,
            "category_id": 1,
            "segmentation": [],
            "area": 143065.97690000004,
            "bbox": [
                67.1,
                48.03,
                302.83,
                472.43
            ],
            "iscrowd": 0,
            "attributes": {
                "occluded": false
            },
            "keypoints": [
                67.1,
                48.03,
                2,
                369.93,
                66.96,
                2,
                352.45,
                517.55,
                2,
                69.29,
                520.46,
                2
            ],
            "num_keypoints": 4
        }
    ]
}
``` 

These are the labels created by my two projects：
```
[
  {
    "name": "points",
    "id": 152,
    "color": "#3464f3",
    "type": "any",
    "attributes": []
  }
]
```
### Expected Behaviour
Successfully imported the annotation file, generating a task that has already been annotated

### Current Behaviour
thorw excetion,erro:"cvat.apps.dataset_manager.bindings.CvatImportError: Image cE9VSk9GWEo2Nkhv20230311: can't import annotation #0 (points): Label None is not registered for this task\n"

### Possible Solution
version question?

If I remove annotations from JSON, I can succeed, but there is no annotation information

**Comment by yasakova-anastasia** [comment]
@liudaolunboluo, you have wrong annotations. Could you please provide categories from your project/task? Or could you please share a task/project backup? What annotations do you have? Skeletons or points?

**Comment by liudaolunboluo** [comment]
> @liudaolunboluo, you have wrong annotations. Could you please provide categories from your project/task? Or could you please share a task/project backup? What annotations do you have? Skeletons or points?

is points ,Raw :
```
[
  {
    "name": "points",
    "id": 151,
    "color": "#3464f3",
    "type": "any",
    "attributes": []
  }
]
```

**Comment by liudaolunboluo** [comment]
This is indeed a bug. The exported JSON in Coco keypoints format does not have the key 'label', but in the code bindings. py, 'self.'_ Get_ Label_ Id (_tag. pop ('label ')' but attempting to obtain this key resulted in an exception,plz fix it quickly

**Comment by realtimshady1** [comment]
do you get any issues if you try importing the zip into the same project/task?

**Comment by liudaolunboluo** [comment]
> do you get any issues if you try importing the zip into the same project/task?

yes,if format is coco keypoints,it will be thorw excetion,but if format is cvat images,it's ok

**Comment by liudaolunboluo** [comment]
hi,It has been two weeks now. Do you have a conclusion on this issue
