### ISSUE TITLE
Issue with Cache Paths After Moving Job Images to a New Directory 

### ISSUE THREAD

**Issue by filipmika** [opencv/cvat#6289]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Title
Issue with Cache Paths After Moving Job Images to a New Directory 

### Steps to Reproduce 
1. Mount a drive with job images for annotation.
1. Move job images into a new subdirectory on the mounted drive.
1. Manually change the paths in the PostgreSQL DB to reflect the new image location.
1. Manually delete tasks cache in docker container using  _docker exec -it cvat_server bash_
1. Restart the Docker container.

### Expected Behaviour
After manually changing the paths and restarting the Docker container, I expected the CVAT to load images from the new location.

### Current Behaviour
Upon opening a job, CVAT throws the error "Could not fetch frame data from the server". It seems like old job paths are still being loaded from cache, even after manually updating the paths and restarting the Docker container.

### Possible Solution
I am unsure of the specific cache file that needs to be deleted to ensure new paths take effect. Looking for guidance on this.

### Context
This issue prevents me from moving images to new directories on the mounted drive, as the old job paths seem to be persisting in cache even after updating them manually in the PostgreSQL DB and restarting the Docker container.

### Your Environment
- Git hash commit: 2c4676ace32a68572b38205f002a98e93af917d0
- Docker version: 24.0.1
- Are you using Docker Swarm or Kubernetes? [provide answer here]
- Operating System and version: Linux  Ubuntu 22.04.2

**Comment by bsekachev** [comment]
Hi, @filipmika 
We do not support such custom scenarious.
