### ISSUE TITLE
Cuboid is not placeable free (in main view) in a point cloud scene

### ISSUE THREAD

**Issue by DensoADAS** [opencv/cvat#6291]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

While creating a label, the cuboid is movable only on the coordinate system axis. Its not possible to move it elsewhere. Afterwards if the label is saved, its movable everywhere, but only in the "Top", "Side" and "Front" view.

https://github.com/opencv/cvat/assets/46967124/4a19f978-8ae2-40ed-a084-2e55b7b70dc9

### Steps to Reproduce (for bugs)
1. Install CVAT like described here: https://opencv.github.io/cvat/docs/administration/basics/installation/
2. Open CVAT with localhost:8080
3. Create a project
4. Upload PCD files
5. Create a job with labels
6. Label a cuboid

### Expected Behaviour
The expected behaviour is, while creating the label, the cuboid should be movable in the complete pointcloud.

### Current Behaviour
The cuboid is only moveable on the coordinate system axis, and no where else.

### Possible Solution
Place the cuboid in the mid, then after saving it, use "Top", "Side" and "Front" view to move the cuboid to the correct position in the pointcloud.

### Context
Annotation is way to slow if the free movable cuboid in main view is not available.

### Your Environment
- Git hash commit (`git log -1`): 5fa11c9eaefdfc2c3b35fb95646d53be67a5341a
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.2
- Are you using Docker Swarm or Kubernetes? Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04

Thank you very much.

**Comment by bsekachev** [comment]
Please, share this .pcd file
The issue might be related to #6288

**Comment by DensoADAS** [comment]
> Please, share this .pcd file The issue might be related to #6288

We removed the nan in our pcd files and now its working fine. 

Thank you for your support.
