### ISSUE TITLE
Model provider list is empty

### ISSUE THREAD

**Issue by alicelarsen** [opencv/cvat#6295]
### My actions before raising this issue
- [ +] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ +] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Models
2. Add a model
3. Model URL: https://universe.roboflow.com/roboflow-jvuqo/football-players-detection-3zvbc/model/2 
4. Provider: No data
5. Submit: Please, specify model provider

### Expected Behaviour
Not empty provider drop-down list while adding model from Roboflow

### Current Behaviour
Trying to add custom model from Roboflow but my provider drop-down list is empty. Same with Huggingface models. 
app.cvat.ai works well but couldn't be used because of data size limitations. 

### Your Environment

- Git hash commit (`git log -1`): cvat version: cvat-2.4.6
- Docker version `docker version` (e.g. Docker 17.0.05): 23.0.6
- Are you using Docker Swarm or Kubernetes? Docker Swarm
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem: 
- Other diagnostic information / logs:
Please, specify model provider

**Comment by priyanshum-cashify** [comment]
I m also facing the same issue, model provider dropdown list is empty

**Comment by priyanshum-cashify** [comment]
> I m also facing the same issue, model provider dropdown list is empty

is it a paid feature:  **https://github.com/opencv/cvat/issues/6057**
