### ISSUE TITLE
Error: Could not create the task Error: Could not create the task on the server. Non public IP address 'xxx.xxx.xxx.xxx' is provided!.

### ISSUE THREAD

**Issue by caigang5280** [opencv/cvat#6303]
When I was creating a task, I entered Remote sources
It is an image URL deployed on an internal server, and the following error may occur:

Error: Could not create the task Error: Could not create the task on the server. Non public IP address 'xxx.xxx.xxx.xxx' is provided!.

How to solve it!!

**Comment by bsekachev** [comment]
Provided IP address can not be accessed from CVAT.
What is a problem?

**Comment by caigang5280** [comment]
I have deployed CVAT service and file storage service mini on a private internal server.

When creating a task, upload the image address stored on the file storage mini (setting all permissions on the bucket to be public),

Step: 'task' - 'Select files' Select the' Remote sources' method.

I ended up with an error:
Error: Could not create the task Error: Could not create the task on the server. Non public IP address 'xxx.xxx.xxx.xxx' is provided!.


> Provided IP address can not be accessed from CVAT. What is a problem?

**Comment by caigang5280** [comment]
> This is because CVAT does not see your **private internal server**. Probably they are in different networks.

I have checked their network and it is possible to ping them. I've been trying for a long time

Is there any other reason?

**Comment by bsekachev** [comment]
Try to ping it from the inside the container, not from the host.

**Comment by caigang5280** [comment]
> Try to ping it from the inside the container, not from the host.

I just tried, and inside the Docker container **cvat-server** , I can ping to the image server, while the **curl** command can retrieve the file binary.

Where else do you think I should check for errors?

**Comment by caigang5280** [comment]
> Try to ping it from the inside the container, not from the host.

**Console info:**

cvat_worker_default     | 2023-06-13 13:39:01,903 DEBG 'rqworker_default_0' stderr output:
cvat_worker_default     | [2023-06-13 13:39:01,902] INFO cvat.server: create task #125
cvat_worker_default     | 
cvat_worker_default     | 2023-06-13 13:39:01,903 DEBG 'rqworker_default_0' stderr output:
cvat_worker_default     | INFO:cvat.server:create task #125
cvat_worker_default     | 
cvat_worker_default     | 2023-06-13 13:39:01,905 DEBG 'rqworker_default_0' stderr output:
cvat_worker_default     | DEBUG:rq.worker:Handling failed execution of job /api/tasks/125
cvat_worker_default     | 
cvat_worker_default     | 2023-06-13 13:39:01,906 DEBG 'rqworker_default_0' stderr output:
cvat_worker_default     | ERROR:rq.worker:Traceback (most recent call last):
cvat_worker_default     |   File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
cvat_worker_default     |     rv = job.perform()
cvat_worker_default     |   File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
cvat_worker_default     |     self._result = self._execute()
cvat_worker_default     |   File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
cvat_worker_default     |     return self.func(*self.args, **self.kwargs)
cvat_worker_default     |   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
cvat_worker_default     |     return func(*args, **kwds)
cvat_worker_default     |   File "/home/django/cvat/apps/engine/task.py", line 310, in _create_thread
cvat_worker_default     |     data['remote_files'] = _download_data(data['remote_files'], upload_dir)
cvat_worker_default     |   File "/home/django/cvat/apps/engine/task.py", line 277, in _download_data
cvat_worker_default     |     _validate_url(url)
cvat_worker_default     |   File "/home/django/cvat/apps/engine/task.py", line 245, in _validate_url
cvat_worker_default     |     _validate_ip_address(ip_address)
cvat_worker_default     |   File "/home/django/cvat/apps/engine/task.py", line 234, in _validate_ip_address
cvat_worker_default     |     raise ValidationError('Non public IP address \'{}\' is provided!'.format(ip_address))
cvat_worker_default     | rest_framework.exceptions.ValidationError: [ErrorDetail(string="Non public IP address '192.168.8.191' is provided!", code='invalid')]
cvat_worker_default     | Traceback (most recent call last):
cvat_worker_default     |   File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
cvat_worker_default     |     rv = job.perform()
cvat_worker_default     |   File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
cvat_worker_default     |     self._result = self._execute()
cvat_worker_default     |   File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
cvat_worker_default     |     return self.func(*self.args, **self.kwargs)
cvat_worker_default     |   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
cvat_worker_default     |     return func(*args, **kwds)
cvat_worker_default     |   File "/home/django/cvat/apps/engine/task.py", line 310, in _create_thread
cvat_worker_default     |     data['remote_files'] = _download_data(data['remote_files'], upload_dir)
cvat_worker_default     |   File "/home/django/cvat/apps/engine/task.py", line 277, in _download_data
cvat_worker_default     |     _validate_url(url)
cvat_worker_default     |   File "/home/django/cvat/apps/engine/task.py", line 245, in _validate_url
cvat_worker_default     |     _validate_ip_address(ip_address)
cvat_worker_default     |   File "/home/django/cvat/apps/engine/task.py", line 234, in _validate_ip_address
cvat_worker_default     |     raise ValidationError('Non public IP address \'{}\' is provided!'.format(ip_address))
cvat_worker_default     | rest_framework.exceptions.ValidationError: [ErrorDetail(string="Non public IP address '192.168.8.191' is provided!", code='invalid')]

**Comment by caigang5280** [comment]
> Try to ping it from the inside the container, not from the host.

browser console:
![image](https://github.com/opencv/cvat/assets/95113564/08e799e1-a492-40a3-97d2-10e424dc6c14)

error message:
![image](https://github.com/opencv/cvat/assets/95113564/7b7ef177-0981-4f4b-9642-016f294a8d9f)

**Comment by azhavoro** [comment]
We explicitly filter non-global IP addresses for security reasons [here] (https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/task.py#L350), currently the only way to fix this is to change the source code and rebuild the image. It is probably reasonable to have settings to allow/deny non-global addresses, but this is definitely not a priority, perhaps the community is interested in implementing such setting.

**Comment by caigang5280** [comment]
> We explicitly filter non-global IP addresses for security reasons [here](https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/task.py#L350), currently the only way to fix this is to change the source code and rebuild the image. It is probably reasonable to have settings to allow/deny non-global addresses, but this is definitely not a priority, perhaps the community is interested in implementing such setting.

Thank you. I would like to confirm if there is only one way to modify the source code, and is there any other feasible way to complete it

**Comment by azhavoro** [comment]
> currently the only way to fix this is to change the source code and rebuild the image.

**Comment by caigang5280** [comment]
Resolved, thank you!
