### ISSUE TITLE
Could not upload annotation

### ISSUE THREAD

**Issue by aligh97** [opencv/cvat#6304]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Created a project and upload images locally 
1. Uploaded COCO annotations `.json` using [this guide](https://opencv.github.io/cvat/docs/manual/advanced/export-import-datasets/) 

### Expected Behaviour

I expected that the annotations upload and create masks
### Current Behaviour

When I upload `annotation.json` I get this error:

![photo_2023-06-13_14-03-19](https://github.com/opencv/cvat/assets/66427191/e84c9e96-ba5e-4695-a5d2-661a9b64e803)

![photo_2023-06-13_14-03-25](https://github.com/opencv/cvat/assets/66427191/15113637-cfd9-422c-b6c9-f5afe716f86d)

how can I upload annotated data to CVAT?

**Comment by bsekachev** [comment]
``docker logs cvat_server``?

**Comment by bsekachev** [comment]
@aligh97 

Check your annotations file to correspond the specification. 
Stacktrace says:

```
cvat.apps.dataset_manager.bindings.CvatImportError: 
Image 325993751_557047063027508_8450010938490438274_nH4GU0RW9AJG39POKEFGZ_39e3: can't import annotation #1 (polygon): annotation has no label
```

**Comment by bsekachev** [comment]
@aligh97 Does CVAT task contains these categories in labels specification?

**Comment by bsekachev** [comment]
@zhiltsov-max  Maybe you have an idea?

**Comment by aligh97** [comment]
I solved it.
When I create a new task with different labels, CVAT gives them id like 21, 22, ...(that's because the last label category id from the last task we created is 20). if we assign these label ids to our category ids in `annotation.json`, it will upload properly.

**Comment by zhiltsov-max** [comment]
> I get that error again.
> this is the content of annotation.json:

```
...
"categories": [
        {
            "id": 0,
            "name": "COAT"
        },
...
"id": 5,
"image_id": 2,
"category_id": 0,
```

The reason is probably that the category ids are starting from 0 in the annotation file. CVAT follows the original format and expects category ids starting from 1. As a simple workaround, I can suggest changing the category id to some other positive number in the category definitions and in the following annotations.

**Comment by aligh97** [comment]
@zhiltsov-max
Yes. I changed the category ids in the annotation file and it worked. thanks.

**Comment by xieyimin** [comment]
@zhiltsov-max 我的错误是 "can't import annotation #0 (bbox): annotation has no label"，根据你的提示最终解决了问题，谢谢！
