### ISSUE TITLE
Unsupported media type \"application/x-www-form-urlencoded\" in request

### ISSUE THREAD

**Issue by jv1522** [opencv/cvat#6311]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have deployed CVAT UI and the CVAT Server as two different instances. The UI was built and deployed using nginx. However, I could see HTTP 415 from cvat server as it was unable to parse application/x-www-form-urlencoded request.

Is there any one who faced similaar issue?
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi, could you please be more specific about how the problem occurs and how it can be reproduced? Did you build and send any server requests manually? I don't think cvat server supports such media type.

**Comment by bsekachev** [comment]
Issue template was not filled.
