### ISSUE TITLE
Unable to adopt SSO with the method on the doc. Does the documentation needs to be update?

### ISSUE THREAD

**Issue by anitahuang121** [opencv/cvat#6312]
### My actions before raising this issue
- [x] Read/searched [the docs][(https://github.com/cvat-ai/cvat/tree/master#documentation](https://opencv.github.io/cvat/docs/enterprise/social-accounts-configuration/#enable-authentication-with-a-google-account))
- [x] Tried the method above
- [x] Lookup the API documents(https://app.cvat.ai/api/docs/)

### Steps to Reproduce (for bugs)

1.Add auth_config.yml:
```
---
social_account:
  enabled: true
  google:
    client_id: <some_client_id>
    client_secret: <some_client_secret>
```
2. add env AUTH_CONFIG_PATH="<path_to_auth_config> in docker-compose.yaml
3. docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.override.yml up -d --build

But the google social login doesn't shows in UI and doesn't work

### Possible Solution
If I do something wrong? or the doc should be update
CVAT website has this API(https://app.cvat.ai/api/auth/social), but I cannot find it in CVAT:v2.4.6, which version is the app.cvat.ai uses?

### Context
I wonder how to adopt SSO login

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes? docker
- Operating System and version (e.g. Linux, Windows, MacOS): linux
- Code example or link to GitHub repo or gist to reproduce problem: cvat:v2.4.6
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Hi @anitahuang121 

This is not open-source plugin.

**Comment by anitahuang121** [comment]
@bsekachev Hi, I wonder that if I modify yaml, I can deploy it with social auth? (because I can adopt google allauth in cvat:v2.3.0)
Or if This function is Charged in v2.4.6? thanks.

**Comment by bsekachev** [comment]
I do not think actually you can do it, because we never open sourced backend code for social authorization.
In 2.3.0 you can only find some pieces of frontend code.

**Comment by bsekachev** [comment]
You can try, but we do not support previous releases and I have no idea what steps should be done.
