### ISSUE TITLE
No more options for review

### ISSUE THREAD

**Issue by ASAADASKAR** [opencv/cvat#6316]
In Review, when I click on "Open an issue", I don't get options like quick issue -> wron label. 

does anyone know how i can keep the options displayed?

**Comment by bsekachev** [comment]
Quick issue is available when you do right click an object in review mode:

<img width="425" alt="image" src="https://github.com/opencv/cvat/assets/40690378/076c6d57-c26c-48ac-803b-ef6a32ca7757">
