### ISSUE TITLE
File upload limits in cvat.ai

### ISSUE THREAD

**Issue by iameira** [opencv/cvat#6318]
### My actions before raising this issue
- [ +] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ +] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. 
1.
1.
1.

### Current Behaviour

Hi CVAT team! 
I have paid version of cvat.ai and self-hosted docker with CVAT as well. Due to necessity of huge amounts of data annotation I very need an ability to integrate custom model from Roboflow. Self-hosted version doesn't allow it because it's paid feature. Ok, my solution is online version. 
But current implementation of CVAT has a lot of limits. It's 500 files for cloud storage and ~500MB for uploading from computer. If I understood correctly connected file share it's feature only for self-hosted CVAT. Could you give me some advice how to be with these limits or how to add Roboflow integration to the self-hosted version (maybe login from my paid account)?
I look forward to your reply. 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
@kirill-sizov 

Could you please answer?

**Comment by kirill-sizov** [comment]
Hi, @iameira

About limits: [we already removed](https://github.com/opencv/cvat/pull/6292) the limit of the number of files for uploading data from cloud storage, so stay tuned, we will make a release in the nearest future.

About the custom model: you can upload your custom model in Roboflow and then use it in CVAT via our integration with Roboflow, [the link may help you](https://www.cvat.ai/post/annotation-with-roboflow).

**Comment by iameira** [comment]
Thank you so much, I'm looking forward to this release!
