### ISSUE TITLE
Cannot import annotations for image path with dot

### ISSUE THREAD

**Issue by yf-yang** [opencv/cvat#6319]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Trying to upload annotations for IMAGE task in Pascal VOC format, following [this doc](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-voc/#pascal-voc-import). When the image's name is normal (example.jpg), it works as expected. When the image contains additional dot (example.rgb.jpg), annotations could not be uploaded successfully.

### Steps to Reproduce (for bugs)
1. Suppose I have an image in the task, called `prefix/100114004_186_44624.rgb.jpg`
2. create a file `100114004_186_44624.rgb.xml`
3. inside the xml file, specify the filename tag as
``` xml
<annotation>
<filename>prefix/100114004_186_44624.rgb.jpg</filename>
</annotation>
```
4. make a zip file, upload it
5. CVAT complains `Request failed with status code 400. "Could not match item id: '100114004_186_44624.rgb' with any task frame\n"`
6. Changing file name to `100114004_186_44624.xml` does not help
7. For images with only one dot (the one before jpg suffix), everything works

### Expected Behaviour
For images with additional dot, I can upload annotations

### Current Behaviour
Described above.

### Possible Solution
Maybe check how you match annotation file with images?

**Comment by bsekachev** [comment]
@zhiltsov-max Can you look into the issue?

**Comment by yf-yang** [comment]
Guys, did you find anything? 👀
