### ISSUE TITLE
Cannot connect to external PostgreSQL which has SSL enabled

### ISSUE THREAD

**Issue by rychuhardy** [opencv/cvat#6323]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Right now it is not possible to configure cvat to connect to external PostgreSQL server which requires SSL. You can only set the following variables to configure connection to postgres
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('CVAT_POSTGRES_HOST', 'cvat_db'),
        'NAME': os.getenv('CVAT_POSTGRES_DBNAME', 'cvat'),
        'USER': os.getenv('CVAT_POSTGRES_USER', 'root'),
        'PASSWORD': os.getenv('CVAT_POSTGRES_PASSWORD', ''),
        'PORT': os.getenv('CVAT_POSTGRES_PORT', 5432),
    }
}
```

### Possible Solution

Add another variable CVAT_POSTGRES_SSL_MODE to the configuration
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('CVAT_POSTGRES_HOST', 'cvat_db'),
        'NAME': os.getenv('CVAT_POSTGRES_DBNAME', 'cvat'),
        'USER': os.getenv('CVAT_POSTGRES_USER', 'root'),
        'PASSWORD': os.getenv('CVAT_POSTGRES_PASSWORD', ''),
        'PORT': os.getenv('CVAT_POSTGRES_PORT', 5432),
        'OPTIONS': {'sslmode': os.getenv('CVAT_POSTGRES_SSL_MODE', 'disable')},
    }
}
```

### Context

I'm trying to connect to an external PostgreSQL database which requires SSL.

**Comment by bsekachev** [comment]
Hi @rychuhardy 

You can configure your self-hosted CVAT as you want. 
We do not have requirements on SSL encrypted Postgres server.

**Comment by rychuhardy** [comment]
I can't configure CVAT to use SSL with postgres unless I make changes to the source code or build the CVAT docker image myself, which is something I want to avoid. There's no way to configure it e.g. via helm chart. This issue is to add such possibility.

**Comment by bsekachev** [comment]
In this case, please update the issue template according to this.
There was not anything about helm.

**Comment by rychuhardy** [comment]
Well, helm was just an example. If I want to run CVAT in docker I have the same problem - I can't connect to PostgreSQL with SSL. Adding this variable CVAT_POSTGRES_SSL_MODE solves the problem for both helm and docker.

**Comment by azhavoro** [comment]
@rychuhardy Could you please prepare a PR?

**Comment by rychuhardy** [comment]
Sure, I can try

**Comment by SpecLad** [comment]
As I noted in the linked pull request, it is already possible to set these settings via the [libpq environment variables](https://www.postgresql.org/docs/current/libpq-envars.html). Given this, I don't think there's anything we need to do here.

I'd also like to note that the default `sslmode` is `prefer`, so it shouldn't be necessary to touch these settings to use SSL unless you want to enable a more stringent mode.
