### ISSUE TITLE
skeleton editing: right click context menu position wrong in Firefox

### ISSUE THREAD

**Issue by smidm** [opencv/cvat#6330]
### My actions before raising this issue

- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. setup new skeleton 
1. right click on a keypoint

### Expected Behaviour

The context menu appears right below the pointer.

### Current Behaviour

The context menu appears on correct position in Chrome, but on very top left of the canvas in Firefox. The position seems to be scaled down keypoint coordinates in Firefox.

![Firefox](https://github.com/opencv/cvat/assets/820292/06427a35-c5c9-4782-b061-c31ce503506d)
Firefox above

![Chromium](https://github.com/opencv/cvat/assets/820292/126cf334-aa4d-43c8-bb37-d7363fd17f60)
Chromium above

### Context

This issue affects configuration of multiple keypoints in Firefox. The selected keypoint is not fixed while is the contex menu displayed. When moving mouse cursor to the off-positioned menu a different keypoint is often selected (which is probably a bug by itself).

### Your Environment

- affects https://app.cvat.ai/
- Firefox 114 on Fedora Linux 38

**Comment by bsekachev** [comment]
@smidm

I will keep the issue, but Firefox is not supported well. 
Better to use any Chrome-based browser.
