### ISSUE TITLE
Cant create Account 

### ISSUE THREAD

**Issue by ConteXCrown** [opencv/cvat#6331]
Error when trying to register on the https://app.cvat.ai/auth/register website.
TypeError
a.map is not a function

nM@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:5929049
$o@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4323125
zi@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4331974
Ii@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4331793
ji@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4331476
ws@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4372558
fl@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4361808
dl@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4361731
rl@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4358761
43577/qa/<@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4310534
73323/t.unstable_runWithPriority@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4518901
Ua@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4310243
qa@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4310481
Ga@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4310414
j@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4379169
qt@https://app.cvat.ai/assets/cvat-ui.dd9b13c57bf6b4b32f30.min.js:2:4287741

**Comment by azhavoro** [comment]
@ConteXCrown 
app.cvat.ai site is currently under maintenance, please try again later

**Comment by gibranlp** [comment]
Do you guys have an ETA on this?

**Comment by bsekachev** [comment]
It should work now
