### ISSUE TITLE
Unable to export to cloud storage using API

### ISSUE THREAD

**Issue by realtimshady1** [opencv/cvat#6333]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Using the API tool, fill in the following
<img width="934" alt="image" src="https://github.com/opencv/cvat/assets/20720732/ddceba53-685d-4e62-9173-91a58407f90a">

### Expected Behaviour

There should be an output.zip in the cloud storage

### Current Behaviour

There is no dataset file in the cloud storage

### Possible Solution

Manually export using the UI
<img width="381" alt="image" src="https://github.com/opencv/cvat/assets/20720732/aed30e67-0eab-40a8-9457-d03a76094e54">

### Context

I want to automate the data export using the API

### Your Environment

Version: https://github.com/opencv/cvat/commit/8fae5d3f408cae61f74c8b6493ac82b650222dc6 (HEAD) Release 2.5.0
Docker version: 20.10.22
Docker Swarm/ Kubernetes: No
OS: Debian GNU/Linux 11 (bullseye)
```
cvat_server             | INFO:     220.233.199.36:0 - "GET /api/jobs/278/annotations/?cloud_storage_id=10&filename=output.zip&format=YOLO%201.1&location=cloud_storage&use_default_location=false HTTP/1.0" 201 Created
cvat_server             | INFO:     220.233.199.36:0 - "GET /api/jobs/278/annotations/?cloud_storage_id=10&filename=output.zip&format=YOLO%201.1&location=cloud_storage&use_default_location=false HTTP/1.0" 201 Created
cvat_server             | 2023-06-17 01:55:56,908 DEBG 'uvicorn-0' stdout output:
cvat_server             | INFO:     220.233.199.36:0 - "GET /api/jobs/278/annotations/?cloud_storage_id=10&filename=output.zip&format=YOLO%201.1&location=cloud_storage&use_default_location=false HTTP/1.0" 201 Created
```

**Comment by Marishka17** [comment]
@realtimshady1, You need to set action to _download_.

**Comment by realtimshady1** [comment]
I have tried that also

**Comment by realtimshady1** [comment]
thanks, I found that the problem was both needing to set the action to 'download' but also that the parameter 'use_default_location' should be 'false' rather than the python False
