### ISSUE TITLE
Not able to reset password

### ISSUE THREAD

**Issue by chchienGH** [opencv/cvat#6334]
### My actions before raising this issue
- Trying to reset the password through "Forgot password" Search google for similar issues.
- Searching Google for similar issues.

I am trying to reset the password of my accounts through ("Forgot password". I have tried more than 10 times, but have yet to receive any email with a link for password rest. Is there any other way to get my password reset.

I also trid to create another account, but not sure if it has been successful created. While I am able to log onto my new account, I am not able to create a task from a backed-up tasks due to un-authorization . Can a task be created from a backed-up task created by another account? 

Please advise where to post the question, it this forum is for code related issues only.

Thanks in advance.

**Comment by bsekachev** [comment]
> Can a task be created from a backed-up task created by another account?

Yes, it can.
