### ISSUE TITLE
cannot access analytics 

### ISSUE THREAD

**Issue by ASAADASKAR** [opencv/cvat#6335]
I can't access the analytics. When i click on analytics, a black page comes up with bad gateway.
I look forward to some help.

**Comment by pktiuk** [comment]
@ASAADASKAR  Have you fixed this?

**Comment by ASAADASKAR** [comment]
@pktiuk  yes i did it

**Comment by pktiuk** [comment]
But how?

**Comment by ASAADASKAR** [comment]
@pktiuk everything's ok, thx
