### ISSUE TITLE
Create automatic annotation with line format

### ISSUE THREAD

**Issue by thuyngch** [opencv/cvat#6337]
Hi, I can setup automatic annotation with object detection with the output format as the following:

```python
                    results.append({
                        "confidence": float(score),
                        "label": self.labels.get(label, "unknown"),
                        "points": [xtl, ytl, xbr, ybr],
                        "type": "rectangle",
                    })
```

Now, I want to setup automatic annotation for line detection (x1, y1, x2, y2). How should I change the format in the code?

Thanks!

**Comment by bsekachev** [comment]
Hi @thuyngch 

Try ``"type": "polyline"``.
