### ISSUE TITLE
sdk throws NotFoundException

### ISSUE THREAD

**Issue by tomer-segal-saips** [opencv/cvat#6338]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

when i try the `api_client.tasks_api.list()` api i get a `cvat_sdk.api_client.exceptions.NotFoundException: Status Code: 404` exception.
when i debug further i see that the sdk is accessing the url ` http://host:port/api/tasks`
when i try this url from the browser it doesn't work either.
the webui accesses a `/v1/` url - `http://host:port/api/v1/tasks`
where can i find documentation showing which cvat server version works with which cvat-sdk version?

### Steps to Reproduce (for bugs)
run example code from docs: https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/tasks-api/#list

### Expected Behaviour
expecting to get a list of tasks or an api error (but not a 404 error)

### Current Behaviour
`cvat_sdk.api_client.exceptions.NotFoundException: Status Code: 404`

### Your Environment
- cvat server version 2.0, core version 4.1.0
- cva-sdk version 2.4.6 (2.1.0 shows the same symptom)
- Docker version: 20.10.5
- Are you using Docker Swarm or Kubernetes? no
- operating system ubuntu 20.4
- Code example: https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/tasks-api/#list

**Comment by zhiltsov-max** [comment]
Hi, compatibility info can be found [here](https://opencv.github.io/cvat/docs/api_sdk/#component-compatibility), it's quite simple - SDK major.minor must be equal to the server major.minor. You can always check the server API version at `http:// yourhost /api/swagger/` at the top of the page. SDK supports only 2.x server versions, if you need to work with older versions, please check [this CLI tool](https://github.com/opencv/cvat/tree/v1.7.0/utils/cli).

**Comment by tomer-segal-saips** [comment]
i don't see cvat-sdk ver 2.0 on pypi, do i just follow https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/ to install from my old working dir instead?

**Comment by zhiltsov-max** [comment]
SDK supports only 2.x server versions, if you need to work with older versions, please check [this CLI tool](https://github.com/opencv/cvat/tree/v1.7.0/utils/cli).

**Comment by tomer-segal-saips** [comment]
i'm running server version 2.0, doesn't that qualify as 2.x?
looking at the v2.0.0, v2.1.0 git tags, i don't see a cvat-sdk folder, do only 2.2.0+ support sdk?
