### ISSUE TITLE
Upload fails with custom Domain when deploying cvat within a docker container

### ISSUE THREAD

**Issue by yarhant** [opencv/cvat#6339]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Good afternoon,

We were trying to deploy a custom CVAT server on a node of a GPU cluster served at a custom subdomain name of my institution with an external traefik server which TLS forwards to the 8080 port of CVAT. Exporting the CVAT host works like a charm, except for any upload (project backup, annotations, etc.) that uses the tus-js-client. Hence it gives mixed content Cross-Origin Request (CORS) issues in the browser as the result of https -> http 307 Temporary redirect from the tus-js-client.

![Debugging with the browser 1](https://github.com/opencv/cvat/assets/135619345/823422a7-9e71-45da-9886-999e5695dfb5)

Therefore, is this a X-forwarded-proto : https issue from any traefik such as described in [tus-js-client#233](https://github.com/tus/tus-js-client/issues/233) ? 

![Debugging with the browser 2](https://github.com/opencv/cvat/assets/135619345/14e0382e-0cd0-4172-8bf3-9fb09c197e9d)

The issue is similar to the infrastructure issue [#4531](https://github.com/opencv/cvat/issues/4531) at cvat.ai from last year.

We can't find the origin of the issue of running tus-js-client behind two/three reverse proxies with all different configurations. We thank you for your time reading and answering that issue.

### Your Environment

- Tested with CVAT v2.3.0 and 2.4.3
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.22
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22 (container)

**Comment by azhavoro** [comment]
@yarhant look at https://github.com/traefik/traefik/issues/5551

**Comment by azhavoro** [comment]
I will close the question for now, please reopen it if you have any questions.

**Comment by yarhant** [comment]
@azhavoro Thank you very much. I just tested now and it works perfectly.
