### ISSUE TITLE
Can not upload annotation

### ISSUE THREAD

**Issue by curiosity2** [opencv/cvat#634]
I rewrite the dumped annotation with all images' label as a prelabel annotation then upload it but there is an error.
When I only write three images' label it will be ok, Why? Can someone help me?
![捕获](https://user-images.githubusercontent.com/11660784/62857643-bab1c780-bd2a-11e9-9ca7-9a61ce75890b.PNG)

**Comment by bsekachev** [comment]
@curiosity2 
Hi, could you please attach example of your annotation file and labels specification for a task?

**Comment by curiosity2** [comment]
Hi, bsekachev, thanks for your reply, here are the examples,

normal example:
![1](https://user-images.githubusercontent.com/11660784/62861614-a673c780-bd36-11e9-9d66-7d1240e031fc.jpg)
![2](https://user-images.githubusercontent.com/11660784/62861615-a70c5e00-bd36-11e9-804d-f168d493ea42.PNG)
![3](https://user-images.githubusercontent.com/11660784/62861617-a70c5e00-bd36-11e9-9c96-c39b4240b404.PNG)
report error example:
![4](https://user-images.githubusercontent.com/11660784/62861654-c0ada580-bd36-11e9-950f-df8b26cac2ec.jpg)
![5](https://user-images.githubusercontent.com/11660784/62861656-c0ada580-bd36-11e9-8a9a-d88e3181ddf7.PNG)
![6](https://user-images.githubusercontent.com/11660784/62861657-c0ada580-bd36-11e9-9c0a-54282e37b814.PNG)
![7](https://user-images.githubusercontent.com/11660784/62861658-c1463c00-bd36-11e9-8b3e-e86b747a30b3.PNG)

The file can't be taken out from my work environment, so I post the screenshot. It's an OCR task and the label is only 'shape', I write the text to attribute.

**Comment by bsekachev** [comment]
@curiosity2 
It would be better if you attach text files.
Because I need to test them.

**Comment by bsekachev** [comment]
@curiosity2 
Also it would be useful to see an output of ```docker logs cvat``` and a upload request info in chrome dev tools.

**Comment by bsekachev** [comment]
@curiosity2 
And finally you can try update CVAT from the develop branch. Upload/download functionality is being updated continuously now. 
May be this error has already disappeared.

**Comment by BowieHsu** [comment]
@curiosity2 maybe the reason is points out of boundary? have you checked the points in the polygon?

**Comment by nmanovic** [comment]
@curiosity2 , we need more information about the issue. Without it we are not able to help and resolve the issue. I will close the issue for now. Feel free to reopen it if you can give us more information about the problem.

**Comment by kgloveyou** [comment]
@curiosity2 , 你好，想了解下cvat中是如何做ocr标注的？怎么输入人工识别的文字呢？
