### ISSUE TITLE
/tasks/{}/data API not found 

### ISSUE THREAD

**Issue by jv1522** [opencv/cvat#6345]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am using version 2.2.0 and uploaded tasks using the UI. However, I see 404 response when the UI is trying to get the task data from /api/tasks/{task_id}/data

### Steps to Reproduce (for bugs)

1. Create a project
2. Create a task with uploading images from local

### Expected Behaviour
I expect to see data uploading progress on the UI

### Current Behaviour
Progress upload is hung at 0 percent with 404 error from the backend with call to /api/tasks/{task_id}/data

### Your Environment
CVAT Version: 2.2.0
Deployment Environment: Kubernetes

**Comment by bsekachev** [comment]
Unfortunately 2.2.0 is too old to support. What's more creating tasks from images worked as expected in this release (at least tested by thouthsands users on our online platform for a couple of months), so, steps to reproduce are not clear. 

Please, upgrade to the recent release.
