### ISSUE TITLE
Can't get file when call Export task dataset API

### ISSUE THREAD

**Issue by chang403** [opencv/cvat#6347]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. call this url by http request
http://xxx:8080/api/tasks/140/annotations?org=iauto&use_default_location=true&filename=123.zip&format=CVAT+for+images+1.1
2, this is my code

` public static void main(String[] args) {
        String fileUrl = "http:/xxx:8080/api/tasks/140/annotations?org=iauto&use_default_location=true&filename=123.zip&format=CVAT+for+images+1.1";
        String savePath = "E:\\zip/file.zip";
        try {
            URL url = new URL(fileUrl);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestProperty("Authorization","Token xxx");
            connection.setRequestMethod("GET");
            int responseCode = connection.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_CREATED) {
                InputStream inputStream = connection.getInputStream();

                FileOutputStream outputStream = new FileOutputStream(savePath);
                byte[] buffer = new byte[4096];
                int bytesRead;
                while ((bytesRead = inputStream.read(buffer)) != -1) {
                    outputStream.write(buffer, 0, bytesRead);
                    buffer = new byte[4096];
                }
                outputStream.close();
                inputStream.close();
                System.out.println("ZIP download succeed: " + savePath);
            } else {
                System.out.println("zip download failed");
            }
            connection.disconnect();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }`

3. on cvat page,when click 'Export task dataset', it call this url.I then a xx.zip  was download;
4. I call the same url by postman or send http request in code,I get a xx.zip,but File corruption displayed when unzipping the file

### Expected Behaviour

get a xx .zip, unzipping the file,I will get a useful file 

### Current Behaviour

get a xx .zip, unzipping the file, it throws  File corruption

### Possible Solution

How to receive file stream
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
First request initiates the dataset preparation on the server side and returns code 202. 
Then cvat client pools the server until 201 code is received, after ``?action=download`` is required in URL to get the file. 

Please, get acquainted with REST API.
