### ISSUE TITLE
Bring to foreground, the mask/polygon disappears.

### ISSUE THREAD

**Issue by rpl-alan-shangguan** [opencv/cvat#6352]
Hi, I use that to label the segmentation of images.
Every time I try to bring a mask or a polygon to the foreground, the mask/polygon disappears. But If I refresh the page and load the task again, I will see the mask/polygon has been brought to the foreground and it appears again.

**Comment by bsekachev** [comment]
You need to increase current z layer. 
Only objects from z layers <= current z layer are visible.
When you bring an object to foreground it's z layer greater than the curren one. 

<img width="118" alt="image" src="https://github.com/opencv/cvat/assets/40690378/d4696787-1fd0-4d19-944d-211caefef033">
