### ISSUE TITLE
Serverless functions on AWS EC2 not working after restart

### ISSUE THREAD

**Issue by PAmerikanos** [opencv/cvat#6357]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

I have set up a p3.2xlarge instance on AWS EC2 following the guidelines:
- https://opencv.github.io/cvat/docs/administration/basics/aws-deployment-guide/
- https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
Everything works fine with DEXTER/YOLO/SAM, until I reboot the instance.

### Steps to Reproduce (for bugs)

1. Setup CVAT on a P3 instance with GPU support according to CVAT's/Nvidia's guides
2. Install & test Serverless functions on a task
3. Reboot instance
4. Test Serverless functions on a task

### Expected Behaviour
Even after rebooting, the serverless functions should (ideally) work without redeploying them.

### Current Behaviour
Whenever I reboot the EC2 instance CVAT works as expected, but its detector functions throw various errors (wrong string, wrong url/whatever). The workaround is to redeploy the functions using `./serverless/deploy_gpu.sh`. However, that takes some time and is not very easy to use. Restarting docker daemon did not work.

### Possible Solution
Is there perhaps an environmental variable that does not persist with the docker containers, eg. CVAT_HOST?

### Context
The GPU instance is pretty expensive and does not need to be online 24/7, but should be deployable on demand. Restarting and having immediately functional autoannotating functions is of major significance. A system admin who knows how to redeploy will not always be available.

### Your Environment

- Git hash commit (`git log -1`): 5bc8c7b267a1e713d30419ca90288cf916baf908
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.2
- Are you using Docker Swarm or Kubernetes? neither
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by PAmerikanos** [comment]
Dexter error:
```Interaction error occurred
e is undefined```

YOLOv3 error:
```Detection error occurred
Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://host.docker.internal:32770/".```

SAM, weirdly, worked fine this time.

**Comment by KojoBarbie** [comment]
Hello.
I had a same problem. 
My error is "requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://host.docker.internal:32768/". 

I add port settings to function.yaml.(Thanks to this issue: #4108 )

**Comment by bsekachev** [comment]
Dublicate of #5509

Check your ports, they probably have changed after restart
