### ISSUE TITLE
No documentation about CVAT analytics data migration from Elaticsearch to Clickhouse

### ISSUE THREAD

**Issue by PMazarovich** [opencv/cvat#6360]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
 
There is no information about the data migration from ELK to Clickhouse:
https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/
Is it possible or we might drop all elasticsearch data  for being able to use 2.4.5?
Thanks!

**Comment by bsekachev** [comment]
There is no data migration from ELK to Clickhouse. 
@azhavoro Please, correct me if I am wrong.

**Comment by PMazarovich** [comment]
@bsekachev thanks for the response
