### ISSUE TITLE
Tags Not Present in COCO 1.0 export json file

### ISSUE THREAD

**Issue by priyanshum-cashify** [opencv/cvat#6368]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

I have applied Tags on Images, when i export the Job in COCO 1.0  fromat, I do not find any Tag Annotation data in the COCO exported json file "instance_default.json". Why are Tags not visible in the COCO 1.0 format export file.
In which export Format can i get the info detailing Which Tags are applied on which image?. I require the tags on the image to process them further.

Please provide suggestion/recommendations

**Comment by zhiltsov-max** [comment]
Hi, COCO doesn't support tags, you can find the format descriptions [here](https://opencv.github.io/cvat/docs/manual/advanced/formats/). If you need to export tags in any format, you can choose one of PASCAL VOC, CVAT for *, Datumaro, ImageNet, OpenImages.
