### ISSUE TITLE
How to upload images via REST ?

### ISSUE THREAD

**Issue by cache91** [opencv/cvat#637]
I know that there are REST endpoints for creating new tasks. But i also could not find the images being uploaded along. How do i do it ?

**Comment by cache91** [comment]
I looked at #493 and I tried the code there. Still not able to upload the files via request/python

**Comment by nmanovic** [comment]
@cache91 , I saw in gitter that you were able to modify the script and solve the issue. I will close the issue for now. Feel free to send us a PR.
