### ISSUE TITLE
CVAT API upload documents to annotate in a task - Error

### ISSUE THREAD

**Issue by Nirali22** [opencv/cvat#6376]
### My actions before raising this issue
- [ ] Read CVAT.ai's API documentation to figure how to create a task, upload documents to annotate to the task and upload initial annotations. https://app.cvat.ai/api/docs

I've been able to create a task, but everytime I try to upload docs via the API, it returns a 500 Internal Server Error or run into other errors.

### Steps to Reproduce (for bugs)
I used this code to upload documents to a task:
```
import base64
headers = {
        "Authorization": f"Token {token}",
        "Upload-Multiple": "true"
}
client_files = []
files = []
for path in img_paths:
    with open(path, 'rb') as f:
        image_data = f.read()

    image_base64 = base64.b64encode(image_data).decode('utf-8')
    client_files.append(image_base64)


files = []
for path in img_paths:
    files.append(('client_files', open(path, 'rb')))

data = {
    "image_quality": 70,
    "client_files": client_files
}
r = requests.post(f'https://app.cvat.ai/api/tasks/{task_id}/data', headers=headers, json=data)
```

### Expected Behaviour
The files are uploaded successfully to the task created under my account.

### Context
I am unable to proceed beyond creating a task (with no documents attached). I need to be able to upload multiple documents to annotate as well as initial annotations for each.

**Comment by zhiltsov-max** [comment]
Hi, please check [this example](https://opencv.github.io/cvat/docs/api_sdk/sdk/lowlevel-api/#example) and [this section](https://opencv.github.io/cvat/docs/api_sdk/sdk/lowlevel-api/#binary-data-in-requests-and-responses) in the docs to get information about uploading protocols. CVAT doesn't use base64 for file uploads now - you will need to send them in binary encoding and with the `multipart/form-data` media type.

**Comment by Nirali22** [comment]
Thank you! It worked!

I ran into errors when using the token for authentication, but username and password worked!

(But I can't create multiple jobs within the same task. It says "Adding more data is not supported". Can you help me overcome this issue?)

**Comment by zhiltsov-max** [comment]
> I ran into errors when using the token for authentication, but username and password worked!

You can find examples on using token auth in low-level SDK [here](https://github.com/opencv/cvat/blob/develop/tests/python/rest_api/test_auth.py#L41-L51).

> I can't create multiple jobs within the same task. It says "Adding more data is not supported". Can you help me overcome this issue?

CVAT doesn't support adding or removing jobs (except they are GT jobs), they are created automatically after the task data is uploaded. If you want to modify how jobs are created, consider using the `job_frame_mapping`, `segment_size`, and `overlap` parameters (described [here](https://opencv.github.io/cvat/docs/manual/basics/create_an_annotation_task/#advanced-configuration), the parameters are split between [tasks_api.create()](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/tasks-api/#create) and [tasks_api.create_data()](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/tasks-api/#create-data)). If you want to add new data to the task later, you'll need to use projects instead - task data can't be modified after creation.

**Comment by Nirali22** [comment]
Thanks a lot for all your help! I will look into these!

Can you elaborate on this: If you want to add new data to the task later, you'll need to use projects instead - task data can't be modified after creation.

Here's what I want to do: Have a separate project per organization, within every organization, create a task with a set of labels.
As and when a user sends a file to me, I want to upload it to the task to create a new job (That way, I have a single task with multiple jobs rather than a redundant structure with multiple tasks and 1 job per task). How can I achieve this?

**Comment by zhiltsov-max** [comment]
> As and when a user sends a file to me, I want to upload it to the task to create a new job

It's only possible if there is only one file upload including all the files. If you need to upload files several times, you need to use projects and create one task per upload, even if it looks redundant at this point. CVAT doesn't support job creation by request yet. The whole workflow you're describing, with label definition first and uploading data in portions later - this is what projects are for in CVAT.

**Comment by Nirali22** [comment]
Okay, thank you!
Since I have all the answers I need, I'm closing this issue.
