### ISSUE TITLE
Can we change the SAM weights?

### ISSUE THREAD

**Issue by davodogster** [opencv/cvat#6380]
Hi guys,

Are we able to change the SAM weights here to a smaller model. If we can, will it have a noticeable effect on GPU RAM usage and inference speed?
![image](https://github.com/opencv/cvat/assets/46079516/f178e496-ebd5-4e54-9a84-a89c3606538e)

Thanks, Sam

**Comment by bsekachev** [comment]
You can. 
Please, refer to the original PR to get more information: https://github.com/opencv/cvat/pull/6019
