### ISSUE TITLE
Is it possible to assign separate attributes for any point of the drawn polylines? or polygons?

### ISSUE THREAD

**Issue by ataberkarman** [opencv/cvat#6385]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Drawing a random polyline.
2. Clicking points of the polyline,

### Expected Behaviour

Assigning separate attributes for any point of the drawn polylines? or polygons? So that, an annotation of a class with hierarchy can be obtained.

### Current Behaviour

There is not such a functionality that i found so far.

### Context

I was trying to create complex, high detailed annotations for the datasets i have.

**Comment by bsekachev** [comment]
It is not possible for polygons and polylines.
But  it is possible for [skeletons](https://opencv.github.io/cvat/docs/manual/advanced/annotation-with-skeletons/) if your objects have fixed number of points or can be divided into groups, each with a fixed number of points.
