### ISSUE TITLE
failed to solve: process "/bin/bash -xo pipefail -c omz_converter     --name yolo-v3-tf     --precisions FP32     -d /opt/nuclio/open_model_zoo.orig     -o /opt/nuclio/open_model_zoo" did not complete successfully: exit code: 137

### ISSUE THREAD

**Issue by spoilsme** [opencv/cvat#6387]
root@lantern:/opt/cvat# ./serverless/deploy_cpu.sh serverless/openvino/omz/public/yolo-v3-tf
[+] Building 12.1s (9/9) FINISHED                                                                                                                                       
 => [internal] load .dockerignore                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                                                                               0.1s
 => => transferring dockerfile: 418B                                                                                                                               0.0s
 => [internal] load metadata for docker.io/openvino/ubuntu20_runtime:2022.3.0                                                                                     11.2s
 => [internal] load build context                                                                                                                                  0.1s
 => => transferring context: 66B                                                                                                                                   0.0s
 => [1/4] FROM docker.io/openvino/ubuntu20_runtime:2022.3.0@sha256:0cdf91fab23967cbffd57edf203811fd77dde2ea7fe251d240d6ef2a0882db24                                0.0s
 => CACHED [2/4] RUN apt-get update     && apt-get -y --no-install-recommends install python-is-python3     && rm -rf /var/lib/apt/lists/*                         0.0s
 => CACHED [3/4] RUN pip install --no-cache-dir opencv-python-headless pillow pyyaml                                                                               0.0s
 => CACHED [4/4] COPY model_loader.py shared.py /opt/nuclio/common/openvino/                                                                                       0.0s
 => exporting to image                                                                                                                                             0.1s
 => => exporting layers                                                                                                                                            0.0s
 => => writing image sha256:70e9dbf2ca437896d2484682b9ae88d25f424aa2e738ed51a45be0cdd0be9bfc                                                                       0.0s
 => => naming to docker.io/library/cvat.openvino.base                                                                                                              0.0s
23.06.28 01:40:40.763                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}
[+] Building 47.3s (8/9)                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                               0.1s
 => => transferring dockerfile: 440B                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                  0.1s
 => => transferring context: 2B                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/openvino/ubuntu20_dev:2022.3.0                                                                                          4.4s
 => [internal] load metadata for docker.io/library/cvat.openvino.base:latest                                                                                       0.0s
 => [build 1/3] FROM docker.io/openvino/ubuntu20_dev:2022.3.0@sha256:1ba0022c1352d5f303a4833607a9aac0bdac2c4810dc46d1ea2d2ca160c3ad9d                              0.0s
 => CACHED [stage-1 1/2] FROM docker.io/library/cvat.openvino.base                                                                                                 0.0s
 => CACHED [build 2/3] RUN omz_downloader     --name yolo-v3-tf     -o /opt/nuclio/open_model_zoo.orig                                                             0.0s
 => ERROR [build 3/3] RUN omz_converter     --name yolo-v3-tf     --precisions FP32     -d /opt/nuclio/open_model_zoo.orig     -o /opt/nuclio/open_model_zoo      42.2s
------                                                                                                                                                                  
 > [build 3/3] RUN omz_converter     --name yolo-v3-tf     --precisions FP32     -d /opt/nuclio/open_model_zoo.orig     -o /opt/nuclio/open_model_zoo:                  
#0 0.883 + omz_converter --name yolo-v3-tf --precisions FP32 -d /opt/nuclio/open_model_zoo.orig -o /opt/nuclio/open_model_zoo                                           
#0 9.555 ========== Converting yolo-v3-tf to IR (FP32)                                                                                                                  
#0 9.555 Conversion command: /usr/bin/python3.8 -- /usr/local/bin/mo --framework=tf --data_type=FP32 --output_dir=/opt/nuclio/open_model_zoo/public/yolo-v3-tf/FP32 --model_name=yolo-v3-tf --input=input_1 '--scale_values=input_1[255]' --reverse_input_channels --transformations_config=/opt/nuclio/open_model_zoo.orig/public/yolo-v3-tf/yolo-v3.json --input_model=/opt/nuclio/open_model_zoo.orig/public/yolo-v3-tf/yolo-v3.pb '--layout=input_1(NHWC)' '--input_shape=[1, 416, 416, 3]'
#0 9.555 
#0 13.20 [ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal. 
------
Dockerfile:9
--------------------
   8 |     
   9 | >>> RUN omz_converter \
  10 | >>>     --name yolo-v3-tf \
  11 | >>>     --precisions FP32 \
  12 | >>>     -d /opt/nuclio/open_model_zoo.orig \
  13 | >>>     -o /opt/nuclio/open_model_zoo
  14 |     
--------------------
ERROR: failed to solve: process "/bin/bash -xo pipefail -c omz_converter     --name yolo-v3-tf     --precisions FP32     -d /opt/nuclio/open_model_zoo.orig     -o /opt/nuclio/open_model_zoo" did not complete successfully: exit code: 137

**Comment by Petros626** [comment]
nothing new?
