### ISSUE TITLE
Unable to run in ubuntu latest (22.04)

### ISSUE THREAD

**Issue by deepakbandela** [opencv/cvat#6389]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)
have looked at the issues mentioned here
Tried installing it from source with older versions
tried installing it in older versions of Ubuntu
Checked Traefik logs. don't find any issue.

I installed the cvat tool from the https://opencv.github.io/cvat/v2.4.8/docs/administration/basics/installation/ on ubuntu 20.04 as well as 18.04 in AWS EC2 and AZ VM. But when all installation steps are complete I see 404 error in the port given.

### Steps to Reproduce (for bugs)

1. Follow the steps given in https://opencv.github.io/cvat/v2.4.8/docs/administration/basics/installation/
2. Open the port which gives 404 not found error in the response as a text.

### Expected Behaviour

It should be loading the application so that I can login and use the system.

### Current Behaviour

404 not found error is happening

### Possible Solution

The docker services might not be properly initiated.

### Context

I'm trying to open up the application and use it. but the app doesn't seems to be opening up .

### Your Environment

- Latest version from the https://opencv.github.io/cvat/v2.4.8/docs/administration/basics/installation/
- Docker version `docker version` (e.g. Docker 17.0.05): 17.0.05
- Are you using Docker Swarm or Kubernetes? Using Docker Compose Up 
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04- 
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by azhavoro** [comment]
@deepakbandela Does [this](https://opencv.github.io/cvat/docs/administration/advanced/analytics/#fetching-event-data-as-csv-from-the-apievents-endpoint:~:text=The%20/api/events%20endpoint%20allows%20the%20fetching%20of%20event%20data%20with%20filtering%20parameters%20such) solve the issue?

**Comment by deepakbandela** [comment]
No it didn't fix the problem. I still see 404 page not found error while using the IP address. While using the localhost:8080 it opens up my server.
