### ISSUE TITLE
Code: 403 when creating a new task

### ISSUE THREAD

**Issue by edrdos101** [opencv/cvat#639]
I am encountering the following error when trying to create a new task with a shared volume:
Code: 403. Message: {"detail":"You do not have permission to perform this action."}

<img width="640" alt="Screenshot 2019-08-13 at 10 49 12" src="https://user-images.githubusercontent.com/46657022/62924097-09597300-bdb8-11e9-91d4-95229402b93c.png">

Couldn't find any mentions of this error in the issues, any advice would be much appreciated

Thanks!

**Comment by bsekachev** [comment]
@edrdos101 
How did you create this account? Probably you don't have permission for task creating. 
You need to create a superuser account and than you can create other accounts (via default registration) and entitle them by the superuser account.

**Comment by nmanovic** [comment]
@edrdos101 , your user doesn't have enough privileges to create a task. Please read our documentation. You need to assign additional rights. The question was discussed many times on our gitter channel. I will close the issue for now. We definitely need better messages about errors but it is a separate issue.

**Comment by AeolusTech** [comment]
For anyone else encountering this problem - the fix is really easy, but **it's not stated anywhere** in the "User Guide" (as of February 24th 2021). Only a user assigned an admin role in the Django administration panel can create new tasks. Log in as a superuser and assign it properly. Hope that helps :)

**Comment by bsekachev** [comment]
@AeolusTech 

>  Only a user assigned an admin role

It is not exactly true. CVAT has different user groups: admins, users, annotators, observers. 
Tasks can be created by a user who belongs to one admins or users.

**Comment by AeolusTech** [comment]
Thank you for a very quick reply, Boris! I am just starting with CVAT

**Comment by shajahanpc** [comment]
I'm using CVAT online tool, I created a project for my organization, But it is showing a warning message that you can add a project, you want permission. actually, where do I find this permission access to allow. Are there any other methods to add projects to organization?

Note: I use admin account and im on the one user for this account.

**Comment by nmanovic** [comment]
@shajahanpc , if you are using cvat.org, you can have only "user" permissions. Users can create 3 projects and 10 tasks on the public instance (see the scope `create` in csv tables below).

https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/projects.csv
https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/tasks.csv

There are two possible options:
- We can assign `business` permissions to your account on cvat.org temporary. To do that we need strong reasons. Please send us information about how you are using cvat.org inside your organization. Also please share information about your organization and needs.
- You can setup your local CVAT instance.

**Comment by viniciusczar** [comment]
For everyone having the same problem, i'm using that in my Kubernetes. Execute that command in backend pod: python3 ~/manage.py createsuperuser
