### ISSUE TITLE
Unable to import dataset in Coco format

### ISSUE THREAD

**Issue by liudaolunboluo** [opencv/cvat#6392]
version:2.3.0

dataset directory structure:
├── annotations
│   └── test_abc.json
└── images

error info:cvat-app.tsx:357 Error: Request failed with status code 500. "datumaro.components.errors.AnnotationImportError: Failed to import item (4588, 'default') annotation: object of type 'float' has no len()\n"..

**Comment by liudaolunboluo** [comment]
because,id 4588 annotations is:
        {
            "segmentation": [
                123.16,
                336.84,
                625.2,
                326.0,
                632.41,
                640.95,
                95.92,
                638.22
            ],
            "iscrowd": 0,
            "image_id": 1,
            "area": 168967.52550000002,
            "bbox": [
                95.92,
                326.0,
                536.49,
                314.95
            ],
            "category_id": 12,
            "id": 1439
        },
area is float

**Comment by zhiltsov-max** [comment]
Hi, please check this [example](https://github.com/cvat-ai/datumaro/blob/ff83c00c2c1bc4b8fdfcc55067fcab0a9b5b6b11/tests/assets/coco_dataset/coco_instances/annotations/instances_val.json). The "segmentation" field should be one of: `[ ]`, `[ [x1,y1, x2,y2, ... ], ... ]`, or `{"counts": [...], "size": [...]}`. Probably, you'll need to add a pair of square brackets around the segmentation value list to fix the problem.

**Comment by liudaolunboluo** [comment]
> Hi, please check this [example](https://github.com/cvat-ai/datumaro/blob/ff83c00c2c1bc4b8fdfcc55067fcab0a9b5b6b11/tests/assets/coco_dataset/coco_instances/annotations/instances_val.json). The "segmentation" field should be one of: `[ ]`, `[ [x1,y1, x2,y2, ... ], ... ]`, or `{"counts": [...], "size": [...]}`. Probably, you'll need to add a pair of square brackets around the segmentation value list to fix the problem.


oh! thank you very much,it's my problem,But I think it would be better to include the format that doesn't meet the requirements in the exception message. You see, I saw an error and I don't know which field has the problem

**Comment by zhiltsov-max** [comment]
> it would be better to include the format that doesn't meet the requirements in the exception message.

It's a good idea, but it's very hard to implement for all supported formats. This request will be tracked in #1529
