### ISSUE TITLE
Allow inviting unregistered users to an organization by email

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6393]
I created an organization 

Then clicked on invite members and entered several valid email addresses like _xxx@gmail.com_ and get this error for all addresses:

> Could not invite this member "xxx@gmail.com" to the organization
> 
> Error: Request failed with status code 400. ["You cannot invite an user with dbaruchg@gmail.com email. It is not a valid email in the system."].

Many thanks

**Comment by bsekachev** [comment]
Hi @DaveBGld 

This email is not registered on app.cvat.ai. Need to register a user with this email first.

**Comment by DaveBGld** [comment]
Thanks!

**Comment by DaveBGld** [comment]
As a recommendation: Send the email in one of two versions: registered and unregistered user email. This way the onboarding of new users is easier ==> more users.

I found the process cumbersome and frustrating to the point that I almost cancelled my pro subscription

**Comment by bsekachev** [comment]
Let's keep as possible enhancement

**Comment by bsekachev** [comment]
Now that is supported
