### ISSUE TITLE
Recovery - Annotations in a hard drive that does not boot

### ISSUE THREAD

**Issue by agporto** [opencv/cvat#6398]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

Can I manually recover images and image annotations from a hard drive that does not boot anymore? If so, how? 
Can't find anything in the manual about it.

**Comment by azhavoro** [comment]
https://opencv.github.io/cvat/docs/faq/#where-are-uploaded-imagesvideos-stored
https://opencv.github.io/cvat/docs/faq/#how-to-transfer-cvat-to-another-machine
https://docs.docker.com/storage/volumes/

**Comment by agporto** [comment]
Thank you!
