### ISSUE TITLE
Chrome doesn't load the labelling workspace in v2.4.8

### ISSUE THREAD

**Issue by tvanderwal-lmco** [opencv/cvat#6399]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Deploy v2.4.8 with helm chart version 0.7.3
1. Navigate to a labelling job
1. Attempt to launch the job

### Expected Behaviour
That the workspace launches correctly and allows the user to label the images

### Current Behaviour
When launching the job the canvas just spins as if it's constantly loading the data. Looking at the console logs there is actually a cors header issue. This does not happen when using FireFox (version 114.0.5735.133) 

```
Specify a Cross-Origin Embedder Policy to prevent this frame from being blocked
Because your site has the Cross-Origin Embedder Policy (COEP) enabled, each embedded iframe must also specify this policy. This behavior protects private data from being exposed to untrusted third party sites.
To solve this, add one of following to the embedded frame’s HTML response header:
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Embedder-Policy: credentialless (Chrome > 96)
```

### Possible Solution
I'm not too familiar with these headers but I believe it might be this configuration here https://github.com/opencv/cvat/blob/v2.4.8/cvat-ui/react_nginx.conf#L28. For things under /assets it's being set to `require-corp` but doesn't have the Cross-Origin-Resource-Policy: cross-origin header documented [here](https://developer.chrome.com/blog/coep-credentialless-origin-trial/#can-i-also-load-cross-origin-iframes-without-special-headers-under-a-credentialless-environment). 

### Context
We upgraded our on-prem environment from 2.4.3 to 2.4.8 and got reports of data not loading which we also reproduced. Within these minor releases is also when the code I linked above was released. It does seem like we can direct users to use Firefox but many developers here prefer Chrome as their browser. 

### Your Environment
- Git hash commit (`git log -1`): commit ab020f53c5658065a2e4d81f55a50ccd6e41210e (HEAD, tag: v2.4.8, origin/master)
- Are you using Docker Swarm or Kubernetes? Kubernetes
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS Ventura
- Chrome 114.0.5735.133 

<img width="1792" alt="Screenshot 2023-06-28 at 10 09 28 PM" src="https://github.com/opencv/cvat/assets/83782809/4445b37c-eb5d-44cf-bab0-0eefd2d5160a">

**Comment by bsekachev** [comment]
Hi @tvanderwal-lmco 

* Clear the browser cache to get relevant results from the server (not cached ones)
* Or click "Disable cache" at the top of chrome dev tools and update the page once

**Comment by tvanderwal-lmco** [comment]
Oof I'm embarrassed I didn't think of that first! Thanks for the help @bsekachev :)
