### ISSUE TITLE
CVAT behave unstable with wrong uploaded auto annotation models

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#640]
If a user had been able to upload a wrong model, or a script, or something else, dashboard can't be downloaded anymore because of wrong meta information request. 

Several users have already come across this problem. 

WORKAROUND:
Delete a broken model manually from the CVAT database:
```bash
docker exec -it cvat_db bash
su postgres     # change a user to postgres (default you are root, so password isn't needed)
psql cvat     # connect to cvat database
\dt     # show all tables
select * from auto_annotation_autoannotationmodel; 
delete * from auto_annotation_autoannotationmodel where id=<id_of_broken_model>;
```

**Comment by azhavoro** [comment]
Bug already fixed in https://github.com/opencv/cvat/pull/573.
Also models can be deleted via admin panel without direct query to the database.
