### ISSUE TITLE
Enforcing uniqueness of project and task names under projects

### ISSUE THREAD

**Issue by rogvidarge** [opencv/cvat#6406]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Using the cvat sdk it is currently impossible to find the right project if you don't have the ID. This means that if someone by accident creates two projects with the same name, you have no way of getting the right project id from the project name. 
The same issue exists with tasks in projects. 

#### Duplicate project names
1. Create a project in the projects tab
2. Create another project with the same name in the projects tab
The only way to differentiate the projects is project ID, which is not easily memorized for users

#### Duplicate task names
1. Create a task in the tasks tab
2. Create another task in the tasks tab with the same name
The only way to differentiate the tasks is the task ID which is not easily memorized for users

### Expected Behaviour
Similar to how Organization names are expected to be unique, project names within organizations (also within personal space) should enforce the same uniqueness of name as organizations does. The same goes for task names in projects.

### Current Behaviour
See previous sections

### Possible Solution
The simplest fix is to add uniqueness requirements in the django db models.

### Context
I am trying to make the annotation experience as seamless as possible for a large number of different types of users, and these problems currently mean that I need to make some assumptions that might not be true in the future.

### Your Environment
Not relevant

**Comment by bsekachev** [comment]
Hi @rogvidarge 

I do not think we are going to implement it. There are a lot of potential difficulties and really do not see reasons to do it. 
If on your instance you need unique names, keep them unique. 

> The simplest fix is to add uniqueness requirements in the django db models.

This will not work. A lot of dublicates in existing data.

**Comment by rogvidarge** [comment]
I do understand that this is a breaking change, but the solution should work. Keeping names unique, requires a whole other level of management, that I don't want to get into. 

Is there a reason for no uniqueness restriction of project names, and task names in projects, when there is uniqueness in organization slurs?

**Comment by bsekachev** [comment]
I do not think this change is demanded. Actually for several years you are the first one who interested it.

**Comment by rogvidarge** [comment]
I understand and respect the decision, and have already worked around it in our setup. But I am still curious as to why the data models of the projects and tasks don't have unique slugs like organizations do.

**Comment by bsekachev** [comment]
I believe because "Organization" is something what keeps the idea of mapping somehow with instances in the real world. Whether it is a real organization (like Intel, AMD, NVidia), or internal departments that are also usually have unique naming. All they are regular use-cases in our practice.  

In contrast with projects, where can be multiple: "Test" or "RoadTraffic", even for the same user.
