### ISSUE TITLE
No matching distribution found for tensorflow

### ISSUE THREAD

**Issue by arrrshia** [opencv/cvat#6407]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

I have been trying to run the server less setup given the tutorial [https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models](url) and it just isn't installing the requirements (specifically tensor flow) on my M2 Mac running Ventura 13.2.1.

### Steps to Reproduce (for bugs)

1. Install CVAT like normal given the tutorial
2. Change h5py version to 3.9.0 in requirements because 3.6.0 wouldn't work

### Expected Behaviour
I expect the command to just run like normal, but it doesn't

### Current Behaviour
When I keep tensorflow==2.11.1 or tensorflow==2.11.0 in requirements.txt, I get the error
`#0 2.241 ERROR: Could not find a version that satisfies the requirement tensorflow-cpu-aws==2.11.0; platform_system == "Linux" and (platform_machine == "arm64" or platform_machine == "aarch64") (from tensorflow) (from versions: none)
#0 2.241 ERROR: No matching distribution found for tensorflow-cpu-aws==2.11.0; platform_system == "Linux" and (platform_machine == "arm64" or platform_machine == "aarch64")
`
When I try tensorflow-macos==2.11.1 and tensorflow-macos==2.11.0 I get the error
`ERROR: Could not find a version that satisfies the requirement tensorflow-macos==2.11.1 (from versions: none)
#0 40.25 ERROR: No matching distribution found for tensorflow-macos==2.11.1`

### Possible Solution
Tensorflow installs just fine on my Mac, so I'm not sure what the problem is here.

### Context
I'm just trying to install and run the server less functionality to deploy auto-annotation models.

### Your Environment
- Docker version: v20.10.22
- Are you using Docker Swarm or Kubernetes: 👎 
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS Ventura 13.2.1 M2 MacBook Air

**Comment by arrrshia** [comment]
Closing issue. Solved by switching off ARM platform.

**Comment by yhranik-vp** [comment]
Hi @arrrshia ,
Sorry to bother, I'm having the same issue when running docker compose on M1 Mac. Can you please elaborate on how you switched off ARM platform?

**Comment by arrrshia** [comment]
Hi @yhranik-vp,
I switched to a remote ubuntu server LOL
