### ISSUE TITLE
Add new menu to task dropdown

### ISSUE THREAD

**Issue by prnr** [opencv/cvat#6408]
### My actions before raising this issue
- [O] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [O] Searched [past issues](/issues)

### Context
I want to add new features (face de-identification in images) to the menu, but I don't know what steps to work on. 

What I'm currently trying to add is [https://github.com/ORB-HD/deface ], and I can add a menu referring to this[https://github.com/opencv/cvat/issues/4933] article, but I don't know how to access the image file directly and how to operate that python cli using API. 

What part should I study?

**Comment by bsekachev** [comment]
Where do you want to run deface? In the browser?

**Comment by bsekachev** [comment]
Image can at least be accessed from DOM element  with id ``#cvat_canvas_background``.
You can find a lot of code snippets from the internet how canvas element can be converted to image. 

For example this one:
```
function convertCanvasToImage() {
  let canvas = document.getElementById("canvas");
  let image = new Image();
  image.src = canvas.toDataURL();
  return image;
}
```

**Comment by prnr** [comment]
> I'll try to study it, I didn't understand the structure of the cvat yet, so I asked you a question. It's been a lot of help!

**Comment by prnr** [comment]
> Image can at least be accessed from DOM element with id `#cvat_canvas_background`. You can find a lot of code snippets from the internet how canvas element can be converted to image.
> 
> For example this one:
> 
> ```
> function convertCanvasToImage() {
>   let canvas = document.getElementById("canvas");
>   let image = new Image();
>   image.src = canvas.toDataURL();
>   return image;
> }
> ```

I'll try to study it, I didn't understand the structure of the cvat yet, so I asked you a question. It's been a lot of help!
