### ISSUE TITLE
Webhooks not working as intended

### ISSUE THREAD

**Issue by hey-its-suvi** [opencv/cvat#6419]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create a webhook for a project. Set it up to only send Task events.
2. Go to a task with 1 job, change the Job stage from annotation to acceptance

### Expected Behaviour

Webhook should trigger as task goes from 0% complete to 100% complete

### Current Behaviour

Webhook does not trigger

### Context

I want webhook to be triggered on change in task state. That is not working

### Your Environment
- Operating System and version: Linux Ubuntu 20.04
- Browser: Google Chrome

**Comment by bsekachev** [comment]
> from 0% complete to 100% complete

Actually this is not a part of task state. The value is computed depending on jobs state.
So, if you want to know when job stage changed, please listen for Job events.

**Comment by bsekachev** [comment]
I will close the issue
