### ISSUE TITLE
Error 400 in creating new Task: video encoding problem?

### ISSUE THREAD

**Issue by caloc** [opencv/cvat#642]
Hi everyone,
I have 6 videos of different length taken with the same webcam, in .mov format. No one is bigger than 400 MB.
I got error 400 when creating a task on CVAT and looking at the docker logs, it seems like the error is related to the video encoding. However I don't get the error when uploading the smallest video, 30 MB circa. Converting the video in MPEG-4, relating to [this issue](https://github.com/opencv/cvat/issues/539) (I tried H.264 and MPEG-4 video-encoder) with Handbrake does not fix the problem, but splitting it in subvideos of minor lenght sometime works. For example, 1 min is ok, 3 min is not. It looks like a random behaviour, I don't understand if the problem is the video size of the encoding.
Is there a specific video encoding which is more likely to work? Are there knows size limits to video files?

Thank you

[log.txt](https://github.com/opencv/cvat/files/3498300/log.txt)

**Comment by nmanovic** [comment]
@caloc ,

we decode a video file using FFMPEG. Please use gitter to ask similar questions and submit here a bug or a feature request.

```
docker exec cvat bash -ic "ffmpeg -codecs"
```
