### ISSUE TITLE
Can we directly import Tensorflow model(.pb fle) in CVAT.

### ISSUE THREAD

**Issue by Abhirao024** [opencv/cvat#6427]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Can we directly import Tensorflow model(.pb fle) in CVAT.

I have developed a model in tensorflow2 and a created a .pb file using the checkpoints. I am now trying to import this model into CVAT docker container (Windows) , however  im not able to import. I would appreiciate if you can please share me detailed steps regarding how i can proceed further.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by Abhirao024** [comment]
Need help regarding how to import a tesnsorflow 2 model into cvat

**Comment by bsekachev** [comment]
https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models

Also we have a lot of examples in ``serverless/`` directory.

**Comment by Abhirao024** [comment]
Can we directly deploy a Tensorflow2 Mask_RCNN model saved file (.pb format ) into Nuclio?

Also i would appreciate if you could share any examples
