### ISSUE TITLE
Not able to convert annotation output to json using COCO

### ISSUE THREAD

**Issue by vamsykothuru** [opencv/cvat#643]
Hi,

I am trying to convert the xml output to JSON. Followed the doc https://github.com/opencv/cvat/blob/develop/utils/coco/converter.md for the instructions.

Tried the command 
python converter.py --cvat-xml </path/to/cvat/annotation.xml> --output </path/to/output/coco/annotation.json> --image-dir </path/to/directory/with/images> --draw </path/to/save/directory> --draw_labels --use_background_label

I am able to see the image and the json file getting created but the JSON file has only the meta data got captured. It has ignored the bbox values of the vehicle.

Attaching the json file in zip format.
Kindly suggest..

[456.zip](https://github.com/opencv/cvat/files/3500198/456.zip)

**Comment by BowieHsu** [comment]
you can modify converter.py with adding bbox parsing function. for example:
`for poly in img.iter('box'):
            polygon = {}
            xtl = -1
            ytl = -1
            xbr = -1
            ybr = -1
            save_flag = True
            for key, value in poly.items():
                # print('key', key)
                # print('value', value)
                if key == 'label':
                #   print(value not in category_map.keys())
                #   print(value)
                #   print(category_map.keys())
                  if value not in category_map.keys():
                     save_flag = False
                     continue
                if key == 'xtl':
                    xtl = value
                elif key == 'ytl':
                    ytl = value
                elif key == 'xbr':
                    xbr = value
                elif key == 'ybr':
                    ybr = value
                else:
                    polygon[key] = value
                if key == 'z_order':
                    z_order_on_counter += 1
                polygon['points'] = str(xtl) + ',' + str(ytl) + ';' + str(xbr) + ',' + str(ytl) + ';' + str(xbr) + ',' + str(ybr) + ';' + str(xtl) + ',' + str(ybr)
 if (float(xbr) - float(xtl)) <= 5.0:
                save_flag = False

            if (float(ybr) - float(ytl)) <= 5.0:
                save_flag = False
            # print(polygon)
            if save_flag:
               polygon_counter += 1
               image['polygon'].append(polygon)`

**Comment by bsekachev** [comment]
@vamsykothuru 
You can update CVAT. Now it supports dump to COCO files immediately.

**Comment by nmanovic** [comment]
CVAT now supports COCO dump directly from UI. I will close the issue. Don't hesitate to reopen it if you have still problems.

**Comment by vamsykothuru** [comment]
Thanks @nmanovic  and @bsekachev

**Comment by congnguyenthe** [comment]
Hi,
I would like to ask if cvat has supported dump keypoints for the skeleton detection to COCO format?

I tried but it seems that cvat only supports dump segmentation(boxes) by now.

**Comment by Baiju-Pro** [comment]
Hi , Even I am facing the same issue - coco format is not supported for point marking. please suggest any way to make it.
