### ISSUE TITLE
NameError: name 'FunctionCallRequest' is not defined

### ISSUE THREAD

**Issue by NSalberg** [opencv/cvat#6430]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.  install cvat-sdk: `pip install cvat-sdk`
2. run code provide by the [docs](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/lambda-api/#create_requests) replacing necessary fields

### Expected Behaviour
Automatic annotation should begin with model provided

### Current Behaviour
When running the code provided by the docs this error appears
`Traceback (most recent call last):
  File "/pathtofile/annotate.py", line 18, in <module>
    function_call_request = FunctionCallRequest(
NameError: name 'FunctionCallRequest' is not defined`

### Possible Solution
cvat_sdk should have the model FunctionCallRequest 
`api_client.lambda_api.create_requests()` should take FunctionCallRequest as input

### Your Environment
- cvat_sdk==2.4.7
- Windows

**Comment by zhiltsov-max** [comment]
Hi, probably, you're reading the development version docs, as the API definitions for lambda were introduced in https://github.com/opencv/cvat/pull/6276, which has not been included in any release yet. If you're actually using the development version, you can build SDK for your version [manually](https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/#how-to-generate-package-code).

Related: https://github.com/opencv/cvat/issues/6351

**Comment by NSalberg** [comment]
Yep building the sdk worked!
