### ISSUE TITLE
Deploying mask_rcnn is stuck in endless loop.

### ISSUE THREAD

**Issue by prnr** [opencv/cvat#6434]
### My actions before raising this issue
- [O] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [O] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Clone Repository
2. Set up for WSL2/Docker Desktop environment(With installation guide)
3. Run as serverless
4. Deploy DL model with codes on https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
5. Modify the files related to deploy by following https://github.com/opencv/cvat/issues/5170.

### Expected Behaviour

Model deploying successful within 1hr

### Current Behaviour

The model is not deployed, and the cls screen remains unchanged. The loop log of the nuclio container is as follows.
[log.txt](https://github.com/opencv/cvat/files/11966732/log.txt)
cli logs
[log2.txt](https://github.com/opencv/cvat/files/11966751/log2.txt)

### Your Environment

CPU : Intel 12700F
Memory: 64GB
GPU : RTX3060 / Nvidia Studio driver 531.61 / cuda 12.1.0.531.14
OS : Windows 11 Pro insider / WSL2 Ubuntu-20.04
Python 3.8.10 / Docker Desktop 4.19.0 / Git 2.40.1
A brain with a low understanding of coding
Terrible English skills through a web translator

**Comment by bsekachev** [comment]
In some cases it is taking more than 1hr, depending on many factors. Agree, that need some additional progress visualization, but currently I can suggest waiting more.

**Comment by prnr** [comment]
> In some cases it is taking more than 1hr, depending on many factors. Agree, that need some additional progress visualization, but currently I can suggest waiting more.

It's been 19 hours now, and it's still looping.
![image](https://github.com/opencv/cvat/assets/22967869/8f229431-b47b-40a9-853c-ca7e24f5fba8)

**Comment by bsekachev** [comment]
@prnr 

Screenshot you sent contains logs from run nuclio dashboard container (you started it not in detached mode), so it will work until you end this process. This is not function building.

**Comment by bsekachev** [comment]
@prnr Basically you should look at the Terminal window where the building was started.

**Comment by prnr** [comment]
> @prnr Basically you should look at the Terminal window where the building was started.

![image](https://github.com/opencv/cvat/assets/22967869/f322b07d-e169-4e66-8efa-2ab2a2b3d2a1)

Well, it hasn't changed in four days. Are you sure this isn't normal?

**Comment by bsekachev** [comment]
What region are you working from? Do you have system proxy or VPN installed?

**Comment by prnr** [comment]
@bsekachev What means the 'region'? I'm currently running on local(C:) with serverless, and I have a VPN client installed (Softether, Windows vpn) but I'm not using it.

**Comment by bsekachev** [comment]
Region, I mean Europe/China/United States, etc.

**Comment by prnr** [comment]
@bsekachev In Korea

**Comment by bsekachev** [comment]
It cannot be reproduced on our side.
