### ISSUE TITLE
how to custom set the video frame rate?

### ISSUE THREAD

**Issue by Rajkumar-9** [opencv/cvat#6436]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi, please check if the `Frame step` parameter helps 
https://opencv.github.io/cvat/v2.4.9/docs/manual/basics/create_an_annotation_task/#advanced-configuration
