### ISSUE TITLE
Online documentation for non-development releases misses SDK API docs

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#6437]
On an older release docs page (basically, any), there is no SDK API models or APIs descriptions available. 

Example: https://opencv.github.io/cvat/v2.4.9/docs/api_sdk/sdk/reference/models/
![image](https://github.com/opencv/cvat/assets/13832349/9bdc9918-5944-4eb6-bd64-009e3ec8e12a)

**Comment by bsekachev** [comment]
It looks like the issue was solved
