### ISSUE TITLE
Error in uploading annotation in yolo format

### ISSUE THREAD

**Issue by ravibdf** [opencv/cvat#6438]
I was trying to upload a dataset that I created in cvat and upload back to cvat. When I upload the same zip file given by cvat, tha annotation doesn't upload, when using the yolo format, but with pascal VOC format the annotations was uploaded.

### Steps to Reproduce (for bugs)

1. Upload in cvat a zip file, created by cvat, with annotation in yolo format.
2. Create a zip file with only the annotations in yolo format and upload them using the upload annotations button.

### Expected Behaviour
When using the zip file in yolo format, just upload all annotations in the right images.

### Current Behaviour
With annotations in yolo format, an error appear

Could not upload annotation for the [task 116](http://localhost:8080/tasks/116)

Error: Request failed with status code 500. "datumaro.components.errors.DatasetNotFoundError: Failed to find dataset at '/home/django/data/jobs/109/tmp/tmp5vyqd0nl'\n"..

### Possible Solution
Change the annotation format to pascal VOC and upload a zip file containing all annotations using the buttom upload annotations.
The error is using the yolo format to upload the annotations, but with pascal VOC format it was just fine.

**Comment by zhiltsov-max** [comment]
Hi, please make sure the uploaded archive has the format described [here](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-yolo/) ([example](https://github.com/cvat-ai/datumaro/tree/v0.3/tests/assets/yolo_dataset)). It's possible that an extra leading dir is added in the archive.
