### ISSUE TITLE
output = response.json()['result'] comes with KeyError: 'result'

### ISSUE THREAD

**Issue by eric4note** [opencv/cvat#6439]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Follow the instruction at https://opencv.github.io/cvat/docs/contributing/development-environment/
1. The Error shows up when accessing localhost:3000

### Expected Behaviour

Allow login without errors

### Current Behaviour

File "/home/username/cvat/cvat/apps/iam/permissions.py", line 170, in check_access
    output = response.json()['result']
KeyError: 'result'

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05): the latest development version of CVAT on Jul 1, 2023
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi. If you're using a local dev environment, it's possible that OPA is not reachable on some platforms. Please try to start it this way:

```
docker run -d --rm --name cvat_opa_debug -p 8181:8181 -v ${PWD}/cvat/apps/iam/rules:/rules openpolicyagent/opa:0.45.0-rootless    run --server --set=decision_logs.console=true /rules
```

**Comment by bsekachev** [comment]
@eric4note 
Try to play with options: ``--add-host=host.docker.internal:host-gateway`` and ``--net=host``, adding them to command to start opa container:

```
 docker run -d --rm --net=host --add-host=host.docker.internal:host-gateway --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.45.0-rootless \
 run --server --set=decision_logs.console=true --set=services.cvat.url=http://host.docker.internal:7000 \
 --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules
```

**Comment by eric4note** [comment]
> @eric4note Try to play with options: `--add-host=host.docker.internal:host-gateway` and `--net=host`, adding them to command to start opa container:
> 
> ```
>  docker run -d --rm --net=host --add-host=host.docker.internal:host-gateway --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.45.0-rootless \
>  run --server --set=decision_logs.console=true --set=services.cvat.url=http://host.docker.internal:7000 \
>  --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules
> ```

At the nodejs end, we run into the following problem
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:3000/api/server/health/?format=json&org= to http://localhost:7000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by zhiltsov-max** [comment]
Please make sure there a 2 running containers: `cvat_db` and `cvat_opa_debug`. You can try to use the regular `cvat_db` container: `docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d cvat_db`. You'll need to make sure the migrations are applied: `python manage.py migrate`.
