### ISSUE TITLE
Cannot upload annotation, may be an issue with unzip

### ISSUE THREAD

**Issue by yf-yang** [opencv/cvat#6443]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When I upload a dataset annotation zip file to a task reated by connected file share, it reports 
```
Request failed with status code 400. "Could not match item id: '47441408973' with any task frame"
```
Actually, this frame exists and when I exclude this frame from my annotations, other frame will report the same error.

Contexts:
- this is a image labeling task
- I am uploading annotations of `Pascal VOC 1.1` format

I found some interesting facts:
1. This task has multiple dataset folders (from the connected file share), it seems when I create a task that contains exactly one folder, the issue will not happen.
2. If I upload an annotation zip file with only one frame (exactly the frame that reports the error), the issue will not happen.
3. (needs test), if I create a multiple-folder task and upload only one folder of annotations, will the issue happen?
4. If I export the annotation file in Pascal VOC 1.1 format, then upload the zipfile back, the issue will not happen.
5. If I export the annotation file in Pascal VOC 1.1 format, then unzip the file, then zip the folder again (using MacOS V13.2.1's finder's builtin zip utility), then upload the zip file, the issue will happen.
6. I've also try to use python's zipfile package in windows/macos, it is similar to fact 1.

Therefore, I suspect it is something related to multiple folder's format in a zip file. May I know how you unzip the file?

**Comment by yf-yang** [comment]
OK, fact 3, when I upload a single folder (it should not be deeply nested) of xml files, there is no issue.

Therefore, I can make a guess that all of the annotation files I want to upload should all map to images that located at the same leaf folder.

**Comment by yf-yang** [comment]
Now the problem is, if I download the annotations and keep it intact and untouched, I can upload it back even if they are from multiple folders, but I cannot unzip and zip it again (fact 4/5)

**Comment by zhiltsov-max** [comment]
Hi, this has probably been improved in #6350 (no public release with this update yet). 

> If I export the annotation file in Pascal VOC 1.1 format, then unzip the file, then zip the folder again (using MacOS V13.2.1's finder's builtin zip utility), then upload the zip file, the issue will happen.

Please note that OS file managers often add an extra leading directory in the archive, and it can confuse the file matching.

**Comment by yf-yang** [comment]
Sure, I'll go back to dev branch and take a look 👍 and give further feedbacks.

**Comment by yf-yang** [comment]
@zhiltsov-max tried with version 2.5, it became even more weird: 
- When uploading multiple folders of annotation files, status code 400 with message 'No such file were uploaded', nothing happens
- When uploading single folder of annotation files, still status code 400 with message 'No such file were uploaded', but the annotations are successfully imported to the task.

The code:
``` python
with make_client(URL, credentials=(username, passwd)) as client:
  task = client.tasks.retrieve(TASK_ID)
  task.import_annotations('PASCAL VOC 1.1', 'tmp.zip')
```

**Comment by yf-yang** [comment]
> @zhiltsov-max tried with version 2.5, it became even more weird:
> 
> * When uploading multiple folders of annotation files, status code 400 with message 'No such file were uploaded', nothing happens
> * When uploading single folder of annotation files, still status code 400 with message 'No such file were uploaded', but the annotations are successfully imported to the task.
> 
> The code:
> 
> ```python
> with make_client(URL, credentials=(username, passwd)) as client:
>   task = client.tasks.retrieve(TASK_ID)
>   task.import_annotations('PASCAL VOC 1.1', 'tmp.zip')
> ```

Nevermind, I forgot to upgrade python sdk

**Comment by yf-yang** [comment]
@zhiltsov-max Upgraded to 2.5, got the same error, I'll show how it occurs:
Suppose a task TASK_ID has multiple folders of images from a connected file share, then

If creating zipfile like this:
``` python
with zipfile.ZipFile('tmp.zip', 'w') as zf:
    for path, content in data_list:
        zf.writestr('tmp/'+PurePosixPath(path).name, content) # all in the same folder, only file names are kept, their parent folders are removed
task.import_annotations('PASCAL VOC 1.1', 'tmp.zip')
```
- If uploading multiple files within the same folder, SUCCESS
- If uploading multiple files from multiple folders, FAIL, *Could not match item id xxx with any task frame*

If creating zipfile like this:
``` python
with zipfile.ZipFile('tmp.zip', 'w') as zf:
    for path, content in data_list:
        zf.writestr(path, content) # following how they are downloaded, path is 'Annotations/xxx' in Pascal format
task.import_annotations('PASCAL VOC 1.1', 'tmp.zip')
```
- If uploading multiple files within the same folder, FAIL, *Failed to find dataset at /home/django/data/tasks/TASK_ID/tmp/tmpld0t7qpa*
- If uploading multiple files from multiple folders, FAIL, *Failed to find dataset at /home/django/data/tasks/TASK_ID/tmp/tmpld0t7qpa*

**Comment by yf-yang** [comment]
☹️ If an additional option is provided, so that uploading only some files will not clear other annotations (if not specified, then clear all of them), I can upload folders of annotations one by one, it could be a workaround.

**Comment by zhiltsov-max** [comment]
I suppose the problem can be in the [CVAT extension to the format](https://github.com/opencv/cvat/blob/develop/cvat/apps/dataset_manager/formats/pascal_voc.py#L43-L55), which allows a simple file layout, since it only supports a flat file structure. Could you please share the file layout of the uploaded archive that reproduces the problem?

**Comment by yf-yang** [comment]
``` python
with zipfile.ZipFile('tmp.zip', 'w') as zf:
    for path, content in data_list:
        zf.writestr('tmp/'+PurePosixPath(path).name, content) # all in the same folder, only file names are kept, their parent folders are removed
task.import_annotations('PASCAL VOC 1.1', 'tmp.zip')
```
Layout:
- tmp
--- name1.xml
--- name2.xml
--- name3.xml

``` python
with zipfile.ZipFile('tmp.zip', 'w') as zf:
    for path, content in data_list:
        zf.writestr(path, content) # following how they are downloaded, path is 'Annotations/xxx' in Pascal format
task.import_annotations('PASCAL VOC 1.1', 'tmp.zip')
```
Layout:
- Annotations
--- connectedFileShareRoot
----- folder1
------- name1.xml
------- name2.xml
----- folder2
------- name3.xml

**Comment by yf-yang** [comment]
Seems to be how datumaro deals with input files. I'm new to the library and am checking the docs

**Comment by yf-yang** [comment]
Finally got it worked!

For others facing similar issue:

The required zipfile layout:
```
- Annotations
|-- connectedFileShareRoot
|  |-- folder1
|  |  |-- name1.xml
|  |  |-- name2.xml
|  |-- folder2
|  |  |-- name3.xml
- ImageSets
|-- Main
|  |-- default.txt
```
Within default.txt:
```
connectedFileShareRoot/folder1/name1
connectedFileShareRoot/folder1/name2
connectedFileShareRoot/folder2/name3
```
Reference: [datumaro doc](https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/pascal_voc.html#import-pascal-voc-dataset)
---
The reason that I unpack a downloaded Pascal VOC zip at MacOS, then zip it again, then upload it and fails (fact 5):
After unzip the file, MacOS added another folder, so it becomes `<zipfileName>/Annotations` and `<zipfileName>/ImageSets`. If directly cd into `<zipfileName>` and zip those two folders, then those two folders can be successfully uploaded.
---
@zhiltsov-max the doc [here](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-voc/#pascal-voc-import) is still the flat version, it works for single folder scenario, but for more complex scenario, maybe follow datumaro's spec is better.

This issue can be closed 👍 . Thanks for your efforts!
