### ISSUE TITLE
Export Dataset for Unet

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6446]
I am a paid pro subscriber...

Unet requires segmentation masks where the value of each pixel corresponds to the class.

What would be the proper export format? I've looked into the documentation and can't find ... 

Many thanks for the help!

**Comment by DaveBGld** [comment]
Paid subscriber with NO SUPPORT! 

I'll be moving to something else and cancelling...

Thanks!

**Comment by zhiltsov-max** [comment]
Hi! There are several formats that you can use:
- [Segmentation Mask (aka PASCAL VOC segmentation)](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-voc) - the "simplest" one with class and instance masks
- [CamVid](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-camvid) - also simple, similar to PASCAL VOC
- [Cityscapes](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-cityscapes) - with several different label encodings available
- [KITTI](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-kitti) - also has several label encodings, including simple RGB
- [MOTS](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-mots) - for segmentation tracks
- [Datumaro](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-datumaro)
