### ISSUE TITLE
Changes not visible after containers build

### ISSUE THREAD

**Issue by ASAADASKAR** [opencv/cvat#6448]
I changed something in CVAt and then updated the docker but I can't see the changes.

I would be very grateful for help.

Thank you

**Comment by RoutineZ** [comment]
How to solve this problem?  Thanks

**Comment by ASAADASKAR** [comment]
@RoutineZ 
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
 docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d`
