### ISSUE TITLE
converter.py outputs wrong labels unless labels supplied explicitly with no warning

### ISSUE THREAD

**Issue by LukeAI** [opencv/cvat#645]
I have downloaded the cvat xml files and tried to convert them to Yolo format.
I found that running:
`./converter.py --cvat-xml ~/data_collection/image_annotations/11_007.xml --image-dir ~/data_collection/yolo/run2_cam_front_bottom_centre/ --output-dir .`
generated labels as expected but the class_id (first field - an integer) was just some random number that didn't have a relationship with the order of labels.

Running the converter with the labels explicitly stated, solved the issue.
`./converter.py --cvat-xml ~/data_collection/image_annotations/11_007.xml --image-dir ~/data_collection/yolo/run2_cam_front_bottom_centre/ --output-dir . --labels Car,Person,Truck,Bus,Traffic_light,Cycle`

But this cannot be correct behaviour - either the script should use the label order specified when the task was created OR refuse to run, advising me that I need to explicitly provide the order of labels. At the moment it just silently outputs incorrect labels.

I've inspected the top of the XML file and noted that the order of classes as they appear there are correct. I'm using python 3.5 in a virtualenv created especially for this script to run in.

Wild speculation:
I have a suspicion that this behaviour might be because of an assumption that a dictionary of labels maintains it's order, which is true in more recent pythons but not in 3.5.

**Comment by nmanovic** [comment]
@LukeAI , could you please check our new functionality? You can download YOLO format directly from UI in browser. Does it work correctly for you?

**Comment by LukeAI** [comment]
I haven't tried the new functionality - I have a large number of annotations on the current running instance of cvat and the pipeline worked out for exporting them so I don't really want to mess around with any part of that until I'm done with the current jobs, very much looking forward to the new functionality in the near future. Will it also export blank labels for images with no annotations? Will it allow me to download the entire job (images + labels) in one big dump? That would make my process a lot easier :)
