### ISSUE TITLE
Issuse about time of creating containers after editing the path of shared folder

### ISSUE THREAD

**Issue by ShangWeiKuo** [opencv/cvat#6450]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Hello. 
I ran the command **docker compose up -d** after editing the shared folder path in **docker-compose.override.yml** by following with the [tutorial](https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path).

However. There were 4 containers always in creating status as the picture below.
![image](https://github.com/opencv/cvat/assets/26018604/ee1086c8-3732-4c0c-b986-7215a0639b2c)

Is it normal for those containers to cost a large amount of time to be created ?

If not. How should I do to deal with the problem ?

**Comment by azhavoro** [comment]
How we can reproduce the problem?

**Comment by ShangWeiKuo** [comment]
Excuse me. @azhavoro @bsekachev 

Is it possible that this problem occurred because my shared folder was empty ?

**Comment by bsekachev** [comment]
It is not clear how to reproduce the issue, so, unfortunately we can't make any suggestions
