### ISSUE TITLE
Question regarding the measurement of the job duration

### ISSUE THREAD

**Issue by lukazso** [opencv/cvat#6462]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When creating a task, automatically a job is created. The `duration` field in the job is supposed to show the duration a job is being worked on. I would understand this as the time an annotator takes to annotate the images. However, the annotator has not yet annotated a single image, yet `duration` field already shows 22 minutes, which seems to be the time since the job was created by me.  Not sure if this is actually a bug, or if the current behavior is intended. 

### Expected Behaviour
The `duration` field should only show the amount of time spent on actually annotating the job. This means that when the job is opened by the annotator, the time tracking should start. When the job is closed by the annotator, the time tracking should stop.

### Current Behaviour
The job duration does not show the time actually spent on annotating a job. Rather, it seems to show the duration since the job was created.

### Context
I am trying to get some efficiency metrics, e.g. which annotation method is most efficient for my use case. For that, I need to track the time an annotator needs for a specific job.

### Your Environment

- Git hash commit (`git log -1`): 44382be02e98a29c28e9adf42fd7c56bd3bde298
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 23.0.6
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): 20.04.6 LTS (Focal Fossa)

**Comment by bsekachev** [comment]
Please, look at #6466.
``duration`` is useless for your use-case, and maybe even will be removed in the future.

**Comment by bsekachev** [comment]
For self-hosted solutions also currently this kind of analytics available: https://opencv.github.io/cvat/docs/administration/advanced/analytics/

**Comment by lukazso** [comment]
Thank you @bsekachev, the analytics feature will definetely help!
