### ISSUE TITLE
Failing to Run Docker Image - start service cvat_server: failed to create shim task

### ISSUE THREAD

**Issue by jitaxis** [opencv/cvat#6469]
### My actions before raising this issue
-  Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- Searched [past issues](/issues)

I have a fresh download from the GitHub, try to run docker-compose up -d and I get the following error:
![image](https://github.com/opencv/cvat/assets/99373584/ec489cc2-6fe0-4f6a-bc54-4762d9399f5b)

### Steps to Reproduce (for bugs)

1. Download the repository and run docker-compose up -d in the local repositories folder.

### Your Environment

- Git hash commit (`git log -1`): 0c8a46e3
- Docker version `docker version` (e.g. Docker 17.0.05):
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2

- Are you using Docker Swarm or Kubernetes?
Docker
- Operating System and version (e.g. Linux, Windows, MacOS):
Linux

Any help to solve this issue would be greatly appreciated. Thanks.

**Comment by zhiltsov-max** [comment]
Hi. Probably you're using the `develop` branch, which may have changes in deployment comparing to the latest release. Please try to switch to a latest release tag and specify the required version in the environment variable (`git checkout v2.5.0 && CVAT_VERSION='v2.5.0' docker compose -f docker-compose.yml up -d`), or rebuild the containers if you want to use the development version (`docker compose -f docker-compose.yml - docker-compose.dev.yml up -d --build`).

**Comment by jitaxis** [comment]
I could check out the branch v2.5.0 but checked out v2.4.9. I tried running the container and got the following error when loading the webpage.

cvat_db                        | 
cvat_db                        | PostgreSQL Database directory appears to contain a database; Skipping initialization
cvat_db                        | 
cvat_db                        | 2023-07-17 21:00:35.961 UTC [1] FATAL:  database files are incompatible with server
cvat_db                        | 2023-07-17 21:00:35.961 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 15.3.
cvat_db exited with code 1
cvat_opa                       | {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.21.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-07-17T21:00:37Z"}
cvat_db                        | 
cvat_db                        | PostgreSQL Database directory appears to contain a database; Skipping initialization
cvat_db                        | 
cvat_db                        | 2023-07-17 21:00:49.139 UTC [1] FATAL:  database files are incompatible with server
cvat_db                        | 2023-07-17 21:00:49.139 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 15.3.
cvat_db exited with code 1
cvat_opa                       | {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.21.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-07-17T21:00:50Z"}

It would be great if you have any thoughts on what I should do next. 
Thank you for your help.

**Comment by jitaxis** [comment]
I just built again with v2.4.9 somehow it works now. Thanks for the help.
