### ISSUE TITLE
analytics (kibana visualize) : when or how is "object count" refreshed? 

### ISSUE THREAD

**Issue by sanghun-scalawox** [opencv/cvat#6473]
i am visualizing object count line graph. graph by one user, line by task. but i know object count is being refreshed real-time.

as i know, when raise "Send task info" event.

can you let me know what is trigger of "Send task info" event?

Thank you for reading this issue!

**Comment by bsekachev** [comment]
@sanghun-scalawox 
Looks like now this event is not used anymore.

@azhavoro 
Did we miss something or event is outdated? There is the event in the enum on client, but it is not sent anywhere.

**Comment by sanghun-scalawox** [comment]
@bsekachev I'm sorry, I had to say that I am using cvat 2.2.0v.

**Comment by bsekachev** [comment]
We do not support 2.2.0, it is too old.
