### ISSUE TITLE
Major image/chunks transfer slowdown on CVAT (>2.4.5), maybe related to uvicorn/nginx config?

### ISSUE THREAD

**Issue by titarch** [opencv/cvat#6477]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am maintaining a fork of CVAT (deployed with helm on a kubernetes cluster) and I regularly sync with upstream, I recently rebased from version release-2.4.0 to hotfix-2.4.7 and noticed some significant slowdowns for all endpoints retrieving data from the data volume (although it may not be limited to them but it is maybe more noticeable given these endpoints are resulting in the majority of the data transfers).

The most problematic slowdowns are happening when fetching chunks of frames which are 1.5x~2x slower than before, but I also noticed a significant slowdown on the /preview endpoint (up to 10x, around 3s instead of 300ms) when loading a task list view:
![image](https://github.com/opencv/cvat/assets/23527994/bbecd408-b288-4d27-a638-7e46fd498a59)

I saw that there were some major changes regarding the way the data is served, changing from mod_wsgi to uvicorn asgi with some nginx config. This was to me the most probable culprit which is why I reverted and rebased on version release-2.4.5 and the issue went away. This does not confirm for sure that this change alone is responsible as it could be anything between version 2.4.5 and 2.4.7, but I still have strong suspicions it is the new socket config. Do you think this is plausible or something else entirely?

I also noted that performance does not seem to much affected when running locally with docker-compose instead of helm, since the later uses a data volume linked to a SMB fileshare on Azure, throughput is more limited, so if the average network throughput required to run CVAT increased then it could be a reason for the slowdown.

For now I will stick to version 2.4.5 but any help or idea would be very welcome, as I am quite interested by some upcoming features on 2.5.x.
Thanks a lot in advance.

### Steps to Reproduce (for bugs)

1. Deploy CVAT >= 2.4.7 on a cluster and 2.4.5 on another identical cluster
2. Create some tasks
3. Measure the difference in performance between the preview or data endpoints
### Expected Behaviour
Similar or better performance

### Current Behaviour
Significantly degraded performance, slow data transfers, slower global throughput

### Context
Running CVAT 2.4.7 on a kubernetes cluster deployed using a helm chart and with a custom data volume using an Azure SMB file share.

### Your Environment

- Rebased for on top of hotfix-2.4.7 branch
- Docker version 24.0.2
- Are you using Docker Swarm or Kubernetes? Kubernetes
- Operating System and version (e.g. Linux, Windows, MacOS): Linux

**Comment by Zanz2** [comment]
I had simillar issues too, but it could be that it is completely unrelated to yours. Out of curiosity though, how many import pods are you running, and if you exec into the backend server pod and run `python manage.py rqstats` how many import workers does it list?

**Comment by titarch** [comment]
Thanks for the suggestion, I do seem to have a normal import worker config does not appear to do anything, and increasing the chunk size sounds like a hassle given that I would have to re-run the frame extraction on hundreds of tasks.
I would really like to get back the performance of version 2.4.5 on later versions.

**Comment by Zanz2** [comment]
Just to make sure, im talking about the TUS resumable file upload chunk size, this one you cannot set via the task upload form.  I dont know which version you are on but at some point the limit got changed from 100mb to 2mb (im assuming) for compatibility reasons for people on a slower connection (https://github.com/opencv/cvat/pull/6058).
My build (2.4.9) was using the 2MB limit, but since i am on a faster connection I increased it. https://github.com/opencv/cvat/blob/99a6cf9e5e1d1763cfb70fdd43f79c4c53c1d1c8/cvat-ui/src/cvat-core-wrapper.ts#L38 
If you modify this and rebuild just the UI image i found there is a bit less overhead, and it still works fine if you are on a fast connection. It is not a crazy 100% speed up or anything but it helped with my deployment a little. On a unrelated note regarding the workers; I am using the helm deploy version, so the workers i increased by adding the NUMPROCS: 3 environment variable to additionalEnv

**Comment by titarch** [comment]
Yes, exactly. I also have issues downloading the frame chunks for the player which is the biggest problems.
I am using a fork, and depending on which version of CVAT I rebase I get this issue, so I don't think the issues comes from redis.

**Comment by titarch** [comment]
I did a git bisect between v2.4.5 and v2.4.6, I reduced the changed of my fork to only the deployment config and stashed on every step. The result confirmed my intuition as it returned the following commit:
```
87dd7fff928a38a5275ebe4de3793016392e8c0e is the first bad commit
commit 87dd7fff928a38a5275ebe4de3793016392e8c0e
Author: Andrey Zhavoronkov <andrey@cvat.ai>
Date:   Tue May 30 15:24:58 2023 +0300

    Switch to uvicorn (#6195)
```

I will do more experimenting.

**Comment by titarch** [comment]
I have identified the core problem, this is due to the `NUMPROC` environment variable.
The value seems to be 1 by default and is not overridden to anything higher in the helm config.
If I manually set the numproc to something higher, e.g. 4:
```diff
[fcgi-program:uvicorn]
socket=tcp://localhost:8000
command=%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_POSTGRES_HOST)s:5432 -t 0 -- python3 -m uvicorn
    --fd 0 --forwarded-allow-ips='*' cvat.asgi:application
environment=SSH_AUTH_SOCK="/tmp/ssh-agent.sock"
-numprocs=%(ENV_NUMPROCS)s
+numprocs=4
process_name=%(program_name)s-%(process_num)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
```
this seems to give performances closer to what was there before.

Is there anything I am missing that would have made the value of NUMPROCS higher?

**Comment by Zanz2** [comment]
Nice, yeah thats what i meant in my 1st post. the numprocs is the number of workers that i mentioned, it seems like they are at 1 now by default. You can even set it via the helm chart (additionalEnv: NUMPROCS: 4). you can test that they are changed using python manage.py rqstats

**Comment by titarch** [comment]
Right so actually same reason for two different problems, that would be a good way to set it too, I think this should be documented if it is going to remain like that, or a sane default should be added in the values.yaml.

**Comment by Zanz2** [comment]
Yeah, aggree it took me a lot of looking before i found that that was the cause, it is indeed not mentioned anywhere unless you go browsing trough the supervisord .conf files for all the workers

**Comment by bsekachev** [comment]
@azhavoro  Are we using only one process now? Do you think we need to document it?

**Comment by Zanz2** [comment]
From my limited findings it seemed like a bug, the config files state that 3 workers should be spawned, but you only end up with 1
