### ISSUE TITLE
Best Practice to only allow certain people to register

### ISSUE THREAD

**Issue by Hegelim** [opencv/cvat#6479]
### My actions before raising this issue
- [checked] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [checked] Searched [past issues](/issues)
When I am on the login page
![image](https://github.com/opencv/cvat/assets/55818214/7e64a2a6-adc4-4c32-89b1-e0c15bba1ede)
Basically everyone can register. For privacy concerns, I am wondering if there is a way to only allow certain people to register? Because of my limited knowledge of front-end tech stack, please recommend simple, effective solutions. 

### Steps to Reproduce (for bugs)

Follow the installation guide.

### Possible Solution

Several ideas that I have:
1. disable the login page completely. Only give credentials to certain people through backend (don't like it, feel like cheating)
2. somehow people who are not authorized cannot register (don't know how to do that)

### Your Environment

- Git hash commit (`git log -1`): 44382be02e98a29c28e9adf42fd7c56bd3bde298
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.4
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Centos

**Comment by bsekachev** [comment]
You can remove/disable ``/api/auth/register`` endpoint on backend. 
After that users can still be added throught admin panel
