### ISSUE TITLE
Can we directly deploy a Tensorflow2 Mask_RCNN model saved file (.pb format ) into Nuclio?

### ISSUE THREAD

**Issue by Abhirao024** [opencv/cvat#6481]
Can we directly deploy a Tensorflow2 Mask_RCNN model saved file (.pb format ) into Nuclio?(We are configuring CVAT serverless on a Windows-GPU machine) 

Do we need to convert  saved file (.pb format ) to openvino format ? or its not required?

Also i would appreciate if you could share any examples

_Originally posted by @Abhirao024 in https://github.com/opencv/cvat/issues/6427#issuecomment-1635362477_

**Comment by bsekachev** [comment]
You do not need to convert it to OpenVINO format.

**Comment by Abhirao024** [comment]
Thank you for your help. I really appreciate it.

Also i cant see that Model tab after installing the Serverless CVAT, Are there any steps that I am missing?

> You do not need to convert it to OpenVINO format.

Thank you for your help. I really appreciate it.

Also i cant see that Model tab after installing the Serverless CVAT, Are there any steps that I am missing?

**Comment by bsekachev** [comment]
Please, read the installation guide https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/

**Comment by Abhirao024** [comment]
Thank you Boris,

In the below link the path it is pointing for a MASK_RCNN.h5 file, however in our case we are wanting to use a model that we have already trained and is in .pb (saved file) tensorflow2 model.

https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L1820 

Could you please guide us on what all changes we have to make?

**Comment by bsekachev** [comment]
Model format totally is not important. Just install Tensorflow and write inference script in the serverless container. I cannot help here, I am not DL expert
