### ISSUE TITLE
Storage content fetching failed error when creating a task without a manifest

### ISSUE THREAD

**Issue by lubin-liu** [opencv/cvat#6484]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When I attempt to navigate folders in cloud storage during task creation, for some folders (but not others) clicking on the folder returns a `Storage content fetching failed Error: Request failed with status code 400. "content".` error message. There does not appear to be any pattern pertaining to which folders work and which doesn't.

### Steps to Reproduce (for bugs)

1. Click create a new task
2. In 'Select files', select 'Cloud Storage' 
3. In 'Select data source', select 'All files'
4. Clicking on some of the folders return a `Storage content fetching failed Error: Request failed with status code 400. "content".` error

### Expected Behaviour

Be able to go into the folder in cloud storage without encountering an error. 

### Your Environment

- Git hash commit (`git log -1`): a63f0f10aaab813565eeb24a19852c23fcc7e002
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.4
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): linux 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by dustycodes** [comment]
I am also running into this. If I debug it in the django REST framework with the Content V2 extra action it works. I haven't figured out a way to get this request on the front end yet though

**Comment by stefan-veriphy** [comment]
Also experiencing this issue.

**Comment by tailaiw** [comment]
Same here. In this same S3 bucket, some directory is file while some are not. I couldn't figure out what caused the issue.

**Comment by angarsky** [comment]
Version: v2.7.4
Env: docker-compose on AWS EC2

I see the same issue: only files/folders from the root of a bucket is visible without the specified `manifest.jsonl`. If I try to go deep into any folder - 400 error.

**Workaround**: but the good news is that you can select folder from the root and all files will be loaded into CVAT recursively. So, it's still possible to use.

Can the `manifest.jsonl` file be generated without a cloning of the bucket to local machine (or somewhere to instance)? I guess most of us would like to manage dataset files remote only. I understand that the `manifest.jsonl` is dedicated to improve performance - I just shared my opinion that some users would like to manage their dataset remotely.

**Comment by dimakan** [comment]
same hre
