### ISSUE TITLE
centos docker build ui error

### ISSUE THREAD

**Issue by liudaolunboluo** [opencv/cvat#6486]
erro info：
```
Step 17/26 : RUN yarn install --ignore-scripts --frozen-lockfile
 ---> Running in 7201a21f5a12
node[6]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb7a940 node::Abort() [node]
 2: 0xb7a9be  [node]
 3: 0xbe98be  [node]
 4: 0xbe99a1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb38f5b node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb395ab node::Start(int, char**) [node]
 7: 0x7fd2bb9f318a  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fd2bb9f3245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xabbdee _start [node]
Aborted (core dumped)
```
becase  Conflict between node:18.16 and centos,so turn into  FROM node:18.16-bullseye-slim AS cvat-ui ,it works，

plz fix it

**Comment by bsekachev** [comment]
Hi @liudaolunboluo 

Thank you for the report, but CentOS is not supported by our team.

**Comment by bsekachev** [comment]
@liudaolunboluo 

There is not CentOS mentions in the [installation guide](https://opencv.github.io/cvat/docs/getting_started/).
![image](https://github.com/opencv/cvat/assets/40690378/e172d767-5602-4257-96a7-c95eb2918c4f)

**Comment by liudaolunboluo** [comment]
oh，If you support windows 10 why can't you support centos, there are still a lot of centos users out there, please think about it!

**Comment by liudaolunboluo** [comment]
> @liudaolunboluo
> 
> There is not CentOS mentions in the [installation guide](https://opencv.github.io/cvat/docs/getting_started/). ![image](https://user-images.githubusercontent.com/40690378/253881892-e172d767-5602-4257-96a7-c95eb2918c4f.png)

oh，If you support windows 10 why can't you support centos, there are still a lot of centos users out there, please think about it!
