### ISSUE TITLE
export image classification dataset

### ISSUE THREAD

**Issue by shaojun** [opencv/cvat#6488]
I'm doing image classification job.
I've been able to `Tag label` each image to a class:
![image](https://github.com/opencv/cvat/assets/3241829/8f13ae66-c495-4ad8-9a51-af613123f68d)
Question: which export format can satisfy that put different class of images into different folders (I have total 4 clasess, that should generate 4 folders, and put images into them seperately)

**Comment by bsekachev** [comment]
I am not sure we have such format. 

@zhiltsov-max What do you think?

**Comment by zhiltsov-max** [comment]
Hi, please check the ImageNet format. You will need to export dataset (i.e. include images) to obtain the desired file layout.
