### ISSUE TITLE
slow to open

### ISSUE THREAD

**Issue by qybing** [opencv/cvat#6496]
Follow the deployment steps and the deployment is successful, but when the dataset is uploaded and opened, when doing labeling tasks, the response is very slow, saving the marked information is also very slow, and the response is also very slow when switching to the next picture. Where is it? something went wrong

**Comment by bsekachev** [comment]
Please, be more specific. "very slow" is not easy to investigate.

**Comment by qybing** [comment]
> Please, be more specific. "very slow" is not easy to investigate. What dataset? What resolution do image have? What is chunk size when creating a task? How many annotations are you trying to create? What is your version, how did you deploy it? Also, please, fill the issue template.

data:custom data set;
version:2.4.6;
resolution：2k;
label:23;
deployment command：docker-compose up -d;
When I save the annotation result, it prompts saving changes on sever, but it takes 3 or 4 seconds for the save to succeed

**Comment by bsekachev** [comment]
First of all, try the newest version. If it does not help, please provide us request details (body and time details). You can find everything on Network tab of the chrome dev tools. Just open it before making a request.
Can you reproduce it on app.cvat.ai?

**Comment by bsekachev** [comment]
Additionally, I can say that we implemented advanced client-side caching on app.cvat.ai to reduce number of server requests. I will close the issue.
