### ISSUE TITLE
CVAT Annotation Communication Plugin

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#6510]
Does CVAT currently have a built-in communication plugin? If there is a communication plugin that can annotate and communicate within the platform, it will be 
![image](https://github.com/opencv/cvat/assets/135221549/c4979102-27f9-47fc-bd1e-1ebe449260f5)
greatly helpful for the team to work together remotely

**Comment by bsekachev** [comment]
What do you mean when you speak "communication plugin"? CVAT has issues in review mode: https://opencv.github.io/cvat/docs/manual/advanced/review/
