### ISSUE TITLE
User login prompt

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#6511]
Can CVAT add user login prompts and enable each user to select and view login prompts through a switch

**Comment by bsekachev** [comment]
What do you mean?

**Comment by KTXKIKI** [comment]
If a CVAT platform user logs in, can there be a login prompt that shows XX user logging in and enable each user to select and view login prompts through a switch @bsekachev

**Comment by KTXKIKI** [comment]
enable each user to select view login prompts through a switch
