### ISSUE TITLE
PCD format error

### ISSUE THREAD

**Issue by papandadj** [opencv/cvat#6512]
Hello, I've been using the CVAT project recently, and I want to import PCD files into CVAT. I've checked the documentation on 3D formats and adjusted the directory structure to the format below
<img width="890" alt="image" src="https://github.com/opencv/cvat/assets/25424898/57951d3c-9be5-4e49-b7b6-38d8ce737751">

 but it resulted in an error. 
![abc](https://github.com/opencv/cvat/assets/25424898/2ce06f42-2f7e-4edf-bb1e-201f490c52e6)

Could you please provide a working PCD zip file for me? I would like to unzip and check if there are any issues with my directory hierarchy.

**Comment by KTXKIKI** [comment]
https://opencv.github.io/cvat/docs/manual/advanced/contextual-images/#folder-structure

**Comment by papandadj** [comment]
Also not work. 
<img width="707" alt="image" src="https://github.com/opencv/cvat/assets/25424898/2981eac2-7f5e-48e7-951a-85b826dd9921">

**Comment by bsekachev** [comment]
@papandadj 

How can we reproduce the issue? Structure is not matter, something can not be decoded in your archive.

**Comment by papandadj** [comment]
Can you please provide me with a test zip file of PCD? I want to see if it can be uploaded to my local machine.
I'm not very familiar with 3D structures,and I convert the TIF file to a PCD format.

**Comment by bsekachev** [comment]
@papandadj 

https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/tests/assets/test_pointcloud_pcd.zip

**Comment by papandadj** [comment]
Thanks. This work use [test_pointcloud_pcd.zip](https://github.com/opencv/cvat/blob/develop/cvat/apps/engine/tests/assets/test_pointcloud_pcd.zip) . Perhaps there is an issue with my PDC file.
