### ISSUE TITLE
Cvat annotation upload issue for big image datasets "ValueError: could not convert string to float: ''\n".. 

### ISSUE THREAD

**Issue by IuliaIleana** [opencv/cvat#6515]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hello guys, I am trying to upload some annotations for bigger datasets in cvat. I want to upload the annotations in CVAT 1.1 format (XML file). If the dataset has more images, around 440, I get the following error message: "ValueError: could not convert string to float: ''\n".. 

Initially I thought that my xml file has a space in the wrong position and cannot be properly parsed. I checked it using an xml lint program and the file has correct syntax.

I saw that if I lower the amount of images into the dataset to about 100 the issue goes away, but I would like to understand what causes this issue because I need to work with bigger datasets in my project. The issue also does not seem to be caused by images in my dataset, because if I spit it in multiple pieces, and I make a new task for each one of them in cvat, the annotation upload works without issue. 

I work on a local installation of cvat. 

Any idea what could be causing this?

![image](https://github.com/opencv/cvat/assets/82262852/00d79082-3db5-4499-b0e7-3eaaa96e6c1b)

I will also provide a screenshot of my annotation file:

![image](https://github.com/opencv/cvat/assets/82262852/9db099d8-53e3-4a36-b820-3071a4ac47f0)

**Comment by zhiltsov-max** [comment]
Hi, it seems that some numeric value has been split by a newline character, for example: 

```
points="1,
2"
```

Please try checking for such errors.

**Comment by IuliaIleana** [comment]
Thank you! I will try looking into this!

**Comment by IuliaIleana** [comment]
Hello,

I am writing with a follow-up. I analyzed my annotation XML file using Notepad++, looking for illegal \n characters in between the points of the annotation polygons. Did not find anything suspect. Then I tried to reproduce the error by dividing a value by an enter. When I do this, the error message changes and it also mentions the value of the number which was split by a newline character. I will provide screenshots with the results. @zhiltsov-max 
![Picture1](https://github.com/opencv/cvat/assets/82262852/aada06ab-c8df-4e6b-a712-1828720bfd92)

**Comment by bsekachev** [comment]
Hope you solved the issue. Without original annotation file we can't help. I will close the issue.

**Comment by stefan-veriphy** [comment]
Also having this issue, with a large xml file CVAT for images 1.1 format.
Happy to share the annotations file, should I share images as well?

**Comment by stefan-veriphy** [comment]
> ```
> 1320
> ```

Update:
When I was constructing the xml, point elements with no actual points were added. My mistake:

```xml
<image id="0" name="image.jpg">
        <points label="Human" occluded="0" points="" z_order="0" />
    </image>
````
