### ISSUE TITLE
Model Manager issue NameError

### ISSUE THREAD

**Issue by M-crazy** [opencv/cvat#652]
Is this a bug? Multi layer method call error:
Test failed: NameError at line 474: name 'test2' is not defined

Interpretation script:
```
def test2():
    test3()

def test1():
    test2()
```

**Comment by nmanovic** [comment]
@M-crazy , please published here 4 files to debug on our side. Otherwise we cannot help you.

**Comment by M-crazy** [comment]
Thanks for your quick reply.This error is not just for my model, you can use any model you want

**Comment by nmanovic** [comment]
https://stackoverflow.com/questions/24733831/using-a-function-defined-in-an-execed-string-in-python-3

**Comment by M-crazy** [comment]
@nmanovic Thank you for helping to troubleshoot the problem，It's helpful to me

**Comment by M-crazy** [comment]
hi，@nmanovic 
This is a new question

In the Interpretation script，whether I can pre-process my input before detect？

**Comment by nmanovic** [comment]
@M-crazy, it is not implemented for now. Could you please describe your scenario?

**Comment by M-crazy** [comment]
@nmanovic , I use data preprocessing as a new layer，now it works

**Comment by benhoff** [comment]
It would be worth adding this limitation directly to the Auto Annotation README.

I believe this is an issue with using `exec` and the scoping of that call. On way to get around this limitation is to create a class, and put all the methods in the class. This allows multi-level method calling as the scope is controlled by the class itself.

**Comment by nmanovic** [comment]
@M-crazy , I will close the issue for now. I believe it was fixed in the past somehow or workaround methods exist. Don't hesitate to reopen the issue.
