### ISSUE TITLE
Error: Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations".

### ISSUE THREAD

**Issue by erenuito** [opencv/cvat#6522]
### My actions before raising this issue
docker compose -f docker-compose.yml -f docker-compose.dev.yml -f components/serverless/docker-compose.serverless.yml up -d
docker-compose pulldocker-compose pull
nuctl get functions
and I connected to localhost:8080 .
I login and I tried to use SiamMask.

 (nuclio get functions) nuclio    | pth-foolwood-siammask                                  | cvat    | error    |         0 | 1/1   
(try to use siammask )
Tracker initialization error
Error: Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations".

### Your Environment

- Git hash commit (`git log -1`):
-Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2
- I am using docker
- Linux Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
![Screenshot from 2023-07-19 15-59-46](https://github.com/opencv/cvat/assets/115638862/753200c3-80b4-431b-9105-ae11fc85bdf7)
![Screenshot from 2023-07-19 16-01-58](https://github.com/opencv/cvat/assets/115638862/583f6a18-4f6c-4d45-9690-361b68065a25)
![Screenshot from 2023-07-19 16-03-03](https://github.com/opencv/cvat/assets/115638862/1e1e15f7-8c74-4d59-9bf5-6eee67ac0c43)

Please help me... I am beginner at these topics. (cvat, docker, nuclio etc.) please explain me clearly. I dont understand many things. Tell me What should I do as tell a st*pid person..

**Comment by bsekachev** [comment]
Dublicate of #6523
