### ISSUE TITLE
Tracker initialization error , Error: Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations".

### ISSUE THREAD

**Issue by erenuito** [opencv/cvat#6523]
### My actions before raising this issue
docker compose -f docker-compose.yml -f docker-compose.dev.yml -f components/serverless/docker-compose.serverless.yml up -d
docker-compose pulldocker-compose pull
nuctl get functions
and I connected to localhost:8080 .
I login and I tried to use SiamMask.

 (nuclio get functions) nuclio    | pth-foolwood-siammask                                  | cvat    | error    |         0 | 1/1   
(try to use siammask )
Tracker initialization error
Error: Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations".

### Your Environment

- Git hash commit (`git log -1`):
-Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2
- I am using docker
- Linux Ubuntu 20.04
- ➜ docker version
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~20.04.2
 Built:             Thu Apr 27 05:56:19 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~20.04.2
  Built:            Thu Apr 27 05:37:01 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.12-0ubuntu1~20.04.3
  GitCommit:        
 runc:
  Version:          1.1.4-0ubuntu1~20.04.3
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
![Screenshot from 2023-07-19 15-59-46](https://github.com/opencv/cvat/assets/115638862/753200c3-80b4-431b-9105-ae11fc85bdf7)
![Screenshot from 2023-07-19 16-01-58](https://github.com/opencv/cvat/assets/115638862/583f6a18-4f6c-4d45-9690-361b68065a25)
![Screenshot from 2023-07-19 16-03-03](https://github.com/opencv/cvat/assets/115638862/1e1e15f7-8c74-4d59-9bf5-6eee67ac0c43)

Please help me... I am beginner at these topics. (cvat, docker, nuclio etc.) please explain me clearly. I dont understand many things. Tell me What should I do as tell a st*pid person..

**Comment by bsekachev** [comment]
``docker logs nuclio-nuclio-pth-foolwood-siammask`` ?
