### ISSUE TITLE
Nuclio - Deploy a function in the Dashboard without access into the Internet

### ISSUE THREAD

**Issue by RoseDeSable** [opencv/cvat#6530]
Hello guys,
 I receive this error message, when I want to deploy a function by the webgui of nuclio. 

"error response from daemon: Get "https://quay.io/v2/": dial tcp: lookup quay.io on x.x.x.x:53: no such host"

My collegue downloaded the images, that nuclio wished. But with no effort. The error always occurs. Because we are an enterprise, we wan't, that an application downloads content of external sources. 

Now my questions:

1) What for global options can we set in nuclio, to prohibit downloads from external ? 

2) Offers nuclio the possibility to download the wished content by an internal mirror ?

Best Regards
Rose

**Comment by bsekachev** [comment]
Hi @RoseDeSable 
Try to address your question to nuclio team. It is a 3rdparty product. They also have GitHub.

**Comment by RoseDeSable** [comment]
Ok,
 now I directly contacted the team of nuclio. 

Thanks
Rose
