### ISSUE TITLE
Restricting Dataset Export for Specific User Groups

### ISSUE THREAD

**Issue by Daydream3r** [opencv/cvat#6531]
- [Y] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [Y] Searched [past issues](/issues)

Currently, all users have access to the "Export as a dataset" function for all tasks. However, we need to restrict this functionality to only certain user groups. This way, we can ensure that only authorized users have the ability to download datasets, while allowing all users to view tasks and perform annotations. Any guidance on how to achieve this would be highly appreciated. Thank you!

**Comment by bsekachev** [comment]
> Currently, all users have access to the "Export as a dataset" function for all tasks

This is not true. Export as a dataset for a task is available only for task owner, task assingee, project owner and project assignee.
If the task is in an organization, also for organization owner and maintainer. And for any user who has ``admin`` role.

**Comment by bsekachev** [comment]
In general if you want to modify any permissions, you need to modify rego rules in this directory ``cvat/apps/iam/rules`` and then rebuild CVAT. 

This [article](https://www.cvat.ai/post/cvat-open-policy-agent) also can be useful, but outdated a little bit.

**Comment by lxy5513** [comment]
FIRSTLT:   
change two rego file:
(apps/iam/rules/jobs.rego 
apps/iam/rules/`tasks.rego)   

```python
@@ -156,7 +156,6 @@ allow {

 allow {
     { utils.VIEW,
-      utils.EXPORT_DATASET, utils.EXPORT_ANNOTATIONS,
       utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_METADATA
     }[input.scope]
     utils.is_sandbox
@@ -165,7 +164,6 @@ allow {

 allow {
     { utils.CREATE, utils.DELETE, utils.VIEW,
-      utils.EXPORT_DATASET, utils.EXPORT_ANNOTATIONS,
       utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_METADATA
     }[input.scope]
     input.auth.organization.id == input.resource.organization.id
@@ -175,7 +173,6 @@ allow {

 allow {
     { utils.VIEW,
-      utils.EXPORT_DATASET, utils.EXPORT_ANNOTATIONS,
       utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_METADATA
     }[input.scope]
     input.auth.organization.id == input.resource.organization.id
@@ -183,6 +180,12 @@ allow {
     is_job_staff
 }

+allow {
+    { utils.EXPORT_DATASET
+    }[input.scope]
+    input.auth.user.privilege == utils.admin
+}
+

allow {
    { utils.EXPORT_DATASET
    }[input.scope]
    input.auth.user.privilege == utils.admin
}
```

SECONDLY  
`docker compose -f docker-compose.yml -f docker-compose.dev.yml build`                                                              

LASTLY  
`docker compose up -d`

**Comment by azadehashouri** [comment]
Hello @lxy5513 ,
Could you help me how you add "return Response(status=status.HTTP_400_BAD_REQUEST)" to the CVAT codes?

I changed cvat/cvat/apps/engine/rules/jobs.rego but still worker users can export tasks.

Thank you in advance.
