### ISSUE TITLE
SAM - instance inside an instance dissapears when I set it to foreground.

### ISSUE THREAD

**Issue by davodogster** [opencv/cvat#6546]
I'm running the self hosted CVAT with a local GPU. I'm annotating my objects using SAM and it works well.

When I set the nested instance to foreground it disappears and I cant see the colour (green). When I set it to background it re-appears. It seems that background and foreground are reversed (for visualisation only) for some reason? This is not good when I export the instances as the will be missing,

Both instances annotated (one hidden on purpose)
![image](https://github.com/opencv/cvat/assets/46079516/2e000ffa-7bdc-4731-9069-e5479637ff78)

Seed (black part) set to foreground, the green instance is not visible.
![image](https://github.com/opencv/cvat/assets/46079516/831d0317-4ee4-4fc8-a64f-858bb4509c8a)

However, it exports correctly as foreground:
![image](https://github.com/opencv/cvat/assets/46079516/562c04a3-1e0e-4467-8ef1-bd7c3c13c3f0)

Seed set to background:
![image](https://github.com/opencv/cvat/assets/46079516/8a3cc685-1d21-40b0-b071-ea0b06635f63)

Thanks

**Comment by bsekachev** [comment]
Hello,
Selected objects always float to the top. When you deselect it, it returns back to the place according to its z order.

**Comment by davodogster** [comment]
When I set it to foreground and hover over the object I am unable to see it, and also unable to click on it.

**Comment by bsekachev** [comment]
@davodogster 

Please, provide any screenshots/gifs. From your first post I see that it floats as expected.

**Comment by davodogster** [comment]
@bsekachev I have screenshots above. It is not intuitive. I set the green instance to foreground and then hover over it with the mouse and it does not float. This does not allow for quality control and inspection of my annotations. I hope you understand the issue and let me know if you don't. Cheers, Sam

**Comment by bsekachev** [comment]
![image](https://github.com/opencv/cvat/assets/40690378/ca9e5463-88c2-4def-a55e-f54ea7e2b3eb)
 On this screenshot green instance (selected), is on the top, so, I am not really understand what is wrong.

**Comment by davodogster** [comment]
@bsekachev Yes, that is before I set the instance to foreground. Afterwards it will not float. It's gone forever and I can only see it on export. Its not useful for quality control. Cheers

**Comment by bsekachev** [comment]
Did you increase current z layer after setting it to foreground? With z-layer N only objects with z position <= N are visible.

<img width="305" alt="image" src="https://github.com/opencv/cvat/assets/40690378/160329d6-ebe9-405b-b14c-03828b4aeab8">

**Comment by davodogster** [comment]
Thanks that works! All sorted
