### ISSUE TITLE
How to filter when using high-level api

### ISSUE THREAD

**Issue by JerryLu991223** [opencv/cvat#6547]
### My actions before raising this issue
- [Done] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [Done] Searched [past issues](/issues)

How to filter when using high-level api.

### Steps to Reproduce (for bugs)

1. client.tasks does not have filter funtion.
2. client.tasks.list() will return all the tasks.
3. Based on the whole tasks, I filter on my own. But when I have many tasks, I guess get all the tasks will be slow, so I want to filter before I use list() funtion.

### Expected Behaviour
How to filter when using high-level api. 

### Current Behaviour
1. Get all the tasks use list() funtion
2. Do the filter on my own.

### Possible Solution
No idea.

### Context
When I have many tasks, I guess get all the tasks will be slow, so I want to filter before I use list() funtion.

**Comment by zhiltsov-max** [comment]
Hi, high-level API in SDK doesn't allow server-side filtering yet, but I agree that it could be a nice extension. You can use low-level API instead:

```python
from cvat_sdk.core.proxies.tasks import Task
tasks = [Task(client, model=task_model) for task_model in client.tasks.api.list(project_id=42)[0].results]
```

or request all the list data and filter via python code (as you probably do now):

```python
tasks = [task for task in client.tasks.list() if task.project_id == 42]
```

**Comment by JerryLu991223** [comment]
Thanks for replying. I still have a question about how to filter when using the low-level api. For example, I want to get the tasks from a given task_id_list. Then how can I use the filter attribute in the low-level list() api?
(tasks, response) = api_client.tasks_api.list(
                project_id=project_id,
                filter = ???,
                page_size=100
            )

**Comment by zhiltsov-max** [comment]
Please read [the documentation]() about the function parameters. There are 2 kinds of filters available - "simple" and "complex" ones. The "simple" ones are equality filters like `project_id`, `name`, `assignee` etc. The "complex" are passed via the `filter` parameter and allow you to use more complex requests in the [json logic](https://jsonlogic.com/) format. There is no detailed documentation about these filters, but you can see an example if you check the request sent (in the developer tools page in your browser, open by the F12 key) or the page url after specifying a task filter on the tasks page.

![image](https://github.com/opencv/cvat/assets/13832349/6c554867-6d21-4095-af74-774ddbea47cf)

**Comment by JerryLu991223** [comment]
Get it. Thanks so much for your help and guidance!
