### ISSUE TITLE
Can multi-users annotate the task same time on cvat offline version? 

### ISSUE THREAD

**Issue by JinanZou** [opencv/cvat#6549]
For the offline version of CVAT. I am wondering if you know how to add different users (who will be using different computers) to a task, so that multiple people can work on a task at the same time.

**Comment by bsekachev** [comment]
Create a task with multiple jobs. To do that, specify "Segment  size" option when creating a task. Segment size is a number of frames within one job. In case of video, also Overlap parameter can be adjusted. Please, refer to the guide to get more details.

Created task will consist of many jobs and each job can be assigned to a dedicated user. This way one task can be annotated by multiple users. Annotating one jobs by several users in parallel, in theory, possible, but strongly not recommended.
