### ISSUE TITLE
[BUG] Server Error (500) when called for api `/api/server/annotation/formats`

### ISSUE THREAD

**Issue by pktiuk** [opencv/cvat#6550]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.Log in to cvat app
2. open `/api/server/annotation/formats` for example in your instance https://app.cvat.ai/api/server/annotation/formats

### Expected Behaviour
get list of formats

### Current Behaviour
I get `Server Error (500)`

### Your Environment

Bug exists on your public instance and on my private instance (2.5.0)

- Other diagnostic information / logs:

[cvat.log](https://github.com/opencv/cvat/files/12144159/cvat.log)

**Comment by bsekachev** [comment]
Thank you for report.
