### ISSUE TITLE
The cvat server will be connected  failed after a while, why this happen?

### ISSUE THREAD

**Issue by bigking20172** [opencv/cvat#6552]
when start the cvat by docker-compose,  the localhost:8080  was working in the beginning , but after a while,  it mat cant connect the server in to the gui, but the  Control panel(admin page) is working fine.  every time i want to use cvat，I need to docker down and restart cvat server.  I want to know the solutions

**Comment by bsekachev** [comment]
Please, fill the issue template and attach logs. Without them it impossible to make any suggestions.
