### ISSUE TITLE
[BUG] cvat-cli returns error when trying to authentificate

### ISSUE THREAD

**Issue by leoc70** [opencv/cvat#6555]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
- [x] Try on local and remote machine
- [x] Check my credentials 

I try to interact with my cvat server from command line with cvat-cli but I get an error when trying to authentificate. 

```
PS D:\> cvat-cli --server-host http://MyServerIp --server-port 8080 --auth MyUsername
Password:
Traceback (most recent call last):
  File "C:\Users\lcoquio\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lcoquio\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\lcoquio\AppData\Local\Programs\Python\Python310\Scripts\cvat-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\lcoquio\AppData\Local\Programs\Python\Python310\lib\site-packages\cvat_cli\__main__.py", line 67, in main
    actions[parsed_args.action](cli, **vars(action_args))
KeyError: None
```

I verified my username and password were correct using the frontend web page. In command line if I enter a wrong password I have a ``` Status Code : 400 Bad Request ``` error which I suppose means the server is responding.

I tried using cvat-cli directly on the server computer. I still have the same error.

### Steps to Reproduce (for bugs)
Call ```cvat-cli --server-host http://MyServerIp --server-port 8080 --auth MyUsername``` 

### Your Environment
- cvat-cli version : 2.4.0
- cvat server version : 
```
Server version: 2.4
Core version: 8.0.0
Canvas version: 2.16.2
UI version: 1.47.1
```
- Docker version : 
``` 
PS C:\Users\Admin> docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Operating System and version : Windows 11 Pro 22H2, OS Build 22621.1992

**Comment by bsekachev** [comment]
```cvat-cli --server-host http://MyServerIp --server-port 8080 --auth MyUsername```

You did not provide actions to be done.
