### ISSUE TITLE
 Project/Task/Job Analytics  Analytics  report container issues

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#6561]
/usr/bin/supervisord -c supervisord/worker.analytics_reports.conf
Error: could not find config file supervisord/worker.analytics_reports.conf    The copy supervisor directory of dockerfile does not include this worker. analytics_ Copying the reports.conf file causes the container command to not find it    Under Windows  wsl  git  arrange

**Comment by azhavoro** [comment]
duplicate of #6562
