### ISSUE TITLE
Some logs (e.g. changeLabel) are not counted on client

### ISSUE THREAD

**Issue by GeorgePearse** [opencv/cvat#6568]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
Start labelling a task, sometimes Changed Label will be recorded in Kibana, sometimes it won't (all other events are counted reliably).

### Context
Trying to pay our annotators, we have a 'per change' rate, and without this information it's going to need to be guess work. 

I'm assuming the fix will be to switch to 2.4 and use the new Grafana dashboard, but wanted to leave this here in case anyone else hits the same problem, or if there were a way to better warn against the use of 2.3 for the Kibana analytics.

**Comment by GeorgePearse** [comment]
In fact here are the logs after I change label. 

![image](https://github.com/opencv/cvat/assets/47161914/c4e66851-d8eb-48c0-b5ac-57bffe0771e5)

vs. delete object

![image](https://github.com/opencv/cvat/assets/47161914/d941ac3f-c447-418e-89c9-98e9ffd37082)

**Comment by GeorgePearse** [comment]
I don't know what causes the difference between label changes that are recorded, and those that aren't. But they're recorded a very small fraction of the time.

**Comment by azhavoro** [comment]
@GeorgePearse 
Hi, 2.3 is too outdated and in the latest versions analytics is completely redesigned with a different stack. https://opencv.github.io/cvat/docs/administration/advanced/analytics/
Unfortunately we don't have the resources to support old versions, please consider upgrading.

**Comment by bsekachev** [comment]
Looks like ``changeLabel`` and set of other logs are not counted but exists even if our develop branch and the latest releases.

**Comment by GeorgePearse** [comment]
Any update on when this is likely to be resolved? Can't really get more annotations completed until it is. Thanks a lot!

**Comment by bsekachev** [comment]
Should be fixed in the latest release
