### ISSUE TITLE
Pro vs self-hosted: number of annotators supported

### ISSUE THREAD

**Issue by lukasugar** [opencv/cvat#6574]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

For the managed pro solution, the maximum number of members is 3 ([link](https://www.cvat.ai/pricing/cloud)).
Is there a limit on the number of members when using self-hosted community solution?

I'd need to have ~10 members. Is that possible with the self-hosted community version?

**Comment by bsekachev** [comment]
Basically CVAT is open source product. There could not be any limitation for self-hosted solution since you can always modify the code, so, the answer is yes, it is possible.
