### ISSUE TITLE
Detection error occurred Request failed with status code 503. "HTTPConnectionPool(host='host.docker.internal', port=51603): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0f468250>: Failed to establish a new connection: [Errno 111] Connection refused'))".

### ISSUE THREAD

**Issue by AjmalShahbaz** [opencv/cvat#6582]
### My actions before raising this issue
- [yes ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ yes] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by AjmalShahbaz** [comment]
The above mentioned issue occurs when I try to run custom yolov5 model for auto annotation tool. I have used auto-annotation tool for same model before. It suddenly started to show the above mentioned error. I have tried all the trouble shooting mentioned in older issues. Anyone had the similar issue recently?

**Comment by bsekachev** [comment]
Try to delete and re-deploy the model with nuclio

**Comment by bsekachev** [comment]
What things from other issues did you try to fix it?

**Comment by AjmalShahbaz** [comment]
Hi Boris, 
Thank you for your reply. 
I have checked several threads here or somewhere else to fix the error:
https://github.com/opencv/cvat/issues/4904
https://github.com/opencv/cvat/issues/5205
or the links mentioned in the above links.

I have tried everything that could be done to fix this. 
- adding ip address in host-gateway
### extra_hosts:
      - "host.docker.internal:host-gateway"
- checking firewall setting
- resetting network setting
- redeploying model several times
- reinstalling cvat several times
- reinstalling cvat dependencies like docker several times

Thank you.

**Comment by bsekachev** [comment]
What port the function is working on? 
You can check that using "nuctl get function".

Are you trying to run the model online (on a single frame) or offline (on the whole task)?

**Comment by AjmalShahbaz** [comment]
The ports are different. Nuclio function is deployed at 51297. and docker is ported at 51603. 
I tried to redeploy/ restart as well. but no good. 
I have tried on single frame and whole task. I am running cvat locally on windows 11.

**Comment by bsekachev** [comment]
How are you trying to re-deploy? Did you try to delete the previous function first?

**Comment by AjmalShahbaz** [comment]
yes delete previous function first and deploy as a new function.

**Comment by AjmalShahbaz** [comment]
Hi Boris, 
I solved it. 
Main problem was port numbers were different on nuclio and docker. 
I predefined my choice of port number while deploying the function on nuclio. 
In function.yaml, 
I added:
attributes:
      port: [my own choice]

Details can be found here: 
https://nuclio.io/docs/latest/reference/triggers/http/

**Comment by Petros626** [comment]
@AjmalShahbaz could you assist me to solve this problem too? When it's the port number how can I change it, that it works?

**Comment by AjmalShahbaz** [comment]
Hi, in yolov5 serverless function, there is a file named, 'function.yaml' or 'function.yaml'. In that file, find this part, 

_triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB
        port: 12345
 
The port number here is what I specified by my choice. This solved my issue. Hope this helps!

**Comment by Petros626** [comment]
@AjmalShahbaz ,

thank you for the quick reply.

your port number is randomly choosed or did you do a mapping from `nuclio` to `docker` with specifying in each `function.yaml` a new port?

I got these ports for the model in nuclio:
![port numbers](https://github.com/opencv/cvat/assets/62354721/93707f57-a01f-45b9-915c-409a95d0e870)

and this ports in docker:
![image](https://github.com/opencv/cvat/assets/62354721/ad2f8309-7100-4275-9b1d-f27a2ed5a4d8)

So before building the models with `nuctl` I have to add the docker ports in `function.yaml`, but how can I guess which port it is? During the building process a port is assigned from docker?

**Comment by AjmalShahbaz** [comment]
The port number is my choice. It can be any number you want. 
If you see in pictures, nuclio and docker ports are different for same function ( for example,onnx.wongkiu). Hence, the error 503. and this problem only occurs when you try to put more than one function.
When you assign a port number in .yaml file, what happens is that it make sure docker and nuclio communicates on same port number (i.e., assigned same port).

**Comment by Petros626** [comment]
In general I thought I can deploy several models (functions), so that I can use object detection or mask detection. I delete this old functions and then configure every `function.yaml` with a specific port like 1886.

**Comment by AjmalShahbaz** [comment]
you can deploy multiple functions (I do). Just specify port number. Its something I learned in hard way :)

**Comment by Petros626** [comment]
Ah okay, I understand I will apply this what I've understand from your advices and lets see, if I can deploy and use it succesfully :)

**Comment by ganindu7** [comment]
I had the same problem after updating cvat.

My difference is cvat running from a docker container and nuclio running from a kubernetes cluster. 

my deployment looks like this 

```
(TAOPY) g@nvdgx:~/Workspace/sandbox/nuclio-serverless-sandbox/ganindu-tests$ ./deploy.sh nozzlenet_1/
23.10.17 10:17:33.441                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}
Deploying . function...
23.10.17 10:17:33.561                     nuctl (I) Deploying function {"name": "test-nuctl-function-nozzlenet-1"}
23.10.17 10:17:33.566                     nuctl (I) Building {"builderKind": "docker", "versionInfo": "Label: 1.11.24, Git commit: f2a3900d23b92fd3639dc9cb765044ef53a4fb2b, OS: linux, Arch: amd64, Go version: go1.19.10", "name": "test-nuctl-function-nozzlenet-1"}
23.10.17 10:17:33.650                     nuctl (I) Staging files and preparing base images
23.10.17 10:17:33.678                     nuctl (I) Building processor image {"registryURL": "172.16.3.2:5000", "taggedImageName": "nozzlenet-nuclio-v1:latest"}
23.10.17 10:17:33.678     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.11.24-amd64"}
23.10.17 10:17:35.818            nuctl.platform (I) Building docker image {"image": "nozzlenet-nuclio-v1:latest"}
23.10.17 10:17:41.437            nuctl.platform (I) Pushing docker image into registry {"image": "nozzlenet-nuclio-v1:latest", "registry": "172.16.3.2:5000"}
23.10.17 10:17:41.437     nuctl.platform.docker (I) Pushing image {"from": "nozzlenet-nuclio-v1:latest", "to": "172.16.3.2:5000/nozzlenet-nuclio-v1:latest"}
23.10.17 10:17:42.850            nuctl.platform (I) Docker image was successfully built and pushed into docker registry {"image": "nozzlenet-nuclio-v1:latest"}
23.10.17 10:17:42.850                     nuctl (I) Build complete {"image": "nozzlenet-nuclio-v1:latest"}
23.10.17 10:17:50.882                     nuctl (I) Function deploy complete {"functionName": "test-nuctl-function-nozzlenet-1", "httpPort": 30555, "internalInvocationURLs": ["nuclio-test-nuctl-function-nozzlenet-1.nuclio.svc.cluster.local:8080"], "externalInvocationURLs": [":30555"]}
23.10.17 10:17:50.888    nuctl.platform.updater (I) Updating function {"name": "test-nuctl-function-nozzlenet-1"}
23.10.17 10:17:51.166    nuctl.platform.updater (I) Function updated {"functionName": "test-nuctl-function-nozzlenet-1"}
 NAMESPACE | NAME                            | PROJECT | STATE | REPLICAS | NODE PORT 
 nuclio    | test-nuctl-function-nozzlenet-1 | cvat    | ready | 1/1      | 30555     

```

as you can see mine uses ther nodepoprt `30555`

my `docker-compose-override.yaml' used to look like this 

```
services:
  cvat_server:

    environment:
      CVAT_SERVERLESS: 1
      CVAT_NUCLIO_SCHEME: "http"  # Updated value
      CVAT_NUCLIO_HOST: "aisrv.gnet.lan"  # Updated value
      CVAT_NUCLIO_PORT: 30936 # Updated value
      KUBERNETES_SERVICE_HOST: "true"
      CVAT_NUCLIO_FUNCTION_NAMESPACE: "nuclio"

    volumes:
      - cvat_data:/home/django/data:rw

    extra_hosts:
      - "host.docker.internal:host-gateway"

  cvat_worker_annotation:
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cvat_data:
    driver_opts:
      type: none
      device: /mnt/cvat_data
      o: bind


```

and the error I was getting was (I will put only a part of it for brevity)


```
2023-10-17 10:45:54,639 DEBG 'rqworker-annotation-0' stderr output:
[2023-10-17 10:45:54,639] ERROR rq.worker: Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f20c8f38b80>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=30555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20c8f38b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))

```

the intersting bit was where it seem to think the nodeport service was hosted in the docker host port 30555

```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=30555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20c8f38b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

so in a very dodgy way I modified the `docker-compse.override.yaml ` file to (which I know is wrong)

```
  cvat_worker_annotation:
    extra_hosts:
      - "host.docker.internal:172.16.1.19"

```

and this partially fixed the issue where I was not able to automatically label (but still does not work for individual images) 

I'm not a docker power user I just think the `fix` I did is because of some other potential error I made somewhere. can you please  help me point out where could the original problem be. 

Thanks

**Comment by MuHe0826** [comment]
@AjmalShahbaz Hello, I am a beginner of container. Can you tell me the detailed solution to this problem? I can’t find these two files. Thank you very much.
