### ISSUE TITLE
Use temporal annotations as options for spatial annotations

### ISSUE THREAD

**Issue by yiftachbeer** [opencv/cvat#6589]
Hi,
Not sure this is the perfect place for this, but I couldn't start a discussion.

In my project, for each one of my videos, I already have temporal annotations for all of the objects (I know which objects appear in which frames, but not where they are - like a multi-label classification setting). I trust these annotations, and In each frame, I want to also annotate where these objects appear in the image.
Does CVAT have existing functionality that aids me in using these prior temporal annotations and simplifies the annotation process, instead of starting from scratch?

**Comment by bsekachev** [comment]
You can prepare an annotation file with wrong/random positions, but with objects having correct classes on correct frames, upload it, and adjust positions on client.
