### ISSUE TITLE
Error: Test failed: ''itertools" is not defined

### ISSUE THREAD

**Issue by allenxcp** [opencv/cvat#659]
When I import the landmark model(landmarks-regression-retail-0009.xml and landmarks-regression-retail-0009.bin),one error happened:
### Checking request has returned the "failed" status. Message: Exception: Model was not properly created/updated. Test failed: ''itertools" is not defined
 I add  code "import itertools" in the file（ cvat/cvat/apps/auto_annotation/inference.py ）,then rebuild the cvat docker. It work well. 

from .model_loader import ModelLoader
from cvat.apps.engine.utils import import_modules, execute_python_code

### import itertools

def _process_detections(detections, path_to_conv_script, restricted=True): 

@benhoff
@nmanovic

**Comment by benhoff** [comment]
Aww, shoot. My mistake.
Looks like someone already submitted a PR.
https://github.com/opencv/cvat/pull/660
