### ISSUE TITLE
Typo in interface

### ISSUE THREAD

**Issue by kirill-sizov** [opencv/cvat#6591]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

"Createda"

![Screenshot from 2023-07-31 15-29-36](https://github.com/opencv/cvat/assets/43179655/b8b9ae31-37a3-430b-9968-d868e267a326)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Fixed in this #6367
