### ISSUE TITLE
GIS application

### ISSUE THREAD

**Issue by dodler** [opencv/cvat#6595]
How can I use cvat for gis application? I mean at least intergration with google map (use google map for annotation), use shapes etc

**Comment by bsekachev** [comment]
Please, describe your use-case. How do you want to use google maps for annotations? To visualize GPS data or .. ?

**Comment by dodler** [comment]
I would like to visualize existing polygons (with geo coordinates) and add new ones

**Comment by bsekachev** [comment]
I see. Unfortunately right now integration with any maps is not supported.

**Comment by dodler** [comment]
Got it, thanks
