### ISSUE TITLE
CVAT SDK retrieve_annotations only works after download from UI

### ISSUE THREAD

**Issue by AlanBlanchetNeovision** [opencv/cvat#6601]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues) - [most similar](https://github.com/opencv/cvat/issues/6026)

### Steps to Reproduce (for bugs)

Whenever using the piece of code below. The annotations don't seem to want to download or sometimes download but without any good reason.

```python
_, res = project_api.retrieve_annotations(
    "CVAT for images 1.1",
    project.id,
    _parse_response=False,
    action="download",
)
```

I sometimes get HTTP errors but this is not stable.

### Expected Behaviour

The function `.retrieve_annotations` should always return the same result with the same params.

### Current Behaviour

The function sometimes work and sometimes returns HTTP errors.

### Possible Solution

I believe that CVAT caches the annotation ZIP. And whenever the file is in cache, the CVAT SDK is able to download it.
But if the ZIP isn't in cache, then the `retrieve_annotations` method will crash.

Whenever I need to download the annotations from my CVAT SDK, I first download it from the UI, then I relaunch my script and it works.

### Context

I want to retrieve annotations for my images like I can form the CVAT UI.

### Your Environment

- CVAT versions
  - Server version: 2.4.5
  - Core version: 9.1.1
  - Canvas version: 2.16.6
  - UI version: 1.51.1
  - Python SDK: 2.5.0
- Operating System and version: Linux 5.15.0-78-generic #85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zhiltsov-max** [comment]
Hi, the downloading requires several requests, please read [this answer](https://github.com/opencv/cvat/issues/5942#issuecomment-1497066693) about dataset downloading protocol. Everything is the same for downloading annotations. Please also consider using the high-level SDK, which allows downloading annotations and datasets [simpler](https://github.com/opencv/cvat/blob/develop/tests/python/sdk/test_tasks.py#L281-L297).
