### ISSUE TITLE
Paid Pro User Unable to create Task

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6603]
I am a Paid Pro User. When creating a new Task I get an error...

![image](https://github.com/opencv/cvat/assets/16646702/711360a9-4505-46ea-893f-3b359683a3b6)

THE NUMBER OF TASKS IS SUPPOSED TO BE UNLIMITED

![image](https://github.com/opencv/cvat/assets/16646702/b66e51c6-466a-4922-a94d-cf07070c08af)

Thanks!

**Comment by bsekachev** [comment]
Hi @DaveBGld 

Personal **Pro** privileges don't work in context of organizations. You can create unlimited number of projects and tasks in personal workspace with **Pro** account. For organizations there is a **Team** plan. 

Regarding subscription issues, please write to dedicated email support@cvat.ai

**Comment by DaveBGld** [comment]
Hi @bsekachev ! That's not what it says in your advertisement as I posted above. It says unlimited organizations with up to 3 members and Unlimited Tasks! 

It actually appears that it is the team privileges don't work in context of organizations.

DBG
