### ISSUE TITLE
Can't assign task to member

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6605]
I have a CVAT hosted Pro account. 

A team member has two tasks assigned to him two months ago which he can have access without issue, but a new task I assigned 4 hours ago can't be accessed by him.

As a result my project has stopped on its tracks!!! Other people are waiting at great cost.

Many thanks!

**Comment by bsekachev** [comment]
Hi, 

Did you assign tasks for him in organization? (I suppose yes, because it is considered that you can see other users only if you work within the same organization).

So, the main question is: Did he enable organization to access tasks assigned for him?
