### ISSUE TITLE
Exporting task to YOLO 1.1, the label file becomes 0 byte

### ISSUE THREAD

**Issue by prnr** [opencv/cvat#6609]
### My actions before raising this issue
- [O] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [O] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. import custom coco annotation file to task
 [20230724112437283_coco.zip](https://github.com/opencv/cvat/files/12246620/20230724112437283_coco.zip)
2. export to YOLO 1.1 format
[task_test-2023_08_03_03_13_44-yolo 1.1.zip](https://github.com/opencv/cvat/files/12246616/task_test-2023_08_03_03_13_44-yolo.1.1.zip)
3. All labels are blank txt file
![image](https://github.com/opencv/cvat/assets/22967869/6058a6e7-9b00-4f13-9cea-f725c32f3787)

The imported cocojson file contains only B.box data, so I think it is not a problem that polygon is not recognized. Also, since jobs normally display B.box, there seems to be no problem until import, but I think there is a problem with YOLO 1.1 export.
The imported cocojson file is a file exported while working on another platform. Could this be the cause of the problem? (some images have not been annotated)

I've tried a bunch of other coco2yolo tools, but most of them couldn't work normally (no expected results due to env issues etc), and I'm trying to convert them using cvat.

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05):Docker Desktop 4.16.3
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):Windows 11 build 23511

**Comment by HawkingRadiation42** [comment]
im facing the same issue here the label files are blank, did you find any solution for it?

**Comment by njoguamos** [comment]
Same issue over here.

**Comment by khushyrie** [comment]
same issue here

**Comment by njoguamos** [comment]
I ended up using rectangular bounding boxes. I will consider doing object segmentation later.

**Comment by khushyrie** [comment]
I export the dataset into coco format first. Then convert it to yolo using roboflow

**Comment by prnr** [comment]
> im facing the same issue here the label files are blank, did you find any solution for it?

I replaced the work with another tool. I tried many conversion methods with cvat but couldn't solve it.

**Comment by njoguamos** [comment]
> I ended up using rectangular bounding boxes. I will consider doing object segmentation later.

I ended up doing image segmentation instead. 

I exported the masks and converted them to polygons.

Turns out that segmentation is all I needed for my problem.

**Comment by bsekachev** [comment]
1. When you imported COCO to CVAT, it probably was imported as polygons (check on UI how the object is recognized)
2. YOLO format supports only bounding boxes, polygons are ignored -> files are empty

Workaround:
On app.cvat.ai you may now convert polygons to rectangles:
<img width="192" alt="image" src="https://github.com/opencv/cvat/assets/40690378/9dd19c67-e22d-4a81-abc6-5f660e617eb5">
<img width="527" alt="image" src="https://github.com/opencv/cvat/assets/40690378/48f13a09-56c9-4457-a7ea-5bb29c470f63">

Check and save job, export to YOLO.
