### ISSUE TITLE
Lack of precision when zoomed in

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6613]
If I am editing an annotation with polygon while zoomed in, the actual location of the mark when clicking, is off by some pixels....

DBG

**Comment by bsekachev** [comment]
Please, provide example. Description is not clearly gives a chance to understand the problem

**Comment by syangdung** [comment]
<img width="1650" height="942" alt="Image" src="https://github.com/user-attachments/assets/59467bdc-68aa-4e18-bd5e-adf4f71bb33f" />
