### ISSUE TITLE
Click or Hover one left menu when annotating

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6616]
When I am in the annotation window on a job, there is a vertical menu with tools on the left hand side. 

These tools are activated by hovering only. If by mistake I clicked, the tool disappears, and now I need to hover.... 

I think that the UX would be better if the tool is activated also by clicking on it.

Also, I think it would be an improvement if the tool stays active with the same settings even after clicking done or Shift-N so the user con repeat the previous annotation, until esc is pressed, or another tool is selected...

DBG

**Comment by bsekachev** [comment]
The first is clear. About the second one:

> Also, I think it would be an improvement if the tool stays active with the same settings even

Could you clarify? As I remeber it works now exactly this way. If you created a rectangle from external points, than pressing N again it will again create rectangle from external points. Or you mean issue like this one #3474 when an object was created with any automatic tool, on Shift + N is being redrawn as a regular one?

**Comment by DaveBGld** [comment]
@bsekachev  Thank you!
