### ISSUE TITLE
My issue  #6603 Closed? No its not!!

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6617]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Hi @DaveBGld 

Please, send us a letter to support@cvat.ai and describe your problem. 
GitHub issues are for feature requests and bug reports of CVAT as a product in general. It is not about app.cvat.ai subscribtions support.
