### ISSUE TITLE
Paid Pro user, Limited autimatyed annotations?

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6621]
Using the AI tools I got 

![image](https://github.com/opencv/cvat/assets/16646702/97f6b840-88bb-4b1d-b481-368de865bef2)

But in the plan info it says it is unlimited!!

![image](https://github.com/opencv/cvat/assets/16646702/b5594048-e5aa-4a55-b691-9649dc90834a)

**Comment by bsekachev** [comment]
Hi @DaveBGld

Personal **Pro** privileges don't work in context of organizations. You can use automatic annotation without any limitations in your personal workspace. To use it within organization you need **Team** plan. Apologise for being confused if you are.

Also, again I remember you, that regarding subscription issues, please write to dedicated email [support@cvat.ai](mailto:support@cvat.ai).
