### ISSUE TITLE
not be able to import cityscape annotation

### ISSUE THREAD

**Issue by rpl-alan-shangguan** [opencv/cvat#6624]
I downloaded a cityscape format annotation file from cvat, then I imported this file to the same task, but I get this error.

cvat-app.tsx:359 Error: Request failed with status code 500. "Traceback (most recent call last):\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/components/dataset.py\", line 1197, in import_from\n    env.make_extractor(src_conf.format, src_conf.url, **extractor_kwargs)\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/components/environment.py\", line 230, in make_extractor\n    return self.extractors.get(name)(*args, **kwargs)\nTypeError: CityscapesExtractor.__init__() got an unexpected keyword argument 'ctx'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/venv/lib/python3.10/site-packages/rq/worker.py\", line 936, in perform_job\n    rv = job.perform()\n  File \"/opt/venv/lib/python3.10/site-packages/rq/job.py\", line 684, in perform\n    self._result = self._execute()\n  File \"/opt/venv/lib/python3.10/site-packages/rq/job.py\", line 690, in _execute\n    return self.func(*self.args, **self.kwargs)\n  File \"/home/django/cvat/apps/engine/utils.py\", line 260, in import_resource_with_clean_up_after\n    result = func(filename, *args, **kwargs)\n  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n    return func(*args, **kwds)\n  File \"/home/django/cvat/apps/dataset_manager/task.py\", line 914, in import_task_annotations\n    task.import_annotations(f, importer, conv_mask_to_poly=conv_mask_to_poly)\n  File \"/home/django/cvat/apps/dataset_manager/task.py\", line 798, in import_annotations\n    importer(src_file, temp_dir, task_data, **options)\n  File \"/home/django/cvat/apps/dataset_manager/formats/registry.py\", line 36, in __call__\n    f_or_cls(*args, **kwargs)\n  File \"/home/django/cvat/apps/dataset_manager/formats/cityscapes.py\", line 46, in _import\n    dataset = Dataset.import_from(temp_dir, 'cityscapes', env=dm_env)\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/components/dataset.py\", line 1214, in import_from\n    env.make_extractor(src_conf.format, src_conf.url, **extractor_kwargs)\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/components/environment.py\", line 230, in make_extractor\n    return self.extractors.get(name)(*args, **kwargs)\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/plugins/cityscapes_format.py\", line 230, in __init__\n    assert osp.isdir(path), path\nAssertionError: /home/django/data/tasks/38/tmp/tmprdt9jgdn/gtFine/backyards_testing_20230720_VID20230719141002_002100_gtFine_color.png\n"..

**Comment by zhiltsov-max** [comment]
Hi, it seems the `gtFine/backyards_testing_20230720_VID20230719141002_002100_gtFine_color.png` file is missing in the uploaded data.

**Comment by rpl-alan-shangguan** [comment]
I didn't label that image. So when I download cityscape annotation from cvat, it won't include the labelling file of that images. Could CVAT importation ignore that one?
