### ISSUE TITLE
Can I use my own AI model for automatic annotation, and which model formats are supported? Please let me know.

### ISSUE THREAD

**Issue by kirorotarzan** [opencv/cvat#6625]
I am considering using my own AI model for automatic annotation. Is it possible to integrate a custom model into CVAT? If it is possible, please provide the method and the supported model formats.

**Comment by kirorotarzan** [comment]
Also, I want to introduce the annotation model into CVAT.

**Comment by bsekachev** [comment]
Hello, it is possible.

``https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models``

You have a lot of examples in ``serverless/**``.
