### ISSUE TITLE
Label's attribute is changed automatically on the previous frames, when label with track

### ISSUE THREAD

**Issue by AnnaHumeniuk2212** [opencv/cvat#6627]
Label's attribute is changed automatically on the previous frames, if change it for the label on one of frames using track annotation

### Steps to Reproduce (for bugs)

1. Go to the web CVAT
1. Create a project with label (e.g. person) and add attribute with radio button and different attributes for it (e.g. position - sit, stay, go)
2. Create task - add video for it.
1. Label one object using rectangle by two points - track (not shape) and choose for it attribute (e.g. sit)
3. Go to the next frame and change value attribute for this object (e.g. from sit to stay)
4. Return to the previous frame and pay attention to the value attribute

### Expected Behaviour
Label's attribute is changed automatically only on the next frames (not previous), if change it for the label on one of frames using track annotation

### Current Behaviour
Label's attribute is changed automatically on the previous and on next frames, if change it for the label on one of frames (labelling object using rectangle by two points - track and attribute).

Server version: 2.5.2
Core version: 9.3.0
Canvas version: 2.17.1
UI version: 1.54.1
MacOS Ventura  13.5

**Comment by bsekachev** [comment]
Hi @AnnaHumeniuk2212 

Be sure that attribute is mutable.
Immutable attributes have only one of possible values on the whole frames range.

**Comment by AnnaHumeniuk2212** [comment]
Thank you for your help. With mutable function it works fine.
