### ISSUE TITLE
Wrong image order when uploading images to cvat

### ISSUE THREAD

**Issue by TheBurntWaffl3** [opencv/cvat#6630]
I extracted every 5th frame from a 25,000 frame video, resulting in 5,000ish images that I uploaded to cvat. Everything is fine when annotating the images in cvat until I transition past image 999. Instead of going from 999 -> 1004 it goes from 999 -> 10,003, 10,008 etc all the way up to 10,035, where the next frame afterward is 1004. This makes it very difficult to use tracking to annotate the images since the 1000s and 10,000s images are mixed up. I'm going to go ahead and rewrite the name of each frame so that it caps out at around 5,000, but I was curious to know if there was a work around for future uses where I have more than 10,000 frames. Let me know if I need to clarify, I appreciate any help!

**Comment by bsekachev** [comment]
Hi @TheBurntWaffl3 

Append leading zeros to all images names. This way: 00000, 00005, 00999, 10003
From the lexicographical POV (default sorting method), '10003' < '1004'.
