### ISSUE TITLE
CVAT cache management 

### ISSUE THREAD

**Issue by theFilipko** [opencv/cvat#6631]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Environment
Server version: 2.4
Core version: 8.2.0
Canvas version: 2.16.2
UI version: 1.49.3
OS: Windows
Docker: Docker Desktop 4.19.0 (106363), Version: 23.0.5

### Context
Hello guys.
I have a huge dataset of images linked to the CVAT server. I am trying to understand how CVAT works with data and set it to store as little data in its docker as possible. Here is the behaviour I have observed per one 50MB image and 100% image quality:
* "Use Cache = False" -> 63MB docker disk space
* "Use Cache = True" -> 1.7MB docker disk space, after first access 28MB docker disk space

Then I reinstalled the CVAT with the `CACHES.default.OPTIONS.size_limit = 2 ** 34` which is 17Gb (2GB) based on this comment https://github.com/opencv/cvat/issues/3285#issuecomment-857431314. I assumed that the docker disk space would stop growing with accessing more and more tasks/jobs for the first time. But that is not the case. After loading over 200 images, the docker local volumes increased by 6GB. Also, when I loaded all jobs for the first time and afterwards I deleted all images from the local storage from where I linked them, it did not affect CVAT at all and tasks/jobs/images were loaded. 

Can you please explain how CVAT handles data internally? Is there any way to restrict CVAT to grow?

**Comment by theFilipko** [comment]
Hello guys.
After playing for a while with the system, I have new findings:
* The comment https://github.com/opencv/cvat/blob/72fdef4335b5b88743829a58a8c707fe32a6f7b4/cvat/settings/base.py#L473 `# 1Tb` is misleading. We were considering it as Tera BITs, which is wrong! The [Django documentation](http://www.grantjenks.com/docs/diskcache/tutorial.html#djangocache) states it is in BYTEs!
* The changes done to the code in the cvat repo (in this case `cvat/settings/base.py`) prior to building docker were not passed in!!! I mean, when the CVAT was build and up and running, in the `cvat_server` container the CACHE size limit was still set to `2 ** 40`. Good thing though is that after changing it directly in the container, it remained there after the restart.

**Comment by bsekachev** [comment]
> We were considering it as Tera BITs, which is wrong! 

Nobody measures disk space in kbit, mbit, etc IMHO :) 

> The changes done to the code in the cvat repo (in this case cvat/settings/base.py) prior to building docker were not passed in!!!

To rebuild docker with your local changes: ``docker compose -f docker-compose.yml -f docker-compose.dev.yml build``. Otherwise you will use prebuild images from dockerhub.

**Comment by theFilipko** [comment]
> Nobody measures disk space in kbit, mbit, etc IMHO :)

Yeah, you are right :D 

> To rebuild docker with your local changes: `docker compose -f docker-compose.yml -f docker-compose.dev.yml build`. Otherwise you will use prebuild images from dockerhub.

Here's the script we are using to build CVAT. However, after the installation, scripts in the 'cvat_server' container are not modified, but they are modified locally in the repo.
```shell
#!/bin/bash
version='2.4.0'
file_share='/c/CVAT/acq_data'
host='vh22110301'

# get the latest version of CVAT
git clone https://github.com/opencv/cvat.git

# checkout the desired version
cd cvat
git fetch
git checkout -b v$version origin/release-$version

# add docker-compose.override.yml file
echo -e "version: '3.3'" > docker-compose.override.yml
echo -e "" >> docker-compose.override.yml
echo -e "services:" >> docker-compose.override.yml
echo -e "   cvat_server:" >> docker-compose.override.yml
echo -e "       volumes:" >> docker-compose.override.yml
echo -e "           - $file_share:/home/django/share:ro" >> docker-compose.override.yml 
echo -e "   cvat_worker_import:" >> docker-compose.override.yml
echo -e "       volumes:" >> docker-compose.override.yml
echo -e "           - $file_share:/home/django/share:ro" >> docker-compose.override.yml

# change cvat/apps/engine/views.py to disable export
sed -i '/def _export_annotations/Q' cvat/apps/engine/views.py
echo 'def _export_annotations(db_instance, rq_id, request, format_name, action, callback, filename, location_conf):' >> cvat/apps/engine/views.py
echo -e '\treturn Response(data="Für das MeRu Projekt wurde das Exportieren von Daten deaktiviert.", status=status.HTTP_403_FORBIDDEN)' >> cvat/apps/engine/views.py

# change cvat/apps/iam/urls.py to disable registration
sed -i "/path('register', RegisterViewEx.as_view(), name='rest_register')/d" cvat/apps/iam/urls.py

# set the cache to 1GB -> exponent is 30
sed -E -i "s/('size_limit'\s*:\s*)2 \*\* [0-9]+/\12 \*\* 30/" cvat/settings/base.py

# build images and start docker
docker compose -f docker-compose.yml -f docker-compose.dev.yml build
export CVAT_HOST=$host
docker compose up -d
```

**Comment by theFilipko** [comment]
Nope, running `docker compose down` before `docker compose up` doesn't work :(

**Comment by theFilipko** [comment]
Hello. Has this been fixed? The `cvat/cvat/settings/base.py` has been changed. What is the current cache size limit?

**Comment by theFilipko** [comment]
Hello :) How does the CVAT cache management works now?

**Comment by bsekachev** [comment]
@theFilipko 

Cache in RAM: https://github.com/opencv/cvat/pull/6773
