### ISSUE TITLE
How to work with huge images in CVAT

### ISSUE THREAD

**Issue by darkAlert** [opencv/cvat#6633]
We are trying to annotate panoramic images at 3800x1200 resolution (tracking task), but some annotators faced the problem of cvat freezing when changing chunk (size 50). CVAT is deployed on our own server, it has sufficient computing power. During a chunk change, the server generates huge outbound traffic. So those guys who do not have a very wide Internet channel begin to experience problems.

Could you please give some advice on how to deal with this? Maybe there is an option to pre-download all the data in the cache to the local machine? Since the tracking task requires sequential actions, freezing greatly complicates the work.

p.s. we cannot reduce the resolution or quality of the images

**Comment by vladyskai** [comment]
I have a similar problem. My images have very thin lines that are not being displayed properly. Because of this navigating the large image becomes very cumbersome.

**Comment by bsekachev** [comment]
We implemented advanced client-side cache and deployed it on https://app.cvat.ai. It is available for anyone.

**Comment by darkAlert** [comment]
> We implemented advanced client-side cache and deployed it on https://app.cvat.ai. It is available for anyone.
great! thank you! 
Is it possible to deploy it from source at the moment?

**Comment by bsekachev** [comment]
It was not open sourced currently. We will look, whether it is possible in the future. And it will not work without enabled HTTPs (browser security politics requirement).

**Comment by Kaoukaou** [comment]
> great! thank you! Is it possible to deploy it from source at the moment?

@darkAlert i would like to contact you for a project
