### ISSUE TITLE
Tasks cannot be opened

### ISSUE THREAD

**Issue by ASAADASKAR** [opencv/cvat#6637]
Hello, I created two tasks in CVAT and I annotated them. After I try to open the tasks, nothing happens just it keeps trying to open the task all the time.

I'm looking forward to solving this.

  
![image](https://github.com/opencv/cvat/assets/96923410/f0605aee-33fa-475a-90a7-3abe15a556af)

![image](https://github.com/opencv/cvat/assets/96923410/dbbf0edb-3819-4f8e-8b65-ae64fbb866bf)

**Comment by bsekachev** [comment]
Hi @ASAADASKAR 

app.cvat.ai or self hosted solution? 
Do you see any errors in the browser console?

**Comment by ASAADASKAR** [comment]
Hi @bsekachev 

self hosted solution  and I see no error

**Comment by bsekachev** [comment]
Can you share screenshot from Network tab in this case? First open it in the browser dev tools (F12 in Chrome) and then update the page with F5. 

Like this: 
<img width="1920" alt="image" src="https://github.com/opencv/cvat/assets/40690378/e9079b9d-a685-4915-b873-7851749c6a02">

**Comment by bsekachev** [comment]
I see request for decoder.worker.js is blocked. Can you share its details? Try to clear the browser cache, or click **Disable cache** in the top bar of Network tab and update page once

**Comment by ASAADASKAR** [comment]
I deactivated the browser cache and refreshed the page again and the problem is solved.

@bsekachev thank you very much for the help.
