### ISSUE TITLE
Hide all annotations on an image

### ISSUE THREAD

**Issue by RichardMoffett** [opencv/cvat#6639]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

There's no way to easily hide all annotations on an image, so that multiple annotations can be made easily.
You can hide all annotations by clicking on each annotation's visibility, but that takes a long time & many clicks.

### Possible Solution
Add a "hide all visible annotations" feature e.g. one keyboard shortcut toggles visibility of existing annotations.

### Context
When annotating medical images, many annotations overlap each other.
Viewing pixels is essential. Existing annotations get in the way of new annotation, and high contrast of existing annotations prevents this, even when displayed with low opacity.
Hiding 50+ annotations takes a very long time at the moment.
(appreciate that CVAT is not designed for medical images)

**Comment by bsekachev** [comment]
<img width="259" alt="image" src="https://github.com/opencv/cvat/assets/40690378/e60ad0af-67a8-4e3b-afbb-f91e231ce6a0">
