### ISSUE TITLE
How does contrast and brightness affect greyscale images?

### ISSUE THREAD

**Issue by RichardMoffett** [opencv/cvat#6640]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

You can adjust "brightness" and "contrast" of greyscale images in CVAT, but can't tell what the feature does to greyscale images without reviewing CVAT code.

### Expected Behaviour
A Window/Level feature is available for working with greyscale medical images.

### Current Behaviour
Can't tell how changes to brightness and contrast affect greyscale medical images without looking at CVAT code.

### Possible Solution
Add a Window/Level feature for greyscale medical images (per DICOM standard)
or
Document how brightness and contrast adjustments affect greyscale images.

### Context
Most medical images are greyscale.
When annotating medical images, window/level adjustments allow you to see what you are trying to annotate.

**Comment by bsekachev** [comment]
Hi @RichardMoffett 

I am not sure I understand the problem. Could you provide some examples?

**Comment by RichardMoffett** [comment]
Thanks for replying, please let me explain further.

In medical imaging, DICOM (https://www.dicomstandard.org/) is the only standard image data format used by all medical devices, with specific support for "window and level", which means changing 1. the range of pixel values that are displayed, and 2. how pixel values in that range map to greyscale values on screen.

The DICOM standard describes this better than I can, at https://www.dicomstandard.org/standards/view/explanatory-information#figure_Y-1 - see section titled "VOI LUT Functions (Informative)".

Unfortunately I can't provide any medical image examples because they belong to patients and research subjects.
However, there are a large number of freely available DICOM images (from many different types of scanners) here: https://www.dicomlibrary.com/

**Comment by bsekachev** [comment]
Okay, I see. Unfortunately we do not support DICOM images natively, so, this feature request relates to this issue #4663
You can drop a line there, or anyway this issue will be shown there as related.

**Comment by RichardMoffett** [comment]
Thank you for considering this request Boris, will take a look at issue
#4633.

**Comment by RichardMoffett** [comment]
Just a little more detail:
I'm using raw greyscale images converted to PNG, rather than DICOM images.
