### ISSUE TITLE
Annotations statistics in the 'info' tab includes annotations on deleted frames

### ISSUE THREAD

**Issue by lubin-liu** [opencv/cvat#6641]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

After deleting images with boxes drawn, the annotation statistics provided by the 'info' tab (image below) does not change. 
![Capture](https://github.com/opencv/cvat/assets/69323872/99cdd707-434a-43e2-8955-7c75dde11795)

### Steps to Reproduce (for bugs)

1. Check annotation statistic before deleting frame with boxes
2. Delete some frames with boxes
3. Check annotation statistic again should show that the counts have not changed

### Expected Behaviour

Boxes in deleted frames should not be counted

### Your Environment

- Git hash commit (`git log -1`): a63f0f10aaab813565eeb24a19852c23fcc7e002
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.4
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): linux 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Shall be fixed by #6493
Please, let us know if it was not.
