### ISSUE TITLE
Error response from daemon: Container b44554ea8c1 is restarting, wait until the container is running

### ISSUE THREAD

**Issue by TYUTYQS** [opencv/cvat#6644]
docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'
happens it (a problem)

**Comment by bsekachev** [comment]
Please, fill the issue template as detailed as possible. Otherwise we can't help you.

**Comment by Petros626** [comment]
@TYUTYQS for me too with a fresh installed CVAT :D
