### ISSUE TITLE
cvat_ui Error: could not find config file supervisord/all.conf

### ISSUE THREAD

**Issue by Linhbui-792002** [opencv/cvat#6650]
docker-compose logs cvat_ui
cvat_ui  | Error: could not find config file supervisord/all.conf

CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                  PORTS                                                    NAMES
3164e1933870   cvat/ui:dev                                "/usr/bin/supervisor…"   4 minutes ago    Up Less than a second   8080/tcp                                                 cvat_ui
eb738ffe92ff   cvat/server:dev                            "/usr/bin/supervisor…"   7 minutes ago    Up 12 seconds           8080/tcp                                                 cvat_utils
7e94431911e9   cvat/server:dev                            "/usr/bin/supervisor…"   7 minutes ago    Up 12 seconds           8080/tcp                                                 cvat_worker_analytics_reports
f427e1248acf   cvat/server:dev                            "/usr/bin/supervisor…"   7 minutes ago    Up 12 seconds           8080/tcp                                                 cvat_worker_quality_reports
4e7abc92b9ff   cvat/server:dev                            "/usr/bin/supervisor…"   7 minutes ago    Up 12 seconds           8080/tcp                                                 cvat_worker_webhooks
f2c09a7bb254   cvat/server:dev                            "/usr/bin/supervisor…"   7 minutes ago    Up 11 seconds           8080/tcp                                                 cvat_worker_import
c868439f8093   cvat/server:dev                            "/home/django/backen…"   7 minutes ago    Up 11 seconds           8080/tcp                                                 cvat_server
c7a027e7c1bc   cvat/server:dev                            "/usr/bin/supervisor…"   7 minutes ago    Up 12 seconds           8080/tcp                                                 cvat_worker_annotation
c77664cfdd76   cvat/server:dev                            "/usr/bin/supervisor…"   7 minutes ago    Up 12 seconds           8080/tcp                                                 cvat_worker_export
a33ce4f5018a   timberio/vector:0.26.0-alpine              "/usr/local/bin/vect…"   7 minutes ago    Up 11 seconds                                                                    cvat_vector
a51fca5d1613   redis:7.0-alpine                           "docker-entrypoint.s…"   8 minutes ago    Up 14 seconds           6379/tcp                                                 cvat_redis
0063cdf26da7   traefik:v2.9                               "/entrypoint.sh --pr…"   8 minutes ago    Up 13 seconds           0.0.0.0:8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp   traefik
bac31c542444   openpolicyagent/opa:0.45.0-rootless        "/opa run --server -…"   8 minutes ago    Up 14 seconds                                                                    cvat_opa
85b8d0e1259d   clickhouse/clickhouse-server:22.3-alpine   "/entrypoint.sh"         8 minutes ago    Up 13 seconds           8123/tcp, 9000/tcp, 9009/tcp                             cvat_clickhouse
870f3adecda1   grafana/grafana-oss:9.3.6                  "sh -euc 'mkdir -p /…"   8 minutes ago    Up 13 seconds           3000/tcp                                                 cvat_grafana
be5e33f12e31   postgres:15-alpine                         "docker-entrypoint.s…"   8 minutes ago    Up 14 seconds           5432/tcp                                                 cvat_db

**Comment by Linhbui-792002** [comment]
I custom cvat-ui and build again image by : docker build -t cvat/ui:dev . 
I try run dock-compose up -d and check logs cvat_ui 
docker-compose logs cvat_ui
cvat_ui | Error: could not find config file supervisord/all.conf

**Comment by bsekachev** [comment]
You need to use docker compose to build:
``docker compose up -d --build``.

If you modified code, you need to add dev compose file:
``docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build``

**Comment by Linhbui-792002** [comment]
Thank you so much. Problem solved
