### ISSUE TITLE
removed volume cvat_cvat_db, but when task is created, old image(already removed on old db) is on task.

### ISSUE THREAD

**Issue by sanghun-scalawox** [opencv/cvat#6653]
what should i do?  I alrerady did command `docker volume rm cvat_cvat_db` and retried docker compose up.

the situation is occured when first task is created too.

I am using v2.4.9. 

can i get your help?

thank you.

**Comment by bsekachev** [comment]
You need to remove cache. 

``docker exec -it cvat_server /bin/bash``
``rm /home/django/data/cache -r`` # as far as I remember this patch. But check it additionally

**Comment by sanghun-scalawox** [comment]
thank you!
i also tried `docker volume rm cvat_cvat_data` before you comment (thankfully), problem solved!
if i meet this situaition again, i will try. thank you. I'll close issue.
