### ISSUE TITLE
Customizing Task Workflows

### ISSUE THREAD

**Issue by jeethesh-pai** [opencv/cvat#6654]
Hi, 

This is a general question regarding Task workflow in CVAT. Is it possible to create custom workflows for some Projects. For e.g.,

If I have a new complicated Object Detection Project, whose annotation workflow, I would like to split into 6 stages namely

- annotation-boxes
- annotation-attributes
- validation-boxes
- validation-attributes
- completed-boxes
- completed-attributes

or using include some custom extra states  other than `new`, `in progress`, `rejected`, `completed` like `boxes` and `attributes` for the existing stages

I am completely new to CVAT SDK or API. I have been using only UI till now.  Please suggest me where to start, if this is possible.

Thanks
Pai

**Comment by bsekachev** [comment]
In general you can do annotation/validation/completed for boxes and attributes in one project. 
If you would like to split it to several steps, you can create two projects in your case.

The first pipeline is:
* annotation-boxes
* validation-boxes
* completed-boxes
Which is compatible with existing states and stages in CVAT.

Then export the project, import it (creating a copy actually) and add attributes to the labels specification. 
And do the second pipeline:
* annotation-attributes
* validation-attributes
* completed-attributes

Combining annotations from these two projects will give you final annotations you want. You need to pick coordinates from the first project and attributes from the second one. It will guarantee, that coordinates weren't broken during attributes annotation.

**Comment by jeethesh-pai** [comment]
Hi @bsekachev ,

Thanks for your quick support. This seems to be an elegant solution without touching the SDK. I will try to do as you suggested. But just out of curiosity, is it also possible to do, what I suggested using SDK? 

Thanks 
Pai

**Comment by bsekachev** [comment]
To be honest, I am not SDK expert. 
Maybe @SpecLad can suggest something.

**Comment by SpecLad** [comment]
The SDK won't help you add extra states, but you can use it to automate manual tasks. E.g. you could use it to write a script that exports a project and imports it again, like @bsekachev suggested.

**Comment by jeethesh-pai** [comment]
Hi @SpecLad ,

Yea, an automation for exporting is indeed helpful. But is it not possible to add new states of stages in CVAT workflows?

Thanks 
Pai

**Comment by SpecLad** [comment]
No, this isn't supported at the moment.

**Comment by jeethesh-pai** [comment]
Alright. I got what I was looking for. Thanks for your quick support

**Comment by jeethesh-pai** [comment]
Hi @bsekachev ,

Sorry for reopening this issue again, As per your suggestion, I have created two projects and built a custom pipeline. I would like to ask, if there is a way to share the source images, since both the projects differ only based on annotations, the image of both are actually the same. If I create two project and respective tasks in it, I have to upload the images twice for each of them. I used CLI for this. Please suggest a better way to create tasks without duplicating memory.

**Comment by bsekachev** [comment]
- Shared storage https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path (with disabled Copy Data checkbox)
- Or cloud storage https://opencv.github.io/cvat/docs/manual/basics/attach-cloud-storage/
- Together with Use cache https://opencv.github.io/cvat/docs/manual/advanced/data_on_fly/ might help to reduce data usage

But not sure that project can be backed up with shared/cloud storage data. Need to check in advance.
