### ISSUE TITLE
Similar to Getting error - missing 1 required positional argument: 'jobs' while trying to execute CVAT-CLI commands #5872

### ISSUE THREAD

**Issue by alijawad07** [opencv/cvat#6657]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by alijawad07** [comment]
This issue has appeared again in
cvat-cli - 2.5.2
cvat-sdk - 2.5.2

in 2.4.0 job issue was fixed but it was throwing an error because there was no argument for organization
in 2.5.2 there is an argument for organization but again it starts asking for job argument

**Comment by bsekachev** [comment]
Hope now it works well
