### ISSUE TITLE
IT TAKES ONE YEAR TO UPLOAD YOLO DATASET

### ISSUE THREAD

**Issue by sezarxray** [opencv/cvat#6662]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Expected Behaviour

YOLO IS JUST TEXT AND IMAGE(AND AT LAST CLASS FILE)  
FOR UPLOAD A YOLO FORMAT I HAVE TO DO MANY THING.
obj.data
train.txt
zip 
 obj_set_data
IT TAKES ONE YEAR TO UPLOAD YOLO DATASET

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Hello @sezarxray 

Apologize for the bad experience. If you are ready to contribute to better user experience when working with YOLO, detailing issues you met and solutions you applied, it would be great.

**Comment by sezarxray** [comment]
Way1: I have a zip file that contains images and labels in YOLO format. I believe this information is sufficient to create a task. The task itself includes defining the classes.No need for txt file with name of all images. Regardless of the folder and directory arrangement within the zip file, it is easy for CVAT to identify all the txt and image files present in the zip file and create task.
Way 2: add missing classes to task instead of rising error.


Issues arise in the absence of this process:
1- When images are uploaded from the zip file, they retain the original directory paths from the zipfile. This poses a challenge when attempting to directly upload a zip file containing labels. The recommended approach is to initially download the task, gain an understanding of how CVAT organizes the dataset, and then properly place the labels within the appropriate directory.
2- You need to put classes.txt and obj.data and obj.names and train.txt

**Comment by bsekachev** [comment]
@zhiltsov-max 

Could you please comment on that?

**Comment by sezarxray** [comment]
???????????????????????????????????????????

**Comment by zhiltsov-max** [comment]
Hi! If you see how this can be improved and want to help the project, don't hesitate to send us a pull request. Here you can find [contributing guidelines](https://opencv.github.io/cvat/docs/contributing/). I think, it would be a nice feature - especially, because we already have something similar for PASCAL VOC. You can find the related files [here (for YOLO format support)](https://github.com/opencv/cvat/blob/develop/cvat/apps/dataset_manager/formats/yolo.py) and [here (for PASCAL VOC example)](https://github.com/opencv/cvat/blob/develop/cvat/apps/dataset_manager/formats/pascal_voc.py).
