### ISSUE TITLE
Problems in migartion from version 1.4 to version 1.6

### ISSUE THREAD

**Issue by RoseDeSable** [opencv/cvat#6667]
Hello,
 we are migrating from our elder version (Server version: 1.4, Core version: 3.12.1, Canvas version: 2.4.3,UI version: 1.19.1) to the newest (Server version: 2.6 Core version: 9.2.0, Canvas version: 2.17.1,UI version: 1.53.1). My collegue pulled the database of postgres with the postgres tools into the db of the new version. Then he completely copied the Volume "cvat_data". But something seems not to be correct. We cannot find the reason:

I can login in the new version with my actual credentials, that I use for the elder version. But my profile of the new version shows an additionally point: organization. Therefore I don't see our projects for example. What have we forgotten to do ? Where is our failure ?

Best Regards
Rose

**Comment by zhiltsov-max** [comment]
Hi! Please use this information for upgrading: https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/

**Comment by RoseDeSable** [comment]
Ok,
 we read the manual. But I have a question: Are all the user informations (profiles, login credentials) completely stored in the postgres db or exist referals in locations outside of the db ?

**Comment by zhiltsov-max** [comment]
All this information should be stored only in the DB.

**Comment by RoseDeSable** [comment]
Ok,
 and the "organization" ? I believe, that it is also stored in the database. Or not ?

**Comment by bsekachev** [comment]
Everything except for image data are stored in the database. 
Image data are stored in docker volume ``cvat_data``.
