### ISSUE TITLE
Management dashboard

### ISSUE THREAD

**Issue by ASAADASKAR** [opencv/cvat#6672]
### **Working Time**
I have exported working time excel spreadsheet from management dashboard but there are some values ​​that I don't understand.
![image](https://github.com/opencv/cvat/assets/96923410/448c3a98-ec8f-4a59-bdce-bab214d2a619)

It can't be that I put 309 hours in exercise 3. I don't know exactly what the activity means either.

Are the values ​​plausible?

`SELECT
  user_id as User,
  user_name,
  project_id as Project,
  task_id as Task,
  job_id as Job, sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 3600 as "Working time(h)",
  count() as Activity
FROM events
WHERE JSONHas(payload, 'working_time')
  AND $__timeFilter(timestamp)
  AND (-1 IN (${users}) OR user_id IN (${users}))
  AND (-1 IN (${projects}) OR project_id IN (${projects}))
  AND task_id IN (${tasks})
  AND job_id IN (${jobs})
  AND source = 'client'
GROUP BY user_id, project_id, task_id, job_id, user_name`

### More info for the tasks and jobs 
get more info besides  to task_id and job_id like task_name and job_name etc..., is that possible?

I would be very grateful for the help

**Comment by azhavoro** [comment]
please attach the exported csv file

**Comment by ASAADASKAR** [comment]
[]
[working-time.xlsx](https://github.com/opencv/cvat/files/12428432/working-time.xlsx)

**Comment by azhavoro** [comment]
How did you export the xlsx file from the grafana dashboard, it shouldn't be a csv?

As for the other question, this information is not currently stored in the database, please take a look at the documentation
https://opencv.github.io/cvat/docs/administration/advanced/analytics/

**Comment by ASAADASKAR** [comment]
@azhavoro 
yes right from Grafana can be exported only CSV, but I have imported the CSV in XLSX.

**Comment by ASAADASKAR** [comment]
@azhavoro 
Correct, only CSV can be exported from Grafan, but I have imported the CSV into XLSX to make it easier to read.

But if I use Grafan in SQLITE code the Job_name or Task_name, then they can't be found. They are not.

Relational database:
`CREATE TABLE IF NOT EXISTS ${CLICKHOUSE_DB}.events
(
    \`scope\` String NOT NULL,
    \`obj_name\` String NULL,
    \`obj_id\` UInt64 NULL,
    \`obj_val\` String NULL,
    \`source\` String NOT NULL,
    \`timestamp\` DateTime64(3, 'Etc/UTC') NOT NULL,
    \`count\` UInt16 NULL,
    \`duration\` UInt32 DEFAULT toUInt32(0),
    \`project_id\` UInt64 NULL,
    \`task_id\` UInt64 NULL,
    \`job_id\` UInt64 NULL,
    \`user_id\` UInt64 NULL,
    \`user_name\` String NULL,
    \`user_email\` String NULL,
    \`org_id\` UInt64 NULL,
    \`org_slug\` String NULL,
    \`payload\` String NULL
)`

**Comment by azhavoro** [comment]
@ASAADASKAR please attach original csv file
As I said before, we **don't** store task name as an event field. This is exactly what you can see in the `events` table schema. Probably only the `create:task` event can contain this information in the payload, but it's not clear to me what you want to get out of it.

**Comment by ASAADASKAR** [comment]
[Working time-data-2023-08-14 20_12_45.csv](https://github.com/opencv/cvat/files/12432450/Working.time-data-2023-08-14.20_12_45.csv)
I have uploaded the file, but I think the problem has been solved and now the Excel table shows plausible numbers.

**Comment by ASAADASKAR** [comment]
@azhavoro Also, in the dashboard I will also see the task_name and project_name such as task_id

**Comment by ASAADASKAR** [comment]
The problem with exported files from Grafana is solved
