### ISSUE TITLE
Create task with images from s3: are they copied to local cvat storage or not?

### ISSUE THREAD

**Issue by chekhovana** [opencv/cvat#6677]
I wonder how image files are handled when I use s3-compatible storage (minio) as a source. 

I searched docker cvat volumes and there was no image files in the corresponding task folder. On the other side, when I remove images in minio, they are still visible in cvat task.

Could someone clarify this?

**Comment by bsekachev** [comment]
They might be cached on the server in ``data/cache``. Gradually they will be overwritten in this case.

**Comment by chekhovana** [comment]
@bsekachev Thanks for the quick response.

So permanent local copies of these image files are not created in cvat repository, right?

**Comment by bsekachev** [comment]
1. As far as I know, if we are talking about images and with enabled use_cache option, they are not copied. Related: https://opencv.github.io/cvat/docs/manual/advanced/data_on_fly/ 
2. As I told before, ``data/cache``. The volume ``cvat_data`` mounted to several containers, for example to ``cvat_server``.

**Comment by chekhovana** [comment]
thank you!
