### ISSUE TITLE
about FAST-SAM

### ISSUE THREAD

**Issue by stone100010** [opencv/cvat#6680]
Hello, scientists of cvat, it's a great honor to learn about your project cvat, and thank you for your contribution to the data set annotation tool. I saw the auxiliary annotation function of SAM on YouTube, which may be a little slow. May I ask scientists, will you consider supporting FAST-SAM in the future? Best wishes!
From cvat fans

**Comment by bsekachev** [comment]
app.cvat.ai now supports EfficientSAM
