### ISSUE TITLE
using stylus pen for annotation 

### ISSUE THREAD

**Issue by KanielDatz** [opencv/cvat#6681]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
connect your machine to a painting tablet or use a touchscreen.
try using the brush tool to paint masks

### Expected Behaviour
moving the stylus over the screen will leave marks when using the brush tool.

### Current Behaviour
CVAT wont respond to the touch of the pen. it does work with polygon mask marking but not the brush.
the curser runs according to the stylus but doesn't leave any marks.
I did manage to use several drawing tablet when activating 'disable windows ink'.
### Possible Solution
windows ink compatibility will be nice (no need to be sensitive to intensity).
or any other solution.

### Context
using stylus to paint the masks makes the annotation process much faster.  I believe it is a very valuable feature.

### Your Environment
Server version: 2.5
Core version: 9.1.3
Canvas version: 2.16.7
UI version: 1.51.2
Docker version : 4.20.1
Operating System and version (e.g. Linux, Windows, MacOS): win11 with WSL2 running Ubunto
this are the settings that work for GAOMON drawing tablet:
![image](https://github.com/opencv/cvat/assets/93449840/2b8ad525-d158-468d-a55f-8319d0e4334a)
tried superdisplay app on samsung tablet / using touch screen - both didn't work.

**Comment by bsekachev** [comment]
Hi @KanielDatz

CVAT does not support touchscreens and mobile devices to annotate.

**Comment by bsekachev** [comment]
In general it is duplicate for #3744
