### ISSUE TITLE
Convert Mask to Polygon

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6685]
In the AI tools there is an option to convert masks to polygon. 

It would be a great tool to convert any mask to polygon.

Also, is there a setting for the density of dots in the polygon for the AI tools convert masks to polygon?

Many thanks!

DBG

**Comment by bsekachev** [comment]
> Also, is there a setting for the density of dots in the polygon for the AI tools convert masks to polygon?

You can see this settings during drawing polygon with AI tool:
![image](https://github.com/opencv/cvat/assets/40690378/6ca04623-3575-4051-8de4-6771f7991146)

Default value can be changed in Settings -> Workspace:
![image](https://github.com/opencv/cvat/assets/40690378/5728b109-2b3a-466f-ba65-f1cac3a8cc1e)

**Comment by DaveBGld** [comment]
@bsekachev Thanks!

**Comment by bsekachev** [comment]
Implemented on app.cvat.ai. 
Menu => Run Action => Shape converters

**Comment by DaveBGld** [comment]
Great! Thanks!! 

Is it going to be implemented in the docker version?

**Comment by kim-tom** [comment]
Great feature! I want to know how to enabled this in Docker version.
I need this feature because converting polygon distort mask's shape.
I want to convert mask to polygon only when I need to update mask's shape.
