### ISSUE TITLE
sqlite3.DatabaseError: file is not a database

### ISSUE THREAD

**Issue by Pan-will** [opencv/cvat#6691]
### My actions before raising this issue
There is a problem with the CVAT backend server deployed in the cluster. 
I tried to recreate pods, but it didn't work.
The deployment is as follows:
![image](https://github.com/opencv/cvat/assets/50573470/e0ad7240-fd4a-410e-9a4c-a5fd2ecb099a)

It can be seen that the backend service is down. The query pod log is shown below:
![image](https://github.com/opencv/cvat/assets/50573470/aa7e7441-9b83-4d3a-978f-c71f7e38e291)
The error message is as follows: sqlite3.DatabaseError: file is not a database

### Environment
The Tag(version) of backend server image: v2.4.6
![image](https://github.com/opencv/cvat/assets/50573470/91fc2106-f3ea-4085-a6dc-3ebaf209de62)

Has anyone encountered a backend server crash for the same reason?

**Comment by azhavoro** [comment]
The problem is related to a third-party component (disckcache), try deleting the contents of the cache folder
