### ISSUE TITLE
change share path is not successful.

### ISSUE THREAD

**Issue by seasenzzr000** [opencv/cvat#6698]
Ubantu:18.04
docker:24.0.2
python3.8
cvat server version:2.6

hi,guys.
I want to create share path on CVAT, and according to the prompts, I created Docker-Compose. override. yml .and edit it. 
Run `Docker Compose  up - d ' has been in the Recreate state for about 20 minutes.
please help me.

Step:

```shell
git clone https://github.com/opencv/cvat
``` 
```shell
export CVAT_HOST=<YOUR_DOMAIN>
``` 
```shell
export ACME_EMAIL=<YOUR_EMAIL>
``` 
```shell
docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'
``` 
```shell
docker compose up -d
``` 

Then, I tried to set the share path.
```shell
vim  docker-compose.override.yml
``` 
```python
 cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /data/labelshare
      o: bind
services:
``` 
 

run 
```shell
docker compose - up -d
``` 

However, it was not successful.

I want to set the share path to` /data/labelshare` .how do?please help me.

**Comment by azhavoro** [comment]
@seasenzzr000 try stopping cvat containers, deleting the `cvat_cvat_share` volume and start again

**Comment by seasenzzr000** [comment]
> @seasenzzr000 try stopping cvat containers, deleting the `cvat_cvat_share` volume and start again

Thank you very much for the help you provided. CVAT is an excellent project. I have successfully configured the docker-compose.override.yml file.

I have deployed SAM and YOLOv7.
However, I encountered an issue where the shared path disappeared after running the command . Could you please advise on how to proceed?

```shell
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
``` 
After running .the shared path disappeared.

Even after adding , it still doesn’t work.  `--build`

**Comment by azhavoro** [comment]
@seasenzzr000 you have to include your override file 
```
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml -f docker-compose.override.yml up -d
```
