### ISSUE TITLE
clarify how to create multiple labels

### ISSUE THREAD

**Issue by kodonnell** [opencv/cvat#67]
I might have missed it, but the [documentation](https://github.com/opencv/cvat/blob/badddeb07f04011d2d2abc54b443ca9197903186/cvat/apps/documentation/user_guide.md#creating-an-annotation-task) doesn't seem to specify how to add multiple labels. I assumed it was just comma-separated (e.g. "car,truck,bus") but that didn't work.

**Comment by nmanovic** [comment]
Hi @kodonnell ,

Please use space as the separator: "car truck bus". We will add such example explicitly. Thanks for the feedback.

**Comment by kodonnell** [comment]
Thanks @nmanovic - after trying semicolon delimited, I went and figured it out by digging through the source code.

NB - might pay to update the documentation in the GUI too (i.e. when you hover over the input).
