### ISSUE TITLE
opencv.js   CVAT There are issues with the latest version

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#6703]
![20230820-054734](https://github.com/opencv/cvat/assets/135221549/f5e5d150-7ebd-4bda-b0b2-d6e4b4f7b7e5)
![20230820-054739](https://github.com/opencv/cvat/assets/135221549/0c8d8d5b-65a9-421f-b7d8-92c043014301)

**Comment by KTXKIKI** [comment]
There was a problem opening Google Chrome, but when Edge was opened, it disappeared. It's strange

**Comment by bsekachev** [comment]
@KTXKIKI  What is Google Chrome version?

**Comment by KTXKIKI** [comment]
> 

116.05845   the latest version

**Comment by bsekachev** [comment]
Hm, for me it works in this browser. Could you please provide response details? (general, headers) and maybe screenshot with Preview. 

Also, one more question, can you download opencv on app.cvat.ai?

**Comment by bsekachev** [comment]
If you did upgrade CVAT to the latest dev version, you need to reload the page at least to get relevant client-side files.

**Comment by KTXKIKI** [comment]
> 如果您确实将 CVAT 升级到最新的开发版本，则至少需要重新加载页面才能获取相关的客户端文件。
Fixed
