### ISSUE TITLE
Could not initialize OpenCV library

### ISSUE THREAD

**Issue by rezabasiri** [opencv/cvat#6704]
Running the docker image on MacOS as instructed in the guide. Once I open a task on Chrome where the image is viewed with the sidebar, the docker engine fails to load OpenCV. I get this message:

Could not initialize OpenCV library
SyntaxError: Unexpected token '<'

What could be the issue?

**Comment by bsekachev** [comment]
Hi @rezabasiri 

Can you provider opencv request details? Such, like general/response headers/preview response screenshot

**Comment by rezabasiri** [comment]
![Screen Shot 2023-08-20 at 2 32 07 PM](https://github.com/opencv/cvat/assets/57999540/a8316543-a5a8-4a36-a6ca-8d5361204cfe)
![Screen Shot 2023-08-20 at 2 29 51 PM](https://github.com/opencv/cvat/assets/57999540/22747eb2-62d4-442c-879e-3917a04b2a85)
![Screen Shot 2023-08-20 at 2 30 02 PM](https://github.com/opencv/cvat/assets/57999540/c4120031-bea2-4796-b597-184b2485e81e)
![Screen Shot 2023-08-20 at 2 33 12 PM](https://github.com/opencv/cvat/assets/57999540/fce111fb-d39e-4666-b9e9-aa4dbf693489)
![Screen Shot 2023-08-20 at 2 31 35 PM](https://github.com/opencv/cvat/assets/57999540/3afc70bd-5e21-46a1-9941-e12151d39f2f)
![Screen Shot 2023-08-20 at 2 31 44 PM](https://github.com/opencv/cvat/assets/57999540/889036d9-736e-4970-bc86-b3d0b4160895)

**Comment by bsekachev** [comment]
What CVAT version do you use? 
And you recently deployed it? Did you have installed CVAT before?

**Comment by rezabasiri** [comment]
2.6.0 version for CVAT, it was deployed yesterday and fresh installation for docker and cvat on macos monterey.

**Comment by bsekachev** [comment]
@rezabasiri 

What command did you use to deploy?

**Comment by rezabasiri** [comment]
`docker compose --file './cvat/docker-compose.yml' --project-name 'cvat' start` Or just from docker desktop

**Comment by bsekachev** [comment]
Please, try to follow official installation guide: 

```
docker compose down
CVAT_VERSION=latest docker compose pull
docker compose up -d
```

More info is here: https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/

**Comment by DmitryBabichev** [comment]
I have the same issue, "Could not initialize OpenCV library", I have installed the latest version of cvat today
