### ISSUE TITLE
Google Chrome and Edge's Everything Segmentation

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#6708]
![image](https://github.com/opencv/cvat/assets/135221549/f0d18b28-64de-4127-bb4e-d0f921bd9e1c)
Google Chrome and Edge's Everything Segmentation

**Comment by KTXKIKI** [comment]
Google Chrome and Edge reported an error when using one of their segmentation points for everything

**Comment by KTXKIKI** [comment]
![img_v2_fc7be406-5144-4f30-9098-733ae0004f1g](https://github.com/opencv/cvat/assets/135221549/fcaa7127-23a6-4a3f-aa51-fc208ad8cfb8)
Google Chrome's Everything Segmentation Click Continuously Prompts This

**Comment by bsekachev** [comment]
Please, fill the issue template

**Comment by KTXKIKI** [comment]
> 请填写问题模板
Click on 'Everything Splits' in Google Chrome to report this er

https://github.com/opencv/cvat/assets/135221549/1a921f26-3188-41a3-9206-5641860aad3a

ror   @bsekachev

**Comment by KTXKIKI** [comment]
Another error occurred in the Edge browser @bsekachev 

https://github.com/opencv/cvat/assets/135221549/f47ae4fd-d5e8-4b2c-8f36-8997fb5e95eb

**Comment by KTXKIKI** [comment]
arrange：    git bash    CVAT_VERSION=dev docker compose-f docker-compose.yml-f components/serverless/doker-compoce.serverless.yml up-d

**Comment by KTXKIKI** [comment]
What could be the issue?

**Comment by bsekachev** [comment]
> Click on 'Everything Splits' in Google Chrome to report this error

Please, look at ``decoder.onnx`` response on Network tab.

> Another error occurred in the Edge browser @bsekachev

We need somehow reproduce it, for example if you can post your task on app.cvat.ai, I could try.

**Comment by KTXKIKI** [comment]
@bsekachev 
![20230821-164603 340-4](https://github.com/opencv/cvat/assets/135221549/c56f58b0-5dee-4dc9-9d09-c4d997a622b7)
![20230821-164603 340-5](https://github.com/opencv/cvat/assets/135221549/467f6e7b-3973-40bb-ae96-6cd12bb2babf)
![20230821-164603 340-6](https://github.com/opencv/cvat/assets/135221549/89290c32-5554-4e81-8103-4cbc4ac92a28)
![20230821-164603 340-7](https://github.com/opencv/cvat/assets/135221549/1865efc6-1aea-45bc-bd68-e2ec7665babc)
![20230821-164603 340-8](https://github.com/opencv/cvat/assets/135221549/559048db-c9b6-46de-b21c-b9ce3d54d5b8)
![20230821-164603 340-9](https://github.com/opencv/cvat/assets/135221549/b8f75c50-8655-4b62-8456-23e17e0520f0)
![20230821-164603 340-10](https://github.com/opencv/cvat/assets/135221549/b5d53d32-0115-441b-8d96-781697e40037)
![20230821-164603 340-11](https://github.com/opencv/cvat/assets/135221549/f42394c2-1c2f-4e98-97be-94b8b2612e00)

**Comment by bsekachev** [comment]
Update the page with ``Shift + F5`` and try again.

**Comment by KTXKIKI** [comment]
I have tried it before, and it still has the same problem, whether it's Shift+F5 or Ctrl+f5 @bsekachev

**Comment by KTXKIKI** [comment]
I tried restarting and running the CVAT service, but the same problem still exists

**Comment by bsekachev** [comment]
Can you reproduce it on current develop branch without custom modifications?

**Comment by bsekachev** [comment]
I was able to reproduce something like that

![image](https://github.com/opencv/cvat/assets/40690378/25713a5d-afd5-4b87-a970-e30eff775633)

But: This happens because you get updated onnxruntime package 1.15 and **ort-wasm-simd.wasm** file from 1.14. 
And to fix it you need to only reload once the page without using browser cache (Shift + F5 if one of ways to do it), with checked "Disable cache" or clear cache through browser settings. 

And as I see from your screenshot, it is received from the browser cache:
![image](https://github.com/opencv/cvat/assets/40690378/e136094e-becb-46a3-90f7-b62786f57c96)
