### ISSUE TITLE
The issues about privacy of different users' shared folder

### ISSUE THREAD

**Issue by ShangWeiKuo** [opencv/cvat#6711]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Excuse me @bsekachev

I've been mounted shared folder to CVAT successfully. However. I found that the data I've mounted to CVAT can be seen by different users. It's very dangerous for my data has high probability to be used by another users.

How should I do to make the shared folder be visible only to specific accounts ?

**Comment by bsekachev** [comment]
Shared folder is dedicated to other user see its content. We do not have configuration that strict it.
If you want privacy for your data, your choice is cloud storages.

On your self-hosted instance you can try to setup corresponding access rules in this file:  ``cvat/apps/iam/rules/server.rego``. For example, now each user who has at least WORKER role may access it. 

https://opencv.github.io/cvat/docs/administration/advanced/iam_system_roles/
https://www.cvat.ai/post/cvat-open-policy-agent

**Comment by ShangWeiKuo** [comment]
> Shared folder is dedicated to other user see its content. We do not have configuration that strict it. If you want privacy for your data, your choice is cloud storages.
> 
> On your self-hosted instance you can try to setup corresponding access rules in this file: `cvat/apps/iam/rules/server.rego`. For example, now each user who has at least WORKER role may access it.
> 
> https://opencv.github.io/cvat/docs/administration/advanced/iam_system_roles/ https://www.cvat.ai/post/cvat-open-policy-agent

Excuse me @bsekachev 

Do the data in the shared folder and the names of models in AI tools can still be seen by other users even I setup those access rules ?

**Comment by bsekachev** [comment]
> data in the shared folder

You can setup access the way, other users can not see it. It totally depends on your wish. 
But it will be a custom modification.

> names of models in AI tools 

That is a different questions, need to work with other rules in the same directory.

**Comment by ShangWeiKuo** [comment]
> server.rego

Could you provide me an example ?
