### ISSUE TITLE
How to take backup in cvat 

### ISSUE THREAD

**Issue by Drkhushal** [opencv/cvat#6715]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Expected Behaviour
![error_cvat_git](https://github.com/opencv/cvat/assets/142792979/31dfb66d-3fc3-4cbe-a6fa-f140cc1569d2)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
How to take backup in cvat 
It gives error 
![error_cvat_git](https://github.com/opencv/cvat/assets/142792979/87649db8-95b6-4138-9bc7-f2301c5d9663)

**Comment by bsekachev** [comment]
Please, fill the issue template properly

**Comment by Drkhushal** [comment]
I initially established a project where I successfully annotated a set of images. Subsequently, I created a new account and set up a Docker environment. Within this new environment, I am tasked with working on a fresh project that requires the use of the images that were annotated in my earlier project.

**Comment by bsekachev** [comment]
[Backup guide](https://opencv.github.io/cvat/docs/manual/advanced/backup/)

**Comment by Drkhushal** [comment]
follow with same steps. but it gives error
