### ISSUE TITLE
Could not restore project backup

### ISSUE THREAD

**Issue by Drkhushal** [opencv/cvat#6716]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by Drkhushal** [comment]
![Uploading error_cvat_git.jpg…]()

**Comment by Drkhushal** [comment]
Could not restore project backup.

Error: tus: failed to upload chunk at offset 0, caused by [object ProgressEvent], originated from request (method: PATCH, url: http://blatantly-ideal-javelin.ngrok-free.app/api/projects/backup/ded11bb7-ea65-4728-971f-b2452578b5c9, response code: n/a, response text: n/a, request id: n/a)

**Comment by bsekachev** [comment]
Steps to reproduce? Version? Screenshot you sent is not valid.
