### ISSUE TITLE
Upgrade cvat from v 0.2.0 to v 0.4.2

### ISSUE THREAD

**Issue by LucianoTarouco1** [opencv/cvat#672]
Hello,
We have a lot of work done on our instance of cvat v 0.2.0 and we are trying to update to version 0.4.2. The installation process went fine but when we try to copy the database from the old version to the new version the front end stops working. It seems as though as the schema of the database is different. Also, as far as I verified the images are not contained in the database. They are on a virtual machine called cvat under a folder called data. I will also have to copy all the images to the new version. Maybe the directory structure where the images are placed also changed from the old version to the new, right? Is there some way to overcome this situation and to be able to update keeping all the work that we have already done?

Regards,
Luciano

**Comment by bsekachev** [comment]
@LucianoTarouco1 
Database schemes is actually different.
But I don't understand why you need to copy old database to new instance manually. 
CVAT update don't erase old data.

**Comment by LucianoTarouco1** [comment]
Hi, thanks for your reply.
Please let me know how should I proceed to do the update. Shall I follow the steps on the installation guide? Updating from the repository to the same folder and then doing "docker-compose build" etc?
Will this process update the database schema and maintain the data?

Regards,
Luciano

**Comment by bsekachev** [comment]
@LucianoTarouco1 
Something like that:
```
git clone https://github.com/opencv/cvat.git
cd cvat
git checkout master
# the same build and up commands like before
```

Done.

**Comment by bsekachev** [comment]
@LucianoTarouco1 
If you have downloaded previous repository, then from it's root dir:
```
git checkout master
git pull origin master
# the same build and up commands like before
```

**Comment by bsekachev** [comment]
@LucianoTarouco1 
I'll close this issue. Don't be shy to reopen it if you still have questions. Or you can ask them on gitter.

**Comment by shsegev** [comment]
Hi, 
I am also trying to upgrade. I have pulled the new version from git and ran docker-compose build. 
After the upgrade, the dashboard looks fine but when opening a task I get a blank screen. 
I understand that the schema has changed. Is there a way to update the old data so it fits the new schema?

Thanks
