### ISSUE TITLE
如何在vue项目中 加入cvat cvat项目如何跑起来

### ISSUE THREAD

**Issue by Ming0053** [opencv/cvat#6725]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
- Please, write in English.
- We do not have guidelines regarding integration with vue apps.

**Comment by Ming0053** [comment]
How does cvat run up I can't start the project

**Comment by bsekachev** [comment]
https://opencv.github.io/cvat/docs/administration/basics/installation/
