### ISSUE TITLE
Allow Unauthenticated Requests between Backend Services within Docker's Internal Network

### ISSUE THREAD

**Issue by Tlmonko** [opencv/cvat#6728]
In our current setup, we have multiple backend services communicating with each other within Docker's internal network. These services interact for various purposes, and not all of these interactions require user-related authorization.

I'm wondering if there's a way to configure our backend services so that requests that are not user-related can flow freely without requiring authentication. This would optimize the communication process and reduce unnecessary overhead for these specific interactions.

I'd greatly appreciate any guidance or insights on how to best handle this situation. Thank you for your assistance!

**Comment by bsekachev** [comment]
What kind of requests? 
We have different services like ``cvat_server``, ``cvat_worker_default``, etc.
All they have access to the database and all image data
