### ISSUE TITLE
cvat_db error

### ISSUE THREAD

**Issue by vaneuss1** [opencv/cvat#6737]
The problem with cvat_db, after a while, postgresql vacuum loads and loads the password to 100%, after which a message appears in the cvat_db log about a password authentication failure for the "root" user. I went into the container and saw the postgres: autovacuum reader process, it is he who loads the processors. Is it possible to disable it?

**Comment by bsekachev** [comment]
You should not disable autovacuum process:

https://dba.stackexchange.com/questions/273159/high-autovacuum-cpu-io-usage-from-database-with-more-than-10k-append-only-tables
