### ISSUE TITLE
upload dataset fail

### ISSUE THREAD

**Issue by liudaolunboluo** [opencv/cvat#6751]
### My actions before raising this issue
- [ ☑️] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [☑️ ] Searched [past issues](/issues)

when i upload datset,thorw error:
```
Not allowed to request resource
Error: tus: failed to upload chunk at offset 0, caused by [object XMLHttpRequestProgressEvent], originated from request (method: PATCH, url: http://{CVAT_HOST}/api/projects/47/dataset/6def5e6a-9be0-4c50-b1e5-eb3da9cee626, response code: n/a, response text: n/a, request id: n/a).
```

reproduce this bug. Include code to reproduce, if relevant -->
1.open project
1.choic upload

I suspect it's a cross-domain issue, I can see that the URL requested here is HTTP, but my service is HTTPS, it seems that I can't choose whether it's http or https when configuring CVAT_HOST, and the traefik configuration in yml is also http, so how do I configure it to https?

### Your Environment
Server version: 2.3

Core version: 7.3.0

Canvas version: 2.16.1

UI version: 1.45.0

**Comment by bsekachev** [comment]
Hi @liudaolunboluo 

Please, try to upgrade version to the latest release, before submitting the issue.

**Comment by Votess4All** [comment]
using 2.6 server version still got the bug

**Comment by bsekachev** [comment]
Do you see any other errors? Maybe CORS errors? 
As described in this issue #6339
