### ISSUE TITLE
Can not access Analytics.

### ISSUE THREAD

**Issue by lll9p** [opencv/cvat#6752]
### My actions before raising this issue
- [ * ] Read/searched [analytics docs](https://opencv.github.io/cvat/docs/administration/advanced/analytics/)
- [ * ] Searched 
  - #6109 
  - #2647 
  - #6335 
  - #2225 
  - #6579 
  - #6724 
  - #6540 
  - #5922 

All functions of cvat are normal except that Analytics cannot be opened. I searched for issues but didn't find a solution.

### Steps to Reproduce (for bugs)

1. Open Cvat.
2. Click "Analytics" tab
3. Then the page redirect to task page.
    <details>
    <summary>Explorer</summary>

    ![screenshot-20230825-133421](https://github.com/opencv/cvat/assets/1697421/169dfc74-dfd5-47c4-b8a0-5a87b9c02ca4)

    </details>

    <details>
    <summary>Video of this issue</summary>

    https://github.com/opencv/cvat/assets/1697421/ea7c012c-7a58-410d-97f6-f9b4b5a88eec

    </details>

### Context

In `docker-compose.override.yml`, I modified the `volume` of `cvat_grafana` so that `grafana-clickhouse-datasource` does not require network installation (because the server cannot access the network smoothly).

### Environment

- Git hash commit (`git log -1`):
  - commit 68e690f8588fa984c9f0c4c9403d89b8d8298fa8 (HEAD -> master, tag: v2.6.0, origin/master)
- Docker version `docker version` (e.g. Docker 17.0.05):
    <details>
    <summary>Version:           24.0.5</summary>
    <p>
    Client:
     Version:           24.0.5
     API version:       1.43
     Go version:        go1.20.6
     Git commit:        ced0996600
     Built:             Wed Jul 26 21:44:58 2023
     OS/Arch:           linux/amd64
     Context:           default
    
    Server:
     Engine:
      Version:          24.0.5
      API version:      1.43 (minimum version 1.12)
      Go version:       go1.20.6
      Git commit:       a61e2b4c9c
      Built:            Wed Jul 26 21:44:58 2023
      OS/Arch:          linux/amd64
      Experimental:     false
     containerd:
      Version:          v1.7.2
      GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58.m
     runc:
      Version:          1.1.9
      GitCommit:
     docker-init:
      Version:          0.19.0
      GitCommit:        de40ad0
    </p>
    </details>
- Are you using Docker Swarm or Kubernetes? no.
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat_server` container</summary>
    <p>
    cvat_ui                        | 192.168.0.5 - - [25/Aug/2023:04:02:59 +0000] "GET /analytics HTTP/1.1" 200 668 "https://domain0.org/jobs?page=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.200" "10.66.100.7, 192.168.0.1"
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:00,943 DEBG 'uvicorn-0' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/users/self?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:00,995 DEBG 'uvicorn-0' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/users/self?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/users/self?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,041 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/users/self?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     192.168.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
    
    cvat_server                    | 2023-08-25 04:03:01,059 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     192.168.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | 2023-08-25 04:03:01,070 DEBG 'uvicorn-1' stderr output:
    
    cvat_server                    | [2023-08-25 04:03:01,070] WARNING django.request: Not Found: /api/user-agreements
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | 2023-08-25 04:03:01,072 DEBG 'uvicorn-1' stderr output:
    
    cvat_server                    | WARNING:django.request:Not Found: /api/user-agreements
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/user-agreements?org= HTTP/1.0" 404 Not Found
    
    cvat_server                    | 2023-08-25 04:03:01,075 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/user-agreements?org= HTTP/1.0" 404 Not Found
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "OPTIONS /api/auth/password/change?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,090 DEBG 'uvicorn-0' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "OPTIONS /api/auth/password/change?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/server/plugins?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,104 DEBG 'uvicorn-0' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/server/plugins?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "OPTIONS /api/auth/password/reset?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,106 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "OPTIONS /api/auth/password/reset?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/server/about?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,108 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/server/about?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/server/annotation/formats?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,113 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/server/annotation/formats?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/organizations?org=&page_size=500&page=1 HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,131 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/organizations?org=&page_size=500&page=1 HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/lambda/functions?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,292 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/lambda/functions?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | 2023-08-25 04:03:01,307 DEBG 'uvicorn-1' stderr output:
    
    cvat_server                    | [2023-08-25 04:03:01,306] WARNING django.request: Not Found: /api/functions
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | 2023-08-25 04:03:01,307 DEBG 'uvicorn-1' stderr output:
    
    cvat_server                    | WARNING:django.request:Not Found: /api/functions
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/functions?org=&page_size=500&page=1 HTTP/1.0" 404 Not Found
    
    cvat_server                    | 2023-08-25 04:03:01,307 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/functions?org=&page_size=500&page=1 HTTP/1.0" 404 Not Found
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/tasks?org=&page=1&page_size=10 HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,433 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/tasks?org=&page=1&page_size=10 HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/lambda/requests?org= HTTP/1.0" 200 OK
    
    cvat_server                    | 2023-08-25 04:03:01,486 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/lambda/requests?org= HTTP/1.0" 200 OK
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | 2023-08-25 04:03:01,502 DEBG 'uvicorn-1' stderr output:
    
    cvat_server                    | [2023-08-25 04:03:01,501] WARNING django.request: Not Found: /api/functions/requests/
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | 2023-08-25 04:03:01,502 DEBG 'uvicorn-1' stderr output:
    
    cvat_server                    | WARNING:django.request:Not Found: /api/functions/requests/
    
    cvat_server                    |
    
    cvat_server                    |
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/functions/requests/?org= HTTP/1.0" 404 Not Found
    
    cvat_server                    | 2023-08-25 04:03:01,502 DEBG 'uvicorn-1' stdout output:
    
    cvat_server                    | INFO:     10.66.100.7:0 - "GET /api/functions/requests/?org= HTTP/1.0" 404 Not Found
    
    cvat_server                    |
    
    cvat_server                    |
    </p>
    </details>

    <details>
    <summary>Logs from `traefik` container</summary>
    <p>
    time="2023-08-25T03:11:19Z" level=info msg="Configuration loaded from flags."
    
    time="2023-08-25T03:11:19Z" level=error msg="entryPoint \"websecure\" doesn't exist" entryPointName=websecure routerName=grafana_https@file
    
    time="2023-08-25T03:11:19Z" level=error msg="no valid entryPoint for this router" routerName=grafana_https@file
    
    time="2023-08-25T03:11:19Z" level=error msg="entryPoint \"websecure\" doesn't exist" entryPointName=websecure routerName=grafana_https@file
    
    time="2023-08-25T03:11:19Z" level=error msg="no valid entryPoint for this router" routerName=grafana_https@file
    
    time="2023-08-25T03:11:19Z" level=error msg="entryPoint \"websecure\" doesn't exist" routerName=grafana_https@file entryPointName=websecure
    
    time="2023-08-25T03:11:19Z" level=error msg="no valid entryPoint for this router" routerName=grafana_https@file
    
    time="2023-08-25T03:11:19Z" level=error msg="entryPoint \"websecure\" doesn't exist" routerName=grafana_https@file entryPointName=websecure
    
    time="2023-08-25T03:11:19Z" level=error msg="no valid entryPoint for this router" routerName=grafana_https@file
    
    time="2023-08-25T03:11:21Z" level=error msg="entryPoint \"websecure\" doesn't exist" routerName=grafana_https@file entryPointName=websecure
    
    time="2023-08-25T03:11:21Z" level=error msg="no valid entryPoint for this router" routerName=grafana_https@file
    
    time="2023-08-25T03:11:21Z" level=error msg="entryPoint \"websecure\" doesn't exist" routerName=grafana_https@file entryPointName=websecure
    
    time="2023-08-25T03:11:21Z" level=error msg="no valid entryPoint for this router" routerName=grafana_https@file
    </p>
    </details>

    <details>
    <summary>Logs from `cvat_opa` container</summary>
    <p>
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:22Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:22Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:22Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:22Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:22Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:23Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:24Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:26Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:28Z"}
    
    {"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 192.168.0.9:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-08-25T03:11:32Z"}
    </p>
    </details>
- `docker-compose.override.yml`
    <details>
    <summary>Content of docker-compose.override.yml</summary>
    <p>
    version: "3.3"
    
    services:
      cvat_server:
        volumes:
          - cvat_share:/home/django/share:rw
          - cvat_keys:/home/django/keys:rw
        environment:
          no_proxy: clickhouse,grafana,vector,nuclio,opa,host.docker.internal,${no_proxy:-}
        labels:
          - traefik.enable=true
          - traefik.http.services.cvat.loadbalancer.server.port=8080
          - traefik.http.routers.cvat.entrypoints=web
          - traefik.http.routers.cvat.rule=(Host(`${CVAT_HOST:-localhost}`) ||
            Host(`domain0.org`) ||
            Host(`domain0.org`)) &&
            PathPrefix(`/api/`, `/git/`, `/analytics/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)
      cvat_worker_import:
        volumes:
          - cvat_share:/home/django/share:rw
      cvat_worker_export:
        volumes:
          - cvat_share:/home/django/share:rw
      cvat_worker_annotation:
        volumes:
          - cvat_share:/home/django/share:rw
      cvat_ui:
        labels:
          - traefik.http.routers.cvat-ui.rule=Host(`${CVAT_HOST:-localhost}`) || Host(`domain0.org`) || Host(`domain1.org`)
      traefik:
        command:
          - '--providers.docker.exposedByDefault=false'
          - '--providers.docker.network=cvat'
          - '--entryPoints.web.address=:8080'
          - '--providers.file.directory=/etc/traefik/rules'
          - '--entryPoints.web.forwardedHeaders.insecure'
      cvat_grafana:
        volumes:
          - /home/xxx/docker/cvat/components/analytics/grafana/dashboards/:/var/lib/grafana/dashboards/:ro
          - /home/xxx/docker/cvat_analytics/grafana-clickhouse-datasource/:/var/lib/grafana/plugins/grafana-clickhouse-datasource/:ro
          - /home/xxx/docker/cvat_analytics/run.sh:/run.sh
    volumes:
      cvat_share:
        driver_opts:
          type: none
          device: /home/xxx/docker/cvat_share
          o: bind
      cvat_keys:
        driver_opts:
          type: none
          device: /home/xxx/docker/cvat_keys
          o: bind
    </p>
    </details>

**Comment by bsekachev** [comment]
I believe this is a reason:

```
time="2023-08-25T03:11:19Z" level=error msg="no valid entryPoint for this router" routerName=grafana_https@file
time="2023-08-25T03:11:19Z" level=error msg="entryPoint "websecure" doesn't exist" entryPointName=websecure routerName=grafana_https@file
```

After modification it does not see entrypoint and redirects to default CVAT page.

**Comment by lll9p** [comment]
@bsekachev Got it worked. I removed `/Analytics` from cvat_server's labels, like

      - traefik.http.routers.cvat.rule=(Host(`${CVAT_HOST:-localhost}`) || Host(`somedomain.org`)) &&
        PathPrefix(`/api/`, `/git/`, `/opencv`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)

💯

**Comment by sunyuan789** [comment]
@lll9p Hello, I meet the same problem as you. Could you please tell me how to solve it? There is not /Analytics in cvat_server's labels.

**Comment by lll9p** [comment]
> [@lll9p](https://github.com/lll9p) Hello, I meet the same problem as you. Could you please tell me how to solve it? There is not /Analytics in cvat_server's labels.

I manually downloaded grafana and it worked, maybe you can try with it.


```yaml
.... other configs
  traefik:
    command:
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=cvat'
      - '--entryPoints.web.address=:8080'
      - '--providers.file.directory=/etc/traefik/rules'
      - '--entryPoints.web.forwardedHeaders.insecure'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/some_dir/cvat_analytics/grafana_conf.yml:/etc/traefik/rules/grafana_conf.yml:ro
  cvat_grafana:
    volumes:
      - grafana_dashboards:/var/lib/grafana/dashboards/:ro
      - grafana_clickhouse:/var/lib/grafana/plugins/grafana-clickhouse-datasource/:ro
      - ${HOME}/some_dir/cvat_analytics/run.sh:/run.sh:ro
volumes:
  grafana_dashboards:
    driver_opts:
      type: none
      device: ${HOME}/some_dir/cvat/components/analytics/grafana/dashboards
      o: bind
  grafana_clickhouse:
    driver_opts:
      type: none
      device: ${HOME}/some_dir/cvat_analytics/grafana-clickhouse-datasource
      o: bind
.... other configs
```
