### ISSUE TITLE
Fresh cvat installation result in huge django size

### ISSUE THREAD

**Issue by Djkmarco** [opencv/cvat#6757]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

Fresh installation on cvat after removing previous installation, uninstalled docker and all related files. The disk is 4Tb and 75% is free.

### Expected Behaviour
Working CVAT on local machine

### Current Behaviour
Cannot connect to the server
Make sure the CVAT backend and all necessary services (Database, Redis and Open Policy Agent) are running and available. If you upgraded from version 2.2.0 or earlier, manual actions may be needed, see the [Upgrade Guide](https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide).

### Context
Relevant log:

```
2023-08-28 10:02:51,691 DEBG 'uvicorn-1' stderr output:
ERROR:health-check:warning: b6837d7489b2 96.0% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(
health_check.exceptions.ServiceWarning: warning: b6837d7489b2 96.0% disk usage exceeds 90%

2023-08-28 10:02:51,775 DEBG 'uvicorn-1' stderr output:
[2023-08-28 10:02:51,774] ERROR django.request: Internal Server Error: /api/server/health/

2023-08-28 10:02:51,775 DEBG 'uvicorn-1' stderr output:
ERROR:django.request:Internal Server Error: /api/server/health/

INFO:     172.21.0.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error
2023-08-28 10:02:51,775 DEBG 'uvicorn-1' stdout output:
INFO:     172.21.0.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error
```
```

docker exec -it -u django cvat_server python -c 'import os; print(os.statvfs("/"))'
os.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=480302136, f_bfree=42468282, f_bavail=18051822, f_files=122068992, f_ffree=117056135, f_favail=117056135, f_flag=4096, f_namemax=255)
```

```
docker exec -it -u django cvat_server python -c 'import psutil; print(psutil.disk_usage("/"))'
sdiskusage(total=1967317549056, used=1793367642112, free=73940086784, percent=96.0)

```

```
Filesystem      Size  Used Avail Use% Mounted on
overlay         1.8T  1.7T   69G  97% /
```

### Your Environment

- Git hash commit (`git log -1`): ttps://github.com/opencv/cvat
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 24.0.5, build ced0996
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04

**Comment by bsekachev** [comment]
- Check unused docker images
- ONLY If you wanted to delete all existed data, be sure you removed corresponding docker volumes (like cvat_data and cvat_db)
- Check what consumes your disk space, you have only 73 Gb free

**Comment by Djkmarco** [comment]
Thanks, deleting the old volumes worked for me.
