### ISSUE TITLE
Add information about Swagger REST API documentation to CVAT documentation

### ISSUE THREAD

**Issue by lmessinger** [opencv/cvat#676]
hi all
we're adding tasks through the API (post http://localhost:8080/api/v1/tasks) which works nicely (adding data is **undocumented** but we were lucky to **guess** it: http://localhost:8080/api/v1/tasks/-id here-/data')

But: can't find the field name to put the **git repository**. 

Any ideas?

thanks very much!

**Comment by bsekachev** [comment]
@lmessinger 
First of all, there is a documentation about Rest API: http://localhost:8080/api/swagger
Now about git repository. It isn't included to Rest API for now.
If you look at client side JS code, you can see how it is implemented and what URLs are used.
```
try {
    response = await $.ajax({
        url: `/git/repository/create/${createdTask.id}`,
        type: 'POST',
        data: JSON.stringify({
            path,
            lfs,
            tid: createdTask.id,
        }),
        contentType: 'application/json',
    });
} catch (errorData) {
    createdTask.delete();
    const message = `Can not send a request to clone the repository. Code: ${errorData.status}. `
        + `Message: ${errorData.responseText || errorData.statusText}`;
    throw new Error(message);
}

More code there: ``cvat/apps/git/static/git/js/dashboardPlugin.js``
```

**Comment by lmessinger** [comment]
thank you very much. I had no idea about this swagger thing. i would suggest to put it on the wiki so people would know

**Comment by bsekachev** [comment]
@lmessinger 
Great, I agree about documentation.
