### ISSUE TITLE
Label conversion/matching when uploading annotations

### ISSUE THREAD

**Issue by menggui1993** [opencv/cvat#6763]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I want to match the labels for several datasets. So I'm looking for a function to match the labels when uploading annotations or convert the labels after the annotations are uploaded. I tried to search the docs but found no luck. Is there an existing feature in cvat to do this or maybe adding this function in the future? Thanks.

**Comment by zhiltsov-max** [comment]
Hi! Please explain what you're trying to do in more detail. If you want to upload a dataset with some labels, that do not match task labels in CVAT, there is no option for this in CVAT yet. However, you can try to use, e.g., Datumaro, to transform the labels before uploading:

```bash
python3 -m virtualenv venv
. venv/bin/activate
pip install 'git+https://github.com/cvat-ai/datumaro.git@ff83c00c2c1bc4b8fdfcc55067fcab0a9b5b6b11'

datum transform --help
datum transform -t remap_labels -- --help
```

Read command docs [here](https://openvinotoolkit.github.io/datumaro/latest/docs/command-reference/context_free/transform.html#remap-labels).

If CLI is not enough, you can also use a simple custom script instead: 

```python
import datumaro as dm

dataset = dm.Dataset.import_from(path) # check format names in 'datum import -h'
dataset.transform('remap_labels', 
    mapping={ # suppose we have labels "label0...label5" in the dataset
        "label1": "label9",  # rename & join with new label9 (from label3)
        "label2": "label0",  # rename & join with existing label0
        "label3": "label9",  # rename & join with new label9 (from label1)
        "label4": "",  # delete the label and associated annotations
        # 'label5' - unchanged
    },
    default="keep",
)
dataset.export(new_path, format_name, save_images=True) # check format names in 'datum export -h'
```

**Comment by menggui1993** [comment]
@zhiltsov-max Thanks. This is exactly what I'm looking for.
