### ISSUE TITLE
Error when Docker Builing Cvat 2.4.2

### ISSUE THREAD

**Issue by Lee4396** [opencv/cvat#6764]
The following error happens when building version 2.4.1 and 2.4.2:

Collecting av==9.2.0
#19 79.79   Downloading av-9.2.0.tar.gz (2.4 MB)
#19 79.83      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 71.2 MB/s eta 0:00:00
#19 80.21   Installing build dependencies: started
#19 85.26   Installing build dependencies: finished with status 'done'
#19 85.26   Getting requirements to build wheel: started
#19 88.45   Getting requirements to build wheel: finished with status 'error'
#19 88.46   error: subprocess-exited-with-error
#19 88.46
#19 88.46   × Getting requirements to build wheel did not run successfully.
#19 88.46   │ exit code: 1
#19 88.46   ╰─> [70 lines of output]
#19 88.46       Compiling av/_core.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/_core.pyx
#19 88.46       Compiling av/buffer.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/buffer.pyx
#19 88.46       Compiling av/bytesource.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/bytesource.pyx
#19 88.46       Compiling av/descriptor.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/descriptor.pyx
#19 88.46       Compiling av/dictionary.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/dictionary.pyx
#19 88.46       Compiling av/enum.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/enum.pyx
#19 88.46       Compiling av/error.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/error.pyx
#19 88.46       Compiling av/format.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/format.pyx
#19 88.46       Compiling av/frame.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/frame.pyx
#19 88.46
#19 88.46       Error compiling Cython file:
#19 88.46       ------------------------------------------------------------
#19 88.46       ...
#19 88.46       cdef const char *log_context_name(void *ptr) nogil:
#19 88.46           cdef log_context *obj = <log_context*>ptr
#19 88.46           return obj.name
#19 88.46
#19 88.46       cdef lib.AVClass log_class
#19 88.46       log_class.item_name = log_context_name
#19 88.46                             ^
#19 88.46       ------------------------------------------------------------
#19 88.46
#19 88.46       av/logging.pyx:216:22: Cannot assign type 'const char *(void *) except? NULL nogil' to 'const char *(*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'const char *(void *) except? NULL nogil'.
#19 88.46
#19 88.46       Error compiling Cython file:
#19 88.46       ------------------------------------------------------------
#19 88.46       ...
#19 88.46
#19 88.46       # Start the magic!
#19 88.46       # We allow the user to fully disable the logging system as it will not play
#19 88.46       # nicely with subinterpreters due to FFmpeg-created threads.
#19 88.46       if os.environ.get('PYAV_LOGGING') != 'off':
#19 88.46           lib.av_log_set_callback(log_callback)
#19 88.46                                   ^
#19 88.46       ------------------------------------------------------------
#19 88.46
#19 88.46       av/logging.pyx:351:28: Cannot assign type 'void (void *, int, const char *, va_list) except * nogil' to 'av_log_callback'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *, va_list) except * nogil'.
#19 88.46       Compiling av/logging.pyx because it changed.
#19 88.46       [1/1] Cythonizing av/logging.pyx
#19 88.46       Traceback (most recent call last):
#19 88.46         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#19 88.46           main()
#19 88.46         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#19 88.46           json_out['return_val'] = hook(**hook_input['kwargs'])
#19 88.46         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#19 88.46           return hook(config_settings)
#19 88.46         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
#19 88.46           return self._get_build_requires(
#19 88.46         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
#19 88.46           self.run_setup()
#19 88.46         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
#19 88.46           super(_BuildMetaLegacyBackend,
#19 88.46         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
#19 88.46           exec(compile(code, __file__, 'exec'), locals())
#19 88.46         File "setup.py", line 157, in <module>
#19 88.46           ext_modules += cythonize(
#19 88.46         File "/tmp/pip-build-env-tcb_ig11/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
#19 88.46           cythonize_one(*args)
#19 88.46         File "/tmp/pip-build-env-tcb_ig11/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
#19 88.46           raise CompileError(None, pyx_file)
#19 88.46       Cython.Compiler.Errors.CompileError: av/logging.pyx
#19 88.46       [end of output]
#19 88.46
#19 88.46   note: This error originates from a subprocess, and is likely not a problem with pip.
#19 88.46 error: subprocess-exited-with-error
#19 88.46
#19 88.46 × Getting requirements to build wheel did not run successfully.
#19 88.46 │ exit code: 1
#19 88.46 ╰─> See above for output.
#19 88.46
#19 88.46 note: This error originates from a subprocess, and is likely not a problem with pip.
------
executor failed running [/bin/sh -c DATUMARO_HEADLESS=1 python3 -m pip wheel --no-cache-dir     -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt     -r /tmp/dataset_manifest/requirements.txt     -w /tmp/wheelhouse]: exit code: 1

**Comment by bsekachev** [comment]
Hi, @Lee4396 

First of all, try the latest release 2.6.1.

**Comment by zhiltsov-max** [comment]
Might have been fixed in https://github.com/opencv/cvat/pull/6592

**Comment by bsekachev** [comment]
Database will migrate to the newest version keeping existing data on container startup.
I do not have enough knowledge to make an idea about file storage, maybe @azhavoro can suggest something.

**Comment by arunima-pirllabs** [comment]
for **Python 3.11.8** make these changes in the following requirements files: 
```
## cvat/requirements/base.in
-boto3==1.17.61
+boto3==1.34.64
-botocore==1.20.112
+botocore==1.34.64
     # via
     #   boto3
     #   s3transfer
-s3transfer==0.4.2
+s3transfer==0.10.1
-urllib3==1.26.18
+urllib3==2.2.1
     # via
     #   botocore
     #   clickhouse-connect

## utils/dataset_manifest/requirements.in
-av==9.2.0  # Pinned for the whole CVAT
+av==11.0.0  # Pinned for the whole CVAT

## utils/dataset_manifest/requirements.txt
-av==9.2.0
+av==11.0.0
     # via -r utils/dataset_manifest/requirements.in
 natsort==8.0.0
     # via -r utils/dataset_manifest/requirements.in
-numpy==1.22.4
+numpy==1.26.4
     # via opencv-python-headless
-opencv-python-headless==4.8.1.78
+opencv-python-headless==4.9.0.80
     # via -r utils/dataset_manifest/requirements.in

```
![Screenshot from 2024-03-18 11-06-45](https://github.com/opencv/cvat/assets/162993962/7b60a6f4-f895-484f-92d8-0a10903a802e)
