### ISSUE TITLE
Export takes and [endless] amount of time, barely any cpu usage

### ISSUE THREAD

**Issue by samsterckval** [opencv/cvat#6765]
### My actions before raising this issue
- [ x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x ] Searched [past issues](/issues)

### Expected Behaviour
On the web UI, click "export dataset", select COCO, unselect export images, click export.
After a while the ZIP is downloaded with the annotations in COCO format.

### Current Behaviour
On the web UI, click "export dataset", select COCO, unselect export images, click export.
1 hour later, still nothing has downloaded, but can't export to COCO again (grayed out & rotating icon).

### Context
Around 100 video's of a 300 video dataset have been annotated.  Trying to export them to run first few test.
CVAT running in container through docker compose on a local PC, which has no internet access.
I have no prior experience with CVAT, so I might be overlooking something stupid.
Where would CVAT store everything?  Is there a way I can copy everything onto a different PC already so I am sure the data wont just get lost? 

### Your Environment

- Git hash commit (`git log -1`): commit 636dc6a58e279990088d3b6a7f7f66452c2ecc43 (HEAD, tag: v2.5.2, origin/master)
- Docker version `docker version` (e.g. Docker 17.0.05): 23.0.2
- Are you using Docker Swarm or Kubernetes?  Docker compose locally
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04.1
- Other diagnostic information / logs:
<details>
    <summary>Logs from `cvat_worker_export` container</summary>

```
2023-08-29 08:12:56,136 DEBG 'rqworker-export-0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-08-29 08:12:56,136 DEBG 'rqworker-export-1' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-08-29 08:19:41,181 DEBG 'rqworker-export-0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-08-29 08:19:41,181 DEBG 'rqworker-export-1' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
```

</details>

**Comment by bsekachev** [comment]
You can find if there are any active export requests on django admin page: ``<host:port>/django-rq/``
If there are not, try to export one more time. It is difficult to make a suggestions on what is going on without access to the server.
According to provided logs, I do not see any export requests.
