### ISSUE TITLE
Error: Request failed with status code 400.

### ISSUE THREAD

**Issue by Sandesh-Rprocess** [opencv/cvat#6767]
Hello there,

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/issues/4433)

I'm writing to you because we have been facing an issue with the tool CVAT. When we try to upload the annotations. it gives us the following error:

Error: Request failed with status code 400. "Image B8_1_w_carrots/images/crop1_b8_1_586: can't import annotation #1 (mask): zero-size array to reduction operation minimum which has no identity"..
&
Error: Request failed with status code 400. "Could not match item id: 'B8_1_w_carrots/images/crop0_b8_1_002' with any task frame"..

I am trying to upload the format in COCO 1.0 format.

tried to upload the task with version 2.61 (Online) & Localhost:8080
below is the error ststua we received while upload the file :
![image](https://github.com/opencv/cvat/assets/113497605/59c0a0bc-571d-47c0-8573-b182f4ef18c2)

I would really appreciate it if you have any idea on how we can fix this. Thanks!

**Comment by bsekachev** [comment]
> Error: Request failed with status code 400. "Image B8_1_w_carrots/images/crop1_b8_1_586: can't import annotation https://github.com/opencv/cvat/issues/1 (mask): zero-size array to reduction operation minimum which has no identity"..

Looks like the annotation format has incorrect input for a mask (empty array?)

> Error: Request failed with status code 400. "Could not match item id: 'B8_1_w_carrots/images/crop0_b8_1_002' with any task frame"

Imported file does contains file names not presented in the task

**Comment by Sandesh-Rprocess** [comment]
> > Error: Request failed with status code 400. "Image B8_1_w_carrots/images/crop1_b8_1_586: can't import annotation #1 (mask): zero-size array to reduction operation minimum which has no identity"..
> 
> Looks like the annotation format has incorrect input for a mask (empty array?)
> 
> > Error: Request failed with status code 400. "Could not match item id: 'B8_1_w_carrots/images/crop0_b8_1_002' with any task frame"
> 
> Imported file contains file names not presented in the task

Thank you for the reply, will check with the output file again.
