### ISSUE TITLE
backup error

### ISSUE THREAD

**Issue by didnmj** [opencv/cvat#6774]
![image](https://github.com/opencv/cvat/assets/71330550/b46b716e-e708-4f63-ac59-98338de0f237)

Hello
I backed up a 56GB project, closed the server, and reopened it.
And when I tried to add a backed up project, I got this error.
Please help me

**Comment by bsekachev** [comment]
You can setup TUS_MAX_FILE_SIZE = 26843545600 # 25gb option in configuration file ```cvat/settings/base.py```, than rebuild CVAT with ``-f docker-compose.dev.yml`` option.
