### ISSUE TITLE
cvat sdk export task dataset without saving images

### ISSUE THREAD

**Issue by VG-Huai** [opencv/cvat#6776]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/tasks-api/#retrieve_dataset)
- [ ] Searched [past issues](/issues)

Hello, 
I tried to export a task dataset's annotations with a specific format by cvat sdk.  But I can not export the task dataset without saving images by function  `api_client.tasks_api.retrieve_dataset` and haven't found solutions in doc. I would be very grateful for the help

Here's my code:
```
with ApiClient(configuration) as api_client:
    format = "LabelMe 3.0" # str | Desired output format name You can get the list of supported formats at: /server/annotation/formats
    id = 106 # int | A unique integer value identifying this task.
    action = "download" # str | Used to start downloading process after annotation file had been created (optional) if omitted the server will use the default value of "download"
    # cloud_storage_id = 3.14 # float | Storage id (optional)
    filename = "my_dir/filename_example.zip" # str | Desired output file name (optional)
    location = "local" # str | Where need to save downloaded dataset (optional)
    use_default_location = True # bool | Use the location that was configured in task to export annotations (optional) if omitted the server will use the default value of True

    try:
        (data, response) = api_client.tasks_api.retrieve_dataset(
            format,
            id,
            action=action,
            # cloud_storage_id=cloud_storage_id,
            filename=filename,
            location=location,
            use_default_location=use_default_location,
        )
        pprint(data)
    except exceptions.ApiException as e:
        print("Exception when calling TasksApi.retrieve_dataset(): %s\n" % e)
```

**Comment by zhiltsov-max** [comment]
Hi, please use [`retrieve_annotations()`](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/tasks-api/#retrieve_annotations) instead. You can also use the high-level API ([example](https://github.com/opencv/cvat/issues/6678#issuecomment-1679616560)).

**Comment by VG-Huai** [comment]
Thanks a lot，I use the high-level API and it works
