### ISSUE TITLE
Could not Upload Annotations

### ISSUE THREAD

**Issue by rickearthc137** [opencv/cvat#6782]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I'm trying to upload annotations to a already created task. I used YOLO 1.1 format as mentioned in the [cvat docs](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-yolo/#yolohttpspjreddiecomdarknetyolo), even used the same format for uploading dataset also.
### Steps to Reproduce (for bugs)

1. 
1.
1.
1.

### Expected Behaviour

I should be able to upload annotations
### Current Behaviour

![image](https://github.com/opencv/cvat/assets/135340559/4d086c92-bf35-49bd-9647-f042299871bb)

Console:

cvat-app.tsx:359 Error: Request failed with status code 500. "Traceback (most recent call last):\n  File \"/opt/venv/lib/python3.10/site-packages/rq/worker.py\", line 936, in perform_job\n    rv = job.perform()\n  File \"/opt/venv/lib/python3.10/site-packages/rq/job.py\", line 684, in perform\n    self._result = self._execute()\n  File \"/opt/venv/lib/python3.10/site-packages/rq/job.py\", line 690, in _execute\n    return self.func(*self.args, **self.kwargs)\n  File \"/home/django/cvat/apps/engine/utils.py\", line 260, in import_resource_with_clean_up_after\n    result = func(filename, *args, **kwargs)\n  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n    return func(*args, **kwds)\n  File \"/home/django/cvat/apps/dataset_manager/task.py\", line 895, in import_task_annotations\n    task.import_annotations(f, importer, conv_mask_to_poly=conv_mask_to_poly)\n  File \"/home/django/cvat/apps/dataset_manager/task.py\", line 779, in import_annotations\n    importer(src_file, temp_dir, task_data, **options)\n  File \"/home/django/cvat/apps/dataset_manager/formats/registry.py\", line 36, in __call__\n    f_or_cls(*args, **kwargs)\n  File \"/home/django/cvat/apps/dataset_manager/formats/yolo.py\", line 50, in _import\n    dataset = Dataset.import_from(temp_dir, 'yolo',\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/components/dataset.py\", line 1197, in import_from\n    env.make_extractor(src_conf.format, src_conf.url, **extractor_kwargs)\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/components/environment.py\", line 230, in make_extractor\n    return self.extractors.get(name)(*args, **kwargs)\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/plugins/yolo_format/extractor.py\", line 107, in __init__\n    AnnotationType.label: self._load_categories(\n  File \"/opt/venv/lib/python3.10/site-packages/datumaro/plugins/yolo_format/extractor.py\", line 252, in _load_categories\n    with open(names_path, \"r\", encoding=\"utf-8\") as f:\nFileNotFoundError: [Errno 2] No such file or directory: '/home/django/data/tasks/21/tmp/tmpvy4kwehu/obj.names'\n"..

### Possible Solution

No idea
### Context

Since I'm using already annotated data to change the labels, it would save a lot of time.
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):  4.21.1
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Windows
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>[2023-09-01 09:57:32,981] INFO cvat.server: Starting to get chunk from cache: key 21_686_Quality.COMPRESSED
[2023-09-01 09:57:32,985] INFO cvat.server: Ending to get chunk from cache: key 21_686_Quality.COMPRESSED, is_cached False
[2023-09-01 09:57:32,985] INFO cvat.server: Starting to prepare chunk: key 21_686_Quality.COMPRESSED
[2023-09-01 09:57:36,959] INFO cvat.server: Ending to prepare chunk: key 21_686_Quality.COMPRESSED
[2023-09-01 10:33:13,229] ERROR cvat.server.engine: Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/engine/utils.py", line 260, in import_resource_with_clean_up_after
    result = func(filename, *args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 895, in import_task_annotations
    task.import_annotations(f, importer, conv_mask_to_poly=conv_mask_to_poly)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 779, in import_annotations
    importer(src_file, temp_dir, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/yolo.py", line 50, in _import
    dataset = Dataset.import_from(temp_dir, 'yolo',
  File "/opt/venv/lib/python3.10/site-packages/datumaro/components/dataset.py", line 1197, in import_from
    env.make_extractor(src_conf.format, src_conf.url, **extractor_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/datumaro/components/environment.py", line 230, in make_extractor
    return self.extractors.get(name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/datumaro/plugins/yolo_format/extractor.py", line 107, in __init__
    AnnotationType.label: self._load_categories(
  File "/opt/venv/lib/python3.10/site-packages/datumaro/plugins/yolo_format/extractor.py", line 252, in _load_categories
    with open(names_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/data/tasks/21/tmp/tmpe729s4nz/obj.names'

[2023-09-01 10:33:13,240] ERROR django.request: Internal Server Error: /api/tasks/21/annotations</summary>
    </details>

**Comment by bsekachev** [comment]
Please, check if you have file ``obj.names`` in your archive.

**Comment by rickearthc137** [comment]
Sorry, my bad. While was checking, I found out that the `obj.names` file is actually saved as `obj.names.txt`
Thanks @bsekachev

**Comment by rickearthc137** [comment]
I changed the file name and created a new task. When I try to upload annotations, I get this error:
`Error: Request failed with status code 400. "Failed to import item (file_name, 'valid'): [Errno 2] No such file or directory: '/home/django/data/tasks/2/tmp/tmp2841ek1c/obj_train_data/file_name.txt'"..`

Here's the folder structure of the .zip file that is used for uploading annotations:
├───`obj_train_data`
├───`obj_valid_data`
├───`obj.names`
├───`obj.data`
├───`train.txt`
└───`valid.txt`

I don't understand why it's searching in `obj_train_data` when the file is in the `valid` folder.

**Comment by Lee4396** [comment]
I also have this problem, and it seems to be related to cvat version upgrade
