### ISSUE TITLE
Pre-annotated dataset not visualized correctly in CVAT

### ISSUE THREAD

**Issue by prashant-dn** [opencv/cvat#6785]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I annotate a simple one image data by drawing a rotated bounding box. Then I export it in COCO format. 
Then I try to upload/load this dataset (zip) into CVAT to visualize my annotations and add more boxes but now the boxes are visualized un-rotated. 
e.g., while annotating
<img width="804" alt="Screenshot 2023-09-02 at 12 17 52 AM" src="https://github.com/opencv/cvat/assets/138000770/7311862b-d225-46cf-b3fd-2b4ec4e7a2b0">

After exporting and re-uploading 
<img width="758" alt="Screenshot 2023-09-02 at 12 18 41 AM" src="https://github.com/opencv/cvat/assets/138000770/9576db6e-7c00-4548-8630-fb39f233e4f5">

### Steps to Reproduce (for bugs)
Use this exported dataset and upload it to CVAT using coco format
[](url)
[coco-rotated.zip](https://github.com/opencv/cvat/files/12500825/coco-rotated.zip)

The json reflects the actual rotation component of the bounding boxes which is not reflected in the visualization window.

### Expected Behaviour
Rotated bounding boxes

### Current Behaviour
Un-rotated bounding boxes

### Possible Solution
NA

### Your Environment

- Git hash commit (`git log -1`): NA
- Docker version `docker version` (e.g. Docker 17.0.05): No
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:

**Comment by zhiltsov-max** [comment]
Hi! COCO doesn't support rotated bounding boxes natively. CVAT adds rotation as a custom attribute, but it's not imported, as COCO isn't expected to contain it.

**Comment by prashant-dn** [comment]
Hi @zhiltsov-max 
So what format does CVAT have, that supports rotation?

**Comment by zhiltsov-max** [comment]
You can use both CVAT for images/video formats instead.
