### ISSUE TITLE
Error when deploying CPU SAM model on Ubuntu 20.04 x86_64

### ISSUE THREAD

**Issue by GilbertPan97** [opencv/cvat#6787]
I encountered an issue while attempting to deploy a CPU-based SAM model on my machine running Ubuntu 20.04 x86_64 using the following deployment command:
```
./serverless/deploy_cpu.sh serverless/pytorch/facebookresearch/sam/nuclio/
```
The error message I received is as follows:
```
[+] Building 3.2s (9/9) FINISHED                                                                                                                                                            docker:default
 => [internal] load .dockerignore                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                       0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.0s
 => => transferring dockerfile: 418B                                                                                                                                                                  0.0s
 => [internal] load metadata for docker.io/openvino/ubuntu20_runtime:2022.3.0                                                                                                                         3.1s
 => [1/4] FROM docker.io/openvino/ubuntu20_runtime:2022.3.0@sha256:0cdf91fab23967cbffd57edf203811fd77dde2ea7fe251d240d6ef2a0882db24                                                                   0.0s
 => [internal] load build context                                                                                                                                                                     0.0s
 => => transferring context: 66B                                                                                                                                                                      0.0s
 => CACHED [2/4] RUN apt-get update     && apt-get -y --no-install-recommends install python-is-python3     && rm -rf /var/lib/apt/lists/*                                                            0.0s
 => CACHED [3/4] RUN pip install --no-cache-dir opencv-python-headless pillow pyyaml                                                                                                                  0.0s
 => CACHED [4/4] COPY model_loader.py shared.py /opt/nuclio/common/openvino/                                                                                                                          0.0s
 => exporting to image                                                                                                                                                                                0.0s
 => => exporting layers                                                                                                                                                                               0.0s
 => => writing image sha256:30925cd206b30b711dbdf618083a324f2bc4eb59323d62a0de72f107f092aff8                                                                                                          0.0s
 => => naming to docker.io/library/cvat.openvino.base                                                                                                                                                 0.0s

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
23.09.02 18:09:46.071     nuctl.platform.docker (W) Failed to run container {"err": "stdout:\nUnable to find image 'gcr.io/iguazio/alpine:3.17' locally\ndocker: Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.\n\nstderr:\n", "errVerbose": "\nError - exit status 125\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\n\nCall stack:\nstdout:\nUnable to find image 'gcr.io/iguazio/alpine:3.17' locally\ndocker: Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.\n\nstderr:\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\nstdout:\nUnable to find image 'gcr.io/iguazio/alpine:3.17' locally\ndocker: Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.\n\nstderr:\n", "stdout": "Unable to find image 'gcr.io/iguazio/alpine:3.17' locally\ndocker: Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.\n", "stderr": ""}

Error - exit status 125
    /nuclio/pkg/cmdrunner/shellrunner.go:114

Call stack:
stdout:
Unable to find image 'gcr.io/iguazio/alpine:3.17' locally
docker: Error response from daemon: Get "https://gcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

stderr:

    /nuclio/pkg/cmdrunner/shellrunner.go:114
Failed to run container with storage volume
    ...//nuclio/pkg/platform/local/client/store.go:432
Failed to run cat command
    ...//nuclio/pkg/platform/local/client/store.go:342
Failed to get projects
    ...//nuclio/pkg/platform/local/client/store.go:101
Failed getting projects
    /nuclio/pkg/platform/local/platform.go:509
```
I try to execute the following deployment command without using a script, while it return the same error:
```
nuctl deploy --project-name cvat --path "`pwd`/pytorch/facebookresearch/sam/nuclio/"  --file "`pwd`/pytorch/facebookresearch/sam/nuclio/function.yaml" --platform local
```
If there's any additional information needed, please let me know, and I'll do my best to provide it.
Thank you for your assistance in resolving this issue! Your help is greatly appreciated.

**Comment by KTXKIKI** [comment]
挂外网  找个vpn啊  兄弟  要挂外网才能拉到'gcr.io/iguazio/alpine:3.17'这个镜像

**Comment by bsekachev** [comment]
```
 Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Docker engine could not achieve gcr.io domain. It may be a temporary problem and later deploy will be successful. 
If the problem persists, try to sort out if you can reach the domain from host machine / from inside the docker container. 
Try to look at other existing issues regarding the problem, like this one #5012

**Comment by GilbertPan97** [comment]
> ```
>  Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> ```
> 
> Docker engine could not achieve gcr.io domain. It may be a temporary problem and later deploy will be successful. If the problem persists, try to sort out if you can reach the domain from host machine / from inside the docker container. Try to look at other existing issues regarding the problem, like this one #5012

First of all, thank you for your prompt response. I followed this issue #5012 to manually pull the 'alpine:3.17' image using the provided command, and it indeed worked successfully on my computer. However, when I attempted to redeploy using './serverless/deploy_cpu.sh serverless/pytorch/facebookresearch/sam/nuclio/', I encountered the following error:
```
 > [ 4/13] RUN pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx:
665.5     for chunk in response.raw.stream(
665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 576, in stream
665.5     data = self.read(amt=amt, decode_content=decode_content)
665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 512, in read
665.5     with self._error_catcher():
665.5   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
665.5     self.gen.throw(typ, value, traceback)
665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
665.5     raise ReadTimeoutError(self._pool, None, "Read timed out.")
665.5 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
------
Dockerfile.processor:24
--------------------
  22 |     RUN apt-get update && apt-get -y install curl git python3 python3-pip ffmpeg libsm6 libxext6
  23 |     
  24 | >>> RUN pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx
  25 |     
  26 |     RUN pip3 install git+https://github.com/facebookresearch/segment-anything.git
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx" did not complete successfully: exit code: 2

    /nuclio/pkg/cmdrunner/shellrunner.go:114
Failed to build
    /nuclio/pkg/dockerclient/shell.go:116
Failed to build docker image
    .../pkg/containerimagebuilderpusher/docker.go:70
Failed to build processor image
    /nuclio/pkg/processor/build/builder.go:264
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:227
```
It seems like a network timeout issue on my computer. However, even when I tried to run the 'deploy_cpu.sh' script again, it kept giving me the following error:
```
What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
23.09.04 18:20:54.600                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}
Deploying pytorch/facebookresearch/sam function...

Error - Function cannot be updated when existing function is being provisioned
    /nuclio/pkg/platform/local/platform.go:219
```
Does this mean I should manually delete 'platform.go' and then rerun the 'deploy_cpu.sh' script, or is there another solution to this issue?

Thank you for your assistance,

**Comment by bsekachev** [comment]
> Does this mean I should manually delete 'platform.go' and then rerun the 'deploy_cpu.sh' script, or is there another solution to this issue?

@GilbertPan97 

Better to ask [nuclio](https://github.com/nuclio/nuclio) community. This is 3rdparty product.

**Comment by fanandli** [comment]
> What's Next?
>   View summary of image vulnerabilities and recommendations → docker scout quickview
> 23.09.04 18:20:54.600                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}
> Deploying pytorch/facebookresearch/sam function...
> 
> Error - Function cannot be updated when existing function is being provisioned
>     /nuclio/pkg/platform/local/platform.go:219

You can log in to the [localhost: 8070](url) page and delete the 'tf patternport mask rcnn' project.
If you have used SSH client software for operation, you can use the tunnel function of SSH client software to map to the local area

**Comment by GilbertPan97** [comment]
> @GilbertPan97 You can log in to the [localhost: 8070](url) page and delete the 'tf patternport mask rcnn' project. If you have used SSH client software for operation, you can use the tunnel function of SSH client software to map to the local area

Thank you for your help. I have already removed the CVAT function from the nuclio dashboard and redeployed it. However, I am still receiving an error as I mentioned earlier:
```
ERROR: failed to solve: process "/bin/sh -c pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx" did not complete successfully: exit code: 2
```
This seems to be caused by an unstable connection of nuclio. Do you have any better ideas?

**Comment by fanandli** [comment]
@GilbertPan97 Perhaps you can try using pip's mirror source. This is usually caused by pip dependency package download failure.
just like:
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by Kk875** [comment]
> > ```
> >  Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> > ```
> > 
> > 
> > Docker engine could not achieve gcr.io domain. It may be a temporary problem and later deploy will be successful. If the problem persists, try to sort out if you can reach the domain from host machine / from inside the docker container. Try to look at other existing issues regarding the problem, like this one #5012
> 
> First of all, thank you for your prompt response. I followed this issue #5012 to manually pull the 'alpine:3.17' image using the provided command, and it indeed worked successfully on my computer. However, when I attempted to redeploy using './serverless/deploy_cpu.sh serverless/pytorch/facebookresearch/sam/nuclio/', I encountered the following error:
> 
> ```
>  > [ 4/13] RUN pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx:
> 665.5     for chunk in response.raw.stream(
> 665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 576, in stream
> 665.5     data = self.read(amt=amt, decode_content=decode_content)
> 665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 512, in read
> 665.5     with self._error_catcher():
> 665.5   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
> 665.5     self.gen.throw(typ, value, traceback)
> 665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
> 665.5     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> 665.5 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
> ------
> Dockerfile.processor:24
> --------------------
>   22 |     RUN apt-get update && apt-get -y install curl git python3 python3-pip ffmpeg libsm6 libxext6
>   23 |     
>   24 | >>> RUN pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx
>   25 |     
>   26 |     RUN pip3 install git+https://github.com/facebookresearch/segment-anything.git
> --------------------
> ERROR: failed to solve: process "/bin/sh -c pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx" did not complete successfully: exit code: 2
> 
>     /nuclio/pkg/cmdrunner/shellrunner.go:114
> Failed to build
>     /nuclio/pkg/dockerclient/shell.go:116
> Failed to build docker image
>     .../pkg/containerimagebuilderpusher/docker.go:70
> Failed to build processor image
>     /nuclio/pkg/processor/build/builder.go:264
> Failed to deploy function
>     ...//nuclio/pkg/platform/abstract/platform.go:227
> ```
> 
> It seems like a network timeout issue on my computer. However, even when I tried to run the 'deploy_cpu.sh' script again, it kept giving me the following error:
> 
> ```
> What's Next?
>   View summary of image vulnerabilities and recommendations → docker scout quickview
> 23.09.04 18:20:54.600                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}
> Deploying pytorch/facebookresearch/sam function...
> 
> Error - Function cannot be updated when existing function is being provisioned
>     /nuclio/pkg/platform/local/platform.go:219
> ```
> 
> Does this mean I should manually delete 'platform.go' and then rerun the 'deploy_cpu.sh' script, or is there another solution to this issue?
> 
> Thank you for your assistance,
hello，i meet the same error：
What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
23.10.17 18:25:12.543                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}
Deploying pytorch/facebookresearch/sam function...

Error - Function cannot be updated when existing function is being provisioned
    /nuclio/pkg/platform/local/platform.go:219
what should i do，thank you very much！

**Comment by GilbertPan97** [comment]
> @GilbertPan97 Perhaps you can try using pip's mirror source. This is usually caused by pip dependency package download failure. just like: pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

I've tried this but it doesn't seem to work, due to missing other dependencies in Tsinghua source

**Comment by GilbertPan97** [comment]
> Error - Function cannot be updated when existing function is being provisioned
> /nuclio/pkg/platform/local/platform.go:219
> what should i do，thank you very much！

I previously opened another [question page](https://github.com/nuclio/nuclio/issues/3013) on nuclio's github issue, where there are more details about your question.

**Comment by Kk875** [comment]
> > @GilbertPan97 Perhaps you can try using pip's mirror source. This is usually caused by pip dependency package download failure. just like: pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
> 
> I've tried this but it doesn't seem to work, due to missing other dependencies in Tsinghua source
hello! what should i do if i meet the error like you:Error - Function cannot be updated when existing function is being provisioned
    /nuclio/pkg/platform/local/platform.go:219   thanks!

**Comment by MirPing** [comment]
> > Error - Function cannot be updated when existing function is being provisioned
> > /nuclio/pkg/platform/local/platform.go:219
> > what should i do，thank you very much！
> 
> I previously opened another [question page](https://github.com/nuclio/nuclio/issues/3013) on nuclio's github issue, where there are more details about your question.

@GilbertPan97 hello guys, Is there any solutions?

**Comment by bsekachev** [comment]
@MirPing Open nuclio dashboard (http://localhost:8070 by default) and there you can remove the function

**Comment by MirPing** [comment]
> > ```
> >  Error response from daemon: Get \"https://gcr.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Docker engine could not achieve gcr.io domain. It may be a temporary problem and later deploy will be successful. If the problem persists, try to sort out if you can reach the domain from host machine / from inside the docker container. Try to look at other existing issues regarding the problem, like this one #5012
> 
> First of all, thank you for your prompt response. I followed this issue #5012 to manually pull the 'alpine:3.17' image using the provided command, and it indeed worked successfully on my computer. However, when I attempted to redeploy using './serverless/deploy_cpu.sh serverless/pytorch/facebookresearch/sam/nuclio/', I encountered the following error:
> 
> ```
>  > [ 4/13] RUN pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx:
> 665.5     for chunk in response.raw.stream(
> 665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 576, in stream
> 665.5     data = self.read(amt=amt, decode_content=decode_content)
> 665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 512, in read
> 665.5     with self._error_catcher():
> 665.5   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
> 665.5     self.gen.throw(typ, value, traceback)
> 665.5   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
> 665.5     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> 665.5 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
> ------
> Dockerfile.processor:24
> --------------------
>   22 |     RUN apt-get update && apt-get -y install curl git python3 python3-pip ffmpeg libsm6 libxext6
>   23 |     
>   24 | >>> RUN pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx
>   25 |     
>   26 |     RUN pip3 install git+https://github.com/facebookresearch/segment-anything.git
> --------------------
> ERROR: failed to solve: process "/bin/sh -c pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx" did not complete successfully: exit code: 2
> 
>     /nuclio/pkg/cmdrunner/shellrunner.go:114
> Failed to build
>     /nuclio/pkg/dockerclient/shell.go:116
> Failed to build docker image
>     .../pkg/containerimagebuilderpusher/docker.go:70
> Failed to build processor image
>     /nuclio/pkg/processor/build/builder.go:264
> Failed to deploy function
>     ...//nuclio/pkg/platform/abstract/platform.go:227
> ```
> 
> It seems like a network timeout issue on my computer. However, even when I tried to run the 'deploy_cpu.sh' script again, it kept giving me the following error:
> 
> ```
> What's Next?
>   View summary of image vulnerabilities and recommendations → docker scout quickview
> 23.09.04 18:20:54.600                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}
> Deploying pytorch/facebookresearch/sam function...
> 
> Error - Function cannot be updated when existing function is being provisioned
>     /nuclio/pkg/platform/local/platform.go:219
> ```
> 
> Does this mean I should manually delete 'platform.go' and then rerun the 'deploy_cpu.sh' script, or is there another solution to this issue?
> 
> Thank you for your assistance,

@GilbertPan97 @bsekachev sorry,I want to ask this question

**Comment by 1jozon** [comment]
解决了吗
