### ISSUE TITLE
Bug: When in Review Mode, Writing and Issue and Auto Save

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#6788]
So I am on a Job, in review mode, Selected an area to write an issue. 

If while I am writing the issue the auto save is activated, it navigates to a random window...

**Comment by bsekachev** [comment]
Cannot reproduce as described, could you please describe in more details and provide some screencasts?

**Comment by bsekachev** [comment]
Probably you mean not window, but frame. 
If pressing d/f/c/v during saving, shortcut is triggered and it navigates to another frame. 
A was not able to reproduce it with navigation to another window

**Comment by DaveBGld** [comment]
@bsekachev Yes, sorry, I meant to say frame...

DBG
