### ISSUE TITLE
dumped coco format is different from standard format

### ISSUE THREAD

**Issue by FLming** [opencv/cvat#679]
Dear authors,
Firstly, thanks for your work.
Why the coco format is not the standard format? 
1. Categories'id is not starting from 1.
2. Annotations'id is not a global growth integer. 
Therefore, when I use cocoapi(getAnnIds and loadAnns), I got the wrong annotations.

**Comment by nmanovic** [comment]
@FLming , let's look at the issue. I believe it is a bug. Do you use UI to dump annotations?

@azhavoro , please take a look. Need to fix it in the release.

**Comment by FLming** [comment]
@nmanovic, yes, I use UI to dump annotations

**Comment by nmanovic** [comment]
@FLming , could you please confirm that the merged fix works for you?
