### ISSUE TITLE
Clickhouse database

### ISSUE THREAD

**Issue by ASAADASKAR** [opencv/cvat#6792]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://opencv.github.io/cvat/docs/administration/advanced/analytics/)

### Description of my problem
 In clickhouse there is a database called cvat and this Database has a table called **events**, this table is connected to Grafana from clickhaouse Data source to show the events and work time and job and task ID etc….

I want to add rows in this table for the **task name** and **project name**, but I don't know where this table is created in CVAT, or how this table takes the values.

I would be very grateful for the help.

### Log from clickhouse continier
`/ # clickhouse-client
ClickHouse client version 22.3.20.29 (official build).
Connecting to localhost:9000 as user user.
Connected to ClickHouse server version 22.3.20 revision 54455.

240dbcaf5625 :) SHOW DATABASES

SHOW DATABASES

Query id: e41e00fd-cdfa-40e6-90e6-a08d9ead494c

┌─name───────────────┐
│ INFORMATION_SCHEMA │
│ cvat               │
│ default            │
│ information_schema │
│ system             │
└────────────────────┘

5 rows in set. Elapsed: 0.001 sec. 

240dbcaf5625 :) SHOW TABLES FROM cvat;

SHOW TABLES FROM cvat

Query id: 2c2790f3-7794-4bc3-9221-5891f53e928c

┌─name───┐
│ events │
│ test   │
└────────┘

2 rows in set. Elapsed: 0.003 sec. 

240dbcaf5625 :) DESCRIBE TABLE cvat.events;

DESCRIBE TABLE cvat.events

Query id: 0a13b5e9-8563-4966-883e-c37a8e9bdb06

┌─name───────┬─type─────────────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ scope      │ String                   │              │                    │         │                  │                │
│ obj_name   │ Nullable(String)         │              │                    │         │                  │                │
│ obj_id     │ Nullable(UInt64)         │              │                    │         │                  │                │
│ obj_val    │ Nullable(String)         │              │                    │         │                  │                │
│ source     │ String                   │              │                    │         │                  │                │
│ timestamp  │ DateTime64(3, 'Etc/UTC') │              │                    │         │                  │                │
│ count      │ Nullable(UInt16)         │              │                    │         │                  │                │
│ duration   │ UInt32                   │ DEFAULT      │ toUInt32(0)        │         │                  │                │
│ project_id │ Nullable(UInt64)         │              │                    │         │                  │                │
│ task_id    │ Nullable(UInt64)         │              │                    │         │                  │                │
│ job_id     │ Nullable(UInt64)         │              │                    │         │                  │                │
│ user_id    │ Nullable(UInt64)         │              │                    │         │                  │                │
│ user_name  │ Nullable(String)         │              │                    │         │                  │                │
│ user_email │ Nullable(String)         │              │                    │         │                  │                │
│ org_id     │ Nullable(UInt64)         │              │                    │         │                  │                │
│ org_slug   │ Nullable(String)         │              │                    │         │                  │                │
│ payload    │ Nullable(String)         │              │                    │         │                  │                │
└────────────┴──────────────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

17 rows in set. Elapsed: 0.002 sec. 

240dbcaf5625 :) `

**Comment by bsekachev** [comment]
Created from this file: **components/analytics/clickhouse/init.sh**

**Comment by PauloFavero** [comment]
Hello,

I have a self-hosted CVAT instance and the company stack holders need to get metrics of given users, tasks and organizations from the Grafana management dashboard.

It's very hard once that we do not have project_name, job_name and, for example, in the Clickhouse DB. I modified the script that creates the Clickhouse events table to include these columns. 

Could someone help me pointing out where in the code should I modify to feed these fields from cvat->vector->clickhouse? I have been looking for but I was unable to find it. 

Any help is appreciated. 

Thanks.

**Comment by ASAADASKAR** [comment]
@PauloFavero 
Hello, 
do you still need help?

**Comment by PauloFavero** [comment]
HI @ASAADASKAR,

Yes, any help would be appreciated. 

For now, I created another data source inside Grafana that connnects to the postgres DB. I will query the organizations, users, projects and tasks in this database. From the results, I will dinammically query the clickhouse db based on the user row selection.

With this approach, I will be able to show to the stockholders meaningful information while getting insights from the clickhouse DB. Do you think this is a good approach? Have you found another solution for this?

**Comment by ASAADASKAR** [comment]
For me, it was important that I can also show names on Grafana with the IDs, as the screenshot shows:

![image](https://github.com/opencv/cvat/assets/96923410/8397e17f-14b4-46fa-bff4-50b22d461764)

I did this from the same data source. 
I only extended events serialisers to send more data like Job_name Task_name to  clickhouse in logs. 
And I made the same extension in vector and clickhouse.
Backend ---> Vector---> Cklickhouse

**Comment by PauloFavero** [comment]
@ASAADASKAR 

This was my first approach. I modified the serializers to send username, projectName and orgName but this only works for events generated in the backend, right? 


The events from the client like, drag,time in task and so would not have these named values. For this to work, it would requiere a lot of changes in the client code making it hard for future updates.
