### ISSUE TITLE
CVAT storage limit

### ISSUE THREAD

**Issue by manojhacklabs** [opencv/cvat#6796]
Under cvat/settings/base.py there are few parameters
1. DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 MB
2. TUS_MAX_FILE_SIZE = 26843545600 # 25gb

Does it mean that we can't upload above 100mb of data?

I have currently uploaded around 20gb of data and I am not able to upload any more tasks, is there a way to resolve it?
Also the disk utilization was around 71%.

**Comment by bsekachev** [comment]
Does it mean that we can't upload above 100mb of data?

> No, it does not. 

I have currently uploaded around 20gb of data and I am not able to upload any more tasks, is there a way to resolve it?

> Please, fill the issue template.

**Comment by azhavoro** [comment]
closing due to no response
