### ISSUE TITLE
Add identifier to each element annotated

### ISSUE THREAD

**Issue by SDMMG** [opencv/cvat#6810]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I am trying to get some quality metrics of my projects, like IoU. I saw that in the formats in which I downloaded the projects, the polygons, bboxes, tags, etc., did not have a unique identifier, and I need this field to compare each element of the annotation with the  corresponding one in the revision. Is this something planned to add in future versions? Where can I add this feature in the code?

Thanks in advance.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):  23.0.1
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Linux

**Comment by bsekachev** [comment]
Dublicate, please look at following threads

#4625
#3934
