### ISSUE TITLE
Two versions of annotations within task?

### ISSUE THREAD

**Issue by chekhovana** [opencv/cvat#6816]
I plan to organize my data annotation pipeline in the following way:

- use model predictions to pre-annotate my data
- manually correct these annotations

Is there a way to keep 2 versions of annotations within single task? By comparing model predictions and manually corrected annotations it would be possible to:
- validate model accuracy
- calculate the price of annotator work

I tried to adapt Honeypot feature, but it doesn't suit this usecase, as it's impossible to create second job with 100% images.

**Comment by bsekachev** [comment]
> Is there a way to keep 2 versions of annotations within single task?

No, there is not. 

@zhiltsov-max 

Do we have any reason to keep number of frames in GT job strictly less than in the main one? 
I can't create GT job with 100% frames, but I can with 100% - 1 frame.

**Comment by zhiltsov-max** [comment]
@bsekachev,

> Do we have any reason to keep number of frames in GT job strictly less than in the main one?
> I can't create GT job with 100% frames, but I can with 100% - 1 frame.

This problem is fixed in the PR #6367 (which we still need to merge).

**Comment by bsekachev** [comment]
Was resolved in #7126
