### ISSUE TITLE
cvat memory usage too high

### ISSUE THREAD

**Issue by Votess4All** [opencv/cvat#6826]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. update cvat from v2.4.5 to v2.6.0
2. just start the container by `docker compose -f docker-compose.yml -f docker-compose.override.yml up -d`

### Expected Behaviour

not occupying too much memory, according to my colleague the previous 2.4.5 version only consumes around 2G, however current service round 6G above.

### Current Behaviour

current service occupys around 6G above.

### Possible Solution

I think may restart service can solve the problem, however it doesn't change too much.

### Context

Cause we're using cvat in our company, and when mem is above certain threshold, it continue throws warning, which is very annoying, and we can't close it.

### Your Environment

- Git hash commit (`git log -1`): zip version of release 2.6.0
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.2
- Are you using Docker Swarm or Kubernetes? maybe the first one
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:  referring to https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/#how-to-upgrade-cvat-from-v220-to-v230
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

[cvat_server.log](https://github.com/opencv/cvat/files/12543812/cvat_server.log)

**Comment by azhavoro** [comment]
It would be nice if you could add some details about the problem (which container is consuming more memory than you expect, screenshots, etc) and help to investigate this issue, especially you have full access to the machine that cvat is running on.

**Comment by azhavoro** [comment]
From your screen, it looks like the clickhouse-serv process is only consuming ~206MB RAM... You're talking about 4GB in your first post. Have I missing something?
Please provide as much information as possible, without this it is impossible to guess which CVAT component is consuming RAM in your case.

**Comment by Votess4All** [comment]
sorry to miss the total mem occupied by the whole cvat project, can you help me figure out the cpu usage, I only have two core for the machine, however the clickhouse-server cosumes about 400% of it, and it often throws out the error that "load5 per core", which meas the cpu load is very high.

**Comment by azhavoro** [comment]
You can set cpu limits for clickhouse https://docs.docker.com/compose/compose-file/deploy/#resources
or disable analytics if you don't need them https://github.com/opencv/cvat/issues/6863
or consider using a machine with a larger cpus

**Comment by mmoollllee** [comment]
Same for me :( Running on 2 cpus and 8GB memory the instance dies with:
```
Mar 07 13:22:43 cvat systemd[1]: docker-cc7f54d21eebd5e6a4e8fd5304a20eb48578a60e9b3cdf277cad1c8491ba6d80.scope: A process of this unit has been killed by the OOM killer.
```

Watching `top` command cvat_clickhouse consumes a lot...

trying to set limits on cvat_clickhouse fails with this error:

`validating /root/cvat/docker-compose.override.yml: services.cvat_clickhouse Additional property limits is not allowed`
