### ISSUE TITLE
Exporting Progress bar.

### ISSUE THREAD

**Issue by rpl-alan-shangguan** [opencv/cvat#6827]
I have labelled many images in a segmentation project. Whenever I try to export them to cityscape format, It takes more than an hour. Is there any way to speed up this, or is there any chance to have a progress bar for the exporting?

**Comment by bsekachev** [comment]
Hi @rpl-alan-shangguan,

I believe exporting brogress bar would be a good feature.

**Comment by rpl-alan-shangguan** [comment]
That would be very good to have it.
