### ISSUE TITLE
Interpretation script for Yolo's region based output

### ISSUE THREAD

**Issue by alontrais** [opencv/cvat#683]
Hello I am new to CVAT, I use openvino to run auto annotation, I want to use YoloV3 for this mission in CVAT. I converted Yolo model to OpenVINO format and created xml and bin files.
Now I need to write interpretation python script for Yolo's region based output. How can I do that?
Is there an interrupt file from tensorflow models to openvino?

**Comment by gwestner94** [comment]
I have the same issue, are there any existing approaches/ scripts for using yolov3 models?

**Comment by azhavoro** [comment]
@gwestner94 Hi, example how to use OpenVINO output from Yolov3 you can find here https://github.com/opencv/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py

**Comment by jimwormold** [comment]
> @gwestner94 Hi, example how to use OpenVINO output from Yolov3 you can find here https://github.com/opencv/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py

Thanks for this response, but it is really not quite as simple as that as no imports are available as I understand it within CVAT. If I compare the example interpreter for the SSD (in https://github.com/opencv/cvat/blob/develop/cvat/apps/auto_annotation/README.md) and the equivalent ssd_async demo (https://github.com/opencv/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.py), again, this is not entirely straightforward and YOLO looks considerably more effort.

I appreciate I may be able to use the debugger in https://github.com/opencv/cvat/tree/develop/utils/auto_annotation, but I am currently running in a docker container and this again is not entirely obvious how to achieve.

If you could post an interp.py for yolov3 that would be very helpful!

**Comment by benhoff** [comment]
https://github.com/opencv/cvat/pull/794

**Comment by benhoff** [comment]
> Thanks for this response, but it is really not quite as simple as that as no imports are available as I understand it within CVAT. If I compare the example interpreter for the SSD (in https://github.com/opencv/cvat/blob/develop/cvat/apps/auto_annotation/README.md) and the equivalent ssd_async demo (https://github.com/opencv/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.py), again, this is not entirely straightforward and YOLO looks considerably more effort.

It was considerably more effort :)
Let me know if you run into any issues.

**Comment by benhoff** [comment]
I'd recommend closing this now

**Comment by nmanovic** [comment]
https://github.com/opencv/cvat/tree/develop/utils/open_model_zoo/yolov3
