### ISSUE TITLE
Huge Backup import "Work-horse was terminated unexpectedly (waitpid returned 9)".

### ISSUE THREAD

**Issue by mmoollllee** [opencv/cvat#6831]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. imported Visdrone2019-det-train dataset with ~6.500 frames and +300.000 objects in YOLO 1.1 format
1. did a backup via CVAT UI of the Visdrone2019-det-train task
1. Searched & Replaced `annotations.json` with vim to merge classes (e.g. `people` & `pedestrian` => `person`)
1. Tryed to import the modified backup ([Download](https://fromsmash.com/WoxsqwE.KU-dt))
1. `Error: Request failed with status code 500. "Work-horse was terminated unexpectedly (waitpid returned 9)".` after long waiting time.
1. importing the original backup ends with the same error.

I guess the ammount of annotations is just too huge! What can I do? Extend some timeout?

### Your Environment
- Git hash commit (`git log -1`): a8e921bdd7d008f6b7a9a07430956a5fba6385f5
- Docker version `docker version` (e.g. Docker 17.0.05): Docker Engine 24.0.2
- Are you using Docker Swarm or Kubernetes? ❌ 
- Operating System and version (e.g. Linux, Windows, MacOS): macOS

**Comment by mmoollllee** [comment]
Importing in YOLO 1.1 works. Had to split in 3 parts with ~2.500 frames each to make reimport work. Stil I'm wondering if there is some option to make it work anyway? Increase Docker's memory & CPU? Is there something else that might help?

**Comment by azhavoro** [comment]
Most likely the process was killed due to OOM, try increasing the memory limit for the cvat_worker_export container or RAM on the host if the limits are not set

**Comment by skoroneos** [comment]
Greetings.
I would like to reopen this issue
I have tried to export a project with about 80K objects/100k images to yolo v.1 and it fails with 
"Work-horse terminated unexpectedly; waitpid returned None;"

System has 64GB of ram 32GB of cache and does not run out of memory as i was monitoring RAM/Buffer/Swap usage.
There are no limits set (as far as i know), but if someone could point a way to double check that is more than welcome.
In general there seems to be varius issues when handling large/very large projects import/export wize.
