### ISSUE TITLE
How to change the default storage path of CVAT from docker compose?

### ISSUE THREAD

**Issue by b-niu** [opencv/cvat#6832]
### Question

I have known that, if I build a CVAT environment and run it, all the image data uploaded will be stored in the default docker volumes,
which is located in the `/var/lib/docker/volumes/` of the host server.

I tried to write a `compose.yml` to change the path of docker volumes of CVAT, but it took no effect.

Can you tell me the best practice of changing docker volumes' path of CVAT?

My server has a small `/` partition, and it is not easy to increase it.

Thank you very much.

### Your Environment

- Ubuntu 22.04 LTS
- docker 24.0.1
- CVAT 2.5.2

**Comment by bsekachev** [comment]
Hi @b-niu 

> Can you tell me the best practice of changing docker volumes' path of CVAT?

This is not about CVAT, this is about how docker works.
I do not think docker-compose is able to configure this. Try to address the question to Docker community.

**Comment by bsekachev** [comment]
https://tienbm90.medium.com/how-to-change-docker-root-data-directory-89a39be1a70b

**Comment by b-niu** [comment]
Thank you @bsekachev , I will check it.
