### ISSUE TITLE
PREDEFINED sorting method is not working when task is created from Cloud Storage

### ISSUE THREAD

**Issue by bedilbek** [opencv/cvat#6836]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Create task from cloud storage with `manifest.jsonl` with custom order and `predefined` sorting method, however after task is created, the order is not the same as in `manifest.jsonl`.

### Steps to Reproduce (for bugs)
1. Upload a `manifest.jsonl` to Google Cloud Storage Bucket
`manifest.jsonl`
```json
{"version": "1.1"}
{"type": "images"}
{"name": "timestamps-0-49/0-0", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "03afa507f4042a78ad08de9ad06221a9"}
{"name": "timestamps-0-49/1-0", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "52c01b8c0730ae257843b625ca912ee4"}
{"name": "timestamps-0-49/0-1", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "0ff50e3ce774a2cc02123d9a36dfb020"}
{"name": "timestamps-0-49/1-1", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "10d386a0c23a75d0bb549efae5494b9b"}
{"name": "timestamps-0-49/0-2", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "7bba2850b0cb946d1c90bda84645dd30"}
{"name": "timestamps-0-49/1-2", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "227d492b41c80a7a87a62656cf07cba1"}
```
2. Upload images to bucket folder `timestamps-0-49`
3. Create task with the following configuration:
![image_2023-09-08_16-32-47](https://github.com/opencv/cvat/assets/23011104/9e8a9230-d6c5-4734-a1b5-310da3547f6a)
![image](https://github.com/opencv/cvat/assets/23011104/161c710a-f6ff-40d1-84f8-b769cb7cabf2)

### Expected Behaviour
For example inside the first job, the order of the images should be:
```
0-0.png
1-0.png
```

### Current Behaviour
```
0-0.png
0-1.png
```

![image](https://github.com/opencv/cvat/assets/23011104/5e609ee5-6fc8-4d97-9d5d-1d68d9caf546)
![image](https://github.com/opencv/cvat/assets/23011104/26cf55b8-9acc-4d07-9519-76dd86a44f1c)

### Possible Solution
![image_2023-09-08_17-11-21](https://github.com/opencv/cvat/assets/23011104/b3aaaaa0-d7d3-42ed-9f41-3c9e9b9aae4d)
It is written inside the [docs](https://opencv.github.io/cvat/docs/manual/advanced/dataset_manifest/#the-predefined-sorting-method)

### Your Environment
- v2.6.2
- Docker version 24.0.5, build ced0996
- Docker Compose
- Linux: Ubuntu 22.04.2 LTS

**Comment by bsekachev** [comment]
@bedilbek 

I suppose manifest file should be on the cloud storage and when creating a task you need to select it together with ``timestamps-0-49``. @Marishka17 I am correct?

**Comment by bedilbek** [comment]
@bsekachev Yes, I have uploaded manifest file and also selected this `manifest.jsonl` when creating task as you can see in the screenshot above

**Comment by bsekachev** [comment]
@bedilbek 

Not exactly.

On the screenshot above you selected manifest.jsonl as the source for cloud storage browser. Browser uses it to get list of files, to avoid extra request and make user free of extra payments for these requests. Additionally you need to have one more manifest.jsonl file on cloud storage itself, laying together with the timestamps folder.

The core thing to understand here is that manifest.jsonl you specified during cloud storage creation and manifest file required to create task with predefined method of sorting, in general, are different manifest files. 

But I believe we may use cloud storage manifest as a source for predefined sorting, it would be a good feature.

**Comment by bedilbek** [comment]
> @bedilbek
> 
> Not exactly.
> 
> On the screenshot above you selected manifest.jsonl as the source for cloud storage browser. Browser uses it to get list of files, to avoid extra request and make user free of extra payments for these requests. Additionally you need to have one more manifest.jsonl file on cloud storage itself, laying together with the timestamps folder.
> 
> The core thing to understand here is that manifest.jsonl you specified during cloud storage creation and manifest file required to create task with predefined method of sorting, in general, are different manifest files.
> 
> But I believe we may use cloud storage manifest as a source for predefined sorting, it would be a good feature.

If I understand you correctly I need to have 2 kinds of manifest files, one for Cloud Storage Browser, the other one located inside the input files folder for sorting method. But I believe it creates confusion for the first time users and I guess it should be defined very clearly in the documentation. 

Also another confusion I am having right now after your explanation, the format of the image name is going to be different in both those manifest files, right?

Manifest file for Cloud Storage Browsing:
```json
{"version": "1.1"}
{"type": "images"}
{"name": "timestamps-0-49/0-0", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "03afa507f4042a78ad08de9ad06221a9"}
{"name": "timestamps-0-49/1-0", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "52c01b8c0730ae257843b625ca912ee4"}
{"name": "timestamps-0-49/0-1", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "0ff50e3ce774a2cc02123d9a36dfb020"}
{"name": "timestamps-0-49/1-1", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "10d386a0c23a75d0bb549efae5494b9b"}
{"name": "timestamps-0-49/0-2", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "7bba2850b0cb946d1c90bda84645dd30"}
{"name": "timestamps-0-49/1-2", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "227d492b41c80a7a87a62656cf07cba1"}
```

Manifest file inside Input files directory for sorting method:
 ```json
{"version": "1.1"}
{"type": "images"}
{"name": "0-0", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "03afa507f4042a78ad08de9ad06221a9"}
{"name": "1-0", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "52c01b8c0730ae257843b625ca912ee4"}
{"name": "0-1", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "0ff50e3ce774a2cc02123d9a36dfb020"}
{"name": "1-1", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "10d386a0c23a75d0bb549efae5494b9b"}
{"name": "0-2", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "7bba2850b0cb946d1c90bda84645dd30"}
{"name": "1-2", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "227d492b41c80a7a87a62656cf07cba1"}
```

**Comment by bedilbek** [comment]
@bsekachev I checked both types of manifest configurations inside the input files directory: first configuration, for each image name inside the manifest I leave the name as it is without adding any prefix (folder name), second configuration, for each image I add the prefix `timestamps-0-49` folder to the image name. In both configurations sorting did not work. So it means your method of 2 different manifest files is also not working, I guess you can label it as a bug now
