### ISSUE TITLE
Images not listed inside the manifest are being added to the job when task is created from Cloud Storage

### ISSUE THREAD

**Issue by bedilbek** [opencv/cvat#6837]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have 3500 images on the cloud storage. However I created `manifest.jsonl` for only 6 random images out of that 3500 images. I set the `segment_size` to 2. Then I created task and I see 1750 jobs, however I only wanted to create 3 jobs for 6 images.

### Steps to Reproduce (for bugs)
1. Upload a `manifest.jsonl` to Google Cloud Storage Bucket
`manifest.jsonl`
```json
{"version": "1.1"}
{"type": "images"}
{"name": "timestamps-0-49/0-0", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "03afa507f4042a78ad08de9ad06221a9"}
{"name": "timestamps-0-49/1-0", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "52c01b8c0730ae257843b625ca912ee4"}
{"name": "timestamps-0-49/0-1", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "0ff50e3ce774a2cc02123d9a36dfb020"}
{"name": "timestamps-0-49/1-1", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "10d386a0c23a75d0bb549efae5494b9b"}
{"name": "timestamps-0-49/0-2", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "7bba2850b0cb946d1c90bda84645dd30"}
{"name": "timestamps-0-49/1-2", "extension": ".png", "width": 1920, "height": 1080, "meta": {"related_images": []}, "checksum": "227d492b41c80a7a87a62656cf07cba1"}
```
2. Upload 3500 images to bucket folder `timestamps-0-49`
3. Create task with the following configuration:
![image](https://user-images.githubusercontent.com/23011104/266626230-9e8a9230-d6c5-4734-a1b5-310da3547f6a.png)
![image](https://user-images.githubusercontent.com/23011104/266624051-161c710a-f6ff-40d1-84f8-b769cb7cabf2.png)

### Expected Behaviour
3 jobs should be created each containing 2 images

### Current Behaviour
1750 jobs are created each containing 2 images

![image](https://github.com/opencv/cvat/assets/23011104/11bce569-2aa7-4d0a-af5f-8495778d1fa2)

### Possible Solution
 Images listed inside the manifest should be respected and only those images should be added to the task

### Your Environment
- v2.6.2
- Docker version 24.0.5, build ced0996
- Docker Compose
- Linux: Ubuntu 22.04.2 LTS

**Comment by Marishka17** [comment]
@bedilbek, Hello, thanks for reporting the issue. I've prepared the [PR](https://github.com/opencv/cvat/pull/6850) to fix that but as a workaround, you can create a task with our REST API/SDK specified `["timestamps-0-49/", "manifest.jsonl"]` in  `server_files` and the task will be created only with files from the manifest.

**Comment by bedilbek** [comment]
Thank you for your PR, but my main issue was related to #6836, so I will wait until it is merged
