### ISSUE TITLE
ImportError in django test (auto annotation)

### ISSUE THREAD

**Issue by KiteYeh** [opencv/cvat#684]
When i enable openvino (OPENVINO_TOOLKIT: "yes") for auto annotation and run **manage.py test** in cvat docker shell

fails with error below: 
```
 File "/home/django/cvat/apps/reid/urls.py", line 6, in <module>
    from . import views
  File "/home/django/cvat/apps/reid/views.py", line 10, in <module>
    from cvat.apps.reid.reid import ReID
  File "/home/django/cvat/apps/reid/reid.py", line 7, in <module>
    import cv2
ImportError: No module named 'cv2'
```
I disable openvino (OPENVINO_TOOLKIT: "no") and It work well.

Thanks in advance

**Comment by bsekachev** [comment]
@KiteYeh 
Have you installed OpenVINO with OpenCV?

**Comment by KiteYeh** [comment]
> @KiteYeh
> Have you installed OpenVINO with OpenCV?
hi bsekachev,
I referenced document to enable openVINO:
[](https://github.com/opencv/cvat/tree/develop/components/openvino)

Build docker image
```
# From project root directory
docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build
```
Run docker container
```
# From project root directory
docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml up -d
```
I couldn't sure if openVINO and openCV are installed or not after build openVINO image, Did I missed any step for enabling auto annotation?

Thanks in advance

**Comment by bsekachev** [comment]
@KiteYeh 
Could you please send us the whole sequence of steps you do to reproduce the issue?

**Comment by bsekachev** [comment]
@KiteYeh 
I built container with OpenVINO support.
Went to its bash, install all dependencies ```pip3 install -r cvat/requirements/testing.py```
And finally I was be able to run testing: ```python3 manage.py test cvat/apps/engine/ --settings=cvat.settings.testing```
Everything is alright.

**Comment by KiteYeh** [comment]
@bsekachev 
thanks for your reply, 

The cvat codebase pull from master branch not developer,
It set `DJANGO_CONFIGURATION: "production"` in docker-compose yml file so that docker only installed production requirement.

the sequence of steps:

1. enable openVINO and run the docker container: [](https://github.com/opencv/cvat/tree/develop/components/openvino)
2. Went to its bash
3. run django test:` python3 manage.py test`

fails with error below:
```
 File "/home/django/cvat/apps/reid/urls.py", line 6, in <module>
    from . import views
  File "/home/django/cvat/apps/reid/views.py", line 10, in <module>
    from cvat.apps.reid.reid import ReID
  File "/home/django/cvat/apps/reid/reid.py", line 7, in <module>
    import cv2
ImportError: No module named 'cv2'
```
is there any mistake in test steps?

**Comment by bsekachev** [comment]
@KiteYeh 
Master branch has been updated a long time ago. 
So, first of all I would recommend you to use newer version of CVAT. 
In the middle of September we are going to make a release if you don't want to use code from develop branch. 

Also short question. When you go to container's bash, do you get a message "[setupvars.sh] OpenVINO environment initialized"?
And another short question. What OpenVINO version do you use?

**Comment by KiteYeh** [comment]
@bsekachev
Yes, I got a message "[setupvars.sh] OpenVINO environment initialized"
and I use OpenVINO 2019R2.
the auto annotation work well, but `python3 manage.py test` has failed. 

If no any suggestion, I will upgrade too after you release the new version and test again.
Thanks for your reply.

**Comment by bsekachev** [comment]
@KiteYeh 
I use OpenVINO 2019R1, maybe it's a reason. But I am not sure. Will check it later.

**Comment by KiteYeh** [comment]
> @KiteYeh
> I use OpenVINO 2019R1, maybe it's a reason. But I am not sure. Will check it later.

@bsekachev 
Has the new version of master branch been released?
Do you try the OpenVINO 2019R1 and is there any feedback on the test result?

thanks for your reply

**Comment by KiteYeh** [comment]
> @KiteYeh
> I use OpenVINO 2019R1, maybe it's a reason. But I am not sure. Will check it later.

@bsekachev 
It work well on master branch with released 0.5.0 version.
Thanks for your reply

**Comment by bsekachev** [comment]
@KiteYeh 
Great news.
So, has the issue been resolved?

**Comment by KiteYeh** [comment]
> @KiteYeh
> Great news.
> So, has the issue been resolved?

Thanks for your reply,
the sequence of steps:

1. Went to docker bash
2. run django test: python3 manage.py test

Another fail with error below

```
===============================================================
ERROR: utils.voc.tests.test_process_cvat_xml (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: utils.voc.tests.test_process_cvat_xml
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/django/utils/voc/tests/test_process_cvat_xml.py", line 5, in <module>
    from utils.voc.converter import process_cvat_xml
  File "/home/django/utils/voc/converter.py", line 16, in <module>
    import glog as log
ImportError: No module named 'glog'
----------------------------------------------------------------------
```

could you help to check this issue?
Thanks in advance

**Comment by KiteYeh** [comment]
@bsekachev 
Thanks for your reply, the issue could be closed.
