### ISSUE TITLE
GIT Dataset Repo in Azure Devops 

### ISSUE THREAD

**Issue by alziegel** [opencv/cvat#6845]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. create a new task
2. try to set the repositories https link as dataset repository URL (format: https://user:password@dev.azure.com/company/project/repo)

(alternatively also tried the same with ssh and different ways writing it)
In comparison via cli its possible to deploy it directly, similar to [this](https://github.com/opencv/cvat/issues/2737#issuecomment-769099900)

### Expected Behaviour
Task can be created and repo added as target for labeling

### Current Behaviour
Error: 
`Error: Repository status check failed. Traceback (most recent call last):`
`File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 220, in init_repos`
`   self._rep = git.Repo(self._cwd)`
`File "/opt/venv/lib/python3.10/site-packages/git/repo/base.py", line 210, in __init__`
`  raise NoSuchPathError(epath)`
`git.exc.NoSuchPathError: /home/django/data/tasks/149/artifacts/repos`
`...`
`raise Exception("Git repository URL does not satisfy pattern")`
`Exception: Git repository URL does not satisfy pattern`

### Your Environment
- CVAT-Version: `2.6`
- Docker version `Docker 24.0.5`
- Operating System: `Linux`

**Comment by bsekachev** [comment]
This feature was removed in #6904 as outdated.
Please, consider using cloud storages instead.
