### ISSUE TITLE
SAM backend multi mask is true or false??

### ISSUE THREAD

**Issue by vijayreddysamula** [opencv/cvat#6846]
Hello CVAT community,
                                     I have tried using CVAT with SAM, I encountered some problems there.
1)  I am labeling agriculture data with **crops and weeds**. Problem is when i use **SAM** to label. it is labeling soil too sometimes. I have tried my SAM standalone with the same data, but i didn't encounter that issue when i switched to **multi-mask=false**. Can you let me know how to change that in CVAT?
2) Is there any way to undo with SAM ?

**Comment by bsekachev** [comment]
Hi @vijayreddysamula 

As far as I remember, onnx decoder was prepared with ``--return-single-mask`` argument.

**Comment by bsekachev** [comment]
You can cancel any drawn point by clicking it again.

**Comment by vijayreddysamula** [comment]
Hi bsekachev, 
    Thanks for the reply. But SAM in serverless is implemented through pytorch not via onnx. If possible can you share where is the exact location?

**Comment by bsekachev** [comment]
@vijayreddysamula 

It is only encoder working serverless on pytorch. Decoder is running in the browser as onnx network. 
``multimask_output`` is decoder argument.

**Comment by bsekachev** [comment]
Decoder can be found here: https://github.com/opencv/cvat/tree/develop/cvat-ui/plugins/sam/assets
Code running decoder is here: https://github.com/opencv/cvat/blob/develop/cvat-ui/plugins/sam/src/ts/index.tsx 

But --return-single-mask is onnx compilation argument, it is not available in runtime for onnx. Please, refer to SAM repository for details.

**Comment by vijayreddysamula** [comment]
@bsekachev 

Thank you for the information.
