### ISSUE TITLE
Import dataset as a project (with annotation), and split it into segmented tasks

### ISSUE THREAD

**Issue by GeorgePPP** [opencv/cvat#6849]
I am wondering if there's a way to import semi-annotated images (with YOLO format) as project, and then segment it into tasks? I can only do this for unannotated images from a task to jobs

**Comment by zhiltsov-max** [comment]
Hi! You can import annotated dataset as one or several tasks using the Import Dataset button in the project actions. Tasks will be created automatically from each subset found in the dataset (e.g. train, test, etc.). Note, however, that there will be no option to split images between tasks manually. If you want to control this, you will need to create some tasks manually and upload annotations after this.
![image](https://github.com/opencv/cvat/assets/13832349/eae9c238-0bf4-43fd-b0c5-2be2f80bd864)

**Comment by GeorgePPP** [comment]
> Hi! You can import annotated dataset as one or several tasks using the Import Dataset button in the project actions. Tasks will be created automatically from each subset found in the dataset (e.g. train, test, etc.). Note, however, that there will be no option to split images between tasks manually. If you want to control this, you will need to create some tasks manually and upload annotations after this. ![image](https://user-images.githubusercontent.com/13832349/267893029-f02ba40f-d808-4f8d-b5f7-eb82c8199656.png)

Thanks for the information! However I was wondering to update annotated dataset and split them to different jobs, looks like it's not the way to go.
