### ISSUE TITLE
[Question] Need guidance through the code to add unique ID

### ISSUE THREAD

**Issue by SDMMG** [opencv/cvat#6853]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

First of all, I strongly apologize for opening the issue again, but I read this issues https://github.com/opencv/cvat/issues/4625 and https://github.com/opencv/cvat/issues/3934 and I still have a question. I cannot identify where I should modify the code to add automatically to each polygon (or element) annotated a unique identifier as an attribute, so I would like to ask if I could get some guidance on this.

Thank you and sorry for any inconvinience.

**Comment by bsekachev** [comment]
Probably, first of all you want to add unique id (automatic uuid?) in Annotation model in django database: cvat/apps/engine/models.py::class Annotation

Then you need to modify UI (cvat-core, cvat-ui modules) if you want to see it there, and add this field as an attribute to export/import formats (somewhere in cvat/apps/dataset_manager/bindings.py and probably in other places). You can see to ``rotation`` or ``group`` attributes, to see how they dumped in different formats. It is enough complex patch, there is not a single place in the code you need to modify, there are a lot of them.
