### ISSUE TITLE
Polylines duplications after uploading manually created annotations

### ISSUE THREAD

**Issue by mehanat** [opencv/cvat#6854]
Task link: https://app.cvat.ai/tasks/296356/jobs/306603

Steps to reproduce:
1. Created new task
2. Uploaded annotation with CVAT 1.1 format. The annotations xml file was created manually using the Python script

Expectations:
1. Annotations were uploaded correctly
2. An opportunity to add new elements to the annotations on the CVAT platform

Real result:
1. Annotations were uploaded correctly
BUT
2. When I added a polyline to the first image in the task, this polyline was duplicated for all subsequent images (see creenshots)

Here I added new polyline to the image
![2023-09-12_19-15-13](https://github.com/opencv/cvat/assets/17254183/fb1e43ca-6509-40a8-a3bc-5cddff86bfb3)

And I see it on the next image
![2023-09-12_19-14-00](https://github.com/opencv/cvat/assets/17254183/ad990688-e61c-4976-a267-61a43eaf969f)

**Comment by bsekachev** [comment]
@mehanat 

> When I added a polyline to the first image in the task, this polyline was duplicated for all subsequent images (see creenshots)

You created polyline with "Track" track. This button is dedicated for video or image sequences to create the same object on range of frames. 
You should create polylines with "Shape" button.
