### ISSUE TITLE
Unable to add S3-Compatible cloud storage on CVAT web app

### ISSUE THREAD

**Issue by sidharthrajaram** [opencv/cvat#6856]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. On app.cvat.ai, click on Cloud Storages tab in menu bar
2. Try adding a S3-compatible cloud storage (i.e. MinIO)
3. After providing correct endpoint URL, key pair, bucket name, etc, I get a Status 400 error: `"Could not create the cloud storage. Error: Request failed with status code 400. resource: The resource <bucket-name> not found. It may have been deleted."`

### Expected Behaviour
Cloud storage should have been added.

### Current Behaviour
Getting Status 400 error popups. My S3-Compatible cloud storage is not added.

### Your Environment
I'm using the CVAT web app directly on app.cvat.ai.

**Comment by zhiltsov-max** [comment]
Hi! Probably, we need more details to help. I successfully use MinIO in my local deployment, and we use it in our tests. Just need to make sure the storage host is reachable from the CVAT server. The online platform should not be different in this regard.

**Comment by sidharthrajaram** [comment]
Update: the storage host was not actually reachable from the CVAT server. Thanks!

**Comment by vudq** [comment]
> Update: the storage host was not actually reachable from the CVAT server. Thanks!

Changed in docker-compose.yml

SMOKESCREEN_OPTS: ${SMOKESCREEN_OPTS:--allow-address=192.168.11.164}

https://github.com/cvat-ai/cvat/issues/8207#issuecomment-2247243019
