### ISSUE TITLE
CVAT error when using SAM for some images

### ISSUE THREAD

**Issue by jcorrochanoj** [opencv/cvat#6861]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. Setup CVAT with serverless functions
2. Enable SAM model

### Current Behaviour
Using SAM on some images, the interface indicates that it is waiting for SAM processing but immediately gives an error:

"Interaction error occurred. Request failed with status 400. 400 Client Error: Bad request for URL: HTTP://host.docker.internal:32768"
![image](https://github.com/opencv/cvat/assets/23344850/38875b36-071c-4187-a847-e62581faa57c)

Logs in the SAM container: 
![image](https://github.com/opencv/cvat/assets/23344850/6ffaeb44-92cf-4c53-a246-c6c0ae9250d2)

This only happens with some images and I can intuit that it is due to the size of these images. What can I do to be able to work with SAM and these images?
This is happening with images between 40 and 50 MB in size, but not with smaller images.

### Your Environment
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.25
- Are you using Docker Swarm or Kubernetes? --> Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Amazon Linux
- CVAT v2.7.0

**Comment by bsekachev** [comment]
HI @jcorrochanoj 

You can configure body size in corresponding nuclio config:
https://github.com/opencv/cvat/blob/develop/serverless/pytorch/facebookresearch/sam/nuclio/function.yaml (default value for body size is 32 Mb)

But I believe error message should be improved.

**Comment by jcorrochanoj** [comment]
Modifying the maxRequestBodySize works with my images. Thank you very much for the solution!
