### ISSUE TITLE
How to disable analytics

### ISSUE THREAD

**Issue by tadejsv** [opencv/cvat#6863]
Is there any way to disable analytics?

I have set `CVAT_ANALYTICS: 0`, but I still am seeing logs of errors from failed connections to `vector` (I have commented out this service in my docker compose file). I would like to run CVAT without analytics features, as I don't need them.

Also, does CVAT analytics (things using vector and clickhouse) encompass only things that you can explore in grafana - or does it also include task/project analytics that you can see in CVAT and quality reports?

**Comment by bsekachev** [comment]
@azhavoro 

Do we have such an option?
I can't see vector configuration to be disabled somehow depending on CVAT_ANALYTICS env in base.py.

**Comment by bsekachev** [comment]
@tadejsv 

Probably you need to remove ``DJANGO_LOG_SERVER_HOST`` anywhere from docker compose files.
