### ISSUE TITLE
Serverless anotation return format

### ISSUE THREAD

**Issue by ndhuynh02** [opencv/cvat#6866]
I am trying to add my own DL model into CVAT. However, I am encountering a problem. The return value format of the function `handler` in `main.py` is not clear for each task. I have looked into the example code in the folder `serverless/pytorch` and `serverless/tensorflow` but they do not follow any principle; they are all different from each other. 
Can anybody provide me the document for the reuturn JSON format of every task such as detection, segmentation, etc.
I have tried so many ways but none of them seem to work. I always get this error: `triggersError": "json: unsupported value: encountered a cycle via *http.http"`

**Comment by bsekachev** [comment]
Please, refer to #6332
