### ISSUE TITLE
exported categories different from project categories

### ISSUE THREAD

**Issue by matt-d** [opencv/cvat#6871]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. create a project with 1 category - eg. car
2. add a task with a single image to the project
3. annotate a car in the image
4. export the task (I'm using coco format)
5. confirm the categories in the export annotation json match the project(car)
6. add another category to the project - eg. person
8. export the task again
9. unexpectedly there is only the car in the export task annotation json file.

### Expected Behaviour
When exporting a task in coco format the categories in the annotation json should match those of the project, not just those present in the project when the task was last saved.

### Current Behaviour
When exporting a task in coco format, the categories present in the annotation json are not in line with those in the project.

**Comment by matt-d** [comment]
It seems likely to be a caching issue, however the problem persists even 4+ days after making the change to the project categories.

**Comment by matt-d** [comment]
down and up the containers also doesnt seem to fix the problem.

**Comment by zhiltsov-max** [comment]
Hi, I tried these steps, but could not reproduce the problem. In the exported file I have all the expected categories after the second one is added. Could you please check the name of the downloaded file to be sure? If the archive is cached, it should have the same downloaded file name (the browser will automatically append (1), (2) etc. to save the file). I tested it with the develop branch (commit 06bae53b80026d6f25174b415b097dd1d50c94d7).

**Comment by zhiltsov-max** [comment]
Hi, I was able to reproduce the problem. As a workaround, please update the task somehow before exporting to make sure the export cache is cleaned. For instance, you can re-save the task annotations.

**Comment by matt-d** [comment]
Hi, thanks for the reply - yes this is what we've been doing for some years now as a work around.  The issue is that at this point there are hundreds and hundreds of tasks that would need to be 'edited' and then re-saved.  Is there anything I can do to help track down the cause of the issue?

**Comment by zhiltsov-max** [comment]
> The issue is that at this point there are hundreds and hundreds of tasks that would need to be 'edited' and then re-saved.

If you have lots of tasks in projects, please consider writing a simple script based on the SDK as a temporary workaround.

> Is there anything I can do to help track down the cause of the issue?

Thank you, but the cause is pretty clear - CVAT just doesn't store any information to clear the nested object export cache on label updates in the parent entities. I've discovered the same problem for jobs as well. We'll try to find a solution for this problem.

**Comment by matt-d** [comment]
OK thanks, will do - I was going to ask if just updating a timestamp on the task was enough, but your PR makes that clear.

**Comment by matt-d** [comment]
thanks!
