### ISSUE TITLE
Create pop up containing entire task name when hovering over a task in both project and task list CVAT UI

### ISSUE THREAD

**Issue by RHogan615** [opencv/cvat#6874]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create a long task name (over 75 characters) and notice how it gets cut off in task page view

### Expected Behaviour

If you hover your cursor over task name in the task list or inside project a pop up will appear showing full name of task. If there is a long task name it can be hard to read the tasks quickly

### Current Behaviour

Doesn't show entire character length of task name for particularly long names

### Possible Solution

Create a pop up window when hovering over name, particularly if the name is long. For example, my current tasks names are roughly ~75 characters 

### Context

I typically name my batches the name of the .bag file they originated from and then ending in `batch_x`. sometimes when my log names are long it can be difficult to quickly read the batch number when looking through task list

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by syedbarimanjan** [comment]
I would like to add this tooltip to the task card so that when the name is long then hovering over it will show the name in a tooltip and this tooltip will be by default it will be there even for short named tasks. @bsekachev can I work on it.

**Comment by bsekachev** [comment]
@syedbarimanjan Community contributions are always welcome.
