### ISSUE TITLE
Could not create model. Error 400

### ISSUE THREAD

**Issue by Hagonata** [opencv/cvat#6877]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Add a model
2. Huggingface model url
3. Create and enter Access token
4. *Submit*

### Expected Behaviour
Add the model from HuggingFace
https://huggingface.co/keremberke/yolov8n-pothole-segmentation

### Current Behaviour
![Screenshot from 2023-09-19 15-56-16](https://github.com/opencv/cvat/assets/95108691/f086ffb1-e1c1-4d28-b908-4e4f19de15ed)

### Your Environment

I use it from web. 

Ubuntu 20.04

Server version: 2.7.1

Core version: 11.1.0

Canvas version: 2.17.5

UI version: 1.56.1
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by Petros626** [comment]
How did you install the Semi-Automatic and Automatic Annotation?

**Comment by Hagonata** [comment]
> @Hagonata finally I was able to deploy some specific ones, but not every model. Thanks for generally answering my question.

Sorry, I don't answer your first question clearly. You can install it through this documentation  https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/.
