### ISSUE TITLE
How to annotate a segmented object? 

### ISSUE THREAD

**Issue by FLming** [opencv/cvat#688]
I want to label a segmented object. For example, an occluded rope.
I find coco dataset has flag 'iscrowd' to create RLE format annotation can label the segmented object.
Is cvat can do it?

**Comment by bsekachev** [comment]
@FLming 
I believe the property ["group"](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md#shape-grouping) is what can help you in such a scenario.

**Comment by FLming** [comment]
@bsekachev Thank you, got it.
