### ISSUE TITLE
Need to store additional information with uploaded images

### ISSUE THREAD

**Issue by hetfmt** [opencv/cvat#6885]
Using the Python high-level API, I am able to create a "task" and "upload" images using a modified version of the example given in: https://opencv.github.io/cvat/docs/api_sdk/sdk/highlevel-api/

Along with each image, I need to store additional "meta data" that relates to the origin of the image.

I have been searching the net, and reading the documentation, but I cannot find a "key" that I can use to store this additional information. Is it not possible to add extra information/description to an image?

Thanks.

**Comment by bsekachev** [comment]
Binding 3rdparty metadata to images is not supported.

**Comment by HeffRaleigh** [comment]
@bsekachev I just submitted this as a feature request.  See dev-328.  Thanks!
