### ISSUE TITLE
Git Integration not working for private repositories

### ISSUE THREAD

**Issue by stavyadatta** [opencv/cvat#6886]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Went to create task window, added images, title and labels 

![issue_git_integration_cvat](https://github.com/opencv/cvat/assets/62042596/883836a7-2f15-40ea-87e7-e240d14dad14)

2. However I receive this error message
![issue_git_integration_error_message](https://github.com/opencv/cvat/assets/62042596/6dd3826a-d0b0-46ce-9c3b-a0258233c311)

My repository is private and I have added the ssh keys to my github account. Can anyone  please assist me with this. 

Thank you so much for such a wonderful open source tool!!!

### Context
I am trying to have data annotation version system for my organization using UI of CVAT

### Your Environment

- Git hash commit -  213bcf0b360d0e09fcfee1ff71ccf0d4e7a7b2b0 
- Docker version  24.0.6
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version - Fedora 38

**Comment by stavyadatta** [comment]
Hey Team! Hoping to hear from you soon!

**Comment by alziegel** [comment]
Hi, seems to be similar issue to mine, also tested with ssh-keys too and had the same errors.

**Comment by stavyadatta** [comment]
@bsekachev, can you please assist us in this issue. Thank you!

**Comment by bsekachev** [comment]
This feature was removed in #6904 as outdated.
Please, consider using cloud storages instead.
