### ISSUE TITLE
when I use ModelTask to upload a model, an error happen

### ISSUE THREAD

**Issue by wemamawe** [opencv/cvat#689]
this is the error 

> Checking request has returned the "failed" status. Message: Exception: Model was not properly created/updated. Test failed: 'in <string>' requires string as left operand, not  int

The model is download from[ OpenVinoToolkit](https://github.com/opencv/open_model_zoo/blob/master/intel_models/semantic-segmentation-adas-0001/description/semantic-segmentation-adas-0001.md)
The Interpretation script is like
 `
def clip(value):
  return max(min(1.0, value), 0.0)

for frame_results in detections:
  frame_height = frame_results["frame_height"]
  frame_width = frame_results["frame_width"]
  frame_number = frame_results["frame_id"]

  for i in range(frame_results["detections"].shape[2]):
    confidence = frame_results["detections"][0, 0, i, 2]
    if confidence < 0.5:
      continue

    results.add_box(
      xtl=clip(frame_results["detections"][0, 0, i, 3]) * frame_width,
      ytl=clip(frame_results["detections"][0, 0, i, 4]) * frame_height,
      xbr=clip(frame_results["detections"][0, 0, i, 5]) * frame_width,
      ybr=clip(frame_results["detections"][0, 0, i, 6]) * frame_height,
      label=int(frame_results["detections"][0, 0, i, 1]),
      frame_number=frame_number,
      attributes={
        "confidence": "{:.2f}".format(confidence),
      },
    )
`

**Comment by azhavoro** [comment]
@wemamawe Hi, you tried to use interpretation script for ssd based models, but semantic-segmentation-adas-0001 has completely different output. You need to write a proper interpretation script for this model.

**Comment by wemamawe** [comment]
@azhavoro can you tell me how to write the interpretation script for semantic-segmentation-adas-0001, i can't find the tutorial about how to code interpretation script .

**Comment by azhavoro** [comment]
@wemamawe Please read documentation for auto annotation component https://github.com/opencv/cvat/blob/develop/cvat/apps/auto_annotation/README.md

**Comment by wemamawe** [comment]
yes, i read many times, but it don't very clearly, i can't find enough imformation

**Comment by azhavoro** [comment]
What kind of information do you need?

**Comment by azhavoro** [comment]
According you question about interpretation script: Output of mentioned model is essentially a pixel map. You need to convert it to one of supported shapes (polygon, rectangle, polyline, points) and pass to CVAT.

**Comment by wemamawe** [comment]
there are already existed two examples, one is box and another is point, can you write the other two example for polyline and polygon

**Comment by azhavoro** [comment]
Signatures of add_points and add_polyline, add_polygon methods are exactly the same https://github.com/opencv/cvat/blob/7ea84d1bc74d3d1053bef2677ece13e7add1c905/cvat/apps/auto_annotation/inference.py#L55. You can use add_polygon and add_polyline instead of add_points without any problems.

**Comment by wemamawe** [comment]
According to your answer, i rewrite the interpretation script.
`def clip(value):
  return max(min(1.0, value), 0.0)

for frame_results in detections:
  frame_height = frame_results["frame_height"]
  frame_width = frame_results["frame_width"]
  frame_number = frame_results["frame_id"]

  for i in range(frame_results["detections"].shape[2]):
    confidence = frame_results["detections"][0, 0, i, 2]
    if confidence < 0.5:
      continue
    x = frame_results["detections"][0, i, 0, 0]
    y = frame_results["detections"][0, i + 1, 0, 0]
    results.add_polygon(
      points=[(clip(x) * frame_width, clip(y) * frame_height)],
      label=int(frame_results["detections"][0, 0, i, 1]),
      frame_number=frame_number,
      attributes={
        "confidence": "{:.2f}".format(confidence),
      },
    )`
but still has error

>  
Checking request has returned the "failed" status. Message: Exception: Model was not properly created/updated. Test failed: index 1 is out of bounds for axis 1 with size 1

**Comment by azhavoro** [comment]
Output blob of segmentation model has shape [B, H=1024, W=2048], but you still tried use the code for blob with shape: [1, 1, N, 7]. You can "convert" pixel mask to polygons via 
Opencv's findContours for example https://docs.opencv.org/trunk/d4/d73/tutorial_py_contours_begin.html.

**Comment by azhavoro** [comment]
Also you can use https://github.com/opencv/cvat/blob/develop/utils/auto_annotation/run_model.py script to simplify debugging of you code.

**Comment by wemamawe** [comment]
sorry, According to all information that i can get, i can't code interpretation script

**Comment by azhavoro** [comment]
What kind of information do you miss?
Your interpretation code should do following steps:
1. get polygons from pixel map via findContours function from OpenCV or any similar functionality (measure.find_contours form skimage python package)
2. pass all interesting polygons to CVAT via results.add_polygon(...)

I can submit feature request for add example with interpretation script for segmentation models.

**Comment by azhavoro** [comment]
Related feature request #701 
I'll close the issue. Don't hesitate ask other questions on our gitter channel.

**Comment by wemamawe** [comment]
@azhavoro if you can write an example, it can help me a lot. thanks
> I can submit feature request for add example with interpretation script for segmentation models.

**Comment by benhoff** [comment]
@wemamawe, can you look at the expanded documentation and see if that helps you? Alternatively, I have two examples I can point you to.
