### ISSUE TITLE
Could not create the task (Open the Browser Console to get details)

### ISSUE THREAD

**Issue by Petros626** [opencv/cvat#6894]
### My actions before raising this issue
Installing CVAT with the Installation Guide under Windows 10 (https://opencv.github.io/cvat/docs/administration/basics/installation/)
Install the Semi-Automatic and Automatic Annotation (https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)

### Steps to Reproduce (for bugs)

1. Open `localhost:8080`
1. Log in and create a project
1. Paste my labels in the required format from a text file
1. Create a task with a specific name and the labels from the project (no new labels created)
2. Press Upload and wait until the error message occurs

### Expected Behaviour
That everything works fine, the health check of the containers passed succesfully.

I try to upload around ~6300 HQ `.png` images, but every time I try the upload fails. The other issues with the same issue title didn't helped me. Which specific logs should I provide for more detailed information?

Maybe the RAM is a limited Source (got 11,9GB) and I checked, if any image of the dataset is broken.

![image](https://github.com/opencv/cvat/assets/62354721/37a55932-191e-4f83-90bc-12bb7528d5e6)

**Comment by azhavoro** [comment]
please provide logs from cvat_Server container

**Comment by Petros626** [comment]
@azhavoro solved it, with providing more memory for `wsl` it seems, that every time I uploaded images the max of the memory was used and leads to this failures.
