### ISSUE TITLE
docker containers won't start

### ISSUE THREAD

**Issue by softwarelifecycle** [opencv/cvat#6899]
### Steps to Reproduce (for bugs)
After running docker compose up -d, the containers are shown started (attached)
after entering "docker ps -a", it lists all of the containers and shows some as being restarted but never fully up
Then after entering "docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'" it throws an error saying the cvat container is not started.

### Expected Behaviour
After running "docker compose up -d", and then navigating to "[localhost:8080](http://localhost:8080/)" should display homepage of cvat

### Context
CVAT is not usable

### Your Environment
Ubuntu 23.04
Not using docker swarm or Kubernetes
docker version=24.0.6
git commit: ee1d421536078be04f8b8a99e4042b7191ba6263

![cvatErrors](https://github.com/opencv/cvat/assets/44659478/2733c491-bdc2-41f1-8371-f2c5fbea9d2a)

![dockercompose](https://github.com/opencv/cvat/assets/44659478/b36b7785-2318-49a6-9c24-276ade9f2043)

**Comment by jsxyhelu** [comment]
What is your operating system version?

**Comment by azhavoro** [comment]
Logs?

**Comment by softwarelifecycle** [comment]
As stated above i am using Ubuntu 23.04 and specifically Linux 6.2.12-060212-generic

**Comment by bsekachev** [comment]
@jsxyhelu 

We are not able to help without logs from failed docker containers. I will close the issue for now.
