### ISSUE TITLE
Create job URL-s pointing at selected frame

### ISSUE THREAD

**Issue by pktiuk** [opencv/cvat#6903]
### Expected Behaviour

When you go to through frames URL changes and looks like this: `https://cvat.local/tasks/1542/jobs/4790?frame=888`. Now you can easily share an url to selected job pointing at exact frame.

### Possible Solution

Implement opening jobs at selected frame when `frame` in URL is defined.

### Context

This issue is linked with: https://github.com/opencv/cvat/issues/5109

**Comment by bsekachev** [comment]
You can copy link to a current frame using the corresponding button: https://opencv.github.io/cvat/docs/manual/basics/basic-navigation/ 

Adding frame as a query parameter affects playback performance.
