### ISSUE TITLE
Documentation for formats is cropped

### ISSUE THREAD

**Issue by 0xAtlxolotlz** [opencv/cvat#6906]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

The documentation for some file formats is cropped.

Initially I found it for YOLO, but when I looked at the [PR that changed it](https://github.com/opencv/cvat/pull/6795/) I noticed that the same happens for others:
- [YOLO](https://github.com/opencv/cvat/pull/6795/files#diff-9ca90de48d230043c1ce0f90b715881e6865923c86efea91032cdfd86dc4c317)
![YOLO](https://github.com/opencv/cvat/assets/32249096/c71f9f48-46e3-44ea-b028-2c4fb2aed9cc)

- [WIDER Face](https://github.com/opencv/cvat/pull/6795/files#diff-f601c51b618163f5f6db7343da93c77ba2904e2cc2facf047be2e9a8b49ac9d4)
![WIDER Face](https://github.com/opencv/cvat/assets/32249096/c2fb93f5-4b13-4a8f-9aa3-6280a5433c41)

- [Pascal VOC](https://github.com/opencv/cvat/pull/6795/files#diff-93789de076c248b15450570240f262a632587eb330878e5decf81b6133054f36)
![Pascal VOC](https://github.com/opencv/cvat/assets/32249096/b69a53cd-d067-4c5a-91df-2d0d7544ee2b)

### Possible Solution

Since I'm not sure what were the intended documentation I can't provide a solution.

### Context

I was reading documentation to export in YOLO format.

**Comment by azhavoro** [comment]
Fixed in #6947
