### ISSUE TITLE
How to redeploy YOLO and SAM, which are currently deployed on CPU, to GPU?

### ISSUE THREAD

**Issue by seasenzzr000** [opencv/cvat#6921]
I  deployed YOLOv7 and SAM on a CPU. I would like to inquire, in a sincere manner, about the steps and settings required to transition their deployment to a GPU.

**Comment by Petros626** [comment]
https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/#gpu-support

I guess just follow here the instructions, can do this.

**Comment by bsekachev** [comment]
Dublicate for #6793 

@SpecLad 
Have you tested this model running on GPU? 
It looks like installation pipeline is correct, but for the user it does not work on GPU

**Comment by huttunensami** [comment]
You probably need to install `onnxruntime-gpu` instead of `onnxruntime` in
https://github.com/opencv/cvat/blob/develop/serverless/onnx/WongKinYiu/yolov7/nuclio/function-gpu.yaml#L110

**Comment by seasenzzr000** [comment]
hank you very much to all the scientists at CVAT for the help provided, the problem has been perfectly solved!CVAT is an exceptional product! :)

**Comment by Petros626** [comment]
@seasenzzr000 change the issue name to a proper name to your problem, that you have already deployed on cpu is not your intension to ask

**Comment by seasenzzr000** [comment]
> @seasenzzr000 change the issue name to a proper name to your problem, that you have already deployed on cpu is not your intension to ask

Sure, the title has been updated
