### ISSUE TITLE
Possible review mode completion issues button program error

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#6950]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1.Administrator users click on review mode to review problem descriptions
2.Then try reopening to complete the error update
3.Then a browser page crash occurred

### Context

https://github.com/opencv/cvat/assets/135221549/c78cf4f6-9dec-4b04-bb5e-2199ad8b4d80

### Environment

```Markdown
-DockerDesktop latest version
-Deployment method   docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
- windows11
-i7  NVIDIA-3060
```

**Comment by bsekachev** [comment]
@KTXKIKI 

The tool version?

**Comment by KTXKIKI** [comment]
> @KTXKIKI
> 
> 工具版本？

Server version: 2.8.0

Core version: 11.1.0

Canvas version: 2.17.6

UI version: 1.57.2

**Comment by bsekachev** [comment]
@KTXKIKI 

Could you please check if this patch #6977 solves the issue for you?

**Comment by KTXKIKI** [comment]
That's awesome @bsekachev

**Comment by KTXKIKI** [comment]
@bsekachev hi  mogul  I don't know if it's a problem with my operation  
Do I create a problem as an administrator and then click to solve it, or do I report an error

https://github.com/opencv/cvat/assets/135221549/abf5a30e-f080-4a0c-9f13-23cab3ebd228

**Comment by KTXKIKI** [comment]
I am using Edge's browser and there is no built-in translation for browser plugins

**Comment by KTXKIKI** [comment]
Server version: 2.8.0

Core version: 11.1.0

Canvas version: 2.17.6

UI version: 1.57.3    

We have installed your repaired

**Comment by bsekachev** [comment]
I submit that it is reproducable with enabled Chrome translactor. I will take a look.

**Comment by KTXKIKI** [comment]
i try  it's all a matter of the browser's built-in translation
