### ISSUE TITLE
It cannot be processed

### ISSUE THREAD

**Issue by nasserdr** [opencv/cvat#6956]
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Connect the account to an Azure storage.
2. Add a project.
3. Inside the project, create a new task,
4. Then, select files from Cloud Storage and choose some files.

I get the message shown below.
I am working on a trial account on cvat.ai
![image](https://github.com/opencv/cvat/assets/15745564/b78746ab-31c3-4d46-9153-ef5748e1ff19)

**Comment by bsekachev** [comment]
Please, be sure that you did not select anything except for images
