### ISSUE TITLE
Can attribute name is sorted by alphabetical order in xml?

### ISSUE THREAD

**Issue by jeamk** [opencv/cvat#696]
List of attribute name is looks like random in xml as follows.

```
<image height="3648" width="5472" name="car01.JPG" id="0">
<box occluded="0" ybr="2099.93" xbr="1640.76" ytl="1574.92" xtl="919.91" label="container">
<attribute name="manufacture">bmw</attribute>
<attribute name="color">red</attribute>
<attribute name="weather">cloudy</attribute>
<attribute name="size">2</attribute>
</box>
</image>
-<image height="3648" width="5472" name="car02.JPG" id="1">
-<box occluded="0" ybr="2141.60" xbr="2953.27" ytl="1549.92" xtl="2144.93" label="container">
<attribute name="color">red</attribute>
<attribute name="size">2</attribute>
<attribute name="weather">cloudy</attribute>
<attribute name="manufacture">bmw</attribute>
 ```

Do you know attribute name is sorted by alphabetical order in xml ?

**Comment by nmanovic** [comment]
@jeamk , why do you need that?

**Comment by bsekachev** [comment]
@jeamk 
Order isn't sorted alphabetically

**Comment by jeamk** [comment]
We need to convert from xml to json which can load to SSD 512.
I want the order to be fixed so that it can be converted automatically.

**Comment by bsekachev** [comment]
@jeamk 
You can sort these names at conversion time if you need.

**Comment by jeamk** [comment]
I'm sorry but what do you mean by conversion time?

**Comment by bsekachev** [comment]
@jeamk 
When you convert from xml to json you can sort attributes by name just "on the fly".

**Comment by jeamk** [comment]
Thank you for your help.
