### ISSUE TITLE
Unable to upload more videos

### ISSUE THREAD

**Issue by trinath503** [opencv/cvat#697]
1. Currently, I uploaded 110 videos, after that, I am unable to upload more videos
2. The screenshot is added: The message displayed by the server while uploading
![Screenshot from 2019-09-06 12-07-39](https://user-images.githubusercontent.com/19545163/64406379-48b96d80-d09f-11e9-869d-49e93d3f1af0.png)

**Comment by bsekachev** [comment]
@trinath503 
Not enough data for investigation. 
There should be an exception message. 
Could you attach more logs?

**Comment by trinath503** [comment]
WARNINGS:
cvat          | [Fri Sep 06 06:51:32.232920 2019] [mpm_event:info] [pid 11:tid 140509430810496] AH00490: Server built: 2019-04-03T13:34:47
cvat          |                                                                                                                             [35/34449]
cvat          | 2019-09-06 06:51:31,304 DEBG 'ssh-agent' stderr output:
cvat          | debug1: XXX shrink: 3 < 4
cvat          |
cvat          | 2019-09-06 06:51:32,196 DEBG 'runserver' stdout output:
cvat          | Successfully ran command.
cvat          | Server URL         : http://localhost:8080/
cvat          | Server Root        : /tmp/mod_wsgi-localhost:8080:1000
cvat          | Server Conf        : /tmp/mod_wsgi-localhost:8080:1000/httpd.conf
cvat          | Error Log File     : /dev/stderr (INFO)
cvat          | Request Capacity   : 5 (1 process * 5 threads)
cvat          | Request Timeout    : 60 (seconds)
cvat          | Startup Timeout    : 15 (seconds)
cvat          | Queue Backlog      : 100 (connections)
cvat          | Queue Timeout      : 45 (seconds)
cvat          | Server Capacity    : 20 (event/worker), 20 (prefork)
cvat          | Server Backlog     : 500 (connections)
cvat          | Locale Setting     : C.UTF-8
cvat          |
cvat          | 2019-09-06 06:51:32,233 DEBG 'runserver' stderr output:
cvat          | [Fri Sep 06 06:51:32.232770 2019] [wsgi:info] [pid 139:tid 140509430810496] mod_wsgi (pid=139): Starting process 'localhost:8080' with
 threads=5.
cvat          |
cvat          | 2019-09-06 06:51:32,233 DEBG 'runserver' stderr output:
cvat          | [Fri Sep 06 06:51:32.232869 2019] [mpm_event:notice] [pid 11:tid 140509430810496] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.6.2 Pytho
n/3.5 configured -- resuming normal operations
cvat          | [Fri Sep 06 06:51:32.232920 2019] [mpm_event:info] [pid 11:tid 140509430810496] AH00490: Server built: 2019-04-03T13:34:47
cvat          | [Fri Sep 06 06:51:32.232927 2019] [core:notice] [pid 11:tid 140509430810496] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tm
p/mod_wsgi-localhost:8080:1000/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE
 -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'
cvat          |
cvat          | 2019-09-06 06:51:32,234 DEBG 'runserver' stderr output:
cvat          | [Fri Sep 06 06:51:32.233962 2019] [wsgi:info] [pid 139:tid 140509430810496] mod_wsgi (pid=139): Python home /usr.
cvat          | [Fri Sep 06 06:51:32.233996 2019] [wsgi:info] [pid 139:tid 140509430810496] mod_wsgi (pid=139): Initializing Python.
cvat          |
cvat          | 2019-09-06 06:51:32,259 DEBG 'runserver' stderr output:
cvat          | [Fri Sep 06 06:51:32.259504 2019] [wsgi:info] [pid 139:tid 140509430810496] mod_wsgi (pid=139): Attach interpreter ''.
2019-09-06 06:51:32,263 DEBG 'runserver' stderr output:
cvat          | [Fri Sep 06 06:51:32.263075 2019] [wsgi:info] [pid 139:tid 140509430810496] mod_wsgi (pid=139): Imported 'mod_wsgi'.
cvat          | [Fri Sep 06 06:51:32.263128 2019] [wsgi:info] [pid 139:tid 140509430810496] mod_wsgi (pid=139, process='localhost:8080', application='
'): Loading Python script file '/tmp/mod_wsgi-localhost:8080:1000/handler.wsgi'.
cvat          |
cvat          | 2019-09-06 06:51:32,492 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          |
cvat          | 2019-09-06 06:51:32,494 DEBG 'ssh-agent' stderr output:
cvat          | debug1: type 17
cvat          |
cvat          | 2019-09-06 06:51:32,496 DEBG 'ssh-agent' stderr output:
cvat          | debug1: XXX shrink: 3 < 4
cvat          |
cvat          | 2019-09-06 06:51:32,499 DEBG 'ssh-agent' stderr output:
cvat          | debug2: fd 4 setting O_NONBLOCK
cvat          | debug1: type 11
cvat          |
cvat          | 2019-09-06 06:51:32,500 DEBG 'ssh-agent' stderr output:
cvat          | debug1: XXX shrink: 3 < 4
cvat          |
cvat          | 2019-09-06 07:08:12,236 DEBG 'runserver' stderr output:
cvat          | [Fri Sep 06 07:08:12.235814 2019] [wsgi:error] [pid 139:tid 140509230384896] [remote 122.112.199.218:49222] [2019-09-06 07:08:12,235]
WARNING django.request: Not Found: /axis2/
cvat          |
cvat          | 2019-09-06 07:31:49,547 DEBG 'runserver' stderr output:
cvat          | [Fri Sep 06 07:31:49.547202 2019] [wsgi:error] [pid 139:tid 140509196814080] [remote 196.52.43.90:56806] [2019-09-06 07:31:49,547] ERR
OR django.security.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8080'. You may need to add 'localhost' to ALLOWED_HOSTS.
cvat          |
cvat          | 2019-09-06 07:31:49,548 DEBG 'runserver' stderr output:
cvat          | [Fri Sep 06 07:31:49.548217 2019] [wsgi:error] [pid 139:tid 140509196814080] [remote 196.52.43.90:56806] [2019-09-06 07:31:49,548] WAR
NING django.request: Bad Request: /





![Screenshot from 2019-09-06 13-10-02](https://user-images.githubusercontent.com/19545163/64410163-07798b80-d0a8-11e9-81db-4458204cb027.png)

**Comment by bsekachev** [comment]
@trinath503 
Everything alright in logs.

**Comment by nmanovic** [comment]
@trinath503 , do you still have the issue? Do you have more information for us? Could you please attach archived `logs` directory from the docker container?

**Comment by nmanovic** [comment]
@trinath503 , I will close the issue till we have more information to investigate it.
