### ISSUE TITLE
Total work time reported from ClickHouse is significantly less than actual work time

### ISSUE THREAD

**Issue by may109** [opencv/cvat#6973]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. go to cvat main page and click on "Analytics" using admin login
2. Click Dashboards and go to Management
3. Select a user id and check the total working time reported

### Expected Behavior

The reported working time should match the actual working time in cvat.

### Possible Solution

Is there alternative way to get the actual working time from CVAT logs? We tried to use SQL builder in the "analytics" but the counted hour is still less than user's hour. Could you please suggest some sample SQL so we may capture all?

**Comment by may109** [comment]
We asked labelers to report their own working time daily. We've noticed a big difference between the user reported time and the dashboard reported time. I tracked my own work for 3.87 actual work hours but dashboard of "Management" only reports 1.91 hours in total. I looked at the logs from ClickHouse SQL, it captures the activity logs properly for the 3.87 hours but the total work_time from "payload" column only sums up to 2.21 hours.

**Comment by katab** [comment]
We have the same issue!

**Comment by may109** [comment]
@nmanovic Any thoughts pls?

**Comment by azhavoro** [comment]
For each batch of events that the UI sends to the backend, we calculate the total uptime using the following approach:
timedelta = event_1.timestamp - event_2.timestamp
if timedelta < 100 seconds, the working_time field is set in the payload
but for the first event in the batch the working time is always 0, which results in a negligible difference
You can easily verify the report time calculation by exporting all task related events to csv format and calculating the working time in ms excel using the above formula

If you will find any mistake in the calculation please provide your calculations, we are always open to contributions

**Comment by azhavoro** [comment]
No response, so I'm closing the question for now
