### ISSUE TITLE
Fixing image while annotating

### ISSUE THREAD

**Issue by wiekern** [opencv/cvat#6979]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

Hi, I would like to fix the image in mode of "Cursor [Esc]", since I am not willing to move image, unless "Move the image" pressed.

### Describe the solution you'd like

Providing a switch that I could lock the image preventing it from moving.

**Comment by bsekachev** [comment]
Not sure what is the problem.
Canvas is not moved on left mouse button down/move/up when you are drawing a polygon, or another shape.

**Comment by wiekern** [comment]
e.g. I hope I can make the image fit the window and moving is disable, unless I press "Move the image"
![image](https://github.com/opencv/cvat/assets/3865455/f4189266-68a2-4f3c-b8a4-2017a3367340)
At this moement, in state of Cursor [Esc] the image can be moved if I drag and drop it.

**Comment by bsekachev** [comment]
I see. CVAT does not have such the option as far as I remember.

**Comment by wiekern** [comment]
Could you give me some advice that I am able to develop this feature in my local environment? e.g. comment the code of moving images out.

**Comment by bsekachev** [comment]
You need to modify event listener in this place: https://github.com/opencv/cvat/blob/176bac2d0ba5b41533a3e69d9779685bab3d3f39/cvat-canvas/src/typescript/canvasView.ts#L1246

**Comment by wiekern** [comment]
Hi, I deploy CVAT via docker-compose on Windows, is it possible modify the relevant code above directly in a container list below
![image](https://github.com/opencv/cvat/assets/3865455/f51713ad-5038-429d-aea2-cfed324e838b)
? If yes, could you tell me in which container it locates in. If not, how could I build a local docker image and push it in my current production environment? 
Thanks~

**Comment by bsekachev** [comment]
> Hi, I deploy CVAT via docker-compose on Windows, is it possible modify the relevant code above directly in a container list below

I do not think so. Client application code maggled and bundled with webpack. After build process it is very difficult to locate and change it.

**Comment by jneeven** [comment]
@bsekachev 
> Not sure what is the problem. Canvas is not moved on left mouse button down/move/up when you are drawing a polygon, or another shape.

https://docs.cvat.ai/docs/manual/advanced/annotation-with-polygons/manual-drawing/ mentions
> When Shift isn’t pressed, you can zoom in/out (when scrolling the mouse wheel) and move (when clicking the mouse wheel and moving the mouse), you can also delete the previous point by right-clicking on it.

This doesn't seem to be true; if I want to move around the image while drawing I need to hold the Alt key. Is this deliberate?
