### ISSUE TITLE
Google Translator makes reactive app unusable

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#6983]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Click on cloud storage
Click on New Cloud Storage
Switching between different servers

### Context

https://github.com/opencv/cvat/assets/135221549/3279093c-f8b8-4573-9ae8-a55e2099b6a2

### Environment

```Markdown
Server version: 2.8.0

Core version: 11.1.0

Canvas version: 2.17.6

UI version: 1.57.3
```

**Comment by bsekachev** [comment]
Hi @KTXKIKI 

Looks like the problem also related to enabled translation.

**Comment by KTXKIKI** [comment]
year  i try   it's all a matter of the browser's built-in translation

**Comment by bsekachev** [comment]
It is a problem of interaction between React and Google Translator. 
As I understand from these resources, Google Translator not just modifies text content, it insert/removes node from DOM. 
It creates issues with different reactive frameworks. 

https://bugs.chromium.org/p/chromium/issues/detail?id=872770 
https://github.com/facebook/react/issues/11538

**Comment by bsekachev** [comment]
And looks like there is not a solution from React team except for:
- Inserting additional code that slows down the app in common
- Disabling the translation of the page

Issue on Google Translation team is still opened. 
Maybe you should try another translator as a workaround.

**Comment by KTXKIKI** [comment]
ok
