### ISSUE TITLE
How to upload dataset from host device

### ISSUE THREAD

**Issue by WilberRojas** [opencv/cvat#6986]
Hello, I have a code that generates images, and I want to automatically upload them to a locally running CVAT instance using Docker containers.

Essentially, what I want to do is use one or multiple 'docker cp' commands to copy the necessary images and files into the containers and have them appear in CVAT when it's opened. (Or if there's already an implemented code that does this, then I'd like to use that)

**Comment by maecky** [comment]
There is an API and SDK available: https://opencv.github.io/cvat/docs/api_sdk/sdk/
