### ISSUE TITLE
WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)".

### ISSUE THREAD

**Issue by maecky** [opencv/cvat#6987]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. I created a MINIO docker instance (same server as CVAT is running)
`
docker run -p 9000:9000 -p 9090:9090 --name minio1 -v D:\minio\data:/data -e "MINIO_ROOT_USER=ROOTUSER" -e "MINIO_ROOT_PASSWORD=CHANGEME123" quay.io/minio/minio server /data --console-address ":9090"
`
3. I created a testbucket
4. I created an AWS S3 Cloud Storage Entry in CVAT and clicked submit

I get the following error:
Error: Request failed with status code 400. "SSL validation failed for https://192.168.0.200:9090/testbucket [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)".

### Expected Behavior

New connected S3 compatible cloud storage

### Environment

CVAT Version 2.7.2

**Comment by maecky** [comment]
I don't think that this is a question, @bsekachev . I clearly throws an error. I guess that is not the intended behaviour? ;)

**Comment by maecky** [comment]
@bsekachev, I understand that but it's about connecting to minIO. minIO is a self-hosted S3 bucket and is fully compatible with Amazon S3. But it's not working with CVAT because of the error above.

I guess connecting to a S3 bucket needs SSL too and doesn't work over an unencrypted HTTP connection.

**Comment by azhavoro** [comment]
please provide a full stack trace of the error from `cvat_server` container
