### ISSUE TITLE
Create new job by API

### ISSUE THREAD

**Issue by WilberRojas** [opencv/cvat#6988]
Hello, I'm having difficulties when trying to create a new JOB using the API. According to the documentation, it mentions that I should include "type": "annotation" in the JSON, but I'm getting the following error:

400 ["Unexpected job type 'annotation'"]

I've noticed that in older forums, It's mentioned that a JOB can't be created after creating a TASK, which has left me confused because the documentation has a section explaining how to do it, but it's not working for me. You can find the documentation here: [Method creates a new job in the task](https://app.cvat.ai/api/docs/#tag/jobs/operation/jobs_create).

So, I wonder if I'm doing something wrong. In case a JOB can't be created after a TASK. how should I create the TASK to upload images during its creation?

I'm using the following code, but only `create_task.py` works correctly.
P.S.: I'm providing it in text format (.txt) since it doesn't allow me to upload files with a .py extension.

[create_job.py.txt](https://github.com/opencv/cvat/files/12875526/create_job.py.txt)
[create_task.py.txt](https://github.com/opencv/cvat/files/12875527/create_task.py.txt)

**Comment by zhiltsov-max** [comment]
Hi. In general, the basic workflow is the following: you create a task, upload the data, and it automatically gets split into jobs. You can't add or remove regular annotation jobs manually, but you can control how the data is split between jobs with task parameters. The endpoint for job creation that you mention only allows to create special ground truth jobs for task quality estimation.

If you just want to create a new task with data, please consider using the high-level SDK API ([docs](https://opencv.github.io/cvat/docs/api_sdk/sdk/highlevel-api/#example)):

```python
from cvat_sdk import make_client, models

with make_client(host="localhost", credentials=('user', 'password')) as client:
    task = client.tasks.create_from_data(
        spec=models.TaskWriteRequest(
            name="example task",
            labels=[ { "name": "car" } ],
        ),
        resources=['image1.jpg', 'image2.png'],
    )
```

**Comment by hetfmt** [comment]
Using the high-level CVAT Python SDK, I have successfully created an empty task using the following code:

```
# Create task spec
task_spec = {
    "name": "task_without_images",
    "project_id": desired_project_id,
    "mode": "annotation",  # Can be: "annotation", "validation" or "acceptance"
    "subset": "Train",  # Can be: "Train", "Test" or "Validation"
}
# Create task
task_without_images = client.tasks.create(spec=task_spec)
```

Now I can add images using the following code:
```
# Get handle to task
task = client.tasks.retrieve(desired_task_id)  # Or I could have used the above created handle

# Create list of files to add to task
resources = ["image1.jpg", "image2.jpg"]

# Upload images
task.upload_data(resources)
```
This works for me.

**Comment by WilberRojas** [comment]
Thank you very much, both comments were very helpful
