### ISSUE TITLE
Can not import dataset or create task -> cvat_worker_import: ./backend_entrypoint.sh: run: expected 1 argument

### ISSUE THREAD

**Issue by baudneo** [opencv/cvat#6999]
# CVAT is proxied by Cloudflare tunnel

### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Applied the `CSRF_TRUSTED_ORIGINS` fix (for POST on django admin page) - https://github.com/opencv/cvat/pull/6322
- [X] Set `CVAT_HOST=cvat.<REDACTED>.com`
- [X] Set `CVAT_BASE_URL=https://cvat.<REDACTED>.com`
- [X] Set traefik `'--entryPoints.web.forwardedHeaders.trustedIPs'` to all Cloudflare IP ranges and my local host's IP that is running cloudflared (fixes not being able to POST aka create tasks) - https://github.com/opencv/cvat/issues/6917#issuecomment-1748186496

### Steps to Reproduce

1. Export dataset from roboflow
2. Convert dataset from roboflow_coco to coco 1.0 using datamuro
3. Zip the dataset
4. Navigate to your cvat instance **proxied by Cloudflare tunnel**.
5. Project > Actions > Import Dataset
6. Select COCO 1.0 as format and try to upload the zip file: RESULT => Error.
7. Try to create a new task: RESULT => Stuck at 0% importing.

### Expected Behaviour

I expect to be able to import datasets into the project

### Possible Solution

I see an error in the logs:
```
cvat_worker_import             | ./backend_entrypoint.sh: run: expected 1 argument
cvat_worker_import exited with code 1
```
I am assuming this error is in regard to importing the new task. Possible fix is to debug why it is not receiving its 1 argument.

### Context
My CVAT instance is **proxied by Cloudflare tunnel**.
This error looks exactly like the error I was having when trying to create a task, but there is not a `Content-Mismatch` warning -> https://github.com/opencv/cvat/issues/6917#issuecomment-1748186496

# Error
```
Error: tus: failed to upload chunk at offset 0, caused by [object ProgressEvent], originated from request 
(method: PATCH, url: http://cvat.<REDACTED>.com/api/projects/1/dataset/d85df7ff-29b6-40dc-a5ad-2c0bf296d5a2, response code: n/a, response text: n/a, request id: n/a).
```

My site is HTTPS only and tus seems to be requesting HTTP, this may be a red herring though. Also, `cvat_worker_import` container is throwing errors:

```
cvat_worker_import             | ./backend_entrypoint.sh: run: expected 1 argument
cvat_worker_import exited with code 1
```

How can I fix this?

### Environment

```Markdown
- Latest cvat docker images (tags: latest and dev) both tags have same issue.
- Docker version: Docker version 24.0.6, build ed223bc
- Debian Bullseye (Proxmox)
- `docker compose logs` have some weird logs, see below comments

I think it has something to do with this log error:

cvat_worker_import             | ./backend_entrypoint.sh: run: expected 1 argument
cvat_worker_import exited with code 1

```

**Comment by baudneo** [comment]
There is a weird warning in traefik DEBUG logs for `cvat_server` and `cvat_ui`:
```
traefik                        | time="2023-10-13T02:02:16Z" level=warning msg="Could not find network named 'cvat' for container '/cvat_ui'! Maybe you're missing the project's prefix in the label? Defaulting to first available network." providerName=docker container=cvat-ui-cvat-ffcdb0fe823bfd37e399ab2b68c2fcddd89e28447f87bb268f417b41e429ab2d serviceName=cvat-ui
-------------------------------------------------

traefik                        | time="2023-10-13T02:02:16Z" level=warning msg="Could not find network named 'cvat' for container '/cvat_server'! Maybe you're missing the project's prefix in the label? Defaulting to first available network." serviceName=cvat providerName=docker container=cvat-server-cvat-18b2d93dc8c774858312dc9ce0257f0e574dc0b483dda959b10872dc886e35ac
```

There is a `cvat_cvat` network.
```
╰─❯ docker network ls
NETWORK ID     NAME                  DRIVER    SCOPE
32463f9aaca3   bridge                bridge    local
e626d6bee2b5   cloudflared_default   bridge    local
e663802c6bf7   cvat_cvat             bridge    local
4105980eab99   host                  host      local
4ea78961b37d   none                  null      local
```

Both `cvat_ui` and `cvat_server` have

```
# cvat_server
    networks:
      cvat:
        aliases:
          - cvat-server
# cvat_ui
    networks:
      - cvat
```

**Comment by baudneo** [comment]
More weird actions: I was getting the same error when creating a task but all of a sudden, It allows me to create a task, but it sits at 0%.

![Screenshot_2023-10-14_09-32-09](https://github.com/opencv/cvat/assets/86508179/3f3845f3-5b2e-4e98-a6f1-6b39d6c53104)

**Comment by baudneo** [comment]
I am also noticing some weirdness with tags on images. I issued a `docker compose pull` and now I am seeing `latest` and `dev` tags.

```
cvat/ui                           dev               c0b16e084d1f   45 hours ago    145MB
cvat/server                       dev               d2b9351cedf0   46 hours ago    2.77GB
traefik                           latest            cc365cbb0397   3 days ago      151MB
cvat/ui                           <none>            d99892aa9005   4 days ago      145MB
cvat/server                       <none>            8c2b8b050d3a   4 days ago      2.77GB
postgres                          15-alpine         9f959158ce82   10 days ago     237MB
cvat/server                       latest            ed304b59905c   11 days ago     3.14GB
cvat/ui                           <none>            5358101b1b13   3 weeks ago     144MB
cvat/server                       <none>            e685cf17c422   3 weeks ago     2.78GB
postgres                          <none>            ab8fb914369e   2 months ago    237MB
traefik                           v2.9              d1e26b5f8193   6 months ago    138MB
clickhouse/clickhouse-server      22.3-alpine       d4088d71d1dc   6 months ago    773MB
eqalpha/keydb                     x86_64_v6.3.2     b9c88d8f9d06   8 months ago    129MB
grafana/grafana-oss               9.3.6             f925787d0f79   8 months ago    317MB
timberio/vector                   0.26.0-alpine     d8ecc9831523   10 months ago   122MB
openpolicyagent/opa               0.45.0-rootless   8723f2dc306a   12 months ago   84.3MB
```

**Comment by baudneo** [comment]
Just updating, its been almost 24 hours and the task is still sitting at 0% importing.

![Screenshot_2023-10-15_09-22-25](https://github.com/opencv/cvat/assets/86508179/f6adfa38-009b-4166-86eb-cd920df543d5)

**Comment by baudneo** [comment]
Hi, sorry to bug again but can anyone possibly take a look at this? I can't create any tasks or import any datasets so, I can't use cvat.

I really don't want to use roboflow. I would prefer to run cvat but, it has been unbelievably unreliable. I've spent more time debugging and fixing cvat than I have working on my projects.

Any advice or pointers would be appreciated.

**Comment by baudneo** [comment]
I nuked the install and managed to get things working again.

**Comment by shojint** [comment]
I also got the same problem. After I deleted all CVAT's containers and images, I no longer get this error.

Unfortunately for me, now I get 404 instead when typing localhost:8080.

**Comment by shojint** [comment]
Eventually, the 404 error resolved itself for whatever reason. Then I encountered this problem https://github.com/cvat-ai/cvat/issues/9594.

Anyway, everything is working now.

**Comment by shojint** [comment]
Turns out I could have avoided the first error in the first place if I had read the update guide carefully.
https://docs.cvat.ai/docs/administration/advanced/upgrade_guide/
`Update local CVAT images. Pull or build new CVAT images, see [How to pull/build/update CVAT images section](https://docs.cvat.ai/docs/administration/basics/installation/#how-to-pullbuildupdate-cvat-images) for details.`
