### ISSUE TITLE
i can not visit app.cvat.ai (Oct 13, 2023)

### ISSUE THREAD

**Issue by syyxtl** [opencv/cvat#7000]
i can not visit app.cvat.ai (Oct 13, 2023). 
![image](https://github.com/opencv/cvat/assets/66545456/3772b677-b551-4aa7-9388-549257069527)

what happened?

**Comment by rogercomeon** [comment]
I encountered the same problem and there is no solution yet

**Comment by syyxtl** [comment]
> I encountered the same problem and there is no solution yet

the problem is solved, i can visit the website now
