### ISSUE TITLE
The number of additional annotations (BBox) in CVAT work is different from the number of BBoxes stored in the JSON file exported in COCO format

### ISSUE THREAD

**Issue by kirorotarzan** [opencv/cvat#7001]
"I apologize for the inconvenience. I added BBoxes to images in CVAT and exported them as a JSON file in COCO format. Upon checking the contents, I found that the number of BBoxes in CVAT and those stored in the JSON file don't match. For instance, some BBoxes that are not displayed in the CVAT workspace exist in the JSON file, or some BBoxes that were added in CVAT are missing when I check the contents of the JSON file. It's possible that this issue arises from a problem during CVAT's export process or maybe due to using the 'outside' property. If there are any potential reasons for this discrepancy or solutions to this problem, I would greatly appreciate your guidance."

Would you like me to address the issue you mentioned as well?

**Comment by kirorotarzan** [comment]
> "I apologize for the inconvenience. I added BBoxes to images in CVAT and exported them as a JSON file in COCO format. Upon checking the contents, I found that the number of BBoxes in CVAT and those stored in the JSON file don't match. For instance, some BBoxes that are not displayed in the CVAT workspace exist in the JSON file, or some BBoxes that were added in CVAT are missing when I check the contents of the JSON file. It's possible that this issue arises from a problem during CVAT's export process or maybe due to using the 'outside' property. If there are any potential reasons for this discrepancy or solutions to this problem, I would greatly appreciate your guidance."
> 
> Would you like me to address the issue you mentioned as well?

**Comment by zhiltsov-max** [comment]
Hi. Please add more details so we could help.

**Comment by kirorotarzan** [comment]
"Sorry for the delayed response.

Phenomenon that occurred this time:
When annotating images in CVAT and exporting them as JSON files in COCO format, I found that BBoxes that were not displayed on the CVAT UI were included in the JSON's BBox information. Furthermore, the BBox with the same coordinates remained from the problem frame until the last frame of the job. The same phenomenon was confirmed when exporting in other formats as well. Upon investigating whether there was a problem with the way I was annotating in CVAT, I confirmed that I had used the 'Track' feature for the BBoxes. Once I removed the BBoxes added through 'Track,' the above phenomenon was resolved.

Current question:
Does such a phenomenon occur when using the 'Track' feature?"

**Comment by zhiltsov-max** [comment]
Yes, the track annotations are supposed to work this way - they fill the whole range of frames from the first one, where they appear, till the last one. Their visibility can be controlled by the "outside" option. 
https://opencv.github.io/cvat/docs/manual/basics/track-mode-basics/
