### ISSUE TITLE
i can't import labels to yolov1.1

### ISSUE THREAD

**Issue by ig-byte** [opencv/cvat#7008]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I have a problem, when I import the tags in yolov1.1 and finish the upload process. cvat shows this error.
![Could not upload annotation for the X](https://github.com/opencv/cvat/assets/37984764/00f756a3-8672-4aad-a548-3de71f1b129e)

When I check the file inside, it contains:
![Archivo Edición Formato Ver Ayuda](https://github.com/opencv/cvat/assets/37984764/fe48547f-9ec1-4d74-b320-248c918ee3c5)
Inside the file, there is a line break, but in the line below, there are no spaces.  

the Docker logs show this:

![Captura de pantalla 2023-10-13 a la(s) 15 19 12](https://github.com/opencv/cvat/assets/37984764/6853f22c-8d82-4995-9e01-2f0f66fe4efe)

In the cvat project, I have configured the corresponding tags and the index found in the .txt file should be correct.

**Comment by zhiltsov-max** [comment]
Hi, please make sure there are at least 4 labels in the obj.names file, so the label id 3 is valid.

**Comment by ig-byte** [comment]
> Hi, please make sure there are at least 4 labels in the obj.names file, so the label id 3 is valid.

thank you so much ! , i checked this and you are right.
