### ISSUE TITLE
Interpretation script for segmentation models

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#701]
It would be nice to extend the documentation with examples of interpretation script for segmentation models:
https://github.com/opencv/open_model_zoo/tree/master/intel_models/road-segmentation-adas-0001
https://github.com/opencv/open_model_zoo/blob/master/intel_models/instance-segmentation-security-0010/description/instance-segmentation-security-0010.md

**Comment by benhoff** [comment]
This isn't 100% working out of the box, but it might be a decent reference script:  https://github.com/benhoff/cvat/blob/instance-segmentation/utils/open_model_zoo/Security/instance_segmentation/interp.py

**Comment by benhoff** [comment]
https://github.com/opencv/cvat/pull/804

**Comment by benhoff** [comment]
I'd recommend closing this.
