### ISSUE TITLE
Can not access cvat analytics, bad gateway

### ISSUE THREAD

**Issue by VG-Huai** [opencv/cvat#7010]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Go to cvat web page
2. click on the analytics button
3. Get 502 Bad gateway

**Comment by VG-Huai** [comment]
Sorry, I found that the reason is some people had deployed their own docker functions but used the same port as cvat analytics. I will close this issue.

**Comment by VG-Huai** [comment]
Sorry, I found that the reason is some people had deployed their own docker functions but used the same port as cvat analytics. I will close this issue.

**Comment by apanaskar** [comment]
CVAT installed on Ubuntu 18.04 as per steps from `https://opencv.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64`

CVAT version : 2.9.0

Used this command to access CVAT over a network `export CVAT_HOST=10.21.134.90`
Consider this IP 10.21.134.90 as my systems static IP.

Server is accessible on `10.21.134.90:8080 `& not on `10.21.134.90`

On `10.21.134.90:8080` I am able to access Projects, Tasks, Jobs, Cloud Storage but when clicked on 'Analytics' page, it shows 502 Bad gateway error.

How to resolve this issue?

**Comment by arhmnsh** [comment]
I am facing the same issue. Any pointers on how this can be fixed?

**Comment by apanaskar** [comment]
It worked for me after changing Network settings.

Set Network Proxy to Automatic- then restart the server once (down and up)

**Comment by Sepharial144** [comment]
release-2.3.0 Had the same problem
This problem appear when docker does't get no proxy settings, so to fix it need to do
1. create docker config file if not exist and write no proxy in ~/.docker/config.json
{
  "proxies": {
    "default": {
      "httpProxy": "",
      "httpsProxy": "",
      "noProxy": "127.0.0.1"
    }
  }
}
2. create bash file to run application run.sh, or whatewer you want:
#!bin/bash
export CVAT_HOST=your_ip_of_server
export no_proxy=localhost,127.0.0.1
docker compose up -d

If it does not worked, try to provide these variables into docker manually from command
use docker logs cvat_server to debug you variables if has problems in symbols
