### ISSUE TITLE
Question: How can I see the current number of annotations for each class? 

### ISSUE THREAD

**Issue by ganindu7** [opencv/cvat#7012]
Hi, is there a way to see the counts for each label class at any given time? 

Basically annotation stats for a given project so I know how many images I have completed labling for each label class.

the grafana analytics seem to be action based and more suited for large teams with dedicated annotators (we just simply want to know the stats for each project and are not intersted in macro actions performed by an indivudual)

**Comment by bsekachev** [comment]
For a project there is no way to do that, only for a job.

**Comment by ganindu7** [comment]
Thanks for tha answer!
