### ISSUE TITLE
Use cvat without internet connection

### ISSUE THREAD

**Issue by tugcekiziltepe** [opencv/cvat#7015]
I have a computer which does not have internet connection. But I can transfer data to this computer. I wonder if I can use CVAT without accessing internet and signing in.

**Comment by bsekachev** [comment]
In theory you can try doing that, by building self-hosted version and moving docker images to this machine. But you need advanced technical skills for that. 
Maybe swapping physical drive between computer with/without the Internet would be an easier solution.
