### ISSUE TITLE
JSON parsing error reported

### ISSUE THREAD

**Issue by fengdouzhe** [opencv/cvat#7017]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I have already started cvat using Python management. py runserver locally, and then I have also started the cvat ui front-end. When logging in, I ensure that the JSON parsing is incorrect and I cannot find the problem

### Expected Behavior

I have already started cvat using Python management. py runserver locally, and then I have also started the cvat ui front-end. When logging in, I ensure that the JSON parsing is incorrect and I cannot find the problem

### Possible Solution

I have already started cvat using Python management. py runserver locally, and then I have also started the cvat ui front-end. When logging in, I ensure that the JSON parsing is incorrect and I cannot find the problem

### Context

I have already started cvat using Python management. py runserver locally, and then I have also started the cvat ui front-end. When logging in, I ensure that the JSON parsing is incorrect and I cannot find the problem

### Environment

```Markdown
I have already started cvat using Python management. py runserver locally, and then I have also started the cvat ui front-end. When logging in, I ensure that the JSON parsing is incorrect and I cannot find the problem
```

**Comment by fengdouzhe** [comment]
I started it locally using Python management. py runserver, and Redis, pg, and clickhouse are services that access the online Docker environment. After starting it, I reported a JSON parsing error using localhost: 8080/api/users

**Comment by bsekachev** [comment]
Please, fill the issue template properly, your environment and steps to reproduce if you believe it is a bug. Provide us all the logs and screenshots according to the template. 

Try to follow step by step installation guide: https://opencv.github.io/cvat/docs/administration/basics/installation/.  

You can also try online version for free: https://app.cvat.ai

**Comment by fengdouzhe** [comment]
> Please, fill the issue template properly, your environment and steps to reproduce if you believe it is a bug. Provide us all the logs and screenshots according to the template.
> 
> Try to follow step by step installation guide: https://opencv.github.io/cvat/docs/administration/basics/installation/.
> 
> You can also try online version for free: https://app.cvat.ai

I have resolved the issue with the configuration file. Thank you
