### ISSUE TITLE
Annotations worked with Track are not extracted as coco keypoints.

### ISSUE THREAD

**Issue by sh0622-kim** [opencv/cvat#7021]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Draw new skeleton
2. Select Label
3. Track
4. Annotation...
5. Export COCO Keypoints 1.0

```json
 {
      "id": 1,    <-- Shape Annotate
      "image_id": 211,
      "category_id": 1,
      "segmentation": [],
      "area": 3624.4991999999997,
      "bbox": [
        20.51,
        37.12,
        67.42,
        53.76
      ],
      "iscrowd": 0,
      "attributes": {
        "occluded": false
      },
      "keypoints": [
        21.05,
        37.12,
        2,
        87.93,
        37.98,
        2,
        87.62,
        90.88,
        2,
        20.51,
        90.02,
        2
      ],
      "num_keypoints": 4
    },
    {
      "id": 2,   <-- Track Annotate
      "image_id": 212,
      "category_id": 1,
      "segmentation": [],
      "area": 0,
      "bbox": [
        0,
        0,
        0,
        0
      ],
      "iscrowd": 0,
      "attributes": {
        "occluded": false,
        "track_id": 0,
        "keyframe": true
      },
      "keypoints": [],
      "num_keypoints": 0
    },
```

### Expected Behavior

It is hoped that the attribute items will be applied normally even if the track is used.

### Context

I want to extract with COCO Keyports even if I annotate with Track.

### Environment

```Markdown
commit 56f527aa2ff663521654e889c80615061d7f89c0 (HEAD, tag: v2.7.6, origin/master)
Merge: 7956a1879 3c05e8479
Author: Nikita Manovich <nikita@cvat.ai>
Date:   Mon Oct 16 15:33:39 2023 +0300

    Merge pull request #7005 from opencv/release-2.7.6
    
    Release v2.7.6
```

**Comment by zhiltsov-max** [comment]
Hi, 

I could not reproduce the problem, annotations are exported both from shapes and tracks. From the file contents you posted, I can see there is 0 in the `num_keypoints` field of the skeleton annotation. This value is copied from the label definition, but it should not be possible to create an empty skeleton label from UI or by importing a dataset. Could you add more details about the task label configuration and list the `categories` section of the exported annotations?

**Comment by sh0622-kim** [comment]
@zhiltsov-max 
I will reproduce the problem in detail and register it soon.

**Comment by bsekachev** [comment]
@sh0622-kim 

Let us know when you reproduced the issue and we will reopen
