### ISSUE TITLE
[Question] Group copy-paste

### ISSUE THREAD

**Issue by rahulsrajeev** [opencv/cvat#7022]
Is it possible to select a set of annotations and paste it elsewhere in the same frame, or even a later frame?

I have this set of images where I come across a sequence of similar annotations, for instance, I annotate a set of components, but then this same set of components may appear in the same order in the same frame itself, or sometimes a similar set after a few frames.
since the frames are not continuous footage but screenshots of websites, "Propagate" doesn't work for the same.

**Comment by bsekachev** [comment]
Hi @rahulsrajeev 

Unfortunately it is not possible.
See related issue #2340.
