### ISSUE TITLE
Server Version Roll Back Causing Uploading Issue

### ISSUE THREAD

**Issue by Lee4396** [opencv/cvat#7034]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

deploy Cvat version release v2.5.1 then switch back to v2.4.1, but keeping the databases

### Expected Behavior

The cloud storage doesnt work any more with the following error when trying to create a new task from it: 
![image](https://github.com/opencv/cvat/assets/43795612/b4f571f7-e28c-4fc5-8f9e-7c5ce71ef12a)

**Comment by bsekachev** [comment]
Hi @Lee4396 

- Do not fallback to previous versions when database migration occurred, not always there are reversible migration available
- It would be a good idea to make a database backup before upgrading

We can't do anything with your issue. Why not to use 2.5.1 or later releases?

**Comment by Lee4396** [comment]
> Hi @Lee4396
> 
> * Do not fallback to previous versions when database migration occurred, not always there are reversible migration available
> * It would be a good idea to make a database backup before upgrading
> 
> We can't do anything with your issue. Why not to use 2.5.1 or later releases?

2.5.1 presents cache issues, will try newer versions

**Comment by bsekachev** [comment]
What kind of cache issue?

**Comment by Lee4396** [comment]
> What kind of cache issue?

upload from CS with manifest will cause the server to upload all data in the folder the manifest points to instead of only the ones in the manifest. This issue is observed after we upgrade from 2.4.2 to 2.5.2 and persists even without using cache. 

Another problem is when we upload zip file containing more than 10000 images from local storage, the upload will fail unless we set use_cache to false.
