### ISSUE TITLE
Could someone explain me why after following the steps to install SAM in CVAT the AI tools does not appear in the toolbar? Is it a bug or I have deployed something worng?

### ISSUE THREAD

**Issue by frl93** [opencv/cvat#7037]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Follow the process described in the webpage on install SAM in CVAT with GPU. 
![image](https://github.com/opencv/cvat/assets/148674315/eae3ae4d-23a8-40a9-a80f-d7233fe0ab1a)

2. Check that I have the nuclio function depolyed "ready" for its use by doing "nuctl get functions"
![image](https://github.com/opencv/cvat/assets/148674315/b31421df-99de-4980-8731-99fa8f43f309)

3. Check by doing docker ps, that it is also in the docker desktop properly installed.
![image](https://github.com/opencv/cvat/assets/148674315/18fc02b0-cc57-476f-a1fe-3ff749fbf956)

4. Therefore, I supposed that all the steps have been properly followed and AI tools must apprear in the CVAT tool.

### Expected Behavior

However, when I open the cvat application in localhost:8080 the AI tools option does not appear.
![image](https://github.com/opencv/cvat/assets/148674315/4667793f-a9aa-4db0-9738-d0ab8fe18414)

### Context

If someone can explain me how to solve the issue please let me know. I need the tool for doing segment annotation quicly. Thank you so much for your time .

### Environment

```Markdown
-Docker version docker version (e.g. Docker 17.0.05):
The current version is Docker Desktop (Docker version 24.0.2, build cb74dfc).

-Are you using Docker Swarm or Kubernetes?
No.

-Operating System and version (e.g. Linux, Windows, MacOS):
system:windows 10 pro
Ubuntu 18.04.6 LTS
GIT :git version 2.17.1.windows.1
WSL2

Thank you so much for your time.
```

**Comment by bsekachev** [comment]
You deployed functions, but it looks like you didn't install CVAT with serverless module.

```
docker compose -f docker-compose.yml -f docker-compose.dev.yml -f components/serverless/docker-compose.serverless.yml up -d --build
```

https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/

**Comment by frl93** [comment]
Thak you very much @bsekachev. Your solution allows AI tools on my CVAT application as you can see in the following image.

![image](https://github.com/opencv/cvat/assets/148674315/d6e2b710-3e9a-4d66-8c33-52b38da26195)

However, when I start annotating an error appear and no mask is available as you can see in the image.

![image](https://github.com/opencv/cvat/assets/148674315/7019fa47-7ee4-4a7a-b76e-9dbe641a4b2c)

The error is "Interaction error occurred" and it says that "Request failed with status code 503. "HTTPConnectionPool(host='host.docker.internal', port=62395): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa93e017f40>: Failed to establish a new connection: [Errno 111] Connection refused'))"

**Comment by bsekachev** [comment]
Try to re-deploy the serverless function.

**Comment by frl93** [comment]
Once again, thank you @bsekachev. The error has disappear but still I am not able to annotate properly. 

As you are going to see in the followin images, SAM is able to detect tha appel but it does not label as appel even I put three points on it.

1. Select apple from AI tools

![image](https://github.com/opencv/cvat/assets/148674315/84cfb89c-8332-4b11-a145-b554df4509fb)

2. Put first green bullet in an appel.

![image](https://github.com/opencv/cvat/assets/148674315/6c91f69c-43aa-4ce2-a62c-355169cf982d)

3. Put the second green bullet in the same apple

![image](https://github.com/opencv/cvat/assets/148674315/44945400-4bb7-4a3a-9cb9-9a5841768b6b)

4. However the object annotation does not appear in the right part of the CVAT application.

![image](https://github.com/opencv/cvat/assets/148674315/d5a706c9-8365-4217-8118-a6472a434484)

Do I need to do something else? I have been examining SAM videos and the object annotation appears alone...

**Comment by bsekachev** [comment]
You need to finish drawing process and object will appear. 
Press "Done" button in header or key N on your keyboardd

**Comment by frl93** [comment]
Once again thank you for yout help. It works perfect!!!!
