### ISSUE TITLE
CVAT with SAM experiment a fatal error and all the Dockers dissapeared.

### ISSUE THREAD

**Issue by frl93** [opencv/cvat#7040]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Yesterday I was able to introduce SAM application in CVAT. I have been working on it until a fatal error happened and the laptop has shutdown by itself. When I have shut it on all the dockers are removed with the CVAT application.

I have started to installing once again SAM following the instructions and I was able to arrive until nuctl get funtions step. It retunrs me that no function is installed becuase I do not load them.
![image](https://github.com/opencv/cvat/assets/148674315/f86d0c11-ac31-444c-be57-e56917e7dafe)

However, when I try to load the functions, such as "./serverless/deploy_cpu.sh serverless/openvino/dextr", this error appears.
![image](https://github.com/opencv/cvat/assets/148674315/7e0d3515-e48e-45c1-8bb2-127b9c660c02)

Can somone explain me how to fix this?. Should I remove everythin and start again?

### Environment

```Markdown
-Docker version docker version (e.g. Docker 17.0.05):
The current version is Docker Desktop (Docker version 24.0.2, build cb74dfc).

-Are you using Docker Swarm or Kubernetes?
No.

-Operating System and version (e.g. Linux, Windows, MacOS):
system:windows 10 pro
Ubuntu 18.04.6 LTS
GIT :git version 2.17.1.windows.1
WSL2

Thank you so much for your time.
```

**Comment by frl93** [comment]
Thank you to everybody. I am able to fix the problem, it is because of the restrictions of the Wifi of my company. Be carful with that!

**Comment by bsekachev** [comment]
tar util can't unarchive the file because it is broken.
Probably network issue, try to install later/disable VPN if enabled/connect to another wifi point

**Comment by frl93** [comment]
Hi! Once again @bsekachev,  you are right! Trying in another wifi port makes possible to do the following instance. 

docker compose -f docker-compose.yml -f docker-compose.dev.yml -f components/serverless/docker-compose.serverless.yml up -d --build

However, at the end of the process I get the following error

![image](https://github.com/opencv/cvat/assets/148674315/d5cd00bb-7ddc-4a0e-8ff3-9845fb593326)

And the "AI tool" and the "Models" do not appear. Should I reinstall the SAM serverless function?

![image](https://github.com/opencv/cvat/assets/148674315/2db09b4b-9cfd-45bb-9ba1-7cba9dd3b4b2)

**Comment by bsekachev** [comment]
Please, refer to your previous issue #7037 
There is nothing to say anymore.
