### ISSUE TITLE
Use IAM Roles instead of Access Keys for S3 Storage

### ISSUE THREAD

**Issue by Adalbertobcl** [opencv/cvat#7042]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Hello everyone I noticed that currently the implementation for CVAT is only allowing the use of AK/SK to use S3 buckets. That does present problems when a organization does not allow the usage of such feature, if possible it would be nice to use IAM roles on CVAT instances that are deployed on AWS.

**Comment by bsekachev** [comment]
Hello,

Thanks for contacting us, but we are not going to implement that now.
It might be a feature boosted request from our side, or organizations may implement it on their own and publish open source.
