### ISSUE TITLE
how to restore backup data?

### ISSUE THREAD

**Issue by josh3255** [opencv/cvat#7045]
Thank you for sharing a good project.

While replacing the server equipment, I compressed the old cvat data as it was in the folder.

After replacing the /data/cvat path inside docker-compose.yml with /data/cvat_legacy, the docker compose up -d command did not restore the data.

How do I restore compressed old data to my current CVAT?

architecture:
```
/root
└── /cvat/ (this is cvat projects folder)

/data
└── /cvat/
          └── cvat_data/
          └── cvat_keys/
          └── cvat_db/
          └── cvat_letsencrypt/
          └── cvat_logs/
└── /cvat_legacy/ (this is a backup folder)
          └── cvat_data/
          └── cvat_keys/
          └── cvat_db/
          └── cvat_letsencrypt/
          └── cvat_logs/
```

**Comment by bsekachev** [comment]
https://opencv.github.io/cvat/docs/administration/advanced/backup_guide/
