### ISSUE TITLE
Different class order in project "Constructor" tab and "Raw" 

### ISSUE THREAD

**Issue by VABer-dv** [opencv/cvat#7051]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

CVAT UI shows one classes order in constructor tab, but after "Exporting task dataset" in yolo format "obj.names" file has wrong classes order.
![image](https://github.com/opencv/cvat/assets/15277074/162f7fef-5189-49b7-b945-36b965876f05)
It is important to notice that in raw tab labels ids matches with order in "obj.names", but order of list's dicts matches with constructor tab order:
![image](https://github.com/opencv/cvat/assets/15277074/0ff51c1b-60c7-48f0-939f-8afe3ca32515)

### Expected Behavior

Classes order in  "constructor tab" should be the same as classes order in "obj.names" file after "exporting task dataset" in yolo format 

### Possible Solution

Sort labels in "constructor tab" according ids in the list that presented in "raw tab" (ascending order). It seems that now labels in "constructor tab" are shown according their appearance in the list that presented in "raw tab".

### Context

Also it would be nice if you add UI mechanism to change labels order in project

### Environment

```Markdown
Server version: 2.3
Core version: 7.3.0
Canvas version: 2.16.1
UI version: 1.45.0
```

**Comment by bsekachev** [comment]
> Classes order in "constructor tab" should be the same as classes order in "obj.names" file after "exporting task dataset" in yolo format

That is not true. There is nothing in common with labels editor in the interface and target dataset which you will use to export. 
We can only try to sort it by internal database IDs, which labels have in CVAT. But there is not any correlation with the dataset IDs and desired request will not be satisfied this way.
