### ISSUE TITLE
Ability to export segmentation masks for each class in separate mask file (png)

### ISSUE THREAD

**Issue by rusty-electron** [opencv/cvat#7058]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I am working on a task where I need to segment parts of the human face.  As of now, the only helpful export option is the "segmentation masks 1.0" but in these outputs the masks for multi-class segmentation tasks are aggregated in a single png file with each mask coloured uniquely. I had to write an additional script to separate the masks based on the colour values. This issue is currently not a problem but I have to deal with overlapping masks in many cases. If I run the same script for such files, the information of the background mask is lost, right now I have no solution to deal with this problem. As the layer information for each mask is available in the CVAT UI, it is possible to create an export option to fix this issue.

### Describe the solution you'd like

 It would be helpful to have an export option in cvat where separate masks can be generated for each class. It will solve the problem with overlapping masks.

**Comment by stone100010** [comment]
请将你的需求举个的例子，图片包含如下内容：

输入图片
输出图片

**Comment by zhiltsov-max** [comment]
Hi, please try to use the COCO, CVAT xml, Datumaro formats for export - they all store masks separately for each object in RLE format. Then you can convert each mask into a single separate image. [Here](https://github.com/opencv/cvat/issues/6487#issuecomment-1640097518) you can find conversion samples for CVAT format masks. For COCO and Datumaro you can use [Datumaro](https://github.com/cvat-ai/datumaro) - to install, run `pip install 'git+https://github.com/cvat-ai/datumaro#egg=datumaro[default]'`. You can find examples for working with masks here [[1](https://github.com/cvat-ai/datumaro/blob/develop/tests/test_masks.py), [2](https://github.com/cvat-ai/datumaro/blob/develop/tests/test_coco_format.py#L63), [3](https://github.com/cvat-ai/datumaro/blob/develop/tests/test_datumaro_format.py#L65), [4](https://github.com/cvat-ai/datumaro/blob/develop/datumaro/components/annotation.py#L260-L520), [5](https://github.com/cvat-ai/datumaro/blob/develop/tests/test_image.py)]. Basically, you'll need a script like this:

```python
import datumaro as dm
from datumaro.util.image import save_image

dataset = dm.Dataset.import_from('<dir_path>', 'coco'/'datumaro')
for item in dataset:
  for ann_idx, ann in enumerate(item.annotations):
    if not isinstance(ann, dm.Mask):
      continue
    object_binary_mask = ann.image
    save_image(f'{dataset.data_path}object-masks/{item.id}-mask{ann_idx}.png', 
      object_binary_mask * ann.label, create_dir=True)
```
