### ISSUE TITLE
How to save annotated video?

### ISSUE THREAD

**Issue by hiteshreddy95** [opencv/cvat#706]
Is there any way to save or download the annotated video in cvat?

**Comment by bsekachev** [comment]
@hiteshreddy95 

Answered you on gitter. 
Duplicate here: 

> CVAT doesn't change video in any way.
You cannot download annotated video because there isn't it.
You have only annotation file with all bounding boxes, polygons, etc per frame. You can use it in order to draw anything on the video on your own.

**Comment by nmanovic** [comment]
@hiteshreddy95 , we have multiple download formats. If you really need the feature it is better to implement it as a download format. Thus you will be able to download the result file as a XML file with annotations.

**Comment by Tarangworld** [comment]
Best way is to do a screen recoding..
