### ISSUE TITLE
I found a problem with “CVAT” front-end page

### ISSUE THREAD

**Issue by syyxtl** [opencv/cvat#7062]
I found a problem with “CVAT” front-end page
![image](https://github.com/opencv/cvat/assets/66545456/8dad9edc-f754-4f92-b98d-3b490510d27e)

I upload dataset coco, the box did not match the obj. When i download corresponding job dataset and show it local, the display is normal.

**Comment by bsekachev** [comment]
Hi @syyxtl 
Thank you for the report. 

- Please, fill the issue template and provide the version you are using, steps to reproduce the issue.
- Provide us some minimal set of data to reproduce the bug. 

Thank you.

**Comment by syyxtl** [comment]
> Hi @syyxtl Thank you for the report.
> 
> * Please, fill the issue template and provide the version you are using, steps to reproduce the issue.
> * Provide us some minimal set of data to reproduce the bug.
> 
> Thank you.

[coco.zip](https://github.com/opencv/cvat/files/13174391/coco.zip)
i upload the picture and json to “ https://app.cvat.ai/ ” and find these boxes have some problem;

**Comment by syyxtl** [comment]
> Hi @syyxtl Thank you for the report.
> 
> * Please, fill the issue template and provide the version you are using, steps to reproduce the issue.
> * Provide us some minimal set of data to reproduce the bug.
> 
> Thank you.

@bsekachev 
i upload the picture and json to “ https://app.cvat.ai/ ” and find these boxes have some problem; but it display normal locally
[coco.zip](https://github.com/opencv/cvat/files/13174451/coco.zip)

**Comment by bsekachev** [comment]
@syyxtl 

cv.rectangle expects point1 and point2 as arguments. 
<img width="823" alt="image" src="https://github.com/opencv/cvat/assets/40690378/9099aeb7-0bf8-4680-86ac-1b78a2f476fd">


But ``box = anno['bbox']`` returns xtl, ytl, width, height. 

<img width="539" alt="image" src="https://github.com/opencv/cvat/assets/40690378/fb47e9bb-e5d2-4385-b2ad-8f6c3c68fd60">


So, the problem is with your script. UI shows annotation correctly.

**Comment by syyxtl** [comment]
> @syyxtl
> 
> cv.rectangle expects point1 and point2 as arguments. <img alt="image" width="823" src="https://user-images.githubusercontent.com/40690378/278264104-9099aeb7-0bf8-4680-86ac-1b78a2f476fd.png">
> 
> But `box = anno['bbox']` returns xtl, ytl, width, height.
> 
> <img alt="image" width="539" src="https://user-images.githubusercontent.com/40690378/278263846-fb47e9bb-e5d2-4385-b2ad-8f6c3c68fd60.png">
> So, the problem is with your script. UI shows annotation correctly.

@bsekachev 
thank you, i will check it. 
The reason why I found this issue is because I used the same script(some automatic annotation code) to generate annotations. The first batch of data displayed normally, but the second batch had a real problem.

i will check my script.
thank you for you answer again!
