### ISSUE TITLE
Is it a possible to export annotated images?

### ISSUE THREAD

**Issue by XinyueZ** [opencv/cvat#7065]
Hey guys,

my question is not about to export annotations.

my question is about how to export annotated images, ie. a zip containing images with annotated bounding-boxes.

thank you.

**Comment by bsekachev** [comment]
Hello, it is possible.

<img width="392" alt="image" src="https://github.com/opencv/cvat/assets/40690378/782e0b93-08b8-4f19-990f-7656aec92d79">

**Comment by XinyueZ** [comment]
but, the images will not be drawn with the bboxes, right?

**Comment by bsekachev** [comment]
oh, if you mean that, no, they will not be drawn with the bboxes. 
there is not such annotation format.
