### ISSUE TITLE
I cant download annotations with single channel

### ISSUE THREAD

**Issue by DanMenCas** [opencv/cvat#7066]
Hi,

Before all, this an excelent tool is very useful, but i have a problem, i already did my annotations but when i try to download in every format, i cant find the annotation with single channel (not RGB), **how i can download with a single channel?**

Thanks!

**Comment by zhiltsov-max** [comment]
Hi. I suppose you're trying to download segmentation masks in the indexed format. Please check if the Cityscapes format masks suit your needs. You can find documentation [here](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-cityscapes/).

**Comment by DanMenCas** [comment]
Thanks so much, this works very well.
