### ISSUE TITLE
Is there an attribute added on the rectangle indicating the direction, i.e., whether it's facing towards x or y?

### ISSUE THREAD

**Issue by pluto1104** [opencv/cvat#7069]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I would like the rectangle to have a direction when annotating. For example, when annotating cars, I want the arrow direction to be consistent with the car head.

### Describe the solution you'd like

Can there be an arrow indicating the direction, similar to that of a polygon?

**Comment by bsekachev** [comment]
I  would suggest you to create an attribute with possible values and annotate it together with rectangle coordinates.
