### ISSUE TITLE
404 Page not found on CVAT server link

### ISSUE THREAD

**Issue by thestammerer12** [opencv/cvat#7072]
I run the command "docker compose down"
after it stopped everything I run "docker compose up -d"
it started everything, but i'm getting this error:

2023-10-25 06:42:05,049 DEBG 'uvicorn-0' stdout output:
 INFO: [172.19.0.2](https://172.19.0.2/):0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

Also when i'm trying to open my cvat it says "404 page not found"

I'm using CVAT on my personal server.

**Comment by zhiltsov-max** [comment]
Hi, could you specify which error you're worried about? The `INFO: 172.19.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified` line is not an error, it's a regular log message.

**Comment by thestammerer12** [comment]
![image](https://github.com/opencv/cvat/assets/149149391/98a4c5b6-f6f4-4f7a-b39c-29baa9ee7817)
MY cvat is not working it says 404 page not found. please refer to the image attached. this error occured after i run docker up and down command.

**Comment by bsekachev** [comment]
@thestammerer12 

Please, fill the issue template properly, providing all the details, logs and steps to reproduce (including changes your made in configuration files). 
Unfortunately  it is not possible to understand the reason from the screenshot.

**Comment by azhavoro** [comment]
There are no `up` and `down` commands for docker, you probably mean `docker compose`.
Seems you just forgot to export the CVAT_HOST environment variable before the `up` command.
If this does not help, please provide the exact steps on how we can reproduce the problem.

**Comment by blueclowd** [comment]
Got the same log using the latest repository and use `docker compose up -d` to start the container
Log:
`2023-10-25 06:42:05,049 DEBG 'uvicorn-0' stdout output:
INFO: [172.19.0.2](https://172.19.0.2/):0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified`

**Comment by ywangwxd** [comment]
I hope this is helpful for someone having the same issue.
When exporting CVAT_HOST, try to use the hostname instead of the ip address of the host.
