### ISSUE TITLE
Unable to access cvat running on localhost:8080 via ngrok tunnel

### ISSUE THREAD

**Issue by rickearthc137** [opencv/cvat#7075]
CVAT is running on localhost:8080. 
![image](https://github.com/opencv/cvat/assets/135340559/1d563ff0-d789-4865-ac20-e559a535f2fb)
Created ngrok tunnel for localhost:8080
![image](https://github.com/opencv/cvat/assets/135340559/d79926e0-ea4a-474d-8dbb-285aac838aca)

However, despite the ngrok tunnel being in place, I'm encountering a 404 error when attempting to access CVAT through the ngrok tunnel, as depicted in the image above. Strangely, when I tried this with other server on localhost:8080, it worked. 
Are there any additional configurations that I have to make so that I can access it CVAT via ngrok tunnel?

**Comment by bsekachev** [comment]
Hi, please try to refer to other issues like #1011 or #3982
We do not have ngrok out of the box support.
