### ISSUE TITLE
Unable to upload mask-based annotation

### ISSUE THREAD

**Issue by Lee4396** [opencv/cvat#7076]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [x] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

cvat version: 2.7.6 (upgraded from v2.5.1)

create a labelling job and label one image with mask painter, then save and export the annotation.

Upload the downloaded annotation to the same project

### Expected Behavior

expect it to upload like other types of annotations but instead got the following error (for both CamVid 1.0 and Cityscapes 1.0 format):
![image](https://github.com/opencv/cvat/assets/43795612/416f2800-edda-49f9-a3d9-5c6b238a5a82)

### Environment

AWS EC2 deployment with EFS, RDS and ElasticCache as data blocks

**Comment by Lee4396** [comment]
Am I tried the version 2.4.1 and it worked, seems like a new issue introduced in one of the version update

**Comment by Lee4396** [comment]
and when I upload the same annotation again I always get the following error:
![image](https://github.com/opencv/cvat/assets/43795612/b404bf06-8c22-41a6-a0bd-fec19711679a)

**Comment by Lee4396** [comment]
I have found out this is a bug from v2.5.1 but inherited to v2.7.6. Is there a potential fix on it?

**Comment by bsekachev** [comment]
I was not able to reproduce according to provided steps on CamVid 1.0. Please share with us a backed up task with play data which we could restore and try.
You can also share a task from app.cvat.ai where the problem could be reproduced.

**Comment by Lee4396** [comment]
> I was not able to reproduce according to provided steps on CamVid 1.0. Please share with us a backed up task with play data which we could restore and try. You can also share a task from app.cvat.ai where the problem could be reproduced.

Hi, I found out the cause I think, so I created 2 cvat server pointing to the same DB structures in hope for increasing the performance, but it seems such error happens if I have more than one server running at the same time. is there any hidden cache shared between different servers besides those three docker volumes or some other issues causing the issue?

The error cannot be reproduced on the online version.

**Comment by Lee4396** [comment]
I have found a work-around on this problem, so in my load balancer I added stickiness_cookie_duration to direct the traffic to a fixed server in a certain amount of time. And this fixed the problem. I am guessing there are some delay in the shared volumes between servers or some hidden cache for individual server.
