### ISSUE TITLE
Segment Anything (SAM) time response varies a lot

### ISSUE THREAD

**Issue by CedricLienhard** [opencv/cvat#7078]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

- Click on a new image
- Select the SAM model
- Click on the first object to segment

### Expected Behavior

Time for first segmentation in 2 images should be approximately the same all the time

### Context

I deployed SAM (with docker) with GPU support and I noticed that the time to get the first segmentation of an object in an image is highly superior compared to the segmentation of further objects in the same image. My first assumption is that this is a normal behavior and that the model needs some kind of "initialization" for the first segmentation in a new image. Is that a correct assumption ?

Anyway this is not so annoying as long as this first initialization doesn't take too long. Which is the case sometimes and sometimes not. To give an example, from one annotation session to the next, it can take approx. 5 seconds for the first segmentation (which is okay since the next annotations on the same image are almost immediate) and then up to 30s, which is kind of annoying.

Is there a reason for that ? Did someone experience that as well ? 

### Environment

```Markdown
- Linux Ubuntu
- Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
```

**Comment by bsekachev** [comment]
It is a normal behavior. If you are interested in details, please read about how Segment Anything works.

**Comment by CedricLienhard** [comment]
Thanks for the quick feedback. From what I understand, it could be related to the generation of a one-time embedding of the image, is that correct ?

Also, my assumption is that by selecting a smaller model, such as 'ViT-B', it would then be faster. Wouldn't it be great to be able to select any model to use in CVAT ?

**Comment by bsekachev** [comment]
> is that correct? 

Yes, it is correct

> smaller model, such as 'ViT-B', it would then be faster.

Yes, ViT-B is faster, but less quality. 

> Wouldn't it be great to be able to select any model to use in CVAT ?

Internally we do not need this. And we just provided a way how SAM could work in CVAT. If somebody wants to contribute another model, they are welcome to do it. 

FYI: But in general nuclio reserves GPU/RAM memory for each model when it is deployed, even if not used. And SAM is quite powerful model requiring a lot of memory, so, it would not be a good solution just to deploy all and select in the interface which one user wants to use.
