### ISSUE TITLE
Instances order when exporting masks as segmentation format

### ISSUE THREAD

**Issue by lelouedec** [opencv/cvat#7080]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Having multiple masks per image, and keeping their order consistent across frames (eg. first one is top most one, second one bottom most one in consecutive frames). 

When exporting as segmentation mask, the order of instances (green or red coloured) changes randomly. 

### Expected Behavior

The segmentation mask should be consistent with order of the mask instances in the annotation tool once exported (mask 0 always top most object, mask 1 always bottom most object).

**Comment by bsekachev** [comment]
Object index is not a marker of position on a frame from "far" to "near". 
Please, set correct z layer properties for objects. 

Some discussion can be found here #6686

**Comment by bsekachev** [comment]
https://opencv.github.io/cvat/docs/manual/basics/workspace/#adding-layers-and-z-axis-slider
Plus to background/foreground buttons in context menu: https://opencv.github.io/cvat/docs/manual/basics/objects-sidebar/#objects-properties

**Comment by lelouedec** [comment]
Perhaps I poorly worded my question. I didnt mean order from far to near, rather I would like to have a way to specify for consecutive frames which one of the masked instance should be exported as instance ZERO and instance ONE (when to instances of the same class). As right now when I am exporting the annotations, no matter what format the number for an instance seems random.

**Comment by bsekachev** [comment]
Please, provide any examples with screenshots 
What do you mean  when speaking "instance number"?

**Comment by lelouedec** [comment]
![image](https://github.com/opencv/cvat/assets/16105109/dd1ee280-c20b-4e87-a731-b5131b70f25b)
![image](https://github.com/opencv/cvat/assets/16105109/55bc3d65-3325-46c5-a62a-e450aacf7982)
![Screenshot 2023-10-30 at 15 05 27](https://github.com/opencv/cvat/assets/16105109/273d0884-d439-4b1a-a464-b82867f4a29c)


As you can see on the pictures, we try to keep consistent order and even tried to play with layers, but the masks keep getting us random order for the instances (last screenshot).

**Comment by bsekachev** [comment]
Okay, now I see.
But I am not sure that instance segmentation assumes the way to persist objects color between different frame.

@zhiltsov-max Could you please comment on that?

**Comment by zhiltsov-max** [comment]
CVAT doesn't have a way to control instance ids in segmentation now. Please consider adding a custom label attribute instead. Then, you can export in some format that supports custom attributes, such as CVAT, Datumaro, COCO, Pascal VOC.
