### ISSUE TITLE
Can't Delete Task on v2.8.0

### ISSUE THREAD

**Issue by valGavin** [opencv/cvat#7082]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Delete Task as usual

### Expected Behavior

Task should be deleted

### Possible Solution

Something related to task deletion process

### Context

![Error message](https://github.com/opencv/cvat/assets/54397015/c699ddb4-0bf1-49ce-b051-905eb6d999d9)
![cvat_server log](https://github.com/opencv/cvat/assets/54397015/8b075d31-80f7-4e4f-9c72-39bd740f275e)
![cvat_db log](https://github.com/opencv/cvat/assets/54397015/2a224ab0-46f5-4cc2-9d46-7992f4565c25)

Seems like `dataset_repo_gitdata` table is not exist anymore.

### Environment

- CVAT release v2.8.0
- Docker Enginer 24.0.6
- Ubuntu 22.04.3

**Comment by bsekachev** [comment]
Be sure you restarted the server and applied all the migrations properly.
This table and related functionality have been removed

**Comment by valGavin** [comment]
@bsekachev Thank you for your response. Strangely, I have to do the migration manually from inside the container. Perhaps I missed a step or something, did I?
