### ISSUE TITLE
Parameter to save images for task dataset in REST API

### ISSUE THREAD

**Issue by realtimshady1** [opencv/cvat#7083]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I want to have the option to save images when I export task datasets using the CVAT REST API

### Describe the solution you'd like

A parameter 'save_images' for get request to 'api/tasks/{id}/annotations' that accepts either 'true' or 'false'
<img width="706" alt="image" src="https://github.com/opencv/cvat/assets/20720732/8947574d-0e87-4ba0-bfe6-6939fcb661dd">

Just like in the UI

<img width="368" alt="image" src="https://github.com/opencv/cvat/assets/20720732/71605129-38cb-43d2-bf3e-5bd81ecd5363">

**Comment by zhiltsov-max** [comment]
Hi, this is done in 2 separate endpoints instead - please look for `GET /api/{project|task|job}/dataset/`. All have the same usage principles, you just choose `.../dataset` or `.../annotations`.
