### ISSUE TITLE
How to get task_name with job_id

### ISSUE THREAD

**Issue by yaeji98** [opencv/cvat#7088]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. I added a new annotation format support.
``` 
@exporter(name='MyFormat', ext='ZIP', version='1.0')
    def _export(dst_file, temp_dir, instance_data, save_images=False):
       instance_meta = instance_data.meta [instance_data.META_FIELD] 
       job id = instance_meta ['id']

2. i want to get task_name with job_id

thank you :)

### Expected Behavior

 i want to get task_name with job_id

### Possible Solution

_No response_

### Context

_No response_

### Environment

_No response_

**Comment by zhiltsov-max** [comment]
Hi, please check the documentation [here](https://opencv.github.io/cvat/docs/contributing/new-annotation-format/) and check other format implementations for examples. There is the `instance_data` parameter, which can be [`ProjectData`](https://github.com/opencv/cvat/blob/623476e2596044fcdad7bd52507387e9254e8f69/cvat/apps/dataset_manager/bindings.py#L1007), [`TaskData`](https://github.com/opencv/cvat/blob/623476e2596044fcdad7bd52507387e9254e8f69/cvat/apps/dataset_manager/bindings.py#L760) or [`JobData`](https://github.com/opencv/cvat/blob/623476e2596044fcdad7bd52507387e9254e8f69/cvat/apps/dataset_manager/bindings.py#L657) - please check the class fields to get the required information.
