### ISSUE TITLE
AI tool button missing

### ISSUE THREAD

**Issue by Lee4396** [opencv/cvat#7089]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. download the nuclio cli following https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
2. start the nuclio dashboard with 'docker run -p 8070:8070 -v /var/run/docker.sock:/var/run/docker.sock --name nuclio-dashboard quay.io/nuclio/dashboard:1.11.24-amd64'
3. start the containers with customized docker-compose file(removing the load balancer and use aws alb) with 'docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d --build'

### Expected Behavior

I can see model is running in the background and the model tab shows up in the front end but it is empty. Following the conversation of #6864, I have updated my cvat version to v2.7.6 and am facing the same error. Screenshots are documented in the mentioned issue

### Possible Solution

similar issue was solved in #7037 but doesnt work in my case

**Comment by bsekachev** [comment]
Sorry, we can't help with customized installations.

**Comment by lucidBrot** [comment]
I had a similar issue and the solution was to force a reload in the browser (CTRL+SHIFT+R) and then navigate to my task anew. Now the magic wand was there.
