### ISSUE TITLE
Issue with the development environment after updating the develop branch

### ISSUE THREAD

**Issue by pauchai** [opencv/cvat#7091]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I cloned the repository on the develop branch.
I updated to the latest version using git pull.
I set up the OPA server in Docker , cva-ui, redis and other  as described in the following guide: 
https://opencv.github.io/cvat/docs/contributing/development-environment/
Suddenly, I encountered issues with my development environment.

### Expected Behavior

I expect my development environment to work correctly after the update.
But after updating in the develop branch, I encountered ERROR health-check: unknown error: 500 Server Error: Internal Server Error for url: http://localhost:8181/health?bundles.
This includes : 
[2023-11-03 10:17:18,582] ERROR health-check: unknown error: 500 Server Error: Internal Server Error for url: http://localhost:8181/health?bundles
Traceback (most recent call last):
  File "/home/ubuntu/cvat/cvat/apps/health/backends.py", line 25, in check_status
    response.raise_for_status()
  File "/home/ubuntu/cvat/.env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8181/health?bundles

### Environment

```Markdown
-- Windows 10 WSL2 (Ubuntu 22.04.2 LTS)
-- Docker Desctop v4.22.1
```

**Comment by pauchai** [comment]
![2023-11-03_16-32-35](https://github.com/opencv/cvat/assets/91274804/34d8461d-cacf-4060-92d1-7aa466caedd4)

**Comment by bsekachev** [comment]
Check your ``cvat_opa_debug`` container up and running correctly.
Check its logs with ``docker logs cvat_opa_debug``

**Comment by pauchai** [comment]
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://host.docker.internal:7000/api/auth/rules\": dial tcp 192.168.65.254:7000: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-11-03T14:03:28Z"}

**Comment by pauchai** [comment]
I dont know if git pull changed configuration
Where can i find this configuration . cvat/cvat/settings?

**Comment by pauchai** [comment]
hear is my opa docker run
 docker run -d --rm --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.45.0-rootless  run --server --set=decision_logs.console=true --set=services.cvat.url=http://host.docker.internal:7000  --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules

**Comment by pauchai** [comment]
strange. it start working.
close this issue. thank you.

**Comment by bsekachev** [comment]
Very good. For somebody having the same issue.. If you experiencing the same problem with host.docker.internal, you may try to switch container to host network and specify localhost

```
docker run -d --rm --network=host --name cvat_opa_debug -p 8181:8181 openpolicyagent/opa:0.45.0-rootless  run --server --set=decision_logs.console=true --set=services.cvat.url=http://localhost:7000  --set=bundles.cvat.service=cvat --set=bundles.cvat.resource=/api/auth/rules
```
