### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by santhosh186** [opencv/cvat#7092]
**Actions before raising this **

- [ I searched the existing issues and did not find anything similar.] 

**Steps to Reproduce**

Running CVAT 2.8.0 version in Azure VM on Ubuntu 20.04.6 LTS. Following error was produced in the middle of Automatic Annotation run. I'm running custom Yolov8 model deployed in AKS for inference.

<img width="1784" alt="Screenshot 2023-11-03 at 1 21 30 PM" src="https://github.com/opencv/cvat/assets/131335699/de75a498-f301-41cf-965c-76960f08f3ac">

When I inspect http://host.docker.internal:32773/ which is docker image of Yolov8 inference sometimes I get either of the two errors.

- Exception caught in handler {"exc": "('The API request to the model failed', 'Request got 502 error: {\\n  \"message\":\"An invalid response was received from the upstream server\"\\n}')", "traceback": "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 118, in serve_requests\n    await self._handle_event(event)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 312, in _handle_event\n    entrypoint_output = self._entrypoint(self._context, event)\n  File \"/opt/nuclio/main.py\", line 32, in infer\n    results = context.user_data.model.infer(image_bytes, threshold)\n  File \"/opt/nuclio/model_handler.py\", line 23, in infer\n    \"Request got {} error: {}\".format(response.status_code, response.text),\nException: ('The API request to the model failed', 'Request got 502 error: {\\n  \"message\":\"An invalid response was received from the upstream server\"\\n}')\n", "worker_id": "0"}
- {
   "exc":"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",
   "traceback":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 677, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 426, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 421, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1356, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 307, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/requests/adapters.py\", line 449, in send\n    timeout=timeout\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 725, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 403, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py\", line 734, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 677, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 426, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 421, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1356, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 307, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 118, in serve_requests\n    await self._handle_event(event)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 312, in _handle_event\n    entrypoint_output = self._entrypoint(self._context, event)\n  File \"/opt/nuclio/main.py\", line 32, in infer\n    results = context.user_data.model.infer(image_bytes, threshold)\n  File \"/opt/nuclio/model_handler.py\", line 17, in infer\n    url=url, verify=False, data=data, files=files, timeout=500\n  File \"/usr/local/lib/python3.6/dist-packages/requests/api.py\", line 119, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/requests/sessions.py\", line 530, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/requests/sessions.py\", line 643, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/requests/adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\nrequests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
   "worker_id":"0"
}

**Comment by bsekachev** [comment]
There is not a way we can help with custom models.

Regarding error 2:

It looks like you are running out of timeout when working with this model. Default timeout is 30s defined in nuclio yaml file. 

Regarding error 1:

Probably your model refers to some Internet resources during inference and this resource returns 502 code.
