### ISSUE TITLE
could not save annotations error: request failed with status code 400. [label_id 1474045 is invalid].

### ISSUE THREAD

**Issue by LCS0822** [opencv/cvat#7099]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [x] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I pressed save after I finished labeling video in CVAT, but I can't save with the following error message. Please tell me how to fix it.

Could not save annotations

Error: Request failed with status code 400. ["label_id 1474045 is invalid"].

![image](https://github.com/opencv/cvat/assets/144994634/6b0a0b1e-ca94-4217-af25-ab9e1ad97a52)

**Comment by bsekachev** [comment]
It looks like you've removed label and continued to annotate in already opened task where the label still exists locally.
Now back-end does not know about the label and throws the error. 

You need to refresh tab, but unsaved annotations will be lost. In fact, it is already lost if you open the job in another tab, you will see it.

**Comment by LCS0822** [comment]
> It looks like you've removed label and continued to annotate in already opened task where the label still exists locally. Now back-end does not know about the label and throws the error.
> 
> You need to refresh tab, but unsaved annotations will be lost. In fact, it is already lost if you open the job in another tab, you will see it.

Hi, Thank you very much for your reply.
As I looked into it a little more, I think my team member transferred the task I am working on to a project while I was labeling the video. In this process, the labels were moved to the label of the project, causing a collision, so is there any way to recover it?

**Comment by bsekachev** [comment]
When you move a task to a project, existing annotations is kept. But nevertheless need to refresh tabs with annotation view, before continuing annotation.
In your case only objects, annotated between moving and first save are lost. There is no formal way to recover them
