### ISSUE TITLE
How to deploy CVAT using k8s??

### ISSUE THREAD

**Issue by JeongHanJun** [opencv/cvat#7105]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hi, I'd like to deploy data labelling to the outside so that I can access and work from the outside IP using CVAT.
To do this, we checked the guidelines for external distribution through Minikube provided by CVAT.
https://opencv.github.io/cvat/docs/administration/advanced/k8s_deployment_with_helm/

However, if you follow the instructions above, you will get an ImagePullBackOff/ErImagePull error.
$ helm upgrade -n cvat cvat -i --create-namespace ./helm-chart -f ./helm-chart/values.yaml -f ./helm-chart/cvat.values.yaml
I tried to deploy through Minikube by executing the above command.

After that, I wanted to check the distribution results using the command below.
$ kubectl get all -n cvat
The output results for the above command are below.

NAME                                                        		READY   STATUS             RESTARTS   AGE
pod/cvat-backend-initializer-r1-sl9hf                       		0/1     ImagePullBackOff   0              107s
pod/cvat-backend-server-6d7cff587-p8t8h                     		0/1     ErrImagePull         0              107s
pod/cvat-backend-utils-5d7f64c865-6j6fw                     		0/1     ErrImagePull         0              107s
pod/cvat-backend-worker-analyticsreports-589b9fdd6c-ql8mv   	0/1     ImagePullBackOff   0              107s
pod/cvat-backend-worker-annotation-845f9c79f6-4rbh5         	0/1     ImagePullBackOff   0              106s
pod/cvat-backend-worker-export-59b46bcb74-rlg9g             	0/1     ErrImagePull         0              107s
pod/cvat-backend-worker-export-59b46bcb74-vw6tk             	0/1     ImagePullBackOff   0              107s
pod/cvat-backend-worker-import-f86974576-2hj8j              	0/1     ImagePullBackOff   0              106s
pod/cvat-backend-worker-import-f86974576-tgwgt              	0/1     ImagePullBackOff   0              106s
pod/cvat-backend-worker-qualityreports-77549759b9-jjfxc     	0/1     ErrImagePull         0              107s
pod/cvat-backend-worker-webhooks-c756f6d56-7m6nk            	0/1     ErrImagePull         0              107s
pod/cvat-frontend-6c6bb88fcc-5s9jl                          		1/1     Running              0              107s
pod/cvat-keydb-0                                            		1/1     Running              0              107s
pod/cvat-opa-67bd5b59d6-pxjkk                               		1/1     Running              0              107s
pod/cvat-postgresql-0                                       		1/1     Running              0              107s
pod/cvat-traefik-bc4dd6888-lg9hk                            		1/1     Running              0              107s

NAME                            	TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                      AGE
service/cvat-backend-service  ClusterIP      10.98.104.103    <none>         8080/TCP                     107s
service/cvat-frontend-service  ClusterIP      10.103.134.103   <none>         80/TCP                       107s
service/cvat-keydb               ClusterIP      10.100.195.100   <none>         6379/TCP,9121/TCP            107s
service/cvat-keydb-headless   ClusterIP      None             <none>         6379/TCP                     107s
service/cvat-postgresql         ClusterIP      10.110.148.87    <none>         5432/TCP                     107s
service/cvat-postgresql-hl      ClusterIP      None             <none>         5432/TCP                     107s
service/cvat-traefik            LoadBalancer   10.101.140.74    192.168.49.2   80:32000/TCP,443:30837/TCP   107s
service/opa                     ClusterIP      10.110.170.122   <none>         8181/TCP                     107s

Could you tell me in detail the difference between values.yaml and cvat.value.yaml pie??
What parts I did wrong and how do I fix it so that external IP can access and use CVAT??
There are many things I don't know very well, so I'd be very grateful if you could tell me in detail!

The above error was due to the lack of docker images, and the image was imported after docker composite up, as if installing in Local. Since then, the above error has been resolved, and now it seems to be fine at first glance.
The following is my current situation.

$ kubectl get all -n cvat
NAME                                                        READY   STATUS      RESTARTS   AGE
pod/cvat-backend-initializer-r3-cqc8s                       0/1     Completed   0          27s
pod/cvat-backend-server-6d7cff587-czjff                     1/1     Running     0          23h
pod/cvat-backend-utils-5d7f64c865-fq9jw                     1/1     Running     0          23h
pod/cvat-backend-worker-analyticsreports-589b9fdd6c-z9d4g   1/1     Running     0          23h
pod/cvat-backend-worker-annotation-845f9c79f6-xh67n         1/1     Running     0          23h
pod/cvat-backend-worker-export-59b46bcb74-8bczr             1/1     Running     0          23h
pod/cvat-backend-worker-export-59b46bcb74-s8wwn             1/1     Running     0          23h
pod/cvat-backend-worker-import-f86974576-6qvdl              1/1     Running     0          23h
pod/cvat-backend-worker-import-f86974576-sg98n              1/1     Running     0          23h
pod/cvat-backend-worker-qualityreports-77549759b9-ftthb     1/1     Running     0          23h
pod/cvat-backend-worker-webhooks-c756f6d56-wl76b            1/1     Running     0          23h
pod/cvat-frontend-6c6bb88fcc-wtv8s                          1/1     Running     0          23h
pod/cvat-keydb-0                                            1/1     Running     0          23h
pod/cvat-opa-67bd5b59d6-bqj7l                               1/1     Running     0          23h
pod/cvat-postgresql-0                                       1/1     Running     0          23h
pod/cvat-traefik-bc4dd6888-mvzn5                            1/1     Running     0          23h

NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                      AGE
service/cvat-backend-service    ClusterIP      10.97.28.164     <none>         8080/TCP                     23h
service/cvat-frontend-service   ClusterIP      10.102.140.143   <none>         80/TCP                       23h
service/cvat-keydb              ClusterIP      10.106.102.176   <none>         6379/TCP,9121/TCP            23h
service/cvat-keydb-headless     ClusterIP      None             <none>         6379/TCP                     23h
service/cvat-postgresql         ClusterIP      10.111.144.182   <none>         5432/TCP                     23h
service/cvat-postgresql-hl      ClusterIP      None             <none>         5432/TCP                     23h
service/cvat-traefik            LoadBalancer   10.106.17.211    192.168.58.2   80:32675/TCP,443:31705/TCP   23h
service/opa                     ClusterIP      10.107.201.196   <none>         8181/TCP                     23h

NAME                                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cvat-backend-server                    1/1     1            1           23h
deployment.apps/cvat-backend-utils                     1/1     1            1           23h
deployment.apps/cvat-backend-worker-analyticsreports   1/1     1            1           23h
deployment.apps/cvat-backend-worker-annotation         1/1     1            1           23h
deployment.apps/cvat-backend-worker-export             2/2     2            2           23h
deployment.apps/cvat-backend-worker-import             2/2     2            2           23h
deployment.apps/cvat-backend-worker-qualityreports     1/1     1            1           23h
deployment.apps/cvat-backend-worker-webhooks           1/1     1            1           23h
deployment.apps/cvat-frontend                          1/1     1            1           23h
deployment.apps/cvat-opa                               1/1     1            1           23h
deployment.apps/cvat-traefik                           1/1     1            1           23h

NAME                                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/cvat-backend-server-6d7cff587                     1         1         1       23h
replicaset.apps/cvat-backend-utils-5d7f64c865                     1         1         1       23h
replicaset.apps/cvat-backend-worker-analyticsreports-589b9fdd6c   1         1         1       23h
replicaset.apps/cvat-backend-worker-annotation-845f9c79f6         1         1         1       23h
replicaset.apps/cvat-backend-worker-export-59b46bcb74             2         2         2       23h
replicaset.apps/cvat-backend-worker-import-f86974576              2         2         2       23h
replicaset.apps/cvat-backend-worker-qualityreports-77549759b9     1         1         1       23h
replicaset.apps/cvat-backend-worker-webhooks-c756f6d56            1         1         1       23h
replicaset.apps/cvat-frontend-6c6bb88fcc                          1         1         1       23h
replicaset.apps/cvat-opa-67bd5b59d6                               1         1         1       23h
replicaset.apps/cvat-traefik-bc4dd6888                            1         1         1       23h

NAME                               READY   AGE
statefulset.apps/cvat-keydb        1/1     23h
statefulset.apps/cvat-postgresql   1/1     23h

NAME                                    COMPLETIONS   DURATION   AGE
job.batch/cvat-backend-initializer-r3   1/1           17s        27s

POD and service seem to be working normally.
Here, 192.168.58.2 is the IP output when $minikube ip is executed.
I think the host name is basically "cvat.local" given.
My question is as follows.
Is it right that my PODs and services have gone up well now??
If so, is the CVAT UI window not output when "http://cvat.local" or "http://cvat.local:80" is entered in the browser??
How can I see the CVAT UI window, and later give permission to each account??
Is this right for CVAT deployment??
If anyone has ever deployed CVAT to the outside world, it would be greatly appreciated if you could let me know about this!

### Environment

```Markdown
<Versions>
Ubuntu : 20.04
Docker Engine : 24.0.7
Kubectl Client : 1.28.2
Kubectl Server : 1.27.4
Kubeadm : 1.28.2
```

**Comment by azhavoro** [comment]
Please follow the documentation, your questions are well documented
[Please read the documenta](https://opencv.github.io/cvat/docs/administration/advanced/k8s_deployment_with_helm/#optional-steps)
https://helm.sh/docs/chart_template_guide/values_files/
https://opencv.github.io/cvat/docs/administration/advanced/k8s_deployment_with_helm/#how-to-create-superuser

**Comment by JeongHanJun** [comment]
![image](https://github.com/opencv/cvat/assets/54197360/90cc72d1-b85c-4f57-b3da-8c78c52c3a99)
Does anyone know a solution to this situation??

I am currently
https://opencv.github.io/cvat/docs/administration/advanced/k8s_deployment_with_helm/#how-to-create-superuser
We are doing the above.

If anyone has solved this error while deploying and creating a superuser using minikube and helm, I would greatly appreciate it if you could let me know how to solve it.
