### ISSUE TITLE
How CVAT synchronize annotations across modalities data like text, video, audio

### ISSUE THREAD

**Issue by JennaWu** [opencv/cvat#7110]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

**Comment by bsekachev** [comment]
Currently it only supports CV data, so, audio is not an option for CVAT. 
Video splitted to frames with precise positioning (frame based, not timestamp based). 
Text on images can be annotated in a regular way as any others objects.
