### ISSUE TITLE
Task status does not change to done on the Tasks page

### ISSUE THREAD

**Issue by arvfilippov** [opencv/cvat#7112]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Сhange the job stage to acceptance.
2. Go to the Tasks page 
![acceptance](https://github.com/opencv/cvat/assets/45945021/ed5bdcdd-74d5-46d1-b195-0b5a16c9723b)

### Expected Behavior

On the Tasks page, the progress of this task will change (progress bar will turn green).

**Comment by Marishka17** [comment]
As far as I remember, job status depends not only on the job `stage` but also on the job `state`. The status of a job will be changed to completed only when a stage becomes `acceptance` and the state becomes `completed` (this is what happens when you click finish the job).

**Comment by bsekachev** [comment]
Yes, that is not a bug. 

<img width="559" alt="image" src="https://github.com/opencv/cvat/assets/40690378/23f5c3dc-6e09-4630-96df-7f0c4343e49d">
