### ISSUE TITLE
Further images to existing task and upload only some annotations to a task

### ISSUE THREAD

**Issue by PatrickKiefer93** [opencv/cvat#7114]
Maybe I am wrong, but I am not able to add further images to a existing task. Is this true? Or am I just to stupid?

Secondly, I have a system which creates for each "inspection" one image and the coco annotion from the already existing prediction.
As already mentioned at the first point. I am not able to add this image to an existing task, but also I am not able to add the annotation of only one image to a batch of images. It deletes all existing annotations of the whole batch. 
Further, if i try to upload for example 5 annotations (with 5 separate COCO .json files) to the task with this 5 images, it only adds one annotation.
Is it my fault or is this really not possible?

**Comment by bsekachev** [comment]
Adding new images to a task is not available #3072 #95 #1278

**Comment by valentin-fngr** [comment]
> Adding new images to a task is not available #3072 #95 #1278

even though everybody is asking for this feature ?
