### ISSUE TITLE
Is it possible to export the annotations done with SAM in YOLO format?

### ISSUE THREAD

**Issue by frl93** [opencv/cvat#7115]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. I have installed SAM in CVAT and annotate the images as can it be seen in the following picture as an example.

![image](https://github.com/opencv/cvat/assets/148674315/9201a3f3-78d6-43b2-8968-81c73e46e3fa)

2. After annotating all the images, I want to obtain the bounding box produced by the mask obtained by the SAM AI Tool. 

![image](https://github.com/opencv/cvat/assets/148674315/f551846b-61fb-4276-9806-2490d132f2bd)

3. Therefore, we have decided to export the annotations of the task in YOLO format.

![image](https://github.com/opencv/cvat/assets/148674315/3cdf7d06-6f07-454a-bb35-75daeb9d9f0a)

### Expected Behavior

It was expected that the downloaded .txt files would contain, for each image, the corresponding bounding boxes of the annotated objects. However, all the .txt file associated for the images are empty. 

In the following picture, it can be seen that all .txt files are empty. The selected .txt file is the one that should contain the bounding box information for the tram, as presented in the "Steps to Reproduce" section.

![image](https://github.com/opencv/cvat/assets/148674315/163b2941-06ab-4fd5-8985-dcbd02ccf879)

### Possible Solution

I have been reading about this issue and may be the problem  is that SAM does not allow to export the annotations directly in YOLO format. Therefore, should I need to use an intermediate code to get the bounding boxes of the mask?

**Comment by bsekachev** [comment]
@frl93 

SAM produces masks, polygons. YOLO does not support masks/polygons => files are empty. 
There is not implicit cast when exporting annotations. So, right now it is not possible to get YOLO annotations from SAM out of the box. 

But you can export another format and convert it to YOLO with a script. There is a patch to support bounding boxes output from SAM in CVAT, but I didn't have time yet to finish it #6665

**Comment by frl93** [comment]
Hi @bsekachev!

After reading about the issue, I have seen that the only way to obtain the bounding boxes is to follow your advice. Thus, I have to get the mask obtained through SAM and then, use and script to obtain the bouding box. 

However, this proceses has a big trouble that I don`t know how to solve it. I am going to present the issue through three different examples and may be somebody can help me.

Example 1: I have just a mask in the picture. Therefore, I can Identify the contour and get the bounding box for that element
![image](https://github.com/opencv/cvat/assets/148674315/08ebeaf7-c8b6-4fb7-a82b-9a2b216f775e)

Example 2: I have different masks in the picture which are from different categories. Thanks to the colours and the well difined contour of each image, I am able to obtain not only which is the bounding box, but also which is the category for that mask.
![image](https://github.com/opencv/cvat/assets/148674315/0398b993-042d-496a-a371-5ac33b6c1d58)

Example 3:  I have different masks in the picture which are from different categories. In this case masks of same or different categories are overlapped in the image. Therefore, I am not able to assign a bounding box for each of the elements in the image.
![image](https://github.com/opencv/cvat/assets/148674315/5e32dde7-270a-4e10-b4f6-39024fa0c095)
![image](https://github.com/opencv/cvat/assets/148674315/48197b51-41e6-4f9e-b098-165bd18650f6)

**Comment by frl93** [comment]
Hi once again @bsekachev.

I have been checking both possibilities. As you can see in the following pictures, for CVAT works fine, but not for COCO. Do you know which is the reason?

CVAT format works as you have said. Do you know any application, tool or script that changes from CVAT format and returns the bounding boxes in YOLO format?
![image](https://github.com/opencv/cvat/assets/148674315/283163a6-5a90-4bea-a2b8-7dac25befe53)

COCO format does not have any information about the bounding box
![image](https://github.com/opencv/cvat/assets/148674315/65ff08ac-8fba-4f8f-ab51-9f9957b64e41)

It is true that in CVAT format the "ID" for the picture is 13, whereas in the COCO format is 14. However, you can check that the name of the picture is the same.

**Comment by frl93** [comment]
You are right @bsekachev . The bounding box annotation for each image that contains at least one object apprears after the images list.

The last question is: Does exist any code which makes possible to change from  CVAT or COCO formats to the desired YOLO format?

**Comment by bsekachev** [comment]
I am not sure about such code. I believe you may find ready COCO parser

**Comment by frl93** [comment]
Thanks for you advice @bsekachev. I have been analysing different scripts to transform CVAT or COCO format into YOLO format, but I have realized that there is a problem or may be I am no table to understand properly the exported information from CVAT application. 

If you checked our previous comments, you will see that the bounding boxes coordinates for CVAT and COCO formats are the same.  However, I have been checking different web pages and I concluded that the way for expressing the bounding box coordinates is different.

For CVAT format, I have examined these web pages, where it is explained that CVAT format follows this bounding box coordinates annotation (x_top_left, y_top_left, x_bottom_right, y_bottom_right). https://ms-neerajkrishna.medium.com/sure-the-labelling-is-done-with-the-cvat-tool-and-the-annotations-are-exported-to-the-xml-format-998af628e6ee#:~:text=Each%20box%20object%20has%20a,y_top_left%2C%20x_bottom_right%2C%20y_bottom_right%5D. and https://github.com/wingedrasengan927/pytorch-tutorials/blob/master/Object%20Detection/data/annotations.xml. 

For COCO format, I have examined these web pages, where it is explained that COCO format follows this bounding box coordinates annotation (x_min, y_min, width, height). https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/#:~:text=In%20coco%20%2C%20a%20bounding%20box,height%20of%20the%20bounding%20box.

Therefore, if the annotation of the bounding boxes coordinates is different in CVAT and COCO formats, how is it possible to appear same numbers in the exportations files? Are the bounding boxes annotations correct in CVAT or in COCO format?

**Comment by fattypiggy** [comment]
you can export it as COCO format, and then use this [script](https://github.com/ultralytics/JSON2YOLO) to convert COCO into YOLO.

**Comment by kh-diab** [comment]
> you can export it as COCO format, and then use this [script](https://github.com/ultralytics/JSON2YOLO) to convert COCO into YOLO.

which script exactly you mean please

**Comment by kh-diab** [comment]
> you can export it as COCO format, and then use this [script](https://github.com/ultralytics/JSON2YOLO) to convert COCO into YOLO.

which script in the link you mean exactly. do you have an example please?
