### ISSUE TITLE
question about deploy (detection+classfication)model on CVAT for auto and semi annotations

### ISSUE THREAD

**Issue by zzd1994** [opencv/cvat#7117]
hi, i'm trying to deploy (detection+classfication)model on CVAT for auto and semi annotations, the detection model detect box and crop bbox form origin images, put it to the classfication model, the classfication  results for each bbox's attributs;
i've run my DL model successfully in local,  and i manually annotate several boxes , press F12  check the response format in the pic below
![微信图片_20231109155118](https://github.com/opencv/cvat/assets/48470140/d803de76-b672-4b92-a78a-d91ac1a99e1f)
the task only one label with two attributes
![微信图片_20231109160317](https://github.com/opencv/cvat/assets/48470140/6f331c0a-8373-444b-8e3f-7e9263acb24b)
I would like to confirm if the the response format is available first, so i modify the serverless/onnx/WongKinYiu/yolov7/nuclio/model_handler.py (i've deployed yolov7 nuclio demo)
![微信图片_20231109160121](https://github.com/opencv/cvat/assets/48470140/8bd5c141-6239-4ddb-b5cf-336e9e311662)
and report error 
![微信图片_20231109160604](https://github.com/opencv/cvat/assets/48470140/9c229946-39a6-4473-b9b6-11e47cf91895)
I would really appreciate it if you could help me solve this problem, thanks!

**Comment by bsekachev** [comment]
Hello, 

``docker logs cvat_server``
``docker logs nuclio-nuclio-<function-container-name>``

Should show you what happened. Also you can setup development environment and leave breakpoints in the server code. You can find in our guide how to do that.

**Comment by zzd1994** [comment]
> Hello,
> 
> `docker logs cvat_server` `docker logs nuclio-nuclio-<function-container-name>`
> 
> Should show you what happened. Also you can setup development environment and leave breakpoints in the server code. You can find in our guide how to do that.

hi, thanks for your reply!
docker logs cvat_server:
![微信图片_20231110085721](https://github.com/opencv/cvat/assets/48470140/550f8ef4-519c-4720-9e50-547c4dd28a04)
docker logs nuclio-nuclio-onnx-wongkinyiu-yolov7:
![微信图片_20231110090705](https://github.com/opencv/cvat/assets/48470140/19f80206-f72c-4f94-97f8-8a95b46489a7)

**Comment by bsekachev** [comment]
Okay, result append returns attribute ``name`` instead of ``spec_id``.
Otherwise models would work only on one task/project, because ``spec_id`` is internal CVAT identificator for an attribute.

**Comment by zzd1994** [comment]
> Okay, result should return attribute `name` instead of `spec_id`. Otherwise models would work only on one task/project, because `spec_id` is internal CVAT identificator for an attribute.

hi, i replace `spec_id ` to `name`, restart the nuclio function and don't report any error
![微信图片_20231110164328](https://github.com/opencv/cvat/assets/48470140/452e901a-6eff-4cf3-82f5-7887c2910175)
but the attribute don't have any change (still default attribute)
![微信图片_20231110164325](https://github.com/opencv/cvat/assets/48470140/3ba48b20-f1c2-45c3-9092-c09ea37b15a3)

**Comment by bsekachev** [comment]
Be sure your declared these attributes in config yaml files
You can take this model like a reference: https://github.com/opencv/cvat/tree/develop/serverless/openvino/omz/intel/face-detection-0205/nuclio

**Comment by zzd1994** [comment]
> Be sure your declared these attributes in config yaml files You can take this model like a reference: https://github.com/opencv/cvat/tree/develop/serverless/openvino/omz/intel/face-detection-0205/nuclio

hi, i add these attributes in config yaml, and it worked! thanks!
