### ISSUE TITLE
Avoid copy data into CVAT

### ISSUE THREAD

**Issue by realtimshady1** [opencv/cvat#7119]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Select create new task
2. Select video file from connected fileshare (I have also tried through cloud storage)
3. Untick 'Copy data into CVAT'
<img width="596" alt="image" src="https://github.com/opencv/cvat/assets/20720732/f21d7a3a-d281-4789-9d4b-322ee9043ae3">

I have also attempted to do the same thing using the CVAT rest API but still end up with the same result

### Expected Behavior

That the disk usage by docker would not increase significantly, or more than the original video size. But instead it does increase which indicates that the video data is being copied into CVAT docker volume instead of being fetched from the mount or cloud storage.

<img width="1084" alt="image" src="https://github.com/opencv/cvat/assets/20720732/b958cc22-c487-42a7-8ba9-0c717116fe81">

### Environment

```Markdown
Version: 3c05e8479d4113470c1164349253a67e8767b1ec (HEAD -> release-2.7.6, origin/release-2.7.6)
Docker version: 20.10.22
Docker Swarm/ Kubernetes: No
OS: Debian GNU/Linux 11 (bullseye)
```

**Comment by bsekachev** [comment]
Without **Use Cache** option enabled CVAT prepares all the chunks during creating a task. Usually these chunks (original and compressed) take even more space than the original data. 

With this option enabled, chunks are lazy generated when requested and stored in RAM cache with key db. 
But as far as I remember it is not supported for videos from shared/cloud storages. Maybe @Marishka17 or @azhavoro correct me if I am wrong.

**Comment by realtimshady1** [comment]
Thanks Boris, this was the solution that I was looking for
