### ISSUE TITLE
Job URL while CVAT is behind a proxy

### ISSUE THREAD

**Issue by str1k3r** [opencv/cvat#713]
Currently my CVAT instance is running behind the proxy, but Job url is showing it like http://localhost:8080/?id=1
Any way to change that?

Thanks.

**Comment by nmanovic** [comment]
@str1k3r , let's say your hostname is "myhostname.com" and you specified `ALLOWED_HOSTS: myhostname.com` (or `myhostname:8080`, don't remember exactly) in your docker-compose.override.yml. Now you should be able to access your instance using http://myhostname.com:8080. CVAT will use the hostname to construct list of job urls.

https://github.com/opencv/cvat/blob/c05c7aea8b548d71f9b5cce62370160051535237/cvat/apps/dashboard/views.py#L28

**Comment by nmanovic** [comment]
Please ask your questions in gitter next time. I will close the issue for now.
