### ISSUE TITLE
How to Deploy MMPOSE GPU

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#7131]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

**Comment by KTXKIKI** [comment]
[mmpose.zip](https://github.com/opencv/cvat/files/13331276/mmpose.zip)
ok   done  @bsekachev

**Comment by KTXKIKI** [comment]
cd serverless && ./deploy_gpu.sh pytorch/mmpose/hrnet32/nuclio/

**Comment by bsekachev** [comment]
We do not have GPU configuration for this model.

**Comment by KTXKIKI** [comment]
Hi, I have written the compressed package above. Maybe you can try deploying my GPU function. I tested and found that there was a call to the GPU deployment command above

> 我们没有此模型的 GPU 配置。
