### ISSUE TITLE
Continued use of an interactor (like SAM)

### ISSUE THREAD

**Issue by GeorgePearse** [opencv/cvat#7134]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Use an interactor, try to create a second object. In order to do so you have to reselect the interactor, which completely removes the speed benefit it otherwise provides.

### Expected Behavior

To be able to quickly annotate via shortcuts 

### Possible Solution

If you use [shift + N], to be returned to normal use of the interactor, not exited out of its useage.

Could also add another shortcut [shit + I] to re-enter the interactor mode or something like that.

### Context

You need to reclick on the Select button here every time (between every useage)
![image](https://github.com/opencv/cvat/assets/47161914/47c0189c-b3bf-4548-a317-25274359eaab)

**Comment by GeorgePearse** [comment]
Dumping some of the relevant code here, so that I can refind it if I try to fork 
   
   https://github.com/opencv/cvat/blob/e1d4f30df75297c2026434c9d6b088dd6bf0b962/cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx#L551
   
    ```javascript
    private setActiveInteractor = (value: string): void => {
        const { interactors } = this.props;
        const [interactor] = interactors.filter((_interactor: MLModel) => _interactor.id === value);

        if (interactor.version < MIN_SUPPORTED_INTERACTOR_VERSION) {
            notification.warning({
                message: 'Interactor API is outdated',
                description: 'Probably, you should consider updating the serverless function',
            });
        }

        this.setState({
            activeInteractor: interactor,
        });
    };

```

**Comment by GeorgePearse** [comment]
This demo implies that I'm not using it right, but I can't workout how.

https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat

**Comment by GeorgePearse** [comment]
OHHH, double tap N, so nice

**Comment by bsekachev** [comment]
Hello, 

To call interactor again, you may press N once.
