### ISSUE TITLE
Opacity Slider shortcut

### ISSUE THREAD

**Issue by yaeji98** [opencv/cvat#7136]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Expected Behavior

![화면 캡처 2023-11-14 170515](https://github.com/opencv/cvat/assets/65532694/3a38ae7d-3fd5-44de-bdcf-88a37546eed6)
I want to register a opacity shortcut button that, when pressed, will increase the opacity value to 100, and when pressed again, will decrease the opacity value to 0.

What code should I add?

thank you!!!! :)

**Comment by bsekachev** [comment]
Basically all this logic is in `cvat-ui` module. 
You may start from modifying shortcuts reducer: `cvat-ui/src/reducers/shortcuts-reducer.ts`. 
After, you may find shortcuts (e.g. `DELETE_OBJECT` within a project to see how they are passed to target components).
