### ISSUE TITLE
cvat is changing unintentionally my image 

### ISSUE THREAD

**Issue by Jamshid-Mamatov** [opencv/cvat#7141]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

when i upload my dataset, cvat resized my images , that is why I am taking wrong labling coordinates 
how can i solve this ?

![image](https://github.com/opencv/cvat/assets/76895281/94ce67bb-e5fc-489c-98ae-2ce610525a3b)

**Comment by azhavoro** [comment]
How we can reproduce the issue?
