### ISSUE TITLE
Execution error   'docker-compose up -d'

### ISSUE THREAD

**Issue by wangyp0701** [opencv/cvat#7142]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

git clone https://github.com/opencv/cvat
cd cvat
export CVAT_HOST=your-ip-address

docker-compose up -d

Execution error

```
ERROR: Invalid interpolation format for "no_proxy" option in service "x-backend-env": "clickhouse,grafana,vector,nuclio,opa,${no_proxy:-}"
```

### Environment

Ubuntu 20.04 LTS
docker Version: 24.0.5
docker-compose version 1.25.0

**Comment by azhavoro** [comment]
Please provide full details so that the issue can be reproduced, including the docker compose version at least

**Comment by wangyp0701** [comment]
Ubuntu 20.04 LTS
docker Version: 24.0.5
docker-compose version 1.25.0

**Comment by azhavoro** [comment]
Please use docker compose v2:  https://docs.docker.com/compose/install/linux/
Does this solve the issue?

**Comment by wangyp0701** [comment]
Thank you. The v2 version is fine

**Comment by Aygi235813** [comment]
''docker-compose up -d'', I see the problem, here is _**no dash line**_ ( - ) between ''docker'' and ''compose''

**Comment by AIyc-0101** [comment]
> ''docker-compose up -d'', I see the problem, here is _**no line**_ ( - ) between ''docker'' and ''compose'', just enter a ''space''. See official document
> 
> > ''docker compose up -d''

Thank tou. I solve this issue.
