### ISSUE TITLE
cvat_redis problem after upgrading to newest dev commit 

### ISSUE THREAD

**Issue by AHansoe** [opencv/cvat#7145]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I am fresh in wokring with CVAT and computer science in general, so might just be a dumb mistake/hardware limitation on my end, but checking here just in case. Let me know what more info you need and i will respond shortly! 

I have been using CVAT with serverless functions, not having any issues with composing. New function released with latest dev commit, so followed your "Upgrade guide" to change to a stable version, then went to upgrade to latest dev. Error as follows. 

1. docker working fine on my old dev (month old maybe)
2. docker compose down 
3. git checkout tags/v2.8.2 (to test stable version change. everything worked fine) 
5. git checkout develop 
6. git pull 
7. docker compose up -d 
8. CVAT not stable in docker desktop, cvat_redis constantly restarting 
9. docker logs cvat_redis:

:~/cvat$ docker logs cvat_redis
1:1:C 15 Nov 2023 11:05:54.643 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
1:1:C 15 Nov 2023 11:05:54.643 # KeyDB version=6.3.4, bits=64, commit=7e7e5e57, modified=1, pid=1, just started
1:1:C 15 Nov 2023 11:05:54.643 # Configuration loaded
1:1:C 15 Nov 2023 11:05:54.643 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:1:C 15 Nov 2023 11:05:54.643 * Initializing FLASH storage provider (this may take a long time)
1:1:C 15 Nov 2023 11:05:54.646 # ERROR: Failed to initialize flash storage provider. Details to follow below.
1:1:C 15 Nov 2023 11:05:54.646 #        Invalid argument: Column families not opened: 40, 39, 38, 37, 36, 35, 34, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33

... (looping)

### Expected Behavior

Expected latest dev to work without error like earlier versions always have. 

### Possible Solution

Full removal and fresh re-install? I don't have anything critical stored as of now.

### Context

Could it be that i have to little free RAM? in that case i dont understand why it was working earlier. 

:~/cvat$ top
top - 12:15:56 up 41 min,  2 users,  load average: 0.08, 0.65, 0.68
Tasks:  48 total,   1 running,  47 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.6 sy,  0.0 ni, 99.0 id,  0.1 wa,  0.0 hi,  0.1 si,  0.
MiB Mem :   7826.3 total,   1469.1 free,   3154.5 used,   3202.7 buff/cache
MiB Swap:   2048.0 total,   1901.1 free,    146.9 used.   4360.7 avail Mem

### Environment

```Markdown
1. :~/cvat$ git log -1
commit 401989d0a20794235e16aa33665bf9587c2f60df (HEAD -> develop, origin/ma/default-prefix, origin/develop, origin/HEAD)
Author: Boris Sekachev <boris.sekachev@yandex.ru>
Date:   Tue Nov 14 18:11:12 2023 +0200

    Added new tools to join masks together and to slice a polygon/mask into two parts (#7084)
2. Docker version 24.0.6
3. No 
4. 
Docker Compose version v2.23.0-desktop.1
WSL version: 2.0.9.0
Ubuntu 22.04.2 LTS
```

**Comment by azhavoro** [comment]
I assume the reason is that we have upgraded keydb to the new version and it can't load the flash created by the previous version.
Just try deleting the corresponding volume, most likely its name is `cvat_cvat_cache_db` using the `docker volume rm cvat_cvat_cache_db` command. Not that you need to stop and delete keydb container before.

**Comment by lamuyang** [comment]
> I assume the reason is that we have upgraded keydb to the new version and it can't load the flash created by the previous version. Just try deleting the corresponding volume, most likely its name is `cvat_cvat_cache_db` using the `docker volume rm cvat_cvat_cache_db` command. Not that you need to stop and delete keydb container before.

Thanks for that.
I am facing the same issue right now.
That really solve my problem.

**Comment by AHansoe** [comment]
Thank you! Fixed the issue for me as well.
