### ISSUE TITLE
Can't export dataset of task - IndexError: index 4056 is out of bounds for axis 0 with size 4056

### ISSUE THREAD

**Issue by arrrshia** [opencv/cvat#7151]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

`Error: Request failed with status code 500. "IndexError: index 4056 is out of bounds for axis 0 with size 4056\n".`

I am getting this error both when using the API to export a dataset for a task/job with annotated images as well as exporting it manually on the website.
What I am doing on the website is just creating a task, adding images, annotating, and then exporting with Segmentation Mask 1.1 and I am getting the error. The code below is my API testing that leads to this error.

```python
pbar_out = io.StringIO() 
pbar = make_pbar(file=pbar_out)
path = os.getcwd() + "/cvat_task.zip"
with make_client(host="http://url:8080",credentials=(x,y)) as client:
            client.tasks.retrieve(task.id).export_dataset(format_name="Segmentation mask 1.1",filename=path,pbar=pbar,include_images=True)
assert "100%" in pbar_out.getvalue().strip("\r").split("\r")[-1]`
``` 

### Expected Behavior

I expect the dataset to be exported normally, as it is normally.

### Possible Solution

Perhaps I must split the images into several tasks/jobs?

### Context

I am simply trying to export the images + segmentation masks for a task with the API.

### Environment

```Markdown
Docker Containers
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml -f docker-compose.dev.yml up -d
Nothing else has been edited in the code.
```

**Comment by zhiltsov-max** [comment]
Hi, could you attach the server error log please? You can obtain it by running `docker logs cvat_worker_export > export.log` in the terminal.

**Comment by arrrshia** [comment]
Fixed, though not sure what the problem was restarting cvat fixed it. Thank you though!

**Comment by arrrshia** [comment]
I reopened because I ran into the issue again. Here is docker logs cvat_worker_export > export.log
[export.log](https://github.com/opencv/cvat/files/13595255/export.log)

**Comment by arrrshia** [comment]
Changing cvat/apps/dataset_manager/formats/transformations.py to match the below fixed it for me thus far. Will update if breaks again.
` 
class CVATRleToCOCORle(ItemTransform):
    @staticmethod
    def convert_mask(shape, img_h, img_w):
        rle = shape.points[:-4]
        left, top, right = list(math.trunc(v) for v in shape.points[-4:-1])
        mat = np.zeros((img_h, img_w), dtype=np.uint8)
        width = right - left + 1
        value = 0
        offset = 0
        for rleCount in rle:
            rleCount = math.trunc(rleCount)
            while rleCount > 0:
                x, y = offset % width, offset // width
                **if 0 <= x + left < img_w and 0 <= y + top < img_h:
                    mat[y + top][x + left] = value**
                rleCount -= 1
                offset += 1
            value = abs(value - 1)

        rle = mask_utils.encode(np.asfortranarray(mat))
        return dm.RleMask(rle=rle, label=shape.label, z_order=shape.z_order,
            attributes=shape.attributes, group=shape.group)

`
