### ISSUE TITLE
Failing import from an exported task

### ISSUE THREAD

**Issue by RoseDeSable** [opencv/cvat#7152]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hi,
 I export a task, delete it and import the dataset. The import run and I see the percent circle. After 100 percent the message appears, that the import fails. Here is the log of my browser:

-----------------

cvat-server/:1  The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
/api/user-agreements?org=:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/api/auth/password/change?org=:1 
        
        
        Failed to load resource: the server responded with a status of 401 (Unauthorized)
/api/functions?org=&page_size=500&page=1:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/api/functions/requests/?org=:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/api/functions/requests/?org=:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/api/functions/requests/?org=:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/api/functions/requests/?org=:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/api/functions/requests/?org=:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/api/projects/9/dataset?org=&use_default_location=true&format=CVAT+1.1&filename=my-export-file--2023_03_21_14_24_05-cvat+for+images+1.1.zip&conv_mask_to_poly=true&action=import_status&rq_id=import:project-9-dataset-by-admin:1 
        
        
        Failed to load resource: the server responded with a status of 500 (Internal Server Error)
cvat-app.tsx:376  Error: Request failed with status code 500. "Traceback (most recent call last):\n  File \"/opt/venv/lib/python3.10/site-packages/rq/worker.py\", line 1428, in perform_job\n    rv = job.perform()\n  File \"/opt/venv/lib/python3.10/site-packages/rq/job.py\", line 1278, in perform\n    self._result = self._execute()\n  File \"/opt/venv/lib/python3.10/site-packages/rq/job.py\", line 1315, in _execute\n    result = self.func(*self.args, **self.kwargs)\n  File \"/home/django/cvat/apps/engine/utils.py\", line 306, in import_resource_with_clean_up_after\n    result = func(filename, *args, **kwargs)\n  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n    return func(*args, **kwds)\n  File \"/home/django/cvat/apps/dataset_manager/project.py\", line 176, in import_dataset_as_project\n    project.import_dataset(f, importer, conv_mask_to_poly=conv_mask_to_poly)\n  File \"/home/django/cvat/apps/dataset_manager/project.py\", line 155, in import_dataset\n    importer(dataset_file, temp_dir, project_data, self.load_dataset_data, **options)\n  File \"/home/django/cvat/apps/dataset_manager/formats/registry.py\", line 36, in __call__\n    f_or_cls(*args, **kwargs)\n  File \"/home/django/cvat/apps/dataset_manager/formats/cvat.py\", line 1444, in _import\n    load_data_callback(dataset, instance_data)\n  File \"/home/django/cvat/apps/dataset_manager/project.py\", line 141, in load_dataset_data\n    load_dataset_data(self, *args, **kwargs)\n  File \"/home/django/cvat/apps/dataset_manager/bindings.py\", line 2134, in load_dataset_data\n    raise CvatImportError(f'Target project does not have label with name \"{label.name}\"')\ncvat.apps.dataset_manager.bindings.CvatImportError: Target project does not have label with name \"B\"\n"..
e @ cvat-app.tsx:376

---------------

The format of the file like yolo, cvat-image, ... has any influence of the process.

Here is our cvat - version

Server version: 2.8.2
Core version: 12.0.0
canvas version: 2.18.1
UI version: 1.58.1

Best Regards
Rose

### Expected Behavior

importing without problems

### Possible Solution

no

**Comment by zhiltsov-max** [comment]
Hi, could you attach the full export logs from the server please? You can obtain the log by running `docker logs cvat_worker_export > export.log` in the terminal.

**Comment by RoseDeSable** [comment]
Ok,
 here is the log

[export.log](https://github.com/opencv/cvat/files/13423914/export.log)

**Comment by zhiltsov-max** [comment]
Could you check the label list in the exported dataset for any anomalies? You can find it in the `obj.names` file in the YOLO export and in the beginning of the file for CVAT export. The error message says about the label `B` - is it one of the labels in your project?

**Comment by RoseDeSable** [comment]
Ok,
 here ist the full small export.dataset.

[my-export-yolo.zip](https://github.com/opencv/cvat/files/13424136/my-export-yolo.zip)

**Comment by zhiltsov-max** [comment]
There is only 1 label called "background" in the file. Is it the same as in the original project?

**Comment by zhiltsov-max** [comment]
Ok. Can we also check the beginning of the exported file in CVAT format? The error message was about that format.

**Comment by RoseDeSable** [comment]
You has here the whole exported file
