### ISSUE TITLE
Docker compose up not working out of the box - "services.traefik.command must be a string"

### ISSUE THREAD

**Issue by JanLippemeier** [opencv/cvat#7153]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Checkout the latest commit on develop (commit: 6ae1cffdabcd4b3aeae30f07cb1236807c3a2d15)
Enter docker compose up
Error message: services.traefik.command must be a string

Note: I was just following https://opencv.github.io/cvat/docs/administration/basics/installation/

### Expected Behavior

I would expect this to work out of the box.

### Possible Solution

Rollback to commit f1f6e7853 works as a workaround
I suppose there should be some basic command in the traefik command specification
Maybe the Documentation should instead suggest the option to checkout the latest release branch instead of development.

### Environment

```Markdown
6ae1cffdabcd4b3a
Docker Engine v20.10.17
```

**Comment by bigstones** [comment]
Me either

I think

this is proble

**Comment by SpecLad** [comment]
Thank you for the report. I think the problem is just that I forgot to remove the `command` key in 6ae1cffd. However, I can't reproduce it locally. Which version of Docker Compose are you using?

**Comment by JanLippemeier** [comment]
I am using Docker Compose version v2.7.0

**Comment by SpecLad** [comment]
I see. Looks like null command values are only supported starting with Docker Compose v2.17.1. I'll fix it anyway, but you should be able to work around the problem by upgrading.

**Comment by pktiuk** [comment]
My organization is also affected by this bug.  
We cannot upgrade to 2.9.1
