### ISSUE TITLE
CVAT GUI showing rotated and stretched images. SAM recognises "correct" image

### ISSUE THREAD

**Issue by serena-mou** [opencv/cvat#7155]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I created a folder of images, zipped it and uploaded to CVAT.
Some images are rotated and stretched, see attached images. Left is image courtesy of CVAT and the mask is courtesy of SAM. Right is the original image.
I double checked the raw images, unzipping the file and checking those images.

So far 4 frames have had this behaviour, I am 36 images through a dataset of 248. 

![Screenshot from 2023-11-21 15-16-26](https://github.com/opencv/cvat/assets/77711788/6ad352d4-7684-482f-8644-0e1f2fd4fc18)
![Screenshot from 2023-11-21 15-28-10](https://github.com/opencv/cvat/assets/77711788/56f30b7b-c098-45f2-b90e-24bdb05c1041)
![Screenshot from 2023-11-21 15-37-29](https://github.com/opencv/cvat/assets/77711788/b2f5076a-6dcd-4781-82f2-0d9f36b05ca6)

I have logged out and in of CVAT and restarted the browser, re-zipped and re-uploaded the images, problem persists. 

### Environment

```Markdown
- Using web server app.cvat.ai
- Ubuntu 20.04
- Chromium browser
```

**Comment by bsekachev** [comment]
Hi @serena-mou 

Please, share task ID from app.cvat.ai

**Comment by serena-mou** [comment]
Hello,

Task #381197

Thank you

**Comment by bsekachev** [comment]
@serena-mou 

Thank you, I am investigating the problem. For now I'd recommend delete such broken images from the task.
