### ISSUE TITLE
File index.json in the project backup

### ISSUE THREAD

**Issue by MicalWillen** [opencv/cvat#7157]
Hello，
  I have a probelm, I want to selfcreat a task using c# to create a document like a task backup from cvat, include annotations.json、task.json、index.json and manifest.jsonl. The question is I dont know how to design the index.json
index.json like that
{"0":36,"1":209,"2":382,"3":555,"4":728,"5":901,"6":1074,"7":1247,"8":1420,"9":1589} 
I dont know this number how to design, because every tasks have different number.

Can you tell me how to define these key values? When id is 1, what is its corresponding number?
Thanks！

**Comment by MicalWillen** [comment]
@bsekachev ,Thank you for your response. I've addressed the issue. 
        I discovered a functional issue in CVAT: when choosing the "Labelme 3.0 "export format in the "Export Task Dataset" option, the resulting file is in XML format. However, Labelme exclusively supports JSON format, and the content in XML doesn't align with the JSON structure used by Labelme. This mismatch hinders my ability to convert CVAT-annotated files into a format that Labelme can open. I hope this matter can receive your attention. 
        having a good day!

**Comment by bsekachev** [comment]
@zhiltsov-max 

Do you think labelme changed their format from XML to JSON?

**Comment by MicalWillen** [comment]
Certainly, in Labelme, only JSON format is supported, as I am currently using Labelme for annotation.

**Comment by zhiltsov-max** [comment]
@bsekachev, yes, seems like there is [LabelMe v4.0 format](https://github.com/wkentaro/labelme/blob/67e489ba236eceee19a7d82c37e7d80cd3d849c6/examples/tutorial/apc2016_obj3.json) now, which uses JSON. The format is pretty simple, you can find it's implementation [here](https://github.com/wkentaro/labelme/blob/67e489ba236eceee19a7d82c37e7d80cd3d849c6/labelme/label_file.py).
