### ISSUE TITLE
Keypoint Annotation export only gives 1 set of keypoints

### ISSUE THREAD

**Issue by dcai-emancro** [opencv/cvat#7159]
Hi, I have annotated images with keypoints on cvat and many of the images contain multiple sets of keypoints annotations. When I export the annotations, however, I am only getting 1 set of keypoints. Can someone please tell me out to correctly export such that I can have all the keypoint annotations exported? Thank you!
<img width="921" alt="image" src="https://github.com/opencv/cvat/assets/128842803/6c5099be-8eb9-455b-8632-03c2a32c3952">
<img width="403" alt="label" src="https://github.com/opencv/cvat/assets/128842803/dcd15fb7-7745-45cb-a4ce-3d197e0a9873">

**Comment by zhiltsov-max** [comment]
Hi. Please add more information how we can reproduce the error. I have created a task with 1 skeleton label with 2 joined points, and drawn 2 annotations. Both appeared in the downloaded json after export in COCO keypoints.

**Comment by dcai-emancro** [comment]
Hi, apologies! All the annotations are all there. I have mistaken "id" for "image_id".
