### ISSUE TITLE
COCO Export missing keypoints

### ISSUE THREAD

**Issue by julien-flack-adnav** [opencv/cvat#7161]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Add a new label, set it to "Points" (not a shape skeleton but simply keypoints that may vary in number per image, for example, links in a chain)
2. Annotate points in one or more images
3. Export the annotations to the COCO format
4. The exported instances_default.json do not contain any annotations - despite the fact that COCO explicitly supports keypoints

Note: if you export the annotations into the CVAT format the keypoints are present

### Expected Behavior

COCO export annotations should include "Points" style annotations

### Possible Solution

Include "Points" annotations as keypoints in COCO format. 

### Context

Annotate keypoints for links on a chain. The annotations will be used to detect the keypoints rather than using bounding boxes

### Environment

```Markdown
Used online trial account to verify issue:
https://app.cvat.ai/tasks/383174/jobs/423493
```

**Comment by zhiltsov-max** [comment]
Hi. As you said, [the COCO Keypoints format supports keypoints](https://cocodataset.org/#format-data). Each annotation belongs to one of the labels, and each label has a corresponding skeleton (joints and vertices), i.e. a fixed size structure. COCO doesn't support point sets of different sizes in COCO format under one label.

**Comment by julien-flack-adnav** [comment]
Thanks for clarifying @zhiltsov-max
