### ISSUE TITLE
Using SDK to set a job state won't change an associated task state.

### ISSUE THREAD

**Issue by mezotaken** [opencv/cvat#7163]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Create a project with a single task, assign a single job to it.
2. Using the `PatchedJobWriteRequest` set the `state='completed'`, `status='accepted'`
3. Observe that the jobs are being filtered by state correctly, but the tasks and projects are not.

### Expected Behavior

It should work exactly like finishing the job manually through UI. While doing so, task status was updated as expected. 
At first i thought that there's a corresponding field in patch method for tasks/projects, but it seems like their state should be changed automatically when all the parts are completed.
I assume the same issue would arise when using the REST API

### Environment

```Markdown
Commit: 59519dc453c5976fc36545733270fffb3c79e678
Docker 23.0.5
```

**Comment by bsekachev** [comment]
Hello, 

Try state='completed', stage='acceptance'

``status`` is legacy field, and read-only in current REST API

**Comment by mezotaken** [comment]
Yes, sorry for the typo, I didnt actually use the `status`, it was the `state`. The problem was that i did them separately, i suppose. First i only did the stage='acceptance', and then with a separate request i changed the state. Weird, but doing it at the same time works fine. That's on me i guess, don't know why i didnt even try using them both.
