### ISSUE TITLE
Opacity settings keep resetting to high values

### ISSUE THREAD

**Issue by DariusLiesis** [opencv/cvat#7176]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Go to any task of the project;
2. Change Opacity settings;
2. Change frame/Make any update;
3. Opacity settings will reset to the same high values;

### Expected Behavior

Expected the settings to remain the changed values, however, they keep being reset.

### Possible Solution

We are certain this is from the server-side, because the entirety of our project was affected. No matter which video is selected, the opacity values default to high once a page update occurs. Restarting the computer, refreshing the page, saving annotations with the correct Opacity did not help.

### Context

This issue affected me by preventing accurate labelling of sensitive objects. The high opacity becomes an issue to to the inability to notice the finer borders.

**Comment by bsekachev** [comment]
Hello

Do you have any masks annotated on the frame? If so, opacity settings are set such way that the masks are visible normally

**Comment by bsekachev** [comment]
Okay @DariusLiesis 

Thank you, we are working on the issue #7186

**Comment by DariusLiesis** [comment]
Thank you kindly for the help. Take your time, and if there's anything further I can provide, let me know.
