### ISSUE TITLE
mask problem on coco json style

### ISSUE THREAD

**Issue by synsis** [opencv/cvat#718]
The overlap part between two masks would disappear,  and the area would only be covered by one of these masks. and another one, would be separated into two parts by the overlap area.

**Comment by nmanovic** [comment]
@synsis , could you please attach data to reproduce the issue?

**Comment by synsis** [comment]
@nmanovic 

For example, I draw shapes like this.
![Screenshot from 2019-09-16 18-03-28](https://user-images.githubusercontent.com/20524338/64949937-df123e00-d8ac-11e9-8673-bf243727212e.png)

when I download and upload it as cvat xml, it is normal.

But, when I download and upload it in coco xml format, it changes, the overlap part is disapear.
![Screenshot from 2019-09-16 18-05-05](https://user-images.githubusercontent.com/20524338/64950040-17b21780-d8ad-11e9-9391-d53ed9f8544e.png)

For another example, it even create a new shape itself.
![Screenshot from 2019-09-16 18-05-46](https://user-images.githubusercontent.com/20524338/64950087-2e586e80-d8ad-11e9-835a-a4bbd695b7ca.png)
![Screenshot from 2019-09-16 18-06-22](https://user-images.githubusercontent.com/20524338/64950088-32848c00-d8ad-11e9-8af2-8c14f7ad70ac.png)

**Comment by synsis** [comment]
BTW, I use polygon mode to draw these.

**Comment by nmanovic** [comment]
@synsis , I see the problem. Need to check if it is correct behaviours or not. We will investigate.

**Comment by alexolenskyj** [comment]
I am getting this same issue, even if I export as CVAT XML and convert to COCO JSON using the coco converter in the CVAT utils. Instances can be separated, but if there is overlap, only one instance mask will include those pixels.

**Comment by nmanovic** [comment]
The issue was fixed by @Johannes222
