### ISSUE TITLE
Optimization of Everything Segmentation Model

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#7181]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

Perhaps we can use this pytorch to rewrite segment anything
https://github.com/pytorch-labs/segment-anything-fast

**Comment by bsekachev** [comment]
Duplicate of #6680
