### ISSUE TITLE
Analytics Ingress in Helm Chart does not fully support controllers other than Traefik

### ISSUE THREAD

**Issue by ozen** [opencv/cvat#7185]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

The issue is related to the helm chart.

When analytics is enabled, two `Ingress` resources are created, one main and one analytics. Both resources use the same host name.

When using Traefik controller, the analytics ingress has `traefik.ingress.kubernetes.io/router.middlewares` annotation but the main ingress does not. 

Similarly, when using other Ingress controllers, different annotations for the two ingresses may be needed. But the `ingress.annotations` value is shared between the ingresses and different annotations for different ingresses is not supported.

### Possible Solution

We may add `analytics.ingress` dictionary to the values. The analytics ingress template may use `.Values.analytics.ingress` first, and use `.Values.ingress` when the value is not found in the former.

### Context

Here is one example:

Different ingress controllers handle "multiple ingress - same host" case differently.
Traefik, by default, sorts rules in descending order using rules length. To change the order, `traefik.ingress.kubernetes.io/router.priority` annotation is used. Using Traefik, CVAT Ingress resources works fine as they are.
AWS Load Balancer Controller, by default, sorts rules lexicographically by the Ingress’s namespace/name. With the current CVAT templates, `/*` rule comes before `/analytics` and analytics path does not work as intended. To fix the ordering, `alb.ingress.kubernetes.io/group.order` annotation must be added.

**Comment by bsekachev** [comment]
I do not consider it to be a bug since originally we work with Traefik only.
You are always welcome to contribute.
