### ISSUE TITLE
How to get background data from the analytics of the cvat?

### ISSUE THREAD

**Issue by adreamero** [opencv/cvat#7187]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I want to get and export the background data in the cvat interface analytics button. What should I do? 

### Describe the solution you'd like

1、Using a spider to crawl page data.
2、Accessing the database.

**Comment by bsekachev** [comment]
Please, clarify what you mean speaking ``background data``?

**Comment by adreamero** [comment]
Thank you for responding promptly,
I've just realized that I can directly download the data from Grafana dashboards, and this data is exactly what I need.
