### ISSUE TITLE
keypoint annotation export gives wrong bbox

### ISSUE THREAD

**Issue by dcai-emancro** [opencv/cvat#7193]
Hi, after exporting keypoint annotations, I found that there are several instances where the bbox has 0 width. I double checked each image and didn't find any mistakes during annotation. Can someone help me with this please? I have attached one of the examples below. Thank you!

{"id":98,"image_id":34,"category_id":1,"segmentation":[],"area":1247.6373999999978,"bbox":[68.43,159.55,274.81,4.54],"iscrowd":0,"attributes":{"occluded":false,"keyframe":false},"keypoints":[343.24,159.55,2,68.43,164.09,2],"num_keypoints":2},

{"id":99,"image_id":34,"category_id":1,"segmentation":[],"area":0.0,"bbox":[72.45,31.01,278.31,0.0],"iscrowd":0,"attributes":{"occluded":false,"keyframe":false},"keypoints":[72.45,31.01,2,350.76,31.01,2],"num_keypoints":2},

{"id":100,"image_id":34,"category_id":1,"segmentation":[],"area":37428.146,"bbox":[87.59,35.95,220.36,169.85],"iscrowd":0,"attributes":{"occluded":false,"keyframe":false},"keypoints":[307.95,35.95,1,87.59,205.8,2],"num_keypoints":2},

{"id":101,"image_id":34,"category_id":1,"segmentation":[],"area":10561.5643,"bbox":[48.34,183.66,278.89,37.87],"iscrowd":0,"attributes":{"occluded":false,"keyframe":false},"keypoints":[48.34,183.66,2,327.23,221.53,2],"num_keypoints":2}

<img width="731" alt="bug" src="https://github.com/opencv/cvat/assets/128842803/e860f791-f225-44c5-add7-145e44a716ab">

**Comment by bsekachev** [comment]
Hello, I see area == 0 in your data in one case where height == 0.
Since **area = height * width**, you have such results. Height is 0, because the skeleton line as I can see horizontal. So, what is the problem?

**Comment by dcai-emancro** [comment]
@bsekachev hi, i was under the impression that the bbox recorded during annotation is the bbox we see during annotation. Is this not the case? I have attached an image below showing the bbox I thought the horizontal skeleton line would have. 
<img width="734" alt="horizontal bbox" src="https://github.com/opencv/cvat/assets/128842803/76a8e896-1e45-48b5-9498-ecd81474dc82">
Is there anyway to get the bbox info for the bbox we see during annotation? Thank you!

**Comment by bsekachev** [comment]
Bbox you see during annotation has functional purposes only, like dragging/resizing the whole skeleton. You will not see it in annotation file.

**Comment by bsekachev** [comment]
Related #7156
Related #6158
Related #5904
