### ISSUE TITLE
Uploading of annotations results in all frames being keyframes

### ISSUE THREAD

**Issue by Hiddenfire21** [opencv/cvat#720]
Annotations dumped in CVAT XML 1.1 for videos and uploaded for a similar task. However after uploading all frames are keyframes even though XML has information on which frames should be keyframes.
This makes it tedious to make changes to a track as each frame has to be edited

**Comment by nmanovic** [comment]
@azhavoro , need to investigate. If both tasks are in interpolation mode and dumped annotations for videos it is a bug.

**Comment by bsekachev** [comment]
@Hiddenfire21 @nmanovic @azhavoro 
Bug is confirmed.
