### ISSUE TITLE
endless docker build

### ISSUE THREAD

**Issue by Maximal4028** [opencv/cvat#7200]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hello! I'm trying to install cvat with semi-automatic and automatic annotation (I want to install magic wind with facebook SAM):
https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat

I following instructions in official docs:
https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

However, when I started docker compose command:
`docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d`
it has an endless building 
![Screenshot from 2023-11-29 09-12-54](https://github.com/opencv/cvat/assets/23663993/c12534b8-cd6f-4360-bcdb-5d03594df142)

When I started default docker compose command:
`docker compose up -d`
it works, but doesn't have magic wand
![Screenshot from 2023-11-29 10-01-26](https://github.com/opencv/cvat/assets/23663993/08d51c5c-7bd5-4da1-a14c-d6ede74f1002)

Ubuntu 20.04
Docker version:
![Screenshot from 2023-11-29 10-05-16](https://github.com/opencv/cvat/assets/23663993/317b7e4d-fffb-4fbe-81b7-552e7a088d6e)

What can I do to fix this? Thank you.

**Comment by bsekachev** [comment]
Just tried this command, works as expected for me. We need some more details to be able to reproduce the issue on our side.
