### ISSUE TITLE
YOLOv5 automatic annotation

### ISSUE THREAD

**Issue by chang50961471** [opencv/cvat#7201]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Expected Behavior

Through YOLOv5 automatic labeling, I found that it takes up a lot of disk space. How to free up the occupied space

**Comment by bsekachev** [comment]
``nuctl delete function <function-name>``

Additionally you may try removing docker images if they are not removed automatically (like ``docker rmi <image_name>``). Please, refer to Docker documentation.

**Comment by chang50961471** [comment]
> `nuctl delete function <function-name>`
> 
> Additionally you may try removing docker images if they are not removed automatically (like ). Please, refer to Docker documentation.`docker rmi <image_name>`

If I keep using automatic annotation, will the disk space continue to increase

**Comment by bsekachev** [comment]
If you mean that it uses more and more disk space when you are running automatic annotations, than we need more details and steps to reproduce. 
Anyway, since we do not have YOLOv5 I can't recommend something specific here.
