### ISSUE TITLE
Can't import hugging face model in CVAT 2.7.4

### ISSUE THREAD

**Issue by stevezkw1998** [opencv/cvat#7204]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I follow the steps on https://www.cvat.ai/post/integrating-hugging-face-and-roboflow-models
But when I tried to add model from hugging face, I was blocked by “Please, specify model provider”
But there is no option in the selecting bar see attach image:
![image](https://github.com/opencv/cvat/assets/53121066/34d71c1b-cd03-403c-988b-483044dfd997)
![image](https://github.com/opencv/cvat/assets/53121066/553086b4-5702-4436-9bbd-d44e87fbec26)

### Expected Behavior

It should has the same behavior as the article shown https://www.cvat.ai/post/integrating-hugging-face-and-roboflow-models

**Comment by bsekachev** [comment]
Hello, Roboflow and Huggingface models are enterprise features. It may be available on app.cvat.ai or on a self-hosted enterprise solution.
