### ISSUE TITLE
How can I obtain statistical information for each job from the database?

### ISSUE THREAD

**Issue by adreamero** [opencv/cvat#7205]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

Hello, may I ask how to retrieve the following statistical information for all users from the database of cvat?
The version of cvat i am currently using is 2.8.2.

**Comment by adreamero** [comment]
here is the statistical information what i need
![2](https://github.com/opencv/cvat/assets/73162110/094751c1-19cb-4915-ae41-810a50a88c72)

**Comment by bsekachev** [comment]
This information itself not stored in the database. 
When you open a job, client code has information about all annotations in this job and it uses this information to calculate this statistics. This logic is a part of cvat-core library:

Basically the code, to get statistics for a job using cvat-core:

```
cvat.jobs.get({ jobID: 188 }).then(async ([job]) => {
    await job.annotations.get(0);
    const statistics = await job.annotations.statistics();
    console.log(JSON.stringify(statistics))
    await job.close()
})
```

You may execute this code in the browser console in opened CVAT. 

![image](https://github.com/opencv/cvat/assets/40690378/1f32bc1a-2f5c-451a-8683-a90049ff89d8)
