### ISSUE TITLE
Network Error to load next image while annoting

### ISSUE THREAD

**Issue by adcetian11** [opencv/cvat#7220]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

**Comment by bsekachev** [comment]
Hello, usually network error means Connection lost to the server.
Anyway we are not able to help without any details.

**Comment by adcetian11** [comment]
why CVat requires very good internet connectivity it is not running at normal internet speed ... at same speed  image dataset uploading on google drive done. But it works well with wifi and LAN connectivity.
