### ISSUE TITLE
Alt Key alone Zooms out

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#7223]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Using app.cvat.ai

Zoom IN , the click Alt alone. It zooms out

### Expected Behavior

Since Alt is used in combination with other keys for various commands, Alt by itself should do nothing...

There is Alt-K for Zoom out

**Comment by bsekachev** [comment]
Please, provide steps to reproduce the problem / a screencast.
Pressing ``Alt`` does not affect zoom level somehow.
