### ISSUE TITLE
Could not receive image data  Error: Corrupted zip: can't find end of central directory

### ISSUE THREAD

**Issue by sajibbormon** [opencv/cvat#7226]
can not load next image
![image](https://github.com/opencv/cvat/assets/145423839/441e70a7-ed80-412d-a3b4-f72c6ccc5dc2)
![error](https://github.com/opencv/cvat/assets/145423839/d93b22a8-e1db-47ce-aa12-55daeb5e9a6f)

**Comment by bsekachev** [comment]
Version?

**Comment by sajibbormon** [comment]
> Version?
free 
Server version: 2.9.1

Core version: 12.1.0

Canvas version: 2.19.0

UI version: 1.59.0

**Comment by bsekachev** [comment]
Very interesting. 
Couple of months ago we met this error and fixed it. Since then, it did not appear anymore. 
How often do you meet it? Is your server highly loaded?

**Comment by bsekachev** [comment]
The root problem here is that truncated data chunk is received from the server. So, ZIP file gets broken and can not decode all the images inside.

**Comment by sajibbormon** [comment]
> The root problem here is that truncated data chunk is received from the server. So, ZIP file gets broken and can not decode all the images inside.

What should I do now? any suggestion

**Comment by sajibbormon** [comment]
> Very interesting. Couple of months ago we met this error and fixed it. Since then, it did not appear anymore. How often do you meet it? Is your server highly loaded?

Can I upload the same image again for this task? How can I upload the same image again?

**Comment by azhavoro** [comment]
Try to clear data cache:

**Comment by bsekachev** [comment]
I believe that should be fixed in v2.9.2.
