### ISSUE TITLE
It seem ignorePattern eslint in workspace not working

### ISSUE THREAD

**Issue by lequangkhanh2901** [opencv/cvat#7230]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Edit `cvat-data/src/ts/3rdparty/Decoder.worker.js`

Just small change to `staged` watch it.

### Expected Behavior

Eslint should ignore it like specific in `ignorePattern` in `.eslintrc.js` in `cvat-data`

**Comment by bsekachev** [comment]
Thank you, fixed it in this commit https://github.com/opencv/cvat/pull/7232/commits/d147bf7d057aaed7a0239f5df5a1083227268569 in the PR #7232
