### ISSUE TITLE
Segmentation based on several images

### ISSUE THREAD

**Issue by PierreBoyeau** [opencv/cvat#7234]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I am trying to segment cells in biological tissues. I have multiple images of the exact same region, which highlights different cells in the regions. 
Right now, I use one of these images as the main image, the other ones as contextual ones. However, it is impossible to segment a contextual image, and to share segmentations made on the main and contextual images.

### Describe the solution you'd like

I would like CVAT to allow segmentations to be made on contextual images. I understand, however, that my use-case is very specific.
However, I was wondering if a functionality existed for scenarios close to mine.

**Comment by kerowak** [comment]
I believe I have also encountered this issue, and the solution I've landed upon is uploading each channel from my multichannel image as a separate frame of a video. You can see how I did it [here](https://github.com/Barmada-Lab/lab-tools/blob/main/src/gecs/cvat/upload.py) in the "upload" function. This approach is limited in that it will not work for z-stacks or t-stacks, unfortunately. Hopefully this helps!

**Comment by PierreBoyeau** [comment]
Hi Jacob, many thanks for your answer. I will have a careful look at this. The solution I found temporarily was to load the different images as different tasks, and to transfer the annotations when need be (which is definitely not the best approach).

**Comment by bsekachev** [comment]
Contextual images can not be annotated. We do not have plans to support it. 
There is another option we would like to support in the future: multi-modal data (many images threads, geo-data, etc.). The request may b a part of such feature.

**Comment by XuYunqiu** [comment]
Hi all,

I have the similar need for annotating the contextual images. 
In my case, I would like to label some related regions from paired images. In other words, the two images should be annotated at the same time.
Is there any potential solution for this purpose?
