### ISSUE TITLE
Task not "completed" even though the job stage is "acceptance" and job state is "completed"

### ISSUE THREAD

**Issue by swardh** [opencv/cvat#7246]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Set job stage to "acceptance.
2. Set job state to "completed"
3. Go to "api/swagger" and check "api/tasks", "status=completed"
4. It's not there. (Only the ones where you click, "finish the job")

### Expected Behavior

I would expect that the task status would be "completed" if the "stage" is "acceptance" and "state" is "completed" for all jobs in the task. In my case it's just one job per task.
"Finish the job" changes the state and stage to the same, but also sets the task as "completed"

### Context

The api is used to see which tasks are done and people don't always click "finish the job" but instead set it to acceptance/completed themselves, so it doesn't show up as done.

**Comment by bsekachev** [comment]
@swardh 

Please, double check. "Finish job button" does exactly the same, stage => acceptance, state => completed,  using the same REST APi. 

Also, all the jobs within a task have to be (acceptance, completed) to make task completed.

**Comment by swardh** [comment]
Thanks for your answer.
I've checked several times, and made more tests now. When Acceptance and Completed is set manually, the status is set to "Validation", not "Completed". Only when "finish the job" is clicked it's set to "Completed"
I've tried this with only 1 job in a task, and with several jobs in a task. 
It looks correct in the ui, the green bar and "done". But with the api (api/tasks and api/jobs/{id} the status is "validation" when it should be "completed".

I'm using version 2.7.6

**Comment by bsekachev** [comment]
Be sure you do not set first state to "Completed" and then stage to "Acceptance". When you change stage, state is reset to "New" automatically.

**Comment by swardh** [comment]
I am setting the stage first to acceptance, and then state to completed.
The screenshot is from a task with only one job, should it be possible for the status to be "validation" in this case? What does "status" represent in the job? (api/jobs/{id}).
Status for the task is the same "validation", even though the only job in the task is as in the screenshot, acceptance/completed.
![cvat](https://github.com/opencv/cvat/assets/73133546/94cc2da2-b34f-4962-b555-49bf0a28b7cc)

**Comment by bsekachev** [comment]
Task does not have fields "stage" and "state". You are looking at Job instance, not Task instance. 
Field "status" in Job is deprecated and did not use anymore.
