### ISSUE TITLE
How to use cvat at other computer

### ISSUE THREAD

**Issue by wonyeoblee** [opencv/cvat#7248]
What settings do I need to configure to use cvat's localhost on another computer?

**Comment by bsekachev** [comment]
You can't access ``localhost`` from another computer (except for some hacks of course , like for exampe ssh reverse tunneling), it is a networking issue. 
If you want to deploy CVAT in your local network, deploy it on external IP (e.g. 192.168.*.*) or another one, again it depends on your network configuration. 

Please, read documentation before opening the issue: https://opencv.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

**Comment by wonyeoblee** [comment]
Thanks for reply.
I understand that i can't access localhost form another computer.
Thank u:)
