### ISSUE TITLE
I have the sane problem, but I need save the data over my NAS, is it possible that?

### ISSUE THREAD

**Issue by wisrovi** [opencv/cvat#7250]
I'm so sorry. It seems to be my own mistake, I found that the mypath set cannot be a NAS, it must be a directory of the current host, and after I changed it, it worked fine.

thx

_Originally posted by @wangwangteam in https://github.com/opencv/cvat/issues/6119#issuecomment-1540112959_

**Comment by wisrovi** [comment]
I need to save the data over a NAS, is it possible that?

**Comment by bsekachev** [comment]
Please, try to address your question to Docker community. We did not use NAS paths together with docker volumes.
