### ISSUE TITLE
Uninstall CVAT

### ISSUE THREAD

**Issue by devHand6** [opencv/cvat#7260]
Unlike Issue #2044 I deleted Docker and CVAT is left on my computer. How do I remove CVAT?

Thanks

**Comment by prayas7102** [comment]
using which OS?

**Comment by devHand6** [comment]
Sonoma 14.0
________________________________

**Comment by bsekachev** [comment]
To remove CVAT you need to remove corresponding Docker containers/images and volumes.

To remove a container: 
`docker rm -f <container_name>`

To remove images/volumes you may use:
`docker system prune` (be careful with this command if you have something else deployed with Docker on your system)

Please, read the documentation: https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by devHand6** [comment]
Docker was removed without the terminal. There is an internal command in docker to remove itself.

I need to delete the CVAT files. I never used CVAT.

Thanks!
________________________________

**Comment by Villjoie** [comment]
Hello

I need to remove the CVAT from my computer, how do I do it?

**Comment by Villjoie** [comment]
Hello

I need to remove the CVAT from my computer, how do I do it?
Windows 10
