### ISSUE TITLE
Unable to reset password in CVAT 

### ISSUE THREAD

**Issue by ragahdtareg** [opencv/cvat#7262]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. I am using the local host using localhost:8080
2. the browser i used is Brave and I reinstall it
3. then the CVAT is not letting me to log in or even to reset the password and this error shows:

_Could not reset password on the server.

Could not login on the server

Error: Request failed with status code 400. {"non_field_errors":["Unable to log in with provided credentials."]}.
### Expected Behavior

I can log in to my account

### Possible Solution

I tried to reset the password but I am pretty sure the password is correct.

### Context

My annotation for all my video are there in the CVAT so I need to to log in!

**Comment by bsekachev** [comment]
I hardly think you setup email configuration to reset your password on localhost.
So, just create another superuser account, login and get your data. 

Please, follow the link to see how to setup superuser account: https://opencv.github.io/cvat/docs/administration/basics/admin-account/
