### ISSUE TITLE
Key points and shapes not showing 

### ISSUE THREAD

**Issue by laurahgdrn** [opencv/cvat#7263]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Open new project 
2. Add labels
3. Import images (.jpg files) 
4. Open job 
5. Click on "Draw new points"
6. Add number of key points
7. Click "shape" 

### Expected Behavior

Be able to draw key points, but nothing happens (neither for the polygon function). I've tried different images, file types, resolutions, etc. I've followed several tutorials, but I cannot draw anything on the image. 

### Environment

```Markdown
- MacOS 14.1.1
- Safari 17.1 (I cannot use a different browser, maybe that's the issue?)
```

**Comment by bsekachev** [comment]
Safari is not supported, you can see the corresponding message when open CVAT for the first time.
Please use Chromium based browser.

**Comment by laurahgdrn** [comment]
Thanks for the fast response! Unfortunately I cannot use a different browser, but at least I know what the issue is now.
