### ISSUE TITLE
Unable to accept youtube video url from remote resource

### ISSUE THREAD

**Issue by prayas7102** [opencv/cvat#7264]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

possible error: ![image](https://github.com/opencv/cvat/assets/71717433/a21fd9ce-baf6-4369-a5b2-d930dd419595)

docker server logs: 
![image](https://github.com/opencv/cvat/assets/71717433/54e88328-4380-472a-853f-1f7420805a33)

### Expected Behavior

I expected it to load the video without any error, for annotation.

### Context

I want that the client can just paste utube video link and get along with annotation etc. 

### Environment

```Markdown
I'm using CVAT in ubuntu local host.
```

**Comment by bsekachev** [comment]
It does not work this way, CVAT needs direct link to the videofile, not to YouTube page.
