### ISSUE TITLE
Reload gpu model from local docker image instead of  using the following command "./severless/deploy_gpu.sh xxxx"

### ISSUE THREAD

**Issue by xuexigua** [opencv/cvat#7270]
I delete sam gpu inference server from nuctl,  how can I restart this server by load my local docker image instead of rebuilding docker image? 
![20231215-124932](https://github.com/opencv/cvat/assets/44158956/f301a1ea-185e-48fd-b0e5-927e0c1ffa75)
![20231215-124940](https://github.com/opencv/cvat/assets/44158956/5e8db4cb-91e9-43ed-9ad1-852104af1a2b)

**Comment by bsekachev** [comment]
Unfortunately we can't help with the request.
Please, use standard way to deploy nuclio functions.
