### ISSUE TITLE
CVAT and the way from lan into internet

### ISSUE THREAD

**Issue by RoseDeSable** [opencv/cvat#7271]
Hi,
 we have a discussion inside of our enterprise. Therefore I have the following question to you:

We want to load a model from outside our lan - for example from roboflow. How is the way of this process ? The user starts the process over his browser. Who makes than the further work: his browser or the cvat-container ? In other words: Must we give the cvat-container access into internet ? This is the controversial subject in our team. 

If the cvat-container must access into internet, have we the possibility to build a mirror for roboflow in our enterprise ? This could be the next question.

Best Regards
Rose

**Comment by bsekachev** [comment]
Everything is proxied through cvat containers, so, it needs access to the Internet. 
I am not sure it will work with mirrors, it was not supposed during implementation, but you may try.
