### ISSUE TITLE
ports error after going into developer mode

### ISSUE THREAD

**Issue by zainkiyani682** [opencv/cvat#7272]
<e> [webpack-dev-server] [HPM] Error occurred while proxying request 127.0.0.1:3000/api/events?org= to http://localhost:7000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
That's the error which is shown if any one has knowledge about that kindly help me out.
--source from where i try developer mode After all the installation error define in start when in run "yarn run start:cvat-ui"
Source https://opencv.github.io/cvat/docs/contributing/development-environment/

**Comment by bsekachev** [comment]
Perhaps you did not start backend process

**Comment by zainkiyani682** [comment]
sorry what do you mean?

**Comment by bsekachev** [comment]
Please, follow step by step guide carefully: https://opencv.github.io/cvat/docs/contributing/development-environment/ 

If you have an issue on a specific step, ask questions providing all the details.
