### ISSUE TITLE
How to generate output file names with input video name 

### ISSUE THREAD

**Issue by lenka-79** [opencv/cvat#7276]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

Hi,

While doing Annotation with CVAT tool, how to get the annotated output.zip file with input video name,
right now I am getting annotated output *.zip contains both *.png & yolo.txt files, but both files names are getting like, frame.png & farem.txt and so on.. but I need these names with input record name, how to get it with this tool, I think some where need to select these options, please let me know if I miss anything here.

Thanks in Advance,
L V Giribabu.

**Comment by bsekachev** [comment]
YOLO format does not support meta information, so, you can't get source video name in this format. 
You may use `CVAT for Images`, for example. It contains source file name.
