### ISSUE TITLE
Slow Interface Opening When Accessing CVAT Server with Custom IP Address

### ISSUE THREAD

**Issue by arcibiyo** [opencv/cvat#7277]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Expected Behavior

I finished Quick installation guide for ubuntu. cvat project worked well on localhost:8080. I entered my own IP address instead of localhost because I want to run the project on an Ubuntu server computer without internet access. I connected a second computer to this server via Ethernet. When I enter "ip_address:8080" in my browser, the interface takes 1-2 minutes to open. However, once the interface is open, other tabs and labeling operations work quite quickly. In summary, after using the "export CVAT_HOST=your-ip-address" feature and trying to access the interface by entering my own IP address in the browser, the interface opens slowly. Similarly, when I refresh the site, it also opens slowly. What is the solution to this problem?

**Comment by bsekachev** [comment]
Please, check on Network tab in the browser dev tools what exactly consumes time, also check you bandwidth.
