### ISSUE TITLE
How to install cvat project without internet connection?

### ISSUE THREAD

**Issue by arcibiyo** [opencv/cvat#7278]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Possible Solution

I completed the installation on my internet-connected computer and ran it on localhost. I observed that it was running on localhost:8080. I wanted to transform it into an offline server as I planned to run the project on the local network. I changed the IP address, etc. The project was working, but while troubleshooting some issues, I accidentally deleted all the images. Now, since I don't have an internet connection, I am encountering an error when executing the 'docker compose up -d' command. Can't I restart the system without reconnecting my server to the internet, without using the internet?

**Comment by bsekachev** [comment]
To install CVAT you need internet connection, because it fetches 3rdparty packages from the Internet during installation.
For an advanced user, there are some options with building images on another machine and then transferring them to target, but that is not what we support out of the box.

**Comment by arcibiyo** [comment]
actually ı installed cvat with models which are sam, yolo vs. Also ı can use sam model to annotate without internet. However when ı restart my pc, models(yolo,sam..) give error. Before restart ı done down steps like below.
`docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml down
`
When pc opens, ı tried to use models to annotate. But ı got some error. I understood that when pc restart, models like sam needs internet. Because I deleted models from :8070 then deploy again, it works. My goal is using cvat with models like sam without internet. How can ı fix this problem?

**Comment by arcibiyo** [comment]
@bsekachev my project in offline. So when ı run `docker compose -f docker-compose.yml -f docker-compose.dev.yml build`, I got this error **ERROR [cvat_server internal] load metadata for [docker.io/library/golang:1.20.5](http://docker.io/library/golang:1.20.5).**
![oso](https://github.com/opencv/cvat/assets/47760055/ec46c8ef-49d4-44f0-80c7-a3308783c658)

how to run `docker compose -f docker-compose.yml -f docker-compose.dev.yml build` code without internet?

**Comment by arcibiyo** [comment]
> @bsekachev my project in offline. So when ı run `docker compose -f docker-compose.yml -f docker-compose.dev.yml build`, I got this error **ERROR [cvat_server internal] load metadata for [docker.io/library/golang:1.20.5](http://docker.io/library/golang:1.20.5).** ![oso](https://private-user-images.githubusercontent.com/47760055/293882807-ec46c8ef-49d4-44f0-80c7-a3308783c658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzY0NjUsIm5iZiI6MTcwNDI3NjE2NSwicGF0aCI6Ii80Nzc2MDA1NS8yOTM4ODI4MDctZWM0NmM4ZWYtNDlkNC00NGYwLTgwYzctYTMzMDg3ODNjNjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEwMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYThjMjFkZTUxODg3MWU3Njk4NGNmMmVhY2FkMTdkNjJjOTBjYTJjNjkzNmIwMmU3YmZlY2M3MjQ4YzEyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FLudKs9n4JyYJbPmB9wsKIAcQRQhbhJftGD__PBcV5o)
> 
> how to run `docker compose -f docker-compose.yml -f docker-compose.dev.yml build` code without internet?

I just wanna update something in index.html. After update, ı need to run this code to show changing. Because of that, ı need to run .dev code without internet
