### ISSUE TITLE
Could not receive image data Error , when 'Create a task from Backup' 

### ISSUE THREAD

**Issue by timiil** [opencv/cvat#7280]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

# 1, we upload a zip file to 'Create a task from Backup'， it shows the upload is OK

# 2, but when we click into the job, it is failed to say 'Could not receive image data Error'

![64ad7ffd3b2d1561da54610b8abe49a](https://github.com/opencv/cvat/assets/6621768/52e31112-d26d-405a-ac8e-7747d32c8169)
![ad528f507c057bd69015ae0cd5d5405](https://github.com/opencv/cvat/assets/6621768/46429d9a-0e53-418e-a905-cba8a414d9db)

i also upload this simple task zip file, any help is very very thanks :)

### Expected Behavior

expected can view the image

### Environment

```Markdown
Server version: 2.10.0
Core version: 12.2.0
Canvas version: 2.19.0
Ul version: 1.60.0


```

**Comment by bsekachev** [comment]
Hello, please check the link to a file you sent, it is incorrect.

**Comment by timiil** [comment]
[Uploading my_task_2.zip…]()
upload the test zip file here, only two png images inside

**Comment by timiil** [comment]
[my_task_2.zip](https://github.com/opencv/cvat/files/13722135/my_task_2.zip)
tks for your notice, i had upload the zip file again @bsekachev

**Comment by bsekachev** [comment]
``stop_frame`` in `task.json` has incorrect value `2`, because there are two images with indexes `0` and `1`. So, the correct value is `1`.

**Comment by timiil** [comment]
thanks for your kindly reply, it is ok now. the stop_frame is really incorrect. thanks you.
