### ISSUE TITLE
Thank you for this software it is very good

### ISSUE THREAD

**Issue by AlphonsGwatimba** [opencv/cvat#729]
This is the best thing ever. Just the fact that to make an annotation you just have to click twice instead of clicking then holding down the mouse button and dragging like all the other annotators was enough to make me start using cvat. Especially how the bounding boxes have no fill is very good, unlike the others which are so annoying to use. The aws deployment, github syncing, auto annotation, its all amazing. When I can afford it one day I will make a donation 

Thank you

**Comment by nmanovic** [comment]
@AlphonsGwatimba , thanks for the feedback. Great to hear that! Even though it is the best issue ever submitted I have to close it. :)
