### ISSUE TITLE
Uploaded annotation does not show up in cvat web app?

### ISSUE THREAD

**Issue by bignfuse** [opencv/cvat#7290]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Upload the video and annotation to web application.

### Expected Behavior

I have a annotation in coco json format for ball tracking in videos. I want to upload the annotation along with the video. I want to visualize the bounding box drawn in each frame and correct it if it is wrong.

### Context

https://drive.google.com/file/d/1eOp4wlYzsalIoJ5EtfVkbXFRciUisEmS/view?usp=sharing 

You use the above link for downloading annotation

**Comment by bignfuse** [comment]
@bsekachev could look into this?

**Comment by bsekachev** [comment]
@bignfuse 

At least no one `"keyframe": true` in the provided annotations file. 
Only objects with `keyframe: true` will be saved to database when import annotation. Intermediate positions with keyframe: false are interpolated with linear algorithm in CVAT. 

The second thing I would recommend is to draw a track, save and export annotations and carefully compare format with your file.
