### ISSUE TITLE
./backend_entrypoint.sh: at least one subcommand required

### ISSUE THREAD

**Issue by deepthi960** [opencv/cvat#7296]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

cvat/ui                                    "./backend_entrypoin…"   53 minutes ago   Restarting (1) 20 seconds ago       is keep on restarting

**Comment by bsekachev** [comment]
Please, fill the issue template correctly, otherwise the issue will be closed

**Comment by deepthi960** [comment]
The CVAT UI page is inaccessible, and upon inspecting the Docker container using the docker ps command, it appears that the CVAT UI is not binding to any ports. Subsequently, I checked the container logs using docker logs container_ID and found an error message indicating:

"Available subcommands:
- bash <bash args...>
- init
- run <config name>

The error message suggests that at least one subcommand is required in the container's entrypoint script (backend_entrypoint.sh). The root cause of this issue is currently unclear.

Also I see that cvat/UI is keep on restarting 

cvat/ui                                    "./backend_entrypoin…"   3 hours ago   Restarting (1) 37 seconds ago

**Comment by bsekachev** [comment]
How can we reproduce the issue? What is your environment?

**Comment by deepthi960** [comment]
Build is successful,  but UI page is not working, also this is in our test environment.

**Comment by bsekachev** [comment]
Information to reproduce and system environment were not provided, I will close the issue.
