### ISSUE TITLE
How to have share file with serverless cvat?

### ISSUE THREAD

**Issue by Q-Tran** [opencv/cvat#7303]
I know this is QA and not appropriate here, but it seems like I do not have any permissions to post anything in the discussions tab

I initially set up the share file and it works correctly when using

docker compose up -d

I later needed to add my own custom model. No problem I went ahead and set up serverless cvat using

docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d --build

upon closer inspection it looks like the share volume isn't even being loaded, which I'm guessing means the override yml file isn't being seen. I tried adding -f docker-compose.override.yml, but that didn't work either.

Is there a way I can use serverless with an attached share file? How can I set that up?

**Comment by bsekachev** [comment]
If your override yaml file is correct, the command should work:

`docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.override.yml -f components/serverless/docker-compose.serverless.yml up -d --build`
