### ISSUE TITLE
Enhanced YOLO-Segmentation Annotation Import/Export

### ISSUE THREAD

**Issue by DaphnaNanovel** [opencv/cvat#7304]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

#### Description
I'm requesting improved support for seamlessly exporting and importing YOLO-segmentation annotations in CVAT, with a focus on preserving both masks and bounding boxes.

####  Current Workflow and Challenges
1. Export segmentation masks from CVAT.
2. Manually convert masks to YOLO-segmentation annotations.
3. Train YOLOv8-seg using the converted annotations.
4. Convert YOLOv8 annotations back into masks.
5. Re-upload masks into CVAT, but bounding box information is lost.

#### Desired Features
1. Direct YOLO-segmentation annotation export/import: Ability to directly export and import annotations in YOLO format without manual conversions.

#### Alternative Features
1. Bounding box preservation during mask-based workflows: Methods to ensure bounding box information is retained when masks are used for export/import.

**Comment by bsekachev** [comment]
Answered in a private channel. It is recommended to use COCO format.

**Comment by Cung-AGA** [comment]
> ### Actions before raising this issue
> * [x]  I searched the existing issues and did not find anything similar.
> * [x]  I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
> 
> ### Is your feature request related to a problem? Please describe.
> #### Description
> I'm requesting improved support for seamlessly exporting and importing YOLO-segmentation annotations in CVAT, with a focus on preserving both masks and bounding boxes.
> 
> #### Current Workflow and Challenges
> 1. Export segmentation masks from CVAT.
> 2. Manually convert masks to YOLO-segmentation annotations.
> 3. Train YOLOv8-seg using the converted annotations.
> 4. Convert YOLOv8 annotations back into masks.
> 5. Re-upload masks into CVAT, but bounding box information is lost.
> 
> ### Describe the solution you'd like
> #### Desired Features
> 1. Direct YOLO-segmentation annotation export/import: Ability to directly export and import annotations in YOLO format without manual conversions.
> 
> ### Describe alternatives you've considered
> #### Alternative Features
> 1. Bounding box preservation during mask-based workflows: Methods to ensure bounding box information is retained when masks are used for export/import.
> 
> ### Additional context
> _No response_

You can show me the second step "Manually Convert Masks to Yolo-Segmentation Annotations." I am in need of building a Segmentation problem for 2 subjects. Thank you
