### ISSUE TITLE
Missing Bounding Box and other annotation tools from toolbar

### ISSUE THREAD

**Issue by Q-Tran** [opencv/cvat#7307]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Serverless cvat running with the following

`docker compose -f docker-compose.yml -f docker-compose.override.yml -f components/serverless/docker-compose.serverless.yml up -d --build
`
Custom model deployed as well

`./serverless/deploy_gpu.sh serverless/custom`
![cvat_toolbar](https://github.com/opencv/cvat/assets/10189171/043e1a1f-e54e-4496-bcbf-2dcc7d8a379f)

### Expected Behavior

AI tools should be added along with other polygon tools like bounding boxes

### Context

I cannot add bounding box annotations

**Comment by bsekachev** [comment]
You do not see bounding boxes tool, ellipses tool, etc, because you have label configuration for the task/project where you specified exact type for a label (polygon). And do not have any other types there. At least one label with type `any` should be specified to display all primitive shapes.
