### ISSUE TITLE
Administration of users - not only about localhost ?

### ISSUE THREAD

**Issue by RoseDeSable** [opencv/cvat#7316]
Hi,
 my user has admin-rights. If I want access the admin panel by https://cvat-server/admin, I receive the error-message: 503 Service Unavailable. I have no local access on the container. Therefore I can't access django-panel by http://localhost.... What's to do ?

Best Regards
Rose

**Comment by bsekachev** [comment]
If you up CVAT on host: `cvat-server`, than correct URL for admin page is `cvat-server/admin`, http or https depending on your setup. You can't access it from localhost. 

Something is wrong with your configuration if you see 503 Service Unavailable.

**Comment by RoseDeSable** [comment]
Thanks,
 I try to correct it.

**Comment by RoseDeSable** [comment]
Ok,
 we have a proxy-server for termination of tls before the cvat-server. Because the page "admin" was reserved for the proxy, the url of cvat's admin couldn't be reached. After deleting the reservation I can call django.
