### ISSUE TITLE
Request error when using AI tool

### ISSUE THREAD

**Issue by HenriqueAJNB** [opencv/cvat#7323]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

On computer vision annotation tool:
1. Click on the AI tool
2. Select the label and use the default Segment Anything option
3. Click on the item to be segmented on the image of the desired area
4. Errors occurs

>Interaction error occurred
Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://nuclio-dashboard.internal.cvat.ai:8070/api/function_invocations"

![error](https://github.com/opencv/cvat/assets/54143210/f5eb75c3-1d18-4bff-a6af-a16ffc2e95fd)

### Expected Behavior

Segmentation happen without errors.

### Context

Can't segment any images with AI tools.

**Comment by bsekachev** [comment]
Hello, image size 7000x9000px is too big to be handled by AI tools
