### ISSUE TITLE
Customize shortcuts

### ISSUE THREAD

**Issue by liujisihan** [opencv/cvat#7324]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Describe the solution you'd like

My dataset is too large and I want define shortcut keys by myself to improve efficiency. For example right mouse click to delete a track boxs  or let cursor is a cross mode in default to avoid to create a new track by pressing "n". Does CVAT support setting shortcut keys? Thanks.

**Comment by bsekachev** [comment]
Duplicate of #747

**Comment by doantientai** [comment]
So the answer is still no I guess.
