### ISSUE TITLE
CVAT serverless function return type support

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#7328]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I would like to know all types returned by all serverless functions currently supported by CVAT

Does CVAT support rotation box object detection without server function type return

**Comment by bsekachev** [comment]
Hello, please, refer to #6332

> Does CVAT support rotation box object detection without server function type return

https://github.com/opencv/cvat/pull/6961

**Comment by KTXKIKI** [comment]
> 您好，请参考#6332
> 
> > CVAT是否支持无服务器函数类型返回的旋转框对象检测
> 
> #6961

thanks you so much
