### ISSUE TITLE
How to use prebuilt docker image?

### ISSUE THREAD

**Issue by blueclowd** [opencv/cvat#7329]
Hello, does anyone managed to run cvat using the prebuilt docker images? 
I have encountered many issues using docker compose on MacOS so wanna tryout the prebuilt docker images.
Is there a comprehensive document explaining how to use the two prebuilt docker images `cvat/server` and `cvat/ui`?
After pulling the two docker images from Docker Hub,

1. Should we run both images separately or is there a way to run both together?
2. If run separately, which one should run first?
3. After running the containers, are the rest of steps the same as building using docker compose?

Thanks

**Comment by blueclowd** [comment]
If use the below command to run cvat/server
`docker run -p 8080:8080 --name some-cvat-server -e CVAT_POSTGRES_HOST=cvat_db -e CVAT_REDIS_HOST=cvat_redis -d cvat/server
`
And got the error message in container log:
```
2024-01-06 17:50:18 ./backend_entrypoint.sh: at least one subcommand required
2024-01-06 17:50:18 
2024-01-06 17:50:18 available subcommands:
2024-01-06 17:50:18     bash <bash args...>
2024-01-06 17:50:18     init
2024-01-06 17:50:18     run <config name>
```

**Comment by bsekachev** [comment]
Hello,
That is not supported out of the box, but you may look how it works in our [CI workflow](https://github.com/opencv/cvat/blob/develop/.github/workflows/main.yml), where it uses prebuilt docker images in E2E testing
