### ISSUE TITLE
Labels rotated with images in portrait mode?

### ISSUE THREAD

**Issue by dzanaga** [opencv/cvat#733]
I am using CVAT to annotate a collection of images, some in landscape and some in portrait mode. The first image of the collection is in landscape mode (if this makes a difference).
On each image I draw a 'rectangular' polygon.
I exported the labels with CVAT xml format.

The labels for the images in landscape mode are good, while those for the images in portrait are rotated 90 degrees left. e.g. when I am burning the polygons to raster masks for an image in portrait mode, I have to rotate the original image 90 degrees left to have a correct mask.

Am I doing something wrong?

**Comment by bsekachev** [comment]
@dzanaga 

Hi,
When you create a task, all your image are in landscape mode? Do use use "rotate" functionality in CVAT client?

**Comment by dzanaga** [comment]
When I create a task I load in a folder from the share mount point and the folder contains a mixture of landscape and portrait images.
I didn't use any rotate functionality.
Also the images might be of different resolution. Is this a problem for CVAT?
I was expecting it to treat every image individually, even though now I realize that some tools like the interpolate one might not like that.

What would be the expected behavior here? CVAT handling correctly a task with incosistent (res, orientation) frames or raising an error on task creation?

**Comment by nmanovic** [comment]
@dzanaga ,

CVAT should handle the case correctly. Just try. I will close the issue for now. If you see any problems with annotations such images just submit a bug request. If you have more questions please ask them on gitter.im/opencv-cvat

**Comment by panban-ux** [comment]
Im having this issue on exif loaded photos. With labelImg and some another browser annotating tool BB boxes are where my objects are. Now when i import a task on CVAT with the above data (photos and annotations) there is a shift of phase between the images and annotations in CVAT by 90 degrees. While the image is counterclockwise annotations are on 0 and cannot syncronise them. Im wondering what the darknet gets for training

**Comment by bsekachev** [comment]
@panban-ux 

Please take a loot at this [reply](https://github.com/openvinotoolkit/cvat/issues/738#issuecomment-541958365)
