### ISSUE TITLE
I cannot create bounding box for annotations.

### ISSUE THREAD

**Issue by shuheiintokyo** [opencv/cvat#7330]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I cannot create bounding boxes from annotation. I watch YouTube channel to follow instructions, and the difference I found on my screen to the YouTube channel is upon Objects selectors, mine shows the key is locked and eyes shut.

**Comment by shuheiintokyo** [comment]
if there is any help, pls let me know.

**Comment by bsekachev** [comment]
May you share  a screenshot? Did you add labels to the task/project?

**Comment by shuheiintokyo** [comment]
Sorry that I didn’t reply earlier I tried in different pc and worked. Thank
you. Shuhei
