### ISSUE TITLE
502, 500: BadGateway Error and Internal server error when Launching cvat

### ISSUE THREAD

**Issue by bedanar** [opencv/cvat#7331]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Expected Behavior

I have installed cvat following the installation guide, my OS is Linux. After running the comman `docker compose up -d` the following happens in the Google Chrome:
<img width="1272" alt="Screenshot 2024-01-07 at 12 55 02 PM" src="https://github.com/opencv/cvat/assets/57563409/8e2db773-dc27-4411-b1b3-1e356930eb2d">
<img width="1273" alt="Screenshot 2024-01-07 at 12 59 42 PM" src="https://github.com/opencv/cvat/assets/57563409/b984cf92-409f-4d25-99ab-1bcc056c5822">
<img width="1470" alt="Screenshot 2024-01-07 at 1 00 01 PM" src="https://github.com/opencv/cvat/assets/57563409/5411db6a-177d-49ab-8f6d-f8403dced5bd">

### Context

I want to launch cvat. Previously I already had problems with launching (it was 405 error), but it was successfully solved. Now for some unknown reson I have this problem.

**Comment by bsekachev** [comment]
Project does not have variables defined like ``ENV_CVAT_REDIS_HOST``. 
And if you look at logs, you will see that this environment variable is unknown. Try to add it to compose files.

**Comment by blueclowd** [comment]
Also having the same 500 error, it seems like the internal server is not that stable. 
Based on my observation, it usually happens when the server is idle for a while or right at the login stage.
It can be solved by rerun the container (may need to tried a few times) on my side
Also wondering how to prevent this problem.

**Comment by bedanar** [comment]
okay, thanks, I will try

**Comment by bsekachev** [comment]
Version? 

If this is current develop branch, please pay attention that `ENV_CVAT_REDIS_HOST` was removed in this pull request: https://github.com/opencv/cvat/pull/7245 

But it is still used in the container. Did you try to rebuild docker images with `docker compose up -d --build`?

**Comment by bedanar** [comment]
I reinstalled the platform yesterday according to https://opencv.github.io/cvat/docs/administration/basics/installation/, I think it is the most recent version. I just did 'docker compose up -d --build', the error is still there.

**Comment by bsekachev** [comment]
@bedanar 

Try: 

```sh
docker compose down
git checkout v2.9.2
docker compose up -d
```

**Comment by bsekachev** [comment]
Alternatively, you may use:
``CVAT_VERSION=dev docker compose up -d`` to install develop version. 

And one more suggestion is to built everything from sources:
`docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

**Comment by bedanar** [comment]
Unfortunately, the error is still present after all these commands

**Comment by InRiPa** [comment]
Had the same issue as well. Wanted to try the compose variation again to maybe figure out, the reason that i can't get the helm chart alternative to run.

The proposed try
```bash
docker compose down
git checkout v2.9.2
docker compose up -d
```
worked for me. 

Got it fixed through learning that `docker system prune -a` [doesn't remove volumes anymore](https://github.com/docker/cli/issues/4028#issuecomment-1429538145)
Running (well aware, that I used it on a test system) `docker volume prune --all` resolved the issue for me. 
Full steps:
```bash
docker compose down
git checkout develop
docker system prune -a
docker volume prune --all
docker compose up -d
```

Maybe it helps.

**Comment by bsekachev** [comment]
Removing docker volumes is not necessary, and it is dangerous. Creating risk that you remove all existing data.

**Comment by mpolinowski** [comment]
@InRiPa Thank you for sharing.

I was able to get past the `cannot connect to the server` issue using [security_opt: seccomp:unconfined](https://github.com/opencv/cvat/issues/6038). But then I was running into `status 504 - method not allowed` errors when trying to  log in.

Nuking everything ended up working.

This did not help - `504`s remained:

```
docker compose down
git checkout v2.9.2
docker compose up -d
```

The following - as expected - got rid of all the data but left me with a so far functioning installation:

```
docker compose down
git checkout develop
docker system prune -a
docker volume prune --all
docker compose up -d
```

Now let's figure out how to restore projects from backups :)
