### ISSUE TITLE
Front page Elements with rego rules

### ISSUE THREAD

**Issue by thibaulttroadec** [opencv/cvat#7333]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Edit cvat/apps/iam/rules/projects.rego with : 
allow {
    utils.is_business
}
2. Rebuild and start docker
3. Connect with User in Business group.
 Projet are not show in front page (but the rules work when we try to access with directly link to project)

### Expected Behavior

I want to show all projects/tasks/jobs in frontpage with user in group Business.

**Comment by bsekachev** [comment]
Hello,
Try to setup Django Query object at the same file, it used to receive correct objects list from the database.

![image](https://github.com/opencv/cvat/assets/40690378/24e649d9-2970-4c49-b389-dc4892231a30)

**Comment by thibaulttroadec** [comment]
Thanks Bsekachev!
