### ISSUE TITLE
Privacy of Online Annotation

### ISSUE THREAD

**Issue by monkeygobah** [opencv/cvat#7343]
This might be a dumb question, but is the annotation online cvat.ai secure? I need to annotate some patient data and invite collaborators, but I do not want to upload the data if using the online service temporarily or permanently stores the data somewhere that is not local.

**Comment by bsekachev** [comment]
Data you upload in general stored on amazon servers in Ireland, EU. These data not available for other users without explicit assignment of a project/task/job.
