### ISSUE TITLE
Can we change the supported models?

### ISSUE THREAD

**Issue by hzlbbfrog** [opencv/cvat#7351]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I want to ask if we can use our self-trained automatic labeling model.

### Describe the solution you'd like

Maybe CVAT can provide a interface or tutorial to guide to us to achieve this.

**Comment by valGavin** [comment]
https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models

**Comment by bsekachev** [comment]
- On self hosted you may deploy your own serverless models with nuclio, please see the documentation
- On app.cvat.ai you may import models from Roboflow or Huggingface
- On both you may use automatic annotations via CLI, please see the guide: https://www.cvat.ai/post/an-introduction-to-automated-data-annotation-with-cvat-ai-cli

**Comment by hzlbbfrog** [comment]
Wow, thanks so much! They are very helpful!
