### ISSUE TITLE
Can not connect MinIO Bucket to CVAT as a S3 Storage due to Endpoint URL Error

### ISSUE THREAD

**Issue by ozangungortuhh** [opencv/cvat#7352]
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [x] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

Hello,

I am trying to attach a cloud storage (MinIO) to CVAT and could not figure out what endpoint I should be using.

I am hosting both MinIO and CVAT locally on my computer. 

CVAT is running on `localhost:8080` and MinIO is running on `localhost:9000`

By using the `127.0.0.1:9000` address, I am able to connect to MinIO from my python script and upload files to the bucket.

However, when I try to add it to CVAT as a storage, I get the error:

```
Could not create the cloud storage

Error: Request failed with status code 400. "Could not connect to the endpoint URL: "http://127.0.0.1:9000/test-bucket"".
```
Thanks for any suggestions in advance!

![Screenshot from 2024-01-12 17-24-30](https://github.com/opencv/cvat/assets/43760324/dde27aa9-3233-4aa0-849e-43c879697457)

**Comment by bsekachev** [comment]
`https://127.0.0.1:9000` is not reachable from inside the Docker container

**Comment by bsekachev** [comment]
You may look how we attach minio in our test environment: tests/docker-compose.minio.yml

**Comment by HalkScout** [comment]
For those who also find this:

I changed `http://<IP_Address>:9000` to `host.docker.internal:9000` and it works, although this is only good for a testing environment.
