### ISSUE TITLE
Bounding box coordinates not from rectangle but from skeleton

### ISSUE THREAD

**Issue by lillian-miles** [opencv/cvat#7353]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar, I am raising this issue because this one is closed: https://github.com/opencv/cvat/issues/5904
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I tried to use the functionality recently and think that this issue is happening again. I am using the tool present on the web interface https://app.cvat.ai/
Below image contains both the bbox that I selected myself and the one through the skeleton with the keypoints.

(https://github.com/opencv/cvat/assets/91839547/fa201786-81ce-4fc3-90d7-9f1709381d1e)
![img1](https://github.com/opencv/cvat/assets/156352027/b4d7b649-9ee4-40ad-8124-0b0cdfcc72d9)

I am exporting to the COCO Keypoints 1.0 format and as can be seen from the below image, the bbox co-ordinates are clearly not from the rectangle that I selected but from the skeleton.

(https://github.com/opencv/cvat/assets/91839547/13f544d8-8194-4b2d-bcf6-ca00e3c24f61)
![img2](https://github.com/opencv/cvat/assets/156352027/360b0018-7a4c-4a3a-91a3-d947a6db2eb5)

The web version shows me the below version.

Server version: 2.10.0 Core version: 14.0.3 Canvas version: 2.19.1 UI version: 1.61.1

### Expected Behavior

The x,y coordinates returned by the json file should be for the bbox and not for the skeleton

**Comment by bsekachev** [comment]
You need to group bounding box and skeleton together if they relate to the same object
