### ISSUE TITLE
Changing Label id numbers reverts to default

### ISSUE THREAD

**Issue by dronespov** [opencv/cvat#7355]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Specify multiple Labels for a task
2. Upload Images
3. Start annotating 
4. In the right side menu, Click on labels
5. Click on a label number
6. change label numbers
7. save task
8. refresh page
9. click on labels in the right side menu
10. observe label numbers revert to default

### Environment

```Markdown
- Chrome 
- Safari
- MacBOOK PRO 2021
```

**Comment by bsekachev** [comment]
Hello, it does not clear what you mean by "changing label numbers". Please, clarify.

**Comment by dronespov** [comment]
I'll show you, see attached video. In this video you'll see that when I chan

https://github.com/opencv/cvat/assets/77562708/ca034413-4f4e-427c-b757-4a874eea6172

**Comment by bsekachev** [comment]
That is not a bug, shortcuts are not expected to be saved.

**Comment by dronespov** [comment]
@bsekachev Then how do I change the Label Id number? This link is the only documentation I have found for changing label id number - fast label changing

https://opencv.github.io/cvat/docs/manual/basics/objects-sidebar/#:~:text=Fast%20label%20change&text=In%20order%20to%20do%20it,label%20name%20on%20the%20sidebar.

- Andrew k.

**Comment by bsekachev** [comment]
I do not know what you are trying to achieve here, but:
- That is not related somehow to your config file
- This is UI feature for quickly assigning labels using shortcuts

**Comment by dronespov** [comment]
@bsekachev In my config file, Dog: 2. Within CVAT, the Label is Dog:1. Within CVAT, I am trying to change Dog: 1 to Dog: 2 so the exported masks follow my config file.

**Comment by bsekachev** [comment]
There is not a "class id" within CVAT. Objects only have text labels.

**Comment by dronespov** [comment]
Then how will the model know the different between classes if there's no Class id to reference? Example of class id 

The issue I'm facing is that when I export the dataset for yolo segmentation 1.1, convert masks to polygons, then train, the model is classifying dog and cat the same since CVAT is defining both as the same class. 

Cat: 1
Dog: 2

**Comment by bsekachev** [comment]
CVAT does not have `yolo segmentation 1.1` format. How can you export into it?

**Comment by dronespov** [comment]
see attached 
<img width="1241" alt="Screenshot 2024-01-15 at 12 56 26 AM" src="https://github.com/opencv/cvat/assets/77562708/fd0faea9-125c-4d2b-b4b2-82247a1fa241">

**Comment by bsekachev** [comment]
I do not argue with you, but you should know that it is not YOLO segmentation format. 

YOLO itself supports only bounding boxes, there are some customizations, like this one: https://docs.ultralytics.com/datasets/segment/ 
Such custom format are not supported. 

Format on the screenshot is a regular segmentation mask, and if you labeled objects in CVAT as different classes, they will have different colors on bitmap where a specific color bound to a specific class. You may find this mapping in a text file. Please, refer to the specification: https://opencv.github.io/cvat/docs/manual/advanced/formats/format-smask/

**Comment by dronespov** [comment]
@bsekachev When I convert the exported Segmentation class to a polygons in a txt format, Im having to change the <class-index> for all txt files. This is very time consuming, especially on a large dataset with multiple different classes. From CVAT, How can I export the Segmented Masks and Convert the Segmentation Class to txt with the correct <class-index>?

Here's a snippet of my code 


import os

import cv2

input_dir = 'path/to/SegmentationClass'
output_dir = 'path/to/dir'

for j in os.listdir(input_dir):
    image_path = os.path.join(input_dir, j)
    # load the binary mask and get its contours

    # Skip non-image files
    if not j.lower().endswith(('.jpg', '.jpeg', '.png')):
        print(f"Skipping non-image file: {image_path}")
        continue


    mask = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    # Check if the image was successfully loaded

    if mask is None:
        print(f"Error reading image: {image_path}")
        continue
    _, mask = cv2.threshold(mask, 1, 255, cv2.THRESH_BINARY)

    H, W = mask.shape
    contours, hierarchy = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # convert the contours to polygons
    polygons = []
    for cnt in contours:
        if cv2.contourArea(cnt) > 200:
            polygon = []
            for point in cnt:
                x, y = point[0]
                polygon.append(x / W)
                polygon.append(y / H)
            polygons.append(polygon)


    # print the polygons
    with open('{}.txt'.format(os.path.join(output_dir, j)[:-4]), 'w') as f:
        for polygon in polygons:
            for p_, p in enumerate(polygon):
                if p_ == len(polygon) - 1:
                    f.write('{}\n'.format(p))
                elif p_ == 0:
                    f.write('0 {} '.format(p))
                else:
                    f.write('{} '.format(p))

        f.close()
else:
        print("No contours found in {image_path}")
