### ISSUE TITLE
Annotation for COCO format for rotated bounding box with theta  

### ISSUE THREAD

**Issue by kkamalrajk** [opencv/cvat#7356]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Uploaded images
2. Unable to upload annotations in .json format (COCO with theta) for these images 

### Expected Behavior

Could not upload annotation for the [task 449744](https://app.cvat.ai/tasks/449744)

Error: Request failed with status code 400. "Failed to import item (None, 'default'): Invalid annotation field 'id' type '<class 'str'>'. Expected <class 'int'>"..

**Comment by bsekachev** [comment]
Hello, How did you get this annotations file?

**Comment by kkamalrajk** [comment]
Hello, I have created similar to COCO format 
[output (1).json](https://github.com/opencv/cvat/files/13936232/output.1.json)

**Comment by bsekachev** [comment]
Please, be sure your file has correct format. Try to compare the file with another file, exported as COCO from CVAT.

**Comment by kkamalrajk** [comment]
Thanks you @bsekachev for the quick response. I am able to upload the data in the correct format.
I am able to see a shift in the bounding box. Attached 2 images one plotted locally in python and the other from CVAT. 
Could you please help me with it ?
<img width="749" alt="Screenshot 2024-01-16 at 2 40 29 PM" src="https://github.com/opencv/cvat/assets/152950867/412392cd-4f03-4d52-8134-26a0abc2dbc7">
<img width="1470" alt="Screenshot 2024-01-16 at 12 52 34 PM" src="https://github.com/opencv/cvat/assets/152950867/77c022a4-6bdc-47e0-9f26-51df3d9326de">
