### ISSUE TITLE
The "Move to project " has gone?

### ISSUE THREAD

**Issue by kitterive** [opencv/cvat#7360]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I upgrade my cvat version from 2.0.0 to 2.9.2, the  "Move to project " pop menu of task has gone?  how to show it?

this is my version
![my](https://github.com/opencv/cvat/assets/16040174/06f8d089-84b0-4826-97d9-d2949f61bd0e)

while this is the mannul documention 

![网站](https://github.com/opencv/cvat/assets/16040174/32e52f9c-f942-487b-a427-5c3f1f233a53)

**Comment by bsekachev** [comment]
"Move to project" works for tasks not in any project

**Comment by kitterive** [comment]
oo, thanks.
