### ISSUE TITLE
Polygon label exceeding max amount of points.

### ISSUE THREAD

**Issue by EmielFeryn1** [opencv/cvat#7366]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Open job
2. Start labeling
3. Made polygon with 4 points
<img width="214" alt="image" src="https://github.com/opencv/cvat/assets/91069614/0125b238-c2d4-4b77-9b34-315d1acf6d2e">

4. After looking at output i noticed that there were polygons with 5 points which were not intended and which i didn't notice during labeling
<img width="263" alt="image" src="https://github.com/opencv/cvat/assets/91069614/58ada147-52d7-4db8-93e9-f5bd1fe8a99b">

Is there something i did wrong or is this a bug?

### Expected Behavior

Polygons with 4 points

**Comment by bsekachev** [comment]
Hello,

- When you specify number of points, it only defines maximum number of points you may left during creating. If you can provide steps to reproduce a case when you may set more points during drawing, its is a bug.
- You still may prevent adding more points, by pressing N (before all points are set). For example after 3rd point, the polygon will be created with 3 points in this case.
- You still may modify a polygon after creating, adding or removing points, dragging polygons, etc.
- It, finally, does not guarantee a polygon with exact number of points. For example if you set points out of the frame, final algorithm will be applied to cut polygon. As result, a polygon with more points may appear.

Example:
![image](https://github.com/opencv/cvat/assets/40690378/c2523fb0-fc6b-4bf9-b4dd-fa19183244d2)

![image](https://github.com/opencv/cvat/assets/40690378/738bdbea-19eb-4a31-b2ab-95eaf6fdf008)

**Comment by EmielFeryn1** [comment]
Thank you very much for the clear explanation!

Is there a way to disable this/get notified or is the only option to do this in post processing?

**Comment by bsekachev** [comment]
There is no ability to disable this behavior.
And, actually it is not clear if the tool continue working correctly in all cases with negative coordinates, we did not test it.
