### ISSUE TITLE
Offset of the bounding box in COCO format with rotation

### ISSUE THREAD

**Issue by kkamalrajk** [opencv/cvat#7367]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Possible Solution

I have uploaded COCO format json file along with images for rotated bounding boxes.
<img width="749" alt="Screenshot 2024-01-16 at 2 40 29 PM" src="https://github.com/opencv/cvat/assets/152950867/f8e266f1-5db5-4c74-9b25-462b222a67f5">
<img width="1470" alt="Screenshot 2024-01-16 at 12 52 34 PM" src="https://github.com/opencv/cvat/assets/152950867/ea101f8d-70f7-4223-8773-0d31df15388d">

I am able to see a shift in the bounding box. Attached 2 images one plotted locally in python and the other from CVAT.
Could you please help me with it ?

**Comment by bsekachev** [comment]
Hello

If you believe it is a bug, we need to be able to reproduce it, but that is not possible without minimum reproducing dataset (at least one image with annotations).
