### ISSUE TITLE
yolo 1.1 export doesn't work

### ISSUE THREAD

**Issue by Bowensa** [opencv/cvat#7369]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

go to menu  and select: export job dataset
then select yolo1.1 and fill in a custom name
after that press OK
then it says the following: Annotations export was started for job #"JOB NR" Download will start automatically as soon as the Annotations is ready.
after 30 minutes nothing has happend yet

### Expected Behavior

when going to the menu and selecting export job dataset i select yolo 1.1. then i give it a name for exaple "yolodataset.zip".  then i press oke and expect the dataset.zip to be downloaded

### Context

it not starting the download for the dataset. no matter how long i wait it does not start the export. please fix this or tell me how to fix this so i can download my custom dataset

**Comment by mamdmmdi** [comment]
i had exactly same problem i dont know what should i do. its keep requesting to server but no response

**Comment by mamdmmdi** [comment]
It is stuck on loading mode and nothing happens 
![Screenshot 2024-01-17 201159](https://github.com/opencv/cvat/assets/121638259/7c6e6aae-455b-449e-ac89-86c1c48544ca)

**Comment by Bowensa** [comment]
mine does  the exact same. yesterday i had the same problem but when i refreshed and started it again it worked for me. but today it doesn't work

**Comment by mamdmmdi** [comment]
> mine does the exact same. yesterday i had the same problem but when i refreshed and started it again it worked for me. but today it doesn't work

I refreshed and reapplied several times but nothing changed.

**Comment by bsekachev** [comment]
Do you experience that on app.cvat.ai or self-hosted solution?

**Comment by Bowensa** [comment]
on app.cvat.ai. but i just tried it again and it worked

**Comment by janwillemwind** [comment]
I'm experiencing the same problem. I read something about queues on the server side? is that right? does the paid subscription have the same problems?

**Comment by seasenzzr000** [comment]
I'm experiencing the same problem. Open export in django-rq/ to show that there are export jobs in the queue. But we haven't been able to export it. F12 An error message is displayed on the console. How should I handle this?please help me.
![1](https://github.com/cvat-ai/cvat/assets/103553607/17413609-5998-4f17-9d38-ef5edfd4d59b)
![2](https://github.com/cvat-ai/cvat/assets/103553607/2c5ca152-8f2c-486c-a89d-7c799b8d6607)
@bsekachev
