### ISSUE TITLE
cvat tool is not working

### ISSUE THREAD

**Issue by madhuleventm** [opencv/cvat#737]
Hello, 
I am not able to open the cvat tool with localhost:8080. For further information i recently used cvat a week ago but not able to open now. Please help out.

**Comment by nmanovic** [comment]
@madhuleventm , please provide log information. You can get it using the command `docker logs cvat`. Also if you shutdown your computer and run it again probably a temporary file inside a docker container doesn't allow apache to start again. Please run two commands below (add extra arguments if it is necessary) to remove such temporary files:

```
docker-compose down
docker-compose up -d
```

**Comment by madhuleventm** [comment]
Thanks a lot. The two docker commands worked as a charm.

 

 

 

Thanks & Regards,

Madhu

Business Development Manager

Leventm Technologies Pvt Ltd.

 <http://www.leventm.com/> www.leventm.com

+91-9945839913

**Comment by nmanovic** [comment]
I will close the issue in this case.

**Comment by madhuleventm** [comment]
Surely

 

Thanks & Regards,

Madhu

Business Development Manager

Leventm Technologies Pvt Ltd.

 <http://www.leventm.com/> www.leventm.com

+91-9945839913
