### ISSUE TITLE
Can't remove annotations (keypoints skeleton and bounding box)

### ISSUE THREAD

**Issue by devvaibhav455** [opencv/cvat#7376]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I referred to [https://opencv.github.io/cvat/docs/manual/basics/top-panel/#:~:text=Remove%20Annotations%20%E2%80%94%20calls%20the%20confirmation,the%20tracks%2C%20on%20the%20selected](url) for deleting annotations.

Input video: [https://www.youtube.com/watch?v=_zudxPk8WuQ](url)

1. Create a task and upload a video to it.
2. Open the annotation view. 
3. Select frame # 197 (just for the sake of it.../ any frame in the middle)
4. Draw a rectangle bounding box and keypoints skeleton using Track mode for both.
5. All frames from 197 till the end will show the BB and skeleton
6. Since, I don't want the annotations till the end of the video, I plan to delete annotations from 201 till end.
7. Select Menu --> Remove Annotations --> Select Range from 201 till 2456

Before:
![image](https://github.com/opencv/cvat/assets/91839547/bbeafee7-8a37-4f0e-b82a-7c38db022a49)

After:
![image](https://github.com/opencv/cvat/assets/91839547/8583fccd-65c0-4b0e-8e2f-2c2cc8242d45)

CVAT version:
![image](https://github.com/opencv/cvat/assets/91839547/40a952ae-b805-4cf9-9662-a2fd3c198e56)

### Expected Behavior

1. Only the annotations between the frame range [197,200] should be shown after doing so but as can be seen in the images above, annotations are still shown on the screen for all the frames.
I tried saving after performing the remove annotations action but it still remains the same.

**Comment by bsekachev** [comment]
Hello,

Your understanding of "Remove annotations" feature is wrong. 
To stop automatic propagation track on frame 201 set "Outside" property to True on this frame for the skeleton and bounding box. Please, refer to documentation (Track mode basics) for more details. 

Track is a type of object that exist on many frames, if you remove it, it will be removed from all frames.

**Comment by devvaibhav455** [comment]
@bsekachev  Thanks for the quick response. I see. "Remove annotations" doesn't work on the "Track" but works if I draw the BB and skeleton using shape.
