### ISSUE TITLE
CVAT - Depth estimation of everything

### ISSUE THREAD

**Issue by KTXKIKI** [opencv/cvat#7389]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

CVAT may be able to add depth estimation to everything, which would be a good feature
https://github.com/LiheYoung/Depth-Anything

**Comment by bsekachev** [comment]
I do not think that CVAT may effectively handle such kind of annotations, as depth. Usually they are heatmaps.
One heatmap, of course may be re-presented as 256 binary masks (or less in case of quantization), but working with these masks in the tool would be painful.
