### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by serwansj** [opencv/cvat#7396]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Whenever i am trying to access the CVAT server on my host, I encounter the error `Cannot connect to the server` (see image below). Specifically, it is the request to `/api/server/health/?format=json&org=` that fails as can be seen in the network logs. 

Executing `docker exec -t cvat_server python manage.py health_check` on the machine that runs the CVAT server also hangs. I also checked docker logs and didn't spot any hints to the issue.

This only happens after the CVAT server has been running for a couple of days. If I restart the server, everything works fine again for a couple of days.

<img width="1512" alt="Screenshot 2024-01-24 at 17 04 39" src="https://github.com/opencv/cvat/assets/44338225/709173fc-87e0-4698-b801-7ec38ac22393">

### Expected Behavior

Having access to the CVAT UI

**Comment by antortjim** [comment]
I have the exact same problem, and I am trying with multiple versions of the repo (`master`, `develop` and a couple of tags). I come from an existing installation that used to work but after a while not using it, now I needed to get back to it and I am encountering this issue.

**Comment by antortjim** [comment]
This screenshot shows the errors I get with master (`a33f7f57088744bab61f18e8a8cf6528a0c22fd2`).
![image](https://github.com/opencv/cvat/assets/13869571/864374e6-5dee-453b-bfc8-feb40ec7e2e9)

**Comment by antortjim** [comment]
The problem is my root partition was >90% used. I saw the message in the logs, but didn't realize it was an error (thought it was just a warning). I am not sure this is the desired behavior anyway.

**Comment by serwansj** [comment]
unfortunately, on my end that is not the issue. it also stops working even if the machine is not being used at all.

**Comment by bsekachev** [comment]
Hello, please provide output of 'docker ps' and 'docker logs cvat_server'

**Comment by antortjim** [comment]
> unfortunately, on my end that is not the issue. it also stops working even if the machine is not being used at all.

I meant it seems that if 90% of the storage is used, cvat won't work (even if the computer is not busy or not being used at all like you said. So it's not RAM, it's storage.

**Comment by bsekachev** [comment]
> I meant it seems that if 90% of the storage is used, cvat won't work

That is true

**Comment by serwansj** [comment]
@antortjim i got that, however, what i meant was that even if nothing is changed in the storage it also stops working.

@bsekachev i will post the outputs and logs once it stops working again. just restarted the server after i opened this issue, so i will probably have to wait a couple of days

**Comment by stone100010** [comment]
事情没有大家想象的那么麻烦，重启一下你的服务器即可，一切都会恢复如常。祝各位好运~

**Comment by bsekachev** [comment]
Please, provide all logs from `cvat_server`, `cvat_traefik` and `cvat_redis`. 

Also, please try to upgrade, we got rid of `keydb` storage (in `cvat_redis` container) because it was not stable.
