### ISSUE TITLE
error response from daemon : Container 9073356edadc... is restarting, wait until the container is running

### ISSUE THREAD

**Issue by jlam29** [opencv/cvat#7397]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. `git clone https://github.com/opencv/cvat`
2. `cd cvat`
3. `export CVAT_HOST=ip-address`
4. `docker compose up -d`
5. `docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'`
6. Error response from daemon: Container 9073356edadc07b1a37971d6ee28bc2c9441869b1acb249137b6095c8809424c is restarting, wait until the container is running
7. `docker exec -it cvat_server /bin/bash` 
8. Error response from daemon: Container 9073356edadc07b1a37971d6ee28bc2c9441869b1acb249137b6095c8809424c is restarting, wait until the container is running

[docker_ps.txt](https://github.com/opencv/cvat/files/14044371/docker_ps.txt)
[docker-logs-cvat_server.txt](https://github.com/opencv/cvat/files/14044373/docker-logs-cvat_server.txt)
[docker-logs-cvat_db.txt](https://github.com/opencv/cvat/files/14044402/docker-logs-cvat_db.txt)

### Expected Behavior
CVAT UI should have been displayed without issues.
There is an access to the web-server page http://localhost:8088/  but there is error '404 page not found' on the web page.  
The same for Traefik : http://localhost:8090/ expected "404 page not found"
For an external access it is the same result: http://ip-address:8088/ : page not found

### Possible Solution
1. Upgrade postgresql : [https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/#how-to-upgrade-postgresql-database-base-image](url) 
check version after upgrade : postgres (PostgreSQL) 10.23 (Ubuntu 10.23-0ubuntu0.18.04.2)
finally run : `docker compose pull`

2. Use an old cvat image?

### Context
I am using chromium web interface. 

### Environment

```Markdown
docker version :
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:03 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:51:03 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
Are you using Docker Swarm or Kubernetes? No
Operating System and version : Ubuntu 18.04
```

**Comment by antortjim** [comment]
This seems to happen because my drive is > 90% used. I did see the messages in the logs, but I thought they were just  warnings. Indeed, cleaning up my drive makes cvat work.

**Comment by jlam29** [comment]
> This seems to happen because my drive is > 90% used. I did see the messages in the logs, but I thought they were just warnings. Indeed, cleaning up my drive makes cvat work.

Thanks for your answer. I check the drive - 39% free space (close to 20Gb free). 

![Screenshot from 2024-01-25 09-17-00](https://github.com/opencv/cvat/assets/90317048/afd91a39-e4a1-4156-8938-86886e9b9700)
![Screenshot from 2024-01-25 09-18-35](https://github.com/opencv/cvat/assets/90317048/184837a1-b65d-42e0-9f4e-b76754d02c62)
 
Also I clean up the disk as explained here [https://itsfoss.com/free-up-space-ubuntu-linux/](url)

1. `sudo apt-get autoremove` : 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded
2. `sudo apt-get autoclean`
3. `sudo journalctl --vacuum-time=3d`

**Comment by jlam29** [comment]
Additional comment : when I close the docker an error is indicated : Network cvat_cvat : failed to remove network cvat_cvat: Error response from daemon: error while removing network: network cvat_cvat id 050332d193a3060ec88e9e54941f041aacc81266c6e184457edbcb7076b7cbfc has active endpoints

1. `docker compose down`

> [+] Running 18/17
 ✔ Container cvat_worker_analytics_reports  Removed                                                                         0.9s 
 ✔ Container cvat_utils                     Removed                                                                         1.4s 
 ✔ Container cvat_worker_export             Removed                                                                         0.9s 
 ✔ Container cvat_worker_annotation         Removed                                                                         0.9s 
 ✔ Container cvat_worker_quality_reports    Removed                                                                         0.9s 
 ✔ Container cvat_grafana                   Removed                                                                         3.2s 
 ✔ Container cvat_worker_webhooks           Removed                                                                         0.9s 
 ✔ Container cvat_worker_import             Removed                                                                         0.9s 
 ✔ Container cvat_ui                        Removed                                                                         1.1s 
 ✔ Container traefik                        Removed                                                                         3.6s 
 ✔ Container cvat_vector                    Removed                                                                         3.0s 
 ✔ Container cvat_server                    Removed                                                                         0.8s 
 ✔ Container cvat_redis_inmem               Removed                                                                         1.9s 
 ✔ Container cvat_db                        Removed                                                                         1.9s 
 ✔ Container cvat_opa                       Removed                                                                         0.8s 
 ✔ Container cvat_redis_ondisk              Removed                                                                         1.8s 
 ✔ Container cvat_clickhouse                Removed                                                                         0.2s 
 ✘ Network cvat_cvat                        Error                                                                           0.0s 
failed to remove network cvat_cvat: Error response from daemon: error while removing network: network cvat_cvat id 050332d193a3060ec88e9e54941f041aacc81266c6e184457edbcb7076b7cbfc has active endpoints

**Comment by bsekachev** [comment]
@jlam29 

> The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested.

ARM architecture is not supported

**Comment by jlam29** [comment]
> @jlam29
> 
> > The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested.
> 
> ARM architecture is not supported

Ok, thanks for your answer

**Comment by antortjim** [comment]
@jlam29 I just removed files from my disk

**Comment by antortjim** [comment]
Oh I am so sorry , my issue is actually https://github.com/opencv/cvat/issues/7396, I somehow mixed them up. So I have no idea if this is related to space

**Comment by jlam29** [comment]
> @jlam29 I just removed files from my disk
> Oh I am so sorry , my issue is actually https://github.com/opencv/cvat/issues/7396, I somehow mixed them up. So I have no idea if this is related to space

Thanks for this precision.
