### ISSUE TITLE
question regarding Cloud storage

### ISSUE THREAD

**Issue by PushpakBhoge512** [opencv/cvat#7404]
the behavior I am looking for is as follows
1) I add an AWS bucket 
2) I create a task using objects from that bucket
3) when a user opens that task, the image should be downloaded on the client side directly from the s3 pre-signed URL and then cached on the client side

does CVAT support this behavior? If not then how does the current implementation work also why not have this type of behavior

While creating a task with cloud storage use_cache set to True it takes good long time to load it. does it download all images to generate manifest.jsonl for data?

**Comment by bsekachev** [comment]
Hi, it should work almost us you described, two moments:

1. It has also server side cache (disk cache, key db, rvrocks depends on CVAT version).
2. For videos it will download the video from the cloud storage, because it needs to prepare all the data chunks beforehand.

**Comment by PushpakBhoge512** [comment]
Hi, @bsekachev when you server-side cache does that mean the images are saved as cache on the server, and then the server sends those relatively large image files to the client side by server?

also, what are the recommended system requirements for CVAT setup?  In my setup, I am using the latest 2.10.1, and I am experiencing server crashes
