### ISSUE TITLE
Uploading images through REST API

### ISSUE THREAD

**Issue by 4sfaloth** [opencv/cvat#741]
Hi,

I have succesfully created a task through the REST API, and now am trying to upload images to it (also through the REST API).

I have seen https://github.com/opencv/cvat/issues/493 and tried to replicate the code there, but still I always get a 500 error :\

My code below:

> image_filename = r'...\image.jpg'  # (obviously full path to image here)
> image_file = open(image_filename, encoding="utf8", errors='ignore').read()
> 
> image_data = {
>     'client_files': [image_file]
> }
> 
> response = session.post(cvat_url + f'tasks/{task_id}/data', json=image_data,
>                                   stream=False, headers={'Authorization': f'token {token}'})

Thanks in advance

**Comment by nmanovic** [comment]
Hi @4sfaloth , please ask questions in gitter next time. Issues only for bugs or feature requests. Please look here: https://github.com/opencv/cvat/blob/f271d2a969d30806d5e86a7cc47159c7192e37ba/utils/cli/core/core.py#L24

I will close the issue for now.

**Comment by nguyengocaocuong** [comment]
@nmanovic  
I have tested this line of code 
 **_files = {f'client_files[{i}]': open(f, 'rb') for i, f in enumerate(resources)}_** 
 but I get the following response: 
**_{'image_quality': ['This field is required.']}_**

My code bellow:
_**def add_resources_to_tasks(tasks_id, resources, resources_type='LOCAL'):
    print(tasks_id)

    task_url = f'{URL}/tasks/{tasks_id}/data'
    data = {'image_quality': 70}
    files = None
    if resources_type == 'LOCAL':
        files = {
            f'client_files[{i}]': open(
                f, 'rb') for i, f in enumerate(resources)
        }
        # files['image_quality'] = 70
        # print(files)
    else:
        data['remote_files'] = resources

    headers = {
        "accept": "application/json, text/plain, */*",
        "content-type": "multipart/form-data;application/json; boundary=----WebKitFormBoundaryQnbWISKWNB65vyl0",
        "authorization": f"Token {str(key)}",
        "cookie": f"csrftoken={str(token)}; sessionid={str(sessionid)}",
        "x-csrftoken": str(token)
    }
    response = requests.post(task_url, json=data, files=files, headers=headers)**_
