### ISSUE TITLE
Is there a way to fix the skeleton's bounding box and move only keypoints inside ?

### ISSUE THREAD

**Issue by medphisiker** [opencv/cvat#7411]
Hello,

Is there a way to fix the skeleton's bounding box and move only the points inside ?

I have been looking through various tutorials on data labeling for the key point detection task.

I also read about deep learning models that solve this task: Keypoint RCNN([link](https://learnopencv.com/human-pose-estimation-using-keypoint-rcnn-in-pytorch)) and YOLOv8([link](https://docs.ultralytics.com/tasks/pose/)).

As I understand, the task of detecting keypoints consist from several stages. First, we detect the object we need by bounding box, for example, a person, and then in this bounding box we look for masks with an active single pixel that corresponds to one key point.

We need a bounding box that highlights the entire object so that the detector can find it.

The tutorial from roboflow([link](https://blog.roboflow.com/train-a-custom-yolov8-pose-estimation-model/)) shows the process of marking up skeleton in roboflow.
First, we set a bounding box and then move the key points inside it. When moving the key points, the bounding box itself does not move. We can independently move the boundaries of the bounding box under the object and separately each key point. They don't affect each other.

![roboflow](https://github.com/opencv/cvat/assets/4876436/4b3aa20d-83a9-4dba-87fb-b5b485618a40)

When we place the skeleton in the CVAT, changing the bounding box scales and shifts all the key points inside it. Conversely, moving a key point changes the bounding box.

![cvat](https://github.com/opencv/cvat/assets/4876436/cb70ee00-45e1-49a5-92aa-2c82ab4f3040)

Is there any option in the CVAT to edit them separately in the same way as in roboflow? Or so that the bounding box is not recalculated every time a key point is moved?

As a markup tool, I like CVAT more than rotoflow ) But now I need to label up the data to search for key points in fish and in robolow I can do this, but not in CVAT.

I use self-hosted CVAT v2.10.2.

**Comment by bsekachev** [comment]
You do not have bounding box in your example, you have only skeleton.
If you need a bounding box, annotate a bounding box. Group it together with skeleton using grouping.

Dublicate #7193

**Comment by medphisiker** [comment]
Thank you for your quick reply. I will deal with the keypoint labeling further.
