### ISSUE TITLE
Support for stylus

### ISSUE THREAD

**Issue by DaveBGld** [opencv/cvat#7414]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Describe the solution you'd like

Some computers and most tablets support touch based drawing, and some have stylus based drawing.

I think it would add great flexibility and ease of use to support stylus

**Comment by bsekachev** [comment]
Duplicate #3744
