### ISSUE TITLE
Python SDK: Missing parameter for "Dataset repository URL" in create_from_data() method

### ISSUE THREAD

**Issue by dpovision** [opencv/cvat#7415]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I want to automatize the job task creation via high-level Python SDK API of CVAT and I can't find a parameter for the "Dataset repository URL" to create a backup storage.

### Describe the solution you'd like

Please provide a possibility for the UI field "Dataset repository URL" in the high-level Python SDK API.

### Describe alternatives you've considered

I tried to define the "Dataset repository URL" after task creation, but this seems also not possible via Python SDK.

### Additional context

![advanced_config](https://github.com/opencv/cvat/assets/58401814/8bc5cb33-24e4-46d4-8618-6646e8afaf8e)

**Comment by PMazarovich** [comment]
That functionality was removed from CVAT

**Comment by dpovision** [comment]
Thank you very much for your response.
Do you know the reason and how an automatic backup repository can be defined now or has it to be done manually?

**Comment by PMazarovich** [comment]
From my understanding, this is impossible with native cvat fratures.
Here is the PR with explanation https://github.com/opencv/cvat/pull/6904
You can add your comment there and explain your usage, maybe that feature will be resurrected

**Comment by dpovision** [comment]
Thank you very much again for your response. I left a comment in the other task #6904 and will close this task, since the feature is now not available anymore and therefore this parameter is technically spoken not missing anymore. But maybe we have luck and the feature is implemented again in future. :-)
