### ISSUE TITLE
Question: how to make this font size bigger and re-compile the server

### ISSUE THREAD

**Issue by Hegelim** [opencv/cvat#7418]
I have some images hosted on a CVAT server which is compiled and running on a AWS EC2 instance. How can I make the text font inside the red rectangle box larger? Where's the part of the code I need to change and how to recompile it without losing data?
![image](https://github.com/opencv/cvat/assets/55818214/8eb0d8a9-62f8-44bd-b7ad-fa3addf99772)
Any help is appreciated.

**Comment by bsekachev** [comment]
You may setup font size in the tool.

![image](https://github.com/opencv/cvat/assets/40690378/580483d3-7758-4928-9ca2-8b2f051bd72f)
