### ISSUE TITLE
Suspicious URL pattern warning during deployment

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#742]
**The problem**
[Documented installation steps for Ubuntu 18.04](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#ubuntu-1804-x86_64amd64) produce the following warning message during the deployment.

**How to reproduce**
``` bash
$ docker-compose build
$ docker-compose up -d
$ docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'

System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern 'api/swagger.<slug:format>$' [name='schema-json'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
Username (leave blank to use 'django'):
```

**Environment**
- OS: Ubuntu 18.04
- Commit SHA: f537236e11f9428a3bc57475c001122a8c23c8ff

**Comment by nmanovic** [comment]
It should be fixed by https://github.com/opencv/cvat/pull/978
