### ISSUE TITLE
 How to use automatic annotation for 3D Point Clouds with CVAT?

### ISSUE THREAD

**Issue by ralwing** [opencv/cvat#7420]
Hi,

I'm trying to use automatic annotation for 3D Point Clouds with CVAT, but I'm having some difficulties. 
I've read [serverless-tutorial](https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/), but I don't want to spend a lot of time preparing a model without knowing if it will work.

I have the following questions:

•  Is it possible to use automatic annotation for 3D Point Clouds with CVAT? If yes, what are the requirements and steps to do so?

•  Does anyone successfully added a model for either serverless or web version of CVAT? If yes, can you share your experience and tips?

•  Is there a model on Hugging Face that can be used for automatic annotation for 3D Point Clouds with CVAT? If yes, how can I use it?

I've found this model on Hugging Face: [keras-io/Pointnet](https://huggingface.co/keras-io/PointNet/tree/main), but when I tried to use it with CVAT, it said that there's no configuration file, so it can't be used. How can I fix this issue?

I've also tried to find documentation regarding the Hugging Face CVAT interface, but I couldn't find any. Is there any documentation where I can find requirements for Hugging Face model to make it CVAT loadable model?

 
I'm using serverless CVAT version 2.10.2 on Ubuntu 22.04. I appreciate any help or guidance on this topic. 

Thank you.

**Comment by bsekachev** [comment]
> Is it possible to use automatic annotation for 3D Point Clouds with CVAT? If yes, what are the requirements and steps to do so?

Hello, unfortunately CVAT is not set up out of the box for running 3D point cloud models.

**Comment by Winter24** [comment]
Will this feature will be update in the future? I would like to use my own model to label the data for me
