### ISSUE TITLE
Fail to docker-compose build

### ISSUE THREAD

**Issue by sakilo1990** [opencv/cvat#744]
Hey everyone, when trying to docker-compose build I get the following error

TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c pip3 install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt' returned a non-zero code: 2

Is anyone aware of a method to resolve this?

**Comment by sakilo1990** [comment]
Turned out to be a timeout issue, resolved with the following live in the yaml file:

> RUN pip3 install --no-cache-dir --default-timeout=100000 -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt

**Comment by test4fest** [comment]
Installation of Openvino 2019 R3 failed to build with this error:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hn8i63fm/scikit-image/
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c pip3 install --no-cache-dir  -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt' returned a non-zero code: 1

Any suggestion?
