### ISSUE TITLE
Saving transaction of annotations gets a long time and does not even happens sometimes!

### ISSUE THREAD

**Issue by 922tech** [opencv/cvat#7445]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Just go ahead and try to save an image with a lot of annotations(after days of working).

### Expected Behavior

saving data lasts 2-3 minutes at the worst case or saving the data locally somewhere, preventing data from getting lost.

### Possible Solution

Persist the data locally (in the localstorage) or saving it real time(while annotating) on the database. 

### Context

Our annotators that use this project version 2.5 have complained that saving annotations takes a lot of time to happen and sometimes they does not even get saved after waiting for a long time (about 15 mins!) and all their work gets disappeared.
 

### Environment

```Markdown
The project is deployed according to the instructions in the documentation.
```

**Comment by 922tech** [comment]
I'm interested to know in which part of the source code that state of the annotation component gets handled. Can somebody give me a clue?

**Comment by bsekachev** [comment]
Hello, 

We do not support 2.5 anymore. It is too old. Try the latest release first.
