### ISSUE TITLE
Error in saving annotations

### ISSUE THREAD

**Issue by thestammerer12** [opencv/cvat#7455]
I'm getting the following error sometime while saving the annotations. I'm new to CVAT, could you please tell what might be the issue exactly??
<img width="193" alt="save error" src="https://github.com/opencv/cvat/assets/149149391/19530a33-85d0-4ca9-ad77-0fcdf211fce8">

**Comment by bsekachev** [comment]
Than I would recommend you to check server logs `docker logs cvat_server`.

**Comment by thestammerer12** [comment]
> Than I would recommend you to check server logs `docker logs cvat_server`.

docker logs cvat_server gives this output:

 
`2024-02-08 10:04:11,576 DEBG 'uvicorn-0' stdout output:
INFO:     10.132.132.60:0 - "PATCH /api/jobs/82/data/meta?org= HTTP/1.0" 200 OK

2024-02-08 10:04:11,744 DEBG 'uvicorn-1' stdout output:
INFO:     10.132.132.60:0 - "PATCH /api/jobs/82/annotations?org=&action=update HTTP/1.0" 200 OK

2024-02-08 10:04:11,888 DEBG 'uvicorn-1' stdout output:
INFO:     10.132.132.60:0 - "PATCH /api/jobs/82/annotations?org=&action=delete HTTP/1.0" 200 OK

2024-02-08 10:04:11,926 DEBG 'uvicorn-1' stdout output:
INFO:     10.132.132.60:0 - "PATCH /api/jobs/82/annotations?org=&action=create HTTP/1.0" 200 OK

2024-02-08 10:04:11,959 DEBG 'uvicorn-1' stdout output:
INFO:     10.132.132.60:0 - "POST /api/events?org= HTTP/1.0" 201 Created

2024-02-08 10:04:12,825 DEBG 'uvicorn-0' stdout output:
INFO:     172.18.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
`

**Comment by bsekachev** [comment]
> redis.exceptions.ConnectionError: Error 113 connecting to cvat_redis_inmem:6379. No route to host.

This is the problem. Check that `cvat_redis_inmem` container is up and running.

**Comment by thestammerer12** [comment]
> > redis.exceptions.ConnectionError: Error 113 connecting to cvat_redis_inmem:6379. No route to host.
> 
> This is the problem. Check that `cvat_redis_inmem` container is up and running.

its shows container is up since 5 days

![Screenshot from 2024-02-08 16-08-09](https://github.com/opencv/cvat/assets/149149391/49ce9741-b531-463d-9320-a547636240df)

**Comment by bsekachev** [comment]
Hmm, try to restart with `docker compose restart`
Maybe it will help.

**Comment by thestammerer12** [comment]
Restarted.. will update if problem happens again
