### ISSUE TITLE
Automatioc Annotation  get failed from task page but works from inside the job for single frames. 

### ISSUE THREAD

**Issue by thestammerer12** [opencv/cvat#7462]
I'm using CVAT hosted locally.

When i perform automatic annotation it gets failed (yolov7 model). but when i use the AI magic brush tool and annotate the frame, it annotate but only for the current frame. I get following error while performing auto annotation from outside the task. 

![image](https://github.com/opencv/cvat/assets/149149391/623a994b-2992-4590-9719-8057ac46b8c7)

![image](https://github.com/opencv/cvat/assets/149149391/d9e2389e-7ecd-49cf-9b7a-15613d85ea62)

**Comment by bsekachev** [comment]
Perhaps it gets failed on specific image. Payload to nuclio is too large? Unsupported image format? Or something else? 
Try to look at logs of nuclio dasboard immediately after failing. 
And to logs from `cvat_worker_annotation`. Maybe you will see something useful. 

Also, there is an issue about keeping annotation process healthy if it was failed on specific frames #7334
