### ISSUE TITLE
Custom Trained Detectron2 Instance Segmentation Mask RCNN Incorporation

### ISSUE THREAD

**Issue by purvaja2001** [opencv/cvat#7463]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I have a fine tuned model in Detectron2 Instance Segmentation Mask RCNN , 
Now, how to go incorporate that model in CVAT for semi automated annotations.
I have tried with Nuclio but that doesn't support the model
I tried with CVAT SDK but couldn't find and relevant documentation for this also.
Could you help me solve this problem?

**Comment by bsekachev** [comment]
> Nuclio but that doesn't support the model

I do have an idea what it means "doesn't support". Nuclio is model agnostic tool, just write inference script and config file. There are many examples in `serverless/*` directory. 

>
