### ISSUE TITLE
How to run a mock server for front-end development ?

### ISSUE THREAD

**Issue by 922tech** [opencv/cvat#7464]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I'm wondering how your front-end developers work with this issue that you can almost do nothing with front-end if there is no backend server available. Do your developers use a real running backend server or run a mock server?

### Describe the solution you'd like

Setting up a mock server

**Comment by bsekachev** [comment]
There is not a mock server. 
There is a dev server: https://opencv.github.io/cvat/docs/contributing/development-environment/
