### ISSUE TITLE
404 error on new install

### ISSUE THREAD

**Issue by MartinKlefas** [opencv/cvat#7469]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I've followed the guide here to install https://discordapp.com/channels/1000789942802337834/1000789943293063257/1205268156482846730 and the last step is to connect ot localhost:8080 when I do all I get is a 404 error page. I've checked it's coming from this by taking the containers down, and when I do I get a host not found error.

I don'tknow if there's files missing from github clones somehow, or if there's a config step missing from the install instructions, but can someone point me towards what I should change to get a home page of some kind

### Expected Behavior

Open the homepage for the new server

### Context

Brand new install on a local linux machine, and then a second attempt on a clean aws machine.

### Environment

```Markdown
git clone from 08/02/2024
ubuntu 20.04 local
aws linux on ec2 instance
ubuntu 20.04 on remote machine for one last try!
```

**Comment by bsekachev** [comment]
`docker ps`?

**Comment by bsekachev** [comment]
Hmmm.. 

If you deployed on AWS, you can't use localhost :)
It should have a specific IP address, but when in browser you use localhost it asks your computer to have this server up

**Comment by MartinKlefas** [comment]
> Hmmm..
> 
> If you deployed on AWS, you can't use localhost :) It should have a specific IP address, but when in browser you use localhost it asks your computer to have this server up

Yes, sorry I should perhaps have been more clear. When using my local machine I went to localhost from that local machine, an it served the 404 error.
when using a remote machine, I first opened the port on the relevant firewall for that remote machine and then went to the public facing IP of the machine.

In each instance I got a very specific looking 404 error page - with a particular font etc. When I turned off the containers that error page no longer came up.

I can run docker ps - but there were no errors starting the containers for CVAT and no other docker processes running as there was literally nothing else on the machine.

**Comment by bsekachev** [comment]
> went to the public facing IP of the machine.

You deployed on localhost, you can't use public IP. It is about security policies.
If you are planning to use on public IP, please export corresponding env variable and upgrade a port in config file: https://opencv.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

**Comment by MartinKlefas** [comment]
> > went to the public facing IP of the machine.
> 
> You deployed on localhost, you can't use public IP. It is about security policies. If you are planning to use on public IP, please export corresponding env variable and upgrade a port in config file: https://opencv.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

Sorry I shouldn't have conflated the error on different machines back to one - I was trying to say that the behaviour was the same or similar from different installs. On the AWS machine I changed the configs as intended.
The error seems to be different today on my local machine though:
![image](https://github.com/opencv/cvat/assets/12558370/127ae67d-c08a-4081-9835-9770fe84dee9)

I've taken a screen recording of the process to get to error in case that helps. As mentioned in there I replaced 8080 & 8090 in the docker yaml file with 8082 and 8092 - maybe that needs changing elsewhere? 

https://github.com/opencv/cvat/assets/12558370/9d08a5bb-b2cf-4d94-be8b-bb39fe102e3f

**Comment by bsekachev** [comment]
> The error seems to be different today on my local machine though:

First of all, please check `/healthcheck` response in the browser console (F12, Network, Refresh page, wait).

**Comment by MartinKlefas** [comment]
Similar to the homepage - spinning animated connection wheel then the same error message:
![image](https://github.com/opencv/cvat/assets/12558370/a2a3dcc7-c1fd-4237-9f1e-2fa6782e7b19)

**Comment by bsekachev** [comment]
Please, check one more time what the guide suggests to change and what you changed in the videofile. 
That is not the same..

**Comment by MartinKlefas** [comment]
Sorry I did a search and replace, and then a find to "demonstrate" the change and obviously picked the wrong place - I've had a look back and it's also changed in the right place:
![image](https://github.com/opencv/cvat/assets/12558370/f363ab8e-864d-4660-a394-ba82021c1825)

It's also changed in some extra places that aren't mentioned though, so I've put those back for to 8080 to see if that fixes anything and the healthcheck runs for a bit longer maybe, but still comes up as unavailable:
![image](https://github.com/opencv/cvat/assets/12558370/ac07449f-9d27-4374-b685-1265d5ef24a7)

**Comment by bsekachev** [comment]
Still not correct file, at least in this place.
![image](https://github.com/opencv/cvat/assets/40690378/3870c56e-1b30-43a5-944e-062e0de82ccb)

Internal docker ports 8082, 8092 are empty.  Please, re-check all again.

**Comment by MartinKlefas** [comment]
ok, healthcheck wasn't working, but the main screen now seems to.
It seems that whatever is on my port 8080 and my subsequent attempts to side-step it are what's caused all the issues.
