### ISSUE TITLE
Task Description is missing on the task page while available via /guide

### ISSUE THREAD

**Issue by mickaeltardy** [opencv/cvat#7470]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

Having task description is a nice to have feature that I spotted in the cloud version of CVAT 2.10 (it might have been available before). This feature is not disclosed in the docs 
https://opencv.github.io/cvat/docs/manual/basics/task-details/

Unfortunately, the community on-prem version has a slightly different behavior: the task description is not available from the task page, while one can open the editing interface via /guide endpoint. 

This is confusing. Obviously it would be great having this feature available. 

### Describe the solution you'd like

It would be useful accessing and seing the descriptions through the web interface. 

Getting them via CLI is relevant as well.

### Additional context

# On cloud (at the time of writing)
Server version: 2.10.2
Core version: 14.1.0
Canvas version: 2.19.1
UI version: 1.61.3

# On prem
Server version: 2.10.3
Core version: 14.1.1
Canvas version: 2.19.1
UI version: 1.61.4

**Comment by mickaeltardy** [comment]
Few more details 

The data submitted via /guide UI successfully land in the engine_annotationguide table. However, there is no other option other than using API to get it 
https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/guides-api/

**Comment by bsekachev** [comment]
There are not any restrictions of this feature in open source solution. 
It is available, please, re-check.

**Comment by mickaeltardy** [comment]
No restriction would be the expected behaviour. 

Unfortunately this is not the case: double-checked, please see the screenshots

- The Task description button is available in the cloud version
<img width="1409" alt="cvat-cloud-task-description" src="https://github.com/opencv/cvat/assets/6764005/f9905742-517c-42bd-b8cd-6e7ad96dfc57">


- There is no task decription in Task interface
<img width="1442" alt="cvat-on-prem-no-task-description" src="https://github.com/opencv/cvat/assets/6764005/ef776fab-77ab-40fe-9416-84e211b01a1d">

- The guide endpoint is still available
<img width="1469" alt="cvat-on-prem-task-description-guide" src="https://github.com/opencv/cvat/assets/6764005/df61190d-f672-4868-8fd6-c1ed309c9549">

**Comment by bsekachev** [comment]
I see. The same scheme as with labels.

If a task in a project, setup guide on the project page.
If a task not in a project, setup guide on the task page.

**Comment by mickaeltardy** [comment]
Ok. Understood. Thanks. 
I would like to be able to customize the description task-wise. Any thoughts of that being useful?
