### ISSUE TITLE
Change of job state multiple times requires refresh

### ISSUE THREAD

**Issue by serwansj** [opencv/cvat#7471]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Create a new job and assign a worker.
2. As a worker open the newly created job that is in the state `new`.
3. As soon as annotation begins, the job state automatically switches to `in progress`.
4. After the job state switched to `in progress`, switching manually to `completed` returns a 403: permission denied error.

This also happens when manually switching to `in progress` and then to `completed` or from `in progress` to `new` (doesn't matter which order, after the first change all subsequent changes return 403: permission denied).

Switching to another job state only works after refreshing the browser tab.

### Expected Behavior

A worker should be able to switch the job state to `completed` without having to refresh the browser tab.

**Comment by bsekachev** [comment]
That can not be reproduced (at least on the current version). 
Is the task in an organization? 

Please, check if it is not duplicate of #7241 (where you first try to finish the job)

**Comment by serwansj** [comment]
closing because updating to the newest version fixed this issue
