### ISSUE TITLE
Showing Return- and Reason-Codes of Nuclio models

### ISSUE THREAD

**Issue by RoseDeSable** [opencv/cvat#7483]
Hi,
 sometimes a long running automated annotation with a function in Nuclio is broken. CVAT doesn't know a reason. But in our analysis we seem to see, that a mount is disrupted on a server with the pictures (In the most cases we use "Connected file share"). I say: we seem. For further analysis we want to see a return and reason-code of the function, that run in Nuclio. Offers CVAT a possibility to show such Codes in a status line near the job, where the annotation run ?

Best Regards
Rose

**Comment by bsekachev** [comment]
You may find this information in admin panel (Queues -> Annotation -> Failed).

**Comment by RoseDeSable** [comment]
Ok,
 if find the panel, but I see no entries from the past

![grafik](https://github.com/opencv/cvat/assets/42828799/f34cf554-3d0c-46f1-8912-8d987a4ba048)

Have we a failure in our configuration ?

**Comment by RoseDeSable** [comment]
Now an annotation is running and I see the job

![grafik](https://github.com/opencv/cvat/assets/42828799/8c3d6af9-d9d7-4074-83e3-da18fff029ea)

with the wished metadata as my username, which started the annotation

That's good

**Comment by RoseDeSable** [comment]
but I see no name of the model, that is running.

If I cancel the job, I see no notice of that action. Instead the type of ending is "successful". 

![grafik](https://github.com/opencv/cvat/assets/42828799/f052f21d-84bf-472a-9a53-b7e0b5703a9e)

Then I find a field "Return Value" 

![grafik](https://github.com/opencv/cvat/assets/42828799/fc0a01d6-6b78-43ca-bd81-27e69973a720)

Can I give out a return code on this position ? If it is, have you an example for me, what's to do in the function of Nuclio ? 

and now I'm very happy. By clicking on the number of the failing jobs, I find all jobs of the last days and a detailed description of their failing. That's good.
