### ISSUE TITLE
CVAT on GCP 

### ISSUE THREAD

**Issue by purvaja2001** [opencv/cvat#7487]
Hi I am trying to access the CVAT using CVAT_HOST via GCP SSH
I have followed all the steps in The installation guide
https://opencv.github.io/cvat/docs/administration/basics/installation/
First I have installed Docker
Then I have cloned GitHub repo
Then cd cvat
Then exported my CVAT_HOST
Then I have done docker compose up -d
But then when I am trying to access the CVAT_HOST:8080 port 
I am unable to access the CVAT UI
I am getting 404 
![IMG_20240219_142450](https://github.com/opencv/cvat/assets/145646908/ed367902-ee95-4b58-a71e-b7b91c4f671d)

If anybody knows what can be done here, please help me.

**Comment by sago2693** [comment]
Hi, what did you do in this case to solve the issue?

**Comment by purvaja2001** [comment]
While creating an instance we have to attach an external IP address to the instance and we have to export that Cvat_host address. And all the steps remain same.
