### ISSUE TITLE
Exporting Dataset Eats up local disk memory, canceling the exportation and restarting it 

### ISSUE THREAD

**Issue by devwasabi** [opencv/cvat#7495]
I've always had memory issues with cvat, since I'm using my local machine as storage. I am using cvat within wsl. Yesterday I decided to move cvat to my 2nd drive which has more storage (around 1 terabyte). Cvat was working seamlessly until I started to export my datasets.

![image](https://github.com/opencv/cvat/assets/159067732/89f5e379-fb15-4e2f-a923-3b44e0f9cb23)

![Screenshot 2024-02-19 112157](https://github.com/opencv/cvat/assets/159067732/26d4ab43-1797-4a2c-9fd0-03abd3fac68e)
Above is the storage before I started exporting the datasets

![Screenshot 2024-02-20 091339](https://github.com/opencv/cvat/assets/159067732/ad92b0d9-1533-4eb6-8f72-ac4fac006c1d)
Above is the storage after I began exporting the datasets

 Thereafter, +- 300 gigs of extra memory suddenly decreased to a few gigs. Now, all of a sudden I have only 6 gigs left. I have already checked the logs for cvat_server, and it's here below:
`
[2024-02-20 07:34:29,941] ERROR health-check: warning: 603a12ee426c 92.9% disk usage exceeds 90%
`
It's clear that the issue is memory, it's just that I am not sure how to fix it now, since i am using local storage instead of cloud storage. My annotations are probably a lot. Is there a way to stop the exportation and restart it. I think it may have been that I made multiple export requests, because I wasn't getting a quick response (the downloading of the dataset). I feel like I may be suffering the repurrcussions of exporting multiple datasets simultaneously, and now my storage is taking the lagging backlash.

**Comment by bsekachev** [comment]
1. You did not specify which version you are using and what dataset you tried to export. So, I can't estimate how many gygabytes the dataset file is.
2. When you export a dataset, it creates an archive file on filesystem where all annotations and images are stored. This file is not removed immediately, usually after several hours. If you export more datasets in this period, it will collect more files on the filesystem.
3. WSL file system is not shrink-ed automatically. Once it has eaten more gygabites, it will not become less itself. Please, google for more information. 

To cancel current processes you may just restart CVAT server (or only `cvat_worker_export`)
Like: `docker compose restart cvat_worker_export`. One more way is to go inside a container and kill processes. 

To free memory, you may go inside the container and remove unnecessary files:
`docker exec -it cvat_server bash`
`cd /home/django/data/projects/<project_id>/export_cache` # or the same for tasks if you are exporting tasks
`rm <export_file>`

**Comment by devwasabi** [comment]
Thanks. I could eventually solve the storage problem by deleting the export cache. I think another thing that created a problem was that I was saving the images from the annotations (the save images option when exporting the dataset). Saving every image from a large video (where I only annotated 20% of the frame that make up the video) created a huge overhead. When I download the annotations without saving the images/frames, I don't get storage issues.
