### ISSUE TITLE
CVAT corrupts annotations when importing

### ISSUE THREAD

**Issue by PMazarovich** [opencv/cvat#7498]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

How I did it on app.cvat.ai
1. Create a task with 1 job
2. Annotate one skeleton track
3. Create a task with 2 jobs
4. Export from 1 and import to 3. (cvat for video)
You'll see that for first job in second task - coordinates of annotations are the same and not changing.
Demo:
https://github.com/opencv/cvat/assets/57707673/45018fd7-e70c-4f05-afb6-aa0ff4efa5da
Annotations:
[DEMO.zip](https://github.com/opencv/cvat/files/14345529/DEMO.zip)

### Expected Behavior

cvat should not corrupt annotations 

### Environment

```Markdown
cvat 2.9.2 and app.cvat.ai
```

**Comment by bsekachev** [comment]
Hello,

Only keyframes are imported when you upload annotations. 
In your case in the first job of the second task only one keyframe was imported.

**Comment by PMazarovich** [comment]
The idea is that keyframes actually does matter comparing to annotation coordinates. That is why, as for me, it is better to add some keyframes rather then loose a bunch of annotations

**Comment by ccinv** [comment]
Hello @nmanovic, I am interested in this issue, can you assign it to me?

**Comment by ccinv** [comment]
i'm trying to solve this issue by a adding some interpolation to the improrted data patch part, for which I think it's best to inserted in slice function of tracks. 

https://github.com/opencv/cvat/blob/f22322f4349a91bbb645dfcacf1e799d870a6f16/cvat/apps/dataset_manager/annotation.py#L131-L146

modify the for loop starting from 139 could work. But I can't figure out what track['shapes'] means and what's the difference with track['elements']. Could you please give me a hint? @bsekachev @nmanovic

**Comment by bsekachev** [comment]
track['shapes'] contains positions data of the track on different frames
track['elements'] is about skeletons, which are complex shapes consisted of other shapes (points). This is array of other "children" tracks.
