### ISSUE TITLE
3D point color coding

### ISSUE THREAD

**Issue by MarvinKlemp** [opencv/cvat#7499]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

I wanted to ask if there is any way to color code points 
(For example by their height, or by their intensity)

Its extremely hard to annotate point cloud only datasets. However, with different color encoding its often easier.

If someone could lead me to the code where points are actually arawn I could create a PR

**Comment by bsekachev** [comment]
As far as I remember you may provide colors in a PCD file, but need to double check.

**Comment by MarvinKlemp** [comment]
Thanks, you can easily just set the color @bsekachev :)

Probably this line here `https://github.com/opencv/cvat/blob/7286d659bdc3ff346cb0322fcccd398801043f64/cvat-canvas3d/src/typescript/canvas3dView.ts#L1226C1-L1235C38`
