### ISSUE TITLE
Automatic Annotations Error 500 with TransT Model

### ISSUE THREAD

**Issue by thestammerer12** [opencv/cvat#7502]
I'm getting the following error while using using the transT model. I also used siammask for the same task and it is working but transt is giving the following error what could be the possible reason for this??

Output of docker logs cvat_server:

> 2024-02-21 08:14:35,426 DEBG 'uvicorn-0' stderr output:
[2024-02-21 08:14:35,425] ERROR django.request: Internal Server Error: /api/lambda/functions/pth-dschoerk-transt

2024-02-21 08:14:35,426 DEBG 'uvicorn-0' stdout output:
INFO:     10.132.201.66:0 - "POST /api/lambda/functions/pth-dschoerk-transt?org= HTTP/1.0" 500 Internal Server Error

Output of Nuctl get functions:
![image](https://github.com/opencv/cvat/assets/149149391/07ee6d92-17b5-4415-990f-26f146fbddbc)

![image](https://github.com/opencv/cvat/assets/149149391/f85d9d59-43e7-492b-aef0-bd1002f41365)

**Comment by thestammerer12** [comment]
@nmanovic  Please help

**Comment by bsekachev** [comment]
I would suggest to check Docker container logs for this serverless function.

**Comment by thestammerer12** [comment]
> I would suggest to check Docker container logs for this serverless function.
here is the logs of this function, Unable to understand the error
![image](https://github.com/opencv/cvat/assets/149149391/4d5240e8-cbef-4a6b-8c33-7f2c52d610d7)

**Comment by bsekachev** [comment]
It is not really clear how to reproduce the issue.  Some connection issues?
Try to ask [nuclio community](https://github.com/nuclio/nuclio). We do not really have expertise there.
