### ISSUE TITLE
Segment Anything @ self-hosted: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded

### ISSUE THREAD

**Issue by cbasavaraj** [opencv/cvat#7505]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hi, I'm using CVAT on a GCP instance. In particular, I'm using Segment Anything to segment some objects. Two days ago, it was working fine, but today I get this error:

```
Interaction error occurred
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```

<img width="1627" alt="Screenshot 2024-02-21 at 21 53 14" src="https://github.com/opencv/cvat/assets/15706875/2be92bfb-b3dc-41ca-b192-51997657e0a5">

I tried restarting CVAT using docker compose down and then up, but it's not helping. 

Any ideas? Thanks

### Expected Behavior

Normally, the objects are selected fine by SAM.

### Environment

```Markdown
- Git hash: commit 42be015f70e3770178b46e111ff2f8e24cd2ba93 (HEAD -> develop, origin/develop, origin/HEAD)

- Docker version
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:09 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:13:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- OS:
Ubuntu 22.04 LTS
```

**Comment by bsekachev** [comment]
Check the response body, you are getting from the server on the first request.
