### ISSUE TITLE
wanna get the source code for polyline function

### ISSUE THREAD

**Issue by zhangzhangzhiyuan** [opencv/cvat#7506]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

Hello, I am a newbie and not very good at using giuhub. I used CVAT as my annotation platform before. Now I need to write the implementation method of polyline into my paper, but I can't find the source code. Can any kind person tell me where the source code of polyline is. Especially the step of automatically completing the information between annotated frames, this is particularly critical to me.

### Describe the solution you'd like

may anyone can share the source code to me ? or that is impolite? pls tell me~

**Comment by bsekachev** [comment]
Hello, 

`cvat-core` module, `annotation-objects.ts`, see PolylineTrack class and its parent classes.

**Comment by zhangzhangzhiyuan** [comment]
thank you very much for your answer

Boris Sekachev ***@***.***> 于2024年2月22日周四 16:36写道：
