### ISSUE TITLE
The backup guide is not work for CVAT2.2.0 container

### ISSUE THREAD

**Issue by jenhaoyang** [opencv/cvat#7509]
The following command will not work for CVAT2.2.0 container, it just generate many empty folder inside compressed file.
```
docker run --rm --name temp_backup --volumes-from cvat_db -v $(pwd)/backup:/backup ubuntu tar -czvf /backup/cvat_db.tar.gz /var/lib/postgresql/data
```

**Comment by bsekachev** [comment]
Just tried this line and it worked.

**Comment by bsekachev** [comment]
Perhaps you need to investigate the issue on your own. It is a magic to find what is a problem on remote system, hope you understand. 
Feel free to share your thoughts to help others if somebody finds the same issue.  

Thank you.
