### ISSUE TITLE
Google login using docker

### ISSUE THREAD

**Issue by montabano1** [opencv/cvat#7517]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I signed up via the google login button online, and i wanted to use docker locally, but there is no google sign in. I tried forgot password with my google account email but nothing was sent. 

### Expected Behavior

Be able to sign in if i registered using google button

### Possible Solution

Can you please add a google sign in to docker version or allow users who sign up with google online to set a password

### Context

I am unable to login locally

### Environment

```Markdown
% git log -1
commit 537036362efc4ed5020d8f7fd323936e2472ff1f (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 2c5bb6917 5812aceff
Author: Boris Sekachev <boris.sekachev@yandex.ru>
Date:   Fri Feb 23 16:04:03 2024 +0200

    Merge pull request #7513 from opencv/dev-release-2.11.0
    
    Update develop after v2.11.0

% docker version
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.27.2 (137060)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by bsekachev** [comment]
Hello,
Social authentification is enterprise feature.

> Be able to sign in if i registered using google button

1. You may use "Reset password feature" to add password to your account and then use the password to login
2. You may change password on admin page (users => user => change password)

**Comment by montabano1** [comment]
I did forgot password, set my password, but im unable to log in with that (email or username) and password using docker. I was able to log in on the web.

**Comment by bsekachev** [comment]
I don't really understand what you mean in loggining with docker.

**Comment by montabano1** [comment]
Logging in locally on localhost doesn’t work with my google registered
email paid solo account. I set up a new account for free with an email and
password and that worked, but my google one doesn’t work locally but works
on the web

**Comment by bsekachev** [comment]
app.cvat.ai and localhost are two totally different instances with different databases. They do not share any common data.
