### ISSUE TITLE
Empty txt files when using polygons if exporting task in Yolo 1.1 format

### ISSUE THREAD

**Issue by LennyJS** [opencv/cvat#7518]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Upload data
2. Annotate it using polygons
3. Export task in Yolo 1.1 format
4. Empty txt files 

### Expected Behavior

When downloading the files using polygons I thought the txt files would be storing the information about the mask

### Possible Solution

Show annotations in txt files when annotating with polygons

### Environment

```Markdown
Operating system is iOs
```

**Comment by bsekachev** [comment]
Yolo does not support polygons, only rectangles. 
Please, refer to documentation.
