### ISSUE TITLE
Can't Establish client connection via python cvat_sdk

### ISSUE THREAD

**Issue by AmitNativ1984** [opencv/cvat#7519]
Hello.
I have CVAT running successfully with docker-compose.
I can successfully enter the platform from CHROME, but when I'm trying to connect to the server using the python-sdk, it's not working.

I'm using **cvat_sdk.__version__ = '2.11.0'**

## This is the code I use:

```python
with make_client(host=args.host, credentials=(args.username, args.password)) as client:
    my_tasks = client.tasks.list()
```

### terminal:
``
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /api/server/about
``

### docker-compose:
`{"ClientAddr":"172.20.0.1:42394","ClientHost":"172.20.0.1","ClientPort":"42394","ClientUsername":"-","DownstreamContentSize":3612,"DownstreamStatus":200,"Duration":46211746,"OriginContentSize":3612,"OriginDuration":46175788,"OriginStatus":200,"Overhead":35958,"RequestAddr":"localhost:8080","RequestContentSize":0,"RequestCount":21,"RequestHost":"localhost","RequestMethod":"GET","RequestPath":"/api/tasks?page=1","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"cvat@docker","ServiceAddr":"172.20.0.9:8080","ServiceName":"cvat@docker","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.20.0.9:8080","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-02-25T15:58:57.134918876Z","StartUTC":"2024-02-25T15:58:57.134918876Z","entryPointName":"web","level":"info","msg":"","time":"2024-02-25T15:58:57Z"}
cvat_server                    | 2024-02-25 15:59:02,940 DEBG 'uvicorn-0' stdout output:
cvat_server                    | INFO:     172.20.0.3:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
`

**Comment by bsekachev** [comment]
Hmm, ... try to specify protocol in host, like `http://`

**Comment by AmitNativ1984** [comment]
Thanks. It turned out to be related to an issue with VSCode and running the code from inside a devcontainer.
