### ISSUE TITLE
Mask to polygon broke

### ISSUE THREAD

**Issue by drkousek** [opencv/cvat#7520]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Create masks
Run Actions -> Convert Mask to Polygons
Polygons are broken, some are randomly missing

### Expected Behavior

I expect 1:1 convert to polygons from masks.

### Context

I am trying to convert like 400 images annotated from Mask to Polygon so I can export.

### Environment

```Markdown
cvat online
```

**Comment by bsekachev** [comment]
Hello, 
Please, provide example.

**Comment by drkousek** [comment]
First - masks.
![image](https://github.com/opencv/cvat/assets/26819551/c283a51b-6a40-4172-a91b-d6556ea6ead1)
Second - polygons, nearly completely broken, not all correctly transformed
![image](https://github.com/opencv/cvat/assets/26819551/5dc5d2c9-e216-43ea-974f-da7907d6be9a)

**Comment by bsekachev** [comment]
Do you have a minimal reproducing example (like a small task backup that I can restore and reproduce)? It is quite difficult to conclude what has happened from the screenshot.

**Comment by drkousek** [comment]
I have send you message with backup on Discord, please check

**Comment by bsekachev** [comment]
Okay, I see.

In your case there are some problems because of that separated pixel:
<img width="392" alt="image" src="https://github.com/opencv/cvat/assets/40690378/fbcd63da-73fe-4194-aa1b-b9823d1ddd6f">

I will look how such cases may be handled.

**Comment by bsekachev** [comment]
Also, take into account that polygon can't have holes, but masks can.
And if a mask consist of two parts, you will get two polygons for this mask.

**Comment by siddagra** [comment]
How did you even get this option? I don't even get this option on CVAT 2.11.0

**Comment by siddagra** [comment]
How did you even get this option? I don't even get this option on CVAT 2.11.0

**Comment by drkousek** [comment]
> How did you even get this option? I don't even get this option on CVAT 2.11.0

It is on app.cvat.ai

**Comment by siddagra** [comment]
No way to get this on local docker version?

**Comment by siddagra** [comment]
No way to get this on local docker version? app.cvat.ai is unbearably slow...

**Comment by mfkeles** [comment]
I am encountering a similar issue where running mask to polygon removes masks on my frames without resulting in polygons.

**Comment by siddagra** [comment]
Find it kind of upsetting that this is anyways only an enterprise feature, but I found a better solution. Export to COCO and then use this:
https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py

**Comment by drkousek** [comment]
> Find it kind of upsetting that this is anyways, only an enterprise feature, but I found a better solution. Export to COCO and then use this: https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py
> 
> Maybe the authors can implement something similar. Though regardless, not like it will benefit or affect me I guess.

unfortunately COCO doesn't support masks
https://opencv.github.io/cvat/docs/manual/advanced/formats/

> No way to get this on local docker version? app.cvat.ai is unbearably slow...

I cannot use docker, I don't have machine for that.

**Comment by siddagra** [comment]
> > Find it kind of upsetting that this is anyways, only an enterprise feature, but I found a better solution. Export to COCO and then use this: https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py
> > Maybe the authors can implement something similar. Though regardless, not like it will benefit or affect me I guess.
> 
> unfortunately COCO doesn't support masks https://opencv.github.io/cvat/docs/manual/advanced/formats/
> 
> > No way to get this on local docker version? app.cvat.ai is unbearably slow...
> 
> I cannot use docker, I don't have machine for that.

COCO from CVAT does support masks. I think COCO in general also supports masks. also that general_json2yolo.py i linked can convert COCO masks to yolo

**Comment by ryouchinsa** [comment]
Using the script [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py), you can convert the RLE mask with holes to the YOLO segmentation format.

The RLE mask is converted to a parent polygon and a child polygon using `cv2.findContours()`.
The parent polygon points are sorted in clockwise order. 
The child polygon points are sorted in counterclockwise order.
Detect the nearest point in the parent polygon and in the child polygon.
Connect those 2 points with narrow 2 lines.
So that the polygon with a hole is saved in the YOLO segmentation format.

```
def is_clockwise(contour):
    value = 0
    num = len(contour)
    for i, point in enumerate(contour):
        p1 = contour[i]
        if i < num - 1:
            p2 = contour[i + 1]
        else:
            p2 = contour[0]
        value += (p2[0][0] - p1[0][0]) * (p2[0][1] + p1[0][1]);
    return value < 0

def get_merge_point_idx(contour1, contour2):
    idx1 = 0
    idx2 = 0
    distance_min = -1
    for i, p1 in enumerate(contour1):
        for j, p2 in enumerate(contour2):
            distance = pow(p2[0][0] - p1[0][0], 2) + pow(p2[0][1] - p1[0][1], 2);
            if distance_min < 0:
                distance_min = distance
                idx1 = i
                idx2 = j
            elif distance < distance_min:
                distance_min = distance
                idx1 = i
                idx2 = j
    return idx1, idx2

def merge_contours(contour1, contour2, idx1, idx2):
    contour = []
    for i in list(range(0, idx1 + 1)):
        contour.append(contour1[i])
    for i in list(range(idx2, len(contour2))):
        contour.append(contour2[i])
    for i in list(range(0, idx2 + 1)):
        contour.append(contour2[i])
    for i in list(range(idx1, len(contour1))):
        contour.append(contour1[i])
    contour = np.array(contour)
    return contour

def merge_with_parent(contour_parent, contour):
    if not is_clockwise(contour_parent):
        contour_parent = contour_parent[::-1]
    if is_clockwise(contour):
        contour = contour[::-1]
    idx1, idx2 = get_merge_point_idx(contour_parent, contour)
    return merge_contours(contour_parent, contour, idx1, idx2)

def mask2polygon(image):
    contours, hierarchies = cv2.findContours(image, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS)
    contours_approx = []
    polygons = []
    for contour in contours:
        epsilon = 0.001 * cv2.arcLength(contour, True)
        contour_approx = cv2.approxPolyDP(contour, epsilon, True)
        contours_approx.append(contour_approx)

    contours_parent = []
    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx < 0 and len(contour) >= 3:
            contours_parent.append(contour)
        else:
            contours_parent.append([])

    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx >= 0 and len(contour) >= 3:
            contour_parent = contours_parent[parent_idx]
            if len(contour_parent) == 0:
                continue
            contours_parent[parent_idx] = merge_with_parent(contour_parent, contour)

    contours_parent_tmp = []
    for contour in contours_parent:
        if len(contour) == 0:
            continue
        contours_parent_tmp.append(contour)

    polygons = []
    for contour in contours_parent_tmp:
        polygon = contour.flatten().tolist()
        polygons.append(polygon)
    return polygons 

def rle2polygon(segmentation):
    if isinstance(segmentation["counts"], list):
        segmentation = mask.frPyObjects(segmentation, *segmentation["size"])
    m = mask.decode(segmentation) 
    m[m > 0] = 255
    polygons = mask2polygon(m)
    return polygons
```

The RLE mask.

![スクリーンショット 2023-11-22 1 57 52](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/df2dfad5-a13f-49c6-818a-8aba1d3ce83c)

The converted YOLO segmentation format.

![スクリーンショット 2023-11-22 2 11 14](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/cc34027a-075f-4b67-8de7-bd2dddddac59)

To run the script, put the COCO JSON file coco_train.json into `datasets/coco/annotations`.
Run the script. `python general_json2yolo.py  `
The converted YOLO txt files are saved in `new_dir/labels/coco_train`.

![スクリーンショット 2023-11-23 16 39 21](https://github.com/ultralytics/JSON2YOLO/assets/1954306/c3d98120-66f5-4cb8-b74d-a500f0bd811d)

Edit use_segments and use_keypoints in the script.

```
if __name__ == '__main__':
    source = 'COCO'

    if source == 'COCO':
        convert_coco_json('../datasets/coco/annotations',  # directory with *.json
                          use_segments=True,
                          use_keypoints=False,
                          cls91to80=False)
```

To convert the COCO bbox format to YOLO bbox format.
```
use_segments=False,
use_keypoints=False,
```

To convert the COCO segmentation format to YOLO segmentation format.
```
use_segments=True,
use_keypoints=False,
```

To convert the COCO keypoints format to YOLO keypoints format.
```
use_segments=False,
use_keypoints=True,
```

This script originates from Ultralytics [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO) repository.
We hope this script would help your business.

**Comment by nmanovic** [comment]
the problem with small masks which are deleted automatically will be solved in the next release. Thank you for the report.

**Comment by bsekachev** [comment]
I expect now it should be solved.
