### ISSUE TITLE
How to define a Label, which has a fixed W/H ratio?

### ISSUE THREAD

**Issue by jinjingzhong** [opencv/cvat#7521]
Hi, I want to define a Rect Label for a project, which has a fixed W/H ratio, when I change the size of the Rectangle, it always maintains a fixed WH ratio， for example, 16:9 or 4:3. How can I make this in CVAT, please help.

Also, I want to define a rect mask, when I annotate this rect mask, the image will be blurred except the mask area, How can I do? Thanks!

**Comment by bsekachev** [comment]
Hello, that is not possible.

**Comment by jinjingzhong** [comment]
Thanks, does it mean it is not possible in current version, This requires rewriting part of the source codes , right?

**Comment by jinjingzhong** [comment]
> Hello, that is not possible.

Thanks, does it mean it is not possible in current version, This requires rewriting part of the source codes , right?

**Comment by bsekachev** [comment]
Yep, with modifying source code everything is possible. 
But I do not think we are going to support it. Also, that will not be just several lines of code.

**Comment by jinjingzhong** [comment]
> Yep, with modifying source code everything is possible. But I do not think we are going to support it. Also, that will not be just several lines of code.

Thank you for the reply.
