### ISSUE TITLE
Is there a way to calculate embeddings for all images with SAM?

### ISSUE THREAD

**Issue by vladimirstarygin** [opencv/cvat#7525]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

When I'm using AI annotation tool (SAM) the first part, when embedding is calculated, takes too long on cpu (I'm currently unable to use gpu for my project). Is there a way to load images into task, precalculate embeddings for all of them and store them in the db. Then, when all embeddings are ready, to acquire them from the db and run only image decoder. That would fasten the markup progress a lot when we have a lot of images.

### Describe the solution you'd like

Maybe a button which precalculate embeddings for all images.

**Comment by bsekachev** [comment]
Hello, there is no such ability. Saving embeddings on the server would require signicant modification. 
But, you may write a script to compute embeddings beforehand, save them in a database (or just a text file) and modify serverless function, in order to it just read them from the file.
