### ISSUE TITLE
Could not upload annotation

### ISSUE THREAD

**Issue by vga-frontmatec** [opencv/cvat#7527]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Create a new project.
2. Enter a name (test) for the project.
3. Add label (label1) of type Tag.
4. Submit & Open.
5. Create a new task.
6. Enter a name (test).
7. Select the project created earlier (test).
8. Drag a random .png file.
9. Submit & Open.
10. Select the job that was just created.
11. Annotate the image by selecting the tag label1.
12. Save.
13. Go back to the test task.
14. Export annotations using Datumaro 1.0.
15. Download of a zip file will begin.
16. Import annotations that was just exported using the zip file.

The error that we constantly receive:
Could not upload annotation for the [task 528524] (https://app.cvat.ai/tasks/528524)
Cannot read properties of undefined (reading 'attributes')

cvat-ui.ec77c400e46942ed8d77.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'attributes')
    at wi.appendDefaultAttributes (cvat-ui.ec77c400e46942ed8d77.min.js:2:2801171)
    at new bi (cvat-ui.ec77c400e46942ed8d77.min.js:2:2798369)
    at new wi (cvat-ui.ec77c400e46942ed8d77.min.js:2:2814852)
    at Xi.import (cvat-ui.ec77c400e46942ed8d77.min.js:2:2843733)
    at mo (cvat-ui.ec77c400e46942ed8d77.min.js:2:2873707)
    at async No.e.annotations.clear.implementation (cvat-ui.ec77c400e46942ed8d77.min.js:2:2883891)
    at async Ca.apiWrapper (cvat-ui.ec77c400e46942ed8d77.min.js:2:2610028)
    at async Ca.clear (cvat-ui.ec77c400e46942ed8d77.min.js:2:2749919)
    at async cvat-ui.ec77c400e46942ed8d77.min.js:2:8116485

### Expected Behavior

I expect that annotations will be uploaded successfully and replace the existing annotations.

### Possible Solution

I tried other formats such as CVAT 1.1 and it didn't work.

### Context

We have existing annotations that we want to migrate to CVAT. We just bought the Team plan on Cloud but we cannot migrate our existing annotations using Datumaro 1.0 as we constantly face the error.

### Environment

```Markdown
Operating system is Linux using Chrome on the latest version.
We are using CVAT hosted on Cloud (Team Plan).
```

**Comment by bsekachev** [comment]
Closed as there is no response on internal channel.

**Comment by DmitryBabichev** [comment]
Have the same problem

**Comment by ejboomus** [comment]
I am also having the same problem

**Comment by vga-frontmatec** [comment]
Even though I get the error messages, the upload is still done successfully. I still don't know why that error happens, but it works on our ends anyway.

**Comment by xebcam** [comment]
> Even though I get the error messages, the upload is still done successfully. I still don't know why that error happens, but it works on our ends anyway.

Same.
