### ISSUE TITLE
Shape converter not available in docker

### ISSUE THREAD

**Issue by siddagra** [opencv/cvat#7530]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

Self explanatory, Shape converter not available in docker. Many other annotation tools, softwares, etc. to import do not support masks. I need to convert these to polygons but the shape converter is not available in local docker installation.

### Describe the solution you'd like

Please add shape converter to local docker installation of CVAT

### Describe alternatives you've considered

I could make my own conversion tool to post process it, or download and reupload annotations. but it takes very long and is very cumbersome. Not a good experience overall. Especially since app.cvat.ai (the website) already supports this.

**Comment by bsekachev** [comment]
Right now that is enterprise feature. It might be open sourced in the future.
