### ISSUE TITLE
dont receive the email to verify my email

### ISSUE THREAD

**Issue by Windlance** [opencv/cvat#7543]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

created account with my email josemaria.depereda@cora3.es but im unable to log in because ive still havent receive the email to confirm my own email.

been waiting for a long time to receive it, checked all email folders (like spam, unwanted and so), and still nothing.

Please help

**Comment by nmanovic** [comment]
Hi,

I see that 3 emails were sent on your email address. As reported, they were delivered by you didn't open them. Please check it on your side.
I have manually verified your account. You should be able to login. Have a great day!
