### ISSUE TITLE
how to get a bound box in the cvat sdk

### ISSUE THREAD

**Issue by husia777** [opencv/cvat#7546]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

how to get a bound box in the chat sdk

**Comment by bsekachev** [comment]
Hello,

Please, refer to the documentation to find an answer: https://opencv.github.io/cvat/docs/api_sdk/sdk/
