### ISSUE TITLE
does anyone know how to run the cvat through Docker Desktop?

### ISSUE THREAD

**Issue by manesvenom** [opencv/cvat#7567]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

<img width="766" alt="Screenshot 2024-03-08 at 12 20 36 AM" src="https://github.com/opencv/cvat/assets/7610019/596d3f40-423a-4d4d-b00f-ae0117e1af28">

<img width="1272" alt="Screenshot 2024-03-08 at 12 17 24 AM" src="https://github.com/opencv/cvat/assets/7610019/9efa04ee-ad73-45e5-9831-dd8e4d4c4c8b">

<img width="1270" alt="Screenshot 2024-03-08 at 12 17 43 AM" src="https://github.com/opencv/cvat/assets/7610019/b67753dd-a16c-4f01-be02-4c0e46579835">

The server can't be started and it keeps showing "./backend_entrypoint.sh at least one subcommand required" in the log message. I can't find the way to provide the subcommand

### Environment

```Markdown
-Docker Desktop version 4.28.0 (139021)
```

**Comment by nmanovic** [comment]
https://opencv.github.io/cvat/docs/administration/basics/installation/

**Comment by manesvenom** [comment]
Thank you for the installation guide.   It is working finally as I followed the video guide step by step.

Below is the detailed instruction guide for Window and Mac respectively.
Window installation Guide
https://www.youtube.com/watch?v=hyvNFuc06qQ

Mac installation Guide
https://www.youtube.com/watch?v=n8Ir1jo5z7g
