### ISSUE TITLE
How to automatically save annotated results to an Azure blob

### ISSUE THREAD

**Issue by Shin-ichi-Takayama** [opencv/cvat#7570]
I am considering how to automatically save annotated results to an Azure blob.

I have a few questions.
- Is there a way to set up automatic saving of annotated results to an Azure blob?
- Is there a way to know if the annotation of a task has been completed?
- How can I use the cvat-cli command to dump to an Azure blob?

Best regards.

**Comment by bsekachev** [comment]
Hello

> Is there a way to set up automatic saving of annotated results to an Azure blob?

From CVAT interface - No.

> Is there a way to know if the annotation of a task has been completed?

Webhooks. 

> How can I use the cvat-cli command to dump to an Azure blob?

Please, look at the documentation. But I am not sure you may do that with CLI. But there is CVAT SDK that can be used to write your own scripts.
