### ISSUE TITLE
Missing "Dataset Repository URL" option in the new task creation interface

### ISSUE THREAD

**Issue by cento** [opencv/cvat#7574]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

In the "new task" interface:
![image](https://github.com/opencv/cvat/assets/2317186/8ca0a643-28db-494e-a776-7c17e638a85b)

### Expected Behavior

Dataset Repository URL field, as reported here:
https://opencv.github.io/cvat/docs/manual/basics/create_an_annotation_task/#create-a-task

![image](https://github.com/opencv/cvat/assets/2317186/29b038bb-9b3d-4b97-9c1b-4cc61392bc19)

### Environment

```Markdown
- local CVAT installation
- local machine on WSL2
```

**Comment by bsekachev** [comment]
This feature was removed several releases ago.
Please, use integration with cloud storages instead.

**Comment by bsekachev** [comment]
I will update documentation.
