### ISSUE TITLE
Imporve ux

### ISSUE THREAD

**Issue by syedbarimanjan** [opencv/cvat#7579]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

When I created a project the first time and clicked the submit and continue button i was expecting it to create the project and take me back to the projects main page but it didnt and then i searched for a back button which wasnt there.

### Describe the solution you'd like

I would like to either add a back button on the create a new projects page which would take the user back to the main projects page or I would like to redirect the user to the main projects page when they click submit and continue button.

**Comment by syedbarimanjan** [comment]
@bsekachev @nmanovic could you review this.

**Comment by bsekachev** [comment]
You are welcome to contribute.
