### ISSUE TITLE
redis/keydb too many writes and cpu on idle

### ISSUE THREAD

**Issue by piotr-sikora-v** [opencv/cvat#7584]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

I have small instance of CVAT running inside VM, after while I saw some high usage on this VM.
When I check I saw that `cvat_redis` taking many CPU and disk reads/writes.
Data from `docker stats`
```
f86b186fbbef   cvat_redis                                      77.76%    631.8MiB / 39.87GiB   1.55%     80MB / 54.2MB     239GB / 243GB    23
``` 
243GB writes in 3h uptime.
No one is using it.

### Expected Behavior

idle usage

**Comment by bsekachev** [comment]
@piotr-sikora-v 

Please, upgrade CVAT first.
