### ISSUE TITLE
Model is deployed and is in ready state but is not visible in CVAT.

### ISSUE THREAD

**Issue by purvaja2001** [opencv/cvat#7588]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. I deployed the custom model similar to the code as it is there. 
2.  Used the below code for deployment
. serverless/deploy_cpu.sh serverless/pytorch/facebookresearch/custom_model
3. The model is deployed and is in ready state 
4. Logs are also checked but no error is there.
5. But when I am trying to access that model in CVAT I am unable to see the model there. But getting the below error. Need some help here.
![IMG_20240311_221017](https://github.com/opencv/cvat/assets/145646908/5187a58e-af9d-42de-b653-53b0db845a3a)

**Comment by bsekachev** [comment]
Hello,
1. That is not a bug if you are using custom model.
2. Check you logs from `cvat_server` container to get more information about code 500.
