### ISSUE TITLE
Problem with the annotation export

### ISSUE THREAD

**Issue by Estariol4** [opencv/cvat#7589]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. Export the annotations
2. Choose CVAT for Video 1.1
3. Receive the message with error: Could not export dataset for the task xxxxxx — ValueError: operands could not be broadcast together with shapes (0,) (6,)

### Expected Behavior

I expected to export the annotations. For every other similar task it works well. Task has rectangle tracks and skeleton tracks. It is impossible to export the annotation in any of the formats.

### Environment

I am using your platform app.cvat.ai
Operating system: MacOS 12.6.1

**Comment by bsekachev** [comment]
Hello, 

Please, fill the environment. Otherwise the issue will be closed.

**Comment by Estariol4** [comment]
Hello, I have updated this section as you asked, but I don't have a lot of information to provide since I use CVAT on your servers

**Comment by bsekachev** [comment]
If that is our platform, than please provide your username.

**Comment by Estariol4** [comment]
ivan1

**Comment by bsekachev** [comment]
Did you upload annotations first to the task and then adjusted it? 
Or it was full annotating from scratch?

**Comment by bsekachev** [comment]
You have several corrupted keyframes in annotations.
Like this. As you can see, "points" array is empty for some of tracked shapes. That does not seem to be correct. 

![image](https://github.com/opencv/cvat/assets/40690378/a48f33ef-47e0-4b04-8d22-1456e45d8cc5)

**Comment by Estariol4** [comment]
Thank you for the explanation. Everything was done from scratch, there are only 2 tasks with this issue: 520915 and 526001. Is there any way to detect tracked shapes with this issue from the tool interface? or can it only be done on your side? Is there anything I can do to prevent these issues to appear? @bsekachev

**Comment by bsekachev** [comment]
1. Export as datumaro
2. Text search `"points": []`, remove.
3. Import back
4. Export as CVAT for Video.

**Comment by Estariol4** [comment]
Thank you so much! I have found only the backup guide for docker. Is there way to restore annotations using the platform? Can it be performed via the "upload annotations" action? @bsekachev

**Comment by bsekachev** [comment]
https://opencv.github.io/cvat/docs/manual/advanced/backup/

**Comment by Estariol4** [comment]
thank you!

**Comment by Estariol4** [comment]
Hello @bsekachev, I tried to upload the .zip with backup, however I receive the message that archive doesn't contain the task.json file. That is strange since the file is in archive. Could you please explain how resolve this issues?
<img width="385" alt="Screenshot 2024-03-20 at 18 34 50" src="https://github.com/opencv/cvat/assets/65850038/43d65d09-d493-4a52-bb05-6c6517ec3c1a">
<img width="251" alt="Screenshot 2024-03-20 at 18 36 37" src="https://github.com/opencv/cvat/assets/65850038/88bb94af-5f2b-47e6-b758-cd393a40b657">

**Comment by Estariol4** [comment]
@bsekachev

**Comment by bsekachev** [comment]
Export any backup from CVAT and compare archive formats. I suspect there is extra top level directory

**Comment by Estariol4** [comment]
Thank you, it worked
