### ISSUE TITLE
To download all the annotations of all Tasks at once

### ISSUE THREAD

**Issue by purvaja2001** [opencv/cvat#7613]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

Currently, There is download Project where only the images of all tasks are being saved.
Is it possible to extend this to download annotations in COCO JSON format as well? 

### Describe the solution you'd like

To be able to download the annotations at once for all tasks.

**Comment by adkbbx** [comment]
@purvaja2001 Is it posiible give a bit more information on the issue since I think it is possible to download the annotations of all the tasks in the format you wish if it is grouped under a single project.

**Comment by purvaja2001** [comment]
Yes found that, thank you!
