### ISSUE TITLE
can't install cvat v1.0.0

### ISSUE THREAD

**Issue by wanghaowish** [opencv/cvat#7629]
I want to deploy cvat for v1.0.0, here are my steps:
1. wget https://github.com/opencv/cvat/archive/refs/tags/v1.0.0.zip
2. unzip v1.0.0.zip && mv cvat-1.0.0 cvat && cd cvat
3. export CVAT_HOST=10.10.9.235
4. docker compose up -d
Prompt the following error：
`[+] Running 1/1
 ! cvat Warning                                                                                                                                                                       33.7s 
[+] Building 44.5s (15/30)                                                                                                                                                   docker:default
 => [cvat internal] load build definition from Dockerfile                                                                                                                              0.0s
 => => transferring dockerfile: 5.40kB                                                                                                                                                 0.0s
 => [cvat internal] load .dockerignore                                                                                                                                                 0.1s
 => => transferring context: 116B                                                                                                                                                      0.1s
 => [cvat internal] load metadata for docker.io/library/ubuntu:16.04                                                                                                                  15.3s
 => [cvat internal] load build context                                                                                                                                                 0.3s
 => => transferring context: 25.07MB                                                                                                                                                   0.2s
 => [cvat  1/26] FROM docker.io/library/ubuntu:16.04@sha256:0f71fa8d4d2d4292c3c617fda2b36f6dabe5c8b6e34c3dc5b0d17d4e704bd39c                                                           0.0s
 => CACHED [cvat  2/26] RUN apt-get update &&     apt-get --no-install-recommends install -yq         software-properties-common &&     add-apt-repository ppa:mc3man/xerus-media -y   0.0s
 => CACHED [cvat  3/26] WORKDIR /home/django                                                                                                                                           0.0s
 => CACHED [cvat  4/26] RUN adduser --shell /bin/bash --disabled-password --gecos "" django &&     if [ -z  ]; then         echo export "GIT_SSH_COMMAND="ssh -o StrictHostKeyCheckin  0.0s
 => [cvat  5/26] COPY components /tmp/components                                                                                                                                       0.1s
 => [cvat  6/26] RUN if [ "no" = "yes" ]; then         /tmp/components/openvino/install.sh &&         mkdir /home/django/reid &&         curl https://download.01.org/openvinotoolkit  0.5s
 => [cvat  7/26] RUN if [ "no" = "yes" ]; then         bash -i /tmp/components/tf_annotation/install.sh;     fi                                                                        0.8s
 => [cvat  8/26] RUN if [ "no" = "yes" ]; then     bash -i /tmp/components/auto_segmentation/install.sh;     fi                                                                        0.7s
 => [cvat  9/26] COPY cvat/requirements/ /tmp/requirements/                                                                                                                            0.0s
 => [cvat 10/26] COPY supervisord.conf mod_wsgi.conf wait-for-it.sh manage.py /home/django/                                                                                            0.1s
 => ERROR [cvat 11/26] RUN python3 -m pip install --no-cache-dir -r /tmp/requirements/production.txt                                                                                  26.5s
------                                                                                                                                                                                      
 > [cvat 11/26] RUN python3 -m pip install --no-cache-dir -r /tmp/requirements/production.txt:                                                                                              
17.59 Error processing line 1 of /usr/local/lib/python3.5/dist-packages/distutils-precedence.pth:                                                                                           
17.59                                                                                                                                                                                       
17.59   Traceback (most recent call last):                                                                                                                                                  
17.59     File "/usr/lib/python3.5/site.py", line 173, in addpackage                                                                                                                        
17.59       exec(line)
17.59     File "<string>", line 1, in <module>
17.59     File "/usr/local/lib/python3.5/dist-packages/_distutils_hack/__init__.py", line 187
17.59       f'spec_for_{name}',
17.59                        ^
17.59   SyntaxError: invalid syntax
17.59 
17.59 Remainder of file ignored
17.59 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/click/
19.60 Collecting click==6.7
20.31   Downloading click-6.7-py2.py3-none-any.whl (71 kB)
21.95 Collecting Django==2.2.10
22.15   Downloading Django-2.2.10-py3-none-any.whl (7.5 MB)
23.98 Collecting django-appconf==1.0.2
24.12   Downloading django_appconf-1.0.2-py2.py3-none-any.whl (7.4 kB)
24.63 Collecting django-auth-ldap==1.4.0
24.78   Downloading django_auth_ldap-1.4.0-py2.py3-none-any.whl (21 kB)
25.13 Collecting django-cacheops==4.0.6
25.27   Downloading django-cacheops-4.0.6.tar.gz (52 kB)
25.33     ERROR: Command errored out with exit status 1:
25.33      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f4cy1_v_/django-cacheops/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f4cy1_v_/django-cacheops/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-f4cy1_v_/django-cacheops/pip-egg-info
25.33          cwd: /tmp/pip-install-f4cy1_v_/django-cacheops/
25.33     Complete output (18 lines):
25.33     Error processing line 1 of /usr/local/lib/python3.5/dist-packages/distutils-precedence.pth:
25.33     
25.33       Traceback (most recent call last):
25.33         File "/usr/lib/python3.5/site.py", line 173, in addpackage
25.33           exec(line)
25.33         File "<string>", line 1, in <module>
25.33         File "/usr/local/lib/python3.5/dist-packages/_distutils_hack/__init__.py", line 187
25.33           f'spec_for_{name}',
25.33                            ^
25.33       SyntaxError: invalid syntax
25.33     
25.33     Remainder of file ignored
25.33     Traceback (most recent call last):
25.33       File "<string>", line 1, in <module>
25.33       File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 95
25.33         dist.announce(f"\n{msg}\n")
25.33                                  ^
25.33     SyntaxError: invalid syntax
25.33     ----------------------------------------
25.50 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
26.34 WARNING: You are using pip version 20.0.1; however, version 20.3.4 is available.
26.34 You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
------
failed to solve: executor failed running [/bin/sh -c python3 -m pip install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt]: exit code: 1`

**Comment by bsekachev** [comment]
We will not consider this like an issue, please use latest releases
