### ISSUE TITLE
I don't have administration panel

### ISSUE THREAD

**Issue by 2013zhouying** [opencv/cvat#763]
After i install the Analytics for Computer Vision Annotation Tool (CVAT)
# From project root directory
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml build
# From project root directory
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up -d
docker-compose up -d 

I still have only these two options (Creat New Task and User Guide).
Why, can someone help me?  Thank you very much.

**Comment by azhavoro** [comment]
Hi @2013zhouying,
Looks like the last command is not needed. In components/analytics/docker-compose.analytics.yml defined some env variables that required by CVAT and last command recreates CVAT container without passing them.
Please try to use:
```
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml build
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up -d
```
or one line command variant
```
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up -d --build
```

**Comment by 2013zhouying** [comment]
Thank you very much
