### ISSUE TITLE
High Latency for Label APIs in Large CVAT Projects

### ISSUE THREAD

**Issue by harryp-cw** [opencv/cvat#7630]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Description
We are experiencing very high latency with Label APIs in some of our large CVAT projects, which contain hundreds of tasks and over a thousand labels. The project detail page load time is exceptionally high, primarily due to multiple calls to the Label API.

### Steps to Reproduce
1. Access a large CVAT project with 100s of tasks and 1000+ labels.
2. Observe the latency in loading the project detail page.

### Expected Behaviour
The project detail page should load within a reasonable amount of time.

### Actual Behaviour
The project detail page takes an exceptionally long time to load, mainly due to the following API call being made multiple times:

This API is called 4 times to accommodate the 1500+ labels.
https://<hostname>/api/labels?project_id=49&org=&page_size=500&page=1

### Investigation
Upon further investigation, it was found that the majority of the time is consumed by the `LabelSerializer` class in `serializer.py`. Each label record takes approximately 0.06 seconds at the `LabelSerializer.to_representation` function call, resulting in a total response time of about 32.5 seconds for a single label API call.

###Attempted Solutions
Increased memory and CPU for the `backend-server` pod, but no significant change was observed.

### Request
We are seeking assistance in optimizing the performance of the Label API to reduce the latency experienced in large projects.

### Expected Behaviour

The project detail page should load within a reasonable amount of time.

### Environment

```Markdown
- CVAT version: v2.11.0
- Deployment: Google Kubernetes Engine (GKE)
- Database: Cloud SQL PostgreSQL
- Cache: Redis (MemoryStore)
```

**Comment by bsekachev** [comment]
Hello,

It is not clear what we are supposed to do with the issue. We also have some performance problem and improve it gradually. But we can't investigate exactly your use-case. 
Please, send us PRs with optimizations if you have any.
