### ISSUE TITLE
Allow Siammask active tracker to run for more frames

### ISSUE THREAD

**Issue by siddtmb** [opencv/cvat#7639]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

# I hope this does not get taken down as a duplicate. The previous issue was closed without ever being resolved to my knowledge/understanding. If I am wrong in my understanding, please guide me.

### Is your feature request related to a problem? Please describe.

I don't know why the automatic annotation for "Allow Siammask active tracker to run for more frames" was closed, at the moment, it can only run on the frame you are on and is incredibly slow. Let me know if I am incorrect in my understanding, if so, how do I make it run for the next 100 frames?

### Describe the solution you'd like

If v is pressed (skip with jump) just annotate all the frames till that jump in a single server request. Or let us set the number of future frames to auto-annotate in some config or option menu.

### Describe alternatives you've considered

I could keep pressing F key for hours on my computer... I shouldn't have to mention why that is very undesirable. Makes this useless and unusable, especially with how slow siammask runs at the moment. It is odd because the official implementation is blazing fast.

### Additional context

There was a previous issue that was closed and it seems it was closed without ever actually addressing the issue.

**Comment by bsekachev** [comment]
Dublicate #5686 #7515
