### ISSUE TITLE
Can't import CVAT XML format for videos

### ISSUE THREAD

**Issue by unamed-** [opencv/cvat#764]
I have a task consisting of multiple segments, each with interpolation annotations. The task was created from a video using a frame filter with "step=5".

I exported the task with "CVAT XML 1.1 for videos" and inspecting the xml afterwise all tracks where stored correctly. Although when I imported the XML again in the same task, only the first track was showing on incorrect frames. After inspecting the "cvat.py" and comparing the frame numbers, I figure the step size is not considered when importing the file.

Unfortunately I can't show screenshots of the example, but to describe the problem more precise:
In the CVAT Client the task consists of 32999 frames, split to 7 segments with each 5000 frames. In each segment I created a track with around 1000 frames. After exporting the XML file has 7 tracks, but the first track starts at frame 0 and ends at frame 5675. The boxes in the track are defined in steps of 5, hence my conclusion. When I import the XML again, the only track I can see is the one starting at frame 0 and ending at frame 5675 (already in the second segment).

I hope my description is somehow understandable and the problem can be fixed, as I need this use case.

Thanks in advance for your help and this great tool!

**Comment by nmanovic** [comment]
@azhavoro , please try to reproduce and fix.

**Comment by manisoftwartist** [comment]
I have been trying to use this tool. The first issue I faced is with transformin gour bounding box data into the CVAT XML format. I solved a couple of problems before I could get CVAT to load our annotations. I remember 2 of them: the first being presence of nan in some of our data files with missing bounding boxes, the "outside" attribute in box tags were all 0 for certain tracks.  
@unamed- If you have the XML file which actually contains the interpolation annotations and a video file with those frames (if that is possible), please share so the developers can reproduce your bug. Or perhaps provide you a suggestion how to go around this issue, if at all this is possible.

**Comment by unamed-** [comment]
@manisoftwartist I created the annotations using the tool, therefore the creation of the XML is successful as long as no steps are set as filter. I don't really understand your suggestion, I described the problem as accurate as possible and also mentioned that I cannot upload the video and xml (also it shouldn't be necessary as the problem is with the XML creation and not my video file).

**Comment by zhiltsov-max** [comment]
I guess, it is fixed already - exporting and importing tracks from multiple jobs as `CVAT for video` provides the same annotations. If you still can reproduce it, don't hesitate to reopen the issue.
