### ISSUE TITLE
The content of the output annotation file is empty

### ISSUE THREAD

**Issue by Tanxinman** [opencv/cvat#7643]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

I annotated 329 images, each with only one circle label. When I output the annotation file, all txt in yolov1 are empty, and the XML file in the annotations folder in pascal_voc does not contain boundary coordinate information.

![image](https://github.com/opencv/cvat/assets/58769184/f90ca671-fb06-448e-a942-18caf796d888)

![image](https://github.com/opencv/cvat/assets/58769184/05250302-a60c-4b2d-822d-36487eb6c81f)

![image](https://github.com/opencv/cvat/assets/58769184/6f47fcf5-5ffe-48dd-b8f8-efa1dca88b29)

### Environment

```Markdown
windows10
docker 4.25.2
cvat server version 2.12.0
```

**Comment by zhiltsov-max** [comment]
Hi! Both YOLOv1 and PASCAL VOC (xml) formats contain only bbox information in the annotations, all the other annotations are filtered out during exporting. For PASCAL VOC, you can find the circles in the exported segmentations.
