### ISSUE TITLE
Rotated Box set to Zero on attribute change

### ISSUE THREAD

**Issue by eldadv** [opencv/cvat#7644]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. Open an task with existing rotated boxes, imported from a different CVAT user (say an external contractor, CVAT VIDEO format).
2. Change an attribute in an existing label-track.
3. The rotated box angle is reset to ZERO.
4. USER has to rotate the box again to the previous angle.

### Environment

```Markdown
server 2.1
core 5.0.1
canvas 2.13.2
ui 1.37
```

**Comment by bsekachev** [comment]
The version is too old, please submit bugs only from latest releases. 
Try to upgrade.
