### ISSUE TITLE
Docker build fails when deploying custom model

### ISSUE THREAD

**Issue by camkisailus** [opencv/cvat#7645]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

I have the following directory structure:

```
segformer-person/
└── nuclio
    ├── config.json
    ├── function-gpu.yaml
    ├── function.yml
    ├── main.py
    ├── model.safetensors
    └── pytorch_model.bin
```
In my function_gpu.yml, I attempt to copy over the model and weights as such:

```
- kind: COPY
          value: {ABSOLUTE_PATH}/config.json /opt/nuclio/segformer-person/model/config.json
        - kind: COPY
          value: {ABSOLUTE_PATH}/model.safetensors /opt/nuclio/segformer-person/model/model.safetensors
        - kind: COPY
          value: {ABSOLUTE_PATH}/pytorch_model.bin /opt/nuclio/segformer-person/model/pytorch_model.bin
```
I try to deploy the model using 

`./serverless/deploy_gpu.sh serverless/custom/segformer-person/nuclio`

but the COPY command fails with:

```
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref dbfa48f1-1535-42fa-8794-cfad4fcd008e::vo2qis6iaccs3znwrz1crddb9: "/home/thoro-ml/cvat-2.5.2/serverless/thoro/segformer-person/nuclio/pytorch_model.bin": not found
```

### Expected Behavior

Deploy to GPU succesfully.

**Comment by bsekachev** [comment]
We can't help with custom models, sorry.
