### ISSUE TITLE
Export annotations generating individual JSON files

### ISSUE THREAD

**Issue by cericattojulia** [opencv/cvat#7647]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

It is possible to export annotations from a job or a task in a way that generates individual JSON files for each of the images, instead of generating a single file containing the entire job or task?

**Comment by zhiltsov-max** [comment]
Hi, please be more specific about the output format. There is no such thing as "JSON" dataset format, JSON is just a "language" to describe arbitrary data, the same as XML. But answering to the question - no, there are no formats currently in CVAT that would store annotations for each frame in a separate file. It's not hard to do this manually, though, e.g. starting from the Datumaro format, as it already stores annotations as json structures, one per frame, just in a single file.
