### ISSUE TITLE
Move multiple track rectangles together.

### ISSUE THREAD

**Issue by jhaggle** [opencv/cvat#7655]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

Assume you want to track the two digits in this sign with two track rectangles. Ofc they move together. There should really now may to select the two rectangles and move them together?

![image](https://github.com/opencv/cvat/assets/11705343/5bb510e5-1cf2-41c9-985a-df3b85ee1cd5)

### Describe the solution you'd like

Implement the feature described above

**Comment by bsekachev** [comment]
Duplicate #3069
