### ISSUE TITLE
Projects search doesnt work with single letters

### ISSUE THREAD

**Issue by syedbarimanjan** [opencv/cvat#7660]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. Search for a in the searchbar of projects page and it will render all of the projects.

### Expected Behavior

The search should show only projects starting with a.

**Comment by thekavikumar** [comment]
@syedbarimanjan sure

**Comment by bsekachev** [comment]
> The search should show only projects starting with a.

No. It checks including, not starting with.

**Comment by bsekachev** [comment]
I may suggest you to implement one more filter. Now it also supports only `Contains` rule. 
If the use-case is important for you.

![image](https://github.com/opencv/cvat/assets/40690378/1ea6b15f-c2a7-4c24-9c90-2ffc7951826e)
