### ISSUE TITLE
Downloading Annotations in name of the task order

### ISSUE THREAD

**Issue by berengueradrian** [opencv/cvat#7677]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

I am downloading my annotations from several tasks and I need them to be in a specific order by task name and not by task id which is how it is being downloaded now. I would like to know if it is possible to download them in the task name alphabetically order.

### Describe the solution you'd like

I would like to be able to download the annotations in the order that I have sorted the tasks right in the moment of download.

### Describe alternatives you've considered

I have thought that maybe if I could edit the tasks ids, it could work in some way, I have CVAT built locally, I don't know if this could be possible.

### Additional context

I am working in a project in which it is needed to have the different videos ordered in specific order for the correctness of them so it is necessary for them to be in order.

**Comment by bsekachev** [comment]
Hello, 
I can't really understand the request, you may sort tasks by many parameters and download as you wish. 
![image](https://github.com/opencv/cvat/assets/40690378/53545361-c238-42d1-a625-bcbf141da7b4)

**Comment by berengueradrian** [comment]
Hi, that is what I tried. I ordered it by names but when I download it, the order is lost, it does not matter what order I do, the export with YOLO version is being done in the descending ID order.

**Comment by bsekachev** [comment]
Still not clear what you want to be sorted. Each export creates a new archive. 
One task = one archive.

**Comment by bsekachev** [comment]
Do you mean you are trying to export a project with 100+ tasks?

**Comment by bsekachev** [comment]
That is not a bad practice, but here you do not have an option to sort tasks in necessary order.

**Comment by berengueradrian** [comment]
Ok, and is there any way to sort them in a necessary order?

**Comment by bsekachev** [comment]
Download one by one.

**Comment by berengueradrian** [comment]
Ok, thanks a lot for the help.
