### ISSUE TITLE
It can not be processed. You can upload one or more videos

### ISSUE THREAD

**Issue by xiakj** [opencv/cvat#7679]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

when upload data, comes to this error:"It can not be processed. You can upload one or more videos".
the data format is zip or source image data.
Is the CVAT can only support upload videos data?
![image](https://github.com/opencv/cvat/assets/15704302/894df084-df77-4bcf-b62f-ec816668d9f8)

**Comment by xiakj** [comment]
It can not be processed. **You can upload one or more videos**
![image](https://github.com/opencv/cvat/assets/15704302/a96f9574-647f-401d-9d09-eff4184cb012)

**Comment by xiakj** [comment]
the cvat version is v2.5.0

**Comment by bsekachev** [comment]
Please, read documentation first: 
https://opencv.github.io/cvat/docs/manual/basics/create_an_annotation_task/
https://opencv.github.io/cvat/docs/manual/basics/create-multi-tasks/
