### ISSUE TITLE
Running CVAT on a specified url path

### ISSUE THREAD

**Issue by MarvinKlemp** [opencv/cvat#7686]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

Is there any way to host CVAT after a URL path?
like: `localhost:8080/cvat` instead of `localhost:8080`

I played around with the traefik rules but could not achieve it.
Any ideas?

**Comment by bsekachev** [comment]
No, there is no formal way to do that.
