### ISSUE TITLE
The cvat interface doesn't have both analytics and model manager features. 

### ISSUE THREAD

**Issue by 2013zhouying** [opencv/cvat#769]
I installed cvat on ubuntu 16.04 according to the quick installation guide, after completing the installation of additional components.  The cvat interface still doesn't have both analytics and model manager features.

**Comment by bsekachev** [comment]
@2013zhouying 

What command have you used to build?

**Comment by benhoff** [comment]
You'll want to follow the instructions here to get model manager: https://github.com/opencv/cvat/blob/develop/components/openvino/README.md

**Comment by 2013zhouying** [comment]
> You'll want to follow the instructions here to get model manager: https://github.com/opencv/cvat/blob/develop/components/openvino/README.md

> @2013zhouying
> 
> What command have you used to build?

I used OpenVINO toolkit 2019R3 before, but then I came out with the manger interface of OpenVINO toolkit 2018R5.  thank you for setting up this marking software，I'll support and refuel you.

**Comment by bsekachev** [comment]
@2013zhouying 

Interface doesn't depend on OpenVINO version. 
Probably you have used wrong command for build in the first time.

**Comment by xinyuabcd** [comment]
I met the same problem that the cvat interface still doesn't have both analytics and model manager features when I installed cvat on ubuntu 18.04 according to the quick installation guide:
https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md

**Comment by bsekachev** [comment]
@xinyuabcd 

Commands from quick installation guide don't give you these components. Please read (advanced)[https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#additional-components] options.

**Comment by nmanovic** [comment]
@2013zhouying, @xinyuabcd , the functionality works properly on our side. Without extra information we are impossible to investigate the issue. Let's close the issue for now. Don't hesitate to reopen it if you have more information for us.
