### ISSUE TITLE
Where is the attempted backup

### ISSUE THREAD

**Issue by Petros626** [opencv/cvat#7700]
Hey guys,

I'm using CVAT on Windows and tried the backup of my project and a example task, but suddenly I ran out of memory on my ssd. I choosed the option save local, but I can't find the files anymore. Where can I find these two failed attempts to delete them, because I got 0 GB rest memory.

Thanks in advance

**Comment by bsekachev** [comment]
- If the file was downloaded, you may find it in a folder where your browser saves downloaded files.
- If you run out of memory during CVAT was preparing the file internally, you may find it within the docker container, e.g.


```bash
docker exec -it cvat_server bash
cd /home/django/projects/<project_id>/export_cache

# or

cd /home/django/tasks/<task_id>/export_cache
```

**Comment by Petros626** [comment]
The downloads are empty, because the file was prepared and not succesfully downloaded.

The mysterious issue is, that in `/home/` there is no django folder only cvat. I can't even start docker or search in my WSL distribution, because lack of memory. Would it be possible that the folder is hidden?

**Comment by bsekachev** [comment]
These paths are not WSL paths, they are path inside Docker container. It has `/home/django/*` directory. 

Try to free up memory to start docker if you can't do that. Also you may try to shrink WSL storage (try to google "shrink wsl disk")

**Comment by Petros626** [comment]
I got the two paths, just to be sure my current tasks will not be affected by deleting the `exported_cache` content, right?

**Comment by bsekachev** [comment]
They will not be affected. It is only export cache. 
Cache will be deleted automatically (I do not remember exact period of time), but exporting process must be successful to schedule removing job. In your case, it probably was not successful because of memory issues.
