### ISSUE TITLE
Problems sorting images in job

### ISSUE THREAD

**Issue by thgpddl** [opencv/cvat#7701]
Problems sorting images in job

As the question, I want the image order to be 1.jpg,2.jpg, 3.jpg when labelling in job ... , how should I achieve this?

**Comment by bsekachev** [comment]
1. Rename them as 01.jpg, 02.jpg, 03.jpg, ... Number of leading zeros depends on total count of files
2. Use predefined sorting method when create a task (`manifest.jsonl` must be provided within a list of files when creating a task)
