### ISSUE TITLE
Using the Helm deployment CVAT unable to login

### ISSUE THREAD

**Issue by v-wenlong** [opencv/cvat#7702]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

Pods with CVAT are up and running after deployment with helm.
![image](https://github.com/opencv/cvat/assets/152575079/5216193b-f3dc-4fb2-b1d3-e4c185a95b34)

### Expected Behavior

When I run 'minikube service cvat-frontend-service-n ingres-nginx --url' to generate an ip that I can access, I see an error message when I enter the page.
![image](https://github.com/opencv/cvat/assets/152575079/95d7cf31-d155-4544-8500-6828d7b42f2d)
![image](https://github.com/opencv/cvat/assets/152575079/2db65e52-1665-4a1d-86a3-bd5ae3b95a22)

I checked redis and postgresql logs and found no issues.
![image](https://github.com/opencv/cvat/assets/152575079/4baa4885-29d0-43b3-81b4-81f9d4d21066)
![image](https://github.com/opencv/cvat/assets/152575079/bb2036b2-fbb8-47a8-a0a3-430d03cec775)

Below is my frontend log, which shows 405 issues:
10.244.0.1 - - [29/Mar/2024:07:19:01 +0000] "GET / HTTP/1.1" 200 1077 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:02 +0000] "GET /api/users/self?org= HTTP/1.1" 200 1077 "http://127.0.0.1:5386/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:02 +0000] "GET /api/users/self?org= HTTP/1.1" 200 1077 "http://127.0.0.1:5386/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:02 +0000] "GET /favicon.ico HTTP/1.1" 200 1077 "http://127.0.0.1:5386/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:02 +0000] "GET /api/restrictions/user-agreements?org= HTTP/1.1" 200 1077 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:02 +0000] "OPTIONS /api/auth/password/change?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:02 +0000] "OPTIONS /api/auth/password/reset?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:02 +0000] "GET /favicon.ico HTTP/1.1" 200 1077 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:20 +0000] "OPTIONS /api/auth/password/change?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:20 +0000] "OPTIONS /api/auth/password/reset?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:20 +0000] "GET /favicon.ico HTTP/1.1" 200 1077 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:31 +0000] "GET /auth/login HTTP/1.1" 200 1077 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:32 +0000] "GET /api/users/self?org= HTTP/1.1" 200 1077 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:32 +0000] "GET /api/users/self?org= HTTP/1.1" 200 1077 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:32 +0000] "OPTIONS /api/auth/password/change?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:19:32 +0000] "OPTIONS /api/auth/password/reset?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:20:14 +0000] "POST /api/auth/login?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:28:45 +0000] "POST /api/auth/login?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:30:38 +0000] "POST /api/auth/login?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:31:30 +0000] "POST /api/auth/login?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:32:24 +0000] "POST /api/auth/login?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:33:10 +0000] "POST /api/auth/login?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"
10.244.0.1 - - [29/Mar/2024:07:33:16 +0000] "POST /api/auth/login?org= HTTP/1.1" 405 559 "http://127.0.0.1:5386/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" "-"

### Context

I want to implement the basic functionality of being able to log into the cvat application and use cvat normally.

### Environment

```Markdown
docker version: 25.0.3
minikube version: 1.32.0
cvat version: 2.1.0
```

**Comment by bsekachev** [comment]
Hello, 

Please, try the latest release first. We will not look at issues in 2.1.0 version.

**Comment by waryak** [comment]
@bsekachev Hi!
I have the same 405 error on `api/auth/login` for the latest `2.7.6` release.
Shall we reopen issue?
