### ISSUE TITLE
Cannot Export nor Backup

### ISSUE THREAD

**Issue by JFMeyer2k** [opencv/cvat#7708]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

For any task, click 'Actions' -> 'Export tasks dataset'.
Pick any Format
The file does not download.

Furthermore, 'Actions' -> 'Backup task' also does not work.

### Expected Behavior

For any task, click 'Actions' -> 'Export tasks dataset'.
Pick any Format
A file in the respective format starts to download.

Furthermore, 'Actions' -> 'Backup task' downloads the backup of the task

### Environment

[CVAT.ai](https://app.cvat.ai/)

**Comment by fanyujie** [comment]
I got the same issue.

**Comment by mananme02** [comment]
Even I am getting the same issue, not able to export annotations.

**Comment by bsekachev** [comment]
Are u still experience the issue? There was a long queue of requests, but now it is resolved.

**Comment by JFMeyer2k** [comment]
The issue seems to be resolved. 
Thanks
