### ISSUE TITLE
UI becomes slow when current annotation has too many points in polygon

### ISSUE THREAD

**Issue by rsnk96** [opencv/cvat#773]
The UI starts to become slow when there are a lot of points that are defined in the polygon mode.

As the shape is being drawn in the polygon mode, the two polygon edges on MouseMove slowly trails the mouse movement.

In case an image is already annotated with polygons with a lot of points defining their shape, the UI slows down shifting to/from that image

**Comment by bsekachev** [comment]
Probably related: #1141, #1182
Should be fixed in old UI with: #1197
React UI doesn't have such a problem. 

Let me now if the PR doesn't help.
