### ISSUE TITLE
When the video is played, the video is jammed and loaded slowly.

### ISSUE THREAD

**Issue by 2013zhouying** [opencv/cvat#775]
We have 100M bandwidth and good network speed, but when we play video on CVAT, no matter how big the video is, it will be jammed and loaded slowly;  why? what can be improved?  thank you very much~

**Comment by nmanovic** [comment]
Hi @2013zhouying ,

I believe the problem with how CVAT is serving frames to a client. It splits the video into separate frames and send them one by one. The problem should be solved very soon with the PR: https://github.com/opencv/cvat/pull/760


Could you please describe your task? Why do you need "real time" video streaming?

**Comment by 2013zhouying** [comment]
The video that we want to annotate is very long and with high resolution. Thus, it costs much time for the annotater to load the video sequence. Yes, it will not impact the annotation result but slow down the annotation work. I am wondering whether I can resize the video into a lower resolution when release the annotation task, or maybe you have any good idea/soution to solve this problem. Thanks a lot. 

We want to watch a lot of videos and record the number of starting and ending frames that appear on the target object.

**Comment by nmanovic** [comment]
@2013zhouying , right now you can use "image quality" parameter when creating an annotation task. It is supported out of the box. Thus each frame will be smaller.

> I am wondering whether I can resize the video into a lower resolution when release the annotation task

It is an option which you always can consider (especially if you need only frame numbers and you are not using location of your objects).

I hope till EOY performance of the scenario will be improved dramatically when we integrate the streaming feature.

**Comment by 2013zhouying** [comment]
@nmanovic  I am looking forward to your early integrate the streaming feature, thank you for your hard work

**Comment by nmanovic** [comment]
The data streaming feature was integrated. Please check and let us know if you see problems which we need to address.
