### ISSUE TITLE
Importing a skeleton track with no shapes for one of the points leads to import crash

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#7783]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a task from backup 
[task_test_6779-job-overlap-merge_backup_2024_04_17_12_49_41.zip](https://github.com/cvat-ai/cvat/files/15011261/task_test_6779-job-overlap-merge_backup_2024_04_17_12_49_41.zip)
1. Import annotations
[annotations-cvat-for-video.zip](https://github.com/cvat-ai/cvat/files/15011267/annotations-cvat-for-video.zip)

### Possible Solution

Can probably be fixed by adding this [here](https://github.com/cvat-ai/cvat/blob/a5269b056341db726da01c2d779d6e3dbb20c8bc/cvat/apps/dataset_manager/annotation.py#L540):

```python
    def _modify_unmatched_object(self, obj, end_frame):
        if not obj["shapes"]:
            return
```

Once done, leads to the problem #6779.

### Context

Related https://github.com/cvat-ai/cvat/issues/6779
Related https://github.com/cvat-ai/cvat/pull/7669

**Comment by Eldies** [comment]
fixed in https://github.com/cvat-ai/cvat/pull/8377
