### ISSUE TITLE
Add xml upload to CLI (Command Line Interface) 

### ISSUE THREAD

**Issue by NicolasR1** [opencv/cvat#781]
Hi, 

This is a feature request for the Command line interface (CLI).
A must should be to add optionnal **upload** argument to allow annotation upload on task creation :
`cli.py create "new task" --labels labels.json **--upload annotation.xml** local file.avi`

With this amazing feature, one could, for example, uses this workflow : 
1) translate a public dataset format to **annotation.xml**
2) batch the import to cvat through the command line interface

Facilitate public dataset translation to cvat will help massive cvat adoption  !

Best regards,

Nicolas

**Comment by egrinstein** [comment]
Adding the option to upload the annotations with the creation of the task would be great.

**Comment by ncianeo** [comment]
#958 
I added this option to cli
Usage: 
```bash
python cli.py upload [-h] [--format FILEFORMAT] task_id filename
```

FILEFORMAT:
CVAT XML 1.1
PASCAL VOC ZIP 1.0
YOLO ZIP 1.0
COCO JSON 1.0
TFRecord ZIP 1.0

**Comment by nmanovic** [comment]
Fixed by @ncianeo. Great job!

**Comment by NicolasR1** [comment]
Thanks a lot  @ncianeo  !

**Comment by egrinstein** [comment]
Great job, @ncianeo !
