### ISSUE TITLE
'share' for windows

### ISSUE THREAD

**Issue by stormchasingg** [opencv/cvat#784]
editing 'docker-compose.override.yml' for 'share' is not available for win10

**Comment by nmanovic** [comment]
@stormchasingg , what do you mean? It is pure docker-compose and docker functionality. I believe it is supported the same way on all OSes.

**Comment by stormchasingg** [comment]
@nmanovic thanks for your reply. maybe because the format of dirs is different between ubuntu and windows. I have found some information in docker compose repository but can't talk it in detail right now. I will close this issue unless I can't figure it out. thx again.
