### ISSUE TITLE
Image captioning

### ISSUE THREAD

**Issue by egrinstein** [opencv/cvat#786]
Is it possible to perform image captioning tasks on Cvat, that is, assigning global labels out of a list to an image? 

Thanks,

Eric

**Comment by bsekachev** [comment]
Hi, @egrinstein 
Not exactly. CVAT hasn't able to annotate images directly yet. 
But you can create fake bounding boxes on each image (this is extremely easy, several clicks in UI with propagate function) and annotate these boxes (assign labels from a list) like the images.

**Comment by egrinstein** [comment]
Thank you for the answer, @bsekachev.
I think this solves my issue.
I think implementing the image captioning functionality could benefit many people. I'd be happy to implement it, given some guidance. What do you think?

**Comment by nmanovic** [comment]
@egrinstein , we have such feature request (e.g. https://github.com/opencv/cvat/issues/425). It is implemented on server side and need to support in UI. I will close the issue.

**Comment by egrinstein** [comment]
Hello @nmanovic, thank you for the time. It seems to be indeed similar. I have however a couple questions:
- If I had many labels I'd like to assign to an image, would this be achievable through the grid view feature?
- If I'd like to switch to the single image view to label it, would it still be possible? This would be needed for images with small details, for example.

Best regards,

Eric

**Comment by nmanovic** [comment]
@egrinstein , it should be possible. We will design the feature with all requests from community in our mind.
