### ISSUE TITLE
Subtract one mask from another

### ISSUE THREAD

**Issue by 421psh** [opencv/cvat#790]
Hi!
Thanks a lot for your CVAT, it is extremely helpful.
I would like to know: do you have a tool for a mask subtraction from another one? This opportunity would make life of annotators much easier. For example, they would be able to choose whole road and then adjust its contour by subtracting all cars masks from it.

**Comment by nmanovic** [comment]
@421psh , we have such feature. It is z-order (specify the option when you create a task). Please look at the screencast: https://www.youtube.com/watch?v=Fh8oKuSUIPs&feature=youtu.be

Does it help?

**Comment by 421psh** [comment]
Yes. Thank you!.
