### ISSUE TITLE
get an error loading a model for auto-annotation 

### ISSUE THREAD

**Issue by test4fest** [opencv/cvat#792]
I am trying to use Faster-RCNN model from model zoo of auto annotation from the following link:

https://github.com/opencv/cvat/tree/develop/utils/open_model_zoo/faster_rcnn_inception_v2_coco

I follow the documentation and convert tensorflow model of faster- RCNN to xml and bin files with OpenVini 2019- R3, but when I ran CVAT with OpenVino 2018-R5.
I get this error:

Checking request has returned the "failed" status. Message: Exception: Model was not properly created/updated. Test failed: Error reading network: cannot parse future versions: 6

Does it mean the conversion is not correct, or using different version of OpenVino, or something else?

**Comment by benhoff** [comment]
Different version of OpenVino. You should be able to use OpenVino - R3 with the CVAT installation.

**Comment by test4fest** [comment]
The problem remains unsolved. I can run auto-annotation with person-vehicle auto-annotation model but not aforementioned one.

**Comment by benhoff** [comment]
If you're a Python developer, can you run the following script and post the traceback?

https://github.com/opencv/cvat/tree/develop/utils/auto_annotation

Otherwise I'll try to reproduce tomorrow.

**Comment by benhoff** [comment]
I tried with my local system, but was not able to reproduce. I would try cleaning the docker image. You've probably got a stale OpenVINO installation.

**Comment by test4fest** [comment]
> If you're a Python developer, can you run the following script and post the traceback?
> 
> https://github.com/opencv/cvat/tree/develop/utils/auto_annotation
> 
> Otherwise I'll try to reproduce tomorrow.

Thanks for your reply

I got the foolowing error:

Enter passphrase for /home/username/.ssh/id_rsa: 
SSH keys were not found
Traceback (most recent call last):
  File "/media/username/object-detectioin/tools/CVAT/cvat/utils/auto_annotation/run_model.py", line 16, in <module>
    from cvat.apps.auto_annotation.inference import run_inference_engine_annotation
  File "/media/username/object-detectioin/tools/CVAT/cvat/utils/auto_annotation/../../cvat/apps/auto_annotation/inference.py", line 1, in <module>
    from .model_loader import ModelLoader
  File "/media/username/object-detectioin/tools/CVAT/cvat/utils/auto_annotation/../../cvat/apps/auto_annotation/model_loader.py", line 12, in <module>
    from cvat.apps.auto_annotation.inference_engine import make_plugin, make_network
  File "/media/username/object-detectioin/tools/CVAT/cvat/utils/auto_annotation/../../cvat/apps/auto_annotation/inference_engine.py", line 5, in <module>
    from openvino.inference_engine import IENetwork, IEPlugin
ModuleNotFoundError: No module named 'openvino

**Comment by benhoff** [comment]
That's frustrating! Sorry about that.

Related: https://github.com/opencv/open_model_zoo/issues/71

> Sorry, the models were uploaded a little bit earlier than the upcoming release itself. Once it's out (hopefully, this week) you should be able to run the model. For now, you're better off using the 2018 branch.

[Here's the line of code](https://github.com/opencv/dldt/blob/1c794d971cdd3c94de5ea4a6c9588eac63f4cc57/inference-engine/src/inference_engine/ie_cnn_net_reader_impl.cpp#L137) that is throwing the error.

Potential that they've released the models without the updated code? Or that OpenVINO messed up its versioning. But I don't know that that makes sense given that you hand converted the bin/xml files. Maybe try converting with the 2019 R3 candidate, or an earlier one and see if that works? The above linked issue mentions converting with the 2018 version, which I believe is what I converted with.

I was going to post my bin and xml files to github, but it's over the 10 MB limit on Github, (zipped files together are 200 MB). If you've got a better site to get them to you, let me know and I'll put them up.

**Comment by benhoff** [comment]
If you use the 2018 version, it looks like it will convert to version 3. See here: https://github.com/opencv/dldt/blob/669bee86e580cbbc8ef40b440ab195ba2cbf5142/inference-engine/src/inference_engine/ie_cnn_net_reader_impl.cpp#L144

**Comment by benhoff** [comment]
@test4fest did you ever get this fixed? What was the resolution?

**Comment by savan77** [comment]
@benhoff Using this (https://github.com/opencv/dldt/releases/tag/2018_R5) version solved error for me.

**Comment by anujonthemove** [comment]
> Different version of OpenVino. You should be able to use OpenVino - R5 with the CVAT installation. Try reinstalling the OpenVino component with R5.

I am using OpenVINO version 2019.R3 (l_openvino_toolkit_p_2019.3.376), got error on console: `Checking request has returned the "failed" status. Message: Exception: Model was not properly created/updated. Test failed: module 'cvat.apps.auto_annotation.inference' has no attribute 'run_inference_engine_annotation'`, I then tried out https://github.com/opencv/cvat/tree/develop/utils/auto_annotation but on similar error while running it on terminal `ImportError: cannot import name 'run_inference_engine_annotation' `.

**Comment by azhavoro** [comment]
@anujonthemove Hi, #1826 should fix this issue.
