### ISSUE TITLE
invalid parse_label_arg

### ISSUE THREAD

**Issue by collinarnett** [opencv/cvat#795]
I am trying to use the cli tool to add a lot of annotation jobs at once. The documentation mentions that you can use strings for labels but I am getting the following error:
```
cli.py create: error: argument --labels: invalid parse_label_arg value: 'dag'
```
The documentation also uses the following example:
```
cli.py create "new task" --labels labels.json local file1.jpg file2.jpg
```
however it does not mention what format the json file needs to be in. I have tried my best to find a example of a json label but I only have one label so I would like to pass a single string to `cli.py`

---
The command I originally ran is:
```
~/apps/cvat/utils/cli/cli.py --auth user:"pass" create "new task" --labels dag local file.mp4
```
I isolated this issue by creating a job without passing the tags argument and it works fine.

**Comment by collinarnett** [comment]
I found the details of `label_map` in https://github.com/opencv/cvat/blob/3bc1df8ece87cd65d3e39572e1535d01cc6b35b2/cvat/apps/auto_annotation/README.md but cli.py returns `400 Client Error: Bad Request for url: http://localhost:8080/api/v1/tasks`.

My json file is:
```json
{
"label_map": {
    "1": "DAG",
    "2": "CL"
    }
}
```

**Comment by nmanovic** [comment]
@collinarnett , it is labels for other functionality. The correct format is below:

![image](https://user-images.githubusercontent.com/40690625/67476482-c988f480-f660-11e9-8e1a-1018cf7b8966.png)


For example, 
```
[{
  'name': 'car', 
  'attributes': [{
      'name': 'model',
      'mutable': false,
      'input_type': 'select', 
      'values': ['mazda', 'bmw', 'kia', 'mercedes']
    }]
}, 
{'name': 'person'}
]
```

**Comment by collinarnett** [comment]
Ok that worked. I used 
```json
[{name:DAG}]
```
in my json file and it successfully created a job. It would be nice to be able to just use a string in the command line though.

@nmanovic Thank you for your help

**Comment by nmanovic** [comment]
@collinarnett , I will close the issue in the case.
