### ISSUE TITLE
Adding more properties to project like validator and some exif tags to images

### ISSUE THREAD

**Issue by sankhakarfa** [opencv/cvat#798]
TAG: Question
I want to add more properties to project like validator name and tags to each image which will reflect back in XML output.
I will change the model.py to accommodate the changes.
Anywhere else I have to change to add the extra values.

**Comment by nmanovic** [comment]
@sankhakarfa , I'm not sure that understand what you are going to do. I will suggest discussing such questions on our gitter dev channel: https://gitter.im/opencv-cvat/dev

I will close the issue for now.
