### ISSUE TITLE
Can not creating task with large total size 

### ISSUE THREAD

**Issue by gachiemchiep** [opencv/cvat#799]
Hello cvat team.

Currently, I'm doing annotation for the following 2 dataset

1. 143 images, image size is 1920x1080. 
    The total size of 143 images is around 360 MB
2. 437 images, image size is 1920x1080. 
    The total size of 143 images is around 1.3 GB

For the first dataset, I can sucessful create the task. 
But for the second dataset, the following error occurred.

![image](https://user-images.githubusercontent.com/2300329/67613103-73dd5500-f7e4-11e9-896b-beed5eb5d157.png)

```bash
Could not put data to the server. Request failed with status code 413. 
"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n
<html><header>\n<title>413 Request Entity Too Large</title>\n</head><body>\n<h1>
Request Entity Too Large</h1>\nThe requested resource does not allow request data with POST requests, or the amout of data provided in \nthe request exceeds the capacity limi.\n</body></html>\n". Code 413
```

Is there any configuration that I can use to change the capacity limit?

**Comment by bsekachev** [comment]
@gachiemchiep 

You can connect a share folder with any data to CVAT container. Look [there].(https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path)

**Comment by gachiemchiep** [comment]
Hello @bsekachev 

I tried your link but but failed to. 
My *docker-compose.override.yml*  is as follows.

```bash
version: "2.3"

services:
  cvat:
    # ports:
      # - "80:8080"
    build:
      context: .
      args:
        TF_ANNOTATION: "yes"
    environment:
      CVAT_SHARE_URL: "Mounted from /datadrive/cvat host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /datadrive/cvat


```
The same error happened.

![image](https://user-images.githubusercontent.com/2300329/67619822-41ab1200-f83b-11e9-9ab1-c1203db5f783.png)

**Comment by bsekachev** [comment]
@gachiemchiep 

Use the "share" option.

**Comment by gachiemchiep** [comment]
@bsekachev 

I chose the "share" option but when I click "Select files", a blank box appears and I can not upload or drag/drog images.

![image](https://user-images.githubusercontent.com/2300329/67619995-1aeddb00-f83d-11e9-9024-38f2f7f1e68a.png)


![image](https://user-images.githubusercontent.com/2300329/67619990-0e698280-f83d-11e9-9f03-f9f12fe9bccc.png)

**Comment by bsekachev** [comment]
@gachiemchiep 

It isn't upload/drag-and-drop window.
It is expected that here you can browse a shared directory ``/datadrive/cvat`` in your case and upload files from there.  

But something wrong on the screenshot above. Do you have any exceptions in dev console? (F12, Console tab)

**Comment by gachiemchiep** [comment]
Hello @bsekachev 

I forgot to put files inside the share directory, so nothing appeared. After putting files into share directory, files did appear and I can create a big task now. 

Thank you very much. 

![image](https://user-images.githubusercontent.com/2300329/67621935-a1131d00-f84f-11e9-83db-a8aef8204c2b.png)

**Comment by mengfu188** [comment]
When I use `ln -s` it didn't not appear. It should use `cp`
