### ISSUE TITLE
Video/Image loading status as on youtube

### ISSUE THREAD

**Issue by headdab** [opencv/cvat#8]
Another question and likely feature suggestion.

When start a job, if I wait long enough, will all the frames be loaded into the browser?
Or, are they loaded on demand as I seek through the video?
Are they cached locally in memory?

I'm working with 4k video and the interface isn't that usable, at least for my current use model, until all frames have been loaded.

Based on the answer above, it would be great to have feedback as to whether the frames have all been loaded or, better, which frames have been loaded.   What I've seen that works well is using a different color on the seek bar for frames that have been loaded.

If they are demand loaded, it would be nice to have a way to force it to load them all (as long as there's enough memory available).

**Comment by nmanovic** [comment]
> When start a job, if I wait long enough, will all the frames be loaded into the browser?
Or, are they loaded on demand as I seek through the video?

No, they don't. To reduce server load it will try to preload next 500 frames and it will continue preload other frames as soon as necessary. After jump it will start preload next frames from the new position.

> Are they cached locally in memory?
Yes.

> I'm working with 4k video and the interface isn't that usable, at least for my current use model, until all frames have been loaded.

Could you please describe your annotation use case? Another way to optimize your case is to resize the video before uploading to CVAT.

> What I've seen that works well is using a different color on the seek bar for frames that have been loaded.

I like the feature. I will add it into our internal roadmap. It should not be difficult to implement.

> If they are demand loaded, it would be nice to have a way to force it to load them all (as long as there's enough memory available).

Let's understand your use case. If you annotate with a reasonable speed (e.g. several seconds per image) CVAT should be fast enough to preload next frames for you.

**Comment by headdab** [comment]
We're annotating sports video from stationary cameras.  Sometimes the players and ball are rather small in the resulting video making scaling the video down less desirable.  At the end of the day, we have to balance accuracy of the annotations with the time it takes to download and tag the videos.  I realize I can scale down the video, or compress the frames more, but need to understand the loading and caching strategy to determine the appropriate trade-offs.  How is the frame cache size determined?  Currently, I'm annotating 30s clips.  I'm guessing the segmentation options when creating jobs is so you can break big jobs into smaller ones, to handle related issues.

The model I'm currently using, in interpolation mode, is to step through the video using at a coarse level (c/v keys) labeling the boxes for a given player.  I think that's the best way to get good per player tracks.  Then I use the scroll bar and single step to quickly slide back and forth through the video, stopping when necessary to add more keyframes to the track.

We're still trying to find the most effective way to annotate these videos, but that's what we're doing so far.  I recall in the research that its easier to annotate one object at a time.  I use the filtering functionality to only show the boxes for the current object.  If you have other suggestions or ideas, please share.
