### ISSUE TITLE
how to get the Label map (*.json) file from open-model-zoo?

### ISSUE THREAD

**Issue by LightningApple** [opencv/cvat#800]
In order to use the function of auto annotaion, I had to supply a label map(*.json) file. I want to use the model from open-model-zoo, but I only download *.xml and *.bin, how I can get the label map file?

**Comment by azhavoro** [comment]
Hi @LightningApple, you should create it yourself(it's simple json). Usually you can find this info in the model description.

Please use gitter for future questions.

**Comment by nmanovic** [comment]
@LightningApple, Also please read the documentation: https://github.com/opencv/cvat/blob/develop/cvat/apps/auto_annotation/README.md. I will close the issue for now.
