### ISSUE TITLE
What is the error?

### ISSUE THREAD

**Issue by yokoi-engineering** [opencv/cvat#803]
An error will occur if a large number of images are inserted. Is this a timeout?

![image](https://user-images.githubusercontent.com/18681817/67755217-17e02e00-fa7b-11e9-84fa-2f32490af03a.png)

**Comment by bsekachev** [comment]
@yokoi-engineering 

You do not have a connection with the CVAT server.

**Comment by bsekachev** [comment]
@yokoi-engineering 

Have you coped with this issue? Can I close it?
