### ISSUE TITLE
win10 run the command "docker-compose build" wrong

### ISSUE THREAD

**Issue by CarryLing** [opencv/cvat#806]
ERROR: Service 'cvat' failed to build: {'stream': 'Get:70 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libxml2 amd64 2.9.3+dfsg1-1ubuntu0.6 [697 kB]\n'}

**Comment by nmanovic** [comment]
@CarryLing , it looks like a problem with your network. Do you have proxy?

**Comment by nmanovic** [comment]
@CarryLing , I will close the issue. Don't hesitate to reopen it if you have any additional information.
