### ISSUE TITLE
[Question] Distribute docker container with a built in task

### ISSUE THREAD

**Issue by egrinstein** [opencv/cvat#815]
Good morning,

We would like to distribute annotation tasks for users within our company in the following manner:

1. The annotator downloads the Cvat image
2. A mechanism (either copying files through docker-compose, or an Http call using the api)
creates a task with a zipped dataset. 
3. The annotator performs the task
4. We retrieve the annotations from the container using the Http api

My questions are:
1. Would this be possible?
2. Could I do this by creating task files and copying the images to the image, or do I have to do this using the ReST API?

Thank you,

Eric

**Comment by nmanovic** [comment]
@egrinstein , the usual way to annotate data using a team:
- install CVAT on a server inside your company
- create all necessary tasks. If you have only one dataset you can split it on jobs using `segment size` parameter
- Ask your users to annotate a specific task/job (send them a link).

**Comment by nmanovic** [comment]
@egrinstein , please ask questions on our gitter channel: https://gitter.im/opencv-cvat. I will close the issue for now.
