### ISSUE TITLE
A JSON Response instead of Token, when creating users with REST API

### ISSUE THREAD

**Issue by dev225reddys** [opencv/cvat#816]
When used REST API to register Users, The response is Token. Instead if a JSON Response of Registered User with Unique ID (Assigned at the time of registration), It will be helpful to assign tasks to Users with ID at the time task creation.

**Comment by nmanovic** [comment]
@dev225reddys ,

I have spent some time to investigate. CVAT uses different frameworks and Django apps to implement different features. Authorization is handled by django_rest_auth app and it implements RegisterView using the way (https://github.com/Tivix/django-rest-auth/blob/95fafe5e0f6716296a1c664c2b870876a6b4e0cc/rest_auth/registration/views.py#L60). Probably it is good in most of cases. Thus I'm not going to change that in CVAT as well.

But to solve the motioned problem you can call /api/v1/users/self REST API method with the token to get full information about the user. I hope it will work for you.

I will close the issue. Please don't hesitate to reopen it if you think that the provided advice doesn't work for you.
