### ISSUE TITLE
Get Image Frames same as CVat annotated

### ISSUE THREAD

**Issue by hasanahmedfaisal** [opencv/cvat#818]
Hi @nmanovic , 

i have just started using Cvat , it is really amazing tool.Thanks for making it

I was able to upload a video and annotate it and download Cvat XML for videos format in dump annotation, itwas great

But my one doubt is now , How to get the image frames as a cvat frames with same fps , Is there a way to get image frames directly from cvat , same as "MASK ZIP 1.0" option in dump annotation , but instead of mask of image frame, it would be original rgb image frames of video 

Or is there a way to find fps and use  ffmpeg to extract frames , please please help me with this

Thank you

**Comment by nmanovic** [comment]
@hasanahmedfaisal , 

@zhiltsov-max is working on the feature: https://github.com/opencv/cvat/pull/813

For now you can use FFMPEG by yourself. You command can look like `ffmpeg -i path/to/your/video -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 images/%d.jpg`.  FFMPEG version is 3.4.1 (sometime it can be important).

**Comment by hasanahmedfaisal** [comment]
Hi @nmanovic ,

Thank you for the help , it works

Few thing i am assuming , please correct me if i am wrong

FPS is  not fixed , and i think i need not worry about that , as above command would take frames same way as cvat and names the files with same frame no in xml

Can i ask on what does Fps dependent on? 

Thank you

**Comment by nmanovic** [comment]
@hasanahmedfaisal , you don't need to care about FPS. Use command above for now. If FFMPEG version is the same and the command is the same you have to get the right sequence of frames as in CVAT.

Internally we annotated a lot of videos. Thus you can be sure that the advice works. In the future we are going to improve UX only (provide you a way to download images together with annotations).

**Comment by hasanahmedfaisal** [comment]
Hi @nmanovic , OK

Thank you for the amazing tool and all the help

**Comment by M-Younus** [comment]
> @hasanahmedfaisal ,
> 
> @zhiltsov-max is working on the feature: #813
> 
> For now you can use FFMPEG by yourself. You command can look like `ffmpeg -i path/to/your/video -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 images/%d.jpg`. FFMPEG version is 3.4.1 (sometime it can be important).

It works,Thank you man.
And for getting file names same as cvat annotations there is need of little changes in command.
ffmpeg -i path/to/your/video -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 images2/**_frame_%06d.jpg_**

**Comment by hasanahmedfaisal** [comment]
Hi @M-Younus  ,  @nmanovic  ,  thanks 

is there any way instead of images2/frame_%06d.jpg 

i can set targetdir = 'Imagedata' , this would be dynamically assigned in each loop

and so that i can write 

ffmpeg -i path/to/your/video -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 
 targetdir/frame_%06d.jpg

Presently i need to set directory manually , how can i do it

please help me

**Comment by nmanovic** [comment]
@hasanahmedfaisal , please use gitter channel for such questions. Actually I'm not sure that I can understand your question right.

**Comment by hasanahmedfaisal** [comment]
Thank you , sorry i asked here,  i will ask in gitter

**Comment by ladykarel** [comment]
hi how can I hide the boxes on the next frame , please help .

**Comment by zhiltsov-max** [comment]
@ladykarel, hi, check if "Outside" property helps: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/user_guide.md#track-mode-basics

**Comment by ladykarel** [comment]
is there any option for it not to show on next frames aside from outside
property?

**Comment by zhiltsov-max** [comment]
@ladykarel, you can also try to use "Occluded" property, but this will only mean partial covering. What is wrong with outside?

**Comment by ladykarel** [comment]
my client needs every annotation different from each other so for an
example rectangle #24 should no longer appear in the next frame

**Comment by AnkushMalaker** [comment]
> @hasanahmedfaisal ,
> 
> @zhiltsov-max is working on the feature: #813
> 
> For now you can use FFMPEG by yourself. You command can look like `ffmpeg -i path/to/your/video -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 images/%d.jpg`. FFMPEG version is 3.4.1 (sometime it can be important).

Is the FFMPEG version to be used in latest version of CVAT still the same? 
There's a mismatch in the biggest frame number in the annotations file gotten through CVAT, and the number of frames I get using the command mentioned above. The number of frames through the command is the same I get if I use OpenCV to extract and save frames one by one.
