### ISSUE TITLE
how to change attribute in interpolation mode??

### ISSUE THREAD

**Issue by bobmukza** [opencv/cvat#820]
if I change last frame that I worked, every frame that I previously worked on changes.
then how should I change specific frame attribute that I want??

**Comment by nmanovic** [comment]
@bobmukza , please use our gitter channel next time for such questions. You should mark N-1 frame as key frame without any changes and after that change attributes on the frame N. Thus on the internal (M, N-1) you will have the same values for attributes (where M is the previous key frame). 

I will close the issue. Don't hesitate to continue the discussion on gitter.
