### ISSUE TITLE
Interpolation of polygons

### ISSUE THREAD

**Issue by fywu85** [opencv/cvat#824]
I understand that by enabling dragging, I can move a polygon around by shifting it in X and Y directions. Similarly, is there a feature in CVAT that would also allow me to rotate the polygon?

**Comment by nmanovic** [comment]
@fywu85 , it is not possible. What is the reason for the request? Could you please describe your use case?

**Comment by fywu85** [comment]
Say if I want to label an object in a video that rotates only in the image plane from frame to frame, e.g., a vehicle making a left turn, being able to rotate the object's polygon would be huge time saver. For example, one of my use cases is as follows:
![image](https://user-images.githubusercontent.com/8881002/68434758-a08f5600-016e-11ea-9488-8e0123879bab.png)
Without rotation, I will need to readjust every point in the polygon in the previous frame to make it refit to the left turning vehicles in the current frame. With rotation, this operation will be almost instant.

**Comment by nmanovic** [comment]
@fywu85 , internally we have a prototype for interpolation of polygons between frames (as for bounding boxes). In the case it will work perfect. But it will take time to release it. Let me rename the issue. I'm not sure that the feature will be available in next release.

**Comment by fywu85** [comment]
Thank you for the info. That sounds great! In your knowledge, what would be the current best approach to label this? If I do not care about the precision of the boundary of the object, can I rotate or interpolate a bounding box to get a reasonable location label of a turning vehicle? Or, can I potentially use the semi-automatic segmentation feature here?

**Comment by nmanovic** [comment]
@fywu85 , to do that efficiently need to wait interpolation of polygons. You can find technical resources on your side and we will give you ideas and a sample of code how it can be implemented inside CVAT.

**Comment by fywu85** [comment]
@nmanovic Thank you! That will be really helpful. Would you mind sharing with us your ideas on how to approach implementing this interpolation + rotation feature? If we succeed, we will be happy to contribute a PR (:

**Comment by bsekachev** [comment]
@fywu85 

Hi, as Nikita said, we have a prototype for interpolation of a poly shapes (not only polygons, by the way). 
It can be found in ``cvat-core`` module which is expected to be a part of the tool in the nearest future (current production version CVAT mostly doesn't work with this module).

- Our JavaScript client-side implementation can be found [here](https://github.com/opencv/cvat/blob/690ecf9c6672c20310d04a55538c5bd67227237f/cvat-core/src/annotations-objects.js#L1125)
It is based on ``stable marriage problem`` algorithm which is used to finding a matching of points between two shapes. 
- It doesn't work perfectly yet, but we suppose after some testing and adjustment it would be much better. 
- One more comment is that algorithm isn't implemented on the server part at all, so it is also need to write the same code in Python. But it isn't expected to be the most difficult thing here.

Glad to see your comments and ideas about how it can be improved.

**Comment by enavarro222** [comment]
I'm also very interested in this feature.

Thanks for your work on this soft !

**Comment by ekingedik** [comment]
Hello! We are also really interested in this feature. Is there a rough estimation when this functionality will be available? 

Best,
Ekin

**Comment by bsekachev** [comment]
We will try hard to implement it in this month. 
But there aren't guarantees
