### ISSUE TITLE
CLI set dataset repository when creating new task

### ISSUE THREAD

**Issue by rotorliu** [opencv/cvat#825]
I want to set "Dataset Repository" when creating new task.
How to set cli params?

**Comment by nmanovic** [comment]
@rotorliu , please use our gitter channel (gitter.im/opencv-cvat/public) for such questions in the future. I don't think that I understand your question. Could you please elaborate a little bit?

**Comment by bsekachev** [comment]
@rotorliu 

Command line tool doesn't support such a parameter for creating a task (if I understood you right).

**Comment by rotorliu** [comment]
@bsekachev Thank you!
You are right!
