### ISSUE TITLE
Exception in plugin Git Plugin

### ISSUE THREAD

**Issue by rotorliu** [opencv/cvat#826]
I set the dataset repository of new task like this: http://172.23.129.161/user/annos-repo.git
I got this exception as follow:

Exception in plugin Git Plugin: Error: Repository status check failed. Exception: Got URL doesn't sutisfy for regular expression

How to fix?

Thank you!

**Comment by rotorliu** [comment]
ip addr is not work!

**Comment by nmanovic** [comment]
@rotorliu , probably it is a bug. I believe we have to support IP address as well.

**Comment by rotorliu** [comment]
Greate!
