### ISSUE TITLE
Unable to log in normally through other computers

### ISSUE THREAD

**Issue by BerryRB** [opencv/cvat#828]
Hi, I tried to access cvat on another computer. When I entered my account number and password, an interface appeared, which showed LOADING, and then stopped at this interface without response. So far, I have been waiting for 30 minutes. I want to know where the problem occurred.

**Comment by bsekachev** [comment]
@BerryRB 

Do you have any errors in chrome console this time? 
Press F12 (or via menu) and go to the tab ``console``. 
What URL are you trying to open?

**Comment by BerryRB** [comment]
@bsekachev  Thank you for your reply. I have solved this problem because the chrome version of my windows system is too old. I can log in normally after updating chrome.
