### ISSUE TITLE
About postgre database

### ISSUE THREAD

**Issue by synsis** [opencv/cvat#829]
I am using this project now, and I want to link to the database directly, to find the data I need but not shown in the web, so what should I do to access to it?

**Comment by bsekachev** [comment]
@synsis 

Here you can see how to connect to DB directly #640. 
I will close this issue. Don't hesitate reopen it if you aren't satisfied with the answer.

**Comment by alberthyd** [comment]
@synsis 

You can set port binding and exposing in "docker-compose.yml" file as following:

services:
　cvat_db:
　　ports:
　　　- "5432:5432"

and now, you can access to the database (localhost:5432) via pgadmin or others postgresql GUI tool.
