### ISSUE TITLE
Dump annotation Error 

### ISSUE THREAD

**Issue by xinyuabcd** [opencv/cvat#831]
When we want to save our annotations by pressing Dump Annotation button, it occurs one error as follows:
![image](https://user-images.githubusercontent.com/8544767/68525919-70cc8380-0311-11ea-9c74-128b08011f34.png)

**Comment by bsekachev** [comment]
@xinyuabcd 

First of all could you please attach logs from ``docker logs cvat`` as a text file here?

**Comment by nmanovic** [comment]
@xinyuabcd ,

we don't have enough information to investigate the issue. I will close the issue. Please don't hesitate to reopen it if you have more information and can attach logs.
