### ISSUE TITLE
Auto Segmentation mode missing

### ISSUE THREAD

**Issue by ArefAz** [opencv/cvat#832]
Hello,

I want to use semantic segmentation mode for annotation, but I don't have such option on the panel (Below Box, Points, Polyline, Polygon). Should I install something or do anything else on the server before having this option?

Thanks.

**Comment by benhoff** [comment]
I think you're talking about the semi automatic segmentation.

I would follow the instructions here: https://github.com/opencv/cvat/blob/1257a1b245a3c9ec1a21c084b2db9ffd56954106/cvat/apps/dextr_segmentation/README.md

**Comment by bsekachev** [comment]
@ArefAz 

Please, follow the installation manual carefully to get ability to use semantic segmentation. 
I will close this issue. Don't hesitate reopen it if you have problems with installation.
