### ISSUE TITLE
OpenVINO installation error

### ISSUE THREAD

**Issue by ArefAz** [opencv/cvat#833]
I installed OpenVINO using [the official guide](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html). Then I followed the instruction [here](https://github.com/opencv/cvat/blob/1257a1b245a3c9ec1a21c084b2db9ffd56954106/cvat/apps/dextr_segmentation/README.md) and [here](https://github.com/opencv/cvat/blob/develop/components/openvino/README.md) to install OpenVINO for using it on CVAT.

I encountered this error and could not resolve it. Do you have any suggestions?
[error.txt](https://github.com/opencv/cvat/files/3828408/error.txt)

Besides that, how can I add "Run TF Annotation" button to CVAT. Currently, my CVAT looks like this and misses some other features mentioned in the User's guide as well. ![image](https://user-images.githubusercontent.com/49265411/68544001-96ba5c80-03d3-11ea-84eb-12a2b6a3be3e.png)
PS:
Installing on Ubuntu 18.04
Thanks.

**Comment by bsekachev** [comment]
@ArefAz 
Hi, 

What exact commands have you use to build? 
Error above isn't related with OpenVino as well as with CVAT. Probably temporary problems with your network. You can try to perform them later or perform them outside of Docker (just for test).

**Comment by ArefAz** [comment]
@bsekachev 
I used this command to build:
`docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/openvino/docker-compose.openvino.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml build` 

I did try it outside of Docker, just used: `sudo apt-get install -y git-lfs` and `git lfs install` and everything went okay. I will try it later, but I do not think there is something wrong with the network because I checked it when I encountered the error.

Thanks.

**Comment by bsekachev** [comment]
@ArefAz 

As far as I see you have already built CVAT container before. So, this command has been already successful inside Docker. 
Anyway, let us know any results on your side later.

**Comment by benhoff** [comment]
I think you just need to restart the container to have the changes take effect.  I'm a bit of a docker noob, but maybe just a `docker-compose restart`?

Reference the docker commands here: https://docs.docker.com/v17.09/compose/reference/

Maybe @bsekachev can help you with the specific docker commands. Most of the additional buttons (like "Run TF Annotation) in CVAT are included by environmental variable, so I think you'll need to restart the container to have the variables show appropriately.  So for example, this inclusion in the docker-compose.dextr.yml file [here](https://github.com/opencv/cvat/blob/690ecf9c6672c20310d04a55538c5bd67227237f/cvat/apps/dextr_segmentation/docker-compose.dextr.yml#L14) makes the button show up. If you're missing something, you could try logging into the docker container and checking if the environmental variable is set correctly.

**Comment by ArefAz** [comment]
@benhoff @bsekachev 
The problem is the new components are not built because of the error I mentioned. I restarted the container, nothing's changed and I don't have any new buttons. because no new components are installed. Also, when I run docker container it says that everything is up-to-date.

Let me explain again: I want to add "Run TF Annotaion" and "Run Auto Annotation" to my CVAT, so I followed the instructions and when I used `docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/openvino/docker-compose.openvino.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml build` in the installation process I encounterd this error: 
![image](https://user-images.githubusercontent.com/49265411/68649014-f4b38500-0536-11ea-952e-c18a0671af3e.png)
Here is the log before the error: 
[log.txt](https://github.com/opencv/cvat/files/3834754/log.txt)

The internet connection is fine. I tried to build several times as well and every time the same error came up.

Thanks a lot.

**Comment by bsekachev** [comment]
@ArefAz, 

First of all if you want to add "Run TF Annotation" you need also add ```-f components/tf_annotation/docker-compose.tf_annotation.yml``` to your command. 

Finally I checked the command ```docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml -f components/tf_annotation/docker-compose.tf_annotation.yml build``` and it works as expected for me. 

I suppose there are some proxy issues on your side because I see that git-lfs package is trying to be installed more than 1.5 hours.

One of workarounds is just to remove git-lfs from Docker file 9(rows [125-128]), but in this case some functions related with git repository is expected to be broken.

**Comment by nmanovic** [comment]
@ArefAz ,

I will close the issue for now. Don't hesitate to reopen it if you have more information. Looks like a problem with your network. Internally we can build the develop branch without any problems (look at the build status on README.md).
