### ISSUE TITLE
Coco occlusion attribute error

### ISSUE THREAD

**Issue by BerryRB** [opencv/cvat#836]
@azhavoro Hi, when I I look at code /cvat/blob/develop/cvat/apps/annotation/coco.py, I see it on line 248 of the code:

      new_anno['iscrowd'] = 0

So why is this attribute all set to 0? I tried to annotate the annotation with occlusion attribute.I found that this attribute is not reflected in the coco format file.

**Comment by nmanovic** [comment]
I think `iscrowd != occluded` in common case. But I don't think that it is correct to assign zero here as well. Probably if a label has 'iscrowd' attribute it should be used for COCO format.

**Comment by azhavoro** [comment]
@BerryRB Hi. 
Quote from http://cocodataset.org/#format-data:
>  The segmentation format depends on whether the instance represents a single object (iscrowd=0 in which case polygons are used) or a collection of objects (iscrowd=1 in which case RLE is used). Note that a single object (iscrowd=0) may require multiple polygons, for example if occluded. Crowd annotations (iscrowd=1) are used to label large groups of objects (e.g. a crowd of people).

For now CVAT interprets all objects as a single object. If you want to annotate objects with multiple polygons you can annotate all parts of the object using separate polygons and group it together. In this case it should be dumped as 1 object with multiple polygons.

**Comment by BerryRB** [comment]
@azhavoro  Hi, I found that group_id in XML file is not reflected in coco format. If I want to convert a group of objects in XML file to RLE format in coco, can you give me some suggestions?
