### ISSUE TITLE
Uploaded annotations in wrong position and\or frame

### ISSUE THREAD

**Issue by adizhol** [opencv/cvat#837]
I uploaded annotations in CVAT XML 1.1 format, but the bboxes are located in the wrong place or even on the wrong image.
Since this XML file was created with an external script, I could have a mistake. 
How does CVAT group annotations and images before displaying?  Is it with the image id, or the image path?

Thanks

**Comment by anilgurses** [comment]
How do you solve that? I am encountering the same issue that you described. I have COCO annotation json which I generate it from my model predictions. I gathered predictions from the frames. However, the image orders are different.

**Comment by adizhol** [comment]
I don't remember exactly how I re-ordered my frames in the XML. That's why
I gave up on using CVAT for serious projects.

**Comment by anilgurses** [comment]
Thank you for your response. I have been trying to fix my image id order for a week. I haven't made any progress.

**Comment by anilgurses** [comment]
I solved it. The frame ids are sorted lexically. However, the image ids are sorted numerically.

**Comment by nmanovic** [comment]
@anilgurses , @adizhol , files path should be sorted lexicographical. After that you can enumerate them and it is the right order.

**Comment by nmanovic** [comment]
@anilgurses , @adizhol , files path should be sorted lexicographical. After that you can enumerate them and it is the right order.

**Comment by anilgurses** [comment]
Thanks for the clarification
