### ISSUE TITLE
How to create a new task by cli.py

### ISSUE THREAD

**Issue by 330833904** [opencv/cvat#841]
example：
python3 cli.py --auth **:** --server-host localhost --server-port 8080 create "test_cli_create_tas1k" --labels human local test_img/*

hi,i use this to create a new task,but i failed.
can you tell me strings of label how to write?

**Comment by nmanovic** [comment]
@330833904 ,

It is a question for our gitter channel. I believe Boris already answered to you. Labels should be in json format. I will close the issue.
