### ISSUE TITLE
Upload Annotation Data

### ISSUE THREAD

**Issue by clydebailey** [opencv/cvat#846]
Hello @nmanovic .

I have an existing postgres db that maintains annotation data of all images. I wish to upload this data dynamically to '**upload annotation**'. Where can i find the source code that parses the json/xml and uploads it to the cvat_ui.

Regards
Clyde

**Comment by nmanovic** [comment]
Hi @clydebailey ,

https://github.com/opencv/cvat/tree/develop/cvat/apps/annotation

Look at TFRecord/COCO/CVAT/... annotation formats. You can upload any file and parse it. 

Please ask questions on our gitter channel next time. I will close the issue.

**Comment by clydebailey** [comment]
Hello @nmanovic 
Thank you for the fast reply.

I am sorry if I phrased by question wrongly.
Suppose I have a coco.json file residing in my pc and I want to upload it to the cvat job without the need to use the "upload annotation" radio button. How can i achieve this?
I am finding it difficult to debug the source  code since it is installed with docker.
Any guidance would be appreciated.

Thanks

**Comment by clydebailey** [comment]
No worries, I figured it out. Thanks

**Comment by burnzzz** [comment]
> https://github.com/opencv/cvat/tree/develop/cvat/apps/annotation

This link is dead

**Comment by nmanovic** [comment]
@burnzzz , please look here https://github.com/openvinotoolkit/cvat/tree/develop/cvat/apps/dataset_manager
