### ISSUE TITLE
How to run annotation on a video (without interpolation) 

### ISSUE THREAD

**Issue by yterme** [opencv/cvat#847]
I am uploading my own tracking annotations. My annotations look like
track 1
- box: frame 1
- box: frame 2 
- box: frame 5

During the annotation, CVAT interpolates my file and the output file is now
track 1
- box: frame 1
- box: frame 2 
- box: frame 3
- box: frame 4
- box: frame 5

However, I want to avoid this behavior. Annotation mode could be a way to do it but it does not enable tracking between frames. Is there a way to annotate videos without interpolation ?

**Comment by nmanovic** [comment]
@yterme ,

Could you please explain your case? Why do you need that?

**Comment by yterme** [comment]
So I have a video of the street and I upload tracking boxes of objects in the street. I want to add information about these boxes on CVAT such as specifying the subcategory to the object. However objects sometimes get occluded and then reappear and I don't want to interpolate the boxes during occlusion. Also, tracking sometimes fails in which case interpolation is not desired as well.

**Comment by nmanovic** [comment]
@yterme , you can use boxes with "outside=True". In this case the box isn't interpolated further till you have a box inside the track with outside=False. Does it help?

**Comment by yterme** [comment]
Thank you for your answer. When I set "outside=True", I can still see interpolation. 

However, I noticed that boxes created by interpolation have "keyframe=0". So in my case, I can simply ignore all boxes with "keyframe=0" which solves the problem.

**Comment by nmanovic** [comment]
@yterme , great that you have found a solution. I will close the issue in the case.
