### ISSUE TITLE
upload block when i try debuging it

### ISSUE THREAD

**Issue by naah69** [opencv/cvat#848]
i install cvat as the way of [CONTRIBUTING.md](https://github.com/opencv/cvat/blob/develop/CONTRIBUTING.md)

system: both of macOS 10.14 and Windows10
python version：3.6.7
cvat version：0.5/0.4.1

but when i upload picture,it blocked.

![image](https://user-images.githubusercontent.com/25682169/69130879-47b7aa00-0aec-11ea-8566-194d2358fde5.png)
```
url: http://127.0.0.1:8000/api/v1/tasks
POST
request:
{"name":"ddd","labels":[{"name":"ddd","attributes":[]}],"image_quality":50}

response:
{"url":"http://127.0.0.1:8000/api/v1/tasks/5","id":5,"name":"ddd","size":0,"mode":"","owner":1,"assignee":null,"bug_tracker":"","created_date":"2019-11-19T11:51:46.566911+03:00","updated_date":"2019-11-19T11:51:46.566946+03:00","overlap":null,"segment_size":0,"z_order":false,"flipped":false,"status":"annotation","labels":[{"id":5,"name":"ddd","attributes":[]}],"segments":[],"image_quality":50}
```

![image](https://user-images.githubusercontent.com/25682169/69130902-51411200-0aec-11ea-9e21-cfbb65a64e13.png)
```
url:http://127.0.0.1:8000/api/v1/tasks/5/data
POST
request:
picture data

reponse:
{"client_files":["物理图.jpg"],"server_files":[],"remote_files":[]}
```
![image](https://user-images.githubusercontent.com/25682169/69130937-60c05b00-0aec-11ea-99d9-eb4337b54420.png)
```
url:
http://127.0.0.1:8000/api/v1/tasks/5/status

repsonse:
{"state":"Queued","message":""}
```

## when i refresh the page, it will be empty.

![image](https://user-images.githubusercontent.com/25682169/69131001-82b9dd80-0aec-11ea-9a94-16a4bc1d5075.png)

**Comment by nmanovic** [comment]
Hi @naah69 ,

Please use our gitter channel (https://gitter.im/opencv-cvat/dev) for such kind of questions. Most probably you forget to run other processes. Look at https://github.com/opencv/cvat/blob/develop/supervisord.conf. The ` /usr/bin/python3 %(ENV_HOME)s/manage.py rqworker -v 3 default` process is important to create a new task.

I will close the issue.
