### ISSUE TITLE
[Question] Source code for auto-annotation model: Semantic Segmentation

### ISSUE THREAD

**Issue by gachiemchiep** [opencv/cvat#850]
Hello cvat team. @bsekachev

There's an example of auto-annotation using tensorflow semantic segmentation at : [https://github.com/opencv/cvat/tree/develop/cvat/apps/auto_annotation](https://github.com/opencv/cvat/tree/develop/cvat/apps/auto_annotation) 

Do you know where I can find source code for that model?
I want to fine-tune for my own dataset and objects.

Thank you.

**Comment by nmanovic** [comment]
@gachiemchiep , please use gitter channel next time for such questions.

There are several ways to use automatic segmentation in CVAT. One way is https://github.com/opencv/cvat/tree/develop/components/auto_segmentation. Source code for the model can be found here: https://github.com/matterport/Mask_RCNN.git

You can preload any model in OpenVINO format: https://github.com/opencv/cvat/tree/develop/utils/open_model_zoo/mask_rcnn_inception_resnet_v2_atrous_coco
Look at https://github.com/opencv/open_model_zoo/blob/master/models/public/mask_rcnn_inception_resnet_v2_atrous_coco/model.yml

**Comment by nmanovic** [comment]
I will close the issue.

**Comment by gachiemchiep** [comment]
@nmanovic 
Sorry. I don't know about that rule.
