### ISSUE TITLE
disable pagination

### ISSUE THREAD

**Issue by wuyuanyi135** [opencv/cvat#853]
Hello,

The `tasks` api is paginated. I found the pagination is hard-coded in backend code. Do you think there should be a bypass mechanism (e.g. page=-1) that return the full list? Is there any API that I can determine how many pages exist?

**Comment by nmanovic** [comment]
https://www.django-rest-framework.org/api-guide/pagination/
```
page_size_query_param - If set, this is a string value indicating the name of a query parameter that allows the client to set the page size on a per-request basis. Defaults to None, indicating that the client may not control the requested page size.
```

**Comment by nmanovic** [comment]
@wuyuanyi135 , I agree that it can be useful. It seems it is easy to implement.

**Comment by FighttoSurvivor** [comment]
Brother I was trying to get used to the new system basically I messed up? ignorance, but could not create tools above, which only allow current updates

**Comment by bsekachev** [comment]
Probably should be closed. 
There is a separated issue for UI client: #898
