### ISSUE TITLE
psycopg2.OperationalError when executing manage.py during installation

### ISSUE THREAD

**Issue by MatejVitek** [opencv/cvat#857]
I'm trying to install on Ubuntu 18.04, following the instructions. I've successfully built the containers, but when I execute the line
`docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'`
I get the following error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
>     self.connect()
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 195, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/django/manage.py", line 21, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in execute
>     return super().execute(*args, **options)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 363, in execute
>     self.check_migrations()
>   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 453, in check_migrations
>     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
>   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 18, in __init__
>     self.loader = MigrationLoader(self.connection)
>   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 49, in __init__
>     self.build_graph()
>   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 212, in build_graph
>     self.applied_migrations = recorder.applied_migrations()
>   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
>     if self.has_table():
>   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/recorder.py", line 56, in has_table
>     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 256, in cursor
>     return self._cursor()
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 233, in _cursor
>     self.ensure_connection()
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
>     self.connect()
>   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
>     self.connect()
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 195, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> django.db.utils.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution

I've tried removing all docker containers and images and rebuilding but still get the same error.

I'm attaching the outputs of `docker-compose build` and `docker-compose up -d`.

[docker-compose-build.log](https://github.com/opencv/cvat/files/3879394/docker-compose-build.log)
[docker-compose-up.log](https://github.com/opencv/cvat/files/3879395/docker-compose-up.log)

**Comment by bsekachev** [comment]
@MatejVitek 

Can this bug be reproduced every time?

**Comment by MatejVitek** [comment]
Yes, I've tried restarting and also removing all the containers/images and rebuilding, but the error still persists.

My colleague working on another computer, however, successfully set up the application.

**Comment by nmanovic** [comment]
@MatejVitek , can it be a problem with your proxy? Did you modify code? Did you build CVAT successfully previously?
It seems it is a problem with your local machine. I have no idea how to help in the situation. Nobody previously reported about such issues. 

I will close the issue for now. If you have any new insights for us to investigate don't hesitate to reopen the issue.

**Comment by MatejVitek** [comment]
I just thought I'd come by and mention, in the unlikely event that this happens to someone else, that after purging everything docker-related from my computer (including all configuration files, containers, images, and the repository added in the CVAT installation instructions) and running
`sudo apt install docker.io` (just using Ubuntu's default repository), I've now successfully followed the subsequent instructions to install docker-compose and build and run CVAT.
