### ISSUE TITLE
Make "Job Statisitcs" table in the menu scrollable

### ISSUE THREAD

**Issue by newpavlov** [opencv/cvat#86]
If there is a big number of label types menu buttons are moved outside of the screen. I think it's worth to make statistics table scrollable with `max-height` and `overflow: scroll;` rules. In addition to CSS changes, some changes in JS will be needed as well.

**Comment by nmanovic** [comment]
Hi @newpavlov ,

Thanks for your feedback. I believe it is a good idea. Could you please send us a PR for the functionality?

**Comment by nmanovic** [comment]
It was already fixed in the past.
