### ISSUE TITLE
auto annotation using OpenVino no a Mac

### ISSUE THREAD

**Issue by cbasavaraj** [opencv/cvat#873]
Hi, is it possible to use OpenVino auto annotation on a MacBook Pro? This link https://github.com/opencv/cvat/tree/develop/components/openvino mentions only Ubuntu, but OpenVino is supported on Mac: [OpenVino on Mac](https://docs.openvinotoolkit.org/2019_R3.1/_docs_install_guides_installing_openvino_macos.html#set-the-environment-variables). I managed to install OpenVino and test it as described on the Intel site, but on the other hand when I run 
`docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build`, I get 

> ERROR:` Service 'cvat' failed to build: The command '/bin/sh -c if [ "$OPENVINO_TOOLKIT" = "yes" ]; then         /tmp/components/openvino/install.sh &&         mkdir ${REID_MODEL_DIR} &&         wget https://download.01.org/openvinotoolkit/2018_R5/open_model_zoo/person-reidentification-retail-0079/FP32/person-reidentification-retail-0079.xml -O reid/reid.xml &&         wget https://download.01.org/openvinotoolkit/2018_R5/open_model_zoo/person-reidentification-retail-0079/FP32/person-reidentification-retail-0079.bin -O reid/reid.bin;     fi' returned a non-zero code: 64
`

**Comment by nmanovic** [comment]
@cbasavaraj ,

You don't need to run OpenVINO on Mac natively. It should be run inside Docker. Just follow instructions and download **OpenVINO for Ubuntu**, put it into the corresponding directory and build CVAT with appropriate options.

Please ask such questions in our gitter channel. I will close the issue for now.
