### ISSUE TITLE
Playback buffering and slow

### ISSUE THREAD

**Issue by stobias123** [opencv/cvat#874]
Any way to improve performance of playback? I can hardly playback more than 5 seconds without buffering.

OSX i7 16GB Memory - running off docker compose.

**Comment by nmanovic** [comment]
@stobias123 , 

It will be addressed in the patch: https://github.com/opencv/cvat/pull/787. For now it is under review.

**Comment by bsekachev** [comment]
@stobias123 
Currently you can also reduce image quality during task creating 
In most annotation cases this quality isn't very significant

**Comment by nmanovic** [comment]
Please try develop branch. Data streaming feature was integrated.

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/40690625/77940262-1c767000-72c1-11ea-872a-3d740b6c1b14.png">

**Comment by Icxa** [comment]
Hi, I have been using the develop branch but still I feel that there is a lot of laoding/buffering time when I access the server via a proxy.

**Comment by noamzilo** [comment]
I am running the last version and this clearly doesn't work. After exactly 36 frames, be it video or singular frame, be it in the official cloud or if self hosting (HEAD detached at v2.37.0) the UI does buffering for the next X frames.
What should happen, is for prefetching to occur in the background, so that the user can go on with their lives without having to stop and wait every 1 second.

**Comment by nmanovic** [comment]
@noamzilo , there are multiple reasons for the behaviors. Try to create the task on CVAT Online (app.cvat.ai) and if you see the same problem, just contact our support team. We will look into the issues.

**Comment by noamzilo** [comment]
> [@noamzilo](https://github.com/noamzilo) , there are multiple reasons for the behaviors. Try to create the task on CVAT Online (app.cvat.ai) and if you see the same problem, just contact our support team. We will look into the issues.

https://github.com/user-attachments/assets/e2402b0e-a844-482c-a4c5-8848388cc05e


I just opened an issue about this
https://github.com/cvat-ai/cvat/issues/9519

How do I contact support? This is quite urgent for me.

This happens both on cloud and locally, with any image downsize, with multiple video encodings, from my computer (now in Colombia and from my partner's, now in Portugal). This eliminates most reasons I can think of.
