### ISSUE TITLE
Dump unlabelled images as empty annotations in XML file

### ISSUE THREAD

**Issue by tom-garford** [opencv/cvat#888]
Hi All, 

I am a beginner to cvat, so I apologise if this is a simple question. 

I am just wondering if it is possible to generate "empty" labelling files for unlabelled images when annotations are dumped to a .xml file. 

The main reason for this would be to store a record relating image file name to the image_id value. 

I am looking to convert annotations generated from my pretrained network back into an xml file to edit in cvat. However, in order to do this, I would need to store the annotations with the correct image_id to be matched with the correct image in cvat. 

An equally useful answer would be to know how cvat assigns image_id values when images are imported into a new cvat job. It appears they are ordered in some numerical order, but it would be good to hear "from the horse's mouth"!

I notice that pascal voc annotations are generated for each individual image. If someone knows if keypoints (I am only interested in keypoints and polylines) can be stores in pascal voc format, that may be another way to sidestep the image_id issue. 

Kind regards,

Tom.

**Comment by nmanovic** [comment]
@tom-garford ,

>> An equally useful answer would be to know how cvat assigns image_id values when images are imported into a new cvat job. It appears they are ordered in some numerical order, but it would be good to hear "from the horse's mouth"!

You just need to sort your images in lexicographical order (by name). First image has id equals to 0, second image has id == 1, ...

I will close the issue for now. Please use our gitter channel to ask next questions.
