### ISSUE TITLE
'Annotation has failed' for YOLOv3 object detection in CVAT.

### ISSUE THREAD

**Issue by PareshKamble** [opencv/cvat#896]
Hi!

I want to use YOLOv3 for automatic annotation using CVAT tool. I understand that I need .bin, .xml, mapping.json and interp.py files. 

I followed the steps given [here](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html#yolov3-overview) for generation of .pb file and IR files subsequently. For the above said task, I used official [yolov3](https://pjreddie.com/media/files/yolov3.weights) weights and custom attributes from the corresponding [cfg](https://github.com/pjreddie/darknet/tree/master/cfg) file. 
I successfully generated the IR files.

Later, I used the mapping.json and interp.py files provided [here](https://github.com/opencv/cvat/tree/develop/utils/open_model_zoo/yolov3). Now, I had the 4 required files for auto annotation at CVAT.

Finally, I provided these 4 files as YOLOv3 through the **model manager** option in CVAT GUI for object detection. When I press the **_Run Auto Annotation_** button, the process completes with **_Annotation has Failed_** message.

Is there something I am missing? 
Is there any method to know what might have gone wrong?
During the process of IR files generation, I kept the yolov3.json file as it is since the custom_attributes were the same in the provided file and that in yolov3.cfg [here](https://github.com/pjreddie/darknet/tree/master/cfg)

Any help would be highly appreciated!

**Comment by nmanovic** [comment]
@benhoff ,

Do you think you can answer on the question?

**Comment by benhoff** [comment]
@PareshKamble , can you attach the logs? `$ docker cvat log` is the command I believe.

Is there a traceback that is provided when you submit the 4 files? If not, what version of cvat are you using?

**Comment by PareshKamble** [comment]
Thanks @benhoff for the reply. The command is correct but the log is too big to be attached. Do you want a particular portion of the log to be attached or the complete log? 

No traceback is provided when I submit the 4 files. Interestingly, everything works smooth unless I run the auto annotation. How to know the version of cvat? However, I cloned cvat on 23 November 2019. Hope it does help? 

I get the below shown message after running the auto annotation. First the message as shown in the left image then the right image.
![cvat1](https://user-images.githubusercontent.com/26019729/70218570-349e0e80-1769-11ea-8466-5fae37ce0edf.png) ![cvat](https://user-images.githubusercontent.com/26019729/70218581-38319580-1769-11ea-931d-cf9c272d2a36.png)

**Comment by benhoff** [comment]
Version of CVAT sounds fine. What version of OpenVino?

If you're a Python developer, can you run this script and post the traceback? 

https://github.com/opencv/cvat/tree/develop/utils/auto_annotation

I don't need the entire log, there should just be a section that talks about the errors. Should talk about exceptions. Likely in the last quarter. 
You can email it to me, beohoff@gmail.com
Or, I can try to induce an error in CVAT and I'll post an example so you know what I mean.

**Comment by PareshKamble** [comment]
I am using **l_openvino_toolkit_p_2019.3.376** version of openvino. 
I shall mail you the log right away. 
Thanks!

**Comment by himalayanZephyr** [comment]
Hi Ben
I'm getting the same error when I followed the same process. I've emailed the logs to beohoff@gmail.com

**Comment by benhoff** [comment]
@himalayanZephyr / @PareshKamble, Thanks for submitting the logs! It looks like it's an issue with the serializer. Specifically, the serializers ensures that no points are less than or equal to zero. Which means that some of the point values being submitted are less than zero, and I need to add some additional validation into the `interp.py` script.

I need some additional time to diagnose the issue. If you don't want to wait for me to do that though, I believe that I need to put some additional validation in the lines to check the xmin/ymin and xmax/ymax values here, to ensure that the selected mins are actually mins: 
https://github.com/opencv/cvat/blob/c0f1854f799c5e28022c1a686e6718db392430ba/utils/open_model_zoo/yolov3/interp.py#L12

Additionally, you could put a print or enforcing statement in [this line](https://github.com/opencv/cvat/blob/c0f1854f799c5e28022c1a686e6718db392430ba/utils/open_model_zoo/yolov3/interp.py#L154) to ensure that nothing less than zero sneaks in.

I'm a little slammed with some other stuff, but I'll try to get this diagnosed and patched.

**Comment by PareshKamble** [comment]
Hi Ben,

Thank you for your reply. I would try to do what you suggested. However, it would be great if you manage time to rectify the issue.

**Comment by himalayanZephyr** [comment]
Hi Ben
Thanks for your reply.

It seems to work now with some enforcing lines as you suggested.

Also, I noticed the sample mapping file starts with 1, whereas it should start at 0. I noticed that because I mapped my label to 'person', however, it was detecting bicycles.

I just submitted a pull request for this as well.

**Comment by PareshKamble** [comment]
Hi @himalayanZephyr 

Can you please share the rectified interp.py file on kamble.paresh@gmail.com?

**Comment by benhoff** [comment]
@himalayanZephyr , do you want to submit a pull request into CVAT itself? `nmanovic` doesn't bite and loves new contributors.

You would need to squash into one commit and add a note in the [changelog found here](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md).

I usually use git reset to do it. So in your case, `$ git reset --soft HEAD~2` would stage the two commits you've made to be committed at once. You could then edit the changelog, add it, and then do the commit message.

**Comment by himalayanZephyr** [comment]
@benhoff just submitted a pull request. Thanks for the tips above.

@PareshKamble You can refer to [this](https://github.com/opencv/cvat/pull/912/commits/f75d96c36c3f0a899642f90251f0a79b1d9e19f1)

**Comment by benhoff** [comment]
@himalayanZephyr , congrats on your first pull request to CVAT! Thanks for making the code base better!
