### ISSUE TITLE
Ability to sort tasks by a criteria (creation data, name, updation date, etc.)

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#899]
It needs to be supported by a REST server first
After UI controls have to be added

**Comment by katab** [comment]
Hello, I have a couple of questions: 
1) Is this issue being worked on? Any estimate on when the functionality could be in place? 
2) We would highly benefit from a possibility to sort the tasks based on priority, would that be solved with this issue?

**Comment by bsekachev** [comment]
Hi, @katab 

Right now we aren't working for the feature. 
Sorting tasks by priority is possible, but first we need to introduce task priority. We haven't considered such a feature, but I suppose it is implementable.

**Comment by katab** [comment]
Thanks for your reply @bsekachev! Is there a way to vote for this issue or affect the priority in any way?

**Comment by nmanovic** [comment]
@katab , the best way to vote is to send us a PR with the required functionality. Also you can add +1 to the issue.

**Comment by katab** [comment]
Sorry for my ignorance, do I +1 this issue by giving the first comment a "thumbs up" or is there another way? (New to using github in this way)

**Comment by nmanovic** [comment]
The following filters below are supported. Need add 'created date', 'updated date'.

![image](https://user-images.githubusercontent.com/40690625/143779166-037a28e5-2997-438a-a3e1-8e3f5aa556ea.png)

**Comment by bsekachev** [comment]
Now tasks/projects/jobs have advanced filtration, I believe we can close the issue.
