### ISSUE TITLE
Allowing attributes without objects

### ISSUE THREAD

**Issue by 4sfaloth** [opencv/cvat#90]
First of all, I'd like to thank all the contributors for this amazing tool. I'd like to suggest a modification (new feature if you'd like), which is to allow attributes without any associated object. This is useful when you want to label properties of the image itself, and not any object it contains (eg: landscape type, is_sharp, etc...). As of now I just create a dummy object and set the attributes on it, but it would make more sense (and be faster) to just set the attributes directly on the image without having to create the object

**Comment by nmanovic** [comment]
Hi @4sfaloth ,

Thanks for you feedback. I agree that the feature will be verify useful. Even there is a workaround it is much better to support such mode natively.

**Comment by 4sfaloth** [comment]
@nmanovic 

Thank you for your fast reply. I'm glad you found the suggestion helpful. Looking forward for it on 0.3.0 :)

**Comment by nmanovic** [comment]
It will be fixed on server side only with REST API in the current release. UI will be implemented only in the next release.

**Comment by nmanovic** [comment]
Make sense to do the task in new UI. Moved to v1.0.0

**Comment by nmanovic** [comment]
Particular fixed. Now it is possible to annotate tags in new UI. The workflow isn't optimised yet.
