### ISSUE TITLE
All Keyframes=1 after export and then import

### ISSUE THREAD

**Issue by Ballinho** [opencv/cvat#900]
Hi,
I create a task with 1 job and load a video from a shared server.
Then I create an annotation (track) over 10 frames in interpolation mode.
At frame 11 I stop the track by clicking on the eye.

Then I export it as "CVAT XML 1.1 for videos" and check the xml. Everything looks fine.
Frame 1 and 10 have the keyframe=1. 2-9 are set to keyframe=0.
The additional frame 11 with outside=1 is also set to keyframe=1.

But when I import this dump again and export it, every box has keyframe=1.
I can see it also in the tool that the interpolation is not working anymore, when I move the box of frame 5 to somewhere else. Then it is not interpolating anymore.

**Comment by nmanovic** [comment]
@Ballinho , could you please specify the version of CVAT tool? Is it the latest develop branch? I have checked and it works as expected. We had the bug (https://github.com/opencv/cvat/issues/720) but it was fixed.

**Comment by Ballinho** [comment]
Hi,
we are using version 0.5.0 from master, which was almost the development at that time.
But #720 sounds exactly like our problem. Why didn't I find the issue myself? ;-)
So we will update.
Thanks a lot.
