### ISSUE TITLE
Question/Bug: Duplicate tracks / Tracks not ending

### ISSUE THREAD

**Issue by Ballinho** [opencv/cvat#901]
Hi,
we do an automatic recognition of objects and a tracking.
Out of this we create 1 XML (with 1 job/segment) that can be imported into CVAT.
Sometimes the XML is imported into a task with several jobs to split it.
(In CVAT we do the review of the automatism and do some rework.)

Sometimes it happens that complete tracks are doubled. Only the track-id is another one.
This happens not only when a track runs over 2 or more jobs.

And sometimes it seems that the attribute "outside=1" of the last box of a track get lost and the track runs over all frames (interpolation mode).

Currently I'm not able to reproduce this issue.
So does anyone know of such issues?

**Comment by nmanovic** [comment]
@Ballinho , we really have an algorithm to merge tracks in adjacent segments.  

>> So does anyone know of such issues?

I believe it is better to ask the question on gitter. We don't know about such problems. We use interpolation constantly. Please try to update CVAT version.

I will close the issue. Don't hesitate to reopen it if you have steps to reproduce.
