### ISSUE TITLE
Remote access issue

### ISSUE THREAD

**Issue by lastlaugher** [opencv/cvat#907]
Hi CVAT team,

I installed CVAT and set " ALLOWED_HOSTS: '*' " to access from remote client. The login window succeeds to show but the next step fails.

Chrome debug console says like followings:
GET http://localhost:8080/api/v1/users/self xhr.js:160 
net::ERR_CONNECTION_REFUSED
GET http://localhost:8080/api/v1/auth/login xhr.js:160 
net::ERR_CONNECTION_REFUSED

It shouldn't connect to the localhost but remote location. 

Could you help me to resolve this issue?

**Comment by lastlaugher** [comment]
I resolved myself. I updated UI_HOST and REACT_APP_API_HOST and then build again. Then it works. Sorry for bothering you guys.

**Comment by chengzhao000** [comment]
> I resolved myself. I updated UI_HOST and REACT_APP_API_HOST and then build again. Then it works. Sorry for bothering you guys.

can you tell me how to update UI_HOST and REACT_APP_API_HOST? thanks.

**Comment by lastlaugher** [comment]
> > I resolved myself. I updated UI_HOST and REACT_APP_API_HOST and then build again. Then it works. Sorry for bothering you guys.
> 
> can you tell me how to update UI_HOST and REACT_APP_API_HOST? thanks.

I updated docker-compose.yml, which I set the variables with the hostname of the machine which cvat is installed. If the hostname is not added in DNS, you should set IP address.
