### ISSUE TITLE
Add a copy to clipboard button for the list of jobs

### ISSUE THREAD

**Issue by achernovx** [opencv/cvat#909]
Sometimes it's necessary to copy all URL -addresses. It'll be good to have a corresponding button somewhere near the list of jobs.
![copy_jobs_urls](https://user-images.githubusercontent.com/43407217/70326835-91232b80-1846-11ea-91a4-ed5a19c9eab2.JPG)

**Comment by nmanovic** [comment]
@achernovx , thanks! Great report 👍
