### ISSUE TITLE
Cannot accept OpenVINO license in docker installation

### ISSUE THREAD

**Issue by manybodycpa** [opencv/cvat#910]
I'm following the instructions (https://github.com/opencv/cvat/tree/master/components/openvino) for
installing OpenVINO. When running 

> docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build

I end up in an infinite loop with the error 

> "Type "accept" to continue or "decline" to go back to the previous menu: Incorrect input, please try again"

I'm running Ubuntu 18.04.

**Comment by nmanovic** [comment]
@manybodycpa , what is the OpenVINO version?

**Comment by manybodycpa** [comment]
@nmanovic 2019 R3.1, the latest version available. Version 2018 R5 (mentioned in the instructions) does not seem to be available anymore.

**Comment by bongmo** [comment]
I had the same program in 2019 R3.1. 
Intel no longer provides OPENVINO 2018 R5 version.

**Comment by manybodycpa** [comment]
Same problem with 2018 R5 here. How can I pass "accept" via the docker command line? Is there any other way to accept the agreement?

**Comment by machinedogwc** [comment]
> @manybodycpa , what is the OpenVINO version?

could you help to provide a usable OpenVINO file? thanks.
