### ISSUE TITLE
Create a lot of tasks with videos at the same time

### ISSUE THREAD

**Issue by Dodoooh** [opencv/cvat#916]
I have about 240 videos which I want to tag. 

But to create a single task for each video is very time-consuming. I would like to upload several videos and edit them all together.

**Comment by nmanovic** [comment]
@Dodoooh , you can use command line tools to create tasks semi-automatically https://github.com/opencv/cvat/tree/develop/utils/cli. But it makes sense to support uploading multiple videos in the future for "projects" functionality.

**Comment by jasonkena** [comment]
Any progress?

**Comment by matthaeusheer** [comment]
I'd be happy to see this feature too :-)

**Comment by lanybass** [comment]
2020-6-3 loading......

**Comment by rdesc** [comment]
I would also really like this feature given I have 1000+ different videos to label.

**Comment by rdesc** [comment]
Does anyone have any suggestions on how to get around this besides using the cli tools?

**Comment by mikeyEcology** [comment]
I'd also like to be able to create one task with all of the videos in a folder. My solution was to convert all of the videos to `.jpg` files and put them in one folder, then upload these. You can watch them and annotate as if they were movies in cvat.

**Comment by nmanovic** [comment]
@ActiveChooN , it looks like a feature for importing a dataset which contains a lot of videos. For each video we can create a separate task.

**Comment by zanjonke** [comment]
Will this be available for cloud storage options as well ?

**Comment by nmanovic** [comment]
@zanjonke , it will. We are working on the feature right now in the repo: https://github.com/cvat-ai/cvat

**Comment by bsekachev** [comment]
Hi guys, please look at this patch #4824 and give us a feedback :)
