### ISSUE TITLE
labels in coco.json

### ISSUE THREAD

**Issue by clydebailey** [opencv/cvat#920]

**Comment by clydebailey** [comment]
Hello @nmanovic !!!
My dataset comprises of images

**Comment by zhiltsov-max** [comment]
@clydebailey, hi. Could you please specify what exactly is missing in coco annotations file? There should be both "annotations" and "categories" sections filled.

**Comment by clydebailey** [comment]
Hello @zhiltsov-max The coco.json does not have support for multiclassification. 
As you can see in the xml.txt file attached I have the label for the image as well as the classifier
But this is missing in the coco.json file. 
[coco.txt](https://github.com/opencv/cvat/files/3945256/coco.txt)
[xml.txt](https://github.com/opencv/cvat/files/3945257/xml.txt)

Could you add this functionality to the coco.json as well 
Regards

**Comment by zhiltsov-max** [comment]
As far as I can see from [COCO dataset specifications](http://cocodataset.org/#format-data), there is no support for classification scenario in COCO at all, nor for object attributes, nor for multiple object parts except for keypoints scenario, which is not currently supported in CVAT. Am I missing something?

**Comment by muck27** [comment]
Thanks for the clarification!!!

**Comment by zhiltsov-max** [comment]
By the way, id Datumaro we have extended COCO format to support label annotations specifically. You can try use it by exporting a dataset in COCO-labels format:
```
datum project export -f coco -d some_dir -- --tasks='labels'
```

**Comment by nmanovic** [comment]
@clydebailey , it seems we have a solution with datumaro. I will close the issue. Don't hesitate to reopen it if the provided solution isn't enough or you think CVAT can do that better.
