### ISSUE TITLE
Tooltips duplicate text of headers

### ISSUE THREAD

**Issue by TOsmanov** [opencv/cvat#923]
On page for creating a new task, headers have tooltips that duplicate text of headers. This complicates search for useful tooltips.

![name name](https://user-images.githubusercontent.com/54434686/70430881-ccaf3700-1a8c-11ea-9b1e-c3177e8dfad7.png)

The following headers have these tooltips:

- Name
- Image quality
- Overlap size
- Segment size
- Start frame
- Stop frame
- Frame step
- Dataset repository URL
- Issue tracker

**Comment by nmanovic** [comment]
@TOsmanov ,

> This complicates search for useful tooltips.

What do you mean?

**Comment by TOsmanov** [comment]
I mean, it would be more convenient to have only useful hints, such as:

![useful tooltips](https://user-images.githubusercontent.com/54434686/70434060-472f8500-1a94-11ea-8449-d2f6a6ce3830.PNG)

And tooltips with duplicate heading text do not carry useful information.
Because of this, in order to get the right advice, you may have to take a look at unnecessary advice.

**Comment by bsekachev** [comment]
@TOsmanov 
I do not specify these tooltips (like name, image quality, overlap size, etc.). They are added automatically by a framework which I use. 

There are also meaningful descriptions for image quality, overlap size, segment size. To get them you need to hover mouse cursor on an input field, not on a label of the input field. 

@nmanovic Any questions about it?
