### ISSUE TITLE
Difficulty installing cvat out of docker

### ISSUE THREAD

**Issue by illuminati945** [opencv/cvat#925]
Attempts to install cvat out of docker (for development) on Ubuntu 18.04.3 have all failed. Chrome opens with localhost:7000, and fails to connect. it then changes automatically to localhost:3000/login and fails once again.

**Comment by bsekachev** [comment]
@illuminati945 
Any logs from the browser console?

**Comment by illuminati945** [comment]
[vscode-chrome-debug.txt](https://github.com/opencv/cvat/files/3944621/vscode-chrome-debug.txt)
yup, don't know if there's any useful information in it though

**Comment by benhoff** [comment]
I've seen this issue as well. Actually have a server running on my LAN. Trying to browse to CVAT from another computer and CVAT kicks back a 301 to localhost:3000

I assumed that I misconfigured something.

**Comment by illuminati945** [comment]
Any idea what to do?

**Comment by illuminati945** [comment]
![Screenshot from 2019-12-10 13-49-37](https://user-images.githubusercontent.com/20105326/70527165-f4b59d80-1b53-11ea-8dc8-8626382bc263.png)
Also there's this thing, although it probably has nothing to do with the problem

**Comment by bsekachev** [comment]
@illuminati945 
First of all try to remove all cookies and cache in the browser which you use

**Comment by bsekachev** [comment]
@illuminati945 
If it won't help, sent us logs exact from the browser, not from visual studio code.

**Comment by zhiltsov-max** [comment]
@bsekachev, I can confirm it happened somewhere between 59df0df and 34c3e0a - after I pulled my develop it reproduces.

**Comment by illuminati945** [comment]
it didn't help, where do i find those logs?

**Comment by bsekachev** [comment]
@illuminati945 
@zhiltsov-max 
Try these steps:
```bash
cd cvat-ui # from root cvat dir
npm install
npm run server
``` 
These commands will start debug server with UI.

**Comment by illuminati945** [comment]
![Screenshot from 2019-12-10 14-21-39](https://user-images.githubusercontent.com/20105326/70529094-6b549a00-1b58-11ea-97ab-50e595420cb9.png)

Sorry for all the troubles, it's not working once again :/

**Comment by bsekachev** [comment]
@illuminati945 
Because 3000 port is in use for you. 
Try to free it.

**Comment by benhoff** [comment]
59df0df works for me as well. The latest commit off of develop does not work.

**Comment by illuminati945** [comment]
![Screenshot from 2019-12-10 14-41-26](https://user-images.githubusercontent.com/20105326/70530726-377b7380-1b5c-11ea-9110-a99c6075bd5c.png)
![Screenshot from 2019-12-10 14-41-10](https://user-imag@bsekachev s.githubusercontent.com/20105326/70530727-38140a00-1b5c-11ea-9f0e-dc9575780711.png)
@bsekachev nodejs was open from the previous attempt to run npm. this is a fresh run

**Comment by bsekachev** [comment]
@illuminati945 
Sorry, one more step:
```cd cvat-core && npm install```
After
```
cd ../cvat-ui && npm run server
```

**Comment by illuminati945** [comment]
![Screenshot from 2019-12-10 15-51-31](https://user-images.githubusercontent.com/20105326/70535046-f9cf1880-1b64-11ea-83e6-27f4206368a8.png)
Alright, we are getting somewhere... however now there's this

**Comment by illuminati945** [comment]
Also, npm seems to be running in the background on port 3000, and I cant run server again. How do I stop it?

**Comment by bsekachev** [comment]
@illuminati945 
Do not forget  to start a server with REST API
You can do it in vscode, for example.

**Comment by bsekachev** [comment]
@illuminati945 
```bash
lsof -i :3000 
kill -9 {process_id}
```

**Comment by illuminati945** [comment]
How do I start the server with rest api?

**Comment by bsekachev** [comment]
@illuminati945 

Select server: debug configuration and start debugging (F5)

**Comment by illuminati945** [comment]
Thank you very much. It's working.

**Comment by bsekachev** [comment]
@illuminati945 
I keep this issue opened till we update CONTRIBUTING documentation and VSCode configurations to make this process easier.

**Comment by illuminati945** [comment]
Oh one last thing... hopefully.
![Screenshot from 2019-12-10 16-12-43](https://user-images.githubusercontent.com/20105326/70536730-f6895c00-1b67-11ea-9e33-2148845d0513.png)
[localhost-1575987149770.log](https://github.com/opencv/cvat/files/3945219/localhost-1575987149770.log)

What does this mean?

**Comment by bsekachev** [comment]
@illuminati945 
Have you done this step?
```
pip install -r datumaro/requirements.txt
```
