### ISSUE TITLE
How to install the OpenVino Toolkit without Docker?

### ISSUE THREAD

**Issue by illuminati945** [opencv/cvat#928]
I downloaded the development version of cvat (runs standalone without dockers), and i'm not attempting to isntall OpenVino for auto-annotation. How would I install that? I've searched around and found nothing.

Thank you in advance

**Comment by bsekachev** [comment]
@illuminati945 
It depends on your platform. Probably it would be better to read about it on [OpenVINO website](https://docs.openvinotoolkit.org/latest/index.html)

**Comment by illuminati945** [comment]
I'm running Ubuntu 18.
I'm sorry, I may have not phrases the question correctly. How do I enable auto-annotation in the standalone development version on cvat?

**Comment by bsekachev** [comment]
@illuminati945 
1) Install OpenVINO (according to instructions)
2) Activate OpenVINO environment
3) Export some environment variables

The last two steps can be automated by adding some shell code to ``.env/bin/activate`` file.

For example I have added these lines to the end of my file:
```sh
source /opt/intel/openvino/bin/setupvars.sh # activate OpenVINO environment

export CUDA_SUPPORT="yes" # CUDA support (If CUDA toolkit is installed)
export TF_ANNOTATION="yes" # Tensorflow RCNN support
export AUTO_SEGMENTATION="yes" # Tensorflow MASK RCNN support
export OPENVINO_TOOLKIT="yes" # If OpenVINO toolkit is installed
export WITH_DEXTR="yes"  # with deep extreme cut model

export IE_PLUGINS_PATH="/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64" # define if with OpenVINO
export OpenCV_DIR="/usr/local/lib/cmake/opencv4" # define if with OpenVINO
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/intel/openvino/inference_engine/lib/intel64" # define if with OpenVINO

export TF_ANNOTATION_MODEL_PATH="/home/bsekache/_models/tf_rcnn/inference_graph" # if with TF ANNOTATION
export AUTO_SEGMENTATION_PATH="/home/bsekache/_models/mask_rcnn" # if with TF SEGMENTATION
export REID_MODEL_DIR="/home/bsekache/_models/reid" # define if with OpenVINO
export DEXTR_MODEL_DIR="/home/bsekache/_models/dextr" # define if WITH_DEXTR

```

**Comment by bsekachev** [comment]
@illuminati945 
I tried to improve manual for your case. 
Don't hesitate offer improvements.

**Comment by illuminati945** [comment]
Thank you very much, you've really helped me out
