### ISSUE TITLE
using datumaro to convert voc annotations to cvat

### ISSUE THREAD

**Issue by verasativa** [opencv/cvat#937]
I'm trying to figure out how datumaro works, and eventually how to integrate to our dvc workflow. But I'm starting with a simple task: convert voc annotations to cvat format.
I'm creating a datumaro dataset with:
`pythonw -m datumaro create -d data/datumaro_dataset`
then adding the one source with:
`pythonw -m datumaro source import -f voc -n v1 -p data/datumaro_dataset/ dir data/Workers/version_1/Annotations`
then from the `data/datumaro_dataset`dir:
`pythonw -m datumaro source export -n datumaro_dataset -d ../export -f cvat`
but I'm getting a:
`KeyError: 'Key "datumaro_dataset" does not exist` or a:
`FileExistsError: [Errno 17] File exists: '/Users/vera/repositories/workers-detector/data/export'`

Questions:
What will be the proper way to do this conversion?
I'm interested on contributing to datumaro; what will be the best communication channel with developers? (no really lucky on gitter)

cc: @zhiltsov-max

**Comment by zhiltsov-max** [comment]
@verasativa, currently, CVAT format support is not implemented in Datumaro, we are going to do it soon. Once it is supported, to export a dataset you would do:
```
datum project import -d data/datumaro_dataset -f voc data/Workers/version_1/Annotations
datum project export -p data/datumaro_dataset -f cvat ../export
```

Your variant with `source`s is also OK, but it should look like this:
```
pythonw -m datumaro create -d data/datumaro_dataset
pythonw -m datumaro source import -f voc -n v1 -p data/datumaro_dataset/ dir data/Workers/version_1/Annotations
pythonw -m datumaro source export -n v1 -d ../export -f cvat # note v1 here as source name
```
`KeyError` is for non-existing project source which was named `v1`, not `datumaro_dataset`.

Regarding `FileExistsError`: currently we avoid overwriting existing dirs to prevent data loss. We're open for your suggestions on design.
