### ISSUE TITLE
[Datumaro] VOC export does not export annotations

### ISSUE THREAD

**Issue by BenjiSchlotter** [opencv/cvat#942]
Dumping the annotations as Pascal VOC Zip results in a zip file with xml files that look like that:  
```
<annotation>
    <folder></folder>
    <filename>888.jpg</filename>
    <path></path>
    <source>
        <database>Unknown</database>
    </source>
    <size>
        <width>1920</width>
        <height>1080</height>
        <depth>3</depth>
    </size>
    <segmented>0</segmented>
    <object>
        <name>Blub</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <difficult>0</difficult>
        <bndbox>
            <xmin>1484.83984375</xmin>
            <ymin>496.052734375</ymin>
            <xmax>1510.2798442840576</xmax>
            <ymax>518.972734451294</ymax>
        </bndbox>
    </object>
</annotation>
```

Exporting the dataset as pascal voc results in xml files that look like: 
```
<annotation>
  <folder></folder>
  <filename>0.jpg</filename>
  <size>
    <width>1920</width>
    <height>1080</height>
    <depth>3</depth>
  </size>
</annotation>
```

I tested it on a task containing a single image with one bounding box as annotation. 

Tested on Commit: 310ee37b

I am grateful for any help regarding this problem.

**Comment by zhiltsov-max** [comment]
I suppose the issue with empty annotations is that `Blub` is not a VOC label, so it was skipped. What would be the expected output? The same as in annotations export?

**Comment by BenjiSchlotter** [comment]
@zhiltsov-max i tested again with a VOC label. I simply created a new task with one image and one label. This time I used the Person label without any additional annotations. But the same problem persists.

I expected the output of the dataset export to have the same annotations as the dump annotation feature exports. 

My current workaround is to export the data and folder structure via dataset export and then dump the annotations and rename them accordingly.

**Comment by zhiltsov-max** [comment]
For the current label list check [this file](https://github.com/opencv/cvat/blob/develop/datumaro/datumaro/components/formats/voc.py#L18-L39), labels are tested for exact match. Could you describe your use case for the modified label set? It would be great to make the export more useful.

**Comment by BenjiSchlotter** [comment]
Thanks. It works for me as expected when use the lower case voc labels. 

My use case is that I have a dataset with custom labels that I want to convert to tfrecords. For me the easiest way was to first create a voc style dataset structure and export that to tfrecords with the scripts provided by the tensorflow object detection api.

Is there a reason why the exporter works only with the original labels? I think that for other custom datasets a more general export would be beneficial as well. I encountered a couple of projects that require the trainings data in voc style.

**Comment by zhiltsov-max** [comment]
@BenjiSchlotter, have you tried to use `TFrecord / TF detection api` export in CVAT or Datumaro? It's already there, but masks are not exported yet.

**Comment by BenjiSchlotter** [comment]
yes I tried that. But I always get an error during export:

```
Could not export dataset for the task 14
Error: Request failed with status code 500. "Work-horse process was terminated unexpectedly (waitpid returned 134)".
```

I will make a seperate issue for that.

**Comment by nmanovic** [comment]
@BenjiSchlotter , we had the problem but it was fixed in the latest develop branch. Could you please try again?

**Comment by zhiltsov-max** [comment]
@nmanovic, it looks like another problem
