### ISSUE TITLE
Use "Depth" when using dump CVAT xml for images and dump for tfrecords

### ISSUE THREAD

**Issue by Sparrowtech** [opencv/cvat#946]
Noticed recently the VOC converter that utilizes depth from CVAT XML if available.  Can "depth" easily be added to the dump function of CVAT XML for images and for tfrecords.  Currently appears to be excluded.  Have tried to append the utility files but to no avail.  Either incorporating into the CVAT gui or if can provide some direction how to add it myself would be appreciated.

Thanks!

**Comment by zhiltsov-max** [comment]
@Sparrowtech, Hi, could you clarify what is the "depth" you are talking about? Is it the number of color channels in an image?

**Comment by nmanovic** [comment]
@Sparrowtech , we will close the issue. If it is still actual for you please re-open and answer on the question from @zhiltsov-max .
