### ISSUE TITLE
Issue with hanging web application in browser when annotations save is called.

### ISSUE THREAD

**Issue by vskubriev** [opencv/cvat#949]
Specifically, with the current task, we had a problem - the interface freezes when saving a frame (frames through autosave). The server is powerful enough and its la is very low. Therefore, I believe that the problem is precisely in the client part of the markup executable in the browser. Apparently, the interface freezes at the time of autosave or manual saving by `Ctrl+S`. The entire task contains 3.5 thousand frames. Frames can contain up to 80 objects of type polyline. The entire task almost completely marked.

It can also be noted that:

1. Previously (when marking up images in this task just started): the open menu button and autosave function did not cause web ui hanging.
2. Also, another task with a small fraction of similarly marked images works without problems. 
3. First pre-main page with LOADING shows a long time compared to other tasks.wed 
4. Saving in another tasks with bounding boxes and smaller frames is running without hanging.

How can I help myself in solving/analyze this problem?

**Comment by vskubriev** [comment]
![image](https://user-images.githubusercontent.com/4639077/70801020-bff94e80-1dbe-11ea-9718-f4747691971e.png)

**Comment by vskubriev** [comment]
![image](https://user-images.githubusercontent.com/4639077/70801057-dbfcf000-1dbe-11ea-92d1-398dbee0e6f0.png)

**Comment by vskubriev** [comment]
![image](https://user-images.githubusercontent.com/4639077/70801478-13b86780-1dc0-11ea-9058-f42f2fa760af.png)

**Comment by vskubriev** [comment]
When is beta 1.0 roughly planned?

**Comment by nmanovic** [comment]
@vskubriev , we will look in the problem. Could you please provide some parameters of your task? How many annotations do you have and its type? Please post label specification?

**Comment by nmanovic** [comment]
@vskubriev , we will try to fix the issue till next release but cannot promise.

**Comment by nmanovic** [comment]
@vskubriev , you are welcome to contribute!

**Comment by vskubriev** [comment]
> @vskubriev , we will look in the problem. Could you please provide some parameters of your task? How many annotations do you have and its type? Please post label specification?

Task is about 3.5k images with 1920*1200 pixels. Most of images are marked up.

What do you mean by "its type" - type of objects is polylines.
What do you mean by "label specification" - Where I can find it?

**Comment by vskubriev** [comment]
Latest info from one of out markupers:

When he switched to marking up earlier frames (almost at the very beginning), saving became much faster in the same folder.

**Comment by bsekachev** [comment]
@vskubriev 

Hi, what chrome version have you used to profile?

**Comment by vskubriev** [comment]
> @vskubriev
> 
> Hi, what chrome version have you used to profile?

google-chrome-stable:amd64=78.0.3904.108-1 on Ubuntu 18.04 (when i did profiling)

**Comment by bsekachev** [comment]
Results for me with a task where 50k polygons
Just Array.includes() is not a bottleneck in my case.
It's quite strange.

![Screenshot from 2019-12-24 16-57-40](https://user-images.githubusercontent.com/40690378/71415902-23149c00-266f-11ea-8065-0e57b54ac868.png)


Anyway, I've found some performance problems here. 
PR above should resolve them.

**Comment by bsekachev** [comment]
@vskubriev 

Please, try the PR.
And let us know if it helps.

**Comment by vskubriev** [comment]
Thank you. We can apply this update only next year. Happy new year.

**Comment by bsekachev** [comment]
@vskubriev 

Hi, what is the news?

**Comment by vskubriev** [comment]
@bsekachev Sorry for a delay. We has installed cvat (Couple of fixes in "save annotations" #1000) at the end of past year. There are no any issues with hanging. We assume that the problem is fixed.

**Comment by bsekachev** [comment]
@vskubriev 

Great, let's close this issue in this case.
