### ISSUE TITLE
Support in AAM for selecting only objects of one type (at one time) and iterating over all objects of that type in a frame

### ISSUE THREAD

**Issue by pawan9** [opencv/cvat#959]
AAM currently selects only one object from a frame of any type (label).
Instead it should support 

1. Selecting label for which we need to perform attribute annotation
2. Iterate/traverse over all objects of that label ( if there are multiple objects in the same frame it should go on them one by one )

**Comment by bsekachev** [comment]
@pawan9 
Hi, try to combine AAM with a filter.

**Comment by pawan9** [comment]
> @pawan9
> Hi, try to combine AAM with a filter.

that solves point 1 but point 2 still remains

**Comment by bsekachev** [comment]
@pawan9 

What do you mean in the second point?
You can iterate over objects in AAM by using Tab, Shift + Tab keys

**Comment by pawan9** [comment]
@bsekachev thanks
