### ISSUE TITLE
Add info about auto segmentation to advanced topics of the installation guide

### ISSUE THREAD

**Issue by san999p** [opencv/cvat#969]
Hi,

I see a folder for Auto Segmentation which has code to run segmentation model. I assume this supports matterport implementation of maskrcnn. However, I could not find any information on how to use it. There is no button in the dashboard.

Any help will be appreciated.
Thanks

**Comment by bsekachev** [comment]
@san999p 

Hi, [here](https://github.com/opencv/cvat/tree/develop/components/auto_segmentation).
But you are right, there isn't link from root README.md.

**Comment by san999p** [comment]
@bsekachev Thanks for the information.

**Comment by bsekachev** [comment]
Resolved
