### ISSUE TITLE
How to select all files under tab 'Connected file share' convinently?

### ISSUE THREAD

**Issue by richardxdh** [opencv/cvat#979]
I can see the files under cvat_share, but I don't know how to select all easily, except selecting them one by one.

![image](https://user-images.githubusercontent.com/1438841/71149891-e1e54c00-226a-11ea-9ec6-993e65dad322.png)

**Comment by bsekachev** [comment]
@richardxdh 

Hi, 
1) Put the files into a folder
2) Select a folder

**Comment by nmanovic** [comment]
@bsekachev ,

I believe in previous version it was possible to choose
- [ ] '/' 

Can we implement a similar approach here?

**Comment by bsekachev** [comment]
Probably we can
