### ISSUE TITLE
Incompatible CUDA version with tensorflow-gpu 1.15

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#982]
As in tensor flow gpu support page, cuda-10.0 is required to run the tensorflow-gpu 1.15 . But inside the cvat/components/cuda/install.sh you're still using the cuda9.0

CUDA_VERSION=9.0.176
NCCL_VERSION=2.1.15
CUDNN_VERSION=7.6.2.24
CUDA_PKG_VERSION="9-0=${CUDA_VERSION}-1"

**Comment by nmanovic** [comment]
The PR #968 is the root cause of the issue.

**Comment by bsekachev** [comment]
Related:

```
ERROR: tensorflow-gpu 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.0.2 which is incompatible.
ERROR: tensorflow-gpu 1.15.0 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
```
during build the image (installing datumaro deps)
