### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Gitanjali450** [opencv/cvat#988]
Hello,
The command 'docker-compose build' gives the following error:

Step 1/56 : FROM ubuntu:16.04
ERROR: Service 'cvat' failed to build: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Is this because of proxy?
How can I resolve this?

**Comment by nmanovic** [comment]
Hi @Gitanjali450 ,

Probably it is better to ask the question in our gitter. We are trying to keep only real bugs and feature requests. I will close the issue.

P.S. https://stackoverflow.com/questions/48056365/error-get-https-registry-1-docker-io-v2-net-http-request-canceled-while-b
