### ISSUE TITLE
Jump to next annotation

### ISSUE THREAD

**Issue by manybodycpa** [opencv/cvat#989]
This is perhaps a feature request but I'm asking anyway in case I missed it. 

If I have a longer video with only a few annotations spread out over time, it would be very handy to be able to jump to the next frame that has a label/annotation. A simple button would be sufficient. Alternatively, some sort of display of where in the video annotations are present (below the progress bar) would do the trick.

**Comment by bsekachev** [comment]
@manybodycpa 

There is a solution for you in CVAT.
Just use left and right arrows to jump.

These buttons find the nearest frame which has objects according to the filter field (If filter is empty, it just finds a frame with any objects)

**Comment by nmanovic** [comment]
@manybodycpa , it seems that we already have the feature. Please try it. If it doesn't work for you please reopen the issue. I will close it for now.

**Comment by dsantiago** [comment]
Just to note, i was looking for this feature (to navigate between annotated images) and could not find it in documentation, found it here in Issues...

**Comment by nmanovic** [comment]
@dsantiago , https://cvat-ai.github.io/cvat/docs/manual/advanced/filter/
