### ISSUE TITLE
It dumps occluded objects when data is generated in YOLO format

### ISSUE THREAD

**Issue by sadeqbillah** [opencv/cvat#994]
HI,

We have used this tool for a project and got the scariest output ever with YOLO Framework.

Later we checked the generated dataset text files. When we set some object as occluded, this should be in the YOLO annotation files, but the tool does it somehow. At this moment I am not allowed to share the proprietary data and the annotations. But you can reproduce the issue with only 2 or 3 frames easily.

Reproduction Path:
1. Annotate a frame
2. Set the object as occluded
3. Dump in YOLO Format

Later I downloaded in another format and curated the dataset with some scripts and considered the IsOccluded field to avoid dumping the object in the annotation file.

However, overall this tool is quite amazing and have better prospect from other candidates as it directly comes from the OpenCV ecosystem. So we can rely on it. 

I hope my observation will help you make this tool better and we can rely on it without any doubts. 

I appreciate your good work. Please keep it up.

Meer

**Comment by nmanovic** [comment]
@sadeqbillah , thank for the report. We will look in the problem. If you can send us a PR to fix the issue it will be awesome.

**Comment by zhiltsov-max** [comment]
@sadeqbillah, hi, how would you like to see the export work with (partially-)occluded objects?

**Comment by HagegeR** [comment]
@zhiltsov-max  I'm thinking that this should be an option, regardless of the format: sometimes you would want to use occluded on some networks (that tracks probably), and don't on others.
